-- 045: Expansão do seed da Calculadora de Interações Medicamentosas
-- Adiciona 10 pares adicionais de uso comum (alguns surgiram em testes de
-- produção), complementando os 22 pares do 044. Total após 044+045: 32 pares.
--
-- Fontes do conteúdo: literatura de referência -- Stockley's Drug
-- Interactions, Micromedex e AHFS/ASHP para o conteúdo farmacológico; RCM
-- (Resumo das Características do Medicamento, INFARMED) para as fichas
-- aprovadas em língua portuguesa. As instituições de referência são também
-- listadas na secção "Fontes" da página pública da calculadora.
--
-- Cada par é canónico (drug_a_id < drug_b_id) via LEAST/GREATEST sobre
-- subconsultas por slug, cumprindo a constraint CHECK e a UNIQUE (a, b).
-- Idempotente: se um par já existir, o UNIQUE previne duplicados (falha a
-- migração apenas se o par for repetido sem conteúdo novo).

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  -- Paracetamol + Ibuprofeno (analgésicos de uso muito comum)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'paracetamol'),
         (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'paracetamol'),
            (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   'moderate',
   'Risco acrescido de lesão renal e sintomas gastrointestinais com uso prolongado ou em doses elevadas dos dois analgésicos. Em doses habituais e de curto prazo é geralmente bem tolerada.',
   'Increased risk of renal injury and gastrointestinal symptoms with prolonged use or high doses of both analgesics. At usual short-term doses it is generally well tolerated.',
   'Efeitos aditivos: o Ibuprofeno inibe a síntese renal de prostaglandinas; em uso crónico soma-se a carga sobre a função renal. A associação em doses terapêuticas não potencia a hepatotoxicidade do Paracetamol.',
   'Additive effects: Ibuprofen inhibits renal prostaglandin synthesis and chronic use adds renal load. At therapeutic doses the combination does not potentiate paracetamol hepatotoxicity.',
   'Usar as menores doses eficazes pelo menor tempo necessário. Dar preferência a um único analgésico. Em doentes com doença renal, hipertensão ou idade avançada, reforçar a vigilância.',
   'Use the lowest effective doses for the shortest time. Prefer a single analgesic. In patients with renal disease, hypertension or older age, reinforce monitoring.',
   'Função renal e sinais de toxicidade em doentes de risco ou em uso prolongado. Evitar a combinação em crianças sem dose ajustada por peso.',
   'Renal function and signs of toxicity in at-risk patients or prolonged use. Avoid the combination in children without weight-adjusted dosing.',
   'Dor lombar de novo, edema, redução do débito urinário, elevação da tensão arterial.',
   'New flank pain, oedema, reduced urine output, rising blood pressure.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Captopril + Amlodipina (IECA + bloqueador de canais de cálcio)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'captopril'),
         (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'captopril'),
            (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   'moderate',
   'Hipotensão aditiva. A combinação de um IECA (Captopril) com um bloqueador dos canais de cálcio (Amlodipina) reforça o efeito hipotensor, sobretudo no início ou com doses elevadas.',
   'Additive hypotension. Combining an ACE inhibitor (Captopril) with a calcium channel blocker (Amlodipine) enhances the hypotensive effect, especially early on or at higher doses.',
   'Efeito sinérgico: o IECA reduz a resistência periférica via diminuição de angiotensina II; a Amlodipina relaxa a musculatura arterial — queda aditiva da pressão arterial.',
   'Synergistic effect: the ACE inhibitor lowers peripheral resistance via reduced angiotensin II while Amlodipine relaxes vascular smooth muscle — additive blood pressure reduction.',
   'Iniciar com doses baixas e titular de forma gradual. Monitorizar a pressão arterial, sobretudo nas primeiras semanas.',
   'Start at low doses and titrate gradually. Monitor blood pressure, especially in the first weeks.',
   'Pressão arterial na 1.ª semana; função renal e potássio se houver risco de hipotensão prolongada.',
   'Blood pressure in week 1; renal function and potassium if prolonged hypotension risk.',
   'Tonturas, síncope, fadiga intensa, edema dos membros.',
   'Dizziness, syncope, marked fatigue, peripheral oedema.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Enalapril + Amlodipina
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'enalapril'),
         (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'enalapril'),
            (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   'moderate',
   'Hipotensão aditiva. Também o Enalapril associado à Amlodipina pode causar hipotensão sintomática, sobretudo em doentes com outro anti-hipertensor em uso.',
   'Additive hypotension. Enalapril combined with Amlodipine may also cause symptomatic hypotension, especially in patients already on other therapy.',
   'Somatório de vasodilatação arterial (Amlodipina) com redução da resistência periférica (Enalapril).',
   'Sum of arterial vasodilation (Amlodipine) plus reduced peripheral resistance (Enalapril).',
   'Monitorizar a pressão arterial no início e em cada ajuste de dose; iniciar com a menor dose eficaz.',
   'Monitor blood pressure at initiation and at each dose change; start at the lowest effective dose.',
   'Pressão arterial e eletrólitos no início do tratamento.',
   'Blood pressure and electrolytes at treatment start.',
   'Tonturas, síncope, cefaleia, edema periférico.',
   'Dizziness, syncope, headache, peripheral oedema.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Metformina + Cotrimoxazol (diminuição da depuração renal; risco de acidose láctica)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'metformina'),
         (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'metformina'),
            (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   'moderate',
   'Aumento do risco de acidose láctica: o trimetoprim do Cotrimoxazol reduz a excreção renal da Metformina, elevando as suas concentrações.',
   'Increased risk of lactic acidosis: the trimethoprim component reduces renal clearance of Metformin, raising its levels.',
   'O trimetoprim compete com a Metformina pela secreção tubular renal (transportador OCT2), diminuindo a sua eliminação.',
   'Trimethoprim competes with Metformin for renal tubular secretion (OCT2 transporter), reducing its elimination.',
   'Vigiar sinais de acidose láctica em doentes com função renal reduzida; considerar doses baixas de Metformina durante a antibioterapia.',
   'Monitor for lactic acidosis in patients with reduced renal function; consider low Metformin doses during antibiotic therapy.',
   'Função renal antes e durante; sinais de acidose (respiração profunda, sonolência, hipotensão).',
   'Renal function before and during; signs of acidosis (Kussmaul breathing, drowsiness, hypotension).',
   'Fraqueza, mialgia, dor abdominal, hiperventilação, sonolência — suspender e procurar ajuda médica.',
   'Weakness, myalgia, abdominal pain, hyperventilation, drowsiness — stop and seek medical help.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Sertralina + Fluoxetina (dois ISRS — síndrome serotoninérgico)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'sertralina'),
         (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'sertralina'),
            (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   'critical',
   'Risco elevado de síndrome serotoninérgica: a associação de dois ISRS (Sertralina + Fluoxetina) acumula serotonina e pode ser perigosa.',
   'High risk of serotonin syndrome: combining two SSRIs (Sertraline + Fluoxetine) accumulates serotonin and can be dangerous.',
   'Ambos inibem a recaptação de serotonina; a Fluoxetina tem ainda metabolitos de longa duração que potenciam o efeito do segundo ISRS.',
   'Both inhibit serotonin reuptake; Fluoxetine has long-acting metabolites that potentiate the second SSRI.',
   'Evitar a associação. Quando a transição é necessária, respeitar um período de washout e usar doses baixas isoladas.',
   'Avoid the combination. When switching is necessary, respect a washout period and use single low doses.',
   'Vigilância de sinais de serotonina nas primeiras semanas; aconselhar a não duplicar doses.',
   'Monitor serotonin signs in the first weeks; advise against dose doubling.',
   'Agitação, hipertermia, taquicardia, tremor, clónus, diarreia, confusão.',
   'Agitation, hyperthermia, tachycardia, tremor, clonus, diarrhoea, confusion.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Sertralina + Tramadol (síndrome serotoninérgico + convulsões)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'sertralina'),
         (SELECT id FROM public.drugs WHERE slug = 'tramadol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'sertralina'),
            (SELECT id FROM public.drugs WHERE slug = 'tramadol')),
   'moderate',
   'Risco de síndrome serotoninérgica e diminuição do limiar convulsivo quando a Sertralina é combinada com o Tramadol.',
   'Risk of serotonin syndrome and a lowered seizure threshold when Sertraline is combined with Tramadol.',
   'A Sertralina aumenta a serotonina central e o Tramadol também o faz, além de reduzir o limiar para convulsões.',
   'Sertraline raises central serotonin and Tramadol does as well, further lowering the seizure threshold.',
   'Evitar a combinação se possível; se inevitável, usar a menor dose e vigiar sinais.',
   'Avoid the combination if possible; if unavoidable, use the lowest dose and monitor signs.',
   'Observar sinais de serotonina e convulsões nos primeiros dias da associação.',
   'Watch for serotonin signs and seizures in the first days of association.',
   'Agitação, tremor, hipertermia, clonus, convulsões, confusão.',
   'Agitation, tremor, hyperthermia, clonus, seizures, confusion.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Clopidogrel + Aspirina (dupla antiagregação — aumenta o risco hemorrágico)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'clopidogrel'),
         (SELECT id FROM public.drugs WHERE slug = 'aspirina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'clopidogrel'),
            (SELECT id FROM public.drugs WHERE slug = 'aspirina')),
   'moderate',
   'Dupla antiagregação plaquetária: aumenta o risco de hemorragia. É uma associação frequentemente indicada (ex.: pós-síndrome coronária aguda), mas requer avaliação do risco hemorrágico.',
   'Dual antiplatelet therapy: increases bleeding risk. This association is frequently indicated (e.g. after acute coronary syndrome), but requires bleeding risk assessment.',
   'A Aspirina inibe irreversivelmente a COX-1 e o Clopidogrel bloqueia o recetor P2Y12 — efeito aditivo na agregação plaquetária.',
   'Aspirin irreversibly inhibits COX-1 and Clopidogrel blocks the P2Y12 receptor — additive platelet inhibition.',
   'Usar apenas sob prescrição médica dentro das indicações aprovadas; avaliar a duração do tratamento e o risco hemorrágico individual.',
   'Use only under medical prescription within approved indications; assess treatment duration and individual bleeding risk.',
   'Vigilância de sinais de hemorragia durante todo o tratamento.',
   'Watch for signs of bleeding throughout therapy.',
   'Hemorragia prolongada, hematúria, melenas, dor abdominal intensa.',
   'Prolonged bleeding, haematuria, melaena, severe abdominal pain.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Ibuprofeno + Diclofenac (dois AINE — sem benefício, mais risco)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ibuprofeno'),
         (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ibuprofeno'),
            (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   'moderate',
   'Não é recomendado usar dois AINE em simultâneo: aumenta o risco de hemorragia, ulceração gastrointestinal e lesão renal sem acrescentar eficácia.',
   'Not recommended to use two NSAIDs at once: increases the risk of bleeding, ulceration and renal injury without adding efficacy.',
   'Efeito aditivo na inibição das COX e na redução de prostaglandinas protetoras gástricas e renais.',
   'Additive COX inhibition and reduced protective gastric and renal prostaglandins.',
   'Evitar a associação; usar apenas um AINE na menor dose eficaz, com proteção gástrica se inevitável.',
   'Avoid the combination; use only one NSAID at the lowest effective dose, with gastric protection if unavoidable.',
   'Sinais gastrointestinais (dispepsia, melena) e função renal em uso prolongado.',
   'Gastrointestinal signs (dyspepsia, melaena) and renal function in prolonged use.',
   'Dor abdominal, melena, hematemeses, edema, agravamento da tensão arterial.',
   'Abdominal pain, melaena, haematemesis, oedema, rising blood pressure.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Diclofenac + Prednisolona (corticosteroide + AINE)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diclofenac'),
         (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diclofenac'),
            (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   'moderate',
   'Risco hemorrágico gastrointestinal acrescido pela associação de um corticosteroide (Prednisolona) com um AINE.',
   'Increased gastrointestinal bleeding risk when a corticosteroid (Prednisolone) is combined with an NSAID.',
   'Efeitos lesivos na mucosa gástrica somados (redução de prostaglandinas protetoras).',
   'Additive gastric mucosal injury (reduced protective prostaglandins).',
   'Considerar proteção gástrica (IBP) se a associação for inevitável; usar as menores doses eficazes pelo menor tempo.',
   'Consider gastric protection (PPIs) if unavoidable; use the lowest effective doses for the shortest time.',
   'Vigiar sintomas dispépticos e sangue oculto nas fezes.',
   'Watch for dyspepsia and occult blood in stool.',
   'Dor abdominal intensa, melena, hematemeses.',
   'Severe abdominal pain, melaena, haematemesis.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00'),

  -- Paracetamol + Warfarina (uso prolongado de paracetamol pode elevar o INR)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'paracetamol'),
         (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'paracetamol'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O uso regular e prolongado de Paracetamol (> ~1-2 g/dia durante dias) pode elevar o efeito anticoagulante da Warfarina (INR), sobretudo em uso contínuo.',
   'Regular, prolonged use of paracetamol may enhance the anticoagulant effect of warfarin (INR), especially with daily use.',
   'Mecanismo ainda incompletamente esclarecido: possível interferência no metabolismo de vitamina K e dos fatores de coagulação.',
   'Not yet fully established: likely interference with vitamin K and clotting factor metabolism.',
   'Não contraindicado no uso pontual. Em uso crónico, vigiar o INR e ajustar a dose de Warfarina se necessário.',
   'Not contraindicated as a single dose. In chronic use, monitor INR and adjust warfarin if needed.',
   'INR regular em doentes que usam Paracetamol diariamente há mais de uma semana.',
   'Regular INR monitoring in patients taking paracetamol daily for more than a week.',
   'Sangramento incomum, hematomas espontâneos, gengivorragia, melaena.',
   'Unusual bleeding, spontaneous bruising, gum bleeding, melaena.',
   'Stockley''s Drug Interactions; Micromedex; ASHP; RCM de cada fármaco (INFARMED)',
   'Stockley''s Drug Interactions; Micromedex; ASHP; SmPC of each drug',
   'published', '2026-08-02 09:00:00+00');