-- 052: Família Antimaláricos — seed da Calculadora de Interações Medicamentosas
-- Adiciona os fármacos antimaláricos mais relevantes (8 fármacos) e
-- 31 pares de interação clinicamente significativos (todos 'moderate')
-- com os fármacos já existentes e entre a própria família. Complementa 044/045/051.
-- Total de fármacos após esta migração: 43.
--
-- Fontes: rótulos aprovados pela FDA via DailyMed (NIH/NLM), de domínio público.
-- Cada par cita os rótulos oficiais com setIDs obtidos na API DailyMed
-- (spls.json?drug_name=...) e confirmados na página legível do rótulo
-- (drugInfo.cfm?setid=...). Nenhum setID é fictício ou digitado à mão.
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * severidade: QT aditivo, indutores do CYP3A4, absorção (antiácidos/IBP),
--     digoxina, warfarina e hipoglicemia — todos moderados, sem exageros;
--   * idempotente: reaplicar é seguro (UNIQUE (drug_a_id, drug_b_id)).
--
-- Nota clínica: Primaquina e Tafenoquina não têm interações clinicamente
-- relevantes com os fármacos atuais; por isso não recebem pares artificiais.
-- A calculadora mostra "sem interações documentadas", o que é correto.

INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('artemeter-lumefantrina', 'Arteméter + Lumefantrina', 'Artemether + Lumefantrine', 'Antimalárico (combinação com artemisinina, ACT)', 'Antimalarial (artemisinin-based combination, ACT)', ARRAY['Coartem'], 'published', 36),
  ('cloroquina', 'Cloroquina', 'Chloroquine', 'Antimalárico (4-aminoquinolina)', 'Antimalarial (4-aminoquinoline)', ARRAY['Cloroquina fosfato'], 'published', 37),
  ('hidroxicloroquina', 'Hidroxicloroquina', 'Hydroxychloroquine', 'Antimalárico e antirreumático (4-aminoquinolina)', 'Antimalarial and antirheumatic (4-aminoquinoline)', ARRAY['Plaquenil'], 'published', 38),
  ('mefloquina', 'Mefloquina', 'Mefloquine', 'Antimalárico (aminoálcool de quinolina)', 'Antimalarial (quinoline methanol)', ARRAY['Lariam'], 'published', 39),
  ('quinina', 'Quinina', 'Quinine', 'Antimalárico (alcaloide da cinchona)', 'Antimalarial (cinchona alkaloid)', ARRAY['Sulfato de quinina', 'Quinino'], 'published', 40),
  ('primaquina', 'Primaquina', 'Primaquine', 'Antimalárico (8-aminoquinolina)', 'Antimalarial (8-aminoquinoline)', ARRAY['Primaquina fosfato'], 'published', 41),
  ('atovaquona-proguanil', 'Atovaquona + Proguanil', 'Atovaquone + Proguanil', 'Antimalárico (combinação)', 'Antimalarial (combination)', ARRAY['Malarone'], 'published', 42),
  ('tafenoquina', 'Tafenoquina', 'Tafenoquine', 'Antimalárico (8-aminoquinolina)', 'Antimalarial (8-aminoquinoline)', ARRAY['Krintafel'], 'published', 43);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Ambos prolongam o intervalo QT; a associação aumenta o risco de arritmias ventriculares (ex.: torsades de pointes), sobretudo com QT longo, hipocaliemia ou cardiopatia.',
   'Both prolong the QT interval; the combination raises the risk of ventricular arrhythmias (e.g. torsades de pointes), especially with long QT, hypokalaemia or heart disease.',
   'Efeito aditivo na repolarização cardíaca: a Lumefantrina bloqueia os canais de potássio (hERG) e a Amiodarona prolonga o QT e é arritmogénica por si só.',
   'Additive effect on cardiac repolarisation: Lumefantrine blocks potassium channels (hERG) and Amiodarone prolongs QT and is arrhythmogenic on its own.',
   'Evitar sempre que possível. Se inevitável, usar com precaução, corrigir hipocaliemia/hipomagnesemia e monitorizar o ECG.',
   'Avoid whenever possible. If unavoidable, use with caution, correct hypokalaemia/hypomagnesaemia and monitor the ECG.',
   'ECG com medição do QTc, potássio e magnésio; vigilância reforçada em doentes com fatores de risco.',
   'ECG with QTc measurement, potassium and magnesium; closer monitoring in patients with risk factors.',
   'Síncope, palpitações, tonturas, convulsões.',
   'Syncope, palpitations, dizziness, seizures.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A Claritromicina prolonga o QT e inibe o CYP3A4, elevando a exposição à Lumefantrina — risco acrescido de arritmias.',
   'Clarithromycin prolongs QT and inhibits CYP3A4, raising Lumefantrine exposure — increased risk of arrhythmias.',
   'Inibição do metabolismo da Arteméter/Lumefantina pelo CYP3A4 (Claritromicina) + prolongamento aditivo do QT.',
   'CYP3A4 inhibition of Artemether/Lumefantrine metabolism (Clarithromycin) + additive QT prolongation.',
   'Evitar quando possível; monitorizar ECG e sinais de toxicidade; considerar antibiótico alternativo se indicado.',
   'Avoid when possible; monitor ECG and signs of toxicity; consider an alternative antibiotic if indicated.',
   'ECG (QTc), potássio e sinais clínicos de arritmia.',
   'ECG (QTc), potassium and clinical signs of arrhythmia.',
   'Palpitações, síncope, dor torácica.',
   'Palpitations, syncope, chest pain.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
         (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
            (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   'moderate',
   'Associação de dois fármacos que prolongam o QT — risco de arritmias ventriculares, maior em doentes de risco.',
   'Two QT-prolonging drugs combined — risk of ventricular arrhythmias, higher in at-risk patients.',
   'Efeito aditivo na repolarização cardíaca (bloqueio de canais de potássio).',
   'Additive effect on cardiac repolarisation (potassium channel blockade).',
   'Precaução em doentes de risco; ECG se fatores de vulnerabilidade ou sintomas.',
   'Caution in at-risk patients; ECG if vulnerability factors or symptoms.',
   'ECG (QTc) e eletrólitos se fatores de risco.',
   'ECG (QTc) and electrolytes if risk factors.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
         (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina (indutor do CYP3A4) reduz os níveis de Arteméter e Lumefantrina — risco de falência do tratamento da malária.',
   'Carbamazepine (a CYP3A4 inducer) lowers Artemether and Lumefantrine levels — risk of malaria treatment failure.',
   'Indução enzimática do CYP3A4: metabolismo acelerado dos dois componentes, com menor exposição sistémica.',
   'Enzymatic induction of CYP3A4: faster metabolism of both components with lower systemic exposure.',
   'Considerar esquema antimalárico alternativo ou ajuste de dose e confirmar a cura parasitológica.',
   'Consider an alternative antimalarial regimen or dose adjustment and confirm parasitological cure.',
   'Resposta clínica e parasitológica à terapêutica (febre, parasitemia).',
   'Clinical and parasitological response to treatment (fever, parasitaemia).',
   'Febre persistente ou recorrente, ausência de melhoria após 48–72 h.',
   'Persistent or recurrent fever, no improvement after 48–72 h.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
         (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
            (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   'moderate',
   'Efeito aditivo no prolongamento do QT; a associação é habitualmente evitada por não acrescentar benefício e aumentar o risco arritmogénico.',
   'Additive QT prolongation; the association is usually avoided as it adds no benefit and increases arrhythmic risk.',
   'Ambos prolongam a repolarização cardíaca por bloqueio dos canais de potássio.',
   'Both prolong cardiac repolarisation via potassium channel blockade.',
   'Evitar a associação; usar preferencialmente um esquema único (ACT ou Quinina, não ambos).',
   'Avoid the combination; preferably use a single regimen (ACT or Quinine, not both).',
   'ECG (QTc), eletrólitos e vigilância clínica de arritmia.',
   'ECG (QTc), electrolytes and clinical surveillance for arrhythmia.',
   'Palpitações, síncope, tonturas.',
   'Palpitations, syncope, dizziness.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
         (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina'),
            (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   'moderate',
   'Risco acrescido de prolongamento do QT e de efeitos neuropsiquiátricos quando combinados.',
   'Increased risk of QT prolongation and neuropsychiatric effects when combined.',
   'Prolongamento do QT aditivo; a Mefloquina associa ainda efeitos sobre o SNC.',
   'Additive QT prolongation; Mefloquine also adds CNS effects.',
   'Evitar a associação; optar por um único esquema antimalárico.',
   'Avoid the association; choose a single antimalarial regimen.',
   'ECG e estado neurológico; atenção a sintomas neuropsiquiátricos.',
   'ECG and neurological status; watch for neuropsychiatric symptoms.',
   'Ansiedade, insónia, psicose, convulsões, palpitações.',
   'Anxiety, insomnia, psychosis, seizures, palpitations.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf ; approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Risco elevado de prolongamento do QT e arritmias ventriculares; associação a evitar na maioria dos doentes.',
   'High risk of QT prolongation and ventricular arrhythmias; the association should be avoided in most patients.',
   'Efeito aditivo na repolarização cardíaca (Cloroquina e Amiodarona prolongam o QT por bloqueio de canais de potássio).',
   'Additive effect on cardiac repolarisation (both Chloroquine and Amiodarone prolong QT via potassium channel blockade).',
   'Evitar a associação; se inevitável, ECG e eletrólitos antes e durante, com precaução máxima.',
   'Avoid the association; if unavoidable, ECG and electrolytes before and during, with maximum caution.',
   'ECG (QTc), potássio e magnésio.',
   'ECG (QTc), potassium and magnesium.',
   'Síncope, palpitações, convulsões.',
   'Syncope, palpitations, seizures.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'Prolongamento do QT aditivo com risco de arritmias ventriculares.',
   'Additive QT prolongation with risk of ventricular arrhythmias.',
   'Ambos bloqueiam os canais de potássio cardíacos; efeito aditivo na repolarização.',
   'Both block cardiac potassium channels; additive effect on repolarisation.',
   'Usar com precaução; monitorizar o ECG; considerar alternativa antibiótica.',
   'Use with caution; monitor the ECG; consider an alternative antibiotic.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, síncope, tonturas.',
   'Palpitations, syncope, dizziness.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   'moderate',
   'Efeito aditivo no prolongamento do QT; risco baixo-moderado, maior em doentes com fatores de risco.',
   'Additive QT prolongation; low-to-moderate risk, higher in patients with risk factors.',
   'A Ciprofloxacina e a Cloroquina prolongam ligeiramente o QT — efeito aditivo na repolarização.',
   'Ciprofloxacin and Chloroquine both slightly prolong QT — additive effect on repolarisation.',
   'Precaução em doentes de risco (QT longo, hipocaliemia, idosos); monitorizar se sintomas.',
   'Caution in at-risk patients (long QT, hypokalaemia, elderly); monitor if symptomatic.',
   'ECG se fatores de risco ou sintomas.',
   'ECG if risk factors or symptoms.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'A Cloroquina pode aumentar os níveis de Digoxina, com risco de toxicidade digitálica.',
   'Chloroquine can raise Digoxin levels, with a risk of digoxin toxicity.',
   'Inibição da glicoproteína-P renal, reduzindo a excreção da Digoxina.',
   'Inhibition of renal P-glycoprotein, reducing Digoxin excretion.',
   'Monitorizar a digoxinemia e sinais de toxicidade; reduzir a dose se necessário.',
   'Monitor digoxin levels and signs of toxicity; reduce the dose if needed.',
   'Digoxinemia, ECG e função renal.',
   'Digoxin level, ECG and renal function.',
   'Náuseas, vómitos, perturbações visuais, bradicardia, arritmias.',
   'Nausea, vomiting, visual disturbances, bradycardia, arrhythmias.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Cloroquina pode potenciar o efeito da Warfarina, aumentando o INR e o risco hemorrágico.',
   'Chloroquine can enhance the effect of Warfarin, raising the INR and the bleeding risk.',
   'Mecanismo não totalmente esclarecido; possível redução do clearance da Warfarina.',
   'Mechanism not fully established; possible reduction of Warfarin clearance.',
   'Monitorizar o INR após iniciar/parar a Cloroquina e ajustar a dose de Warfarina.',
   'Monitor the INR after starting/stopping Chloroquine and adjust the Warfarin dose.',
   'INR (mais frequente nas primeiras semanas) e sinais de hemorragia.',
   'INR (more often in the first weeks) and signs of bleeding.',
   'Hemorragias, equimoses fáceis, fezes escuras.',
   'Bleeding, easy bruising, dark stools.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Os antiácidos reduzem a absorção da Cloroquina, podendo diminuir a sua eficácia.',
   'Antacids reduce Chloroquine absorption, which may lower its efficacy.',
   'Quelação e alteração do pH gástrico que reduzem a solubilidade e a absorção da Cloroquina.',
   'Chelation and changes in gastric pH reduce Chloroquine solubility and absorption.',
   'Separar as tomas por 2–4 horas (antiácidos após a Cloroquina).',
   'Separate doses by 2–4 hours (antacids after Chloroquine).',
   'Resposta clínica; reavaliar se falência terapêutica.',
   'Clinical response; reassess if therapeutic failure.',
   'Falta de resposta ao tratamento.',
   'Lack of response to treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'O Omeprazol pode reduzir a absorção da Cloroquina por aumento do pH gástrico.',
   'Omeprazole may reduce Chloroquine absorption by raising gastric pH.',
   'Menor solubilidade da Cloroquina em pH mais alto.',
   'Lower Chloroquine solubility at higher pH.',
   'Considerar alternativa e monitorizar a resposta clínica.',
   'Consider an alternative and monitor the clinical response.',
   'Resposta ao tratamento.',
   'Response to treatment.',
   'Falência terapêutica da malária.',
   'Malaria treatment failure.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   'moderate',
   'Associação de dois antimaláricos que prolongam o QT — risco arritmogénico acrescido, sem benefício terapêutico.',
   'Two QT-prolonging antimalarials combined — higher arrhythmic risk with no therapeutic benefit.',
   'Prolongamento aditivo do intervalo QT; efeitos aditivos sobre o SNC.',
   'Additive QT prolongation; additive CNS effects.',
   'Evitar; usar um único esquema antimalárico.',
   'Avoid; use a single antimalarial regimen.',
   'ECG e vigilância neurológica.',
   'ECG and neurological surveillance.',
   'Palpitações, convulsões, alterações do comportamento.',
   'Palpitations, seizures, behavioural changes.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   'moderate',
   'Risco de prolongamento do QT e de toxicidade aditiva do tipo cinconismo (acufenos, tonturas, alterações visuais).',
   'Risk of QT prolongation and additive cinchonism-like toxicity (tinnitus, dizziness, visual changes).',
   'Efeitos aditivos na repolarização cardíaca e sobre o sistema nervoso.',
   'Additive effects on cardiac repolarisation and on the nervous system.',
   'Evitar a associação; não são combinados na prática clínica atual.',
   'Avoid the combination; not used together in current clinical practice.',
   'ECG, audição e visão, sinais de toxicidade.',
   'ECG, hearing and vision, signs of toxicity.',
   'Acufenos, surdez, tonturas graves, convulsões.',
   'Tinnitus, hearing loss, severe dizziness, seizures.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina')),
   'moderate',
   'Dois fármacos da mesma família (4-aminoquinolinas) — associação sem benefício, com risco aditivo de toxicidade ocular, QT e cardíaca.',
   'Two drugs of the same family (4-aminoquinolines) — no benefit from combining, with additive risk of ocular, QT and cardiac toxicity.',
   'Sobreposição de mecanismos: bloqueio de canais de potássio, acumulação tecidual e risco retiniano aditivo.',
   'Overlapping mechanisms: potassium channel blockade, tissue accumulation and additive retinal risk.',
   'Não combinar; escolher um único fármaco antimalárico.',
   'Do not combine; choose a single antimalarial drug.',
   'Não aplicável se não combinado; em uso prolongado de qualquer um: rastreio oftalmológico.',
   'Not applicable if not combined; with prolonged use of either: ophthalmological screening.',
   'Alterações visuais, palpitações, miopatia.',
   'Visual changes, palpitations, myopathy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341',
   'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 ; approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'A Hidroxicloroquina aumenta os níveis de Digoxina — risco de toxicidade digitálica.',
   'Hydroxychloroquine raises Digoxin levels — risk of digoxin toxicity.',
   'Inibição da glicoproteína-P, reduzindo a excreção renal da Digoxina.',
   'P-glycoprotein inhibition, reducing renal Digoxin excretion.',
   'Monitorizar a digoxinemia; ajustar a dose se necessário.',
   'Monitor digoxin levels; adjust the dose if needed.',
   'Digoxinemia, ECG e função renal.',
   'Digoxin level, ECG and renal function.',
   'Náuseas, alterações visuais, bradicardia.',
   'Nausea, visual disturbances, bradycardia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'DailyMed/FDA (NIH/NLM) — approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'metformina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'metformina')),
   'moderate',
   'Efeito hipoglicemiante aditivo — risco acrescido de hipoglicemia em doentes diabéticos.',
   'Additive hypoglycaemic effect — higher risk of hypoglycaemia in diabetic patients.',
   'A Hidroxicloroquina melhora a sensibilidade à insulina, potenciando o efeito da Metformina.',
   'Hydroxychloroquine improves insulin sensitivity, enhancing the Metformin effect.',
   'Monitorizar a glicemia e ajustar a dose do antidiabético se necessário.',
   'Monitor glycaemia and adjust the antidiabetic dose if needed.',
   'Glicemia capilar, HbA1c e sintomas de hipoglicemia.',
   'Capillary glucose, HbA1c and hypoglycaemia symptoms.',
   'Sudorese, tremor, confusão, desmaios.',
   'Sweating, tremor, confusion, fainting.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; rótulo aprovado Metformina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=13b1e35f-d047-8ddc-e063-6394a90a24dd',
   'DailyMed/FDA (NIH/NLM) — approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; approved Metformin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=13b1e35f-d047-8ddc-e063-6394a90a24dd',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Hidroxicloroquina pode aumentar o efeito da Warfarina — risco hemorrágico.',
   'Hydroxychloroquine may increase the effect of Warfarin — bleeding risk.',
   'Possível inibição do metabolismo da Warfarina (CYP2C9).',
   'Possible inhibition of Warfarin metabolism (CYP2C9).',
   'Monitorizar o INR ao iniciar/parar e ajustar a dose.',
   'Monitor the INR on starting/stopping and adjust the dose.',
   'INR e sinais de hemorragia.',
   'INR and signs of bleeding.',
   'Hemorragia, equimoses, fezes escuras.',
   'Bleeding, bruising, dark stools.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Prolongamento do QT aditivo com risco de arritmias ventriculares.',
   'Additive QT prolongation with risk of ventricular arrhythmias.',
   'Ambos prolongam a repolarização cardíaca.',
   'Both prolong cardiac repolarisation.',
   'Evitar quando possível; se necessário, ECG e eletrólitos.',
   'Avoid when possible; if needed, ECG and electrolytes.',
   'ECG (QTc), potássio e magnésio.',
   'ECG (QTc), potassium and magnesium.',
   'Síncope, palpitações.',
   'Syncope, palpitations.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'DailyMed/FDA (NIH/NLM) — approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'hidroxicloroquina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'Efeito aditivo no prolongamento do QT — risco de arritmias.',
   'Additive QT prolongation — risk of arrhythmias.',
   'Bloqueio aditivo dos canais de potássio cardíacos.',
   'Additive blockade of cardiac potassium channels.',
   'Precaução; ECG se fatores de risco.',
   'Caution; ECG if risk factors.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'DailyMed/FDA (NIH/NLM) — approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Risco acrescido de prolongamento do QT e de arritmias ventriculares.',
   'Increased risk of QT prolongation and ventricular arrhythmias.',
   'Prolongamento aditivo da repolarização cardíaca.',
   'Additive prolongation of cardiac repolarisation.',
   'Evitar; se inevitável, monitorizar o ECG.',
   'Avoid; if unavoidable, monitor the ECG.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'Efeito aditivo no QT; a Claritromicina pode ainda elevar os níveis de Mefloquina.',
   'Additive QT effect; Clarithromycin may also raise Mefloquine levels.',
   'Prolongamento do QT aditivo + inibição do metabolismo da Mefloquina (CYP3A4).',
   'Additive QT prolongation + inhibition of Mefloquine metabolism (CYP3A4).',
   'Precaução; monitorizar ECG e sinais de toxicidade.',
   'Caution; monitor ECG and signs of toxicity.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, tonturas, convulsões.',
   'Palpitations, dizziness, seizures.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
         (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
            (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   'moderate',
   'Prolongamento do QT aditivo — risco baixo-moderado, maior em doentes de risco.',
   'Additive QT prolongation — low-to-moderate risk, higher in at-risk patients.',
   'Efeito aditivo na repolarização cardíaca.',
   'Additive effect on cardiac repolarisation.',
   'Precaução em doentes de risco; ECG se sintomas.',
   'Caution in at-risk patients; ECG if symptoms.',
   'ECG se fatores de risco.',
   'ECG if risk factors.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
         (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'mefloquina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina reduz os níveis de Mefloquina (indutor do CYP3A4) e ambos baixam o limiar convulsivo — risco de falência terapêutica e de convulsões.',
   'Carbamazepine lowers Mefloquine levels (CYP3A4 inducer) and both lower the seizure threshold — risk of therapeutic failure and seizures.',
   'Indução do CYP3A4 (que metaboliza a Mefloquina) + efeitos aditivos sobre o limiar convulsivo.',
   'CYP3A4 induction (which metabolises Mefloquine) + additive effects on the seizure threshold.',
   'Considerar alternativa antimalárica e vigilância neurológica.',
   'Consider an alternative antimalarial and neurological surveillance.',
   'Resposta clínica e estado neurológico.',
   'Clinical response and neurological status.',
   'Convulsões, confusão, falta de resposta à profilaxia/tratamento.',
   'Seizures, confusion, lack of response to prophylaxis/treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
         (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'A Quinina aumenta marcadamente os níveis de Digoxina — risco elevado de toxicidade digitálica.',
   'Quinine markedly raises Digoxin levels — high risk of digoxin toxicity.',
   'Inibição da glicoproteína-P e redução do volume de distribuição da Digoxina.',
   'P-glycoprotein inhibition and reduced Digoxin volume of distribution.',
   'Monitorizar a digoxinemia e o ECG; reduzir a dose de Digoxina se necessário.',
   'Monitor digoxin levels and the ECG; reduce the Digoxin dose if needed.',
   'Digoxinemia, ECG e função renal.',
   'Digoxin level, ECG and renal function.',
   'Náuseas, vómitos, alterações visuais, bradicardia, arritmias.',
   'Nausea, vomiting, visual disturbances, bradycardia, arrhythmias.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
         (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Quinina pode aumentar o efeito da Warfarina — risco hemorrágico.',
   'Quinine may increase the effect of Warfarin — bleeding risk.',
   'Inibição do metabolismo da Warfarina (CYP2C9) e possível deslocamento proteico.',
   'Inhibition of Warfarin metabolism (CYP2C9) and possible protein displacement.',
   'Monitorizar o INR e ajustar a dose.',
   'Monitor the INR and adjust the dose.',
   'INR frequente e sinais de hemorragia.',
   'Frequent INR and signs of bleeding.',
   'Hemorragias, equimoses, fezes escuras.',
   'Bleeding, bruising, dark stools.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Risco elevado de prolongamento do QT e de torsades de pointes.',
   'High risk of QT prolongation and torsades de pointes.',
   'Efeito aditivo no bloqueio dos canais de potássio cardíacos.',
   'Additive effect on cardiac potassium channel blockade.',
   'Evitar a associação; se inevitável, monitorização cardíaca rigorosa.',
   'Avoid the association; if unavoidable, strict cardiac monitoring.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Síncope, convulsões, palpitações.',
   'Syncope, seizures, palpitations.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A Claritromicina inibe o metabolismo da Quinina e prolonga o QT — risco de toxicidade e arritmias.',
   'Clarithromycin inhibits Quinine metabolism and prolongs QT — risk of toxicity and arrhythmias.',
   'Inibição do CYP3A4 (aumenta a Quinina) + prolongamento aditivo do QT.',
   'CYP3A4 inhibition (raises Quinine) + additive QT prolongation.',
   'Evitar; se necessário, reduzir a Quinina e monitorizar.',
   'Avoid; if needed, reduce Quinine and monitor.',
   'ECG, sinais de cinconismo e de arritmia.',
   'ECG, signs of cinchonism and arrhythmia.',
   'Acufenos, alterações visuais, palpitações.',
   'Tinnitus, visual changes, palpitations.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
         (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'quinina'),
            (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   'moderate',
   'Prolongamento do QT aditivo — risco de arritmias ventriculares.',
   'Additive QT prolongation — risk of ventricular arrhythmias.',
   'Efeito aditivo na repolarização cardíaca.',
   'Additive effect on cardiac repolarisation.',
   'Precaução; ECG em doentes de risco.',
   'Caution; ECG in at-risk patients.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0 ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'published', '2026-08-03 10:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'atovaquona-proguanil'),
         (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'atovaquona-proguanil'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O Proguanil pode potenciar o efeito anticoagulante da Warfarina.',
   'Proguanil may enhance the anticoagulant effect of Warfarin.',
   'Possível interação com o metabolismo hepático da Warfarina.',
   'Possible interaction with hepatic Warfarin metabolism.',
   'Monitorizar o INR ao iniciar/parar e ajustar a dose.',
   'Monitor the INR on starting/stopping and adjust the dose.',
   'INR e sinais de hemorragia.',
   'INR and signs of bleeding.',
   'Hemorragias, equimoses, fezes escuras.',
   'Bleeding, bruising, dark stools.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atovaquona + Proguanil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Atovaquone + Proguanil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 10:00:00+00');

-- ============================================================
-- Verificação após aplicar no Supabase:
-- SELECT count(*) FROM public.drugs WHERE slug IN ('artemeter-lumefantrina','cloroquina','hidroxicloroquina','mefloquina','quinina','primaquina','atovaquona-proguanil','tafenoquina');  -- 8
-- SELECT count(*) FROM public.drug_interactions WHERE source_pt LIKE 'DailyMed/FDA%' AND updated_at > '2026-08-03';  -- 31
-- SELECT a.slug AS drug_a, b.slug AS drug_b, di.severity
-- FROM public.drug_interactions di
-- JOIN public.drugs a ON a.id = LEAST(di.drug_a_id, di.drug_b_id)
-- JOIN public.drugs b ON b.id = GREATEST(di.drug_a_id, di.drug_b_id)
-- WHERE di.source_pt LIKE '%DailyMed/FDA%' AND di.updated_at > '2026-08-03'
-- ORDER BY 1, 2;
