-- 053: Família Antimaláricos (ACTs sem rótulo FDA) — seed da Calculadora de Interações
-- Adiciona 4 fármacos e 11 pares de interação (todos 'moderate').
-- Total após esta migração: 47 fármacos e 74 pares.
--
-- Fontes: estes ACTs não têm rótulo aprovado pela FDA/DailyMed, por isso a
-- citação principal vem de fontes oficiais de domínio público:
--   * OMS (WHO) — Directrizes da OMS para a malária (artesunato, artesunato+amodiaquina,
--     sulfadoxina+pirimetamina/TPI);
--   * EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina).
-- Os fármacos parceiros já existentes são citados pelos seus rótulos DailyMed
-- (setIDs validados nas migrações 051/052).
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * severidade: indutores do CYP (redução de eficácia do ACT), prolongamento do QT
--     (piperaquina/amodiaquina) e reações aditivas (sulfonamidas, warfarina) — moderados;
--   * idempotente: reaplicar é seguro (UNIQUE (drug_a_id, drug_b_id)).
--
-- Nota clínica: o Artesunato injetável (malária grave, curso curto) não tem
-- interações clinicamente relevantes com os fármacos atuais — não recebe pares
-- artificiais (a calculadora mostra "sem interações documentadas", correto).

INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('artesunato', 'Artesunato', 'Artesunate', 'Antimalárico (derivado da artemisinina; injetável — malária grave)', 'Antimalarial (artemisinin derivative; injectable — severe malaria)', ARRAY['Artesunato injetável'], 'published', 44),
  ('artesunato-amodiaquina', 'Artesunato + Amodiaquina', 'Artesunate + Amodiaquine', 'Antimalárico (combinação com artemisinina, ACT)', 'Antimalarial (artemisinin-based combination, ACT)', ARRAY['Coarsucam'], 'published', 45),
  ('diidroartemisinina-piperaquina', 'Dihidroartemisinina + Piperaquina', 'Dihydroartemisinin + Piperaquine', 'Antimalárico (combinação com artemisinina, ACT)', 'Antimalarial (artemisinin-based combination, ACT)', ARRAY['Eurartesim'], 'published', 46),
  ('sulfadoxina-pirimetamina', 'Sulfadoxina + Pirimetamina', 'Sulfadoxine + Pyrimethamine', 'Antimalárico antifólico (sulfonamida + diamino-pirimidina)', 'Antimalarial antifolate (sulfonamide + diaminopyrimidine)', ARRAY['Fansidar'], 'published', 47);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artesunato-amodiaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artesunato-amodiaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina (indutor do CYP2C8/3A4) acelera o metabolismo da Amodiaquina — risco de níveis subterapêuticos e falência do tratamento.',
   'Carbamazepine (a CYP2C8/3A4 inducer) accelerates Amodiaquine metabolism — risk of subtherapeutic levels and treatment failure.',
   'Indução enzimática que reduz a exposição à Amodiaquina (componente do ACT).',
   'Enzymatic induction reducing exposure to Amodiaquine (the ACT component).',
   'Considerar um ACT alternativo e confirmar a cura parasitológica.',
   'Consider an alternative ACT and confirm parasitological cure.',
   'Resposta clínica e parasitológica ao tratamento.',
   'Clinical and parasitological response to treatment.',
   'Febre persistente ou recorrente, ausência de melhoria após 48–72 h.',
   'Persistent or recurrent fever, no improvement after 48–72 h.',
   'OMS (WHO) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'WHO — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artesunato-amodiaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artesunato-amodiaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A Amiodarona soma-se ao efeito da Amodiaquina no prolongamento do QT — risco de arritmias ventriculares.',
   'Amiodarone adds to Amodiaquine''s QT-prolonging effect — risk of ventricular arrhythmias.',
   'Prolongamento aditivo da repolarização cardíaca.',
   'Additive prolongation of cardiac repolarisation.',
   'Preferir evitar; se inevitável, monitorizar ECG e eletrólitos.',
   'Prefer to avoid; if unavoidable, monitor ECG and electrolytes.',
   'ECG (QTc), potássio e magnésio.',
   'ECG (QTc), potassium and magnesium.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'OMS (WHO) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'WHO — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'artesunato-amodiaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'artesunato-amodiaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A Claritromicina prolonga o QT e inibe o CYP3A4 (que participa no metabolismo da Amodiaquina) — risco de arritmias e de toxicidade.',
   'Clarithromycin prolongs QT and inhibits CYP3A4 (involved in Amodiaquine metabolism) — risk of arrhythmias and toxicity.',
   'Prolongamento do QT aditivo + inibição enzimática que pode elevar os níveis de Amodiaquina.',
   'Additive QT prolongation + enzymatic inhibition that may raise Amodiaquine levels.',
   'Evitar quando possível; monitorizar ECG; considerar antibiótico alternativo.',
   'Avoid when possible; monitor ECG; consider an alternative antibiotic.',
   'ECG (QTc) e sinais de toxicidade.',
   'ECG (QTc) and signs of toxicity.',
   'Palpitações, icterícia (hepatotoxicidade da Amodiaquina).',
   'Palpitations, jaundice (amodiaquine hepatotoxicity).',
   'OMS (WHO) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'WHO — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A Piperaquina prolonga o QT; a associação com Amiodarona aumenta o risco de arritmias ventriculares (ex.: torsades de pointes).',
   'Piperaquine prolongs QT; combining with Amiodarone raises the risk of ventricular arrhythmias (e.g. torsades de pointes).',
   'Efeito aditivo na repolarização cardíaca.',
   'Additive effect on cardiac repolarisation.',
   'Evitar; se inevitável, monitorização cardíaca rigorosa (ECG e eletrólitos).',
   'Avoid; if unavoidable, strict cardiac monitoring (ECG and electrolytes).',
   'ECG (QTc), potássio e magnésio.',
   'ECG (QTc), potassium and magnesium.',
   'Síncope, palpitações, convulsões.',
   'Syncope, palpitations, seizures.',
   'EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A Claritromicina prolonga o QT e inibe o CYP3A4 (que metaboliza a Piperaquina) — risco elevado de arritmias.',
   'Clarithromycin prolongs QT and inhibits CYP3A4 (which metabolises Piperaquine) — high risk of arrhythmias.',
   'Prolongamento do QT aditivo + inibição enzimática que eleva a exposição à Piperaquina.',
   'Additive QT prolongation + enzymatic inhibition raising Piperaquine exposure.',
   'Evitar a associação; considerar antibiótico alternativo.',
   'Avoid the association; consider an alternative antibiotic.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   'moderate',
   'Prolongamento do QT aditivo (Piperaquina + Ciprofloxacina) — risco de arritmias ventriculares.',
   'Additive QT prolongation (Piperaquine + Ciprofloxacin) — risk of ventricular arrhythmias.',
   'Efeito aditivo na repolarização cardíaca.',
   'Additive effect on cardiac repolarisation.',
   'Precaução em doentes de risco; ECG se sintomas.',
   'Caution in at-risk patients; ECG if symptoms.',
   'ECG (QTc) e eletrólitos.',
   'ECG (QTc) and electrolytes.',
   'Palpitações, síncope.',
   'Palpitations, syncope.',
   'EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina (indutor) reduz os níveis de Piperaquina e Dihidroartemisinina — risco de falência do tratamento.',
   'Carbamazepine (an inducer) lowers Piperaquine and Dihydroartemisinin levels — risk of treatment failure.',
   'Indução enzimática (CYP3A4) que acelera o metabolismo dos componentes do ACT.',
   'Enzymatic induction (CYP3A4) accelerating metabolism of the ACT components.',
   'Considerar um ACT alternativo e confirmar a cura parasitológica.',
   'Consider an alternative ACT and confirm parasitological cure.',
   'Resposta clínica e parasitológica.',
   'Clinical and parasitological response.',
   'Febre persistente ou recorrente.',
   'Persistent or recurrent fever.',
   'EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   'moderate',
   'Ambos prolongam o QT — associação sem benefício e com risco arritmogénico acrescido.',
   'Both prolong QT — combining adds no benefit and increases arrhythmic risk.',
   'Prolongamento aditivo do intervalo QT.',
   'Additive QT prolongation.',
   'Evitar; usar um único esquema antimalárico.',
   'Avoid; use a single antimalarial regimen.',
   'ECG e vigilância neurológica.',
   'ECG and neurological surveillance.',
   'Palpitações, tonturas, convulsões.',
   'Palpitations, dizziness, seizures.',
   'EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
         (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'diidroartemisinina-piperaquina'),
            (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   'moderate',
   'Risco de prolongamento do QT aditivo; não são combinados na prática clínica.',
   'Risk of additive QT prolongation; not combined in clinical practice.',
   'Efeito aditivo na repolarização cardíaca.',
   'Additive effect on cardiac repolarisation.',
   'Evitar; escolher um esquema único.',
   'Avoid; choose a single regimen.',
   'ECG (QTc) e sinais de toxicidade.',
   'ECG (QTc) and signs of toxicity.',
   'Palpitações, acufenos, síncope.',
   'Palpitations, tinnitus, syncope.',
   'EMA — EPAR Eurartesim (dihidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim ; DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'sulfadoxina-pirimetamina'),
         (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'sulfadoxina-pirimetamina'),
            (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   'moderate',
   'Dois fármacos com sulfonamida (Sulfadoxina + Sulfametoxazol) — risco aditivo de reações de hipersensibilidade graves (ex.: síndrome de Stevens-Johnson) e de supressão da medula óssea.',
   'Two sulfonamide-containing drugs (Sulfadoxine + Sulfamethoxazole) — additive risk of severe hypersensitivity reactions (e.g. Stevens-Johnson syndrome) and bone marrow suppression.',
   'Sulfadoxina e Sulfametoxazol partilham o grupo sulfonamida; ambos são também antifólicos (com Pirimetamina e Trimetoprim).',
   'Sulfadoxine and Sulfamethoxazole share the sulfonamide group; both are also antifolates (with Pyrimethamine and Trimethoprim).',
   'Evitar a associação; usar um antibiótico alternativo sempre que possível.',
   'Avoid the association; use an alternative antibiotic whenever possible.',
   'Pele (erupção, bolhas), hemograma e função renal.',
   'Skin (rash, blisters), blood count and renal function.',
   'Erupção cutânea extensa, bolhas/descolamento da pele, febre, anemia, icterícia.',
   'Extensive rash, blisters/skin detachment, fever, anaemia, jaundice.',
   'OMS (WHO) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0',
   'WHO — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0',
   'published', '2026-08-03 11:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'sulfadoxina-pirimetamina'),
         (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'sulfadoxina-pirimetamina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Sulfadoxina (sulfonamida) pode potenciar o efeito da Warfarina — risco hemorrágico.',
   'Sulfadoxine (a sulfonamide) may enhance the effect of Warfarin — bleeding risk.',
   'Possível inibição do metabolismo da Warfarina e/ou deslocamento da ligação proteica.',
   'Possible inhibition of Warfarin metabolism and/or protein-binding displacement.',
   'Monitorizar o INR ao iniciar/parar e ajustar a dose.',
   'Monitor the INR on starting/stopping and adjust the dose.',
   'INR e sinais de hemorragia.',
   'INR and signs of bleeding.',
   'Hemorragias, equimoses, fezes escuras.',
   'Bleeding, bruising, dark stools.',
   'OMS (WHO) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'WHO — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria ; DailyMed/FDA (NIH/NLM) — approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 11:00:00+00');

-- ============================================================
-- Verificação após aplicar no Supabase:
-- SELECT count(*) FROM public.drugs WHERE slug IN ('artesunato','artesunato-amodiaquina','diidroartemisinina-piperaquina','sulfadoxina-pirimetamina');  -- 4
-- SELECT count(*) FROM public.drug_interactions WHERE source_pt LIKE 'OMS%' OR source_pt LIKE 'EMA%';  -- 11
-- SELECT a.slug AS drug_a, b.slug AS drug_b, di.severity
-- FROM public.drug_interactions di
-- JOIN public.drugs a ON a.id = LEAST(di.drug_a_id, di.drug_b_id)
-- JOIN public.drugs b ON b.id = GREATEST(di.drug_a_id, di.drug_b_id)
-- WHERE di.source_pt LIKE 'OMS%' OR di.source_pt LIKE 'EMA%'
-- ORDER BY 1, 2;
