-- 054: Família Antituberculares — seed da Calculadora de Interações
-- Adiciona 8 fármacos e 31 pares de interação (4 críticos, 27 moderados).
-- Total após 052+053+054: 55 fármacos e 105 pares.
--
-- Fontes: todos os fármacos têm rótulo aprovado pela FDA/DailyMed — DailyMed/FDA
-- (NIH/NLM); setIDs validados nas páginas de rótulo (drugInfo.cfm) a 2026-08-03.
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * severidade: 'critical' reservado a estados perigosos (síndrome serotoninérgica, falência
--     do tratamento da malária); os restantes são 'moderate';
--   * idempotente (UNIQUE (drug_a_id, drug_b_id)).
--
-- Nota clínica: a Pirazinamida só tem interações marginalmente relevantes; não são criados
-- pares artificiais (a calculadora mostra 'sem interações documentadas', correto).
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('rifampicina', 'Rifampicina', 'Rifampin', 'Antituberculoso (ansamicina; indutor enzimático potente)', 'Antituberculosis agent (ansamycin; potent enzyme inducer)', ARRAY['Rifadin', 'Rimactane'], 'published', 48),
  ('isoniazida', 'Isoniazida', 'Isoniazid', 'Antituberculoso (hidrazida do ácido isonicotínico)', 'Antituberculosis agent (isonicotinic acid hydrazide)', ARRAY['INH', 'Isoniazid'], 'published', 49),
  ('pirazinamida', 'Pirazinamida', 'Pyrazinamide', 'Antituberculoso (análogo da nicotinamida)', 'Antituberculosis agent (nicotinamide analogue)', ARRAY['PZA', 'Zinamide'], 'published', 50),
  ('etambutol', 'Etambutol', 'Ethambutol', 'Antituberculoso (etilenodiamina)', 'Antituberculosis agent (ethylenediamine)', ARRAY['Myambutol'], 'published', 51),
  ('rifabutina', 'Rifabutina', 'Rifabutin', 'Antituberculoso (ansamicina; indutor mais fraco que a rifampicina)', 'Antituberculosis agent (ansamycin; weaker inducer than rifampin)', ARRAY['Mycobutin'], 'published', 52),
  ('estreptomicina', 'Estreptomicina', 'Streptomycin', 'Aminoglicósido (tuberculostático injetável)', 'Aminoglycoside (injectable antituberculosis agent)', ARRAY['Estreptomicina'], 'published', 53),
  ('linezolida', 'Linezolida', 'Linezolid', 'Oxazolidinona (tuberculostático de 2.ª linha; inibidor da MAO)', 'Oxazolidinone (2nd-line antituberculosis agent; MAO inhibitor)', ARRAY['Zyvox'], 'published', 54),
  ('bedaquilina', 'Bedaquilina', 'Bedaquiline', 'Diarilquinolina (tuberculostático de 2.ª linha; prolonga o QT)', 'Diarylquinoline (2nd-line antituberculosis agent; QT prolongation)', ARRAY['Sirturo'], 'published', 55);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'artemeter-lumefantrina')),
   'critical',
   'A Rifampicina (indutor potente do CYP3A4) reduz drasticamente os níveis de Arteméter e Lumefantrina — risco elevado de falência do tratamento da malária.',
'Rifampin (a potent CYP3A4 inducer) markedly reduces Artemether and Lumefantrine levels — high risk of malaria treatment failure.',
'Indução enzimática que acelera o metabolismo do ACT, com reduções importantes da exposição à Lumefantrina.',
'Enzymatic induction accelerating ACT metabolism, with substantial reductions in Lumefantrine exposure.',
   'Evitar a associação. Se a rifampicina for essencial, usar um esquema antimalárico alternativo e confirmar a cura parasitológica.',
'Avoid the combination. If rifampin is essential, use an alternative antimalarial regimen and confirm parasitological cure.',
'Resposta clínica e parasitológica; vigilância de malária recorrente.',
'Clinical and parasitological response; watch for recurrent malaria.',
   'Febre persistente ou recorrente, parasitemia na lâmina.',
'Persistent or recurrent fever, parasitaemia on smear.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Rifampicina acelera o metabolismo da Warfarina e reduz o INR — risco de trombose por anticoagulação insuficiente.',
'Rifampin accelerates Warfarin metabolism and lowers the INR — risk of thrombosis from under-anticoagulation.',
'Indução do CYP2C9 (e CYP3A4), principal via de metabolização da Warfarina.',
'CYP2C9 (and CYP3A4) induction, the main Warfarin metabolic pathway.',
   'Monitorizar o INR ao iniciar/parar a rifampicina e ajustar a dose.',
'Monitor the INR when starting/stopping rifampin and adjust the dose.',
'INR semanal no início; sinais de trombose.',
'Weekly INR when starting; signs of thrombosis.',
   'TVP/EP, AVC, isquemia dos membros.',
'DVT/PE, stroke, limb ischaemia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'A Rifampicina reduz os níveis de Digoxina (indução da glicoproteína-P) — risco de perda de controlo da insuficiência cardíaca ou da fibrilhação auricular.',
'Rifampin lowers Digoxin levels (P-glycoprotein induction) — risk of losing control of heart failure or atrial fibrillation.',
'Indução do transportador glicoproteína-P que elimina a Digoxina.',
'Induction of the P-glycoprotein transporter that eliminates Digoxin.',
   'Monitorizar digoxinemia e os sinais clínicos; ajustar a dose.',
'Monitor digoxin levels and clinical signs; adjust the dose.',
'Digoxinemia, frequência cardíaca, sinais de insuficiência cardíaca.',
'Digoxin levels, heart rate, heart-failure signs.',
   'Agravamento da dispneia, taquiarritmias.',
'Worsening dyspnoea, tachyarrhythmias.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A Rifampicina reduz marcadamente os níveis de Amiodarona — risco de recidiva de arritmias.',
'Rifampin markedly lowers Amiodarone levels — risk of arrhythmia recurrence.',
'Indução do CYP3A4, principal via de metabolização da Amiodarona.',
'CYP3A4 induction, the main Amiodarone metabolic pathway.',
   'Evitar se possível; se inevitável, vigiar o ritmo e considerar alternativa.',
'Avoid if possible; if unavoidable, monitor rhythm and consider an alternative.',
'ECG/ritmo, sinais de recidiva arrítmica.',
'ECG/rhythm, signs of arrhythmia recurrence.',
   'Palpitações, síncope, taquicardia.',
'Palpitations, syncope, tachycardia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'Interação recíproca: a Rifampicina reduz os níveis de Carbamazepina e a Carbamazepina reduz os da Rifampicina — possível perda de eficácia de ambos.',
'Two-way interaction: Rifampin lowers Carbamazepine levels and Carbamazepine lowers Rifampin levels — possible loss of efficacy of both.',
'Indução enzimática mútua (CYP3A4/2C9).',
'Mutual enzymatic induction (CYP3A4/2C9).',
   'Monitorizar níveis de carbamazepina e resposta clínica; ajustar doses.',
'Monitor carbamazepine levels and clinical response; adjust doses.',
'Níveis de carbamazepina, controlo de crises, resposta à TB.',
'Carbamazepine levels, seizure control, TB response.',
   'Crises convulsivas, febre persistente na TB.',
'Seizures, persistent TB fever.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'A Rifampicina reduz muito os níveis de Atorvastatina — perda do efeito hipolipemiante.',
'Rifampin greatly reduces Atorvastatin levels — loss of the lipid-lowering effect.',
'Indução do CYP3A4, via principal de metabolização da Atorvastatina.',
'CYP3A4 induction, the main Atorvastatin metabolic pathway.',
   'Considerar outra estatina ou ajustar a dose vigiando os lípidos.',
'Consider another statin or adjust the dose while monitoring lipids.',
'Perfil lipídico.',
'Lipid profile.',
   'Elevação do LDL apesar da terapêutica.',
'Rising LDL despite therapy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'A Rifampicina acelera o metabolismo do Omeprazol e reduz o seu efeito de supressão ácida.',
'Rifampin accelerates Omeprazole metabolism and reduces its acid-suppressing effect.',
'Indução do CYP2C19, principal via do metabolismo do Omeprazol.',
'CYP2C19 induction, the main Omeprazole metabolic pathway.',
   'Considerar aumentar a dose ou usar alternativa (ex.: IBP menos dependente do CYP2C19).',
'Consider a higher dose or an alternative (e.g. a PPI less dependent on CYP2C19).',
'Controlo dos sintomas (dispepsia, DRGE, úlcera).',
'Symptom control (dyspepsia, GERD, ulcer).',
   'Recidiva de sintomas gástricos.',
'Recurrent gastric symptoms.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   'moderate',
   'A Rifampicina reduz os níveis de Sildenafil — perda de eficácia (ou necessidade de doses maiores).',
'Rifampin lowers Sildenafil levels — loss of efficacy (or need for higher doses).',
'Indução do CYP3A4, via de metabolização do Sildenafil.',
'CYP3A4 induction, the Sildenafil metabolic pathway.',
   'Vigiar a resposta; ajustar a dose (sem exceder o máximo diário).',
'Monitor response; adjust dose (without exceeding the daily maximum).',
'Resposta clínica.',
'Clinical response.',
   'Falta de efeito.',
'Lack of effect.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Sildenafil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Sildenafil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   'moderate',
   'A Rifampicina reduz os níveis de Prednisolona — menor efeito anti-inflamatório e imunossupressor.',
'Rifampin lowers Prednisolone levels — reduced anti-inflammatory and immunosuppressive effect.',
'Indução do CYP3A4 que acelera a eliminação do corticosteroide.',
'CYP3A4 induction accelerating corticosteroid elimination.',
   'Ajustar a dose com base na resposta; considerar reforço durante crises.',
'Adjust the dose based on response; consider reinforcement during flares.',
'Resposta clínica; sinais de exacerbação da doença de base.',
'Clinical response; signs of underlying disease flare.',
   'Exacerbação da doença (asma, DPOC, doença autoimune).',
'Disease flare (asthma, COPD, autoimmune disease).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
        (SELECT id FROM public.drugs WHERE slug = 'doxiciclina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifampicina'),
            (SELECT id FROM public.drugs WHERE slug = 'doxiciclina')),
   'moderate',
   'A Rifampicina reduz os níveis de Doxiciclina — risco de subdosagem (ex.: profilaxia da malária, brucelose, riquetsioses).',
'Rifampin lowers Doxycycline levels — risk of underdosing (e.g. malaria prophylaxis, brucellosis, rickettsial infections).',
'Indução enzimática que acelera a eliminação da Doxiciclina.',
'Enzymatic induction accelerating Doxycycline elimination.',
   'Considerar alternativa antibiótica ou ajustar a dose.',
'Consider an alternative antibiotic or adjust the dose.',
'Resposta clínica à infeção.',
'Clinical response to infection.',
   'Febre persistente, falência do tratamento.',
'Persistent fever, treatment failure.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cf95b2ca-2cf8-49a8-8e3a-f9b0f5b2072c',
'DailyMed/FDA (NIH/NLM) — approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b ; approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cf95b2ca-2cf8-49a8-8e3a-f9b0f5b2072c',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Isoniazida inibe o metabolismo da Carbamazepina e pode elevar os seus níveis — risco de toxicidade.',
'Isoniazid inhibits Carbamazepine metabolism and may raise its levels — risk of toxicity.',
'Inibição do CYP2C19/3A4 e possível inibição da epóxido hidrolase.',
'CYP2C19/3A4 inhibition and possible epoxide hydrolase inhibition.',
   'Monitorizar níveis de carbamazepina e sinais de toxicidade.',
'Monitor carbamazepine levels and signs of toxicity.',
'Níveis de carbamazepina, sinais neurológicos.',
'Carbamazepine levels, neurological signs.',
   'Nistagmo, ataxia, sonolência, diplopia.',
'Nystagmus, ataxia, drowsiness, diplopia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Isoniazida pode potenciar o efeito da Warfarina — aumento do INR e risco hemorrágico.',
'Isoniazid may enhance the effect of Warfarin — raised INR and bleeding risk.',
'Inibição do CYP2C9, principal via de metabolização da Warfarina.',
'CYP2C9 inhibition, the main Warfarin metabolic pathway.',
   'Monitorizar o INR ao iniciar/parar a isoniazida e ajustar a dose.',
'Monitor the INR when starting/stopping isoniazid and adjust the dose.',
'INR, sinais de hemorragia.',
'INR, signs of bleeding.',
   'Hemorragias, equimoses, fezes escuras.',
'Bleeding, bruising, dark stools.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
        (SELECT id FROM public.drugs WHERE slug = 'paracetamol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
            (SELECT id FROM public.drugs WHERE slug = 'paracetamol')),
   'moderate',
   'A Isoniazida (indutora do CYP2E1) aumenta a formação do metabólito tóxico do Paracetamol — maior risco de hepatotoxicidade, sobretudo em doses altas ou com álcool.',
'Isoniazid (a CYP2E1 inducer) increases formation of the toxic paracetamol metabolite — higher risk of hepatotoxicity, especially at high doses or with alcohol.',
'Indução do CYP2E1 com produção aumentada de NAPQI (metabólito hepatotóxico).',
'CYP2E1 induction with increased NAPQI (hepatotoxic) metabolite production.',
   'Limitar a dose de paracetamol (2 a 3 g por dia) e evitar álcool durante o tratamento.',
'Limit paracetamol dose (2-3 g/day) and avoid alcohol during treatment.',
'Função hepática (ALT/AST) em doentes de risco; sinais de hepatite.',
'Liver function (ALT/AST) in at-risk patients; signs of hepatitis.',
   'Icterícia, náuseas, dor no hipocôndrio direito.',
'Jaundice, nausea, right upper quadrant pain.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; rótulo aprovado Paracetamol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bf001b70-6164-1ec9-e053-2a95a90a1274',
'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; approved Paracetamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bf001b70-6164-1ec9-e053-2a95a90a1274',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
        (SELECT id FROM public.drugs WHERE slug = 'tramadol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
            (SELECT id FROM public.drugs WHERE slug = 'tramadol')),
   'moderate',
   'A Isoniazida com Tramadol aumenta o risco serotoninérgico e pode baixar o limiar convulsivo.',
'Isoniazid with Tramadol raises serotonergic risk and may lower the seizure threshold.',
'Efeito MAO fraco da isoniazida e efeitos serotoninérgicos e convulsivos do tramadol.',
'Weak MAO effect of isoniazid and serotonergic and seizure effects of tramadol.',
   'Evitar se possivel; se usados, vigiar sinais de serotonina e convulsoes.',
'Avoid if possible; if used, watch for serotonin signs and seizures.',
'Sinais serotoninergicos e neurologicos.',
'Serotonergic and neurological signs.',
   'Confusao, tremor, convulsoes, hipertermia.',
'Confusion, tremor, seizures, hyperthermia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; rótulo aprovado Tramadol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=552955e6-2bb3-8755-e063-6394a90ab21c',
'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; approved Tramadol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=552955e6-2bb3-8755-e063-6394a90ab21c',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'etambutol'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'etambutol'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Os antiacidos (aluminio e magnesio) reduzem a absorcao do Etambutol — risco de niveis sub-terapeuticos.',
'Antacids (aluminium and magnesium) reduce Ethambutol absorption — risk of subtherapeutic levels.',
'Quelacao e reducao da absorcao gastrointestinal.',
'Chelation and reduced gastrointestinal absorption.',
   'Separar a toma do etambutol e dos antiacidos por pelo menos 4 horas.',
'Separate ethambutol and antacid intake by at least 4 hours.',
'Resposta clinica a TB; adesao.',
'Clinical TB response; adherence.',
   'Falencia do tratamento.',
'Treatment failure.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etambutol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f6428d6-3745-4337-ad78-ebfff9f49135 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb',
'DailyMed/FDA (NIH/NLM) — approved Ethambutol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f6428d6-3745-4337-ad78-ebfff9f49135 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifabutina'),
        (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifabutina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'Interacao bidirecional: a Claritromicina aumenta os niveis de Rifabutina (risco de uveite e neutropenia) e a Rifabutina reduz os da Claritromicina.',
'Two-way interaction: Clarithromycin raises Rifabutin levels (risk of uveitis and neutropenia) and Rifabutin lowers Clarithromycin levels.',
'Inibicao do CYP3A4 pela claritromicina mais inducao pela rifabutina.',
'CYP3A4 inhibition by clarithromycin plus induction by rifabutin.',
   'Reduzir a dose de rifabutina (ex.: 150 mg por dia ou intermitente) e vigiar toxicidade.',
'Reduce the rifabutin dose (e.g. 150 mg/day or intermittent) and watch for toxicity.',
'Exame oftalmologico (dor e vermelhidao ocular) e hemograma.',
'Ophthalmic review (eye pain and redness) and blood count.',
   'Dor ocular, vermelhidao, visao turva (uveite); febre, neutropenia.',
'Eye pain, redness, blurred vision (uveitis); fever, neutropenia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifabutina'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifabutina'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'A Rifabutina reduz os níveis de Atorvastatina — menor efeito hipolipemiante.',
'Rifabutin lowers Atorvastatin levels — reduced lipid-lowering effect.',
'Indução do CYP3A4 (mais fraca que a rifampicina, mas significativa).',
'CYP3A4 induction (weaker than rifampin, but significant).',
   'Monitorizar os lípidos e ajustar a dose.',
'Monitor lipids and adjust the dose.',
'Perfil lipídico.',
'Lipid profile.',
   'LDL elevado.',
'High LDL.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707 ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4',
'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707 ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'rifabutina'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'rifabutina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A Rifabutina reduz os níveis de Amiodarona — risco de recidiva de arritmias.',
'Rifabutin lowers Amiodarone levels — risk of arrhythmia recurrence.',
'Indução do CYP3A4.',
'CYP3A4 induction.',
   'Vigiar o ritmo; considerar alternativa.',
'Monitor rhythm; consider an alternative.',
'ECG e ritmo.',
'ECG and rhythm.',
   'Palpitações, síncope.',
'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'estreptomicina'),
        (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'estreptomicina'),
            (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   'moderate',
   'A associação de Estreptomicina (aminoglicósido) com diuréticos de ansa (Furosemida) aumenta o risco de ototoxicidade e nefrotoxicidade.',
'Combining Streptomycin (an aminoglycoside) with loop diuretics (Furosemide) raises the risk of ototoxicity and nephrotoxicity.',
'Toxicidade aditiva no ouvido interno e no rim.',
'Additive toxicity to the inner ear and kidney.',
   'Evitar se possível; se inevitável, reduzir as doses e vigiar função renal e audição.',
'Avoid if possible; if unavoidable, reduce doses and monitor renal function and hearing.',
'Audição (acufenos, hipoacusia) e função renal (creatinina).',
'Hearing (tinnitus, hearing loss) and renal function (creatinine).',
   'Acufenos, hipoacusia, tonturas; aumento da creatinina.',
'Tinnitus, hearing loss, dizziness; rising creatinine.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972',
'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'estreptomicina'),
        (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'estreptomicina'),
            (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   'moderate',
   'Os AINE (Ibuprofeno) com aminoglicósidos (Estreptomicina) aumentam o risco de lesão renal, sobretudo em idosos ou desidratação.',
'NSAIDs (Ibuprofen) with aminoglycosides (Streptomycin) raise the risk of renal injury, especially in the elderly or dehydrated.',
'Redução do fluxo sanguíneo renal pelos AINE e toxicidade tubular do aminoglicósido.',
'Reduced renal blood flow from NSAIDs and aminoglycoside tubular toxicity.',
   'Evitar AINE durante o tratamento; garantir hidratação.',
'Avoid NSAIDs during treatment; ensure hydration.',
'Função renal (creatinina, diurese).',
'Renal function (creatinine, urine output).',
   'Oligúria, edema, elevação da creatinina.',
'Oliguria, oedema, rising creatinine.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14515409-736f-4119-b6a0-cb19ee2e948e',
'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14515409-736f-4119-b6a0-cb19ee2e948e',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'estreptomicina'),
        (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'estreptomicina'),
            (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   'moderate',
   'Risco nefrotóxico aditivo entre Estreptomicina e Diclofenac (AINE).',
'Additive nephrotoxicity risk between Streptomycin and Diclofenac (an NSAID).',
'Idem associação de AINE com aminoglicósido.',
'Same NSAID and aminoglycoside mechanism.',
   'Evitar AINE; hidratar; vigiar função renal.',
'Avoid NSAIDs; hydrate; monitor renal function.',
'Creatinina e diurese.',
'Creatinine and urine output.',
   'Insuficiência renal aguda (oligúria, fadiga, edema).',
'Acute renal failure (oliguria, fatigue, oedema).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e ; rótulo aprovado Diclofenac: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0931350-28a9-4f00-9254-1d72e31f04c3',
'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e ; approved Diclofenac label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0931350-28a9-4f00-9254-1d72e31f04c3',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
        (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
            (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   'critical',
   'Risco elevado de síndrome serotoninérgica: a Linezolida é um inibidor da MAO e com a Fluoxetina acumula serotonina — pode ser perigosa.',
'High risk of serotonin syndrome: Linezolid is an MAO inhibitor and with Fluoxetine serotonin accumulates — it can be dangerous.',
'Inibição da MAO (linezolida) e inibição da recaptação da serotonina (fluoxetina), com meia-vida longa da fluoxetina.',
'MAO inhibition (linezolid) and serotonin reuptake inhibition (fluoxetine), with long fluoxetine half-life.',
   'Evitar a associação; aguardar pelo menos 2 semanas após parar um deles.',
'Avoid the combination; wait at least 2 weeks after stopping one of them.',
'Vigilância de sinais serotoninérgicos.',
'Watch for serotonergic signs.',
   'Confusão, agitação, hipertermia, tremor, rigidez, instabilidade autonómica.',
'Confusion, agitation, hyperthermia, tremor, rigidity, autonomic instability.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; rótulo aprovado Fluoxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490',
'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; approved Fluoxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
        (SELECT id FROM public.drugs WHERE slug = 'sertralina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
            (SELECT id FROM public.drugs WHERE slug = 'sertralina')),
   'critical',
   'Risco elevado de síndrome serotoninérgica entre Linezolida e Sertralina (ISRS).',
'High risk of serotonin syndrome between Linezolid and Sertraline (an SSRI).',
'Inibição da MAO (linezolida) e inibição da recaptação da serotonina.',
'MAO inhibition (linezolid) and serotonin reuptake inhibition.',
   'Evitar; intervalo de segurança de pelo menos 14 dias entre fármacos.',
'Avoid; washout of at least 14 days between drugs.',
'Sinais de síndrome serotoninérgica.',
'Signs of serotonin syndrome.',
   'Agitação, tremor, hipertermia, rigidez, mioclonias.',
'Agitation, tremor, hyperthermia, rigidity, myoclonus.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; rótulo aprovado Sertralina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61835f25-bfe4-49ac-9dbf-3d6387866e78',
'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; approved Sertraline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61835f25-bfe4-49ac-9dbf-3d6387866e78',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
        (SELECT id FROM public.drugs WHERE slug = 'tramadol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
            (SELECT id FROM public.drugs WHERE slug = 'tramadol')),
   'critical',
   'Risco elevado de síndrome serotoninérgica e de convulsões com Linezolida e Tramadol.',
'High risk of serotonin syndrome and seizures with Linezolid and Tramadol.',
'Inibição da MAO (linezolida) somada à ação serotoninérgica e ao baixo limiar convulsivo do tramadol.',
'MAO inhibition (linezolid) plus tramadol serotonergic action and low seizure threshold.',
   'Evitar; escolher um analgésico alternativo (ex.: paracetamol ou um opioide não serotoninérgico).',
'Avoid; choose an alternative analgesic (e.g. paracetamol or a non-serotonergic opioid).',
'Sinais serotoninérgicos e neurológicos.',
'Serotonergic and neurological signs.',
   'Convulsões, confusão, hipertermia, mioclonias.',
'Seizures, confusion, hyperthermia, myoclonus.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; rótulo aprovado Tramadol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=552955e6-2bb3-8755-e063-6394a90ab21c',
'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; approved Tramadol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=552955e6-2bb3-8755-e063-6394a90ab21c',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'linezolida'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A Rifampicina reduz os níveis de Linezolida — risco de perda de eficácia do tratamento da TB.',
'Rifampin lowers Linezolid levels — risk of losing TB treatment efficacy.',
'Indução de enzimas e transportadores que eliminam a Linezolida.',
'Induction of enzymes and transporters that eliminate Linezolid.',
   'Considerar monitorização farmacoterapêutica ou ajustar o esquema; vigiar a resposta.',
'Consider therapeutic drug monitoring or regimen adjustment; watch the response.',
'Resposta clínica à TB.',
'Clinical TB response.',
   'Febre persistente, baciloscopia positiva.',
'Persistent fever, positive sputum smear.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b',
'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=374af2a7-d994-40bd-a86a-cd9038d0b72c ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A Rifampicina reduz substancialmente os níveis de Bedaquilina (cerca de 50%) — risco de falência e resistência na TB multirresistente.',
'Rifampin substantially lowers Bedaquiline levels (about 50%) — risk of failure and resistance in multidrug-resistant TB.',
'Indução do CYP3A4, principal via de metabolização da Bedaquilina.',
'CYP3A4 induction, the main Bedaquiline metabolic pathway.',
   'Evitar a coadministração; se inevitável, considerar monitorização farmacoterapêutica.',
'Avoid coadministration; if unavoidable, consider therapeutic drug monitoring.',
'Resposta microbiológica (cultura e baciloscopia).',
'Microbiological response (culture and smear).',
   'Persistência da positividade, resistência emergente.',
'Persistent positivity, emerging resistance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b',
'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A Bedaquilina prolonga o QT; a associação com Amiodarona aumenta o risco de arritmias ventriculares.',
'Bedaquiline prolongs the QT interval; combining with Amiodarone raises the risk of ventricular arrhythmias.',
'Prolongamento aditivo da repolarização cardíaca.',
'Additive cardiac repolarisation prolongation.',
   'Evitar; se inevitável, ECG periódico e controle de eletrólitos.',
'Avoid; if unavoidable, periodic ECG and electrolyte control.',
'ECG (QTc), potássio e magnésio.',
'ECG (QTc), potassium and magnesium.',
   'Síncope, palpitações.',
'Syncope, palpitations.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
        (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A Claritromicina prolonga o QT e inibe o CYP3A4, elevando os níveis de Bedaquilina — risco acrescido de arritmias.',
'Clarithromycin prolongs the QT interval and inhibits CYP3A4, raising Bedaquiline levels — increased arrhythmia risk.',
'Inibição do metabolismo da bedaquilina e prolongamento do QT aditivo.',
'Bedaquiline metabolism inhibition and additive QT prolongation.',
   'Evitar quando possível; ECG e vigilância.',
'Avoid when possible; ECG and surveillance.',
'ECG (QTc) e eletrólitos.',
'ECG (QTc) and electrolytes.',
   'Palpitações, síncope.',
'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
        (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'bedaquilina'),
            (SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina')),
   'moderate',
   'Prolongamento do QT aditivo entre Bedaquilina e Ciprofloxacina.',
'Additive QT prolongation between Bedaquiline and Ciprofloxacin.',
'Efeito aditivo na repolarização cardíaca.',
'Additive effect on cardiac repolarisation.',
   'Precaução; ECG se fatores de risco.',
'Caution; ECG if risk factors.',
'ECG (QTc).',
'ECG (QTc).',
   'Palpitações, síncope.',
'Palpitations, syncope.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
        (SELECT id FROM public.drugs WHERE slug = 'sertralina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
            (SELECT id FROM public.drugs WHERE slug = 'sertralina')),
   'moderate',
   'A Isoniazida tem um efeito inibidor fraco da monoaminoxidase; com ISRS (Sertralina) pode aumentar o risco de síndrome serotoninérgica.',
'Isoniazid has a weak monoamine oxidase-inhibiting effect; with SSRIs (Sertraline) it may raise the risk of serotonin syndrome.',
'Inibição fraca da MAO pela isoniazida e inibição da recaptação da serotonina.',
'Weak MAO inhibition by isoniazid and serotonin reuptake inhibition.',
   'Vigiar sinais serotoninérgicos; usar com precaução.',
'Watch for serotonergic signs; use with caution.',
'Sinais de síndrome serotoninérgica.',
'Signs of serotonin syndrome.',
   'Agitação, tremor, hipertermia, rigidez, diarreia.',
'Agitation, tremor, hyperthermia, rigidity, diarrhoea.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; rótulo aprovado Sertralina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61835f25-bfe4-49ac-9dbf-3d6387866e78',
'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; approved Sertraline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61835f25-bfe4-49ac-9dbf-3d6387866e78',
   'published', '2026-08-03 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
        (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isoniazida'),
            (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   'moderate',
   'Risco semelhante ao de outros ISRS: a Isoniazida com Fluoxetina pode precipitar síndrome serotoninérgia.',
'Similar risk to other SSRIs: Isoniazid with Fluoxetine may precipitate serotonin syndrome.',
'Efeito MAO fraco da isoniazida e inibição da recaptação da serotonina, com meia-vida longa da fluoxetina.',
'Weak MAO effect of isoniazid and serotonin reuptake inhibition, with long fluoxetine half-life.',
   'Vigiar sinais serotoninérgicos; informar o doente.',
'Watch for serotonergic signs; counsel the patient.',
'Sinais de síndrome serotoninérgica.',
'Signs of serotonin syndrome.',
   'Agitação, confusão, tremor, hipertermia.',
'Agitation, confusion, tremor, hyperthermia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; rótulo aprovado Fluoxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490',
'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e ; approved Fluoxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490',
   'published', '2026-08-03 12:00:00+00');

-- Verificação após aplicar no Supabase: SELECT count(*) FROM public.drugs WHERE slug LIKE 'rifrafrico%'
