-- 055: Família Antifúngicos Azólicos — seed da Calculadora de Interações
-- Adiciona 4 fármacos (cetoconazol, itraconazol, fluconazol, voriconazol) e 41 pares
-- de interação, todos de severidade 'moderate' (QT aditivo, inibição/indução enzimática,
-- falência antifúngica por redução de absorção). Total após 054: 59 fármacos e 146 pares.
--
-- Fontes: rótulos aprovados pela FDA/DailyMed — DailyMed/FDA (NIH/NLM); setIDs validados
-- nas páginas de rótulo (drugInfo.cfm) a 2026-08-04. Referência clínica adicional:
-- Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — secções 1.2.1 (antifúngicos) e
-- Anexo 7 (Interacções importantes, classe "Antifúngicos (Azol)").
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * todos os pares são 'moderate' (nenhum par crítico: sem síndromes serotoninérgicas nem
--     estados de falência de malária; as associações contraindicadas, ex. voriconazol +
--     rifampicina, ficam documentadas como moderate com conduta 'evitar');
--   * idempotente (UNIQUE (drug_a_id, drug_b_id)).
--
-- Nota clínica: a amlodipina e a atorvastatina já existiam na base; a associação com os
-- azóis é clinicamente relevante em Angola (candidíases/terapêutica sistémica em doentes
-- com hipertensão e dislipidemia). O voriconazol + omeprazol, sildenafil, digoxina e
-- amiodarona/quinina baseiam-se nos rótulos aprovados (não documentados no Prontuário).
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('cetoconazol', 'Cetoconazol', 'Ketoconazole', 'Antifúngico azólico (imidazol; inibidor potente do CYP3A4)', 'Azole antifungal (imidazole; potent CYP3A4 inhibitor)', ARRAY['Nizoral', 'Cetoconazol'], 'published', 56),
  ('itraconazol', 'Itraconazol', 'Itraconazole', 'Antifúngico azólico (triazol; inibidor potente do CYP3A4 e da glicoproteína-P)', 'Azole antifungal (triazole; potent CYP3A4 and P-glycoprotein inhibitor)', ARRAY['Sporanox', 'Itraconazol'], 'published', 57),
  ('fluconazol', 'Fluconazol', 'Fluconazole', 'Antifúngico azólico (triazol; inibidor do CYP2C9/CYP3A4)', 'Azole antifungal (triazole; CYP2C9/CYP3A4 inhibitor)', ARRAY['Diflucan', 'Fluconazol'], 'published', 58),
  ('voriconazol', 'Voriconazol', 'Voriconazole', 'Antifúngico azólico (triazol; inibidor do CYP2C19/CYP2C9/CYP3A4)', 'Azole antifungal (triazole; CYP2C19/CYP2C9/CYP3A4 inhibitor)', ARRAY['Vfend', 'Voriconazol'], 'published', 59);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'O Cetoconazol (inibidor potente do CYP3A4) aumenta os níveis da Atorvastatina, com risco de miopatia e rabdomiólise.',
'Ketoconazole (a potent CYP3A4 inhibitor) raises Atorvastatin levels, increasing the risk of myopathy and rhabdomyolysis.',
'Inibição do CYP3A4 pelo cetoconazol, reduzindo o metabolismo de primeira passagem da atorvastatina e aumentando a sua exposição sistémica.',
'CYP3A4 inhibition by ketoconazole reduces first-pass metabolism of atorvastatin, increasing its systemic exposure.',
'Preferir uma estatina não metabolizada pelo CYP3A4 (ex.: pravastatina, rosuvastatina) ou suspender o cetoconazol durante o tratamento. Se inevitável, usar a dose mínima de atorvastatina e vigiar.',
'Prefer a statin not metabolized by CYP3A4 (e.g., pravastatin, rosuvastatin) or discontinue ketoconazole during therapy. If unavoidable, use the lowest atorvastatin dose with monitoring.',
'Creatina-quinase (CK), sintomas musculares (mialgias, fraqueza, urina escura).',
'Creatine kinase (CK), muscle symptoms (myalgia, weakness, dark urine).',
'Dor muscular intensa, fraqueza, urina de cor escura (sinal de rabdomiólise).',
'Severe muscle pain, weakness, dark-coloured urine (sign of rhabdomyolysis).',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'O Cetoconazol aumenta as concentrações de Digoxina, com risco de toxicidade digitálica.',
'Ketoconazole raises Digoxin concentrations, with a risk of digitalis toxicity.',
'Inibição da glicoproteína-P pelo cetoconazol, reduzindo a eliminação da digoxina e aumentando a sua biodisponibilidade.',
'P-glycoprotein inhibition by ketoconazole reduces digoxin elimination and increases its bioavailability.',
'Monitorizar digoxinemia e sinais clínicos; reduzir a dose de digoxina se necessário. Vigiar sobretudo nos idosos e na insuficiência renal.',
'Monitor digoxin levels and clinical signs; reduce the digoxin dose if needed. Watch closely in the elderly and in renal impairment.',
'Digoxinemia, ECG (bradicardia, arritmias), sintomas gastrointestinais e visuais.',
'Digoxin levels, ECG (bradycardia, arrhythmias), gastrointestinal and visual symptoms.',
'Náuseas, vómitos, arritmias, visão amarela/verde (xantopsia).',
'Nausea, vomiting, arrhythmias, yellow/green vision (xanthopsia).',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O Cetoconazol potencia o efeito anticoagulante da Varfarina, com aumento do risco hemorrágico.',
'Ketoconazole potentiates the anticoagulant effect of Warfarin, increasing the bleeding risk.',
'Inibição do CYP2C9 (e CYP3A4) pelo cetoconazol, reduzindo o metabolismo da varfarina e aumentando o INR.',
'CYP2C9 (and CYP3A4) inhibition by ketoconazole reduces warfarin metabolism and raises the INR.',
'Monitorizar o INR de forma mais frequente após iniciar/suspender o cetoconazol; ajustar a dose de varfarina conforme necessário.',
'Monitor the INR more frequently after starting/stopping ketoconazole; adjust the warfarin dose accordingly.',
'INR, sinais de hemorragia (gengivas, equimoses, melenas).',
'INR, signs of bleeding (gums, bruising, melena).',
'Hemorragia inexplicada, hematúria, melena, hemorragia intracraniana.',
'Unexplained bleeding, haematuria, melena, intracranial haemorrhage.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   'moderate',
   'O Cetoconazol aumenta as concentrações de Sildenafil, com risco de hipotensão e efeitos adversos intensificados.',
'Ketoconazole raises Sildenafil concentrations, with a risk of hypotension and intensified adverse effects.',
'Inibição do CYP3A4, principal via de metabolismo do sildenafil, aumentando a sua exposição plasmática.',
'CYP3A4 inhibition — the main sildenafil metabolic pathway — increases its plasma exposure.',
'Limitar a dose de sildenafil (máx. 25 mg) durante o tratamento com cetoconazol; evitar o uso em doentes com doença cardiovascular instável.',
'Limit the sildenafil dose (max 25 mg) during ketoconazole therapy; avoid use in unstable cardiovascular disease.',
'Pressão arterial, cefaleia, rubor facial, palpitações.',
'Blood pressure, headache, facial flushing, palpitations.',
'Hipotensão grave, síncope, dor torácica, priapismo.',
'Severe hypotension, syncope, chest pain, priapism.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Sildenafil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Sildenafil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A Rifampicina (indutor do CYP450) reduz acentuadamente as concentrações de Cetoconazol, com risco de falência terapêutica antifúngica.',
'Rifampin (a CYP450 inducer) markedly reduces Ketoconazole levels, risking antifungal treatment failure.',
'Indução enzimática (CYP3A4/glicoproteína-P) pela rifampicina, acelerando a eliminação do cetoconazol e reduzindo a sua eficácia.',
'Enzymatic induction (CYP3A4/P-glycoprotein) by rifampin accelerates ketoconazole elimination and reduces its efficacy.',
'Evitar a associação. Se forem necessários ambos, usar antifúngico alternativo e monitorizar a resposta clínica e micológica.',
'Avoid the combination. If both are required, use an alternative antifungal and monitor clinical and mycological response.',
'Resposta clínica ao antifúngico; níveis de cetoconazol (se disponíveis); provas de função hepática.',
'Clinical response to the antifungal; ketoconazole levels (if available); liver function tests.',
'Persistência/agravamento da infeção fúngica, febre recorrente.',
'Persistent or worsening fungal infection, recurrent fever.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina reduz as concentrados de Cetoconazol (indução) e o cetoconazol pode aumentar a carbamazepina (inibição), com efeitos recíprocos.',
'Carbamazepine lowers ketoconazole levels (induction) while ketoconazole can raise carbamazepine; reciprocal effects.',
'A carbamazepina induz o metabolismo do cetoconazol; o cetoconazol inibe o CYP3A4 reduzindo o metabolismo da carbamazepina.',
'Carbamazepine induces ketoconazole metabolism; ketoconazole inhibits CYP3A4, reducing carbamazepine metabolism.',
'Monitorizar níveis de carbamazepina e resposta antifúngica; ajustar doses; considerar alternativa não indutora de CYP3A4.',
'Monitor carbamazepine levels and antifungal response; adjust doses; consider a non-CYP3A4-inducing alternative.',
'Concentração de carbamazepina, sintomas de intoxicação (diplopia, nistagmo, ataxia), resposta à micose.',
'Carbamazepine concentration, toxicity symptoms (diplopia, nystagmus, ataxia), mycosis response.',
'Diplopia, nistagmo, ataxia, sonolência; ou agravamento da infeção fúngica.',
'Diplopia, nystagmus, ataxia, drowsiness; or worsening fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Associação de Cetoconazol e Amiodarona com risco de prolongamento do intervalo QT e arritmias ventriculares.',
'Ketoconazole plus Amiodarone carries a risk of QT prolongation and ventricular arrhythmias.',
'Efeito aditivo sobre a repolarização cardíaca; o cetoconazol também pode aumentar os níveis de amiodarona por inibição do metabolismo.',
'Additive effect on cardiac repolarization; ketoconazole may also raise amiodarone levels via metabolic inhibition.',
'Usar com precaução; monitorizar ECG (intervalo QT) e eletrólitos (K+, Mg2+); corrigir hipocalemia antes de associar.',
'Use with caution; monitor ECG (QT interval) and electrolytes (K+, Mg2+); correct hypokalaemia before combining.',
'ECG (intervalo QT), eletrólitos (K+, Mg2+), sinais de arritmia/palpitações.',
'ECG (QT interval), electrolytes (K+, Mg2+), signs of arrhythmia/palpitations.',
'Síncope, palpitações, torsades de pointes.',
'Syncope, palpitations, torsades de pointes.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Os antiácidos, antagonistas H2, inibidores da bomba de protões e sucralfato reduzem significativamente a absorção do Cetoconazol, comprometendo a sua eficácia.',
'Antacids, H2-blockers, proton-pump inhibitors and sucralfate markedly reduce Ketoconazole absorption, compromising efficacy.',
'A absorção do cetoconazol depende do pH gástrico ácido; fármacos que elevam o pH gástrico reduzem a sua dissolução e absorção.',
'Ketoconazole absorption depends on gastric acidity; agents that raise gastric pH reduce its dissolution and absorption.',
'Administrar o cetoconazol ≥2 h antes dos antiácidos/IBP; se não for possível, usar fluconazol/voriconazol (menos pH-dependentes).',
'Give ketoconazole at least 2 h before antacids/PPIs; otherwise use fluconazole/voriconazole (less pH-dependent).',
'Resposta clínica; sinais de falência antifúngica; separação temporal das tomas.',
'Clinical response; signs of antifungal failure; temporal separation of doses.',
'Agravamento/persistência da infeção fúngica.',
'Worsening or persistent fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'O Omeprazol (inibidor da bomba de protões) reduz a absorção do Cetoconazol por aumentar o pH gástrico.',
'Omeprazole (proton-pump inhibitor) reduces Ketoconazole absorption by raising gastric pH.',
'A absorção dependente do pH: a supressão ácida reduz a dissolução do cetoconazol no estômago.',
'pH-dependent absorption: acid suppression reduces ketoconazole dissolution in the stomach.',
'Separar as tomas (cetoconazol 2 h antes do omeprazol) ou preferir um azol não pH-dependente.',
'Separate dosing (ketoconazole 2 h before omeprazole) or prefer a non-pH-dependent azole.',
'Resposta clínica ao antifúngico.',
'Clinical response to the antifungal.',
'Persistência da infeção fúngica.',
'Persistent fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'O Itraconazol (inibidor potente do CYP3A4) aumenta os níveis da Atorvastatina, com risco de miopatia e rabdomiólise.',
'Itraconazole (a potent CYP3A4 inhibitor) raises Atorvastatin levels, increasing the risk of myopathy and rhabdomyolysis.',
'Inibição do CYP3A4 pelo itraconazol, reduzindo o metabolismo de primeira passagem da atorvastatina e aumentando a sua exposição.',
'CYP3A4 inhibition by itraconazole reduces first-pass atorvastatin metabolism, increasing its exposure.',
'Preferir estatina não metabolizada pelo CYP3A4 (pravastatina, rosuvastatina) ou suspender o itraconazol; caso contrário, usar dose mínima de atorvastatina com vigilância.',
'Prefer a non-CYP3A4 statin (pravastatin, rosuvastatin) or stop itraconazole; otherwise use the lowest atorvastatin dose with monitoring.',
'Creatina-quinase (CK), sintomas musculares (mialgias, fraqueza, urina escura).',
'Creatine kinase (CK), muscle symptoms (myalgia, weakness, dark urine).',
'Dor muscular intensa, fraqueza, urina de cor escura (rabdomiólise).',
'Severe muscle pain, weakness, dark-coloured urine (rhabdomyolysis).',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'O Itraconazol aumenta as concentrações de Digoxina, com risco de toxicidade digitálica.',
'Itraconazole raises Digoxin concentrations, with a risk of digitalis toxicity.',
'Inibição da glicoproteína-P pelo itraconazol, reduzindo a eliminação da digoxina.',
'P-glycoprotein inhibition by itraconazole reduces digoxin elimination.',
'Monitorizar digoxinemia e sinais clínicos; reduzir a dose de digoxina se necessário (sobretudo idosos e IR).',
'Monitor digoxin levels and clinical signs; reduce the digoxin dose if needed (especially the elderly and renal impairment).',
'Digoxinemia, ECG, sintomas gastrointestinais e visuais.',
'Digoxin levels, ECG, gastrointestinal and visual symptoms.',
'Náuseas, vómitos, arritmias, visão amarela/verde.',
'Nausea, vomiting, arrhythmias, yellow/green vision.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O Itraconazol potencia o efeito anticoagulante da Varfarina, com aumento do risco hemorrágico.',
'Itraconazole potentiates the anticoagulant effect of Warfarin, increasing the bleeding risk.',
'Inibição do metabolismo (CYP2C9/CYP3A4) da varfarina pelo itraconazol, aumentando o INR.',
'Metabolic inhibition (CYP2C9/CYP3A4) of warfarin by itraconazole, raising the INR.',
'Monitorizar o INR com frequência após iniciar/suspender o itraconazol; ajustar a dose de varfarina.',
'Monitor the INR frequently after starting/stopping itraconazole; adjust the warfarin dose.',
'INR, sinais de hemorragia (gengivas, equimoses, melenas).',
'INR, signs of bleeding (gums, bruising, melena).',
'Hemorragia inexplicada, hematúria, melena.',
'Unexplained bleeding, haematuria, melena.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   'moderate',
   'O Itraconazol aumenta as concentrações de Sildenafil, com risco de hipotensão e efeitos adversos.',
'Itraconazole raises Sildenafil concentrations, with a risk of hypotension and adverse effects.',
'Inibição do CYP3A4, principal via de metabolismo do sildenafil, aumentando a sua exposição.',
'CYP3A4 inhibition — the main sildenafil metabolic pathway — increases its exposure.',
'Limitar a dose de sildenafil (máx. 25 mg) durante o tratamento com itraconazol.',
'Limit the sildenafil dose (max 25 mg) during itraconazole therapy.',
'Pressão arterial, cefaleia, rubor, palpitações.',
'Blood pressure, headache, flushing, palpitations.',
'Hipotensão, síncope, priapismo.',
'Hypotension, syncope, priapism.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Sildenafil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Sildenafil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A Rifampicina (indutor do CYP450) reduz acentuadamente as concentrações de Itraconazol, com risco de falência terapêutica antifúngica.',
'Rifampin (a CYP450 inducer) markedly reduces Itraconazole levels, risking antifungal treatment failure.',
'Indução enzimática (CYP3A4/glicoproteína-P) pela rifampicina, acelerando a eliminação do itraconazol e reduzindo a sua eficácia.',
'Enzymatic induction (CYP3A4/P-glycoprotein) by rifampin accelerates itraconazole elimination, reducing efficacy.',
'Evitar a associação. Se ambos forem necessários, usar antifúngico alternativo e monitorizar a resposta clínica e micológica.',
'Avoid the combination. If both are needed, use an alternative antifungal and monitor clinical and mycological response.',
'Resposta clínica ao antifúngico; provas de função hepática.',
'Clinical response to the antifungal; liver function tests.',
'Persistência/agravamento da infeção fúngica.',
'Persistent or worsening fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina reduz as concentrações de Itraconazol (indução) e aumenta o metabolismo do azol, com risco de falência antifúngica.',
'Carbamazepine lowers Itraconazole levels (induction), increasing the risk of antifungal failure.',
'A carbamazepina induz o CYP3A4, acelerando o metabolismo do itraconazol e reduzindo a sua exposição.',
'Carbamazepine induces CYP3A4, accelerating itraconazole metabolism and reducing its exposure.',
'Considerar antifúngico alternativo; se a associação for inevitável, monitorizar a resposta clínica e micológica.',
'Consider an alternative antifungal; if the combination is unavoidable, monitor clinical and mycological response.',
'Resposta à micose; níveis de itraconazol (se disponíveis).',
'Mycosis response; itraconazole levels (if available).',
'Agravamento da infeção fúngica.',
'Worsening fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Associação de Itraconazol e Amiodarona com risco de prolongamento do intervalo QT e arritmias ventriculares.',
'Itraconazole plus Amiodarone carries a risk of QT prolongation and ventricular arrhythmias.',
'Efeito aditivo sobre a repolarização cardíaca; o itraconazol também pode aumentar os níveis de amiodarona.',
'Additive effect on cardiac repolarization; itraconazole may also raise amiodarone levels.',
'Usar com precaução; monitorizar ECG (QT) e eletrólitos (K+, Mg2+); corrigir hipocalemia antes de associar.',
'Use with caution; monitor ECG (QT) and electrolytes (K+, Mg2+); correct hypokalaemia before combining.',
'ECG (intervalo QT), eletrólitos (K+, Mg2+), sinais de arritmia.',
'ECG (QT interval), electrolytes (K+, Mg2+), signs of arrhythmia.',
'Síncope, palpitações, torsades de pointes.',
'Syncope, palpitations, torsades de pointes.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Os antiácidos, antagonistas H2, inibidores da bomba de protões e sucralfato reduzem significativamente a absorção do Itraconazol.',
'Antacids, H2-blockers, proton-pump inhibitors and sucralfate markedly reduce Itraconazole absorption.',
'A absorção do itraconazol (cápsulas) depende do pH gástrico ácido; fármacos que elevam o pH reduzem a sua absorção.',
'Itraconazole (capsule) absorption depends on gastric acidity; agents that raise gastric pH reduce absorption.',
'Administrar o itraconazol ≥2 h antes dos antiácidos/IBP; considerar a solução oral (absorção menos pH-dependente).',
'Give itraconazole at least 2 h before antacids/PPIs; consider the oral solution (less pH-dependent absorption).',
'Resposta clínica; sinais de falência antifúngica.',
'Clinical response; signs of antifungal failure.',
'Persistência/agravamento da infeção fúngica.',
'Persistent or worsening fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'O Omeprazol reduz a absorção do Itraconazol por aumentar o pH gástrico, comprometendo a eficácia.',
'Omeprazole reduces Itraconazole absorption by raising gastric pH, compromising efficacy.',
'A absorção pH-dependente: a supressão ácida reduz a dissolução do itraconazol no estômago.',
'pH-dependent absorption: acid suppression reduces itraconazole dissolution in the stomach.',
'Separar as tomas, evolit omeprazol por um antiácido de ação curta fora da janela de absorção, ou usar outra classe.',
'Separate dosing, switch omeprazole to a short-acting antacid outside the dosing window, or use another class.',
'Resposta clínica ao antifúngico.',
'Clinical response to the antifungal.',
'Persistência da infeção fúngica.',
'Persistent fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O Fluconazol potencia o efeito anticoagulante da Varfarina, com aumento significativo do INR e risco hemorrágico.',
'Fluconazole potentiates the anticoagulant effect of Warfarin, markedly raising the INR and the bleeding risk.',
'Inibição do CYP2C9 pelo fluconazol, reduzindo o metabolismo da varfarina (isómero S ativo) e aumentando o INR.',
'CYP2C9 inhibition by fluconazole reduces the metabolism of the active S-warfarin isomer, raising the INR.',
'Monitorizar o INR com frequência (início e suspensão do fluconazol); reduzir a dose de varfarina conforme necessário.',
'Monitor the INR frequently (on starting and stopping fluconazole); reduce the warfarin dose as needed.',
'INR, sinais de hemorragia (gengivas, equimoses, melenas).',
'INR, signs of bleeding (gums, bruising, melena).',
'Hemorragia inexplicada, hematúria, melena.',
'Unexplained bleeding, haematuria, melena.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'glibenclamida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'glibenclamida')),
   'moderate',
   'O Fluconazol potencia o efeito da Glibenclamida, com risco de hipoglicemia grave.',
'Fluconazole potentiates the effect of Glyburide (Glibenclamide), with a risk of severe hypoglycaemia.',
'Inibição do CYP2C9 pelo fluconazol, reduzindo o metabolismo da glibenclamida e aumentando as suas concentrações.',
'CYP2C9 inhibition by fluconazole reduces glibenclamide metabolism, increasing its concentrations.',
'Monitorizar a glicemia de forma mais frequente; pode ser necessário reduzir a dose da sulfonilureia.',
'Monitor blood glucose more frequently; a sulfonylurea dose reduction may be needed.',
'Glicemia capilar, sintomas de hipoglicemia (tremor, sudorese, confusão).',
'Capillary glucose, hypoglycaemia symptoms (tremor, sweating, confusion).',
'Hipoglicemia grave (perda de consciência, convulsões).',
'Severe hypoglycaemia (loss of consciousness, seizures).',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Glibenclamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524eec41-37ee-419a-b7a1-d23e888ae6ab — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Glyburide (Glibenclamide) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524eec41-37ee-419a-b7a1-d23e888ae6ab — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'O Fluconazol aumenta os níveis da Atorvastatina (inibição do CYP3A4), com risco de miopatia.',
'Fluconazole raises Atorvastatin levels (CYP3A4 inhibition), with a risk of myopathy.',
'Inibição moderada do CYP3A4 pelo fluconazol, reduzindo o metabolismo da atorvastatina.',
'Moderate CYP3A4 inhibition by fluconazole reduces atorvastatin metabolism.',
'Vigiar sintomas musculares e CK; considerar estatina alternativa ou dose ajustada.',
'Watch for muscle symptoms and CK; consider an alternative statin or adjusted dose.',
'Creatina-quinase (CK), mialgias, fraqueza.',
'Creatine kinase (CK), myalgia, weakness.',
'Dor muscular intensa, urina escura.',
'Severe muscle pain, dark urine.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   'moderate',
   'Associação de Fluconazol e Quinina com risco de prolongamento do intervalo QT e arritmias ventriculares.',
'Fluconazole plus Quinine carries a risk of QT prolongation and ventricular arrhythmias.',
'Efeito aditivo sobre a repolarização cardíaca; o fluconazol também pode aumentar os níveis de quinina.',
'Additive effect on cardiac repolarization; fluconazole may also raise quinine levels.',
'Usar com precaução; monitorizar ECG (QT) e eletrólitos; preferir esquema antimalárico alternativo quando possível.',
'Use with caution; monitor ECG (QT) and electrolytes; prefer an alternative antimalarial regimen when possible.',
'ECG (intervalo QT), eletrólitos (K+, Mg2+), sinais de arritmia.',
'ECG (QT interval), electrolytes (K+, Mg2+), signs of arrhythmia.',
'Síncope, palpitações, torsades de pointes.',
'Syncope, palpitations, torsades de pointes.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'mefloquina')),
   'moderate',
   'Associação de Fluconazol e Mefloquina com risco de prolongamento do intervalo QT e arritmias.',
'Fluconazole plus Mefloquine carries a risk of QT prolongation and arrhythmias.',
'Efeito aditivo sobre a repolarização cardíaca (ambos prolongam o QT).',
'Additive effect on cardiac repolarization (both prolong the QT).',
'Usar com precaução; monitorizar ECG (QT) e eletrólitos; considerar alternativa antimalárica.',
'Use with caution; monitor ECG (QT) and electrolytes; consider an alternative antimalarial.',
'ECG (intervalo QT), eletrólitos (K+, Mg2+).',
'ECG (QT interval), electrolytes (K+, Mg2+).',
'Síncope, palpitações, torsades de pointes.',
'Syncope, palpitations, torsades de pointes.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'cloroquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'cloroquina')),
   'moderate',
   'Associação de Fluconazol e Cloroquina com risco de prolongamento do intervalo QT.',
'Fluconazole plus Chloroquine carries a risk of QT prolongation.',
'Efeito aditivo sobre a repolarização cardíaca (ambos prolongam o QT).',
'Additive effect on cardiac repolarization (both prolong the QT).',
'Usar com precaução; monitorizar ECG (QT) e eletrólitos.',
'Use with caution; monitor ECG (QT) and electrolytes.',
'ECG (intervalo QT), eletrólitos (K+, Mg2+).',
'ECG (QT interval), electrolytes (K+, Mg2+).',
'Síncope, palpitações.',
'Syncope, palpitations.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'O Fluconazol pode aumentar as concentrações de Carbamazepina (inibição do metabolismo), com risco de toxicidade.',
'Fluconazole may raise Carbamazepine levels (metabolic inhibition), with a risk of toxicity.',
'Inibição do CYP3A4 pelo fluconazol, reduzindo o metabolismo da carbamazepina.',
'CYP3A4 inhibition by fluconazole reduces carbamazepine metabolism.',
'Monitorizar níveis de carbamazepina e sintomas de toxicidade; ajustar a dose conforme necessário.',
'Monitor carbamazepine levels and toxicity symptoms; adjust the dose as needed.',
'Concentração de carbamazepina, sintomas (diplopia, nistagmo, ataxia).',
'Carbamazepine concentration, symptoms (diplopia, nystagmus, ataxia).',
'Diplopia, nistagmo, ataxia, sonolência.',
'Diplopia, nystagmus, ataxia, drowsiness.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A Rifampicina reduz as concentrações de Fluconazol, com risco de falência terapêutica antifúngica.',
'Rifampin reduces Fluconazole levels, risking antifungal treatment failure.',
'Indução enzimática da rifampicina, acelerando o metabolismo do fluconazol.',
'Enzymatic induction by rifampin accelerates fluconazole metabolism.',
'Monitorizar a resposta clínica; pode ser necessário aumentar a dose de fluconazol ou usar antifúngico alternativo.',
'Monitor clinical response; a fluconazole dose increase or an alternative antifungal may be needed.',
'Resposta clínica, provas de função hepática.',
'Clinical response, liver function tests.',
'Persistência/agravamento da infeção fúngica.',
'Persistent or worsening fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   'moderate',
   'O Fluconazol pode aumentar os níveis de Prednisolona (inibição do metabolismo), com risco de efeitos corticosteróides aumentados.',
'Fluconazole may raise prednisolone levels (metabolic inhibition), with a risk of enhanced corticosteroid effects.',
'Inibição do CYP3A4 pelo fluconazol, reduzindo o metabolismo da prednisolona.',
'CYP3A4 inhibition by fluconazole reduces prednisolone metabolism.',
'Vigiar efeitos de corticoterapia (hiperglicemia, retenção hídrica); ajustar a dose do corticoide se sintomas de sobredosagem.',
'Watch for corticosteroid effects (hyperglycaemia, fluid retention); adjust the steroid dose if overdosage symptoms occur.',
'Glicemia, pressão arterial, sinais de Cushing iatrogénico.',
'Blood glucose, blood pressure, signs of iatrogenic Cushing.',
'Edema, hiperglicemia, fácies cushingoide.',
'Oedema, hyperglycaemia, Cushingoid facies.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873 ; approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'O Omeprazol aumenta as concentrações de Voriconazol (inibição do CYP2C19) e o voriconazol aumenta os níveis de omeprazol.',
'Omeprazole raises Voriconazole levels (CYP2C19 inhibition) and voriconazole raises omeprazole levels.',
'Interação bidirecional no CYP2C19: o omeprazol inibe o metabolismo do voriconazol; o voriconazol inibe o metabolismo do omeprazol.',
'Bidirectional CYP2C19 interaction: omeprazole inhibits voriconazole metabolism; voriconazole inhibits omeprazole metabolism.',
'Monitorizar a resposta e efeitos adversos do voriconazol; considerar reduzir a dose de voriconazol se usado a longo prazo.',
'Monitor voriconazole response and adverse effects; consider reducing the voriconazole dose with long-term use.',
'Níveis de voriconazol (se disponíveis), provas de função hepática, efeitos visuais.',
'Voriconazole levels (if available), liver function tests, visual effects.',
'Fotofobia, alterações visuais, elevação das transaminases.',
'Photophobia, visual disturbances, elevated transaminases.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A Carbamazepina (indutora do CYP450) reduz significativamente as concentrações de Voriconazol, com risco de falência antifúngica.',
'Carbamazepine (a CYP450 inducer) markedly reduces Voriconazole levels, risking antifungal failure.',
'Indução do CYP3A4/CYP2C19 pela carbamazepina, acelerando a eliminação do voriconazol.',
'CYP3A4/CYP2C19 induction by carbamazepine accelerates voriconazole elimination.',
'Evitar a associação; se inevitável, monitorizar níveis de voriconazol e resposta clínica, ajustando a dose.',
'Avoid the combination; if unavoidable, monitor voriconazole levels and clinical response, adjusting the dose.',
'Níveis de voriconazol, resposta micológica, provas de função hepática.',
'Voriconazole levels, mycological response, liver function tests.',
'Persistência/agravamento da infeção fúngica.',
'Persistent or worsening fungal infection.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A Rifampicina (indutor potente) reduz acentuadamente as concentrações de Voriconazol, com alto risco de falência terapêutica.',
'Rifampin (a potent inducer) markedly reduces Voriconazole levels, with a high risk of therapeutic failure.',
'Indução potente do CYP3A4/CYP2C19 pela rifampicina, acelerando fortemente a eliminação do voriconazol.',
'Potent CYP3A4/CYP2C19 induction by rifampin strongly accelerates voriconazole elimination.',
'Evitar a associação (considerada contraindicada). Usar antifúngico alternativo quando coexiste tuberculose.',
'Avoid the combination (considered contraindicated). Use an alternative antifungal when tuberculosis coexists.',
'Resposta clínica e micológica; considerar monitorização de níveis.',
'Clinical and mycological response; consider level monitoring.',
'Falência do tratamento antifúngico (infeção fúngica invasiva).',
'Antifungal treatment failure (invasive fungal infection).',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   'moderate',
   'O Voriconazol aumenta as concentrações de Sildenafil (inibição do CYP3A4), com risco de hipotensão e efeitos adversos.',
'Voriconazole raises Sildenafil concentrations (CYP3A4 inhibition), with a risk of hypotension and adverse effects.',
'Inibição do CYP3A4 pelo voriconazol, aumentando a exposição do sildenafil.',
'CYP3A4 inhibition by voriconazole increases sildenafil exposure.',
'Limitar a dose de sildenafil durante o tratamento com voriconazol; monitorizar a pressão arterial.',
'Limit the sildenafil dose during voriconazole therapy; monitor blood pressure.',
'Pressão arterial, cefaleia, rubor, palpitações.',
'Blood pressure, headache, flushing, palpitations.',
'Hipotensão, síncope.',
'Hypotension, syncope.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Sildenafil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Sildenafil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'O Voriconazol aumenta os níveis da Atorvastatina, com risco de miopatia e rabdomiólise.',
'Voriconazole raises Atorvastatin levels, with a risk of myopathy and rhabdomyolysis.',
'Inibição do CYP3A4 pelo voriconazol, reduzindo o metabolismo da atorvastatina.',
'CYP3A4 inhibition by voriconazole reduces atorvastatin metabolism.',
'Vigiar sintomas musculares e CK; considerar estatina alternativa ou dose reduzida.',
'Watch for muscle symptoms and CK; consider an alternative statin or reduced dose.',
'Creatina-quinase (CK), mialgias, fraqueza.',
'Creatine kinase (CK), myalgia, weakness.',
'Dor muscular intensa, urina escura.',
'Severe muscle pain, dark urine.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'O Voriconazol pode aumentar as concentrações de Digoxina, com risco de toxicidade digitálica.',
'Voriconazole may raise Digoxin concentrations, with a risk of digitalis toxicity.',
'Possível inibição da glicoproteína-P e do metabolismo, reduzindo a eliminação da digoxina.',
'Possible P-glycoprotein and metabolic inhibition, reducing digoxin elimination.',
'Monitorizar digoxinemia e sinais clínicos; reduzir a dose se necessário.',
'Monitor digoxin levels and clinical signs; reduce the dose if needed.',
'Digoxinemia, ECG, sintomas gastrointestinais e visuais.',
'Digoxin levels, ECG, gastrointestinal and visual symptoms.',
'Náuseas, vómitos, arritmias, xantopsia.',
'Nausea, vomiting, arrhythmias, xanthopsia.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   'moderate',
   'O Voriconazol aumenta os níveis de Prednisolona (inibição do CYP3A4), com risco de efeitos corticosteróides aumentados.',
'Voriconazole raises Prednisolone levels (CYP3A4 inhibition), with a risk of enhanced corticosteroid effects.',
'Inibição do CYP3A4 pelo voriconazol, reduzindo o metabolismo da prednisolona.',
'CYP3A4 inhibition by voriconazole reduces prednisolone metabolism.',
'Vigiar efeitos de corticoterapia; ajustar a dose do corticoide se sinais de sobredosagem.',
'Watch for corticosteroid effects; adjust the steroid dose if overdosage signs occur.',
'Glicemia, pressão arterial, sinais de Cushing iatrogénico.',
'Blood glucose, blood pressure, signs of iatrogenic Cushing.',
'Edema, hiperglicemia, fácies cushingoide.',
'Oedema, hyperglycaemia, Cushingoid facies.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O Voriconazol potencia o efeito anticoagulante da Varfarina, com aumento do INR e risco hemorrágico.',
'Voriconazole potentiates the anticoagulant effect of Warfarin, raising the INR and the bleeding risk.',
'Inibição do CYP2C9 pelo voriconazol, reduzindo o metabolismo da varfarina.',
'CYP2C9 inhibition by voriconazole reduces warfarin metabolism.',
'Monitorizar o INR com frequência; ajustar a dose de varfarina conforme necessário.',
'Monitor the INR frequently; adjust the warfarin dose as needed.',
'INR, sinais de hemorragia.',
'INR, signs of bleeding.',
'Hemorragia inexplicada, melena.',
'Unexplained bleeding, melena.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'glibenclamida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'glibenclamida')),
   'moderate',
   'O Voriconazol potencia o efeito da Glibenclamida, com risco de hipoglicemia.',
'Voriconazole potentiates the effect of Glyburide (Glibenclamide), with a risk of hypoglycaemia.',
'Inibição do CYP2C9 pelo voriconazol, reduzindo o metabolismo da glibenclamida.',
'CYP2C9 inhibition by voriconazole reduces glibenclamide metabolism.',
'Monitorizar a glicemia; pode ser necessário reduzir a dose da sulfonilureia.',
'Monitor blood glucose; a sulfonylurea dose reduction may be needed.',
'Glicemia capilar, sintomas de hipoglicemia.',
'Capillary glucose, hypoglycaemia symptoms.',
'Hipoglicemia grave.',
'Severe hypoglycaemia.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Glibenclamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524eec41-37ee-419a-b7a1-d23e888ae6ab — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Glyburide (Glibenclamide) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524eec41-37ee-419a-b7a1-d23e888ae6ab — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'Associação de Voriconazol e Amiodarona com risco de prolongamento do intervalo QT e arritmias ventriculares.',
'Voriconazole plus Amiodarone carries a risk of QT prolongation and ventricular arrhythmias.',
'Efeito aditivo sobre a repolarização cardíaca.',
'Additive effect on cardiac repolarization.',
'Usar com precaução; monitorizar ECG (QT) e eletrólitos (K+, Mg2+).',
'Use with caution; monitor ECG (QT) and electrolytes (K+, Mg2+).',
'ECG (intervalo QT), eletrólitos, sinais de arritmia.',
'ECG (QT interval), electrolytes, signs of arrhythmia.',
'Síncope, palpitações, torsades de pointes.',
'Syncope, palpitations, torsades de pointes.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'quinina')),
   'moderate',
   'Associação de Voriconazol e Quinina com risco de prolongamento do intervalo QT e arritmias.',
'Voriconazole plus Quinine carries a risk of QT prolongation and arrhythmias.',
'Efeito aditivo sobre a repolarização cardíaca.',
'Additive effect on cardiac repolarization.',
'Usar com precaução; monitorizar ECG (QT) e eletrólitos.',
'Use with caution; monitor ECG (QT) and electrolytes.',
'ECG (intervalo QT), eletrólitos (K+, Mg2+).',
'ECG (QT interval), electrolytes (K+, Mg2+).',
'Síncope, palpitações, torsades de pointes.',
'Syncope, palpitations, torsades de pointes.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cetoconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   'moderate',
   'O Cetoconazol aumenta os níveis de Amlodipina (inibição do CYP3A4), com risco de hipotensão e edema.',
'Ketoconazole raises Amlodipine levels (CYP3A4 inhibition), with a risk of hypotension and oedema.',
'Inibição do CYP3A4 pelo cetoconazol, reduzindo o metabolismo de primeira passagem da amlodipina.',
'CYP3A4 inhibition by ketoconazole reduces first-pass amlodipine metabolism.',
'Vigiar pressão arterial e edema; considerar reduzir a dose de amlodipina se efeitos adversos.',
'Monitor blood pressure and oedema; consider reducing the amlodipine dose if adverse effects occur.',
'Pressão arterial, edema periférico, cefaleia, rubor.',
'Blood pressure, peripheral oedema, headache, flushing.',
'Hipotensão sintomática, edema significativo.',
'Symptomatic hypotension, significant oedema.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; rótulo aprovado Amlodipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58a67272-c4c7-4e2c-85a5-9d39034d12c3 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 ; approved Amlodipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58a67272-c4c7-4e2c-85a5-9d39034d12c3 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'itraconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   'moderate',
   'O Itraconazol aumenta os níveis de Amlodipina (inibição do CYP3A4), com risco de hipotensão e edema.',
'Itraconazole raises Amlodipine levels (CYP3A4 inhibition), with a risk of hypotension and oedema.',
'Inibição do CYP3A4 pelo itraconazol, reduzindo o metabolismo da amlodipina.',
'CYP3A4 inhibition by itraconazole reduces amlodipine metabolism.',
'Vigiar pressão arterial e edema; considerar dose reduzida de amlodipina.',
'Monitor blood pressure and oedema; consider a reduced amlodipine dose.',
'Pressão arterial, edema periférico.',
'Blood pressure, peripheral oedema.',
'Hipotensão sintomática, edema significativo.',
'Symptomatic hypotension, significant oedema.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; rótulo aprovado Amlodipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58a67272-c4c7-4e2c-85a5-9d39034d12c3 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0 ; approved Amlodipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58a67272-c4c7-4e2c-85a5-9d39034d12c3 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
        (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'voriconazol'),
            (SELECT id FROM public.drugs WHERE slug = 'amlodipina')),
   'moderate',
   'O Voriconazol aumenta os níveis de Amlodipina (inibição do CYP3A4), com risco de hipotensão e edema.',
'Voriconazole raises Amlodipine levels (CYP3A4 inhibition), with a risk of hypotension and oedema.',
'Inibição do CYP3A4 pelo voriconazol, reduzindo o metabolismo da amlodipina.',
'CYP3A4 inhibition by voriconazole reduces amlodipine metabolism.',
'Vigiar pressão arterial e edema; considerar dose reduzida de amlodipina.',
'Monitor blood pressure and oedema; consider a reduced amlodipine dose.',
'Pressão arterial, edema periférico.',
'Blood pressure, peripheral oedema.',
'Hipotensão sintomática, edema significativo.',
'Symptomatic hypotension, significant oedema.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; rótulo aprovado Amlodipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58a67272-c4c7-4e2c-85a5-9d39034d12c3 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f6a1a792-141b-42e8-8bd1-884e4408eb8a ; approved Amlodipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58a67272-c4c7-4e2c-85a5-9d39034d12c3 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
   'published', '2026-08-04 12:00:00+00');