-- 057: Família Antibacterianos (diversos) — Aminoglicosídeos, Macrólidos, Quinolonas e Outros
-- Adiciona 11 fármacos e 22 pares de interação, todos de severidade 'moderate'.
-- Total após 056: 82 fármacos e 175 pares.
--
-- Fármacos novos:
--   1.1.7 Aminoglicosídeos (3): gentamicina, amicacina, tobramicina.
--     A estreptomicina já existia (054); a neomicina (uso tópico/oral com absorção
--     sistémica mínima) e a netilmicina (sem rótulo FDA) foram OMITIDAS.
--   1.1.8 Macrólidos (2): azitromicina, eritromicina.
--     A claritromicina já existia (044) — recebe agora o par com warfarina.
--   1.1.10 Quinolonas (2): levofloxacina, moxifloxacina.
--     A ciprofloxacina já existia (044) — recebe agora o par com warfarina.
--     Norfloxacina OMITIDA: sem rótulo aprovado ativo na DailyMed (descontinuada nos
--       EUA, 0 rótulos mono-ingrediente). Ofloxacina OMITIDA: uso predominante tópico.
--   1.1.11 Outros antibacterianos (4): metronidazol, vancomicina, daptomicina, fosfomicina.
--     A linezolida já existia (044) com pares serotoninérgicos (sertralina/fluoxetina/
--       tramadol) — não repetidos. Teicoplanina e ácido fusídico OMITIDOS (sem rótulo
--       FDA). Colistina, rifaximina, tinidazol, lincomicina e clindamicina OMITIDOS por
--       uso hospitalar/tópico restrito e interações limitadas com a base atual.
--
-- Pares (22, todos 'moderate'), agrupados:
--   Aminoglicosídeos × furosemida/vancomicina (6): ototoxicidade/nefrotoxicidade aditiva.
--   Macrólidos (6): CYP3A4/P-gp — eritromicina × atorvastatina (miopatia) e × digoxina;
--     azitromicina × digoxina; INR — eritromicina, azitromicina e claritromicina × warfarina.
--   Quinolonas (7): INR — ciprofloxacina e levofloxacina × warfarina; levofloxacina ×
--     ibuprofeno (AINE → limiar convulsivo) e × amiodarona (QT); catiões — levofloxacina e
--     moxifloxacina × antiácidos; QT — moxifloxacina × cloroquina.
--   Outros (3): metronidazol × warfarina (inibe metabolismo dos anticoagulantes orais);
--     daptomicina × atorvastatina (miopatia/rabdomiólise); fosfomicina × antiácidos (absorção).
--
-- Fontes: rótulos aprovados pela FDA/DailyMed — DailyMed/FDA (NIH/NLM); setIDs validados
-- na API pública v2 (spls.json?drug_name=<INN inglês>) e confirmados n=1 a 2026-08-04.
-- As palavras-chave de cada interação (loop diuretic, vancomycin, warfarin/prothrombin,
-- NSAID/convulsion, antacid, amiodarone/QT, statin/myopathy, metoclopramide) foram
-- confirmadas no texto dos rótulos (drugInfo.cfm). Referência clínica adicional (onde o
-- livro documenta): Prontuário Terapêutico do INFARMED (11.ª ed., 2012), secções 1.1.7,
-- 1.1.8, 1.1.10, 1.1.11 e Anexo 7 (Interacções importantes). Pares da azitromicina com
-- digoxina e warfarina citam apenas o rótulo (o Anexo 7 nomeia eritromicina/claritromicina
-- como os macrólidos de interação mais frequente).
--
-- Decisões editoriais (sem pares artificiais):
--   * moxifloxacina × warfarina NÃO criado: o rótulo (Avelox) documenta ausência de
--     interação farmacodinâmica significativa com a varfarina.
--   * daptomicina × warfarina NÃO criado: a elevação do INR com daptomicina é sobretudo
--     interferência analítica do doseamento (fosfolípidos), não interação farmacodinâmica.
--   * vancomicina × furosemida NÃO criado: o rótulo não documenta a associação; a
--     ototoxicidade aditiva com diuréticos de ansa está sobretudo documentada para
--     os aminoglicosídeos.
--   * vancomicina + aminoglicosídeos: incluída como interação adversa (nefro/ototoxicidade
--     documentada nos rótulos) — ao contrário da associação penicilina + aminoglicosídeo
--     (sinergia intencional, ver 056).
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * idempotente (UNIQUE (drug_a_id, drug_b_id)).
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('gentamicina', 'Gentamicina', 'Gentamicin', 'Aminoglicosídeo bactericida (aeróbios gram-negativos)', 'Bactericidal aminoglycoside (aerobic gram-negative)', ARRAY['Garamicina', 'Gentalin'], 'published', 72),
  ('amicacina', 'Amicacina', 'Amikacin', 'Aminoglicosídeo bactericida (largo espetro, incl. Pseudomonas)', 'Bactericidal aminoglycoside (broad spectrum, incl. Pseudomonas)', ARRAY['Amikin'], 'published', 73),
  ('tobramicina', 'Tobramicina', 'Tobramycin', 'Aminoglicosídeo bactericida (anti-Pseudomonas)', 'Bactericidal aminoglycoside (anti-Pseudomonas)', ARRAY['Tobrex', 'TOBI'], 'published', 74),
  ('azitromicina', 'Azitromicina', 'Azithromycin', 'Macrólido (azálido) bacteriostático', 'Bacteriostatic macrolide (azalide)', ARRAY['Zitromax', 'Azitromax'], 'published', 75),
  ('eritromicina', 'Eritromicina', 'Erythromycin', 'Macrólido bacteriostático', 'Bacteriostatic macrolide', ARRAY['Eritrocina', 'Erythrocin'], 'published', 76),
  ('levofloxacina', 'Levofloxacina', 'Levofloxacin', 'Quinolona (fluorquinolona) de largo espetro', 'Broad-spectrum fluoroquinolone', ARRAY['Tavanic', 'Levaquin'], 'published', 77),
  ('moxifloxacina', 'Moxifloxacina', 'Moxifloxacin', 'Quinolona (fluorquinolona) de largo espetro', 'Broad-spectrum fluoroquinolone', ARRAY['Avalox', 'Avelox'], 'published', 78),
  ('metronidazol', 'Metronidazol', 'Metronidazole', 'Antibacteriano/antiparasitário (nitroimidazol)', 'Antibacterial/antiparasitic (nitroimidazole)', ARRAY['Flagyl'], 'published', 79),
  ('vancomicina', 'Vancomicina', 'Vancomycin', 'Glicopéptido ativo contra gram+ (incl. MRSA)', 'Glycopeptide active against gram+ (incl. MRSA)', ARRAY['Vancocina', 'Vancocin'], 'published', 80),
  ('daptomicina', 'Daptomicina', 'Daptomycin', 'Lipopéptido cíclico (gram+ multirresistentes)', 'Cyclic lipopeptide (multidrug-resistant gram+)', ARRAY['Cubicin'], 'published', 81),
  ('fosfomicina', 'Fosfomicina', 'Fosfomycin trometamol', 'Derivado do ácido fosfónico (infeções urinárias)', 'Phosphonic acid derivative (urinary tract)', ARRAY['Monuril'], 'published', 82);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'gentamicina'),
        (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'gentamicina'),
            (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   'moderate',
   'A associação de Gentamicina com Furosemida aumenta o risco de ototoxicidade e, em menor grau, de nefrotoxicidade, por efeito aditivo sobre o ouvido interno e a função renal.',
'Combining Gentamicin with Furosemide increases the risk of ototoxicity and, to a lesser degree, nephrotoxicity, through an additive effect on the inner ear and the kidneys.',
'A Furosemida (diurético de ansa) e a Gentamicina (aminoglicosídeo) são ambas ototóxicas e nefrotóxicas; a co-administração resulta em toxicidade aditiva sobre a cóclea/vestíbulo e sobre o túbulo renal, sobretudo em doentes com insuficiência renal ou depleção volémica.',
'Both Furosemide (loop diuretic) and Gentamicin (aminoglycoside) are ototoxic and nephrotoxic; together they exert additive toxicity on the cochlea/vestibule and the renal tubule, particularly in patients with renal impairment or volume depletion.',
'Evitar a associação sempre que possível; se inevitável, usar a menor duração possível e ajustar as doses à função renal. Considerar alternativa a um dos fármacos.',
'Avoid the combination whenever possible; if unavoidable, use the shortest course and adjust doses to renal function. Consider an alternative to either drug.',
'Monitorizar a função renal (creatinina/clearance), o débito urinário, os eletrólitos e sinais de ototoxicidade (zumbidos, vertigens, hipoacusia). Vigiar níveis séricos do aminoglicosídeo em terapêutica prolongada.',
'Monitor renal function (creatinine/clearance), urine output, electrolytes and signs of ototoxicity (tinnitus, vertigo, hearing loss). Check aminoglycoside serum levels during prolonged therapy.',
'Zumbidos, vertigens, perda auditiva, oligúria ou elevação rápida da creatinina impõem a suspensão e avaliação imediata.',
'Tinnitus, vertigo, hearing loss, oliguria or a rapid rise in creatinine require prompt discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Gentamicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=441b6232-bb60-40ad-85ec-7c41ba43fd5f ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Gentamicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=441b6232-bb60-40ad-85ec-7c41ba43fd5f ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'amicacina'),
        (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'amicacina'),
            (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   'moderate',
   'A associação de Amicacina com Furosemida aumenta o risco de ototoxicidade e nefrotoxicidade, por efeito aditivo sobre o ouvido interno e o rim.',
'Combining Amikacin with Furosemide increases the risk of ototoxicity and nephrotoxicity through an additive effect on the inner ear and the kidney.',
'A Amicacina (aminoglicosídeo) e a Furosemida (diurético de ansa) são ototóxicas e nefrotóxicas; a co-administração potencia a toxicidade vestibular/coclear e renal, especialmente com insuficiência renal ou desidratação.',
'Amikacin (aminoglycoside) and Furosemide (loop diuretic) are both ototoxic and nephrotoxic; co-administration potentiates vestibular/cochlear and renal toxicity, especially with renal impairment or dehydration.',
'Evitar a associação; se necessária, minimizar a duração, hidratar adequadamente e ajustar a dose de amicacina à função renal.',
'Avoid the combination; if needed, minimize duration, ensure adequate hydration and adjust the amikacin dose to renal function.',
'Monitorizar função renal, débito urinário, eletrólitos e sinais ototóxicos; doseamentos séricos de amicacina em regimes prolongados.',
'Monitor renal function, urine output, electrolytes and ototoxic signs; serum amikacin levels during prolonged regimens.',
'Zumbidos, vertigens, hipoacusia ou deterioração renal exigem suspensão e avaliação imediata.',
'Tinnitus, vertigo, hearing loss or worsening renal function require prompt discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amicacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890 ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Amikacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890 ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tobramicina'),
        (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tobramicina'),
            (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   'moderate',
   'A associação de Tobramicina com Furosemida aumenta o risco de ototoxicidade e nefrotoxicidade, por efeito aditivo sobre o ouvido interno e o rim.',
'Combining Tobramycin with Furosemide increases the risk of ototoxicity and nephrotoxicity through an additive effect on the inner ear and the kidney.',
'A Tobramicina (aminoglicosídeo) e a Furosemida (diurético de ansa) partilham toxicidade coclear/vestibular e renal; a administração conjunta soma os efeitos, com risco acrescido em doentes com função renal comprometida.',
'Tobramycin (aminoglycoside) and Furosemide (loop diuretic) share cochlear/vestibular and renal toxicity; combined use sums these effects, with greater risk when renal function is impaired.',
'Evitar a associação; se inevitável, reduzir a duração, otimizar hidratação e ajustar doses à função renal.',
'Avoid the combination; if unavoidable, shorten the course, optimize hydration and adjust doses to renal function.',
'Monitorizar função renal, diurese, eletrólitos e sinais de ototoxicidade; doseamentos séricos da tobramicina se indicado.',
'Monitor renal function, diuresis, electrolytes and ototoxicity signs; tobramycin serum levels when indicated.',
'Zumbidos, vertigens, hipoacusia ou piora renal impõem suspensão e reavaliação imediata.',
'Tinnitus, vertigo, hearing loss or worsening renal function require prompt discontinuation and reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tobramicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4751a4f-c9c1-60c5-e053-2995a90aeba9 ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Tobramycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4751a4f-c9c1-60c5-e053-2995a90aeba9 ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cdcd001-ab4b-4210-a455-2e17a7bc4972 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'gentamicina'),
        (SELECT id FROM public.drugs WHERE slug = 'vancomicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'gentamicina'),
            (SELECT id FROM public.drugs WHERE slug = 'vancomicina')),
   'moderate',
   'A associação de Gentamicina com Vancomicina aumenta significativamente o risco de nefrotoxicidade e ototoxicidade, com efeito aditivo sobre o rim e o VIII par craniano.',
'Combining Gentamicin with Vancomycin significantly increases the risk of nephrotoxicity and ototoxicity, with an additive effect on the kidney and the eighth cranial nerve.',
'A Vancomicina e os aminoglicosídeos são nefro- e ototóxicos; a co-administração potencia a lesão tubular renal e auditiva, risco bem documentado sobretudo em doentes críticos ou com função renal comprometida.',
'Vancomycin and aminoglycosides are nephrotoxic and ototoxic; co-administration potentiates renal tubular and auditory injury, a well-documented risk particularly in critically ill patients or those with renal impairment.',
'Evitar quando possível; se a associação for clinicamente necessária, minimizar a duração, garantir hidratação e ajustar doses à função renal.',
'Avoid when possible; if clinically necessary, minimize duration, ensure hydration and adjust doses to renal function.',
'Monitorizar estreitamente a função renal, os níveis séricos de vancomicina e da gentamicina, o débito urinário e sinais de ototoxicidade.',
'Closely monitor renal function, vancomycin and gentamicin serum levels, urine output and signs of ototoxicity.',
'Elevação da creatinina, oligúria, zumbidos, vertigens ou hipoacusia exigem reavaliação imediata da terapêutica.',
'Rising creatinine, oliguria, tinnitus, vertigo or hearing loss require immediate reassessment of therapy.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Gentamicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=441b6232-bb60-40ad-85ec-7c41ba43fd5f ; rótulo aprovado Vancomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b01aaa02-8f1d-4b57-96a5-337503428af1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Gentamicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=441b6232-bb60-40ad-85ec-7c41ba43fd5f ; approved Vancomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b01aaa02-8f1d-4b57-96a5-337503428af1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'amicacina'),
        (SELECT id FROM public.drugs WHERE slug = 'vancomicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'amicacina'),
            (SELECT id FROM public.drugs WHERE slug = 'vancomicina')),
   'moderate',
   'A associação de Amicacina com Vancomicina aumenta o risco de nefrotoxicidade e ototoxicidade, com efeito aditivo sobre o rim e o ouvido interno.',
'Combining Amikacin with Vancomycin increases the risk of nephrotoxicity and ototoxicity, with an additive effect on the kidney and the inner ear.',
'A Vancomicina e a Amicacina (aminoglicosídeo) são nefro- e ototóxicas; a co-administração soma a toxicidade renal e coclear/vestibular, sobretudo em doentes com insuficiência renal prévia ou terapêutica prolongada.',
'Vancomycin and Amikacin (aminoglycoside) are nephrotoxic and ototoxic; combined use adds renal and cochlear/vestibular toxicity, particularly with prior renal impairment or prolonged therapy.',
'Evitar a associação; se necessária, usar a menor duração, hidratar e ajustar doses à função renal.',
'Avoid the combination; if needed, use the shortest course, hydrate and adjust doses to renal function.',
'Monitorizar função renal, níveis séricos de ambos os fármacos e sinais de ototoxicidade.',
'Monitor renal function, serum levels of both drugs and signs of ototoxicity.',
'Deterioração renal, oligúria ou sinais auditivos impõem suspensão e avaliação imediata.',
'Worsening renal function, oliguria or auditory signs require prompt discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amicacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890 ; rótulo aprovado Vancomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b01aaa02-8f1d-4b57-96a5-337503428af1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Amikacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890 ; approved Vancomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b01aaa02-8f1d-4b57-96a5-337503428af1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tobramicina'),
        (SELECT id FROM public.drugs WHERE slug = 'vancomicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tobramicina'),
            (SELECT id FROM public.drugs WHERE slug = 'vancomicina')),
   'moderate',
   'A associação de Tobramicina com Vancomicina aumenta o risco de nefrotoxicidade e ototoxicidade, por efeito aditivo sobre o rim e o ouvido interno.',
'Combining Tobramycin with Vancomycin increases the risk of nephrotoxicity and ototoxicity through an additive effect on the kidney and the inner ear.',
'A Vancomicina e a Tobramicina (aminoglicosídeo) têm nefro- e ototoxicidade sobreponíveis; a co-administração potencia a lesão renal e coclear/vestibular, com risco acrescido na insuficiência renal.',
'Vancomycin and Tobramycin (aminoglycoside) have overlapping nephrotoxicity and ototoxicity; co-administration potentiates renal and cochlear/vestibular injury, with added risk in renal impairment.',
'Evitar a associação; se inevitável, minimizar a duração e ajustar doses à função renal.',
'Avoid the combination; if unavoidable, minimize duration and adjust doses to renal function.',
'Monitorizar função renal, níveis séricos e sinais de ototoxicidade durante a associação.',
'Monitor renal function, serum levels and ototoxicity signs during the combination.',
'Elevação da creatinina, oligúria, zumbidos ou hipoacusia exigem reavaliação imediata.',
'Rising creatinine, oliguria, tinnitus or hearing loss require immediate reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tobramicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4751a4f-c9c1-60c5-e053-2995a90aeba9 ; rótulo aprovado Vancomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b01aaa02-8f1d-4b57-96a5-337503428af1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Tobramycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4751a4f-c9c1-60c5-e053-2995a90aeba9 ; approved Vancomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b01aaa02-8f1d-4b57-96a5-337503428af1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'A Eritromicina inibe o CYP3A4 que metaboliza a Atorvastatina, aumentando as suas concentrações e o risco de miopatia e rabdomiólise.',
'Erythromycin inhibits the CYP3A4 that metabolizes Atorvastatin, raising atorvastatin levels and the risk of myopathy and rhabdomyolysis.',
'A Eritromicina é um inibidor do citocromo CYP3A4; a Atorvastatina é substrato deste CYP. A inibição enzimática eleva os níveis da estatina e aumenta o risco de toxicidade muscular, sobretudo com doses altas.',
'Erythromycin is a CYP3A4 inhibitor; Atorvastatin is a substrate of this CYP. Enzymatic inhibition raises statin levels and the risk of muscle toxicity, especially at higher doses.',
'Evitar a associação; se necessária, escolher um macrólido que não iniba o CYP3A4 (ex.: azitromicina, quando adequado) ou suspender temporariamente a estatina.',
'Avoid the combination; if needed, choose a macrolide that does not inhibit CYP3A4 (e.g. azithromycin, when appropriate) or temporarily hold the statin.',
'Vigiar sintomas musculares (dores, fraqueza, cãibras), CPK e coloração escura da urina durante e após a associação.',
'Watch for muscle symptoms (pain, weakness, cramps), CPK and dark urine during and after the combination.',
'Mialgia intensa, fraqueza muscular, urina escura ou CPK muito elevada impõem a suspensão imediata da estatina.',
'Severe myalgia, muscle weakness, dark urine or markedly elevated CPK require immediate statin discontinuation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49b3ca93-43cc-439c-8f5d-e3ea2e87ad2f ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49b3ca93-43cc-439c-8f5d-e3ea2e87ad2f ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'),
        (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'A Eritromicina pode aumentar os níveis plasmáticos de Digoxina, com risco de toxicidade digitálica (arritmias, náuseas, perturbações visuais).',
'Erythromycin may raise plasma Digoxin levels, with a risk of digitalis toxicity (arrhythmias, nausea, visual disturbances).',
'A Eritromicina inibe a glicoproteína-P e o CYP3A4, reduzindo a eliminação da Digoxina e aumentando o seu efeito; distúrbios eletrolíticos (hipocaliemia) podem potenciar a toxicidade digitálica.',
'Erythromycin inhibits P-glycoprotein and CYP3A4, reducing Digoxin elimination and increasing its effect; electrolyte disturbances (hypokalemia) may potentiate digitalis toxicity.',
'Monitorizar os níveis séricos de digoxina e os sinais de toxicidade; pode ser necessário reduzir a dose de digoxina ou usar um macrólido alternativo.',
'Monitor serum digoxin levels and signs of toxicity; a digoxin dose reduction or an alternative macrolide may be needed.',
'Vigiar bradicardia, arritmias, náuseas, anorexia, perturbações visuais e níveis de potássio.',
'Watch for bradycardia, arrhythmias, nausea, anorexia, visual disturbances and potassium levels.',
'Arritmias, bradicardia marcada, náuseas persistentes ou turvação visual impõem avaliação urgente e doseamento de digoxina.',
'Arrhythmias, marked bradycardia, persistent nausea or blurred vision require urgent evaluation and a digoxin level.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49b3ca93-43cc-439c-8f5d-e3ea2e87ad2f ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49b3ca93-43cc-439c-8f5d-e3ea2e87ad2f ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'azitromicina'),
        (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'azitromicina'),
            (SELECT id FROM public.drugs WHERE slug = 'digoxina')),
   'moderate',
   'A Azitromicina pode aumentar os níveis plasmáticos de Digoxina por inibição da glicoproteína-P, com risco de toxicidade digitálica.',
'Azithromycin may raise plasma Digoxin levels by inhibiting P-glycoprotein, with a risk of digitalis toxicity.',
'A Azitromicina inibe a glicoproteína-P, transportador de efluxo que elimina a Digoxina; a inibição eleva a concentração sérica da digoxina e pode desencadear toxicidade digitálica.',
'Azithromycin inhibits P-glycoprotein, the efflux transporter that clears Digoxin; inhibition raises serum digoxin and may trigger digitalis toxicity.',
'Vigiar sinais de toxicidade digitálica e, se possível, doseamentos séricos de digoxina durante a associação.',
'Watch for digitalis toxicity and, when possible, check serum digoxin levels during the combination.',
'Monitorizar náuseas, anorexia, perturbações visuais, bradicardia/arritmias e níveis de digoxina e potássio.',
'Monitor nausea, anorexia, visual disturbances, bradycardia/arrhythmias and digoxin and potassium levels.',
'Bradiarritmias, náuseas persistentes, confusão ou alterações visuais requerem avaliação imediata.',
'Bradyarrhythmias, persistent nausea, confusion or visual changes require immediate evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Eritromicina pode potenciar o efeito anticoagulante da Varfarina, com aumento do INR e do risco hemorrágico.',
'Erythromycin may potentiate the anticoagulant effect of Warfarin, raising the INR and the bleeding risk.',
'A Eritromicina inibe a CYP3A4 e a CYP1A2, reduzindo o metabolismo da Varfarina (sobretudo do isómero ativo); o aumento dos níveis do anticoagulante eleva o INR.',
'Erythromycin inhibits CYP3A4 and CYP1A2, reducing Warfarin metabolism (mainly the active isomer); higher anticoagulant levels raise the INR.',
'Vigiar o INR e ajustar a dose de varfarina durante e após a antibioterapia; informar o doente do risco hemorrágico.',
'Monitor the INR and adjust the warfarin dose during and after antibiotic therapy; inform the patient of the bleeding risk.',
'Monitorizar o INR com maior frequência e sinais de hemorragia (hematomas, gengivorragia, melenas).',
'Monitor the INR more frequently and watch for bleeding signs (bruising, gum bleeding, melena).',
'Hemorragia, INR muito elevado ou sinais de sangramento exigem suspensão/ajuste e avaliação médica urgente.',
'Bleeding, a very high INR or signs of hemorrhage require discontinuation/adjustment and urgent medical evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49b3ca93-43cc-439c-8f5d-e3ea2e87ad2f ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49b3ca93-43cc-439c-8f5d-e3ea2e87ad2f ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'azitromicina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'azitromicina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Azitromicina pode potenciar o efeito anticoagulante da Varfarina, com aumento do INR e risco hemorrágico (efeito variável e por vezes retardado).',
'Azithromycin may potentiate the anticoagulant effect of Warfarin, raising the INR and the bleeding risk (variable and sometimes delayed effect).',
'Mecanismo não totalmente esclarecido; a Azitromicina parece alterar o metabolismo ou a flora intestinal, potenciando o efeito anticoagulante da Varfarina, habitualmente nos primeiros dias ou semanas de associação.',
'Mechanism not fully established; Azithromycin appears to alter metabolism or gut flora, potentiating Warfarin anticoagulation, usually within the first days or weeks of combined use.',
'Vigiar o INR e ajustar a varfarina conforme necessário; vigiar sinais hemorrágicos durante e após a associação.',
'Monitor the INR and adjust warfarin as needed; watch for bleeding signs during and after the combination.',
'Monitorizar o INR com maior frequência e sinais de hemorragia durante a terapêutica.',
'Monitor the INR more frequently and watch for bleeding signs during therapy.',
'Sangramento, INR elevado ou hematomas espontâneos exigem avaliação urgente.',
'Bleeding, an elevated INR or spontaneous bruising require urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'claritromicina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'claritromicina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Claritromicina inibe o CYP3A4 e pode potenciar o efeito anticoagulante da Varfarina, com aumento do INR e do risco hemorrágico.',
'Clarithromycin inhibits CYP3A4 and may potentiate the anticoagulant effect of Warfarin, raising the INR and the bleeding risk.',
'A Claritromicina é um inibidor potente do CYP3A4; reduz o metabolismo da Varfarina, elevando as suas concentrações plasmáticas e o INR.',
'Clarithromycin is a potent CYP3A4 inhibitor; it reduces Warfarin metabolism, raising plasma warfarin levels and the INR.',
'Ajustar a dose de varfarina com base no INR; considerar uma alternativa antibiótica quando possível.',
'Adjust the warfarin dose based on the INR; consider an alternative antibiotic when possible.',
'Vigiar o INR com frequência e sinais de hemorragia durante e após a associação.',
'Monitor the INR frequently and watch for bleeding signs during and after the combination.',
'Hemorragia ativa, INR marcadamente elevado ou hematomas novos exigem intervenção urgente.',
'Active bleeding, a markedly elevated INR or new bruising require urgent intervention.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ciprofloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Ciprofloxacina pode potenciar o efeito anticoagulante da Varfarina, com aumento do INR e do risco hemorrágico.',
'Ciprofloxacin may potentiate the anticoagulant effect of Warfarin, raising the INR and the bleeding risk.',
'A Ciprofloxacina inibe a CYP1A2 e, em menor grau, a CYP3A4, reduzindo o metabolismo da Varfarina; a alteração da flora intestinal produtora de vitamina K contribui também para o efeito anticoagulante aumentado.',
'Ciprofloxacin inhibits CYP1A2 and, to a lesser extent, CYP3A4, reducing Warfarin metabolism; altered vitamin K-producing gut flora also contributes to the enhanced anticoagulant effect.',
'Vigiar o INR e ajustar a dose de varfarina durante a associação; reforçar a vigilância hemorrágica.',
'Monitor the INR and adjust the warfarin dose during the combination; reinforce bleeding surveillance.',
'Monitorizar o INR com maior frequência e sinais de sangramento.',
'Monitor the INR more frequently and watch for bleeding signs.',
'INR elevado, hemorragia ou equimoses espontâneas requerem avaliação imediata.',
'An elevated INR, bleeding or spontaneous bruising require immediate evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57e5832f-9168-1f24-e063-6294a90aaae6 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57e5832f-9168-1f24-e063-6294a90aaae6 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A Levofloxacina pode potenciar o efeito anticoagulante da Varfarina, com aumento do INR e do risco hemorrágico.',
'Levofloxacin may potentiate the anticoagulant effect of Warfarin, raising the INR and the bleeding risk.',
'As quinolonas (incluindo a levofloxacina) podem prolongar o tempo de protrombina em doentes medicados com anticoagulantes orais, por inibição metabólica e possível alteração da flora intestinal.',
'Quinolones (including levofloxacin) may prolong prothrombin time in patients on oral anticoagulants through metabolic inhibition and possible gut flora changes.',
'Monitorizar o INR e ajustar a dose de varfarina; informar o doente do risco hemorrágico.',
'Monitor the INR and adjust the warfarin dose; inform the patient of the bleeding risk.',
'Vigiar o INR e sinais de hemorragia durante e após a terapêutica.',
'Monitor the INR and bleeding signs during and after therapy.',
'Sangramento ou INR elevado exigem avaliação médica urgente.',
'Bleeding or an elevated INR require urgent medical evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   'moderate',
   'A associação de Levofloxacina com Ibuprofeno (AINE) aumenta o risco de convulsões, pela redução do limiar convulsivo.',
'Combining Levofloxacin with Ibuprofen (NSAID) increases the risk of seizures by lowering the seizure threshold.',
'Os AINEs e as quinolonas podem reduzir o limiar convulsivo (interferência central, nomeadamente com o GABA); a co-administração soma o efeito e aumenta o risco de convulsões, sobretudo em doentes com epilepsia ou predisposição.',
'NSAIDs and quinolones may lower the seizure threshold (central interference, notably with GABA); combined use adds these effects and increases the seizure risk, especially in patients with epilepsy or predisposition.',
'Preferir um antibiótico alternativo em doentes com epilepsia/história convulsiva; se a associação for necessária, vigiar muito de perto.',
'Prefer an alternative antibiotic in patients with epilepsy/a history of seizures; if the combination is necessary, monitor very closely.',
'Vigiar sintomas neurológicos (tonturas, tremores, alterações do comportamento) e sinais prodrómicos de convulsão.',
'Watch for neurological symptoms (dizziness, tremor, behavioral changes) and prodromal seizure signs.',
'Qualquer convulsão ou suspeita exige a suspensão e avaliação neurológica urgente.',
'Any seizure or suspicion thereof requires discontinuation and urgent neurological evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14515409-736f-4119-b6a0-cb19ee2e948e — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14515409-736f-4119-b6a0-cb19ee2e948e — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Antiácidos com catiões (alumínio, magnésio, cálcio) e suplementos de ferro/zinco reduzem significativamente a absorção da Levofloxacina, comprometendo a sua eficácia.',
'Antacids with cations (aluminium, magnesium, calcium) and iron/zinc supplements significantly reduce Levofloxacin absorption, compromising its efficacy.',
'Os catiões bi/trivalentes quelam as quinolonas no intestino, formando complexos insolúveis que reduzem a biodisponibilidade da levofloxacina.',
'Bi/trivalent cations chelate quinolones in the gut, forming insoluble complexes that reduce levofloxacin bioavailability.',
'Administrar a levofloxacina pelo menos 2 horas antes ou 2 a 4 horas depois dos antiácidos, suplementos de ferro/zinco ou preparações com cálcio.',
'Give levofloxacin at least 2 hours before or 2–4 hours after antacids, iron/zinc supplements or calcium preparations.',
'Assegurar o espaçamento das tomas e vigiar a resposta clínica ao antibiótico.',
'Ensure the dosing interval is respected and monitor the clinical response to the antibiotic.',
'Falha terapêutica com persistência dos sinais de infeção após toma concomitante.',
'Treatment failure with persistent signs of infection after concurrent dosing.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'levofloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A associação de Levofloxacina com Amiodarona aumenta o risco de prolongamento do intervalo QT e de arritmias ventriculares (ex.: torsades de pointes).',
'Combining Levofloxacin with Amiodarone increases the risk of QT prolongation and ventricular arrhythmias (e.g. torsades de pointes).',
'A Levofloxacina prolonga o intervalo QT no ECG e a Amiodarona é um antiarrítmico da classe III com efeito aditivo; a soma aumenta o risco de arritmias ventriculares graves.',
'Levofloxacin prolongs the ECG QT interval and Amiodarone is a class III antiarrhythmic with an additive effect; together they raise the risk of serious ventricular arrhythmias.',
'Evitar a associação em doentes com fatores de risco (hipocaliemia, QT longo, bradicardia); se inevitável, monitorizar o ECG.',
'Avoid the combination in patients at risk (hypokalemia, long QT, bradycardia); if unavoidable, monitor the ECG.',
'Monitorizar o ECG (intervalo QT), os eletrólitos (potássio/magnésio) e sintomas como palpitações ou síncope.',
'Monitor the ECG (QT interval), electrolytes (potassium/magnesium) and symptoms such as palpitations or syncope.',
'Síncope, palpitações, QT muito prolongado ou arritmia exigem suspensão e avaliação urgente.',
'Syncope, palpitations, a very prolonged QT or arrhythmia require discontinuation and urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5c6c117c-9d91-48f4-9aaa-ee70b99218c2 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'moxifloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'moxifloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Antiácidos com catiões (alumínio, magnésio, cálcio) e preparações com ferro/zinco reduzem significativamente a absorção da Moxifloxacina, comprometendo a sua eficácia.',
'Antacids with cations (aluminium, magnesium, calcium) and iron/zinc preparations significantly reduce Moxifloxacin absorption, compromising its efficacy.',
'Os catiões bi/trivalentes quelam a moxifloxacina no tubo digestivo, formando complexos insolúveis que reduzem a sua biodisponibilidade.',
'Bi/trivalent cations chelate moxifloxacin in the gut, forming insoluble complexes that reduce its bioavailability.',
'Separar as tomas: moxifloxacina pelo menos 4 horas antes ou 8 horas depois dos antiácidos e preparações com catiões.',
'Separate the doses: moxifloxacin at least 4 hours before or 8 hours after antacids and cation-containing preparations.',
'Garantir o espaçamento das tomas e vigiar a resposta clínica.',
'Ensure the dosing interval and monitor the clinical response.',
'Falha terapêutica/persistência da infeção após toma simultânea.',
'Treatment failure/persistent infection after concurrent dosing.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Moxifloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1ed191f5-7df5-488c-bb72-91ac0b618d9a ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Moxifloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1ed191f5-7df5-488c-bb72-91ac0b618d9a ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'moxifloxacina'),
        (SELECT id FROM public.drugs WHERE slug = 'cloroquina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'moxifloxacina'),
            (SELECT id FROM public.drugs WHERE slug = 'cloroquina')),
   'moderate',
   'A associação de Moxifloxacina com Cloroquina pode prolongar o intervalo QT e aumentar o risco de arritmias ventriculares (torsades de pointes).',
'Combining Moxifloxacin with Chloroquine may prolong the QT interval and increase the risk of ventricular arrhythmias (torsades de pointes).',
'A Moxifloxacina prolonga o intervalo QT e a Cloroquina também afeta a repolarização cardíaca; o efeito aditivo aumenta o risco de arritmias ventriculares graves.',
'Moxifloxacin prolongs the QT interval and Chloroquine also affects cardiac repolarization; the additive effect increases the risk of serious ventricular arrhythmias.',
'Evitar a associação quando possível; monitorizar o ECG e corrigir distúrbios eletrolíticos em doentes de risco.',
'Avoid the combination when possible; monitor the ECG and correct electrolyte disturbances in at-risk patients.',
'Vigiar o ECG (QT), potássio/magnésio e sintomas cardíacos; atenção a doentes com QT longo ou cardiopatia.',
'Monitor the ECG (QT), potassium/magnesium and cardiac symptoms; caution in patients with long QT or heart disease.',
'Palpitações, síncope ou QT muito prolongado exigem intervenção urgente.',
'Palpitations, syncope or a very prolonged QT require urgent intervention.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Moxifloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1ed191f5-7df5-488c-bb72-91ac0b618d9a ; rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Moxifloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1ed191f5-7df5-488c-bb72-91ac0b618d9a ; approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'metronidazol'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'metronidazol'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'O Metronidazol inibe o metabolismo da Varfarina, potenciando o seu efeito anticoagulante, com aumento do INR e do risco hemorrágico.',
'Metronidazole inhibits Warfarin metabolism, potentiating its anticoagulant effect, with a raised INR and bleeding risk.',
'O Metronidazol inibe as enzimas hepáticas (CYP2C9/CYP3A4) que metabolizam os anticoagulantes orais, elevando as concentrações da Varfarina e prolongando o tempo de protrombina.',
'Metronidazole inhibits the hepatic enzymes (CYP2C9/CYP3A4) that metabolize oral anticoagulants, raising Warfarin levels and prolonging prothrombin time.',
'Ajustar a dose de varfarina com base no INR e reforçar a vigilância hemorrágica durante e após a associação.',
'Adjust the warfarin dose based on the INR and reinforce bleeding surveillance during and after the combination.',
'Monitorizar o INR com frequência e sinais de hemorragia.',
'Monitor the INR frequently and watch for bleeding signs.',
'Hemorragia ativa, INR elevado ou hematomas novos exigem avaliação urgente.',
'Active bleeding, an elevated INR or new bruising require urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5784eeb-6b99-4e8a-847b-b0d1090ed48a ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5784eeb-6b99-4e8a-847b-b0d1090ed48a ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'daptomicina'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'daptomicina'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'A associação de Daptomicina com Atorvastatina (estatina) aumenta o risco de miopatia e rabdomiólise.',
'Combining Daptomycin with Atorvastatin (statin) increases the risk of myopathy and rhabdomyolysis.',
'A Daptomicina e os inibidores da HMG-CoA redutase (estatinas) podem causar miopatia; o efeito aditivo potencia a lesão muscular e o risco de rabdomiólise.',
'Daptomycin and HMG-CoA reductase inhibitors (statins) can both cause myopathy; the additive effect potentiates muscle injury and the risk of rhabdomyolysis.',
'Considerar suspender a estatina durante a terapêutica com daptomicina ou escolher uma alternativa; vigiar sintomas musculares.',
'Consider holding the statin during daptomycin therapy or choosing an alternative; watch for muscle symptoms.',
'Monitorizar CPK, sintomas de miopatia (dores, fraqueza muscular) e função renal.',
'Monitor CPK, myopathy symptoms (muscle pain, weakness) and renal function.',
'Mialgia intensa, fraqueza, urina escura ou CPK muito elevada impõem suspensão e avaliação imediata.',
'Severe myalgia, weakness, dark urine or markedly elevated CPK require discontinuation and immediate evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Daptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f4ad8613-f25e-4b82-9621-cc5ff9525d3e ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Daptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f4ad8613-f25e-4b82-9621-cc5ff9525d3e ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fosfomicina'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fosfomicina'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Antiácidos e preparações com cálcio reduzem significativamente a absorção da Fosfomicina, comprometendo a sua eficácia na infeção urinária.',
'Antacids and calcium-containing preparations significantly reduce Fosfomycin absorption, compromising its efficacy in urinary tract infection.',
'Antiácidos, sais de cálcio (e também a metoclopramida) interferem com a biodisponibilidade oral da fosfomicina, reduzindo as concentrações alcançadas no trato urinário.',
'Antacids, calcium salts (and also metoclopramide) interfere with oral fosfomycin bioavailability, reducing the concentrations reached in the urinary tract.',
'Separar a toma de fosfomicina dos antiácidos e suplementos com cálcio por várias horas e evitar a toma junto das refeições.',
'Separate fosfomycin dosing from antacids and calcium supplements by several hours and avoid taking it with meals.',
'Vigiar a resposta clínica e a resolução dos sintomas urinários.',
'Monitor the clinical response and resolution of urinary symptoms.',
'Persistência dos sintomas de infeção urinária após toma concomitante.',
'Persistent urinary tract infection symptoms after concurrent dosing.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fosfomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4f206750-8126-99a3-e063-6294a90ade4c ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Fosfomycin trometamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4f206750-8126-99a3-e063-6294a90ade4c ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00');
