-- 058: Antirretrovirais, Antiparasitários, Antiepilépticos e Psicofármacos
-- Adiciona 15 fármacos e 41 pares de interação, todos de severidade 'moderate'.
-- Total após 057: 82 fármacos e 175 pares.
-- Total após 058: 97 fármacos e 216 pares.
--
-- Fármacos novos:
--   1.3.1 Antirretrovirais (6): ritonavir, atazanavir, nevirapina, efavirenz,
--     zidovudina, lamivudina.
--     Tenofovir OMITIDO (rótulo com poucas interações relevantes para a base atual).
--   1.4 Antiparasitários (1): praziquantel.
--     Albendazol OMITIDO: as interações documentadas nos rótulos FDA (dexametasona,
--       cimetidina, praziquantel) não têm parceiros na base atual; a interação com
--       ritonavir é documentada no Prontuário mas não nos rótulos FDA.
--     Mebendazol OMITIDO: o rótulo FDA (incl. EMVERM) não documenta interações com os
--       parceiros da base; a redução por carbamazepina/fenitoína (indução enzimática) é
--       documentada apenas no Prontuário e só tem relevância clínica em terapêuticas
--       prolongadas (não no uso de dose única habitual).
--     Flubendazol, piperazina e pirantel OMITIDOS (interações com fármacos fora da base).
--   2.6 Antiepilépticos e anticonvulsionantes (4): fenitoína, valproato, lamotrigina,
--     fenobarbital.
--     Carbamazepina já existia (044). Etossuximida, primidona e outros OMITIDOS.
--   2.9 Psicofármacos (4): lítio, haloperidol, clozapina, alprazolam.
--     Fluvoxamina OMITIDA (sem rótulo mono-ingrediente validado); diazepam não incluído —
--       representado pela benzodiazepina alprazolam (interações mais documentadas).
--
-- Pares (41, todos 'moderate'), agrupados:
--   Antirretrovirais (14): IP inibidores do CYP3A4 — ritonavir × varfarina (INR),
--     sildenafil (↑), atorvastatina (miopatia), carbamazepina (↑); atazanavir ×
--     omeprazol/antiácidos (↓ absorção por pH) e × varfarina (INR); INNTR indutores —
--     nevirapina × varfarina (↓) e × cetoconazol; efavirenz × claritromicina (↓, QT),
--     × carbamazepina (↓↓) e × warfarina (INR); INTR — zidovudina e lamivudina ×
--     cotrimoxazol (mielotoxicidade aditiva / ↑ lamivudina).
--   Antiparasitários (3): praziquantel × rifampicina (contraindicada, indutor forte) e
--     × efavirenz (indutor moderado) → falência terapêutica; × ritonavir (↑ praziquantel).
--   Antiepilépticos (11): fenitoína × warfarina, × amiodarona, × omeprazol,
--     × isoniazida, × fenobarbital, × valproato; valproato × warfarina e ×
--     lamotrigina (rash grave); lamotrigina × carbamazepina; fenobarbital × warfarina
--     e × valproato.
--   Psicofármacos (13): lítio × AINE (ibuprofeno, diclofenac), × tiazida
--     (hidroclorotiazida), × IECA (enalapril, captopril), × ISRS (fluoxetina — síndrome
--     serotoninérgica) e × metronidazol (↑ lítio); haloperidol × carbamazepina (↓) e ×
--     lítio (neurotoxicidade); clozapina × carbamazepina (agranulocitose) e × fluoxetina
--     (↑); alprazolam × cetoconazol e × claritromicina (↑ benzodiazepina, sedação).
--
-- Decisões editoriais (sem pares artificiais):
--   * fenitoína × carbamazepina NÃO criado: o rótulo FDA da fenitoína refere a
--     carbamazepina apenas no contexto do alelo HLA-B*1502 (risco de SJS/TEN), não como
--     interação farmacocinética documentada.
--   * valproato × AINE (ibuprofeno) NÃO criado: o rótulo do valproato documenta apenas
--     a aspirina, que não está na base; AINE em geral não referido no rótulo.
--   * efavirenz × fenitoína NÃO criado: a indução enzimática do efavirenz está
--     representada através da carbamazepina (mais frequente na prática).
--   * alprazolam × ritonavir NÃO criado: o rótulo do ritonavir mostra variação mínima do
--     alprazolam (↓ ≈ 12%), não clinicamente relevante.
--
-- Fontes: rótulos aprovados pela FDA/DailyMed — DailyMed/FDA (NIH/NLM); setIDs validados
-- na API pública v2 (spls.json?setid=<uuid>, n=1) a 2026-08-04. As palavras-chave de cada
-- interação foram confirmadas no texto dos rótulos (drugInfo.cfm). Referência clínica
-- adicional (documentada nas secções): Prontuário Terapêutico do INFARMED (11.ª ed., 2012),
-- secções 1.3.1 (Antirretrovirais), 1.4 (Antiparasitários), 2.6 (Antiepilépticos) e 2.9
-- (Psicofármacos), e Anexo 7 (Interacções importantes).
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * idempotente (UNIQUE (drug_a_id, drug_b_id)).
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('ritonavir', 'Ritonavir', 'Ritonavir', 'Antirretroviral inibidor da protease (IP) — potente inibidor do CYP3A4/P-gp', 'Antiretroviral protease inhibitor (PI) — potent CYP3A4/P-gp inhibitor', ARRAY['Norvir'], 'published', 83),
  ('atazanavir', 'Atazanavir', 'Atazanavir', 'Antirretroviral inibidor da protease (IP)', 'Antiretroviral protease inhibitor (PI)', ARRAY['Reyataz'], 'published', 84),
  ('nevirapina', 'Nevirapina', 'Nevirapine', 'Antirretroviral inibidor não nucleósido da transcriptase reversa (INNTR), indutor enzimático', 'Antiretroviral non-nucleoside reverse transcriptase inhibitor (NNRTI), enzyme inducer', ARRAY['Viramune'], 'published', 85),
  ('efavirenz', 'Efavirenz', 'Efavirenz', 'Antirretroviral INNTR, indutor enzimático', 'Antiretroviral NNRTI, enzyme inducer', ARRAY['Sustiva', 'Stocrin'], 'published', 86),
  ('zidovudina', 'Zidovudina', 'Zidovudine', 'Antirretroviral inibidor nucleósido da transcriptase reversa (INTR)', 'Antiretroviral nucleoside reverse transcriptase inhibitor (NRTI)', ARRAY['Retrovir', 'AZT'], 'published', 87),
  ('lamivudina', 'Lamivudina', 'Lamivudine', 'Antirretroviral INTR', 'Antiretroviral NRTI', ARRAY['Epivir', '3TC'], 'published', 88),
  ('praziquantel', 'Praziquantel', 'Praziquantel', 'Anti-helmíntico (céstodos e tremátodos)', 'Anthelmintic (cestodes and trematodes)', ARRAY['Biltricide'], 'published', 89),
  ('fenitoina', 'Fenitoína', 'Phenytoin', 'Antiepiléptico (bloqueador de canais de sódio)', 'Antiepileptic (sodium channel blocker)', ARRAY['Dilantin', 'Epanutin'], 'published', 90),
  ('valproato', 'Valproato', 'Valproic acid', 'Antiepiléptico (estabilizador de membrana; inibidor da GABA transaminase)', 'Antiepileptic (membrane stabilizer; GABA transaminase inhibitor)', ARRAY['Depakene', 'Depakote', 'ácido valpróico', 'valproato de sódio'], 'published', 91),
  ('lamotrigina', 'Lamotrigina', 'Lamotrigine', 'Antiepiléptico (bloqueador de canais de sódio)', 'Antiepileptic (sodium channel blocker)', ARRAY['Lamictal'], 'published', 92),
  ('fenobarbital', 'Fenobarbital', 'Phenobarbital', 'Barbitúrico antiepiléptico, indutor enzimático', 'Antiepileptic barbiturate, enzyme inducer', ARRAY['Gardenal', 'Luminal'], 'published', 93),
  ('litio', 'Lítio', 'Lithium', 'Estabilizador do humor (psicofármaco)', 'Mood stabilizer (psychotropic)', ARRAY['Priadel', 'Camcolit', 'carbonato de lítio'], 'published', 94),
  ('haloperidol', 'Haloperidol', 'Haloperidol', 'Antipsicótico (butirofenona)', 'Antipsychotic (butyrophenone)', ARRAY['Haldol'], 'published', 95),
  ('clozapina', 'Clozapina', 'Clozapine', 'Antipsicótico atípico', 'Atypical antipsychotic', ARRAY['Leponex', 'Clozaril'], 'published', 96),
  ('alprazolam', 'Alprazolam', 'Alprazolam', 'Benzodiazepina ansiolítica de curta duração', 'Short-acting anxiolytic benzodiazepine', ARRAY['Xanax'], 'published', 97);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Ritonavir com Varfarina pode alterar de forma imprevisível o efeito anticoagulante da Varfarina, com risco de hemorragia ou de eventos trombóticos.',
'Combining Ritonavir with Warfarin can unpredictably alter the anticoagulant effect of Warfarin, posing a risk of bleeding or thrombotic events.',
'Ritonavir é um potente inibidor do CYP3A4 e da glicoproteína-P; a Varfarina é metabolizada sobretudo pelo CYP2C9. O efeito líquido sobre as concentrações de Varfarina é variável (aumento ou redução) entre doentes, exigindo monitorização.',
'Ritonavir is a potent inhibitor of CYP3A4 and P-glycoprotein; Warfarin is mainly metabolised by CYP2C9. The net effect on warfarin exposure is variable (increase or decrease) between patients, requiring monitoring.',
'Manter monitorização do INR sempre que o Ritonavir for iniciado, suspenso ou ajustado; titular a dose de Varfarina com base no INR. Preferir, se possível, anticoagulantes com farmacocinética mais previsível.',
'Maintain INR monitoring whenever Ritonavir is started, stopped or adjusted; titrate the Warfarin dose based on the INR. When possible, prefer anticoagulants with more predictable pharmacokinetics.',
'INR frequente no início e em cada alteração de dose; vigiar sinais de hemorragia (equimoses espontâneas, hemorragia gengival, hematúria) e sintomas de trombose.',
'Frequent INR at start and at each dose change; watch for bleeding signs (spontaneous bruising, gum bleeding, haematuria) and thrombotic symptoms.',
'INR acima de 3,5 ou hemorragia ativa exigem suspensão ou ajuste imediato do anticoagulante.',
'INR above 3.5 or active bleeding requires immediate discontinuation or adjustment of the anticoagulant.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
        (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
            (SELECT id FROM public.drugs WHERE slug = 'sildenafil')),
   'moderate',
   'A associação de Ritonavir com Sildenafil aumenta de forma marcada as concentrações e os efeitos do Sildenafil, com risco acrescido de hipotensão e priapismo.',
'Combining Ritonavir with Sildenafil markedly increases Sildenafil concentrations and effects, with an increased risk of hypotension and priapism.',
'Ritonavir (inibidor do CYP3A4) reduz drasticamente o metabolismo de primeira passagem do Sildenafil, aumentando muito a sua exposição sistémica.',
'Ritonavir (a CYP3A4 inhibitor) markedly reduces first-pass metabolism of Sildenafil, greatly increasing its systemic exposure.',
'O Sildenafil para disfunção erétil deverá ser iniciado em dose baixa (máx. 25 mg em 48 h) com Ritonavir; para hipertensão pulmonar a combinação é contraindicada em muitos regimes.',
'Sildenafil for erectile dysfunction should be started low (max 25 mg every 48 h) with Ritonavir; for pulmonary hypertension the combination is contraindicated in many regimens.',
'Vigiar tensão arterial, sintomas de hipotensão ortostática e duração anormal de ereção.',
'Monitor blood pressure, orthostatic hypotension and abnormally prolonged erection.',
'Hipotensão sintomática grave ou ereção com duração superior a 4 horas exigem avaliação médica urgente.',
'Severe symptomatic hypotension or an erection lasting more than 4 hours requires urgent medical evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; rótulo aprovado Sildenafil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; approved Sildenafil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
        (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
            (SELECT id FROM public.drugs WHERE slug = 'atorvastatina')),
   'moderate',
   'A associação de Ritonavir com Atorvastatina aumenta as concentrações de Atorvastatina, com risco acrescido de miopatia e rabdomiólise.',
'Combining Ritonavir with Atorvastatin increases Atorvastatin concentrations, with an increased risk of myopathy and rhabdomyolysis.',
'Ritonavir, ao inibir o CYP3A4, reduz o metabolismo da Atorvastatina (substrato do CYP3A4), elevando a sua exposição e o risco de toxicidade muscular.',
'By inhibiting CYP3A4, Ritonavir reduces the metabolism of Atorvastatin (a CYP3A4 substrate), raising its exposure and the risk of muscular toxicity.',
'Limitar a dose de Atorvastatina a 20 mg/dia durante o uso de Ritonavir, ou selecionar uma estatina menos dependente do CYP3A4 (por exemplo pravastatina).',
'Limit Atorvastatin to 20 mg/day during Ritonavir use, or choose a statin less dependent on CYP3A4 (e.g. pravastatin).',
'Vigiar sintomas musculares (mialgias, fraqueza, urina escura) e, se sintomático, doseamento da creatina quinase.',
'Watch for muscle symptoms (myalgia, weakness, dark urine) and, if symptomatic, check creatine kinase.',
'Mialgia intensa, fraqueza proximal ou urina acastanhada impõem suspensão da estatina e avaliação médica.',
'Severe myalgia, proximal weakness or brown urine require stopping the statin and medical evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86841382-4229-4e03-958e-3ac22639efd4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ritonavir'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A associação de Ritonavir com Carbamazepina aumenta as concentrações e a toxicidade da Carbamazepina, exigindo ajuste de dose e monitorização.',
'Combining Ritonavir with Carbamazepine increases Carbamazepine concentrations and toxicity, requiring dose adjustment and monitoring.',
'Ritonavir inibe o CYP3A4, principal via de metabolismo da Carbamazepina, reduzindo a sua clearance e aumentando o risco de efeitos adversos (neurológicos, hematológicos).',
'Ritonavir inhibits CYP3A4, the main metabolic pathway of Carbamazepine, lowering its clearance and increasing the risk of adverse effects (neurological, haematological).',
'Reduzir a dose de Carbamazepina conforme necessário e, se disponível, monitorizar as concentrações séricas; considerar antiepiléptico alternativo.',
'Reduce the Carbamazepine dose as needed and, if available, monitor serum concentrations; consider an alternative antiepileptic.',
'Vigiar sinais de toxicidade da Carbamazepina: diplopia, ataxia, sonolência, náuseas, hiponatremia.',
'Watch for signs of Carbamazepine toxicity: diplopia, ataxia, drowsiness, nausea, hyponatraemia.',
'Sonolência marcada, ataxia ou diplopia requerem suspensão e reavaliação do esquema.',
'Marked drowsiness, ataxia or diplopia require discontinuation and reassessment of the regimen.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'atazanavir'),
        (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'atazanavir'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'A associação de Atazanavir com Omeprazol reduz substancialmente as concentrações de Atazanavir, com risco de falência virológica.',
'Combining Atazanavir with Omeprazole substantially reduces Atazanavir concentrations, with a risk of virological failure.',
'Os inibidores da bomba de protões, como o Omeprazol, elevam o pH gástrico, reduzindo a absorção do Atazanavir e diminuindo a sua exposição.',
'Proton pump inhibitors such as Omeprazole raise gastric pH, reducing Atazanavir absorption and lowering its exposure.',
'Evitar a associação quando possível; se inevitável, preferir antagonistas dos recetores H2 e/ou separar as administrações; não usar IBP com doses baixas de Atazanavir.',
'Avoid the combination when possible; if unavoidable, prefer H2-receptor antagonists and/or separate dosing times; do not use a PPI with low doses of Atazanavir.',
'Monitorizar a carga viral e, se disponível, a litemia/imunidade; reavaliar quando da introdução ou suspensão do Omeprazol.',
'Monitor viral load and, if available, CD4; reassess when Omeprazole is started or stopped.',
'Carga viral detetável ou sinais de falência terapêutica após início do Omeprazol exigem reavaliação do esquema antirretroviral.',
'Detectable viral load or signs of therapeutic failure after starting Omeprazole require reassessment of the antiretroviral regimen.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8 ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8 ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'atazanavir'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'atazanavir'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'A associação de Atazanavir com Antiácidos reduz a absorção do Atazanavir, com risco de diminuição da sua eficácia.',
'Combining Atazanavir with Antacids reduces Atazanavir absorption, with a risk of reduced efficacy.',
'Os antiácidos (hidróxido de alumínio/magnésio) elevam o pH gástrico e podem quelar o Atazanavir, diminuindo a sua biodisponibilidade.',
'Antacids (aluminium/magnesium hydroxide) raise gastric pH and may chelate Atazanavir, lowering its bioavailability.',
'Separar a administração: tomar os antiácidos pelo menos 2 horas antes ou depois do Atazanavir.',
'Separate administration: take antacids at least 2 hours before or after Atazanavir.',
'Monitorizar a resposta virológica ao regime antirretroviral.',
'Monitor the virological response to the antiretroviral regimen.',
'Carga viral detetável após uso regular de antiácidos exige reavaliação do esquema.',
'Detectable viral load with regular antacid use requires reassessment of the regimen.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c72f0736-ee20-45b4-baf0-b80f1e3fa9cb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'atazanavir'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'atazanavir'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Atazanavir com Varfarina pode potenciar o efeito anticoagulante e aumentar o risco de hemorragia grave.',
'Combining Atazanavir with Warfarin may potentiate the anticoagulant effect and increase the risk of serious bleeding.',
'O Atazanavir inibe vias metabólicas da Varfarina; o rótulo alerta para o potencial de hemorragia grave e/ou potencialmente fatal na co-administração.',
'Atazanavir inhibits metabolic pathways of Warfarin; the label warns of the potential for serious and/or potentially fatal bleeding with co-administration.',
'Monitorizar o INR de forma frequente e ajustar a dose de Varfarina durante a co-administração.',
'Monitor the INR frequently and adjust the Warfarin dose during co-administration.',
'Vigiar sinais de hemorragia; doseamentos regulares do INR na introdução e em alterações de dose.',
'Watch for bleeding signs; regular INR testing at start and dose changes.',
'INR elevado com hemorragia ativa exige a suspensão imediata do anticoagulante e avaliação urgente.',
'A high INR with active bleeding requires immediate discontinuation of the anticoagulant and urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'nevirapina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'nevirapina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Nevirapina com Varfarina reduz o efeito anticoagulante da Varfarina, com risco de eventos trombóticos.',
'Combining Nevirapine with Warfarin reduces the anticoagulant effect of Warfarin, posing a risk of thrombotic events.',
'A Nevirapina, como indutora do citocromo P450, aumenta o metabolismo da Varfarina, diminuindo as suas concentrações e o seu efeito.',
'As a cytochrome P450 inducer, Nevirapine increases Warfarin metabolism, lowering its concentrations and its effect.',
'Vigiar o INR e ajustar a dose de Varfarina sempre que a Nevirapina for iniciada, suspensa ou modificada.',
'Monitor the INR and adjust the Warfarin dose whenever Nevirapine is started, stopped or changed.',
'Monitorização do INR na introdução e nas alterações de dose; sinais de tromboembolismo.',
'INR monitoring at start and dose changes; signs of thromboembolism.',
'INR elevado com hemorragia ou sinais de trombose exigem ajuste imediato do anticoagulante.',
'A high INR with bleeding or signs of thrombosis requires immediate anticoagulant adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fbd628db-4076-4fe0-8323-9cc33ae92e42 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fbd628db-4076-4fe0-8323-9cc33ae92e42 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'nevirapina'),
        (SELECT id FROM public.drugs WHERE slug = 'cetoconazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'nevirapina'),
            (SELECT id FROM public.drugs WHERE slug = 'cetoconazol')),
   'moderate',
   'A associação de Nevirapina com Cetoconazol altera as concentrações de ambos: aumenta a Nevirapina e reduz o Cetoconazol.',
'Combining Nevirapine with Ketoconazole alters the concentrations of both: it raises Nevirapine and lowers Ketoconazole.',
'A Nevirapina (indutora enzimática) reduz as concentrações do Cetoconazol; o Cetoconazol (inibidor do CYP3A4) aumenta as concentrações da Nevirapina.',
'Nevirapine (an enzyme inducer) lowers Ketoconazole concentrations; Ketoconazole (a CYP3A4 inhibitor) raises Nevirapine concentrations.',
'Evitar a associação sempre que possível; se necessária, monitorizar a resposta terapêutica e os efeitos adversos de ambos.',
'Avoid the combination whenever possible; if needed, monitor the therapeutic response and adverse effects of both.',
'Monitorizar a função hepática e a eficácia antifúngica; sinais de toxicidade da Nevirapina (erupção cutânea, hepatite).',
'Monitor liver function and antifungal efficacy; signs of Nevirapine toxicity (skin rash, hepatitis).',
'Falha do tratamento antifúngico ou elevação das transaminases exigem reavaliação do esquema.',
'Antifungal failure or raised transaminases require reassessment of the regimen.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fbd628db-4076-4fe0-8323-9cc33ae92e42 ; rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fbd628db-4076-4fe0-8323-9cc33ae92e42 ; approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'efavirenz'),
        (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'efavirenz'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A associação de Efavirenz com Claritromicina reduz as concentrações da Claritromicina, comprometendo a resposta antimicrobiana; existe ainda risco de prolongamento do intervalo QT.',
'Combining Efavirenz with Clarithromycin reduces Clarithromycin concentrations, compromising the antimicrobial response; there is also a risk of QT prolongation.',
'O Efavirenz, indutor do CYP3A4, acelera o metabolismo da Claritromicina (↓ Claritromicina, ↑ do metabolito), reduzindo a sua eficácia.',
'Efavirenz, a CYP3A4 inducer, accelerates Clarithromycin metabolism (↓ Clarithromycin, ↑ of the metabolite), reducing its efficacy.',
'Considerar um antibiótico alternativo (por exemplo azitromicina) para evitar a interação e reduzir o risco de QT prolongado.',
'Consider an alternative antibiotic (e.g. azithromycin) to avoid the interaction and reduce the risk of QT prolongation.',
'Vigiar sinais de infeção não controlada e, se fatores de risco, o intervalo QT.',
'Watch for signs of uncontrolled infection and, with risk factors, the QT interval.',
'Agravamento da infeção durante o tratamento exige revisão do antibiótico.',
'Worsening infection during treatment requires review of the antibiotic.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'efavirenz'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'efavirenz'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A associação de Efavirenz com Carbamazepina reduz as concentrações de ambos os fármacos, com risco de falência no controlo da epilepsia e do VIH.',
'Combining Efavirenz with Carbamazepine reduces the concentrations of both drugs, risking failure in controlling epilepsy and HIV.',
'Efavirenz induz o metabolismo da Carbamazepina e a Carbamazepina induz o metabolismo do Efavirenz, diminuindo mutuamente a exposição.',
'Efavirenz induces Carbamazepine metabolism and Carbamazepine induces Efavirenz metabolism, mutually lowering exposure.',
'Não havendo recomendação posológica fiável, preferir um antiepiléptico alternativo quando possível (por exemplo valproato, levetiracetam).',
'With no reliable dose recommendation, prefer an alternative antiepileptic when possible (e.g. valproate, levetiracetam).',
'Monitorizar a ocorrência de crises convulsivas e a carga viral do VIH.',
'Monitor seizure control and HIV viral load.',
'Agravamento das crises ou carga viral detetável exigem reavaliação do esquema antiepilético/antirretroviral.',
'Worsening seizures or a detectable viral load require reassessment of the antiepileptic/antiretroviral regimen.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'efavirenz'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'efavirenz'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Efavirenz com Varfarina pode aumentar ou diminuir o efeito anticoagulante, com risco de hemorragia ou trombose.',
'Combining Efavirenz with Warfarin may increase or decrease the anticoagulant effect, with a risk of bleeding or thrombosis.',
'O Efavirenz, indutor enzimático, altera o metabolismo da Varfarina; o efeito líquido é variável entre doentes.',
'As an enzyme inducer, Efavirenz alters Warfarin metabolism; the net effect is variable between patients.',
'Monitorizar o INR e ajustar a dose de Varfarina durante a co-administração.',
'Monitor the INR and adjust the Warfarin dose during co-administration.',
'INR frequente na introdução e nas alterações de dose.',
'Frequent INR at start and dose changes.',
'INR elevado ou sinais de hemorragia/trombose exigem ajuste do anticoagulante.',
'A high INR or signs of bleeding/thrombosis require anticoagulant adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'zidovudina'),
        (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'zidovudina'),
            (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   'moderate',
   'A associação de Zidovudina com Cotrimoxazol aumenta o risco de mielotoxicidade (anemia e neutropenia), por efeito aditivo sobre a medula óssea.',
'Combining Zidovudine with Co-trimoxazole increases the risk of myelotoxicity (anaemia and neutropenia) through an additive effect on the bone marrow.',
'Ambos os fármacos podem induzir alterações hematológicas; a co-administração potencia a depressão medular, sobretudo em doentes com imunodeficiência.',
'Both drugs can induce haematological abnormalities; co-administration potentiates marrow suppression, especially in immunodeficient patients.',
'Utilizar Cotrimoxazol e Zidovudina em associação apenas quando estritamente indicado (por exemplo profilaxia de Pneumocystis) e com vigilância hematológica.',
'Use Co-trimoxazole with Zidovudine only when strictly indicated (e.g. Pneumocystis prophylaxis) and with haematological monitoring.',
'Hemograma periódico: hemoglobina, leucócitos e neutrófilos.',
'Periodic blood counts: haemoglobin, white cells and neutrophils.',
'Anemia ou neutropenia significativas exigem reavaliação da associação.',
'Significant anaemia or neutropenia requires reassessing the combination.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Zidovudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6df09f15-b102-431c-adde-d7aeef6f5d84 ; rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Zidovudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6df09f15-b102-431c-adde-d7aeef6f5d84 ; approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'lamivudina'),
        (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'lamivudina'),
            (SELECT id FROM public.drugs WHERE slug = 'cotrimoxazol')),
   'moderate',
   'A associação de Lamivudina com Cotrimoxazol aumenta as concentrações de Lamivudina, com risco de toxicidade.',
'Combining Lamivudine with Co-trimoxazole increases Lamivudine concentrations, with a risk of toxicity.',
'O trimetoprim reduz a secreção tubular renal da Lamivudina (via transporte de catiões orgânicos), aumentando a sua exposição em cerca de 40%.',
'Trimethoprim reduces the renal tubular secretion of Lamivudine (via organic cation transport), increasing its exposure by about 40%.',
'Manter vigilância; ajustar a dose de Lamivudina na insuficiência renal e vigiar a toxicidade em terapêutica prolongada.',
'Maintain surveillance; adjust the Lamivudine dose in renal impairment and watch for toxicity in prolonged therapy.',
'Função renal e sinais de toxicidade da Lamivudina (pancreatite, anemia, neuropatia periférica).',
'Renal function and signs of Lamivudine toxicity (pancreatitis, anaemia, peripheral neuropathy).',
'Sinais de toxicidade da Lamivudina (náuseas, dor abdominal, anemia, neuropatia) impõem reavaliação.',
'Signs of Lamivudine toxicity (nausea, abdominal pain, anaemia, neuropathy) require reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamivudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95 ; rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lamivudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95 ; approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'praziquantel'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'praziquantel'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'A associação de Praziquantel com Rifampicina está contraindicada: a Rifampicina reduz acentuadamente as concentrações de Praziquantel, com risco de falência terapêutica.',
'The combination of Praziquantel with Rifampin is contraindicated: Rifampin markedly reduces Praziquantel concentrations, posing a risk of therapeutic failure.',
'A Rifampicina, forte indutor do CYP3A4, aumenta o metabolismo hepático do Praziquantel, diminuindo de forma significativa a sua exposição.',
'Rifampin, a strong CYP3A4 inducer, increases the hepatic metabolism of Praziquantel, significantly reducing its exposure.',
'Não coadministrar; concluir o tratamento com Rifampicina antes de iniciar o Praziquantel ou escolher tratamento alternativo da parasitose.',
'Do not co-administer; complete Rifampin treatment before starting Praziquantel or choose an alternative antiparasitic treatment.',
'Vigiar a resposta terapêutica à parasitose (por exemplo eliminação de ovos) quando a associação for inevitável.',
'Monitor the parasitological response (e.g. egg clearance) when the combination is unavoidable.',
'Persistência da parasitose apesar do tratamento sugere falência e exige estratégia alternativa.',
'Persisting parasitosis despite treatment suggests failure and requires an alternative strategy.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Praziquantel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34ce1cdd-648e-4f1e-8512-bf3d4cc22eb9 ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Praziquantel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34ce1cdd-648e-4f1e-8512-bf3d4cc22eb9 ; approved Rifampin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'praziquantel'),
        (SELECT id FROM public.drugs WHERE slug = 'efavirenz')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'praziquantel'),
            (SELECT id FROM public.drugs WHERE slug = 'efavirenz')),
   'moderate',
   'A associação de Praziquantel com Efavirenz não é recomendada: reduz de forma significativa as concentrações de Praziquantel, com risco de falência terapêutica.',
'The combination of Praziquantel with Efavirenz is not recommended: it significantly reduces Praziquantel concentrations, with a risk of therapeutic failure.',
'O Efavirenz, indutor moderado do CYP3A4, acelera o metabolismo hepático do Praziquantel, diminuindo a sua exposição.',
'Efavirenz, a moderate CYP3A4 inducer, accelerates the hepatic metabolism of Praziquantel, lowering its exposure.',
'Preferir alternativa terapêutica; se inevitável, monitorizar de perto a resposta à parasitose.',
'Prefer an alternative; if unavoidable, closely monitor the parasitological response.',
'Vigiar a resposta parasitológica e os sintomas da infeção.',
'Monitor the parasitological response and symptoms of the infection.',
'Falência do tratamento exige alternativa terapêutica.',
'Treatment failure requires a therapeutic alternative.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Praziquantel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34ce1cdd-648e-4f1e-8512-bf3d4cc22eb9 ; rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Praziquantel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34ce1cdd-648e-4f1e-8512-bf3d4cc22eb9 ; approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'praziquantel'),
        (SELECT id FROM public.drugs WHERE slug = 'ritonavir')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'praziquantel'),
            (SELECT id FROM public.drugs WHERE slug = 'ritonavir')),
   'moderate',
   'A associação de Praziquantel com Ritonavir aumenta as concentrações de Praziquantel, com risco acrescido de efeitos adversos, sobretudo do sistema nervoso central.',
'Combining Praziquantel with Ritonavir increases Praziquantel concentrations, with an increased risk of adverse effects, especially of the central nervous system.',
'O Ritonavir, inibidor do CYP3A4, reduz o metabolismo do Praziquantel, aumentando a sua exposição e o risco de toxicidade (cefaleias, tonturas, convulsões).',
'As a CYP3A4 inhibitor, Ritonavir reduces Praziquantel metabolism, increasing its exposure and the risk of toxicity (headache, dizziness, seizures).',
'Monitorizar os efeitos adversos e considerar reduzir a dose de Praziquantel se a associação for necessária.',
'Monitor adverse effects and consider reducing the Praziquantel dose if the combination is necessary.',
'Vigiar efeitos adversos do SNC (cefaleias, tonturas, sonolência, convulsões).',
'Watch for CNS adverse effects (headache, dizziness, drowsiness, seizures).',
'Convulsões ou efeitos neurológicos graves exigem suspensão e avaliação.',
'Seizures or severe neurological effects require discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Praziquantel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34ce1cdd-648e-4f1e-8512-bf3d4cc22eb9 ; rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Praziquantel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34ce1cdd-648e-4f1e-8512-bf3d4cc22eb9 ; approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Fenitoína com Varfarina reduz o efeito anticoagulante da Varfarina, com risco de eventos trombóticos.',
'Combining Phenytoin with Warfarin reduces the anticoagulant effect of Warfarin, posing a risk of thrombotic events.',
'A Fenitoína, indutora enzimática, acelera o metabolismo da Varfarina, diminuindo as suas concentrações e o seu efeito anticoagulante.',
'As an enzyme inducer, Phenytoin accelerates Warfarin metabolism, lowering its concentrations and its anticoagulant effect.',
'Monitorizar o INR e ajustar a dose de Varfarina durante a co-administração.',
'Monitor the INR and adjust the Warfarin dose during co-administration.',
'INR frequente na introdução e em alterações de dose; sinais de tromboembolismo.',
'Frequent INR at start and dose changes; signs of thromboembolism.',
'INR sub-otimizado ou eventos trombóticos exigem ajuste da dose de Varfarina.',
'A suboptimal INR or thrombotic events require Warfarin dose adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
        (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
            (SELECT id FROM public.drugs WHERE slug = 'amiodarona')),
   'moderate',
   'A associação de Fenitoína com Amiodarona aumenta as concentrações de Fenitoína e pode provocar sinais de toxicidade.',
'Combining Phenytoin with Amiodarone increases Phenytoin concentrations and may cause signs of toxicity.',
'A Amiodarona inibe o metabolismo da Fenitoína, elevando os seus níveis séricos; a Fenitoína pode, por sua vez, reduzir os níveis de Amiodarona.',
'Amiodarone inhibits Phenytoin metabolism, raising its serum levels; Phenytoin may in turn lower Amiodarone levels.',
'Monitorizar as concentrações séricas de Fenitoína e ajustar a dose; vigiar os efeitos cardíacos da Amiodarona.',
'Monitor serum Phenytoin concentrations and adjust the dose; watch the cardiac effects of Amiodarone.',
'Vigiar sinais de toxicidade da Fenitoína: nistagmo, ataxia, diplopia, sedação.',
'Watch for signs of Phenytoin toxicity: nystagmus, ataxia, diplopia, sedation.',
'Nistagmo, ataxia ou sintomas de toxicidade da Fenitoína exigem doseamento e ajuste.',
'Nystagmus, ataxia or signs of Phenytoin toxicity require level testing and adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
        (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
            (SELECT id FROM public.drugs WHERE slug = 'omeprazol')),
   'moderate',
   'A associação de Fenitoína com Omeprazol pode aumentar as concentrações de Fenitoína e provocar toxicidade.',
'Combining Phenytoin with Omeprazole may increase Phenytoin concentrations and cause toxicity.',
'O Omeprazol é um inibidor do CYP2C19, via envolvida no metabolismo da Fenitoína, podendo elevar os seus níveis.',
'Omeprazole is a CYP2C19 inhibitor, a pathway involved in Phenytoin metabolism, and may raise its levels.',
'Monitorizar os sinais de toxicidade da Fenitoína e os níveis séricos, ajustando a dose se necessário.',
'Monitor signs of Phenytoin toxicity and serum levels, adjusting the dose if needed.',
'Vigiar nistagmo, ataxia e sedação após início do Omeprazol.',
'Watch for nystagmus, ataxia and sedation after starting Omeprazole.',
'Nistagmo, ataxia ou sedação após início do Omeprazol exigem doseamento e ajuste.',
'Nystagmus, ataxia or sedation after starting Omeprazole require level testing and adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=37291cab-e350-d8e3-e063-6294a90a9cb1 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
        (SELECT id FROM public.drugs WHERE slug = 'isoniazida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
            (SELECT id FROM public.drugs WHERE slug = 'isoniazida')),
   'moderate',
   'A associação de Fenitoína com Isoniazida aumenta os níveis séricos de Fenitoína, com risco de toxicidade, sobretudo nos acetiladores lentos.',
'Combining Phenytoin with Isoniazid raises Phenytoin serum levels, with a risk of toxicity, especially in slow acetylators.',
'A Isoniazida inibe o metabolismo da Fenitoína, elevando as suas concentrações; o risco é maior nos doentes que acetilam lentamente a Isoniazida.',
'Isoniazid inhibits Phenytoin metabolism, raising its concentrations; the risk is higher in patients who slowly acetylate Isoniazid.',
'Monitorizar os níveis e os sinais de toxicidade da Fenitoína; considerar reduzir a dose de Fenitoína quando se institui Isoniazida.',
'Monitor Phenytoin levels and signs of toxicity; consider reducing the Phenytoin dose when Isoniazid is started.',
'Nistagmo, ataxia, diplopia ou sedação após início da Isoniazida exigem doseamento e ajuste.',
'Nystagmus, ataxia, diplopia or sedation after starting Isoniazid require level testing and adjustment.',
'Nistagmo, ataxia, diplopia ou sedação exigem doseamento e ajuste da dose.',
'Nystagmus, ataxia, diplopia or sedation require level testing and dose adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
        (SELECT id FROM public.drugs WHERE slug = 'fenobarbital')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
            (SELECT id FROM public.drugs WHERE slug = 'fenobarbital')),
   'moderate',
   'A associação de Fenitoína com Fenobarbital pode aumentar ou diminuir as concentrações de Fenitoína, exigindo monitorização.',
'Combining Phenytoin with Phenobarbital may increase or decrease Phenytoin concentrations, requiring monitoring.',
'O Fenobarbital, indutor enzimático, e a Fenitoína competem e induzem vias metabólicas partilhadas; o efeito líquido é variável (aumento ou redução dos níveis de Fenitoína).',
'Phenobarbital, an enzyme inducer, and Phenytoin compete and induce shared metabolic pathways; the net effect is variable (increase or decrease in Phenytoin levels).',
'Monitorizar os níveis séricos de Fenitoína e, se possível, de Fenobarbital na introdução e em ajustes de dose.',
'Monitor serum Phenytoin and, if possible, Phenobarbital levels at start and dose adjustments.',
'Monitorizar os níveis séricos de Fenitoína e os sinais clínicos de toxicidade.',
'Monitor serum Phenytoin levels and clinical signs of toxicity.',
'Toxicidade ou perda de controlo das crises exigem reavaliação da dose.',
'Toxicity or loss of seizure control require dose reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Fenobarbital: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa09b4f2-edb0-4594-a2d2-b16f7b9686b4 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Phenobarbital label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa09b4f2-edb0-4594-a2d2-b16f7b9686b4 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
        (SELECT id FROM public.drugs WHERE slug = 'valproato')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'),
            (SELECT id FROM public.drugs WHERE slug = 'valproato')),
   'moderate',
   'A associação de Fenitoína com Valproato pode aumentar ou diminuir a fração livre de Fenitoína, com risco de toxicidade ou de perda de eficácia.',
'Combining Phenytoin with Valproate may increase or decrease the free fraction of Phenytoin, with a risk of toxicity or loss of efficacy.',
'O Valproato desloca a Fenitoína das proteínas plasmáticas e inibe o seu metabolismo; o efeito sobre a fração livre é variável. A Fenitoína pode, por sua vez, reduzir os níveis de Valproato.',
'Valproate displaces Phenytoin from plasma proteins and inhibits its metabolism; the effect on the free fraction is variable. Phenytoin may in turn lower Valproate levels.',
'Monitorizar os níveis de Fenitoína (idealmente a fração livre) e os sinais clínicos de toxicidade.',
'Monitor Phenytoin levels (ideally the free fraction) and clinical signs of toxicity.',
'Nistagmo, ataxia, sedação ou agravamento do controlo das crises impõem reavaliação.',
'Nystagmus, ataxia, sedation or worsening seizure control require reassessment.',
'Sinais de toxicidade da Fenitoína ou agravamento das crises impõem avaliação dos níveis.',
'Signs of Phenytoin toxicity or worsening seizures require level assessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Valproato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Valproic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'valproato'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'valproato'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Valproato com Varfarina pode aumentar o efeito anticoagulante e o risco de hemorragia.',
'Combining Valproate with Warfarin may increase the anticoagulant effect and the risk of bleeding.',
'O Valproato desloca a Varfarina das proteínas plasmáticas, podendo aumentar a fração livre e o efeito anticoagulante.',
'Valproate displaces Warfarin from plasma proteins, potentially increasing the free fraction and the anticoagulant effect.',
'Monitorizar o INR e vigiar sinais de hemorragia.',
'Monitor the INR and watch for bleeding signs.',
'Monitorizar o INR e os sinais de hemorragia.',
'Monitor the INR and signs of bleeding.',
'INR elevado ou hemorragia ativa exigem ajuste do anticoagulante.',
'A high INR or active bleeding require anticoagulant adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Valproato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Valproic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'valproato'),
        (SELECT id FROM public.drugs WHERE slug = 'lamotrigina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'valproato'),
            (SELECT id FROM public.drugs WHERE slug = 'lamotrigina')),
   'moderate',
   'A associação de Valproato com Lamotrigina aumenta as concentrações de Lamotrigina, com risco aumentado de reação cutânea grave, incluindo síndrome de Stevens-Johnson.',
'Combining Valproate with Lamotrigine increases Lamotrigine concentrations, with an increased risk of serious skin reactions, including Stevens-Johnson syndrome.',
'O Valproato inibe a glucuronidação da Lamotrigina, dobrando a sua semivida e elevando as suas concentrações; o risco de rash grave é maior nos primeiros meses.',
'Valproate inhibits the glucuronidation of Lamotrigine, doubling its half-life and raising its concentrations; the risk of severe rash is highest in the first months.',
'Reduzir a dose de Lamotrigina (aproximadamente metade) quando coadministrada com Valproato e aumentar a dose de forma muito gradual.',
'Reduce the Lamotrigine dose (approximately half) when given with Valproate and increase it very gradually.',
'Vigiar o aparecimento de erupção cutânea, febre, linfadenopatia ou sintomas gripais nas primeiras 8 semanas.',
'Watch for rash, fever, lymphadenopathy or flu-like symptoms in the first 8 weeks.',
'Qualquer erupção cutânea ou sintomas compatíveis com reação grave exigem suspensão imediata da Lamotrigina e avaliação médica.',
'Any rash or symptoms suggestive of a serious reaction require immediate discontinuation of Lamotrigine and medical evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Valproato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e ; rótulo aprovado Lamotrigina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57f04b9b-06cd-8044-e063-6394a90ae733 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Valproic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e ; approved Lamotrigine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57f04b9b-06cd-8044-e063-6394a90ae733 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'lamotrigina'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'lamotrigina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A associação de Lamotrigina com Carbamazepina reduz as concentrações de Lamotrigina, podendo exigir aumento de dose; a Lamotrigina pode também aumentar a toxicidade do metabolito da Carbamazepina.',
'Combining Lamotrigine with Carbamazepine reduces Lamotrigine concentrations, possibly requiring a higher dose; Lamotrigine may also increase the toxicity of the Carbamazepine metabolite.',
'A Carbamazepina induz a glucuronidação da Lamotrigina, reduzindo os seus níveis; a Lamotrigina pode elevar o carbamazepina-10,11-epóxido, aumentando a toxicidade.',
'Carbamazepine induces the glucuronidation of Lamotrigine, lowering its levels; Lamotrigine may raise carbamazepine-10,11-epoxide, increasing toxicity.',
'Ajustar a dose de Lamotrigina conforme a resposta e, se disponível, os níveis séricos; vigiar toxicidade neurológica.',
'Adjust the Lamotrigine dose according to response and, if available, serum levels; watch for neurological toxicity.',
'Monitorizar o controlo das crises e os sinais de toxicidade neurológica (diplopia, ataxia).',
'Monitor seizure control and signs of neurological toxicity (diplopia, ataxia).',
'Erupção cutânea ou sinais de reação grave exigem suspensão e avaliação.',
'Rash or signs of a serious reaction require discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamotrigina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57f04b9b-06cd-8044-e063-6394a90ae733 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lamotrigine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57f04b9b-06cd-8044-e063-6394a90ae733 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenobarbital'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenobarbital'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'A associação de Fenobarbital com Varfarina reduz o efeito anticoagulante da Varfarina, com risco de eventos trombóticos.',
'Combining Phenobarbital with Warfarin reduces the anticoagulant effect of Warfarin, posing a risk of thrombotic events.',
'O Fenobarbital, indutor enzimático, acelera o metabolismo da Varfarina, diminuindo o seu efeito anticoagulante.',
'As an enzyme inducer, Phenobarbital accelerates Warfarin metabolism, reducing its anticoagulant effect.',
'Monitorizar o INR e ajustar a dose de Varfarina durante a co-administração.',
'Monitor the INR and adjust the Warfarin dose during co-administration.',
'INR frequente na introdução e em alterações de dose.',
'Frequent INR at start and dose changes.',
'INR sub-otimizado ou eventos trombóticos exigem ajuste do anticoagulante.',
'A suboptimal INR or thrombotic events require anticoagulant adjustment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenobarbital: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa09b4f2-edb0-4594-a2d2-b16f7b9686b4 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenobarbital label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa09b4f2-edb0-4594-a2d2-b16f7b9686b4 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenobarbital'),
        (SELECT id FROM public.drugs WHERE slug = 'valproato')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenobarbital'),
            (SELECT id FROM public.drugs WHERE slug = 'valproato')),
   'moderate',
   'A associação de Fenobarbital com Valproato aumenta as concentrações de Fenobarbital, com risco de sedação e toxicidade.',
'Combining Phenobarbital with Valproate increases Phenobarbital concentrations, with a risk of sedation and toxicity.',
'O Valproato inibe o metabolismo do Fenobarbital, elevando os seus níveis séricos e potenciando o seu efeito depressivo.',
'Valproate inhibits Phenobarbital metabolism, raising its serum levels and potentiating its depressant effect.',
'Monitorizar os sinais de sedação e, se disponível, os níveis de Fenobarbital; considerar reduzir a dose.',
'Monitor signs of sedation and, if available, Phenobarbital levels; consider reducing the dose.',
'Monitorizar a sedação e, se disponível, os níveis de Fenobarbital.',
'Monitor sedation and, if available, Phenobarbital levels.',
'Sedação excessiva ou depressão respiratória exigem suspensão e avaliação.',
'Excessive sedation or respiratory depression require discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenobarbital: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa09b4f2-edb0-4594-a2d2-b16f7b9686b4 ; rótulo aprovado Valproato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Phenobarbital label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa09b4f2-edb0-4594-a2d2-b16f7b9686b4 ; approved Valproic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a33f7657-ad0f-43e9-ba48-024746e6d08e — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'ibuprofeno')),
   'moderate',
   'A associação de Lítio com Ibuprofeno aumenta as concentrações séricas de Lítio, com risco de toxicidade.',
'Combining Lithium with Ibuprofen increases serum Lithium concentrations, with a risk of toxicity.',
'Os anti-inflamatórios não esteroides, como o Ibuprofeno, reduzem a excreção renal de Lítio, elevando os seus níveis.',
'Non-steroidal anti-inflammatory drugs such as Ibuprofen reduce the renal excretion of Lithium, raising its levels.',
'Evitar AINEs em doentes medicados com Lítio; se inevitável, usar a menor dose e vigiar os níveis de Lítio.',
'Avoid NSAIDs in patients taking Lithium; if unavoidable, use the lowest dose and monitor Lithium levels.',
'Doseamentos de Lítio após introdução ou ajuste do AINE.',
'Lithium levels after starting or adjusting the NSAID.',
'Confusão, tremor grosseiro, ataxia, vómitos, diarreia ou convulsões sugerem intoxicação por Lítio e exigem avaliação urgente.',
'Confusion, coarse tremor, ataxia, vomiting, diarrhoea or seizures suggest Lithium toxicity and require urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14515409-736f-4119-b6a0-cb19ee2e948e — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14515409-736f-4119-b6a0-cb19ee2e948e — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   'moderate',
   'A associação de Lítio com Diclofenac aumenta as concentrações séricas de Lítio, com risco de toxicidade.',
'Combining Lithium with Diclofenac increases serum Lithium concentrations, with a risk of toxicity.',
'Os AINEs, como o Diclofenac, diminuem a excreção renal de Lítio, elevando os seus níveis séricos.',
'NSAIDs such as Diclofenac decrease the renal excretion of Lithium, raising its serum levels.',
'Evitar a associação; se necessária, usar a menor dose de Diclofenac e monitorizar os níveis de Lítio.',
'Avoid the combination; if needed, use the lowest Diclofenac dose and monitor Lithium levels.',
'Vigiar sinais de toxicidade do Lítio após início do Diclofenac.',
'Watch for signs of Lithium toxicity after starting Diclofenac.',
'Sinais de intoxicação por Lítio (confusão, tremor, vómitos, convulsões) exigem avaliação urgente.',
'Signs of Lithium toxicity (confusion, tremor, vomiting, seizures) require urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Diclofenac: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0931350-28a9-4f00-9254-1d72e31f04c3 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Diclofenac label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0931350-28a9-4f00-9254-1d72e31f04c3 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'hidroclorotiazida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'hidroclorotiazida')),
   'moderate',
   'A associação de Lítio com Hidroclorotiazida aumenta as concentrações séricas de Lítio, com risco de toxicidade.',
'Combining Lithium with Hydrochlorothiazide increases serum Lithium concentrations, with a risk of toxicity.',
'Os diuréticos tiazídicos reduzem a excreção renal de Lítio (aumento de reabsorção tubular), elevando os seus níveis séricos.',
'Thiazide diuretics reduce the renal excretion of Lithium (increased tubular reabsorption), raising its serum levels.',
'Evitar a associação sempre que possível; se necessária, monitorizar de perto os níveis de Lítio e a função renal.',
'Avoid the combination whenever possible; if needed, closely monitor Lithium levels and renal function.',
'Doseamentos frequentes de Lítio e de eletrólitos/creatinina.',
'Frequent Lithium levels and electrolyte/creatinine checks.',
'Sinais de intoxicação por Lítio (confusão, tremor, vómitos, convulsões) exigem suspensão e avaliação urgente.',
'Signs of Lithium toxicity (confusion, tremor, vomiting, seizures) require discontinuation and urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'enalapril')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'enalapril')),
   'moderate',
   'A associação de Lítio com Enalapril aumenta as concentrações séricas de Lítio, com risco de toxicidade.',
'Combining Lithium with Enalapril increases serum Lithium concentrations, with a risk of toxicity.',
'Os inibidores da enzima de conversão da angiotensina, como o Enalapril, reduzem a clearance renal de Lítio, elevando os seus níveis.',
'Angiotensin-converting enzyme inhibitors such as Enalapril reduce the renal clearance of Lithium, raising its levels.',
'Monitorizar os níveis de Lítio e a função renal se a associação for necessária.',
'Monitor Lithium levels and renal function if the combination is needed.',
'Vigiar sinais de toxicidade do Lítio após início do Enalapril.',
'Watch for signs of Lithium toxicity after starting Enalapril.',
'Sinais de toxicidade do Lítio após início do Enalapril exigem doseamento e avaliação.',
'Signs of Lithium toxicity after starting Enalapril require level testing and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Enalapril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b31372f7-cda3-4ead-a481-4cde62e843fd — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Enalapril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b31372f7-cda3-4ead-a481-4cde62e843fd — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'captopril')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'captopril')),
   'moderate',
   'A associação de Lítio com Captopril aumenta as concentrações séricas de Lítio, com risco de toxicidade.',
'Combining Lithium with Captopril increases serum Lithium concentrations, with a risk of toxicity.',
'O Captopril, inibidor da enzima de conversão da angiotensina, reduz a excreção renal de Lítio, elevando os seus níveis.',
'Captopril, an angiotensin-converting enzyme inhibitor, reduces the renal excretion of Lithium, raising its levels.',
'Monitorizar os níveis de Lítio e a função renal durante a co-administração.',
'Monitor Lithium levels and renal function during co-administration.',
'Monitorizar os níveis de Lítio após a introdução do Captopril.',
'Monitor Lithium levels after starting Captopril.',
'Sinais de toxicidade do Lítio exigem suspensão e avaliação.',
'Signs of Lithium toxicity require discontinuation and evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Captopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a43a5373-ded9-4912-8c98-edaec8352836 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Captopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a43a5373-ded9-4912-8c98-edaec8352836 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   'moderate',
   'A associação de Lítio com Fluoxetina aumenta o risco de síndrome serotoninérgica e pode elevar os níveis de Lítio.',
'Combining Lithium with Fluoxetine increases the risk of serotonin syndrome and may raise Lithium levels.',
'O Lítio e a Fluoxetina aumentam a disponibilidade serotoninérgica; os ISRS podem ainda reduzir a excreção de Lítio, elevando os seus níveis.',
'Lithium and Fluoxetine increase serotonergic activity; SSRIs may also reduce Lithium excretion, raising its levels.',
'Usar a associação com prudência, em doses baixas, e monitorizar os níveis de Lítio.',
'Use the combination cautiously, at low doses, and monitor Lithium levels.',
'Vigiar agitação, tremor, hipertermia, hiperreflexia, mioclonias ou diarreia (síndrome serotoninérgica).',
'Watch for agitation, tremor, hyperthermia, hyperreflexia, myoclonus or diarrhoea (serotonin syndrome).',
'Febre, agitação, hiperreflexia ou mioclonias (síndrome serotoninérgica) exigem suspensão e avaliação urgente.',
'Fever, agitation, hyperreflexia or myoclonus (serotonin syndrome) require discontinuation and urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Fluoxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Fluoxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'litio'),
        (SELECT id FROM public.drugs WHERE slug = 'metronidazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'litio'),
            (SELECT id FROM public.drugs WHERE slug = 'metronidazol')),
   'moderate',
   'A associação de Lítio com Metronidazol aumenta as concentrações séricas de Lítio, com risco de toxicidade.',
'Combining Lithium with Metronidazole increases serum Lithium concentrations, with a risk of toxicity.',
'O Metronidazol pode aumentar as concentrações séricas de Lítio; o mecanismo envolve a redução da sua excreção renal.',
'Metronidazole may increase serum Lithium concentrations; the mechanism involves reduced renal excretion.',
'Monitorizar os níveis de Lítio e vigiar sinais de toxicidade durante o uso de Metronidazol.',
'Monitor Lithium levels and watch for signs of toxicity during Metronidazole use.',
'Confusão, tremor ou vómitos após início do Metronidazol exigem doseamento e reavaliação.',
'Confusion, tremor or vomiting after starting Metronidazole require level testing and reassessment.',
'Confusão, tremor ou vómitos após início do Metronidazol exigem doseamento e reavaliação.',
'Confusion, tremor or vomiting after starting Metronidazole require level testing and reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5784eeb-6b99-4e8a-847b-b0d1090ed48a — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 ; approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5784eeb-6b99-4e8a-847b-b0d1090ed48a — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'haloperidol'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'haloperidol'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A associação de Haloperidol com Carbamazepina reduz acentuadamente as concentrações de Haloperidol, com risco de perda do efeito antipsicótico.',
'Combining Haloperidol with Carbamazepine markedly reduces Haloperidol concentrations, risking loss of the antipsychotic effect.',
'A Carbamazepina, indutora enzimática, acelera o metabolismo do Haloperidol, diminuindo os seus níveis séricos.',
'As an enzyme inducer, Carbamazepine accelerates Haloperidol metabolism, lowering its serum levels.',
'Monitorizar a resposta clínica e considerar ajustar a dose de Haloperidol ou usar antipsicótico alternativo.',
'Monitor the clinical response and consider adjusting the Haloperidol dose or using an alternative antipsychotic.',
'Monitorizar a resposta antipsicótica e os sinais de recaída.',
'Monitor the antipsychotic response and signs of relapse.',
'Recaída psicótica durante a associação exige revisão do esquema.',
'Psychotic relapse during the combination requires regimen review.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Haloperidol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e2eed126-cb82-42b1-9b48-9cbeb6873b50 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Haloperidol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e2eed126-cb82-42b1-9b48-9cbeb6873b50 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'haloperidol'),
        (SELECT id FROM public.drugs WHERE slug = 'litio')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'haloperidol'),
            (SELECT id FROM public.drugs WHERE slug = 'litio')),
   'moderate',
   'A associação de Haloperidol com Lítio aumenta o risco de neurotoxicidade e de sintomas extrapiramidais graves.',
'Combining Haloperidol with Lithium increases the risk of neurotoxicity and severe extrapyramidal symptoms.',
'A co-administração de antipsicóticos e Lítio pode produzir encefalopatia, confusão e síndrome extrapiramidal, sobretudo com doses elevadas.',
'Co-administration of antipsychotics and Lithium can produce encephalopathy, confusion and extrapyramidal syndrome, especially at high doses.',
'Usar doses prudentes de ambos e monitorizar o aparecimento de sinais neurológicos.',
'Use cautious doses of both and monitor for the onset of neurological signs.',
'Confusão, rigidez, tremor ou sinais de síndrome neuroléptico maligno exigem suspensão e avaliação urgente.',
'Confusion, rigidity, tremor or signs of neuroleptic malignant syndrome require discontinuation and urgent evaluation.',
'Confusão, rigidez, tremor ou febre exigem suspensão e avaliação urgente.',
'Confusion, rigidity, tremor or fever require discontinuation and urgent evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Haloperidol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e2eed126-cb82-42b1-9b48-9cbeb6873b50 ; rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Haloperidol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e2eed126-cb82-42b1-9b48-9cbeb6873b50 ; approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e6b0a2d-b79c-44d8-b785-5267df9e8f72 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'clozapina'),
        (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'clozapina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbamazepina')),
   'moderate',
   'A associação de Clozapina com Carbamazepina aumenta o risco de agranulocitose, para além de reduzir as concentrações de Clozapina.',
'Combining Clozapine with Carbamazepine increases the risk of agranulocytosis and also lowers Clozapine concentrations.',
'Ambos podem induzir discrasias sanguíneas; além disso, a Carbamazepina induz o metabolismo da Clozapina, reduzindo os seus níveis.',
'Both can induce blood dyscrasias; in addition, Carbamazepine induces Clozapine metabolism, lowering its levels.',
'Evitar a associação sempre que possível; se inevitável, monitorizar rigorosamente o hemograma.',
'Avoid the combination whenever possible; if unavoidable, strictly monitor the blood count.',
'Hemograma regular (leucócitos e neutrófilos) durante o uso conjunto.',
'Regular blood counts (white cells and neutrophils) during combined use.',
'Febre, faringite ou infeção súbita com neutropenia exigem suspensão e avaliação imediata.',
'Fever, sore throat or sudden infection with neutropenia require discontinuation and immediate evaluation.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Clozapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61fe53d5-ed5c-4e45-9189-709d08d386cb ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Clozapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61fe53d5-ed5c-4e45-9189-709d08d386cb ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f3d91cd-a959-4e07-a51b-8a4e9ba9ece2 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'clozapina'),
        (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'clozapina'),
            (SELECT id FROM public.drugs WHERE slug = 'fluoxetina')),
   'moderate',
   'A associação de Clozapina com Fluoxetina aumenta as concentrações de Clozapina, com risco de toxicidade.',
'Combining Clozapine with Fluoxetine increases Clozapine concentrations, with a risk of toxicity.',
'A Fluoxetina, inibidora do CYP2D6/3A4, reduz o metabolismo da Clozapina, elevando os seus níveis séricos.',
'Fluoxetine, a CYP2D6/3A4 inhibitor, reduces Clozapine metabolism, raising its serum levels.',
'Monitorizar os sinais de toxicidade da Clozapina e considerar reduzir a dose; vigiar o hemograma.',
'Monitor signs of Clozapine toxicity and consider reducing the dose; watch the blood count.',
'Sedação excessiva, sialorreia, convulsões ou febre exigem reavaliação.',
'Excessive sedation, drooling, seizures or fever require reassessment.',
'Sedação, convulsões ou sinais de discrasia hematológica exigem reavaliação.',
'Sedation, seizures or signs of haematological dyscrasia require reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Clozapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61fe53d5-ed5c-4e45-9189-709d08d386cb ; rótulo aprovado Fluoxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Clozapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61fe53d5-ed5c-4e45-9189-709d08d386cb ; approved Fluoxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'alprazolam'),
        (SELECT id FROM public.drugs WHERE slug = 'cetoconazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'alprazolam'),
            (SELECT id FROM public.drugs WHERE slug = 'cetoconazol')),
   'moderate',
   'A associação de Alprazolam com Cetoconazol aumenta as concentrações de Alprazolam, com risco de sedação excessiva.',
'Combining Alprazolam with Ketoconazole increases Alprazolam concentrations, with a risk of excessive sedation.',
'O Cetoconazol, inibidor do CYP3A4, reduz o metabolismo do Alprazolam, elevando os seus níveis.',
'Ketoconazole, a CYP3A4 inhibitor, reduces Alprazolam metabolism, raising its levels.',
'Reduzir a dose de Alprazolam ou evitar a associação; monitorizar a sedação.',
'Reduce the Alprazolam dose or avoid the combination; monitor sedation.',
'Sedação marcada, confusão ou depressão respiratória exigem intervenção imediata.',
'Marked sedation, confusion or respiratory depression require immediate intervention.',
'Sedação marcada ou depressão respiratória exigem intervenção imediata.',
'Marked sedation or respiratory depression require immediate intervention.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Alprazolam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0cf8b567-201b-44fa-8fd3-c74023aff44f ; rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Alprazolam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0cf8b567-201b-44fa-8fd3-c74023aff44f ; approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00'),
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'alprazolam'),
        (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'alprazolam'),
            (SELECT id FROM public.drugs WHERE slug = 'claritromicina')),
   'moderate',
   'A associação de Alprazolam com Claritromicina aumenta as concentrações de Alprazolam, com risco de sedação excessiva.',
'Combining Alprazolam with Clarithromycin increases Alprazolam concentrations, with a risk of excessive sedation.',
'A Claritromicina, inibidora do CYP3A4, reduz o metabolismo do Alprazolam, elevando os seus níveis séricos.',
'Clarithromycin, a CYP3A4 inhibitor, reduces Alprazolam metabolism, raising its serum levels.',
'Considerar reduzir a dose de Alprazolam durante o uso de Claritromicina.',
'Consider reducing the Alprazolam dose during Clarithromycin use.',
'Vigiar sedação e depressão do sistema nervoso central.',
'Watch for sedation and central nervous system depression.',
'Sedação marcada ou confusão exigem redução de dose e reavaliação.',
'Marked sedation or confusion require dose reduction and reassessment.',
'DailyMed/FDA (NIH/NLM) — rótulo aprovado Alprazolam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0cf8b567-201b-44fa-8fd3-c74023aff44f ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
'DailyMed/FDA (NIH/NLM) — approved Alprazolam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0cf8b567-201b-44fa-8fd3-c74023aff44f ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)',
'published', '2026-08-04 12:00:00+00');
