-- ================================================================
-- 063_seed_interacoes_cardiovasculares.sql
-- Secções 3.1 (Cardiotónicos), 3.2 (Antiarrítmicos), 3.3 (Simpaticomiméticos),
-- 3.4 Anti-hipertensores: 3.4.1 Diuréticos e 3.4.2 Eixo renina-angiotensina.
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico. Etilefrina sem DailyMed/EMC-UK
-- (não comercializada nos EUA/Reino Unido) — usa Prontuário do INFARMED.
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES

  ('flecainida', 'Flecainida', 'Flecainide', 'Antiarrítmico classe Ic', 'Class Ic antiarrhythmic', ARRAY['Tambocor', 'flecainide acetate'], 'published', 106),
  ('propafenona', 'Propafenona', 'Propafenone', 'Antiarrítmico classe Ic', 'Class Ic antiarrhythmic', ARRAY['Rytmonorm'], 'published', 107),
  ('sotalol', 'Sotalol', 'Sotalol', 'Antiarrítmico classe III (betabloqueador)', 'Class III antiarrhythmic (β-blocker)', ARRAY['Sotalex'], 'published', 108),
  ('etilefrina', 'Etilefrina', 'Etilefrine', 'Simpaticomimético (agonista alfa/beta)', 'Sympathomimetic (α/β agonist)', ARRAY['Effortil'], 'published', 109),
  ('midodrina', 'Midodrina', 'Midodrine', 'Simpaticomimético (agonista alfa-1)', 'Sympathomimetic (α-1 agonist)', ARRAY['Gutron'], 'published', 110),
  ('bumetanida', 'Bumetanida', 'Bumetanide', 'Diurético de ansa', 'Loop diuretic', ARRAY['Burinex'], 'published', 111),
  ('indapamida', 'Indapamida', 'Indapamide', 'Diurético tiazídico', 'Thiazide-like diuretic', ARRAY['Natrilix'], 'published', 112),
  ('acetazolamida', 'Acetazolamida', 'Acetazolamide', 'Inibidor da anidrase carbónica (diurético)', 'Carbonic anhydrase inhibitor (diuretic)', ARRAY['Diamox'], 'published', 113),
  ('ramipril', 'Ramipril', 'Ramipril', 'IECA (modificador do eixo renina-angiotensina)', 'ACE inhibitor (renin-angiotensin axis)', ARRAY['Tritace'], 'published', 114),
  ('valsartana', 'Valsartana', 'Valsartan', 'ARA II (modificador do eixo renina-angiotensina)', 'ARB (renin-angiotensin axis)', ARRAY['Diovan'], 'published', 115);
-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('flecainida', 'amiodarona', 'moderate', 'A amiodarona eleva a flecainida e ambas prolongam o intervalo QT.', 'Amiodarone raises flecainide and both prolong the QT.', 'A amiodarona inibe o metabolismo da flecainida (CYP2D6/CYP3A4) e adiciona prolongamento do QT classe III.', 'Amiodarone inhibits flecainide metabolism (CYP2D6/CYP3A4) and adds class III QT effect.', 'Reduzir a flecainida e monitorizar o ECG; evitar se QT basal longo.', 'Reduce flecainide and monitor the ECG; avoid if baseline QT is long.', 'ECG (QT, QRS), sinais de proarrítmia.', 'ECG (QT, QRS), proarrhythmia signs.', 'Torsades de pointes, síncope, agravamento de insuficiência cardíaca.', 'Torsades de pointes, syncope, worsening heart failure.', 'DailyMed (FDA) — rótulo aprovado Flecainida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=74c1eb2a-a37f-4f33-86bf-51e0d1d0c2bc ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Flecainide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=74c1eb2a-a37f-4f33-86bf-51e0d1d0c2bc ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('flecainida', 'digoxina', 'moderate', 'A flecainida pode aumentar até cerca de 20% as concentrações de digoxina.', 'Flecainide may raise digoxin by up to about 20%.', 'A flecainida reduz discretamente o clearance renal da digoxina, relevante em idosos e insuficiência renal.', 'Flecainide slightly reduces renal clearance of digoxin, chiefly in the elderly and renal impairment.', 'Vigiar níveis de digoxina e sinais de toxicidade digitálica.', 'Monitor digoxin levels and signs of toxicity.', 'Níveis de digoxina, frequência cardíaca, sintomas gastrointestinais.', 'Digoxin levels, heart rate, gastrointestinal symptoms.', 'Náuseas, bradicardia ou arritmias.', 'Nausea, bradycardia or arrhythmia.', 'DailyMed (FDA) — rótulo aprovado Flecainida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=74c1eb2a-a37f-4f33-86bf-51e0d1d0c2bc ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Flecainide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=74c1eb2a-a37f-4f33-86bf-51e0d1d0c2bc ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('propafenona', 'digoxina', 'moderate', 'A propafenona aumenta as concentrações de digoxina, potenciando a toxicidade digitálica.', 'Propafenone raises digoxin levels, potentiating digitalis toxicity.', 'A propafenona reduz o clearance renal da digoxina; efeito maior em doses elevadas.', 'Propafenone reduces digoxin renal clearance; largest effect at high doses.', 'Considerar redução de digoxina e monitorizar níveis/ECG.', 'Consider digoxin reduction and monitor levels/ECG.', 'Níveis de digoxina, bradicardia, sintomas gastrointestinais.', 'Digoxin levels, bradycardia, GI symptoms.', 'Arritmias, náuseas, confusão ou letargia.', 'Arrhythmia, nausea, confusion or lethargy.', 'DailyMed (FDA) — rótulo aprovado Propafenona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2ecd6452-ccc3-493f-9a4a-69f0fbf67a42 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Propafenone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2ecd6452-ccc3-493f-9a4a-69f0fbf67a42 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sotalol', 'digoxina', 'moderate', 'A associação aumenta o risco de bradicardia e disfunção do nó AV.', 'The combination raises the risk of bradycardia and AV-node dysfunction.', 'O sotalol e a digoxina deprimem a condução AV; o sotalol também prolonga o QT.', 'Sotalol and digoxin depress AV conduction; sotalol also prolongs the QT.', 'Monitorizar frequência cardíaca e ECG; ajustar com precaução.', 'Monitor heart rate and ECG; titrate with caution.', 'Frequência cardíaca, ECG (intervalo PR/QT).', 'Heart rate, ECG (PR/QT interval).', 'Bloqueio AV avançado, síncope ou bradicardia grave.', 'High-degree AV block, syncope or severe bradycardia.', 'DailyMed (FDA) — rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sotalol', 'furosemida', 'critical', 'A hipocaliemia induzida pela furosemida aumenta o risco de torsades de pointes com sotalol.', 'Loop-diuretic hypokalaemia raises the risk of torsades de pointes with sotalol.', 'A depleção de potássio e magnésio pela furosemida predispõe a arritmias ventriculares no QT do sotalol.', 'Potassium/magnesium depletion by furosemide predisposes to ventricular arrhythmias on sotalol.', 'Corrigir a hipocalemia antes da associação e monitorizar eletrólitos.', 'Correct the hypokalaemia before combining and monitor electrolytes.', 'Potássio, magnésio, ECG (QT).', 'Potassium, magnesium, ECG (QT).', 'Síncope ou arritmia ventricular (torsades).', 'Syncope or ventricular tachycardia (torsades).', 'DailyMed (FDA) — rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sotalol', 'hidroclorotiazida', 'critical', 'A hipocalemia induzida pela hidroclorotiazida aumenta o risco de torsades com sotalol.', 'Thiazide-induced hypokalaemia raises the risk of torsades with sotalol.', 'O diurético tiazídico depleta potássio e amplia o prolongamento do QT do sotalol.', 'The thiazide depletes potassium and amplifies sotalol''s QT prolongation.', 'Monitorizar potássio e ECG; corrigir hipocalemia antes.', 'Monitor potassium and ECG; correct the hypokalaemia first.', 'Potássio, magnésio, ECG (QT).', 'Potassium, magnesium, ECG (QT).', 'Arritmia ventricular ou síncope.', 'Ventricular arrhythmia or syncope.', 'DailyMed (FDA) — rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 ; rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 ; approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('bumetanida', 'digoxina', 'moderate', 'A hipocalemia da bumetanida aumenta a toxicidade da digoxina.', 'Bumetanide-induced hypokalaemia increases digoxin toxicity.', 'A depleção de potássio pelo diurético de ansa sensibiliza o miocárdio para a digoxina.', 'Loop-diuretic potassium depletion sensitizes the myocardium to digoxin.', 'Monitorizar potássio e sinais de toxicidade digitálica.', 'Monitor potassium and digoxin toxicity signs.', 'Potássio, níveis de digoxina, ECG.', 'Potassium, digoxin levels, ECG.', 'Arritmias ou bradicardia com náuseas.', 'Arrhythmia or bradycardia with nausea.', 'DailyMed (FDA) — rótulo aprovado Bumetanida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4a9229c8-89ba-423e-8e36-f56bc329ed38 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Bumetanide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4a9229c8-89ba-423e-8e36-f56bc329ed38 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('bumetanida', 'espironolactona', 'moderate', 'Associação de diurético de ansa com poupador de potássio: risco de desequilíbrio eletrolítico.', 'Loop plus potassium-sparing diuretic: risk of electrolyte imbalance.', 'Usados juntos para regular o potássio, o balanço depende da função renal.', 'Used together to manage potassium; balance depends on renal function.', 'Monitorizar eletrólitos; evitar na insuficiência renal avançada.', 'Monitor electrolytes; avoid in advanced renal failure.', 'Potássio, creatinina, diurese.', 'Potassium, creatinine, diuresis.', 'Cãibras, arritmias ou hipotensão.', 'Cramps, arrhythmia or hypotension.', 'DailyMed (FDA) — rótulo aprovado Bumetanida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4a9229c8-89ba-423e-8e36-f56bc329ed38 ; rótulo aprovado Espironolactona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57d1c333-c229-54aa-e063-6394a90a84ce — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Bumetanide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4a9229c8-89ba-423e-8e36-f56bc329ed38 ; approved Spironolactone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57d1c333-c229-54aa-e063-6394a90a84ce — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('indapamida', 'digoxina', 'moderate', 'A hipocalemia da indapamida aumenta a toxicidade da digoxina.', 'Indapamide-induced hypokalaemia raises digoxin toxicity.', 'O efeito tiazídico depleta potássio, sensibilizando o miocárdio para a digoxina.', 'The thiazide-like effect depletes potassium, sensitizing the myocardium to digoxin.', 'Monitorizar potássio e sinais de toxicidade digitálica.', 'Monitor potassium and digoxin toxicity signs.', 'Potássio, ECG, sintomas gastrointestinais.', 'Potassium, ECG, GI symptoms.', 'Arritmias ou bradicardia com náuseas.', 'Arrhythmia or bradycardia with nausea.', 'DailyMed (FDA) — rótulo aprovado Indapamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=59cd3331-7afe-432a-8b50-39533fd5f392 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Indapamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=59cd3331-7afe-432a-8b50-39533fd5f392 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('acetazolamida', 'furosemida', 'moderate', 'O acetazolamida somado à furosemida pode aprofundar a acidose e a depleção de potássio.', 'Adding acetazolamide to furosemide may deepen metabolic acidosis and hypokalaemia.', 'Ambos causam perda de bicarbonato/cloro e potássio; risco de acidose metabólica acentuada.', 'Both cause bicarbonate/chloride and potassium loss; risk of marked metabolic acidosis.', 'Monitorizar gasometria e eletrólitos; usar com precaução em idosos.', 'Monitor gases and electrolytes; use cautiously in the elderly.', 'Potássio, cloro, pH.', 'Potassium, chloride, pH.', 'Sinais de acidose (respiração de Kussmaul) ou arritmia.', 'Signs of acidosis (Kussmaul breathing) or arrhythmia.', 'DailyMed (FDA) — rótulo aprovado Acetazolamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=268db224-d5db-457c-86bc-972c9fe07917 ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Acetazolamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=268db224-d5db-457c-86bc-972c9fe07917 ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('midodrina', 'digoxina', 'moderate', 'A midodrina pode potenciar a bradicardia da digoxina.', 'Midodrine may potentiate digoxin bradycardia.', 'A midodrina (agonista alfa-1) reduz reflexamente a frequência; a digoxina também deprime o nó AV.', 'Midodrine (alpha-1 agonist) reflexively lowers heart rate; digoxin also slows AV conduction.', 'Vigiar frequência cardíaca e tensão arterial.', 'Watch heart rate and blood pressure.', 'Frequência cardíaca, TA, sintoma de bradicardia.', 'Heart rate, BP, bradycardia symptoms.', 'Bradicardia sintomática ou hipotensão supina.', 'Symptomatic bradycardia or supine hypertension.', 'DailyMed (FDA) — rótulo aprovado Midodrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=79b712a3-be12-4ea6-ac42-742826685ae5 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Midodrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=79b712a3-be12-4ea6-ac42-742826685ae5 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ramipril', 'espironolactona', 'moderate', 'IECA com poupador de potássio aumenta o risco de hipercaliemia.', 'ACE inhibitor plus potassium-sparing diuretic raises hyperkalaemia risk.', 'O ramipril reduz a aldosterona e a espironolactona retém potássio; o efeito é aditivo.', 'Ramipril lowers aldosterone and spironolactone retains potassium; the effect is additive.', 'Monitorizar potássio e função renal; evitar na insuficiência renal.', 'Monitor potassium and renal function; avoid in renal impairment.', 'Potássio, creatinina.', 'Potassium, creatinine.', 'Hipercaliemia (fraqueza, arritmia).', 'Hyperkalaemia (weakness, arrhythmia).', 'DailyMed (FDA) — rótulo aprovado Ramipril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa ; rótulo aprovado Espironolactona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57d1c333-c229-54aa-e063-6394a90a84ce — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ramipril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa ; approved Spironolactone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57d1c333-c229-54aa-e063-6394a90a84ce — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ramipril', 'furosemida', 'moderate', 'A primeira dose de IECA em doente com diurético ativo pode causar hipotensão.', 'First-dose ACE-i in a patient on an active diuretic may cause hypotension.', 'A depleção volémica pelo diurético acentua a queda pressórica após a primeira dose do IECA.', 'Volume depletion by the diuretic amplifies first-dose ACE-i hypotension.', 'Ajustar o diurético antes de iniciar o IECA e vigiar a tensão arterial.', 'Adjust the diuretic before starting the ACE-i and check blood pressure.', 'Pressão arterial, sintomas de pré-síncope.', 'Blood pressure, presyncope symptoms.', 'Hipotensão sintomática ou síncope na 1.ª toma.', 'Symptomatic hypotension or syncope on first dose.', 'DailyMed (FDA) — rótulo aprovado Ramipril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ramipril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('valsartana', 'espironolactona', 'moderate', 'ARA II com poupador de potássio aumenta o risco de hipercaliemia.', 'ARB with a potassium-sparing diuretic raises hyperkalaemia risk.', 'Ambos poupam potássio; o risco aumenta com função renal diminuída.', 'Both spare potassium; risk rises with reduced renal function.', 'Monitorizar potássio; evitar na insuficiência renal avançada.', 'Monitor potassium; avoid in advanced renal failure.', 'Potássio, ritmo cardíaco.', 'Potassium, heart rhythm.', 'Hipercaliemia ou arritmia.', 'Hyperkalaemia or arrhythmia.', 'DailyMed (FDA) — rótulo aprovado Valsartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a8af3d9-4053-4233-82a7-e8c7bc9e302f ; rótulo aprovado Espironolactona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57d1c333-c229-54aa-e063-6394a90a84ce — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Valsartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a8af3d9-4053-4233-82a7-e8c7bc9e302f ; approved Spironolactone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57d1c333-c229-54aa-e063-6394a90a84ce — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('valsartana', 'captopril', 'moderate', 'Duplo bloqueio do eixo renina-angiotensina (IECA+ARA) com risco de hipotensão, hipercaliemia e declínio renal.', 'Dual RAAS blockade (ACE+ARB) with risk of hypotension, hyperkalaemia and renal decline.', 'O bloqueio reforçado do eixo remove a compensação renal e eleva o potássio.', 'Enhanced RAAS blockade removes renal compensation and raises potassium.', 'Evitar a associação rotineira; se usada, monitorizar potássio, creatinina e TA.', 'Avoid routinely; if used, monitor potassium, creatinine and BP.', 'Potássio, creatinina, tensão arterial.', 'Potassium, creatinine, blood pressure.', 'Hipotensão ou hipercaliemia.', 'Hypotension or hyperkalaemia.', 'DailyMed (FDA) — rótulo aprovado Valsartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a8af3d9-4053-4233-82a7-e8c7bc9e302f ; rótulo aprovado Captopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=563737c5-4d63-4957-8022-e3bc3112dfac — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Valsartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a8af3d9-4053-4233-82a7-e8c7bc9e302f ; approved Captopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=563737c5-4d63-4957-8022-e3bc3112dfac — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ramipril', 'valsartana', 'moderate', 'Duplo bloqueio do eixo renina-angiotensina (IECA+ARA) com risco de hipotensão e lesão renal.', 'Dual RAAS blockade (ACE+ARB) with risk of hypotension and renal injury.', 'O bloqueio reforçado reduz a pressão intraglomerular; pode agravar a função renal e a hipercaliemia.', 'Enhanced blockade lowers intraglomerular pressure, impairing renal function and raising potassium.', 'Evitar a associação sem benefício comprovado; monitorizar a função renal.', 'Avoid unless proven benefit; monitor renal function.', 'Creatinina, diurese, potássio.', 'Creatinine, diuresis, potassium.', 'Hipotensão ou piora renal.', 'Hypotension or renal worsening.', 'DailyMed (FDA) — rótulo aprovado Ramipril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa ; rótulo aprovado Valsartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a8af3d9-4053-4233-82a7-e8c7bc9e302f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ramipril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa ; approved Valsartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a8af3d9-4053-4233-82a7-e8c7bc9e302f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)') ) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('flecainida', 'sumo_toranja', 'Sumo de toranja', 'Grapefruit juice', 'moderate', 'O sumo de toranja inibe a glicoproteína-P e o CYP3A4 intestinais, podendo reduzir a depuração da flecainida e aumentar a sua exposição.', 'Grapefruit juice inhibits intestinal P-glycoprotein and CYP3A4, which may reduce flecainide clearance and increase its exposure.', 'Evitar o consumo regular de sumo de toranja durante o tratamento com flecainida.', 'Avoid regular grapefruit juice intake during flecainide treatment.', 'EMC-UK (MHRA) — SmPC aprovada Flecainida: https://www.medicines.org.uk/emc/product/3086/smpc', 'EMC-UK (MHRA) — approved Flecainide SmPC: https://www.medicines.org.uk/emc/product/3086/smpc', 1),
  ('propafenona', 'sumo_toranja', 'Sumo de toranja', 'Grapefruit juice', 'moderate', 'O sumo de toranja aumenta a biodisponibilidade da propafenona por inibição do CYP3A4 e da glicoproteína-P intestinais, elevando o risco de efeitos adversos cardíacos.', 'Grapefruit juice increases propafenone bioavailability by inhibiting intestinal CYP3A4 and P-glycoprotein, raising the risk of cardiac adverse effects.', 'Evitar o sumo de toranja durante o tratamento; o risco é maior em doentes com baixa capacidade metabólica do CYP2D6.', 'Avoid grapefruit juice during treatment; the risk is greater in poor CYP2D6 metabolisers.', 'EMC-UK (MHRA) — SmPC aprovada Propafenona: https://www.medicines.org.uk/emc/product/1733/smpc', 'EMC-UK (MHRA) — approved Propafenone SmPC: https://www.medicines.org.uk/emc/product/1733/smpc', 1),
  ('bumetanida', 'alcacuz', 'Alcaçuz (glicirrizina)', 'Liquorice (glycyrrhizin)', 'moderate', 'O alcaçuz provoca pseudoaldosteronismo com retenção de sódio e depleção de potássio, que antagoniza o efeito diurético e aumenta o risco de hipocaliemia.', 'Liquorice causes pseudoaldosteronism with sodium retention and potassium depletion, opposing the diuretic effect and increasing the risk of hypokalaemia.', 'Evitar o consumo excessivo de alcaçuz durante o tratamento com bumetanida.', 'Avoid excessive liquorice intake during bumetanide treatment.', 'EMC-UK (MHRA) — SmPC aprovada Bumetanida: https://www.medicines.org.uk/emc/product/13372/smpc', 'EMC-UK (MHRA) — approved Bumetanide SmPC: https://www.medicines.org.uk/emc/product/13372/smpc', 1),
  ('indapamida', 'alcacuz', 'Alcaçuz (glicirrizina)', 'Liquorice (glycyrrhizin)', 'moderate', 'O alcaçuz promove pseudoaldosteronismo com hipocaliemia e hipomagnesiemia, somando-se ao efeito da indapamida e aumentando o risco de arritmias.', 'Liquorice promotes pseudoaldosteronism with hypokalaemia and hypomagnesaemia, adding to the indapamide effect and increasing the risk of arrhythmias.', 'Evitar o consumo excessivo de alcaçuz; vigiar o potássio sérico.', 'Avoid excessive liquorice intake; monitor serum potassium.', 'EMC-UK (MHRA) — SmPC aprovada Indapamida: https://www.medicines.org.uk/emc/product/6223/smpc', 'EMC-UK (MHRA) — approved Indapamide SmPC: https://www.medicines.org.uk/emc/product/6223/smpc', 1),
  ('ramipril', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate', 'O ramipril reduz a excreção de potássio; alimentos ricos em potássio ou substitutos de sal com potássio podem causar hipercaliemia, sobretudo com função renal diminuída.', 'Ramipril reduces potassium excretion; potassium-rich foods or potassium-containing salt substitutes may cause hyperkalaemia, especially with reduced renal function.', 'Evitar substitutos de sal com potássio; a ingestão alimentar habitual de potássio não é problemática.', 'Avoid potassium-containing salt substitutes; usual dietary potassium intake is not problematic.', 'EMC-UK (MHRA) — SmPC aprovada Ramipril: https://www.medicines.org.uk/emc/product/8067/smpc', 'EMC-UK (MHRA) — approved Ramipril SmPC: https://www.medicines.org.uk/emc/product/8067/smpc', 1),
  ('valsartana', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate', 'Tal como os IECA, os ARA II podem elevar o potássio sérico; a ingestão elevada de potássio ou substitutos de sal aumentam o risco de hipercaliemia.', 'As with ACE inhibitors, ARBs can raise serum potassium; high potassium intake or salt substitutes increase the risk of hyperkalaemia.', 'Evitar suplementos e substitutos de sal com potássio sem supervisão; vigiar o potássio em doentes de risco.', 'Avoid potassium supplements and salt substitutes without supervision; monitor potassium in at-risk patients.', 'EMC-UK (MHRA) — SmPC aprovada Valsartana: https://www.medicines.org.uk/emc/product/14212/smpc', 'EMC-UK (MHRA) — approved Valsartan SmPC: https://www.medicines.org.uk/emc/product/14212/smpc', 1),
  ('digoxina', 'fibra_alimentar', 'Fibras alimentares (farelo)', 'Dietary fibre (bran)', 'minor', 'As fibras alimentares, como o farelo de trigo, podem adsorver a digoxina e reduzir a sua absorção oral.', 'Dietary fibre, such as wheat bran, may adsorb digoxin and reduce its oral absorption.', 'Separar a toma de digoxina pelo menos 2 horas das refeições ricas em fibras.', 'Separate digoxin intake from high-fibre meals by at least 2 hours.', 'EMC-UK (MHRA) — SmPC aprovada Digoxina: https://www.medicines.org.uk/emc/product/5463/smpc', 'EMC-UK (MHRA) — approved Digoxin SmPC: https://www.medicines.org.uk/emc/product/5463/smpc', 1),
  ('furosemida', 'alcacuz', 'Alcaçuz (glicirrizina)', 'Liquorice (glycyrrhizin)', 'moderate', 'O alcaçuz causa depleção de potássio e retenção de sódio, que se somam ao efeito da furosemida, aumentando o risco de hipocaliemia.', 'Liquorice causes potassium depletion and sodium retention, adding to the furosemide effect and increasing the risk of hypokalaemia.', 'Evitar o consumo excessivo de alcaçuz durante o tratamento.', 'Avoid excessive liquorice intake during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Furosemida: https://www.medicines.org.uk/emc/product/2380/smpc', 'EMC-UK (MHRA) — approved Furosemide SmPC: https://www.medicines.org.uk/emc/product/2380/smpc', 1),
  ('hidroclorotiazida', 'alcacuz', 'Alcaçuz (glicirrizina)', 'Liquorice (glycyrrhizin)', 'moderate', 'O alcaçuz provoca pseudoaldosteronismo com hipocaliemia, que se soma à depleção de potássio induzida pela tiazida.', 'Liquorice causes pseudoaldosteronism with hypokalaemia, adding to thiazide-induced potassium depletion.', 'Evitar o consumo excessivo de alcaçuz; vigiar o potássio sérico.', 'Avoid excessive liquorice intake; monitor serum potassium.', 'EMC-UK (MHRA) — SmPC aprovada Hidroclorotiazida: https://www.medicines.org.uk/emc/product/11721/smpc', 'EMC-UK (MHRA) — approved Hydrochlorothiazide SmPC: https://www.medicines.org.uk/emc/product/11721/smpc', 1),
  ('hidroclorotiazida', 'suplementos_calcio', 'Suplementos de cálcio', 'Calcium supplements', 'moderate', 'As tiazidas reduzem a excreção renal de cálcio; suplementos de cálcio em doses elevadas podem causar hipercalcemia.', 'Thiazides reduce renal calcium excretion; high-dose calcium supplements may cause hypercalcaemia.', 'Monitorizar o cálcio sérico em doentes a tomar suplementos de cálcio em dose elevada.', 'Monitor serum calcium in patients taking high-dose calcium supplements.', 'EMC-UK (MHRA) — SmPC aprovada Hidroclorotiazida: https://www.medicines.org.uk/emc/product/11721/smpc', 'EMC-UK (MHRA) — approved Hydrochlorothiazide SmPC: https://www.medicines.org.uk/emc/product/11721/smpc', 2),
  ('espironolactona', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate', 'A espironolactona retém potássio; a ingestão elevada de potássio na dieta ou substitutos de sal aumentam o risco de hipercaliemia.', 'Spironolactone retains potassium; high dietary potassium or salt substitutes increase the risk of hyperkalaemia.', 'Evitar substitutos de sal com potássio e consumo excessivo de alimentos ricos em potássio.', 'Avoid potassium-containing salt substitutes and excessive intake of potassium-rich foods.', 'EMC-UK (MHRA) — SmPC aprovada Espironolactona: https://www.medicines.org.uk/emc/product/2898/smpc', 'EMC-UK (MHRA) — approved Spironolactone SmPC: https://www.medicines.org.uk/emc/product/2898/smpc', 1),
  ('captopril', 'alimentos_refeicao', 'Alimentos (refeições)', 'Food (meals)', 'minor', 'A presença de alimentos reduz a absorção do captopril em cerca de 30-40%, diminuindo a sua biodisponibilidade.', 'Food reduces captopril absorption by about 30-40%, lowering its bioavailability.', 'Tomar o captopril uma hora antes das refeições.', 'Take captopril one hour before meals.', 'EMC-UK (MHRA) — SmPC aprovada Captopril: https://www.medicines.org.uk/emc/product/5250/smpc', 'EMC-UK (MHRA) — approved Captopril SmPC: https://www.medicines.org.uk/emc/product/5250/smpc', 1),
  ('enalapril', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate', 'A ingestão elevada de potássio ou substitutos de sal podem aumentar o risco de hipercaliemia em doentes tratados com enalapril.', 'High potassium intake or salt substitutes may increase the risk of hyperkalaemia in patients treated with enalapril.', 'Evitar substitutos de sal com potássio; vigiar o potássio em doentes de risco.', 'Avoid potassium-containing salt substitutes; monitor potassium in at-risk patients.', 'EMC-UK (MHRA) — SmPC aprovada Enalapril: https://www.medicines.org.uk/emc/product/15458/smpc', 'EMC-UK (MHRA) — approved Enalapril SmPC: https://www.medicines.org.uk/emc/product/15458/smpc', 1),
  ('losartano', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate', 'O losartano pode elevar o potássio sérico; suplementos de potássio ou substitutos de sal podem causar hipercaliemia.', 'Losartan may raise serum potassium; potassium supplements or salt substitutes may cause hyperkalaemia.', 'Evitar suplementos e substitutos de sal com potássio sem supervisão; vigiar o potássio em doentes de risco.', 'Avoid potassium supplements and salt substitutes without supervision; monitor potassium in at-risk patients.', 'EMC-UK (MHRA) — SmPC aprovada Losartano: https://www.medicines.org.uk/emc/product/7783/smpc', 'EMC-UK (MHRA) — approved Losartan SmPC: https://www.medicines.org.uk/emc/product/7783/smpc', 1)) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('flecainida', 'cardiopatia_estrutural', 'Cardiopatia estrutural (disfunção ventricular)', 'Structural heart disease (ventricular dysfunction)', 'contraindication', 'critical', 'A flecainida é contraindicada em doentes com cardiopatia estrutural ou disfunção ventricular, pelo risco de proarrítmia e morte súbita.', 'Flecainide is contraindicated in structural heart disease or ventricular dysfunction because of the risk of proarrhythmia and sudden death.', 'Não usar em doentes com doença cardíaca estrutural, enfarte do miocárdio prévio ou disfunção ventricular esquerda.', 'Do not use in structural heart disease, prior myocardial infarction or left ventricular dysfunction.', 'EMC-UK (MHRA) — SmPC aprovada Flecainida: https://www.medicines.org.uk/emc/product/3086/smpc', 'EMC-UK (MHRA) — approved Flecainide SmPC: https://www.medicines.org.uk/emc/product/3086/smpc', 1),
  ('propafenona', 'cardiopatia_estrutural', 'Cardiopatia estrutural (disfunção ventricular)', 'Structural heart disease (ventricular dysfunction)', 'contraindication', 'critical', 'A propafenona está contraindicada em doentes com cardiopatia estrutural ou disfunção ventricular, pelo risco de proarrítmia.', 'Propafenone is contraindicated in structural heart disease or ventricular dysfunction because of the risk of proarrhythmia.', 'Não usar em doentes com doença cardíaca estrutural ou disfunção ventricular esquerda.', 'Do not use in structural heart disease or left ventricular dysfunction.', 'EMC-UK (MHRA) — SmPC aprovada Propafenona: https://www.medicines.org.uk/emc/product/1733/smpc', 'EMC-UK (MHRA) — approved Propafenone SmPC: https://www.medicines.org.uk/emc/product/1733/smpc', 1),
  ('sotalol', 'asma_dpoc', 'Asma / DPOC', 'Asthma / COPD', 'contraindication', 'critical', 'O sotalol possui atividade betabloqueadora e está contraindicado em doentes com asma brônquica ou DPOC, pelo risco de broncospasmo.', 'Sotalol has beta-blocking activity and is contraindicated in bronchial asthma or COPD because of the risk of bronchospasm.', 'Não usar em doentes com asma ou DPOC; considerar um antiarrítmico classe III sem bloqueio beta.', 'Do not use in asthma or COPD; consider a class III antiarrhythmic without beta-blockade.', 'EMC-UK (MHRA) — SmPC aprovada Sotalol: https://www.medicines.org.uk/emc/product/7039/smpc', 'EMC-UK (MHRA) — approved Sotalol SmPC: https://www.medicines.org.uk/emc/product/7039/smpc', 1),
  ('sotalol', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'contraindication', 'critical', 'O sotalol prolonga o intervalo QT e está contraindicado em doentes com prolongamento QT congénito ou antecedentes de torsades de pointes.', 'Sotalol prolongs the QT interval and is contraindicated in congenital QT prolongation or a history of torsades de pointes.', 'Não usar; verificar o QT basal no ECG antes de iniciar e monitorizar o QT durante o tratamento.', 'Do not use; check baseline QT on ECG before starting and monitor QT during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Sotalol: https://www.medicines.org.uk/emc/product/7039/smpc', 'EMC-UK (MHRA) — approved Sotalol SmPC: https://www.medicines.org.uk/emc/product/7039/smpc', 2),
  ('etilefrina', 'hipertensao_grave', 'Hipertensão grave', 'Severe hypertension', 'contraindication', 'critical', 'A etilefrina, como simpatomimético, está contraindicada em doentes com hipertensão grave, pelo risco de crise hipertensiva.', 'Etilefrine, being a sympathomimetic, is contraindicated in severe hypertension because of the risk of a hypertensive crisis.', 'Não usar em doentes com hipertensão grave ou não controlada.', 'Do not use in patients with severe or uncontrolled hypertension.', 'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Etilefrina', 'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Etilefrine', 1),
  ('midodrina', 'hipertensao_supina', 'Hipertensão em decúbito', 'Supine hypertension', 'contraindication', 'critical', 'A midodrina está contraindicada em doentes com hipertensão, sobretudo hipertensão em decúbito, e em doença cardiovascular grave, pelo risco de elevação pressórica perigosa.', 'Midodrine is contraindicated in hypertension, particularly supine hypertension, and severe cardiovascular disease because of the risk of dangerous blood pressure elevation.', 'Não usar em doentes hipertensos; monitorizar a tensão arterial em decúbito e em ortostatismo.', 'Do not use in hypertensive patients; monitor supine and standing blood pressure.', 'EMC-UK (MHRA) — SmPC aprovada Midodrina: https://www.medicines.org.uk/emc/product/12040/smpc', 'EMC-UK (MHRA) — approved Midodrine SmPC: https://www.medicines.org.uk/emc/product/12040/smpc', 1),
  ('bumetanida', 'anuria', 'Anúria', 'Anuria', 'contraindication', 'critical', 'A bumetanida está contraindicada em doentes com anúria, uma vez que o efeito diurético depende de uma função renal adequada.', 'Bumetanide is contraindicated in anuria because the diuretic effect depends on adequate renal function.', 'Não usar em doentes com anúria.', 'Do not use in patients with anuria.', 'EMC-UK (MHRA) — SmPC aprovada Bumetanida: https://www.medicines.org.uk/emc/product/13372/smpc', 'EMC-UK (MHRA) — approved Bumetanide SmPC: https://www.medicines.org.uk/emc/product/13372/smpc', 1),
  ('bumetanida', 'encefalopatia_hepatica', 'Encefalopatia hepática', 'Hepatic encephalopathy', 'contraindication', 'critical', 'A bumetanida está contraindicada em doentes com encefalopatia hepática, pois a depleção de potássio pode precipitar o coma hepático.', 'Bumetanide is contraindicated in hepatic encephalopathy because potassium depletion may precipitate hepatic coma.', 'Não usar em doentes com encefalopatia hepática.', 'Do not use in patients with hepatic encephalopathy.', 'EMC-UK (MHRA) — SmPC aprovada Bumetanida: https://www.medicines.org.uk/emc/product/13372/smpc', 'EMC-UK (MHRA) — approved Bumetanide SmPC: https://www.medicines.org.uk/emc/product/13372/smpc', 2),
  ('indapamida', 'anuria', 'Anúria', 'Anuria', 'contraindication', 'critical', 'A indapamida está contraindicada em doentes com anúria, pelo risco de acumulação do fármaco e ineficácia do efeito diurético.', 'Indapamide is contraindicated in anuria because of the risk of drug accumulation and ineffective diuresis.', 'Não usar em doentes com anúria.', 'Do not use in patients with anuria.', 'EMC-UK (MHRA) — SmPC aprovada Indapamida: https://www.medicines.org.uk/emc/product/6223/smpc', 'EMC-UK (MHRA) — approved Indapamide SmPC: https://www.medicines.org.uk/emc/product/6223/smpc', 1),
  ('acetazolamida', 'cirrose_hepatica', 'Cirrose hepática', 'Hepatic cirrhosis', 'contraindication', 'critical', 'A acetazolamida está contraindicada em doentes com cirrose hepática, pois pode precipitar encefalopatia hepática.', 'Acetazolamide is contraindicated in hepatic cirrhosis because it may precipitate hepatic encephalopathy.', 'Não usar em doentes com cirrose hepática.', 'Do not use in patients with hepatic cirrhosis.', 'EMC-UK (MHRA) — SmPC aprovada Acetazolamida: https://www.medicines.org.uk/emc/product/100949/smpc', 'EMC-UK (MHRA) — approved Acetazolamide SmPC: https://www.medicines.org.uk/emc/product/100949/smpc', 1),
  ('ramipril', 'angioedema_previo', 'Angioedema prévio (IECA/hereditário)', 'Previous angioedema (ACE-i/hereditary)', 'contraindication', 'critical', 'O ramipril está contraindicado em doentes com antecedentes de angioedema associado a IECA ou angioedema hereditário/idiopático, pelo risco de recorrência grave.', 'Ramipril is contraindicated in previous ACE-inhibitor-associated angioedema or hereditary/idiopathic angioedema because of the risk of severe recurrence.', 'Não usar em doentes com antecedentes de angioedema; usar alternativa de outra classe.', 'Do not use in patients with a history of angioedema; use an alternative class.', 'EMC-UK (MHRA) — SmPC aprovada Ramipril: https://www.medicines.org.uk/emc/product/8067/smpc', 'EMC-UK (MHRA) — approved Ramipril SmPC: https://www.medicines.org.uk/emc/product/8067/smpc', 1),
  ('ramipril', 'estenose_arteria_renal', 'Estenose bilateral das artérias renais', 'Bilateral renal artery stenosis', 'contraindication', 'critical', 'O ramipril está contraindicado em estenose bilateral das artérias renais (ou estenose em rim único funcionante), pelo risco de insuficiência renal aguda.', 'Ramipril is contraindicated in bilateral renal artery stenosis (or stenosis in a single functioning kidney) because of the risk of acute renal failure.', 'Não usar; avaliar a função renal e a etiologia da hipertensão antes de iniciar um IECA.', 'Do not use; assess renal function and the cause of hypertension before starting an ACE inhibitor.', 'EMC-UK (MHRA) — SmPC aprovada Ramipril: https://www.medicines.org.uk/emc/product/8067/smpc', 'EMC-UK (MHRA) — approved Ramipril SmPC: https://www.medicines.org.uk/emc/product/8067/smpc', 2),
  ('valsartana', 'angioedema_previo', 'Angioedema prévio (ARA II/hereditário)', 'Previous angioedema (ARB/hereditary)', 'contraindication', 'critical', 'A valsartana está contraindicada em doentes com antecedentes de angioedema associado a ARA II ou angioedema hereditário.', 'Valsartan is contraindicated in previous ARB-associated angioedema or hereditary angioedema.', 'Não usar em doentes com antecedentes de angioedema.', 'Do not use in patients with a history of angioedema.', 'EMC-UK (MHRA) — SmPC aprovada Valsartana: https://www.medicines.org.uk/emc/product/14212/smpc', 'EMC-UK (MHRA) — approved Valsartan SmPC: https://www.medicines.org.uk/emc/product/14212/smpc', 1),
  ('valsartana', 'estenose_arteria_renal', 'Estenose bilateral das artérias renais', 'Bilateral renal artery stenosis', 'contraindication', 'critical', 'A valsartana está contraindicada em estenose bilateral das artérias renais (ou estenose em rim único funcionante), pelo risco de insuficiência renal aguda.', 'Valsartan is contraindicated in bilateral renal artery stenosis (or stenosis in a single functioning kidney) because of the risk of acute renal failure.', 'Não usar; avaliar a função renal antes de iniciar um ARA II.', 'Do not use; assess renal function before starting an ARB.', 'EMC-UK (MHRA) — SmPC aprovada Valsartana: https://www.medicines.org.uk/emc/product/14212/smpc', 'EMC-UK (MHRA) — approved Valsartan SmPC: https://www.medicines.org.uk/emc/product/14212/smpc', 2),
  ('digoxina', 'hipocaliemia', 'Hipocaliemia', 'Hypokalaemia', 'precaution', 'moderate', 'A hipocaliemia aumenta a sensibilidade do miocárdio à digoxina e o risco de arritmias, incluindo intoxicação digitálica.', 'Hypokalaemia increases myocardial sensitivity to digoxin and the risk of arrhythmias, including digoxin toxicity.', 'Corrigir o potássio antes e durante o tratamento; monitorizar o ECG e os níveis de digoxina.', 'Correct potassium before and during treatment; monitor ECG and digoxin levels.', 'EMC-UK (MHRA) — SmPC aprovada Digoxina: https://www.medicines.org.uk/emc/product/5463/smpc', 'EMC-UK (MHRA) — approved Digoxin SmPC: https://www.medicines.org.uk/emc/product/5463/smpc', 1),
  ('amiodarona', 'doenca_pulmonar_intersticial', 'Doença pulmonar intersticial', 'Interstitial lung disease', 'contraindication', 'critical', 'A amiodarona pode causar doença pulmonar intersticial ou fibrose pulmonar, por vezes fatal; está contraindicada em doença pulmonar intersticial ativa.', 'Amiodarone may cause interstitial lung disease or pulmonary fibrosis, sometimes fatal; it is contraindicated in active interstitial lung disease.', 'Não usar; monitorizar tosse e dispneia e realizar radiografia torácica perante qualquer suspeita.', 'Do not use; monitor for cough and dyspnoea and obtain a chest X-ray on any suspicion.', 'EMC-UK (MHRA) — SmPC aprovada Amiodarona: https://www.medicines.org.uk/emc/product/8739/smpc', 'EMC-UK (MHRA) — approved Amiodarone SmPC: https://www.medicines.org.uk/emc/product/8739/smpc', 1),
  ('furosemida', 'anuria', 'Anúria', 'Anuria', 'contraindication', 'critical', 'A furosemida está contraindicada em doentes com anúria, pois o efeito diurético depende da função renal.', 'Furosemide is contraindicated in anuria because the diuretic effect depends on renal function.', 'Não usar em doentes com anúria.', 'Do not use in patients with anuria.', 'EMC-UK (MHRA) — SmPC aprovada Furosemida: https://www.medicines.org.uk/emc/product/2380/smpc', 'EMC-UK (MHRA) — approved Furosemide SmPC: https://www.medicines.org.uk/emc/product/2380/smpc', 1),
  ('hidroclorotiazida', 'anuria', 'Anúria', 'Anuria', 'contraindication', 'critical', 'A hidroclorotiazida está contraindicada em doentes com anúria, pelo risco de acumulação do fármaco.', 'Hydrochlorothiazide is contraindicated in anuria because of the risk of drug accumulation.', 'Não usar em doentes com anúria.', 'Do not use in patients with anuria.', 'EMC-UK (MHRA) — SmPC aprovada Hidroclorotiazida: https://www.medicines.org.uk/emc/product/11721/smpc', 'EMC-UK (MHRA) — approved Hydrochlorothiazide SmPC: https://www.medicines.org.uk/emc/product/11721/smpc', 1),
  ('espironolactona', 'hipercaliemia', 'Hipercaliemia', 'Hyperkalaemia', 'contraindication', 'critical', 'A espironolactona está contraindicada em doentes com hipercaliemia e em insuficiência renal grave, pelo risco de hipercaliemia potencialmente fatal.', 'Spironolactone is contraindicated in hyperkalaemia and severe renal impairment because of the risk of potentially fatal hyperkalaemia.', 'Não usar em doentes com potássio elevado ou função renal gravemente diminuída; monitorizar potássio e creatinina.', 'Do not use with elevated potassium or severely reduced renal function; monitor potassium and creatinine.', 'EMC-UK (MHRA) — SmPC aprovada Espironolactona: https://www.medicines.org.uk/emc/product/2898/smpc', 'EMC-UK (MHRA) — approved Spironolactone SmPC: https://www.medicines.org.uk/emc/product/2898/smpc', 1),
  ('captopril', 'angioedema_previo', 'Angioedema prévio (IECA)', 'Previous angioedema (ACE-i)', 'contraindication', 'critical', 'O captopril está contraindicado em doentes com antecedentes de angioedema associado a IECA.', 'Captopril is contraindicated in previous ACE-inhibitor-associated angioedema.', 'Não usar em doentes com antecedentes de angioedema; usar alternativa de outra classe.', 'Do not use in patients with a history of angioedema; use an alternative class.', 'EMC-UK (MHRA) — SmPC aprovada Captopril: https://www.medicines.org.uk/emc/product/5250/smpc', 'EMC-UK (MHRA) — approved Captopril SmPC: https://www.medicines.org.uk/emc/product/5250/smpc', 1),
  ('enalapril', 'angioedema_previo', 'Angioedema prévio (IECA)', 'Previous angioedema (ACE-i)', 'contraindication', 'critical', 'O enalapril está contraindicado em doentes com antecedentes de angioedema associado a IECA ou angioedema hereditário/idiopático.', 'Enalapril is contraindicated in previous ACE-inhibitor-associated angioedema or hereditary/idiopathic angioedema.', 'Não usar em doentes com antecedentes de angioedema.', 'Do not use in patients with a history of angioedema.', 'EMC-UK (MHRA) — SmPC aprovada Enalapril: https://www.medicines.org.uk/emc/product/15458/smpc', 'EMC-UK (MHRA) — approved Enalapril SmPC: https://www.medicines.org.uk/emc/product/15458/smpc', 1),
  ('losartano', 'angioedema_previo', 'Angioedema prévio', 'Previous angioedema', 'contraindication', 'critical', 'O losartano está contraindicado em doentes com antecedentes de angioedema associado a ARA II ou angioedema hereditário.', 'Losartan is contraindicated in previous ARB-associated angioedema or hereditary angioedema.', 'Não usar em doentes com antecedentes de angioedema.', 'Do not use in patients with a history of angioedema.', 'EMC-UK (MHRA) — SmPC aprovada Losartano: https://www.medicines.org.uk/emc/product/7783/smpc', 'EMC-UK (MHRA) — approved Losartan SmPC: https://www.medicines.org.uk/emc/product/7783/smpc', 1),
  ('losartano', 'estenose_arteria_renal', 'Estenose bilateral das artérias renais', 'Bilateral renal artery stenosis', 'contraindication', 'critical', 'O losartano está contraindicado em estenose bilateral das artérias renais (ou estenose em rim único funcionante), pelo risco de insuficiência renal aguda.', 'Losartan is contraindicated in bilateral renal artery stenosis (or stenosis in a single functioning kidney) because of the risk of acute renal failure.', 'Não usar; avaliar a função renal antes de iniciar um ARA II.', 'Do not use; assess renal function before starting an ARB.', 'EMC-UK (MHRA) — SmPC aprovada Losartano: https://www.medicines.org.uk/emc/product/7783/smpc', 'EMC-UK (MHRA) — approved Losartan SmPC: https://www.medicines.org.uk/emc/product/7783/smpc', 2)) AS v(slug, condition_slug, condition_pt, condition_en,
       interaction_type, severity, reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('flecainida', 'caution', 'A flecainida atravessa a placenta; os dados em grávidas são limitados, mas não indicaram teratogenicidade consistente.', 'Flecainide crosses the placenta; data in pregnancy are limited but have not shown consistent teratogenicity.', 'Utilizar apenas se o benefício superar o risco, em particular no tratamento de arritmias maternas com significado clínico.', 'Use only if the benefit outweighs the risk, particularly for clinically significant maternal arrhythmias.', 'A flecainida é excretada no leite materno em pequenas quantidades; os dados disponíveis sugerem baixo risco no lactente.', 'Flecainide is excreted into breast milk in small amounts; available data suggest low risk to the infant.', 'Não é exigida contraceção adicional específica, mas a decisão de tratar na gravidez deve ser documentada.', 'No specific additional contraception is required, but the decision to treat in pregnancy should be documented.', 'EMC-UK (MHRA) — SmPC aprovada Flecainida: https://www.medicines.org.uk/emc/product/3086/smpc', 'EMC-UK (MHRA) — approved Flecainide SmPC: https://www.medicines.org.uk/emc/product/3086/smpc'),
  ('propafenona', 'caution', 'A propafenona atravessa a placenta; os dados em grávidas são limitados e não demonstraram teratogenicidade clara.', 'Propafenone crosses the placenta; data in pregnancy are limited and have not shown clear teratogenicity.', 'Utilizar apenas se o benefício materno superar o risco fetal.', 'Use only if the maternal benefit outweighs the fetal risk.', 'A propafenona é excretada no leite materno; preferir alternativa em lactentes de risco.', 'Propafenone is excreted into breast milk; prefer an alternative in at-risk infants.', 'Documentar a decisão de tratar em idade fértil; considerar contraceção se a terapêutica for nova.', 'Document the decision to treat women of childbearing age; consider contraception if therapy is new.', 'EMC-UK (MHRA) — SmPC aprovada Propafenona: https://www.medicines.org.uk/emc/product/1733/smpc', 'EMC-UK (MHRA) — approved Propafenone SmPC: https://www.medicines.org.uk/emc/product/1733/smpc'),
  ('sotalol', 'caution', 'O sotalol atravessa a placenta e pode causar efeitos beta-bloqueadores no feto (bradicardia, hipoglicemia); os dados não indicam teratogenicidade.', 'Sotalol crosses the placenta and may cause beta-blocking effects in the fetus (bradycardia, hypoglycaemia); data do not indicate teratogenicity.', 'Utilizar apenas se o benefício superar o risco; monitorizar o crescimento e a frequência cardíaca fetal.', 'Use only if the benefit outweighs the risk; monitor fetal growth and heart rate.', 'O sotalol é excretado no leite materno; vigiar o lactente para sinais de bloqueio beta.', 'Sotalol is excreted into breast milk; monitor the infant for signs of beta-blockade.', 'Não é exigida contraceção específica, mas a terapêutica crónica em idade fértil deve ser revista antes da conceção.', 'No specific contraception is required, but chronic therapy in women of childbearing age should be reviewed before conception.', 'EMC-UK (MHRA) — SmPC aprovada Sotalol: https://www.medicines.org.uk/emc/product/7039/smpc', 'EMC-UK (MHRA) — approved Sotalol SmPC: https://www.medicines.org.uk/emc/product/7039/smpc'),
  ('etilefrina', 'caution', 'Os dados sobre o uso de etilefrina na gravidez são limitados; a utilização apenas se o benefício superar o risco.', 'Data on etilefrine use in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar no 1.º trimestre; a utilização no parto deve ser ponderada pelo efeito pressor.', 'Avoid in the 1st trimester; use at delivery must balance the pressor effect.', 'Não há dados suficientes sobre a excreção no leite materno; ponderar alternativa.', 'No sufficient data on excretion into breast milk; consider an alternative.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar tratamento prolongado.', 'In women of childbearing age, rule out pregnancy before starting long-term treatment.', 'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Etilefrina', 'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Etilefrine'),
  ('midodrina', 'caution', 'A midodrina não deve ser utilizada na gravidez exceto se estritamente necessário, por falta de dados de segurança.', 'Midodrine should not be used in pregnancy unless strictly necessary because of a lack of safety data.', 'Utilizar apenas se o benefício superar claramente o risco.', 'Use only if the benefit clearly outweighs the risk.', 'Não há dados suficientes sobre a excreção no leite materno; ponderar alternativa.', 'No sufficient data on excretion into breast milk; consider an alternative.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar tratamento.', 'In women of childbearing age, rule out pregnancy before starting treatment.', 'EMC-UK (MHRA) — SmPC aprovada Midodrina: https://www.medicines.org.uk/emc/product/12040/smpc', 'EMC-UK (MHRA) — approved Midodrine SmPC: https://www.medicines.org.uk/emc/product/12040/smpc'),
  ('bumetanida', 'caution', 'A bumetanida atravessa a placenta; os dados em grávidas são limitados e a utilização apenas se o benefício superar o risco.', 'Bumetanide crosses the placenta; data in pregnancy are limited and use should only occur if the benefit outweighs the risk.', 'Evitar como diurético de rotina na gravidez; restringir a situações com indicação clara (ex.: edema pulmonar).', 'Avoid as routine diuretic therapy in pregnancy; restrict to clear indications (e.g. pulmonary oedema).', 'A bumetanida é excretada no leite materno; vigiar o lactente e considerar a supressão da lactação em doses elevadas.', 'Bumetanide is excreted into breast milk; monitor the infant and consider suppressing lactation at high doses.', 'Diuréticos não são indicados na gravidez normal; a sua utilização crónica em idade fértil deve ser revista.', 'Diuretics are not indicated in normal pregnancy; chronic use in women of childbearing age should be reviewed.', 'EMC-UK (MHRA) — SmPC aprovada Bumetanida: https://www.medicines.org.uk/emc/product/13372/smpc', 'EMC-UK (MHRA) — approved Bumetanide SmPC: https://www.medicines.org.uk/emc/product/13372/smpc'),
  ('indapamida', 'caution', 'A indapamida atravessa a placenta; os dados em grávidas são limitados e a utilização apenas se o benefício superar o risco.', 'Indapamide crosses the placenta; data in pregnancy are limited and use should only occur if the benefit outweighs the risk.', 'Evitar na gravidez, exceto se estritamente indicado; não é adequada como anti-hipertensor na gravidez.', 'Avoid in pregnancy unless strictly indicated; it is not appropriate as an antihypertensive in pregnancy.', 'A indapamida é excretada no leite materno; não é recomendada durante o aleitamento.', 'Indapamide is excreted into breast milk; it is not recommended during breastfeeding.', 'Em idade fértil com hipertensão, preferir anti-hipertensores com perfil de segurança estabelecido na gravidez.', 'In women of childbearing age with hypertension, prefer antihypertensives with an established safety profile in pregnancy.', 'EMC-UK (MHRA) — SmPC aprovada Indapamida: https://www.medicines.org.uk/emc/product/6223/smpc', 'EMC-UK (MHRA) — approved Indapamide SmPC: https://www.medicines.org.uk/emc/product/6223/smpc'),
  ('acetazolamida', 'caution', 'A acetazolamida atravessa a placenta; há relatos de teratogenicidade em estudos animais, pelo que deve ser evitada no 1.º trimestre.', 'Acetazolamide crosses the placenta; teratogenicity has been reported in animal studies, so it should be avoided in the 1st trimester.', 'Evitar no 1.º trimestre; utilizar apenas se o benefício superar o risco.', 'Avoid in the 1st trimester; use only if the benefit outweighs the risk.', 'A acetazolamida é excretada no leite materno; evitar durante o aleitamento por falta de dados.', 'Acetazolamide is excreted into breast milk; avoid during breastfeeding because of a lack of data.', 'Em idade fértil, utilizar contraceção eficaz durante o tratamento.', 'Use effective contraception during treatment in women of childbearing age.', 'EMC-UK (MHRA) — SmPC aprovada Acetazolamida: https://www.medicines.org.uk/emc/product/100949/smpc', 'EMC-UK (MHRA) — approved Acetazolamide SmPC: https://www.medicines.org.uk/emc/product/100949/smpc'),
  ('ramipril', 'contraindicated', 'Os IECA são contraindicados na gravidez: podem causar lesão renal fetal, oligohidrâmnios e hipoplasia do crânio, sobretudo no 2.º e 3.º trimestres.', 'ACE inhibitors are contraindicated in pregnancy: they may cause fetal renal injury, oligohydramnios and skull hypoplasia, especially in the 2nd and 3rd trimesters.', 'Não iniciar em grávidas; se a gravidez for detetada, suspender o ramipril imediatamente e mudar para terapêutica alternativa adequada.', 'Do not start in pregnancy; if pregnancy is detected, stop ramipril immediately and switch to appropriate alternative therapy.', 'Não é recomendado durante o aleitamento; preferir alternativa com perfil de segurança estabelecido.', 'Not recommended during breastfeeding; prefer an alternative with an established safety profile.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Ramipril: https://www.medicines.org.uk/emc/product/8067/smpc', 'EMC-UK (MHRA) — approved Ramipril SmPC: https://www.medicines.org.uk/emc/product/8067/smpc'),
  ('valsartana', 'contraindicated', 'Os ARA II são contraindicados na gravidez: podem causar lesão renal fetal, oligohidrâmnios e hipoplasia do crânio, sobretudo no 2.º e 3.º trimestres.', 'ARBs are contraindicated in pregnancy: they may cause fetal renal injury, oligohydramnios and skull hypoplasia, especially in the 2nd and 3rd trimesters.', 'Não iniciar em grávidas; se a gravidez for detetada, suspender a valsartana imediatamente.', 'Do not start in pregnancy; if pregnancy is detected, stop valsartan immediately.', 'Não é recomendado durante o aleitamento; preferir alternativa com perfil de segurança estabelecido.', 'Not recommended during breastfeeding; prefer an alternative with an established safety profile.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Valsartana: https://www.medicines.org.uk/emc/product/14212/smpc', 'EMC-UK (MHRA) — approved Valsartan SmPC: https://www.medicines.org.uk/emc/product/14212/smpc'),
  ('digoxina', 'caution', 'A digoxina atravessa a placenta; os dados em grávidas não indicam teratogenicidade, mas a dose materna pode precisar de ajuste.', 'Digoxin crosses the placenta; data in pregnancy do not indicate teratogenicity, but the maternal dose may need adjustment.', 'Utilizar se clinicamente indicado, com monitorização dos níveis séricos e ajuste posológico.', 'Use if clinically indicated, with serum level monitoring and dose adjustment.', 'A digoxina é excretada no leite materno em pequenas quantidades, compatíveis com o aleitamento.', 'Digoxin is excreted into breast milk in small amounts, compatible with breastfeeding.', 'Não é exigida contraceção adicional específica em terapêutica crónica.', 'No specific additional contraception is required in chronic therapy.', 'EMC-UK (MHRA) — SmPC aprovada Digoxina: https://www.medicines.org.uk/emc/product/5463/smpc', 'EMC-UK (MHRA) — approved Digoxin SmPC: https://www.medicines.org.uk/emc/product/5463/smpc'),
  ('amiodarona', 'contraindicated', 'A amiodarona está contraindicada na gravidez: contém iodo e pode causar disfunção tiroideia fetal e outras toxicidades.', 'Amiodarone is contraindicated in pregnancy: it contains iodine and may cause fetal thyroid dysfunction and other toxicities.', 'Não usar na gravidez; considerar terapêutica antiarrítmica alternativa.', 'Do not use in pregnancy; consider alternative antiarrhythmic therapy.', 'Contraindicada durante o aleitamento, dado o risco de toxicidade tiroideia no lactente.', 'Contraindicated during breastfeeding because of the risk of thyroid toxicity in the infant.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Amiodarona: https://www.medicines.org.uk/emc/product/8739/smpc', 'EMC-UK (MHRA) — approved Amiodarone SmPC: https://www.medicines.org.uk/emc/product/8739/smpc'),
  ('furosemida', 'caution', 'A furosemida atravessa a placenta; os dados em grávidas são limitados e a utilização apenas se o benefício superar o risco.', 'Furosemide crosses the placenta; data in pregnancy are limited and use should only occur if the benefit outweighs the risk.', 'Evitar como diurético de rotina na gravidez; restringir a situações com indicação clara.', 'Avoid as routine diuretic therapy in pregnancy; restrict to clear indications.', 'A furosemida é excretada no leite materno e pode suprimir a lactação; considerar a supressão da lactação em doses elevadas.', 'Furosemide is excreted into breast milk and may suppress lactation; consider suppressing lactation at high doses.', 'Diuréticos não são indicados na gravidez normal; rever a terapêutica crónica em idade fértil.', 'Diuretics are not indicated in normal pregnancy; review chronic therapy in women of childbearing age.', 'EMC-UK (MHRA) — SmPC aprovada Furosemida: https://www.medicines.org.uk/emc/product/2380/smpc', 'EMC-UK (MHRA) — approved Furosemide SmPC: https://www.medicines.org.uk/emc/product/2380/smpc'),
  ('hidroclorotiazida', 'caution', 'A hidroclorotiazida atravessa a placenta; os dados em grávidas não indicam teratogenicidade, mas pode causar hipoperfusão placentária.', 'Hydrochlorothiazide crosses the placenta; data in pregnancy do not indicate teratogenicity, but it may cause placental hypoperfusion.', 'Evitar como anti-hipertensor na gravidez; a utilização apenas se o benefício superar o risco.', 'Avoid as an antihypertensive in pregnancy; use only if the benefit outweighs the risk.', 'A hidroclorotiazida é excretada no leite materno em pequenas quantidades; a utilização com precaução.', 'Hydrochlorothiazide is excreted into breast milk in small amounts; use with caution.', 'Em idade fértil, a terapêutica diurética crónica deve ser revista antes da conceção.', 'In women of childbearing age, chronic diuretic therapy should be reviewed before conception.', 'EMC-UK (MHRA) — SmPC aprovada Hidroclorotiazida: https://www.medicines.org.uk/emc/product/11721/smpc', 'EMC-UK (MHRA) — approved Hydrochlorothiazide SmPC: https://www.medicines.org.uk/emc/product/11721/smpc'),
  ('espironolactona', 'caution', 'A espironolactona atravessa a placenta; em estudos animais houve efeitos antiandrogénicos no feto masculino, pelo que se recomenda prudência.', 'Spironolactone crosses the placenta; antiandrogenic effects were seen in male fetuses in animal studies, so caution is advised.', 'Utilizar apenas se o benefício superar o risco; evitar no 1.º trimestre sempre que possível.', 'Use only if the benefit outweighs the risk; avoid in the 1st trimester whenever possible.', 'O canrenona (metabolito ativo) é excretado no leite materno; a utilização durante o aleitamento deve ser evitada.', 'Canrenone (active metabolite) is excreted into breast milk; use during breastfeeding should be avoided.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar tratamento prolongado.', 'In women of childbearing age, rule out pregnancy before starting long-term treatment.', 'EMC-UK (MHRA) — SmPC aprovada Espironolactona: https://www.medicines.org.uk/emc/product/2898/smpc', 'EMC-UK (MHRA) — approved Spironolactone SmPC: https://www.medicines.org.uk/emc/product/2898/smpc'),
  ('captopril', 'contraindicated', 'O captopril está contraindicado na gravidez: os IECA podem causar lesão renal fetal, oligohidrâmnios e hipoplasia do crânio, sobretudo no 2.º e 3.º trimestres.', 'Captopril is contraindicated in pregnancy: ACE inhibitors may cause fetal renal injury, oligohydramnios and skull hypoplasia, especially in the 2nd and 3rd trimesters.', 'Não iniciar em grávidas; se a gravidez for detetada, suspender o captopril imediatamente.', 'Do not start in pregnancy; if pregnancy is detected, stop captopril immediately.', 'Não é recomendado durante o aleitamento; preferir alternativa com perfil de segurança estabelecido.', 'Not recommended during breastfeeding; prefer an alternative with an established safety profile.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Captopril: https://www.medicines.org.uk/emc/product/5250/smpc', 'EMC-UK (MHRA) — approved Captopril SmPC: https://www.medicines.org.uk/emc/product/5250/smpc'),
  ('enalapril', 'contraindicated', 'O enalapril está contraindicado na gravidez: os IECA podem causar lesão renal fetal, oligohidrâmnios e hipoplasia do crânio, sobretudo no 2.º e 3.º trimestres.', 'Enalapril is contraindicated in pregnancy: ACE inhibitors may cause fetal renal injury, oligohydramnios and skull hypoplasia, especially in the 2nd and 3rd trimesters.', 'Não iniciar em grávidas; se a gravidez for detetada, suspender o enalapril imediatamente.', 'Do not start in pregnancy; if pregnancy is detected, stop enalapril immediately.', 'Não é recomendado durante o aleitamento; preferir alternativa com perfil de segurança estabelecido.', 'Not recommended during breastfeeding; prefer an alternative with an established safety profile.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Enalapril: https://www.medicines.org.uk/emc/product/15458/smpc', 'EMC-UK (MHRA) — approved Enalapril SmPC: https://www.medicines.org.uk/emc/product/15458/smpc'),
  ('losartano', 'contraindicated', 'O losartano está contraindicado na gravidez: os ARA II podem causar lesão renal fetal, oligohidrâmnios e hipoplasia do crânio, sobretudo no 2.º e 3.º trimestres.', 'Losartan is contraindicated in pregnancy: ARBs may cause fetal renal injury, oligohydramnios and skull hypoplasia, especially in the 2nd and 3rd trimesters.', 'Não iniciar em grávidas; se a gravidez for detetada, suspender o losartano imediatamente.', 'Do not start in pregnancy; if pregnancy is detected, stop losartan immediately.', 'Não é recomendado durante o aleitamento; preferir alternativa com perfil de segurança estabelecido.', 'Not recommended during breastfeeding; prefer an alternative with an established safety profile.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Losartano: https://www.medicines.org.uk/emc/product/7783/smpc', 'EMC-UK (MHRA) — approved Losartan SmPC: https://www.medicines.org.uk/emc/product/7783/smpc')) AS v(slug, pregnancy_category, risk_pt, risk_en,
       trimester_pt, trimester_en, lactation_pt, lactation_en,
       contraception_pt, contraception_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
