-- ================================================================
-- 064_seed_interacoes_hematologia.sql
-- Secção 4 (Hematologia & Hemostase): 4.1 Antianémicos, 4.2 Fatores de
-- crescimento hematopoiéticos, 4.3 Anticoagulantes e antitrombóticos, 4.4 Anti-hemorrágicos.
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico.
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('ferro', 'Ferro (sulfato ferroso)', 'Iron (ferrous sulfate)', 'Antianémico (ferro)', 'Antianaemic (iron)', ARRAY['sulfato ferroso', 'ferrous sulfate', 'Ferrograd'], 'published', 116),
  ('acido_folico', 'Ácido fólico', 'Folic acid', 'Antianémico (folato)', 'Antianaemic (folate)', ARRAY['folato', 'folate', 'vitamina B9', 'vitamin B9'], 'published', 117),
  ('cianocobalamina', 'Cianocobalamina (vitamina B12)', 'Cyanocobalamin (vitamin B12)', 'Antianémico (vitamina B12)', 'Antianaemic (vitamin B12)', ARRAY['cobalamina', 'vitamina B12', 'vitamin B12', 'Cytacon'], 'published', 118),
  ('epoetina_alfa', 'Epoetina alfa', 'Epoetin alfa', 'Fator de crescimento hematopoiético (eritropoietina)', 'Haematopoietic growth factor (erythropoietin)', ARRAY['eritropoietina', 'erythropoietin', 'EPO', 'Eprex'], 'published', 119),
  ('filgrastim', 'Filgrastim', 'Filgrastim', 'Fator de crescimento hematopoiético (G-CSF)', 'Haematopoietic growth factor (G-CSF)', ARRAY['G-CSF', 'Neupogen', 'Nivestim'], 'published', 120),
  ('apixabano', 'Apixabano', 'Apixaban', 'Anticoagulante oral direto (inibidor do fator Xa)', 'Direct oral anticoagulant (factor Xa inhibitor)', ARRAY['Eliquis', 'apixaban'], 'published', 121),
  ('rivaroxabano', 'Rivaroxabano', 'Rivaroxaban', 'Anticoagulante oral direto (inibidor do fator Xa)', 'Direct oral anticoagulant (factor Xa inhibitor)', ARRAY['Xarelto', 'rivaroxaban'], 'published', 122),
  ('dabigatrano', 'Dabigatrano (etexilato)', 'Dabigatran (etexilate)', 'Anticoagulante oral direto (inibidor da trombina)', 'Direct oral anticoagulant (thrombin inhibitor)', ARRAY['Pradaxa', 'dabigatran etexilate'], 'published', 123),
  ('enoxaparina', 'Enoxaparina', 'Enoxaparin', 'Heparina de baixo peso molecular (antitrombótico)', 'Low-molecular-weight heparin (antithrombotic)', ARRAY['Clexane', 'Lovenox', 'enoxaparin'], 'published', 124),
  ('fondaparinux', 'Fondaparinux', 'Fondaparinux', 'Antitrombótico (inibidor seletivo do fator Xa)', 'Antithrombotic (selective factor Xa inhibitor)', ARRAY['Arixtra', 'fondaparinux sodium'], 'published', 125),
  ('acido_tranexamico', 'Ácido tranexâmico', 'Tranexamic acid', 'Anti-hemorrágico (antifibrinolítico)', 'Antihaemorrhagic (antifibrinolytic)', ARRAY['Cyklokapron', 'tranexamic acid', 'ácido tranexâmico'], 'published', 126),
  ('fitomenadiona', 'Fitomenadiona (vitamina K1)', 'Phytomenadione (vitamin K1)', 'Anti-hemorrágico (vitamina K)', 'Antihaemorrhagic (vitamin K)', ARRAY['vitamina K1', 'vitamin K1', 'Konakion', 'phytonadione', 'phytomenadione'], 'published', 127);

-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('apixabano', 'aspirina', 'moderate', 'A associação de apixabano com aspirina aumenta o risco de hemorragia, sobretudo gastrointestinal, embora possa ser benéfica em indicações específicas.', 'Combining apixaban with aspirin increases the risk of bleeding, particularly gastrointestinal, although it may be beneficial in specific indications.', 'O apixabano inibe o fator Xa e a aspirina inibe a cicloxigenase-1 plaquetária; os efeitos anti-hemostáticos são aditivos sem interação farmacocinética relevante.', 'Apixaban inhibits factor Xa and aspirin inhibits platelet COX-1; the anti-haemostatic effects are additive with no relevant pharmacokinetic interaction.', 'Avaliar o risco hemorrágico; quando indicada (ex.: FA com doença arterial), usar a menor dose eficaz e protetor gástrico.', 'Assess bleeding risk; when indicated (e.g. AF with arterial disease), use the lowest effective dose and a gastroprotectant.', 'Vigiar sinais de hemorragia, hemoglobina e sintomas gastrointestinais.', 'Monitor for bleeding signs, haemoglobin and gastrointestinal symptoms.', 'Hemorragia incontrolável, melenas, hematemeses, hematuria.', 'Uncontrolled bleeding, melaena, haematemesis, haematuria.', 'DailyMed (FDA) — rótulo aprovado Apixabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175 ; rótulo aprovado Aspirina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Apixaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175 ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('rivaroxabano', 'aspirina', 'moderate', 'A associação de rivaroxabano com aspirina aumenta o risco de hemorragia, em particular gastrointestinal.', 'Combining rivaroxaban with aspirin increases the risk of bleeding, particularly gastrointestinal.', 'Rivaroxabano inibe o fator Xa; a aspirina bloqueia a via do tromboxano plaquetário, com efeito hemorrágico aditivo.', 'Rivaroxaban inhibits factor Xa; aspirin blocks the platelet thromboxane pathway, with an additive bleeding effect.', 'Ponderar o benefício cardiovascular contra o risco hemorrágico; usar a dose mais baixa eficaz.', 'Weigh cardiovascular benefit against bleeding risk; use the lowest effective dose.', 'Vigiar hemoglobina, hematócrito e sinais de sangramento.', 'Monitor haemoglobin, haematocrit and signs of bleeding.', 'Sangramento gastrointestinal, anemia aguda, tonturas por perda sanguínea.', 'GI bleeding, acute anaemia, dizziness from blood loss.', 'DailyMed (FDA) — rótulo aprovado Rivaroxabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; rótulo aprovado Aspirina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Rivaroxaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('apixabano', 'clopidogrel', 'moderate', 'Apixabano com clopidogrel aumenta o risco hemorrágico; a associação é usada em casos selecionados (ex.: pós-SCA com FA).', 'Apixaban with clopidogrel raises bleeding risk; the combination is used in selected cases (e.g. post-ACS with AF).', 'Inibição combinada do fator Xa e da agregação plaquetária com risco de hemorragia aditivo.', 'Combined inhibition of factor Xa and platelet aggregation with an additive bleeding risk.', 'Usar apenas com indicação clara; reduzir a dose de apixabano conforme o perfil do doente.', 'Use only with a clear indication; reduce the apixaban dose according to patient profile.', 'Vigiar hemorragias ocultas, hematomas e hemograma.', 'Monitor occult bleeding, bruising and blood count.', 'Sangramento gastrointestinal ou cerebral; equimoses extensas espontâneas.', 'GI or intracranial bleeding; extensive spontaneous bruising.', 'DailyMed (FDA) — rótulo aprovado Apixabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175 ; rótulo aprovado Clopidogrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Apixaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175 ; approved Clopidogrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('rivaroxabano', 'clopidogrel', 'moderate', 'A dupla rivaroxabano + clopidogrel aumenta o risco de hemorragia major.', 'Rivaroxaban plus clopidogrel increases the risk of major bleeding.', 'Efeito antitrombótico combinado (fator Xa + P2Y12) com hemorragia aditiva.', 'Combined antithrombotic effect (factor Xa + P2Y12) with additive bleeding.', 'Reservar para indicações de alto risco trombótico; considerar protetor gástrico.', 'Reserve for high thrombotic-risk indications; consider a gastroprotectant.', 'Vigiar sinais de sangramento e hemograma.', 'Monitor for bleeding signs and blood count.', 'Hemorragia cerebral, gastrointestinal ou retroperitoneal.', 'Intracranial, GI or retroperitoneal bleeding.', 'DailyMed (FDA) — rótulo aprovado Rivaroxabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; rótulo aprovado Clopidogrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Rivaroxaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; approved Clopidogrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dabigatrano', 'aspirina', 'moderate', 'Dabigatrano com aspirina aumenta o risco hemorrágico, sobretudo gastrointestinal.', 'Dabigatran with aspirin increases bleeding risk, especially gastrointestinal.', 'O dabigatrano inibe a trombina e a aspirina a COX-1 plaquetária; efeito hemorrágico aditivo.', 'Dabigatran inhibits thrombin and aspirin inhibits platelet COX-1; additive bleeding effect.', 'Avaliar risco-benefício; a associação é usada em FA + doença coronária selecionada.', 'Assess risk-benefit; the combination is used in selected AF + coronary artery disease.', 'Vigiar hemorragia e sintomas dispépticos.', 'Monitor bleeding and dyspeptic symptoms.', 'Sangramento gastrointestinal, anemia, hematúria.', 'GI bleeding, anaemia, haematuria.', 'DailyMed (FDA) — rótulo aprovado Dabigatrano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; rótulo aprovado Aspirina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dabigatran label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dabigatrano', 'clopidogrel', 'moderate', 'A associação dabigatrano + clopidogrel aumenta o risco de hemorragia.', 'Dabigatran plus clopidogrel increases bleeding risk.', 'Inibição combinada da trombina e do recetor P2Y12, com efeito hemorrágico aditivo.', 'Combined thrombin and P2Y12 inhibition, with an additive bleeding effect.', 'Usar apenas com indicação clara; ajustar a dose de dabigatrano à função renal.', 'Use only with a clear indication; adjust the dabigatran dose to renal function.', 'Vigiar hemograma e sinais de sangramento.', 'Monitor blood count and bleeding signs.', 'Sangramento grave, melenas, hematemeses.', 'Severe bleeding, melaena, haematemesis.', 'DailyMed (FDA) — rótulo aprovado Dabigatrano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; rótulo aprovado Clopidogrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dabigatran label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; approved Clopidogrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('apixabano', 'ibuprofeno', 'moderate', 'O ibuprofeno aumenta o risco de hemorragia em doentes tratados com apixabano.', 'Ibuprofen increases the risk of bleeding in patients treated with apixaban.', 'O ibuprofeno inibe a agregação plaquetária e irrita a mucosa gastrointestinal, somando-se ao efeito anticoagulante.', 'Ibuprofen inhibits platelet aggregation and irritates the GI mucosa, adding to the anticoagulant effect.', 'Preferir paracetamol ou AINE seletivo COX-2 se possível; limitar a duração do AINE.', 'Prefer paracetamol or a COX-2 selective NSAID where possible; limit NSAID duration.', 'Vigiar sintomas dispépticos, melenas e hemograma.', 'Monitor dyspepsia, melaena and blood count.', 'Hemorragia gastrointestinal, anemia ferropriva aguda.', 'GI bleeding, acute iron-deficiency anaemia.', 'DailyMed (FDA) — rótulo aprovado Apixabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175 ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Apixaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175 ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('rivaroxabano', 'ibuprofeno', 'moderate', 'O ibuprofeno aumenta o risco hemorrágico com rivaroxabano.', 'Ibuprofen increases the bleeding risk with rivaroxaban.', 'Efeito antiagregante e gastroirritativo do ibuprofeno adiciona-se ao efeito do rivaroxabano.', 'Ibuprofen''s antiplatelet and gastro-irritative effect adds to rivaroxaban.', 'Evitar AINE de forma prolongada; usar a menor dose e a menor duração.', 'Avoid long-term NSAIDs; use the lowest dose for the shortest duration.', 'Vigiar sinais de hemorragia gastrointestinal.', 'Monitor for GI bleeding signs.', 'Melenas, hematemeses, dor abdominal com anemia.', 'Melaena, haematemesis, abdominal pain with anaemia.', 'DailyMed (FDA) — rótulo aprovado Rivaroxabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Rivaroxaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dabigatrano', 'ibuprofeno', 'moderate', 'O ibuprofeno aumenta o risco de hemorragia com dabigatrano.', 'Ibuprofen increases the bleeding risk with dabigatran.', 'O dabigatrano e o ibuprofeno têm efeitos anti-hemostáticos aditivos; o AINE também lesa a mucosa gástrica.', 'Dabigatran and ibuprofen have additive anti-haemostatic effects; the NSAID also damages the gastric mucosa.', 'Preferir analgesia alternativa; se AINE inevitável, vigiar de perto.', 'Prefer alternative analgesia; if an NSAID is unavoidable, monitor closely.', 'Vigiar hemograma e sintomas gastrointestinais.', 'Monitor blood count and GI symptoms.', 'Hemorragia gastrointestinal, anemia aguda.', 'GI bleeding, acute anaemia.', 'DailyMed (FDA) — rótulo aprovado Dabigatrano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dabigatran label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('enoxaparina', 'aspirina', 'moderate', 'A enoxaparina com aspirina aumenta o risco de hemorragia.', 'Enoxaparin with aspirin increases bleeding risk.', 'A HBPM potencializa a antitrombina e a aspirina bloqueia o tromboxano; risco hemorrágico aditivo.', 'LMWH potentiates antithrombin and aspirin blocks thromboxane; additive bleeding risk.', 'Usar a associação apenas quando indicada (ex.: SCA); vigiar sinais de sangramento.', 'Use the combination only when indicated (e.g. ACS); monitor for bleeding.', 'Vigiar hemorragia no local de injeção, hematomas e hemograma.', 'Monitor injection-site bleeding, bruising and blood count.', 'Hematoma extenso, melenas, sangramento prolongado.', 'Large haematoma, melaena, prolonged bleeding.', 'DailyMed (FDA) — rótulo aprovado Enoxaparina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59 ; rótulo aprovado Aspirina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Enoxaparin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59 ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('enoxaparina', 'clopidogrel', 'moderate', 'A enoxaparina com clopidogrel aumenta o risco de hemorragia major.', 'Enoxaparin with clopidogrel increases the risk of major bleeding.', 'Anticoagulante (HBPM) + antiagregante (P2Y12), com hemorragia aditiva.', 'Anticoagulant (LMWH) + antiplatelet (P2Y12), with additive bleeding.', 'Utilizar com precaução em doentes com risco hemorrágico elevado; vigiar.', 'Use with caution in high bleeding-risk patients; monitor.', 'Vigiar hemograma e sinais clínicos de sangramento.', 'Monitor blood count and clinical signs of bleeding.', 'Hemorragia intracraniana ou gastrointestinal; equimoses espontâneas.', 'Intracranial or GI bleeding; spontaneous bruising.', 'DailyMed (FDA) — rótulo aprovado Enoxaparina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59 ; rótulo aprovado Clopidogrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Enoxaparin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59 ; approved Clopidogrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55731d95-0c99-ff61-e063-6394a90a1ab5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('rivaroxabano', 'warfarina', 'moderate', 'A transição entre rivaroxabano e varfarina requer sobreposição controlada; a toma simultânea prolongada aumenta a hemorragia.', 'Switching between rivaroxaban and warfarin requires controlled overlap; prolonged simultaneous use increases bleeding.', 'A sobreposição duplica a anticoagulação; o efeito do rivaroxabano sobrepõe-se à varfarina antes de esta atingir o INR-alvo.', 'Overlap doubles anticoagulation; rivaroxaban''s effect overlaps warfarin before it reaches the target INR.', 'Seguir o esquema de transição da SmPC: varfarina + rivaroxabano durante 2 dias até INR ≥ 2,0 (e vice-versa).', 'Follow the SmPC transition schedule: warfarin plus rivaroxaban for 2 days until INR ≥ 2.0 (and vice versa).', 'Monitorizar o INR conforme o protocolo de transição e sinais de hemorragia.', 'Monitor INR per the transition protocol and bleeding signs.', 'INR supra-terapêutico, hemorragia ativa durante a transição.', 'Supratherapeutic INR, active bleeding during transition.', 'DailyMed (FDA) — rótulo aprovado Rivaroxabano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Rivaroxaban label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=481b7802-5093-43e7-bbd9-1532197eb6e6 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dabigatrano', 'warfarina', 'moderate', 'A transição dabigatrano-varfarina deve ser feita com protocolo para evitar sub ou sobre-anticoagulação.', 'Dabigatran-warfarin transition should follow a protocol to avoid under- or over-anticoagulation.', 'A troca requer coordenação entre o efeito imediato do dabigatrano e o início retardado da varfarina.', 'Switching requires coordination between dabigatran''s immediate effect and warfarin''s delayed onset.', 'Seguir o esquema de transição da SmPC; ajustar com o INR.', 'Follow the SmPC transition schedule; adjust with the INR.', 'Monitorizar INR e sinais hemorrágicos durante a transição.', 'Monitor INR and bleeding signs during the transition.', 'INR supraterapêutico ou hemorragia na transição.', 'Supratherapeutic INR or bleeding during transition.', 'DailyMed (FDA) — rótulo aprovado Dabigatrano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dabigatran label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ferro', 'ciprofloxacina', 'moderate', 'O ferro reduz acentuadamente a absorção da ciprofloxacina por quelação.', 'Iron markedly reduces ciprofloxacin absorption through chelation.', 'Os catiões Fe2+/Fe3+ formam quelatos com a fluoroquinolona no trato gastrointestinal, reduzindo a sua biodisponibilidade.', 'Fe2+/Fe3+ cations chelate the fluoroquinolone in the GI tract, reducing its bioavailability.', 'Administrar a ciprofloxacina pelo menos 2 horas antes ou 4 horas depois do ferro.', 'Give ciprofloxacin at least 2 hours before or 4 hours after iron.', 'Vigiar a eficácia do antibiótico (sinais de infeção persistente).', 'Monitor antibiotic efficacy (signs of persistent infection).', 'Falência terapêutica da ciprofloxacina; infeção não resolvida.', 'Therapeutic failure of ciprofloxacin; unresolved infection.', 'DailyMed (FDA) — rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ferro', 'omeprazol', 'moderate', 'O omeprazol pode reduzir a absorção do ferro oral, sobretudo do ferro não-heme.', 'Omeprazole may reduce the absorption of oral iron, particularly non-heme iron.', 'A supressão ácida gástrica pelo IBP diminui a redução do Fe3+ a Fe2+, essencial para a absorção duodenal do ferro.', 'Gastric acid suppression by the PPI impairs the reduction of Fe3+ to Fe2+, essential for duodenal iron absorption.', 'Considerar monitorização da resposta ao ferro (hemoglobina, ferritina); separar horários de toma.', 'Consider monitoring the response to iron (haemoglobin, ferritin); separate administration times.', 'Vigiar a resposta terapêutica da anemia ferropénica.', 'Monitor the therapeutic response of iron-deficiency anaemia.', 'Persistência de anemia ferropénica apesar do tratamento.', 'Persistent iron-deficiency anaemia despite treatment.', 'DailyMed (FDA) — rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('fitomenadiona', 'warfarina', 'moderate', 'A fitomenadiona (vitamina K1) antagoniza o efeito anticoagulante da varfarina, reduzindo o INR.', 'Phytomenadione (vitamin K1) antagonises the anticoagulant effect of warfarin, lowering the INR.', 'A vitamina K repõe o substrato dos fatores II, VII, IX e X, revertendo o bloqueio da varfarina.', 'Vitamin K replenishes the substrate for factors II, VII, IX and X, reversing warfarin''s block.', 'Usar a vitamina K1 conforme indicação (reversão, correção de INR supraterapêutico); reavaliar o INR 24 h após.', 'Use vitamin K1 as indicated (reversal, correction of supratherapeutic INR); reassess INR 24 h after.', 'Monitorizar o INR e sinais de trombose após a reversão.', 'Monitor INR and signs of thrombosis after reversal.', 'INR subterapêutico ou eventos trombóticos após reversão excessiva.', 'Subtherapeutic INR or thrombotic events after excessive reversal.', 'DailyMed (FDA) — rótulo aprovado Fitomenadiona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c7ef968-2c76-4220-a9ec-3179d243c422 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Phytomenadione label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c7ef968-2c76-4220-a9ec-3179d243c422 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('acido_folico', 'ciprofloxacina', 'minor', 'Associação geralmente sem interação relevante; pode manter-se a terapêutica habitual.', 'The combination is generally safe with no relevant interaction; usual therapy can be maintained.', 'Sem mecanismo de interação conhecido entre folato e fluoroquinolonas.', 'No known interaction mechanism between folate and fluoroquinolones.', 'Sem necessidade de ajuste posológico.', 'No dose adjustment needed.', 'Sem monitorização adicional específica.', 'No specific additional monitoring.', 'Sem sinais de alerta específicos.', 'No specific red flags.', 'DailyMed (FDA) — rótulo aprovado Ácido fólico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0baa10dd-6d1d-4946-8236-566451132da3 ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Folic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0baa10dd-6d1d-4946-8236-566451132da3 ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('cianocobalamina', 'omeprazol', 'minor', 'O uso prolongado de omeprazol pode reduzir a absorção da vitamina B12 alimentar, mas raramente afeta a cianocobalamina suplementar.', 'Long-term omeprazole may reduce absorption of dietary vitamin B12, but rarely affects supplemental cyanocobalamin.', 'A hipocloridria prolongada pelo IBP reduz a libertação da B12 ligada às proteínas alimentares.', 'PPI-induced prolonged hypochlorhydria reduces release of food-bound B12.', 'Em uso prolongado de IBP, vigiar níveis de B12 em doentes de risco.', 'With long-term PPI use, monitor B12 levels in at-risk patients.', 'Vigiar hemograma e níveis de B12 em doentes idosos ou malnutridos.', 'Monitor blood count and B12 levels in elderly or malnourished patients.', 'Anemia macrocítica ou sintomas neuropáticos persistentes.', 'Macrocytic anaemia or persistent neuropathic symptoms.', 'DailyMed (FDA) — rótulo aprovado Cianocobalamina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3bb870d8-128d-75ea-e063-6394a90a707b ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Cyanocobalamin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3bb870d8-128d-75ea-e063-6394a90a707b ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('epoetina_alfa', 'warfarina', 'moderate', 'A epoetina alfa pode alterar a resposta à varfarina; vigiar o INR quando se ajusta a dose de eritropoietina.', 'Epoetin alfa may alter the response to warfarin; monitor INR when the erythropoietin dose is adjusted.', 'A melhoria da eritropoiese e a variação do hematócrito podem alterar a farmacodinâmica da varfarina.', 'Improved erythropoiesis and haematocrit changes may alter warfarin pharmacodynamics.', 'Monitorizar o INR com maior frequência ao iniciar ou ajustar a epoetina.', 'Monitor INR more frequently when starting or adjusting epoetin.', 'Vigiar INR e sinais de hemorragia ou trombose.', 'Monitor INR and signs of bleeding or thrombosis.', 'INR instável, eventos trombóticos (trombose de acesso vascular).', 'Unstable INR, thrombotic events (vascular access thrombosis).', 'DailyMed (FDA) — rótulo aprovado Epoetina alfa: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f2d0b28-9cc5-4523-80b8-637fdaf3f7a5 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Epoetin alfa label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f2d0b28-9cc5-4523-80b8-637fdaf3f7a5 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('acido_tranexamico', 'enoxaparina', 'moderate', 'O ácido tranexâmico combinado com enoxaparina aumenta o risco trombótico; avaliar criteriosamente a indicação.', 'Tranexamic acid combined with enoxaparin increases thrombotic risk; assess the indication carefully.', 'O antifibrinolítico reduz a lise do coágulo enquanto a HBPM acentua a anticoagulação; o balanço é paradoxal e o risco trombótico aditivo em doentes de risco.', 'The antifibrinolytic reduces clot lysis while LMWH enhances anticoagulation; the balance is paradoxical and thrombotic risk is additive in at-risk patients.', 'Usar apenas quando a hemorragia supera o risco trombótico; vigiar sinais de trombose.', 'Use only when bleeding outweighs thrombotic risk; monitor for signs of thrombosis.', 'Vigiar sinais de TVP, embolia pulmonar e hemorragia.', 'Monitor for signs of DVT, pulmonary embolism and bleeding.', 'Dor ou edema de membro, dispneia súbita, hemorragia persistente.', 'Limb pain or swelling, sudden dyspnoea, persistent bleeding.', 'DailyMed (FDA) — rótulo aprovado Ácido tranexâmico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4877eacd-fda7-4708-93a5-81052c1d2e14 ; rótulo aprovado Enoxaparina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Tranexamic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4877eacd-fda7-4708-93a5-81052c1d2e14 ; approved Enoxaparin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)')
) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('ferro', 'cafe_cha', 'Café, chá e outras bebidas com taninos', 'Coffee, tea and tannin-containing drinks', 'moderate', 'Os taninos do café e do chá formam complexos insolúveis com o ferro e reduzem a sua absorção oral.', 'Tannins in coffee and tea form insoluble complexes with iron and reduce its oral absorption.', 'Tomar o ferro pelo menos 1 a 2 horas antes ou depois de café, chá ou bebidas ricas em taninos.', 'Take iron at least 1 to 2 hours before or after coffee, tea or tannin-rich drinks.', 'EMC-UK (MHRA) — SmPC aprovada Ferro: https://www.medicines.org.uk/emc/product/102243/smpc', 'EMC-UK (MHRA) — approved Iron SmPC: https://www.medicines.org.uk/emc/product/102243/smpc', 1),
  ('ferro', 'leite_lacticinios', 'Leite e lacticínios (cálcio)', 'Milk and dairy products (calcium)', 'moderate', 'O cálcio do leite e dos lacticínios compete com o ferro no transporte intestinal, reduzindo a sua absorção.', 'Calcium in milk and dairy competes with iron for intestinal transport, reducing its absorption.', 'Evitar tomar o ferro com leite, iogurte ou queijo; separar as tomas por 2 horas.', 'Avoid taking iron with milk, yoghurt or cheese; separate doses by 2 hours.', 'EMC-UK (MHRA) — SmPC aprovada Ferro: https://www.medicines.org.uk/emc/product/102243/smpc', 'EMC-UK (MHRA) — approved Iron SmPC: https://www.medicines.org.uk/emc/product/102243/smpc', 1),
  ('ferro', 'alimentos_ricos_calcio', 'Alimentos ricos em cálcio', 'Calcium-rich foods', 'moderate', 'Refeições ricas em cálcio diminuem a absorção do ferro, sobretudo do ferro não-heme.', 'Calcium-rich meals decrease iron absorption, mainly non-heme iron.', 'Separar o ferro das refeições ricas em cálcio (2 horas).', 'Separate iron from calcium-rich meals (2 hours).', 'EMC-UK (MHRA) — SmPC aprovada Ferro: https://www.medicines.org.uk/emc/product/102243/smpc', 'EMC-UK (MHRA) — approved Iron SmPC: https://www.medicines.org.uk/emc/product/102243/smpc', 1),
  ('acido_folico', 'alcool', 'Álcool (consumo crónico)', 'Alcohol (chronic use)', 'moderate', 'O consumo crónico de álcool interfere com o metabolismo e a absorção do folato, podendo agravar a deficiência.', 'Chronic alcohol use interferes with folate metabolism and absorption, potentially worsening deficiency.', 'Limitar o consumo de álcool durante o tratamento com ácido fólico.', 'Limit alcohol intake during folic acid treatment.', 'EMC-UK (MHRA) — SmPC aprovada Ácido fólico: https://www.medicines.org.uk/emc/product/6998/smpc', 'EMC-UK (MHRA) — approved Folic acid SmPC: https://www.medicines.org.uk/emc/product/6998/smpc', 1),
  ('cianocobalamina', 'alcool', 'Álcool (consumo crónico)', 'Alcohol (chronic use)', 'minor', 'O alcoolismo crónico pode reduzir a absorção da vitamina B12 alimentar, mas afeta pouco a cianocobalamina oral em dose terapêutica.', 'Chronic alcoholism may reduce absorption of dietary vitamin B12, but it little affects oral cyanocobalamin at therapeutic doses.', 'Em doentes com alcoolismo, vigiar os níveis de B12 e considerar doses mais altas se necessário.', 'In patients with alcoholism, monitor B12 levels and consider higher doses if needed.', 'EMC-UK (MHRA) — SmPC aprovada Cianocobalamina: https://www.medicines.org.uk/emc/product/5716/smpc', 'EMC-UK (MHRA) — approved Cyanocobalamin SmPC: https://www.medicines.org.uk/emc/product/5716/smpc', 1),
  ('apixabano', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O consumo de álcool pode aumentar o risco hemorrágico e interagir com a anticoagulação.', 'Alcohol intake may increase bleeding risk and interact with anticoagulation.', 'Limitar o consumo de álcool durante o tratamento com apixabano.', 'Limit alcohol intake during apixaban treatment.', 'EMC-UK (MHRA) — SmPC aprovada Apixabano: https://www.medicines.org.uk/emc/product/102130/smpc', 'EMC-UK (MHRA) — approved Apixaban SmPC: https://www.medicines.org.uk/emc/product/102130/smpc', 1),
  ('rivaroxabano', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta o risco de hemorragia em doentes anticoagulados com rivaroxabano.', 'Alcohol increases the bleeding risk in patients anticoagulated with rivaroxaban.', 'Limitar o consumo de álcool durante o tratamento.', 'Limit alcohol intake during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Rivaroxabano: https://www.medicines.org.uk/emc/product/100864/smpc', 'EMC-UK (MHRA) — approved Rivaroxaban SmPC: https://www.medicines.org.uk/emc/product/100864/smpc', 1),
  ('dabigatrano', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool pode potenciar o risco hemorrágico do dabigatrano.', 'Alcohol may potentiate the bleeding risk of dabigatran.', 'Limitar o consumo de álcool durante o tratamento.', 'Limit alcohol intake during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Dabigatrano: https://www.medicines.org.uk/emc/product/100715/smpc', 'EMC-UK (MHRA) — approved Dabigatran SmPC: https://www.medicines.org.uk/emc/product/100715/smpc', 1),
  ('dabigatrano', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'O dabigatrano deve ser tomado com água, com ou sem alimentos; a toma com refeição não altera significativamente a absorção.', 'Dabigatran should be taken with water, with or without food; taking it with a meal does not significantly change absorption.', 'Tomar as cápsulas inteiras com água, sem abrir.', 'Swallow the capsules whole with water, without opening them.', 'EMC-UK (MHRA) — SmPC aprovada Dabigatrano: https://www.medicines.org.uk/emc/product/100715/smpc', 'EMC-UK (MHRA) — approved Dabigatran SmPC: https://www.medicines.org.uk/emc/product/100715/smpc', 1),
  ('enoxaparina', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta o risco hemorrágico em doentes tratados com enoxaparina.', 'Alcohol increases the bleeding risk in patients treated with enoxaparin.', 'Limitar o consumo de álcool durante o tratamento.', 'Limit alcohol intake during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Enoxaparina: https://www.medicines.org.uk/emc/product/9329/smpc', 'EMC-UK (MHRA) — approved Enoxaparin SmPC: https://www.medicines.org.uk/emc/product/9329/smpc', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('apixabano', 'hemorragia_ativa', 'Hemorragia ativa clinicamente significativa', 'Clinically significant active bleeding', 'contraindication', 'critical', 'O apixabano é um anticoagulante e está contraindicado em hemorragia ativa clinicamente significativa.', 'Apixaban is an anticoagulant and is contraindicated in clinically significant active bleeding.', 'Não usar em doentes com hemorragia ativa; procurar a causa e tratar a hemorragia.', 'Do not use in patients with active bleeding; investigate the cause and treat the bleeding.', 'EMC-UK (MHRA) — SmPC aprovada Apixabano: https://www.medicines.org.uk/emc/product/102130/smpc', 'EMC-UK (MHRA) — approved Apixaban SmPC: https://www.medicines.org.uk/emc/product/102130/smpc', 1),
  ('apixabano', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave (Child-Pugh C)', 'Severe hepatic impairment (Child-Pugh C)', 'contraindication', 'critical', 'O apixabano está contraindicado em insuficiência hepática grave, pela alteração da coagulação e do metabolismo do fármaco.', 'Apixaban is contraindicated in severe hepatic impairment because of altered coagulation and drug metabolism.', 'Não usar em Child-Pugh C; avaliar a função hepática antes de iniciar.', 'Do not use in Child-Pugh C; assess liver function before starting.', 'EMC-UK (MHRA) — SmPC aprovada Apixabano: https://www.medicines.org.uk/emc/product/102130/smpc', 'EMC-UK (MHRA) — approved Apixaban SmPC: https://www.medicines.org.uk/emc/product/102130/smpc', 1),
  ('rivaroxabano', 'hemorragia_ativa', 'Hemorragia ativa clinicamente significativa', 'Clinically significant active bleeding', 'contraindication', 'critical', 'O rivaroxabano está contraindicado em hemorragia ativa clinicamente significativa.', 'Rivaroxaban is contraindicated in clinically significant active bleeding.', 'Não usar em doentes com hemorragia ativa.', 'Do not use in patients with active bleeding.', 'EMC-UK (MHRA) — SmPC aprovada Rivaroxabano: https://www.medicines.org.uk/emc/product/100864/smpc', 'EMC-UK (MHRA) — approved Rivaroxaban SmPC: https://www.medicines.org.uk/emc/product/100864/smpc', 1),
  ('rivaroxabano', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave (Child-Pugh C)', 'Severe hepatic impairment (Child-Pugh C)', 'contraindication', 'critical', 'O rivaroxabano está contraindicado em doença hepática com coagulopatia e risco hemorrágico clinicamente relevante.', 'Rivaroxaban is contraindicated in hepatic disease with coagulopathy and a clinically relevant bleeding risk.', 'Não usar em Child-Pugh C ou coagulopatia associada.', 'Do not use in Child-Pugh C or associated coagulopathy.', 'EMC-UK (MHRA) — SmPC aprovada Rivaroxabano: https://www.medicines.org.uk/emc/product/100864/smpc', 'EMC-UK (MHRA) — approved Rivaroxaban SmPC: https://www.medicines.org.uk/emc/product/100864/smpc', 1),
  ('dabigatrano', 'hemorragia_ativa', 'Hemorragia ativa clinicamente significativa', 'Clinically significant active bleeding', 'contraindication', 'critical', 'O dabigatrano está contraindicado em hemorragia ativa clinicamente significativa.', 'Dabigatran is contraindicated in clinically significant active bleeding.', 'Não usar em doentes com hemorragia ativa.', 'Do not use in patients with active bleeding.', 'EMC-UK (MHRA) — SmPC aprovada Dabigatrano: https://www.medicines.org.uk/emc/product/100715/smpc', 'EMC-UK (MHRA) — approved Dabigatran SmPC: https://www.medicines.org.uk/emc/product/100715/smpc', 1),
  ('dabigatrano', 'insuficiencia_renal_grave', 'Insuficiência renal grave (CrCl < 30 ml/min)', 'Severe renal impairment (CrCl < 30 ml/min)', 'contraindication', 'critical', 'O dabigatrano é eliminado sobretudo por via renal; em insuficiência renal grave a exposição aumenta muito e o risco hemorrágico é elevado.', 'Dabigatran is predominantly renally eliminated; in severe renal impairment exposure increases markedly and bleeding risk is high.', 'Não usar com CrCl < 30 ml/min; avaliar a função renal antes de iniciar.', 'Do not use with CrCl < 30 ml/min; assess renal function before starting.', 'EMC-UK (MHRA) — SmPC aprovada Dabigatrano: https://www.medicines.org.uk/emc/product/100715/smpc', 'EMC-UK (MHRA) — approved Dabigatran SmPC: https://www.medicines.org.uk/emc/product/100715/smpc', 1),
  ('enoxaparina', 'trombocitopenia_hir', 'Trombocitopenia induzida por heparina (TIH)', 'Heparin-induced thrombocytopenia (HIT)', 'contraindication', 'critical', 'A enoxaparina está contraindicada em doentes com TIH (atual ou prévia), pelo risco de trombose mediada por anticorpos.', 'Enoxaparin is contraindicated in HIT (current or previous) because of the risk of antibody-mediated thrombosis.', 'Não usar enoxaparina (ou outras HBPM/heparinas) em TIH; considerar anticoagulante alternativo.', 'Do not use enoxaparin (or other LMWH/heparins) in HIT; consider an alternative anticoagulant.', 'EMC-UK (MHRA) — SmPC aprovada Enoxaparina: https://www.medicines.org.uk/emc/product/9329/smpc', 'EMC-UK (MHRA) — approved Enoxaparin SmPC: https://www.medicines.org.uk/emc/product/9329/smpc', 1),
  ('enoxaparina', 'insuficiencia_renal_grave', 'Insuficiência renal grave (CrCl < 30 ml/min)', 'Severe renal impairment (CrCl < 30 ml/min)', 'contraindication', 'critical', 'A eliminação da enoxaparina é renal; em CrCl < 30 ml/min o risco de acumulação e hemorragia é elevado.', 'Enoxaparin elimination is renal; at CrCl < 30 ml/min the risk of accumulation and bleeding is high.', 'Em CrCl < 30 ml/min, usar com precaução extrema ou alternativa; ajustar a dose conforme a SmPC.', 'At CrCl < 30 ml/min, use with extreme caution or an alternative; adjust the dose per the SmPC.', 'EMC-UK (MHRA) — SmPC aprovada Enoxaparina: https://www.medicines.org.uk/emc/product/9329/smpc', 'EMC-UK (MHRA) — approved Enoxaparin SmPC: https://www.medicines.org.uk/emc/product/9329/smpc', 1),
  ('fondaparinux', 'insuficiencia_renal_grave', 'Insuficiência renal grave (CrCl < 30 ml/min)', 'Severe renal impairment (CrCl < 30 ml/min)', 'contraindication', 'critical', 'O fondaparinux é eliminado por via renal e está contraindicado em CrCl < 30 ml/min.', 'Fondaparinux is renally eliminated and is contraindicated at CrCl < 30 ml/min.', 'Não usar com CrCl < 30 ml/min; avaliar a função renal antes do início.', 'Do not use at CrCl < 30 ml/min; assess renal function before starting.', 'EMC-UK (MHRA) — SmPC aprovada Fondaparinux: https://www.medicines.org.uk/emc/product/3340/smpc', 'EMC-UK (MHRA) — approved Fondaparinux SmPC: https://www.medicines.org.uk/emc/product/3340/smpc', 1),
  ('epoetina_alfa', 'hipertensao_nao_controlada', 'Hipertensão não controlada', 'Uncontrolled hypertension', 'contraindication', 'critical', 'A epoetina alfa está contraindicada em hipertensão não controlada, pelo risco de crise hipertensiva e encefalopatia.', 'Epoetin alfa is contraindicated in uncontrolled hypertension because of the risk of hypertensive crisis and encephalopathy.', 'Não iniciar com tensão arterial não controlada; tratar a hipertensão antes.', 'Do not start with uncontrolled blood pressure; treat hypertension first.', 'EMC-UK (MHRA) — SmPC aprovada Epoetina alfa: https://www.medicines.org.uk/emc/product/3443/smpc', 'EMC-UK (MHRA) — approved Epoetin alfa SmPC: https://www.medicines.org.uk/emc/product/3443/smpc', 1),
  ('ferro', 'hemocromatose', 'Hemocromatose / sobrecarga de ferro', 'Haemochromatosis / iron overload', 'contraindication', 'critical', 'A suplementação de ferro está contraindicada em sobrecarga de ferro (hemocromatose) e anemias não ferropénicas com sobrecarga.', 'Iron supplementation is contraindicated in iron overload (haemochromatosis) and non-iron-deficiency anaemias with overload.', 'Não administrar ferro em doentes com hemocromatose ou sobrecarga; confirmar o diagnóstico de ferropenia.', 'Do not give iron in haemochromatosis or overload; confirm iron-deficiency diagnosis.', 'EMC-UK (MHRA) — SmPC aprovada Ferro: https://www.medicines.org.uk/emc/product/102243/smpc', 'EMC-UK (MHRA) — approved Iron SmPC: https://www.medicines.org.uk/emc/product/102243/smpc', 1),
  ('acido_tranexamico', 'trombose_ativa', 'Trombose venosa/arterial ativa', 'Active venous/arterial thrombosis', 'contraindication', 'critical', 'O ácido tranexâmico está contraindicado em trombose ativa e em doentes com antecedentes de tromboembolismo, pelo seu efeito antifibrinolítico.', 'Tranexamic acid is contraindicated in active thrombosis and in patients with a history of thromboembolism because of its antifibrinolytic effect.', 'Não usar em trombose ativa; avaliar o risco trombótico antes de iniciar.', 'Do not use in active thrombosis; assess thrombotic risk before starting.', 'EMC-UK (MHRA) — SmPC aprovada Ácido tranexâmico: https://www.medicines.org.uk/emc/product/1077/smpc', 'EMC-UK (MHRA) — approved Tranexamic acid SmPC: https://www.medicines.org.uk/emc/product/1077/smpc', 1),
  ('aspirina', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'contraindication', 'critical', 'A aspirina está contraindicada em úlcera péptica ativa e em hemorragia gastrointestinal ativa, pelo risco de agravamento.', 'Aspirin is contraindicated in active peptic ulcer and active GI bleeding because of the risk of worsening.', 'Não usar em úlcera ativa; considerar antiagregante alternativo após avaliação.', 'Do not use in active ulcer; consider an alternative antiplatelet after assessment.', 'EMC-UK (MHRA) — SmPC aprovada Aspirina: https://www.medicines.org.uk/emc/product/102206/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/102206/smpc', 1),
  ('aspirina', 'asma_aine', 'Asma induzida por AINE', 'NSAID-induced asthma', 'contraindication', 'critical', 'A aspirina pode desencadear broncospasmo grave em doentes com asma induzida por AINE.', 'Aspirin may trigger severe bronchospasm in patients with NSAID-induced asthma.', 'Não usar aspirina em doentes com história de asma/urticária por AINE.', 'Do not use aspirin in patients with a history of NSAID-induced asthma/urticaria.', 'EMC-UK (MHRA) — SmPC aprovada Aspirina: https://www.medicines.org.uk/emc/product/102206/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/102206/smpc', 1),
  ('clopidogrel', 'hemorragia_ativa', 'Hemorragia ativa clinicamente significativa', 'Clinically significant active bleeding', 'contraindication', 'critical', 'O clopidogrel está contraindicado em hemorragia ativa clinicamente significativa, pelo seu efeito antiagregante.', 'Clopidogrel is contraindicated in clinically significant active bleeding because of its antiplatelet effect.', 'Não usar em hemorragia ativa; tratar a causa da hemorragia.', 'Do not use in active bleeding; treat the cause of bleeding.', 'EMC-UK (MHRA) — SmPC aprovada Clopidogrel: https://www.medicines.org.uk/emc/product/5207/smpc', 'EMC-UK (MHRA) — approved Clopidogrel SmPC: https://www.medicines.org.uk/emc/product/5207/smpc', 1),
  ('clopidogrel', 'ulcera_peptica_ativa', 'Úlcera péptica ativa / hemorragia GI recente', 'Active peptic ulcer / recent GI bleeding', 'precaution', 'moderate', 'O clopidogrel aumenta o risco de hemorragia gastrointestinal em doentes com úlcera péptica ou hemorragia GI recente.', 'Clopidogrel increases the risk of GI bleeding in patients with peptic ulcer or recent GI bleeding.', 'Considerar protetor gástrico (IBP) durante o tratamento; vigiar sinais de hemorragia.', 'Consider a gastroprotectant (PPI) during treatment; monitor for bleeding signs.', 'EMC-UK (MHRA) — SmPC aprovada Clopidogrel: https://www.medicines.org.uk/emc/product/5207/smpc', 'EMC-UK (MHRA) — approved Clopidogrel SmPC: https://www.medicines.org.uk/emc/product/5207/smpc', 1),
  ('epoetina_alfa', 'doenca_cardiovascular', 'Doença cardiovascular (enfarte, AVC)', 'Cardiovascular disease (MI, stroke)', 'precaution', 'moderate', 'A epoetina alfa aumenta o risco de eventos trombóticos e cardiovasculares; usar com precaução em doença cardiovascular.', 'Epoetin alfa increases the risk of thrombotic and cardiovascular events; use with caution in cardiovascular disease.', 'Vigiar a hemoglobina (não exceder os alvos da SmPC), a tensão arterial e os sinais de trombose.', 'Monitor haemoglobin (do not exceed SmPC targets), blood pressure and signs of thrombosis.', 'EMC-UK (MHRA) — SmPC aprovada Epoetina alfa: https://www.medicines.org.uk/emc/product/3443/smpc', 'EMC-UK (MHRA) — approved Epoetin alfa SmPC: https://www.medicines.org.uk/emc/product/3443/smpc', 1),
  ('ferro', 'anemia_nao_diagnosticada', 'Anemia sem diagnóstico etiológico', 'Anaemia without an established cause', 'precaution', 'moderate', 'O ferro pode mascarar outras causas de anemia; deve confirmar-se a ferropenia antes do tratamento.', 'Iron may mask other causes of anaemia; iron deficiency should be confirmed before treatment.', 'Confirmar a ferropenia (ferritina, saturação da transferrina) antes de suplementar.', 'Confirm iron deficiency (ferritin, transferrin saturation) before supplementing.', 'EMC-UK (MHRA) — SmPC aprovada Ferro: https://www.medicines.org.uk/emc/product/102243/smpc', 'EMC-UK (MHRA) — approved Iron SmPC: https://www.medicines.org.uk/emc/product/102243/smpc', 1),
  ('acido_folico', 'anemia_nao_diagnosticada', 'Anemia sem diagnóstico etiológico', 'Anaemia without an established cause', 'precaution', 'moderate', 'O ácido fólico pode corrigir a macrocitose e mascarar uma deficiência de vitamina B12 não diagnosticada.', 'Folic acid may correct macrocytosis and mask an undiagnosed vitamin B12 deficiency.', 'Excluir deficiência de B12 antes de iniciar ácido fólico em doentes com anemia macrocítica.', 'Rule out B12 deficiency before starting folic acid in patients with macrocytic anaemia.', 'EMC-UK (MHRA) — SmPC aprovada Ácido fólico: https://www.medicines.org.uk/emc/product/6998/smpc', 'EMC-UK (MHRA) — approved Folic acid SmPC: https://www.medicines.org.uk/emc/product/6998/smpc', 1),
  ('cianocobalamina', 'doenca_de_leber', 'Doença de Leber (atrofia ótica hereditária)', 'Leber''s disease (hereditary optic atrophy)', 'contraindication', 'critical', 'A cianocobalamina está contraindicada na doença de Leber, pelo risco de agravamento da atrofia ótica.', 'Cyanocobalamin is contraindicated in Leber''s disease because of the risk of worsening optic atrophy.', 'Não usar cianocobalamina em doentes com doença de Leber; considerar hidroxocobalamina se necessário.', 'Do not use cyanocobalamin in Leber''s disease; consider hydroxocobalamin if needed.', 'EMC-UK (MHRA) — SmPC aprovada Cianocobalamina: https://www.medicines.org.uk/emc/product/5716/smpc', 'EMC-UK (MHRA) — approved Cyanocobalamin SmPC: https://www.medicines.org.uk/emc/product/5716/smpc', 1),
  ('fitomenadiona', 'deficiencia_g6pd', 'Défice de glicose-6-fosfato desidrogenase', 'Glucose-6-phosphate dehydrogenase deficiency', 'precaution', 'moderate', 'Doses elevadas de fitomenadiona podem precipitar hemólise em doentes com défice de G6PD.', 'High doses of phytomenadione may precipitate haemolysis in patients with G6PD deficiency.', 'Usar com precaução em défice de G6PD; vigiar sinais de hemólise.', 'Use with caution in G6PD deficiency; monitor for signs of haemolysis.', 'EMC-UK (MHRA) — SmPC aprovada Fitomenadiona: https://www.medicines.org.uk/emc/product/9755/smpc', 'EMC-UK (MHRA) — approved Phytomenadione SmPC: https://www.medicines.org.uk/emc/product/9755/smpc', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('ferro', 'compatible', 'O ferro é um nutriente essencial na gravidez; a suplementação é segura nas doses recomendadas.', 'Iron is an essential nutrient in pregnancy; supplementation is safe at recommended doses.', 'Pode ser usado em todos os trimestres, nas doses recomendadas para a prevenção/tratamento da ferropenia.', 'Can be used in all trimesters at recommended doses for prevention/treatment of iron deficiency.', 'O ferro é excretado no leite em pequenas quantidades, sem risco relevante para o lactente.', 'Iron is excreted into breast milk in small amounts, with no relevant risk to the infant.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Ferro: https://www.medicines.org.uk/emc/product/102243/smpc', 'EMC-UK (MHRA) — approved Iron SmPC: https://www.medicines.org.uk/emc/product/102243/smpc'),
  ('acido_folico', 'compatible', 'O ácido fólico é recomendado antes e durante a gravidez para prevenção de defeitos do tubo neural.', 'Folic acid is recommended before and during pregnancy to prevent neural tube defects.', 'Suplementar 400-800 µg/dia na pré-conceção e 1.º trimestre (doses maiores em risco elevado).', 'Supplement 400-800 µg/day preconception and in the 1st trimester (higher doses at high risk).', 'Excretado no leite; seguro durante o aleitamento.', 'Excreted into breast milk; safe during breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Ácido fólico: https://www.medicines.org.uk/emc/product/6998/smpc', 'EMC-UK (MHRA) — approved Folic acid SmPC: https://www.medicines.org.uk/emc/product/6998/smpc'),
  ('cianocobalamina', 'compatible', 'A cianocobalamina pode ser usada na gravidez quando a deficiência de B12 a justifica.', 'Cyanocobalamin can be used in pregnancy when B12 deficiency justifies it.', 'Usar nas doses terapêuticas habituais; a deficiência não tratada é prejudicial ao feto.', 'Use at the usual therapeutic doses; untreated deficiency is harmful to the fetus.', 'Excretada no leite materno; compatível com o aleitamento.', 'Excreted into breast milk; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Cianocobalamina: https://www.medicines.org.uk/emc/product/5716/smpc', 'EMC-UK (MHRA) — approved Cyanocobalamin SmPC: https://www.medicines.org.uk/emc/product/5716/smpc'),
  ('epoetina_alfa', 'caution', 'Os dados sobre epoetina alfa na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on epoetin alfa in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar no 1.º trimestre; usar apenas se estritamente necessário (ex.: anemia grave da doença renal).', 'Avoid in the 1st trimester; use only if strictly necessary (e.g. severe anaemia of kidney disease).', 'Não se conhece a excreção no leite; usar com precaução.', 'Excretion into breast milk is unknown; use with caution.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar tratamento prolongado.', 'In women of childbearing age, rule out pregnancy before starting long-term treatment.', 'EMC-UK (MHRA) — SmPC aprovada Epoetina alfa: https://www.medicines.org.uk/emc/product/3443/smpc', 'EMC-UK (MHRA) — approved Epoetin alfa SmPC: https://www.medicines.org.uk/emc/product/3443/smpc'),
  ('filgrastim', 'caution', 'Os dados sobre filgrastim na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on filgrastim in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar na gravidez exceto em situações com indicação clara (ex.: neutropenia grave).', 'Avoid in pregnancy except in clearly indicated situations (e.g. severe neutropenia).', 'Não se conhece a excreção no leite; evitar durante o aleitamento.', 'Excretion into breast milk is unknown; avoid during breastfeeding.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar.', 'In women of childbearing age, rule out pregnancy before starting.', 'EMC-UK (MHRA) — SmPC aprovada Filgrastim: https://www.medicines.org.uk/emc/product/3000/smpc', 'EMC-UK (MHRA) — approved Filgrastim SmPC: https://www.medicines.org.uk/emc/product/3000/smpc'),
  ('apixabano', 'contraindicated', 'O apixabano está contraindicado na gravidez: os anticoagulantes orais diretos podem causar hemorragia materno-fetal.', 'Apixaban is contraindicated in pregnancy: direct oral anticoagulants may cause maternal-fetal bleeding.', 'Não usar na gravidez; usar HBPM quando anticoagulação for necessária.', 'Do not use in pregnancy; use LMWH when anticoagulation is needed.', 'Contraindicado durante o aleitamento.', 'Contraindicated during breastfeeding.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Apixabano: https://www.medicines.org.uk/emc/product/102130/smpc', 'EMC-UK (MHRA) — approved Apixaban SmPC: https://www.medicines.org.uk/emc/product/102130/smpc'),
  ('rivaroxabano', 'contraindicated', 'O rivaroxabano está contraindicado na gravidez, pelo risco hemorrágico para a mãe e o feto.', 'Rivaroxaban is contraindicated in pregnancy because of the bleeding risk for the mother and fetus.', 'Não usar na gravidez; usar HBPM quando anticoagulação for necessária.', 'Do not use in pregnancy; use LMWH when anticoagulation is needed.', 'Contraindicado durante o aleitamento.', 'Contraindicated during breastfeeding.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Rivaroxabano: https://www.medicines.org.uk/emc/product/100864/smpc', 'EMC-UK (MHRA) — approved Rivaroxaban SmPC: https://www.medicines.org.uk/emc/product/100864/smpc'),
  ('dabigatrano', 'contraindicated', 'O dabigatrano está contraindicado na gravidez, pelo risco hemorrágico e falta de dados de segurança.', 'Dabigatran is contraindicated in pregnancy because of the bleeding risk and lack of safety data.', 'Não usar na gravidez; usar HBPM quando anticoagulação for necessária.', 'Do not use in pregnancy; use LMWH when anticoagulation is needed.', 'Contraindicado durante o aleitamento.', 'Contraindicated during breastfeeding.', 'Mulheres em idade fértil devem utilizar contraceção eficaz durante o tratamento.', 'Women of childbearing age must use effective contraception during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Dabigatrano: https://www.medicines.org.uk/emc/product/100715/smpc', 'EMC-UK (MHRA) — approved Dabigatran SmPC: https://www.medicines.org.uk/emc/product/100715/smpc'),
  ('enoxaparina', 'caution', 'A enoxaparina é a anticoagulação de escolha na gravidez quando indicada; usar sob supervisão médica.', 'Enoxaparin is the anticoagulant of choice in pregnancy when indicated; use under medical supervision.', 'Pode ser usada nos trimestres em que a anticoagulação é necessária, com monitorização (anti-Xa se indicado).', 'Can be used in the trimesters in which anticoagulation is needed, with monitoring (anti-Xa if indicated).', 'A enoxaparina não é excretada em quantidade relevante no leite; compatível com o aleitamento.', 'Enoxaparin is not excreted in significant amounts into breast milk; compatible with breastfeeding.', 'Sem contraceção adicional específica; a indicação anticoagulante domina.', 'No specific additional contraception; the anticoagulant indication dominates.', 'EMC-UK (MHRA) — SmPC aprovada Enoxaparina: https://www.medicines.org.uk/emc/product/9329/smpc', 'EMC-UK (MHRA) — approved Enoxaparin SmPC: https://www.medicines.org.uk/emc/product/9329/smpc'),
  ('fondaparinux', 'caution', 'Os dados sobre fondaparinux na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on fondaparinux in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar na gravidez exceto se estritamente necessário.', 'Avoid in pregnancy unless strictly necessary.', 'Não se conhece a excreção no leite; usar com precaução.', 'Excretion into breast milk is unknown; use with caution.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar.', 'In women of childbearing age, rule out pregnancy before starting.', 'EMC-UK (MHRA) — SmPC aprovada Fondaparinux: https://www.medicines.org.uk/emc/product/3340/smpc', 'EMC-UK (MHRA) — approved Fondaparinux SmPC: https://www.medicines.org.uk/emc/product/3340/smpc'),
  ('acido_tranexamico', 'caution', 'O ácido tranexâmico atravessa a placenta; os dados são limitados e a utilização deve ser criteriosa.', 'Tranexamic acid crosses the placenta; data are limited and use should be judicious.', 'Usar apenas se o benefício superar o risco (ex.: hemorragia grave no pós-parto).', 'Use only if the benefit outweighs the risk (e.g. severe postpartum haemorrhage).', 'Excretado no leite em pequenas quantidades; a utilização pontual é compatível.', 'Excreted into breast milk in small amounts; occasional use is compatible.', 'Em idade fértil, documentar a decisão de tratar.', 'In women of childbearing age, document the decision to treat.', 'EMC-UK (MHRA) — SmPC aprovada Ácido tranexâmico: https://www.medicines.org.uk/emc/product/1077/smpc', 'EMC-UK (MHRA) — approved Tranexamic acid SmPC: https://www.medicines.org.uk/emc/product/1077/smpc'),
  ('fitomenadiona', 'compatible', 'A fitomenadiona é usada na profilaxia da doença hemorrágica do recém-nascido; é segura nas doses recomendadas.', 'Phytomenadione is used for prophylaxis of haemorrhagic disease of the newborn; it is safe at recommended doses.', 'Pode ser usada na gravidez quando indicada (ex.: deficiência de vitamina K materna).', 'Can be used in pregnancy when indicated (e.g. maternal vitamin K deficiency).', 'Excretada no leite; a suplementação materna não é problemática.', 'Excreted into breast milk; maternal supplementation is not problematic.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Fitomenadiona: https://www.medicines.org.uk/emc/product/9755/smpc', 'EMC-UK (MHRA) — approved Phytomenadione SmPC: https://www.medicines.org.uk/emc/product/9755/smpc'),
  ('aspirina', 'caution', 'A aspirina em dose baixa pode ser usada na gravidez quando indicada (ex.: pré-eclâmpsia); doses elevadas devem ser evitadas.', 'Low-dose aspirin can be used in pregnancy when indicated (e.g. pre-eclampsia); high doses should be avoided.', 'Dose baixa (75-150 mg/dia) sob orientação médica; evitar doses analgésicas elevadas no 3.º trimestre.', 'Low dose (75-150 mg/day) under medical guidance; avoid high analgesic doses in the 3rd trimester.', 'A aspirina passa ao leite em pequenas quantidades; o uso ocasional é aceite, doses elevadas devem ser evitadas.', 'Aspirin passes into milk in small amounts; occasional use is acceptable, high doses should be avoided.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Aspirina: https://www.medicines.org.uk/emc/product/102206/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/102206/smpc'),
  ('clopidogrel', 'caution', 'O clopidogrel não é recomendado na gravidez exceto se o benefício superar o risco, por falta de dados de segurança.', 'Clopidogrel is not recommended in pregnancy unless the benefit outweighs the risk, because of a lack of safety data.', 'Evitar na gravidez exceto em indicações vitais (ex.: stent recente).', 'Avoid in pregnancy except for vital indications (e.g. recent stent).', 'Não se conhece a excreção no leite; evitar durante o aleitamento.', 'Excretion into breast milk is unknown; avoid during breastfeeding.', 'Em idade fértil, confirmar a ausência de gravidez antes de iniciar tratamento prolongado.', 'In women of childbearing age, rule out pregnancy before starting long-term treatment.', 'EMC-UK (MHRA) — SmPC aprovada Clopidogrel: https://www.medicines.org.uk/emc/product/5207/smpc', 'EMC-UK (MHRA) — approved Clopidogrel SmPC: https://www.medicines.org.uk/emc/product/5207/smpc')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;