-- ================================================================
-- 065_seed_interacoes_respiratorios.sql
-- Secção 5 (Aparelho respiratório): 5.1 Antiasmáticos e broncodilatadores,
-- 5.2 Antitússicos e expectorantes, 5.3 Tensioativos (surfactantes) pulmonares.
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico.
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('salbutamol', 'Salbutamol', 'Salbutamol', 'Broncodilatador β2-agonista de ação curta (SABA)', 'Short-acting β2-agonist (SABA)', ARRAY['albuterol', 'Ventolin', 'Asthalin'], 'published', 128),
  ('salmeterol', 'Salmeterol', 'Salmeterol', 'Broncodilatador β2-agonista de ação prolongada (LABA)', 'Long-acting β2-agonist (LABA)', ARRAY['Serevent', 'salmeterol xinafoato', 'salmeterol xinafoate'], 'published', 129),
  ('formoterol', 'Formoterol', 'Formoterol', 'Broncodilatador β2-agonista de ação prolongada (LABA)', 'Long-acting β2-agonist (LABA)', ARRAY['Oxis', 'Atimos', 'eformoterol'], 'published', 130),
  ('budesonida', 'Budesonida', 'Budesonide', 'Corticosteroide inalado (CSI)', 'Inhaled corticosteroid (ICS)', ARRAY['Pulmicort', 'Budelin', 'budesónido'], 'published', 131),
  ('ipratropio', 'Brometo de ipratrópio', 'Ipratropium bromide', 'Broncodilatador anticolinérgico de ação curta (SAMA)', 'Short-acting antimuscarinic (SAMA)', ARRAY['Atrovent', 'ipratrópio', 'ipratropium'], 'published', 132),
  ('tiotropio', 'Tiotrópio', 'Tiotropium', 'Broncodilatador anticolinérgico de ação prolongada (LAMA)', 'Long-acting antimuscarinic (LAMA)', ARRAY['Spiriva', 'tiotropium'], 'published', 133),
  ('montelukast', 'Montelucaste', 'Montelukast', 'Antagonista dos recetores dos leucotrienos (LTRA)', 'Leukotriene receptor antagonist (LTRA)', ARRAY['Singulair', 'montelucaste sódico', 'montelukast sodium'], 'published', 134),
  ('teofilina', 'Teofilina', 'Theophylline', 'Broncodilatador metilxantina', 'Methylxanthine bronchodilator', ARRAY['aminofilina', 'aminophylline', 'Uniphyllin'], 'published', 135),
  ('dextrometorfano', 'Dextrometorfano', 'Dextromethorphan', 'Antitússico (supressor da tosse)', 'Antitussive (cough suppressant)', ARRAY['DXM', 'dextromethorphan', 'Romilar'], 'published', 136),
  ('acetilcisteina', 'Acetilcisteína', 'Acetylcysteine', 'Mucolítico / expectorante', 'Mucolytic / expectorant', ARRAY['Fluimucil', 'N-acetilcisteína', 'N-acetylcysteine'], 'published', 137),
  ('poractant_alfa', 'Poractanto alfa', 'Poractant alfa', 'Tensioativo pulmonar (surfactante)', 'Pulmonary surfactant (tensioactive)', ARRAY['Curosurf', 'surfactante', 'poractant alfa'], 'published', 138);

-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('teofilina', 'claritromicina', 'moderate', 'A claritromicina inibe o metabolismo da teofilina e pode aumentar os seus níveis, com risco de toxicidade (náuseas, taquicardia, convulsões).', 'Clarithromycin inhibits theophylline metabolism and may raise its levels, with a risk of toxicity (nausea, tachycardia, seizures).', 'A claritromicina inibe o CYP1A2/CYP3A4, reduzindo a depuração da teofilina, de margem terapêutica estreita.', 'Clarithromycin inhibits CYP1A2/CYP3A4, reducing the clearance of theophylline, which has a narrow therapeutic margin.', 'Vigiar os níveis de teofilina e reduzir a dose se necessário; considerar antibiótico alternativo.', 'Monitor theophylline levels and reduce the dose if needed; consider an alternative antibiotic.', 'Vigiar náuseas, vómitos, taquicardia, tremores e sinais neurológicos (convulsões).', 'Monitor nausea, vomiting, tachycardia, tremor and neurological signs (seizures).', 'Taquicardia, arritmias, vómitos repetidos, convulsões.', 'Tachycardia, arrhythmias, repeated vomiting, seizures.', 'DailyMed (FDA) — rótulo aprovado Teofilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Theophylline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('teofilina', 'ciprofloxacina', 'moderate', 'A ciprofloxacina reduz a depuração da teofilina e pode aumentar a sua toxicidade.', 'Ciprofloxacin reduces theophylline clearance and may increase its toxicity.', 'A ciprofloxacina inibe o CYP1A2, elevando as concentrações de teofilina.', 'Ciprofloxacin inhibits CYP1A2, raising theophylline concentrations.', 'Reduzir a dose de teofilina ou monitorizar os níveis durante o tratamento com ciprofloxacina.', 'Reduce the theophylline dose or monitor levels during ciprofloxacin treatment.', 'Vigiar sinais de toxicidade da teofilina (náuseas, tremores, taquicardia, convulsões).', 'Monitor signs of theophylline toxicity (nausea, tremor, tachycardia, seizures).', 'Convulsões, arritmias graves.', 'Seizures, serious arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Teofilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Theophylline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('teofilina', 'carbamazepina', 'moderate', 'A carbamazepina induz o metabolismo hepático e pode reduzir os níveis de teofilina; a interação é bidirecional e variável.', 'Carbamazepine induces hepatic metabolism and may lower theophylline levels; the interaction is bidirectional and variable.', 'A carbamazepina é indutora enzimática (CYP3A4), acelerando a depuração da teofilina.', 'Carbamazepine is an enzyme inducer (CYP3A4), accelerating theophylline clearance.', 'Monitorizar os níveis de ambos os fármacos ao iniciar, ajustar ou suspender qualquer um deles.', 'Monitor levels of both drugs when starting, adjusting or stopping either one.', 'Vigiar a eficácia terapêutica da teofilina e sinais de convulsões ou toxicidade.', 'Monitor theophylline efficacy and signs of seizures or toxicity.', 'Perda de controlo da asma (teofilina subterapêutica) ou toxicidade ao interromper a carbamazepina.', 'Loss of asthma control (subtherapeutic theophylline) or toxicity when carbamazepine is stopped.', 'DailyMed (FDA) — rótulo aprovado Teofilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=97e6e175-75e8-437b-b457-ddb1ae4e857d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Theophylline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=97e6e175-75e8-437b-b457-ddb1ae4e857d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('teofilina', 'salbutamol', 'moderate', 'A associação de teofilina com salbutamol tem efeitos aditivos (tremores, taquicardia, hipocaliemia).', 'Combining theophylline with salbutamol has additive effects (tremor, tachycardia, hypokalaemia).', 'Ambos os fármacos estimulam a adenilciclase / aumentam o AMPc e podem potenciar o efeito β2 e a perda de potássio.', 'Both drugs stimulate adenylate cyclase / raise cAMP and may potentiate the β2 effect and potassium loss.', 'Monitorizar o potássio sérico e o ritmo cardíaco, sobretudo em doentes com doença cardiovascular.', 'Monitor serum potassium and heart rhythm, especially in patients with cardiovascular disease.', 'Vigiar tremores, palpitações e dosear o potássio em doentes de risco.', 'Monitor tremor, palpitations and check potassium in at-risk patients.', 'Hipocaliemia sintomática, arritmias.', 'Symptomatic hypokalaemia, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Teofilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; rótulo aprovado Salbutamol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Theophylline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 ; approved Salbutamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('salbutamol', 'sotalol', 'moderate', 'Os β-bloqueadores não seletivos como o sotalol antagonizam o efeito broncodilatador do salbutamol e podem desencadear broncospasmo.', 'Non-selective beta-blockers such as sotalol antagonise the bronchodilator effect of salbutamol and may trigger bronchospasm.', 'O sotalol bloqueia os recetores β2 brônquicos, opondo-se ao salbutamol.', 'Sotalol blocks bronchial β2 receptors, opposing salbutamol.', 'Evitar β-bloqueadores não seletivos em doentes asmáticos; se inevitáveis, usar cardioseletivos com precaução.', 'Avoid non-selective beta-blockers in asthmatic patients; if unavoidable, use cardioselective agents with caution.', 'Vigiar a função respiratória e a resposta ao broncodilatador.', 'Monitor respiratory function and response to the bronchodilator.', 'Broncospasmo, agravamento da dispneia.', 'Bronchospasm, worsening dyspnoea.', 'DailyMed (FDA) — rótulo aprovado Salbutamol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d ; rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Salbutamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d ; approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('salmeterol', 'sotalol', 'moderate', 'O sotalol pode reduzir o efeito broncodilatador do salmeterol e aumentar o risco de broncospasmo.', 'Sotalol may reduce the bronchodilator effect of salmeterol and increase the risk of bronchospasm.', 'Antagonismo recetor β2 entre o LABA e o β-bloqueador não seletivo.', 'β2-receptor antagonism between the LABA and the non-selective beta-blocker.', 'Evitar a associação em doentes com asma; monitorizar a função respiratória.', 'Avoid the combination in asthma; monitor respiratory function.', 'Vigiar sintomas de broncospasmo e a eficácia do broncodilatador.', 'Monitor for bronchospasm and bronchodilator efficacy.', 'Broncospasmo, falta de resposta ao salmeterol.', 'Bronchospasm, lack of response to salmeterol.', 'DailyMed (FDA) — rótulo aprovado Salmeterol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=12d9728e-6b5c-4aee-bfb0-745e542ed2e4 ; rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Salmeterol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=12d9728e-6b5c-4aee-bfb0-745e542ed2e4 ; approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('formoterol', 'sotalol', 'moderate', 'O sotalol antagoniza o efeito do formoterol e pode provocar broncospasmo em doentes predispostos.', 'Sotalol antagonises the effect of formoterol and may cause bronchospasm in predisposed patients.', 'Antagonismo β2 recetor entre o formoterol (LABA) e o sotalol (β-bloqueador não seletivo).', 'β2-receptor antagonism between formoterol (LABA) and sotalol (non-selective beta-blocker).', 'Não usar β-bloqueadores não seletivos em doentes com doença respiratória obstrutiva.', 'Do not use non-selective beta-blockers in patients with obstructive airways disease.', 'Vigiar a função respiratória e a resposta ao broncodilatador.', 'Monitor respiratory function and bronchodilator response.', 'Broncospasmo, agravamento da obstrução das vias aéreas.', 'Bronchospasm, worsening of airway obstruction.', 'DailyMed (FDA) — rótulo aprovado Formoterol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35538d89-a984-4335-acdf-85a893f51eee ; rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Formoterol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35538d89-a984-4335-acdf-85a893f51eee ; approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('budesonida', 'claritromicina', 'moderate', 'A claritromicina pode aumentar a exposição sistémica à budesonida inalada, potenciando efeitos corticoides.', 'Clarithromycin may increase systemic exposure to inhaled budesonide, potentiating corticosteroid effects.', 'A claritromicina inibe o CYP3A4, que metaboliza a budesonida.', 'Clarithromycin inhibits CYP3A4, which metabolises budesonide.', 'Vigiar sinais de excesso corticosteroide com uso prolongado da associação.', 'Monitor for signs of corticosteroid excess with prolonged use of the combination.', 'Vigiar equimoses, glicemia e sinais de supressão suprarrenal em doentes de risco.', 'Monitor bruising, blood glucose and signs of adrenal suppression in at-risk patients.', 'Síndrome de Cushing, supressão suprarrenal.', 'Cushing''s syndrome, adrenal suppression.', 'DailyMed (FDA) — rótulo aprovado Budesonida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ae1105cd-69fc-4c15-937f-c535304341c2 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Budesonide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ae1105cd-69fc-4c15-937f-c535304341c2 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dextrometorfano', 'fluoxetina', 'moderate', 'A fluoxetina pode aumentar os níveis de dextrometorfano e o risco de síndrome serotoninérgico.', 'Fluoxetine may raise dextromethorphan levels and the risk of serotonin syndrome.', 'A fluoxetina inibe o CYP2D6, principal via de metabolização do dextrometorfano, e ambos são serotoninérgicos.', 'Fluoxetine inhibits CYP2D6, the main metabolic pathway of dextromethorphan, and both are serotonergic.', 'Evitar a associação; se inevitável, usar a menor dose de dextrometorfano e vigiar.', 'Avoid the combination; if unavoidable, use the lowest dextromethorphan dose and monitor.', 'Vigiar agitação, tremor, hipertermia, mioclonias e alterações do estado mental.', 'Monitor agitation, tremor, hyperthermia, myoclonus and mental status changes.', 'Síndrome serotoninérgico (hipertermia, rigidez, confusão).', 'Serotonin syndrome (hyperthermia, rigidity, confusion).', 'DailyMed (FDA) — rótulo aprovado Dextrometorfano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14 ; rótulo aprovado Fluoxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dextromethorphan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14 ; approved Fluoxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dextrometorfano', 'sertralina', 'moderate', 'A sertralina pode potenciar os efeitos serotoninérgicos do dextrometorfano.', 'Sertraline may potentiate the serotonergic effects of dextromethorphan.', 'Efeito serotoninérgico aditivo; inibição parcial do CYP2D6 pela sertralina.', 'Additive serotonergic effect; partial CYP2D6 inhibition by sertraline.', 'Vigiar sintomas de excesso serotoninérgico na associação.', 'Monitor for symptoms of serotonergic excess with the combination.', 'Vigiar agitação, diarreia, tremor, hiperreflexia e confusão.', 'Monitor agitation, diarrhoea, tremor, hyperreflexia and confusion.', 'Síndrome serotoninérgico.', 'Serotonin syndrome.', 'DailyMed (FDA) — rótulo aprovado Dextrometorfano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14 ; rótulo aprovado Sertralina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=91e24d17-ff0a-449c-9472-b9df74c98456 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dextromethorphan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14 ; approved Sertraline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=91e24d17-ff0a-449c-9472-b9df74c98456 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dextrometorfano', 'tramadol', 'moderate', 'A associação de dextrometorfano com tramadol aumenta o risco de síndrome serotoninérgico e convulsões.', 'Combining dextromethorphan with tramadol increases the risk of serotonin syndrome and seizures.', 'Ambos os fármacos aumentam a serotonina; o tramadol também reduz o limiar convulsivo.', 'Both drugs raise serotonin; tramadol also lowers the seizure threshold.', 'Evitar a associação; se inevitável, vigiar de perto e usar a menor dose eficaz.', 'Avoid the combination; if unavoidable, monitor closely and use the lowest effective dose.', 'Vigiar sintomas serotoninérgicos e neurológicos.', 'Monitor serotonergic and neurological symptoms.', 'Síndrome serotoninérgico, convulsões.', 'Serotonin syndrome, seizures.', 'DailyMed (FDA) — rótulo aprovado Dextrometorfano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14 ; rótulo aprovado Tramadol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f0e33bd-65f8-446a-886f-e7e16a142ce5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dextromethorphan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14 ; approved Tramadol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f0e33bd-65f8-446a-886f-e7e16a142ce5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)')
) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('teofilina', 'cafe_cha', 'Café, chá e bebidas com cafeína', 'Coffee, tea and caffeine-containing drinks', 'moderate', 'A cafeína é uma metilxantina com efeitos aditivos aos da teofilina (estimulação do SNC, taquicardia, tremores).', 'Caffeine is a methylxanthine with additive effects to theophylline (CNS stimulation, tachycardia, tremor).', 'Limitar o consumo de café, chá e bebidas com cafeína durante o tratamento com teofilina.', 'Limit coffee, tea and caffeinated drinks during theophylline treatment.', 'EMC-UK (MHRA) — SmPC aprovada Teofilina: https://www.medicines.org.uk/emc/product/100851/smpc', 'EMC-UK (MHRA) — approved Theophylline SmPC: https://www.medicines.org.uk/emc/product/100851/smpc', 1),
  ('teofilina', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool pode alterar o metabolismo da teofilina e potenciar os efeitos no sistema nervoso central.', 'Alcohol may alter theophylline metabolism and potentiate central nervous system effects.', 'Limitar o consumo de álcool durante o tratamento.', 'Limit alcohol intake during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Teofilina: https://www.medicines.org.uk/emc/product/100851/smpc', 'EMC-UK (MHRA) — approved Theophylline SmPC: https://www.medicines.org.uk/emc/product/100851/smpc', 1),
  ('montelukast', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'O montelucaste deve ser tomado sem alimentos; as refeições podem reduzir a absorção do comprimido.', 'Montelukast should be taken without food; meals may reduce the absorption of the tablet.', 'Tomar 1 hora antes ou 2 horas após as refeições.', 'Take 1 hour before or 2 hours after meals.', 'EMC-UK (MHRA) — SmPC aprovada Montelucaste: https://www.medicines.org.uk/emc/product/1222/smpc', 'EMC-UK (MHRA) — approved Montelukast SmPC: https://www.medicines.org.uk/emc/product/1222/smpc', 1),
  ('dextrometorfano', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool potencia a depressão do sistema nervoso central associada ao dextrometorfano.', 'Alcohol potentiates the central nervous system depression associated with dextromethorphan.', 'Evitar o consumo de álcool durante o tratamento.', 'Avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Dextrometorfano: https://www.medicines.org.uk/emc/product/1523/smpc', 'EMC-UK (MHRA) — approved Dextromethorphan SmPC: https://www.medicines.org.uk/emc/product/1523/smpc', 1),
  ('salbutamol', 'cafe_cha', 'Café e bebidas com cafeína', 'Coffee and caffeinated drinks', 'minor', 'A cafeína pode potenciar os efeitos do salbutamol (tremores, palpitações, taquicardia).', 'Caffeine may potentiate the effects of salbutamol (tremor, palpitations, tachycardia).', 'Limitar o consumo de cafeína em doentes com sintomas adrenérgicos.', 'Limit caffeine intake in patients with adrenergic symptoms.', 'EMC-UK (MHRA) — SmPC aprovada Salbutamol: https://www.medicines.org.uk/emc/product/12983/smpc', 'EMC-UK (MHRA) — approved Salbutamol SmPC: https://www.medicines.org.uk/emc/product/12983/smpc', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('teofilina', 'doenca_hepatica', 'Doença hepática (insuficiência hepática)', 'Hepatic disease (hepatic impairment)', 'precaution', 'moderate', 'A depuração da teofilina está reduzida na doença hepática, com risco de acumulação e toxicidade.', 'Theophylline clearance is reduced in hepatic disease, with a risk of accumulation and toxicity.', 'Reduzir a dose e monitorizar os níveis séricos de teofilina.', 'Reduce the dose and monitor serum theophylline levels.', 'EMC-UK (MHRA) — SmPC aprovada Teofilina: https://www.medicines.org.uk/emc/product/100851/smpc', 'EMC-UK (MHRA) — approved Theophylline SmPC: https://www.medicines.org.uk/emc/product/100851/smpc', 1),
  ('teofilina', 'epilepsia', 'Epilepsia / antecedentes convulsivos', 'Epilepsy / seizure history', 'precaution', 'moderate', 'A teofilina pode reduzir o limiar convulsivo, sobretudo em níveis elevados.', 'Theophylline may lower the seizure threshold, especially at high levels.', 'Usar com precaução e manter os níveis séricos dentro da margem terapêutica.', 'Use with caution and keep serum levels within the therapeutic range.', 'EMC-UK (MHRA) — SmPC aprovada Teofilina: https://www.medicines.org.uk/emc/product/100851/smpc', 'EMC-UK (MHRA) — approved Theophylline SmPC: https://www.medicines.org.uk/emc/product/100851/smpc', 1),
  ('salbutamol', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus', 'precaution', 'moderate', 'Os β2-agonistas podem elevar a glicemia, sobretudo em doses elevadas ou no contexto agudo.', 'β2-agonists may raise blood glucose, especially at high doses or in acute settings.', 'Monitorizar a glicemia em doentes diabéticos durante o tratamento.', 'Monitor blood glucose in diabetic patients during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Salbutamol: https://www.medicines.org.uk/emc/product/12983/smpc', 'EMC-UK (MHRA) — approved Salbutamol SmPC: https://www.medicines.org.uk/emc/product/12983/smpc', 1),
  ('salmeterol', 'doenca_cardiovascular', 'Doença cardiovascular (enfarte, AVC)', 'Cardiovascular disease (MI, stroke)', 'precaution', 'moderate', 'Os LABA podem causar taquicardia e arritmias em doentes com doença cardiovascular.', 'LABAs may cause tachycardia and arrhythmias in patients with cardiovascular disease.', 'Usar com precaução; vigiar o ritmo cardíaco e os sintomas de isquemia.', 'Use with caution; monitor heart rhythm and ischaemic symptoms.', 'EMC-UK (MHRA) — SmPC aprovada Salmeterol: https://www.medicines.org.uk/emc/product/848/smpc', 'EMC-UK (MHRA) — approved Salmeterol SmPC: https://www.medicines.org.uk/emc/product/848/smpc', 1),
  ('salmeterol', 'hipertensao_nao_controlada', 'Hipertensão não controlada', 'Uncontrolled hypertension', 'precaution', 'moderate', 'Os β2-agonistas podem elevar a pressão arterial e a frequência cardíaca.', 'β2-agonists may raise blood pressure and heart rate.', 'Controlar a tensão arterial antes e durante o tratamento.', 'Control blood pressure before and during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Salmeterol: https://www.medicines.org.uk/emc/product/848/smpc', 'EMC-UK (MHRA) — approved Salmeterol SmPC: https://www.medicines.org.uk/emc/product/848/smpc', 1),
  ('formoterol', 'doenca_cardiovascular', 'Doença cardiovascular (enfarte, AVC)', 'Cardiovascular disease (MI, stroke)', 'precaution', 'moderate', 'O formoterol pode provocar taquicardia e arritmias em doentes cardíacos.', 'Formoterol may cause tachycardia and arrhythmias in cardiac patients.', 'Usar com precaução e vigiar sinais cardiovasculares.', 'Use with caution and monitor cardiovascular signs.', 'EMC-UK (MHRA) — SmPC aprovada Formoterol: https://www.medicines.org.uk/emc/product/6316/smpc', 'EMC-UK (MHRA) — approved Formoterol SmPC: https://www.medicines.org.uk/emc/product/6316/smpc', 1),
  ('budesonida', 'tuberculose', 'Tuberculose (ativa ou latente)', 'Tuberculosis (active or latent)', 'precaution', 'moderate', 'Os corticosteroides inalados podem mascarar ou agravar infeções respiratórias, incluindo tuberculose.', 'Inhaled corticosteroids may mask or worsen respiratory infections, including tuberculosis.', 'Vigiar e tratar infeções intercorrentes; considerar profilaxia conforme as normas locais.', 'Monitor and treat intercurrent infections; consider prophylaxis per local guidelines.', 'EMC-UK (MHRA) — SmPC aprovada Budesonida: https://www.medicines.org.uk/emc/product/9715/smpc', 'EMC-UK (MHRA) — approved Budesonide SmPC: https://www.medicines.org.uk/emc/product/9715/smpc', 1),
  ('ipratropio', 'glaucoma_angulo_fechado', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma', 'precaution', 'moderate', 'A inalação de anticolinérgicos pode precipitar um ataque agudo de glaucoma de ângulo fechado.', 'Inhalation of anticholinergics may precipitate an acute angle-closure glaucoma attack.', 'Evitar contacto com os olhos; usar com precaução em doentes com glaucoma.', 'Avoid contact with the eyes; use with caution in patients with glaucoma.', 'EMC-UK (MHRA) — SmPC aprovada Brometo de ipratrópio: https://www.medicines.org.uk/emc/product/61/smpc', 'EMC-UK (MHRA) — approved Ipratropium bromide SmPC: https://www.medicines.org.uk/emc/product/61/smpc', 1),
  ('ipratropio', 'retencao_urinaria', 'Retenção urinária / hiperplasia prostática', 'Urinary retention / prostatic hyperplasia', 'precaution', 'moderate', 'O efeito anticolinérgico pode agravar a retenção urinária.', 'The anticholinergic effect may worsen urinary retention.', 'Usar com precaução em doentes com sintomas urinários obstrutivos.', 'Use with caution in patients with obstructive urinary symptoms.', 'EMC-UK (MHRA) — SmPC aprovada Brometo de ipratrópio: https://www.medicines.org.uk/emc/product/61/smpc', 'EMC-UK (MHRA) — approved Ipratropium bromide SmPC: https://www.medicines.org.uk/emc/product/61/smpc', 1),
  ('tiotropio', 'glaucoma_angulo_fechado', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma', 'precaution', 'moderate', 'Os anticolinérgicos inalados de ação prolongada podem precipitar glaucoma agudo.', 'Long-acting inhaled anticholinergics may precipitate acute glaucoma.', 'Instruir o doente para evitar o contacto com os olhos; vigiar sintomas oculares.', 'Instruct the patient to avoid eye contact; monitor ocular symptoms.', 'EMC-UK (MHRA) — SmPC aprovada Tiotrópio: https://www.medicines.org.uk/emc/product/1693/smpc', 'EMC-UK (MHRA) — approved Tiotropium SmPC: https://www.medicines.org.uk/emc/product/1693/smpc', 1),
  ('tiotropio', 'insuficiencia_renal_grave', 'Insuficiência renal grave (CrCl < 30 ml/min)', 'Severe renal impairment (CrCl < 30 ml/min)', 'precaution', 'moderate', 'A eliminação do tiotrópio é predominantemente renal; pode haver acumulação.', 'Tiotropium elimination is predominantly renal; accumulation may occur.', 'Usar com precaução na insuficiência renal grave.', 'Use with caution in severe renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Tiotrópio: https://www.medicines.org.uk/emc/product/1693/smpc', 'EMC-UK (MHRA) — approved Tiotropium SmPC: https://www.medicines.org.uk/emc/product/1693/smpc', 1),
  ('acetilcisteina', 'asma', 'Asma (broncospasmo)', 'Asthma (bronchospasm)', 'precaution', 'moderate', 'A inalação de acetilcisteína pode desencadear broncospasmo, sobretudo em doentes asmáticos.', 'Inhaled acetylcysteine may trigger bronchospasm, especially in asthmatic patients.', 'Usar com precaução; ter broncodilatador de curta ação disponível.', 'Use with caution; keep a short-acting bronchodilator available.', 'EMC-UK (MHRA) — SmPC aprovada Acetilcisteína: https://www.medicines.org.uk/emc/product/2488/smpc', 'EMC-UK (MHRA) — approved Acetylcysteine SmPC: https://www.medicines.org.uk/emc/product/2488/smpc', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('salbutamol', 'compatible', 'O salbutamol é o broncodilatador mais usado na gravidez e é considerado seguro nas doses habituais.', 'Salbutamol is the most used bronchodilator in pregnancy and is considered safe at usual doses.', 'Pode ser usado em todos os trimestres quando indicado, sob orientação médica.', 'Can be used in all trimesters when indicated, under medical guidance.', 'Excretado em pequenas quantidades no leite; compatível com o aleitamento.', 'Excreted in small amounts into breast milk; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Salbutamol: https://www.medicines.org.uk/emc/product/12983/smpc', 'EMC-UK (MHRA) — approved Salbutamol SmPC: https://www.medicines.org.uk/emc/product/12983/smpc'),
  ('salmeterol', 'caution', 'Os dados sobre salmeterol na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on salmeterol in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar no 1.º trimestre exceto se estritamente necessário.', 'Avoid in the 1st trimester unless strictly necessary.', 'Não se conhece a excreção no leite; usar com precaução.', 'Excretion into breast milk is unknown; use with caution.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Salmeterol: https://www.medicines.org.uk/emc/product/848/smpc', 'EMC-UK (MHRA) — approved Salmeterol SmPC: https://www.medicines.org.uk/emc/product/848/smpc'),
  ('formoterol', 'caution', 'Os dados sobre formoterol na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on formoterol in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar exceto se a asma o exigir, com a menor dose eficaz.', 'Avoid unless asthma requires it, at the lowest effective dose.', 'Não se conhece a excreção no leite; usar com precaução.', 'Excretion into breast milk is unknown; use with caution.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Formoterol: https://www.medicines.org.uk/emc/product/6316/smpc', 'EMC-UK (MHRA) — approved Formoterol SmPC: https://www.medicines.org.uk/emc/product/6316/smpc'),
  ('budesonida', 'compatible', 'A budesonida inalada é o corticoide de escolha na gravidez, com baixa exposição sistémica.', 'Inhaled budesonide is the corticosteroid of choice in pregnancy, with low systemic exposure.', 'Pode ser usada em todos os trimestres quando a asma o exigir.', 'Can be used in all trimesters when asthma requires it.', 'Excretada em pequenas quantidades no leite; compatível com o aleitamento.', 'Excreted in small amounts into breast milk; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Budesonida: https://www.medicines.org.uk/emc/product/9715/smpc', 'EMC-UK (MHRA) — approved Budesonide SmPC: https://www.medicines.org.uk/emc/product/9715/smpc'),
  ('ipratropio', 'caution', 'Os dados sobre ipratrópio na gravidez são limitados; usar apenas se necessário.', 'Data on ipratropium in pregnancy are limited; use only if needed.', 'Evitar exceto se os broncodilatadores habituais forem insuficientes.', 'Avoid unless usual bronchodilators are insufficient.', 'Excretado em pequenas quantidades no leite; provavelmente compatível.', 'Excreted in small amounts into breast milk; probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Brometo de ipratrópio: https://www.medicines.org.uk/emc/product/61/smpc', 'EMC-UK (MHRA) — approved Ipratropium bromide SmPC: https://www.medicines.org.uk/emc/product/61/smpc'),
  ('tiotropio', 'caution', 'Os dados sobre tiotrópio na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on tiotropium in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar no 1.º trimestre exceto se estritamente necessário.', 'Avoid in the 1st trimester unless strictly necessary.', 'Não se conhece a excreção no leite; usar com precaução.', 'Excretion into breast milk is unknown; use with caution.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Tiotrópio: https://www.medicines.org.uk/emc/product/1693/smpc', 'EMC-UK (MHRA) — approved Tiotropium SmPC: https://www.medicines.org.uk/emc/product/1693/smpc'),
  ('montelukast', 'caution', 'Os dados sobre montelucaste na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on montelukast in pregnancy are limited; use only if the benefit outweighs the risk.', 'Pode ser usado se a asma não estiver controlada com CSI isolados.', 'Can be used if asthma is not controlled with ICS alone.', 'Excretado no leite em pequenas quantidades; provavelmente compatível.', 'Excreted into breast milk in small amounts; probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Montelucaste: https://www.medicines.org.uk/emc/product/1222/smpc', 'EMC-UK (MHRA) — approved Montelukast SmPC: https://www.medicines.org.uk/emc/product/1222/smpc'),
  ('teofilina', 'caution', 'A teofilina pode ser usada na gravidez se necessária, com monitorização apertada dos níveis.', 'Theophylline may be used in pregnancy if needed, with tight monitoring of levels.', 'Manter os níveis séricos na margem terapêutica baixa; vigiar taquicardia fetal.', 'Keep serum levels in the low therapeutic range; monitor fetal tachycardia.', 'Excretada no leite em pequenas quantidades; usar com precaução.', 'Excreted into breast milk in small amounts; use with caution.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Teofilina: https://www.medicines.org.uk/emc/product/100851/smpc', 'EMC-UK (MHRA) — approved Theophylline SmPC: https://www.medicines.org.uk/emc/product/100851/smpc'),
  ('dextrometorfano', 'caution', 'Os dados sobre dextrometorfano na gravidez são limitados; usar apenas se necessário.', 'Data on dextromethorphan in pregnancy are limited; use only if needed.', 'Evitar no 1.º trimestre; usar a menor dose e duração possíveis.', 'Avoid in the 1st trimester; use the lowest dose and shortest duration possible.', 'Excretado no leite em pequenas quantidades; uso pontual provavelmente compatível.', 'Excreted into breast milk in small amounts; occasional use is probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Dextrometorfano: https://www.medicines.org.uk/emc/product/1523/smpc', 'EMC-UK (MHRA) — approved Dextromethorphan SmPC: https://www.medicines.org.uk/emc/product/1523/smpc'),
  ('acetilcisteina', 'caution', 'Os dados sobre acetilcisteína na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on acetylcysteine in pregnancy are limited; use only if the benefit outweighs the risk.', 'Em sobredosagem de paracetamol na gravidez, a acetilcisteína é o antídoto de eleição.', 'In paracetamol overdose in pregnancy, acetylcysteine is the antidote of choice.', 'Não se conhece a excreção no leite; uso pontual provavelmente compatível.', 'Excretion into breast milk is unknown; occasional use is probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Acetilcisteína: https://www.medicines.org.uk/emc/product/2488/smpc', 'EMC-UK (MHRA) — approved Acetylcysteine SmPC: https://www.medicines.org.uk/emc/product/2488/smpc'),
  ('poractant_alfa', 'compatible', 'O poractanto alfa é administrado ao recém-nascido por via endotraqueal; não é usado na grávida, mas a sua indicação neonatal é bem estabelecida.', 'Poractant alfa is given to the newborn via the endotracheal route; it is not used in the mother, but its neonatal indication is well established.', 'Não aplicável à gravidez; uso exclusivamente neonatal (SDR do recém-nascido).', 'Not applicable to pregnancy; exclusively neonatal use (neonatal RDS).', 'Não se aplica ao aleitamento (uso neonatal).', 'Not applicable to breastfeeding (neonatal use).', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Poractanto alfa: https://www.medicines.org.uk/emc/product/6450/smpc', 'EMC-UK (MHRA) — approved Poractant alfa SmPC: https://www.medicines.org.uk/emc/product/6450/smpc')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;