-- ================================================================
-- 066_seed_interacoes_digestivos.sql
-- Secção 6 (Aparelho digestivo): 6.1 Boca e orofaringe; 6.2 Antiácidos e
-- anti-ulcerosos; 6.3 Modificadores da motilidade gastrintestinal;
-- 6.4 Antiespasmódicos; 6.5 Inibidores enzimáticos;
-- 6.8 Anti-inflamatórios intestinais; 6.9 Fígado e vias biliares.
-- 6.6 (suplementos enzimáticos/bacilos) e 6.7 (anti-hemorroidários): sem
-- fármacos sistémicos novos (tópicos/nutricionais, fora do âmbito).
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico (sucralfato e antiácidos:
-- sem produto EMC-UK atual — fonte DailyMed/FDA).
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('nistatina', 'Nistatina', 'Nystatin', 'Antifúngico poliénico (uso oral)', 'Polyene antifungal (oral use)', ARRAY['Nystan', 'Micostatin', 'nystatin'], 'published', 139),
  ('famotidina', 'Famotidina', 'Famotidine', 'Antiácidos e anti-ulcerosos — antagonista dos recetores H2', 'Antacids and anti-ulcer agents — histamine H2-receptor antagonist', ARRAY['Pepcid', 'famotidine'], 'published', 140),
  ('sucralfato', 'Sucralfato', 'Sucralfate', 'Citoprotetor da mucosa gástrica (anti-ulceroso)', 'Gastric mucosal cytoprotectant (anti-ulcer)', ARRAY['Antepsin', 'Carafate', 'sucralfate'], 'published', 141),
  ('metoclopramida', 'Metoclopramida', 'Metoclopramide', 'Procinético / antiemético (antagonista dopaminérgico)', 'Prokinetic / antiemetic (dopamine antagonist)', ARRAY['Primperan', 'Maxolon', 'metoclopramide'], 'published', 142),
  ('domperidona', 'Domperidona', 'Domperidone', 'Procinético / antiemético (antagonista dopaminérgico periférico)', 'Prokinetic / antiemetic (peripheral dopamine antagonist)', ARRAY['Motilium', 'domperidone'], 'published', 143),
  ('loperamida', 'Loperamida', 'Loperamide', 'Antidiarreico (agonista opioide de ação periférica)', 'Antidiarrhoeal (peripheral opioid agonist)', ARRAY['Imodium', 'loperamide'], 'published', 144),
  ('ondansetron', 'Ondansetrom', 'Ondansetron', 'Antiemético (antagonista dos recetores 5-HT3)', 'Antiemetic (5-HT3 receptor antagonist)', ARRAY['Zofran', 'Zofren', 'ondansetron'], 'published', 145),
  ('butilbrometo_hioscina', 'Butilbrometo de hioscina', 'Hyoscine butylbromide', 'Antiespasmódico (anticolinérgico)', 'Antispasmodic (antimuscarinic)', ARRAY['Buscopan', 'butilbrometo de escopolamina', 'hyoscine butylbromide', 'butylscopolamine'], 'published', 146),
  ('orlistat', 'Orlistato', 'Orlistat', 'Inibidor das lipases gastrintestinais (anti-obesidade)', 'Gastrointestinal lipase inhibitor (anti-obesity)', ARRAY['Xenical', 'Alli', 'orlistate'], 'published', 147),
  ('mesalazina', 'Mesalazina', 'Mesalazine', 'Anti-inflamatório intestinal (derivado do ácido 5-aminossalicílico)', 'Intestinal anti-inflammatory (5-aminosalicylic acid derivative)', ARRAY['Mesalamine', 'Asacol', 'Pentasa', 'mesalazine'], 'published', 148),
  ('sulfassalazina', 'Sulfassalazina', 'Sulfasalazine', 'Anti-inflamatório intestinal (pró-fármaco de 5-ASA + sulfapiridina)', 'Intestinal anti-inflammatory (prodrug of 5-ASA + sulfapyridine)', ARRAY['Salazopyrin', 'Azulfidine', 'sulfasalazine'], 'published', 149),
  ('acido_ursodesoxicolico', 'Ácido ursodesoxicólico', 'Ursodeoxycholic acid', 'Ácido biliar (colerético / litolítico)', 'Bile acid (choleretic / litholytic)', ARRAY['Ursodiol', 'Urso', 'ursodeoxycholic acid', 'ácido ursodeoxicólico'], 'published', 150);

-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('domperidona', 'claritromicina', 'critical', 'A associação de domperidona com claritromicina está contraindicada: a claritromicina inibe o CYP3A4 e aumenta as concentrações de domperidona, com risco elevado de prolongamento do intervalo QT e torsade de pointes.', 'Combining domperidone with clarithromycin is contraindicated: clarithromycin inhibits CYP3A4 and raises domperidone concentrations, with a high risk of QT-interval prolongation and torsade de pointes.', 'A claritromicina é um inibidor potente do CYP3A4, principal via de metabolização da domperidona; ambas as substâncias prolongam o QT.', 'Clarithromycin is a potent CYP3A4 inhibitor, the main metabolic pathway of domperidone; both substances prolong the QT interval.', 'Evitar a associação; escolher um macrólido alternativo ou um procinético/antiemético sem risco QT.', 'Avoid the combination; choose an alternative macrolide or a prokinetic/antiemetic without QT risk.', 'Vigiar ECG (intervalo QT) e sintomas de arritmia (palpitações, síncope).', 'Monitor ECG (QT interval) and arrhythmia symptoms (palpitations, syncope).', 'Torsade de pointes, morte súbita.', 'Torsade de pointes, sudden death.', 'DailyMed (FDA) — rótulo aprovado Domperidona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdb0c9b9-388c-4a06-9fe9-bb4e52278a4e ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Domperidone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdb0c9b9-388c-4a06-9fe9-bb4e52278a4e ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('domperidona', 'ciprofloxacina', 'moderate', 'A ciprofloxacina pode aumentar a exposição à domperidona e somar efeitos no intervalo QT.', 'Ciprofloxacin may increase domperidone exposure and add QT-interval effects.', 'A ciprofloxacina inibe parcialmente o CYP3A4 e ambas prolongam o QT.', 'Ciprofloxacin partially inhibits CYP3A4 and both prolong the QT.', 'Usar com precaução; considerar alternativa se houver fatores de risco QT.', 'Use with caution; consider an alternative if QT risk factors are present.', 'Vigiar ECG em doentes com fatores de risco (hipocaliemia, bradicardia, outros fármacos QT).', 'Monitor ECG in patients with risk factors (hypokalaemia, bradycardia, other QT drugs).', 'Arritmias ventriculares, torsade de pointes (raro).', 'Ventricular arrhythmias, torsade de pointes (rare).', 'DailyMed (FDA) — rótulo aprovado Domperidona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdb0c9b9-388c-4a06-9fe9-bb4e52278a4e ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Domperidone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdb0c9b9-388c-4a06-9fe9-bb4e52278a4e ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ondansetron', 'tramadol', 'moderate', 'A associação de ondansetrom com tramadol aumenta o risco de síndrome serotoninérgico.', 'Combining ondansetron with tramadol raises the risk of serotonin syndrome.', 'O tramadol é serotoninérgico e o ondansetrom, embora antagonista 5-HT3, pode contribuir para excesso serotoninérgico em doentes suscetíveis.', 'Tramadol is serotonergic and ondansetron, although a 5-HT3 antagonist, may contribute to serotonergic excess in susceptible patients.', 'Vigiar sintomas serotoninérgicos; usar com precaução em doentes polimedicados.', 'Monitor serotonergic symptoms; use with caution in polypharmacy patients.', 'Vigiar agitação, tremor, hipertermia, mioclonias e diarreia.', 'Monitor agitation, tremor, hyperthermia, myoclonus and diarrhoea.', 'Síndrome serotoninérgico (hipertermia, rigidez, confusão).', 'Serotonin syndrome (hyperthermia, rigidity, confusion).', 'DailyMed (FDA) — rótulo aprovado Ondansetrom: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=41366a20-0727-0446-e063-6294a90a957f ; rótulo aprovado Tramadol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f0e33bd-65f8-446a-886f-e7e16a142ce5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ondansetron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=41366a20-0727-0446-e063-6294a90a957f ; approved Tramadol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f0e33bd-65f8-446a-886f-e7e16a142ce5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('metoclopramida', 'levotiroxina', 'moderate', 'A metoclopramida aumenta a motilidade gástrica e pode reduzir a absorção da levotiroxina, diminuindo o seu efeito.', 'Metoclopramide increases gastric motility and may reduce levothyroxine absorption, decreasing its effect.', 'A aceleração do esvaziamento gástrico encurta o tempo de contacto da levotiroxina com a mucosa absortiva.', 'Accelerated gastric emptying shortens levothyroxine contact time with the absorptive mucosa.', 'Separar as tomas e monitorizar a TSH ao iniciar ou suspender a metoclopramida.', 'Separate administration times and monitor TSH when starting or stopping metoclopramide.', 'Monitorizar TSH e sintomas de hipotiroidismo (fadiga, ganho de peso).', 'Monitor TSH and hypothyroidism symptoms (fatigue, weight gain).', 'Hipotiroidismo descompensado.', 'Decompensated hypothyroidism.', 'DailyMed (FDA) — rótulo aprovado Metoclopramida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d31d815-50fa-4e78-8ebd-affc2514ce78 ; rótulo aprovado Levotiroxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Metoclopramide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d31d815-50fa-4e78-8ebd-affc2514ce78 ; approved Levothyroxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('metoclopramida', 'digoxina', 'moderate', 'A metoclopramida pode reduzir a absorção da digoxina e, em alguns doentes, atrasar o seu efeito terapêutico.', 'Metoclopramide may reduce digoxin absorption and, in some patients, delay its therapeutic effect.', 'O aumento do trânsito intestinal pela metoclopramida reduz o tempo de absorção da digoxina.', 'Metoclopramide-induced faster intestinal transit reduces digoxin absorption time.', 'Monitorizar a resposta clínica e considerar dose ajustada ou esquema alternativo.', 'Monitor clinical response and consider dose adjustment or an alternative schedule.', 'Vigiar a resposta antiarrítmica/antifibrilatória e sintomas de insuficiência cardíaca.', 'Monitor the antiarrhythmic/rate-control response and heart failure symptoms.', 'Perda de controlo do ritmo/da insuficiência cardíaca.', 'Loss of rhythm/heart failure control.', 'DailyMed (FDA) — rótulo aprovado Metoclopramida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d31d815-50fa-4e78-8ebd-affc2514ce78 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Metoclopramide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d31d815-50fa-4e78-8ebd-affc2514ce78 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('loperamida', 'claritromicina', 'moderate', 'A claritromicina pode aumentar as concentrações de loperamida, potenciando efeitos depressores do SNC e cardíacos.', 'Clarithromycin may raise loperamide concentrations, potentiating CNS-depressant and cardiac effects.', 'A inibição do CYP3A4 pela claritromicina aumenta a exposição à loperamida.', 'CYP3A4 inhibition by clarithromycin increases loperamide exposure.', 'Usar a menor dose eficaz e vigiar efeitos adversos; evitar doses altas.', 'Use the lowest effective dose and monitor adverse effects; avoid high doses.', 'Vigiar sonolência, obstipação, palpitações e alterações do ritmo.', 'Monitor drowsiness, constipation, palpitations and rhythm changes.', 'Toxicidade por loperamida (SNC, QT).', 'Loperamide toxicity (CNS, QT).', 'DailyMed (FDA) — rótulo aprovado Loperamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=568064c9-139d-7233-e063-6294a90a10d4 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Loperamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=568064c9-139d-7233-e063-6294a90a10d4 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sucralfato', 'ciprofloxacina', 'moderate', 'O sucralfato reduz significativamente a absorção oral da ciprofloxacina quando administrado em simultâneo.', 'Sucralfate significantly reduces oral ciprofloxacin absorption when given at the same time.', 'O sucralfato forma complexos de quelação com as fluoroquinolonas no trato gastrointestinal.', 'Sucralfate chelates fluoroquinolones in the gastrointestinal tract.', 'Administrar a ciprofloxacina 2 horas antes ou 6 horas após o sucralfato.', 'Give ciprofloxacin 2 hours before or 6 hours after sucralfate.', 'Vigiar a resposta clínica à antibioterapia.', 'Monitor the clinical response to antibiotic therapy.', 'Falha terapêutica da ciprofloxacina.', 'Ciprofloxacin therapeutic failure.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sucralfato', 'digoxina', 'moderate', 'O sucralfato pode reduzir a absorção da digoxina, diminuindo o seu efeito.', 'Sucralfate may reduce digoxin absorption, decreasing its effect.', 'A ligação do sucralfato à digoxina no trato gastrointestinal reduz a sua biodisponibilidade.', 'Sucralfate binding to digoxin in the gut reduces its bioavailability.', 'Separar as tomas (2 horas) e monitorizar níveis/resposta.', 'Separate administration times (2 hours) and monitor levels/response.', 'Vigiar a frequência cardíaca e sintomas de insuficiência cardíaca.', 'Monitor heart rate and heart failure symptoms.', 'Perda de controlo do ritmo/da insuficiência cardíaca.', 'Loss of rhythm/heart failure control.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sucralfato', 'levotiroxina', 'moderate', 'O sucralfato reduz a absorção da levotiroxina, comprometendo o controlo do hipotiroidismo.', 'Sucralfate reduces levothyroxine absorption, compromising hypothyroidism control.', 'Quelação/adsorção da levotiroxina pelo sucralfato no trato gastrointestinal.', 'Chelation/adsorption of levothyroxine by sucralfate in the gut.', 'Separar as tomas (4 horas) e monitorizar TSH.', 'Separate administration times (4 hours) and monitor TSH.', 'Monitorizar TSH e sintomas de hipotiroidismo.', 'Monitor TSH and hypothyroidism symptoms.', 'Hipotiroidismo descompensado.', 'Decompensated hypothyroidism.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; rótulo aprovado Levotiroxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; approved Levothyroxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sucralfato', 'antiacidos', 'moderate', 'Os antiácidos podem reduzir o efeito protetor do sucralfato quando tomados em simultâneo.', 'Antacids may reduce the protective effect of sucralfate when taken together.', 'Os antiácidos alteram o pH gástrico e podem interferir com a polimerização do sucralfato.', 'Antacids change gastric pH and may interfere with sucralfate polymerisation.', 'Separar as tomas do sucralfato e dos antiácidos (30–60 minutos).', 'Separate sucralfate and antacid administration (30–60 minutes).', 'Vigiar a resposta sintomática (dor epigástrica, pirose).', 'Monitor symptomatic response (epigastric pain, heartburn).', 'Recidiva de sintomas ulcerosos.', 'Recurrence of ulcer symptoms.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('orlistat', 'warfarina', 'moderate', 'O orlistato pode reduzir a absorção da vitamina K e alterar o INR em doentes a tomar varfarina.', 'Orlistat may reduce vitamin K absorption and alter the INR in patients taking warfarin.', 'A diminuição da absorção de vitamina K lipossolúvel interfere com a síntese dos fatores de coagulação dependentes da vitamina K.', 'Reduced fat-soluble vitamin K absorption interferes with synthesis of vitamin K-dependent clotting factors.', 'Monitorizar o INR com maior frequência ao iniciar, ajustar ou suspender o orlistato.', 'Monitor the INR more frequently when starting, adjusting or stopping orlistat.', 'Vigiar sinais de hemorragia e o INR.', 'Monitor bleeding signs and INR.', 'Hemorragia ou eventos trombóticos por INR instável.', 'Bleeding or thrombotic events from unstable INR.', 'DailyMed (FDA) — rótulo aprovado Orlistato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a2d3bd73-f3af-4ea5-a57c-66b0004cfe4f ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Orlistat label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a2d3bd73-f3af-4ea5-a57c-66b0004cfe4f ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('orlistat', 'levotiroxina', 'moderate', 'O orlistato reduz a absorção da levotiroxina, podendo comprometer o controlo do hipotiroidismo.', 'Orlistat reduces levothyroxine absorption and may compromise hypothyroidism control.', 'Interferência com a absorção de substâncias lipossolúveis / janela de absorção da levotiroxina.', 'Interference with fat-soluble absorption / levothyroxine absorption window.', 'Separar as tomas (4 horas) e monitorizar TSH.', 'Separate administration times (4 hours) and monitor TSH.', 'Monitorizar TSH e sintomas de hipotiroidismo.', 'Monitor TSH and hypothyroidism symptoms.', 'Hipotiroidismo descompensado.', 'Decompensated hypothyroidism.', 'DailyMed (FDA) — rótulo aprovado Orlistato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a2d3bd73-f3af-4ea5-a57c-66b0004cfe4f ; rótulo aprovado Levotiroxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Orlistat label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a2d3bd73-f3af-4ea5-a57c-66b0004cfe4f ; approved Levothyroxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('mesalazina', 'azatioprina', 'moderate', 'A mesalazina pode potenciar a mielossupressão da azatioprina (inibição da TPMT).', 'Mesalazine may potentiate azathioprine myelosuppression (TPMT inhibition).', 'A mesalazina inibe a tiopurina metiltransferase (TPMT), aumentando os níveis de 6-tioguanina ativa.', 'Mesalazine inhibits thiopurine methyltransferase (TPMT), raising active 6-thioguanine levels.', 'Monitorizar o hemograma com regularidade; vigiar sinais de infeção e equimoses.', 'Monitor the blood count regularly; watch for infection and bruising.', 'Hemograma completo periódico, sobretudo nas primeiras semanas.', 'Periodic full blood count, especially in the first weeks.', 'Leucopenia, trombocitopenia, infeções graves.', 'Leucopenia, thrombocytopenia, serious infections.', 'DailyMed (FDA) — rótulo aprovado Mesalazina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=47b5d1ee-b439-4ccb-9b01-c0875ccd748a ; rótulo aprovado Azatioprina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5116b22b-1460-5535-e063-6394a90acbe5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Mesalazine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=47b5d1ee-b439-4ccb-9b01-c0875ccd748a ; approved Azathioprine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5116b22b-1460-5535-e063-6394a90acbe5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sulfassalazina', 'acido_folico', 'moderate', 'A sulfassalazina pode reduzir a absorção do ácido fólico e o seu efeito, sobretudo em uso prolongado.', 'Sulfasalazine may reduce folic acid absorption and its effect, especially with long-term use.', 'Inibição do transportador de folato intestinal pela sulfapiridina (metabolito da sulfassalazina).', 'Inhibition of the intestinal folate transporter by sulfapyridine (a sulfasalazine metabolite).', 'Considerar suplementação de ácido fólico em doentes em tratamento prolongado, sobretudo se anemia ou gravidez.', 'Consider folic acid supplementation in patients on long-term therapy, especially with anaemia or pregnancy.', 'Vigiar hemograma e sinais de anemia megaloblástica.', 'Monitor blood count and signs of megaloblastic anaemia.', 'Anemia megaloblástica.', 'Megaloblastic anaemia.', 'DailyMed (FDA) — rótulo aprovado Sulfassalazina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d967092f-9685-446b-b7b8-17821e29417b ; rótulo aprovado Ácido fólico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0baa10dd-6d1d-4946-8236-566451132da3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sulfasalazine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d967092f-9685-446b-b7b8-17821e29417b ; approved Folic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0baa10dd-6d1d-4946-8236-566451132da3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sulfassalazina', 'azatioprina', 'moderate', 'A sulfassalazina, como a mesalazina, pode inibir a TPMT e aumentar a toxicidade da azatioprina.', 'Sulfasalazine, like mesalazine, may inhibit TPMT and increase azathioprine toxicity.', 'Inibição da TPMT pela sulfassalazina com aumento dos metabolitos ativos da azatioprina.', 'TPMT inhibition by sulfasalazine with increased active azathioprine metabolites.', 'Monitorizar hemograma e dose de azatioprina.', 'Monitor blood count and azathioprine dose.', 'Hemograma periódico.', 'Periodic blood count.', 'Mielossupressão.', 'Myelosuppression.', 'DailyMed (FDA) — rótulo aprovado Sulfassalazina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d967092f-9685-446b-b7b8-17821e29417b ; rótulo aprovado Azatioprina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5116b22b-1460-5535-e063-6394a90acbe5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sulfasalazine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d967092f-9685-446b-b7b8-17821e29417b ; approved Azathioprine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5116b22b-1460-5535-e063-6394a90acbe5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('omeprazol', 'warfarina', 'moderate', 'O omeprazol pode aumentar ligeiramente o efeito da varfarina, com risco de elevação do INR.', 'Omeprazole may slightly increase the effect of warfarin, with a risk of INR elevation.', 'O omeprazol inibe o CYP2C19 e pode alterar o metabolismo da varfarina (isómero R).', 'Omeprazole inhibits CYP2C19 and may alter warfarin metabolism (R-isomer).', 'Monitorizar o INR ao iniciar ou suspender o omeprazol.', 'Monitor the INR when starting or stopping omeprazole.', 'Monitorizar INR com maior frequência.', 'Monitor the INR more frequently.', 'Hemorragia por INR supraterapêutico.', 'Bleeding from supratherapeutic INR.', 'DailyMed (FDA) — rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('omeprazol', 'antiacidos', 'moderate', 'Os antiácidos podem reduzir a absorção do omeprazol se tomados em simultâneo.', 'Antacids may reduce omeprazole absorption when taken at the same time.', 'Alteração do pH e da dissolução das cápsulas gastrorresistentes pelo antiácido.', 'Gastric pH change and altered dissolution of gastro-resistant capsules by the antacid.', 'Separar as tomas (2 horas).', 'Separate administration times (2 hours).', 'Vigiar a resposta à terapêutica antiácida/antiulcerosa.', 'Monitor response to antacid/anti-ulcer therapy.', 'Controlo insuficiente dos sintomas.', 'Insufficient symptom control.', 'DailyMed (FDA) — rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('antiacidos', 'levotiroxina', 'moderate', 'Os antiácidos (alumínio e magnésio) reduzem a absorção da levotiroxina se tomados em simultâneo.', 'Antacids (aluminium and magnesium) reduce levothyroxine absorption when taken at the same time.', 'Quelação/adsorção da levotiroxina pelos catiões do antiácido.', 'Chelation/adsorption of levothyroxine by antacid cations.', 'Separar as tomas (4 horas) e monitorizar TSH.', 'Separate administration times (4 hours) and monitor TSH.', 'Monitorizar TSH e sintomas de hipotiroidismo.', 'Monitor TSH and hypothyroidism symptoms.', 'Hipotiroidismo descompensado.', 'Decompensated hypothyroidism.', 'DailyMed (FDA) — rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f ; rótulo aprovado Levotiroxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f ; approved Levothyroxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55f4c679-86cb-b97f-e063-6294a90ad5ef — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)')
) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('nistatina', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'A suspensão oral de nistatina deve ser mantida em contacto com a mucosa oral; os alimentos podem interferir com a adesão.', 'Oral nystatin suspension should be kept in contact with the oral mucosa; food may interfere with adherence.', 'Administrar após as refeições e manter em contacto com as lesões.', 'Give after meals and keep in contact with the lesions.', 'EMC-UK (MHRA) — SmPC aprovada Nistatina: https://www.medicines.org.uk/emc/product/408/smpc', 'EMC-UK (MHRA) — approved Nystatin SmPC: https://www.medicines.org.uk/emc/product/408/smpc', 1),
  ('famotidina', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'Os alimentos não afetam de forma clinicamente relevante a absorção da famotidina.', 'Food does not clinically affect famotidine absorption.', 'Pode ser tomado com ou sem alimentos, conforme preferência.', 'May be taken with or without food, as preferred.', 'EMC-UK (MHRA) — SmPC aprovada Famotidina: https://www.medicines.org.uk/emc/product/100584/smpc', 'EMC-UK (MHRA) — approved Famotidine SmPC: https://www.medicines.org.uk/emc/product/100584/smpc', 1),
  ('sucralfato', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'moderate', 'Os alimentos (proteínas) podem reduzir a ligação do sucralfato à mucosa e o seu efeito protetor.', 'Food (proteins) may reduce sucralfate binding to the mucosa and its protective effect.', 'Tomar em jejum, 1 hora antes das refeições e ao deitar.', 'Take on an empty stomach, 1 hour before meals and at bedtime.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f', 1),
  ('metoclopramida', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'A metoclopramida deve ser tomada antes das refeições para otimizar o efeito procinético.', 'Metoclopramide should be taken before meals to optimise the prokinetic effect.', 'Tomar 30 minutos antes das refeições.', 'Take 30 minutes before meals.', 'EMC-UK (MHRA) — SmPC aprovada Metoclopramida: https://www.medicines.org.uk/emc/product/6213/smpc', 'EMC-UK (MHRA) — approved Metoclopramide SmPC: https://www.medicines.org.uk/emc/product/6213/smpc', 1),
  ('domperidona', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'A domperidona deve ser tomada antes das refeições para otimizar o efeito procinético.', 'Domperidone should be taken before meals to optimise the prokinetic effect.', 'Tomar 15–30 minutos antes das refeições.', 'Take 15–30 minutes before meals.', 'EMC-UK (MHRA) — SmPC aprovada Domperidona: https://www.medicines.org.uk/emc/product/3188/smpc', 'EMC-UK (MHRA) — approved Domperidone SmPC: https://www.medicines.org.uk/emc/product/3188/smpc', 1),
  ('loperamida', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool potencia a depressão do sistema nervoso central associada à loperamida.', 'Alcohol potentiates the CNS depression associated with loperamide.', 'Evitar o consumo de álcool durante o tratamento.', 'Avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Loperamida: https://www.medicines.org.uk/emc/product/2986/smpc', 'EMC-UK (MHRA) — approved Loperamide SmPC: https://www.medicines.org.uk/emc/product/2986/smpc', 1),
  ('butilbrometo_hioscina', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'O butilbrometo de hioscina deve ser tomado antes das refeições para otimizar o efeito antiespasmódico.', 'Hyoscine butylbromide should be taken before meals to optimise the antispasmodic effect.', 'Tomar 30 minutos antes das refeições.', 'Take 30 minutes before meals.', 'EMC-UK (MHRA) — SmPC aprovada Butilbrometo de hioscina: https://www.medicines.org.uk/emc/product/1775/smpc', 'EMC-UK (MHRA) — approved Hyoscine butylbromide SmPC: https://www.medicines.org.uk/emc/product/1775/smpc', 1),
  ('orlistat', 'refeicoes_gordurosas', 'Refeições ricas em gordura', 'Fat-rich meals', 'moderate', 'Refeições muito ricas em gordura aumentam os efeitos gastrointestinais do orlistato (esteatorreia, flatulência).', 'Very fatty meals increase orlistat gastrointestinal effects (steatorrhoea, flatulence).', 'Tomar o orlistato com ou até 1 hora após as refeições; manter dieta com gordura moderada.', 'Take orlistat with or up to 1 hour after meals; keep a moderate-fat diet.', 'EMC-UK (MHRA) — SmPC aprovada Orlistato: https://www.medicines.org.uk/emc/product/6533/smpc', 'EMC-UK (MHRA) — approved Orlistat SmPC: https://www.medicines.org.uk/emc/product/6533/smpc', 1),
  ('orlistat', 'vitaminas_lipossoliveis', 'Suplementos de vitaminas lipossolúveis (A, D, E, K)', 'Fat-soluble vitamin supplements (A, D, E, K)', 'moderate', 'O orlistato reduz a absorção das vitaminas lipossolúveis.', 'Orlistat reduces absorption of fat-soluble vitamins.', 'Tomar suplementos multivitamínicos pelo menos 2 horas após o orlistato.', 'Take multivitamin supplements at least 2 hours after orlistat.', 'EMC-UK (MHRA) — SmPC aprovada Orlistato: https://www.medicines.org.uk/emc/product/6533/smpc', 'EMC-UK (MHRA) — approved Orlistat SmPC: https://www.medicines.org.uk/emc/product/6533/smpc', 1),
  ('mesalazina', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'Tomar a mesalazina com alimentos reduz o desconforto gastrointestinal.', 'Taking mesalazine with food reduces gastrointestinal discomfort.', 'Tomar com alimentos, conforme a formulação.', 'Take with food, as per the formulation.', 'EMC-UK (MHRA) — SmPC aprovada Mesalazina: https://www.medicines.org.uk/emc/product/6167/smpc', 'EMC-UK (MHRA) — approved Mesalazine SmPC: https://www.medicines.org.uk/emc/product/6167/smpc', 1),
  ('sulfassalazina', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'Os alimentos podem reduzir a absorção da sulfassalazina, mas melhoram a tolerância gastrointestinal.', 'Food may reduce sulfasalazine absorption but improves gastrointestinal tolerance.', 'Tomar com alimentos para reduzir a intolerância gástrica.', 'Take with food to reduce gastric intolerance.', 'EMC-UK (MHRA) — SmPC aprovada Sulfassalazina: https://www.medicines.org.uk/emc/product/6686/smpc', 'EMC-UK (MHRA) — approved Sulfasalazine SmPC: https://www.medicines.org.uk/emc/product/6686/smpc', 1),
  ('acido_ursodesoxicolico', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'Tomar o ácido ursodesoxicólico com alimentos otimiza a sua dissolução e absorção.', 'Taking ursodeoxycholic acid with food optimises its dissolution and absorption.', 'Tomar às refeições.', 'Take with meals.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ursodesoxicólico: https://www.medicines.org.uk/emc/product/101999/smpc', 'EMC-UK (MHRA) — approved Ursodeoxycholic acid SmPC: https://www.medicines.org.uk/emc/product/101999/smpc', 1),
  ('omeprazol', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'Os alimentos podem atrasar a absorção do omeprazol; a toma antes do pequeno-almoço otimiza a supressão ácida.', 'Food may delay omeprazole absorption; taking it before breakfast optimises acid suppression.', 'Tomar 30–60 minutos antes do pequeno-almoço.', 'Take 30–60 minutes before breakfast.', 'EMC-UK (MHRA) — SmPC aprovada Omeprazol: https://www.medicines.org.uk/emc/product/1509/smpc', 'EMC-UK (MHRA) — approved Omeprazole SmPC: https://www.medicines.org.uk/emc/product/1509/smpc', 1),
  ('antiacidos', 'alimentos_refeicao', 'Refeições (recomendação de toma)', 'Meals (administration advice)', 'minor', 'Os antiácidos atuam mais eficazmente após as refeições e ao deitar.', 'Antacids work most effectively after meals and at bedtime.', 'Tomar 1–2 horas após as refeições e ao deitar.', 'Take 1–2 hours after meals and at bedtime.', 'DailyMed (FDA) — rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f', 'DailyMed (FDA) — approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('famotidina', 'insuficiencia_renal_grave', 'Insuficiência renal grave (CrCl < 30 ml/min)', 'Severe renal impairment (CrCl < 30 ml/min)', 'precaution', 'moderate', 'A famotidina é eliminada predominantemente por via renal; a sua semi-vida prolonga-se na insuficiência renal grave.', 'Famotidine is predominantly renally eliminated; its half-life is prolonged in severe renal impairment.', 'Reduzir a dose na insuficiência renal grave.', 'Reduce the dose in severe renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Famotidina: https://www.medicines.org.uk/emc/product/100584/smpc', 'EMC-UK (MHRA) — approved Famotidine SmPC: https://www.medicines.org.uk/emc/product/100584/smpc', 1),
  ('sucralfato', 'insuficiencia_renal_grave', 'Insuficiência renal grave / doença renal terminal', 'Severe renal impairment / end-stage renal disease', 'precaution', 'moderate', 'O sucralfato contém alumínio, que pode acumular-se em doentes com insuficiência renal, com risco de toxicidade (encefalopatia, osteomalácia).', 'Sucralfate contains aluminium, which may accumulate in renal impairment, with a risk of toxicity (encephalopathy, osteomalacia).', 'Evitar o uso prolongado ou doses altas em doentes renais graves; considerar alternativas.', 'Avoid prolonged use or high doses in severe renal disease; consider alternatives.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f', 1),
  ('metoclopramida', 'doenca_parkinson', 'Doença de Parkinson', 'Parkinson''s disease', 'contraindication', 'critical', 'A metoclopramida é antagonista dopaminérgico e pode agravar os sintomas parkinsónicos.', 'Metoclopramide is a dopamine antagonist and may worsen parkinsonian symptoms.', 'Não usar em doentes com doença de Parkinson.', 'Do not use in patients with Parkinson''s disease.', 'EMC-UK (MHRA) — SmPC aprovada Metoclopramida: https://www.medicines.org.uk/emc/product/6213/smpc', 'EMC-UK (MHRA) — approved Metoclopramide SmPC: https://www.medicines.org.uk/emc/product/6213/smpc', 1),
  ('metoclopramida', 'epilepsia', 'Epilepsia / antecedentes convulsivos', 'Epilepsy / seizure history', 'precaution', 'moderate', 'A metoclopramida pode reduzir o limiar convulsivo.', 'Metoclopramide may lower the seizure threshold.', 'Usar com precaução e vigiar sinais neurológicos.', 'Use with caution and monitor neurological signs.', 'EMC-UK (MHRA) — SmPC aprovada Metoclopramida: https://www.medicines.org.uk/emc/product/6213/smpc', 'EMC-UK (MHRA) — approved Metoclopramide SmPC: https://www.medicines.org.uk/emc/product/6213/smpc', 1),
  ('metoclopramida', 'feocromocitoma', 'Feocromocitoma', 'Phaeochromocytoma', 'contraindication', 'critical', 'A metoclopramida pode provocar crises hipertensivas graves em doentes com feocromocitoma.', 'Metoclopramide may cause severe hypertensive crises in patients with phaeochromocytoma.', 'Não usar em doentes com feocromocitoma.', 'Do not use in patients with phaeochromocytoma.', 'EMC-UK (MHRA) — SmPC aprovada Metoclopramida: https://www.medicines.org.uk/emc/product/6213/smpc', 'EMC-UK (MHRA) — approved Metoclopramide SmPC: https://www.medicines.org.uk/emc/product/6213/smpc', 1),
  ('domperidona', 'doenca_hepatica_grave', 'Insuficiência hepática moderada a grave', 'Moderate to severe hepatic impairment', 'contraindication', 'critical', 'A domperidona está contraindicada na insuficiência hepática moderada a grave devido ao risco aumentado de prolongamento do QT.', 'Domperidone is contraindicated in moderate to severe hepatic impairment due to an increased risk of QT prolongation.', 'Não usar na insuficiência hepática moderada a grave.', 'Do not use in moderate to severe hepatic impairment.', 'EMC-UK (MHRA) — SmPC aprovada Domperidona: https://www.medicines.org.uk/emc/product/3188/smpc', 'EMC-UK (MHRA) — approved Domperidone SmPC: https://www.medicines.org.uk/emc/product/3188/smpc', 1),
  ('domperidona', 'prolongamento_qt', 'Prolongamento do intervalo QT (congénito ou adquirido)', 'QT-interval prolongation (congenital or acquired)', 'contraindication', 'critical', 'A domperidona prolonga o intervalo QT e está contraindicada quando o QT já está prolongado.', 'Domperidone prolongs the QT interval and is contraindicated when the QT is already prolonged.', 'Não usar em doentes com QT prolongado ou com fármacos que prolonguem o QT.', 'Do not use in patients with QT prolongation or QT-prolonging drugs.', 'EMC-UK (MHRA) — SmPC aprovada Domperidona: https://www.medicines.org.uk/emc/product/3188/smpc', 'EMC-UK (MHRA) — approved Domperidone SmPC: https://www.medicines.org.uk/emc/product/3188/smpc', 1),
  ('loperamida', 'colite_ulcerosa_aguda', 'Colite ulcerosa aguda / colite pseudomembranosa', 'Acute ulcerative colitis / pseudomembranous colitis', 'contraindication', 'critical', 'A loperamida pode precipitar megacólon tóxico na colite ulcerosa aguda.', 'Loperamide may precipitate toxic megacolon in acute ulcerative colitis.', 'Não usar na colite ulcerosa aguda ou colite associada a antibióticos.', 'Do not use in acute ulcerative colitis or antibiotic-associated colitis.', 'EMC-UK (MHRA) — SmPC aprovada Loperamida: https://www.medicines.org.uk/emc/product/2986/smpc', 'EMC-UK (MHRA) — approved Loperamide SmPC: https://www.medicines.org.uk/emc/product/2986/smpc', 1),
  ('loperamida', 'doenca_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical', 'A loperamida sofre metabolismo de primeira passagem; na insuficiência hepática grave há risco de acumulação e toxicidade no SNC.', 'Loperamide undergoes first-pass metabolism; severe hepatic impairment carries a risk of accumulation and CNS toxicity.', 'Não usar na insuficiência hepática grave.', 'Do not use in severe hepatic impairment.', 'EMC-UK (MHRA) — SmPC aprovada Loperamida: https://www.medicines.org.uk/emc/product/2986/smpc', 'EMC-UK (MHRA) — approved Loperamide SmPC: https://www.medicines.org.uk/emc/product/2986/smpc', 1),
  ('ondansetron', 'prolongamento_qt', 'Prolongamento do intervalo QT (congénito ou adquirido)', 'QT-interval prolongation (congenital or acquired)', 'precaution', 'moderate', 'O ondansetrom pode prolongar o intervalo QT, sobretudo em doses altas.', 'Ondansetron may prolong the QT interval, especially at high doses.', 'Usar com precaução; evitar doses > 16 mg e associações com outros fármacos QT.', 'Use with caution; avoid doses > 16 mg and combinations with other QT drugs.', 'EMC-UK (MHRA) — SmPC aprovada Ondansetrom: https://www.medicines.org.uk/emc/product/5222/smpc', 'EMC-UK (MHRA) — approved Ondansetron SmPC: https://www.medicines.org.uk/emc/product/5222/smpc', 1),
  ('ondansetron', 'doenca_hepatica', 'Doença hepática (insuficiência hepática)', 'Hepatic disease (hepatic impairment)', 'precaution', 'moderate', 'O ondansetrom é metabolizado no fígado; a depuração está reduzida na insuficiência hepática moderada a grave.', 'Ondansetron is hepatically metabolised; clearance is reduced in moderate to severe hepatic impairment.', 'Limitar a dose diária máxima na insuficiência hepática.', 'Limit the maximum daily dose in hepatic impairment.', 'EMC-UK (MHRA) — SmPC aprovada Ondansetrom: https://www.medicines.org.uk/emc/product/5222/smpc', 'EMC-UK (MHRA) — approved Ondansetron SmPC: https://www.medicines.org.uk/emc/product/5222/smpc', 1),
  ('butilbrometo_hioscina', 'glaucoma_angulo_fechado', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma', 'contraindication', 'critical', 'O efeito anticolinérgico pode precipitar um ataque agudo de glaucoma de ângulo fechado.', 'The antimuscarinic effect may precipitate an acute angle-closure glaucoma attack.', 'Não usar em doentes com glaucoma de ângulo fechado.', 'Do not use in patients with angle-closure glaucoma.', 'EMC-UK (MHRA) — SmPC aprovada Butilbrometo de hioscina: https://www.medicines.org.uk/emc/product/1775/smpc', 'EMC-UK (MHRA) — approved Hyoscine butylbromide SmPC: https://www.medicines.org.uk/emc/product/1775/smpc', 1),
  ('butilbrometo_hioscina', 'retencao_urinaria', 'Retenção urinária / hiperplasia prostática', 'Urinary retention / prostatic hyperplasia', 'precaution', 'moderate', 'O efeito anticolinérgico pode agravar a retenção urinária.', 'The antimuscarinic effect may worsen urinary retention.', 'Usar com precaução em doentes com obstrução urinária.', 'Use with caution in patients with urinary obstruction.', 'EMC-UK (MHRA) — SmPC aprovada Butilbrometo de hioscina: https://www.medicines.org.uk/emc/product/1775/smpc', 'EMC-UK (MHRA) — approved Hyoscine butylbromide SmPC: https://www.medicines.org.uk/emc/product/1775/smpc', 1),
  ('orlistat', 'sindrome_malabsorcao', 'Síndrome de má absorção crónica', 'Chronic malabsorption syndrome', 'contraindication', 'critical', 'O orlistato agrava a má absorção de gorduras e vitaminas lipossolúveis.', 'Orlistat worsens malabsorption of fats and fat-soluble vitamins.', 'Não usar em doentes com síndrome de má absorção crónica.', 'Do not use in patients with chronic malabsorption syndrome.', 'EMC-UK (MHRA) — SmPC aprovada Orlistato: https://www.medicines.org.uk/emc/product/6533/smpc', 'EMC-UK (MHRA) — approved Orlistat SmPC: https://www.medicines.org.uk/emc/product/6533/smpc', 1),
  ('orlistat', 'colestase', 'Colestase', 'Cholestasis', 'contraindication', 'critical', 'O orlistato está contraindicado na colestase (ficha técnica).', 'Orlistat is contraindicated in cholestasis (SmPC).', 'Não usar em doentes com colestase.', 'Do not use in patients with cholestasis.', 'EMC-UK (MHRA) — SmPC aprovada Orlistato: https://www.medicines.org.uk/emc/product/6533/smpc', 'EMC-UK (MHRA) — approved Orlistat SmPC: https://www.medicines.org.uk/emc/product/6533/smpc', 1),
  ('mesalazina', 'insuficiencia_renal', 'Insuficiência renal (incluindo disfunção leve)', 'Renal impairment (including mild dysfunction)', 'precaution', 'moderate', 'A mesalazina pode causar ou agravar a nefrotoxicidade (nefrite intersticial).', 'Mesalazine may cause or worsen nephrotoxicity (interstitial nephritis).', 'Avaliar a função renal antes e durante o tratamento; ajustar ou suspender se deterioração.', 'Assess renal function before and during treatment; adjust or stop if deterioration occurs.', 'EMC-UK (MHRA) — SmPC aprovada Mesalazina: https://www.medicines.org.uk/emc/product/6167/smpc', 'EMC-UK (MHRA) — approved Mesalazine SmPC: https://www.medicines.org.uk/emc/product/6167/smpc', 1),
  ('mesalazina', 'doenca_hepatica', 'Doença hepática (insuficiência hepática)', 'Hepatic disease (hepatic impairment)', 'precaution', 'moderate', 'A mesalazina pode alterar a função hepática; vigiar em doentes com doença hepática.', 'Mesalazine may affect liver function; monitor in patients with hepatic disease.', 'Usar com precaução e monitorizar transaminases.', 'Use with caution and monitor transaminases.', 'EMC-UK (MHRA) — SmPC aprovada Mesalazina: https://www.medicines.org.uk/emc/product/6167/smpc', 'EMC-UK (MHRA) — approved Mesalazine SmPC: https://www.medicines.org.uk/emc/product/6167/smpc', 1),
  ('sulfassalazina', 'alergia_sulfonamidas', 'Alergia a sulfonamidas', 'Sulphonamide allergy', 'contraindication', 'critical', 'A sulfassalazina contém sulfapiridina (sulfonamida); pode causar reações alérgicas graves.', 'Sulfasalazine contains sulfapyridine (a sulphonamide); it may cause severe allergic reactions.', 'Não usar em doentes com alergia a sulfonamidas.', 'Do not use in patients with sulphonamide allergy.', 'EMC-UK (MHRA) — SmPC aprovada Sulfassalazina: https://www.medicines.org.uk/emc/product/6686/smpc', 'EMC-UK (MHRA) — approved Sulfasalazine SmPC: https://www.medicines.org.uk/emc/product/6686/smpc', 1),
  ('sulfassalazina', 'insuficiencia_renal', 'Insuficiência renal (incluindo disfunção leve)', 'Renal impairment (including mild dysfunction)', 'precaution', 'moderate', 'A sulfassalazina e os seus metabolitos podem acumular-se na insuficiência renal.', 'Sulfasalazine and its metabolites may accumulate in renal impairment.', 'Usar com precaução e monitorizar a função renal.', 'Use with caution and monitor renal function.', 'EMC-UK (MHRA) — SmPC aprovada Sulfassalazina: https://www.medicines.org.uk/emc/product/6686/smpc', 'EMC-UK (MHRA) — approved Sulfasalazine SmPC: https://www.medicines.org.uk/emc/product/6686/smpc', 1),
  ('acido_ursodesoxicolico', 'colestase_obstrutiva', 'Colestase obstrutiva (obstrução biliar)', 'Obstructive cholestasis (biliary obstruction)', 'contraindication', 'critical', 'O ácido ursodesoxicólico está contraindicado na obstrução das vias biliares e em doentes com colangite não drenada.', 'Ursodeoxycholic acid is contraindicated in biliary obstruction and in patients with undrained cholangitis.', 'Não usar em doentes com obstrução biliar.', 'Do not use in patients with biliary obstruction.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ursodesoxicólico: https://www.medicines.org.uk/emc/product/101999/smpc', 'EMC-UK (MHRA) — approved Ursodeoxycholic acid SmPC: https://www.medicines.org.uk/emc/product/101999/smpc', 1),
  ('omeprazol', 'osteoporose', 'Osteoporose / risco de fratura', 'Osteoporosis / fracture risk', 'precaution', 'moderate', 'O uso prolongado de inibidores da bomba de protões está associado a aumento do risco de fraturas.', 'Long-term proton pump inhibitor use is associated with an increased risk of fractures.', 'Usar a menor dose e duração eficazes; considerar suplementação de cálcio/vitamina D quando indicado.', 'Use the lowest effective dose and duration; consider calcium/vitamin D supplementation when indicated.', 'EMC-UK (MHRA) — SmPC aprovada Omeprazol: https://www.medicines.org.uk/emc/product/1509/smpc', 'EMC-UK (MHRA) — approved Omeprazole SmPC: https://www.medicines.org.uk/emc/product/1509/smpc', 1),
  ('omeprazol', 'hipomagnesemia', 'Hipomagnesemia', 'Hypomagnesaemia', 'precaution', 'moderate', 'O uso prolongado de omeprazol pode causar hipomagnesemia sintomática.', 'Long-term omeprazole may cause symptomatic hypomagnesaemia.', 'Vigiar o magnésio sérico em tratamentos prolongados (> 1 ano), sobretudo com diuréticos ou digoxina.', 'Check serum magnesium in long-term therapy (> 1 year), especially with diuretics or digoxin.', 'EMC-UK (MHRA) — SmPC aprovada Omeprazol: https://www.medicines.org.uk/emc/product/1509/smpc', 'EMC-UK (MHRA) — approved Omeprazole SmPC: https://www.medicines.org.uk/emc/product/1509/smpc', 1),
  ('antiacidos', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'Os catiões alumínio e magnésio dos antiácidos podem acumular-se na insuficiência renal.', 'Aluminium and magnesium cations from antacids may accumulate in renal impairment.', 'Evitar uso prolongado ou doses altas em doentes com insuficiência renal grave.', 'Avoid prolonged use or high doses in severe renal impairment.', 'DailyMed (FDA) — rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f', 'DailyMed (FDA) — approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('nistatina', 'compatible', 'A nistatina oral tem absorção sistémica mínima e é o antifúngico de escolha na candidíase oral na gravidez.', 'Oral nystatin has minimal systemic absorption and is the antifungal of choice for oral candidiasis in pregnancy.', 'Pode ser usada em todos os trimestres.', 'Can be used in all trimesters.', 'Excreção no leite insignificante; compatível com o aleitamento.', 'Excretion into breast milk is negligible; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Nistatina: https://www.medicines.org.uk/emc/product/408/smpc', 'EMC-UK (MHRA) — approved Nystatin SmPC: https://www.medicines.org.uk/emc/product/408/smpc'),
  ('famotidina', 'caution', 'Os dados sobre famotidina na gravidez são limitados; os antagonistas H2 são usados quando os antiácidos são insuficientes.', 'Data on famotidine in pregnancy are limited; H2 antagonists are used when antacids are insufficient.', 'Usar apenas se o benefício superar o risco, preferencialmente no 2.º/3.º trimestre.', 'Use only if the benefit outweighs the risk, preferably in the 2nd/3rd trimester.', 'Excretado no leite em pequenas quantidades; compatível com o aleitamento.', 'Excreted into breast milk in small amounts; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Famotidina: https://www.medicines.org.uk/emc/product/100584/smpc', 'EMC-UK (MHRA) — approved Famotidine SmPC: https://www.medicines.org.uk/emc/product/100584/smpc'),
  ('sucralfato', 'compatible', 'O sucralfato tem absorção sistémica mínima, sendo considerado de baixo risco na gravidez.', 'Sucralfate has minimal systemic absorption and is considered low risk in pregnancy.', 'Pode ser usado em todos os trimestres se necessário.', 'Can be used in all trimesters if needed.', 'Excreção no leite insignificante; compatível com o aleitamento.', 'Excretion into breast milk is negligible; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f'),
  ('metoclopramida', 'caution', 'A metoclopramida é usada na gravidez (hiperémese), mas deve ser usada com precaução no 1.º trimestre e em doses baixas.', 'Metoclopramide is used in pregnancy (hyperemesis), but should be used with caution in the 1st trimester and at low doses.', 'Usar a menor dose eficaz e pelo menor tempo possível.', 'Use the lowest effective dose for the shortest time possible.', 'Excretado no leite em pequenas quantidades; uso pontual provavelmente compatível.', 'Excreted into breast milk in small amounts; occasional use is probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Metoclopramida: https://www.medicines.org.uk/emc/product/6213/smpc', 'EMC-UK (MHRA) — approved Metoclopramide SmPC: https://www.medicines.org.uk/emc/product/6213/smpc'),
  ('domperidona', 'caution', 'Os dados sobre domperidona na gravidez são limitados; usar apenas se o benefício superar o risco.', 'Data on domperidone in pregnancy are limited; use only if the benefit outweighs the risk.', 'Evitar no 1.º trimestre exceto se estritamente necessário.', 'Avoid in the 1st trimester unless strictly necessary.', 'Excretado no leite em pequenas quantidades; compatível com o aleitamento nas doses habituais.', 'Excreted into breast milk in small amounts; compatible with breastfeeding at usual doses.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Domperidona: https://www.medicines.org.uk/emc/product/3188/smpc', 'EMC-UK (MHRA) — approved Domperidone SmPC: https://www.medicines.org.uk/emc/product/3188/smpc'),
  ('loperamida', 'caution', 'A loperamida deve ser evitada na gravidez, sobretudo no 1.º trimestre, salvo sob indicação médica.', 'Loperamide should be avoided in pregnancy, especially in the 1st trimester, unless medically indicated.', 'Usar apenas se estritamente necessário e pelo menor tempo possível.', 'Use only if strictly necessary and for the shortest time.', 'Excretado no leite em pequenas quantidades; uso pontual provavelmente compatível.', 'Excreted into breast milk in small amounts; occasional use is probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Loperamida: https://www.medicines.org.uk/emc/product/2986/smpc', 'EMC-UK (MHRA) — approved Loperamide SmPC: https://www.medicines.org.uk/emc/product/2986/smpc'),
  ('ondansetron', 'caution', 'O ondansetrom é usado na hiperémese gravídica; a evidência sobre malformações é limitada e não conclui risco claro.', 'Ondansetron is used in hyperemesis gravidarum; evidence on malformations is limited and does not show a clear risk.', 'Usar apenas se os antieméticos de primeira linha forem insuficientes, preferencialmente no 2.º/3.º trimestre.', 'Use only if first-line antiemetics are insufficient, preferably in the 2nd/3rd trimester.', 'Excretado no leite em pequenas quantidades; provavelmente compatível.', 'Excreted into breast milk in small amounts; probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Ondansetrom: https://www.medicines.org.uk/emc/product/5222/smpc', 'EMC-UK (MHRA) — approved Ondansetron SmPC: https://www.medicines.org.uk/emc/product/5222/smpc'),
  ('butilbrometo_hioscina', 'caution', 'Os dados sobre butilbrometo de hioscina na gravidez são limitados; o uso é aceite quando indicado por via oral.', 'Data on hyoscine butylbromide in pregnancy are limited; oral use is accepted when indicated.', 'Evitar exceto se necessário, com a menor dose eficaz.', 'Avoid unless necessary, at the lowest effective dose.', 'Excretado no leite em pequenas quantidades; provavelmente compatível.', 'Excreted into breast milk in small amounts; probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Butilbrometo de hioscina: https://www.medicines.org.uk/emc/product/1775/smpc', 'EMC-UK (MHRA) — approved Hyoscine butylbromide SmPC: https://www.medicines.org.uk/emc/product/1775/smpc'),
  ('orlistat', 'contraindicated', 'O orlistato não é recomendado na gravidez (fármaco para perda de peso; não há benefício e a perda de peso materna não é desejada).', 'Orlistat is not recommended in pregnancy (a weight-loss drug; there is no benefit and maternal weight loss is not desired).', 'Suspender antes de engravidar ou assim que a gravidez seja confirmada.', 'Stop before becoming pregnant or as soon as pregnancy is confirmed.', 'Desconhecida a excreção no leite; não recomendado durante o aleitamento.', 'Excretion into breast milk is unknown; not recommended during breastfeeding.', 'Sem contraceção adicional específica (manter a contraceção habitual).', 'No specific additional contraception (keep usual contraception).', 'EMC-UK (MHRA) — SmPC aprovada Orlistato: https://www.medicines.org.uk/emc/product/6533/smpc', 'EMC-UK (MHRA) — approved Orlistat SmPC: https://www.medicines.org.uk/emc/product/6533/smpc'),
  ('mesalazina', 'caution', 'A mesalazina pode ser usada na gravidez para controlo da doença inflamatória intestinal; o benefício geralmente supera o risco.', 'Mesalazine may be used in pregnancy to control inflammatory bowel disease; benefit usually outweighs risk.', 'Manter a dose eficaz mínima; não suspender o tratamento sem orientação médica.', 'Keep the minimum effective dose; do not stop treatment without medical advice.', 'Excretado no leite em pequenas quantidades; compatível com o aleitamento.', 'Excreted into breast milk in small amounts; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Mesalazina: https://www.medicines.org.uk/emc/product/6167/smpc', 'EMC-UK (MHRA) — approved Mesalazine SmPC: https://www.medicines.org.uk/emc/product/6167/smpc'),
  ('sulfassalazina', 'caution', 'A sulfassalazina interfere com o ácido fólico; suplementar folato durante a gravidez e usar com precaução no 3.º trimestre.', 'Sulfasalazine interferes with folic acid; supplement folate during pregnancy and use with caution in the 3rd trimester.', 'Manter a suplementação de ácido fólico (ex. 1 mg/dia) durante toda a gravidez.', 'Maintain folic acid supplementation (e.g. 1 mg/day) throughout pregnancy.', 'Compatível com o aleitamento; vigiar o recém-nascido (teoria: displasia da sulfapiridina).', 'Compatible with breastfeeding; monitor the newborn (sulfapyridine theoretical concerns).', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Sulfassalazina: https://www.medicines.org.uk/emc/product/6686/smpc', 'EMC-UK (MHRA) — approved Sulfasalazine SmPC: https://www.medicines.org.uk/emc/product/6686/smpc'),
  ('acido_ursodesoxicolico', 'caution', 'O ácido ursodesoxicólico é usado na colestase intra-hepática da gravidez; pode ser usado quando indicado.', 'Ursodeoxycholic acid is used in intrahepatic cholestasis of pregnancy; it may be used when indicated.', 'Usar sob orientação médica, geralmente no 2.º/3.º trimestre para colestase da gravidez.', 'Use under medical guidance, usually in the 2nd/3rd trimester for cholestasis of pregnancy.', 'Excretado no leite em pequenas quantidades; provavelmente compatível.', 'Excreted into breast milk in small amounts; probably compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ursodesoxicólico: https://www.medicines.org.uk/emc/product/101999/smpc', 'EMC-UK (MHRA) — approved Ursodeoxycholic acid SmPC: https://www.medicines.org.uk/emc/product/101999/smpc'),
  ('omeprazol', 'compatible', 'O omeprazol é amplamente usado na gravidez (refluxo/pirose); a evidência disponível não indica risco aumentado de malformações.', 'Omeprazole is widely used in pregnancy (reflux/heartburn); available evidence does not indicate an increased risk of malformations.', 'Pode ser usado em todos os trimestres quando indicado.', 'Can be used in all trimesters when indicated.', 'Excretado no leite em pequenas quantidades; compatível com o aleitamento.', 'Excreted into breast milk in small amounts; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Omeprazol: https://www.medicines.org.uk/emc/product/1509/smpc', 'EMC-UK (MHRA) — approved Omeprazole SmPC: https://www.medicines.org.uk/emc/product/1509/smpc'),
  ('antiacidos', 'compatible', 'Os antiácidos de alumínio e magnésio são considerados seguros na gravidez nas doses habituais e em curto prazo.', 'Aluminium and magnesium antacids are considered safe in pregnancy at usual doses and short term.', 'Pode ser usado em todos os trimestres; evitar doses altas prolongadas (acumulação de alumínio).', 'Can be used in all trimesters; avoid prolonged high doses (aluminium accumulation).', 'Excretado no leite em pequenas quantidades; compatível com o aleitamento.', 'Excreted into breast milk in small amounts; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'DailyMed (FDA) — rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f', 'DailyMed (FDA) — approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;