-- ================================================================
-- 067_seed_interacoes_musculoesqueleticas.sql
-- Secção 9 (Aparelho osteoarticular): 9.1 AINE; 9.2 Modificadores da
-- evolução da doença reumática; 9.3 Medicamentos para a gota;
-- 9.4 Medicamentos para a artrose; 9.6 Osso e metabolismo do cálcio.
-- (9.5 Enzimas anti-inflamatórias: tópicos/inespecíficos — sem fármaco
-- sistémico novo, fora do âmbito.)
-- Novos (8): naproxeno, celecoxib, metotrexato, leflunomida, colchicina,
--            febuxostat, alendronato, calcitriol.
-- Extensão 3 dimensões (existentes): aspirina, ibuprofeno, diclofenac,
--            alopurinol, azatioprina, prednisolona, hidroxicloroquina.
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico; fallback DailyMed (FDA).
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('naproxeno', 'Naproxeno', 'Naproxen', 'AINE não seletivo (anti-inflamatório/analgésico)', 'Non-steroidal anti-inflammatory (NSAID)', ARRAY['Naprosyn', 'Aleve', 'naproxeno sódico', 'naproxen'], 'published', 151),
  ('celecoxib', 'Celecoxib', 'Celecoxib', 'AINE seletivo COX-2 (coxibe)', 'Selective COX-2 NSAID (coxib)', ARRAY['Celebrex', 'celecoxib'], 'published', 152),
  ('metotrexato', 'Metotrexato', 'Methotrexate', 'DMARD anti-metabólito (antifólico)', 'DMARD anti-metabolite (antifolate)', ARRAY['Methotrexate', 'metotrexato'], 'published', 153),
  ('leflunomida', 'Leflunomida', 'Leflunomide', 'DMARD (inibidor da síntese de pirimidinas)', 'DMARD (pyrimidine synthesis inhibitor)', ARRAY['Arava', 'leflunomida', 'leflunomide'], 'published', 154),
  ('colchicina', 'Colchicina', 'Colchicine', 'Alcaloide antigotoso (anti-inflamatório dos microtúbulos)', 'Antigout alkaloid (anti-inflammatory via microtubules)', ARRAY['colchicine', 'Yuzu'], 'published', 155),
  ('febuxostat', 'Febuxostat', 'Febuxostat', 'Inibidor da xantina-oxidase (redutor da uricemia)', 'Xanthine oxidase inhibitor (uric-lowering)', ARRAY['Adenuric', 'febuxostat'], 'published', 156),
  ('alendronato', 'Alendronato sódico', 'Sodium alendronate', 'Bifosfonato (anti-reabsortivo ósseo)', 'Bisphosphonate (anti-resorptive)', ARRAY['Fosamax', 'ácido alendrónico', 'alendronic acid', 'sodium alendronate'], 'published', 157),
  ('calcitriol', 'Calcitriol', 'Calcitriol', 'Hormona da vitamina D (regulação do cálcio/fósforo)', 'Vitamin D hormone (calcium/phosphate regulation)', ARRAY['Rocaltrol', 'calcitriol', '1,25-dihidroxicolecalciferol', 'alatrofisterol'], 'published', 158);

-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('naproxeno', 'warfarina', 'moderate', 'AINE + anticoagulante: aumento do risco hemorrágico (gastrointestinal e sistémico).', 'NSAID + anticoagulant: increased bleeding risk (gastrointestinal and systemic).', 'Os AINE inibem a COX e a agregação plaquetária e podem deslocar a Varfarina da ligação proteica, potenciando o efeito anticoagulante.', 'NSAIDs inhibit COX and platelet aggregation and may displace warfarin from protein binding, enhancing anticoagulation.', 'Usar a menor dose de AINE pelo menor tempo; considerar gastroprotecção (IBP). Vigiar sinais de hemorragia.', 'Use the lowest NSAID dose for the shortest time; consider gastroprotection (PPI). Watch for signs of bleeding.', 'INR com maior frequência durante a introdução do AINE; avaliar hemograma e sintomas digestivos.', 'More frequent INR monitoring when starting the NSAID; assess full blood count and GI symptoms.', 'Sangue nas fezes/melena, hematemese, hemorragia cutânea ou mucosas.', 'Blood in stools/melena, haematemesis, skin or mucosal bleeding.', 'DailyMed (FDA) — rótulo aprovado Naproxeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Naproxen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('naproxeno', 'litio', 'moderate', 'AINE + lítio: risco de aumento da litemia e toxicidade pelo lítio.', 'NSAID + lithium: risk of raised serum lithium and lithium toxicity.', 'Os AINE reduzem a depuração renal do lítio (redução da excreção), elevando a litemia.', 'NSAIDs reduce renal lithium clearance (decreased excretion), raising lithium levels.', 'Suspender ou reduzir o AINE com monitorização da litemia; vigiar sinais de toxicidade do lítio.', 'Stop or reduce the NSAID with serum lithium monitoring; watch for signs of lithium toxicity.', 'Litemia e função renal durante a terapêutica combinada.', 'Serum lithium and renal function during combined therapy.', 'Náuseas, confusão, tremor, sinais de neurotoxicidade; arritmias.', 'Nausea, confusion, tremor, signs of neurotoxicity; arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Naproxeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; rótulo aprovado Lítio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=582697c1-063f-366f-e063-6294a90a8d1b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Naproxen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; approved Lithium label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=582697c1-063f-366f-e063-6294a90a8d1b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('naproxeno', 'prednisolona', 'moderate', 'Corticosteroide + AINE: risco gastrointestinal (úlcera/hemorragia) aditivo.', 'Corticosteroid + NSAID: additive gastrointestinal risk (ulcer/bleeding).', 'Ambos enfraquecem a proteção da mucosa gástrica e aumentam o risco de úlcera e hemorragia GI.', 'Both weaken gastric mucosal protection and increase the risk of GI ulcer and bleeding.', 'Combinar apenas se necessário; considerar gastroprotecção e a menor dose eficaz de ambos.', 'Combine only if necessary; consider gastroprotection and the lowest effective dose of both.', 'Vigiar dispepsia, dor abdominal e sinais de hemorragia digestiva.', 'Watch for dyspepsia, abdominal pain and signs of GI bleeding.', 'Dor abdominal, melena, hematemese.', 'Abdominal pain, melena, haematemesis.', 'DailyMed (FDA) — rótulo aprovado Naproxeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Naproxen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('naproxeno', 'ibuprofeno', 'moderate', 'Dois AINE em simultâneo: sem benefício adicional e com maior risco GI/renal.', 'Two NSAIDs together: no added benefit and increased GI/renal risk.', 'Efeitos aditivos na mucosa gástrica, na função renal e na agregação plaquetária.', 'Additive effects on gastric mucosa, renal function and platelet aggregation.', 'Não combinar AINE; usar um único AINE à menor dose eficaz.', 'Do not combine NSAIDs; use a single NSAID at the lowest effective dose.', 'Função renal e sinais de intolerância gastrointestinal em doentes de risco.', 'Renal function and GI intolerance signs in at-risk patients.', 'Dispepsia, dor epigástrica, oligúria, edema.', 'Dyspepsia, epigastric pain, oliguria, oedema.', 'DailyMed (FDA) — rótulo aprovado Naproxeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Naproxen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('naproxeno', 'aspirina', 'moderate', 'AINE + aspirina em baixa dose: pode reduzir o efeito cardioprotetor da aspirina e aumentar o risco GI.', 'NSAID + low-dose aspirin: may reduce aspirin cardioprotection and increase GI risk.', 'Os AINE podem ocupar o mesmo local ativo da COX e interferir com a inibição antiagregante irreversível da aspirina.', 'NSAIDs may occupy the same COX active site and interfere with aspirin irreversible antiplatelet inhibition.', 'Tomar a aspirina pelo menos 2 h antes do AINE quando possível; considerar paracetamol para analgesia.', 'Take aspirin at least 2 h before the NSAID when possible; consider paracetamol for analgesia.', 'Reavaliar periodicamente a necessidade da associação e a gastroproteção.', 'Periodically reassess the need for the combination and gastroprotection.', 'Sinais de evento trombótico ou hemorragia GI.', 'Signs of thrombotic event or GI bleeding.', 'DailyMed (FDA) — rótulo aprovado Naproxeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; rótulo aprovado Ácido acetilsalicílico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Naproxen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('celecoxib', 'warfarina', 'moderate', 'Coxib + anticoagulante: aumento do risco hemorrágico.', 'Coxib + anticoagulant: increased bleeding risk.', 'O celecoxib pode aumentar o risco hemorrágico gastrointestinal e interagir com a anticoagulação.', 'Celecoxib may increase gastrointestinal bleeding risk and interact with anticoagulation.', 'Usar com cautela, considerar gastroprotecção e vigiar sinais de hemorragia.', 'Use with caution, consider gastroprotection and watch for bleeding signs.', 'INR e sintomas digestivos durante a associação.', 'INR and GI symptoms during the combination.', 'Melena, hematemese, equimoses espontâneas.', 'Melena, haematemesis, spontaneous ecchymosis.', 'DailyMed (FDA) — rótulo aprovado Celecoxib: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b06ced10-81c6-4f48-a205-1e0db228cb8b ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Celecoxib label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b06ced10-81c6-4f48-a205-1e0db228cb8b ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('celecoxib', 'ibuprofeno', 'moderate', 'Dois AINE (coxib + clássico): sem benefício e com risco GI/renal/ cardiovascular acrescido.', 'Two NSAIDs (coxib + classical): no benefit and added GI/renal/cardiovascular risk.', 'Efeitos adversos aditivos na mucosa gástrica, função renal e equilíbrio cardiovascular.', 'Additive adverse effects on gastric mucosa, renal function and cardiovascular balance.', 'Não combinar AINE; usar um único AINE à menor dose eficaz.', 'Do not combine NSAIDs; use a single NSAID at the lowest effective dose.', 'Função renal, tensão arterial e sintomas GI.', 'Renal function, blood pressure and GI symptoms.', 'Dispepsia, edema, elevação da tensão arterial.', 'Dyspepsia, oedema, raised blood pressure.', 'DailyMed (FDA) — rótulo aprovado Celecoxib: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b06ced10-81c6-4f48-a205-1e0db228cb8b ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Celecoxib label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b06ced10-81c6-4f48-a205-1e0db228cb8b ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('metotrexato', 'cotrimoxazol', 'moderate', 'Antifólico + antagonista do folato: o cotrimoxazol potencia a toxicidade do metotrexato.', 'Antifolate + folate antagonist: co-trimoxazole potentiates methotrexate toxicity.', 'O trimetoprim inibe a diidrofolato-redutase e reduz a depuração renal do metotrexato, com risco de mielossupressão grave.', 'Trimethoprim inhibits dihydrofolate reductase and reduces methotrexate renal clearance, risking severe marrow suppression.', 'Evitar a associação quando possível; se inevitável, monitorizar hemograma e função renal com frequência.', 'Avoid the combination when possible; if unavoidable, monitor full blood count and renal function frequently.', 'Hemograma e função renal; reavaliar dose de metotrexato.', 'Full blood count and renal function; reassess methotrexate dose.', 'Febre, infeções, úlceras orais, anemia, leucopenia, trombocitopenia.', 'Fever, infections, oral ulcers, anaemia, leucopenia, thrombocytopenia.', 'DailyMed (FDA) — rótulo aprovado Metotrexato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Methotrexate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('metotrexato', 'ciprofloxacina', 'moderate', 'Fluoroquinolona + metotrexato: possível aumento da toxicidade do metotrexato.', 'Fluoroquinolone + methotrexate: possible increased methotrexate toxicity.', 'A ciprofloxacina pode reduzir a depuração renal do metotrexato, elevando as suas concentrações.', 'Ciprofloxacin may reduce methotrexate renal clearance, raising its concentrations.', 'Usar com precaução e monitorizar hemograma e função renal.', 'Use with caution and monitor full blood count and renal function.', 'Hemograma e função renal durante a antibioterapia.', 'Full blood count and renal function during antibiotic therapy.', 'Mielossupressão: febre, úlceras orais, infeções.', 'Marrow suppression: fever, oral ulcers, infections.', 'DailyMed (FDA) — rótulo aprovado Metotrexato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Methotrexate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('metotrexato', 'ibuprofeno', 'moderate', 'AINE + metotrexato: redução da depuração renal e aumento da toxicidade do MTX.', 'NSAID + methotrexate: reduced renal clearance and increased MTX toxicity.', 'Os AINE inibem a excreção renal do metotrexato, elevando as suas concentrações séricas.', 'NSAIDs inhibit renal excretion of methotrexate, raising serum concentrations.', 'Evitar AINE em doentes em metotrexato; se necessário, preferir paracetamol e monitorizar.', 'Avoid NSAIDs in patients on methotrexate; if needed, prefer paracetamol and monitor.', 'Hemograma e função renal; sinais clínicos de toxicidade do MTX.', 'Full blood count and renal function; clinical signs of MTX toxicity.', 'Úlceras orais, mielossupressão, hepatotoxicidade.', 'Oral ulcers, marrow suppression, hepatotoxicity.', 'DailyMed (FDA) — rótulo aprovado Metotrexato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Methotrexate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('metotrexato', 'aspirina', 'moderate', 'Aspirina + metotrexato: possível aumento da toxicidade do metotrexato (depuração renal).', 'Aspirin + methotrexate: possible increased methotrexate toxicity (renal clearance).', 'A aspirina (sobretudo em doses AINE) pode reduzir a depuração renal do metotrexato.', 'Aspirin (especially at NSAID doses) may reduce methotrexate renal clearance.', 'Preferir paracetamol quando possível; monitorizar hemograma se a associação for necessária.', 'Prefer paracetamol when possible; monitor full blood count if the combination is needed.', 'Hemograma e função renal em terapêuticas prolongadas.', 'Full blood count and renal function on long-term therapy.', 'Úlceras orais, sinais de mielossupressão.', 'Oral ulcers, signs of marrow suppression.', 'DailyMed (FDA) — rótulo aprovado Metotrexato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; rótulo aprovado Ácido acetilsalicílico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Methotrexate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('azatioprina', 'febuxostat', 'critical', 'Inibidor da xantina-oxidase + azatioprina: risco de mielossupressão grave e potencialmente fatal.', 'Xanthine oxidase inhibitor + azathioprine: risk of severe, potentially fatal marrow suppression.', 'O febuxostat (como o alopurinol) inibe a xantina-oxidase, enzima que degrada o 6-mercaptopurina ativo da azatioprina; os níveis sobem de forma acentuada.', 'Febuxostat (like allopurinol) inhibits xanthine oxidase, the enzyme that degrades the active 6-mercaptopurine from azathioprine; levels rise markedly.', 'Associação contraindicada. Reduzir a dose de azatioprina em cerca de 75% apenas se for clinicamente imprescindível e com monitorização apertada de hemograma.', 'Combination contraindicated. Reduce azathioprine dose by about 75% only if clinically essential, with tight full blood count monitoring.', 'Hemograma semanal nas primeiras semanas de associação.', 'Weekly full blood count in the first weeks of the combination.', 'Febre, infeções graves, pancitopenia, hemorragia.', 'Fever, severe infections, pancytopenia, bleeding.', 'DailyMed (FDA) — rótulo aprovado Azatioprina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5116b22b-1460-5535-e063-6394a90acbe5 ; rótulo aprovado Febuxostat: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f2c338dc-5bab-49f4-a4ac-d8dea8afeea5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Azathioprine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5116b22b-1460-5535-e063-6394a90acbe5 ; approved Febuxostat label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f2c338dc-5bab-49f4-a4ac-d8dea8afeea5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('colchicina', 'claritromicina', 'critical', 'Colchicina + inibidor potente do CYP3A4/P-gp: risco de toxicidade grave da colchicina.', 'Colchicine + potent CYP3A4/P-gp inhibitor: risk of severe colchicine toxicity.', 'A claritromicina inibe o CYP3A4 e a glicoproteína-P, aumentando muito as concentrações de colchicina.', 'Clarithromycin inhibits CYP3A4 and P-glycoprotein, markedly raising colchicine concentrations.', 'Associação contraindicada; preferir alternativa antibiótica. Se inevitável, reduzir fortemente a dose de colchicina.', 'Contraindicated; prefer an alternative antibiotic. If unavoidable, strongly reduce the colchicine dose.', 'Vigiar sintomas de toxicidade da colchicina (GI, neuromuscular).', 'Watch for colchicine toxicity symptoms (GI, neuromuscular).', 'Diarreia grave, vómitos, rabdomiólise, pancitopenia, arritmias.', 'Severe diarrhoea, vomiting, rhabdomyolysis, pancytopenia, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Colchicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ae87893-a065-468e-b8da-f1db86afcaef ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Colchicine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ae87893-a065-468e-b8da-f1db86afcaef ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('colchicina', 'atorvastatina', 'moderate', 'Colchicina + estatina: risco aumentado de miopatia/rabdomiólise.', 'Colchicine + statin: increased risk of myopathy/rhabdomyolysis.', 'Efeito aditivo sobre o músculo esquelético, sobretudo em doentes com função renal reduzida.', 'Additive effect on skeletal muscle, especially in patients with reduced renal function.', 'Vigiar sintomas musculares; considerar reduzir a dose de colchicina ou suspender a estatina.', 'Watch for muscle symptoms; consider reducing colchicine or stopping the statin.', 'CPK e função renal em doentes sintomáticos.', 'CPK and renal function in symptomatic patients.', 'Mialgias, fraqueza muscular, urina escura.', 'Myalgia, muscle weakness, dark urine.', 'DailyMed (FDA) — rótulo aprovado Colchicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ae87893-a065-468e-b8da-f1db86afcaef ; rótulo aprovado Atorvastatina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fbd1c5da-67fb-4412-acb5-4d4c74a43654 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Colchicine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ae87893-a065-468e-b8da-f1db86afcaef ; approved Atorvastatin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fbd1c5da-67fb-4412-acb5-4d4c74a43654 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('colchicina', 'warfarina', 'moderate', 'Colchicina + anticoagulante: possível aumento do efeito anticoagulante.', 'Colchicine + anticoagulant: possible increased anticoagulant effect.', 'A colchicina pode interferir com o metabolismo/efeito da varfarina, com elevação do INR.', 'Colchicine may interfere with warfarin metabolism/effect, raising INR.', 'Monitorizar INR após introdução ou alteração de dose de colchicina.', 'Monitor INR after starting or changing colchicine dose.', 'INR periódico durante a associação.', 'Periodic INR during the combination.', 'Hemorragia, equimoses espontâneas.', 'Bleeding, spontaneous ecchymosis.', 'DailyMed (FDA) — rótulo aprovado Colchicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ae87893-a065-468e-b8da-f1db86afcaef ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Colchicine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ae87893-a065-468e-b8da-f1db86afcaef ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('alendronato', 'antiacidos', 'moderate', 'Bifosfonato + antiácidos: redução marcada da absorção do alendronato.', 'Bisphosphonate + antacids: marked reduction of alendronate absorption.', 'O cálcio, alumínio e magnésio dos antiácidos quelam o alendronato no trato GI, impedindo a absorção.', 'Calcium, aluminium and magnesium in antacids chelate alendronate in the GI tract, preventing absorption.', 'Separar a toma por pelo menos 2 horas (alendronato em jejum, com água simples).', 'Separate administration by at least 2 hours (alendronate on an empty stomach, with plain water).', 'Confirmar a adesão ao esquema de toma correto.', 'Confirm adherence to the correct dosing schedule.', 'Falta de efeito terapêutico; persistência da osteoporose/dor óssea.', 'Lack of therapeutic effect; persisting osteoporosis/bone pain.', 'DailyMed (FDA) — rótulo aprovado Alendronato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7e470d6-508e-466e-a78d-060bbbc9745c ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Alendronate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7e470d6-508e-466e-a78d-060bbbc9745c ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e346dc0-69ce-4cc5-bb5d-bfa833e11c1f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('alendronato', 'ibuprofeno', 'moderate', 'Bifosfonato + AINE: risco gastrointestinal aditivo.', 'Bisphosphonate + NSAID: additive gastrointestinal risk.', 'Ambos podem irritar a mucosa esofagogástrica.', 'Both may irritate the oesophagogastric mucosa.', 'Vigiar sintomas digestivos; considerar gastroprotecção se fatores de risco.', 'Watch for GI symptoms; consider gastroprotection if risk factors exist.', 'Sintomas GI (dispepsia, dor, disfagia).', 'GI symptoms (dyspepsia, pain, dysphagia).', 'Dor epigástrica, disfagia, melena.', 'Epigastric pain, dysphagia, melena.', 'DailyMed (FDA) — rótulo aprovado Alendronato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7e470d6-508e-466e-a78d-060bbbc9745c ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Alendronate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7e470d6-508e-466e-a78d-060bbbc9745c ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('alendronato', 'omeprazol', 'moderate', 'Bifosfonato + IBP: possível redução da absorção e do efeito do alendronato.', 'Bisphosphonate + PPI: possible reduced alendronate absorption and effect.', 'A supressão ácida pode reduzir a dissolução/absorção do alendronato.', 'Acid suppression may reduce alendronate dissolution/absorption.', 'Assegurar o esquema correto (jejum + água) e reavaliar a necessidade de IBP.', 'Ensure correct schedule (fasting + water) and reassess the need for the PPI.', 'Avaliar adesão e resposta terapêutica.', 'Assess adherence and therapeutic response.', 'Fratura ou ausência de melhoria densitométrica.', 'Fracture or lack of densitometric improvement.', 'DailyMed (FDA) — rótulo aprovado Alendronato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7e470d6-508e-466e-a78d-060bbbc9745c ; rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Alendronate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7e470d6-508e-466e-a78d-060bbbc9745c ; approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('calcitriol', 'digoxina', 'moderate', 'Calcitriol + digoxina: a hipercalcémia potenciada pelo calcitriol aumenta o risco de toxicidade digitálica.', 'Calcitriol + digoxin: calcitriol-enhanced hypercalcaemia increases the risk of digitalis toxicity.', 'O calcitriol aumenta a absorção de cálcio; a hipercalcémia sensibiliza o miocárdio à digoxina.', 'Calcitriol increases calcium absorption; hypercalcaemia sensitises the myocardium to digoxin.', 'Monitorizar calcemia e sinais de toxicidade digitálica; ajustar dose de digoxina se necessário.', 'Monitor serum calcium and signs of digoxin toxicity; adjust digoxin dose if needed.', 'Calcemia, função renal, eletrocardiograma.', 'Serum calcium, renal function, ECG.', 'Náuseas, arritmias, visão a cores alterada, confusão.', 'Nausea, arrhythmias, altered colour vision, confusion.', 'DailyMed (FDA) — rótulo aprovado Calcitriol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8465337c-86ca-ea9d-e053-2991aa0ab167 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Calcitriol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8465337c-86ca-ea9d-e053-2991aa0ab167 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('calcitriol', 'hidroclorotiazida', 'moderate', 'Calcitriol + tiazida: risco de hipercalcémia (redução da excreção renal de cálcio).', 'Calcitriol + thiazide: risk of hypercalcaemia (reduced renal calcium excretion).', 'As tiazidas reduzem a excreção urinária de cálcio, o que se adiciona ao efeito hipercalcémico do calcitriol.', 'Thiazides reduce urinary calcium excretion, adding to the hypercalcaemic effect of calcitriol.', 'Monitorizar calcemia, sobretudo nas primeiras semanas e em doentes com insuficiência renal.', 'Monitor serum calcium, especially in the first weeks and in renal impairment.', 'Calcemia e função renal periodicamente.', 'Serum calcium and renal function periodically.', 'Poliúria, obstipação, confusão, litíase renal.', 'Polyuria, constipation, confusion, renal stones.', 'DailyMed (FDA) — rótulo aprovado Calcitriol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8465337c-86ca-ea9d-e053-2991aa0ab167 ; rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Calcitriol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8465337c-86ca-ea9d-e053-2991aa0ab167 ; approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('calcitriol', 'furosemida', 'minor', 'Calcitriol + diurético de ansa: efeitos contrários sobre a calcemia.', 'Calcitriol + loop diuretic: opposing effects on serum calcium.', 'A furosemida aumenta a excreção renal de cálcio, contrariando em parte o efeito do calcitriol.', 'Furosemide increases renal calcium excretion, partially counteracting calcitriol.', 'Monitorizar calcemia se associação prolongada, especialmente em insuficiência renal.', 'Monitor serum calcium on prolonged combination, especially in renal impairment.', 'Calcemia na terapêutica prolongada.', 'Serum calcium on long-term therapy.', 'Cãibras, parestesias (hipocalcémia).', 'Cramps, paraesthesia (hypocalcaemia).', 'DailyMed (FDA) — rótulo aprovado Calcitriol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8465337c-86ca-ea9d-e053-2991aa0ab167 ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Calcitriol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8465337c-86ca-ea9d-e053-2991aa0ab167 ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('prednisolona', 'warfarina', 'moderate', 'Corticosteroide + anticoagulante: alteração do INR e risco hemorrágico.', 'Corticosteroid + anticoagulant: altered INR and bleeding risk.', 'Os corticosteroides podem potenciar ou reduzir o efeito da varfarina (efeito variável sobre a hemostase e a mucosa GI).', 'Corticosteroids may potentiate or reduce warfarin effect (variable effect on haemostasis and GI mucosa).', 'Monitorizar INR após início/ajuste de corticosteroide; considerar gastroprotecção.', 'Monitor INR after starting/adjusting corticosteroids; consider gastroprotection.', 'INR periódico e sintomas digestivos.', 'Periodic INR and GI symptoms.', 'Melena, hematemese, hemorragia.', 'Melena, haematemesis, bleeding.', 'DailyMed (FDA) — rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('prednisolona', 'furosemida', 'moderate', 'Corticosteroide + diurético de ansa: risco de hipocaliemia aditiva.', 'Corticosteroid + loop diuretic: additive hypokalaemia risk.', 'Ambos aumentam a perda renal de potássio.', 'Both increase renal potassium loss.', 'Monitorizar o potássio sérico; considerar suplementação se necessário.', 'Monitor serum potassium; consider supplementation if needed.', 'Potássio sérico e sintomas de hipocaliemia.', 'Serum potassium and hypokalaemia symptoms.', 'Fraqueza, cãibras, arritmias.', 'Weakness, cramps, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('prednisolona', 'hidroclorotiazida', 'moderate', 'Corticosteroide + tiazida: hipocaliemia e hiperglicemia aditivas.', 'Corticosteroid + thiazide: additive hypokalaemia and hyperglycaemia.', 'Ambos favorecem a perda de potássio e a elevação da glicemia.', 'Both promote potassium loss and raised blood glucose.', 'Monitorizar potássio e glicemia; ajustar terapêutica se necessário.', 'Monitor potassium and blood glucose; adjust therapy if needed.', 'Potássio, glicemia e tensão arterial.', 'Potassium, blood glucose and blood pressure.', 'Fraqueza, cãibras, poliúria, descompensação glicémica.', 'Weakness, cramps, polyuria, glycaemic decompensation.', 'DailyMed (FDA) — rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee ; rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52e6e21d-94b8-41a0-8d13-371c0e66bcee ; approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('diclofenac', 'warfarina', 'moderate', 'AINE + anticoagulante: aumento do risco hemorrágico.', 'NSAID + anticoagulant: increased bleeding risk.', 'O diclofenac inibe a COX, a agregação plaquetária e pode interagir com a varfarina, potenciando a anticoagulação.', 'Diclofenac inhibits COX and platelet aggregation and may interact with warfarin, enhancing anticoagulation.', 'Usar a menor dose de AINE possível; considerar gastroprotecção e vigiar hemorragias.', 'Use the lowest NSAID dose; consider gastroprotection and watch for bleeding.', 'INR e sintomas digestivos.', 'INR and GI symptoms.', 'Melena, hematemese, equimoses.', 'Melena, haematemesis, ecchymosis.', 'DailyMed (FDA) — rótulo aprovado Diclofenac: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2d45648f-cbea-41a4-8e3e-007b7bb7912c ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Diclofenac label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2d45648f-cbea-41a4-8e3e-007b7bb7912c ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('diclofenac', 'naproxeno', 'moderate', 'Dois AINE em simultâneo: sem benefício e com risco GI/renal acrescido.', 'Two NSAIDs together: no benefit and increased GI/renal risk.', 'Efeitos aditivos sobre a mucosa gástrica e a função renal.', 'Additive effects on gastric mucosa and renal function.', 'Não combinar AINE; usar um único AINE à menor dose eficaz.', 'Do not combine NSAIDs; use a single NSAID at the lowest effective dose.', 'Função renal e sintomas GI.', 'Renal function and GI symptoms.', 'Dispepsia, dor epigástrica, edema.', 'Dyspepsia, epigastric pain, oedema.', 'DailyMed (FDA) — rótulo aprovado Diclofenac: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2d45648f-cbea-41a4-8e3e-007b7bb7912c ; rótulo aprovado Naproxeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Diclofenac label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2d45648f-cbea-41a4-8e3e-007b7bb7912c ; approved Naproxen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24d44eb6-921e-4150-a6b2-81f42ced32ab — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('alopurinol', 'febuxostat', 'minor', 'Dois inibidores da xantina-oxidase: sem benefício e com risco aumentado de reações de hipersensibilidade.', 'Two xanthine oxidase inhibitors: no benefit and increased risk of hypersensitivity reactions.', 'Sobreposição do mecanismo de ação (inibição da xantina-oxidase) e do perfil de reações adversas cutâneas graves.', 'Overlapping mechanism (xanthine oxidase inhibition) and risk profile of severe cutaneous reactions.', 'Não associar; escolher apenas um inibidor da xantina-oxidase.', 'Do not combine; choose only one xanthine oxidase inhibitor.', 'Vigiar erupções cutâneas e sintomas de hipersensibilidade.', 'Watch for skin rash and hypersensitivity symptoms.', 'Erupção cutânea, prurido, febre, sintomas de síndrome de hipersensibilidade.', 'Skin rash, pruritus, fever, hypersensitivity syndrome symptoms.', 'DailyMed (FDA) — rótulo aprovado Alopurinol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b6c5b5c0-b1cb-44c0-a849-5d317e6fa300 ; rótulo aprovado Febuxostat: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f2c338dc-5bab-49f4-a4ac-d8dea8afeea5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Allopurinol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b6c5b5c0-b1cb-44c0-a849-5d317e6fa300 ; approved Febuxostat label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f2c338dc-5bab-49f4-a4ac-d8dea8afeea5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('leflunomida', 'warfarina', 'moderate', 'Leflunomida + anticoagulante: possível aumento do efeito anticoagulante.', 'Leflunomida + anticoagulant: possible increased anticoagulant effect.', 'A leflunomida pode inibir o metabolismo da varfarina, elevando o INR.', 'Leflunomide may inhibit warfarin metabolism, raising INR.', 'Monitorizar INR após início ou alteração de dose de leflunomida.', 'Monitor INR after starting or changing leflunomide dose.', 'INR periódico durante a associação.', 'Periodic INR during the combination.', 'Hemorragia, equimoses espontâneas.', 'Bleeding, spontaneous ecchymosis.', 'DailyMed (FDA) — rótulo aprovado Leflunomida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc044417-cd9a-42f6-8a3d-a14e7c2f81a2 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Leflunomide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc044417-cd9a-42f6-8a3d-a14e7c2f81a2 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('leflunomida', 'metotrexato', 'moderate', 'Leflunomida + metotrexato: risco acrescido de hepatotoxicidade e mielossupressão.', 'Leflunomide + methotrexate: increased risk of hepatotoxicity and marrow suppression.', 'Efeitos tóxicos aditivos sobre o fígado e a medula óssea.', 'Additive toxic effects on the liver and bone marrow.', 'A associação só em contexto especializado, com monitorização apertada de transaminases e hemograma.', 'Combination only in specialist settings, with tight monitoring of transaminases and full blood count.', 'Transaminases e hemograma mensais; função renal.', 'Transaminases and full blood count monthly; renal function.', 'Icterícia, febre, infeções, úlceras orais.', 'Jaundice, fever, infections, oral ulcers.', 'DailyMed (FDA) — rótulo aprovado Leflunomida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc044417-cd9a-42f6-8a3d-a14e7c2f81a2 ; rótulo aprovado Metotrexato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Leflunomide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc044417-cd9a-42f6-8a3d-a14e7c2f81a2 ; approved Methotrexate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757d6cef-6696-7a1c-8074-01258aaa8bdd — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('hidroxicloroquina', 'aspirina', 'minor', 'Hidroxicloroquina + aspirina: risco gastrointestinal aditivo.', 'Hydroxychloroquine + aspirin: additive gastrointestinal risk.', 'Ambos podem irritar a mucosa gástrica.', 'Both may irritate the gastric mucosa.', 'Vigiar sintomas dispépticos; considerar gastroprotecção em doentes de risco.', 'Watch for dyspeptic symptoms; consider gastroprotection in at-risk patients.', 'Sintomas GI após a associação.', 'GI symptoms after the combination.', 'Dispepsia, dor epigástrica, melena.', 'Dyspepsia, epigastric pain, melena.', 'DailyMed (FDA) — rótulo aprovado Hidroxicloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=da435181-0c5a-4188-8d59-51234116b005 ; rótulo aprovado Ácido acetilsalicílico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Hydroxychloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=da435181-0c5a-4188-8d59-51234116b005 ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)')
) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('naproxeno', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool agrava a irritação da mucosa gástrica e o risco hemorrágico associado aos AINE.', 'Alcohol worsens gastric mucosal irritation and the bleeding risk associated with NSAIDs.', 'Limitar ou evitar o consumo de álcool durante o tratamento.', 'Limit or avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc', 1),
  ('naproxeno', 'alimentos', 'Alimentos', 'Food', 'minor', 'Os alimentos retardam a absorção mas reduzem a irritação gástrica.', 'Food slows absorption but reduces gastric irritation.', 'Tomar com alimentos ou leite para reduzir o desconforto gástrico.', 'Take with food or milk to reduce stomach discomfort.', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc', 1),
  ('celecoxib', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta o risco de irritação/hemorragia gástrica.', 'Alcohol increases the risk of gastric irritation/bleeding.', 'Evitar álcool durante o tratamento.', 'Avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc', 1),
  ('celecoxib', 'alimentos', 'Alimentos', 'Food', 'minor', 'A toma com alimentos pode atrasar ligeiramente a absorção sem afetar a eficácia.', 'Taking with food may slightly delay absorption without affecting efficacy.', 'Pode tomar com alimentos se houver desconforto gástrico.', 'May take with food if stomach discomfort occurs.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc', 1),
  ('metotrexato', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool potencia a hepatotoxicidade do metotrexato.', 'Alcohol potentiates methotrexate hepatotoxicity.', 'Evitar álcool durante o tratamento (risco hepático aditivo).', 'Avoid alcohol during treatment (additive liver risk).', 'EMC-UK (MHRA) — SmPC aprovada Metotrexato: https://www.medicines.org.uk/emc/product/511/smpc', 'EMC-UK (MHRA) — approved Methotrexate SmPC: https://www.medicines.org.uk/emc/product/511/smpc', 1),
  ('metotrexato', 'alimentos', 'Alimentos', 'Food', 'minor', 'A toma com alimentos reduz as náuseas associadas ao metotrexato.', 'Taking with food reduces methotrexate-related nausea.', 'Tomar com alimentos para melhorar a tolerância gastrointestinal.', 'Take with food to improve GI tolerance.', 'EMC-UK (MHRA) — SmPC aprovada Metotrexato: https://www.medicines.org.uk/emc/product/511/smpc', 'EMC-UK (MHRA) — approved Methotrexate SmPC: https://www.medicines.org.uk/emc/product/511/smpc', 1),
  ('leflunomida', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta o risco de lesão hepática.', 'Alcohol increases the risk of liver injury.', 'Evitar álcool durante o tratamento.', 'Avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Leflunomida: https://www.medicines.org.uk/emc/product/4944/smpc', 'EMC-UK (MHRA) — approved Leflunomide SmPC: https://www.medicines.org.uk/emc/product/4944/smpc', 1),
  ('colchicina', 'toranja', 'Toranja', 'Grapefruit', 'moderate', 'A toranja inibe o CYP3A4 e a glicoproteína-P, elevando as concentrações de colchicina.', 'Grapefruit inhibits CYP3A4 and P-glycoprotein, raising colchicine concentrations.', 'Evitar sumo de toranja durante o tratamento.', 'Avoid grapefruit juice during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Colchicina: https://www.medicines.org.uk/emc/product/14362/smpc', 'EMC-UK (MHRA) — approved Colchicine SmPC: https://www.medicines.org.uk/emc/product/14362/smpc', 1),
  ('colchicina', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode aumentar os efeitos gastrointestinais da colchicina.', 'Alcohol may increase the GI effects of colchicine.', 'Limitar o consumo de álcool.', 'Limit alcohol intake.', 'EMC-UK (MHRA) — SmPC aprovada Colchicina: https://www.medicines.org.uk/emc/product/14362/smpc', 'EMC-UK (MHRA) — approved Colchicine SmPC: https://www.medicines.org.uk/emc/product/14362/smpc', 1),
  ('febuxostat', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta a uricemia e pode precipitar crises de gota.', 'Alcohol raises serum urate and may trigger gout flares.', 'Limitar ou evitar álcool, sobretudo cerveja, durante o tratamento.', 'Limit or avoid alcohol, especially beer, during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Febuxostat: https://www.medicines.org.uk/emc/product/487/smpc', 'EMC-UK (MHRA) — approved Febuxostat SmPC: https://www.medicines.org.uk/emc/product/487/smpc', 1),
  ('febuxostat', 'alimentos', 'Alimentos', 'Food', 'minor', 'Os alimentos não alteram de forma relevante a absorção.', 'Food does not significantly alter absorption.', 'Pode tomar com ou sem alimentos.', 'May take with or without food.', 'EMC-UK (MHRA) — SmPC aprovada Febuxostat: https://www.medicines.org.uk/emc/product/487/smpc', 'EMC-UK (MHRA) — approved Febuxostat SmPC: https://www.medicines.org.uk/emc/product/487/smpc', 1),
  ('alendronato', 'leite_calcio', 'Leite e laticínios', 'Milk and dairy products', 'moderate', 'O cálcio dos laticínios liga-se ao alendronato e impede a sua absorção.', 'Calcium in dairy binds alendronate and prevents its absorption.', 'Não tomar com leite, iogurte ou derivados; tomar o alendronato em jejum com água simples e aguardar 30-60 min.', 'Do not take with milk, yoghurt or dairy; take alendronate on an empty stomach with plain water and wait 30-60 min.', 'EMC-UK (MHRA) — SmPC aprovada Alendronato: https://www.medicines.org.uk/emc/product/5206/smpc', 'EMC-UK (MHRA) — approved Alendronate SmPC: https://www.medicines.org.uk/emc/product/5206/smpc', 1),
  ('alendronato', 'alimentos', 'Alimentos', 'Food', 'moderate', 'Os alimentos, sobretudo os ricos em cálcio, reduzem marcadamente a absorção.', 'Food, especially calcium-rich food, markedly reduces absorption.', 'Tomar o alendronato em jejum (ao acordar) com água simples e não comer durante 30-60 min.', 'Take alendronate fasting (on waking) with plain water and do not eat for 30-60 min.', 'EMC-UK (MHRA) — SmPC aprovada Alendronato: https://www.medicines.org.uk/emc/product/5206/smpc', 'EMC-UK (MHRA) — approved Alendronate SmPC: https://www.medicines.org.uk/emc/product/5206/smpc', 1),
  ('calcitriol', 'alimentos', 'Alimentos ricos em cálcio', 'Calcium-rich food', 'minor', 'Dieta rica em cálcio adiciona-se ao efeito do calcitriol sobre a calcemia.', 'Calcium-rich diet adds to calcitriol effect on serum calcium.', 'Manter ingestão de cálcio equilibrada e vigiar calcemia na suplementação conjunta.', 'Keep calcium intake balanced and monitor serum calcium with concurrent supplementation.', 'EMC-UK (MHRA) — SmPC aprovada Calcitriol: https://www.medicines.org.uk/emc/product/101902/smpc', 'EMC-UK (MHRA) — approved Calcitriol SmPC: https://www.medicines.org.uk/emc/product/101902/smpc', 1),
  ('aspirina', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta o risco de irritação e hemorragia gástrica.', 'Alcohol increases the risk of gastric irritation and bleeding.', 'Evitar álcool, sobretudo em dose anti-inflamatória ou em doentes de risco.', 'Avoid alcohol, especially at anti-inflammatory doses or in at-risk patients.', 'EMC-UK (MHRA) — SmPC aprovada Ácido acetilsalicílico: https://www.medicines.org.uk/emc/product/8627/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/8627/smpc', 1),
  ('ibuprofeno', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool agrava o risco de hemorragia gástrica associada ao AINE.', 'Alcohol worsens the NSAID-related gastric bleeding risk.', 'Limitar ou evitar o consumo de álcool.', 'Limit or avoid alcohol.', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc', 1),
  ('ibuprofeno', 'alimentos', 'Alimentos', 'Food', 'minor', 'A toma com alimentos reduz a irritação gástrica.', 'Taking with food reduces gastric irritation.', 'Tomar com alimentos ou leite se houver desconforto gástrico.', 'Take with food or milk if stomach discomfort occurs.', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc', 1),
  ('diclofenac', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta o risco de irritação e hemorragia gástrica.', 'Alcohol increases the risk of gastric irritation and bleeding.', 'Evitar álcool durante o tratamento.', 'Avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Diclofenac: https://www.medicines.org.uk/emc/product/4333/smpc', 'EMC-UK (MHRA) — approved Diclofenac SmPC: https://www.medicines.org.uk/emc/product/4333/smpc', 1),
  ('alopurinol', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool aumenta a uricemia e pode precipitar crises de gota.', 'Alcohol raises serum urate and may trigger gout flares.', 'Limitar ou evitar álcool, sobretudo cerveja.', 'Limit or avoid alcohol, especially beer.', 'EMC-UK (MHRA) — SmPC aprovada Alopurinol: https://www.medicines.org.uk/emc/product/100235/smpc', 'EMC-UK (MHRA) — approved Allopurinol SmPC: https://www.medicines.org.uk/emc/product/100235/smpc', 1),
  ('azatioprina', 'alimentos', 'Alimentos', 'Food', 'minor', 'A toma com alimentos reduz as náuseas.', 'Taking with food reduces nausea.', 'Tomar com alimentos para melhorar a tolerância.', 'Take with food to improve tolerance.', 'EMC-UK (MHRA) — SmPC aprovada Azatioprina: https://www.medicines.org.uk/emc/product/14296/smpc', 'EMC-UK (MHRA) — approved Azathioprine SmPC: https://www.medicines.org.uk/emc/product/14296/smpc', 1),
  ('prednisolona', 'alimentos', 'Alimentos', 'Food', 'minor', 'A toma com alimentos reduz a irritação gástrica.', 'Taking with food reduces gastric irritation.', 'Tomar com alimentos ou leite, de preferência de manhã.', 'Take with food or milk, preferably in the morning.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc', 1),
  ('prednisolona', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode aumentar o risco gastrointestinal.', 'Alcohol may increase GI risk.', 'Limitar o consumo de álcool durante o tratamento.', 'Limit alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc', 1),
  ('hidroxicloroquina', 'alimentos', 'Alimentos', 'Food', 'minor', 'A toma com alimentos ou leite reduz as náuseas.', 'Taking with food or milk reduces nausea.', 'Tomar com alimentos ou leite para melhorar a tolerância.', 'Take with food or milk to improve tolerance.', 'EMC-UK (MHRA) — SmPC aprovada Hidroxicloroquina: https://www.medicines.org.uk/emc/product/11540/smpc', 'EMC-UK (MHRA) — approved Hydroxychloroquine SmPC: https://www.medicines.org.uk/emc/product/11540/smpc', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('naproxeno', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'contraindication', 'critical', 'Os AINE inibem a síntese de prostaglandinas gastroprotetoras, podendo agravar ou perfurar uma úlcera ativa.', 'NSAIDs inhibit gastroprotective prostaglandin synthesis and may worsen or perforate an active ulcer.', 'Contraindicado; procurar alternativa analgésica (paracetamol).', 'Contraindicated; seek an alternative analgesic (paracetamol).', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc', 1),
  ('naproxeno', 'asma_aine', 'Asma precipitada por AINE', 'NSAID-precipitated asthma', 'precaution', 'moderate', 'Os AINE podem precipitar broncospasmo em doentes com asma sensível a AINE/aspirina.', 'NSAIDs may precipitate bronchospasm in patients with NSAID/aspirin-sensitive asthma.', 'Evitar AINE em asmáticos com história de sensibilidade; usar com precaução e disponibilidade de socorro.', 'Avoid NSAIDs in asthmatics with a history of sensitivity; use with caution and rescue available.', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc', 1),
  ('naproxeno', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease', 'precaution', 'moderate', 'Os AINE reduzem o fluxo sanguíneo renal e podem agravar a função renal.', 'NSAIDs reduce renal blood flow and may worsen renal function.', 'Evitar AINE em insuficiência renal; se inevitável, usar a menor dose e vigiar creatinina.', 'Avoid NSAIDs in renal impairment; if unavoidable, use the lowest dose and monitor creatinine.', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc', 1),
  ('naproxeno', 'doenca_cardiovascular', 'Doença cardiovascular', 'Cardiovascular disease', 'precaution', 'moderate', 'Os AINE podem aumentar o risco de eventos cardiovasculares e reter líquidos.', 'NSAIDs may increase the risk of cardiovascular events and cause fluid retention.', 'Usar com precaução em doentes com doença cardiovascular; preferir a menor dose e duração.', 'Use with caution in cardiovascular disease; prefer the lowest dose and duration.', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc', 1),
  ('celecoxib', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'contraindication', 'critical', 'Apesar da seletividade COX-2, o celecoxib mantém risco de complicação de úlcera ativa.', 'Despite COX-2 selectivity, celecoxib still carries a risk of active ulcer complications.', 'Contraindicado em úlcera ativa; procurar alternativa.', 'Contraindicated in active ulcer; seek an alternative.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc', 1),
  ('celecoxib', 'doenca_cardiovascular', 'Doença cardiovascular', 'Cardiovascular disease', 'precaution', 'moderate', 'Os coxibes aumentam o risco de eventos trombóticos cardiovasculares.', 'Coxibs increase the risk of cardiovascular thrombotic events.', 'Usar com precaução; evitar em doença cardíaca isquémica ou AVC recente.', 'Use with caution; avoid in ischaemic heart disease or recent stroke.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc', 1),
  ('celecoxib', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease', 'precaution', 'moderate', 'Os AINE, incluindo coxibes, podem reduzir a função renal.', 'NSAIDs, including coxibs, may reduce renal function.', 'Vigiar creatinina e diurese; usar a menor dose possível.', 'Monitor creatinine and urine output; use the lowest dose.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc', 1),
  ('celecoxib', 'asma_aine', 'Asma precipitada por AINE', 'NSAID-precipitated asthma', 'precaution', 'moderate', 'Risco de broncospasmo em doentes sensíveis a AINE.', 'Risk of bronchospasm in NSAID-sensitive patients.', 'Usar com precaução; evitar em asma sensível a aspirina.', 'Use with caution; avoid in aspirin-sensitive asthma.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc', 1),
  ('metotrexato', 'doenca_hepatica_ativa', 'Doença hepática ativa', 'Active liver disease', 'contraindication', 'critical', 'O metotrexato é hepatotóxico e pode agravar doença hepática ativa.', 'Methotrexate is hepatotoxic and may worsen active liver disease.', 'Contraindicado em doença hepática ativa; monitorizar transaminases na terapêutica.', 'Contraindicated in active liver disease; monitor transaminases on therapy.', 'EMC-UK (MHRA) — SmPC aprovada Metotrexato: https://www.medicines.org.uk/emc/product/511/smpc', 'EMC-UK (MHRA) — approved Methotrexate SmPC: https://www.medicines.org.uk/emc/product/511/smpc', 1),
  ('metotrexato', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'contraindication', 'critical', 'O metotrexato é excretado por via renal; a insuficiência renal grave eleva a toxicidade.', 'Methotrexate is renally excreted; severe renal impairment raises toxicity.', 'Contraindicado em insuficiência renal grave; ajustar dose na insuficiência moderada.', 'Contraindicated in severe renal impairment; adjust dose in moderate impairment.', 'EMC-UK (MHRA) — SmPC aprovada Metotrexato: https://www.medicines.org.uk/emc/product/511/smpc', 'EMC-UK (MHRA) — approved Methotrexate SmPC: https://www.medicines.org.uk/emc/product/511/smpc', 1),
  ('metotrexato', 'alcoolismo', 'Alcoolismo', 'Alcoholism', 'precaution', 'moderate', 'O álcool adiciona hepatotoxicidade à do metotrexato.', 'Alcohol adds hepatotoxicity to that of methotrexate.', 'Aconselhar abstinência alcoólica durante o tratamento.', 'Advise alcohol abstinence during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Metotrexato: https://www.medicines.org.uk/emc/product/511/smpc', 'EMC-UK (MHRA) — approved Methotrexate SmPC: https://www.medicines.org.uk/emc/product/511/smpc', 1),
  ('leflunomida', 'doenca_hepatica_ativa', 'Doença hepática ativa', 'Active liver disease', 'contraindication', 'critical', 'A leflunomida pode causar lesão hepática grave, sobretudo em doença hepática prévia.', 'Leflunomide may cause severe liver injury, especially with pre-existing liver disease.', 'Contraindicado; monitorizar transaminases mensalmente na terapêutica.', 'Contraindicated; monitor transaminases monthly on therapy.', 'EMC-UK (MHRA) — SmPC aprovada Leflunomida: https://www.medicines.org.uk/emc/product/4944/smpc', 'EMC-UK (MHRA) — approved Leflunomide SmPC: https://www.medicines.org.uk/emc/product/4944/smpc', 1),
  ('leflunomida', 'infeccao_ativa', 'Infeção ativa', 'Active infection', 'precaution', 'moderate', 'A imunossupressão pela leflunomida pode agravar infeções.', 'Immunosuppression from leflunomide may worsen infections.', 'Avaliar e tratar infeções antes de iniciar; vigiar sinais de infeção.', 'Assess and treat infections before starting; watch for signs of infection.', 'EMC-UK (MHRA) — SmPC aprovada Leflunomida: https://www.medicines.org.uk/emc/product/4944/smpc', 'EMC-UK (MHRA) — approved Leflunomide SmPC: https://www.medicines.org.uk/emc/product/4944/smpc', 1),
  ('leflunomida', 'doenca_renal_grave', 'Doença renal grave', 'Severe renal disease', 'precaution', 'moderate', 'A eliminação reduzida pode aumentar a exposição e a toxicidade.', 'Reduced elimination may increase exposure and toxicity.', 'Usar com precaução e monitorizar função renal.', 'Use with caution and monitor renal function.', 'EMC-UK (MHRA) — SmPC aprovada Leflunomida: https://www.medicines.org.uk/emc/product/4944/smpc', 'EMC-UK (MHRA) — approved Leflunomide SmPC: https://www.medicines.org.uk/emc/product/4944/smpc', 1),
  ('colchicina', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'contraindication', 'critical', 'A colchicina acumula-se em insuficiência renal, com risco de toxicidade grave.', 'Colchicine accumulates in renal impairment, with risk of severe toxicity.', 'Contraindicado em insuficiência renal grave; ajustar dose na moderada.', 'Contraindicated in severe renal impairment; adjust dose in moderate impairment.', 'EMC-UK (MHRA) — SmPC aprovada Colchicina: https://www.medicines.org.uk/emc/product/14362/smpc', 'EMC-UK (MHRA) — approved Colchicine SmPC: https://www.medicines.org.uk/emc/product/14362/smpc', 1),
  ('colchicina', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical', 'O metabolismo hepático reduzido eleva as concentrações de colchicina.', 'Reduced hepatic metabolism raises colchicine concentrations.', 'Contraindicado em insuficiência hepática grave.', 'Contraindicated in severe hepatic impairment.', 'EMC-UK (MHRA) — SmPC aprovada Colchicina: https://www.medicines.org.uk/emc/product/14362/smpc', 'EMC-UK (MHRA) — approved Colchicine SmPC: https://www.medicines.org.uk/emc/product/14362/smpc', 1),
  ('colchicina', 'doenca_gastrointestinal', 'Doença gastrointestinal', 'Gastrointestinal disease', 'precaution', 'moderate', 'A colchicina causa diarreia e pode agravar doença GI inflamatória.', 'Colchicine causes diarrhoea and may worsen inflammatory GI disease.', 'Usar com precaução; vigiar diarreia grave (sinal de toxicidade).', 'Use with caution; watch for severe diarrhoea (sign of toxicity).', 'EMC-UK (MHRA) — SmPC aprovada Colchicina: https://www.medicines.org.uk/emc/product/14362/smpc', 'EMC-UK (MHRA) — approved Colchicine SmPC: https://www.medicines.org.uk/emc/product/14362/smpc', 1),
  ('febuxostat', 'doenca_cardiovascular', 'Doença cardiovascular', 'Cardiovascular disease', 'precaution', 'moderate', 'Em estudos, o febuxostat associou-se a maior risco cardiovascular em relação ao alopurinol.', 'In trials, febuxostat was associated with higher cardiovascular risk versus allopurinol.', 'Usar com precaução em doentes com doença cardiovascular prévia.', 'Use with caution in patients with prior cardiovascular disease.', 'EMC-UK (MHRA) — SmPC aprovada Febuxostat: https://www.medicines.org.uk/emc/product/487/smpc', 'EMC-UK (MHRA) — approved Febuxostat SmPC: https://www.medicines.org.uk/emc/product/487/smpc', 1),
  ('febuxostat', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A excreção renal reduzida aumenta a exposição ao febuxostat.', 'Reduced renal excretion increases febuxostat exposure.', 'Usar com precaução e monitorizar função renal.', 'Use with caution and monitor renal function.', 'EMC-UK (MHRA) — SmPC aprovada Febuxostat: https://www.medicines.org.uk/emc/product/487/smpc', 'EMC-UK (MHRA) — approved Febuxostat SmPC: https://www.medicines.org.uk/emc/product/487/smpc', 1),
  ('alendronato', 'doenca_esofagica', 'Doença esofágica', 'Oesophageal disease', 'contraindication', 'critical', 'O alendronato pode causar esofagite grave; está contraindicado em alterações esofágicas que atrasem o trânsito.', 'Alendronate may cause severe oesophagitis; contraindicated in oesophageal abnormalities delaying transit.', 'Contraindicado em estenose/acalasia e dificuldade de deglutição.', 'Contraindicated in stricture/achalasia and swallowing difficulty.', 'EMC-UK (MHRA) — SmPC aprovada Alendronato: https://www.medicines.org.uk/emc/product/5206/smpc', 'EMC-UK (MHRA) — approved Alendronate SmPC: https://www.medicines.org.uk/emc/product/5206/smpc', 1),
  ('alendronato', 'hipocalcemia', 'Hipocalcémia', 'Hypocalcaemia', 'contraindication', 'critical', 'O alendronato deve ser usado apenas com calcemia corrigida.', 'Alendronate should only be used once calcium is corrected.', 'Corrigir hipocalcémia e défice de vitamina D antes de iniciar.', 'Correct hypocalcaemia and vitamin D deficiency before starting.', 'EMC-UK (MHRA) — SmPC aprovada Alendronato: https://www.medicines.org.uk/emc/product/5206/smpc', 'EMC-UK (MHRA) — approved Alendronate SmPC: https://www.medicines.org.uk/emc/product/5206/smpc', 1),
  ('alendronato', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'contraindication', 'critical', 'O alendronato não é recomendado com depuração de creatinina < 35 mL/min.', 'Alendronate is not recommended with creatinine clearance < 35 mL/min.', 'Contraindicado; considerar alternativa terapêutica.', 'Contraindicated; consider an alternative.', 'EMC-UK (MHRA) — SmPC aprovada Alendronato: https://www.medicines.org.uk/emc/product/5206/smpc', 'EMC-UK (MHRA) — approved Alendronate SmPC: https://www.medicines.org.uk/emc/product/5206/smpc', 1),
  ('calcitriol', 'hipercalcemia', 'Hipercalcémia', 'Hypercalcaemia', 'contraindication', 'critical', 'O calcitriol eleva a calcemia e agrava a hipercalcémia.', 'Calcitriol raises serum calcium and worsens hypercalcaemia.', 'Contraindicado; suspender suplementos de cálcio e vigiar calcemia.', 'Contraindicated; stop calcium supplements and monitor serum calcium.', 'EMC-UK (MHRA) — SmPC aprovada Calcitriol: https://www.medicines.org.uk/emc/product/101902/smpc', 'EMC-UK (MHRA) — approved Calcitriol SmPC: https://www.medicines.org.uk/emc/product/101902/smpc', 1),
  ('calcitriol', 'litase_renal', 'Litíase renal', 'Renal lithiasis', 'precaution', 'moderate', 'A hipercalciúria induzida pode favorecer a formação de cálculos.', 'Induced hypercalciuria may favour stone formation.', 'Vigiar calcemia e calciúria; garantir hidratação adequada.', 'Monitor serum calcium and urine calcium; ensure adequate hydration.', 'EMC-UK (MHRA) — SmPC aprovada Calcitriol: https://www.medicines.org.uk/emc/product/101902/smpc', 'EMC-UK (MHRA) — approved Calcitriol SmPC: https://www.medicines.org.uk/emc/product/101902/smpc', 1),
  ('aspirina', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'contraindication', 'critical', 'A aspirina aumenta o risco de hemorragia e perfuração de úlcera ativa.', 'Aspirin increases the risk of bleeding and perforation of an active ulcer.', 'Evitar aspirina em úlcera ativa; reavaliar risco/benefício na prevenção cardiovascular.', 'Avoid aspirin in active ulcer; reassess risk/benefit for cardiovascular prevention.', 'EMC-UK (MHRA) — SmPC aprovada Ácido acetilsalicílico: https://www.medicines.org.uk/emc/product/8627/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/8627/smpc', 1),
  ('aspirina', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease', 'precaution', 'moderate', 'A aspirina (em dose AINE) pode reduzir a função renal.', 'Aspirin (at NSAID dose) may reduce renal function.', 'Usar a menor dose eficaz e vigiar creatinina em insuficiência renal.', 'Use the lowest effective dose and monitor creatinine in renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Ácido acetilsalicílico: https://www.medicines.org.uk/emc/product/8627/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/8627/smpc', 1),
  ('ibuprofeno', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'contraindication', 'critical', 'Os AINE podem agravar ou perfurar úlcera ativa.', 'NSAIDs may worsen or perforate an active ulcer.', 'Contraindicado; procurar alternativa (paracetamol).', 'Contraindicated; seek an alternative (paracetamol).', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc', 1),
  ('ibuprofeno', 'asma_aine', 'Asma precipitada por AINE', 'NSAID-precipitated asthma', 'precaution', 'moderate', 'Risco de broncospasmo em doentes sensíveis a AINE.', 'Risk of bronchospasm in NSAID-sensitive patients.', 'Evitar em asma sensível a aspirina; usar com precaução.', 'Avoid in aspirin-sensitive asthma; use with caution.', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc', 1),
  ('ibuprofeno', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease', 'precaution', 'moderate', 'Os AINE podem agravar a função renal.', 'NSAIDs may worsen renal function.', 'Evitar ou usar a menor dose com monitorização de creatinina.', 'Avoid or use the lowest dose with creatinine monitoring.', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc', 1),
  ('ibuprofeno', 'doenca_cardiovascular', 'Doença cardiovascular', 'Cardiovascular disease', 'precaution', 'moderate', 'Os AINE podem aumentar o risco cardiovascular.', 'NSAIDs may increase cardiovascular risk.', 'Usar com precaução em doença cardiovascular.', 'Use with caution in cardiovascular disease.', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc', 1),
  ('diclofenac', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'contraindication', 'critical', 'Os AINE podem agravar ou perfurar úlcera ativa.', 'NSAIDs may worsen or perforate an active ulcer.', 'Contraindicado; procurar alternativa.', 'Contraindicated; seek an alternative.', 'EMC-UK (MHRA) — SmPC aprovada Diclofenac: https://www.medicines.org.uk/emc/product/4333/smpc', 'EMC-UK (MHRA) — approved Diclofenac SmPC: https://www.medicines.org.uk/emc/product/4333/smpc', 1),
  ('diclofenac', 'asma_aine', 'Asma precipitada por AINE', 'NSAID-precipitated asthma', 'precaution', 'moderate', 'Risco de broncospasmo em doentes sensíveis a AINE.', 'Risk of bronchospasm in NSAID-sensitive patients.', 'Evitar em asma sensível a aspirina.', 'Avoid in aspirin-sensitive asthma.', 'EMC-UK (MHRA) — SmPC aprovada Diclofenac: https://www.medicines.org.uk/emc/product/4333/smpc', 'EMC-UK (MHRA) — approved Diclofenac SmPC: https://www.medicines.org.uk/emc/product/4333/smpc', 1),
  ('diclofenac', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease', 'precaution', 'moderate', 'Os AINE podem agravar a função renal.', 'NSAIDs may worsen renal function.', 'Evitar ou usar a menor dose com monitorização de creatinina.', 'Avoid or use the lowest dose with creatinine monitoring.', 'EMC-UK (MHRA) — SmPC aprovada Diclofenac: https://www.medicines.org.uk/emc/product/4333/smpc', 'EMC-UK (MHRA) — approved Diclofenac SmPC: https://www.medicines.org.uk/emc/product/4333/smpc', 1),
  ('diclofenac', 'doenca_cardiovascular', 'Doença cardiovascular', 'Cardiovascular disease', 'precaution', 'moderate', 'Os AINE podem aumentar o risco cardiovascular.', 'NSAIDs may increase cardiovascular risk.', 'Usar com precaução em doença cardiovascular.', 'Use with caution in cardiovascular disease.', 'EMC-UK (MHRA) — SmPC aprovada Diclofenac: https://www.medicines.org.uk/emc/product/4333/smpc', 'EMC-UK (MHRA) — approved Diclofenac SmPC: https://www.medicines.org.uk/emc/product/4333/smpc', 1),
  ('alopurinol', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A excreção renal reduzida aumenta o risco de hipersensibilidade ao alopurinol.', 'Reduced renal excretion increases the risk of allopurinol hypersensitivity.', 'Ajustar a dose à função renal e monitorizar.', 'Adjust dose to renal function and monitor.', 'EMC-UK (MHRA) — SmPC aprovada Alopurinol: https://www.medicines.org.uk/emc/product/100235/smpc', 'EMC-UK (MHRA) — approved Allopurinol SmPC: https://www.medicines.org.uk/emc/product/100235/smpc', 1),
  ('alopurinol', 'sindrome_hipersensibilidade', 'Síndrome de hipersensibilidade (história)', 'Hypersensitivity syndrome (history)', 'contraindication', 'critical', 'História prévia de reação grave ao alopurinol contra-indica a reintrodução.', 'Prior severe reaction to allopurinol contraindicates reintroduction.', 'Contraindicado; considerar alternativa (febuxostat) com precaução.', 'Contraindicated; consider an alternative (febuxostat) with caution.', 'EMC-UK (MHRA) — SmPC aprovada Alopurinol: https://www.medicines.org.uk/emc/product/100235/smpc', 'EMC-UK (MHRA) — approved Allopurinol SmPC: https://www.medicines.org.uk/emc/product/100235/smpc', 1),
  ('azatioprina', 'deficiencia_tpmt', 'Deficiência de TPMT', 'TPMT deficiency', 'contraindication', 'critical', 'A deficiência de tiopurina-metiltransferase (TPMT) predispõe a mielossupressão grave.', 'Thiopurine methyltransferase (TPMT) deficiency predisposes to severe marrow suppression.', 'Testar TPMT antes de iniciar; contraindicado se deficiência total.', 'Test TPMT before starting; contraindicated in complete deficiency.', 'EMC-UK (MHRA) — SmPC aprovada Azatioprina: https://www.medicines.org.uk/emc/product/14296/smpc', 'EMC-UK (MHRA) — approved Azathioprine SmPC: https://www.medicines.org.uk/emc/product/14296/smpc', 1),
  ('azatioprina', 'doenca_hepatica_ativa', 'Doença hepática ativa', 'Active liver disease', 'precaution', 'moderate', 'A azatioprina pode causar hepatotoxicidade.', 'Azathioprine may cause hepatotoxicity.', 'Monitorizar função hepática na terapêutica.', 'Monitor liver function on therapy.', 'EMC-UK (MHRA) — SmPC aprovada Azatioprina: https://www.medicines.org.uk/emc/product/14296/smpc', 'EMC-UK (MHRA) — approved Azathioprine SmPC: https://www.medicines.org.uk/emc/product/14296/smpc', 1),
  ('prednisolona', 'infeccao_ativa', 'Infeção ativa (incl. varicela/zona)', 'Active infection (incl. varicella/shingles)', 'contraindication', 'critical', 'Os corticosteroides podem mascarar e agravar infeções, incluindo varicela grave.', 'Corticosteroids may mask and worsen infections, including severe varicella.', 'Evitar em infeções sistémicas ativas sem antibioterapia; vacinação em dia antes de terapêutica prolongada.', 'Avoid in active systemic infections without antibiotic cover; keep vaccinations up to date before long-term therapy.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc', 1),
  ('prednisolona', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus', 'precaution', 'moderate', 'Os corticosteroides elevam a glicemia.', 'Corticosteroids raise blood glucose.', 'Monitorizar glicemia e ajustar antidiabéticos durante a terapêutica.', 'Monitor blood glucose and adjust antidiabetics during therapy.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc', 1),
  ('prednisolona', 'osteoporose', 'Osteoporose', 'Osteoporosis', 'precaution', 'moderate', 'O uso prolongado de corticosteroides acelera a perda óssea.', 'Long-term corticosteroids accelerate bone loss.', 'Usar a menor dose/duração; considerar cálcio + vitamina D e vigiar densidade óssea.', 'Use the lowest dose/duration; consider calcium + vitamin D and monitor bone density.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc', 1),
  ('prednisolona', 'glaucoma', 'Glaucoma', 'Glaucoma', 'precaution', 'moderate', 'Os corticosteroides podem elevar a pressão intraocular.', 'Corticosteroids may raise intraocular pressure.', 'Monitorizar pressão intraocular em terapêuticas prolongadas.', 'Monitor intraocular pressure on long-term therapy.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc', 1),
  ('hidroxicloroquina', 'doenca_retina', 'Doença da retina (maculopatia)', 'Retinal disease (maculopathy)', 'precaution', 'moderate', 'A hidroxicloroquina pode causar retinopatia cumulativa irreversível.', 'Hydroxychloroquine may cause cumulative irreversible retinopathy.', 'Avaliação oftalmológica basal e periódica (sobretudo > 5 anos ou fator de risco).', 'Baseline and periodic ophthalmological review (especially > 5 years or risk factors).', 'EMC-UK (MHRA) — SmPC aprovada Hidroxicloroquina: https://www.medicines.org.uk/emc/product/11540/smpc', 'EMC-UK (MHRA) — approved Hydroxychloroquine SmPC: https://www.medicines.org.uk/emc/product/11540/smpc', 1),
  ('hidroxicloroquina', 'doenca_hepatica_ativa', 'Doença hepática ativa', 'Active liver disease', 'precaution', 'moderate', 'O metabolismo hepático reduzido pode aumentar a exposição.', 'Reduced hepatic metabolism may increase exposure.', 'Usar com precaução e monitorizar função hepática.', 'Use with caution and monitor liver function.', 'EMC-UK (MHRA) — SmPC aprovada Hidroxicloroquina: https://www.medicines.org.uk/emc/product/11540/smpc', 'EMC-UK (MHRA) — approved Hydroxychloroquine SmPC: https://www.medicines.org.uk/emc/product/11540/smpc', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('naproxeno', 'caution', 'Os AINE devem ser evitados no 3.º trimestre (fecho prematuro do canal arterial, oligohidrâmnios). Uso ocasional no 1.º/2.º trimestre com precaução.', 'NSAIDs should be avoided in the 3rd trimester (premature ductus arteriosus closure, oligohydramnios). Occasional use in 1st/2nd trimester with caution.', 'Evitar no 3.º trimestre; usar a menor dose pelo menor tempo possível no 1.º/2.º trimestre.', 'Avoid in the 3rd trimester; use the lowest dose for the shortest time in the 1st/2nd trimester.', 'Preferir paracetamol na gravidez quando indicado.', 'Prefer paracetamol in pregnancy when indicated.', 'A concentração no leite é baixa; uso ocasional compatível com vigilância do lactente.', 'Milk levels are low; occasional use is compatible with infant monitoring.', 'EMC-UK (MHRA) — SmPC aprovada Naproxeno: https://www.medicines.org.uk/emc/product/13237/smpc', 'EMC-UK (MHRA) — approved Naproxen SmPC: https://www.medicines.org.uk/emc/product/13237/smpc'),
  ('celecoxib', 'caution', 'O celecoxib (AINE) deve ser evitado no 3.º trimestre; dados limitados no início da gravidez.', 'Celecoxib (NSAID) should be avoided in the 3rd trimester; limited data in early pregnancy.', 'Evitar no 3.º trimestre; evitar em mulheres que tentam engravidar (possível efeito na ovulação).', 'Avoid in the 3rd trimester; avoid in women trying to conceive (possible effect on ovulation).', 'Preferir paracetamol na gravidez.', 'Prefer paracetamol in pregnancy.', 'Dados limitados; preferir evitar durante a amamentação.', 'Limited data; prefer to avoid during breastfeeding.', 'EMC-UK (MHRA) — SmPC aprovada Celecoxib: https://www.medicines.org.uk/emc/product/5533/smpc', 'EMC-UK (MHRA) — approved Celecoxib SmPC: https://www.medicines.org.uk/emc/product/5533/smpc'),
  ('metotrexato', 'contraindicated', 'O metotrexato é teratogénico e abortivo; está contraindicado na gravidez e na conceção planeada.', 'Methotrexate is teratogenic and abortifacient; contraindicated in pregnancy and planned conception.', 'Contraindicado; usar contraceção eficaz durante e até 3-6 meses após o tratamento (homens: 3 meses).', 'Contraindicated; use effective contraception during and up to 3-6 months after treatment (men: 3 months).', 'Contraindicado na amamentação.', 'Contraindicated during breastfeeding.', 'Contraceção eficaz obrigatória durante e até 3-6 meses após a terapêutica.', 'Effective contraception mandatory during and up to 3-6 months after therapy.', 'EMC-UK (MHRA) — SmPC aprovada Metotrexato: https://www.medicines.org.uk/emc/product/511/smpc', 'EMC-UK (MHRA) — approved Methotrexate SmPC: https://www.medicines.org.uk/emc/product/511/smpc'),
  ('leflunomida', 'contraindicated', 'A leflunomida é teratogénica; está contraindicada na gravidez.', 'Leflunomide is teratogenic; contraindicated in pregnancy.', 'Contraindicado; contraceção eficaz obrigatória e procedimento de washout (colestiramina) antes da conceção.', 'Contraindicated; mandatory effective contraception and washout procedure (cholestyramine) before conception.', 'Contraindicado na amamentação.', 'Contraindicated during breastfeeding.', 'Contraceção eficaz obrigatória; washout com colestiramina antes de engravidar.', 'Effective contraception mandatory; cholestyramine washout before pregnancy.', 'EMC-UK (MHRA) — SmPC aprovada Leflunomida: https://www.medicines.org.uk/emc/product/4944/smpc', 'EMC-UK (MHRA) — approved Leflunomide SmPC: https://www.medicines.org.uk/emc/product/4944/smpc'),
  ('colchicina', 'caution', 'Dados limitados; doses baixas parecem ter baixo risco, mas a exposição deve ser minimizada.', 'Limited data; low doses appear to carry low risk, but exposure should be minimised.', 'Usar apenas se claramente necessário e à menor dose, sobretudo no 1.º trimestre.', 'Use only if clearly necessary and at the lowest dose, especially in the 1st trimester.', 'Dados limitados; preferir evitar durante a amamentação.', 'Limited data; prefer to avoid during breastfeeding.', 'Não há recomendação formal de contraceção, mas minimizar a exposição.', 'No formal contraception requirement, but minimise exposure.', 'EMC-UK (MHRA) — SmPC aprovada Colchicina: https://www.medicines.org.uk/emc/product/14362/smpc', 'EMC-UK (MHRA) — approved Colchicine SmPC: https://www.medicines.org.uk/emc/product/14362/smpc'),
  ('febuxostat', 'no_data', 'Não existem dados suficientes em humanos; estudos animais mostraram efeitos adversos.', 'No adequate human data; animal studies showed adverse effects.', 'Evitar durante a gravidez, exceto se o benefício justificar o risco.', 'Avoid during pregnancy unless benefit justifies risk.', 'Desconhecido; preferir evitar durante a amamentação.', 'Unknown; prefer to avoid during breastfeeding.', 'Usar contraceção eficaz dadas as incertezas quanto ao risco.', 'Use effective contraception given uncertainty about risk.', 'EMC-UK (MHRA) — SmPC aprovada Febuxostat: https://www.medicines.org.uk/emc/product/487/smpc', 'EMC-UK (MHRA) — approved Febuxostat SmPC: https://www.medicines.org.uk/emc/product/487/smpc'),
  ('alendronato', 'contraindicated', 'Os bifosfonatos não são recomendados na gravidez (longa semi-vida e deposição óssea).', 'Bisphosphonates are not recommended in pregnancy (long half-life and bone deposition).', 'Evitar na gravidez; descontinuar antes de uma gravidez planeada se clinicamente possível.', 'Avoid in pregnancy; discontinue before planned conception if clinically possible.', 'Desconhecido; preferir evitar durante a amamentação.', 'Unknown; prefer to avoid during breastfeeding.', 'Descontinuar antes de gravidez planeada; usar contraceção eficaz.', 'Discontinue before planned pregnancy; use effective contraception.', 'EMC-UK (MHRA) — SmPC aprovada Alendronato: https://www.medicines.org.uk/emc/product/5206/smpc', 'EMC-UK (MHRA) — approved Alendronate SmPC: https://www.medicines.org.uk/emc/product/5206/smpc'),
  ('calcitriol', 'caution', 'O calcitriol em doses suprafisiológicas pode ser teratogénico; em doses de reposição o risco é baixo, vigiando a calcemia.', 'Calcitriol at supraphysiological doses may be teratogenic; at replacement doses the risk is low, monitoring serum calcium.', 'Usar apenas se necessário, com monitorização da calcemia.', 'Use only if necessary, with serum calcium monitoring.', 'Compatível na amamentação em doses de reposição, com vigilância do lactente.', 'Compatible during breastfeeding at replacement doses, with infant monitoring.', 'Em doses de reposição não é exigido recurso contracetivo; manter cautela com doses altas.', 'At replacement doses no contraception requirement; caution with high doses.', 'EMC-UK (MHRA) — SmPC aprovada Calcitriol: https://www.medicines.org.uk/emc/product/101902/smpc', 'EMC-UK (MHRA) — approved Calcitriol SmPC: https://www.medicines.org.uk/emc/product/101902/smpc'),
  ('aspirina', 'caution', 'A aspirina em dose antiagregante é usada em situações específicas; em dose analgésica deve ser evitada no 3.º trimestre.', 'Aspirin at antiplatelet dose is used in specific settings; at analgesic dose should be avoided in the 3rd trimester.', 'Manter apenas sob indicação médica (ex.: pré-eclâmpsia); evitar dose analgésica no 3.º trimestre.', 'Keep only on medical indication (e.g. pre-eclampsia); avoid analgesic dose in the 3rd trimester.', 'Dose única ocasional compatível; doses repetidas devem ser evitadas.', 'Occasional single dose is compatible; repeated doses should be avoided.', 'Contraceção não é suprimida; manter apenas por indicação médica.', 'No specific contraception; keep only on medical indication.', 'EMC-UK (MHRA) — SmPC aprovada Ácido acetilsalicílico: https://www.medicines.org.uk/emc/product/8627/smpc', 'EMC-UK (MHRA) — approved Aspirin SmPC: https://www.medicines.org.uk/emc/product/8627/smpc'),
  ('ibuprofeno', 'caution', 'Evitar no 3.º trimestre (fecho do canal arterial, oligohidrâmnios). Uso ocasional no 1.º/2.º trimestre com precaução.', 'Avoid in the 3rd trimester (ductus arteriosus closure, oligohydramnios). Occasional use in 1st/2nd trimester with caution.', 'Evitar no 3.º trimestre; usar a menor dose pelo menor tempo possível.', 'Avoid in the 3rd trimester; use the lowest dose for the shortest time.', 'Concentração no leite baixa; uso ocasional compatível.', 'Low milk levels; occasional use is compatible.', 'Usar paracetamol na gravidez; não há exigência específica de contraceção.', 'Use paracetamol in pregnancy; no specific contraception.', 'EMC-UK (MHRA) — SmPC aprovada Ibuprofeno: https://www.medicines.org.uk/emc/product/6713/smpc', 'EMC-UK (MHRA) — approved Ibuprofen SmPC: https://www.medicines.org.uk/emc/product/6713/smpc'),
  ('diclofenac', 'caution', 'Evitar no 3.º trimestre; dados limitados no início da gravidez.', 'Avoid in the 3rd trimester; limited data in early pregnancy.', 'Evitar no 3.º trimestre; usar a menor dose possível.', 'Avoid in the 3rd trimester; use the lowest dose possible.', 'Dados limitados; uso ocasional provavelmente compatível.', 'Limited data; occasional use probably compatible.', 'Usar paracetamol se possível; não há exigência específica de contraceção.', 'Use paracetamol where possible; no specific contraception.', 'EMC-UK (MHRA) — SmPC aprovada Diclofenac: https://www.medicines.org.uk/emc/product/4333/smpc', 'EMC-UK (MHRA) — approved Diclofenac SmPC: https://www.medicines.org.uk/emc/product/4333/smpc'),
  ('alopurinol', 'caution', 'Dados limitados; uso durante a gravidez apenas se o benefício justificar o risco.', 'Limited data; use in pregnancy only if benefit justifies risk.', 'Usar apenas se necessário, na menor dose eficaz.', 'Use only if necessary, at the lowest effective dose.', 'Dados limitados; preferir evitar durante a amamentação.', 'Limited data; prefer to avoid during breastfeeding.', 'Manter contraceção eficaz; dados limitados na conceção.', 'Maintain effective contraception; limited conception data.', 'EMC-UK (MHRA) — SmPC aprovada Alopurinol: https://www.medicines.org.uk/emc/product/100235/smpc', 'EMC-UK (MHRA) — approved Allopurinol SmPC: https://www.medicines.org.uk/emc/product/100235/smpc'),
  ('azatioprina', 'caution', 'Usado em situações específicas (transplantes, doenças autoimunes) quando o benefício supera o risco.', 'Used in specific settings (transplants, autoimmune diseases) when benefit outweighs risk.', 'Manter apenas sob vigilância especializada; não iniciar sem indicação clara.', 'Keep only under specialist supervision; do not start without clear indication.', 'Dados limitados; preferir evitar, embora seja por vezes mantido em mães transplantadas.', 'Limited data; prefer to avoid, though sometimes kept in transplanted mothers.', 'Planear a gravidez com a equipa médica antes de suspender/continuar.', 'Plan pregnancy with the specialist team before stopping/continuing.', 'EMC-UK (MHRA) — SmPC aprovada Azatioprina: https://www.medicines.org.uk/emc/product/14296/smpc', 'EMC-UK (MHRA) — approved Azathioprine SmPC: https://www.medicines.org.uk/emc/product/14296/smpc'),
  ('prednisolona', 'caution', 'Os corticosteroides atravessam a placenta; risco baixo com doses baixas, mas associados a fenda palatina (pequeno aumento) no 1.º trimestre e retardo do crescimento com uso prolongado.', 'Corticosteroids cross the placenta; low risk at low doses, but associated with cleft palate (small increase) in the 1st trimester and growth restriction with prolonged use.', 'Usar a menor dose eficaz e a mais curta duração; monitorizar crescimento fetal.', 'Use the lowest effective dose for the shortest duration; monitor fetal growth.', 'Baixas doses compatíveis com amamentação; doses elevadas: aguardar 3-4 h após a toma.', 'Low doses are compatible with breastfeeding; high doses: wait 3-4 h after dosing.', 'Contraceção não é requerida de rotina; planear com o médico, sobretudo em terapêutica prolongada.', 'No routine contraception needed; plan with the doctor, especially long-term therapy.', 'EMC-UK (MHRA) — SmPC aprovada Prednisolona: https://www.medicines.org.uk/emc/product/2427/smpc', 'EMC-UK (MHRA) — approved Prednisolone SmPC: https://www.medicines.org.uk/emc/product/2427/smpc'),
  ('hidroxicloroquina', 'caution', 'Usada habitualmente em lúpus durante a gravidez (reduz surtos); benefício geralmente supera o risco.', 'Routinely used in lupus during pregnancy (reduces flares); benefit usually outweighs risk.', 'Manter sob vigilância especializada; não suspender em lúpus sem indicação médica.', 'Keep under specialist supervision; do not stop in lupus without medical advice.', 'Concentrações no leite baixas; considerado compatível com a amamentação.', 'Low milk levels; considered compatible with breastfeeding.', 'Planear a gravidez com a equipa; contraceção não é contraindicada.', 'Plan pregnancy with the team; contraception not contraindicated.', 'EMC-UK (MHRA) — SmPC aprovada Hidroxicloroquina: https://www.medicines.org.uk/emc/product/11540/smpc', 'EMC-UK (MHRA) — approved Hydroxychloroquine SmPC: https://www.medicines.org.uk/emc/product/11540/smpc')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;