-- ================================================================
-- 068_seed_interacoes_antialergicos.sql
-- Secção 10 (Medicação antialérgica): 10.1 Anti-histamínicos;
-- 10.2 Corticosteróides (uso sistémico na alergia);
-- 10.3 Simpaticomiméticos (adrenalina, descongestionantes).
-- Novos (9): cetirizina, loratadina, desloratadina, fexofenadina,
--            levocetirizina, difenidramina, dexametasona, adrenalina,
--            pseudoefedrina.
-- Extensão 3 dimensões (existentes): budesonida (alimento), midodrina
--            (alimento), montelukast (doença).
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico; fallback DailyMed (FDA).
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('cetirizina', 'Cetirizina', 'Cetirizine', 'Anti-histamínico H1 de 2.ª geração (piperazina)', 'Second-generation H1 antihistamine (piperazine)', ARRAY['Zyrtec', 'cetirizina', 'cetirizine', 'Zirtin'], 'published', 159),
  ('loratadina', 'Loratadina', 'Loratadine', 'Anti-histamínico H1 de 2.ª geração (tricíclico)', 'Second-generation H1 antihistamine (tricyclic)', ARRAY['Clarityn', 'loratadina', 'loratadine'], 'published', 160),
  ('desloratadina', 'Desloratadina', 'Desloratadine', 'Anti-histamínico H1 de 2.ª geração (metabolito ativo da loratadina)', 'Second-generation H1 antihistamine (active loratadine metabolite)', ARRAY['Aerius', 'desloratadina', 'desloratadine'], 'published', 161),
  ('fexofenadina', 'Fexofenadina', 'Fexofenadine', 'Anti-histamínico H1 de 2.ª/3.ª geração (metabolito da terfenadina)', 'Second/third-generation H1 antihistamine (terfenadine metabolite)', ARRAY['Telfast', 'fexofenadina', 'fexofenadine', 'Allegra'], 'published', 162),
  ('levocetirizina', 'Levocetirizina', 'Levocetirizine', 'Anti-histamínico H1 de 2.ª geração (enantiómero ativo da cetirizina)', 'Second-generation H1 antihistamine (active cetirizine enantiomer)', ARRAY['Xyzal', 'levocetirizina', 'levocetirizine'], 'published', 163),
  ('difenidramina', 'Difenidramina', 'Diphenhydramine', 'Anti-histamínico H1 de 1.ª geração (sedativo)', 'First-generation H1 antihistamine (sedating)', ARRAY['Benadryl', 'difenidramina', 'diphenhydramine'], 'published', 164),
  ('dexametasona', 'Dexametasona', 'Dexamethasone', 'Corticosteroide sistémico (glucocorticoide)', 'Systemic corticosteroid (glucocorticoid)', ARRAY['Dexametasona', 'dexamethasone', 'Decadron'], 'published', 165),
  ('adrenalina', 'Adrenalina', 'Epinephrine', 'Simpaticomimético (catecolamina α/β)', 'Sympathomimetic (α/β catecholamine)', ARRAY['Epipen', 'adrenalina', 'epinephrine', 'adrenaline'], 'published', 166),
  ('pseudoefedrina', 'Pseudoefedrina', 'Pseudoephedrine', 'Simpaticomimético (descongestionante nasal α-agonista)', 'Sympathomimetic (α-agonist nasal decongestant)', ARRAY['Sudafed', 'pseudoefedrina', 'pseudoephedrine'], 'published', 167);

-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('cetirizina', 'ritonavir', 'moderate', 'Cetirizina + ritonavir: possível aumento da exposição à cetirizina.', 'Cetirizine + ritonavir: possible increased cetirizine exposure.', 'O ritonavir pode aumentar a concentração da cetirizina (interação farmacocinética descrita no rótulo).', 'Ritonavir may raise cetirizine concentrations (pharmacokinetic interaction described in the label).', 'Vigiar sonolência excessiva e efeitos adversos do anti-histamínico.', 'Watch for excessive drowsiness and antihistamine adverse effects.', 'Efeitos sedativos e tolerância à terapêutica.', 'Sedative effects and tolerance to therapy.', 'Sonolência marcada, boca seca, confusão.', 'Marked drowsiness, dry mouth, confusion.', 'DailyMed (FDA) — rótulo aprovado Cetirizina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b92d959d-dd35-b2a3-e053-2995a90af3ff ; rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Cetirizine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b92d959d-dd35-b2a3-e053-2995a90af3ff ; approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('loratadina', 'eritromicina', 'moderate', 'Loratadina + eritromicina: possível aumento das concentrações de loratadina.', 'Loratadine + erythromycin: possible increased loratadine concentrations.', 'A eritromicina (inibidor do CYP3A4) reduz o metabolismo da loratadina.', 'Erythromycin (CYP3A4 inhibitor) reduces loratadine metabolism.', 'Vigiar sedação e efeitos adversos; a maioria tolera sem ajuste de dose.', 'Watch for sedation and adverse effects; most tolerate without dose adjustment.', 'Sintomas de excesso de anti-histamínico.', 'Symptoms of antihistamine excess.', 'Sonolência, cefaleias, palpitações.', 'Drowsiness, headache, palpitations.', 'DailyMed (FDA) — rótulo aprovado Loratadina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=569a35be-d653-181c-e063-6294a90a6eb9 ; rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c05e1f7-a3d4-8e69-e063-6394a90aecc3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Loratadine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=569a35be-d653-181c-e063-6294a90a6eb9 ; approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c05e1f7-a3d4-8e69-e063-6394a90aecc3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('loratadina', 'cetoconazol', 'moderate', 'Loratadina + cetoconazol: possível aumento das concentrações de loratadina.', 'Loratadine + ketoconazole: possible increased loratadine concentrations.', 'O cetoconazol (inibidor do CYP3A4 e da P-gp) reduz a depuração da loratadina.', 'Ketoconazole (CYP3A4 and P-gp inhibitor) reduces loratadine clearance.', 'Vigiar sonolência; em ensaios não se observou prolongamento do QTc relevante.', 'Watch for drowsiness; trials showed no relevant QTc prolongation.', 'Efeitos sedativos e eletrocardiograma se fatores de risco.', 'Sedative effects and ECG if risk factors present.', 'Síncope, palpitações, sonolência acentuada.', 'Syncope, palpitations, marked drowsiness.', 'DailyMed (FDA) — rótulo aprovado Loratadina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=569a35be-d653-181c-e063-6294a90a6eb9 ; rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Loratadine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=569a35be-d653-181c-e063-6294a90a6eb9 ; approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('desloratadina', 'eritromicina', 'moderate', 'Desloratadina + eritromicina: possível aumento das concentrações de desloratadina.', 'Desloratadine + erythromycin: possible increased desloratadine concentrations.', 'A eritromicina reduz o metabolismo da desloratadina (CYP3A4).', 'Erythromycin reduces desloratadine metabolism (CYP3A4).', 'Vigiar sedação; não é geralmente necessário ajuste de dose.', 'Watch for sedation; dose adjustment is usually not required.', 'Efeitos adversos do anti-histamínico.', 'Antihistamine adverse effects.', 'Sonolência, xerostomia, cefaleia.', 'Drowsiness, dry mouth, headache.', 'DailyMed (FDA) — rótulo aprovado Desloratadina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2a90b899-7746-43dc-ac8a-e754428eb30c ; rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c05e1f7-a3d4-8e69-e063-6394a90aecc3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Desloratadine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2a90b899-7746-43dc-ac8a-e754428eb30c ; approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c05e1f7-a3d4-8e69-e063-6394a90aecc3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('desloratadina', 'cetoconazol', 'moderate', 'Desloratadina + cetoconazol: possível aumento das concentrações de desloratadina.', 'Desloratadine + ketoconazole: possible increased desloratadine concentrations.', 'O cetoconazol inibe o CYP3A4, elevando os níveis de desloratadina.', 'Ketoconazole inhibits CYP3A4, raising desloratadine levels.', 'Vigiar sedação e efeitos adversos.', 'Watch for sedation and adverse effects.', 'Sintomas de excesso de anti-histamínico.', 'Symptoms of antihistamine excess.', 'Sonolência, palpitações, tonturas.', 'Drowsiness, palpitations, dizziness.', 'DailyMed (FDA) — rótulo aprovado Desloratadina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2a90b899-7746-43dc-ac8a-e754428eb30c ; rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Desloratadine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2a90b899-7746-43dc-ac8a-e754428eb30c ; approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('fexofenadina', 'eritromicina', 'moderate', 'Fexofenadina + eritromicina: aumento da exposição à fexofenadina (transporte OATP/P-gp).', 'Fexofenadine + erythromycin: increased fexofenadine exposure (OATP/P-gp transport).', 'A eritromicina interfere com o transporte intestinal (P-gp/OATP), elevando os níveis de fexofenadina.', 'Erythromycin interferes with intestinal transport (P-gp/OATP), raising fexofenadine levels.', 'Vigiar efeitos adversos; sem relevância clínica significativa para a maioria.', 'Watch for adverse effects; not clinically significant for most.', 'Efeitos adversos do anti-histamínico.', 'Antihistamine adverse effects.', 'Náuseas, tonturas, sonolência.', 'Nausea, dizziness, drowsiness.', 'DailyMed (FDA) — rótulo aprovado Fexofenadina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd0da52b-fc82-4ec9-854c-0d7c52e926fb ; rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c05e1f7-a3d4-8e69-e063-6394a90aecc3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Fexofenadine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd0da52b-fc82-4ec9-854c-0d7c52e926fb ; approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c05e1f7-a3d4-8e69-e063-6394a90aecc3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('fexofenadina', 'cetoconazol', 'moderate', 'Fexofenadina + cetoconazol: aumento da exposição à fexofenadina.', 'Fexofenadine + ketoconazole: increased fexofenadine exposure.', 'O cetoconazol interfere com o transporte intestinal da fexofenadina (P-gp/OATP).', 'Ketoconazole interferes with intestinal fexofenadine transport (P-gp/OATP).', 'Vigiar efeitos adversos; sem impacto clínico relevante na maioria dos doentes.', 'Watch for adverse effects; no relevant clinical impact for most patients.', 'Efeitos adversos do anti-histamínico.', 'Antihistamine adverse effects.', 'Sonolência, tonturas, náuseas.', 'Drowsiness, dizziness, nausea.', 'DailyMed (FDA) — rótulo aprovado Fexofenadina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd0da52b-fc82-4ec9-854c-0d7c52e926fb ; rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Fexofenadine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd0da52b-fc82-4ec9-854c-0d7c52e926fb ; approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('levocetirizina', 'ritonavir', 'moderate', 'Levocetirizina + ritonavir: possível aumento da exposição à levocetirizina.', 'Levocetirizine + ritonavir: possible increased levocetirizine exposure.', 'O ritonavir pode reduzir a depuração da levocetirizina.', 'Ritonavir may reduce levocetirizine clearance.', 'Vigiar sedação e efeitos adversos.', 'Watch for sedation and adverse effects.', 'Efeitos sedativos e tolerância.', 'Sedative effects and tolerance.', 'Sonolência, fadiga, boca seca.', 'Drowsiness, fatigue, dry mouth.', 'DailyMed (FDA) — rótulo aprovado Levocetirizina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f722b84-08de-7e6a-41ac-2c9d9bb9fb43 ; rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Levocetirizine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f722b84-08de-7e6a-41ac-2c9d9bb9fb43 ; approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('difenidramina', 'morfina', 'moderate', 'Anti-histamínico sedativo + opioide: depressão do SNC aditiva.', 'Sedating antihistamine + opioid: additive CNS depression.', 'Ambos deprimem o sistema nervoso central, potenciando a sedação e a depressão respiratória.', 'Both depress the CNS, potentiating sedation and respiratory depression.', 'Evitar a associação; se inevitável, usar a menor dose e vigiar sedação/respiração.', 'Avoid the combination; if unavoidable, use the lowest dose and watch sedation/respiration.', 'Nível de consciência, frequência respiratória, oximetria.', 'Level of consciousness, respiratory rate, oximetry.', 'Sonolência profunda, bradipneia, confusão.', 'Deep drowsiness, bradypnoea, confusion.', 'DailyMed (FDA) — rótulo aprovado Difenidramina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8944f3c-acef-4ebe-9633-7d641ae95edf ; rótulo aprovado Morfina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57ee014e-744e-65e1-e063-6394a90a8c93 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Diphenhydramine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8944f3c-acef-4ebe-9633-7d641ae95edf ; approved Morphine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=57ee014e-744e-65e1-e063-6394a90a8c93 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('difenidramina', 'tramadol', 'moderate', 'Anti-histamínico sedativo + tramadol: sedação aditiva e risco de convulsões.', 'Sedating antihistamine + tramadol: additive sedation and seizure risk.', 'Efeito depressor do SNC aditivo; o tramadol baixa o limiar convulsivo.', 'Additive CNS depressant effect; tramadol lowers the seizure threshold.', 'Evitar em doentes idosos/frágeis; vigiar sedação e sintomas neurológicos.', 'Avoid in elderly/frail patients; watch for sedation and neurological symptoms.', 'Nível de consciência e sintomas neurológicos.', 'Level of consciousness and neurological symptoms.', 'Convulsões, sonolência excessiva, confusão.', 'Seizures, excessive drowsiness, confusion.', 'DailyMed (FDA) — rótulo aprovado Difenidramina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8944f3c-acef-4ebe-9633-7d641ae95edf ; rótulo aprovado Tramadol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f0e33bd-65f8-446a-886f-e7e16a142ce5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Diphenhydramine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8944f3c-acef-4ebe-9633-7d641ae95edf ; approved Tramadol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9f0e33bd-65f8-446a-886f-e7e16a142ce5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('difenidramina', 'sertralina', 'minor', 'Anti-histamínico sedativo + ISRS: sedação aditiva ligeira.', 'Sedating antihistamine + SSRI: mild additive sedation.', 'Ambos podem causar sedação e efeitos anticolinérgicos aditivos.', 'Both may cause sedation and additive anticholinergic effects.', 'Usar com precaução; vigiar sonolência diurna.', 'Use with caution; watch for daytime drowsiness.', 'Sintomas de sedação excessiva.', 'Symptoms of excessive sedation.', 'Sonolência diurna, confusão em idosos.', 'Daytime drowsiness, confusion in the elderly.', 'DailyMed (FDA) — rótulo aprovado Difenidramina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8944f3c-acef-4ebe-9633-7d641ae95edf ; rótulo aprovado Sertralina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=91e24d17-ff0a-449c-9472-b9df74c98456 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Diphenhydramine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8944f3c-acef-4ebe-9633-7d641ae95edf ; approved Sertraline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=91e24d17-ff0a-449c-9472-b9df74c98456 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'warfarina', 'moderate', 'Corticosteroide + anticoagulante: alteração do INR e risco hemorrágico.', 'Corticosteroid + anticoagulant: altered INR and bleeding risk.', 'Os corticosteroides podem potenciar ou reduzir o efeito da varfarina (efeito variável sobre a hemostase e a mucosa GI).', 'Corticosteroids may potentiate or reduce warfarin effect (variable effect on haemostasis and GI mucosa).', 'Monitorizar INR após início/ajuste de corticosteroide; considerar gastroprotecção.', 'Monitor INR after starting/adjusting corticosteroids; consider gastroprotection.', 'INR periódico e sintomas digestivos.', 'Periodic INR and GI symptoms.', 'Melena, hematemese, hemorragia.', 'Melena, haematemesis, bleeding.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'furosemida', 'moderate', 'Corticosteroide + diurético de ansa: risco de hipocaliemia aditiva.', 'Corticosteroid + loop diuretic: additive hypokalaemia risk.', 'Ambos aumentam a perda renal de potássio.', 'Both increase renal potassium loss.', 'Monitorizar o potássio sérico; considerar suplementação se necessário.', 'Monitor serum potassium; consider supplementation if needed.', 'Potássio sérico e sintomas de hipocaliemia.', 'Serum potassium and hypokalaemia symptoms.', 'Fraqueza, cãibras, arritmias.', 'Weakness, cramps, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'hidroclorotiazida', 'moderate', 'Corticosteroide + tiazida: hipocaliemia e hiperglicemia aditivas.', 'Corticosteroid + thiazide: additive hypokalaemia and hyperglycaemia.', 'Ambos favorecem a perda de potássio e a elevação da glicemia.', 'Both promote potassium loss and raised blood glucose.', 'Monitorizar potássio e glicemia; ajustar terapêutica se necessário.', 'Monitor potassium and blood glucose; adjust therapy if needed.', 'Potássio, glicemia e tensão arterial.', 'Potassium, blood glucose and blood pressure.', 'Fraqueza, cãibras, poliúria, descompensação glicémica.', 'Weakness, cramps, polyuria, glycaemic decompensation.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'digoxina', 'moderate', 'Corticosteroide + digoxina: a hipocaliemia induzida aumenta a toxicidade digitálica.', 'Corticosteroid + digoxin: induced hypokalaemia increases digoxin toxicity.', 'A perda de potássio associada ao corticosteroide sensibiliza o miocárdio à digoxina.', 'Corticosteroid-associated potassium loss sensitises the myocardium to digoxin.', 'Monitorizar potássio e sinais de toxicidade digitálica.', 'Monitor potassium and signs of digoxin toxicity.', 'Potássio sérico e eletrocardiograma.', 'Serum potassium and ECG.', 'Náuseas, arritmias, confusão, visão a cores alterada.', 'Nausea, arrhythmias, confusion, altered colour vision.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'carbamazepina', 'moderate', 'Corticosteroide + carbamazepina: indução do CYP3A4 reduz o efeito do corticosteroide.', 'Corticosteroid + carbamazepine: CYP3A4 induction reduces corticosteroid effect.', 'A carbamazepina (inductor do CYP3A4) acelera o metabolismo da dexametasona.', 'Carbamazepine (CYP3A4 inducer) accelerates dexamethasone metabolism.', 'Vigiar resposta clínica; pode ser necessário aumentar a dose do corticosteroide.', 'Watch clinical response; a higher corticosteroid dose may be needed.', 'Resposta clínica à terapêutica.', 'Clinical response to therapy.', 'Falta de controlo dos sintomas inflamatórios/alérgicos.', 'Lack of control of inflammatory/allergic symptoms.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=97e6e175-75e8-437b-b457-ddb1ae4e857d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=97e6e175-75e8-437b-b457-ddb1ae4e857d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'fenitoina', 'moderate', 'Corticosteroide + fenitoína: indução enzimática reduz o efeito de ambos.', 'Corticosteroid + phenytoin: enzyme induction reduces the effect of both.', 'A fenitoína induz o CYP3A4 (metabolismo da dexametasona) e a dexametasona altera o metabolismo da fenitoína.', 'Phenytoin induces CYP3A4 (dexamethasone metabolism) and dexamethasone alters phenytoin metabolism.', 'Monitorizar resposta e, se possível, dos níveis de fenitoína.', 'Monitor response and, if feasible, phenytoin levels.', 'Resposta clínica e níveis séricos de fenitoína.', 'Clinical response and serum phenytoin levels.', 'Crises convulsivas, falta de controlo alérgico/inflamatório.', 'Seizures, lack of allergic/inflammatory control.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'claritromicina', 'moderate', 'Corticosteroide + claritromicina: a inibição do CYP3A4 aumenta a exposição ao corticosteroide.', 'Corticosteroid + clarithromycin: CYP3A4 inhibition increases corticosteroid exposure.', 'A claritromicina inibe o CYP3A4, reduzindo o metabolismo da dexametasona.', 'Clarithromycin inhibits CYP3A4, reducing dexamethasone metabolism.', 'Vigiar efeitos dos corticosteroides (hiperglicemia, retenção de líquidos, síndrome de Cushing).', 'Watch for corticosteroid effects (hyperglycaemia, fluid retention, Cushing syndrome).', 'Glicemia, tensão arterial e sinais de excesso de corticosteroides.', 'Blood glucose, blood pressure and signs of corticosteroid excess.', 'Ganho de peso, edema, hiperglicemia.', 'Weight gain, oedema, hyperglycaemia.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d836ae7e-fdbf-4dcb-a90d-ede1dcbc3e67 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'ritonavir', 'moderate', 'Corticosteroide + ritonavir: inibição do CYP3A4 aumenta muito a exposição ao corticosteroide.', 'Corticosteroid + ritonavir: CYP3A4 inhibition markedly increases corticosteroid exposure.', 'O ritonavir (inibidor potente do CYP3A4) reduz o metabolismo da dexametasona, com risco de síndrome de Cushing.', 'Ritonavir (potent CYP3A4 inhibitor) reduces dexamethasone metabolism, risking Cushing syndrome.', 'Evitar a associação; se inevitável, reduzir a dose de dexametasona e vigiar.', 'Avoid the combination; if unavoidable, reduce dexamethasone dose and monitor.', 'Glicemia, tensão arterial, sinais de excesso de corticosteroides.', 'Blood glucose, blood pressure, signs of corticosteroid excess.', 'Síndrome de Cushing, hiperglicemia, edema.', 'Cushing syndrome, hyperglycaemia, oedema.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'aspirina', 'moderate', 'Corticosteroide + aspirina: risco gastrointestinal aditivo (úlcera/hemorragia).', 'Corticosteroid + aspirin: additive gastrointestinal risk (ulcer/bleeding).', 'Ambos enfraquecem a proteção da mucosa gástrica.', 'Both weaken gastric mucosal protection.', 'Considerar gastroprotecção (IBP) em doentes de risco.', 'Consider gastroprotection (PPI) in at-risk patients.', 'Sintomas digestivos e sinais de hemorragia.', 'GI symptoms and signs of bleeding.', 'Melena, hematemese, dor abdominal.', 'Melena, haematemesis, abdominal pain.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Ácido acetilsalicílico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Aspirin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3ba0a9f2-062a-401e-82eb-54383a822366 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'ibuprofeno', 'moderate', 'Corticosteroide + AINE: risco gastrointestinal (úlcera/hemorragia) aditivo.', 'Corticosteroid + NSAID: additive gastrointestinal risk (ulcer/bleeding).', 'Ambos enfraquecem a proteção da mucosa gástrica.', 'Both weaken gastric mucosal protection.', 'Evitar a associação quando possível; se necessária, usar gastroprotecção.', 'Avoid the combination when possible; if needed, use gastroprotection.', 'Sintomas digestivos e hemograma se hemorragia.', 'GI symptoms and full blood count if bleeding.', 'Dor epigástrica, melena, hematemese.', 'Epigastric pain, melena, haematemesis.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Ibuprofeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Ibuprofen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=291602fa-8ebe-4200-bba7-9798c90f8a50 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('adrenalina', 'amiodarona', 'moderate', 'Adrenalina + antiarrítmico: risco de arritmias ventriculares.', 'Epinephrine + antiarrhythmic: risk of ventricular arrhythmias.', 'A estimulação adrenérgica adiciona-se a fármacos que prolongam a repolarização, aumentando o risco de arritmia.', 'Adrenergic stimulation adds to drugs that prolong repolarisation, increasing arrhythmia risk.', 'Usar com precaução em doentes com doença cardíaca; monitorizar ritmo cardíaco.', 'Use with caution in cardiac patients; monitor heart rhythm.', 'Eletrocardiograma e tensão arterial.', 'ECG and blood pressure.', 'Palpitações, taquicardia, arritmias ventriculares.', 'Palpitations, tachycardia, ventricular arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Adrenalina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Epinephrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('adrenalina', 'digoxina', 'moderate', 'Adrenalina + digoxina: risco de arritmias (sensibilização miocárdica).', 'Epinephrine + digoxin: risk of arrhythmias (myocardial sensitisation).', 'Ambos aumentam a automaticidade miocárdica; a hipocaliemia potenciada aumenta o risco de arritmias.', 'Both increase myocardial automaticity; potentiated hypokalaemia increases arrhythmia risk.', 'Monitorizar ritmo cardíaco e potássio em doentes com doença cardíaca.', 'Monitor heart rhythm and potassium in cardiac patients.', 'Eletrocardiograma e potássio sérico.', 'ECG and serum potassium.', 'Arritmias, palpitações, hipocaliemia.', 'Arrhythmias, palpitations, hypokalaemia.', 'DailyMed (FDA) — rótulo aprovado Adrenalina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Epinephrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('adrenalina', 'teofilina', 'moderate', 'Adrenalina + teofilina: efeitos cardíacos e hipocaliemia aditivos.', 'Epinephrine + theophylline: additive cardiac effects and hypokalaemia.', 'Ambos são estimulantes β-adrenérgicos; aumentam o risco de taquicardia, tremores e hipocaliemia.', 'Both are β-adrenergic stimulants; they increase the risk of tachycardia, tremor and hypokalaemia.', 'Monitorizar potássio e ritmo cardíaco, sobretudo em doentes cardiovasculares.', 'Monitor potassium and heart rhythm, especially in cardiovascular patients.', 'Potássio sérico e eletrocardiograma.', 'Serum potassium and ECG.', 'Taquiarritmias, tremores, hipocaliemia sintomática.', 'Tachyarrhythmias, tremor, symptomatic hypokalaemia.', 'DailyMed (FDA) — rótulo aprovado Adrenalina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; rótulo aprovado Teofilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Epinephrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; approved Theophylline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('adrenalina', 'salbutamol', 'moderate', 'Adrenalina + β2-agonista: efeitos simpáticos e hipocaliemia aditivos.', 'Epinephrine + β2-agonist: additive sympathetic effects and hypokalaemia.', 'A sobreposição β-adrenérgica aumenta taquicardia, tremores e perda de potássio.', 'Overlapping β-adrenergic effects increase tachycardia, tremor and potassium loss.', 'Monitorizar potássio e sintomas cardiovasculares em doentes de risco.', 'Monitor potassium and cardiovascular symptoms in at-risk patients.', 'Potássio e ritmo cardíaco.', 'Potassium and heart rhythm.', 'Palpitações, tremores, hipocaliemia.', 'Palpitations, tremor, hypokalaemia.', 'DailyMed (FDA) — rótulo aprovado Adrenalina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; rótulo aprovado Salbutamol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Epinephrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; approved Salbutamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('adrenalina', 'ciprofloxacina', 'minor', 'Adrenalina + fluoroquinolona: risco teórico de prolongamento do QTc.', 'Epinephrine + fluoroquinolone: theoretical risk of QTc prolongation.', 'Ambos podem prolongar o intervalo QTc em doentes suscetíveis.', 'Both may prolong the QTc interval in susceptible patients.', 'Usar com precaução em doentes com fatores de risco de QTc prolongado.', 'Use with caution in patients with QTc risk factors.', 'Eletrocardiograma em doentes de risco.', 'ECG in at-risk patients.', 'Palpitações, síncope.', 'Palpitations, syncope.', 'DailyMed (FDA) — rótulo aprovado Adrenalina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Epinephrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5726eeca-db88-ba8e-e063-6294a90a927d ; approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('pseudoefedrina', 'amiodarona', 'moderate', 'Descongestionante simpaticomimético + antiarrítmico: risco de arritmias e efeito pressor.', 'Sympathomimetic decongestant + antiarrhythmic: risk of arrhythmias and pressor effect.', 'A pseudoefedrina (α-agonista) aumenta a tensão arterial e o trabalho cardíaco, com risco de arritmia em doentes predispostos.', 'Pseudoephedrine (α-agonist) raises blood pressure and cardiac work, risking arrhythmia in predisposed patients.', 'Evitar em doença cardiovascular; se usado, monitorizar TA e ritmo.', 'Avoid in cardiovascular disease; if used, monitor BP and rhythm.', 'Tensão arterial e eletrocardiograma.', 'Blood pressure and ECG.', 'Hipertensão, taquicardia, arritmias.', 'Hypertension, tachycardia, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Pseudoefedrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Pseudoephedrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51a88e8e-da02-4b97-9e7e-442fbffd908d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('pseudoefedrina', 'teofilina', 'moderate', 'Descongestionante + teofilina: estimulação aditiva e hipocaliemia.', 'Decongestant + theophylline: additive stimulation and hypokalaemia.', 'Efeitos estimulantes aditivos (taquicardia, tremores) e possível perda de potássio.', 'Additive stimulant effects (tachycardia, tremor) and possible potassium loss.', 'Vigiar sintomas cardiovasculares; monitorizar potássio em doentes de risco.', 'Watch for cardiovascular symptoms; monitor potassium in at-risk patients.', 'Potássio e sintomas adrenérgicos.', 'Potassium and adrenergic symptoms.', 'Palpitações, tremores, insónia.', 'Palpitations, tremor, insomnia.', 'DailyMed (FDA) — rótulo aprovado Pseudoefedrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; rótulo aprovado Teofilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Pseudoephedrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; approved Theophylline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5e64036a-ee3e-42e7-9e59-881f88a4e298 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('pseudoefedrina', 'salbutamol', 'moderate', 'Descongestionante + β2-agonista: efeitos simpáticos aditivos.', 'Decongestant + β2-agonist: additive sympathetic effects.', 'A sobreposição α/β-adrenérgica aumenta a tensão arterial e a taquicardia.', 'Overlapping α/β-adrenergic effects raise blood pressure and heart rate.', 'Usar com precaução em doentes cardiovasculares; vigiar sintomas.', 'Use with caution in cardiovascular patients; watch for symptoms.', 'Tensão arterial e ritmo cardíaco.', 'Blood pressure and heart rhythm.', 'Hipertensão, palpitações, tremores.', 'Hypertension, palpitations, tremor.', 'DailyMed (FDA) — rótulo aprovado Pseudoefedrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; rótulo aprovado Salbutamol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Pseudoephedrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; approved Salbutamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('pseudoefedrina', 'sertralina', 'minor', 'Descongestionante + ISRS: possível aumento do efeito pressor e serotonérgico.', 'Decongestant + SSRI: possible increased pressor and serotonergic effect.', 'A pseudoefedrina pode adicionar efeito pressor; o ISRS interfere com o metabolismo.', 'Pseudoephedrine may add a pressor effect; the SSRI interferes with metabolism.', 'Vigiar tensão arterial e sintomas serotonérgicos.', 'Monitor blood pressure and serotonergic symptoms.', 'Tensão arterial em doentes de risco.', 'Blood pressure in at-risk patients.', 'Hipertensão, agitação, tremores.', 'Hypertension, agitation, tremor.', 'DailyMed (FDA) — rótulo aprovado Pseudoefedrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; rótulo aprovado Sertralina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=91e24d17-ff0a-449c-9472-b9df74c98456 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Pseudoephedrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; approved Sertraline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=91e24d17-ff0a-449c-9472-b9df74c98456 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('pseudoefedrina', 'fluoxetina', 'minor', 'Descongestionante + ISRS: possível aumento do efeito pressor.', 'Decongestant + SSRI: possible increased pressor effect.', 'Efeito simpaticomimético aditivo em doentes a ISRS (risco de hipertensão/taquicardia).', 'Additive sympathomimetic effect in patients on SSRIs (risk of hypertension/tachycardia).', 'Vigiar tensão arterial e frequência cardíaca.', 'Monitor blood pressure and heart rate.', 'Tensão arterial.', 'Blood pressure.', 'Hipertensão, palpitações.', 'Hypertension, palpitations.', 'DailyMed (FDA) — rótulo aprovado Pseudoefedrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; rótulo aprovado Fluoxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Pseudoephedrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78faa497-6743-b85b-e053-2a91aa0ae822 ; approved Fluoxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09fb3100-1e06-4cdc-8016-7e4f5d097490 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)')
) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('cetirizina', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode potenciar a sonolência causada pela cetirizina.', 'Alcohol may potentiate cetirizine-induced drowsiness.', 'Limitar o consumo de álcool, sobretudo se conduzir ou operar máquinas.', 'Limit alcohol, especially when driving or operating machinery.', 'EMC-UK (MHRA) — SmPC aprovada Cetirizina: https://www.medicines.org.uk/emc/product/3217/smpc', 'EMC-UK (MHRA) — approved Cetirizine SmPC: https://www.medicines.org.uk/emc/product/3217/smpc', 1),
  ('cetirizina', 'alimentos', 'Alimentos', 'Food', 'minor', 'Os alimentos não alteram de forma relevante a absorção da cetirizina.', 'Food does not significantly alter cetirizine absorption.', 'Pode tomar com ou sem alimentos.', 'May take with or without food.', 'EMC-UK (MHRA) — SmPC aprovada Cetirizina: https://www.medicines.org.uk/emc/product/3217/smpc', 'EMC-UK (MHRA) — approved Cetirizine SmPC: https://www.medicines.org.uk/emc/product/3217/smpc', 1),
  ('loratadina', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode potenciar a sonolência (rara com loratadina).', 'Alcohol may potentiate drowsiness (rare with loratadine).', 'Limitar o consumo de álcool em doentes suscetíveis.', 'Limit alcohol in susceptible patients.', 'EMC-UK (MHRA) — SmPC aprovada Loratadina: https://www.medicines.org.uk/emc/product/10942/smpc', 'EMC-UK (MHRA) — approved Loratadine SmPC: https://www.medicines.org.uk/emc/product/10942/smpc', 1),
  ('loratadina', 'toranja', 'Toranja', 'Grapefruit', 'moderate', 'A toranja (sumo) inibe o CYP3A4 e pode aumentar as concentrações de loratadina.', 'Grapefruit (juice) inhibits CYP3A4 and may raise loratadine concentrations.', 'Evitar sumo de toranja durante o tratamento.', 'Avoid grapefruit juice during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Loratadina: https://www.medicines.org.uk/emc/product/10942/smpc', 'EMC-UK (MHRA) — approved Loratadine SmPC: https://www.medicines.org.uk/emc/product/10942/smpc', 1),
  ('desloratadina', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode potenciar a sonolência.', 'Alcohol may potentiate drowsiness.', 'Limitar o consumo de álcool em doentes suscetíveis.', 'Limit alcohol in susceptible patients.', 'EMC-UK (MHRA) — SmPC aprovada Desloratadina: https://www.medicines.org.uk/emc/product/14722/smpc', 'EMC-UK (MHRA) — approved Desloratadine SmPC: https://www.medicines.org.uk/emc/product/14722/smpc', 1),
  ('desloratadina', 'toranja', 'Toranja', 'Grapefruit', 'moderate', 'A toranja (sumo) pode aumentar as concentrações de desloratadina.', 'Grapefruit (juice) may raise desloratadine concentrations.', 'Evitar sumo de toranja durante o tratamento.', 'Avoid grapefruit juice during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Desloratadina: https://www.medicines.org.uk/emc/product/14722/smpc', 'EMC-UK (MHRA) — approved Desloratadine SmPC: https://www.medicines.org.uk/emc/product/14722/smpc', 1),
  ('fexofenadina', 'sumos_frutas', 'Sumo de laranja, maçã e toranja', 'Orange, apple and grapefruit juice', 'moderate', 'Os sumos de laranja, maçã e toranja reduzem a absorção da fexofenadina (inibição do OATP).', 'Orange, apple and grapefruit juice reduce fexofenadine absorption (OATP inhibition).', 'Tomar a fexofenadina com água e separar dos sumos de fruta.', 'Take fexofenadine with water and separate from fruit juices.', 'EMC-UK (MHRA) — SmPC aprovada Fexofenadina: https://www.medicines.org.uk/emc/product/13208/smpc', 'EMC-UK (MHRA) — approved Fexofenadine SmPC: https://www.medicines.org.uk/emc/product/13208/smpc', 1),
  ('fexofenadina', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode potenciar a sonolência.', 'Alcohol may potentiate drowsiness.', 'Limitar o consumo de álcool.', 'Limit alcohol intake.', 'EMC-UK (MHRA) — SmPC aprovada Fexofenadina: https://www.medicines.org.uk/emc/product/13208/smpc', 'EMC-UK (MHRA) — approved Fexofenadine SmPC: https://www.medicines.org.uk/emc/product/13208/smpc', 1),
  ('levocetirizina', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool pode potenciar a sonolência e reduzir o desempenho psicomotor.', 'Alcohol may potentiate drowsiness and impair psychomotor performance.', 'Evitar álcool durante o tratamento, sobretudo ao conduzir.', 'Avoid alcohol during treatment, especially when driving.', 'EMC-UK (MHRA) — SmPC aprovada Levocetirizina: https://www.medicines.org.uk/emc/product/9917/smpc', 'EMC-UK (MHRA) — approved Levocetirizine SmPC: https://www.medicines.org.uk/emc/product/9917/smpc', 1),
  ('difenidramina', 'alcool', 'Álcool', 'Alcohol', 'moderate', 'O álcool potencia marcadamente a sedação da difenidramina.', 'Alcohol markedly potentiates diphenhydramine sedation.', 'Evitar álcool durante o tratamento.', 'Avoid alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Difenidramina: https://www.medicines.org.uk/emc/product/1476/smpc', 'EMC-UK (MHRA) — approved Diphenhydramine SmPC: https://www.medicines.org.uk/emc/product/1476/smpc', 1),
  ('difenidramina', 'alimentos', 'Alimentos', 'Food', 'minor', 'Os alimentos podem reduzir a irritação gástrica.', 'Food may reduce gastric irritation.', 'Pode tomar com alimentos se houver desconforto gástrico.', 'May take with food if stomach discomfort occurs.', 'EMC-UK (MHRA) — SmPC aprovada Difenidramina: https://www.medicines.org.uk/emc/product/1476/smpc', 'EMC-UK (MHRA) — approved Diphenhydramine SmPC: https://www.medicines.org.uk/emc/product/1476/smpc', 1),
  ('dexametasona', 'toranja', 'Toranja', 'Grapefruit', 'moderate', 'A toranja (sumo) inibe o CYP3A4 e aumenta a exposição à dexametasona.', 'Grapefruit (juice) inhibits CYP3A4 and increases dexamethasone exposure.', 'Evitar sumo de toranja durante o tratamento.', 'Avoid grapefruit juice during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('dexametasona', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode aumentar o risco gastrointestinal.', 'Alcohol may increase GI risk.', 'Limitar o consumo de álcool durante o tratamento.', 'Limit alcohol during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('adrenalina', 'cafe_cha', 'Café e bebidas com cafeína', 'Coffee and caffeinated drinks', 'minor', 'A cafeína pode potenciar os efeitos adrenérgicos da adrenalina (tremores, taquicardia).', 'Caffeine may potentiate the adrenergic effects of epinephrine (tremor, tachycardia).', 'Limitar o consumo de cafeína durante o tratamento.', 'Limit caffeine intake during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Adrenalina: https://www.medicines.org.uk/emc/product/3673/smpc', 'EMC-UK (MHRA) — approved Epinephrine SmPC: https://www.medicines.org.uk/emc/product/3673/smpc', 1),
  ('pseudoefedrina', 'cafe_cha', 'Café e bebidas com cafeína', 'Coffee and caffeinated drinks', 'minor', 'A cafeína pode potenciar os efeitos estimulantes da pseudoefedrina (taquicardia, insónia).', 'Caffeine may potentiate the stimulant effects of pseudoephedrine (tachycardia, insomnia).', 'Limitar o consumo de cafeína, sobretudo à noite.', 'Limit caffeine intake, especially at night.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc', 1),
  ('pseudoefedrina', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode potenciar os efeitos cardiovasculares.', 'Alcohol may potentiate the cardiovascular effects.', 'Limitar o consumo de álcool.', 'Limit alcohol intake.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc', 1),
  ('budesonida', 'toranja', 'Toranja', 'Grapefruit', 'moderate', 'A toranja (sumo) inibe o CYP3A4 e aumenta a exposição à budesonida.', 'Grapefruit (juice) inhibits CYP3A4 and increases budesonide exposure.', 'Evitar sumo de toranja durante o tratamento.', 'Avoid grapefruit juice during treatment.', 'EMC-UK (MHRA) — SmPC aprovada Budesonida: https://www.medicines.org.uk/emc/product/9715/smpc', 'EMC-UK (MHRA) — approved Budesonide SmPC: https://www.medicines.org.uk/emc/product/9715/smpc', 1),
  ('budesonida', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode potenciar o risco gastrointestinal dos corticosteroides.', 'Alcohol may potentiate the GI risk of corticosteroids.', 'Limitar o consumo de álcool.', 'Limit alcohol intake.', 'EMC-UK (MHRA) — SmPC aprovada Budesonida: https://www.medicines.org.uk/emc/product/9715/smpc', 'EMC-UK (MHRA) — approved Budesonide SmPC: https://www.medicines.org.uk/emc/product/9715/smpc', 1),
  ('midodrina', 'cafe_cha', 'Café e bebidas com cafeína', 'Coffee and caffeinated drinks', 'minor', 'A cafeína pode potenciar o efeito pressor da midodrina.', 'Caffeine may potentiate the pressor effect of midodrine.', 'Limitar o consumo de cafeína.', 'Limit caffeine intake.', 'EMC-UK (MHRA) — SmPC aprovada Midodrina: https://www.medicines.org.uk/emc/product/12040/smpc', 'EMC-UK (MHRA) — approved Midodrine SmPC: https://www.medicines.org.uk/emc/product/12040/smpc', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('cetirizina', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A cetirizina é excretada por via renal; na insuficiência grave a dose deve ser reduzida.', 'Cetirizine is renally excreted; in severe impairment the dose must be reduced.', 'Reduzir a dose (ex.: 5 mg/dia) em insuficiência renal grave.', 'Reduce the dose (e.g. 5 mg/day) in severe renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Cetirizina: https://www.medicines.org.uk/emc/product/3217/smpc', 'EMC-UK (MHRA) — approved Cetirizine SmPC: https://www.medicines.org.uk/emc/product/3217/smpc', 1),
  ('loratadina', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'precaution', 'moderate', 'O metabolismo hepático reduzido pode aumentar a exposição à loratadina.', 'Reduced hepatic metabolism may increase loratadine exposure.', 'Usar com precaução; dose inicial alternativa em insuficiência hepática grave.', 'Use with caution; alternative initial dose in severe hepatic impairment.', 'EMC-UK (MHRA) — SmPC aprovada Loratadina: https://www.medicines.org.uk/emc/product/10942/smpc', 'EMC-UK (MHRA) — approved Loratadine SmPC: https://www.medicines.org.uk/emc/product/10942/smpc', 1),
  ('desloratadina', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A desloratadina é eliminada por via renal.', 'Desloratadine is eliminated renally.', 'Usar com precaução e ajustar a dose em insuficiência renal grave.', 'Use with caution and adjust the dose in severe renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Desloratadina: https://www.medicines.org.uk/emc/product/14722/smpc', 'EMC-UK (MHRA) — approved Desloratadine SmPC: https://www.medicines.org.uk/emc/product/14722/smpc', 1),
  ('desloratadina', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'precaution', 'moderate', 'A eliminação reduzida pode aumentar a exposição.', 'Reduced elimination may increase exposure.', 'Usar com precaução.', 'Use with caution.', 'EMC-UK (MHRA) — SmPC aprovada Desloratadina: https://www.medicines.org.uk/emc/product/14722/smpc', 'EMC-UK (MHRA) — approved Desloratadine SmPC: https://www.medicines.org.uk/emc/product/14722/smpc', 1),
  ('fexofenadina', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A fexofenadina é eliminada por via renal.', 'Fexofenadine is renally eliminated.', 'Dose inicial recomendada de 60 mg uma vez por dia em insuficiência renal grave.', 'Recommended starting dose of 60 mg once daily in severe renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Fexofenadina: https://www.medicines.org.uk/emc/product/13208/smpc', 'EMC-UK (MHRA) — approved Fexofenadine SmPC: https://www.medicines.org.uk/emc/product/13208/smpc', 1),
  ('levocetirizina', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A levocetirizina é excretada por via renal; a dose deve ser ajustada.', 'Levocetirizine is renally excreted; the dose must be adjusted.', 'Ajustar a dose de acordo com a depuração de creatinina.', 'Adjust the dose according to creatinine clearance.', 'EMC-UK (MHRA) — SmPC aprovada Levocetirizina: https://www.medicines.org.uk/emc/product/9917/smpc', 'EMC-UK (MHRA) — approved Levocetirizine SmPC: https://www.medicines.org.uk/emc/product/9917/smpc', 1),
  ('difenidramina', 'glaucoma', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma', 'contraindication', 'critical', 'A difenidramina tem efeitos anticolinérgicos que podem precipitar glaucoma de ângulo fechado.', 'Diphenhydramine has anticholinergic effects that may precipitate angle-closure glaucoma.', 'Contraindicado em glaucoma de ângulo fechado não tratado.', 'Contraindicated in untreated angle-closure glaucoma.', 'EMC-UK (MHRA) — SmPC aprovada Difenidramina: https://www.medicines.org.uk/emc/product/1476/smpc', 'EMC-UK (MHRA) — approved Diphenhydramine SmPC: https://www.medicines.org.uk/emc/product/1476/smpc', 1),
  ('difenidramina', 'hipertrofia_prostatica', 'Hipertrofia prostática benigna', 'Benign prostatic hyperplasia', 'precaution', 'moderate', 'Os efeitos anticolinérgicos podem agravar a retenção urinária.', 'Anticholinergic effects may worsen urinary retention.', 'Usar com precaução em homens com hipertrofia prostática sintomática.', 'Use with caution in men with symptomatic prostatic hyperplasia.', 'EMC-UK (MHRA) — SmPC aprovada Difenidramina: https://www.medicines.org.uk/emc/product/1476/smpc', 'EMC-UK (MHRA) — approved Diphenhydramine SmPC: https://www.medicines.org.uk/emc/product/1476/smpc', 1),
  ('difenidramina', 'asma', 'Asma/DPOC (secreções espessas)', 'Asthma/COPD (thick secretions)', 'precaution', 'moderate', 'Os efeitos anticolinérgicos podem espessar as secreções e dificultar a expetoração.', 'Anticholinergic effects may thicken secretions and impair expectoration.', 'Usar com precaução em doentes com asma/DPOC.', 'Use with caution in patients with asthma/COPD.', 'EMC-UK (MHRA) — SmPC aprovada Difenidramina: https://www.medicines.org.uk/emc/product/1476/smpc', 'EMC-UK (MHRA) — approved Diphenhydramine SmPC: https://www.medicines.org.uk/emc/product/1476/smpc', 1),
  ('dexametasona', 'infeccao_ativa', 'Infeção ativa (incl. varicela/zona)', 'Active infection (incl. varicella/shingles)', 'contraindication', 'critical', 'Os corticosteroides podem mascarar e agravar infeções, incluindo varicela grave.', 'Corticosteroids may mask and worsen infections, including severe varicella.', 'Evitar em infeções sistémicas ativas sem antibioterapia.', 'Avoid in active systemic infections without antibiotic cover.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('dexametasona', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus', 'precaution', 'moderate', 'Os corticosteroides elevam a glicemia.', 'Corticosteroids raise blood glucose.', 'Monitorizar glicemia e ajustar antidiabéticos durante a terapêutica.', 'Monitor blood glucose and adjust antidiabetics during therapy.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('dexametasona', 'osteoporose', 'Osteoporose', 'Osteoporosis', 'precaution', 'moderate', 'O uso prolongado de corticosteroides acelera a perda óssea.', 'Long-term corticosteroids accelerate bone loss.', 'Usar a menor dose/duração; considerar cálcio + vitamina D.', 'Use the lowest dose/duration; consider calcium + vitamin D.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('dexametasona', 'glaucoma', 'Glaucoma', 'Glaucoma', 'precaution', 'moderate', 'Os corticosteroides podem elevar a pressão intraocular.', 'Corticosteroids may raise intraocular pressure.', 'Monitorizar pressão intraocular em terapêuticas prolongadas.', 'Monitor intraocular pressure on long-term therapy.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('dexametasona', 'hipertensao_arterial', 'Hipertensão arterial', 'Hypertension', 'precaution', 'moderate', 'Os corticosteroides podem reter sódio e líquidos e elevar a tensão arterial.', 'Corticosteroids may retain sodium and fluid and raise blood pressure.', 'Monitorizar tensão arterial e ajustar anti-hipertensores se necessário.', 'Monitor blood pressure and adjust antihypertensives if needed.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('dexametasona', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer', 'precaution', 'moderate', 'Os corticosteroides podem agravar úlcera péptica e o risco de hemorragia.', 'Corticosteroids may worsen peptic ulcer and bleeding risk.', 'Usar com precaução; considerar gastroprotecção.', 'Use with caution; consider gastroprotection.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc', 1),
  ('adrenalina', 'cardiopatia_isquemica', 'Cardiopatia isquémica', 'Ischaemic heart disease', 'precaution', 'moderate', 'A adrenalina aumenta o trabalho miocárdico e pode precipitar isquemia/arritmias.', 'Epinephrine increases myocardial work and may precipitate ischaemia/arrhythmias.', 'Usar com precaução em doentes com cardiopatia isquémica; monitorizar.', 'Use with caution in ischaemic heart disease; monitor.', 'EMC-UK (MHRA) — SmPC aprovada Adrenalina: https://www.medicines.org.uk/emc/product/3673/smpc', 'EMC-UK (MHRA) — approved Epinephrine SmPC: https://www.medicines.org.uk/emc/product/3673/smpc', 1),
  ('adrenalina', 'hipertiroidismo', 'Hipertiroidismo', 'Hyperthyroidism', 'precaution', 'moderate', 'O hipertiroidismo potencia os efeitos da adrenalina (taquicardia, arritmias).', 'Hyperthyroidism potentiates the effects of epinephrine (tachycardia, arrhythmias).', 'Usar com precaução e monitorizar sintomas cardiovasculares.', 'Use with caution and monitor cardiovascular symptoms.', 'EMC-UK (MHRA) — SmPC aprovada Adrenalina: https://www.medicines.org.uk/emc/product/3673/smpc', 'EMC-UK (MHRA) — approved Epinephrine SmPC: https://www.medicines.org.uk/emc/product/3673/smpc', 1),
  ('adrenalina', 'hipertensao_arterial_grave', 'Hipertensão arterial grave', 'Severe hypertension', 'precaution', 'moderate', 'A adrenalina pode elevar marcadamente a tensão arterial.', 'Epinephrine may markedly raise blood pressure.', 'Usar com precaução e monitorizar tensão arterial.', 'Use with caution and monitor blood pressure.', 'EMC-UK (MHRA) — SmPC aprovada Adrenalina: https://www.medicines.org.uk/emc/product/3673/smpc', 'EMC-UK (MHRA) — approved Epinephrine SmPC: https://www.medicines.org.uk/emc/product/3673/smpc', 1),
  ('pseudoefedrina', 'hipertensao_arterial_grave', 'Hipertensão arterial grave', 'Severe hypertension', 'contraindication', 'critical', 'A pseudoefedrina (α-agonista) pode elevar a tensão arterial de forma acentuada.', 'Pseudoephedrine (α-agonist) may markedly raise blood pressure.', 'Contraindicado em hipertensão grave não controlada.', 'Contraindicated in severe uncontrolled hypertension.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc', 1),
  ('pseudoefedrina', 'cardiopatia_isquemica', 'Cardiopatia isquémica', 'Ischaemic heart disease', 'contraindication', 'critical', 'A pseudoefedrina pode precipitar angina e arritmias em doentes com cardiopatia isquémica.', 'Pseudoephedrine may precipitate angina and arrhythmias in ischaemic heart disease.', 'Contraindicado em doença coronária ativa.', 'Contraindicated in active coronary disease.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc', 1),
  ('pseudoefedrina', 'hipertiroidismo', 'Hipertiroidismo', 'Hyperthyroidism', 'precaution', 'moderate', 'O hipertiroidismo potencia os efeitos simpaticomiméticos.', 'Hyperthyroidism potentiates sympathomimetic effects.', 'Usar com precaução; evitar em hipertiroidismo não controlado.', 'Use with caution; avoid in uncontrolled hyperthyroidism.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc', 1),
  ('pseudoefedrina', 'glaucoma', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma', 'contraindication', 'critical', 'A pseudoefedrina pode precipitar crise de glaucoma de ângulo fechado.', 'Pseudoephedrine may precipitate angle-closure glaucoma crisis.', 'Contraindicado em glaucoma de ângulo fechado.', 'Contraindicated in angle-closure glaucoma.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc', 1),
  ('montelukast', 'doenca_hepatica_ativa', 'Doença hepática ativa', 'Active liver disease', 'precaution', 'moderate', 'O montelucaste é metabolizado no fígado; usar com precaução em doença hepática.', 'Montelukast is hepatically metabolised; use with caution in liver disease.', 'Monitorizar função hepática em doentes com doença hepática.', 'Monitor liver function in patients with liver disease.', 'EMC-UK (MHRA) — SmPC aprovada Montelucaste: https://www.medicines.org.uk/emc/product/1222/smpc', 'EMC-UK (MHRA) — approved Montelukast SmPC: https://www.medicines.org.uk/emc/product/1222/smpc', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('cetirizina', 'compatible', 'A cetirizina é um dos anti-histamínicos de eleição na gravidez; não demonstrou teratogenicidade nos estudos disponíveis.', 'Cetirizine is one of the preferred antihistamines in pregnancy; available studies show no teratogenicity.', 'Pode ser usada em todos os trimestres quando indicado, na menor dose eficaz.', 'Can be used in all trimesters when indicated, at the lowest effective dose.', 'Excretada no leite materno em pequenas quantidades; compatível com o aleitamento.', 'Excreted into breast milk in small amounts; compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Cetirizina: https://www.medicines.org.uk/emc/product/3217/smpc', 'EMC-UK (MHRA) — approved Cetirizine SmPC: https://www.medicines.org.uk/emc/product/3217/smpc'),
  ('loratadina', 'compatible', 'A loratadina é considerada compatível na gravidez (grande experiência de uso).', 'Loratadine is considered compatible in pregnancy (extensive use experience).', 'Pode ser usada quando indicado, na menor dose eficaz.', 'Can be used when indicated, at the lowest effective dose.', 'Excretada no leite em pequenas quantidades; compatível.', 'Excreted into milk in small amounts; compatible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Loratadina: https://www.medicines.org.uk/emc/product/10942/smpc', 'EMC-UK (MHRA) — approved Loratadine SmPC: https://www.medicines.org.uk/emc/product/10942/smpc'),
  ('desloratadina', 'caution', 'Dados limitados na gravidez; metabolito ativo da loratadina.', 'Limited data in pregnancy; active loratadine metabolite.', 'Usar apenas se o benefício justificar o risco; preferir loratadina/cetirizina se disponíveis.', 'Use only if benefit justifies risk; prefer loratadine/cetirizine when available.', 'Dados limitados; preferir evitar durante a amamentação.', 'Limited data; prefer to avoid during breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Desloratadina: https://www.medicines.org.uk/emc/product/14722/smpc', 'EMC-UK (MHRA) — approved Desloratadine SmPC: https://www.medicines.org.uk/emc/product/14722/smpc'),
  ('fexofenadina', 'compatible', 'A fexofenadina (metabolito da terfenadina) não demonstrou teratogenicidade nos estudos disponíveis.', 'Fexofenadine (terfenadine metabolite) showed no teratogenicity in available studies.', 'Pode ser usada quando indicado, na menor dose eficaz.', 'Can be used when indicated, at the lowest effective dose.', 'Dados limitados na amamentação; considerar alternativa com mais dados.', 'Limited breastfeeding data; consider an alternative with more data.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Fexofenadina: https://www.medicines.org.uk/emc/product/13208/smpc', 'EMC-UK (MHRA) — approved Fexofenadine SmPC: https://www.medicines.org.uk/emc/product/13208/smpc'),
  ('levocetirizina', 'caution', 'Dados limitados na gravidez; enantiómero ativo da cetirizina.', 'Limited data in pregnancy; active cetirizine enantiomer.', 'Usar apenas se o benefício justificar o risco; preferir cetirizina se disponível.', 'Use only if benefit justifies risk; prefer cetirizine when available.', 'Dados limitados; preferir evitar durante a amamentação.', 'Limited data; prefer to avoid during breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Levocetirizina: https://www.medicines.org.uk/emc/product/9917/smpc', 'EMC-UK (MHRA) — approved Levocetirizine SmPC: https://www.medicines.org.uk/emc/product/9917/smpc'),
  ('difenidramina', 'caution', 'Uso ocasional geralmente considerado seguro; evitar doses elevadas próximo do termo (risco teórico de efeitos oxitócicos/neonatais).', 'Occasional use is generally considered safe; avoid high doses near term (theoretical risk of oxytocic/neonatal effects).', 'Usar a menor dose possível e por curta duração.', 'Use the lowest possible dose for a short duration.', 'Concentrações no leite baixas; uso ocasional compatível com vigilância do lactente.', 'Low milk levels; occasional use compatible with infant monitoring.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Difenidramina: https://www.medicines.org.uk/emc/product/1476/smpc', 'EMC-UK (MHRA) — approved Diphenhydramine SmPC: https://www.medicines.org.uk/emc/product/1476/smpc'),
  ('dexametasona', 'caution', 'Os corticosteroides atravessam a placenta; uso na gravidez apenas quando claramente indicado (ex.: maturação pulmonar fetal sob orientação).', 'Corticosteroids cross the placenta; use in pregnancy only when clearly indicated (e.g. fetal lung maturation under guidance).', 'Usar a menor dose eficaz e a mais curta duração.', 'Use the lowest effective dose for the shortest duration.', 'Baixas doses compatíveis com amamentação; doses elevadas: aguardar 3-4 h após a toma.', 'Low doses are compatible with breastfeeding; high doses: wait 3-4 h after dosing.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Dexametasona: https://www.medicines.org.uk/emc/product/13196/smpc', 'EMC-UK (MHRA) — approved Dexamethasone SmPC: https://www.medicines.org.uk/emc/product/13196/smpc'),
  ('adrenalina', 'caution', 'A adrenalina é usada em emergências (anafilaxia) na gravidez quando o benefício supera o risco; o risco de hipoperfusão materna/fetal não tratada é maior que o da exposição.', 'Epinephrine is used in emergencies (anaphylaxis) in pregnancy when benefit outweighs risk; the risk of untreated maternal/fetal hypoperfusion exceeds exposure risk.', 'Usar apenas em emergência sob orientação médica.', 'Use only in emergencies under medical guidance.', 'Não contraindica a amamentação após uso agudo.', 'Does not contraindicate breastfeeding after acute use.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Adrenalina: https://www.medicines.org.uk/emc/product/3673/smpc', 'EMC-UK (MHRA) — approved Epinephrine SmPC: https://www.medicines.org.uk/emc/product/3673/smpc'),
  ('pseudoefedrina', 'caution', 'Evitar no 1.º trimestre (dados limitados); usar a menor dose pelo menor tempo.', 'Avoid in the 1st trimester (limited data); use the lowest dose for the shortest time.', 'Usar apenas se claramente necessário e com precaução.', 'Use only if clearly necessary and with caution.', 'Dados limitados; preferir evitar durante a amamentação.', 'Limited data; prefer to avoid during breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Pseudoefedrina: https://www.medicines.org.uk/emc/product/8292/smpc', 'EMC-UK (MHRA) — approved Pseudoephedrine SmPC: https://www.medicines.org.uk/emc/product/8292/smpc')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;