-- ================================================================
-- 069_seed_interacoes_nutricao.sql
-- Secção 11 (Nutrição):
--   11.1 Nutrição entérica (glicose — fonte glucídica)
--   11.2 Nutrição parentérica (aminoácidos, emulsão lipídica)
--   11.3 Vitaminas e sais minerais (vitamina D3, ácido ascórbico,
--        carbonato de cálcio, cloreto de potássio, sulfato de
--        magnésio, sulfato de zinco)
-- Novos (9): glicose, aminoacidos, emulsao_lipidica, colecalciferol,
--            acido_ascorbico, carbonato_calcio, cloreto_potassio,
--            sulfato_magnesio, zinco.
-- Nota: ferro, ácido fólico, cianocobalamina (B12) e fitomenadiona
--       (vitamina K1) já foram criados na migração 064 (Hematologia).
-- Aplicar manualmente no Supabase (SQL editor). Idempotente (ON CONFLICT).
-- Fonte fármaco-fármaco: DailyMed (FDA) — setIDs validados na API.
-- Fonte 3 dimensões: EMC-UK (MHRA) canónico; fallback DailyMed (FDA).
-- ================================================================

-- ----------------------------------------------------------------
-- 1. Fármacos novos
-- ----------------------------------------------------------------
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order) VALUES
  ('glicose', 'Glicose (dextrose)', 'Glucose (dextrose)', 'Nutrição entérica (fonte glucídica)', 'Enteral nutrition (carbohydrate source)', ARRAY['dextrose', 'Glicose', 'glucose', 'Glucose 5%'], 'published', 168),
  ('aminoacidos', 'Aminoácidos', 'Amino acids', 'Nutrição parentérica (solução de aminoácidos)', 'Parenteral nutrition (amino acid solution)', ARRAY['aminoácidos', 'amino acids', 'Aminoplasmal', 'amino acids injection'], 'published', 169),
  ('emulsao_lipidica', 'Emulsão lipídica', 'Lipid emulsion', 'Nutrição parentérica (emulsão lipídica)', 'Parenteral nutrition (lipid emulsion)', ARRAY['Intralipid', 'Lipofundin', 'emulsão lipídica', 'lipid emulsion'], 'published', 170),
  ('colecalciferol', 'Colecalciferol (vitamina D3)', 'Cholecalciferol (vitamin D3)', 'Vitamina lipossolúvel (D3)', 'Fat-soluble vitamin (D3)', ARRAY['vitamina D3', 'vitamin D3', 'cholecalciferol', 'Desunin'], 'published', 171),
  ('acido_ascorbico', 'Ácido ascórbico (vitamina C)', 'Ascorbic acid (vitamin C)', 'Vitamina hidrossolúvel (C)', 'Water-soluble vitamin (C)', ARRAY['vitamina C', 'vitamin C', 'ascorbic acid', 'ascorbato'], 'published', 172),
  ('carbonato_calcio', 'Carbonato de cálcio', 'Calcium carbonate', 'Sais minerais (cálcio)', 'Mineral supplement (calcium)', ARRAY['cálcio', 'calcium', 'carbonato de cálcio', 'Adcal', 'Calcichew'], 'published', 173),
  ('cloreto_potassio', 'Cloreto de potássio', 'Potassium chloride', 'Eletrólito (potássio)', 'Electrolyte (potassium)', ARRAY['potássio', 'potassium', 'cloreto de potássio', 'Sando-K'], 'published', 174),
  ('sulfato_magnesio', 'Sulfato de magnésio', 'Magnesium sulfate', 'Eletrólito (magnésio)', 'Electrolyte (magnesium)', ARRAY['magnésio', 'magnesium', 'sulfato de magnésio', 'Epsom'], 'published', 175),
  ('zinco', 'Zinco (sulfato de zinco)', 'Zinc (zinc sulfate)', 'Oligoelemento (zinco)', 'Trace element (zinc)', ARRAY['sulfato de zinco', 'zinc sulfate', 'zinc', 'zinco'], 'published', 176);

-- ----------------------------------------------------------------
-- 2. Fármaco-fármaco (drug_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status)
SELECT LEAST(a.id, b.id), GREATEST(a.id, b.id), v.severity, v.summary_pt, v.summary_en,
       v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
       v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
       v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('ciprofloxacina', 'carbonato_calcio', 'moderate', 'Ciprofloxacina + cálcio: quelação que reduz a absorção da fluoroquinolona.', 'Ciprofloxacin + calcium: chelation reduces fluoroquinolone absorption.', 'Os catiões cálcio formam quelatos com a ciprofloxacina no trato digestivo, reduzindo a sua absorção oral.', 'Calcium cations chelate ciprofloxacin in the gut, reducing its oral absorption.', 'Separar as tomas de cálcio e de ciprofloxacina por pelo menos 2 horas.', 'Separate calcium and ciprofloxacin dosing by at least 2 hours.', 'Resposta clínica à antibioterapia.', 'Clinical response to antibiotic therapy.', 'Falência da terapêutica, infeção não resolvida.', 'Therapy failure, unresolved infection.', 'DailyMed (FDA) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('doxiciclina', 'carbonato_calcio', 'moderate', 'Doxiciclina + cálcio: quelação que reduz a absorção da tetraciclina.', 'Doxycycline + calcium: chelation reduces tetracycline absorption.', 'Os catiões cálcio formam quelatos com a doxiciclina, reduzindo a sua biodisponibilidade oral.', 'Calcium cations chelate doxycycline, reducing its oral bioavailability.', 'Separar as tomas por pelo menos 2 horas; dar a doxiciclina com água.', 'Separate dosing by at least 2 hours; give doxycycline with water.', 'Resposta clínica à antibioterapia.', 'Clinical response to antibiotic therapy.', 'Infeção não resolvida, febre persistente.', 'Unresolved infection, persistent fever.', 'DailyMed (FDA) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fe8cd3c6-36d6-4d92-bc5c-833cd6f9cb32 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fe8cd3c6-36d6-4d92-bc5c-833cd6f9cb32 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('digoxina', 'carbonato_calcio', 'moderate', 'Digoxina + cálcio: a hipercalcémia potencia a toxicidade digitálica.', 'Digoxin + calcium: hypercalcaemia potentiates digoxin toxicity.', 'O cálcio aumenta a contractilidade miocárdica e sensibiliza o coração à digoxina; a administração intravenosa de cálcio pode precipitar arritmias.', 'Calcium increases myocardial contractility and sensitises the heart to digoxin; intravenous calcium may precipitate arrhythmias.', 'Monitorizar o cálcio sérico e os sinais de toxicidade digitálica.', 'Monitor serum calcium and signs of digoxin toxicity.', 'Cálcio sérico, eletrocardiograma, sintomas de toxicidade digitálica.', 'Serum calcium, ECG, symptoms of digoxin toxicity.', 'Náuseas, arritmias, confusão, visão a cores alterada.', 'Nausea, arrhythmias, confusion, altered colour vision.', 'DailyMed (FDA) — rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('hidroclorotiazida', 'carbonato_calcio', 'moderate', 'Tiazida + cálcio: risco de hipercalcémia (a tiazida reduz a excreção renal de cálcio).', 'Thiazide + calcium: risk of hypercalcaemia (thiazide reduces renal calcium excretion).', 'A hidroclorotiazida diminui a eliminação renal de cálcio; com suplementos de cálcio pode surgir hipercalcémia.', 'Hydrochlorothiazide reduces renal calcium elimination; with calcium supplements hypercalcaemia may occur.', 'Monitorizar o cálcio sérico em doentes em suplementação crónica.', 'Monitor serum calcium in patients on chronic supplementation.', 'Cálcio sérico e sintomas de hipercalcémia.', 'Serum calcium and hypercalcaemia symptoms.', 'Poliúria, obstipação, fraqueza, confusão.', 'Polyuria, constipation, weakness, confusion.', 'DailyMed (FDA) — rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('calcitriol', 'carbonato_calcio', 'moderate', 'Calcitriol + cálcio: hipercalcémia aditiva (risco aumentado de toxicidade por vitamina D).', 'Calcitriol + calcium: additive hypercalcaemia (increased risk of vitamin D toxicity).', 'O calcitriol aumenta a absorção intestinal de cálcio; a associação com suplementos de cálcio eleva o cálcio sérico.', 'Calcitriol increases intestinal calcium absorption; combined with calcium supplements serum calcium rises.', 'Monitorizar cálcio sérico e fósforo; ajustar a suplementação.', 'Monitor serum calcium and phosphate; adjust supplementation.', 'Cálcio sérico (Ca × P) e sintomas de hipercalcémia.', 'Serum calcium (Ca × P) and hypercalcaemia symptoms.', 'Náuseas, obstipação, fraqueza, nefrolitíase.', 'Nausea, constipation, weakness, nephrolithiasis.', 'DailyMed (FDA) — rótulo aprovado Calcitriol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdcaffc6-e14e-4607-b77b-fc78a8382f60 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Calcitriol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdcaffc6-e14e-4607-b77b-fc78a8382f60 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('alendronato', 'carbonato_calcio', 'moderate', 'Alendronato + cálcio: o cálcio liga-se ao bisfosfonato e impede a sua absorção.', 'Alendronate + calcium: calcium binds the bisphosphonate and prevents its absorption.', 'Os sais de cálcio formam complexos insolúveis com o alendronato no estômago.', 'Calcium salts form insoluble complexes with alendronate in the stomach.', 'Tomar o alendronato 30-60 minutos antes do cálcio, de manhã em jejum.', 'Take alendronate 30-60 minutes before calcium, in the morning on an empty stomach.', 'Adesão e resposta à terapêutica da osteoporose.', 'Adherence and response to osteoporosis therapy.', 'Falta de eficácia (fraturas), sem outros sintomas agudos.', 'Lack of efficacy (fractures), no other acute symptoms.', 'DailyMed (FDA) — rótulo aprovado Alendronato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ffdd2496-d253-419b-85a6-8c615f7545f1 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Alendronate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ffdd2496-d253-419b-85a6-8c615f7545f1 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('levotiroxina', 'carbonato_calcio', 'moderate', 'Levotiroxina + cálcio: o cálcio reduz a absorção da levotiroxina.', 'Levothyroxine + calcium: calcium reduces levothyroxine absorption.', 'Os sais de cálcio ligam-se à levotiroxina no lúmen gastrointestinal.', 'Calcium salts bind levothyroxine in the gut lumen.', 'Separar a toma de levotiroxina e do cálcio por pelo menos 4 horas.', 'Separate levothyroxine and calcium dosing by at least 4 hours.', 'TSH após 6-8 semanas de qualquer alteração de dose.', 'TSH after 6-8 weeks of any dosing change.', 'Fadiga, ganho de peso, bradicardia (hipotiroidismo).', 'Fatigue, weight gain, bradycardia (hypothyroidism).', 'DailyMed (FDA) — rótulo aprovado Levotiroxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c8ae9dc4-836f-4912-80d7-684fd374f40a ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Levothyroxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c8ae9dc4-836f-4912-80d7-684fd374f40a ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ferro', 'carbonato_calcio', 'moderate', 'Ferro + cálcio: o cálcio inibe a absorção do ferro oral.', 'Iron + calcium: calcium inhibits oral iron absorption.', 'O cálcio compete com o ferro no transporte intestinal.', 'Calcium competes with iron for intestinal transport.', 'Separar as tomas de ferro e de cálcio por pelo menos 2 horas.', 'Separate iron and calcium dosing by at least 2 hours.', 'Resposta hematológica e adesão.', 'Haematological response and adherence.', 'Persistência da anemia ferropriva.', 'Persistent iron-deficiency anaemia.', 'DailyMed (FDA) — rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4e88a847-397b-4ddb-83d7-42c9b963a0b7 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4e88a847-397b-4ddb-83d7-42c9b963a0b7 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sucralfato', 'carbonato_calcio', 'moderate', 'Sucralfato + cálcio: o sucralfato liga-se ao cálcio, reduzindo a sua absorção.', 'Sucralfate + calcium: sucralfate binds calcium, reducing its absorption.', 'O sucralfato forma uma película que liga catiões (incluindo cálcio) no estômago.', 'Sucralfate forms a film that binds cations (including calcium) in the stomach.', 'Separar as tomas por pelo menos 2 horas.', 'Separate dosing by at least 2 hours.', 'Eficácia da suplementação de cálcio.', 'Effectiveness of calcium supplementation.', 'Sem sintomas agudos; risco de défice de cálcio com uso prolongado.', 'No acute symptoms; risk of calcium deficiency with long-term use.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('omeprazol', 'carbonato_calcio', 'moderate', 'IBP + cálcio: o omeprazol reduz a absorção do carbonato de cálcio.', 'PPI + calcium: omeprazole reduces calcium carbonate absorption.', 'O carbonato de cálcio precisa de ácido gástrico para se dissolver e ser absorvido; o omeprazol suprime a acidez.', 'Calcium carbonate requires gastric acid to dissolve and be absorbed; omeprazole suppresses acidity.', 'Em doentes a IBP, preferir citrato de cálcio ou ajustar a dose de cálcio.', 'In PPI patients, prefer calcium citrate or adjust the calcium dose.', 'Cálcio sérico e resposta clínica.', 'Serum calcium and clinical response.', 'Sem sintomas agudos; risco de défice com uso prolongado.', 'No acute symptoms; risk of deficiency with long-term use.', 'DailyMed (FDA) — rótulo aprovado Omeprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Omeprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=348d3dfa-6a52-4583-96e3-83c4bf2df45b — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('espironolactona', 'cloreto_potassio', 'critical', 'Espironolactona + potássio: risco de hipercaliemia grave.', 'Spironolactone + potassium: risk of severe hyperkalaemia.', 'A espironolactona (diurético poupador de potássio) reduz a excreção renal de K+; a suplementação aditiva pode causar hipercaliemia potencialmente fatal.', 'Spironolactone (potassium-sparing diuretic) reduces renal K+ excretion; additive supplementation may cause potentially fatal hyperkalaemia.', 'Evitar a associação; se inevitável, monitorizar o potássio frequentemente e suspender o suplemento.', 'Avoid the combination; if unavoidable, monitor potassium frequently and stop the supplement.', 'Potássio sérico, eletrocardiograma, função renal.', 'Serum potassium, ECG, renal function.', 'Fraqueza, arritmias, ondas T apiculadas, paragem cardíaca.', 'Weakness, arrhythmias, peaked T waves, cardiac arrest.', 'DailyMed (FDA) — rótulo aprovado Espironolactona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ac487ae2-e15f-4781-bae3-a03058cfcfe4 ; rótulo aprovado Cloreto de potássio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=eb56a807-ea94-4edb-9811-a04b19568468 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Spironolactone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ac487ae2-e15f-4781-bae3-a03058cfcfe4 ; approved Potassium chloride label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=eb56a807-ea94-4edb-9811-a04b19568468 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('enalapril', 'cloreto_potassio', 'moderate', 'IECA + potássio: risco de hipercaliemia (sobretudo em insuficiência renal ou diabetes).', 'ACE inhibitor + potassium: risk of hyperkalaemia (especially in renal impairment or diabetes).', 'Os IECAs reduzem a aldosterona e a excreção de K+; a suplementação de potássio adiciona o risco.', 'ACE inhibitors reduce aldosterone and K+ excretion; potassium supplementation adds risk.', 'Monitorizar o potássio sérico; usar suplementos de potássio com precaução.', 'Monitor serum potassium; use potassium supplements with caution.', 'Potássio sérico e função renal.', 'Serum potassium and renal function.', 'Fraqueza, parestesias, arritmias.', 'Weakness, paraesthesia, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Enalapril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f103b9f9-e081-419d-a2d8-b86acda834dd ; rótulo aprovado Cloreto de potássio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=eb56a807-ea94-4edb-9811-a04b19568468 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Enalapril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f103b9f9-e081-419d-a2d8-b86acda834dd ; approved Potassium chloride label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=eb56a807-ea94-4edb-9811-a04b19568468 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('digoxina', 'colecalciferol', 'moderate', 'Digoxina + vitamina D3: a hipercalcémia induzida pela vitamina D pode aumentar a toxicidade digitálica.', 'Digoxin + vitamin D3: vitamin D-induced hypercalcaemia may increase digoxin toxicity.', 'A vitamina D aumenta a absorção de cálcio; em doentes digitálicos a hipercalcémia sensibiliza o miocárdio.', 'Vitamin D increases calcium absorption; in digitalised patients hypercalcaemia sensitises the myocardium.', 'Monitorizar cálcio sérico e sinais de toxicidade digitálica, sobretudo com tiazidas em associação.', 'Monitor serum calcium and signs of digoxin toxicity, especially when thiazides are also used.', 'Cálcio sérico e eletrocardiograma.', 'Serum calcium and ECG.', 'Náuseas, arritmias, confusão.', 'Nausea, arrhythmias, confusion.', 'DailyMed (FDA) — rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 ; rótulo aprovado Colecalciferol (vitamina D3): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 ; approved Cholecalciferol (vitamin D3) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('hidroclorotiazida', 'colecalciferol', 'moderate', 'Tiazida + vitamina D3: hipercalcémia aditiva.', 'Thiazide + vitamin D3: additive hypercalcaemia.', 'A tiazida reduz a excreção de cálcio e a vitamina D aumenta a sua absorção; em conjunto elevam o cálcio sérico.', 'The thiazide reduces calcium excretion and vitamin D increases its absorption; together they raise serum calcium.', 'Monitorizar o cálcio sérico em suplementação prolongada.', 'Monitor serum calcium during prolonged supplementation.', 'Cálcio sérico.', 'Serum calcium.', 'Poliúria, obstipação, fraqueza.', 'Polyuria, constipation, weakness.', 'DailyMed (FDA) — rótulo aprovado Hidroclorotiazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 ; rótulo aprovado Colecalciferol (vitamina D3): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Hydrochlorothiazide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0789baef-3424-43ab-a3fb-4908172da565 ; approved Cholecalciferol (vitamin D3) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('calcitriol', 'colecalciferol', 'moderate', 'Calcitriol + colecalciferol: efeito vitamina D aditivo com risco de hipercalcémia.', 'Calcitriol + cholecalciferol: additive vitamin D effect with risk of hypercalcaemia.', 'Ambos aumentam o cálcio sérico; a associação pode exceder o limiar terapêutico.', 'Both raise serum calcium; the combination may exceed the therapeutic threshold.', 'Evitar a associação sem necessidade clínica; se usada, monitorizar cálcio.', 'Avoid the combination unless clinically needed; if used, monitor calcium.', 'Cálcio sérico (Ca × P).', 'Serum calcium (Ca × P).', 'Hipercalcémia sintomática (náuseas, confusão, nefrolitíase).', 'Symptomatic hypercalcaemia (nausea, confusion, nephrolithiasis).', 'DailyMed (FDA) — rótulo aprovado Calcitriol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdcaffc6-e14e-4607-b77b-fc78a8382f60 ; rótulo aprovado Colecalciferol (vitamina D3): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Calcitriol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cdcaffc6-e14e-4607-b77b-fc78a8382f60 ; approved Cholecalciferol (vitamin D3) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('carbamazepina', 'colecalciferol', 'moderate', 'Carbamazepina + vitamina D3: a carbamazepina acelera o metabolismo da vitamina D, com risco de deficiência.', 'Carbamazepine + vitamin D3: carbamazepine accelerates vitamin D metabolism, risking deficiency.', 'Os antiepiléticos indutores enzimáticos aumentam o catabolismo da vitamina D e do cálcio.', 'Enzyme-inducing antiepileptics increase vitamin D and calcium catabolism.', 'Considerar dose superior de vitamina D e monitorizar níveis/25(OH)D em doentes de risco.', 'Consider a higher vitamin D dose and monitor levels/25(OH)D in at-risk patients.', '25(OH)D, cálcio e densidade óssea em uso crónico.', '25(OH)D, calcium and bone density in chronic use.', 'Défice de vitamina D, osteomalacia, fraturas.', 'Vitamin D deficiency, osteomalacia, fractures.', 'DailyMed (FDA) — rótulo aprovado Carbamazepina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=97e6e175-75e8-437b-b457-ddb1ae4e857d ; rótulo aprovado Colecalciferol (vitamina D3): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Carbamazepine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=97e6e175-75e8-437b-b457-ddb1ae4e857d ; approved Cholecalciferol (vitamin D3) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('fenitoina', 'colecalciferol', 'moderate', 'Fenitoína + vitamina D3: a fenitoína aumenta o metabolismo da vitamina D.', 'Phenytoin + vitamin D3: phenytoin increases vitamin D metabolism.', 'A indução enzimática (CYP450) pela fenitoína acelera a degradação da vitamina D.', 'Phenytoin enzyme induction (CYP450) accelerates vitamin D degradation.', 'Monitorizar 25(OH)D em doentes de risco; suplementar se necessário.', 'Monitor 25(OH)D in at-risk patients; supplement if needed.', '25(OH)D e cálcio.', '25(OH)D and calcium.', 'Défice de vitamina D e alterações ósseas em uso crónico.', 'Vitamin D deficiency and bone changes in chronic use.', 'DailyMed (FDA) — rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; rótulo aprovado Colecalciferol (vitamina D3): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e ; approved Cholecalciferol (vitamin D3) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3822c324-e22a-4ac4-ac1c-9b63983b516a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('digoxina', 'sulfato_magnesio', 'moderate', 'Digoxina + magnésio: desequilíbrio eletrolítico com risco de arritmias.', 'Digoxin + magnesium: electrolyte imbalance with risk of arrhythmias.', 'A hipomagnesiemia aumenta a toxicidade digitálica; o sulfato de magnésio intravenoso é usado na toxicidade, mas exige monitorização cardíaca.', 'Hypomagnesaemia increases digoxin toxicity; intravenous magnesium sulfate is used in toxicity, but cardiac monitoring is required.', 'Monitorizar magnésio, potássio e ritmo cardíaco.', 'Monitor magnesium, potassium and heart rhythm.', 'Magnésio sérico e eletrocardiograma.', 'Serum magnesium and ECG.', 'Arritmias, fraqueza, tetania.', 'Arrhythmias, weakness, tetany.', 'DailyMed (FDA) — rótulo aprovado Digoxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 ; rótulo aprovado Sulfato de magnésio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Digoxin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967 ; approved Magnesium sulfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('salbutamol', 'sulfato_magnesio', 'moderate', 'Salbutamol + magnésio: hipocaliemia aditiva (o β2-agonista baixa o potássio).', 'Salbutamol + magnesium: additive hypokalaemia (the β2-agonist lowers potassium).', 'Os β2-agonistas causam entrada de K+ na célula; a associação com magnésio pode acentuar a hipocaliemia, sobretudo em doses elevadas.', 'β2-agonists cause K+ shift into cells; combined with magnesium, hypokalaemia may be accentuated, especially at high doses.', 'Monitorizar o potássio em doses elevadas ou uso prolongado.', 'Monitor potassium at high doses or with prolonged use.', 'Potássio sérico.', 'Serum potassium.', 'Fraqueza, cãibras, arritmias.', 'Weakness, cramps, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Salbutamol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d ; rótulo aprovado Sulfato de magnésio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Salbutamol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3236f82c-14e9-dfd4-e063-6294a90ac43d ; approved Magnesium sulfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('furosemida', 'sulfato_magnesio', 'moderate', 'Furosemida + magnésio: a furosemida aumenta a perda renal de magnésio.', 'Furosemide + magnesium: furosemide increases renal magnesium loss.', 'Os diuréticos de ansa aumentam a excreção urinária de magnésio; a suplementação corrige o défice, mas exige monitorização.', 'Loop diuretics increase urinary magnesium excretion; supplementation corrects the deficit but requires monitoring.', 'Monitorizar magnésio sérico durante a suplementação em doentes a diuréticos.', 'Monitor serum magnesium during supplementation in patients on diuretics.', 'Magnésio sérico e função renal.', 'Serum magnesium and renal function.', 'Fraqueza, cãibras, arritmias.', 'Weakness, cramps, arrhythmias.', 'DailyMed (FDA) — rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 ; rótulo aprovado Sulfato de magnésio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998 ; approved Magnesium sulfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ciprofloxacina', 'sulfato_magnesio', 'moderate', 'Ciprofloxacina + magnésio: quelação que reduz a absorção da fluoroquinolona.', 'Ciprofloxacin + magnesium: chelation reduces fluoroquinolone absorption.', 'Os catiões magnésio formam quelatos com a ciprofloxacina no intestino.', 'Magnesium cations chelate ciprofloxacin in the gut.', 'Separar as tomas por pelo menos 2 horas (via oral).', 'Separate oral dosing by at least 2 hours.', 'Resposta clínica à antibioterapia.', 'Clinical response to antibiotic therapy.', 'Falência da terapêutica.', 'Therapy failure.', 'DailyMed (FDA) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f ; rótulo aprovado Sulfato de magnésio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f ; approved Magnesium sulfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('gentamicina', 'sulfato_magnesio', 'moderate', 'Aminoglicosídeo + magnésio: risco de bloqueio neuromuscular e nefrotoxicidade aditiva.', 'Aminoglycoside + magnesium: risk of neuromuscular blockade and additive nephrotoxicity.', 'O sulfato de magnésio pode potenciar o bloqueio neuromuscular dos aminoglicosídeos; ambos podem afetar a função renal.', 'Magnesium sulfate may potentiate aminoglycoside neuromuscular blockade; both may affect renal function.', 'Monitorizar função renal e sinais de fraqueza muscular durante a administração conjunta.', 'Monitor renal function and signs of muscle weakness during co-administration.', 'Função renal, magnésio, sinais neurológicos.', 'Renal function, magnesium, neurological signs.', 'Fraqueza, depressão respiratória, aumento da creatinina.', 'Weakness, respiratory depression, rising creatinine.', 'DailyMed (FDA) — rótulo aprovado Gentamicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=977180b3-a222-4282-d485-4a3217674305 ; rótulo aprovado Sulfato de magnésio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Gentamicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=977180b3-a222-4282-d485-4a3217674305 ; approved Magnesium sulfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5a9f565-639c-4b22-b9e5-718bac7cfcf3 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ferro', 'acido_ascorbico', 'moderate', 'Ferro + vitamina C: a vitamina C aumenta a absorção do ferro oral.', 'Iron + vitamin C: vitamin C increases oral iron absorption.', 'O ácido ascórbico reduz o ferro férrico a ferroso e forma complexos solúveis, melhorando a absorção intestinal.', 'Ascorbic acid reduces ferric to ferrous iron and forms soluble complexes, improving intestinal absorption.', 'Associação favorável: pode permitir reduzir a dose de ferro; vigiar sobrecarga em doentes com risco.', 'Favourable combination: may allow a lower iron dose; watch for overload in at-risk patients.', 'Ferritina e hemoglobina.', 'Ferritin and haemoglobin.', 'Sinais de sobrecarga de ferro (raro com doses habituais).', 'Signs of iron overload (rare at usual doses).', 'DailyMed (FDA) — rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4e88a847-397b-4ddb-83d7-42c9b963a0b7 ; rótulo aprovado Ácido ascórbico (vitamina C): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1606e29f-0e80-4069-b688-daab9cbff20a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4e88a847-397b-4ddb-83d7-42c9b963a0b7 ; approved Ascorbic acid (vitamin C) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1606e29f-0e80-4069-b688-daab9cbff20a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('warfarina', 'acido_ascorbico', 'moderate', 'Varfarina + vitamina C (doses elevadas): possível alteração do INR.', 'Warfarin + vitamin C (high doses): possible INR change.', 'Doses muito elevadas de vitamina C podem interferir com a anticoagulação (mecanismo não totalmente esclarecido).', 'Very high vitamin C doses may interfere with anticoagulation (mechanism not fully clarified).', 'Evitar doses altas (>1 g/dia) sem monitorização; vigiar INR.', 'Avoid high doses (>1 g/day) without monitoring; check INR.', 'INR periódico.', 'Periodic INR.', 'Sinais de hemorragia ou trombose.', 'Signs of bleeding or thrombosis.', 'DailyMed (FDA) — rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 ; rótulo aprovado Ácido ascórbico (vitamina C): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1606e29f-0e80-4069-b688-daab9cbff20a — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 ; approved Ascorbic acid (vitamin C) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1606e29f-0e80-4069-b688-daab9cbff20a — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ciprofloxacina', 'zinco', 'moderate', 'Ciprofloxacina + zinco: quelação que reduz a absorção da fluoroquinolona.', 'Ciprofloxacin + zinc: chelation reduces fluoroquinolone absorption.', 'O zinco forma complexos com a ciprofloxacina no trato digestivo.', 'Zinc forms complexes with ciprofloxacin in the gut.', 'Separar as tomas por pelo menos 2 horas.', 'Separate dosing by at least 2 hours.', 'Resposta clínica à antibioterapia.', 'Clinical response to antibiotic therapy.', 'Falência da terapêutica, infeção não resolvida.', 'Therapy failure, unresolved infection.', 'DailyMed (FDA) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f ; rótulo aprovado Zinco (sulfato de zinco): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c527d138-e32c-418f-9573-a3d8a796279f ; approved Zinc (zinc sulfate) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('doxiciclina', 'zinco', 'moderate', 'Doxiciclina + zinco: quelação que reduz a absorção da tetraciclina.', 'Doxycycline + zinc: chelation reduces tetracycline absorption.', 'O zinco forma quelatos com a doxiciclina, reduzindo a sua biodisponibilidade.', 'Zinc chelates doxycycline, reducing its bioavailability.', 'Separar as tomas por pelo menos 2 horas.', 'Separate dosing by at least 2 hours.', 'Resposta clínica à antibioterapia.', 'Clinical response to antibiotic therapy.', 'Infeção não resolvida.', 'Unresolved infection.', 'DailyMed (FDA) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fe8cd3c6-36d6-4d92-bc5c-833cd6f9cb32 ; rótulo aprovado Zinco (sulfato de zinco): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fe8cd3c6-36d6-4d92-bc5c-833cd6f9cb32 ; approved Zinc (zinc sulfate) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('ferro', 'zinco', 'moderate', 'Ferro + zinco: competem pela absorção intestinal.', 'Iron + zinc: they compete for intestinal absorption.', 'O ferro e o zinco partilham mecanismos de transporte intestinal, reduzindo a absorção de ambos quando tomados juntos.', 'Iron and zinc share intestinal transport mechanisms, reducing absorption of both when taken together.', 'Separar as tomas por pelo menos 2 horas.', 'Separate dosing by at least 2 hours.', 'Resposta à suplementação.', 'Response to supplementation.', 'Persistência da deficiência apesar da suplementação.', 'Persistent deficiency despite supplementation.', 'DailyMed (FDA) — rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4e88a847-397b-4ddb-83d7-42c9b963a0b7 ; rótulo aprovado Zinco (sulfato de zinco): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4e88a847-397b-4ddb-83d7-42c9b963a0b7 ; approved Zinc (zinc sulfate) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('levotiroxina', 'zinco', 'moderate', 'Levotiroxina + zinco: o zinco pode reduzir a absorção da levotiroxina.', 'Levothyroxine + zinc: zinc may reduce levothyroxine absorption.', 'Os suplementos de zinco podem ligar-se à levotiroxina no intestino.', 'Zinc supplements may bind levothyroxine in the gut.', 'Separar as tomas por pelo menos 4 horas.', 'Separate dosing by at least 4 hours.', 'TSH após alterações de regime.', 'TSH after regimen changes.', 'Sinais de hipotiroidismo.', 'Signs of hypothyroidism.', 'DailyMed (FDA) — rótulo aprovado Levotiroxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c8ae9dc4-836f-4912-80d7-684fd374f40a ; rótulo aprovado Zinco (sulfato de zinco): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Levothyroxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c8ae9dc4-836f-4912-80d7-684fd374f40a ; approved Zinc (zinc sulfate) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('sucralfato', 'zinco', 'moderate', 'Sucralfato + zinco: o sucralfato liga-se ao zinco, reduzindo a sua absorção.', 'Sucralfate + zinc: sucralfate binds zinc, reducing its absorption.', 'A película de sucralfato liga catiões metálicos no estômago.', 'The sucralfate film binds metal cations in the stomach.', 'Separar as tomas por pelo menos 2 horas.', 'Separate dosing by at least 2 hours.', 'Eficácia da suplementação de zinco.', 'Effectiveness of zinc supplementation.', 'Sem sintomas agudos; défice com uso prolongado.', 'No acute symptoms; deficiency with long-term use.', 'DailyMed (FDA) — rótulo aprovado Sucralfato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; rótulo aprovado Zinco (sulfato de zinco): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Sucralfate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e781cc0-24ec-4028-8262-dcef9873ea1f ; approved Zinc (zinc sulfate) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bd646d2-2a2a-4376-8da0-c7f08b0511ac — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('warfarina', 'emulsao_lipidica', 'moderate', 'Varfarina + emulsão lipídica: a vitamina K dos lípidos pode reduzir o INR.', 'Warfarin + lipid emulsion: the vitamin K content of lipids may reduce INR.', 'As emulsões lipídicas contêm vitamina K, que antagoniza o efeito da varfarina.', 'Lipid emulsions contain vitamin K, which antagonises the warfarin effect.', 'Monitorizar o INR durante a nutrição parentérica com lípidos.', 'Monitor INR during parenteral nutrition with lipids.', 'INR periódico.', 'Periodic INR.', 'Sinais de trombose ou INR sub-terapêutico.', 'Signs of thrombosis or sub-therapeutic INR.', 'DailyMed (FDA) — rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 ; rótulo aprovado Emulsão lipídica: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61e025f1-a38e-4af2-9e18-13ea12977cf5 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057 ; approved Lipid emulsion label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=61e025f1-a38e-4af2-9e18-13ea12977cf5 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)'),
  ('dexametasona', 'glicose', 'moderate', 'Corticosteroide + glicose: hiperglicémia aditiva em doentes em nutrição.', 'Corticosteroid + glucose: additive hyperglycaemia in patients on nutrition.', 'Os corticosteroides aumentam a glicémia; a perfusão de glicose acrescenta carga glucídica.', 'Corticosteroids raise glycaemia; glucose infusion adds a carbohydrate load.', 'Monitorizar a glicemia e ajustar insulina/antidiabéticos durante a terapêutica.', 'Monitor blood glucose and adjust insulin/antidiabetics during therapy.', 'Glicemia capilar/sérica.', 'Capillary/serum glucose.', 'Hiperglicemia sintomática, descompensação metabólica.', 'Symptomatic hyperglycaemia, metabolic decompensation.', 'DailyMed (FDA) — rótulo aprovado Dexametasona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; rótulo aprovado Glicose (dextrose): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=36e9478c-5df0-4b47-b97d-de3626d7cb29 — referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)', 'DailyMed (FDA) — approved Dexamethasone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3 ; approved Glucose (dextrose) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=36e9478c-5df0-4b47-b97d-de3626d7cb29 — additional reference: Prontuário Terapêutico do INFARMED (11th ed., 2012)')
) AS v(slug_a, slug_b, severity, summary_pt, summary_en,
       mechanism_pt, mechanism_en, management_pt, management_en,
       monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
       source_pt, source_en)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- ----------------------------------------------------------------
-- 3. Alimento / Bebida (drug_food_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('glicose', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O álcool pode causar hipoglicemia e perturbar o controlo glicémico durante a nutrição.', 'Alcohol may cause hypoglycaemia and disturb glycaemic control during nutrition.', 'Evitar álcool durante a nutrição entérica/parentérica.', 'Avoid alcohol during enteral/parenteral nutrition.', 'EMC-UK (MHRA) — SmPC aprovada Glicose (dextrose): https://www.medicines.org.uk/emc/product/13132/smpc', 'EMC-UK (MHRA) — approved Glucose (dextrose) SmPC: https://www.medicines.org.uk/emc/product/13132/smpc', 1),
  ('glicose', 'alimentos', 'Alimentos', 'Food', 'minor', 'A carga glucídica alimentar soma-se à glicose administrada.', 'Dietary carbohydrate load adds to administered glucose.', 'Distribuir a ingestão de hidratos de carbono ao longo do dia.', 'Spread carbohydrate intake throughout the day.', 'EMC-UK (MHRA) — SmPC aprovada Glicose (dextrose): https://www.medicines.org.uk/emc/product/13132/smpc', 'EMC-UK (MHRA) — approved Glucose (dextrose) SmPC: https://www.medicines.org.uk/emc/product/13132/smpc', 1),
  ('aminoacidos', 'alimentos', 'Alimentos', 'Food', 'minor', 'A ingestão proteica oral deve ser considerada no total diário de aminoácidos.', 'Oral protein intake should be counted towards the daily amino acid total.', 'Ajustar o aporte de aminoácidos parentéricos à ingestão oral de proteínas.', 'Adjust parenteral amino acid provision to oral protein intake.', 'EMC-UK (MHRA) — SmPC aprovada Aminoácidos: https://www.medicines.org.uk/emc/product/15230/smpc', 'EMC-UK (MHRA) — approved Amino acids SmPC: https://www.medicines.org.uk/emc/product/15230/smpc', 1),
  ('emulsao_lipidica', 'alimentos', 'Alimentos', 'Food', 'minor', 'Os lípidos orais somam-se ao aporte lipídico da emulsão.', 'Oral lipids add to the lipid load of the emulsion.', 'Considerar a ingestão oral de gordura ao calcular a dose lipídica.', 'Consider oral fat intake when calculating the lipid dose.', 'EMC-UK (MHRA) — SmPC aprovada Emulsão lipídica: https://www.medicines.org.uk/emc/product/15164/smpc', 'EMC-UK (MHRA) — approved Lipid emulsion SmPC: https://www.medicines.org.uk/emc/product/15164/smpc', 1),
  ('colecalciferol', 'alimentos', 'Alimentos', 'Food', 'moderate', 'As refeições ricas em gordura aumentam a absorção do colecalciferol.', 'Fat-rich meals increase cholecalciferol absorption.', 'Tomar a vitamina D3 com a refeição principal.', 'Take vitamin D3 with the main meal.', 'EMC-UK (MHRA) — SmPC aprovada Colecalciferol (vitamina D3): https://www.medicines.org.uk/emc/product/7263/smpc', 'EMC-UK (MHRA) — approved Cholecalciferol (vitamin D3) SmPC: https://www.medicines.org.uk/emc/product/7263/smpc', 1),
  ('acido_ascorbico', 'alimentos', 'Alimentos', 'Food', 'minor', 'Tomar com alimentos reduz o desconforto gástrico da vitamina C.', 'Taking with food reduces vitamin C gastric discomfort.', 'Pode tomar com ou sem alimentos, conforme a tolerância.', 'May take with or without food, according to tolerance.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ascórbico (vitamina C): https://www.medicines.org.uk/emc/product/102185/smpc', 'EMC-UK (MHRA) — approved Ascorbic acid (vitamin C) SmPC: https://www.medicines.org.uk/emc/product/102185/smpc', 1),
  ('carbonato_calcio', 'alimentos', 'Alimentos', 'Food', 'moderate', 'A toma com alimentos (ácidos/citratos) melhora a absorção do carbonato de cálcio.', 'Taking with food (acids/citrates) improves calcium carbonate absorption.', 'Tomar o cálcio com a refeição para melhor absorção.', 'Take calcium with a meal for better absorption.', 'EMC-UK (MHRA) — SmPC aprovada Carbonato de cálcio: https://www.medicines.org.uk/emc/product/1295/smpc', 'EMC-UK (MHRA) — approved Calcium carbonate SmPC: https://www.medicines.org.uk/emc/product/1295/smpc', 1),
  ('carbonato_calcio', 'leite_lacticinios', 'Leite e lacticínios (cálcio)', 'Milk and dairy products (calcium)', 'moderate', 'Doses elevadas de cálcio com leite/lacticínios podem causar síndrome leite-álcali.', 'High calcium doses with milk/dairy may cause milk-alkali syndrome.', 'Evitar doses muito elevadas de cálcio juntamente com grandes quantidades de leite.', 'Avoid very high calcium doses together with large amounts of milk.', 'EMC-UK (MHRA) — SmPC aprovada Carbonato de cálcio: https://www.medicines.org.uk/emc/product/1295/smpc', 'EMC-UK (MHRA) — approved Calcium carbonate SmPC: https://www.medicines.org.uk/emc/product/1295/smpc', 1),
  ('cloreto_potassio', 'substitutos_sal', 'Substitutos de sal (cloreto de potássio)', 'Salt substitutes (potassium chloride)', 'moderate', 'Os substitutos de sal contêm cloreto de potássio e aumentam o aporte de K+.', 'Salt substitutes contain potassium chloride and increase K+ intake.', 'Avisar os doentes a suplementos de potássio para não usar substitutos de sal.', 'Advise patients on potassium supplements not to use salt substitutes.', 'EMC-UK (MHRA) — SmPC aprovada Cloreto de potássio: https://www.medicines.org.uk/emc/product/959/smpc', 'EMC-UK (MHRA) — approved Potassium chloride SmPC: https://www.medicines.org.uk/emc/product/959/smpc', 1),
  ('cloreto_potassio', 'alimentos_ricos_potassio', 'Alimentos ricos em potássio', 'Potassium-rich foods', 'moderate', 'Banana, espinafres e leguminosas adicionam potássio à suplementação.', 'Banana, spinach and pulses add potassium to supplementation.', 'Moderar alimentos ricos em potássio durante a suplementação, sobretudo em doentes de risco.', 'Moderate potassium-rich foods during supplementation, especially in at-risk patients.', 'EMC-UK (MHRA) — SmPC aprovada Cloreto de potássio: https://www.medicines.org.uk/emc/product/959/smpc', 'EMC-UK (MHRA) — approved Potassium chloride SmPC: https://www.medicines.org.uk/emc/product/959/smpc', 1),
  ('sulfato_magnesio', 'alcool', 'Álcool', 'Alcohol', 'minor', 'O consumo crónico de álcool aumenta a perda renal de magnésio.', 'Chronic alcohol use increases renal magnesium loss.', 'Moderar o consumo de álcool durante a suplementação de magnésio.', 'Moderate alcohol intake during magnesium supplementation.', 'EMC-UK (MHRA) — SmPC aprovada Sulfato de magnésio: https://www.medicines.org.uk/emc/product/10502/smpc', 'EMC-UK (MHRA) — approved Magnesium sulfate SmPC: https://www.medicines.org.uk/emc/product/10502/smpc', 1),
  ('zinco', 'cafe_cha', 'Café, chá e outras bebidas com taninos', 'Coffee, tea and tannin-containing drinks', 'minor', 'Os taninos do chá e do café reduzem a absorção do zinco.', 'Tannins in tea and coffee reduce zinc absorption.', 'Separar a toma de zinco das bebidas com taninos por 1-2 horas.', 'Separate zinc dosing from tannin-containing drinks by 1-2 hours.', 'EMC-UK (MHRA) — SmPC aprovada Zinco (sulfato de zinco): https://www.medicines.org.uk/emc/product/4930/smpc', 'EMC-UK (MHRA) — approved Zinc (zinc sulfate) SmPC: https://www.medicines.org.uk/emc/product/4930/smpc', 1),
  ('zinco', 'alimentos', 'Alimentos (fitatos dos cereais)', 'Food (cereal phytates)', 'minor', 'Os fitatos dos cereais integrais reduzem a absorção do zinco.', 'Wholegrain phytates reduce zinc absorption.', 'Tomar o zinco entre refeições ou separado dos cereais integrais.', 'Take zinc between meals or away from wholegrains.', 'EMC-UK (MHRA) — SmPC aprovada Zinco (sulfato de zinco): https://www.medicines.org.uk/emc/product/4930/smpc', 'EMC-UK (MHRA) — approved Zinc (zinc sulfate) SmPC: https://www.medicines.org.uk/emc/product/4930/smpc', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 4. Doença / Condição (drug_disease_interactions)
-- ----------------------------------------------------------------
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('glicose', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus', 'precaution', 'moderate', 'A administração de glicose eleva a glicemia, exigindo ajuste da terapêutica antidiabética.', 'Glucose administration raises glycaemia, requiring adjustment of antidiabetic therapy.', 'Monitorizar glicemia e ajustar insulina/antidiabéticos durante a nutrição.', 'Monitor glucose and adjust insulin/antidiabetics during nutrition.', 'EMC-UK (MHRA) — SmPC aprovada Glicose (dextrose): https://www.medicines.org.uk/emc/product/13132/smpc', 'EMC-UK (MHRA) — approved Glucose (dextrose) SmPC: https://www.medicines.org.uk/emc/product/13132/smpc', 1),
  ('aminoacidos', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'A carga proteica dos aminoácidos pode agravar a uremia na insuficiência renal grave.', 'The protein load of amino acids may worsen uraemia in severe renal impairment.', 'Ajustar o aporte de aminoácidos à função renal; considerar aminoácidos essenciais.', 'Adjust amino acid provision to renal function; consider essential amino acids.', 'EMC-UK (MHRA) — SmPC aprovada Aminoácidos: https://www.medicines.org.uk/emc/product/15230/smpc', 'EMC-UK (MHRA) — approved Amino acids SmPC: https://www.medicines.org.uk/emc/product/15230/smpc', 1),
  ('aminoacidos', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'precaution', 'moderate', 'O aporte proteico pode precipitar encefalopatia hepática.', 'Protein provision may precipitate hepatic encephalopathy.', 'Usar com precaução e monitorizar o estado neurológico.', 'Use with caution and monitor neurological status.', 'EMC-UK (MHRA) — SmPC aprovada Aminoácidos: https://www.medicines.org.uk/emc/product/15230/smpc', 'EMC-UK (MHRA) — approved Amino acids SmPC: https://www.medicines.org.uk/emc/product/15230/smpc', 1),
  ('emulsao_lipidica', 'hipertrigliceridemia', 'Hipertrigliceridemia grave', 'Severe hypertriglyceridaemia', 'contraindication', 'critical', 'A emulsão lipídica agrava a hipertrigliceridemia e pode precipitar pancreatite.', 'Lipid emulsion worsens hypertriglyceridaemia and may precipitate pancreatitis.', 'Contraindicada em hipertrigliceridemia grave não controlada.', 'Contraindicated in severe uncontrolled hypertriglyceridaemia.', 'EMC-UK (MHRA) — SmPC aprovada Emulsão lipídica: https://www.medicines.org.uk/emc/product/15164/smpc', 'EMC-UK (MHRA) — approved Lipid emulsion SmPC: https://www.medicines.org.uk/emc/product/15164/smpc', 1),
  ('emulsao_lipidica', 'pancreatite', 'Pancreatite (associada a lípidos)', 'Pancreatitis (lipid-associated)', 'precaution', 'moderate', 'Em doentes com pancreatite, a perfusão lipídica deve ser prudente.', 'In pancreatitis patients, lipid infusion should be cautious.', 'Usar com precaução e monitorizar triglicéridos.', 'Use with caution and monitor triglycerides.', 'EMC-UK (MHRA) — SmPC aprovada Emulsão lipídica: https://www.medicines.org.uk/emc/product/15164/smpc', 'EMC-UK (MHRA) — approved Lipid emulsion SmPC: https://www.medicines.org.uk/emc/product/15164/smpc', 1),
  ('colecalciferol', 'hipercalcemia', 'Hipercalcémia', 'Hypercalcaemia', 'contraindication', 'critical', 'A vitamina D3 aumenta a absorção de cálcio e pode agravar a hipercalcémia.', 'Vitamin D3 increases calcium absorption and may worsen hypercalcaemia.', 'Contraindicado em hipercalcémia não corrigida.', 'Contraindicated in uncorrected hypercalcaemia.', 'EMC-UK (MHRA) — SmPC aprovada Colecalciferol (vitamina D3): https://www.medicines.org.uk/emc/product/7263/smpc', 'EMC-UK (MHRA) — approved Cholecalciferol (vitamin D3) SmPC: https://www.medicines.org.uk/emc/product/7263/smpc', 1),
  ('colecalciferol', 'sarcoidose', 'Sarcoidose', 'Sarcoidosis', 'precaution', 'moderate', 'Na sarcoidose há produção extra-renal de calcitriol, aumentando o risco de hipercalcémia.', 'In sarcoidosis there is extra-renal calcitriol production, increasing hypercalcaemia risk.', 'Usar com precaução e monitorizar o cálcio sérico.', 'Use with caution and monitor serum calcium.', 'EMC-UK (MHRA) — SmPC aprovada Colecalciferol (vitamina D3): https://www.medicines.org.uk/emc/product/7263/smpc', 'EMC-UK (MHRA) — approved Cholecalciferol (vitamin D3) SmPC: https://www.medicines.org.uk/emc/product/7263/smpc', 1),
  ('acido_ascorbico', 'nefrolitiase', 'Nefrolitíase (litíase oxálica)', 'Nephrolithiasis (oxalate stones)', 'precaution', 'moderate', 'Doses elevadas de vitamina C aumentam a excreção de oxalato e o risco de litíase.', 'High vitamin C doses increase oxalate excretion and stone risk.', 'Evitar doses elevadas em doentes com litíase oxálica recorrente.', 'Avoid high doses in patients with recurrent oxalate stones.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ascórbico (vitamina C): https://www.medicines.org.uk/emc/product/102185/smpc', 'EMC-UK (MHRA) — approved Ascorbic acid (vitamin C) SmPC: https://www.medicines.org.uk/emc/product/102185/smpc', 1),
  ('acido_ascorbico', 'hemocromatose', 'Hemocromatose / sobrecarga de ferro', 'Haemochromatosis / iron overload', 'precaution', 'moderate', 'A vitamina C aumenta a absorção de ferro, podendo agravar a sobrecarga férrica.', 'Vitamin C increases iron absorption, which may worsen iron overload.', 'Usar com precaução em doentes com sobrecarga de ferro.', 'Use with caution in patients with iron overload.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ascórbico (vitamina C): https://www.medicines.org.uk/emc/product/102185/smpc', 'EMC-UK (MHRA) — approved Ascorbic acid (vitamin C) SmPC: https://www.medicines.org.uk/emc/product/102185/smpc', 1),
  ('carbonato_calcio', 'hipercalcemia', 'Hipercalcémia', 'Hypercalcaemia', 'contraindication', 'critical', 'A suplementação de cálcio agrava a hipercalcémia.', 'Calcium supplementation worsens hypercalcaemia.', 'Contraindicado em hipercalcémia não corrigida.', 'Contraindicated in uncorrected hypercalcaemia.', 'EMC-UK (MHRA) — SmPC aprovada Carbonato de cálcio: https://www.medicines.org.uk/emc/product/1295/smpc', 'EMC-UK (MHRA) — approved Calcium carbonate SmPC: https://www.medicines.org.uk/emc/product/1295/smpc', 1),
  ('carbonato_calcio', 'nefrolitiase', 'Nefrolitíase', 'Nephrolithiasis', 'precaution', 'moderate', 'O excesso de cálcio urinário aumenta o risco de litíase renal.', 'Excess urinary calcium increases the risk of renal stones.', 'Monitorizar a calciúria em doentes com história de litíase.', 'Monitor urine calcium in patients with a history of stones.', 'EMC-UK (MHRA) — SmPC aprovada Carbonato de cálcio: https://www.medicines.org.uk/emc/product/1295/smpc', 'EMC-UK (MHRA) — approved Calcium carbonate SmPC: https://www.medicines.org.uk/emc/product/1295/smpc', 1),
  ('cloreto_potassio', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'contraindication', 'critical', 'A excreção renal de potássio está reduzida, com risco de hipercaliemia.', 'Renal potassium excretion is reduced, risking hyperkalaemia.', 'Evitar suplementos de potássio na insuficiência renal grave sem monitorização.', 'Avoid potassium supplements in severe renal impairment without monitoring.', 'EMC-UK (MHRA) — SmPC aprovada Cloreto de potássio: https://www.medicines.org.uk/emc/product/959/smpc', 'EMC-UK (MHRA) — approved Potassium chloride SmPC: https://www.medicines.org.uk/emc/product/959/smpc', 1),
  ('cloreto_potassio', 'hipercaliemia', 'Hipercaliemia', 'Hyperkalaemia', 'precaution', 'moderate', 'A suplementação agrava a hipercaliemia pré-existente.', 'Supplementation worsens pre-existing hyperkalaemia.', 'Monitorizar o potássio sérico e suspender se necessário.', 'Monitor serum potassium and stop if needed.', 'EMC-UK (MHRA) — SmPC aprovada Cloreto de potássio: https://www.medicines.org.uk/emc/product/959/smpc', 'EMC-UK (MHRA) — approved Potassium chloride SmPC: https://www.medicines.org.uk/emc/product/959/smpc', 1),
  ('sulfato_magnesio', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'O magnésio acumula-se na insuficiência renal, com risco de hipermagnesiemia.', 'Magnesium accumulates in renal impairment, risking hypermagnesaemia.', 'Usar com precaução e monitorizar o magnésio sérico.', 'Use with caution and monitor serum magnesium.', 'EMC-UK (MHRA) — SmPC aprovada Sulfato de magnésio: https://www.medicines.org.uk/emc/product/10502/smpc', 'EMC-UK (MHRA) — approved Magnesium sulfate SmPC: https://www.medicines.org.uk/emc/product/10502/smpc', 1),
  ('sulfato_magnesio', 'miastenia_gravis', 'Miastenia gravis', 'Myasthenia gravis', 'precaution', 'moderate', 'O magnésio pode agravar a fraqueza neuromuscular na miastenia.', 'Magnesium may worsen neuromuscular weakness in myasthenia.', 'Usar com precaução, sobretudo por via intravenosa, e vigiar a força muscular.', 'Use with caution, especially intravenously, and watch muscle strength.', 'EMC-UK (MHRA) — SmPC aprovada Sulfato de magnésio: https://www.medicines.org.uk/emc/product/10502/smpc', 'EMC-UK (MHRA) — approved Magnesium sulfate SmPC: https://www.medicines.org.uk/emc/product/10502/smpc', 1),
  ('zinco', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate', 'O zinco pode acumular-se na insuficiência renal grave.', 'Zinc may accumulate in severe renal impairment.', 'Usar com precaução em doentes com insuficiência renal grave.', 'Use with caution in patients with severe renal impairment.', 'EMC-UK (MHRA) — SmPC aprovada Zinco (sulfato de zinco): https://www.medicines.org.uk/emc/product/4930/smpc', 'EMC-UK (MHRA) — approved Zinc (zinc sulfate) SmPC: https://www.medicines.org.uk/emc/product/4930/smpc', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- ----------------------------------------------------------------
-- 5. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- ----------------------------------------------------------------
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('glicose', 'compatible', 'A glicose é um nutriente essencial; as soluções de glicose são usadas na gravidez com monitorização glicémica.', 'Glucose is an essential nutrient; glucose solutions are used in pregnancy with glycaemic monitoring.', 'Monitorizar a glicemia, sobretudo em diabetes gestacional.', 'Monitor blood glucose, especially in gestational diabetes.', 'Compatível com a amamentação.', 'Compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Glicose (dextrose): https://www.medicines.org.uk/emc/product/13132/smpc', 'EMC-UK (MHRA) — approved Glucose (dextrose) SmPC: https://www.medicines.org.uk/emc/product/13132/smpc'),
  ('aminoacidos', 'caution', 'As soluções de aminoácidos para nutrição parentérica só devem ser usadas quando o benefício supera o risco.', 'Amino acid solutions for parenteral nutrition should only be used when benefit outweighs risk.', 'Usar sob orientação especializada com monitorização metabólica.', 'Use under specialist guidance with metabolic monitoring.', 'Dados limitados; preferir nutrição entérica quando possível.', 'Limited data; prefer enteral nutrition when possible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Aminoácidos: https://www.medicines.org.uk/emc/product/15230/smpc', 'EMC-UK (MHRA) — approved Amino acids SmPC: https://www.medicines.org.uk/emc/product/15230/smpc'),
  ('emulsao_lipidica', 'caution', 'A emulsão lipídica intravenosa só deve ser usada quando a nutrição entérica não é possível.', 'Intravenous lipid emulsion should only be used when enteral nutrition is not possible.', 'Usar sob orientação especializada, monitorizando triglicéridos.', 'Use under specialist guidance, monitoring triglycerides.', 'Dados limitados; preferir nutrição entérica quando possível.', 'Limited data; prefer enteral nutrition when possible.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Emulsão lipídica: https://www.medicines.org.uk/emc/product/15164/smpc', 'EMC-UK (MHRA) — approved Lipid emulsion SmPC: https://www.medicines.org.uk/emc/product/15164/smpc'),
  ('colecalciferol', 'compatible', 'A vitamina D3 em doses fisiológicas é recomendada na gravidez.', 'Physiological doses of vitamin D3 are recommended in pregnancy.', 'Evitar doses muito elevadas; usar as doses recomendadas (600-800 UI/dia, ou conforme prescrição).', 'Avoid very high doses; use recommended doses (600-800 IU/day, or as prescribed).', 'Compatível com a amamentação nas doses fisiológicas.', 'Compatible with breastfeeding at physiological doses.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Colecalciferol (vitamina D3): https://www.medicines.org.uk/emc/product/7263/smpc', 'EMC-UK (MHRA) — approved Cholecalciferol (vitamin D3) SmPC: https://www.medicines.org.uk/emc/product/7263/smpc'),
  ('acido_ascorbico', 'compatible', 'A vitamina C nas doses recomendadas é segura na gravidez.', 'Vitamin C at recommended doses is safe in pregnancy.', 'Usar as doses recomendadas; evitar megadoses.', 'Use recommended doses; avoid megadoses.', 'Compatível com a amamentação.', 'Compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Ácido ascórbico (vitamina C): https://www.medicines.org.uk/emc/product/102185/smpc', 'EMC-UK (MHRA) — approved Ascorbic acid (vitamin C) SmPC: https://www.medicines.org.uk/emc/product/102185/smpc'),
  ('carbonato_calcio', 'compatible', 'O cálcio é essencial na gravidez; a suplementação é segura nas doses recomendadas.', 'Calcium is essential in pregnancy; supplementation is safe at recommended doses.', 'Usar as doses recomendadas (cerca de 1000 mg/dia).', 'Use recommended doses (about 1000 mg/day).', 'Compatível com a amamentação.', 'Compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Carbonato de cálcio: https://www.medicines.org.uk/emc/product/1295/smpc', 'EMC-UK (MHRA) — approved Calcium carbonate SmPC: https://www.medicines.org.uk/emc/product/1295/smpc'),
  ('cloreto_potassio', 'compatible', 'A manutenção da normocaliemia é importante na gravidez; a suplementação é segura quando indicada.', 'Maintaining normokalaemia is important in pregnancy; supplementation is safe when indicated.', 'Repor o potássio apenas quando indicado, com monitorização.', 'Replace potassium only when indicated, with monitoring.', 'Compatível com a amamentação.', 'Compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Cloreto de potássio: https://www.medicines.org.uk/emc/product/959/smpc', 'EMC-UK (MHRA) — approved Potassium chloride SmPC: https://www.medicines.org.uk/emc/product/959/smpc'),
  ('sulfato_magnesio', 'caution', 'O sulfato de magnésio é usado na gravidez (pré-eclâmpsia/eclâmpsia) apenas sob vigilância clínica.', 'Magnesium sulfate is used in pregnancy (pre-eclampsia/eclampsia) only under clinical supervision.', 'Usar apenas sob indicação e monitorização hospitalar.', 'Use only on indication with hospital monitoring.', 'Dados limitados na amamentação; usar com precaução.', 'Limited data in breastfeeding; use with caution.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Sulfato de magnésio: https://www.medicines.org.uk/emc/product/10502/smpc', 'EMC-UK (MHRA) — approved Magnesium sulfate SmPC: https://www.medicines.org.uk/emc/product/10502/smpc'),
  ('zinco', 'compatible', 'O zinco nas doses recomendadas é seguro na gravidez.', 'Zinc at recommended doses is safe in pregnancy.', 'Usar as doses recomendadas (cerca de 11 mg/dia).', 'Use recommended doses (about 11 mg/day).', 'Compatível com a amamentação.', 'Compatible with breastfeeding.', 'Sem contraceção adicional específica.', 'No specific additional contraception.', 'EMC-UK (MHRA) — SmPC aprovada Zinco (sulfato de zinco): https://www.medicines.org.uk/emc/product/4930/smpc', 'EMC-UK (MHRA) — approved Zinc (zinc sulfate) SmPC: https://www.medicines.org.uk/emc/product/4930/smpc')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;