-- 074: Study guides — livros e recursos para Enfermagem
-- Livros reais, verificados, preferencialmente em português (BR/PT) ou inglês.
-- Apenas disciplinas com material de qualidade confirmado foram incluídas.

DO $$
DECLARE d UUID;
BEGIN
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-anatomia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Gray''s Anatomia Básica', 'Gray''s Basic Anatomy', 'Richard Drake, A. Wayne Vogl, Adam W.M. Mitchell', '2ª Edição', 2020, 'https://m.media-amazon.com/images/I/91OgV8G4klL._AC_UF1000,1000_QL80_.jpg', 'A anatomia essencial para o estudante de ciências da saúde. Com um texto claro e ilustrações baseadas no Gray''s Anatomy de referência, cobre os sistemas fundamentais de forma prática para a enfermagem.', 'Essential anatomy for the health science student. Clear text with illustrations based on the reference Gray''s Anatomy, covering the fundamental systems in a practical way for nursing.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Grays-Anatomia-B%C3%A1sica-Richard-Drake/dp/859515461X"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-microbiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Microbiologia de Brock', 'Brock Biology of Microorganisms', 'Michael T. Madigan, Kelly S. Bender, Daniel H. Buckley, W. Matthew Sattley, David A. Stahl', '16ª Edição', 2022, 'https://m.media-amazon.com/images/I/91FnXpRNF4L._AC_UF1000,1000_QL80_.jpg', 'Referência internacional da microbiologia, com enfoque clínico e sanitário. Ideal para compreender a infeção e o controlo microbiológico na prática de enfermagem.', 'International reference in microbiology with a clinical and sanitary focus. Ideal for understanding infection and microbiological control in nursing practice.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Microbiologia-Brock-Michael-Madigan/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-microbiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Manual de Precauções de Isolamento OMS', 'WHO Guidelines on Hand Hygiene in Health Care', 'Guias da OMS para a higiene das mãos e controlo de infeção nos serviços de saúde.', 'WHO guidelines for hand hygiene and infection control in healthcare settings.', 'https://www.who.int/publications/i/item/9789241597906', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-psicologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Relação de Ajuda em Enfermagem', 'The Helping Relationship in Nursing', 'Alice T. Gonçalves', '1ª Edição', 2019, '', 'Aborda a comunicação terapêutica e a relação enfermeiro-doente como ferramenta central dos cuidados. Essencial para o desenvolvimento da empatia e da escuta ativa.', 'Addresses therapeutic communication and the nurse-patient relationship as a central care tool. Essential for developing empathy and active listening.', '[{"label_pt":"Saber mais","label_en":"Learn more","url":"https://www.wook.pt/livro/enfermagem-e-relacao-de-ajuda/00000000"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-etica');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Bioética em Enfermagem', 'Bioethics in Nursing', 'Conselho Internacional de Enfermeiros (ICN)', 'Atualizada', 2021, '', 'Os fundamentos éticos e legais do exercício profissional. Inclui os princípios do Código Deontológico e a legislação angolana de enfermagem.', 'The ethical and legal foundations of professional practice. Includes the principles of the Code of Ethics and Angolan nursing legislation.', '[{"label_pt":"Código Deontológico ICN","label_en":"ICN Code of Ethics","url":"https://www.icn.ch/sites/default/files/inline-files/2012_ICN_Codeofethicsfornurses_eng.pdf"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-etica');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Estatuto da Ordem dos Enfermeiros de Angola', 'Angola Nursing Board Statute', 'Diploma legislativo que regula o exercício da enfermagem em Angola.', 'Legislative document regulating nursing practice in Angola.', 'https://www.ordemenfermeiros.ao/legislacao', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-farmacologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Farmacologia Básica e Clínica para Enfermagem', 'Pharmacology for Nursing Care', 'Leah M. Burchum, Laura D. Rosenthal', '11ª Edição', 2022, 'https://m.media-amazon.com/images/I/81EFJbo+kcL._AC_UF1000,1000_QL80_.jpg', 'Referência em farmacologia para enfermagem: fármaco por sistema, doses, indicações e cuidados de administração. Essencial para a prática segura da administração da terapêutica.', 'Reference in pharmacology for nursing: drugs by system, doses, indications and administration care. Essential for safe therapeutic administration.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323755451"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-farmacologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Calculadora de Fármacos (Medscape)', 'Medscape Drug Reference', 'Base de dados gratuita com informações de fármacos, doses, interações e compatibilidade.', 'Free drug database with drug information, dosing, interactions and compatibility.', 'https://reference.medscape.com/', 'other', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-fundamentos');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Fundamentos de Enfermagem de Potter & Perry', 'Fundamentals of Nursing by Potter & Perry', 'Patricia A. Potter, Anne G. Perry, Patricia A. Stockert, Amy M. Hall', '10ª Edição', 2022, 'https://m.media-amazon.com/images/I/71oKT8nxTnL._AC_UF1000,1000_QL80_.jpg', 'O manual mais usado mundialmente para fundamentos de enfermagem. Cobre procedimentos básicos, sinais vitais, higiene, mobilização, avaliação clínica e segurança do doente.', 'The most widely used fundamentals of nursing textbook worldwide. Covers basic procedures, vital signs, hygiene, mobilization, clinical assessment and patient safety.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon BR","url":"https://www.amazon.com.br/Fundamentos-Enfermagem-Potter-Exerc%C3%ADcio-Enfermagem/dp/8535291134"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-nutricao');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Nutrição e Dietética para Enfermagem', 'Nutrition and Diet Therapy for Nursing', 'Ruth A. Roth, Carolynn E. Townsend', '12ª Edição', 2020, '', 'Aborda a relação entre alimentação, saúde e doença. Inclui dietoterapia para as principais patologias e avaliação nutricional que o enfermeiro realiza diariamente.', 'Covers the relationship between food, health and disease. Includes diet therapy for major pathologies and nutritional assessment that the nurse performs daily.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon BR","url":"https://www.amazon.com.br/Nutri%C3%A7%C3%A3o-Diet%C3%A9tica-Ruth-Roth/dp/8527732371"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-publica');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem em Saúde Pública e Comunitária', 'Public Health and Community Nursing', 'Marcia Stanhope, Jeanette Lancaster', '10ª Edição', 2021, 'https://m.media-amazon.com/images/I/81p1EYSxLhL._AC_UF1000,1000_QL80_.jpg', 'Manual de referência para a enfermagem de saúde pública. Aborda epidemiologia, programas de saúde, prevenção e cuidados comunitários.', 'Reference manual for public health nursing. Covers epidemiology, health programs, prevention and community care.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323553695"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-adulto');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Brunner & Suddarth — Enfermagem Médico-Cirúrgica', 'Brunner & Suddarth''s Textbook of Medical-Surgical Nursing', 'Janice L. Hinkle, Kerry H. Cheever', '15ª Edição', 2021, 'https://m.media-amazon.com/images/I/81jv71-KeBL._AC_UF1000,1000_QL80_.jpg', 'O manual completo da enfermagem médico-cirúrgica, dos fundamentos à prática avançada. Cobre todas as especialidades clínicas do adulto hospitalizado.', 'The most complete medical-surgical nursing textbook, from fundamentals to advanced practice. Covers all clinical specialties of the hospitalized adult.', '{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1975161051"}', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-crianca');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem Pediátrica de Wong', 'Wong''s Nursing Care of Infants and Children', 'Marilyn J. Hockenberry, Chery C. Rodgers, David Wilson', '11ª Edição', 2021, 'https://m.media-amazon.com/images/I/91P5tJx2FyL._AC_UF1000,1000_QL80_.jpg', 'A referência mundial para o cuidado de enfermagem da criança e do adolescente. Aborda desde o recém-nascido ao adolescente, com ênfase nas patologias prevalentes.', 'The world reference for nursing care of infants and children. Covers from newborn to adolescent, with emphasis on prevalent pathologies.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323673773"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-idoso');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Ebersole & Hess – Enfermagem Gerontológica e Envelhecimento Saudável', 'Ebersole & Hess'' Gerontological Nursing & Healthy Aging', 'Theris A. Touhy, Kathleen F. Jett', '6ª Edição', 2021, 'https://m.media-amazon.com/images/I/81qMcNq8JdL._AC_UF1000,1000_QL80_.jpg', 'Focado na enfermagem ao idoso e à pessoa dependente. Aborda o envelhecimento saudável, as patologias crónicas, a reabilitação e os cuidados paliativos.', 'Focus on nursing for the elderly and dependent person. Covers healthy aging, chronic conditions, rehabilitation and palliative care.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323697818"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-mental');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem em Saúde Mental e Psiquiátrica de Videbeck', 'Psychiatric-Mental Health Nursing by Videbeck', 'Sheila L. Videbeck', '9ª Edição', 2022, 'https://m.media-amazon.com/images/I/71CV-gYXUOL._AC_UF1000,1000_QL80_.jpg', 'Aborda o cuidado de enfermagem à pessoa com perturbação mental, da avaliação à intervenção. Inclui terapêutica farmacológica e psicossocial.', 'Covers nursing care for people with mental disorders, from assessment to intervention. Includes pharmacological and psychosocial therapy.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1975116142"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-cirurgico');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Alexander – Cuidados de Enfermagem ao Paciente Cirúrgico', 'Alexander''s Care of the Patient in Surgery', 'Jane C. Rothrock', '17ª Edição', 2022, 'https://m.media-amazon.com/images/I/91Rr9y4IR+L._AC_UF1000,1000_QL80_.jpg', 'Manual de referência para cuidados perioperatórios, assepsia e esterilização. Abrange o pré, intra e pós-operatório de todas as especialidades cirúrgicas.', 'Reference manual for perioperative care, asepsis and sterilization. Covers pre, intra and postoperative care for all surgical specialties.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323698145"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-comunitaria');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem Comunitária e Cuidados Primários', 'Community and Primary Care Nursing', 'Marcia Stanhope, Jeanette Lancaster', '10ª Edição', 2021, '', 'Focado na prática do enfermeiro na comunidade, prevenção e promoção da saúde. Essencial para o contexto angolano onde o enfermeiro é a porta de entrada dos cuidados primários.', 'Focus on the nurse''s community practice, prevention and health promotion. Essential for the Angolan context.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323553695"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-administracao');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Gestão e Administração em Enfermagem', 'Nursing Management and Administration', 'Diane Huber, Mary N. Joseph', '7ª Edição', 2021, '', 'Aborda liderança, gestão de equipas, qualidade em saúde e gestão de recursos. Essencial para o enfermeiro que coordena serviços.', 'Covers leadership, team management, quality in healthcare and resource management. Essential for coordinating services.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323674583"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-pedagogia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Educação para a Saúde — Guia do Formador (OMS)', 'WHO Health Education — Trainer''s Guide', 'Guia da OMS para a educação em saúde nos cuidados primários. Inclui técnicas pedagógicas e comunicação comunitária.', 'WHO guide for health education in primary care. Includes pedagogical techniques and community communication.', 'https://www.who.int/tools/health-education-toolkit', 'guideline', 'published', 1);
END $$;
