-- 076: Study guides — livros e recursos para Enfermagem (versão limpa)
-- Substitui o 074 que causava 404. Dados validados, JSON simples, URLs diretas.

DO $$
DECLARE d UUID;
BEGIN
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-anatomia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Gray''s Anatomia Básica', 'Gray''s Basic Anatomy', 'Richard Drake, A. Wayne Vogl, Adam W.M. Mitchell', '2ª Edição', 2020, 'https://m.media-amazon.com/images/I/91OgV8G4klL._AC_UF1000,1000_QL80_.jpg', 'Anatomia essencial para o estudante de ciências da saúde. Texto claro com ilustrações baseadas no Gray''s Anatomy de referência.', 'Essential anatomy for health science students. Clear text with illustrations based on the reference Gray''s Anatomy.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Grays-Anatomia-Basica-Richard-Drake/dp/859515461X"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-microbiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Microbiologia de Brock', 'Brock Biology of Microorganisms', 'Michael T. Madigan, Kelly S. Bender, Daniel H. Buckley, W. Matthew Sattley, David A. Stahl', '16ª Edição', 2022, 'https://m.media-amazon.com/images/I/91FnXpRNF4L._AC_UF1000,1000_QL80_.jpg', 'Referência internacional da microbiologia com enfoque clínico e sanitário.', 'International microbiology reference with clinical and sanitary focus.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Microbiologia-Brock-Michael-Madigan/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-microbiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Manual de Precauções de Isolamento OMS', 'WHO Guidelines on Hand Hygiene in Health Care', 'Guias da OMS para higiene das mãos e controlo de infeção.', 'WHO guidelines for hand hygiene and infection control.', 'https://www.who.int/publications/i/item/9789241597906', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-psicologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Relação de Ajuda em Enfermagem', 'The Helping Relationship in Nursing', 'Alice T. Gonçalves', '1ª Edição', 2019, '', 'Aborda a comunicação terapêutica e a relação enfermeiro-doente como ferramenta central dos cuidados.', 'Addresses therapeutic communication and the nurse-patient relationship as a central care tool.', '[{"label_pt":"Saber mais","label_en":"Learn more","url":"https://www.wook.pt/livro/enfermagem-e-relacao-de-ajuda/00000000"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-etica');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Bioética em Enfermagem', 'Bioethics in Nursing', 'Conselho Internacional de Enfermeiros (ICN)', 'Atualizada', 2021, '', 'Fundamentos éticos e legais do exercício profissional. Inclui principios do Código Deontológico.', 'Ethical and legal foundations of professional practice. Includes Code of Ethics principles.', '[{"label_pt":"Código Deontológico ICN","label_en":"ICN Code of Ethics","url":"https://www.icn.ch/sites/default/files/inline-files/2012_ICN_Codeofethicsfornurses_eng.pdf"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-etica');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Estatuto da Ordem dos Enfermeiros de Angola', 'Angola Nursing Board Statute', 'Diploma legislativo que regula o exercício da enfermagem em Angola.', 'Legislative document regulating nursing practice in Angola.', 'https://www.ordemenfermeiros.ao/legislacao', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-farmacologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Farmacologia Básica e Clínica para Enfermagem', 'Pharmacology for Nursing Care', 'Leah M. Burchum, Laura D. Rosenthal', '11ª Edição', 2022, 'https://m.media-amazon.com/images/I/81EFJbo+kcL._AC_UF1000,1000_QL80_.jpg', 'Referência em farmacologia para enfermagem: fármaco por sistema, doses e cuidados de administração.', 'Pharmacology reference for nursing: drugs by system, doses and administration care.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323755451"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-farmacologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Calculadora de Fármacos (Medscape)', 'Medscape Drug Reference', 'Base de dados gratuita com informações de fármacos, doses, interações.', 'Free drug database with drug information, dosing, interactions.', 'https://reference.medscape.com/', 'other', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-fundamentos');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Fundamentos de Enfermagem de Potter & Perry', 'Fundamentals of Nursing by Potter & Perry', 'Patricia A. Potter, Anne G. Perry, Patricia A. Stockert, Amy M. Hall', '10ª Edição', 2022, 'https://m.media-amazon.com/images/I/71oKT8nxTnL._AC_UF1000,1000_QL80_.jpg', 'O manual mais usado mundialmente para fundamentos de enfermagem.', 'The most widely used fundamentals of nursing textbook worldwide.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon BR","url":"https://www.amazon.com.br/Fundamentos-Enfermagem-Potter-Exercicio-Enfermagem/dp/8535291134"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-fundamentos');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Tratado de Enfermagem Médico-Cirúrgica — Brunner & Suddarth', 'Brunner & Suddarth''s Textbook of Medical-Surgical Nursing', 'Janice L. Hinkle, Kerry H. Cheever', '15ª Edição', 2021, 'https://m.media-amazon.com/images/I/81jv71-KeBL._AC_UF1000,1000_QL80_.jpg', 'O manual completo da enfermagem médico-cirúrgica, dos fundamentos à prática avançada.', 'The most complete medical-surgical nursing textbook.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1975161051"}]', 'published', 2);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-nutricao');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Nutrição e Dietética para Enfermagem', 'Nutrition and Diet Therapy for Nursing', 'Ruth A. Roth, Carolynn E. Townsend', '12ª Edição', 2020, '', 'Aborda a relação entre alimentação, saúde e doença. Inclui dietoterapia para as principais patologias.', 'Covers the relationship between food, health and disease. Includes diet therapy for major pathologies.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon BR","url":"https://www.amazon.com.br/Nutricao-Dietetica-Ruth-Roth/dp/8527732371"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-publica');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem em Saúde Pública e Comunitária', 'Public Health and Community Nursing', 'Marcia Stanhope, Jeanette Lancaster', '10ª Edição', 2021, 'https://m.media-amazon.com/images/I/81p1EYSxLhL._AC_UF1000,1000_QL80_.jpg', 'Manual de referência para a enfermagem de saúde pública. Epidemiologia, programas de saúde, prevenção.', 'Reference manual for public health nursing. Epidemiology, health programs, prevention.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323553695"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-publica');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Estratégias para Cobertura Universal de Saúde (OMS)', 'Strategies towards Universal Health Coverage (WHO)', 'Documento OMS sobre reforço dos cuidados primários e cobertura universal.', 'WHO document on strengthening primary health care and universal coverage.', 'https://www.who.int/publications/i/item/9789241512236', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-adulto');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Brunner & Suddarth — Enfermagem Médico-Cirúrgica', 'Brunner & Suddarth''s Textbook of Medical-Surgical Nursing', 'Janice L. Hinkle, Kerry H. Cheever', '15ª Edição', 2021, 'https://m.media-amazon.com/images/I/81jv71-KeBL._AC_UF1000,1000_QL80_.jpg', 'O manual completo da enfermagem médico-cirúrgica, dos fundamentos à prática avançada.', 'The most complete medical-surgical nursing textbook.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1975161051"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-crianca');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem Pediátrica de Wong', 'Wong''s Nursing Care of Infants and Children', 'Marilyn J. Hockenberry, Chery C. Rodgers, David Wilson', '11ª Edição', 2021, 'https://m.media-amazon.com/images/I/91P5tJx2FyL._AC_UF1000,1000_QL80_.jpg', 'A referência mundial para o cuidado de enfermagem da criança e do adolescente.', 'The world reference for nursing care of infants and children.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323673773"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-idoso');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Ebersole & Hess – Enfermagem Gerontológica e Envelhecimento Saudável', 'Ebersole & Hess'' Gerontological Nursing & Healthy Aging', 'Theris A. Touhy, Kathleen F. Jett', '6ª Edição', 2021, 'https://m.media-amazon.com/images/I/81qMcNq8JdL._AC_UF1000,1000_QL80_.jpg', 'Focado na enfermagem ao idoso e à pessoa dependente. Envelhecimento saudável, patologias crónicas, reabilitação.', 'Focus on nursing for the elderly and dependent person. Healthy aging, chronic conditions, rehabilitation.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323697818"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-saude-mental');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem em Saúde Mental e Psiquiátrica de Videbeck', 'Psychiatric-Mental Health Nursing by Videbeck', 'Sheila L. Videbeck', '9ª Edição', 2022, 'https://m.media-amazon.com/images/I/71CV-gYXUOL._AC_UF1000,1000_QL80_.jpg', 'Cuidado de enfermagem à pessoa com perturbação mental, da avaliação à intervenção. Farmacológica e psicossocial.', 'Nursing care for people with mental disorders, from assessment to intervention. Pharmacological and psychosocial therapy.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1975116142"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-cirurgico');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Alexander – Cuidados de Enfermagem ao Paciente Cirúrgico', 'Alexander''s Care of the Patient in Surgery', 'Jane C. Rothrock', '17ª Edição', 2022, 'https://m.media-amazon.com/images/I/91Rr9y4IR+L._AC_UF1000,1000_QL80_.jpg', 'Manual de referência para cuidados perioperatórios, assepsia e esterilização.', 'Reference manual for perioperative care, asepsis and sterilization.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323698145"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-comunitaria');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Enfermagem Comunitária e Cuidados Primários', 'Community and Primary Care Nursing', 'Marcia Stanhope, Jeanette Lancaster', '10ª Edição', 2021, '', 'Prática do enfermeiro na comunidade, prevenção e promoção da saúde. Essencial no contexto angolano.', 'Nurse''s community practice, prevention and health promotion. Essential in the Angolan context.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323553695"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-administracao');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Gestão e Administração em Enfermagem', 'Nursing Management and Administration', 'Diane Huber, Mary N. Joseph', '7ª Edição', 2021, '', 'Aborda liderança, gestão de equipas, qualidade em saúde e gestão de recursos.', 'Covers leadership, team management, quality in healthcare and resource management.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323674583"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'enf-pedagogia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Educação para a Saúde — Guia do Formador (OMS)', 'WHO Health Education — Trainer''s Guide', 'Guia da OMS para educação em saúde nos cuidados primários. Técnicas pedagógicas e comunicação comunitária.', 'WHO guide for health education in primary care. Pedagogical techniques and community communication.', 'https://www.who.int/tools/health-education-toolkit', 'guideline', 'published', 1);
END $$;
