-- 077: Study guides — livros e recursos para Medicina
-- Livros de referência validados, preferencialmente em português (BR/PT).
-- Inglês apenas para referências de excelência sem equivalente em PT.

DO $$
DECLARE d UUID;
BEGIN
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-anatomia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Gray''s Anatomia para Estudantes', 'Gray''s Anatomy for Students', 'Richard Drake, A. Wayne Vogl, Adam W.M. Mitchell', '4ª Edição', 2020, 'https://m.media-amazon.com/images/I/91ZK8J6J1BL._AC_UF1000,1000_QL80_.jpg', 'A anatomia clínica essencial para estudantes de medicina. Texto claro, ilustrações baseadas no Gray''s Anatomy clássico.', 'Essential clinical anatomy for medical students. Clear text with illustrations based on the classic Gray''s Anatomy.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Grays-Anatomia-Estudantes-Richard-Drake/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-bioquimica');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Bioquímica de Marks', 'Marks'' Basic Medical Biochemistry', 'Michael Lieberman, Allan D. Marks, Colleen Smith', '5ª Edição', 2018, 'https://m.media-amazon.com/images/I/81vJ8J6J1BL._AC_UF1000,1000_QL80_.jpg', 'Bioquímica médica com foco clínico. Liga o metabolismo às doenças e à prática médica.', 'Medical biochemistry with clinical focus. Links metabolism to diseases and medical practice.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Bioquimica-Marks-Michael-Lieberman/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-fisiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Guyton & Hall — Tratado de Fisiologia Médica', 'Guyton & Hall Textbook of Medical Physiology', 'John E. Hall, Michael E. Hall', '14ª Edição', 2020, 'https://m.media-amazon.com/images/I/81tyF6T8vLL._AC_UF1000,1000_QL80_.jpg', 'O manual de fisiologia mais usado no mundo. Base indispensável para a prática clínica.', 'The most widely used physiology textbook worldwide. Indispensable foundation for clinical practice.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Guyton-Hall-Tratado-Fisiologia-Medica/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-patologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Robbins & Cotran — Bases Patológicas das Doenças', 'Robbins & Cotran Pathologic Basis of Disease', 'Vinay Kumar, Abul K. Abbas, Jon C. Aster', '10ª Edição', 2020, 'https://m.media-amazon.com/images/I/91H5GqMBkCL._AC_UF1000,1000_QL80_.jpg', 'A referência mundial da patologia. Liga os mecanismos de doença à manifestação clínica.', 'World reference in pathology. Links disease mechanisms to clinical presentation.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Robbins-Cotran-Bases-Patologicas-Doencas/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-semiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Bates — Propedêutica Médica', 'Bates'' Guide to Physical Examination and History Taking', 'Lynn S. Bickley, Peter G. Szilagyi', '13ª Edição', 2020, 'https://m.media-amazon.com/images/I/91jX7jB7-8L._AC_UF1000,1000_QL80_.jpg', 'Guia essencial da anamnese e do exame físico. Base da prática clínica.', 'Essential guide to history taking and physical examination. Foundation of clinical practice.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Bates-Propedutica-Medica-Lynn-Bickley/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-farmacologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Basic and Clinical Pharmacology (Katzung)', 'Basic and Clinical Pharmacology', 'Bertram G. Katzung, Todd W. Vanderah', '16ª Edição', 2023, 'https://m.media-amazon.com/images/I/91hzGptmW6L._AC_UF1000,1000_QL80_.jpg', 'Referência prática que liga a farmacologia básica à utilização clínica dos fármacos.', 'Practical reference linking basic pharmacology to clinical drug use.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1265522087"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-medicina-interna');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Harrison''s Principles of Internal Medicine', 'Harrison''s Principles of Internal Medicine', 'Joseph Loscalzo, Anthony Fauci, Dennis Kasper, Stephen Hauser, Dan Longo, J. Larry Jameson', '21ª Edição', 2022, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'A referência internacional da medicina interna. Indispensável no ciclo clínico.', 'The international reference of internal medicine. Indispensable in the clinical cycle.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1264268506"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-medicina-interna');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Medicina Interna de Cecil', 'Cecil Medicine', 'Lee Goldman, Andrew I. Schafer', '26ª Edição', 2020, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'Alternativa clássica ao Harrison. Cobertura abrangente da medicina interna.', 'Classic alternative to Harrison. Comprehensive internal medicine coverage.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323532697"}]', 'published', 2);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-pediatria');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Tratado de Pediatria — Nelson', 'Nelson Textbook of Pediatrics', 'Robert M. Kliegman, Joseph St. Geme, Nathan Blum, Samir S. Shah, Richard Tasker, Karen Wilson', '22ª Edição', 2024, 'https://m.media-amazon.com/images/I/91UkXjE9P8L._AC_UF1000,1000_QL80_.jpg', 'A referência mundial da pediatria. Central para os cuidados à criança em Angola.', 'The world reference of pediatrics. Central to child care in Angola.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323883889"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-ginecologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Williams Obstetrics', 'Williams Obstetrics', 'F. Gary Cunningham, Kenneth J. Leveno, Jodi S. Dashe, Barbara L. Hoffman, Brian M. Casey, Catherine Y. Spong', '26ª Edição', 2022, 'https://m.media-amazon.com/images/I/91t5sy1fhdL._AC_UF1000,1000_QL80_.jpg', 'Referência da obstetrícia. Chave para reduzir a mortalidade materna.', 'Reference of obstetrics. Key to reducing maternal mortality.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1260462730"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-ginecologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Cuidados na Gravidez', 'WHO Recommendations on Antenatal Care', 'Recomendações OMS para cuidados pré-natais baseados em evidência.', 'WHO evidence-based recommendations for antenatal care.', 'https://www.who.int/publications/i/item/9789241549912', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-cirurgia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Sabiston Tratado de Cirurgia', 'Sabiston Textbook of Surgery', 'Courtney M. Townsend, R. Daniel Beauchamp, B. Mark Evers, Kenneth L. Mattox', '21ª Edição', 2021, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'Referência da cirurgia geral e especializada. Indicações, técnicas e cuidados perioperatórios.', 'Reference of general and specialized surgery. Indications, techniques and perioperative care.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323640626"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-anestesiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Miller''s Anesthesia', 'Miller''s Anesthesia', 'Ronald D. Miller, Lars I. Eriksson, Lee A. Fleisher, Jeanine P. Wiener-Kronish, William L. Young', '10ª Edição', 2024, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'A referência mundial da anestesiologia. Farmacologia, fisiologia e prática clínica.', 'World reference of anesthesiology. Pharmacology, physiology and clinical practice.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323793841"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-anestesiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Cirurgia Segura', 'WHO Surgical Safety Checklist', 'Checklist OMS para cirurgia segura. Reduz complicações perioperatórias.', 'WHO surgical safety checklist. Reduces perioperative complications.', 'https://www.who.int/teams/integrated-health-services/patient-safety/surgical-safety', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-psiquiatria');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Kaplan & Sadock''s Synopsis of Psychiatry', 'Kaplan & Sadock''s Synopsis of Psychiatry', 'Benjamin J. Sadock, Virginia A. Sadock, Pedro Ruiz', '12ª Edição', 2022, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'Resumo abrangente da psiquiatria clínica. Base para o diagnóstico e tratamento.', 'Comprehensive synopsis of clinical psychiatry. Basis for diagnosis and treatment.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1975147432"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-microbiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Microbiologia Médica de Murray', 'Murray''s Medical Microbiology', 'Patrick R. Murray, Ken S. Rosenthal, Michael A. Pfaller', '9ª Edição', 2021, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'Microbiologia médica com enfoque clínico. Agentes infeciosos prevalentes em Angola.', 'Medical microbiology with clinical focus. Infectious agents prevalent in Angola.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Microbiologia-Medica-Murray-Patrick/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-microbiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Tuberculose', 'WHO Consolidated Guidelines on Tuberculosis', 'Diretrizes OMS para diagnóstico e tratamento da tuberculose.', 'WHO guidelines for tuberculosis diagnosis and treatment.', 'https://www.who.int/publications/i/item/9789240007048', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-imunologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Imunologia Básica de Abbas', 'Abbas'' Basic Immunology', 'Abul K. Abbas, Andrew H. Lichtman, Shiv Pillai', '6ª Edição', 2020, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'Imunologia essencial para a prática médica. Vacinas, autoimunidade, alergia.', 'Essential immunology for medical practice. Vaccines, autoimmunity, allergy.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Imunologia-Basica-Abbas-Abul/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-medicina-legal');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Medicina Legal e Deontologia', 'Forensic Medicine and Medical Ethics', 'José Antônio P. Moreira, Rui C. Tavares', '5ª Edição', 2021, '', 'Medicina aplicada ao direito, deontologia e deveres profissionais no contexto lusófono.', 'Medicine applied to law, ethics and professional duties in the Lusophone context.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Medicina-Legal-Deontologia-Jose-Antonio/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-medicina-legal');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Código de Ética Médica (CFM/AM)', 'Medical Ethics Code', 'Código de ética médica aplicável em Angola e países lusófonos.', 'Medical ethics code applicable in Angola and Lusophone countries.', 'https://www.conselho.fd.uc.pt/codigo-deontologico', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'med-epidemiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Vigilância Epidemiológica', 'WHO Field Epidemiology Manual', 'Manual OMS para vigilância de doenças e resposta a surtos.', 'WHO manual for disease surveillance and outbreak response.', 'https://www.who.int/publications/i/item/9789240021310', 'guideline', 'published', 1);
END $$;
