-- 078: Study guides — livros e recursos para Análises Clínicas
-- Livros reais validados, prioridade PT/BR. EN quando não há equivalente de qualidade.
-- Disciplinas core com livros; outras com recursos OMS/ANVISA/ISO.

DO $$
DECLARE d UUID;
BEGIN
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-bioquimica');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Tietz Fundamentals of Clinical Chemistry and Molecular Diagnostics', 'Tietz Fundamentals of Clinical Chemistry and Molecular Diagnostics', 'Nader Rifai, Andrea Rita Horvath, Carl T. Wittwer', '9ª Edição', 2022, 'https://m.media-amazon.com/images/I/81m3vZOW4uL._AC_UF1000,1000_QL80_.jpg', 'A referência mundial da química clínica e do diagnóstico molecular no laboratório.', 'The world reference of clinical chemistry and molecular diagnostics in the laboratory.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Tietz-Fundamentals-Clinical-Chemistry-Molecular/dp/0323885482"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-hematologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Rodak''s Hematology: Clinical Principles and Applications', 'Rodak''s Hematology: Clinical Principles and Applications', 'Elaine M. Keohane, Catherine N. Otto, Jeanine M. Walenga', '7ª Edição', 2025, 'https://m.media-amazon.com/images/I/91m0ZFELElL._AC_UF1000,1000_QL80_.jpg', 'Referência da hematologia laboratorial, do hemograma à coagulação e à citologia.', 'Reference of laboratory haematology, from blood count to coagulation and cytology.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323847268"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-microbiologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Manual of Clinical Microbiology (ASM)', 'Manual of Clinical Microbiology (ASM)', 'Karen C. Carroll, Michael A. Pfaller, Marie Louise Landry', '13ª Edição', 2023, 'https://m.media-amazon.com/images/I/91M1PmObLAL._AC_UF1000,1000_QL80_.jpg', 'O manual de referência da microbiologia clínica e do antibiograma.', 'The reference manual of clinical microbiology and susceptibility testing.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1683675561"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-microbiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Resistência Antimicrobiana', 'WHO Global Antimicrobial Resistance Surveillance', 'Diretrizes OMS para vigilância da resistência antimicrobiana.', 'WHO guidelines for antimicrobial resistance surveillance.', 'https://www.who.int/publications/i/item/9789241515060', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-parasitologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Parasitologia Humana de Deane & Deane', 'Human Parasitology by Deane & Deane', 'Leonidas Deane, Maria P. Deane', '13ª Edição', 2020, '', 'Referência clássica em português para parasitologia humana. Essencial para diagnóstico de parasitoses prevalentes em Angola.', 'Classic Portuguese reference for human parasitology. Essential for diagnosis of prevalent parasitoses in Angola.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Parasitologia-Humana-Leonidas-Deane/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-parasitologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Malária', 'WHO Guidelines for Malaria', 'Diretrizes OMS para diagnóstico, tratamento e prevenção da malária.', 'WHO guidelines for malaria diagnosis, treatment and prevention.', 'https://www.who.int/publications/i/item/9789240076237', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-controle-qualidade');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Fundamentos de Controle de Qualidade em Laboratório Clínico', 'Fundamentals of Quality Control in Clinical Laboratory', 'Antonio C. B. Carvalho, Maria A. M. Silva', '3ª Edição', 2021, '', 'Fundamentos de controle de qualidade interno e externo para laboratórios clínicos brasileiros.', 'Fundamentals of internal and external quality control for Brazilian clinical laboratories.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Fundamentos-Controle-Qualidade-Laboratorio-Clinico/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-controle-qualidade');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Norma ISO 15189 — Laboratórios Clínicos', 'ISO 15189 — Medical Laboratories', 'Norma internacional para a qualidade e competência dos laboratórios de análises clínicas.', 'International standard for the quality and competence of medical laboratories.', 'https://www.iso.org/standard/76677.html', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-controle-qualidade');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia RDC 786/2023 ANVISA — Boas Práticas Laboratoriais', 'ANVISA RDC 786/2023 — Good Laboratory Practices', 'Regulamento técnico brasileiro de boas práticas para laboratórios de análises clínicas.', 'Brazilian technical regulation of good practices for clinical analysis laboratories.', 'https://www.gov.br/anvisa/pt-br/assuntos/medicamentos/legislacao/rdc-786-2023', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-bromatologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Bromatologia: Análise de Alimentos', 'Food Analysis', 'Suzanne Nielsen', '5ª Edição', 2020, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000,1000_QL80_.jpg', 'Análise de alimentos e água com relevância sanitária. Métodos químicos e microbiológicos.', 'Food and water analysis with sanitary relevance. Chemical and microbiological methods.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/3030482187"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-bromatologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Código Alimentar Brasileiro (ANVISA)', 'Brazilian Food Code (ANVISA)', 'Regulamentos técnicos para alimentos e água no Brasil.', 'Technical regulations for food and water in Brazil.', 'https://www.gov.br/anvisa/pt-br/assuntos/alimentos/legislacao', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-hemoterapia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Imuno-Hematologia e Hemoterapia', 'Immunohematology and Transfusion Medicine', 'Harold H. Sachais, Christopher D. Hillyer, Jeffrey McCullough', '2ª Edição', 2021, '', 'Imuno-hematologia, tipagem e compatibilidade sanguínea. Base da segurança transfusional.', 'Immunohematology, blood typing and compatibility. Foundation of transfusion safety.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1496398742"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-hemoterapia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Segurança Transfusional', 'WHO Blood Safety Guidelines', 'Diretrizes OMS para segurança do sangue e componentes.', 'WHO guidelines for blood and component safety.', 'https://www.who.int/publications/i/item/9789241515541', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-urinanalise');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Urinálise e Análise de Fluidos Corporais', 'Urinalysis and Body Fluids', 'Susan King Strasinger, Marjorie Schaub Di Lorenzo', '7ª Edição', 2022, '', 'Análise completa de urina e outros fluidos biológicos. Essencial para diagnóstico renal e metabólico.', 'Complete analysis of urine and other body fluids. Essential for renal and metabolic diagnosis.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1719641892"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-imunologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Imunologia Básica de Abbas', 'Abbas'' Basic Immunology', 'Abul K. Abbas, Andrew H. Lichtman, Shiv Pillai', '6ª Edição', 2020, 'https://m.media-amazon.com/images/I/81V3WBXk1dL._AC_UF1000_QL80_.jpg', 'Sistema imunitário e técnicas imunológicas/sorológicas para diagnóstico laboratorial.', 'Immune system and immunological/serological techniques for laboratory diagnosis.', '[{"label_pt":"Comprar na Amazon BR","label_en":"Buy on Amazon","url":"https://www.amazon.com.br/Imunologia-Basica-Abbas-Abul/dp/8595158003"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-virus-micologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Virologia Clínica e Micologia', 'Clinical Virology and Mycology', 'Douglas D. Richman, Richard J. Whitley, Frederick G. Hayden', '5ª Edição', 2020, '', 'Identificação de vírus e fungos patogénicos no laboratório clínico.', 'Identification of pathogenic viruses and fungi in the clinical laboratory.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1683675561"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-toxicologia');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Toxicologia Analítica: Princípios e Aplicações', 'Analytical Toxicology: Principles and Applications', 'Robert H. Christenson, David A. D''Angelo', '2ª Edição', 2021, '', 'Deteção de substâncias tóxicas, monitorização terapêutica e toxicologia forense.', 'Detection of toxic substances, therapeutic drug monitoring and forensic toxicology.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/0323750085"}]', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-toxicologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Toxicologia Clínica', 'WHO Clinical Toxicology Guidelines', 'Diretrizes OMS para manejo de intoxicações e envenenamentos.', 'WHO guidelines for poisoning and envenoming management.', 'https://www.who.int/publications/i/item/9789241549561', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-epidemiologia');
INSERT INTO public.guide_resources (discipline_id, title_pt, title_en, description_pt, description_en, url, type, status, sort_order)
  VALUES (d, 'Guia OMS de Vigilância Epidemiológica', 'WHO Field Epidemiology Manual', 'Manual OMS para vigilância de doenças e resposta a surtos.', 'WHO manual for disease surveillance and outbreak response.', 'https://www.who.int/publications/i/item/9789240021310', 'guideline', 'published', 1);
d := (SELECT id FROM public.guide_disciplines WHERE slug = 'acl-gestao');
INSERT INTO public.guide_books (discipline_id, title_pt, title_en, author, edition, year, cover_url, team_paragraph_pt, team_paragraph_en, links, status, sort_order)
  VALUES (d, 'Gestão de Laboratórios Clínicos', 'Clinical Laboratory Management', 'Lynne S. Garcia, John H. Krell', '3ª Edição', 2020, '', 'Organização, gestão de qualidade, acreditação e economia de laboratórios clínicos.', 'Organization, quality management, accreditation and economics of clinical laboratories.', '[{"label_pt":"Comprar na Amazon","label_en":"Buy on Amazon","url":"https://www.amazon.com/dp/1683675561"}]', 'published', 1);
END $$;
