-- =====================================================================
-- 088 — Farmacologia do fármaco (drug_pharmacology) — extensão aos 30
--        fármacos com perfil completo (drug_profiles) que ainda não
--        tinham farmacologia.
-- ---------------------------------------------------------------------
-- Complementa a 086 (tabela + seed piloto de 6 fármacos). Conteúdo
-- autoral, ancorado nas fontes citadas em cada linha:
--   • 28 fármacos: secção 12 CLINICAL PHARMACOLOGY dos rótulos
--     aprovados DailyMed (setIDs validados nesta migração);
--   • gliclazida: SmPC EMC-UK (medicines.org.uk, produto 13135);
--   • tiamazol: rótulos DailyMed curtos + farmacocinética corroborada
--     por PubMed (Jansen 1983, Clin Pharmacokinet, PMID 6172233;
--     Cooper DS. N Engl J Med 2005, PMID 15745981).
-- Depende da 086 (tabela drug_pharmacology). Idempotente:
-- ON CONFLICT (drug_id) DO NOTHING — reaplicar é seguro.
-- =====================================================================

INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en, absorption_pt, absorption_en,
   half_life_pt, half_life_en, source_pt, source_en, status)
SELECT d.id, v.pharmacodynamics_pt, v.pharmacodynamics_en, v.mechanism_pt, v.mechanism_en,
       v.metabolism_pt, v.metabolism_en, v.absorption_pt, v.absorption_en,
       v.half_life_pt, v.half_life_en, v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('amiodarona',
   'Antiarrítmico com propriedades das classes I, II, III e IV. O efeito antiarrítmico oral demora 2 dias a 3 semanas a estabelecer-se e, devido à meia-vida muito longa, os efeitos e as interações podem persistir durante semanas a meses após a suspensão. O tempo de recorrência da arritmia após a suspensão é variável e imprevisível.',
   'Antiarrhythmic with class I, II, III and IV properties. The oral antiarrhythmic effect takes 2 days to 3 weeks to develop and, because of the very long half-life, effects and interactions may persist for weeks to months after discontinuation. The time to arrhythmia recurrence after stopping is variable and unpredictable.',
   'Prolonga a fase 3 do potencial de ação (classe III) por bloqueio dos canais de potássio, com prolongamento do intervalo QT; tem também bloqueio dos canais de sódio (classe I), betabloqueio não competitivo (classe II) e bloqueio dos canais de cálcio (classe IV). Produz vasodilatação coronária e periférica e reduz a frequência cardíaca.',
   'Prolongs phase 3 of the action potential (class III) by blocking potassium channels, with QT interval prolongation; it also blocks sodium channels (class I), has non-competitive beta-blockade (class II) and calcium channel blockade (class IV). It produces coronary and peripheral vasodilatation and reduces heart rate.',
   'Metabolizado no fígado, sobretudo pelo CYP3A4 e CYP2C8, com formação do metabolito ativo desetilamiodarona. A eliminação é muito lenta, com acumulação extensa nos tecidos (gordura, fígado, pulmão).',
   'Metabolised in the liver, mainly by CYP3A4 and CYP2C8, with formation of the active metabolite desethylamiodarone. Elimination is very slow, with extensive tissue accumulation (fat, liver, lung).',
   'Após administração oral, o pico plasmático ocorre em 3 a 7 horas. Os alimentos aumentam a taxa e a extensão da absorção: a AUC e a Cmax aumentam cerca de 2,3 e 3,8 vezes, respetivamente, quando tomado com uma refeição rica em gordura. A biodisponibilidade oral é incompleta e variável.',
   'After oral administration, peak plasma concentrations occur in 3 to 7 hours. Food increases the rate and extent of absorption: AUC and Cmax increase about 2.3 and 3.8 times, respectively, when taken with a high-fat meal. Oral bioavailability is incomplete and variable.',
   'A meia-vida da amiodarona é de 15 a 142 dias e a do metabolito ativo desetilamiodarona de 14 a 75 dias, o que explica a persistência dos efeitos e das interações durante semanas após a suspensão.',
   'The half-life of amiodarone is 15 to 142 days and that of the active metabolite desethylamiodarone 14 to 75 days, which explains why effects and interactions persist for weeks after discontinuation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amiodarona, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c149392-a4f0-4e2d-a13f-2b94810005de',
   'DailyMed/FDA (NIH/NLM) — approved Amiodarone label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c149392-a4f0-4e2d-a13f-2b94810005de'),

  ('amlodipina',
   'Anti-hipertensor e antianginoso. O efeito anti-hipertensor máximo surge progressivamente e o estado estacionário é atingido após 7 a 8 dias de toma diária. Em doentes hipertensos, liga-se cerca de 93% às proteínas plasmáticas.',
   'Antihypertensive and antianginal agent. The maximum antihypertensive effect develops gradually and steady state is reached after 7 to 8 days of daily dosing. In hypertensive patients it is about 93% bound to plasma proteins.',
   'Bloqueador dos canais de cálcio do tipo diidropiridina: inibe o influxo transmembranar de iões de cálcio no músculo liso vascular e no músculo cardíaco, produzindo vasodilatação arterial periférica e redução da resistência vascular sistémica.',
   'Dihydropyridine calcium channel blocker: inhibits the transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle, producing peripheral arterial vasodilatation and reduced systemic vascular resistance.',
   'É extensamente (cerca de 90%) convertido em metabolitos inativos por metabolismo hepático; 10% do composto original e 60% dos metabolitos são excretados na urina.',
   'Extensively (about 90%) converted to inactive metabolites via hepatic metabolism; 10% of the parent compound and 60% of the metabolites are excreted in the urine.',
   'Após administração oral, o pico plasmático ocorre entre 6 e 12 horas. A biodisponibilidade absoluta é de 64 a 90% e não é alterada pela presença de alimentos.',
   'After oral administration, peak plasma concentrations occur between 6 and 12 hours. Absolute bioavailability is 64 to 90% and is not altered by food.',
   'A eliminação plasmática é bifásica, com semivida terminal de cerca de 30 a 50 horas (aproximadamente 56 horas em doentes com insuficiência hepática grave).',
   'Plasma elimination is biphasic, with a terminal half-life of about 30 to 50 hours (approximately 56 hours in patients with severe hepatic impairment).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amlodipina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3e9e049d-a988-4dc5-b9aa-14f1162409d6',
   'DailyMed/FDA (NIH/NLM) — approved Amlodipine label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3e9e049d-a988-4dc5-b9aa-14f1162409d6'),

  ('anastrozol',
   'Inibidor da aromatase usado no cancro da mama com recetores hormonais positivos. Em doses de 1 mg por dia, reduz o estradiol circulante em cerca de 70% no prazo de 24 horas e em cerca de 80% após 14 dias. Não afeta de forma clinicamente relevante os corticosteroides, a aldosterona ou as hormonas tiroideias.',
   'Aromatase inhibitor used in hormone receptor-positive breast cancer. At 1 mg daily it reduces circulating estradiol by about 70% within 24 hours and by about 80% after 14 days. It does not clinically meaningfully affect corticosteroids, aldosterone or thyroid hormones.',
   'Inibe de forma seletiva a enzima aromatase (CYP19), reduzindo a conversão de andrógenos adrenais (androstenediona, testosterona) em estrogénios (estrona, estradiol) nos tecidos periféricos e no tumor.',
   'Selectively inhibits the aromatase enzyme (CYP19), reducing the conversion of adrenal androgens (androstenedione, testosterone) into oestrogens (oestrone, oestradiol) in peripheral tissues and in the tumour.',
   'É extensamente metabolizado no fígado (cerca de 85% da dose), por N-desalquilação, hidroxilação e glucuronidação, com participação do CYP3A4. Os metabolitos são eliminados sobretudo na urina.',
   'Extensively metabolised in the liver (about 85% of the dose), by N-dealkylation, hydroxylation and glucuronidation, with involvement of CYP3A4. The metabolites are eliminated mainly in the urine.',
   'Bem absorvido após administração oral, com pico plasmático em cerca de 2 horas. A presença de alimentos não altera a absorção. A ligação às proteínas plasmáticas é de cerca de 40%.',
   'Well absorbed after oral administration, with peak plasma concentrations in about 2 hours. Food does not alter absorption. Plasma protein binding is about 40%.',
   'A semivida de eliminação é de cerca de 50 horas, atingindo-se o estado estacionário após 7 dias de administração diária.',
   'The elimination half-life is about 50 hours, with steady state reached after 7 days of daily administration.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Anastrozol, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54da5c12-cfaf-7a14-e063-6394a90a3635',
   'DailyMed/FDA (NIH/NLM) — approved Anastrozole label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54da5c12-cfaf-7a14-e063-6394a90a3635'),

  ('atorvastatina',
   'Estatinas: a redução do colesterol LDL e dos triglicéridos é dependente da dose e o efeito máximo sobre o LDL surge cerca de 4 semanas após o início ou ajuste da dose (com redução já às 2 semanas). Aumenta também a apoA-1 e o HDL.',
   'Statins: LDL cholesterol and triglyceride reductions are dose-dependent and the maximum effect on LDL appears about 4 weeks after starting or adjusting the dose (with reduction already at 2 weeks). It also increases apoA-1 and HDL.',
   'Inibidor seletivo e competitivo da HMG-CoA redutase, a enzima que limita a síntese do colesterol no fígado. A redução do colesterol intracelular hepático aumenta a expressão dos recetores LDL, aumentando a captação e o catabolismo do LDL plasmático.',
   'Selective, competitive inhibitor of HMG-CoA reductase, the rate-limiting enzyme in hepatic cholesterol synthesis. The reduction in hepatic intracellular cholesterol increases LDL receptor expression, enhancing the uptake and catabolism of plasma LDL.',
   'É extensamente metabolizado no fígado, sobretudo pelo CYP3A4, com formação de metabolitos ativos (orto- e para-hidroxi-atorvastatina, responsáveis por cerca de 70% da atividade inibitória da HMG-CoA redutase). A eliminação é principalmente biliar.',
   'Extensively metabolised in the liver, mainly by CYP3A4, with formation of active metabolites (ortho- and para-hydroxy-atorvastatin, responsible for about 70% of the HMG-CoA reductase inhibitory activity). Elimination is mainly biliary.',
   'Rápida absorção após administração oral, com pico plasmático em 1 a 2 horas. A biodisponibilidade absoluta é de cerca de 14% (elevado efeito de primeira passagem). Os alimentos reduzem a velocidade, mas não a extensão da absorção (Cmax cerca de 25% menor, efeito sobre o LDL inalterado). Liga-se mais de 98% às proteínas plasmáticas.',
   'Rapidly absorbed after oral administration, with peak plasma concentrations in 1 to 2 hours. Absolute bioavailability is about 14% (high first-pass effect). Food reduces the rate but not the extent of absorption (Cmax about 25% lower, LDL effect unchanged). It is more than 98% bound to plasma proteins.',
   'A semivida plasmática é de cerca de 14 horas e a dos metabolitos ativos de 20 a 30 horas.',
   'The plasma half-life is about 14 hours and that of the active metabolites 20 to 30 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atorvastatina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51e24220-3374-4e5e-9a8d-4113002c5bed',
   'DailyMed/FDA (NIH/NLM) — approved Atorvastatin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51e24220-3374-4e5e-9a8d-4113002c5bed'),

  ('carbamazepina',
   'Anticonvulsivante e estabilizador do humor. O efeito terapêutico na epilepsia relaciona-se com a manutenção de concentrações plasmáticas na faixa habitualmente considerada de 4 a 12 mcg/ml. O metabolismo é autoinduzido ao longo de 3 a 5 semanas, exigindo frequentemente ajuste da dose.',
   'Anticonvulsant and mood stabiliser. The therapeutic effect in epilepsy relates to maintenance of plasma concentrations within the range usually considered to be 4 to 12 mcg/ml. Metabolism is auto-induced over 3 to 5 weeks, often requiring dose adjustment.',
   'Bloqueia os canais de sódio dependentes da voltagem, reduzindo a atividade neuronal repetitiva de alta frequência e estabilizando as membranas neuronais. Tem também efeitos sobre os canais de cálcio e sobre os sistemas GABAérgico e serotoninérgico.',
   'Blocks voltage-dependent sodium channels, reducing sustained high-frequency neuronal firing and stabilising neuronal membranes. It also has effects on calcium channels and on GABAergic and serotoninergic systems.',
   'Metabolizado no fígado, com formação do epóxido 10,11-carbamazepina, um metabolito ativo. A carbamazepina é um potente indutor das enzimas do citocromo P450 (incluindo o CYP3A4), acelerando o seu próprio metabolismo e o de muitos outros fármacos. Os metabolitos são eliminados na urina e nas fezes.',
   'Metabolised in the liver, with formation of carbamazepine-10,11-epoxide, an active metabolite. Carbamazepine is a potent inducer of cytochrome P450 enzymes (including CYP3A4), accelerating its own metabolism and that of many other drugs. The metabolites are eliminated in urine and faeces.',
   'A absorção oral é lenta e irregular, com pico plasmático entre 4 e 8 horas após a toma de comprimidos (cerca de 1,5 horas para a suspensão). A ligação às proteínas plasmáticas é de cerca de 76%.',
   'Oral absorption is slow and irregular, with peak plasma concentrations 4 to 8 hours after tablet intake (about 1.5 hours for the suspension). Plasma protein binding is about 76%.',
   'A semivida inicial é de 25 a 65 horas; após autoindução enzimática (3 a 5 semanas), reduz-se para cerca de 12 a 17 horas.',
   'The initial half-life is 25 to 65 hours; after enzyme auto-induction (3 to 5 weeks) it falls to about 12 to 17 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Carbamazepina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52cf3ba9-0a7c-4809-830e-af93d1532726',
   'DailyMed/FDA (NIH/NLM) — approved Carbamazepine label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=52cf3ba9-0a7c-4809-830e-af93d1532726'),

  ('ciprofloxacina',
   'Fluoroquinolona bactericida de largo espetro, ativa contra bactérias Gram-positivas e Gram-negativas, incluindo Pseudomonas aeruginosa. Após dose oral, as concentrações séricas máximas são atingidas em 1 a 2 horas e a concentração tecidular excede frequentemente a sérica.',
   'Broad-spectrum bactericidal fluoroquinolone, active against Gram-positive and Gram-negative bacteria, including Pseudomonas aeruginosa. After an oral dose, peak serum concentrations are reached in 1 to 2 hours and tissue concentrations often exceed serum levels.',
   'A ação bactericida resulta da inibição da topoisomerase II (girase do DNA) e da topoisomerase IV, enzimas essenciais para a replicação, transcrição, reparação e recombinação do DNA bacteriano.',
   'The bactericidal action results from inhibition of topoisomerase II (DNA gyrase) and topoisomerase IV, enzymes essential for bacterial DNA replication, transcription, repair and recombination.',
   'Foram identificados quatro metabolitos na urina, que no conjunto representam cerca de 15% de uma dose oral. A ciprofloxacina é um inibidor do CYP1A2, podendo aumentar as concentrações de fármacos metabolizados por esta isoenzima. Cerca de 40 a 50% da dose oral é excretada inalterada na urina e 20 a 35% nas fezes.',
   'Four metabolites have been identified in urine, together accounting for about 15% of an oral dose. Ciprofloxacin is an inhibitor of CYP1A2 and may increase the concentrations of drugs metabolised by this isoenzyme. About 40 to 50% of an oral dose is excreted unchanged in urine and 20 to 35% in faeces.',
   'A biodisponibilidade oral absoluta é de cerca de 70%, sem perda substancial por efeito de primeira passagem. O pico sérico ocorre 1 a 2 horas após a toma; os alimentos atrasam o pico para cerca de 2 horas sem afetar substancialmente a absorção. A ligação às proteínas séricas é de 20 a 40%. Leite, iogurte, sumos enriquecidos com cálcio e antiácidos reduzem a absorção.',
   'Absolute oral bioavailability is about 70%, with no substantial first-pass loss. Peak serum levels occur 1 to 2 hours after dosing; food delays the peak to about 2 hours without substantially affecting absorption. Serum protein binding is 20 to 40%. Milk, yoghurt, calcium-fortified juices and antacids reduce absorption.',
   'A semivida sérica de eliminação em doentes com função renal normal é de aproximadamente 4 horas (5 horas em crianças).',
   'The serum elimination half-life in patients with normal renal function is approximately 4 hours (5 hours in children).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58388197-82f4-0953-e063-6294a90ac52a',
   'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58388197-82f4-0953-e063-6294a90ac52a'),

  ('digoxina',
   'Glicosídeo cardíaco: aumenta a força e a velocidade da contração sistólica do miocárdio (inotropismo positivo), reduz a frequência cardíaca (cronotropismo negativo) e diminui a velocidade de condução no nó auriculoventricular. O efeito máximo dos comprimidos ocorre 2 a 6 horas após a toma.',
   'Cardiac glycoside: increases the force and velocity of myocardial systolic contraction (positive inotropy), slows the heart rate (negative chronotropy) and decreases conduction velocity through the atrioventricular node. Peak effect of tablets occurs 2 to 6 hours after dosing.',
   'Todas as ações da digoxina são mediadas pela inibição da Na-K-ATPase: aumenta a disponibilidade intracelular de cálcio no miocárdio e no sistema de condução, estimula o parassimpático (efeitos no nó sinusal e auriculoventricular) e reduz a recaptação das catecolaminas.',
   'All of digoxin actions are mediated through inhibition of Na-K-ATPase: it increases intracellular calcium availability in the myocardium and conduction system, stimulates the parasympathetic system (effects on the sino-atrial and atrioventricular nodes) and reduces catecholamine reuptake.',
   'Apenas uma pequena percentagem (cerca de 13%) da dose é metabolizada; o metabolismo não depende do citocromo P450. A digoxina é substrato da glicoproteína P. Cerca de 50 a 70% da dose é excretada inalterada na urina, proporcionalmente à depuração da creatinina.',
   'Only a small percentage (about 13%) of a dose is metabolised; metabolism does not depend on cytochrome P450. Digoxin is a substrate of P-glycoprotein. About 50 to 70% of a dose is excreted unchanged in urine, in proportion to creatinine clearance.',
   'Após administração oral, o pico sérico ocorre em 1 a 3 horas; a absorção dos comprimidos é de 60 a 80% (biodisponibilidade absoluta). As refeições abrandam a absorção sem alterar a quantidade total absorvida; a fibra de farelo pode reduzi-la. A ligação às proteínas plasmáticas é de cerca de 25% e o volume de distribuição é grande (475 a 500 L).',
   'After oral administration, peak serum concentrations occur in 1 to 3 hours; tablet absorption is 60 to 80% (absolute bioavailability). Meals slow absorption without changing the total amount absorbed; bran fibre may reduce it. Plasma protein binding is about 25% and the volume of distribution is large (475 to 500 L).',
   'A semivida de eliminação é de 1,5 a 2 dias em voluntários com função renal normal, prolongando-se para 3,5 a 5 dias em doentes anúricos. A dialise remove a digoxina de forma ineficaz.',
   'The elimination half-life is 1.5 to 2 days in volunteers with normal renal function, prolonging to 3.5 to 5 days in anuric patients. Dialysis removes digoxin ineffectively.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Digoxina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967',
   'DailyMed/FDA (NIH/NLM) — approved Digoxin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967'),

  ('doxazosina',
   'Bloqueador alfa-1 usado na hipertensão e na hiperplasia benigna da próstata. Na hipertensão, as reduções máximas da pressão arterial ocorrem 2 a 6 horas após a toma, com maior efeito na posição de pé. Na HPB melhora de forma significativa o débito urinário máximo.',
   'Alpha-1 blocker used in hypertension and benign prostatic hyperplasia. In hypertension, maximum blood pressure reductions occur 2 to 6 hours after dosing, with a greater effect in the standing position. In BPH it significantly improves maximum urinary flow rate.',
   'Bloqueio seletivo dos recetores adrenérgicos alfa-1 (pós-juncionais): reduz a resistência vascular sistémica (efeito anti-hipertensor) e diminui o tónus do músculo liso da próstata, cápsula prostática e colo vesical (melhoria dos sintomas de HPB).',
   'Selective blockade of alpha-1 (postjunctional) adrenergic receptors: reduces systemic vascular resistance (antihypertensive effect) and decreases smooth muscle tone in the prostate, prostatic capsule and bladder neck (improvement of BPH symptoms).',
   'É extensamente metabolizado no fígado, principalmente por O-desmetilação do núcleo quinazolina e hidroxilação; a via principal de eliminação é o CYP3A4, com participação menor do CYP2D6 e CYP2C9. Vários metabolitos são ativos.',
   'Extensively metabolised in the liver, mainly by O-demethylation of the quinazoline nucleus and hydroxylation; the primary elimination pathway is CYP3A4, with a minor contribution from CYP2D6 and CYP2C9. Several metabolites are active.',
   'Após administração oral, o pico plasmático ocorre em cerca de 2 a 3 horas; a biodisponibilidade é de aproximadamente 65% (efeito de primeira passagem). Os alimentos reduzem ligeiramente a Cmax e a AUC sem significado clínico. Liga-se cerca de 98% às proteínas plasmáticas.',
   'After oral administration, peak plasma concentrations occur at about 2 to 3 hours; bioavailability is approximately 65% (first-pass effect). Food slightly reduces Cmax and AUC without clinical significance. It is about 98% bound to plasma proteins.',
   'A eliminação plasmática é bifásica, com semivida terminal de cerca de 22 horas.',
   'Plasma elimination is biphasic, with a terminal half-life of about 22 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Doxazosina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6b887aa5-5edf-48c5-a480-dea8c35afa9d',
   'DailyMed/FDA (NIH/NLM) — approved Doxazosin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6b887aa5-5edf-48c5-a480-dea8c35afa9d'),

  ('dutasterida',
   'Inibidor da 5-alfa-redutase usado na hiperplasia benigna da próstata. Reduz o DHT sérico em 85 a 90% nas primeiras 1 a 2 semanas de tratamento diário; com 0,5 mg/dia durante 4 anos, a redução mediana do DHT foi de 94 a 95%, com aumento da testosterona dentro do intervalo fisiológico.',
   '5-alpha-reductase inhibitor used in benign prostatic hyperplasia. It reduces serum DHT by 85 to 90% within the first 1 to 2 weeks of daily treatment; with 0.5 mg/day for 4 years, the median DHT reduction was 94 to 95%, with an increase in testosterone within the physiological range.',
   'Inibe de forma competitiva e específica as duas isoenzimas da 5-alfa-redutase (tipo 1 e tipo 2), bloqueando a conversão da testosterona em di-hidrotestosterona (DHT), o androgénio responsável pelo desenvolvimento e crescimento da próstata. Não se liga ao recetor androgénico.',
   'Competitively and specifically inhibits both isoforms of 5-alpha-reductase (type 1 and type 2), blocking the conversion of testosterone to dihydrotestosterone (DHT), the androgen responsible for prostate development and growth. It does not bind to the androgen receptor.',
   'É extensamente metabolizado no fígado, sobretudo pelo CYP3A4 e CYP3A5. A dutasterida e os seus metabolitos são excretados principalmente nas fezes (cerca de 5% inalterada e 40% como metabolitos); menos de 1% aparece inalterada na urina.',
   'Extensively metabolised in the liver, mainly by CYP3A4 and CYP3A5. Dutasteride and its metabolites are excreted mainly in faeces (about 5% unchanged and 40% as metabolites); less than 1% is recovered unchanged in urine.',
   'O pico sérico ocorre 2 a 3 horas após a toma. A biodisponibilidade absoluta é de aproximadamente 60% (40 a 94%); os alimentos reduzem a Cmax em 10 a 15% sem significado clínico. O volume de distribuição é grande (300 a 500 L) e a ligação à albumina é de 99%.',
   'Peak serum concentrations occur 2 to 3 hours after dosing. Absolute bioavailability is approximately 60% (40 to 94%); food reduces Cmax by 10 to 15% without clinical significance. The volume of distribution is large (300 to 500 L) and albumin binding is 99%.',
   'A semivida terminal em estado estacionário é de aproximadamente 5 semanas; as concentrações atingem 65% do estado estacionário após 1 mês e cerca de 90% após 3 meses, permanecendo detetáveis 4 a 6 meses após a suspensão.',
   'The terminal half-life at steady state is approximately 5 weeks; concentrations reach 65% of steady state after 1 month and about 90% after 3 months, remaining detectable for 4 to 6 months after discontinuation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dutasterida, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=947644ea-bc35-41df-8a7a-874360c90192',
   'DailyMed/FDA (NIH/NLM) — approved Dutasteride label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=947644ea-bc35-41df-8a7a-874360c90192'),

  ('estradiol',
   'Hormona esteroide essencial para o desenvolvimento e manutenção do sistema reprodutor feminino e das características sexuais secundárias. Na terapêutica hormonal pós-menopausa previne a perda de massa óssea vertebral; após a suspensão, a perda óssea retoma um ritmo comparável ao do pós-menopausa imediato.',
   'Steroid hormone essential for the development and maintenance of the female reproductive system and secondary sexual characteristics. In postmenopausal hormone therapy it prevents vertebral bone loss; after discontinuation, bone loss resumes at a rate comparable to the immediate postmenopausal period.',
   'Os estrogénios ligam-se a recetores nucleares nos tecidos responsivos, modulando a transcrição genética. O estradiol modula a secreção hipofisária de LH e FSH por mecanismo de feedback negativo, reduzindo os níveis elevados destas hormonas na pós-menopausa.',
   'Oestrogens bind to nuclear receptors in responsive tissues, modulating gene transcription. Oestradiol modulates pituitary secretion of LH and FSH through negative feedback, reducing the elevated levels of these hormones in postmenopause.',
   'Os estrogénios exógenos são metabolizados como os endógenos, sobretudo no fígado: o estradiol converte-se reversivelmente em estrona e ambos em estriol; sofrem conjugação com sulfato e glucurónido e recirculação entero-hepática. O CYP3A4 participa parcialmente no metabolismo; indutores e inibidores desta isoenzima podem alterar as concentrações.',
   'Exogenous oestrogens are metabolised like endogenous ones, mainly in the liver: oestradiol is reversibly converted to oestrone and both to oestriol; they undergo sulfate and glucuronide conjugation and enterohepatic recirculation. CYP3A4 partially participates in metabolism; inducers and inhibitors of this isoenzyme may alter concentrations.',
   'Os estrogénios circulam largamente ligados à globulina ligadora das hormonas sexuais (SHBG) e à albumina, distribuindo-se amplamente pelo organismo com concentrações mais elevadas nos órgãos alvo das hormonas sexuais.',
   'Oestrogens circulate largely bound to sex hormone binding globulin (SHBG) and albumin, distributing widely through the body with higher concentrations in the sex hormone target organs.',
   'O rótulo aprovado não apresenta valores de semivida; o estradiol, a estrona e o estriol são excretados na urina como conjugados (glucurónidos e sulfatos), com o sulfato de estrona a funcionar como reservatório circulante de estrogénios mais ativos.',
   'The approved label does not report half-life values; oestradiol, oestrone and oestriol are excreted in urine as conjugates (glucuronides and sulfates), with oestrone sulfate serving as a circulating reservoir of more active oestrogens.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estradiol, secção Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5718f042-e8c0-b721-e063-6294a90a5bef',
   'DailyMed/FDA (NIH/NLM) — approved Estradiol label, Clinical Pharmacology section: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5718f042-e8c0-b721-e063-6294a90a5bef'),

  ('fenitoina',
   'Anticonvulsivante. Os níveis séricos estáveis terapêuticos são alcançados 7 a 10 dias após o início do tratamento com 300 mg/dia (5 a 7 semividas). Devido à cinética saturável, um aumento da dose de 10% ou mais pode produzir aumentos desproporcionados do nível sérico, com risco de intoxicação.',
   'Anticonvulsant. Stable therapeutic serum levels are reached 7 to 10 days after starting treatment with 300 mg/day (5 to 7 half-lives). Because of saturable kinetics, a dose increase of 10% or more can produce disproportionate increases in serum level, with risk of toxicity.',
   'O mecanismo preciso não está estabelecido, mas pensa-se que envolve o bloqueio dependente da voltagem dos canais de sódio da membrana, reduzindo as descargas neuronais sustentadas de alta frequência.',
   'The precise mechanism has not been established but is thought to involve voltage-dependent blockade of membrane sodium channels, reducing sustained high-frequency neuronal discharges.',
   'É metabolizada principalmente no fígado pelo CYP2C9 e, em menor grau, pelo CYP2C19, por hidroxilação saturável a níveis séricos elevados. É um potente indutor das enzimas metabolizadoras hepáticas. A maior parte é excretada na bílis como metabolitos inativos, reabsorvida e eliminada na urina; a excreção renal ocorre por filtração glomerular e sobretudo por secreção tubular.',
   'Mainly metabolised in the liver by CYP2C9 and, to a lesser extent, CYP2C19, by hydroxylation that is saturable at high serum levels. It is a potent inducer of hepatic drug-metabolising enzymes. Most is excreted in bile as inactive metabolites, reabsorbed and eliminated in urine; renal excretion occurs by glomerular filtration and mainly by tubular secretion.',
   'Nas cápsulas de libertação prolongada, os níveis séricos máximos ocorrem 4 a 12 horas após a administração. A fenitoína liga-se extensamente às proteínas plasmáticas; a fração livre pode aumentar na doença renal ou hepática e na hipoalbuminemia.',
   'With extended-release capsules, peak serum levels occur 4 to 12 hours after administration. Phenytoin is extensively bound to plasma proteins; the free fraction may increase in renal or hepatic disease and in hypoalbuminaemia.',
   'A semivida plasmática média após administração oral é de cerca de 22 horas (intervalo de 7 a 42 horas), aumentando com doses na faixa superior devido à cinética saturável.',
   'The mean plasma half-life after oral administration is about 22 hours (range 7 to 42 hours), increasing at doses in the upper range because of saturable kinetics.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fenitoína, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e',
   'DailyMed/FDA (NIH/NLM) — approved Phenytoin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e'),

  ('finasterida',
   'Inibidor da 5-alfa-redutase tipo II usado na hiperplasia benigna da próstata e na alopecia androgénica. Com 5 mg/dia reduz o DHT sérico em cerca de 70% (efeito máximo 8 horas após a primeira dose) e em cerca de 80% o conteúdo de DHT no tecido prostático. O efeito é reversível: o DHT regressa aos valores basais cerca de 2 semanas após a suspensão.',
   'Type II 5-alpha-reductase inhibitor used in benign prostatic hyperplasia and androgenetic alopecia. At 5 mg/day it reduces serum DHT by about 70% (maximum effect 8 hours after the first dose) and prostatic tissue DHT by about 80%. The effect is reversible: DHT returns to baseline about 2 weeks after discontinuation.',
   'Inibe de forma competitiva e específica a 5-alfa-redutase tipo II, bloqueando a conversão da testosterona em 5-alfa-di-hidrotestosterona (DHT) na próstata, fígado e pele. Não tem afinidade para o recetor androgénico.',
   'Competitively and specifically inhibits type II 5-alpha-reductase, blocking the conversion of testosterone to 5-alpha-dihydrotestosterone (DHT) in the prostate, liver and skin. It has no affinity for the androgen receptor.',
   'É extensamente metabolizado no fígado, principalmente pela subfamília CYP3A4. Os metabolitos identificados não possuem mais de 20% da atividade inibitória da 5-alfa-redutase. Cerca de 39% da dose é excretada na urina como metabolitos e 57% nas fezes.',
   'Extensively metabolised in the liver, mainly by the CYP3A4 subfamily. The identified metabolites have no more than 20% of the 5-alpha-reductase inhibitory activity. About 39% of the dose is excreted in urine as metabolites and 57% in faeces.',
   'A biodisponibilidade média é de 63% (34 a 108%), com pico plasmático 1 a 2 horas após a toma; a biodisponibilidade não é afetada pelos alimentos. Cerca de 90% da finasterida circulante liga-se às proteínas plasmáticas e o volume de distribuição é de cerca de 76 L.',
   'Mean bioavailability is 63% (34 to 108%), with peak plasma concentrations 1 to 2 hours after dosing; bioavailability is not affected by food. About 90% of circulating finasteride is bound to plasma proteins and the volume of distribution is about 76 L.',
   'A semivida média de eliminação é de cerca de 6 horas (3 a 16 horas); em indivíduos com 70 ou mais anos é de aproximadamente 8 horas.',
   'The mean elimination half-life is about 6 hours (3 to 16 hours); in subjects aged 70 years or older it is approximately 8 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Finasterida, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=350b2bdb-84a1-4465-b0ad-175b8f720400',
   'DailyMed/FDA (NIH/NLM) — approved Finasteride label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=350b2bdb-84a1-4465-b0ad-175b8f720400'),

  ('glibenclamida',
   'Sulfonilureia que reduz a glicemia de forma aguda ao estimular a libertação de insulina do pâncreas, dependente de células beta funcionais. O efeito hipoglicemiante persiste 24 horas após uma dose matinal em doentes diabéticos. Produz também uma diurese ligeira por aumento da depuração renal de água livre.',
   'Sulfonylurea that acutely lowers blood glucose by stimulating the release of insulin from the pancreas, an effect dependent on functioning beta cells. The blood glucose lowering effect persists for 24 hours following a single morning dose in diabetic patients. It also produces a mild diuresis by enhancing renal free water clearance.',
   'Estimula a libertação de insulina das células beta pancreáticas (dependente de células beta funcionais); podem estar envolvidos efeitos extrapancreáticos. A combinação com metformina tem efeito sinérgico por mecanismos diferentes mas complementares.',
   'Stimulates the release of insulin from pancreatic beta cells (dependent on functioning beta cells); extrapancreatic effects may be involved. The combination with metformin is synergistic through different but complementary mechanisms.',
   'O principal metabolito é o derivado 4-trans-hidroxi e existe um segundo, o 3-cis-hidroxi, ambos com atividade hipoglicemiante fraca. A glibenclamida é excretada como metabolitos na bílis e na urina, aproximadamente 50% por cada via — padrão diferente das outras sulfonilureias, eliminadas sobretudo na urina.',
   'The major metabolite is the 4-trans-hydroxy derivative, with a second, the 3-cis-hydroxy derivative; both have weak hypoglycaemic activity. Glyburide is excreted as metabolites in bile and urine, approximately 50% by each route — a pattern different from other sulfonylureas, which are eliminated mainly in urine.',
   'Absorção significativa na primeira hora após a toma, pico de concentração plasmática cerca de 4 horas e níveis baixos mas detetáveis às 24 horas. As sulfonilureias ligam-se extensamente às proteínas séricas; a ligação da glibenclamida é predominantemente não iónica.',
   'Significant absorption within one hour of dosing, peak plasma concentrations at about 4 hours and low but detectable levels at 24 hours. Sulfonylureas are extensively bound to serum proteins; glyburide binding is predominantly non-ionic.',
   'O decréscimo da glibenclamida no soro é bifásico, com semivida terminal de cerca de 10 horas.',
   'The decline of glyburide in serum is biphasic, with a terminal half-life of about 10 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Glibenclamida, secções Actions e Pharmacokinetics: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524eec41-37ee-419a-b7a1-d23e888ae6ab',
   'DailyMed/FDA (NIH/NLM) — approved Glyburide label, Actions and Pharmacokinetics sections: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524eec41-37ee-419a-b7a1-d23e888ae6ab'),

  ('gliclazida',
   'Sulfonilureia de segunda geração indicada na diabetes tipo 2 quando dieta, exercício e perda de peso são insuficientes. Restaura o pico precoce de secreção de insulina estimulada pela glicose e reduz a hiperglicemia pós-prandial; reduz a hemoglobina glicada (HbA1c) e a glicemia.',
   'Second-generation sulfonylurea indicated in type 2 diabetes when diet, exercise and weight loss are insufficient. It restores the early peak of glucose-stimulated insulin secretion and reduces postprandial hyperglycaemia; it reduces glycated haemoglobin (HbA1c) and blood glucose.',
   'Sulfonilureia: liga-se ao recetor da sulfonilureia na membrana das células beta pancreáticas, fechando o canal de potássio sensível ao ATP; a despolarização resultante abre canais de cálcio dependentes da voltagem e estimula a libertação de insulina. Tem também propriedades antioxidantes e hemovasculares descritas na SmPC.',
   'Sulfonylurea: binds to the sulfonylurea receptor on pancreatic beta-cell membranes, closing the ATP-sensitive potassium channel; the resulting depolarisation opens voltage-dependent calcium channels and stimulates insulin release. It also has antioxidant and haemovascular properties described in the SmPC.',
   'É extensamente metabolizada no fígado (hidroxilação e oxidação), com formação de metabolitos sem atividade hipoglicemiante relevante. Os metabolitos são eliminados na urina (60 a 70%) e nas fezes (10 a 20%).',
   'Extensively metabolised in the liver (hydroxylation and oxidation), with formation of metabolites without relevant hypoglycaemic activity. The metabolites are eliminated in urine (60 to 70%) and faeces (10 to 20%).',
   'Bem absorvida após administração oral; as concentrações plasmáticas máximas são atingidas entre 2 e 6 horas após a toma. A ligação às proteínas plasmáticas é de cerca de 94%.',
   'Well absorbed after oral administration; peak plasma concentrations are reached between 2 and 6 hours after dosing. Plasma protein binding is about 94%.',
   'A semivida de eliminação é da ordem das 10 a 20 horas, permitindo a toma diária; a semivida pode prolongar-se nos idosos e com doses elevadas.',
   'The elimination half-life is of the order of 10 to 20 hours, allowing daily dosing; the half-life may be prolonged in the elderly and with high doses.',
   'EMC-UK — SmPC Gliclazida 40 mg (Brown & Burk UK Ltd), secção 5.2 Pharmacokinetic properties: https://www.medicines.org.uk/emc/product/13135/smpc',
   'EMC-UK — Gliclazide 40 mg SmPC (Brown & Burk UK Ltd), section 5.2 Pharmacokinetic properties: https://www.medicines.org.uk/emc/product/13135/smpc'),

  ('glimepirida',
   'Sulfonilureia que reduz a glicemia principalmente ao estimular a libertação de insulina das células beta pancreáticas. O efeito máximo (glicemia mínima) ocorre cerca de 2 a 3 horas após doses orais únicas. Melhora a HbA1c, a glicemia em jejum e a glicemia pós-prandial.',
   'Sulfonylurea that lowers blood glucose primarily by stimulating insulin release from pancreatic beta cells. The maximum effect (minimum blood glucose) occurs about 2 to 3 hours after single oral doses. It improves HbA1c, fasting plasma glucose and postprandial glucose.',
   'Liga-se ao recetor da sulfonilureia na membrana plasmática das células beta, fechando o canal de potássio sensível ao ATP e estimulando a libertação de insulina.',
   'Binds to the sulfonylurea receptor in the pancreatic beta-cell plasma membrane, closing the ATP-sensitive potassium channel and stimulating insulin release.',
   'É completamente metabolizada por biotransformação oxidativa: o CYP2C9 converte a glimepirida no metabolito M1 (cerca de um terço da atividade), depois convertido no M2 inativo. Cerca de 60% da radioatividade é recuperada na urina em 7 dias e 40% nas fezes; não se recupera fármaco inalterado.',
   'Completely metabolised by oxidative biotransformation: CYP2C9 converts glimepiride to the M1 metabolite (about one third of the activity), which is then converted to the inactive M2. About 60% of the radioactivity is recovered in urine within 7 days and 40% in faeces; no parent drug is recovered.',
   'O pico de concentração ocorre 2 a 3 horas após a dose. A biodisponibilidade é essencialmente completa; os alimentos reduzem a Cmax e a AUC em 8 e 9%. A ligação às proteínas é superior a 99,5% e o volume de distribuição é de 8,8 L.',
   'Peak concentrations occur 2 to 3 hours after dosing. Bioavailability is essentially complete; food decreases Cmax and AUC by 8 and 9%. Protein binding is greater than 99.5% and the volume of distribution is 8.8 L.',
   'Após administração intravenosa, a semivida terminal é de cerca de 5 horas em dose única, prolongando-se para cerca de 9 horas com doses múltiplas; a semivida não se altera na insuficiência renal.',
   'After intravenous administration, the terminal half-life is about 5 hours after a single dose, prolonging to about 9 hours with multiple dosing; the half-life is unchanged in renal impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Glimepirida, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc9d8495-184c-3af1-e053-6394a90a5e29',
   'DailyMed/FDA (NIH/NLM) — approved Glimepiride label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc9d8495-184c-3af1-e053-6394a90a5e29'),

  ('levonorgestrel',
   'Progestina utilizada em contraceção oral combinada (com etinilestradiol) e em contraceção de emergência. Nos contracetivos orais, a prevenção da gravidez resulta sobretudo da supressão da ovulação.',
   'Progestin used in combined oral contraception (with ethinyl estradiol) and in emergency contraception. In oral contraceptives, pregnancy prevention results mainly from suppression of ovulation.',
   'O levonorgestrel é um progestativo que suprime a ovulação (mecanismo principal nos contracetivos combinados), aumenta a viscosidade do muco cervical e altera o endométrio.',
   'Levonorgestrel is a progestin that suppresses ovulation (main mechanism in combined contraceptives), increases cervical mucus viscosity and alters the endometrium.',
   'Após absorção, o levonorgestrel é conjugado na posição 17-beta-OH (sulfato e, em menor grau, glucurónido); os metabolitos de fase I são excretados sobretudo como glucurónidos. O etinilestradiol sofre 2-hidroxilação hepática pelo CYP3A4. Cerca de 45% do levonorgestrel e metabolitos é excretado na urina e 32% nas fezes.',
   'After absorption, levonorgestrel is conjugated at the 17-beta-OH position (sulfate and, to a lesser extent, glucuronide); the phase I metabolites are excreted mainly as glucuronides. Ethinyl estradiol undergoes hepatic 2-hydroxylation by CYP3A4. About 45% of levonorgestrel and its metabolites is excreted in urine and 32% in faeces.',
   'O levonorgestrel é completamente absorvido (biodisponibilidade de quase 100%, sem efeito de primeira passagem), com pico plasmático em cerca de 1,3 horas; o etinilestradiol tem biodisponibilidade de cerca de 43%. O levonorgestrel liga-se 97,5 a 99% às proteínas, sobretudo à SHBG.',
   'Levonorgestrel is completely absorbed (bioavailability of nearly 100%, without first-pass metabolism), with peak plasma concentrations in about 1.3 hours; ethinyl estradiol has a bioavailability of about 43%. Levonorgestrel is 97.5 to 99% protein-bound, mainly to SHBG.',
   'A semivida terminal do levonorgestrel é de cerca de 34 horas e a do etinilestradiol de cerca de 18 horas; o etinilestradiol sofre recirculação entero-hepática.',
   'The terminal half-life of levonorgestrel is about 34 hours and that of ethinyl estradiol about 18 hours; ethinyl estradiol undergoes enterohepatic recirculation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levonorgestrel/Etinilestradiol (contracetivo oral combinado), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2396d26d-c419-4eca-b5ba-b78becc16fde',
   'DailyMed/FDA (NIH/NLM) — approved Levonorgestrel/Ethinyl estradiol (combined oral contraceptive) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2396d26d-c419-4eca-b5ba-b78becc16fde'),

  ('levotiroxina',
   'Hormona tiroideia sintética (T4) que exerce o mesmo efeito fisiológico da T4 endógena, mantendo níveis normais quando existe deficiência. O início e a duração do efeito dependem da semivida longa da T4, sendo necessários ajustes de dose com base no TSH.',
   'Synthetic thyroid hormone (T4) that exerts the same physiological effect as endogenous T4, maintaining normal levels when a deficiency exists. The onset and duration of effect depend on the long half-life of T4, with dose adjustments based on TSH.',
   'As hormonas tiroideias exercem as suas ações fisiológicas através do controlo da transcrição do DNA e da síntese proteica: a T3 e a T4 difundem-se para o núcleo celular e ligam-se a proteínas recetoras da hormona tiroideia ligadas ao DNA, ativando a transcrição genética. A maioria da ação é produzida pela T3, cerca de 80% derivada da T4 por deiodinação periférica.',
   'Thyroid hormones exert their physiological actions through control of DNA transcription and protein synthesis: T3 and T4 diffuse into the cell nucleus and bind to thyroid receptor proteins attached to DNA, activating gene transcription. Most of the action is produced by T3, about 80% of which is derived from T4 by peripheral deiodination.',
   'A via principal do metabolismo é a deiodinação sequencial; as hormonas são também conjugadas com glucurónidos e sulfatos e excretadas na bílis, com recirculação entero-hepática. As hormonas tiroideias são eliminadas sobretudo pelos rins; cerca de 20% da T4 é eliminada nas fezes.',
   'The major metabolic pathway is sequential deiodination; the hormones are also conjugated with glucuronides and sulfates and excreted in bile, with enterohepatic recirculation. Thyroid hormones are eliminated mainly by the kidneys; about 20% of T4 is eliminated in faeces.',
   'A absorção oral da T4 varia entre 40 e 80%, ocorrendo sobretudo no jejuno e íleon superior. O jejum aumenta a absorção; a fibra alimentar, a soja e as síndromes de má absorção diminuem-na. Mais de 99% das hormonas circulantes ligam-se a proteínas plasmáticas (TBG, TBPA e albumina).',
   'Oral absorption of T4 ranges from 40 to 80%, occurring mainly in the jejunum and upper ileum. Fasting increases absorption; dietary fibre, soybeans and malabsorption syndromes decrease it. More than 99% of circulating hormones are bound to plasma proteins (TBG, TBPA and albumin).',
   'A semivida da T4 é de 6 a 7 dias em doentes eutiroideus (3 a 4 dias no hipertiroidismo e 9 a 10 dias no hipotiroidismo), o que justifica a toma diária única e o ajuste lento da dose.',
   'The half-life of T4 is 6 to 7 days in euthyroid patients (3 to 4 days in hyperthyroidism and 9 to 10 days in hypothyroidism), which justifies once-daily dosing and slow dose titration.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levotiroxina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4ddcaec1-a58f-340b-9bc1-bbe048b8c885',
   'DailyMed/FDA (NIH/NLM) — approved Levothyroxine label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4ddcaec1-a58f-340b-9bc1-bbe048b8c885'),

  ('metformina',
   'Anti-hiperglicemiante da classe das biguanidas que melhora a tolerância à glicose na diabetes tipo 2, reduzindo a glicemia basal e pós-prandial. Não estimula a secreção de insulina, pelo que não causa hipoglicemia quando usada isolada; a secreção de insulina permanece inalterada, podendo diminuir a insulinemia de jejum.',
   'Antihyperglycaemic agent of the biguanide class that improves glucose tolerance in type 2 diabetes, lowering both basal and postprandial plasma glucose. It does not stimulate insulin secretion, so it does not cause hypoglycaemia when used alone; insulin secretion remains unchanged, while fasting insulin levels may decrease.',
   'Diminui a produção hepática de glicose, diminui a absorção intestinal de glicose e melhora a sensibilidade à insulina, aumentando a captação e utilização periférica de glicose.',
   'Decreases hepatic glucose production, decreases intestinal absorption of glucose and improves insulin sensitivity by increasing peripheral glucose uptake and utilisation.',
   'A metformina é excretada inalterada na urina e não sofre metabolismo hepático (não foram identificados metabolitos no homem) nem excreção biliar. A depuração renal é cerca de 3,5 vezes superior à depuração da creatinina, indicando que a secreção tubular é a via principal de eliminação; cerca de 90% do fármaco absorvido é eliminado por via renal nas primeiras 24 horas.',
   'Metformin is excreted unchanged in urine and undergoes no hepatic metabolism (no metabolites have been identified in humans) nor biliary excretion. Renal clearance is about 3.5 times greater than creatinine clearance, indicating that tubular secretion is the major route of elimination; about 90% of the absorbed drug is eliminated renally within the first 24 hours.',
   'Nos comprimidos de libertação prolongada, o pico plasmático é atingido em mediana às 7 horas (4 a 8 horas); nos comprimidos de libertação imediata, em 2 a 3 horas. Os alimentos diminuem a extensão e atrasam a absorção (Cmax cerca de 40% menor). A ligação às proteínas plasmáticas é desprezável.',
   'With extended-release tablets, peak plasma concentrations are reached at a median of 7 hours (4 to 8 hours); with immediate-release tablets, in 2 to 3 hours. Food decreases the extent and delays the absorption (Cmax about 40% lower). Plasma protein binding is negligible.',
   'A semivida de eliminação plasmática é de aproximadamente 6,2 horas; no sangue, a semivida é de aproximadamente 17,6 horas, sugerindo que a massa eritrocitária é um compartimento de distribuição.',
   'The plasma elimination half-life is approximately 6.2 hours; in blood, the half-life is approximately 17.6 hours, suggesting that the erythrocyte mass is a compartment of distribution.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metformina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c1bfc7b5-c7e0-4353-b772-05d463c12886',
   'DailyMed/FDA (NIH/NLM) — approved Metformin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c1bfc7b5-c7e0-4353-b772-05d463c12886'),

  ('metronidazol',
   'Antibiótico e antiprotozoário com atividade bactericida contra anaeróbios e contra Trichomonas, Giardia e Entamoeba. As concentrações plasmáticas são proporcionais à dose: 250, 500 e 2.000 mg produzem picos de 6, 12 e 40 mcg/ml, respetivamente.',
   'Antibiotic and antiprotozoal agent with bactericidal activity against anaerobes and against Trichomonas, Giardia and Entamoeba. Plasma concentrations are proportional to the dose: 250, 500 and 2,000 mg produce peaks of 6, 12 and 40 mcg/ml, respectively.',
   'Pró-fármaco: o grupo nitro é reduzido intracelularmente nos microrganismos anaeróbios, gerando intermediários reativos que danificam o DNA e inibem a síntese de ácidos nucleicos.',
   'Prodrug: the nitro group is reduced intracellularly in anaerobic microorganisms, generating reactive intermediates that damage DNA and inhibit nucleic acid synthesis.',
   'A principal via de eliminação do metronidazol e dos seus metabolitos é a urina (60 a 80% da dose), com excreção fecal de 6 a 15%. Os metabolitos resultam sobretudo da oxidação da cadeia lateral e da conjugação com glucurónido; o composto inalterado representa cerca de 20% do total. O metabolito hidroxilado mantém atividade antimicrobiana.',
   'The major route of elimination of metronidazole and its metabolites is urine (60 to 80% of the dose), with faecal excretion of 6 to 15%. The metabolites result mainly from side-chain oxidation and glucuronide conjugation; unchanged drug accounts for about 20% of the total. The hydroxy metabolite retains antimicrobial activity.',
   'Bem absorvido após administração oral, com pico plasmático entre 1 e 2 horas. Menos de 20% liga-se às proteínas plasmáticas. Aparece no líquido cefalorraquidiano, saliva e leite materno em concentrações semelhantes às plasmáticas.',
   'Well absorbed after oral administration, with peak plasma concentrations between 1 and 2 hours. Less than 20% is bound to plasma proteins. It appears in cerebrospinal fluid, saliva and breast milk at concentrations similar to plasma.',
   'A semivida média de eliminação em indivíduos saudáveis é de cerca de 8 horas.',
   'The mean elimination half-life in healthy subjects is about 8 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol, secção Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6',
   'DailyMed/FDA (NIH/NLM) — approved Metronidazole label, Clinical Pharmacology section: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6'),

  ('nitrofurantoina',
   'Antibacteriano indicado no tratamento e prevenção de infeções urinárias. Concentra-se na urina (a que confere frequentemente uma cor castanha), onde exerce a sua ação; as concentrações plasmáticas após dose oral são baixas, com picos habitualmente inferiores a 1 mcg/ml.',
   'Antibacterial agent indicated for the treatment and prevention of urinary tract infections. It concentrates in urine (to which it often imparts a brown colour), where it exerts its action; plasma concentrations after an oral dose are low, with peaks usually below 1 mcg/ml.',
   'A redução intracelular da nitrofurantoína gera intermediários reativos que inibem enzimas bacterianas e danificam o DNA, o RNA e outras macromoléculas das bactérias sensíveis.',
   'Intracellular reduction of nitrofurantoin generates reactive intermediates that inhibit bacterial enzymes and damage DNA, RNA and other macromolecules of susceptible bacteria.',
   'A nitrofurantoína é rapidamente absorvida e grande parte é metabolizada nos tecidos; cerca de 20 a 25% de uma dose única é recuperada inalterada na urina em 24 horas.',
   'Nitrofurantoin is rapidly absorbed and a large proportion is metabolised in the tissues; about 20 to 25% of a single dose is recovered unchanged in urine within 24 hours.',
   'A cápsula contém duas formas: 25% macrocristalina (dissolução e absorção mais lentas) e 75% mono-hidrato, que forma uma matriz de gel libertando o fármaco ao longo do tempo. Quando administrada com alimentos, a biodisponibilidade aumenta em cerca de 40%.',
   'The capsule contains two forms: 25% macrocrystalline (slower dissolution and absorption) and 75% monohydrate, which forms a gel matrix releasing the drug over time. When administered with food, bioavailability increases by about 40%.',
   'A semivida plasmática é curta (da ordem de 20 a 60 minutos), refletindo a rápida metabolização e eliminação; o fármaco é altamente solúvel na urina.',
   'The plasma half-life is short (of the order of 20 to 60 minutes), reflecting rapid metabolism and elimination; the drug is highly soluble in urine.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nitrofurantoína, secção Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55c75f27-b5fc-4f19-8607-08f8ec0c69ec',
   'DailyMed/FDA (NIH/NLM) — approved Nitrofurantoin label, Clinical Pharmacology section: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55c75f27-b5fc-4f19-8607-08f8ec0c69ec'),

  ('omeprazol',
   'Inibidor da bomba de protões: o efeito antissecretor começa dentro de uma hora, com máximo em duas horas; a inibição é de cerca de 50% do máximo às 24 horas e pode durar até 72 horas, devido à ligação prolongada à bomba H+/K+-ATPase. Após a suspensão, a secreção ácida regressa gradualmente em 3 a 5 dias.',
   'Proton pump inhibitor: the antisecretory effect begins within one hour, with maximum within two hours; inhibition is about 50% of maximum at 24 hours and can last up to 72 hours, due to prolonged binding to the H+/K+-ATPase pump. After discontinuation, acid secretion returns gradually over 3 to 5 days.',
   'Inibe especificamente o sistema enzimático H+/K+-ATPase (bomba de protões) na superfície secretora da célula parietal gástrica, bloqueando o passo final da produção de ácido; o efeito é dependente da dose e inibe a secreção ácida basal e estimulada, qualquer que seja o estímulo.',
   'Specifically inhibits the H+/K+-ATPase enzyme system (proton pump) at the secretory surface of the gastric parietal cell, blocking the final step of acid production; the effect is dose-related and inhibits both basal and stimulated acid secretion, irrespective of the stimulus.',
   'É extensamente metabolizado no fígado pelo citocromo P450: a maior parte depende do CYP2C19 (formação do hidroxiomeprazol) e o restante do CYP3A4 (formação da sulfona do omeprazol). Cerca de 77% da dose é eliminada na urina como, pelo menos, seis metabolitos; o restante é recuperado nas fezes (excreção biliar significativa).',
   'Extensively metabolised in the liver by the cytochrome P450 system: most depends on CYP2C19 (formation of hydroxyomeprazole) and the remainder on CYP3A4 (formation of omeprazole sulphone). About 77% of the dose is eliminated in urine as at least six metabolites; the remainder is recovered in faeces (significant biliary excretion).',
   'A absorção começa apenas depois de os grânulos com revestimento entérico saírem do estômago; o pico plasmático ocorre 0,5 a 3,5 horas após a toma. A biodisponibilidade absoluta é de cerca de 30 a 40% (20 a 40 mg), devido sobretudo ao efeito de primeira passagem. A ligação às proteínas plasmáticas é de cerca de 95%.',
   'Absorption begins only after the enteric-coated granules leave the stomach; peak plasma concentrations occur 0.5 to 3.5 hours after dosing. Absolute bioavailability is about 30 to 40% (20 to 40 mg), largely due to first-pass metabolism. Plasma protein binding is about 95%.',
   'A semivida plasmática em indivíduos saudáveis é de 0,5 a 1 hora; em doentes com doença hepática crónica prolonga-se para cerca de 3 horas. A semivida curta contrasta com a duração prolongada do efeito antissecretor.',
   'The plasma half-life in healthy subjects is 0.5 to 1 hour; in patients with chronic hepatic disease it prolongs to about 3 hours. The short half-life contrasts with the prolonged duration of the antisecretory effect.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Omeprazol, secções 12.1 a 12.3: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66',
   'DailyMed/FDA (NIH/NLM) — approved Omeprazole label, sections 12.1 to 12.3: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6ea9a6f3-b756-4cdf-b3db-f666a2c17d66'),

  ('pioglitazona',
   'Tiazolidinediona que melhora o controlo glicémico na diabetes tipo 2: reduz a resistência à insulina, com diminuição da glicemia, da insulinemia e da HbA1c. Nos doentes com dislipidemia, reduz os triglicéridos séricos e aumenta o colesterol HDL. Efeito aditivo quando combinada com sulfonilureias, metformina ou insulina.',
   'Thiazolidinedione that improves glycaemic control in type 2 diabetes: it reduces insulin resistance, with decreases in plasma glucose, plasma insulin and HbA1c. In patients with dyslipidaemia it lowers serum triglycerides and increases HDL cholesterol. Additive effect when combined with sulfonylureas, metformin or insulin.',
   'Agonista dos recetores ativados pelo proliferador de peroxissomas gama (PPAR-gama), que modula a transcrição de genes responsivos à insulina envolvidos no controlo do metabolismo da glicose e dos lípidos. Diminui a resistência à insulina na periferia e no fígado; não é um secretagogo da insulina.',
   'Agonist of peroxisome proliferator-activated receptor-gamma (PPAR-gamma), which modulates the transcription of insulin-responsive genes involved in glucose and lipid metabolism control. It decreases insulin resistance in the periphery and in the liver; it is not an insulin secretagogue.',
   'É extensamente metabolizada por hidroxilação e oxidação (com conjugação parcial em glucurónidos e sulfatos). O CYP2C8 é a isoenzima principal, com participação menor do CYP3A4; os metabolitos ativos M-III e M-IV são os principais na circulação. Cerca de 15 a 30% da dose é recuperada na urina; o restante é excretado na bílis e eliminado nas fezes.',
   'Extensively metabolised by hydroxylation and oxidation (with partial conjugation to glucuronides and sulfates). CYP2C8 is the main isoenzyme, with a minor contribution from CYP3A4; the active metabolites M-III and M-IV predominate in the circulation. About 15 to 30% of the dose is recovered in urine; the remainder is excreted in bile and eliminated in faeces.',
   'O pico plasmático ocorre nas 2 horas após a toma; os alimentos atrasam o pico para 3 a 4 horas sem alterar a extensão da absorção. Liga-se extensamente às proteínas plasmáticas (mais de 99%), sobretudo à albumina; o volume de distribuição aparente é de 0,63 L/kg.',
   'Peak plasma concentrations occur within 2 hours of dosing; food delays the peak to 3 to 4 hours without changing the extent of absorption. It is extensively bound to plasma proteins (over 99%), mainly albumin; the apparent volume of distribution is 0.63 L/kg.',
   'A semivida sérica média da pioglitazona é de 3 a 7 horas e a dos metabolitos ativos M-III e M-IV de 16 a 24 horas.',
   'The mean serum half-life of pioglitazone is 3 to 7 hours and that of the active metabolites M-III and M-IV 16 to 24 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Pioglitazona, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=31619517-a590-408a-ae9e-76c99f0a0a1d',
   'DailyMed/FDA (NIH/NLM) — approved Pioglitazone label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=31619517-a590-408a-ae9e-76c99f0a0a1d'),

  ('prednisolona',
   'Glucocorticóide sintético com propriedades predominantemente glucocorticoides, usado sobretudo pelos seus potentes efeitos anti-inflamatórios e imunossupressores. Promove a gliconeogénese, aumenta o catabolismo proteico e a lipólise, inibe os processos inflamatórios (edema, deposição de fibrina, dilatação capilar, migração de leucócitos e fagocitose) e suprime a produção de corticotropina. Tem ligeira atividade mineralocorticoide.',
   'Synthetic glucocorticoid with predominantly glucocorticoid properties, used mainly for its potent anti-inflammatory and immunosuppressive effects. It promotes gluconeogenesis, increases protein catabolism and lipolysis, inhibits inflammatory processes (oedema, fibrin deposition, capillary dilatation, leucocyte migration and phagocytosis) and suppresses corticotropin production. It has slight mineralocorticoid activity.',
   'Liga-se ao recetor dos glucocorticoides, modulando a transcrição genética; os efeitos farmacológicos resultam da regulação da expressão de genes pró- e anti-inflamatórios.',
   'Binds to the glucocorticoid receptor, modulating gene transcription; the pharmacological effects result from regulation of the expression of pro- and anti-inflammatory genes.',
   'É metabolizada principalmente no fígado e excretada na urina como conjugados de sulfato e glucurónido; existe interconversão reversível com a prednisona.',
   'Mainly metabolised in the liver and excreted in urine as sulfate and glucuronide conjugates; reversible interconversion with prednisone occurs.',
   'Bem absorvida após administração oral. Liga-se 70 a 90% às proteínas plasmáticas e o volume de distribuição é de 0,22 a 0,7 L/kg.',
   'Well absorbed after oral administration. It is 70 to 90% bound to plasma proteins and the volume of distribution is 0.22 to 0.7 L/kg.',
   'A prednisolona é eliminada do plasma com uma semivida média de cerca de 2,6 horas (2 a 3,5 horas).',
   'Prednisolone is eliminated from plasma with a mean half-life of about 2.6 hours (2 to 3.5 hours).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Prednisolona (Orapred ODT), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e379543-c4cf-4e72-953b-db15b7f0c2a1',
   'DailyMed/FDA (NIH/NLM) — approved Prednisolone (Orapred ODT) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e379543-c4cf-4e72-953b-db15b7f0c2a1'),

  ('sildenafil',
   'Inibidor da PDE5 usado na disfunção erétil. Melhora as ereções durante a estimulação sexual (avaliadas objetivamente), com efeito até cerca de 4 horas após a toma. Produz uma redução ligeira da pressão arterial (diminuição máxima média de 8,3/5,3 mmHg); potencia o efeito hipotensor dos nitratos, pelo que a associação é contraindicada.',
   'PDE5 inhibitor used in erectile dysfunction. It improves erections during sexual stimulation (assessed objectively), with an effect for up to about 4 hours after dosing. It produces a slight blood pressure reduction (mean maximum decrease of 8.3/5.3 mmHg); it potentiates the hypotensive effect of nitrates, so the combination is contraindicated.',
   'Inibe seletivamente a fosfodiesterase tipo 5 (PDE5), responsável pela degradação do cGMP no corpo cavernoso; o aumento do cGMP produz relaxamento do músculo liso e influxo sanguíneo. Sem estimulação sexual (libertação de óxido nítrico), não tem efeito. É cerca de 4.000 vezes mais seletivo para a PDE5 do que para a PDE3.',
   'Selectively inhibits phosphodiesterase type 5 (PDE5), responsible for cGMP degradation in the corpus cavernosum; increased cGMP produces smooth muscle relaxation and blood inflow. Without sexual stimulation (nitric oxide release) it has no effect. It is about 4,000-fold more selective for PDE5 than for PDE3.',
   'Metabolizado no fígado, principalmente pelo CYP3A4 (via principal) e, em menor grau, pelo CYP2C9. O metabolito principal, o N-desmetilsildenafil, tem cerca de 50% da potência do composto original. Cerca de 80% da dose é excretada nas fezes e 13% na urina.',
   'Metabolised in the liver, mainly by CYP3A4 (main pathway) and, to a lesser extent, by CYP2C9. The main metabolite, N-desmethylsildenafil, has about 50% of the potency of the parent compound. About 80% of the dose is excreted in faeces and 13% in urine.',
   'Rapidamente absorvido, com pico plasmático 30 a 120 minutos após a toma (mediana de 60 minutos em jejum). A biodisponibilidade absoluta é de cerca de 41%. Uma refeição rica em gordura reduz a velocidade de absorção. Liga-se cerca de 96% às proteínas plasmáticas.',
   'Rapidly absorbed, with peak plasma concentrations 30 to 120 minutes after dosing (median 60 minutes when fasted). Absolute bioavailability is about 41%. A high-fat meal reduces the rate of absorption. It is about 96% bound to plasma proteins.',
   'A semivida de eliminação é de cerca de 3 a 5 horas (4 horas); 24 horas após uma dose de 100 mg, as concentrações plasmáticas são de aproximadamente 2 ng/ml.',
   'The elimination half-life is about 3 to 5 hours (4 hours); 24 hours after a 100 mg dose, plasma concentrations are approximately 2 ng/ml.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Sildenafil, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b',
   'DailyMed/FDA (NIH/NLM) — approved Sildenafil label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00ee09dd-2de0-4dc4-85f6-b51ed6eabd5b'),

  ('tadalafil',
   'Inibidor da PDE5 de longa duração, usado na disfunção erétil e nos sintomas da hiperplasia benigna da próstata. Em doses terapêuticas não produz alteração significativa da pressão arterial, mas potencia o efeito hipotensor dos nitratos — a associação é contraindicada e deve mediar um intervalo de pelo menos 48 horas após a última toma.',
   'Long-acting PDE5 inhibitor used in erectile dysfunction and in benign prostatic hyperplasia symptoms. At therapeutic doses it produces no significant blood pressure change, but it potentiates the hypotensive effect of nitrates — the combination is contraindicated, with at least 48 hours to elapse after the last dose.',
   'Inibe seletivamente a PDE5, aumentando o cGMP no corpo cavernoso, na próstata e na bexiga e na sua vascularização; a inibição não tem efeito sem estimulação sexual. É mais de 10.000 vezes mais potente para a PDE5 do que para as PDE1, 2, 3, 4, 7, 8, 9 e 10, e 700 vezes mais potente do que para a PDE6.',
   'Selectively inhibits PDE5, increasing cGMP in the corpus cavernosum, prostate, bladder and their vascular supply; inhibition has no effect without sexual stimulation. It is more than 10,000-fold more potent for PDE5 than for PDE1, 2, 3, 4, 7, 8, 9 and 10, and 700-fold more potent than for PDE6.',
   'É predominantemente metabolizado pelo CYP3A4 num metabolito catecol, que sofre metilação e glucuronidação extensas; o principal metabolito circulante é o metilcatecol glucurónido, sem atividade farmacológica relevante. É excretado sobretudo como metabolitos, principalmente nas fezes (cerca de 61%) e, em menor grau, na urina (cerca de 36%).',
   'Predominantly metabolised by CYP3A4 to a catechol metabolite, which undergoes extensive methylation and glucuronidation; the major circulating metabolite is methylcatechol glucuronide, without relevant pharmacological activity. Excreted mainly as metabolites, chiefly in faeces (about 61%) and, to a lesser extent, in urine (about 36%).',
   'Após dose oral única, a Cmax é atingida entre 30 minutos e 6 horas (mediana de 2 horas). A taxa e a extensão da absorção não são influenciadas pelos alimentos. O volume aparente de distribuição é de cerca de 63 L e a ligação às proteínas plasmáticas é de 94%.',
   'After a single oral dose, Cmax is reached between 30 minutes and 6 hours (median 2 hours). The rate and extent of absorption are not influenced by food. The apparent volume of distribution is about 63 L and plasma protein binding is 94%.',
   'A semivida terminal média é de 17,5 horas em indivíduos saudáveis, o que permite a toma diária única.',
   'The mean terminal half-life is 17.5 hours in healthy subjects, allowing once-daily dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tadalafil, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcd8f8ab-81a2-4891-83db-24a0b0e25895',
   'DailyMed/FDA (NIH/NLM) — approved Tadalafil label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcd8f8ab-81a2-4891-83db-24a0b0e25895'),

  ('tamoxifeno',
   'Modulador seletivo do recetor de estrogénio (antiestrogénio não esteroide) usado no cancro da mama com recetores hormonais positivos. No ensaio de prevenção NSABP P-1, reduziu a incidência de cancro da mama invasivo em 44%. O benefício é maior com cerca de 5 anos de tratamento.',
   'Selective oestrogen receptor modulator (nonsteroidal antioestrogen) used in hormone receptor-positive breast cancer. In the NSABP P-1 prevention trial it reduced the incidence of invasive breast cancer by 44%. Benefit is greater with about 5 years of treatment.',
   'Competes com o estradiol pelos locais de ligação nos tecidos alvo, como a mama, exercendo efeito antiestrogénico; o efeito antitumoral resulta da ligação ao recetor de estrogénio.',
   'Competes with oestradiol for binding sites in target tissues such as the breast, exerting an antioestrogenic effect; the antitumour effect results from oestrogen receptor binding.',
   'É extensamente metabolizado após administração oral. O N-desmetiltamoxifeno é o principal metabolito plasmático, com atividade biológica semelhante à do tamoxifeno; o 4-hidroxitamoxifeno é um metabolito menor. É substrato do CYP3A, 2C9 e 2D6 e inibidor da glicoproteína P. Cerca de 65% da dose é excretada em 2 semanas, com excreção fecal como via principal.',
   'Extensively metabolised after oral administration. N-desmethyltamoxifen is the major plasma metabolite, with biological activity similar to tamoxifen; 4-hydroxytamoxifen is a minor metabolite. It is a substrate of CYP3A, 2C9 and 2D6 and an inhibitor of P-glycoprotein. About 65% of the dose is excreted within 2 weeks, with faecal excretion as the primary route.',
   'Após dose oral única de 20 mg, o pico plasmático médio de cerca de 40 ng/ml ocorre cerca de 5 horas após a toma; o estado estacionário é atingido em cerca de 4 semanas (tamoxifeno) e 8 semanas (N-desmetiltamoxifeno). A ligação às proteínas plasmáticas é elevada (cerca de 99%).',
   'After a single 20 mg oral dose, the mean peak plasma concentration of about 40 ng/ml occurs about 5 hours after dosing; steady state is reached in about 4 weeks (tamoxifen) and 8 weeks (N-desmethyltamoxifen). Plasma protein binding is high (about 99%).',
   'A semivida terminal de eliminação do tamoxifeno é de cerca de 5 a 7 dias; a do metabolito N-desmetiltamoxifeno é de aproximadamente 14 dias.',
   'The terminal elimination half-life of tamoxifen is about 5 to 7 days; that of the N-desmethyltamoxifen metabolite is approximately 14 days.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tamoxifeno, secção Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=509f8ba3-214d-aec8-e063-6294a90af498',
   'DailyMed/FDA (NIH/NLM) — approved Tamoxifen label, Clinical Pharmacology section: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=509f8ba3-214d-aec8-e063-6294a90af498'),

  ('tansulosina',
   'Bloqueador alfa-1 seletivo usado nos sintomas da hiperplasia benigna da próstata: melhora o débito urinário máximo e reduz os sintomas obstrutivos e irritativos. Não é indicado como anti-hipertensor.',
   'Selective alpha-1 blocker used in benign prostatic hyperplasia symptoms: it improves maximum urinary flow rate and reduces obstructive and irritative symptoms. It is not intended as an antihypertensive.',
   'Bloqueia seletivamente os recetores adrenérgicos alfa-1A, predominantes na próstata (cerca de 70% dos recetores alfa-1 prostáticos), relaxando o músculo liso da próstata, cápsula prostática, uretra prostática e colo vesical e reduzindo a obstrução do colo vesical.',
   'Selectively blocks alpha-1A adrenergic receptors, predominant in the prostate (about 70% of prostatic alpha-1 receptors), relaxing smooth muscle in the prostate, prostatic capsule, prostatic urethra and bladder neck and reducing bladder outlet obstruction.',
   'É extensamente metabolizada no fígado, sobretudo pelo CYP3A4 e CYP2D6 (com participação menor de outras isoenzimas); menos de 10% da dose é excretada inalterada na urina. Os metabolitos sofrem conjugação com glucurónido ou sulfato antes da excreção renal. A urina é a via principal (76%) e as fezes 21%.',
   'Extensively metabolised in the liver, mainly by CYP3A4 and CYP2D6 (with minor participation of other isoenzymes); less than 10% of the dose is excreted unchanged in urine. The metabolites undergo glucuronide or sulfate conjugation before renal excretion. Urine is the main route (76%) and faeces 21%.',
   'A absorção é essencialmente completa (mais de 90%) em jejum, com Tmax de 4 a 5 horas (6 a 7 horas com alimentos). Em jejum, a biodisponibilidade aumenta 30% (AUC) e a Cmax 40 a 70%. Liga-se 94 a 99% às proteínas plasmáticas, sobretudo à alfa-1-glicoproteína ácida.',
   'Absorption is essentially complete (over 90%) when fasted, with a Tmax of 4 to 5 hours (6 to 7 hours with food). When fasted, bioavailability increases 30% (AUC) and Cmax 40 to 70%. It is 94 to 99% bound to plasma proteins, mainly to alpha-1 acid glycoprotein.',
   'A semivida aparente da tansulosina em cápsulas é de aproximadamente 9 a 13 horas em voluntários saudáveis e de 14 a 15 horas na população alvo; após formulação de libertação imediata, a semivida é de 5 a 7 horas.',
   'The apparent half-life of tamsulosin capsules is approximately 9 to 13 hours in healthy volunteers and 14 to 15 hours in the target population; with the immediate-release formulation, the half-life is 5 to 7 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tansulosina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=38cbc0fa-ca6b-0e39-e063-6394a90abb97',
   'DailyMed/FDA (NIH/NLM) — approved Tamsulosin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=38cbc0fa-ca6b-0e39-e063-6394a90abb97'),

  ('tiamazol',
   'Antitiroideu de síntese usado no tratamento do hipertiroidismo (doença de Graves, bócio multinodular tóxico, adenoma tóxico) e na preparação para tiroidectomia ou radioiodoterapia. Não inativa a tiroxina e a tri-iodotironina já existentes, pelo que o efeito clínico demora dias a semanas a manifestar-se.',
   'Antithyroid agent used in the treatment of hyperthyroidism (Graves disease, toxic multinodular goitre, toxic adenoma) and in preparation for thyroidectomy or radioiodine therapy. It does not inactivate existing thyroxine and triiodothyronine, so the clinical effect takes days to weeks to appear.',
   'Inibe a síntese das hormonas tiroideias ao bloquear a organificação do iodo e o acoplamento das iodotirosinas na glândula tiroideia (inibição da peroxidase tiroideia).',
   'Inhibits thyroid hormone synthesis by blocking iodine organification and coupling of iodotyrosines in the thyroid gland (inhibition of thyroid peroxidase).',
   'É rapidamente absorvido no trato gastrointestinal, metabolizado no fígado e excretado na urina; cerca de 80% do fármaco e metabolitos é eliminado por via renal (7% inalterado).',
   'Readily absorbed in the gastrointestinal tract, metabolised in the liver and excreted in urine; about 80% of the drug and metabolites is eliminated renally (7% unchanged).',
   'Rapidamente absorvido após administração oral, com pico sérico 1 a 2 horas após a toma. Não se liga às proteínas plasmáticas e acumula-se na glândula tiroideia.',
   'Rapidly absorbed after oral administration, with peak serum concentrations 1 to 2 hours after dosing. It is not bound to plasma proteins and accumulates in the thyroid gland.',
   'A semivida plasmática é de cerca de 3 a 5 horas (na literatura até 5 a 13 horas); a duração do efeito é mais prolongada do que a semivida sugere, devido à acumulação intratiroidiana.',
   'The plasma half-life is about 3 to 5 hours (in the literature up to 5 to 13 hours); the duration of effect is longer than the half-life suggests, due to intrathyroidal accumulation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tiamazol (metimazol); farmacocinética corroborada por PubMed: Jansen 1983 (PMID 6172233) e Cooper DS. N Engl J Med 2005;352:905-917 (PMID 15745981): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=244d76f1-98e6-4305-8768-b104f6a4be07',
   'DailyMed/FDA (NIH/NLM) — approved Methimazole label; pharmacokinetics corroborated by PubMed: Jansen 1983 (PMID 6172233) and Cooper DS. N Engl J Med 2005;352:905-917 (PMID 15745981): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=244d76f1-98e6-4305-8768-b104f6a4be07'),

  ('valproato',
   'Anticonvulsivante de largo espetro (também estabilizador do humor). A relação entre a concentração plasmática e a resposta clínica não está bem documentada; a ligação proteica dependente da concentração afeta a depuração, pelo que a monitorização do valproato total pode não refletir de forma fiável a fração bioativa.',
   'Broad-spectrum anticonvulsant (also a mood stabiliser). The relationship between plasma concentration and clinical response is not well documented; concentration-dependent protein binding affects clearance, so monitoring of total valproate may not reliably reflect the bioactive fraction.',
   'O mecanismo exato não está estabelecido; sugere-se que a atividade na epilepsia se relaciona com o aumento das concentrações cerebrais de ácido gama-aminobutírico (GABA).',
   'The exact mechanism has not been established; it has been suggested that its activity in epilepsy is related to increased brain concentrations of gamma-aminobutyric acid (GABA).',
   'É metabolizado quase inteiramente no fígado: em monoterapia, 30 a 50% da dose aparece na urina como conjugado glucurónico; a beta-oxidação mitocondrial é a outra via principal (mais de 40% da dose); menos de 3% é excretado inalterado na urina.',
   'Metabolised almost entirely in the liver: on monotherapy, 30 to 50% of the dose appears in urine as a glucuronide conjugate; mitochondrial beta-oxidation is the other major pathway (over 40% of the dose); less than 3% is excreted unchanged in urine.',
   'Nos comprimidos de libertação prolongada, o Tmax varia entre 4 e 17 horas; o fármaco é bem absorvido. A ligação às proteínas plasmáticas é dependente da concentração: a fração livre aumenta de cerca de 10% (40 mcg/ml) para 18,5% (130 mcg/ml); no líquido cefalorraquidiano, as concentrações aproximam-se da fração livre plasmática.',
   'With extended-release tablets, Tmax ranges from 4 to 17 hours; the drug is well absorbed. Plasma protein binding is concentration-dependent: the free fraction increases from about 10% (40 mcg/ml) to 18.5% (130 mcg/ml); in cerebrospinal fluid, concentrations approximate the unbound plasma fraction.',
   'A semivida terminal média em monoterapia varia entre 9 e 16 horas após doses orais de 250 a 1.000 mg.',
   'The mean terminal half-life on monotherapy ranges from 9 to 16 hours after oral doses of 250 to 1,000 mg.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Valproato (divalproex), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=aa386ae3-ceac-4e3b-8fb1-ced3107a4c54',
   'DailyMed/FDA (NIH/NLM) — approved Valproate (divalproex) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=aa386ae3-ceac-4e3b-8fb1-ced3107a4c54'),

  ('vardenafil',
   'Inibidor da PDE5 usado na disfunção erétil. Produz uma pequena redução da pressão arterial (diminuição máxima média de 7/8 mmHg) e um ligeiro aumento da frequência cardíaca; potencia o efeito hipotensor dos nitratos, pelo que a associação é contraindicada. Em doses supra-terapêuticas prolonga ligeiramente o intervalo QT.',
   'PDE5 inhibitor used in erectile dysfunction. It produces a slight blood pressure reduction (mean maximum decrease of 7/8 mmHg) and a small increase in heart rate; it potentiates the hypotensive effect of nitrates, so the combination is contraindicated. At supratherapeutic doses it slightly prolongs the QT interval.',
   'Inibe seletivamente a PDE5 (mais de 15 vezes mais seletivo para a PDE5 do que para a PDE6), aumentando o cGMP no corpo cavernoso e promovendo o relaxamento do músculo liso durante a estimulação sexual; sem estimulação, não tem efeito.',
   'Selectively inhibits PDE5 (more than 15-fold more selective for PDE5 than for PDE6), increasing cGMP in the corpus cavernosum and promoting smooth muscle relaxation during sexual stimulation; without stimulation it has no effect.',
   'É predominantemente metabolizado no fígado pelo CYP3A4, com participação do CYP3A5 e das isoenzimas CYP2C; o metabolito circulante principal, M1 (desetilação), tem cerca de 28% da potência inibitória in vitro e contribui com cerca de 7% da atividade farmacológica total. É excretado como metabolitos sobretudo nas fezes (91 a 95%) e, em menor grau, na urina (2 a 6%).',
   'Predominantly metabolised in the liver by CYP3A4, with contribution from CYP3A5 and the CYP2C isoforms; the main circulating metabolite, M1 (desethylation), has about 28% of the in vitro inhibitory potency and accounts for about 7% of total pharmacological activity. Excreted as metabolites mainly in faeces (91 to 95%) and, to a lesser extent, in urine (2 to 6%).',
   'Rapidamente absorvido, com biodisponibilidade absoluta de cerca de 15%; o pico plasmático é atingido 30 minutos a 2 horas após a toma (mediana de 60 minutos em jejum). As refeições ricas em gordura reduzem a Cmax em 18 a 50%. Liga-se cerca de 95% às proteínas plasmáticas e o volume de distribuição é de 208 L.',
   'Rapidly absorbed, with absolute bioavailability of about 15%; peak plasma concentrations are reached 30 minutes to 2 hours after dosing (median 60 minutes when fasted). High-fat meals reduce Cmax by 18 to 50%. It is about 95% bound to plasma proteins and the volume of distribution is 208 L.',
   'A semivida terminal do vardenafil e do seu principal metabolito é de aproximadamente 4 a 5 horas.',
   'The terminal half-life of vardenafil and its main metabolite is approximately 4 to 5 hours.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Vardenafil, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2782efed-6198-47b9-81ac-3e255e2ab7f6',
   'DailyMed/FDA (NIH/NLM) — approved Vardenafil label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2782efed-6198-47b9-81ac-3e255e2ab7f6')
) AS v(
  slug, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
  metabolism_pt, metabolism_en, absorption_pt, absorption_en,
  half_life_pt, half_life_en, source_pt, source_en)
  ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
