-- =====================================================================
-- 099 — Dimensões alimento/doença/gestação (lote 1: 15 anti-infeciosos)
-- ---------------------------------------------------------------------
-- Preenche as 3 dimensões em falta (drug_food_interactions,
-- drug_disease_interactions, drug_pregnancy_info) de 15 fármacos
-- anti-infeciosos que não as tinham completas — primeiro lote dos 95
-- fármacos com ≥1 dimensão em falta (auditoria 2026-08-09).
-- Padrão das migrações 062/067/069: INSERT com JOIN (VALUES) ON
-- d.slug = v.slug + ON CONFLICT DO NOTHING, status 'published'.
-- Conteúdo autoral, ancorado nos rótulos aprovados DailyMed citados
-- (setIDs validados) e no Prontuário Terapêutico do INFARMED.
-- Idempotente: reaplicar é seguro.
-- =====================================================================

-- =====================================================================
-- 1. Alimento / Bebida (drug_food_interactions)
-- =====================================================================
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('claritromicina', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja inibe o CYP3A4 e pode aumentar as concentrações de claritromicina, elevando o risco de prolongamento do QT e efeitos adversos.',
   'Grapefruit inhibits CYP3A4 and can raise clarithromycin concentrations, increasing the risk of QT prolongation and adverse effects.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 'DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 1),
  ('claritromicina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais (náuseas, dor abdominal) da claritromicina.',
   'Alcohol may worsen clarithromycin gastrointestinal effects (nausea, abdominal pain).',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 'DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 1),
  ('rifampicina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à da rifampicina e pode interferir com a adesão ao tratamento da tuberculose.',
   'Alcohol adds hepatotoxicity to that of rifampicin and may interfere with tuberculosis treatment adherence.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 'DailyMed/FDA (NIH/NLM) — approved Rifampicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 1),
  ('rifampicina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os alimentos reduzem a absorção da rifampicina; a toma em jejum maximiza os níveis plasmáticos.',
   'Food reduces rifampicin absorption; taking it on an empty stomach maximises plasma levels.',
   'Tomar a rifampicina em jejum, 1 hora antes ou 2 horas depois das refeições.',
   'Take rifampicin on an empty stomach, 1 hour before or 2 hours after meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 'DailyMed/FDA (NIH/NLM) — approved Rifampicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 1),
  ('cetoconazol', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja aumenta as concentrações de cetoconazol (inibição do CYP3A4), elevando o risco de hepatotoxicidade e prolongamento do QT.',
   'Grapefruit raises ketoconazole concentrations (CYP3A4 inhibition), increasing the risk of hepatotoxicity and QT prolongation.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 1),
  ('cetoconazol', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool aumenta o risco de lesão hepática durante o tratamento com cetoconazol.',
   'Alcohol increases the risk of liver injury during ketoconazole treatment.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 1),
  ('ciprofloxacina', 'leite_calcio', 'Leite e laticínios', 'Milk and dairy products', 'moderate',
   'O cálcio dos laticínios quelata a ciprofloxacina no lúmen gastrointestinal e reduz marcadamente a sua absorção.',
   'Calcium in dairy chelates ciprofloxacin in the GI lumen and markedly reduces its absorption.',
   'Não tomar com leite, iogurte ou derivados; separar a toma 2 horas antes ou 6 horas depois dos laticínios.',
   'Do not take with milk, yoghurt or dairy; separate dosing 2 hours before or 6 hours after dairy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 1),
  ('ciprofloxacina', 'cafeina', 'Cafeína', 'Caffeine', 'minor',
   'A ciprofloxacina inibe o CYP1A2 e reduz a clearance da cafeína, potenciando os seus efeitos (insónia, nervosismo, taquicardia).',
   'Ciprofloxacin inhibits CYP1A2 and reduces caffeine clearance, potentiating its effects (insomnia, nervousness, tachycardia).',
   'Limitar o consumo de cafeína durante o tratamento.',
   'Limit caffeine intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 1),
  ('itraconazol', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja reduz a absorção do itraconazol (as cápsulas necessitam de pH ácido) e pode diminuir a eficácia.',
   'Grapefruit reduces itraconazole absorption (capsules need an acid pH) and may decrease efficacy.',
   'Evitar sumo de toranja; tomar as cápsulas com alimentos, mas não com toranja.',
   'Avoid grapefruit juice; take capsules with food, but not with grapefruit.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 1),
  ('itraconazol', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool aumenta o risco de hepatotoxicidade do itraconazol.',
   'Alcohol increases the risk of itraconazole hepatotoxicity.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 1),
  ('cloroquina', 'toranja', 'Toranja', 'Grapefruit', 'minor',
   'A toranja pode alterar o metabolismo da cloroquina (CYP2C8/CYP3A4), com efeito variável nas concentrações.',
   'Grapefruit may alter chloroquine metabolism (CYP2C8/CYP3A4), with a variable effect on concentrations.',
   'Limitar o consumo de sumo de toranja durante o tratamento.',
   'Limit grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 1),
  ('cloroquina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma com alimentos reduz as náuseas associadas à cloroquina sem afetar de forma relevante a absorção.',
   'Taking with food reduces chloroquine-related nausea without significantly affecting absorption.',
   'Tomar com alimentos ou leite para melhorar a tolerância gastrointestinal.',
   'Take with food or milk to improve GI tolerance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 1),
  ('voriconazol', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja inibe o CYP3A4 e pode aumentar as concentrações de voriconazol, elevando o risco de hepatotoxicidade e efeitos visuais.',
   'Grapefruit inhibits CYP3A4 and can raise voriconazole concentrations, increasing the risk of hepatotoxicity and visual effects.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 1),
  ('voriconazol', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool aumenta o risco de hepatotoxicidade do voriconazol.',
   'Alcohol increases the risk of voriconazole hepatotoxicity.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 1),
  ('fluconazol', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool aumenta o risco de hepatotoxicidade do fluconazol.',
   'Alcohol increases the risk of fluconazole hepatotoxicity.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 1),
  ('fluconazol', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A absorção do fluconazol não é afetada de forma relevante pelos alimentos.',
   'Fluconazole absorption is not significantly affected by food.',
   'Pode tomar com ou sem alimentos.',
   'May take with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 1),
  ('eritromicina', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja inibe o CYP3A4 e pode aumentar as concentrações de eritromicina, elevando o risco de prolongamento do QT.',
   'Grapefruit inhibits CYP3A4 and can raise erythromycin concentrations, increasing the risk of QT prolongation.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 1),
  ('eritromicina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os alimentos podem reduzir a absorção de algumas formulações de eritromicina; a toma em jejum maximiza os níveis.',
   'Food may reduce absorption of some erythromycin formulations; taking on an empty stomach maximises levels.',
   'Preferir a toma em jejum, salvo indicação em contrário da formulação.',
   'Prefer taking on an empty stomach unless the formulation advises otherwise.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 1),
  ('isoniazida', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à da isoniazida e aumenta o risco de lesão hepática grave.',
   'Alcohol adds hepatotoxicity to that of isoniazid and increases the risk of severe liver injury.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 1),
  ('isoniazida', 'alimentos_ricos_tiramina', 'Alimentos ricos em tiramina', 'Tyramine-rich foods', 'minor',
   'A isoniazida inibe a monoamina oxidase de forma ligeira e pode potenciar os efeitos da tiramina (queijo curado, vinho tinto).',
   'Isoniazid mildly inhibits monoamine oxidase and may potentiate the effects of tyramine (aged cheese, red wine).',
   'Moderar o consumo de queijos curados e vinho tinto durante o tratamento.',
   'Moderate intake of aged cheeses and red wine during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 1),
  ('metronidazol', 'alcool', 'Álcool', 'Alcohol', 'critical',
   'O metronidazol inibe a acetaldeído desidrogenase: o álcool causa reação dissulfiram-like (rubor, náuseas, vómitos, taquicardia, cefaleias).',
   'Metronidazole inhibits acetaldehyde dehydrogenase: alcohol causes a disulfiram-like reaction (flushing, nausea, vomiting, tachycardia, headache).',
   'Não consumir álcool durante o tratamento e nas 48–72 horas seguintes à última dose.',
   'Do not consume alcohol during treatment and for 48–72 hours after the last dose.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 'DailyMed/FDA (NIH/NLM) — approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 1),
  ('metronidazol', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma com alimentos reduz a irritação gastrointestinal sem afetar de forma relevante a absorção.',
   'Taking with food reduces GI irritation without significantly affecting absorption.',
   'Tomar com alimentos para melhorar a tolerância gastrointestinal.',
   'Take with food to improve GI tolerance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 'DailyMed/FDA (NIH/NLM) — approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 1),
  ('cotrimoxazol', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool pode agravar os efeitos gastrointestinais e a fotossensibilidade associadas ao cotrimoxazol.',
   'Alcohol may worsen the gastrointestinal effects and photosensitivity associated with co-trimoxazole.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 'DailyMed/FDA (NIH/NLM) — approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 1),
  ('cotrimoxazol', 'alimentos_ricos_potassio', 'Alimentos ricos em potássio', 'Potassium-rich foods', 'moderate',
   'O trimetoprim reduz a excreção renal de potássio e pode causar hipercaliemia; alimentos ricos em potássio adicionam-se a este efeito.',
   'Trimethoprim reduces renal potassium excretion and can cause hyperkalaemia; potassium-rich foods add to this effect.',
   'Vigiar a caliemia em doentes de risco; moderar o consumo excessivo de alimentos ricos em potássio.',
   'Monitor serum potassium in at-risk patients; moderate excessive intake of potassium-rich foods.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 'DailyMed/FDA (NIH/NLM) — approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 1),
  ('levofloxacina', 'leite_calcio', 'Leite e laticínios', 'Milk and dairy products', 'moderate',
   'O cálcio dos laticínios pode reduzir a absorção da levofloxacina quando administrados em conjunto.',
   'Calcium in dairy may reduce levofloxacin absorption when taken together.',
   'Separar a toma dos laticínios 2 horas antes ou 6 horas depois.',
   'Separate dairy intake 2 hours before or 6 hours after dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 1),
  ('levofloxacina', 'cafeina', 'Cafeína', 'Caffeine', 'minor',
   'A levofloxacina reduz a clearance da cafeína (inibição do CYP1A2), potenciando os seus efeitos estimulantes.',
   'Levofloxacin reduces caffeine clearance (CYP1A2 inhibition), potentiating its stimulant effects.',
   'Limitar o consumo de cafeína durante o tratamento.',
   'Limit caffeine intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 1),
  ('azitromicina', 'toranja', 'Toranja', 'Grapefruit', 'minor',
   'A toranja pode aumentar ligeiramente as concentrações de azitromicina, com relevância clínica limitada.',
   'Grapefruit may slightly raise azithromycin concentrations, with limited clinical relevance.',
   'Limitar o consumo de sumo de toranja durante o tratamento.',
   'Limit grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 1),
  ('azitromicina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os alimentos reduzem a absorção das cápsulas de azitromicina; os comprimidos podem tomar-se com ou sem alimentos.',
   'Food reduces absorption of azithromycin capsules; tablets may be taken with or without food.',
   'Tomar as cápsulas em jejum; os comprimidos podem tomar-se com alimentos.',
   'Take capsules on an empty stomach; tablets may be taken with food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 1),
  ('doxiciclina', 'leite_calcio', 'Leite e laticínios', 'Milk and dairy products', 'moderate',
   'O cálcio dos laticínios quelata a doxiciclina e reduz a sua absorção; o efeito é menor que com as restantes tetraciclinas, mas relevante.',
   'Calcium in dairy chelates doxycycline and reduces its absorption; the effect is smaller than with other tetracyclines, but relevant.',
   'Separar a toma dos laticínios 2 horas antes ou 6 horas depois.',
   'Separate dairy intake 2 hours before or 6 hours after dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 'DailyMed/FDA (NIH/NLM) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 1),
  ('doxiciclina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool não interage diretamente com a doxiciclina, mas pode agravar os efeitos gastrointestinais.',
   'Alcohol does not interact directly with doxycycline, but may worsen GI effects.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 'DailyMed/FDA (NIH/NLM) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- =====================================================================
-- 2. Doença / Condição (drug_disease_interactions)
-- =====================================================================
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('claritromicina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A claritromicina prolonga o intervalo QT e pode precipitar torsades de pointes em doentes com QT prolongado ou fatores de risco.',
   'Clarithromycin prolongs the QT interval and may precipitate torsades de pointes in patients with QT prolongation or risk factors.',
   'Evitar em doentes com QT prolongado congénito ou adquirido; vigiar ECG e eletrólitos.',
   'Avoid in congenital or acquired QT prolongation; monitor ECG and electrolytes.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 'DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 1),
  ('claritromicina', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate',
   'A claritromicina é excretada por via renal e hepática; na insuficiência renal grave pode acumular-se e exige ajuste de dose.',
   'Clarithromycin is renally and hepatically excreted; in severe renal impairment it may accumulate and requires dose adjustment.',
   'Reduzir a dose na insuficiência renal grave (CrCl < 30 mL/min).',
   'Reduce the dose in severe renal impairment (CrCl < 30 mL/min).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 'DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 1),
  ('rifampicina', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A rifampicina é hepatotóxica e pode agravar a doença hepática pré-existente.',
   'Rifampicin is hepatotoxic and may worsen pre-existing liver disease.',
   'Vigiar transaminases; reduzir a dose ou suspender se houver lesão hepática.',
   'Monitor transaminases; reduce the dose or stop if liver injury occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 'DailyMed/FDA (NIH/NLM) — approved Rifampicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 1),
  ('rifampicina', 'porfiria', 'Porfiria', 'Porphyria', 'precaution', 'moderate',
   'A rifampicina induz a síntese de porfirinas e pode precipitar crises em doentes com porfiria.',
   'Rifampicin induces porphyrin synthesis and may precipitate attacks in patients with porphyria.',
   'Usar com precaução em doentes com porfiria.',
   'Use with caution in patients with porphyria.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 'DailyMed/FDA (NIH/NLM) — approved Rifampicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 1),
  ('cetoconazol', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'contraindication', 'critical',
   'O cetoconazol pode causar hepatotoxicidade grave e está contraindicado em doença hepática aguda ou crónica.',
   'Ketoconazole can cause severe hepatotoxicity and is contraindicated in acute or chronic liver disease.',
   'Contraindicado em doença hepática; avaliar função hepática antes e durante o tratamento.',
   'Contraindicated in liver disease; assess liver function before and during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 1),
  ('cetoconazol', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'O cetoconazol prolonga o QT e aumenta o risco de arritmias ventriculares, sobretudo com fármacos que também prolongam o QT.',
   'Ketoconazole prolongs the QT and increases the risk of ventricular arrhythmias, especially with other QT-prolonging drugs.',
   'Evitar em doentes com QT prolongado ou com fármacos que prolongam o QT; vigiar ECG e eletrólitos.',
   'Avoid in QT prolongation or with QT-prolonging drugs; monitor ECG and electrolytes.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 1),
  ('ciprofloxacina', 'epilepsia', 'Epilepsia / história de convulsões', 'Epilepsy / history of seizures', 'precaution', 'moderate',
   'As fluoroquinolonas podem baixar o limiar convulsivo e precipitar convulsões em doentes predispostos.',
   'Fluoroquinolones can lower the seizure threshold and precipitate seizures in predisposed patients.',
   'Usar com precaução em doentes com epilepsia ou história de convulsões.',
   'Use with caution in patients with epilepsy or a history of seizures.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 1),
  ('ciprofloxacina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A ciprofloxacina prolonga o intervalo QT e aumenta o risco de torsades de pointes em doentes de risco.',
   'Ciprofloxacin prolongs the QT interval and increases the risk of torsades de pointes in at-risk patients.',
   'Evitar em QT prolongado ou hipocaliemia não corrigida; vigiar ECG e eletrólitos.',
   'Avoid in QT prolongation or uncorrected hypokalaemia; monitor ECG and electrolytes.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 1),
  ('itraconazol', 'insuficiencia_cardiaca', 'Insuficiência cardíaca', 'Heart failure', 'contraindication', 'critical',
   'O itraconazol tem efeito inotrópico negativo e está contraindicado em doentes com insuficiência cardíaca ou disfunção ventricular.',
   'Itraconazole has negative inotropic effects and is contraindicated in patients with heart failure or ventricular dysfunction.',
   'Contraindicado em insuficiência cardíaca; avaliar função cardíaca antes do tratamento.',
   'Contraindicated in heart failure; assess cardiac function before treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 1),
  ('itraconazol', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O itraconazol é metabolizado no fígado e pode agravar a doença hepática; o uso prolongado associa-se a hepatotoxicidade.',
   'Itraconazole is metabolised in the liver and may worsen liver disease; prolonged use is associated with hepatotoxicity.',
   'Vigiar transaminases; usar com precaução em doença hepática.',
   'Monitor transaminases; use with caution in liver disease.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 1),
  ('cloroquina', 'retinopatia', 'Doença ocular / retinopatia', 'Eye disease / retinopathy', 'precaution', 'moderate',
   'A cloroquina acumula-se na retina e pode causar retinopatia irreversível, sobretudo em tratamentos prolongados.',
   'Chloroquine accumulates in the retina and can cause irreversible retinopathy, especially with prolonged treatment.',
   'Vigilância oftalmológica de base e periódica em tratamentos > 5 anos ou dose cumulativa elevada.',
   'Baseline and periodic ophthalmological monitoring in treatment > 5 years or high cumulative dose.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 1),
  ('cloroquina', 'deficiencia_g6pd', 'Deficiência de G6PD', 'G6PD deficiency', 'precaution', 'moderate',
   'A cloroquina pode causar hemólise em doentes com deficiência de G6PD, sobretudo em doses elevadas.',
   'Chloroquine can cause haemolysis in G6PD-deficient patients, especially at high doses.',
   'Usar com precaução em deficiência de G6PD; vigiar sinais de hemólise.',
   'Use with caution in G6PD deficiency; monitor for haemolysis signs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 1),
  ('voriconazol', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O voriconazol é hepatotóxico e os níveis aumentam na insuficiência hepática; exige monitorização e ajuste de dose.',
   'Voriconazole is hepatotoxic and levels rise in hepatic impairment; requires monitoring and dose adjustment.',
   'Vigiar transaminases; ajustar a dose na insuficiência hepática ligeira a moderada.',
   'Monitor transaminases; adjust the dose in mild-to-moderate hepatic impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 1),
  ('voriconazol', 'fotossensibilidade', 'Fotossensibilidade', 'Photosensitivity', 'precaution', 'moderate',
   'O voriconazol causa fotossensibilidade grave, com risco de lesões cutâneas e carcinoma espinocelular em exposição prolongada.',
   'Voriconazole causes severe photosensitivity, with risk of skin lesions and squamous cell carcinoma on prolonged exposure.',
   'Evitar exposição solar e usar proteção (roupa e protetor solar) durante e após o tratamento.',
   'Avoid sun exposure and use protection (clothing and sunscreen) during and after treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 1),
  ('fluconazol', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O fluconazol pode causar hepatotoxicidade, incluindo necrose hepática fatal; o risco aumenta em doença hepática prévia.',
   'Fluconazole can cause hepatotoxicity, including fatal hepatic necrosis; the risk increases with prior liver disease.',
   'Vigiar transaminases, sobretudo em tratamentos prolongados.',
   'Monitor transaminases, especially in prolonged treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 1),
  ('fluconazol', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'O fluconazol é eliminado por via renal; a insuficiência renal exige redução da dose.',
   'Fluconazole is renally eliminated; renal impairment requires dose reduction.',
   'Ajustar a dose de acordo com a depuração de creatinina.',
   'Adjust the dose according to creatinine clearance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 1),
  ('eritromicina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A eritromicina prolonga o intervalo QT e aumenta o risco de torsades de pointes, sobretudo em doentes de risco.',
   'Erythromycin prolongs the QT interval and increases the risk of torsades de pointes, especially in at-risk patients.',
   'Evitar em QT prolongado, hipocaliemia ou com fármacos que prolongam o QT.',
   'Avoid in QT prolongation, hypokalaemia or with QT-prolonging drugs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 1),
  ('eritromicina', 'estenose_hipertrofica', 'Estenose pilórica hipertrófica infantil', 'Infantile hypertrophic pyloric stenosis', 'precaution', 'moderate',
   'A eritromicina usada no recém-nascido associa-se a estenose pilórica hipertrófica.',
   'Erythromycin use in neonates is associated with infantile hypertrophic pyloric stenosis.',
   'Evitar em recém-nascidos quando existirem alternativas; vigiar vómitos projetados.',
   'Avoid in neonates when alternatives exist; watch for projectile vomiting.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 1),
  ('isoniazida', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A isoniazida é hepatotóxica e o risco de lesão hepática grave aumenta em doentes com doença hepática prévia.',
   'Isoniazid is hepatotoxic and the risk of severe liver injury increases in patients with prior liver disease.',
   'Vigiar transaminases mensalmente; suspender se houver sintomas de hepatite.',
   'Monitor transaminases monthly; stop if hepatitis symptoms occur.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 1),
  ('isoniazida', 'neuropatia_periferica', 'Neuropatia periférica', 'Peripheral neuropathy', 'precaution', 'moderate',
   'A isoniazida interfere com o metabolismo da vitamina B6 e pode causar neuropatia periférica, sobretudo em doentes de risco.',
   'Isoniazid interferes with vitamin B6 metabolism and can cause peripheral neuropathy, especially in at-risk patients.',
   'Suplementar com vitamina B6 (piridoxina) em doentes de risco (diabetes, alcoolismo, gravidez, desnutrição).',
   'Supplement with vitamin B6 (pyridoxine) in at-risk patients (diabetes, alcoholism, pregnancy, malnutrition).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 1),
  ('metronidazol', 'doenca_hepatica_grave', 'Doença hepática grave', 'Severe liver disease', 'precaution', 'moderate',
   'O metronidazol é metabolizado no fígado; na doença hepática grave a eliminação é reduzida e a acumulação pode causar neurotoxicidade.',
   'Metronidazole is metabolised in the liver; in severe liver disease elimination is reduced and accumulation can cause neurotoxicity.',
   'Reduzir a dose e vigiar sinais de neurotoxicidade (parestesias, ataxia).',
   'Reduce the dose and monitor for neurotoxicity signs (paraesthesia, ataxia).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 'DailyMed/FDA (NIH/NLM) — approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 1),
  ('metronidazol', 'doenca_snc', 'Doença do SNC ativa', 'Active CNS disease', 'precaution', 'moderate',
   'O metronidazol pode causar encefalopatia, convulsões e neuropatia periférica, sobretudo em doses elevadas ou uso prolongado.',
   'Metronidazole can cause encephalopathy, seizures and peripheral neuropathy, especially at high doses or with prolonged use.',
   'Suspender se surgirem sintomas neurológicos; usar com precaução em doença do SNC.',
   'Stop if neurological symptoms appear; use with caution in CNS disease.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 'DailyMed/FDA (NIH/NLM) — approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 1),
  ('cotrimoxazol', 'deficiencia_folato', 'Deficiência de folato', 'Folate deficiency', 'precaution', 'moderate',
   'O trimetoprim interfere com o metabolismo do folato e pode agravar a deficiência, com risco de anemia megaloblástica.',
   'Trimethoprim interferes with folate metabolism and can worsen deficiency, with risk of megaloblastic anaemia.',
   'Usar com precaução em deficiência de folato, alcoolismo e desnutrição; considerar suplementação.',
   'Use with caution in folate deficiency, alcoholism and malnutrition; consider supplementation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 'DailyMed/FDA (NIH/NLM) — approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 1),
  ('cotrimoxazol', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'O cotrimoxazol é excretado por via renal; a insuficiência renal aumenta o risco de toxicidade (incluindo hipercaliemia) e exige ajuste.',
   'Co-trimoxazole is renally excreted; renal impairment increases the toxicity risk (including hyperkalaemia) and requires adjustment.',
   'Ajustar a dose; vigiar função renal e caliemia.',
   'Adjust the dose; monitor renal function and serum potassium.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 'DailyMed/FDA (NIH/NLM) — approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 1),
  ('levofloxacina', 'tendinopatia', 'Tendinopatia / rutura tendinosa', 'Tendinopathy / tendon rupture', 'precaution', 'moderate',
   'As fluoroquinolonas podem causar tendinopatia e rutura tendinosa, sobretudo em idosos, com corticosteroides ou insuficiência renal.',
   'Fluoroquinolones can cause tendinopathy and tendon rupture, especially in the elderly, with corticosteroids or renal impairment.',
   'Suspender ao primeiro sinal de dor tendinosa; evitar em doentes com história de tendinopatia por quinolonas.',
   'Stop at the first sign of tendon pain; avoid in patients with a history of quinolone tendinopathy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 1),
  ('levofloxacina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A levofloxacina prolonga o intervalo QT e aumenta o risco de arritmias ventriculares em doentes de risco.',
   'Levofloxacin prolongs the QT interval and increases the risk of ventricular arrhythmias in at-risk patients.',
   'Evitar em QT prolongado ou com fármacos que prolongam o QT; vigiar ECG.',
   'Avoid in QT prolongation or with QT-prolonging drugs; monitor ECG.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 1),
  ('azitromicina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A azitromicina pode prolongar o intervalo QT e aumentar o risco de arritmias, sobretudo em doentes de risco.',
   'Azithromycin may prolong the QT interval and increase the arrhythmia risk, especially in at-risk patients.',
   'Evitar em QT prolongado conhecido ou com fármacos que prolongam o QT.',
   'Avoid in known QT prolongation or with QT-prolonging drugs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 1),
  ('azitromicina', 'doenca_hepatica_grave', 'Doença hepática grave', 'Severe liver disease', 'precaution', 'moderate',
   'A azitromicina pode causar hepatotoxicidade, incluindo necrose hepática, sobretudo em doença hepática prévia.',
   'Azithromycin can cause hepatotoxicity, including hepatic necrosis, especially with prior liver disease.',
   'Usar com precaução; vigiar sinais de lesão hepática.',
   'Use with caution; monitor for signs of liver injury.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 1),
  ('doxiciclina', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'precaution', 'moderate',
   'A doxiciclina pode agravar a doença hepática; na insuficiência hepática grave exige precaução.',
   'Doxycycline may worsen liver disease; caution is required in severe hepatic impairment.',
   'Usar com precaução e vigiar função hepática.',
   'Use with caution and monitor liver function.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 'DailyMed/FDA (NIH/NLM) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 1),
  ('doxiciclina', 'fotossensibilidade', 'Fotossensibilidade', 'Photosensitivity', 'precaution', 'moderate',
   'As tetraciclinas causam fotossensibilidade; a exposição solar pode provocar queimaduras graves.',
   'Tetracyclines cause photosensitivity; sun exposure can cause severe burns.',
   'Evitar exposição solar e usar proteção durante o tratamento.',
   'Avoid sun exposure and use protection during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 'DailyMed/FDA (NIH/NLM) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- =====================================================================
-- 3. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- =====================================================================
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('claritromicina', 'caution',
   'A claritromicina atravessa a placenta; os dados em humanos são limitados, mas os macrólidos são geralmente usados na gravidez quando indicados.',
   'Clarithromycin crosses the placenta; human data are limited, but macrolides are generally used in pregnancy when indicated.',
   'Usar apenas se o benefício justificar o risco; não é o macrólido de primeira escolha na gravidez.',
   'Use only if the benefit justifies the risk; not the first-choice macrolide in pregnancy.',
   'Excretada no leite; evitar durante a amamentação ou usar com precaução.',
   'Excreted into breast milk; avoid while breastfeeding or use with caution.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Claritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85', 'DailyMed/FDA (NIH/NLM) — approved Clarithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5be5f12-6392-4d7d-ab23-ebc205ac1a85'),
  ('rifampicina', 'caution',
   'A rifampicina atravessa a placenta; os dados são limitados, mas é usada na gravidez para tratar tuberculose ativa.',
   'Rifampicin crosses the placenta; data are limited, but it is used in pregnancy to treat active tuberculosis.',
   'Usar na tuberculose ativa, com suplementação de vitamina K no recém-nascido e vitamina B6 materna.',
   'Use in active tuberculosis, with vitamin K supplementation in the neonate and maternal vitamin B6.',
   'Excretada no leite; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk; compatible with breastfeeding under supervision.',
   'A rifampicina reduz a eficácia dos contracetivos hormonais — usar método adicional (barreira).',
   'Rifampicin reduces the efficacy of hormonal contraceptives — use an additional (barrier) method.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 'DailyMed/FDA (NIH/NLM) — approved Rifampicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b'),
  ('cetoconazol', 'contraindicated',
   'O cetoconazol oral é teratogénico em animais e não deve ser usado na gravidez (o uso tópico tem exposição mínima).',
   'Oral ketoconazole is teratogenic in animals and should not be used in pregnancy (topical use has minimal exposure).',
   'Contraindicado por via oral na gravidez; preferir antifúngico alternativo.',
   'Contraindicated orally in pregnancy; prefer an alternative antifungal.',
   'Excretado no leite; evitar durante a amamentação.',
   'Excreted into breast milk; avoid while breastfeeding.',
   'Aconselhar contraceção eficaz durante o tratamento oral.',
   'Advise effective contraception during oral treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0', 'DailyMed/FDA (NIH/NLM) — approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f162e616-21b4-49b1-b437-15e21001a6f0'),
  ('ciprofloxacina', 'caution',
   'As fluoroquinolonas causam artropatia em animais jovens; os dados humanos são limitados, mas o uso na gravidez é geralmente evitado.',
   'Fluoroquinolones cause arthropathy in young animals; human data are limited, but use in pregnancy is generally avoided.',
   'Evitar na gravidez, exceto se não existirem alternativas seguras.',
   'Avoid in pregnancy unless no safe alternative exists.',
   'Excretada no leite; evitar durante a amamentação.',
   'Excreted into breast milk; avoid while breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ciprofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d', 'DailyMed/FDA (NIH/NLM) — approved Ciprofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14c3bc33-201d-492e-9aee-a4d84c813a3d'),
  ('itraconazol', 'contraindicated',
   'O itraconazol é teratogénico em animais; os dados humanos são limitados e o uso na gravidez deve ser evitado.',
   'Itraconazole is teratogenic in animals; human data are limited and use in pregnancy should be avoided.',
   'Contraindicado na gravidez, exceto em infeção fúngica grave sem alternativa.',
   'Contraindicated in pregnancy, except in severe fungal infection without an alternative.',
   'Excretado no leite; evitar durante a amamentação.',
   'Excreted into breast milk; avoid while breastfeeding.',
   'Aconselhar contraceção eficaz durante o tratamento e até 2 meses após a suspensão.',
   'Advise effective contraception during treatment and up to 2 months after stopping.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25', 'DailyMed/FDA (NIH/NLM) — approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=68165d90-953c-e2f5-e053-2a91aa0ada25'),
  ('cloroquina', 'caution',
   'A cloroquina atravessa a placenta; não é teratogénica nas doses antimaláricas, mas os dados são limitados.',
   'Chloroquine crosses the placenta; it is not teratogenic at antimalarial doses, but data are limited.',
   'Pode ser usada na profilaxia e tratamento da malária na gravidez, sob vigilância.',
   'May be used for malaria prophylaxis and treatment in pregnancy, under supervision.',
   'Excretada no leite; compatível com a amamentação.',
   'Excreted into breast milk; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cloroquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570', 'DailyMed/FDA (NIH/NLM) — approved Chloroquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06c69e2b-211b-4746-9f3a-f86d36520570'),
  ('voriconazol', 'contraindicated',
   'O voriconazol é teratogénico e embriotóxico em animais; contraindicado na gravidez.',
   'Voriconazole is teratogenic and embryotoxic in animals; contraindicated in pregnancy.',
   'Contraindicado na gravidez; usar contraceção eficaz durante o tratamento.',
   'Contraindicated in pregnancy; use effective contraception during treatment.',
   'Excretado no leite; evitar durante a amamentação.',
   'Excreted into breast milk; avoid while breastfeeding.',
   'Aconselhar contraceção eficaz durante o tratamento.',
   'Advise effective contraception during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Voriconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435', 'DailyMed/FDA (NIH/NLM) — approved Voriconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c620b2d7-3c2b-4252-8cfc-2f322d624435'),
  ('fluconazol', 'caution',
   'Doses baixas e curtas de fluconazol não se associam a malformações; doses elevadas (≥ 400 mg/dia) prolongadas associam-se a risco aumentado.',
   'Low, short fluconazole doses are not associated with malformations; prolonged high doses (≥ 400 mg/day) are associated with increased risk.',
   'Usar a menor dose eficaz pelo menor tempo; evitar doses elevadas prolongadas na gravidez.',
   'Use the lowest effective dose for the shortest time; avoid prolonged high doses in pregnancy.',
   'Excretado no leite; compatível com a amamentação em doses habituais.',
   'Excreted into breast milk; compatible with breastfeeding at usual doses.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fluconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873', 'DailyMed/FDA (NIH/NLM) — approved Fluconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7961c029-746c-48c3-888b-8f8344102873'),
  ('eritromicina', 'compatible',
   'A eritromicina é o macrólido de primeira escolha na gravidez quando indicado; não se associou a malformações major.',
   'Erythromycin is the first-choice macrolide in pregnancy when indicated; no major malformations have been associated.',
   'Pode ser usada na gravidez quando indicado (ex.: Legionella, coqueluche, clamídia).',
   'May be used in pregnancy when indicated (e.g. Legionella, pertussis, chlamydia).',
   'Excretada no leite; compatível com a amamentação.',
   'Excreted into breast milk; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Eritromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e', 'DailyMed/FDA (NIH/NLM) — approved Erythromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca65a48f-5fe6-4b31-8359-51dbc31f6d4e'),
  ('isoniazida', 'caution',
   'A isoniazida atravessa a placenta; não é teratogénica, mas é hepatotóxica e exige suplementação de vitamina B6 na gravidez.',
   'Isoniazid crosses the placenta; it is not teratogenic, but is hepatotoxic and requires vitamin B6 supplementation in pregnancy.',
   'Usar na tuberculose ativa na gravidez; suplementar piridoxina e vigiar transaminases.',
   'Use for active tuberculosis in pregnancy; supplement pyridoxine and monitor transaminases.',
   'Excretada no leite; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 'DailyMed/FDA (NIH/NLM) — approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e'),
  ('metronidazol', 'caution',
   'O metronidazol atravessa a placenta; os dados não mostram aumento claro de malformações, mas o uso no 1.º trimestre é cauteloso.',
   'Metronidazole crosses the placenta; data show no clear increase in malformations, but use in the 1st trimester is cautious.',
   'Evitar no 1.º trimestre; usar doses curtas quando claramente indicado.',
   'Avoid in the 1st trimester; use short courses when clearly indicated.',
   'Excretado no leite; evitar a amamentação durante o tratamento e 12–24 h após a última dose.',
   'Excreted into breast milk; avoid breastfeeding during treatment and for 12–24 h after the last dose.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metronidazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6', 'DailyMed/FDA (NIH/NLM) — approved Metronidazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cc3fd98-d579-432e-a4b5-b6d5586991a6'),
  ('cotrimoxazol', 'caution',
   'O trimetoprim é antagonista do folato; o uso no 1.º trimestre associa-se a risco aumentado de malformações (defeitos do tubo neural).',
   'Trimethoprim is a folate antagonist; use in the 1st trimester is associated with an increased risk of malformations (neural tube defects).',
   'Evitar no 1.º trimestre; suplementar ácido fólico se inevitável.',
   'Avoid in the 1st trimester; supplement folic acid if unavoidable.',
   'Excretado no leite; evitar durante a amamentação em recém-nascidos (risco de kernicterus com sulfonamidas).',
   'Excreted into breast milk; avoid while breastfeeding neonates (kernicterus risk with sulphonamides).',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cotrimoxazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0', 'DailyMed/FDA (NIH/NLM) — approved Co-trimoxazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=08500fcb-dbec-4ac2-91c3-189d27907ec0'),
  ('levofloxacina', 'caution',
   'As fluoroquinolonas causam artropatia em animais jovens; o uso na gravidez é geralmente evitado.',
   'Fluoroquinolones cause arthropathy in young animals; use in pregnancy is generally avoided.',
   'Evitar na gravidez, exceto se não existirem alternativas seguras.',
   'Avoid in pregnancy unless no safe alternative exists.',
   'Excretada no leite; evitar durante a amamentação.',
   'Excreted into breast milk; avoid while breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levofloxacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e', 'DailyMed/FDA (NIH/NLM) — approved Levofloxacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=857f256c-88ac-4f73-9815-c2724edf2f1e'),
  ('azitromicina', 'compatible',
   'A azitromicina não se associou a aumento de malformações major; é usada na gravidez quando o macrólido está indicado.',
   'Azithromycin has not been associated with an increase in major malformations; it is used in pregnancy when a macrolide is indicated.',
   'Pode ser usada na gravidez quando indicado.',
   'May be used in pregnancy when indicated.',
   'Excretada no leite; compatível com a amamentação.',
   'Excreted into breast milk; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Azitromicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45', 'DailyMed/FDA (NIH/NLM) — approved Azithromycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=db52b91e-79f7-4cc1-9564-f2eee8e31c45'),
  ('doxiciclina', 'contraindicated',
   'As tetraciclinas causam alterações ósseas e dentárias no feto (descoloração dos dentes, hipoplasia do esmalte) após o 4.º mês.',
   'Tetracyclines cause fetal bone and dental changes (tooth discolouration, enamel hypoplasia) after the 4th month.',
   'Contraindicada no 2.º e 3.º trimestres; evitar sempre que existam alternativas.',
   'Contraindicated in the 2nd and 3rd trimesters; avoid whenever alternatives exist.',
   'Excretada no leite; evitar durante a amamentação (risco de descoloração dentária no lactente).',
   'Excreted into breast milk; avoid while breastfeeding (risk of dental discolouration in the infant).',
   'Aconselhar contraceção eficaz se o tratamento for prolongado.',
   'Advise effective contraception if treatment is prolonged.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe', 'DailyMed/FDA (NIH/NLM) — approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bcc95094-80ed-4023-b2a6-955a4810bfbe')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- FIM — 099: 30 alimento + 30 doença + 15 gestação (15 fármacos)
-- =====================================================================
