-- =====================================================================
-- 101 — Dimensões alimento/doença/gestação (lote 2: 12 anti-TB/ARV + 8 só-alimento)
-- ---------------------------------------------------------------------
-- Preenche as dimensões em falta de 20 fármacos:
--   • 12 antituberculosos/antirretrovíricos a faltar as 3 dimensões
--     (pirazinamida, etambutol, rifabutina, estreptomicina, linezolida,
--      bedaquilina, atazanavir, efavirenz, lamivudina, nevirapina,
--      ritonavir, zidovudina) — alimento + doença + gestação;
--   • 8 fármacos a faltar apenas alimento (tamoxifeno, anastrozol,
--     acetazolamida, clopidogrel, sotalol, amiodarona, ondansetron,
--     acetilcisteina) — alimento.
-- Padrão da 099: INSERT com JOIN (VALUES) ON d.slug = v.slug +
-- ON CONFLICT DO NOTHING, status 'published'.
-- Conteúdo autoral, ancorado nos rótulos aprovados DailyMed citados
-- (setIDs validados nas migrações 088–096/063) e no Prontuário
-- Terapêutico do INFARMED como referência.
-- Idempotente: reaplicar é seguro.
-- =====================================================================

-- =====================================================================
-- 1. Alimento / Bebida (drug_food_interactions)
-- =====================================================================
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('pirazinamida', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A pirazinamida pode ser tomada com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal (náuseas).',
   'Pyrazinamide can be taken with or without food; taking it with food reduces gastrointestinal discomfort (nausea).',
   'Tomar com alimentos se ocorrer náusea ou desconforto gástrico.',
   'Take with food if nausea or gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Pirazinamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 'DailyMed/FDA (NIH/NLM) — approved Pyrazinamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 1),
  ('pirazinamida', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à da pirazinamida, aumentando o risco de lesão hepática durante o tratamento da tuberculose.',
   'Alcohol adds hepatotoxicity to that of pyrazinamide, increasing the risk of liver injury during tuberculosis treatment.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Pirazinamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 'DailyMed/FDA (NIH/NLM) — approved Pyrazinamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 1),
  ('etambutol', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O etambutol pode ser tomado com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal.',
   'Ethambutol can be taken with or without food; taking it with food reduces gastrointestinal discomfort.',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etambutol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 'DailyMed/FDA (NIH/NLM) — approved Ethambutol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 1),
  ('etambutol', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O consumo de álcool pode aumentar o risco de efeitos adversos hepáticos durante o tratamento antituberculoso.',
   'Alcohol intake may increase the risk of hepatic adverse effects during antituberculosis treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etambutol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 'DailyMed/FDA (NIH/NLM) — approved Ethambutol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 1),
  ('rifabutina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os alimentos reduzem a taxa e a extensão da absorção da rifabutina; a toma em jejum maximiza os níveis plasmáticos.',
   'Food decreases the rate and extent of rifabutin absorption; taking it on an empty stomach maximises plasma levels.',
   'Tomar a rifabutina em jejum, 1 hora antes ou 2 horas depois das refeições.',
   'Take rifabutin on an empty stomach, 1 hour before or 2 hours after meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 1),
  ('rifabutina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à da rifabutina, aumentando o risco de lesão hepática.',
   'Alcohol adds hepatotoxicity to that of rifabutin, increasing the risk of liver injury.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 1),
  ('estreptomicina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No significant food interaction', 'none',
   'A estreptomicina é administrada por via intramuscular ou intravenosa; não tem interação alimentar relevante.',
   'Streptomycin is given intramuscularly or intravenously; it has no significant food interaction.',
   'Não é necessário ajustar a toma em função das refeições.',
   'No need to adjust dosing around meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 1),
  ('estreptomicina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Não existe interação direta conhecida entre a estreptomicina e o álcool; recomenda-se prudência pelo risco de efeitos no SNC.',
   'No direct interaction is known between streptomycin and alcohol; caution is advised due to the risk of CNS effects.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 1),
  ('linezolida', 'alimentos_ricos_tiramina', 'Alimentos ricos em tiramina', 'Tyramine-rich foods', 'moderate',
   'A linezolida inibe a monoamina oxidase (MAO-A); alimentos ricos em tiramina (queijos curados, enchidos, vinho tinto, chucrute, fava) podem desencadear crise hipertensiva.',
   'Linezolid inhibits monoamine oxidase (MAO-A); tyramine-rich foods (aged cheese, cured meats, red wine, sauerkraut, broad beans) can trigger a hypertensive crisis.',
   'Evitar alimentos ricos em tiramina durante e até 2 semanas após o tratamento.',
   'Avoid tyramine-rich foods during and up to 2 weeks after treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 1),
  ('linezolida', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'A cerveja e o vinho contêm tiramina e devem ser evitados durante o tratamento com linezolida.',
   'Beer and wine contain tyramine and should be avoided during linezolid treatment.',
   'Evitar cerveja, vinho e bebidas fermentadas durante o tratamento.',
   'Avoid beer, wine and fermented drinks during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 1),
  ('bedaquilina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma da bedaquilina com alimentos aumenta a sua absorção e reduz a variabilidade dos níveis plasmáticos.',
   'Taking bedaquiline with food increases its absorption and reduces plasma level variability.',
   'Tomar com alimentos, de preferência à mesma refeição diária.',
   'Take with food, preferably at the same daily meal.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 1),
  ('bedaquilina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à da bedaquilina, aumentando o risco de lesão hepática.',
   'Alcohol adds hepatotoxicity to that of bedaquiline, increasing the risk of liver injury.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 1),
  ('atazanavir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma do atazanavir com alimentos melhora a sua absorção e reduz a variabilidade dos níveis plasmáticos.',
   'Taking atazanavir with food improves its absorption and reduces plasma level variability.',
   'Tomar com alimentos, de preferência à mesma refeição diária.',
   'Take with food, preferably at the same daily meal.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 1),
  ('atazanavir', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à do atazanavir, com risco aumentado em doentes com hepatite B ou C.',
   'Alcohol adds hepatotoxicity to that of atazanavir, with increased risk in patients with hepatitis B or C.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 1),
  ('efavirenz', 'refeicao_gordurosa', 'Refeição rica em gordura', 'High-fat meal', 'moderate',
   'As refeições ricas em gordura aumentam a absorção do efavirenz e podem potenciar os efeitos adversos no sistema nervoso central (tonturas, pesadelos, insónia).',
   'High-fat meals increase efavirenz absorption and may potentiate central nervous system adverse effects (dizziness, nightmares, insomnia).',
   'Tomar o efavirenz em jejum, de preferência ao deitar.',
   'Take efavirenz on an empty stomach, preferably at bedtime.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 1),
  ('efavirenz', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool pode potenciar os efeitos no sistema nervoso central do efavirenz e adicionar hepatotoxicidade.',
   'Alcohol may potentiate efavirenz central nervous system effects and add hepatotoxicity.',
   'Evitar ou limitar fortemente o consumo de álcool durante o tratamento.',
   'Avoid or strongly limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 1),
  ('lamivudina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A lamivudina pode ser tomada com ou sem alimentos, sem alteração relevante da absorção.',
   'Lamivudine can be taken with or without food, with no relevant change in absorption.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamivudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 'DailyMed/FDA (NIH/NLM) — approved Lamivudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 1),
  ('lamivudina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar a doença hepática subjacente (sobretudo na coinfecção com hepatite B) durante o tratamento com lamivudina.',
   'Alcohol may worsen the underlying liver disease (especially in hepatitis B coinfection) during lamivudine treatment.',
   'Limitar ou evitar o consumo de álcool durante o tratamento.',
   'Limit or avoid alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamivudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 'DailyMed/FDA (NIH/NLM) — approved Lamivudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 1),
  ('nevirapina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A nevirapina pode ser tomada com ou sem alimentos, sem alteração relevante da absorção.',
   'Nevirapine can be taken with or without food, with no relevant change in absorption.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 1),
  ('nevirapina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à da nevirapina, que tem risco elevado de lesão hepática grave.',
   'Alcohol adds hepatotoxicity to that of nevirapine, which carries a high risk of severe liver injury.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 1),
  ('ritonavir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma do ritonavir com alimentos melhora a tolerabilidade gastrointestinal (menos náuseas).',
   'Taking ritonavir with food improves gastrointestinal tolerability (less nausea).',
   'Tomar com alimentos se ocorrer náusea ou desconforto gástrico.',
   'Take with food if nausea or gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 1),
  ('ritonavir', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool adiciona hepatotoxicidade à do ritonavir, com risco aumentado em doentes com hepatite B ou C.',
   'Alcohol adds hepatotoxicity to that of ritonavir, with increased risk in patients with hepatitis B or C.',
   'Evitar o consumo de álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 1),
  ('zidovudina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A zidovudina pode ser tomada com ou sem alimentos; a toma com alimentos pode reduzir as náuseas.',
   'Zidovudine can be taken with or without food; taking it with food may reduce nausea.',
   'Tomar com alimentos se ocorrer náusea.',
   'Take with food if nausea occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Zidovudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 'DailyMed/FDA (NIH/NLM) — approved Zidovudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 1),
  ('zidovudina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar a hepatotoxicidade da zidovudina (sobretudo na coinfecção com hepatite B ou C).',
   'Alcohol may worsen zidovudine hepatotoxicity (especially in hepatitis B or C coinfection).',
   'Limitar ou evitar o consumo de álcool durante o tratamento.',
   'Limit or avoid alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Zidovudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 'DailyMed/FDA (NIH/NLM) — approved Zidovudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 1),
  ('tamoxifeno', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja inibe o CYP3A4 e pode aumentar as concentrações de tamoxifeno; a relevância clínica é incerta, mas recomenda-se evitá-la.',
   'Grapefruit inhibits CYP3A4 and may raise tamoxifen concentrations; the clinical relevance is uncertain, but it is advisable to avoid it.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tamoxifeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=509f8ba3-214d-aec8-e063-6294a90af498', 'DailyMed/FDA (NIH/NLM) — approved Tamoxifen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=509f8ba3-214d-aec8-e063-6294a90af498', 1),
  ('tamoxifeno', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O tamoxifeno pode ser tomado com ou sem alimentos, sem interação alimentar relevante.',
   'Tamoxifen can be taken with or without food, with no relevant food interaction.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tamoxifeno: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=509f8ba3-214d-aec8-e063-6294a90af498', 'DailyMed/FDA (NIH/NLM) — approved Tamoxifen label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=509f8ba3-214d-aec8-e063-6294a90af498', 1),
  ('anastrozol', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'O anastrozol é metabolizado pelo CYP3A4; a toranja pode aumentar as suas concentrações, embora a relevância clínica seja desconhecida.',
   'Anastrozole is metabolised by CYP3A4; grapefruit may raise its concentrations, although the clinical relevance is unknown.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Anastrozol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54da5c12-cfaf-7a14-e063-6394a90a3635', 'DailyMed/FDA (NIH/NLM) — approved Anastrozole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54da5c12-cfaf-7a14-e063-6394a90a3635', 1),
  ('anastrozol', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O anastrozol pode ser tomado com ou sem alimentos, sem interação alimentar relevante.',
   'Anastrozole can be taken with or without food, with no relevant food interaction.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Anastrozol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54da5c12-cfaf-7a14-e063-6394a90a3635', 'DailyMed/FDA (NIH/NLM) — approved Anastrozole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54da5c12-cfaf-7a14-e063-6394a90a3635', 1),
  ('acetazolamida', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma da acetazolamida com alimentos reduz o desconforto gastrointestinal (náuseas, diarreia).',
   'Taking acetazolamide with food reduces gastrointestinal discomfort (nausea, diarrhoea).',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acetazolamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4813b9dd-5f58-44bb-ad64-cdb331828080', 'DailyMed/FDA (NIH/NLM) — approved Acetazolamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4813b9dd-5f58-44bb-ad64-cdb331828080', 1),
  ('acetazolamida', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode aumentar a depressão do sistema nervoso central (sonolência, tonturas) durante o tratamento com acetazolamida.',
   'Alcohol may increase central nervous system depression (drowsiness, dizziness) during acetazolamide treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acetazolamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4813b9dd-5f58-44bb-ad64-cdb331828080', 'DailyMed/FDA (NIH/NLM) — approved Acetazolamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4813b9dd-5f58-44bb-ad64-cdb331828080', 1),
  ('clopidogrel', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja inibe o CYP3A4 (uma das vias de ativação do clopidogrel) e pode reduzir a conversão no metabolito ativo, diminuindo a eficácia antiagregante.',
   'Grapefruit inhibits CYP3A4 (one of the activation pathways of clopidogrel) and may reduce conversion to the active metabolite, decreasing antiplatelet efficacy.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Clopidogrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9928956-bb7b-4ec2-bc38-d3c9c4199cae', 'DailyMed/FDA (NIH/NLM) — approved Clopidogrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9928956-bb7b-4ec2-bc38-d3c9c4199cae', 1),
  ('clopidogrel', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O clopidogrel pode ser tomado com ou sem alimentos, sem interação alimentar relevante.',
   'Clopidogrel can be taken with or without food, with no relevant food interaction.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Clopidogrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9928956-bb7b-4ec2-bc38-d3c9c4199cae', 'DailyMed/FDA (NIH/NLM) — approved Clopidogrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9928956-bb7b-4ec2-bc38-d3c9c4199cae', 1),
  ('sotalol', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os alimentos reduzem a absorção do sotalol em cerca de 20%; a toma em jejum de forma consistente reduz a variabilidade.',
   'Food reduces sotalol absorption by about 20%; taking it consistently on an empty stomach reduces variability.',
   'Tomar o sotalol em jejum, 1 hora antes ou 2 horas depois das refeições.',
   'Take sotalol on an empty stomach, 1 hour before or 2 hours after meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244', 'DailyMed/FDA (NIH/NLM) — approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244', 1),
  ('sotalol', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode perturbar o ritmo cardíaco e potenciar os efeitos hipotensores do sotalol; limitar o consumo.',
   'Alcohol may disturb the heart rhythm and potentiate the hypotensive effects of sotalol; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Sotalol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244', 'DailyMed/FDA (NIH/NLM) — approved Sotalol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9a36d95c-6e93-4e57-befe-b5274f359244', 1),
  ('amiodarona', 'toranja', 'Toranja', 'Grapefruit', 'moderate',
   'A toranja inibe o CYP3A4 e pode aumentar as concentrações de amiodarona, elevando o risco de prolongamento do QT e de arritmias.',
   'Grapefruit inhibits CYP3A4 and may raise amiodarone concentrations, increasing the risk of QT prolongation and arrhythmias.',
   'Evitar sumo de toranja durante o tratamento.',
   'Avoid grapefruit juice during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c149392-a4f0-4e2d-a13f-2b94810005de', 'DailyMed/FDA (NIH/NLM) — approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c149392-a4f0-4e2d-a13f-2b94810005de', 1),
  ('amiodarona', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A amiodarona pode ser tomada com ou sem alimentos; a toma de forma consistente reduz a variabilidade dos níveis.',
   'Amiodarone can be taken with or without food; consistent intake reduces level variability.',
   'Tomar sempre da mesma forma (com ou sem alimentos).',
   'Always take it the same way (with or without food).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amiodarona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c149392-a4f0-4e2d-a13f-2b94810005de', 'DailyMed/FDA (NIH/NLM) — approved Amiodarone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c149392-a4f0-4e2d-a13f-2b94810005de', 1),
  ('ondansetron', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O ondansetrom pode ser tomado com ou sem alimentos, sem interação alimentar relevante.',
   'Ondansetron can be taken with or without food, with no relevant food interaction.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ondansetrom: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14276805-4e99-4bbe-ad76-ffc06eddb38a', 'DailyMed/FDA (NIH/NLM) — approved Ondansetron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14276805-4e99-4bbe-ad76-ffc06eddb38a', 1),
  ('ondansetron', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode aumentar a sonolência e as tonturas associadas ao ondansetrom.',
   'Alcohol may increase the drowsiness and dizziness associated with ondansetron.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ondansetrom: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14276805-4e99-4bbe-ad76-ffc06eddb38a', 'DailyMed/FDA (NIH/NLM) — approved Ondansetron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14276805-4e99-4bbe-ad76-ffc06eddb38a', 1),
  ('acetilcisteina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A acetilcisteína pode ser tomada com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal.',
   'Acetylcysteine can be taken with or without food; taking it with food reduces gastrointestinal discomfort.',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acetilcisteína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586', 'DailyMed/FDA (NIH/NLM) — approved Acetylcysteine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586', 1),
  ('acetilcisteina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode reduzir os níveis de glutationa e contrariar o efeito antioxidante da acetilcisteína; limitar o consumo.',
   'Alcohol may reduce glutathione levels and counteract the antioxidant effect of acetylcysteine; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acetilcisteína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586', 'DailyMed/FDA (NIH/NLM) — approved Acetylcysteine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;-- =====================================================================
-- 2. Doença / Condição (drug_disease_interactions)
-- =====================================================================
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order
FROM public.drugs d
JOIN (VALUES
  ('pirazinamida', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A pirazinamida é hepatotóxica e o risco de lesão hepática grave, sobretudo nos primeiros meses de tratamento, aumenta em doentes com doença hepática prévia.',
   'Pyrazinamide is hepatotoxic and the risk of severe liver injury, especially in the first months of treatment, increases in patients with prior liver disease.',
   'Vigiar transaminases; suspender perante sintomas de hepatite (icterícia, náuseas, dor abdominal).',
   'Monitor transaminases; stop if hepatitis symptoms occur (jaundice, nausea, abdominal pain).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Pirazinamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 'DailyMed/FDA (NIH/NLM) — approved Pyrazinamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 1),
  ('pirazinamida', 'hiperuricemia_gota', 'Hiperuricemia / gota', 'Hyperuricaemia / gout', 'precaution', 'moderate',
   'A pirazinamida inibe a excreção renal de ácido úrico e pode precipitar crises de gota em doentes com hiperuricemia ou história de gota.',
   'Pyrazinamide inhibits renal uric acid excretion and may precipitate gout attacks in patients with hyperuricaemia or a history of gout.',
   'Vigiar ácido úrico e usar com precaução em doentes com gota.',
   'Monitor uric acid and use with caution in patients with gout.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Pirazinamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 'DailyMed/FDA (NIH/NLM) — approved Pyrazinamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 1),
  ('etambutol', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'O etambutol é excretado por via renal; na insuficiência renal a acumulação aumenta o risco de neurite ótica — é necessário ajustar a dose.',
   'Ethambutol is renally excreted; in renal impairment accumulation increases the risk of optic neuritis — dose adjustment is required.',
   'Ajustar a dose à função renal; vigiar acuidade visual e discriminação de cores.',
   'Adjust the dose to renal function; monitor visual acuity and colour discrimination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etambutol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 'DailyMed/FDA (NIH/NLM) — approved Ethambutol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 1),
  ('etambutol', 'neurite_optica', 'Neurite ótica (prévia ou ativa)', 'Optic neuritis (prior or active)', 'contraindication', 'moderate',
   'O etambutol causa neurite ótica dose-dependente; está contraindicado em doentes com neurite ótica prévia ou alterações da visão inexplicadas.',
   'Ethambutol causes dose-dependent optic neuritis; it is contraindicated in patients with prior optic neuritis or unexplained visual changes.',
   'Contraindicado em neurite ótica prévia; excluir alterações visuais antes e durante o tratamento.',
   'Contraindicated in prior optic neuritis; rule out visual changes before and during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etambutol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 'DailyMed/FDA (NIH/NLM) — approved Ethambutol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 1),
  ('rifabutina', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A rifabutina é hepatotóxica e deve ser usada com precaução em doentes com doença hepática, com vigilância de transaminases.',
   'Rifabutin is hepatotoxic and should be used with caution in patients with liver disease, with transaminase monitoring.',
   'Vigiar transaminases; ajustar ou suspender perante lesão hepática.',
   'Monitor transaminases; adjust or stop if liver injury occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 1),
  ('rifabutina', 'neutropenia', 'Neutropenia / leucopenia', 'Neutropenia / leucopenia', 'precaution', 'moderate',
   'A rifabutina causa neutropenia e leucopenia; o risco aumenta em doentes com contagens baixas prévias ou em combinação com fármacos mielossupressores.',
   'Rifabutin causes neutropenia and leucopenia; the risk increases in patients with prior low counts or in combination with myelosuppressive drugs.',
   'Vigiar hemograma; suspender perante neutropenia grave.',
   'Monitor the blood count; stop if severe neutropenia occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 1),
  ('estreptomicina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'A estreptomicina é nefrotóxica e excretada por via renal; na insuficiência renal a acumulação aumenta o risco de ototoxicidade — ajustar a dose.',
   'Streptomycin is nephrotoxic and renally excreted; in renal impairment accumulation increases the risk of ototoxicity — adjust the dose.',
   'Ajustar a dose à função renal; vigiar função renal e sinais de ototoxicidade.',
   'Adjust the dose to renal function; monitor renal function and signs of ototoxicity.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 1),
  ('estreptomicina', 'hipoacusia_doenca_vestibular', 'Hipoacusia / doença vestibular prévia', 'Prior hearing loss / vestibular disease', 'contraindication', 'moderate',
   'A estreptomicina é ototóxica (coclear e vestibular); está contraindicada em doentes com hipoacusia prévia ou doença vestibular pelo risco de surdez irreversível.',
   'Streptomycin is ototoxic (cochlear and vestibular); it is contraindicated in patients with prior hearing loss or vestibular disease due to the risk of irreversible deafness.',
   'Contraindicado em hipoacusia prévia; vigiar acuidade auditiva e equilíbrio.',
   'Contraindicated in prior hearing loss; monitor hearing acuity and balance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 1),
  ('linezolida', 'hipertensao_nao_controlada', 'Hipertensão não controlada', 'Uncontrolled hypertension', 'precaution', 'moderate',
   'A linezolida inibe a monoamina oxidase e pode causar aumentos significativos da pressão arterial em doentes com hipertensão não controlada.',
   'Linezolid inhibits monoamine oxidase and can cause significant blood pressure increases in patients with uncontrolled hypertension.',
   'Usar com precaução e vigiar a pressão arterial durante o tratamento.',
   'Use with caution and monitor blood pressure during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 1),
  ('linezolida', 'depressao_medula_ossea', 'Depressão da medula óssea (história)', 'Bone marrow depression (history)', 'precaution', 'moderate',
   'A linezolida causa mielossupressão (anemia, leucopenia, trombocitopenia), sobretudo em tratamentos prolongados ou em doentes com depressão medular prévia.',
   'Linezolid causes myelosuppression (anaemia, leucopenia, thrombocytopenia), especially with prolonged courses or in patients with prior marrow depression.',
   'Vigiar hemograma semanalmente em tratamentos superiores a 2 semanas.',
   'Monitor the blood count weekly in courses longer than 2 weeks.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 1),
  ('bedaquilina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A bedaquilina prolonga o intervalo QT e o risco de arritmias aumenta em doentes com QT prolongado ou com fármacos que prolongam o QT.',
   'Bedaquiline prolongs the QT interval and the arrhythmia risk increases in patients with QT prolongation or with QT-prolonging drugs.',
   'Evitar em QT prolongado conhecido; vigiar ECG e eletrólitos.',
   'Avoid in known QT prolongation; monitor ECG and electrolytes.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 1),
  ('bedaquilina', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A bedaquilina é hepatotóxica e deve ser usada com precaução em doentes com doença hepática, com vigilância de transaminases.',
   'Bedaquiline is hepatotoxic and should be used with caution in patients with liver disease, with transaminase monitoring.',
   'Vigiar transaminases; suspender perante elevações significativas ou sintomas de hepatite.',
   'Monitor transaminases; stop with significant elevations or hepatitis symptoms.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 1),
  ('atazanavir', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O atazanavir é hepatotóxico, sobretudo em doentes com hepatite B ou C; a doença hepática prévia aumenta o risco de descompensação.',
   'Atazanavir is hepatotoxic, especially in patients with hepatitis B or C; prior liver disease increases the risk of decompensation.',
   'Vigiar transaminases; considerar alternativas em doença hepática grave.',
   'Monitor transaminases; consider alternatives in severe liver disease.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 1),
  ('atazanavir', 'bloqueio_av', 'Bloqueio auriculoventricular', 'Atrioventricular block', 'precaution', 'moderate',
   'O atazanavir prolonga o intervalo PR e pode causar bloqueio auriculoventricular assintomático; o risco aumenta em doença de condução prévia.',
   'Atazanavir prolongs the PR interval and can cause asymptomatic atrioventricular block; the risk increases with pre-existing conduction disease.',
   'Usar com precaução em bloqueio AV prévio ou com fármacos que prolongam o PR; vigiar ECG.',
   'Use with caution in prior AV block or with PR-prolonging drugs; monitor ECG.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 1),
  ('efavirenz', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O efavirenz é hepatotóxico, sobretudo nos primeiros meses e em coinfecção com hepatite B ou C; a doença hepática prévia aumenta o risco.',
   'Efavirenz is hepatotoxic, especially in the first months and in hepatitis B or C coinfection; prior liver disease increases the risk.',
   'Vigiar transaminases; suspender perante sintomas de hepatite.',
   'Monitor transaminases; stop if hepatitis symptoms occur.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 1),
  ('efavirenz', 'doenca_psiquiatrica', 'Doença psiquiátrica (depressão, ideação suicida)', 'Psychiatric disease (depression, suicidal ideation)', 'precaution', 'moderate',
   'O efavirenz causa efeitos neuropsiquiátricos (depressão, ideação suicida, psicose), com risco aumentado em doentes com doença psiquiátrica prévia.',
   'Efavirenz causes neuropsychiatric effects (depression, suicidal ideation, psychosis), with increased risk in patients with prior psychiatric disease.',
   'Vigiar sintomas neuropsiquiátricos; suspender perante depressão grave ou ideação suicida.',
   'Monitor neuropsychiatric symptoms; stop with severe depression or suicidal ideation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 1),
  ('lamivudina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'A lamivudina é excretada predominantemente por via renal; na insuficiência renal a dose deve ser ajustada para evitar toxicidade.',
   'Lamivudine is predominantly renally excreted; in renal impairment the dose must be adjusted to avoid toxicity.',
   'Ajustar a dose à clearance de creatinina.',
   'Adjust the dose to creatinine clearance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamivudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 'DailyMed/FDA (NIH/NLM) — approved Lamivudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 1),
  ('lamivudina', 'acidose_lactica_esteatose_hepatica', 'Acidose láctica / esteatose hepática', 'Lactic acidosis / hepatic steatosis', 'precaution', 'moderate',
   'Os análogos nucleósidos, incluindo a lamivudina, podem causar acidose láctica e esteatose hepática grave, por vezes fatais.',
   'Nucleoside analogues, including lamivudine, can cause lactic acidosis and severe hepatic steatosis, sometimes fatal.',
   'Suspender perante sintomas (náuseas, dor abdominal, dispneia) ou acidose láctica confirmada.',
   'Stop with symptoms (nausea, abdominal pain, dyspnoea) or confirmed lactic acidosis.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamivudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 'DailyMed/FDA (NIH/NLM) — approved Lamivudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 1),
  ('nevirapina', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A nevirapina causa hepatotoxicidade grave, sobretudo nas primeiras 18 semanas e em mulheres com CD4 elevado; a doença hepática prévia aumenta o risco.',
   'Nevirapine causes severe hepatotoxicity, especially in the first 18 weeks and in women with high CD4 counts; prior liver disease increases the risk.',
   'Vigiar transaminases nas primeiras semanas; suspender perante lesão hepática ou sintomas de hepatite.',
   'Monitor transaminases in the first weeks; stop with liver injury or hepatitis symptoms.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 1),
  ('nevirapina', 'erupcao_cutanea_grave', 'Erupção cutânea grave (SJS/TEN)', 'Severe skin rash (SJS/TEN)', 'precaution', 'moderate',
   'A nevirapina causa erupções cutâneas, incluindo síndrome de Stevens-Johnson e necrólise epidérmica tóxica, sobretudo nas primeiras semanas.',
   'Nevirapine causes skin rashes, including Stevens-Johnson syndrome and toxic epidermal necrolysis, especially in the first weeks.',
   'Suspender imediatamente perante erupção grave, bolhas ou envolvimento mucoso.',
   'Stop immediately with a severe rash, blistering or mucosal involvement.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 1),
  ('ritonavir', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O ritonavir é hepatotóxico, sobretudo em coinfecção com hepatite B ou C; a doença hepática prévia aumenta o risco de descompensação.',
   'Ritonavir is hepatotoxic, especially in hepatitis B or C coinfection; prior liver disease increases the risk of decompensation.',
   'Vigiar transaminases; considerar alternativas em doença hepática grave.',
   'Monitor transaminases; consider alternatives in severe liver disease.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 1),
  ('ritonavir', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus', 'precaution', 'moderate',
   'O ritonavir pode causar hiperglicemia, intolerância à glicose e diabetes de novo; o risco é maior em doentes diabéticos ou com fatores de risco.',
   'Ritonavir can cause hyperglycaemia, glucose intolerance and new-onset diabetes; the risk is higher in diabetic patients or those with risk factors.',
   'Vigiar glicemia em doentes diabéticos ou em risco; ajustar a terapêutica antidiabética se necessário.',
   'Monitor blood glucose in diabetic or at-risk patients; adjust antidiabetic therapy if needed.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 1),
  ('zidovudina', 'anemia_neutropenia', 'Anemia / neutropenia prévia', 'Prior anaemia / neutropenia', 'precaution', 'moderate',
   'A zidovudina causa mielossupressão (anemia, neutropenia); o risco aumenta em doentes com contagens baixas prévias ou deficiência de B12/folato.',
   'Zidovudine causes myelosuppression (anaemia, neutropenia); the risk increases in patients with prior low counts or B12/folate deficiency.',
   'Vigiar hemograma; ajustar a dose ou suspender perante anemia ou neutropenia graves.',
   'Monitor the blood count; adjust the dose or stop with severe anaemia or neutropenia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Zidovudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 'DailyMed/FDA (NIH/NLM) — approved Zidovudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 1),
  ('zidovudina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'A zidovudina é eliminada predominantemente por via renal; na insuficiência renal avançada a dose deve ser reduzida.',
   'Zidovudine is predominantly eliminated renally; in advanced renal impairment the dose should be reduced.',
   'Ajustar a dose na insuficiência renal grave; vigiar função renal e hemograma.',
   'Adjust the dose in severe renal impairment; monitor renal function and blood count.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Zidovudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 'DailyMed/FDA (NIH/NLM) — approved Zidovudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;-- =====================================================================
-- 3. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- =====================================================================
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('pirazinamida', 'caution',
   'A pirazinamida atravessa a placenta; é usada no tratamento da tuberculose ativa na gravidez, com vigilância da função hepática.',
   'Pyrazinamide crosses the placenta; it is used to treat active tuberculosis in pregnancy, with monitoring of liver function.',
   'Usar na tuberculose ativa, com vigilância de transaminases; dose habitual em adultos.',
   'Use in active tuberculosis, with transaminase monitoring; usual adult dose.',
   'Excretada no leite; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Pirazinamida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684', 'DailyMed/FDA (NIH/NLM) — approved Pyrazinamide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=262d8829-728c-48db-b89b-88d13b87e684'),
  ('etambutol', 'caution',
   'O etambutol atravessa a placenta; não é teratogénico conhecido nas doses terapêuticas e é usado na tuberculose ativa na gravidez.',
   'Ethambutol crosses the placenta; it is not a known teratogen at therapeutic doses and is used in active tuberculosis in pregnancy.',
   'Usar na tuberculose ativa; a dose baseada no peso é segura na gravidez.',
   'Use in active tuberculosis; the weight-based dose is safe in pregnancy.',
   'Excretado no leite; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etambutol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73', 'DailyMed/FDA (NIH/NLM) — approved Ethambutol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c12b3482-55f0-4324-bdcd-b129ca2dae73'),
  ('rifabutina', 'caution',
   'Os dados em humanos são limitados; a rifabutina deve ser usada na gravidez apenas se o benefício justificar o risco.',
   'Human data are limited; rifabutin should be used in pregnancy only if the benefit justifies the risk.',
   'Usar apenas se o benefício justificar o risco; não é o fármaco de primeira linha na gravidez.',
   'Use only if the benefit justifies the risk; not the first-line agent in pregnancy.',
   'Excretada no leite; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk; compatible with breastfeeding under supervision.',
   'A rifabutina induz o CYP3A4 e reduz a eficácia dos contracetivos hormonais — usar método adicional (barreira).',
   'Rifabutin induces CYP3A4 and reduces the efficacy of hormonal contraceptives — use an additional (barrier) method.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rifabutina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707', 'DailyMed/FDA (NIH/NLM) — approved Rifabutin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2026b67-4755-4236-96b6-a6b5e7399707'),
  ('estreptomicina', 'contraindicated',
   'A estreptomicina atravessa a placenta e pode causar ototoxicidade fetal irreversível (lesão do 8.º par craniano); está contraindicada na gravidez.',
   'Streptomycin crosses the placenta and can cause irreversible fetal ototoxicity (8th cranial nerve damage); it is contraindicated in pregnancy.',
   'Contraindicada na gravidez; escolher esquema antituberculoso alternativo.',
   'Contraindicated in pregnancy; choose an alternative antituberculosis regimen.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e', 'DailyMed/FDA (NIH/NLM) — approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abd1f64e-4283-4370-aae8-3666316aa36e'),
  ('linezolida', 'caution',
   'Os dados em humanos são limitados; a linezolida deve ser usada na gravidez apenas se o benefício justificar o risco.',
   'Human data are limited; linezolid should be used in pregnancy only if the benefit justifies the risk.',
   'Usar apenas se não existirem alternativas mais seguras.',
   'Use only if no safer alternative exists.',
   'Excretada no leite; evitar durante a amamentação ou usar com precaução.',
   'Excreted into breast milk; avoid while breastfeeding or use with caution.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Linezolida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3', 'DailyMed/FDA (NIH/NLM) — approved Linezolid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=90dd8c13-c428-4472-91e5-5b1fcdc4fce3'),
  ('bedaquilina', 'caution',
   'Os dados em humanos são muito limitados; a bedaquilina não é recomendada na gravidez, exceto se o benefício superar claramente o risco.',
   'Human data are very limited; bedaquiline is not recommended in pregnancy unless the benefit clearly outweighs the risk.',
   'Evitar na gravidez; considerar apenas em tuberculose multirresistente sem alternativa.',
   'Avoid in pregnancy; consider only in multidrug-resistant tuberculosis without an alternative.',
   'Excretada no leite; evitar durante a amamentação (dados insuficientes).',
   'Excreted into breast milk; avoid while breastfeeding (insufficient data).',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bedaquilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e', 'DailyMed/FDA (NIH/NLM) — approved Bedaquiline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1534c9ae-4948-4cf4-9f66-222a99db6d0e'),
  ('atazanavir', 'caution',
   'O atazanavir é usado na gravidez como parte da terapêutica anti-retrovírica do HIV; a exposição fetal é aceite face ao benefício da supressão viral.',
   'Atazanavir is used in pregnancy as part of HIV antiretroviral therapy; fetal exposure is accepted given the benefit of viral suppression.',
   'Usar na gravidez como parte do esquema anti-retrovírico; a dose pode necessitar de ajuste no 3.º trimestre.',
   'Use in pregnancy as part of the antiretroviral regimen; the dose may need adjustment in the 3rd trimester.',
   'Excretado no leite; na infeção por HIV recomenda-se não amamentar independentemente do tratamento.',
   'Excreted into breast milk; in HIV infection breastfeeding is not recommended regardless of treatment.',
   'O atazanavir reduz os níveis de estrogénio/progestagénio — considerar método adicional se usado contracetivo hormonal.',
   'Atazanavir lowers oestrogen/progestin levels — consider an additional method if a hormonal contraceptive is used.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 'DailyMed/FDA (NIH/NLM) — approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8'),
  ('efavirenz', 'caution',
   'O efavirenz é teratogénico em primatas (defeitos do tubo neural) e deve ser evitado no 1.º trimestre; os dados humanos são limitados.',
   'Efavirenz is teratogenic in primates (neural tube defects) and should be avoided in the 1st trimester; human data are limited.',
   'Evitar no 1.º trimestre; se possível, preferir alternativa (ex.: dolutegravir) em mulheres em idade fértil.',
   'Avoid in the 1st trimester; where possible, prefer an alternative (e.g. dolutegravir) in women of childbearing age.',
   'Excretado no leite; na infeção por HIV recomenda-se não amamentar independentemente do tratamento.',
   'Excreted into breast milk; in HIV infection breastfeeding is not recommended regardless of treatment.',
   'Aconselhar contraceção eficaz durante o tratamento (o efavirenz pode reduzir a eficácia dos contracetivos hormonais).',
   'Advise effective contraception during treatment (efavirenz may reduce the efficacy of hormonal contraceptives).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Efavirenz: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c', 'DailyMed/FDA (NIH/NLM) — approved Efavirenz label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92603fa5-7a2c-4bfb-9a70-aadb4fba952c'),
  ('lamivudina', 'caution',
   'A lamivudina é usada na gravidez para prevenção da transmissão vertical do HIV; não é teratogénica conhecida nas doses terapêuticas.',
   'Lamivudine is used in pregnancy to prevent vertical transmission of HIV; it is not a known teratogen at therapeutic doses.',
   'Usar na gravidez como parte do esquema anti-retrovírico do HIV.',
   'Use in pregnancy as part of the HIV antiretroviral regimen.',
   'Excretada no leite; na infeção por HIV recomenda-se não amamentar independentemente do tratamento.',
   'Excreted into breast milk; in HIV infection breastfeeding is not recommended regardless of treatment.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lamivudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95', 'DailyMed/FDA (NIH/NLM) — approved Lamivudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6bd6b9da-df69-46db-813e-4e7f3bdecf95'),
  ('nevirapina', 'caution',
   'A nevirapina é usada na gravidez como parte da terapêutica anti-retrovírica do HIV; o risco de hepatotoxicidade é maior em mulheres com CD4 elevado.',
   'Nevirapine is used in pregnancy as part of HIV antiretroviral therapy; the hepatotoxicity risk is higher in women with high CD4 counts.',
   'Usar na gravidez como parte do esquema anti-retrovírico, com vigilância hepática apertada nas primeiras semanas.',
   'Use in pregnancy as part of the antiretroviral regimen, with close hepatic monitoring in the first weeks.',
   'Excretada no leite; na infeção por HIV recomenda-se não amamentar independentemente do tratamento.',
   'Excreted into breast milk; in HIV infection breastfeeding is not recommended regardless of treatment.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nevirapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a', 'DailyMed/FDA (NIH/NLM) — approved Nevirapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6e93829-7024-48f6-8023-da6ff27dfc0a'),
  ('ritonavir', 'caution',
   'O ritonavir é usado na gravidez como potenciador farmacocinético da terapêutica anti-retrovírica do HIV.',
   'Ritonavir is used in pregnancy as a pharmacokinetic booster of HIV antiretroviral therapy.',
   'Usar na gravidez como parte do esquema anti-retrovírico, sob vigilância.',
   'Use in pregnancy as part of the antiretroviral regimen, under supervision.',
   'Excretado no leite; na infeção por HIV recomenda-se não amamentar independentemente do tratamento.',
   'Excreted into breast milk; in HIV infection breastfeeding is not recommended regardless of treatment.',
   'O ritonavir reduz a eficácia dos contracetivos hormonais — usar método adicional (barreira).',
   'Ritonavir reduces the efficacy of hormonal contraceptives — use an additional (barrier) method.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ritonavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925', 'DailyMed/FDA (NIH/NLM) — approved Ritonavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d2f8c6ba-5e06-4b03-8ca5-b4fd7e5a8925'),
  ('zidovudina', 'caution',
   'A zidovudina é usada na gravidez para prevenção da transmissão vertical do HIV; não é teratogénica conhecida nas doses terapêuticas.',
   'Zidovudine is used in pregnancy to prevent vertical transmission of HIV; it is not a known teratogen at therapeutic doses.',
   'Usar na gravidez como parte do esquema anti-retrovírico do HIV; vigiar hemograma materno (anemia).',
   'Use in pregnancy as part of the HIV antiretroviral regimen; monitor maternal blood count (anaemia).',
   'Excretada no leite; na infeção por HIV recomenda-se não amamentar independentemente do tratamento.',
   'Excreted into breast milk; in HIV infection breastfeeding is not recommended regardless of treatment.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Zidovudina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e', 'DailyMed/FDA (NIH/NLM) — approved Zidovudine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e816e8f5-1e50-4f49-8bea-92da0121d26e')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- FIM — 101: 40 alimento + 24 doença + 12 gestação (20 fármacos)
-- =====================================================================


