-- =====================================================================
-- 102 — Dimensões alimento/doença/gestação (lote 3: 10 antimaláricos + 6 beta-lactâmicos)
-- ---------------------------------------------------------------------
-- Preenche as 3 dimensões em falta (drug_food_interactions,
-- drug_disease_interactions, drug_pregnancy_info) de 16 fármacos que
-- não as tinham completas — terceiro lote dos fármacos com ≥1 dimensão
-- em falta (auditoria 2026-08-10).
--   • 10 antimaláricos (artesunato, arteméter+lumefantrina,
--     artesunato+amodiaquina, diidroartemisinina+piperaquina,
--     sulfadoxina+pirimetamina, mefloquina, primaquina, quinina,
--     atovaquona+proguanil, tafenoquina);
--   • 6 beta-lactâmicos (ampicilina, amoxicilina+clavulanato,
--     piperacilina+tazobactam, ceftriaxona, cefalexina, cefuroxima).
-- Padrão da 099/101: INSERT com JOIN (VALUES) ON d.slug = v.slug +
-- ON CONFLICT DO NOTHING, status 'published'.
-- Conteúdo autoral, ancorado nos rótulos aprovados DailyMed citados
-- (setIDs validados nas migrações 052/053/055/056/096) e nas
-- Diretrizes da OMS para a malária / EMA (Eurartesim) para os
-- antimaláricos sem rótulo nos EUA.
-- Idempotente: reaplicar é seguro.
-- =====================================================================

-- =====================================================================
-- 1. Alimento / Bebida (drug_food_interactions)
-- =====================================================================
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('artesunato', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O artesunato (oral ou injetável) pode ser administrado com ou sem alimentos, sem interação alimentar relevante.',
   'Artesunate (oral or injectable) can be given with or without food, with no relevant food interaction.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'SmPC-padrão WHO-prequalificado (MA152) e EMA (Artesunate Amivas) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO-prequalified model SmPC (MA152) and EMA (Artesunate Amivas) — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('artesunato', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Não existe interação direta conhecida entre o artesunato e o álcool; recomenda-se prudência durante o tratamento da malária.',
   'No direct interaction is known between artesunate and alcohol; caution is advised during malaria treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'SmPC-padrão WHO-prequalificado (MA152) e EMA (Artesunate Amivas) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO-prequalified model SmPC (MA152) and EMA (Artesunate Amivas) — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('artemeter-lumefantrina', 'refeicao_gordurosa', 'Refeição rica em gordura', 'High-fat meal', 'minor',
   'A toma com alimentos (em particular com alguma gordura) aumenta a absorção do lumefantrina e é recomendada para otimizar a eficácia do tratamento.',
   'Taking with food (particularly with some fat) increases lumefantrine absorption and is recommended to optimise treatment efficacy.',
   'Tomar com alimentos, de preferência com alguma gordura, para maximizar a absorção.',
   'Take with food, preferably with some fat, to maximise absorption.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 1),
  ('artemeter-lumefantrina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode potenciar os efeitos no sistema nervoso central durante o tratamento com arteméter + lumefantrina.',
   'Alcohol may potentiate central nervous system effects during artemether + lumefantrine treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 1),
  ('artesunato-amodiaquina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma com alimentos pode reduzir as náuseas associadas à amodiaquina; a absorção não é afetada de forma relevante.',
   'Taking with food may reduce amodiaquine-related nausea; absorption is not relevantly affected.',
   'Tomar com alimentos se ocorrer náusea.',
   'Take with food if nausea occurs.',
   'OMS (WHO) — Directrizes para a malária (artesunato + amodiaquina, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (artesunate + amodiaquine, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('artesunato-amodiaquina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais e a hepatotoxicidade da amodiaquina; limitar o consumo.',
   'Alcohol may worsen amodiaquine gastrointestinal effects and hepatotoxicity; limit intake.',
   'Limitar ou evitar o consumo de álcool durante o tratamento.',
   'Limit or avoid alcohol intake during treatment.',
   'OMS (WHO) — Directrizes para a malária (artesunato + amodiaquina, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (artesunate + amodiaquine, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('diidroartemisinina-piperaquina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma com alimentos aumenta a absorção da piperaquina; recomenda-se tomar com alimentos para reduzir a variabilidade.',
   'Taking with food increases piperaquine absorption; it is recommended to take with food to reduce variability.',
   'Tomar com alimentos, de preferência à mesma refeição diária.',
   'Take with food, preferably at the same daily meal.',
   'EMA — EPAR Eurartesim (diidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 1),
  ('diidroartemisinina-piperaquina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode potenciar os efeitos no sistema nervoso central durante o tratamento; limitar o consumo.',
   'Alcohol may potentiate central nervous system effects during treatment; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'EMA — EPAR Eurartesim (diidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 1),
  ('sulfadoxina-pirimetamina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A sulfadoxina + pirimetamina pode ser tomada com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal.',
   'Sulfadoxine + pyrimethamine can be taken with or without food; taking with food reduces gastrointestinal discomfort.',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'OMS (WHO) — Directrizes para a malária (sulfadoxina + pirimetamina): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (sulfadoxine + pyrimethamine): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('sulfadoxina-pirimetamina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais da sulfadoxina + pirimetamina; limitar o consumo.',
   'Alcohol may worsen the gastrointestinal effects of sulfadoxine + pyrimethamine; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'OMS (WHO) — Directrizes para a malária (sulfadoxina + pirimetamina): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (sulfadoxine + pyrimethamine): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('mefloquina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma da mefloquina com alimentos e com bastante água reduz as náuseas e os vómitos, frequentes no início do tratamento.',
   'Taking mefloquine with food and plenty of water reduces the nausea and vomiting common early in treatment.',
   'Tomar com alimentos e um copo de água; se houver vómitos persistentes, contactar o médico (pode ser necessário repetir a dose).',
   'Take with food and a glass of water; with persistent vomiting, contact the doctor (the dose may need to be repeated).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 1),
  ('mefloquina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool pode aumentar o risco de convulsões e de efeitos neuropsiquiátricos (tonturas, ansiedade, pesadelos) associados à mefloquina.',
   'Alcohol may increase the risk of seizures and of the neuropsychiatric effects (dizziness, anxiety, nightmares) associated with mefloquine.',
   'Evitar ou limitar fortemente o consumo de álcool durante o tratamento.',
   'Avoid or strongly limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 1),
  ('primaquina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A primaquina pode ser tomada com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal.',
   'Primaquine can be taken with or without food; taking with food reduces gastrointestinal discomfort.',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Primaquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 'DailyMed/FDA (NIH/NLM) — approved Primaquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 1),
  ('primaquina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais da primaquina; limitar o consumo durante o tratamento.',
   'Alcohol may worsen the gastrointestinal effects of primaquine; limit intake during treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Primaquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 'DailyMed/FDA (NIH/NLM) — approved Primaquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 1),
  ('quinina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A quinina pode ser tomada com alimentos para reduzir o desconforto gastrointestinal; a absorção não é afetada de forma relevante.',
   'Quinine can be taken with food to reduce gastrointestinal discomfort; absorption is not relevantly affected.',
   'Tomar com alimentos se ocorrer náusea ou desconforto gástrico.',
   'Take with food if nausea or gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 1),
  ('quinina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool pode potenciar os efeitos depressores do SNC da quinina e o risco de hipoglicemia; limitar o consumo.',
   'Alcohol may potentiate the CNS-depressant effects of quinine and the risk of hypoglycaemia; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 1),
  ('atovaquona-proguanil', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma com alimentos (ou leite) aumenta a absorção da atovaquona (2–3 vezes) e é recomendada para otimizar a eficácia.',
   'Taking with food (or milk) increases atovaquone absorption (2–3-fold) and is recommended to optimise efficacy.',
   'Tomar com alimentos ou leite, de preferência à mesma refeição diária.',
   'Take with food or milk, preferably at the same daily meal.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atovaquona + Proguanil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 'DailyMed/FDA (NIH/NLM) — approved Atovaquone + Proguanil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 1),
  ('atovaquona-proguanil', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais da atovaquona + proguanil; limitar o consumo.',
   'Alcohol may worsen the gastrointestinal effects of atovaquone + proguanil; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atovaquona + Proguanil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 'DailyMed/FDA (NIH/NLM) — approved Atovaquone + Proguanil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 1),
  ('tafenoquina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A tafenoquina pode ser tomada com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal.',
   'Tafenoquine can be taken with or without food; taking with food reduces gastrointestinal discomfort.',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tafenoquina (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 'DailyMed/FDA (NIH/NLM) — approved Tafenoquine label (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 1),
  ('tafenoquina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos psiquiátricos (insónia, ansiedade, sonhos anormais) da tafenoquina; limitar o consumo.',
   'Alcohol may worsen the psychiatric effects (insomnia, anxiety, abnormal dreams) of tafenoquine; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tafenoquina (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 'DailyMed/FDA (NIH/NLM) — approved Tafenoquine label (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 1),
  ('ampicilina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os alimentos reduzem ligeiramente a absorção da ampicilina oral; a toma em jejum maximiza os níveis plasmáticos.',
   'Food slightly reduces the absorption of oral ampicillin; taking it on an empty stomach maximises plasma levels.',
   'Tomar a ampicilina 1 hora antes ou 2 horas depois das refeições.',
   'Take ampicillin 1 hour before or 2 hours after meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 'DailyMed/FDA (NIH/NLM) — approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 1),
  ('ampicilina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool não interage diretamente com a ampicilina; recomenda-se prudência pelo risco de efeitos gastrointestinais aditivos.',
   'Alcohol does not interact directly with ampicillin; caution is advised due to additive gastrointestinal effects.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 'DailyMed/FDA (NIH/NLM) — approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 1),
  ('amoxicilina-clavulanato', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A toma com alimentos reduz o desconforto gastrointestinal e melhora a absorção do clavulanato; recomenda-se tomar no início da refeição.',
   'Taking with food reduces gastrointestinal discomfort and improves clavulanate absorption; taking at the start of a meal is recommended.',
   'Tomar no início de uma refeição para reduzir os efeitos gastrointestinais.',
   'Take at the start of a meal to reduce gastrointestinal effects.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amoxicilina + Ácido Clavulânico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 'DailyMed/FDA (NIH/NLM) — approved Amoxicillin + Clavulanate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 1),
  ('amoxicilina-clavulanato', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais da amoxicilina + clavulanato; limitar o consumo.',
   'Alcohol may worsen the gastrointestinal effects of amoxicillin + clavulanate; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amoxicilina + Ácido Clavulânico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 'DailyMed/FDA (NIH/NLM) — approved Amoxicillin + Clavulanate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 1),
  ('piperacilina-tazobactam', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No significant food interaction', 'none',
   'A piperacilina + tazobactam é administrada por via intravenosa; não tem interação alimentar relevante.',
   'Piperacillin + tazobactam is given intravenously; it has no significant food interaction.',
   'Não é necessário ajustar a toma em função das refeições.',
   'No need to adjust dosing around meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Piperacilina + Tazobactam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 'DailyMed/FDA (NIH/NLM) — approved Piperacillin + Tazobactam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 1),
  ('piperacilina-tazobactam', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Não existe interação direta conhecida entre a piperacilina + tazobactam e o álcool; recomenda-se prudência durante o tratamento.',
   'No direct interaction is known between piperacillin + tazobactam and alcohol; caution is advised during treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Piperacilina + Tazobactam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 'DailyMed/FDA (NIH/NLM) — approved Piperacillin + Tazobactam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 1),
  ('ceftriaxona', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No significant food interaction', 'none',
   'A ceftriaxona é administrada por via intravenosa ou intramuscular; não tem interação alimentar relevante.',
   'Ceftriaxone is given intravenously or intramuscularly; it has no significant food interaction.',
   'Não é necessário ajustar a toma em função das refeições.',
   'No need to adjust dosing around meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ceftriaxona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 'DailyMed/FDA (NIH/NLM) — approved Ceftriaxone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 1),
  ('ceftriaxona', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Não existe interação direta conhecida entre a ceftriaxona e o álcool; recomenda-se prudência durante o tratamento.',
   'No direct interaction is known between ceftriaxone and alcohol; caution is advised during treatment.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ceftriaxona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 'DailyMed/FDA (NIH/NLM) — approved Ceftriaxone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 1),
  ('cefalexina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A cefalexina pode ser tomada com ou sem alimentos; a toma com alimentos reduz o desconforto gastrointestinal.',
   'Cephalexin can be taken with or without food; taking with food reduces gastrointestinal discomfort.',
   'Tomar com alimentos se ocorrer desconforto gástrico.',
   'Take with food if gastric discomfort occurs.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 'DailyMed/FDA (NIH/NLM) — approved Cephalexin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 1),
  ('cefalexina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais da cefalexina; limitar o consumo.',
   'Alcohol may worsen the gastrointestinal effects of cephalexin; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 'DailyMed/FDA (NIH/NLM) — approved Cephalexin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 1),
  ('cefuroxima', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A cefuroxima axetil deve ser tomada após as refeições: os alimentos melhoram a sua absorção e reduzem o desconforto gastrointestinal.',
   'Cefuroxime axetil should be taken after meals: food improves its absorption and reduces gastrointestinal discomfort.',
   'Tomar logo após uma refeição.',
   'Take immediately after a meal.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima Axetil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 'DailyMed/FDA (NIH/NLM) — approved Cefuroxime Axetil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 1),
  ('cefuroxima', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool pode agravar os efeitos gastrointestinais da cefuroxima; limitar o consumo.',
   'Alcohol may worsen the gastrointestinal effects of cefuroxime; limit intake.',
   'Limitar o consumo de álcool durante o tratamento.',
   'Limit alcohol intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima Axetil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 'DailyMed/FDA (NIH/NLM) — approved Cefuroxime Axetil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;-- =====================================================================
-- 2. Doença / Condição (drug_disease_interactions)
-- =====================================================================
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order
FROM public.drugs d
JOIN (VALUES
  ('artesunato', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'Os derivados da artemisinina podem prolongar ligeiramente o intervalo QT; usar com precaução em doentes com QT prolongado ou com fármacos que prolongam o QT.',
   'Artemisinin derivatives may slightly prolong the QT interval; use with caution in patients with QT prolongation or with QT-prolonging drugs.',
   'Vigiar ECG em doentes de risco.',
   'Monitor ECG in at-risk patients.',
   'SmPC-padrão WHO-prequalificado (MA152) e EMA (Artesunate Amivas) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO-prequalified model SmPC (MA152) and EMA (Artesunate Amivas) — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('artesunato', 'doenca_hepatica_grave', 'Doença hepática grave', 'Severe liver disease', 'precaution', 'moderate',
   'Os dados em insuficiência hepática grave são limitados; o artesunato deve ser usado com precaução, com vigilância.',
   'Data in severe hepatic impairment are limited; artesunate should be used with caution, with monitoring.',
   'Usar com precaução na doença hepática grave.',
   'Use with caution in severe liver disease.',
   'SmPC-padrão WHO-prequalificado (MA152) e EMA (Artesunate Amivas) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO-prequalified model SmPC (MA152) and EMA (Artesunate Amivas) — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('artemeter-lumefantrina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'O lumefantrina prolonga o intervalo QT; o risco de arritmias aumenta em doentes com QT prolongado ou com fármacos que prolongam o QT.',
   'Lumefantrine prolongs the QT interval; the arrhythmia risk increases in patients with QT prolongation or with QT-prolonging drugs.',
   'Evitar em QT prolongado conhecido ou com fármacos que prolongam o QT; vigiar ECG.',
   'Avoid in known QT prolongation or with QT-prolonging drugs; monitor ECG.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 1),
  ('artemeter-lumefantrina', 'doenca_hepatica_grave', 'Doença hepática grave', 'Severe liver disease', 'precaution', 'moderate',
   'O arteméter e o lumefantrina são metabolizados no fígado (CYP3A4); na doença hepática grave a exposição pode aumentar e exige precaução.',
   'Artemether and lumefantrine are metabolised in the liver (CYP3A4); in severe liver disease exposure may increase and requires caution.',
   'Usar com precaução na doença hepática grave.',
   'Use with caution in severe liver disease.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 1),
  ('artesunato-amodiaquina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A amodiaquina prolonga o intervalo QT; o risco aumenta em doentes com QT prolongado ou com fármacos que prolongam o QT.',
   'Amodiaquine prolongs the QT interval; the risk increases in patients with QT prolongation or with QT-prolonging drugs.',
   'Vigiar ECG em doentes de risco; evitar com fármacos que prolongam o QT.',
   'Monitor ECG in at-risk patients; avoid with QT-prolonging drugs.',
   'OMS (WHO) — Directrizes para a malária (artesunato + amodiaquina, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (artesunate + amodiaquine, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('artesunato-amodiaquina', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'A amodiaquina é hepatotóxica (incluindo hepatite grave); usar com precaução em doentes com doença hepática.',
   'Amodiaquine is hepatotoxic (including severe hepatitis); use with caution in patients with liver disease.',
   'Vigiar função hepática; suspender perante sintomas de hepatite.',
   'Monitor liver function; stop with hepatitis symptoms.',
   'OMS (WHO) — Directrizes para a malária (artesunato + amodiaquina, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (artesunate + amodiaquine, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('diidroartemisinina-piperaquina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A piperaquina prolonga de forma significativa o intervalo QT; o risco de arritmias aumenta em doentes com QT prolongado ou com fármacos que prolongam o QT.',
   'Piperaquine significantly prolongs the QT interval; the arrhythmia risk increases in patients with QT prolongation or with QT-prolonging drugs.',
   'Evitar em QT prolongado conhecido ou com fármacos que prolongam o QT; vigiar ECG.',
   'Avoid in known QT prolongation or with QT-prolonging drugs; monitor ECG.',
   'EMA — EPAR Eurartesim (diidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 1),
  ('diidroartemisinina-piperaquina', 'doenca_hepatica_grave', 'Doença hepática grave', 'Severe liver disease', 'precaution', 'moderate',
   'A diidroartemisinina e a piperaquina são metabolizadas no fígado; na doença hepática grave a exposição pode aumentar e exige precaução.',
   'Dihydroartemisinin and piperaquine are metabolised in the liver; in severe liver disease exposure may increase and requires caution.',
   'Usar com precaução na doença hepática grave.',
   'Use with caution in severe liver disease.',
   'EMA — EPAR Eurartesim (diidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 1),
  ('sulfadoxina-pirimetamina', 'alergia_sulfonamidas', 'Alergia a sulfonamidas', 'Sulphonamide allergy', 'contraindication', 'moderate',
   'A sulfadoxina é uma sulfonamida; está contraindicada em doentes com alergia prévia a sulfonamidas (risco de reações graves, incluindo SJS/TEN).',
   'Sulfadoxine is a sulphonamide; it is contraindicated in patients with prior sulphonamide allergy (risk of severe reactions, including SJS/TEN).',
   'Contraindicado em alergia a sulfonamidas; escolher alternativa antimalárica.',
   'Contraindicated in sulphonamide allergy; choose an alternative antimalarial.',
   'OMS (WHO) — Directrizes para a malária (sulfadoxina + pirimetamina): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (sulfadoxine + pyrimethamine): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('sulfadoxina-pirimetamina', 'deficiencia_g6pd', 'Deficiência de G6PD', 'G6PD deficiency', 'precaution', 'moderate',
   'A sulfadoxina pode causar hemólise em doentes com deficiência de G6PD; usar com precaução e vigiar sinais de hemólise.',
   'Sulfadoxine can cause haemolysis in patients with G6PD deficiency; use with caution and monitor for signs of haemolysis.',
   'Usar com precaução na deficiência de G6PD; vigiar hemoglobina e sinais de hemólise.',
   'Use with caution in G6PD deficiency; monitor haemoglobin and signs of haemolysis.',
   'OMS (WHO) — Directrizes para a malária (sulfadoxina + pirimetamina): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (sulfadoxine + pyrimethamine): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 1),
  ('mefloquina', 'epilepsia', 'Epilepsia', 'Epilepsy', 'contraindication', 'moderate',
   'A mefloquina pode baixar o limiar convulsivo; está contraindicada em doentes com epilepsia ou antecedentes de convulsões.',
   'Mefloquine can lower the seizure threshold; it is contraindicated in patients with epilepsy or a history of seizures.',
   'Contraindicada em epilepsia ou antecedentes convulsivos; escolher alternativa antimalárica.',
   'Contraindicated in epilepsy or a history of seizures; choose an alternative antimalarial.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 1),
  ('mefloquina', 'doenca_psiquiatrica', 'Doença psiquiátrica (depressão ativa, psicose)', 'Psychiatric disease (active depression, psychosis)', 'contraindication', 'moderate',
   'A mefloquina causa efeitos neuropsiquiátricos graves (ansiedade, depressão, psicose, ideação suicida); está contraindicada em doença psiquiátrica ativa ou história de psicose.',
   'Mefloquine causes severe neuropsychiatric effects (anxiety, depression, psychosis, suicidal ideation); it is contraindicated in active psychiatric disease or a history of psychosis.',
   'Contraindicada em depressão ativa ou psicose; suspender perante sintomas neuropsiquiátricos.',
   'Contraindicated in active depression or psychosis; stop with neuropsychiatric symptoms.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 1),
  ('primaquina', 'deficiencia_g6pd', 'Deficiência de G6PD', 'G6PD deficiency', 'contraindication', 'moderate',
   'A primaquina causa hemólise grave em doentes com deficiência de G6PD; está contraindicada sem rastreio prévio do défice.',
   'Primaquine causes severe haemolysis in patients with G6PD deficiency; it is contraindicated without prior screening for the deficiency.',
   'Rastrear G6PD antes de prescrever; contraindicada na deficiência ou estado desconhecido.',
   'Screen for G6PD before prescribing; contraindicated in deficiency or unknown status.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Primaquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 'DailyMed/FDA (NIH/NLM) — approved Primaquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 1),
  ('primaquina', 'metemoglobinemia', 'Metemoglobinemia', 'Methaemoglobinaemia', 'precaution', 'moderate',
   'A primaquina pode causar metemoglobinemia, sobretudo em doses elevadas ou em doentes com défice de metemoglobina redutase.',
   'Primaquine can cause methaemoglobinaemia, especially at high doses or in patients with methaemoglobin reductase deficiency.',
   'Vigiar cianose, cefaleia e dispneia; suspender perante metemoglobinemia.',
   'Monitor for cyanosis, headache and dyspnoea; stop with methaemoglobinaemia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Primaquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 'DailyMed/FDA (NIH/NLM) — approved Primaquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 1),
  ('quinina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation', 'precaution', 'moderate',
   'A quinina prolonga o intervalo QT e pode causar arritmias ventriculares; o risco aumenta em QT prolongado ou com fármacos que prolongam o QT.',
   'Quinine prolongs the QT interval and can cause ventricular arrhythmias; the risk increases in QT prolongation or with QT-prolonging drugs.',
   'Evitar em QT prolongado conhecido; vigiar ECG e eletrólitos.',
   'Avoid in known QT prolongation; monitor ECG and electrolytes.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 1),
  ('quinina', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus', 'precaution', 'moderate',
   'A quinina estimula a libertação de insulina e pode causar hipoglicemia, sobretudo em doentes diabéticos, desnutridos ou com insuficiência renal.',
   'Quinine stimulates insulin release and can cause hypoglycaemia, especially in diabetic, malnourished or renally impaired patients.',
   'Vigiar glicemia em doentes de risco; tratar a hipoglicemia prontamente.',
   'Monitor blood glucose in at-risk patients; treat hypoglycaemia promptly.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 1),
  ('atovaquona-proguanil', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'precaution', 'moderate',
   'A atovaquona não é dialisável e a sua excreção depende da via biliar; na insuficiência renal grave (CrCl < 30 ml/min) a profilaxia não é recomendada e o tratamento exige precaução.',
   'Atovaquone is not dialysable and its excretion depends on the biliary route; in severe renal impairment (CrCl < 30 ml/min) prophylaxis is not recommended and treatment requires caution.',
   'Evitar a profilaxia em CrCl < 30 ml/min; usar com precaução no tratamento.',
   'Avoid prophylaxis in CrCl < 30 ml/min; use with caution for treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atovaquona + Proguanil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 'DailyMed/FDA (NIH/NLM) — approved Atovaquone + Proguanil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 1),
  ('atovaquona-proguanil', 'doenca_hepatica', 'Doença hepática', 'Liver disease', 'precaution', 'moderate',
   'O proguanil é metabolizado no fígado; na doença hepática a exposição pode aumentar e exige precaução.',
   'Proguanil is metabolised in the liver; in liver disease exposure may increase and requires caution.',
   'Usar com precaução na doença hepática.',
   'Use with caution in liver disease.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atovaquona + Proguanil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 'DailyMed/FDA (NIH/NLM) — approved Atovaquone + Proguanil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 1),
  ('tafenoquina', 'deficiencia_g6pd', 'Deficiência de G6PD', 'G6PD deficiency', 'contraindication', 'moderate',
   'A tafenoquina causa hemólise grave em doentes com deficiência de G6PD; está contraindicada na deficiência ou quando o estado de G6PD é desconhecido.',
   'Tafenoquine causes severe haemolysis in patients with G6PD deficiency; it is contraindicated in deficiency or when G6PD status is unknown.',
   'Rastreio obrigatório de G6PD antes de prescrever; contraindicada na deficiência ou estado desconhecido.',
   'Mandatory G6PD screening before prescribing; contraindicated in deficiency or unknown status.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tafenoquina (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 'DailyMed/FDA (NIH/NLM) — approved Tafenoquine label (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 1),
  ('tafenoquina', 'doenca_psiquiatrica', 'Doença psiquiátrica (história de psicose)', 'Psychiatric disease (history of psychosis)', 'precaution', 'moderate',
   'A tafenoquina causa efeitos psiquiátricos (insónia, ansiedade, depressão, sonhos anormais); usar com precaução em doentes com doença psiquiátrica.',
   'Tafenoquine causes psychiatric effects (insomnia, anxiety, depression, abnormal dreams); use with caution in patients with psychiatric disease.',
   'Vigiar sintomas psiquiátricos; suspender perante sintomas graves.',
   'Monitor psychiatric symptoms; stop with severe symptoms.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tafenoquina (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 'DailyMed/FDA (NIH/NLM) — approved Tafenoquine label (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 1),
  ('ampicilina', 'alergia_penicilinas', 'Alergia a penicilinas', 'Penicillin allergy', 'contraindication', 'moderate',
   'A ampicilina é uma penicilina; está contraindicada em doentes com alergia prévia a penicilinas (risco de anafilaxia).',
   'Ampicillin is a penicillin; it is contraindicated in patients with prior penicillin allergy (risk of anaphylaxis).',
   'Contraindicada em alergia a penicilinas; escolher alternativa de outra classe.',
   'Contraindicated in penicillin allergy; choose an alternative from another class.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 'DailyMed/FDA (NIH/NLM) — approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 1),
  ('ampicilina', 'mononucleose_infecciosa', 'Mononucleose infecciosa', 'Infectious mononucleosis', 'precaution', 'moderate',
   'A ampicilina causa erupção cutânea maculopapular frequente em doentes com mononucleose infecciosa.',
   'Ampicillin frequently causes a maculopapular rash in patients with infectious mononucleosis.',
   'Evitar ampicilina na mononucleose; preferir alternativa quando possível.',
   'Avoid ampicillin in mononucleosis; prefer an alternative when possible.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 'DailyMed/FDA (NIH/NLM) — approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 1),
  ('amoxicilina-clavulanato', 'alergia_penicilinas', 'Alergia a penicilinas', 'Penicillin allergy', 'contraindication', 'moderate',
   'A amoxicilina é uma penicilina; a associação está contraindicada em doentes com alergia prévia a penicilinas.',
   'Amoxicillin is a penicillin; the combination is contraindicated in patients with prior penicillin allergy.',
   'Contraindicada em alergia a penicilinas; escolher alternativa de outra classe.',
   'Contraindicated in penicillin allergy; choose an alternative from another class.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amoxicilina + Ácido Clavulânico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 'DailyMed/FDA (NIH/NLM) — approved Amoxicillin + Clavulanate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 1),
  ('amoxicilina-clavulanato', 'historia_ictericia_clavulanato', 'Icterícia / disfunção hepática prévia (com clavulanato)', 'Prior jaundice / hepatic dysfunction (with clavulanate)', 'contraindication', 'moderate',
   'O ácido clavulânico associa-se a hepatite colestática; a associação está contraindicada em doentes com história de icterícia ou disfunção hepática atribuída ao clavulanato.',
   'Clavulanic acid is associated with cholestatic hepatitis; the combination is contraindicated in patients with a history of jaundice or hepatic dysfunction attributed to clavulanate.',
   'Contraindicada em história de icterícia com amoxicilina + clavulanato.',
   'Contraindicated in a history of jaundice with amoxicillin + clavulanate.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amoxicilina + Ácido Clavulânico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 'DailyMed/FDA (NIH/NLM) — approved Amoxicillin + Clavulanate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 1),
  ('piperacilina-tazobactam', 'alergia_penicilinas', 'Alergia a penicilinas', 'Penicillin allergy', 'contraindication', 'moderate',
   'A piperacilina é uma penicilina; a associação está contraindicada em doentes com alergia prévia a penicilinas.',
   'Piperacillin is a penicillin; the combination is contraindicated in patients with prior penicillin allergy.',
   'Contraindicada em alergia a penicilinas; escolher alternativa de outra classe.',
   'Contraindicated in penicillin allergy; choose an alternative from another class.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Piperacilina + Tazobactam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 'DailyMed/FDA (NIH/NLM) — approved Piperacillin + Tazobactam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 1),
  ('piperacilina-tazobactam', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'A piperacilina e o tazobactam são excretados por via renal; na insuficiência renal é necessário ajustar a dose e o intervalo.',
   'Piperacillin and tazobactam are renally excreted; in renal impairment the dose and interval must be adjusted.',
   'Ajustar a dose à clearance de creatinina.',
   'Adjust the dose to creatinine clearance.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Piperacilina + Tazobactam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 'DailyMed/FDA (NIH/NLM) — approved Piperacillin + Tazobactam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 1),
  ('ceftriaxona', 'alergia_cefalosporinas', 'Alergia a cefalosporinas', 'Cephalosporin allergy', 'precaution', 'moderate',
   'A ceftriaxona é uma cefalosporina; está contraindicada em alergia prévia a cefalosporinas e exige precaução em alergia grave a penicilinas (reatividade cruzada).',
   'Ceftriaxone is a cephalosporin; it is contraindicated in prior cephalosporin allergy and requires caution in severe penicillin allergy (cross-reactivity).',
   'Contraindicada em alergia a cefalosporinas; precaução em alergia grave a penicilinas.',
   'Contraindicated in cephalosporin allergy; caution in severe penicillin allergy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ceftriaxona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 'DailyMed/FDA (NIH/NLM) — approved Ceftriaxone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 1),
  ('ceftriaxona', 'hiperbilirrubinemia_neonatal', 'Hiperbilirrubinemia neonatal', 'Neonatal hyperbilirubinaemia', 'contraindication', 'moderate',
   'A ceftriaxona desloca a bilirrubina da albumina e está contraindicada em recém-nascidos com hiperbilirrubinemia (risco de encefalopatia bilirrubínica).',
   'Ceftriaxone displaces bilirubin from albumin and is contraindicated in neonates with hyperbilirubinaemia (risk of bilirubin encephalopathy).',
   'Contraindicada em recém-nascidos com hiperbilirrubinemia; preferir alternativa.',
   'Contraindicated in neonates with hyperbilirubinaemia; prefer an alternative.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ceftriaxona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 'DailyMed/FDA (NIH/NLM) — approved Ceftriaxone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 1),
  ('cefalexina', 'alergia_cefalosporinas', 'Alergia a cefalosporinas', 'Cephalosporin allergy', 'precaution', 'moderate',
   'A cefalexina é uma cefalosporina; está contraindicada em alergia prévia a cefalosporinas e exige precaução em alergia grave a penicilinas.',
   'Cephalexin is a cephalosporin; it is contraindicated in prior cephalosporin allergy and requires caution in severe penicillin allergy.',
   'Contraindicada em alergia a cefalosporinas; precaução em alergia grave a penicilinas.',
   'Contraindicated in cephalosporin allergy; caution in severe penicillin allergy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 'DailyMed/FDA (NIH/NLM) — approved Cephalexin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 1),
  ('cefalexina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'A cefalexina é excretada por via renal; na insuficiência renal é necessário ajustar a dose.',
   'Cephalexin is renally excreted; in renal impairment the dose must be adjusted.',
   'Ajustar a dose à função renal.',
   'Adjust the dose to renal function.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 'DailyMed/FDA (NIH/NLM) — approved Cephalexin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 1),
  ('cefuroxima', 'alergia_cefalosporinas', 'Alergia a cefalosporinas', 'Cephalosporin allergy', 'precaution', 'moderate',
   'A cefuroxima é uma cefalosporina; está contraindicada em alergia prévia a cefalosporinas e exige precaução em alergia grave a penicilinas.',
   'Cefuroxime is a cephalosporin; it is contraindicated in prior cephalosporin allergy and requires caution in severe penicillin allergy.',
   'Contraindicada em alergia a cefalosporinas; precaução em alergia grave a penicilinas.',
   'Contraindicated in cephalosporin allergy; caution in severe penicillin allergy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima Axetil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 'DailyMed/FDA (NIH/NLM) — approved Cefuroxime Axetil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 1),
  ('cefuroxima', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   'A cefuroxima é excretada por via renal; na insuficiência renal é necessário ajustar a dose.',
   'Cefuroxime is renally excreted; in renal impairment the dose must be adjusted.',
   'Ajustar a dose à função renal.',
   'Adjust the dose to renal function.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima Axetil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 'DailyMed/FDA (NIH/NLM) — approved Cefuroxime Axetil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;-- =====================================================================
-- 3. Gestação / Lactação (drug_pregnancy_info, 1:1 por fármaco)
-- =====================================================================
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
       v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
       v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('artesunato', 'caution',
   'O artesunato injetável é o fármaco de escolha na malária grave na gravidez (todas as fases); o benefício do tratamento supera claramente o risco.',
   'Injectable artesunate is the drug of choice for severe malaria in pregnancy (all trimesters); the treatment benefit clearly outweighs the risk.',
   'Usar na malária grave na gravidez, em todas as fases, conforme as diretrizes da OMS.',
   'Use for severe malaria in pregnancy, in all trimesters, per WHO guidelines.',
   'Excretado no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'SmPC-padrão WHO-prequalificado (MA152) e EMA (Artesunate Amivas) — Directrizes da OMS para a malária: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO-prequalified model SmPC (MA152) and EMA (Artesunate Amivas) — WHO Guidelines for malaria: https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria'),
  ('artemeter-lumefantrina', 'caution',
   'O arteméter + lumefantrina é recomendado pela OMS para a malária não complicada na gravidez no 2.º e 3.º trimestres; no 1.º trimestre, usar se o benefício justificar.',
   'Artemether + lumefantrine is recommended by WHO for uncomplicated malaria in pregnancy in the 2nd and 3rd trimesters; in the 1st trimester, use if the benefit justifies it.',
   'Usar no 2.º e 3.º trimestres; no 1.º trimestre, considerar apenas se o benefício superar o risco.',
   'Use in the 2nd and 3rd trimesters; in the 1st trimester, consider only if the benefit outweighs the risk.',
   'Excretado no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Possível indução do CYP3A4 pelos derivados da artemisinina — considerar método contracetivo adicional se usado contracetivo hormonal.',
   'Possible CYP3A4 induction by artemisinin derivatives — consider an additional contraceptive method if a hormonal contraceptive is used.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Arteméter + Lumefantrina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf', 'DailyMed/FDA (NIH/NLM) — approved Artemether + Lumefantrine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7866ec19-dfac-47d4-a53f-511a12643cbf'),
  ('artesunato-amodiaquina', 'caution',
   'A OMS não recomenda o artesunato + amodiaquina no 1.º trimestre; no 2.º e 3.º trimestres pode ser usado se o benefício justificar.',
   'WHO does not recommend artesunate + amodiaquine in the 1st trimester; in the 2nd and 3rd trimesters it may be used if the benefit justifies it.',
   'Evitar no 1.º trimestre; considerar apenas se não existir alternativa.',
   'Avoid in the 1st trimester; consider only if no alternative exists.',
   'Excretado no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'OMS (WHO) — Directrizes para a malária (artesunato + amodiaquina, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (artesunate + amodiaquine, Coarsucam): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria'),
  ('diidroartemisinina-piperaquina', 'caution',
   'A diidroartemisinina + piperaquina é recomendada pela OMS para a malária na gravidez no 2.º e 3.º trimestres; no 1.º trimestre os dados são limitados.',
   'Dihydroartemisinin + piperaquine is recommended by WHO for malaria in pregnancy in the 2nd and 3rd trimesters; data in the 1st trimester are limited.',
   'Usar no 2.º e 3.º trimestres; no 1.º trimestre, considerar apenas se o benefício superar o risco.',
   'Use in the 2nd and 3rd trimesters; in the 1st trimester, consider only if the benefit outweighs the risk.',
   'Excretado no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Possível indução do CYP3A4 pelos derivados da artemisinina — considerar método contracetivo adicional se usado contracetivo hormonal.',
   'Possible CYP3A4 induction by artemisinin derivatives — consider an additional contraceptive method if a hormonal contraceptive is used.',
   'EMA — EPAR Eurartesim (diidroartemisinina + piperaquina): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim', 'EMA — EPAR Eurartesim (dihydroartemisinin + piperaquine): https://www.ema.europa.eu/en/medicines/human/EPAR/eurartesim'),
  ('sulfadoxina-pirimetamina', 'caution',
   'A sulfadoxina + pirimetamina é usada na gravidez como tratamento intermitente preventivo da malária (TPIp) a partir do 2.º trimestre, com suplementação de ácido fólico.',
   'Sulfadoxine + pyrimethamine is used in pregnancy as intermittent preventive treatment of malaria (IPTp) from the 2nd trimester, with folic acid supplementation.',
   'Usar como TPIp no 2.º e 3.º trimestres, com ácido fólico.',
   'Use as IPTp in the 2nd and 3rd trimesters, with folic acid.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'OMS (WHO) — Directrizes para a malária (sulfadoxina + pirimetamina): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria', 'WHO — Malaria guidelines (sulfadoxine + pyrimethamine): https://www.who.int/teams/global-malaria-programme/guidelines-for-malaria'),
  ('mefloquina', 'caution',
   'A mefloquina pode ser usada na gravidez no 2.º e 3.º trimestres (profilaxia e tratamento); no 1.º trimestre, usar apenas se o benefício justificar.',
   'Mefloquine may be used in pregnancy in the 2nd and 3rd trimesters (prophylaxis and treatment); in the 1st trimester, use only if the benefit justifies it.',
   'Evitar no 1.º trimestre; nos restantes, usar sob vigilância.',
   'Avoid in the 1st trimester; in the others, use under supervision.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Mefloquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd', 'DailyMed/FDA (NIH/NLM) — approved Mefloquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=09716a24-d7da-42b2-af29-c03a1b6670bd'),
  ('primaquina', 'contraindicated',
   'A primaquina está contraindicada na gravidez: o estado de G6PD do feto é desconhecido e existe risco de hemólise fetal grave.',
   'Primaquine is contraindicated in pregnancy: the fetal G6PD status is unknown and there is a risk of severe fetal haemolysis.',
   'Contraindicada na gravidez; adiar a cura radical (erradicação de hipnozoítos) para após o parto.',
   'Contraindicated in pregnancy; postpone radical cure (hypnozoite eradication) until after delivery.',
   'Excretada no leite; contraindicada na amamentação se o lactente for G6PD deficiente ou de estado desconhecido.',
   'Excreted into breast milk; contraindicated in breastfeeding if the infant is G6PD deficient or of unknown status.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Primaquina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88', 'DailyMed/FDA (NIH/NLM) — approved Primaquine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f16166d-678e-51aa-e054-00144ff88e88'),
  ('quinina', 'caution',
   'A quinina é usada na gravidez para a malária por P. falciparum resistente à cloroquina; em doses elevadas tem efeito abortivo histórico, pelo que a dose deve ser rigorosa.',
   'Quinine is used in pregnancy for chloroquine-resistant P. falciparum malaria; at high doses it has a historical abortifacient effect, so dosing must be strict.',
   'Usar nas doses terapêuticas indicadas, sob vigilância; vigiar glicemia.',
   'Use at the indicated therapeutic doses, under supervision; monitor blood glucose.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Quinina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0', 'DailyMed/FDA (NIH/NLM) — approved Quinine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f32f05c-a215-40be-b951-e41a7b54a8a0'),
  ('atovaquona-proguanil', 'caution',
   'A atovaquona + proguanil pode ser usada no tratamento da malária na gravidez quando o benefício justificar; não é recomendada como profilaxia na gravidez.',
   'Atovaquone + proguanil may be used for malaria treatment in pregnancy when the benefit justifies it; it is not recommended as prophylaxis in pregnancy.',
   'Usar no tratamento apenas se o benefício superar o risco; preferir outra profilaxia na gravidez.',
   'Use for treatment only if the benefit outweighs the risk; prefer another prophylaxis in pregnancy.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atovaquona + Proguanil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887', 'DailyMed/FDA (NIH/NLM) — approved Atovaquone + Proguanil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc22e8d8-3bfb-4f70-a599-dd81262a4887'),
  ('tafenoquina', 'contraindicated',
   'A tafenoquina está contraindicada na gravidez: o estado de G6PD do feto é desconhecido e existe risco de hemólise fetal grave.',
   'Tafenoquine is contraindicated in pregnancy: the fetal G6PD status is unknown and there is a risk of severe fetal haemolysis.',
   'Contraindicada na gravidez; adiar a cura radical para após o parto.',
   'Contraindicated in pregnancy; postpone radical cure until after delivery.',
   'Contraindicada na amamentação se o lactente for G6PD deficiente ou de estado desconhecido.',
   'Contraindicated in breastfeeding if the infant is G6PD deficient or of unknown status.',
   'Aconselhar contraceção eficaz durante o tratamento.',
   'Advise effective contraception during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tafenoquina (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a', 'DailyMed/FDA (NIH/NLM) — approved Tafenoquine label (KRINTAFEL): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5cf989d5-36f5-4561-a30b-9fcb9deb6b6a'),
  ('ampicilina', 'compatible',
   'As penicilinas, incluindo a ampicilina, são geralmente seguras na gravidez e são os antibióticos de primeira linha quando indicadas.',
   'Penicillins, including ampicillin, are generally safe in pregnancy and are first-line antibiotics when indicated.',
   'Pode ser usada na gravidez quando indicada, nas doses habituais.',
   'May be used in pregnancy when indicated, at the usual doses.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a', 'DailyMed/FDA (NIH/NLM) — approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=402e7cc7-5ae8-c113-e063-6394a90aa54a'),
  ('amoxicilina-clavulanato', 'compatible',
   'A amoxicilina + clavulanato é geralmente segura na gravidez quando indicada; usar com precaução em história de hepatite colestática (evitar).',
   'Amoxicillin + clavulanate is generally safe in pregnancy when indicated; use with caution in a history of cholestatic hepatitis (avoid).',
   'Pode ser usada na gravidez quando indicada, exceto em história de icterícia com esta associação.',
   'May be used in pregnancy when indicated, except in a history of jaundice with this combination.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amoxicilina + Ácido Clavulânico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87', 'DailyMed/FDA (NIH/NLM) — approved Amoxicillin + Clavulanate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5250085e-5509-c577-e063-6294a90a9b87'),
  ('piperacilina-tazobactam', 'caution',
   'Os dados em humanos são limitados; a piperacilina + tazobactam deve ser usada na gravidez apenas quando o benefício justificar (infeções graves).',
   'Human data are limited; piperacillin + tazobactam should be used in pregnancy only when the benefit justifies it (severe infections).',
   'Usar apenas em infeções graves sem alternativa.',
   'Use only in severe infections without an alternative.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação sob vigilância.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding under supervision.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Piperacilina + Tazobactam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4', 'DailyMed/FDA (NIH/NLM) — approved Piperacillin + Tazobactam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7aebc0e6-89db-4ef0-b5ab-d6b3199bcfc4'),
  ('ceftriaxona', 'compatible',
   'As cefalosporinas, incluindo a ceftriaxona, são geralmente seguras na gravidez quando indicadas.',
   'Cephalosporins, including ceftriaxone, are generally safe in pregnancy when indicated.',
   'Pode ser usada na gravidez quando indicada; evitar em recém-nascidos com hiperbilirrubinemia (não aplicável na gravidez).',
   'May be used in pregnancy when indicated; avoid in neonates with hyperbilirubinaemia (not applicable in pregnancy).',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ceftriaxona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37', 'DailyMed/FDA (NIH/NLM) — approved Ceftriaxone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9efed4c4-72a7-4669-88ae-c80e882c1b37'),
  ('cefalexina', 'compatible',
   'As cefalosporinas, incluindo a cefalexina, são geralmente seguras na gravidez quando indicadas.',
   'Cephalosporins, including cephalexin, are generally safe in pregnancy when indicated.',
   'Pode ser usada na gravidez quando indicada, nas doses habituais.',
   'May be used in pregnancy when indicated, at the usual doses.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42', 'DailyMed/FDA (NIH/NLM) — approved Cephalexin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b73593ce-0b1f-4371-bae1-140742de3b42'),
  ('cefuroxima', 'compatible',
   'As cefalosporinas, incluindo a cefuroxima, são geralmente seguras na gravidez quando indicadas.',
   'Cephalosporins, including cefuroxime, are generally safe in pregnancy when indicated.',
   'Pode ser usada na gravidez quando indicada, nas doses habituais.',
   'May be used in pregnancy when indicated, at the usual doses.',
   'Excretada no leite em pequenas quantidades; compatível com a amamentação.',
   'Excreted into breast milk in small amounts; compatible with breastfeeding.',
   'Sem contraceção adicional específica.',
   'No specific additional contraception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima Axetil: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a', 'DailyMed/FDA (NIH/NLM) — approved Cefuroxime Axetil label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76cec54f-d167-4298-951b-5411a3c47f4a')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- FIM — 102: 32 alimento + 32 doença + 16 gestação (16 fármacos)
-- =====================================================================


