-- =====================================================================
-- 110 — Dimensões alimento/doença (lote 4b: 15 fármacos)
-- ---------------------------------------------------------------------
-- Completa as dimensões em falta dos 15 fármacos restantes (auditoria
-- 2026-08-10; com a 109 + esta, 182/182 fármacos com as 3 dimensões):
--   • 9 só falta alimento (já têm doença + gestação): ácido tranexâmico,
--     epoetina alfa, etilefrina, fitomenadiona, fondaparinux, formoterol,
--     ipratrópio, salmeterol, tiotrópio;
--   • 4 falta alimento + doença (já têm gestação): filgrastim,
--     levonorgestrel, poractanto alfa, tiamazol;
--   • 2 só falta doença (já têm alimento + gestação): dextrometorfano,
--     nistatina.
-- Padrão da 099/101/102/109: INSERT com JOIN (VALUES) ON d.slug = v.slug +
-- ON CONFLICT DO NOTHING, status 'published'.
-- Conteúdo autoral, ancorado nos rótulos aprovados DailyMed citados
-- (setIDs validados nas migrações 064/065/085/093/095/096).
-- Idempotente: reaplicar é seguro.
-- =====================================================================

-- =====================================================================
-- 1. Alimento / Bebida (drug_food_interactions)
-- =====================================================================
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity,
   mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
       v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('acido_tranexamico', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O ácido tranexâmico pode ser administrado com ou sem alimentos; a toma com alimentos pode reduzir a irritação gastrointestinal.',
   'Tranexamic acid can be administered with or without food; taking it with food may reduce gastrointestinal irritation.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA — Tranexamic Acid Tablets (Northstar Rx): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4877eacd-fda7-4708-93a5-81052c1d2e14', 'DailyMed/FDA — Tranexamic Acid Tablets label (Northstar Rx): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4877eacd-fda7-4708-93a5-81052c1d2e14', 1),
  ('acido_tranexamico', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Sem interação farmacocinética relevante; o álcool pode aumentar o risco de trombose em doentes predispostos — moderação.',
   'No relevant pharmacokinetic interaction; alcohol can increase thrombotic risk in predisposed patients — moderation.',
   'Moderar o consumo de álcool durante o tratamento.',
   'Moderate alcohol intake during treatment.',
   'DailyMed/FDA — Tranexamic Acid Tablets (Northstar Rx): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4877eacd-fda7-4708-93a5-81052c1d2e14', 'DailyMed/FDA — Tranexamic Acid Tablets label (Northstar Rx): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4877eacd-fda7-4708-93a5-81052c1d2e14', 2),
  ('epoetina_alfa', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'A epoetina alfa é administrada por via subcutânea ou intravenosa; os alimentos não afetam a sua farmacocinética.',
   'Epoetin alfa is given subcutaneously or intravenously; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Epoetina alfa: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f2d0b28-9cc5-4523-80b8-637fdaf3f7a5', 'DailyMed/FDA (NIH/NLM) — approved Epoetin alfa label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f2d0b28-9cc5-4523-80b8-637fdaf3f7a5', 1),
  ('epoetina_alfa', 'alimentos_ricos_potassio', 'Alimentos ricos em potássio', 'Potassium-rich foods', 'moderate',
   'A epoetina alfa aumenta o hematócrito e pode elevar o potássio sérico; a ingestão excessiva de potássio pode agravar a hipercaliemia.',
   'Epoetin alfa raises the haematocrit and can increase serum potassium; excessive potassium intake can worsen hyperkalaemia.',
   'Monitorizar o potássio sérico; moderar alimentos muito ricos em potássio em doentes com hipercaliemia.',
   'Monitor serum potassium; moderate very potassium-rich foods in patients with hyperkalaemia.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Epoetina alfa: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f2d0b28-9cc5-4523-80b8-637fdaf3f7a5', 'DailyMed/FDA (NIH/NLM) — approved Epoetin alfa label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f2d0b28-9cc5-4523-80b8-637fdaf3f7a5', 2),
  ('etilefrina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'A etilefrina tem biodisponibilidade oral baixa (efeito de primeira passagem); os alimentos não alteram clinicamente a sua farmacocinética.',
   'Etilefrine has low oral bioavailability (first-pass effect); food does not clinically alter its pharmacokinetics.',
   'Pode tomar com ou sem alimentos.',
   'May be taken with or without food.',
   'Hengstmann JH, Weyand U, Dengler HJ. The pharmacokinetics of etilefrine in man. Eur J Clin Pharmacol 1975 (PMID 9300): https://pubmed.ncbi.nlm.nih.gov/9300/', 'Hengstmann JH, Weyand U, Dengler HJ. The pharmacokinetics of etilefrine in man. Eur J Clin Pharmacol 1975 (PMID 9300): https://pubmed.ncbi.nlm.nih.gov/9300/', 1),
  ('etilefrina', 'cafe_cha', 'Café e chá', 'Coffee and tea', 'minor',
   'As bebidas com cafeína podem potenciar os efeitos estimulantes (taquicardia, tremor) da etilefrina.',
   'Caffeinated drinks can potentiate the stimulant effects (tachycardia, tremor) of etilefrine.',
   'Moderar o consumo de cafeína durante o tratamento.',
   'Moderate caffeine intake during treatment.',
   'Hengstmann JH, Weyand U, Dengler HJ. The pharmacokinetics of etilefrine in man. Eur J Clin Pharmacol 1975 (PMID 9300): https://pubmed.ncbi.nlm.nih.gov/9300/', 'Hengstmann JH, Weyand U, Dengler HJ. The pharmacokinetics of etilefrine in man. Eur J Clin Pharmacol 1975 (PMID 9300): https://pubmed.ncbi.nlm.nih.gov/9300/', 2),
  ('fitomenadiona', 'alimentos', 'Alimentos', 'Food', 'minor',
   'A fitomenadiona (vitamina K1) pode ser administrada com ou sem alimentos; a absorção oral melhora com a toma após refeição.',
   'Phytonadione (vitamin K1) can be administered with or without food; oral absorption improves when taken after a meal.',
   'Pode tomar com ou sem alimentos, de forma consistente.',
   'May be taken with or without food, consistently.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fitomenadiona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c7ef968-2c76-4220-a9ec-3179d243c422', 'DailyMed/FDA (NIH/NLM) — approved Phytonadione label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c7ef968-2c76-4220-a9ec-3179d243c422', 1),
  ('fitomenadiona', 'vitamina_k', 'Alimentos ricos em vitamina K', 'Vitamin K-rich foods', 'moderate',
   'Em doentes anticoagulados com varfarina, a ingestão variável de alimentos ricos em vitamina K (vegetais de folha verde) altera o INR; a suplementação com fitomenadiona é usada como antídoto.',
   'In patients anticoagulated with warfarin, variable intake of vitamin K-rich foods (green leafy vegetables) alters the INR; phytonadione supplementation is used as an antidote.',
   'Manter uma ingestão consistente de vitamina K alimentar; vigiar o INR se em varfarina.',
   'Keep vitamin K intake consistent; monitor the INR if on warfarin.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fitomenadiona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c7ef968-2c76-4220-a9ec-3179d243c422', 'DailyMed/FDA (NIH/NLM) — approved Phytonadione label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0c7ef968-2c76-4220-a9ec-3179d243c422', 2),
  ('fondaparinux', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O fondaparinux é administrado por via subcutânea; os alimentos não afetam a sua farmacocinética.',
   'Fondaparinux is given subcutaneously; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed (Fondaparinux Sodium Injection, Zydus; setID dffbf7c9-495e-4a33-ac76-57b52f014fc2).', 'DailyMed approved label (Fondaparinux Sodium Injection, Zydus; setID dffbf7c9-495e-4a33-ac76-57b52f014fc2).', 1),
  ('fondaparinux', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Sem interação farmacocinética relevante; o álcool em excesso pode aumentar o risco de queda/hemorragia em doentes anticoagulados.',
   'No relevant pharmacokinetic interaction; excessive alcohol can increase the risk of falls/bleeding in anticoagulated patients.',
   'Moderar o consumo de álcool durante o tratamento.',
   'Moderate alcohol intake during treatment.',
   'DailyMed (Fondaparinux Sodium Injection, Zydus; setID dffbf7c9-495e-4a33-ac76-57b52f014fc2).', 'DailyMed approved label (Fondaparinux Sodium Injection, Zydus; setID dffbf7c9-495e-4a33-ac76-57b52f014fc2).', 2),
  ('formoterol', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O formoterol é administrado por via inalatória; os alimentos não afetam a sua farmacocinética.',
   'Formoterol is given by inhalation; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Formoterol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35538d89-a984-4335-acdf-85a893f51eee', 'DailyMed/FDA (NIH/NLM) — approved Formoterol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35538d89-a984-4335-acdf-85a893f51eee', 1),
  ('formoterol', 'cafe_cha', 'Café e chá', 'Coffee and tea', 'minor',
   'A cafeína e outros estimulantes podem potenciar os efeitos simpaticomiméticos do formoterol (taquicardia, tremor).',
   'Caffeine and other stimulants can potentiate the sympathomimetic effects of formoterol (tachycardia, tremor).',
   'Moderar o consumo de cafeína durante o tratamento.',
   'Moderate caffeine intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Formoterol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35538d89-a984-4335-acdf-85a893f51eee', 'DailyMed/FDA (NIH/NLM) — approved Formoterol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35538d89-a984-4335-acdf-85a893f51eee', 2),
  ('ipratropio', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O ipratrópio é administrado por via inalatória; os alimentos não afetam a sua farmacocinética.',
   'Ipratropium is given by inhalation; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed (Ipratropium Bromide Solution; setID 6b730dd7-4d93-403a-bfd2-fa0efa298b75).', 'DailyMed approved label (Ipratropium Bromide Solution; setID 6b730dd7-4d93-403a-bfd2-fa0efa298b75).', 1),
  ('ipratropio', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Sem interação farmacocinética relevante; moderação habitual durante o tratamento.',
   'No relevant pharmacokinetic interaction; usual moderation during treatment.',
   'Moderar o consumo de álcool.',
   'Moderate alcohol intake.',
   'DailyMed (Ipratropium Bromide Solution; setID 6b730dd7-4d93-403a-bfd2-fa0efa298b75).', 'DailyMed approved label (Ipratropium Bromide Solution; setID 6b730dd7-4d93-403a-bfd2-fa0efa298b75).', 2),
  ('salmeterol', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O salmeterol é administrado por via inalatória; os alimentos não afetam a sua farmacocinética.',
   'Salmeterol is given by inhalation; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Salmeterol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=12d9728e-6b5c-4aee-bfb0-745e542ed2e4', 'DailyMed/FDA (NIH/NLM) — approved Salmeterol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=12d9728e-6b5c-4aee-bfb0-745e542ed2e4', 1),
  ('salmeterol', 'cafe_cha', 'Café e chá', 'Coffee and tea', 'minor',
   'A cafeína pode potenciar os efeitos simpaticomiméticos do salmeterol (taquicardia, tremor).',
   'Caffeine can potentiate the sympathomimetic effects of salmeterol (tachycardia, tremor).',
   'Moderar o consumo de cafeína durante o tratamento.',
   'Moderate caffeine intake during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Salmeterol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=12d9728e-6b5c-4aee-bfb0-745e542ed2e4', 'DailyMed/FDA (NIH/NLM) — approved Salmeterol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=12d9728e-6b5c-4aee-bfb0-745e542ed2e4', 2),
  ('tiotropio', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O tiotrópio é administrado por via inalatória; os alimentos não afetam a sua farmacocinética.',
   'Tiotropium is given by inhalation; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed (SPIRIVA RESPIMAT, Boehringer Ingelheim; setID 7b656b14-fcaa-2741-f6f0-e0be48971c02).', 'DailyMed approved label (SPIRIVA RESPIMAT, Boehringer Ingelheim; setID 7b656b14-fcaa-2741-f6f0-e0be48971c02).', 1),
  ('tiotropio', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Sem interação farmacocinética relevante; moderação habitual durante o tratamento.',
   'No relevant pharmacokinetic interaction; usual moderation during treatment.',
   'Moderar o consumo de álcool.',
   'Moderate alcohol intake.',
   'DailyMed (SPIRIVA RESPIMAT, Boehringer Ingelheim; setID 7b656b14-fcaa-2741-f6f0-e0be48971c02).', 'DailyMed approved label (SPIRIVA RESPIMAT, Boehringer Ingelheim; setID 7b656b14-fcaa-2741-f6f0-e0be48971c02).', 2),
  ('filgrastim', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O filgrastim é administrado por via subcutânea ou intravenosa; os alimentos não afetam a sua farmacocinética.',
   'Filgrastim is given subcutaneously or intravenously; food does not affect its pharmacokinetics.',
   'Pode administrar independentemente das refeições.',
   'May be administered regardless of meals.',
   'DailyMed (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 'DailyMed approved label (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 1),
  ('filgrastim', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Sem interação farmacocinética relevante; moderação habitual durante o tratamento.',
   'No relevant pharmacokinetic interaction; usual moderation during treatment.',
   'Moderar o consumo de álcool.',
   'Moderate alcohol intake.',
   'DailyMed (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 'DailyMed approved label (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 2),
  ('levonorgestrel', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Os contracetivos orais podem ser tomados com ou sem alimentos; a toma com alimentos pode reduzir a náusea.',
   'Oral contraceptives can be taken with or without food; taking them with food may reduce nausea.',
   'Tomar à mesma hora todos os dias, com ou sem alimentos.',
   'Take at the same time every day, with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levonorgestrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 'DailyMed/FDA (NIH/NLM) — approved Levonorgestrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 1),
  ('levonorgestrel', 'toranja', 'Sumo de toranja', 'Grapefruit juice', 'moderate',
   'O sumo de toranja pode aumentar as concentrações de etinilestradiol/levonorgestrel (inibição do CYP3A4), com risco de efeitos adversos estrogénicos.',
   'Grapefruit juice can raise ethinylestradiol/levonorgestrel concentrations (CYP3A4 inhibition), with a risk of oestrogenic adverse effects.',
   'Evitar o sumo de toranja durante o uso de contracetivos hormonais.',
   'Avoid grapefruit juice while using hormonal contraceptives.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levonorgestrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 'DailyMed/FDA (NIH/NLM) — approved Levonorgestrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 2),
  ('poractant_alfa', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No relevant food interaction', 'none',
   'O poractanto alfa é administrado por via endotraqueal ao recém-nascido; os alimentos não se aplicam.',
   'Poractant alfa is given endotracheally to the newborn; food does not apply.',
   'Não aplicável (administração endotraqueal neonatal).',
   'Not applicable (neonatal endotracheal administration).',
   'DailyMed (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 'DailyMed approved label (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 1),
  ('poractant_alfa', 'alcool', 'Álcool', 'Alcohol', 'none',
   'Sem interação relevante (administração endotraqueal neonatal).',
   'No relevant interaction (neonatal endotracheal administration).',
   'Não aplicável.',
   'Not applicable.',
   'DailyMed (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 'DailyMed approved label (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 2),
  ('tiamazol', 'alimentos', 'Alimentos', 'Food', 'minor',
   'O tiamazol pode ser administrado com ou sem alimentos, de forma consistente.',
   'Methimazole can be administered with or without food, consistently.',
   'Tomar à mesma hora todos os dias, com ou sem alimentos.',
   'Take at the same time every day, with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tiamazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 'DailyMed/FDA (NIH/NLM) — approved Methimazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 1),
  ('tiamazol', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'Sem interação farmacocinética relevante; moderação habitual durante o tratamento.',
   'No relevant pharmacokinetic interaction; usual moderation during treatment.',
   'Moderar o consumo de álcool.',
   'Moderate alcohol intake.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tiamazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 'DailyMed/FDA (NIH/NLM) — approved Methimazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 2)
) AS v(slug, entity_slug, entity_pt, entity_en, severity,
       mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- =====================================================================
-- 2. Doença (drug_disease_interactions)
-- =====================================================================
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('filgrastim', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease', 'precaution', 'moderate',
   'O filgrastim pode causar glomerulonefrite; doentes com doença renal prévia têm risco aumentado de eventos renais.',
   'Filgrastim can cause glomerulonephritis; patients with pre-existing renal disease are at increased risk of renal events.',
   'Monitorizar a função renal e a proteinúria durante o tratamento.',
   'Monitor renal function and proteinuria during treatment.',
   'DailyMed (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 'DailyMed approved label (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 1),
  ('filgrastim', 'doenca_pulmonar', 'Doença pulmonar', 'Lung disease', 'precaution', 'moderate',
   'O filgrastim associa-se a pneumonite intersticial e síndrome de dificuldade respiratória do adulto, sobretudo com quimioterapia concomitante.',
   'Filgrastim is associated with interstitial pneumonitis and adult respiratory distress syndrome, especially with concomitant chemotherapy.',
   'Vigiar sintomas respiratórios e suspender perante sinais de pneumonite.',
   'Watch for respiratory symptoms and stop at signs of pneumonitis.',
   'DailyMed (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 'DailyMed approved label (NEUPOGEN, Amgen; setID 97cc73cc-b5b7-458a-a933-77b00523e193).', 2),
  ('levonorgestrel', 'historico_tromboembolismo_venoso', 'Histórico de tromboembolismo venoso', 'History of venous thromboembolism', 'contraindication', 'critical',
   'Os contracetivos hormonais combinados estão contraindicados em doentes com história de trombose venosa ou arterial (risco aumentado de eventos tromboembólicos).',
   'Combined hormonal contraceptives are contraindicated in patients with a history of venous or arterial thrombosis (increased risk of thromboembolic events).',
   'Não utilizar contracetivos combinados; considerar métodos sem estrogénio.',
   'Do not use combined contraceptives; consider oestrogen-free methods.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levonorgestrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 'DailyMed/FDA (NIH/NLM) — approved Levonorgestrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 1),
  ('levonorgestrel', 'hipertensao_nao_controlada', 'Hipertensão não controlada', 'Uncontrolled hypertension', 'contraindication', 'critical',
   'A hipertensão não controlada é contraindicação relativa/absoluta aos contracetivos combinados (risco de AVC e eventos cardiovasculares).',
   'Uncontrolled hypertension is a relative/absolute contraindication to combined contraceptives (risk of stroke and cardiovascular events).',
   'Controlar a pressão arterial antes de iniciar; considerar alternativa se PA persistentemente elevada.',
   'Control blood pressure before starting; consider an alternative if BP remains elevated.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Levonorgestrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 'DailyMed/FDA (NIH/NLM) — approved Levonorgestrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 2),
  ('poractant_alfa', 'hemorragia_pulmonar', 'Hemorragia pulmonar (recém-nascido)', 'Pulmonary haemorrhage (newborn)', 'precaution', 'moderate',
   'O poractanto alfa pode associar-se a hemorragia pulmonar no recém-nascido prematuro, sobretudo nos primeiros dias.',
   'Poractant alfa can be associated with pulmonary haemorrhage in the premature newborn, especially in the first days.',
   'Vigiar sinais de hemorragia pulmonar (secreções sanguinolentas, deterioração respiratória) após a administração.',
   'Watch for signs of pulmonary haemorrhage (bloody secretions, respiratory deterioration) after administration.',
   'DailyMed (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 'DailyMed approved label (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 1),
  ('poractant_alfa', 'doenca_pulmonar_intersticial', 'Doença pulmonar (prematuridade grave)', 'Lung disease (severe prematurity)', 'precaution', 'moderate',
   'O poractanto alfa é usado precisamente na síndrome de dificuldade respiratória do recém-nascido; a sua administração requer monitorização ventilatória apertada.',
   'Poractant alfa is used precisely in neonatal respiratory distress syndrome; its administration requires close ventilatory monitoring.',
   'Monitorizar a oxigenação e a ventilação após a administração.',
   'Monitor oxygenation and ventilation after administration.',
   'DailyMed (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 'DailyMed approved label (CUROSURF, Chiesi USA; setID 99bef307-00bd-4379-9f45-ede1380e74d4).', 2),
  ('tiamazol', 'agranulocitose_historico', 'Agranulocitose prévia', 'Previous agranulocytosis', 'precaution', 'moderate',
   'O tiamazol pode causar agranulocitose, sobretudo nas primeiras semanas; doentes com história de discrasias têm risco aumentado.',
   'Methimazole can cause agranulocytosis, especially in the first weeks; patients with a history of blood dyscrasias are at increased risk.',
   'Monitorizar hemograma perante febre ou faringite e suspender se agranulocitose.',
   'Monitor the blood count in the presence of fever or pharyngitis and stop if agranulocytosis.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tiamazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 'DailyMed/FDA (NIH/NLM) — approved Methimazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 1),
  ('tiamazol', 'doenca_hepatica', 'Doença hepática', 'Hepatic disease', 'precaution', 'moderate',
   'O tiamazol pode causar colestase e lesão hepática; usar com precaução em doença hepática prévia.',
   'Methimazole can cause cholestasis and liver injury; use with caution in pre-existing liver disease.',
   'Monitorizar provas hepáticas durante o tratamento.',
   'Monitor liver function tests during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tiamazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 'DailyMed/FDA (NIH/NLM) — approved Methimazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b53f84ac-4263-478c-883d-aca7ab44fef5', 2),
  ('dextrometorfano', 'asma_grave', 'Asma grave', 'Severe asthma', 'precaution', 'moderate',
   'O dextrometorfano é um antitússico central; em doença respiratória grave com hipersecreção, a supressão da tosse pode agravar a retenção de secreções.',
   'Dextromethorphan is a central antitussive; in severe respiratory disease with hypersecretion, cough suppression can worsen secretion retention.',
   'Usar com precaução em doença respiratória grave e avaliar a necessidade real do antitússico.',
   'Use with caution in severe respiratory disease and assess the real need for the antitussive.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dextrometorfano (Drug Facts): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14', 'DailyMed/FDA (NIH/NLM) — approved Dextromethorphan label (Drug Facts): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14', 1),
  ('dextrometorfano', 'epilepsia', 'Epilepsia', 'Epilepsy', 'precaution', 'moderate',
   'O dextrometorfano pode reduzir o limiar convulsivo em doses elevadas ou em doentes suscetíveis.',
   'Dextromethorphan can lower the seizure threshold at high doses or in susceptible patients.',
   'Usar com precaução em doentes com epilepsia e evitar doses elevadas.',
   'Use with caution in patients with epilepsy and avoid high doses.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dextrometorfano (Drug Facts): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14', 'DailyMed/FDA (NIH/NLM) — approved Dextromethorphan label (Drug Facts): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14', 2),
  ('nistatina', 'alergia_antifungicos', 'Alergia a antifúngicos', 'Antifungal allergy', 'precaution', 'moderate',
   'A nistatina é geralmente bem tolerada; reações de hipersensibilidade são raras, mas possíveis em doentes sensibilizados.',
   'Nystatin is generally well tolerated; hypersensitivity reactions are rare but possible in sensitised patients.',
   'Suspender perante reação de hipersensibilidade.',
   'Stop at a hypersensitivity reaction.',
   'DailyMed (Nystatin Tablet; setID 197e3046-3e58-4246-b260-f3995dce41a1).', 'DailyMed approved label (Nystatin Tablet; setID 197e3046-3e58-4246-b260-f3995dce41a1).', 1),
  ('nistatina', 'doenca_gastrointestinal', 'Doença gastrointestinal', 'Gastrointestinal disease', 'precaution', 'moderate',
   'A nistatina oral atua localmente na mucosa; doença gastrointestinal grave pode reduzir a eficácia do contacto local.',
   'Oral nystatin acts locally on the mucosa; severe gastrointestinal disease can reduce the efficacy of local contact.',
   'Considerar formulações adaptadas e garantir o contacto prolongado com a mucosa.',
   'Consider adapted formulations and ensure prolonged contact with the mucosa.',
   'DailyMed (Nystatin Tablet; setID 197e3046-3e58-4246-b260-f3995dce41a1).', 'DailyMed approved label (Nystatin Tablet; setID 197e3046-3e58-4246-b260-f3995dce41a1).', 2)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en,
       source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;
