-- =====================================================================
-- 130 — Explicações fármaco-fármaco dos pares moderados restantes (lote 2)
-- ---------------------------------------------------------------------
-- Preenche summary_pro_* (resumo profissional) e explanation_* (explicação
-- longa) de 20 pares moderados sem explicação: β2-agonistas/teofilina/sotalol
-- (8), antiepiléticos (4), vancomicina/aminoglicosídeos (5) e
-- eritromicina + anti-histamínicos (3).
-- Padrão da 089/100/129: UPDATE com LEAST/GREATEST canónico + updated_at.
-- Conteúdo autoral, ancorado e verificado nos rótulos aprovados citados no
-- campo source_* de cada par (DailyMed/FDA).
-- Mecanismos centrais:
--   antagonismo β2 (sotalol não seletivo) + hipocaliemia (β2-agonistas)
--   potenciando o QT do sotalol; estimulação aditiva β/α (teofilina,
--   pseudoefedrina, adrenalina, salbutamol) com hipocaliemia e arritmias;
--   antiepiléticos: indução/competição enzimática e deslocamento proteico
--   (fenitoína/fenobarbital/valproato, inibição da glucuronidação da
--   lamotrigina); nefro/ototoxicidade aditiva (vancomicina, aminoglicosídeos,
--   AINE, cefalosporina); eritromicina (QT + CYP3A4/transportadores) com
--   fexofenadina, desloratadina e loratadina.
-- Idempotente: reaplicar é seguro.
-- =====================================================================

-- 1/20 — SALBUTAMOL + SOTALOL (antagonismo β2 + hipocaliemia → QT)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Salbutamol + sotalol: o sotalol (β-bloqueador não seletivo) opõe-se ao efeito broncodilatador do salbutamol e a hipocaliemia induzida pelo β2-agonista pode exagerar o prolongamento do QT do sotalol. Evitar ou monitorizar ECG e potássio.',
  summary_pro_en = 'Salbutamol + sotalol: sotalol (non-selective beta-blocker) opposes the bronchodilator effect of salbutamol, and beta2-agonist-induced hypokalaemia may exaggerate sotalol QT prolongation. Avoid or monitor ECG and potassium.',
  explanation_pt = 'O sotalol é um β-bloqueador não seletivo que também prolonga o intervalo QT (classe III); bloqueia os recetores β2 brônquicos, opondo-se diretamente ao efeito broncodilatador do salbutamol, e o rótulo do sotalol adverte que "a hipocaliemia ou hipomagnesemia não corrigidas podem exagerar o grau de prolongamento do QT e aumentar o potencial de Torsade de Pointes", recomendando corrigi-las antes do início. O salbutamol, como os outros β2-agonistas, "pode produzir hipocaliemia significativa em alguns doentes, possivelmente por desvio intracelular, com potencial para efeitos cardiovasculares adversos" (rótulo do salbutamol). A associação junta, assim, o antagonismo broncodilatador ao risco arritmogénico (hipocaliemia + QT). Evitar sempre que possível em doentes com asma e doença cardiovascular; se inevitável, usar a menor dose de salbutamol, corrigir potássio/magnésio e monitorizar ECG e função respiratória.',
  explanation_en = 'Sotalol is a non-selective beta-blocker that also prolongs the QT interval (class III); it blocks bronchial beta2 receptors, directly opposing the bronchodilator effect of salbutamol, and the sotalol label warns that "uncorrected hypokalaemia or hypomagnesaemia can exaggerate the degree of QT prolongation, and increase the potential for Torsade de Pointes", recommending correction before initiation. Salbutamol, like other beta2-agonists, "may produce significant hypokalaemia in some patients, possibly through intracellular shunting, with the potential to produce adverse cardiovascular effects" (salbutamol label). The combination therefore adds bronchial antagonism to the arrhythmogenic risk (hypokalaemia + QT). Avoid whenever possible in patients with asthma and cardiovascular disease; if unavoidable, use the lowest salbutamol dose, correct potassium/magnesium and monitor ECG and respiratory function.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'salbutamol'), (SELECT id FROM public.drugs WHERE slug = 'sotalol'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'salbutamol'), (SELECT id FROM public.drugs WHERE slug = 'sotalol'));

-- 2/20 — FORMOTEROL + SOTALOL (antagonismo β2 + hipocaliemia → QT)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Formoterol + sotalol: o sotalol bloqueia os recetores β2 (antagoniza o LABA) e a hipocaliemia do formoterol pode potenciar o QT do sotalol. Evitar ou monitorizar ECG e potássio.',
  summary_pro_en = 'Formoterol + sotalol: sotalol blocks beta2 receptors (antagonises the LABA) and formoterol-induced hypokalaemia may potentiate sotalol QT. Avoid or monitor ECG and potassium.',
  explanation_pt = 'O formoterol é um β2-agonista de longa duração (LABA) e o sotalol um β-bloqueador não seletivo com atividade antiarrítmica classe III (prolonga o QT). O sotalol bloqueia os recetores β2, opondo-se ao efeito broncodilatador do formoterol (risco de exacerbação da asma/DPOC), e os β2-agonistas "podem produzir hipocaliemia significativa em alguns doentes, possivelmente por desvio intracelular de potássio, com potencial para efeitos cardiovasculares adversos" (rótulo do formoterol) — e a hipocaliemia "pode exagerar o grau de prolongamento do QT e aumentar o potencial de Torsade de Pointes" (rótulo do sotalol). A associação é particularmente arriscada em doentes com doença cardíaca subjacente ou QT longo. Sempre que possível, evitar β-bloqueadores não seletivos em doentes a usar LABA; se inevitável, monitorizar função respiratória, potássio/magnésio e ECG.',
  explanation_en = 'Formoterol is a long-acting beta2-agonist (LABA) and sotalol a non-selective beta-blocker with class III antiarrhythmic activity (QT prolongation). Sotalol blocks beta2 receptors, opposing the bronchodilator effect of formoterol (risk of asthma/COPD exacerbation), and beta2-agonists "may produce significant hypokalaemia in some patients, possibly through intracellular potassium shunting, with the potential to produce adverse cardiovascular effects" (formoterol label) — and hypokalaemia "can exaggerate the degree of QT prolongation, and increase the potential for Torsade de Pointes" (sotalol label). The combination is particularly risky in patients with underlying heart disease or long QT. Whenever possible, avoid non-selective beta-blockers in patients using a LABA; if unavoidable, monitor respiratory function, potassium/magnesium and ECG.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'formoterol'), (SELECT id FROM public.drugs WHERE slug = 'sotalol'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'formoterol'), (SELECT id FROM public.drugs WHERE slug = 'sotalol'));

-- 3/20 — SALMETEROL + SOTALOL (antagonismo β2 + hipocaliemia → QT)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Salmeterol + sotalol: antagonismo β2 (o sotalol opõe-se ao LABA) + hipocaliemia do salmeterol a potenciar o QT do sotalol. Evitar ou monitorizar ECG e eletrólitos.',
  summary_pro_en = 'Salmeterol + sotalol: beta2 antagonism (sotalol opposes the LABA) + salmeterol hypokalaemia potentiating sotalol QT. Avoid or monitor ECG and electrolytes.',
  explanation_pt = 'O salmeterol é um LABA (β2-agonista de longa duração) e o sotalol um β-bloqueador não seletivo com prolongamento do QT (classe III). O sotalol bloqueia os recetores β2 brônquicos, opondo-se à broncodilatação do salmeterol, e os β-agonistas "podem produzir hipocaliemia significativa em alguns doentes, possivelmente por desvio intracelular, com potencial para efeitos cardiovasculares adversos" (rótulo do salmeterol). A hipocaliemia, por sua vez, "pode exagerar o grau de prolongamento do QT e aumentar o potencial de Torsade de Pointes" (rótulo do sotalol). Em doentes com asma/DPOC e doença cardiovascular, a associação soma broncoconstrição, hipocaliemia e risco arritmogénico. Evitar β-bloqueadores não seletivos em doentes a usar LABA; se inevitável, monitorizar sintomas respiratórios, potássio/magnésio e ECG.',
  explanation_en = 'Salmeterol is a LABA (long-acting beta2-agonist) and sotalol a non-selective beta-blocker with QT prolongation (class III). Sotalol blocks bronchial beta2 receptors, opposing the bronchodilation of salmeterol, and beta-agonists "may produce significant hypokalaemia in some patients, possibly through intracellular shunting, with the potential to produce adverse cardiovascular effects" (salmeterol label). Hypokalaemia, in turn, "can exaggerate the degree of QT prolongation, and increase the potential for Torsade de Pointes" (sotalol label). In patients with asthma/COPD and cardiovascular disease, the combination adds bronchoconstriction, hypokalaemia and arrhythmogenic risk. Avoid non-selective beta-blockers in patients using a LABA; if unavoidable, monitor respiratory symptoms, potassium/magnesium and ECG.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'salmeterol'), (SELECT id FROM public.drugs WHERE slug = 'sotalol'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'salmeterol'), (SELECT id FROM public.drugs WHERE slug = 'sotalol'));

-- 4/20 — SALBUTAMOL + TEOFILINA (estimulação β2 aditiva — hipocaliemia e arritmias)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Salbutamol + teofilina: estimulação β-adrenérgica aditiva — taquicardia, tremores, hipocaliemia e risco de arritmias. Monitorizar potássio e sintomas cardiovasculares.',
  summary_pro_en = 'Salbutamol + theophylline: additive beta-adrenergic stimulation — tachycardia, tremor, hypokalaemia and arrhythmia risk. Monitor potassium and cardiovascular symptoms.',
  explanation_pt = 'O salbutamol (β2-agonista) e a teofilina aumentam ambos o AMPc — o primeiro por ativação direta do recetor β2, a segunda por inibição da fosfodiesterase — e o efeito farmacodinâmico é aditivo. A teofilina "aumenta a libertação de catecolaminas endógenas" e o rótulo associa esse efeito ao "risco aumentado de arritmias ventriculares"; o salbutamol "pode produzir hipocaliemia significativa... com potencial para efeitos cardiovasculares adversos". A associação é comum na prática (asma/DPOC grave), mas doses elevadas de ambos somam taquicardia, tremores, náuseas e perda de potássio, com risco de arritmia sobretudo em doentes idosos ou com doença cardíaca. Usar as menores doses eficazes, monitorizar potássio sérico e sintomas (palpitações, tremores, ansiedade) e reduzir a teofilina se surgirem sinais de toxicidade.',
  explanation_en = 'Salbutamol (beta2-agonist) and theophylline both raise cAMP — the former by direct beta2 receptor activation, the latter by phosphodiesterase inhibition — and the pharmacodynamic effect is additive. Theophylline "increases release of endogenous catecholamines" and the label links this to an "increased risk of ventricular arrhythmias"; salbutamol "may produce significant hypokalaemia... with the potential to produce adverse cardiovascular effects". The combination is common in practice (severe asthma/COPD), but high doses of both add up tachycardia, tremor, nausea and potassium loss, with arrhythmia risk mainly in elderly or cardiac patients. Use the lowest effective doses, monitor serum potassium and symptoms (palpitations, tremor, anxiety) and reduce theophylline if toxicity signs appear.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'salbutamol'), (SELECT id FROM public.drugs WHERE slug = 'teofilina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'salbutamol'), (SELECT id FROM public.drugs WHERE slug = 'teofilina'));

-- 5/20 — PSEUDOEFEDRINA + TEOFILINA (estimulação SNC/CV aditiva)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Pseudoefedrina + teofilina: estimulação aditiva do SNC e cardiovascular — náuseas, nervosismo, insónia, taquicardia e tremores. Usar com precaução.',
  summary_pro_en = 'Pseudoephedrine + theophylline: additive CNS and cardiovascular stimulation — nausea, nervousness, insomnia, tachycardia and tremor. Use with caution.',
  explanation_pt = 'A teofilina e a pseudoefedrina (simpatomimético, isómero da efedrina) são ambas estimulantes do SNC e cardiovasculares. O rótulo da teofilina documenta a associação com a efedrina como de "efeitos sinérgicos no SNC, com aumento da frequência de náuseas, nervosismo e insónia" — a mesma classe da pseudoefedrina. Em conjunto aumentam o risco de taquicardia, palpitações, tremores, ansiedade e insónia, e em doentes suscetíveis podem precipitar arritmias ou convulsões (a teofilina baixa o limiar convulsivo). A associação é frequente em fórmulas de constipação/gripe vendidas sem receita — perguntar sempre ao doente sobre descongestionantes. Usar com precaução, preferir descongestionantes tópicos ou teofilina em dose reduzida, e vigiar sintomas adrenérgicos, sobretudo em idosos e cardíacos.',
  explanation_en = 'Theophylline and pseudoephedrine (a sympathomimetic, isomer of ephedrine) are both CNS and cardiovascular stimulants. The theophylline label documents the combination with ephedrine as having "synergistic CNS effects, with increased frequency of nausea, nervousness, and insomnia" — the same class as pseudoephedrine. Together they increase the risk of tachycardia, palpitations, tremor, anxiety and insomnia, and in susceptible patients may precipitate arrhythmias or seizures (theophylline lowers the seizure threshold). The combination is frequent in over-the-counter cold/flu products — always ask the patient about decongestants. Use with caution, prefer topical decongestants or a reduced theophylline dose, and watch for adrenergic symptoms, especially in the elderly and cardiac patients.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'pseudoefedrina'), (SELECT id FROM public.drugs WHERE slug = 'teofilina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'pseudoefedrina'), (SELECT id FROM public.drugs WHERE slug = 'teofilina'));

-- 6/20 — ADRENALINA + TEOFILINA (hipocaliemia e arritmias aditivas)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Adrenalina + teofilina: a teofilina potencia a hipocaliemia da adrenalina e ambas aumentam o risco de arritmias. Monitorizar potássio e ritmo cardíaco.',
  summary_pro_en = 'Epinephrine + theophylline: theophylline potentiates epinephrine hypokalaemia and both increase arrhythmia risk. Monitor potassium and cardiac rhythm.',
  explanation_pt = 'O rótulo da adrenalina documenta explicitamente os "fármacos que potenciam os efeitos hipocaliémicos da epinefrina — diuréticos depletores de potássio, corticosteroides e teofilina" e recomenda "observar o desenvolvimento de arritmias cardíacas" com essas associações. Em sentido inverso, a teofilina "aumenta a libertação de catecolaminas endógenas", com "risco aumentado de arritmias ventriculares" (rótulo da teofilina), e baixa o limiar convulsivo. A associação é sobretudo relevante em contexto hospitalar (adrenalina em perfusão + teofilina/aminofilina) e em doentes com doença cardíaca isquémica ou hipocaliemia prévia. Monitorizar potássio sérico, ECG e sinais de toxicidade (tremores, palpitações, arritmias); corrigir a hipocaliemia e reduzir doses sempre que possível.',
  explanation_en = 'The epinephrine label explicitly documents the "drugs potentiating the hypokalaemic effects of epinephrine — potassium-depleting diuretics, corticosteroids and theophylline" and recommends "observing for the development of cardiac arrhythmias" with these combinations. Conversely, theophylline "increases release of endogenous catecholamines", with an "increased risk of ventricular arrhythmias" (theophylline label), and lowers the seizure threshold. The combination is mainly relevant in hospital settings (epinephrine infusion + theophylline/aminophylline) and in patients with ischaemic heart disease or pre-existing hypokalaemia. Monitor serum potassium, ECG and signs of toxicity (tremor, palpitations, arrhythmias); correct hypokalaemia and reduce doses whenever possible.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'adrenalina'), (SELECT id FROM public.drugs WHERE slug = 'teofilina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'adrenalina'), (SELECT id FROM public.drugs WHERE slug = 'teofilina'));

-- 7/20 — PSEUDOEFEDRINA + SALBUTAMOL (sobreposição α/β-adrenérgica)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Pseudoefedrina + salbutamol: sobreposição adrenérgica α/β — aumento da tensão arterial, taquicardia, tremores e hipocaliemia. Vigiar sintomas cardiovasculares.',
  summary_pro_en = 'Pseudoephedrine + salbutamol: alpha/beta-adrenergic overlap — raised blood pressure, tachycardia, tremor and hypokalaemia. Watch for cardiovascular symptoms.',
  explanation_pt = 'A pseudoefedrina é um simpatomimético com ação α e β (vasoconstrição e estimulação cardíaca) e o salbutamol um β2-agonista; a sobreposição adrenérgica soma os efeitos cardiovasculares — elevação da tensão arterial (α), taquicardia e tremores (β) — e o salbutamol pode ainda "produzir hipocaliemia significativa... com potencial para efeitos cardiovasculares adversos" (rótulo do salbutamol). A associação é frequente em fórmulas de constipação em doentes asmáticos e é particularmente relevante em hipertensos, cardíacos e hipertiroidismo. Preferir descongestionantes tópicos, usar as menores doses e monitorizar tensão arterial, frequência cardíaca e potássio em doentes de risco.',
  explanation_en = 'Pseudoephedrine is a sympathomimetic with alpha and beta activity (vasoconstriction and cardiac stimulation) and salbutamol a beta2-agonist; the adrenergic overlap adds up the cardiovascular effects — raised blood pressure (alpha), tachycardia and tremor (beta) — and salbutamol may also "produce significant hypokalaemia... with the potential to produce adverse cardiovascular effects" (salbutamol label). The combination is frequent in cold formulations in asthmatic patients and is particularly relevant in hypertensives, cardiac patients and hyperthyroidism. Prefer topical decongestants, use the lowest doses and monitor blood pressure, heart rate and potassium in at-risk patients.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'pseudoefedrina'), (SELECT id FROM public.drugs WHERE slug = 'salbutamol'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'pseudoefedrina'), (SELECT id FROM public.drugs WHERE slug = 'salbutamol'));

-- 8/20 — ADRENALINA + SALBUTAMOL (sobreposição β-adrenérgica)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Adrenalina + salbutamol: sobreposição β-adrenérgica — taquicardia, tremores e perda de potássio aditivos. Monitorizar ritmo cardíaco e potássio.',
  summary_pro_en = 'Epinephrine + salbutamol: beta-adrenergic overlap — additive tachycardia, tremor and potassium loss. Monitor cardiac rhythm and potassium.',
  explanation_pt = 'A adrenalina ativa recetores α e β (β1 e β2) e o salbutamol é um β2-agonista seletivo; em conjunto, a estimulação β aditiva aumenta a taquicardia, os tremores e o desvio intracelular de potássio — o rótulo da adrenalina lista a "hipocaliemia" entre as reações adversas e os fármacos que "potenciam os efeitos hipocaliémicos da epinefrina", recomendando observar arritmias; o salbutamol "pode produzir hipocaliemia significativa em alguns doentes... com potencial para efeitos cardiovasculares adversos". A associação ocorre sobretudo em contexto de emergência (anafilaxia/asma aguda em doente a usar β2-agonistas em casa) e em cuidados intensivos. Monitorizar o ritmo cardíaco e o potássio, sobretudo em doses repetidas ou em doentes com doença coronária.',
  explanation_en = 'Epinephrine activates alpha and beta receptors (beta1 and beta2) and salbutamol is a selective beta2-agonist; together, the additive beta stimulation increases tachycardia, tremor and intracellular potassium shift — the epinephrine label lists "hypokalaemia" among adverse reactions and the drugs that "potentiate the hypokalaemic effects of epinephrine", recommending watching for arrhythmias; salbutamol "may produce significant hypokalaemia in some patients... with the potential to produce adverse cardiovascular effects". The combination occurs mainly in emergency settings (anaphylaxis/acute asthma in a patient using beta2-agonists at home) and intensive care. Monitor cardiac rhythm and potassium, especially with repeated doses or in patients with coronary disease.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'adrenalina'), (SELECT id FROM public.drugs WHERE slug = 'salbutamol'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'adrenalina'), (SELECT id FROM public.drugs WHERE slug = 'salbutamol'));

-- 9/20 — FENITOÍNA + FENOBARBITAL (indução/competição enzimática bidirecional)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Fenitoína + fenobarbital: interação bidirecional imprevisível (indução enzimática e competição por vias partilhadas). Monitorizar níveis séricos de ambos.',
  summary_pro_en = 'Phenytoin + phenobarbital: unpredictable bidirectional interaction (enzyme induction and competition for shared pathways). Monitor serum levels of both.',
  explanation_pt = 'O fenobarbital é um indutor potente das enzimas hepáticas (CYP2C9/2C19 — as mesmas que metabolizam a fenitoína) e pode reduzir os níveis de fenitoína, mas a competição pelas mesmas vias e a cinética saturável da fenitoína tornam o efeito líquido variável: o rótulo da fenitoína inclui o fenobarbital entre os "antiepiléticos que podem aumentar ou diminuir os níveis séricos de fenitoína" e refere que "o efeito da fenitoína sobre os níveis séricos de fenobarbital... é imprevisível". Em sentido inverso, a fenitoína pode elevar ou reduzir os níveis de fenobarbital. São dois fármacos com janela terapêutica estreita e efeitos depressores do SNC aditivos. Monitorizar níveis séricos de ambos durante introdução/retirada, ajustar doses com base em níveis e sintomas clínicos, e vigiar sedação, nistagmo e ataxia.',
  explanation_en = 'Phenobarbital is a potent inducer of hepatic enzymes (CYP2C9/2C19 — the same ones that metabolise phenytoin) and may reduce phenytoin levels, but competition for the same pathways and the saturable kinetics of phenytoin make the net effect variable: the phenytoin label includes phenobarbital among the "antiepileptics that may either increase or decrease phenytoin serum levels" and states that "the effect of phenytoin on phenobarbital serum levels... is unpredictable". Conversely, phenytoin may raise or lower phenobarbital levels. Both drugs have narrow therapeutic windows and additive CNS-depressant effects. Monitor serum levels of both during initiation/withdrawal, adjust doses based on levels and clinical symptoms, and watch for sedation, nystagmus and ataxia.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'), (SELECT id FROM public.drugs WHERE slug = 'fenobarbital'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'), (SELECT id FROM public.drugs WHERE slug = 'fenobarbital'));

-- 10/20 — FENITOÍNA + VALPROATO (deslocamento proteico + inibição metabólica)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Fenitoína + valproato: o valproato desloca a fenitoína das proteínas e inibe o seu metabolismo (fração livre ↑); a fenitoína pode reduzir os níveis de valproato. Monitorizar níveis e sinais de toxicidade.',
  summary_pro_en = 'Phenytoin + valproate: valproate displaces phenytoin from protein binding and inhibits its metabolism (free fraction up); phenytoin may lower valproate levels. Monitor levels and toxicity signs.',
  explanation_pt = 'O valproato desloca a fenitoína da ligação às proteínas plasmáticas e inibe o seu metabolismo, podendo elevar a fração livre de fenitoína mesmo com níveis totais aparentemente normais — o rótulo do valproato refere que "as concentrações de fenobarbital e/ou fenitoína podem ser afetadas" e recomenda "determinações periódicas das concentrações plasmáticas dos antiepiléticos concomitantes durante o início da terapêutica"; a fenitoína é, por sua vez, indutora enzimática e "pode reduzir os níveis de valproato" (o rótulo da fenitoína classifica o efeito sobre o valproato como imprevisível). A fração livre elevada de fenitoína aumenta o risco de toxicidade (nistagmo, ataxia, confusão) com níveis totais no intervalo terapêutico. Monitorizar fenitoína livre (ou sintomas clínicos), sinais de toxicidade e ajustar doses; não interpretar níveis totais isoladamente em doentes com hipoalbuminemia ou insuficiência renal.',
  explanation_en = 'Valproate displaces phenytoin from plasma protein binding and inhibits its metabolism, potentially raising the free fraction of phenytoin even with apparently normal total levels — the valproate label states that "phenobarbital and/or phenytoin concentrations may be affected" and recommends "periodic plasma concentration determinations of concomitant antiepileptics during the early course of therapy"; phenytoin, in turn, is an enzyme inducer and "may lower valproate levels" (the phenytoin label classifies its effect on valproate as unpredictable). A raised phenytoin free fraction increases the risk of toxicity (nystagmus, ataxia, confusion) with total levels in the therapeutic range. Monitor free phenytoin (or clinical symptoms), toxicity signs and adjust doses; do not interpret total levels in isolation in patients with hypoalbuminaemia or renal impairment.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'), (SELECT id FROM public.drugs WHERE slug = 'valproato'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenitoina'), (SELECT id FROM public.drugs WHERE slug = 'valproato'));

-- 11/20 — LAMOTRIGINA + VALPROATO (inibição da glucuronidação — rash)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Lamotrigina + valproato: o valproato inibe a glucuronidação da lamotrigina (semivida ~2x, níveis ↑) — maior risco de rash grave. Titular lentamente e vigiar erupção cutânea.',
  summary_pro_en = 'Lamotrigine + valproate: valproate inhibits lamotrigine glucuronidation (half-life ~2x, levels up) — higher risk of serious rash. Titrate slowly and watch for skin eruption.',
  explanation_pt = 'O rótulo da lamotrigina documenta que "o valproato inibe a glucuronidação e diminui a depuração aparente da lamotrigina" — na prática duplica a semivida da lamotrigina e pode duplicar as suas concentrações, pelo que a dose inicial e a titulação da lamotrigina devem ser reduzidas (cerca de metade) quando coadministrada com valproato. O mesmo rótulo identifica o valproato como um dos fatores associados a maior risco de reações cutâneas graves (incluindo síndrome de Stevens-Johnson), sobretudo quando a dose inicial é excedida ou a titulação é rápida. Monitorizar o doente para erupção cutânea, febre, adenopatias ou envolvimento mucoso (sinais de hipersensibilidade grave) — suspender a lamotrigina ao primeiro sinal de rash, exceto se claramente não relacionado.',
  explanation_en = 'The lamotrigine label documents that "valproate inhibits glucuronidation and decreases the apparent clearance of lamotrigine" — in practice it doubles the lamotrigine half-life and may double its concentrations, so the lamotrigine starting dose and titration must be halved when given with valproate. The same label identifies valproate as one of the factors associated with a higher risk of serious skin reactions (including Stevens-Johnson syndrome), especially when the starting dose is exceeded or titration is rapid. Monitor the patient for skin eruption, fever, lymphadenopathy or mucosal involvement (signs of serious hypersensitivity) — stop lamotrigine at the first sign of rash, unless clearly unrelated.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'lamotrigina'), (SELECT id FROM public.drugs WHERE slug = 'valproato'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'lamotrigina'), (SELECT id FROM public.drugs WHERE slug = 'valproato'));

-- 12/20 — FENOBARBITAL + VALPROATO (inibição do metabolismo do fenobarbital)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Fenobarbital + valproato: o valproato inibe o metabolismo do fenobarbital e eleva os seus níveis (sedação ↑). Monitorizar níveis e efeito depressivo.',
  summary_pro_en = 'Phenobarbital + valproate: valproate inhibits phenobarbital metabolism and raises its levels (sedation up). Monitor levels and CNS depression.',
  explanation_pt = 'O rótulo do fenobarbital refere explicitamente que "o valproato e o ácido valproico aumentam os níveis séricos de fenobarbital; portanto, os níveis sanguíneos de fenobarbital devem ser monitorizados de perto e os ajustes de dose adequados feitos conforme indicado clinicamente". O rótulo do valproato confirma que "o valproato inibe o metabolismo do fenobarbital". Níveis elevados de fenobarbital potenciam a depressão do SNC (sedação, sonolência, ataxia, compromisso respiratório em doses altas), sobretudo em idosos. Quando se inicia o valproato em doentes estabilizados com fenobarbital, monitorizar níveis de fenobarbital e sinais clínicos de toxicidade, reduzindo a dose de fenobarbital se necessário (habitualmente 20–30%).',
  explanation_en = 'The phenobarbital label explicitly states that "valproate and valproic acid increase the phenobarbital serum levels; therefore, phenobarbital blood levels should be closely monitored and appropriate dosage adjustments made as clinically indicated". The valproate label confirms that "valproate inhibits the metabolism of phenobarbital". Raised phenobarbital levels potentiate CNS depression (sedation, somnolence, ataxia, respiratory compromise at high doses), mainly in the elderly. When starting valproate in patients stabilised on phenobarbital, monitor phenobarbital levels and clinical toxicity signs, reducing the phenobarbital dose if needed (usually 20–30%).',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'fenobarbital'), (SELECT id FROM public.drugs WHERE slug = 'valproato'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenobarbital'), (SELECT id FROM public.drugs WHERE slug = 'valproato'));

-- 13/20 — VANCOMICINA + GENTAMICINA (nefro/ototoxicidade aditiva)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Vancomicina + gentamicina: nefro- e ototoxicidade aditivas (lesão tubular + coclear/vestibular). Monitorizar função renal, níveis e audição.',
  summary_pro_en = 'Vancomycin + gentamicin: additive nephro- and ototoxicity (tubular + cochlear/vestibular damage). Monitor renal function, levels and hearing.',
  explanation_pt = 'A vancomicina e os aminoglicosídeos são nefro- e ototóxicos por mecanismos sobreponíveis (acumulação tubular renal e lesão coclear/vestibular). O rótulo da vancomicina refere que "a exposição sistémica à vancomicina pode resultar em lesão renal aguda (AKI)", e o da gentamicina que os aminoglicosídeos "têm um potencial inerente para causar ototoxicidade e nefrotoxicidade", com "maior risco quando administrados por períodos mais longos ou em doses mais altas do que as recomendadas". A associação é frequente em endocardite, sépsis e doentes críticos, e o risco soma-se sobretudo em idosos, insuficiência renal prévia, hipovolémia ou terapêutica prolongada. Monitorizar creatinina e débito urinário diariamente, níveis de vancomicina e gentamicina (vales/picos), e sinais de ototoxicidade (tinitus, vertigens, hipoacusia); ajustar doses ao clearance de creatinina e considerar intervalos alargados.',
  explanation_en = 'Vancomycin and aminoglycosides are nephro- and ototoxic through overlapping mechanisms (renal tubular accumulation and cochlear/vestibular damage). The vancomycin label states that "systemic vancomycin exposure may result in acute kidney injury (AKI)", and the gentamicin label that aminoglycosides "have an inherent potential for causing ototoxicity and nephrotoxicity", with "greater risk when administered for longer periods or in higher doses than recommended". The combination is frequent in endocarditis, sepsis and critically ill patients, and the risk adds up especially in the elderly, pre-existing renal impairment, hypovolaemia or prolonged therapy. Monitor creatinine and urine output daily, vancomycin and gentamicin levels (troughs/peaks), and ototoxicity signs (tinnitus, vertigo, hearing loss); adjust doses to creatinine clearance and consider extended intervals.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'vancomicina'), (SELECT id FROM public.drugs WHERE slug = 'gentamicina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'vancomicina'), (SELECT id FROM public.drugs WHERE slug = 'gentamicina'));

-- 14/20 — VANCOMICINA + AMICACINA (nefro/ototoxicidade aditiva)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Vancomicina + amicacina: toxicidade renal e coclear/vestibular aditiva. Monitorizar função renal, níveis e audição; ajustar ao clearance de creatinina.',
  summary_pro_en = 'Vancomycin + amikacin: additive renal and cochlear/vestibular toxicity. Monitor renal function, levels and hearing; adjust to creatinine clearance.',
  explanation_pt = 'A vancomicina ("a exposição sistémica pode resultar em lesão renal aguda") e a amicacina (aminoglicosídeo com "ototoxicidade e nefrotoxicidade associadas ao seu uso", sendo a ototoxicidade "geralmente irreversível" e "maior em doentes com lesão renal") têm toxicidade sobreponível que se soma na associação. O risco é particularmente alto em doentes críticos, com insuficiência renal prévia, hipovolémia, sépsis ou terapêutica prolongada, e a nefrotoxicidade "pode não se tornar aparente até aos primeiros dias após a suspensão da terapêutica" (rótulo da amicacina). Monitorizar creatinina diariamente, níveis de vancomicina e amicacina, e sintomas otológicos (tinitus, vertigem, hipoacusia); ajustar doses ao clearance de creatinina e reavaliar a necessidade de manter ambos após 5–7 dias.',
  explanation_en = 'Vancomycin ("systemic exposure may result in acute kidney injury") and amikacin (an aminoglycoside with "ototoxicity and nephrotoxicity associated with their use", ototoxicity being "usually irreversible" and "greater in patients with renal damage") have overlapping toxicity that adds up in combination. The risk is particularly high in critically ill patients, pre-existing renal impairment, hypovolaemia, sepsis or prolonged therapy, and nephrotoxicity "may not become apparent until the first few days after cessation of therapy" (amikacin label). Monitor creatinine daily, vancomycin and amikacin levels, and otological symptoms (tinnitus, vertigo, hearing loss); adjust doses to creatinine clearance and reassess the need to keep both after 5–7 days.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'vancomicina'), (SELECT id FROM public.drugs WHERE slug = 'amicacina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'vancomicina'), (SELECT id FROM public.drugs WHERE slug = 'amicacina'));

-- 15/20 — VANCOMICINA + TOBRAMICINA (nefro/ototoxicidade aditiva)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Vancomicina + tobramicina: nefro- e ototoxicidade sobreponíveis e aditivas. Monitorizar função renal, níveis e audição, sobretudo em idosos e insuficientes renais.',
  summary_pro_en = 'Vancomycin + tobramycin: overlapping and additive nephro- and ototoxicity. Monitor renal function, levels and hearing, especially in the elderly and renally impaired.',
  explanation_pt = 'A vancomicina e a tobramicina (aminoglicosídeo) têm nefro- e ototoxicidade sobreponíveis: o rótulo da vancomicina adverte que "a exposição sistémica pode resultar em lesão renal aguda" e o da tobramicina que os aminoglicosídeos "têm um potencial inerente para causar ototoxicidade e nefrotoxicidade", com a "perda auditiva induzida por aminoglicosídeos a aumentar com o grau de exposição a picos ou vales séricos elevados". A nefrotoxicidade da associação é bem documentada e o risco aumenta com insuficiência renal prévia, hipovolémia, uso prolongado ou doses altas. Monitorizar creatinina e débito urinário, níveis de vancomicina e tobramicina, e audição/equilíbrio; ajustar doses ao clearance de creatinina e limitar a duração da terapêutica combinada.',
  explanation_en = 'Vancomycin and tobramycin (an aminoglycoside) have overlapping nephro- and ototoxicity: the vancomycin label warns that "systemic exposure may result in acute kidney injury" and the tobramycin label that aminoglycosides "have an inherent potential for causing ototoxicity and nephrotoxicity", with "aminoglycoside-induced hearing loss increasing with the degree of exposure to either high peak or high trough serum concentrations". The nephrotoxicity of the combination is well documented and the risk increases with pre-existing renal impairment, hypovolaemia, prolonged use or high doses. Monitor creatinine and urine output, vancomycin and tobramycin levels, and hearing/balance; adjust doses to creatinine clearance and limit the duration of combined therapy.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'vancomicina'), (SELECT id FROM public.drugs WHERE slug = 'tobramicina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'vancomicina'), (SELECT id FROM public.drugs WHERE slug = 'tobramicina'));

-- 16/20 — DICLOFENAC + ESTREPTOMICINA (AINE + aminoglicosídeo — nefrotoxicidade)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Diclofenac + estreptomicina: o AINE reduz a perfusão renal e aumenta o risco nefrotóxico do aminoglicosídeo. Monitorizar função renal; evitar se possível.',
  summary_pro_en = 'Diclofenac + streptomycin: the NSAID reduces renal perfusion and increases the nephrotoxic risk of the aminoglycoside. Monitor renal function; avoid if possible.',
  explanation_pt = 'Os AINE (incluindo o diclofenac) inibem a síntese de prostaglandinas renais, reduzindo o fluxo sanguíneo renal e a taxa de filtração glomerular — o que aumenta a exposição e a nefrotoxicidade dos aminoglicosídeos. O rótulo da estreptomicina adverte que "o uso concomitante ou sequencial de outros fármacos neurotóxicos e/ou nefrotóxicos... deve ser evitado" e que "a nefrotoxicidade ocorre, embora raramente, sendo a estreptomicina o menos nefrotóxico dos aminoglicosídeos". Em doentes idosos, hipovolémicos, diabéticos ou com insuficiência renal prévia, a associação de um AINE a um aminoglicosídeo pode precipitar lesão renal aguda. Sempre que possível, evitar; se inevitável (ex.: tuberculose com dor inflamatória), usar a menor dose de AINE pelo menor tempo, garantir hidratação e monitorizar creatinina e débito urinário.',
  explanation_en = 'NSAIDs (including diclofenac) inhibit renal prostaglandin synthesis, reducing renal blood flow and glomerular filtration rate — which increases aminoglycoside exposure and nephrotoxicity. The streptomycin label warns that "the concurrent or sequential use of other neurotoxic and/or nephrotoxic drugs... should be avoided" and that "nephrotoxicity does occur, although rarely, streptomycin being the least nephrotoxic of the aminoglycosides". In elderly, hypovolaemic, diabetic or pre-existing renal impairment patients, combining an NSAID with an aminoglycoside can precipitate acute kidney injury. Whenever possible, avoid; if unavoidable (e.g. tuberculosis with inflammatory pain), use the lowest NSAID dose for the shortest time, ensure hydration and monitor creatinine and urine output.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'diclofenac'), (SELECT id FROM public.drugs WHERE slug = 'estreptomicina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'diclofenac'), (SELECT id FROM public.drugs WHERE slug = 'estreptomicina'));

-- 17/20 — CEFTAZIDIMA + ESTREPTOMICINA (cefalosporina + aminoglicosídeo — nefro/ototoxicidade)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Ceftazidima + estreptomicina: nefrotoxicidade documentada na associação de cefalosporinas com aminoglicosídeos. Monitorizar função renal, sobretudo em doses altas ou terapêutica prolongada.',
  summary_pro_en = 'Ceftazidime + streptomycin: nephrotoxicity documented with cephalosporins plus aminoglycosides. Monitor renal function, especially with high doses or prolonged therapy.',
  explanation_pt = 'O rótulo da ceftazidima documenta explicitamente que "foi notificada nefrotoxicidade após a administração concomitante de cefalosporinas com antibacterianos aminoglicosídeos ou diuréticos potentes como a furosemida", recomendando que "a função renal seja cuidadosamente monitorizada, especialmente se forem administradas doses mais altas de aminoglicosídeos ou se a terapêutica for prolongada, devido ao potencial de nefrotoxicidade e ototoxicidade dos aminoglicosídeos". O rótulo da estreptomicina, por seu lado, classifica a associação com fármacos nefrotóxicos/neurotóxicos (incluindo outros aminoglicosídeos e cefalosporinas nefrotóxicas) como a evitar. A associação é usada em infeções graves (ex.: brucelose, endocardite, pneumonia nosocomial) — usar com monitorização diária de creatinina, ajuste de doses ao clearance renal e vigilância auditiva/vestibular.',
  explanation_en = 'The ceftazidime label explicitly documents that "nephrotoxicity has been reported following concomitant administration of cephalosporins with aminoglycoside antibacterial drugs or potent diuretics such as furosemide", recommending that "renal function should be carefully monitored, especially if higher dosages of the aminoglycosides are to be administered or if therapy is prolonged, because of the potential nephrotoxicity and ototoxicity of aminoglycosides". The streptomycin label, in turn, classifies the combination with nephrotoxic/neurotoxic drugs (including other aminoglycosides and nephrotoxic cephalosporins) as one to avoid. The combination is used in severe infections (e.g. brucellosis, endocarditis, nosocomial pneumonia) — use with daily creatinine monitoring, dose adjustment to renal clearance and audiovestibular surveillance.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'ceftazidima'), (SELECT id FROM public.drugs WHERE slug = 'estreptomicina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'ceftazidima'), (SELECT id FROM public.drugs WHERE slug = 'estreptomicina'));

-- 18/20 — ERITROMICINA + FEXOFENADINA (transportadores intestinais — níveis ↑)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Eritromicina + fexofenadina: a eritromicina interfere com o transporte intestinal (P-gp/OATP) e eleva os níveis de fexofenadina. Vigiar efeitos adversos (cefaleia, tonturas).',
  summary_pro_en = 'Erythromycin + fexofenadine: erythromycin interferes with intestinal transport (P-gp/OATP) and raises fexofenadine levels. Watch for adverse effects (headache, dizziness).',
  explanation_pt = 'A fexofenadina é eliminada essencialmente inalterada, sem metabolismo pelo CYP450 relevante; a interação com a eritromicina ocorre ao nível dos transportadores intestinais (P-gp/OATP), que a eritromicina inibe, elevando as concentrações plasmáticas de fexofenadina. O mecanismo está documentado na informação de prescrição da fexofenadina (Allegra), que descreve aumentos da exposição com a coadministração de eritromicina (aumento da AUC em cerca de 100%) sem alterações clinicamente relevantes no QT — ao contrário da terfenadina (o seu precursor), a fexofenadina não prolonga o intervalo QT. A eritromicina, por seu lado, "tem sido associada a prolongamento do intervalo QT e casos infrequentes de arritmia" (rótulo da eritromicina). Na prática, vigiar efeitos adversos da fexofenadina (cefaleia, tonturas, sonolência ligeira) e, no caso da eritromicina, respeitar as contraindicações QT; não é necessário ajuste de rotina da dose, mas evitar doses supramáximas.',
  explanation_en = 'Fexofenadine is eliminated essentially unchanged, without relevant CYP450 metabolism; the interaction with erythromycin occurs at the level of intestinal transporters (P-gp/OATP), which erythromycin inhibits, raising fexofenadine plasma concentrations. The mechanism is documented in the fexofenadine prescribing information (Allegra), which describes increased exposure with erythromycin coadministration (AUC increase of about 100%) without clinically relevant QT changes — unlike terfenadine (its precursor), fexofenadine does not prolong the QT interval. Erythromycin, in turn, "has been associated with prolongation of the QT interval and infrequent cases of arrhythmia" (erythromycin label). In practice, watch for fexofenadine adverse effects (headache, dizziness, mild somnolence) and, for erythromycin, respect the QT contraindications; routine dose adjustment is not needed, but avoid supratherapeutic doses.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'), (SELECT id FROM public.drugs WHERE slug = 'fexofenadina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'), (SELECT id FROM public.drugs WHERE slug = 'fexofenadina'));

-- 19/20 — ERITROMICINA + DESLORATADINA (CYP3A4 — níveis ↑)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Eritromicina + desloratadina: a eritromicina (inibidor do CYP3A4) eleva os níveis de desloratadina, sem alterações clinicamente relevantes no perfil de segurança. Vigiar sonolência.',
  summary_pro_en = 'Erythromycin + desloratadine: erythromycin (CYP3A4 inhibitor) raises desloratadine levels, without clinically relevant safety changes. Watch for somnolence.',
  explanation_pt = 'O rótulo da desloratadina documenta que a coadministração com "eritromicina... resultou em concentrações plasmáticas aumentadas de desloratadina e 3-hidroxidesloratadina, mas não houve alterações clinicamente relevantes no perfil de segurança da desloratadina" — a desloratadina é metabolizada pelo CYP3A4 (e CYP2D6), que a eritromicina inibe. A associação é geralmente bem tolerada; o principal cuidado é a potencialização da sonolência/efeitos no SNC (sobretudo em idosos) e o risco QT da própria eritromicina, que "deve ser evitada em doentes com prolongamento conhecido do QT, hipocaliemia ou hipomagnesemia não corrigidas, bradicardia clinicamente significativa e com antiarrítmicos classe IA/III" (rótulo da eritromicina). Não é necessário ajuste de rotina da dose de desloratadina; vigiar sonolência e informar o doente.',
  explanation_en = 'The desloratadine label documents that coadministration with "erythromycin... resulted in increased plasma concentrations of desloratadine and 3-hydroxydesloratadine, but there were no clinically relevant changes in the safety profile of desloratadine" — desloratadine is metabolised by CYP3A4 (and CYP2D6), which erythromycin inhibits. The combination is generally well tolerated; the main concerns are potentiation of somnolence/CNS effects (especially in the elderly) and the QT risk of erythromycin itself, which "should be avoided in patients with known QT prolongation, uncorrected hypokalaemia or hypomagnesaemia, clinically significant bradycardia, and with class IA/III antiarrhythmics" (erythromycin label). Routine dose adjustment of desloratadine is not needed; watch for somnolence and inform the patient.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'), (SELECT id FROM public.drugs WHERE slug = 'desloratadina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'), (SELECT id FROM public.drugs WHERE slug = 'desloratadina'));

-- 20/20 — ERITROMICINA + LORATADINA (CYP3A4 — níveis ↑)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Eritromicina + loratadina: a eritromicina (inibidor do CYP3A4) reduz o metabolismo da loratadina, elevando os seus níveis. Vigiar sonolência e risco QT da eritromicina.',
  summary_pro_en = 'Erythromycin + loratadine: erythromycin (CYP3A4 inhibitor) reduces loratadine metabolism, raising its levels. Watch for somnolence and erythromycin QT risk.',
  explanation_pt = 'A loratadina é metabolizada no fígado pelo CYP3A4 (e CYP2D6) e a eritromicina é um inibidor conhecido do CYP3A4 — a associação eleva as concentrações de loratadina e do seu metabolito ativo, desloratadina, podendo potenciar a sonolência (sobretudo em idosos e em doses altas de loratadina). O rótulo da eritromicina refere que "a eritromicina tem sido associada a prolongamento do intervalo QT e casos infrequentes de arritmia", com contraindicação de antiarrítmicos classe IA/III e precaução em hipocaliemia/hipomagnesemia — embora a loratadina em doses terapêuticas não prolongue significativamente o QT, o risco arritmogénico da eritromicina deve ser respeitado. Na prática, vigiar sedação e sintomas cardiovasculares, usar a menor dose eficaz de loratadina e monitorizar o intervalo QT em doentes de risco (QT longo, hipocaliemia, idosos).',
  explanation_en = 'Loratadine is metabolised in the liver by CYP3A4 (and CYP2D6) and erythromycin is a known CYP3A4 inhibitor — the combination raises loratadine and its active metabolite desloratadine concentrations, potentially potentiating somnolence (especially in the elderly and with high loratadine doses). The erythromycin label states that "erythromycin has been associated with prolongation of the QT interval and infrequent cases of arrhythmia", with class IA/III antiarrhythmics contraindicated and caution in hypokalaemia/hypomagnesaemia — although loratadine at therapeutic doses does not significantly prolong the QT, the arrhythmogenic risk of erythromycin itself must be respected. In practice, watch for sedation and cardiovascular symptoms, use the lowest effective loratadine dose and monitor the QT interval in at-risk patients (long QT, hypokalaemia, elderly).',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'), (SELECT id FROM public.drugs WHERE slug = 'loratadina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'eritromicina'), (SELECT id FROM public.drugs WHERE slug = 'loratadina'));
