-- =====================================================================
-- 131 — Últimas explicações fármaco-fármaco (fecho dos 56 restantes)
-- ---------------------------------------------------------------------
-- Preenche summary_pro_* (resumo profissional) e explanation_* (explicação
-- longa) dos últimos 17 pares moderados sem explicação: bloqueio duplo do
-- RAAS (5), levotiroxina/absorção (4), azatioprina/aminosalicilatos e
-- folato (3), AINE+AINE (1), leflunomida+metotrexato (1), alopurinol+
-- penicilinas (2) e sedação aditiva (1).
-- Padrão da 089/100/129-130: UPDATE com LEAST/GREATEST canónico + updated_at.
-- Conteúdo autoral, ancorado e verificado nos 24 rótulos aprovados citados
-- (DailyMed/FDA).
-- Com esta migração, os 56 pares moderados sem explicação identificados na
-- auditoria estão todos cobertos (366 moderados — 0 restantes).
-- Idempotente: reaplicar é seguro.
-- =====================================================================

-- 1/17 — VALSARTANA + CAPTOPRIL (bloqueio duplo do RAAS — hipercaliemia, hipotensão, função renal)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Valsartana + captopril: bloqueio duplo do RAAS — maior risco de hipotensão, hipercaliemia e lesão renal. Evitar na maioria dos doentes.',
  summary_pro_en = 'Valsartan + captopril: dual RAAS blockade — higher risk of hypotension, hyperkalaemia and renal impairment. Avoid in most patients.',
  explanation_pt = 'O bloqueio duplo do sistema renina-angiotensina-aldosterona (RAAS) com um ARA II e um IECA soma os efeitos sobre a hemodinâmica renal e o balanço do potássio. O rótulo do captopril documenta a "Dual Blockade of the Renin-Angiotensin System (RAS)" como associada a "risco aumentado de hipotensão, hipercaliemia e alterações da função renal (incluindo falência renal aguda)" e recomenda monitorização apertada da TA, função renal e eletrólitos quando a associação é inevitável; o rótulo da valsartana refere "Dual inhibition of the RAS: Increased risk of renal impairment, hypotension, and hyperkalemia". Grandes ensaios clínicos (ONTARGET, ALTITUDE) demonstraram que o bloqueio duplo não reduz a mortalidade e aumenta os eventos adversos renais e a hipercaliemia. Evitar na maioria dos doentes com HTA; considerar apenas sob supervisão especializada em IC selecionada (Val-HeFT, PARADIGM-HF), com monitorização rigorosa de TA, creatinina e potássio uma semana após o início/ajuste e sempre que a terapêutica mudar.',
  explanation_en = 'Dual RAAS blockade with an ARB and an ACE inhibitor adds the effects on renal haemodynamics and potassium balance. The captopril label documents "Dual Blockade of the Renin-Angiotensin System (RAS)" as associated with "increased risks of hypotension, hyperkalaemia, and changes in renal function (including acute renal failure)" and recommends close monitoring of BP, renal function and electrolytes when the combination is unavoidable; the valsartan label states "Dual inhibition of the RAS: Increased risk of renal impairment, hypotension, and hyperkalemia". Major trials (ONTARGET, ALTITUDE) showed that dual blockade does not reduce mortality and increases renal adverse events and hyperkalaemia. Avoid in most hypertensive patients; consider only under specialist supervision in selected HF (Val-HeFT, PARADIGM-HF), with rigorous monitoring of BP, creatinine and potassium one week after initiation/adjustment and whenever therapy changes.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'valsartana'), (SELECT id FROM public.drugs WHERE slug = 'captopril'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'valsartana'), (SELECT id FROM public.drugs WHERE slug = 'captopril'));

-- 2/17 — VALSARTANA + RAMIPRIL (bloqueio duplo do RAAS)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Valsartana + ramipril: bloqueio duplo do RAAS — maior risco de hipotensão, hipercaliemia e lesão renal. Evitar; monitorizar TA, K+ e creatinina se inevitável.',
  summary_pro_en = 'Valsartan + ramipril: dual RAAS blockade — higher risk of hypotension, hyperkalaemia and renal impairment. Avoid; monitor BP, K+ and creatinine if unavoidable.',
  explanation_pt = 'A associação de um ARA II (valsartana) com um IECA (ramipril) bloqueia o RAAS em duas etapas, somando o risco de hipercaliemia, hipotensão e deterioração da função renal. O rótulo da valsartana refere que a "Dual inhibition of the RAS" aumenta o "risco de compromisso renal, hipotensão e hipercaliemia"; o do ramipril documenta "Dual Blockade of the Renin-Angiotensin System" entre as advertências e "Agents Increasing Serum Potassium" nas interações, e o risco é maior em doentes com insuficiência renal, diabetes ou depleção de volume. O ensaio ONTARGET com telmisartana+ramipril mostrou mais eventos renais adversos sem benefício de mortalidade. Evitar na maioria dos doentes; se absolutamente necessário (IC refratária), monitorizar TA, creatinina e potássio 1–2 semanas após o início ou ajuste de dose e reduzir as doses de ambos.',
  explanation_en = 'Combining an ARB (valsartan) with an ACE inhibitor (ramipril) blocks the RAAS at two steps, adding the risk of hyperkalaemia, hypotension and renal function deterioration. The valsartan label states that "Dual inhibition of the RAS" increases the "risk of renal impairment, hypotension, and hyperkalemia"; the ramipril label documents "Dual Blockade of the Renin-Angiotensin System" among the warnings and "Agents Increasing Serum Potassium" in interactions, and the risk is higher in patients with renal impairment, diabetes or volume depletion. The ONTARGET trial with telmisartan+ramipril showed more renal adverse events without mortality benefit. Avoid in most patients; if absolutely necessary (refractory HF), monitor BP, creatinine and potassium 1–2 weeks after initiation or dose adjustment and reduce the doses of both.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'valsartana'), (SELECT id FROM public.drugs WHERE slug = 'ramipril'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'valsartana'), (SELECT id FROM public.drugs WHERE slug = 'ramipril'));

-- 3/17 — VALSARTANA + ESPIRONOLACTONA (hipercaliemia por duas vias)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Valsartana + espironolactona: hipercaliemia aditiva (ARA II + diurético poupador de K). Monitorizar potássio e função renal; evitar em IRC ou K+ > 5,0.',
  summary_pro_en = 'Valsartan + spironolactone: additive hyperkalaemia (ARB + K-sparing diuretic). Monitor potassium and renal function; avoid in CKD or K+ > 5,0.',
  explanation_pt = 'Tanto a valsartana (ARA II) como a espironolactona (antagonista da aldosterona) reduzem a excreção renal de potássio por vias complementares — a valsartana diminui a aldosterona ao bloquear o recetor AT1, e a espironolactona bloqueia o recetor mineralocorticoide na sua extremidade efetora. O rótulo da espironolactona classifica os "ARA" entre os "agentes que aumentam o potássio sérico" e recomenda "verificar os níveis séricos de potássio quando a terapêutica com IECA ou ARA for alterada em doentes a receber espironolactona"; o da valsartana adverte que "diuréticos poupadores de potássio, suplementos de potássio ou substitutos do sal podem levar a aumentos do potássio sérico". A associação é usada na IC (RALES demonstrou benefício), mas requer monitorização rigorosa. Contraindicada se K+ > 5,0 mEq/L ou clearance de creatinina < 30 mL/min; suspender suplementos de potássio; monitorizar K+ e creatinina aos 3–7 dias e 1 mês, depois trimestralmente.',
  explanation_en = 'Both valsartan (ARB) and spironolactone (aldosterone antagonist) reduce renal potassium excretion through complementary pathways — valsartan decreases aldosterone by blocking the AT1 receptor, and spironolactone blocks the mineralocorticoid receptor at the effector end. The spironolactone label classifies "ARBs" among the "agents that increase serum potassium" and recommends "checking serum potassium levels when ACE inhibitor or ARB therapy is altered in patients receiving spironolactone"; the valsartan label warns that "potassium-sparing diuretics, potassium supplements or salt substitutes may lead to increases in serum potassium". The combination is used in HF (RALES demonstrated benefit) but requires rigorous monitoring. Contraindicated if K+ > 5,0 mEq/L or creatinine clearance < 30 mL/min; stop potassium supplements; monitor K+ and creatinine at 3–7 days and 1 month, then quarterly.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'valsartana'), (SELECT id FROM public.drugs WHERE slug = 'espironolactona'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'valsartana'), (SELECT id FROM public.drugs WHERE slug = 'espironolactona'));

-- 4/17 — ESPIRONOLACTONA + LOSARTANO (hipercaliemia — ARA II + poupador de K)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Espironolactona + losartano: ambos poupam potássio por vias complementares. Monitorizar K+ e creatinina; evitar em IRC ou K+ elevado.',
  summary_pro_en = 'Spironolactone + losartan: both spare potassium through complementary pathways. Monitor K+ and creatinine; avoid in CKD or high K+.',
  explanation_pt = 'O losartano (ARA II) reduz a produção de aldosterona e a espironolactona bloqueia o seu recetor — o efeito sobre o potássio é aditivo. O rótulo da espironolactona inclui os "angiotensin receptor blockers" na lista de "Agents Increasing Serum Potassium" (secção 7.1) e recomenda monitorizar o potássio quando a terapêutica com IECA/ARA é alterada; o do losartano documenta que "diuréticos poupadores de potássio, suplementos de potássio ou substitutos do sal podem levar a aumentos do potássio sérico" e adverte para o risco de hipercaliemia em doentes com insuficiência renal ou diabetes. A monitorização é essencial: potássio e creatinina antes do início, 1 semana após, 1 mês após e depois trimestralmente; não usar se K+ > 5,0 ou clearance de creatinina < 30 mL/min; suspender suplementos de potássio e reduzir a dose de espironolactona se K+ subir acima de 5,5.',
  explanation_en = 'Losartan (ARB) reduces aldosterone production and spironolactone blocks its receptor — the effect on potassium is additive. The spironolactone label includes "angiotensin receptor blockers" in the list of "Agents Increasing Serum Potassium" (section 7.1) and recommends monitoring potassium when ACEi/ARB therapy is altered; the losartan label documents that "potassium-sparing diuretics, potassium supplements or salt substitutes may lead to increases in serum potassium" and warns of hyperkalaemia risk in patients with renal impairment or diabetes. Monitoring is essential: potassium and creatinine before initiation, 1 week after, 1 month after and then quarterly; do not use if K+ > 5,0 or creatinine clearance < 30 mL/min; stop potassium supplements and reduce spironolactone dose if K+ rises above 5,5.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'espironolactona'), (SELECT id FROM public.drugs WHERE slug = 'losartano'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'espironolactona'), (SELECT id FROM public.drugs WHERE slug = 'losartano'));

-- 5/17 — ESPIRONOLACTONA + BUMETANIDA (regulação do potássio — diurético poupador + loop)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Espironolactona + bumetanida: associação usada para regular o potássio na IC (loop perde K, espironolactona poupa). O balanço depende da função renal; monitorizar K+.',
  summary_pro_en = 'Spironolactone + bumetanide: combination used to regulate potassium in HF (loop loses K, spironolactone spares). Balance depends on renal function; monitor K+.',
  explanation_pt = 'A espironolactona (diurético poupador de potássio) e a bumetanida (diurético da ansa, que excreta potássio) são frequentemente usados em conjunto na insuficiência cardíaca para equilibrar o potássio — a bumetanida remove K+ e a espironolactona retém-no. O rótulo da espironolactona refere que "a administração concomitante pode levar a hipercaliemia" e classifica os diuréticos depletores de potássio como interação a monitorizar; o da bumetanida não foi analisado individualmente, mas o efeito líquido depende da função renal e das doses relativas. Em doentes com clearance de creatinina > 50 mL/min, o balanço é geralmente favorável; na IRC (clearance < 30 mL/min), o risco de hipercaliemia aumenta. Monitorizar potássio e creatinina antes do início e 1 semana após; ajustar as doses conforme o potássio (se K+ < 3,5 aumentar espironolactona ou reduzir bumetanida; se K+ > 5,0 reduzir espironolactona ou aumentar bumetanida).',
  explanation_en = 'Spironolactone (potassium-sparing diuretic) and bumetanide (loop diuretic, which excretes potassium) are often used together in heart failure to balance potassium — bumetanide removes K+ and spironolactone retains it. The spironolactone label states that "concomitant administration may lead to hyperkalaemia" and classifies potassium-depleting diuretics as an interaction to monitor; the bumetanide label was not individually analysed, but the net effect depends on renal function and relative doses. In patients with creatinine clearance > 50 mL/min, the balance is generally favourable; in CKD (clearance < 30 mL/min), the risk of hyperkalaemia increases. Monitor potassium and creatinine before initiation and 1 week after; adjust doses according to potassium (if K+ < 3,5 increase spironolactone or reduce bumetanide; if K+ > 5,0 reduce spironolactone or increase bumetanide).',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'espironolactona'), (SELECT id FROM public.drugs WHERE slug = 'bumetanida'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'espironolactona'), (SELECT id FROM public.drugs WHERE slug = 'bumetanida'));

-- 6/17 — LEVOTIROXINA + ORLISTAT (absorção lipossolúvel reduzida)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Levotiroxina + orlistat: o orlistat reduz a absorção da levotiroxina (vitaminas lipossolúveis). Separar a toma 4+ horas; monitorizar TSH.',
  summary_pro_en = 'Levothyroxine + orlistat: orlistat reduces levothyroxine absorption (fat-soluble vitamins). Separate administration by 4+ hours; monitor TSH.',
  explanation_pt = 'O orlistat inibe a lipase pancreática e reduz a absorção de gorduras e vitaminas lipossolúveis. O seu rótulo lista a "medicação para a tiróide" entre os fármacos cuja absorção pode ser alterada e recomenda que os doentes "tomem um multivitamínico diariamente ao deitar" — o que inclui a levotiroxina, embora o mecanismo não seja apenas a lipossolubilidade (a levotiroxina é um aminoácido iodado, mas a sua absorção ocorre no intestino delgado proximal e pode ser afetada pela gordura alimentar e pelo trânsito intestinal). Associam-se casos de TSH elevada após início do orlistat em doentes estáveis com levotiroxina, com normalização após separação das tomas. Administrar a levotiroxina pelo menos 4 horas antes ou depois do orlistat (de preferência ao acordar, em jejum, como habitual); monitorizar TSH 4–8 semanas após o início ou ajuste do orlistat e reajustar a dose de levotiroxina se necessário.',
  explanation_en = 'Orlistat inhibits pancreatic lipase and reduces absorption of fats and fat-soluble vitamins. Its label lists "thyroid medicine" among drugs whose absorption may be altered and recommends that patients "take a multivitamin daily at bedtime" — which includes levothyroxine, although the mechanism is not solely fat-solubility (levothyroxine is an iodinated amino acid, but its absorption occurs in the proximal small intestine and can be affected by dietary fat and intestinal transit). Cases of raised TSH after starting orlistat in stable levothyroxine patients are reported, with normalisation after separating the doses. Administer levothyroxine at least 4 hours before or after orlistat (preferably on waking, fasting, as usual); monitor TSH 4–8 weeks after starting or adjusting orlistat and readjust the levothyroxine dose if needed.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'levotiroxina'), (SELECT id FROM public.drugs WHERE slug = 'orlistat'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'levotiroxina'), (SELECT id FROM public.drugs WHERE slug = 'orlistat'));

-- 7/17 — LEVOTIROXINA + SUCRALFATO (quelação/adsorção)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Levotiroxina + sucralfato: o sucralfato adsorve a levotiroxina e reduz a sua absorção. Separar as tomas por 4+ horas (sucralfato 2h após a levotiroxina).',
  summary_pro_en = 'Levothyroxine + sucralfate: sucralfate adsorbs levothyroxine and reduces its absorption. Separate administration by 4+ hours (sucralfate 2h after levothyroxine).',
  explanation_pt = 'O rótulo do sucralfato documenta que a administração simultânea "reduziu a extensão da absorção (biodisponibilidade) de doses únicas de... l-thyroxine" e que "a administração do medicamento concomitante 2 horas antes do sucralfato eliminou a interação". O sucralfato forma uma barreira aderente na mucosa gástrica e duodenal e pode adsorver quimicamente a levotiroxina, impedindo a sua absorção no duodeno proximal. Esta interação é relevante em doentes com hipotiroidismo que iniciam sucralfato para úlcera péptica ou DRGE (sobretudo em contexto de doença crítica ou polifarmácia). Administrar a levotiroxina em jejum (30–60 minutos antes do pequeno-almoço) e o sucralfato pelo menos 2 horas depois (idealmente 4 horas de intervalo); monitorizar TSH 6–8 semanas após o início, ajuste ou suspensão do sucralfato.',
  explanation_en = 'The sucralfate label documents that simultaneous administration "reduced the extent of absorption (bioavailability) of single doses of... l-thyroxine" and that "dosing the concomitant medication 2 hours before sucralfate eliminated the interaction". Sucralfate forms an adherent barrier on the gastric and duodenal mucosa and may chemically adsorb levothyroxine, preventing its absorption in the proximal duodenum. This interaction is relevant in hypothyroid patients starting sucralfate for peptic ulcer or GERD (especially in the context of critical illness or polypharmacy). Administer levothyroxine on an empty stomach (30–60 minutes before breakfast) and sucralfate at least 2 hours later (ideally a 4-hour interval); monitor TSH 6–8 weeks after starting, adjusting or stopping sucralfate.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'levotiroxina'), (SELECT id FROM public.drugs WHERE slug = 'sucralfato'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'levotiroxina'), (SELECT id FROM public.drugs WHERE slug = 'sucralfato'));

-- 8/17 — METOCLOPRAMIDA + LEVOTIROXINA (esvaziamento gástrico acelerado)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Metoclopramida + levotiroxina: a aceleração do esvaziamento gástrico pela metoclopramida encurta o tempo de contacto da levotiroxina com a mucosa absortiva. Monitorizar TSH.',
  summary_pro_en = 'Metoclopramide + levothyroxine: accelerated gastric emptying by metoclopramide shortens the contact time of levothyroxine with the absorptive mucosa. Monitor TSH.',
  explanation_pt = 'A metoclopramida aumenta o peristaltismo gástrico e acelera o esvaziamento, o que pode reduzir o tempo de dissolução e absorção da levotiroxina no duodeno proximal. O rótulo da metoclopramida documenta que o "aumento da motilidade GI pela metoclopramida pode afetar a absorção de outros fármacos, levando a uma diminuição" da mesma. Embora a levotiroxina não esteja explicitamente listada, o mecanismo é aplicável a fármacos absorvidos no duodeno proximal que dependem de um tempo de contacto adequado. Esta interação é leve e variável entre doentes, mas pode ser clinicamente relevante em doentes com hipotiroidismo limiar ou em que a dose de levotiroxina foi recentemente ajustada. Separar as tomas (metoclopramida após as refeições, levotiroxina em jejum) e monitorizar TSH se houver suspeita de má absorção ou agravamento do hipotiroidismo.',
  explanation_en = 'Metoclopramide increases gastric peristalsis and accelerates gastric emptying, which may reduce the dissolution and absorption time of levothyroxine in the proximal duodenum. The metoclopramide label documents that "increased GI motility by metoclopramide may impact absorption of other drugs, leading to a decrease" thereof. Although levothyroxine is not explicitly listed, the mechanism is applicable to drugs absorbed in the proximal duodenum that depend on adequate contact time. This interaction is mild and variable between patients, but may be clinically relevant in patients with borderline hypothyroidism or who have recently had their levothyroxine dose adjusted. Separate the doses (metoclopramide after meals, levothyroxine on an empty stomach) and monitor TSH if malabsorption or worsening of hypothyroidism is suspected.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'metoclopramida'), (SELECT id FROM public.drugs WHERE slug = 'levotiroxina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'metoclopramida'), (SELECT id FROM public.drugs WHERE slug = 'levotiroxina'));

-- 9/17 — AZATIOPRINA + MESALAZINA (inibição da TPMT — mielotoxicidade)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Azatioprina + mesalazina: a mesalazina inibe a TPMT e aumenta os níveis de 6-tioguanina ativa — mielotoxicidade aditiva. Monitorizar hemograma.',
  summary_pro_en = 'Azathioprine + mesalazine: mesalazine inhibits TPMT and raises active 6-thioguanine levels — additive myelotoxicity. Monitor blood counts.',
  explanation_pt = 'O rótulo da mesalazina documenta a associação com "Azatioprina ou 6-Mercaptopurina: risco aumentado de discrasias sanguíneas; monitorizar hemograma completo e contagem de plaquetas" (secção 7.2). O mecanismo é a inibição da tiopurina metiltransferase (TPMT) pelos aminosalicilatos (mesalazina e sulfassalazina), que reduz a metilação inativadora da 6-mercaptopurina (metabolito ativo da azatioprina) e desvia o metabolismo para a via da 6-tioguanina — mais mielotóxica. Esta interação é bem conhecida na prática gastroenterológica (doença inflamatória intestinal), onde azatioprina e mesalazina são frequentemente coadministradas. Reduzir a dose de azatioprina em 25–50% e monitorizar hemograma semanalmente durante o primeiro mês, depois mensalmente; vigiar leucopenia, trombocitopenia e sintomas infecciosos.',
  explanation_en = 'The mesalazine label documents the combination with "Azathioprine or 6-Mercaptopurine: increased risk of blood dyscrasias; monitor complete blood cell counts and platelet counts" (section 7.2). The mechanism is inhibition of thiopurine methyltransferase (TPMT) by aminosalicylates (mesalazine and sulfasalazine), which reduces the inactivating methylation of 6-mercaptopurine (the active metabolite of azathioprine) and shifts metabolism towards the more myelotoxic 6-thioguanine pathway. This interaction is well known in gastroenterology practice (inflammatory bowel disease), where azathioprine and mesalazine are often coadministered. Reduce the azathioprine dose by 25–50% and monitor blood counts weekly during the first month, then monthly; watch for leucopenia, thrombocytopenia and infectious symptoms.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'azatioprina'), (SELECT id FROM public.drugs WHERE slug = 'mesalazina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'azatioprina'), (SELECT id FROM public.drugs WHERE slug = 'mesalazina'));

-- 10/17 — AZATIOPRINA + SULFASSALAZINA (inibição da TPMT — mielotoxicidade)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Azatioprina + sulfassalazina: inibição da TPMT pela sulfassalazina — risco de mielotoxicidade aditiva. Monitorizar hemograma e reduzir dose de azatioprina.',
  summary_pro_en = 'Azathioprine + sulfasalazine: TPMT inhibition by sulfasalazine — risk of additive myelotoxicity. Monitor blood counts and reduce azathioprine dose.',
  explanation_pt = 'A sulfassalazina (como a mesalazina, seu metabolito ativo) inibe a TPMT, enzima que inativa a 6-mercaptopurina — o metabolito ativo da azatioprina. A inibição da TPMT desvia o metabolismo para a produção de 6-tioguanina, aumentando o risco de mielossupressão (leucopenia, trombocitopenia, anemia). Esta interação é clássica na doença inflamatória intestinal (DII), onde a azatioprina é imunomoduladora e a sulfassalazina é anti-inflamatória — ambas usadas em simultâneo na DII moderada a grave. O rótulo da sulfassalazina não menciona diretamente a azatioprina, mas o mecanismo TPMT está estabelecido na literatura e documentado no rótulo da azatioprina (metabolismo via TPMT). Monitorizar hemograma semanalmente no primeiro mês, depois mensalmente; reduzir a dose de azatioprina em 25–50% ao iniciar o aminosalicilato; vigiar sinais de infeção e anemia.',
  explanation_en = 'Sulfasalazine (like mesalazine, its active metabolite) inhibits TPMT, the enzyme that inactivates 6-mercaptopurine — the active metabolite of azathioprine. TPMT inhibition shifts metabolism towards 6-thioguanine production, increasing the risk of myelosuppression (leucopenia, thrombocytopenia, anaemia). This interaction is classic in inflammatory bowel disease (IBD), where azathioprine is an immunomodulator and sulfasalazine is anti-inflammatory — both used simultaneously in moderate to severe IBD. The sulfasalazine label does not directly mention azathioprine, but the TPMT mechanism is established in the literature and documented in the azathioprine label (metabolism via TPMT). Monitor blood counts weekly during the first month, then monthly; reduce the azathioprine dose by 25–50% when starting the aminosalicylate; watch for signs of infection and anaemia.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'azatioprina'), (SELECT id FROM public.drugs WHERE slug = 'sulfassalazina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'azatioprina'), (SELECT id FROM public.drugs WHERE slug = 'sulfassalazina'));

-- 11/17 — ÁCIDO FÓLICO + SULFASSALAZINA (absorção de folato reduzida)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Ácido fólico + sulfassalazina: a sulfassalazina reduz a absorção intestinal de folato (sulfapiridina). Suplementar e monitorizar níveis de folato.',
  summary_pro_en = 'Folic acid + sulfasalazine: sulfasalazine reduces intestinal folate absorption (sulfapyridine). Supplement and monitor folate levels.',
  explanation_pt = 'O rótulo da sulfassalazina documenta que "foi notificada redução da absorção de ácido fólico e digoxina quando estes agentes foram administrados concomitantemente com sulfassalazina" e que "a sulfassalazina inibe a absorção e o metabolismo do ácido fólico, o que pode interferir com a suplementação de ácido fólico". O mecanismo envolve a sulfapiridina (metabolito da sulfassalazina), que inibe o transportador intestinal de folato reduzido (RFC). Esta interação é particularmente relevante em mulheres em idade fértil com DII (risco de defeitos do tubo neural) e em doentes com anemia megaloblástica ou doses elevadas de sulfassalazina. Suplementar com ácido fólico 1 mg/dia (ou 5 mg se planeamento de gravidez) e monitorizar os níveis séricos de folato, hemoglobina e VCM; considerar doses divididas de sulfassalazina para minimizar a exposição à sulfapiridina.',
  explanation_en = 'The sulfasalazine label documents that "reduced absorption of folic acid and digoxin have been reported when these agents were administered concomitantly with sulfasalazine" and that "sulfasalazine inhibits the absorption and metabolism of folic acid, which may interfere with folic acid supplementation". The mechanism involves sulfapyridine (a sulfasalazine metabolite) which inhibits the reduced folate carrier (RFC) intestinal transporter. This interaction is particularly relevant in women of childbearing age with IBD (risk of neural tube defects) and in patients with megaloblastic anaemia or high-dose sulfasalazine. Supplement with folic acid 1 mg/day (or 5 mg if planning pregnancy) and monitor serum folate levels, haemoglobin and MCV; consider divided doses of sulfasalazine to minimise sulfapyridine exposure.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'acido_folico'), (SELECT id FROM public.drugs WHERE slug = 'sulfassalazina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'acido_folico'), (SELECT id FROM public.drugs WHERE slug = 'sulfassalazina'));

-- 12/17 — DICLOFENAC + NAPROXENO (AINE+AINE — toxicidade GI e renal aditiva)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Diclofenac + naproxeno: dois AINE — toxicidade GI, renal e cardiovascular aditiva. Evitar (não melhora a eficácia e aumenta os riscos).',
  summary_pro_en = 'Diclofenac + naproxen: two NSAIDs — additive GI, renal and cardiovascular toxicity. Avoid (no improvement in efficacy and increased risks).',
  explanation_pt = 'O rótulo do naproxeno inclui uma advertência em caixa sobre o "risco aumentado de eventos cardiovasculares trombóticos graves, incluindo enfarte do miocárdio e AVC, que pode ser fatal" e "risco aumentado de eventos adversos gastrointestinais graves, incluindo hemorragia, ulceração e perfuração do estômago ou intestinos, que pode ser fatal". O diclofenac partilha os mesmos riscos. Associar dois AINE não melhora a eficácia analgésica (a inibição da COX é partilhada e tem efeito teto) mas soma os riscos GI (irritação e hemorragia da mucosa gástrica), renais (redução da perfusão glomerular, retenção de sódio e água) e cardiovasculares (trombose, elevação da TA). O rótulo do naproxeno recomenda evitar a associação: "os AINE com semividas de eliminação curtas (ex.: diclofenac, indometacina) devem ser evitados durante o período de administração de pemetrexed" — uma restrição específica, mas o princípio geral de evitar AINE+AINE aplica-se a todos. Usar um único AINE na menor dose eficaz; se a analgesia for insuficiente, associar paracetamol ou um adjuvante não-AINE.',
  explanation_en = 'The naproxen label includes a boxed warning about "increased risk of serious cardiovascular thrombotic events, including myocardial infarction and stroke, which can be fatal" and "increased risk of serious gastrointestinal adverse events including bleeding, ulceration, and perforation of the stomach or intestines, which can be fatal". Diclofenac shares the same risks. Combining two NSAIDs does not improve analgesic efficacy (COX inhibition is shared and has a ceiling effect) but adds up the GI risks (gastric mucosal irritation and bleeding), renal risks (reduced glomerular perfusion, sodium and water retention) and cardiovascular risks (thrombosis, BP elevation). The naproxen label recommends avoiding the combination: "NSAIDs with short elimination half-lives (e.g., diclofenac, indomethacin) should be avoided" during pemetrexed administration — a specific restriction, but the general principle of avoiding NSAID+NSAID applies to all. Use a single NSAID at the lowest effective dose; if analgesia is insufficient, add paracetamol or a non-NSAID adjuvant.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'diclofenac'), (SELECT id FROM public.drugs WHERE slug = 'naproxeno'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'diclofenac'), (SELECT id FROM public.drugs WHERE slug = 'naproxeno'));

-- 13/17 — LEFLUNOMIDA + METOTREXATO (hepatotoxicidade e mielotoxicidade aditivas)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Leflunomida + metotrexato: toxicidade hepática e medular aditiva na artrite reumatoide. Monitorizar ALT, AST e hemograma; usar sem dose de carga da leflunomida.',
  summary_pro_en = 'Leflunomide + methotrexate: additive hepatic and bone marrow toxicity in rheumatoid arthritis. Monitor ALT, AST and blood counts; use without leflunomide loading dose.',
  explanation_pt = 'O rótulo da leflunomida refere que "para doentes com risco elevado de hepatotoxicidade associada à leflunomida (ex.: doentes a tomar metotrexato concomitante)" ou de mielossupressão "a dose recomendada de leflunomida é 20 mg uma vez ao dia sem dose de carga" e que, se administrados em conjunto, "seguir as diretrizes do American College of Rheumatology (ACR) para monitorizar a toxicidade hepática do metotrexato com ALT, AST e albumina sérica". Ambos os fármacos são imunomoduladores usados na artrite reumatoide, frequentemente em associação, e ambos têm potencial de hepatotoxicidade e mielotoxicidade. Monitorizar ALT, AST e albumina mensalmente durante os primeiros 6 meses, depois trimestralmente; hemograma completo com fórmula mensal; suspender se ALT > 3× LSN ou sinais de mielossupressão. A leflunomida não deve ser iniciada com dose de carga (100 mg × 3 dias) quando usada com metotrexato; usar 20 mg/dia desde o início.',
  explanation_en = 'The leflunomide label states that "for patients at high risk for leflunomide-associated hepatotoxicity (e.g., those taking concomitant methotrexate)" or myelosuppression "the recommended leflunomide dosage is 20 mg once daily without a loading dose" and that, if given together, "follow the American College of Rheumatology (ACR) guidelines for monitoring methotrexate liver toxicity with ALT, AST, and serum albumin testing". Both drugs are immunomodulators used in rheumatoid arthritis, often in combination, and both have hepatotoxic and myelotoxic potential. Monitor ALT, AST and albumin monthly during the first 6 months, then quarterly; complete blood count with differential monthly; discontinue if ALT > 3× ULN or signs of myelosuppression. Leflunomide should not be started with a loading dose (100 mg × 3 days) when used with methotrexate; start at 20 mg/day from the beginning.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'leflunomida'), (SELECT id FROM public.drugs WHERE slug = 'metotrexato'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'leflunomida'), (SELECT id FROM public.drugs WHERE slug = 'metotrexato'));

-- 14/17 — DIFENIDRAMINA + MORFINA (sedação e depressão respiratória aditivas)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Difenidramina + morfina: sedação e depressão do SNC aditivas. Risco de sonolência, tonturas e depressão respiratória. Evitar ou monitorizar de perto.',
  summary_pro_en = 'Diphenhydramine + morphine: additive sedation and CNS depression. Risk of somnolence, dizziness and respiratory depression. Avoid or monitor closely.',
  explanation_pt = 'O rótulo da difenidramina documenta que "a difenidramina tem efeitos aditivos com o álcool e outros depressores do SNC (hipnóticos, sedativos, tranquilizadores, etc.)" e o da morfina classifica os "Benzodiazepines and Other Central Nervous System (CNS) Depressants" como interação com risco de "sedação profunda, depressão respiratória, coma e morte" por efeito farmacológico aditivo. A difenidramina é um anti-histamínico H1 com efeito sedativo central e a morfina é um opioide com depressão do SNC e respiratória — a soma é particularmente arriscada em idosos, doentes com DPOC, apneia do sono ou polifarmácia. Evitar sempre que possível; se inevitável (ex.: prurido urémico ou reação alérgica em doente a tomar morfina), usar a menor dose, vigiar sedação e frequência respiratória, e informar o doente para não conduzir ou operar máquinas. Considerar alternativas não sedativas (anti-histamínicos H1 de segunda geração, como a cetirizina, para o prurido).',
  explanation_en = 'The diphenhydramine label documents that "diphenhydramine has additive effects with alcohol and other CNS depressants (hypnotics, sedatives, tranquilizers, etc.)" and the morphine label classifies "Benzodiazepines and Other Central Nervous System (CNS) Depressants" as an interaction with risk of "profound sedation, respiratory depression, coma, and death" due to additive pharmacologic effect. Diphenhydramine is an H1 antihistamine with central sedative effect and morphine is an opioid with CNS and respiratory depression — the sum is particularly risky in the elderly, patients with COPD, sleep apnoea or polypharmacy. Avoid whenever possible; if unavoidable (e.g., uraemic pruritus or allergic reaction in a patient on morphine), use the lowest dose, watch for sedation and respiratory rate, and inform the patient not to drive or operate machinery. Consider non-sedative alternatives (second-generation H1 antihistamines, such as cetirizine, for pruritus).',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'difenidramina'), (SELECT id FROM public.drugs WHERE slug = 'morfina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'difenidramina'), (SELECT id FROM public.drugs WHERE slug = 'morfina'));

-- 15/17 — ALOPURINOL + AMPICILINA (risco de rash cutâneo aumentado)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Alopurinol + ampicilina: risco de reação cutânea grave aumentado. Vigiar erupção cutânea; suspender alopurinol ao primeiro sinal.',
  summary_pro_en = 'Allopurinol + ampicillin: increased risk of severe skin reaction. Watch for skin rash; stop allopurinol at first sign.',
  explanation_pt = 'O rótulo do alopurinol documenta que "os seguintes fármacos podem aumentar o risco de reações cutâneas graves: bendamustina, diuréticos tiazídicos, ampicilina e amoxicilina" (secção 7.1) e adverte que "reações de hipersensibilidade ao alopurinol podem ser aumentadas em doentes com função renal diminuída a receber diuréticos tiazídicos e alopurinol concomitantemente". O mecanismo não é totalmente conhecido, mas a ampicilina parece aumentar a reatividade cutânea durante a terapêutica com alopurinol — possivelmente relacionado com a acumulação do metabolito oxipurinol na pele. A reação não é alérgica à penicilina, mas uma exantema maculopapular que pode ser grave (incluindo síndrome de hipersensibilidade/DRESS). Se surgir erupção cutânea ao iniciar a associação, suspender ambos e reavaliar; não reintroduzir o alopurinol se a reação foi grave. Em doentes que necessitam de ambos, iniciar separadamente, com intervalos de semanas, e vigiar a pele.',
  explanation_en = 'The allopurinol label documents that "the following drugs may increase the risk of serious skin reactions: bendamustine, thiazide diuretics, ampicillin and amoxicillin" (section 7.1) and warns that "hypersensitivity reactions to allopurinol may be increased in patients with decreased kidney function receiving thiazide diuretics and allopurinol concurrently". The mechanism is not fully known, but ampicillin seems to increase skin reactivity during allopurinol therapy — possibly related to accumulation of the oxypurinol metabolite in the skin. The reaction is not a penicillin allergy but a maculopapular exanthema that can be severe (including hypersensitivity syndrome/DRESS). If a skin eruption appears when starting the combination, stop both and reassess; do not reintroduce allopurinol if the reaction was severe. In patients who need both, start separately, with weeks in between, and watch the skin.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'alopurinol'), (SELECT id FROM public.drugs WHERE slug = 'ampicilina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'alopurinol'), (SELECT id FROM public.drugs WHERE slug = 'ampicilina'));

-- 16/17 — ALOPURINOL + AMOXICILINA (risco de rash cutâneo aumentado)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Alopurinol + amoxicilina: risco de reação cutânea grave aumentado. Vigiar erupção cutânea e suspender se surgir.',
  summary_pro_en = 'Allopurinol + amoxicillin: increased risk of severe skin reaction. Watch for skin rash and stop if it appears.',
  explanation_pt = 'Tal como com a ampicilina, o rótulo do alopurinol lista a "amoxicilina" entre os fármacos que "podem aumentar o risco de reações cutâneas graves" (secção 7.1) e recomenda "suspender o alopurinol imediatamente se surgir uma erupção cutânea". O mecanismo é partilhado com a ampicilina — acredita-se que a penicilina aumenta a reatividade cutânea ao alopurinol, possivelmente por alteração da microbiota intestinal ou acumulação do metabolito oxipurinol. A associação é frequente na prática (profilaxia de gota durante terapêutica antibiótica para infeção respiratória ou urinária). A erupção é geralmente maculopapular e benigna, mas pode progredir para reações graves (DRESS, síndrome de Stevens-Johnson). Iniciar o alopurinol e o antibiótico em alturas diferentes, sempre que possível; se o doente já toma alopurinol, informá-lo para vigiar a pele durante a toma da amoxicilina; se surgir rash, suspender ambos e usar um antibiótico alternativo (macrólido, doxiciclina) ou reintroduzir o alopurinol após resolução, com vigilância.',
  explanation_en = 'As with ampicillin, the allopurinol label lists "amoxicillin" among the drugs that "may increase the risk of serious skin reactions" (section 7.1) and recommends "discontinuing allopurinol immediately if a skin rash develops". The mechanism is shared with ampicillin — penicillins are believed to increase skin reactivity to allopurinol, possibly through alteration of the gut microbiota or accumulation of the oxypurinol metabolite. The combination is frequent in practice (gout prophylaxis during antibiotic therapy for respiratory or urinary infection). The rash is usually maculopapular and benign, but can progress to severe reactions (DRESS, Stevens-Johnson syndrome). Start allopurinol and the antibiotic at different times whenever possible; if the patient is already on allopurinol, advise them to watch their skin while taking amoxicillin; if a rash appears, stop both and use an alternative antibiotic (macrolide, doxycycline) or reintroduce allopurinol after resolution, with vigilance.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'alopurinol'), (SELECT id FROM public.drugs WHERE slug = 'amoxicilina'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'alopurinol'), (SELECT id FROM public.drugs WHERE slug = 'amoxicilina'));

-- 17/17 — FLUOXETINA + DEXTROMETORFANO (CYP2D6 + serotonina)
UPDATE public.drug_interactions
SET
  summary_pro_pt = 'Fluoxetina + dextrometorfano: a fluoxetina inibe o CYP2D6 (eleva os níveis de dextrometorfano) e ambos são serotoninérgicos — risco de síndrome serotoninérgica.',
  summary_pro_en = 'Fluoxetine + dextromethorphan: fluoxetine inhibits CYP2D6 (raises dextromethorphan levels) and both are serotonergic — risk of serotonin syndrome.',
  explanation_pt = 'A fluoxetina é um "inibidor potente da via enzimática do CYP2D6" (rótulo da fluoxetina, secção 7.7) e o dextrometorfano é metabolizado primariamente pelo CYP2D6 (o seu metabolito principal, dextrorfano, é ativo). A inibição do CYP2D6 pela fluoxetina pode aumentar significativamente as concentrações de dextrometorfano, e ambos os fármacos têm atividade serotoninérgica — o dextrometorfano é um inibidor fraco da recaptação de serotonina e a fluoxetina é um ISRS potente. O risco de síndrome serotoninérgica (agitação, confusão, febre, tremor, clónus, hiperreflexia) soma-se ao risco de níveis elevados de dextrometorfano (sedação, tonturas, náuseas, ataxia). A associação é frequente em medicamentos para a tosse de venda livre em doentes a tomar fluoxetina. Evitar o dextrometorfano em doentes a tomar fluoxetina; se inevitável, usar a menor dose e a menor duração possíveis, e informar o doente para vigiar sintomas serotoninérgicos (agitação, espasmos, febre) e neurológicos (tonturas, ataxia). Considerar antitússicos alternativos não serotoninérgicos.',
  explanation_en = 'Fluoxetine is a "potent inhibitor of the CYP2D6 enzyme pathway" (fluoxetine label, section 7.7) and dextromethorphan is primarily metabolised by CYP2D6 (its main metabolite, dextrorphan, is active). CYP2D6 inhibition by fluoxetine can significantly raise dextromethorphan concentrations, and both drugs have serotonergic activity — dextromethorphan is a weak serotonin reuptake inhibitor and fluoxetine is a potent SSRI. The risk of serotonin syndrome (agitation, confusion, fever, tremor, clonus, hyperreflexia) adds to the risk of raised dextromethorphan levels (sedation, dizziness, nausea, ataxia). The combination is frequent in over-the-counter cough medicines in patients taking fluoxetine. Avoid dextromethorphan in patients taking fluoxetine; if unavoidable, use the lowest dose and shortest duration possible, and advise the patient to watch for serotonergic symptoms (agitation, twitching, fever) and neurological symptoms (dizziness, ataxia). Consider alternative non-serotonergic antitussives.',
  updated_at = now()
WHERE LEAST(drug_a_id, drug_b_id) = LEAST((SELECT id FROM public.drugs WHERE slug = 'fluoxetina'), (SELECT id FROM public.drugs WHERE slug = 'dextrometorfano'))
  AND GREATEST(drug_a_id, drug_b_id) = GREATEST((SELECT id FROM public.drugs WHERE slug = 'fluoxetina'), (SELECT id FROM public.drugs WHERE slug = 'dextrometorfano'));