-- 162: Grupo 13 do Prontuário Terapêutico — Dermatologia
-- Adiciona 4 fármacos novos (retinóides sistémicos e tetraciclinas orais) e
-- 18 pares de interação, todos ancorados em rótulos FDA/DailyMed validados.
--
-- Fármacos novos (ação sistémica — os restantes fármacos do grupo 13 são de
-- aplicação tópica, sem interações fármaco-fármaco sistémicas relevantes):
--   isotretinoina (acne severa), acitretina (psoríase grave),
--   tetraciclina e minociclina (acne/rosácea sistémica).
--
-- Pares (documentados nos rótulos):
--   Isotretinoína: × doxiciclina, × minociclina (pseudotumor cerebri — evitar),
--     × fenitoína, × prednisolona (perda óssea — precaução).
--   Acitretina: × metotrexato (hepatite — CONTRAINDICADO), × doxiciclina
--     (pressão intracraneana — CONTRAINDICADO), × fenitoína (reduz ligação
--     proteica da fenitoína).
--   Tetraciclina: × varfarina (deprime protrombina — ajustar dose), × ampicilina
--     (antagonismo bacteriostático/bactericida — evitar), × antiácidos, × zinco,
--     × ferro, × carbonato de cálcio (quelação — absorção reduzida).
--   Minociclina: × varfarina, × ampicilina, × antiácidos, × zinco, × ferro
--     (mesmos mecanismos da classe).
--
-- Fontes: rótulos aprovados pela FDA/DailyMed — DailyMed/FDA (NIH/NLM);
-- setIDs obtidos na API pública v2 (spls.json?drug_name=...) e revalidados
-- pelo endpoint XML (spls/{setid}.xml) com confirmação do nome do produto
-- a 2026-08-17. Palavras-chave confirmadas no texto dos rótulos:
--   isotretinoína: "pseudotumor cerebri... concomitant use of tetracyclines
--     should therefore be avoided"; fenitoína/corticosteróides "may weaken
--     your bones".
--   acitretina: "combined use of methotrexate and etretinate... contraindicated";
--     "both acitretin and tetracyclines can cause increased intracranial
--     pressure, their combined use is contraindicated"; fenitoína "protein
--     binding... may be reduced".
--   tetraciclina: "depress plasma prothrombin activity... anticoagulant dosage";
--     "avoid giving tetracycline in conjunction with penicillin"; "absorption...
--     impaired by antacids containing aluminum, calcium or magnesium and
--     preparations containing iron, zinc, or sodium bicarbonate".
--   minociclina: mesmos mecanismos da classe + "Administration of isotretinoin
--     should be avoided... during... minocycline therapy".
--
-- Metodologia (ver docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST sobre ids por slug;
--   * sem pares artificiais: só pares documentados nos rótulos aprovados;
--   * idempotente (UNIQUE (drug_a_id, drug_b_id), ON CONFLICT DO NOTHING).

INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order)
VALUES
  ('isotretinoina', 'Isotretinoína', 'Isotretinoin', 'Retinóide sistémico (acne nodular/severa)', 'Systemic retinoid (nodular/severe acne)', ARRAY['Isotretinoína', 'Roacutan'], 'published', 191),
  ('acitretina', 'Acitretina', 'Acitretin', 'Retinóide sistémico (psoríase grave)', 'Systemic retinoid (severe psoriasis)', ARRAY['Acitretina', 'Neotigason'], 'published', 192),
  ('tetraciclina', 'Tetraciclina', 'Tetracycline', 'Antibiótico tetraciclina (oral)', 'Tetracycline antibiotic (oral)', ARRAY['Tetraciclina'], 'published', 193),
  ('minociclina', 'Minociclina', 'Minocycline', 'Antibiótico tetraciclina semissintético (oral)', 'Semisynthetic tetracycline antibiotic (oral)', ARRAY['Minociclina'], 'published', 194);

INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
        (SELECT id FROM public.drugs WHERE slug = 'doxiciclina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
            (SELECT id FROM public.drugs WHERE slug = 'doxiciclina')),
   'moderate',
   'A associação de Isotretinoína com tetraciclinas (Doxiciclina) deve ser evitada: ambas podem causar pseudotumor cerebri (hipertensão intracraneana benigna).',
   'The combination of Isotretinoin with tetracyclines (Doxycycline) should be avoided: both may cause pseudotumor cerebri (benign intracranial hypertension).',
   'Tanto a isotretinoína como as tetraciclinas estão associadas a casos de pseudotumor cerebri; o uso concomitante aumenta o risco de forma aditiva.',
   'Both isotretinoin and tetracyclines are associated with cases of pseudotumor cerebri; concomitant use increases the risk additively.',
   'Evitar a associação. Se inevitável, vigiar sinais precoces de pseudotumor cerebri.',
   'Avoid the combination. If unavoidable, monitor for early signs of pseudotumor cerebri.',
   'Vigiar cefaleias, náuseas, vómitos, alterações visuais e papiledema.',
   'Monitor for headache, nausea, vomiting, visual disturbances and papilledema.',
   'Cefaleias persistentes, alterações visuais, papiledema.',
   'Persistent headache, visual disturbances, papilledema.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isotretinoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f0fbf63a-e75c-40cf-b2e9-429deaac899d',
   'DailyMed/FDA (NIH/NLM) — approved Isotretinoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f0fbf63a-e75c-40cf-b2e9-429deaac899d',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
        (SELECT id FROM public.drugs WHERE slug = 'minociclina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
            (SELECT id FROM public.drugs WHERE slug = 'minociclina')),
   'moderate',
   'A administração de Isotretinoína deve ser evitada durante e imediatamente após terapêutica com Minociclina: ambos os fármacos, isoladamente, estão associados a pseudotumor cerebri.',
   'Administration of Isotretinoin should be avoided during and shortly after Minocycline therapy: each drug alone has been associated with pseudotumor cerebri.',
   'Tanto a isotretinoína como a minociclina podem causar pseudotumor cerebri; o uso concomitante ou sequencial próximo aumenta o risco.',
   'Both isotretinoin and minocycline may cause pseudotumor cerebri; concomitant or closely sequential use increases the risk.',
   'Evitar a administração de isotretinoína durante e pouco depois da minociclina.',
   'Avoid isotretinoin administration during and shortly after minocycline.',
   'Vigiar cefaleias, náuseas, vómitos e alterações visuais.',
   'Monitor for headache, nausea, vomiting and visual disturbances.',
   'Cefaleias persistentes, alterações visuais ou papiledema.',
   'Persistent headache, visual disturbances or papilledema.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isotretinoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; rótulo aprovado Minociclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06',
   'DailyMed/FDA (NIH/NLM) — approved Isotretinoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; approved Minocycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
        (SELECT id FROM public.drugs WHERE slug = 'fenitoina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
            (SELECT id FROM public.drugs WHERE slug = 'fenitoina')),
   'moderate',
   'Isotretinoína + Fenitoína: precaução pelo possível efeito aditivo na perda óssea (osteomalácia associada à fenitoína).',
   'Isotretinoin + Phenytoin: caution due to the possible additive effect on bone loss (phenytoin-associated osteomalacia).',
   'A fenitoína é conhecida por causar osteomalácia; não foram conduzidos estudos formais sobre o efeito interativo na perda óssea com a isotretinoína, mas o rótulo recomenda precaução.',
   'Phenytoin is known to cause osteomalacia; no formal studies assessed the interactive effect on bone loss with isotretinoin, but the label advises caution.',
   'Usar com precaução; considerar vigilância da saúde óssea em tratamentos prolongados.',
   'Use with caution; consider bone health monitoring during prolonged treatment.',
   'Vigiar sinais de perda óssea ou fraturas em terapêuticas prolongadas.',
   'Monitor for signs of bone loss or fractures during prolonged therapy.',
   'Dor óssea, fraturas ou osteomalácia em tratamentos prolongados.',
   'Bone pain, fractures or osteomalacia during prolonged treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isotretinoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3580e6a8-f7c3-44a0-a1eb-2a84ae589d21',
   'DailyMed/FDA (NIH/NLM) — approved Isotretinoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3580e6a8-f7c3-44a0-a1eb-2a84ae589d21',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
        (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'isotretinoina'),
            (SELECT id FROM public.drugs WHERE slug = 'prednisolona')),
   'moderate',
   'Isotretinoína + corticosteróides sistémicos (Prednisolona): precaução pelo possível efeito aditivo na perda óssea.',
   'Isotretinoin + systemic corticosteroids (Prednisolone): caution due to the possible additive effect on bone loss.',
   'Os corticosteróides sistémicos podem causar osteoporose/osteomalácia induzida por fármacos; o rótulo da isotretinoína alerta para o risco acrescido de perda óssea com o uso concomitante.',
   'Systemic corticosteroids may cause drug-induced osteoporosis/osteomalacia; the isotretinoin label warns of the increased risk of bone loss with concomitant use.',
   'Usar com precaução; ponderar vigilância da densidade óssea em tratamentos prolongados.',
   'Use with caution; consider bone density monitoring during prolonged treatment.',
   'Vigiar sinais de perda óssea em terapêuticas prolongadas.',
   'Monitor for signs of bone loss during prolonged therapy.',
   'Dor óssea, fraturas ou osteoporose em tratamentos prolongados.',
   'Bone pain, fractures or osteoporosis during prolonged treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isotretinoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; rótulo aprovado Prednisolona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757b41c4-a0fe-4a09-8816-a4cdb7558f41',
   'DailyMed/FDA (NIH/NLM) — approved Isotretinoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d5a26c5e-9c3e-4781-8c08-62b91d21a68d ; approved Prednisolone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=757b41c4-a0fe-4a09-8816-a4cdb7558f41',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'acitretina'),
        (SELECT id FROM public.drugs WHERE slug = 'metotrexato')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'acitretina'),
            (SELECT id FROM public.drugs WHERE slug = 'metotrexato')),
   'critical',
   'Acitretina + Metotrexato é CONTRAINDICADO: risco aumentado de hepatite com a combinação.',
   'Acitretin + Methotrexate is CONTRAINDICATED: increased risk of hepatitis with the combination.',
   'Foi reportado um risco aumentado de hepatite com o uso combinado de metotrexato e etretinato (precursor da acitretina); consequentemente, a combinação de metotrexato com acitretina está contraindicada.',
   'An increased risk of hepatitis has been reported with the combined use of methotrexate and etretinate (a precursor of acitretin); consequently, the combination of methotrexate with acitretin is contraindicated.',
   'Não utilizar a associação. Escolher alternativa terapêutica para a psoríase.',
   'Do not use the combination. Choose an alternative psoriasis therapy.',
   'Vigiar função hepática se houver exposição acidental.',
   'Monitor liver function if there is accidental exposure.',
   'Icterícia, elevação das transaminases ou sinais de hepatite.',
   'Jaundice, elevated transaminases or signs of hepatitis.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acitretina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a6546625-acb8-460e-b34e-f795bfb3680a ; rótulo aprovado Metotrexato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=04a95db9-a124-4b97-bd71-1c37a6b3b0c8',
   'DailyMed/FDA (NIH/NLM) — approved Acitretin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a6546625-acb8-460e-b34e-f795bfb3680a ; approved Methotrexate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=04a95db9-a124-4b97-bd71-1c37a6b3b0c8',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'acitretina'),
        (SELECT id FROM public.drugs WHERE slug = 'doxiciclina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'acitretina'),
            (SELECT id FROM public.drugs WHERE slug = 'doxiciclina')),
   'critical',
   'Acitretina + tetraciclinas (Doxiciclina) é CONTRAINDICADO: ambas podem causar aumento da pressão intracraneana.',
   'Acitretin + tetracyclines (Doxycycline) is CONTRAINDICATED: both may cause increased intracranial pressure.',
   'Como tanto a acitretina como as tetraciclinas podem causar aumento da pressão intracraneana (pseudotumor cerebri), o seu uso combinado está contraindicado.',
   'Since both acitretin and tetracyclines can cause increased intracranial pressure (pseudotumor cerebri), their combined use is contraindicated.',
   'Não utilizar a associação.',
   'Do not use the combination.',
   'Vigiar cefaleias, alterações visuais e papiledema em caso de exposição.',
   'Monitor for headache, visual disturbances and papilledema in case of exposure.',
   'Cefaleias persistentes, alterações visuais, papiledema.',
   'Persistent headache, visual disturbances, papilledema.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acitretina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a6546625-acb8-460e-b34e-f795bfb3680a ; rótulo aprovado Doxiciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f0fbf63a-e75c-40cf-b2e9-429deaac899d',
   'DailyMed/FDA (NIH/NLM) — approved Acitretin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a6546625-acb8-460e-b34e-f795bfb3680a ; approved Doxycycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f0fbf63a-e75c-40cf-b2e9-429deaac899d',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'acitretina'),
        (SELECT id FROM public.drugs WHERE slug = 'fenitoina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'acitretina'),
            (SELECT id FROM public.drugs WHERE slug = 'fenitoina')),
   'moderate',
   'Acitretina + Fenitoína: a acitretina pode reduzir a ligação proteica da fenitoína, com possível aumento da fração livre.',
   'Acitretin + Phenytoin: acitretin may reduce the protein binding of phenytoin, possibly increasing the free fraction.',
   'Quando a acitretina é administrada com fenitoína, a ligação proteica da fenitoína pode ser reduzida, aumentando a fração livre farmacologicamente ativa.',
   'When acitretin is given with phenytoin, the protein binding of phenytoin may be reduced, increasing the pharmacologically active free fraction.',
   'Usar com precaução; considerar vigilância dos níveis de fenitoína e sinais de toxicidade.',
   'Use with caution; consider monitoring phenytoin levels and signs of toxicity.',
   'Vigiar sinais de toxicidade da fenitoína (nistagmo, ataxia, sonolência).',
   'Monitor for signs of phenytoin toxicity (nystagmus, ataxia, drowsiness).',
   'Nistagmo, ataxia, sonolência ou outros sinais de toxicidade da fenitoína.',
   'Nystagmus, ataxia, drowsiness or other signs of phenytoin toxicity.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acitretina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a6546625-acb8-460e-b34e-f795bfb3680a ; rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3580e6a8-f7c3-44a0-a1eb-2a84ae589d21',
   'DailyMed/FDA (NIH/NLM) — approved Acitretin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a6546625-acb8-460e-b34e-f795bfb3680a ; approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3580e6a8-f7c3-44a0-a1eb-2a84ae589d21',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'Tetraciclina + Varfarina: as tetraciclinas podem deprimir a atividade da protrombina; pode ser necessário reduzir a dose do anticoagulante.',
   'Tetracycline + Warfarin: tetracyclines may depress plasma prothrombin activity; a downward adjustment of the anticoagulant dosage may be required.',
   'As tetraciclinas demonstraram deprimir a atividade da protrombina plasmática, potenciando o efeito dos anticoagulantes orais.',
   'Tetracyclines have been shown to depress plasma prothrombin activity, potentiating the effect of oral anticoagulants.',
   'Vigiar o INR durante a associação e ajustar a dose da varfarina conforme necessário.',
   'Monitor INR during the combination and adjust the warfarin dose as needed.',
   'Vigiar INR e sinais de hemorragia.',
   'Monitor INR and signs of bleeding.',
   'Sangramento, hematomas ou INR acima do alvo.',
   'Bleeding, bruising or INR above target.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tetraciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Tetracycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
        (SELECT id FROM public.drugs WHERE slug = 'ampicilina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
            (SELECT id FROM public.drugs WHERE slug = 'ampicilina')),
   'moderate',
   'Tetraciclina + Ampicilina: os fármacos bacteriostáticos podem interferir com a ação bactericida das penicilinas; é aconselhável evitar a associação.',
   'Tetracycline + Ampicillin: bacteriostatic drugs may interfere with the bactericidal action of penicillins; the combination should be avoided.',
   'A tetraciclina, bacteriostática, pode interferir com a ação bactericida da ampicilina quando usadas em conjunto.',
   'Tetracycline, being bacteriostatic, may interfere with the bactericidal action of ampicillin when used together.',
   'Evitar a associação; se necessária, separar a toma e considerar alternativa.',
   'Avoid the combination; if needed, separate dosing and consider an alternative.',
   'Vigiar eficácia terapêutica da infeção.',
   'Monitor therapeutic efficacy of the infection.',
   'Falência terapêutica da infeção tratada.',
   'Therapeutic failure of the treated infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tetraciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3b683547-48ac-48ca-8fd4-6866fd17be34',
   'DailyMed/FDA (NIH/NLM) — approved Tetracycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3b683547-48ac-48ca-8fd4-6866fd17be34',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Tetraciclina + Antiácidos (com alumínio, cálcio ou magnésio): a absorção da tetraciclina fica comprometida por quelação. Separar as tomas.',
   'Tetracycline + Antacids (with aluminum, calcium or magnesium): tetracycline absorption is impaired by chelation. Separate dosing times.',
   'Os antiácidos com alumínio, cálcio ou magnésio quelam a tetraciclina no lúmen gastrointestinal, reduzindo a sua absorção e a eficácia.',
   'Antacids with aluminum, calcium or magnesium chelate tetracycline in the gastrointestinal lumen, reducing its absorption and efficacy.',
   'Separar a toma da tetraciclina dos antiácidos por pelo menos 2–4 horas.',
   'Separate tetracycline dosing from antacids by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tetraciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a13ac81-0c63-48c1-bbb0-f6e67f97b896',
   'DailyMed/FDA (NIH/NLM) — approved Tetracycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a13ac81-0c63-48c1-bbb0-f6e67f97b896',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
        (SELECT id FROM public.drugs WHERE slug = 'zinco')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
            (SELECT id FROM public.drugs WHERE slug = 'zinco')),
   'moderate',
   'Tetraciclina + Zinco: a absorção da tetraciclina fica comprometida por quelação com preparações contendo zinco. Separar as tomas.',
   'Tetracycline + Zinc: tetracycline absorption is impaired by chelation with preparations containing zinc. Separate dosing times.',
   'As preparações contendo zinco quelam a tetraciclina no intestino, reduzindo a sua absorção e eficácia.',
   'Preparations containing zinc chelate tetracycline in the gut, reducing its absorption and efficacy.',
   'Separar a toma da tetraciclina dos suplementos de zinco por pelo menos 2–4 horas.',
   'Separate tetracycline dosing from zinc supplements by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tetraciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; rótulo aprovado Zinco: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49698d00-f44b-4b1f-ae34-6b9067911757',
   'DailyMed/FDA (NIH/NLM) — approved Tetracycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; approved Zinc label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49698d00-f44b-4b1f-ae34-6b9067911757',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
        (SELECT id FROM public.drugs WHERE slug = 'ferro')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
            (SELECT id FROM public.drugs WHERE slug = 'ferro')),
   'moderate',
   'Tetraciclina + Ferro: a absorção da tetraciclina fica comprometida por quelação com preparações contendo ferro. Separar as tomas.',
   'Tetracycline + Iron: tetracycline absorption is impaired by chelation with preparations containing iron. Separate dosing times.',
   'As preparações contendo ferro quelam a tetraciclina no lúmen gastrointestinal, reduzindo a sua absorção e eficácia.',
   'Preparations containing iron chelate tetracycline in the gastrointestinal lumen, reducing its absorption and efficacy.',
   'Separar a toma da tetraciclina dos suplementos de ferro por pelo menos 2–4 horas.',
   'Separate tetracycline dosing from iron supplements by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tetraciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f',
   'DailyMed/FDA (NIH/NLM) — approved Tetracycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
        (SELECT id FROM public.drugs WHERE slug = 'carbonato_calcio')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tetraciclina'),
            (SELECT id FROM public.drugs WHERE slug = 'carbonato_calcio')),
   'moderate',
   'Tetraciclina + Cálcio: a absorção da tetraciclina fica comprometida por quelação com preparações contendo cálcio. Separar as tomas.',
   'Tetracycline + Calcium: tetracycline absorption is impaired by chelation with preparations containing calcium. Separate dosing times.',
   'Os antiácidos e suplementos com cálcio quelam a tetraciclina no lúmen gastrointestinal, reduzindo a sua absorção e eficácia.',
   'Antacids and supplements with calcium chelate tetracycline in the gastrointestinal lumen, reducing its absorption and efficacy.',
   'Separar a toma da tetraciclina dos produtos com cálcio por pelo menos 2–4 horas.',
   'Separate tetracycline dosing from calcium-containing products by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tetraciclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; rótulo aprovado Carbonato de cálcio: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24cec2bc-cf12-b513-e063-6394a90a9447',
   'DailyMed/FDA (NIH/NLM) — approved Tetracycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=02e88b4a-57ae-4ef6-ba48-97c657202b94 ; approved Calcium carbonate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=24cec2bc-cf12-b513-e063-6394a90a9447',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'Minociclina + Varfarina: as tetraciclinas podem deprimir a atividade da protrombina; pode ser necessário reduzir a dose do anticoagulante.',
   'Minocycline + Warfarin: tetracyclines may depress plasma prothrombin activity; a downward adjustment of the anticoagulant dosage may be required.',
   'As tetraciclinas demonstraram deprimir a atividade da protrombina plasmática, potenciando o efeito dos anticoagulantes orais.',
   'Tetracyclines have been shown to depress plasma prothrombin activity, potentiating the effect of oral anticoagulants.',
   'Vigiar o INR durante a associação e ajustar a dose da varfarina conforme necessário.',
   'Monitor INR during the combination and adjust the warfarin dose as needed.',
   'Vigiar INR e sinais de hemorragia.',
   'Monitor INR and signs of bleeding.',
   'Sangramento, hematomas ou INR acima do alvo.',
   'Bleeding, bruising or INR above target.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Minociclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; rótulo aprovado Varfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Minocycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
        (SELECT id FROM public.drugs WHERE slug = 'ampicilina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
            (SELECT id FROM public.drugs WHERE slug = 'ampicilina')),
   'moderate',
   'Minociclina + Ampicilina: os fármacos bacteriostáticos podem interferir com a ação bactericida das penicilinas; é aconselhável evitar a associação.',
   'Minocycline + Ampicillin: bacteriostatic drugs may interfere with the bactericidal action of penicillins; the combination should be avoided.',
   'A minociclina, bacteriostática, pode interferir com a ação bactericida da ampicilina quando usadas em conjunto.',
   'Minocycline, being bacteriostatic, may interfere with the bactericidal action of ampicillin when used together.',
   'Evitar a associação; se necessária, separar a toma e considerar alternativa.',
   'Avoid the combination; if needed, separate dosing and consider an alternative.',
   'Vigiar eficácia terapêutica da infeção.',
   'Monitor therapeutic efficacy of the infection.',
   'Falência terapêutica da infeção tratada.',
   'Therapeutic failure of the treated infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Minociclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; rótulo aprovado Ampicilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3b683547-48ac-48ca-8fd4-6866fd17be34',
   'DailyMed/FDA (NIH/NLM) — approved Minocycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; approved Ampicillin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3b683547-48ac-48ca-8fd4-6866fd17be34',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Minociclina + Antiácidos (com alumínio, cálcio ou magnésio): a absorção da minociclina fica comprometida por quelação. Separar as tomas.',
   'Minocycline + Antacids (with aluminum, calcium or magnesium): minocycline absorption is impaired by chelation. Separate dosing times.',
   'Os antiácidos com alumínio, cálcio ou magnésio quelam a minociclina no lúmen gastrointestinal, reduzindo a sua absorção e eficácia.',
   'Antacids with aluminum, calcium or magnesium chelate minocycline in the gastrointestinal lumen, reducing its absorption and efficacy.',
   'Separar a toma da minociclina dos antiácidos por pelo menos 2–4 horas.',
   'Separate minocycline dosing from antacids by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Minociclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a13ac81-0c63-48c1-bbb0-f6e67f97b896',
   'DailyMed/FDA (NIH/NLM) — approved Minocycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a13ac81-0c63-48c1-bbb0-f6e67f97b896',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
        (SELECT id FROM public.drugs WHERE slug = 'zinco')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
            (SELECT id FROM public.drugs WHERE slug = 'zinco')),
   'moderate',
   'Minociclina + Zinco: a absorção da minociclina fica comprometida por quelação com preparações contendo zinco. Separar as tomas.',
   'Minocycline + Zinc: minocycline absorption is impaired by chelation with preparations containing zinc. Separate dosing times.',
   'As preparações contendo zinco quelam a minociclina no intestino, reduzindo a sua absorção e eficácia.',
   'Preparations containing zinc chelate minocycline in the gut, reducing its absorption and efficacy.',
   'Separar a toma da minociclina dos suplementos de zinco por pelo menos 2–4 horas.',
   'Separate minocycline dosing from zinc supplements by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Minociclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; rótulo aprovado Zinco: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49698d00-f44b-4b1f-ae34-6b9067911757',
   'DailyMed/FDA (NIH/NLM) — approved Minocycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; approved Zinc label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=49698d00-f44b-4b1f-ae34-6b9067911757',
   'published', now()),

  (LEAST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
        (SELECT id FROM public.drugs WHERE slug = 'ferro')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'minociclina'),
            (SELECT id FROM public.drugs WHERE slug = 'ferro')),
   'moderate',
   'Minociclina + Ferro: a absorção da minociclina fica comprometida por quelação com preparações contendo ferro. Separar as tomas.',
   'Minocycline + Iron: minocycline absorption is impaired by chelation with preparations containing iron. Separate dosing times.',
   'As preparações contendo ferro quelam a minociclina no lúmen gastrointestinal, reduzindo a sua absorção e eficácia.',
   'Preparations containing iron chelate minocycline in the gastrointestinal lumen, reducing its absorption and efficacy.',
   'Separar a toma da minociclina dos suplementos de ferro por pelo menos 2–4 horas.',
   'Separate minocycline dosing from iron supplements by at least 2–4 hours.',
   'Vigiar eficácia do antibiótico.',
   'Monitor antibiotic efficacy.',
   'Falência terapêutica da infeção.',
   'Therapeutic failure of the infection.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Minociclina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; rótulo aprovado Ferro: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f',
   'DailyMed/FDA (NIH/NLM) — approved Minocycline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a5fc4d50-50b2-46e0-b722-4c6b2ec47d06 ; approved Iron label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73d1f079-d8eb-44f4-b33d-05fb25b80c8f',
   'published', now())
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;
