-- =====================================================================
-- 173: Pares de interação para os 24 fármacos sem pares + 5 fármacos
--      novos (parceiros fora da BD) — aumento do catálogo
-- ---------------------------------------------------------------------
-- Objetivo: fechar a lacuna dos 24 fármacos com 0 pares em
-- drug_interactions (auditoria 2026-08-08). Quando o parceiro
-- documentado não existe na BD, o parceiro é adicionado como fármaco
-- novo (padrão da 168: antiácidos, ferro, zinco) — 5 novos:
--   probenecida, colestiramina, tizanidina, amantadina, cetamina.
--
-- Fontes: rótulos aprovados FDA/DailyMed (NIH/NLM) — setIDs validados na
-- API pública v2 (spls.json?drug_name=...) + endpoint XML (spls/{setid}.xml)
-- a 2026-08-17; Prontuário Terapêutico do INFARMED (11.ª ed., 2012) para
-- os sem rótulo FDA ativo (artesunato, butilbrometo de hioscina,
-- etilefrina, fenoximetilpenicilina, nistatina) e para corroborar.
-- Parceiros já existentes: setIDs reutilizados das citações já presentes
-- na BD (regra da secção 15.2).
--
-- Fármacos novos (setIDs validados a 2026-08-17):
--   probenecida   (MARLEX)    5d552de5-2d18-4464-bcaf-0311fa3f080d
--   colestiramina (ASCEND)    430ac07e-8524-4dec-a599-b7ebc56d9563
--   tizanidina    (PREFERRED) 8d0b2b22-e1df-4ad5-92e6-f9a369108e4b
--   amantadina    (GOCOVRI)   2bee0631-0028-1314-e063-6394a90aaaed
--   cetamina      (KETALAR)   14e8f864-8b8a-4e7e-8439-e510d3107063
--
-- Pares (36): todos ancorados nas fontes — ver âncora em cada par.
-- Sem pares (documentados no corpo): aminoácidos, artesunato,
-- butilbrometo de hioscina (ver nota), filgrastim, nistatina,
-- poractanto alfa, primaquina.
--
-- Metodologia (docs/INTERACOES_FLUXO_PESQUISA.md):
--   * pares canónicos (drug_a_id < drug_b_id) via LEAST/GREATEST;
--   * sem pares artificiais: só pares documentados;
--   * idempotente (UNIQUE (drug_a_id, drug_b_id), ON CONFLICT DO NOTHING);
--   * ordem de aplicação: 173 após 171/172 (não depende delas).
-- =====================================================================

-- =====================================================================
-- 1. Fármacos novos (5) — padrão 7.3
-- =====================================================================
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order)
VALUES
  ('probenecida', 'Probenecida', 'Probenecid', 'Uricosúrico / adjuvante de antibióticos (bloqueador da secreção tubular)', 'Uricosuric / antibiotic adjuvant (tubular secretion blocker)', ARRAY['Probenecida', 'Benemid'], 'published', 205),
  ('colestiramina', 'Colestiramina', 'Cholestyramine', 'Sequestrante de ácidos biliares (hipolipemiante)', 'Bile acid sequestrant (lipid-lowering)', ARRAY['Colestiramina', 'Questran'], 'published', 206),
  ('tizanidina', 'Tizanidina', 'Tizanidine', 'Relaxante muscular de ação central (agonista alfa-2 adrenérgico)', 'Centrally acting muscle relaxant (alpha-2 adrenergic agonist)', ARRAY['Tizanidina', 'Sirdalud'], 'published', 207),
  ('amantadina', 'Amantadina', 'Amantadine', 'Antiparkinsónico / antiviral (antagonista NMDA)', 'Antiparkinsonian / antiviral (NMDA antagonist)', ARRAY['Amantadina', 'Symmetrel'], 'published', 208),
  ('cetamina', 'Cetamina', 'Ketamine', 'Anestésico dissociativo (antagonista NMDA)', 'Dissociative anaesthetic (NMDA antagonist)', ARRAY['Cetamina', 'Ketalar'], 'published', 209);

-- =====================================================================
-- 2. Pares (36) — padrão 7.4 (INSERT direto com LEAST/GREATEST)
-- =====================================================================
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en, mechanism_pt, mechanism_en,
   management_pt, management_en, monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, status, updated_at)
VALUES
  -- Acetilcisteína × Nitroglicerina (Prontuário 5.2.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'acetilcisteina'),
        (SELECT id FROM public.drugs WHERE slug = 'nitroglicerina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'acetilcisteina'),
            (SELECT id FROM public.drugs WHERE slug = 'nitroglicerina')),
   'moderate',
   'Acetilcisteína + nitroglicerina: risco de hipotensão e cefaleias quando administradas em conjunto.', 
   'Acetylcysteine + nitroglycerin: risk of hypotension and headache when given together.',
   'O Prontuário Terapêutico regista a interação entre a acetilcisteína e a nitroglicerina (hipotensão e cefaleias) na monografia da acetilcisteína (5.2.2). O mecanismo é a potenciação vasodilatadora — a acetilcisteína aumenta a disponibilidade do óxido nítrico, reforçando o efeito vasodilatador e hipotensor da nitroglicerina.',
   'The Prontuário Terapêutico records the interaction between acetylcysteine and nitroglycerin (hypotension and headache) in the acetylcysteine monograph (5.2.2). The mechanism is vasodilatory potentiation — acetylcysteine increases nitric oxide availability, reinforcing the vasodilatory and hypotensive effect of nitroglycerin.',
   'Monitorizar a tensão arterial durante a co-administração; advertir o doente para o risco de cefaleias e hipotensão ortostática.',
   'Monitor blood pressure during co-administration; warn the patient about the risk of headache and orthostatic hypotension.',
   'Vigilância clínica de sintomas (cefaleias, tonturas, hipotensão) nas primeiras administrações conjuntas.',
   'Clinical monitoring of symptoms (headache, dizziness, hypotension) during the first combined administrations.',
   'Hipotensão sintomática, síncope ou cefaleias intensas após a toma conjunta.',
   'Symptomatic hypotension, syncope or severe headache after combined intake.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Acetilcisteína, 5.2.2',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Acetylcysteine, 5.2.2', 'published', now()),

  -- Ácido ursodesoxicólico × Colestiramina (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'acido_ursodesoxicolico'),
        (SELECT id FROM public.drugs WHERE slug = 'colestiramina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'acido_ursodesoxicolico'),
            (SELECT id FROM public.drugs WHERE slug = 'colestiramina')),
   'moderate',
   'Ácido ursodesoxicólico + colestiramina: a colestiramina reduz a absorção do ursodesoxicólico — separar as tomas por 4-6 horas.',
   'Ursodeoxycholic acid + cholestyramine: cholestyramine reduces ursodiol absorption — separate doses by 4-6 hours.',
   'O rótulo FDA do ursodiol documenta: "Bile Acid Sequestering Agents: May interfere with the action of ursodiol tablets by reducing its absorption" (7.1). A colestiramina liga-se aos ácidos biliares no lúmen intestinal e reduz a absorção do ursodesoxicólico administrado por via oral, comprometendo o efeito na litíase biliar.',
   'The FDA ursodiol label documents: "Bile Acid Sequestering Agents: May interfere with the action of ursodiol tablets by reducing its absorption" (7.1). Cholestyramine binds bile acids in the gut lumen and reduces the absorption of orally administered ursodiol, compromising its effect in gallstone disease.',
   'Administrar o ácido ursodesoxicólico pelo menos 1 hora antes ou 4-6 horas depois da colestiramina; idealmente espaçar 4-6 horas.',
   'Give ursodeoxycholic acid at least 1 hour before or 4-6 hours after cholestyramine; ideally space by 4-6 hours.',
   'Avaliar a resposta clínica (sintomas biliares, controlo ecográfico quando aplicável) durante a associação.',
   'Assess clinical response (biliary symptoms, ultrasound follow-up when applicable) during the combination.',
   'Falta de resposta ao tratamento da litíase biliar com toma simultânea.',
   'Lack of response in gallstone treatment with simultaneous intake.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ursodiol (BLUEPOINT LABORATORIES), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a3c98080-0a4d-4a93-8dcb-02ab8533050b ; rótulo aprovado Colestiramina (ASCEND LABORATORIES): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=430ac07e-8524-4dec-a599-b7ebc56d9563',
   'DailyMed/FDA (NIH/NLM) — approved Ursodiol label (BLUEPOINT LABORATORIES), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a3c98080-0a4d-4a93-8dcb-02ab8533050b ; approved Cholestyramine label (ASCEND LABORATORIES): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=430ac07e-8524-4dec-a599-b7ebc56d9563', 'published', now()),

  -- Ácido ursodesoxicólico × Antiácidos (rótulo FDA 7.2 + prontuário)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'acido_ursodesoxicolico'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'acido_ursodesoxicolico'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Ácido ursodesoxicólico + antiácidos: os antiácidos com alumínio reduzem a absorção do ursodesoxicólico — separar as tomas.',
   'Ursodeoxycholic acid + antacids: aluminium-containing antacids reduce ursodiol absorption — separate doses.',
   'O rótulo FDA do ursodiol documenta: "Aluminum-based Antacids: May interfere with the action of ursodiol tablets by reducing its absorption" (7.2), e o Prontuário Terapêutico regista a interação com o hidróxido de alumínio na monografia do ácido ursodesoxicólico (6.9.1). A adsorção aos catiões de alumínio reduz a biodisponibilidade oral do ursodesoxicólico.',
   'The FDA ursodiol label documents: "Aluminum-based Antacids: May interfere with the action of ursodiol tablets by reducing its absorption" (7.2), and the Prontuário Terapêutico records the interaction with aluminium hydroxide in the ursodeoxycholic acid monograph (6.9.1). Adsorption to aluminium cations reduces the oral bioavailability of ursodiol.',
   'Separar a toma do ácido ursodesoxicólico dos antiácidos por pelo menos 2 horas.',
   'Separate ursodeoxycholic acid from antacids by at least 2 hours.',
   'Avaliar a resposta clínica durante a associação.',
   'Assess clinical response during the combination.',
   'Falta de resposta ao tratamento com toma simultânea de antiácidos.',
   'Lack of response with simultaneous antacid intake.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ursodiol (BLUEPOINT LABORATORIES), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a3c98080-0a4d-4a93-8dcb-02ab8533050b ; Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Ácido ursodesoxicólico, 6.9.1',
   'DailyMed/FDA (NIH/NLM) — approved Ursodiol label (BLUEPOINT LABORATORIES), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a3c98080-0a4d-4a93-8dcb-02ab8533050b ; Prontuário Terapêutico do INFARMED (11th ed., 2012) — Ursodeoxycholic acid, 6.9.1', 'published', now()),

  -- Ipratrópio × Tiotrópio (rótulo FDA 7.1/7.2 — anticolinérgico aditivo)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'ipratropio'),
        (SELECT id FROM public.drugs WHERE slug = 'tiotropio')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'ipratropio'),
            (SELECT id FROM public.drugs WHERE slug = 'tiotropio')),
   'moderate',
   'Ipratrópio + tiotrópio: efeito anticolinérgico aditivo — evitar a associação de anticolinérgicos.',
   'Ipratropium + tiotropium: additive anticholinergic effect — avoid combining anticholinergics.',
   'Os rótulos FDA do ipratrópio (secção 7.1) e do tiotrópio (secção 7.2) documentam: "Anticholinergics: May interact additively with concomitantly used anticholinergic medications. Avoid administration with other anticholinergic-containing drugs". A associação de dois anticolinérgicos inalados aumenta o risco de efeitos sistémicos anticolinérgicos (boca seca, retenção urinária, glaucoma de ângulo fechado, obstipação) sem benefício broncodilatador adicional comprovado.',
   'The FDA labels of ipratropium (section 7.1) and tiotropium (section 7.2) document: "Anticholinergics: May interact additively with concomitantly used anticholinergic medications. Avoid administration with other anticholinergic-containing drugs". Combining two inhaled anticholinergics increases the risk of systemic anticholinergic effects (dry mouth, urinary retention, angle-closure glaucoma, constipation) without proven additional bronchodilator benefit.',
   'Evitar a associação de dois anticolinérgicos inalados (ipratrópio + tiotrópio); optar pela monoterapia com o mais adequado.',
   'Avoid combining two inhaled anticholinergics (ipratropium + tiotropium); choose monotherapy with the most appropriate agent.',
   'Se inevitável, vigiar boca seca, retenção urinária, obstipação e alterações visuais.',
   'If unavoidable, monitor for dry mouth, urinary retention, constipation and visual changes.',
   'Retenção urinária aguda, glaucoma agudo ou taquicardia com a associação.',
   'Acute urinary retention, acute glaucoma or tachycardia with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Ipratrópio (ARMSTRONG), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=133cc2ed-f018-4295-b84e-b24382299360 ; rótulo aprovado Tiotrópio (LUPIN), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=496b38ee-45b6-4bb2-a35e-9023c3b73719',
   'DailyMed/FDA (NIH/NLM) — approved Ipratropium label (ARMSTRONG), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=133cc2ed-f018-4295-b84e-b24382299360 ; approved Tiotropium label (LUPIN), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=496b38ee-45b6-4bb2-a35e-9023c3b73719', 'published', now()),

  -- Cefalexina × Metformina (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefalexina'),
        (SELECT id FROM public.drugs WHERE slug = 'metformina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefalexina'),
            (SELECT id FROM public.drugs WHERE slug = 'metformina')),
   'moderate',
   'Cefalexina + metformina: a cefalexina aumenta as concentrações de metformina — vigiar hipoglicemia.',
   'Cephalexin + metformin: cephalexin increases metformin concentrations — monitor for hypoglycaemia.',
   'O rótulo FDA da cefalexina documenta: "Metformin: increased metformin concentrations. Monitor for hypoglycemia" (7.1). A cefalexina compete com a metformina pela secreção tubular renal (transportador OCT2), reduzindo a sua eliminação e aumentando a exposição sistémica da metformina.',
   'The FDA cephalexin label documents: "Metformin: increased metformin concentrations. Monitor for hypoglycemia" (7.1). Cephalexin competes with metformin for renal tubular secretion (OCT2 transporter), reducing its elimination and increasing metformin systemic exposure.',
   'Vigiar sinais de hipoglicemia em doentes diabéticos durante a antibioterapia com cefalexina.',
   'Monitor for signs of hypoglycaemia in diabetic patients during cephalexin antibiotic therapy.',
   'Monitorizar a glicemia e os sintomas de hipoglicemia durante a associação.',
   'Monitor blood glucose and hypoglycaemia symptoms during the combination.',
   'Hipoglicemia sintomática (sudorese, tremor, confusão) em doente diabético a tomar cefalexina.',
   'Symptomatic hypoglycaemia (sweating, tremor, confusion) in a diabetic patient taking cephalexin.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina (PREFERRED PHARMACEUTICALS), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=553485f8-890d-4929-a6bb-905221cf411d ; rótulo aprovado Metformina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341',
   'DailyMed/FDA (NIH/NLM) — approved Cephalexin label (PREFERRED PHARMACEUTICALS), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=553485f8-890d-4929-a6bb-905221cf411d ; approved Metformin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341', 'published', now()),

  -- Cefalexina × Probenecida (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefalexina'),
        (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefalexina'),
            (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   'moderate',
   'Cefalexina + probenecida: a probenecida inibe a secreção tubular da cefalexina — associação não recomendada.',
   'Cephalexin + probenecid: probenecid inhibits cephalexin tubular secretion — combination not recommended.',
   'O rótulo FDA da cefalexina documenta: "Probenecid - The renal excretion of cephalexin is inhibited by probenecid. Co-administration of probenecid with cephalexin is not recommended" (7.2). A probenecida bloqueia a secreção tubular renal dos beta-lactâmicos, elevando e prolongando as concentrações séricas da cefalexina (risco de toxicidade/efeitos adversos dose-dependentes).',
   'The FDA cephalexin label documents: "Probenecid - The renal excretion of cephalexin is inhibited by probenecid. Co-administration of probenecid with cephalexin is not recommended" (7.2). Probenecid blocks the renal tubular secretion of beta-lactams, raising and prolonging serum cephalexin concentrations (risk of dose-dependent toxicity/adverse effects).',
   'Evitar a associação; se a probenecida for essencial, considerar redução da dose ou intervalo da cefalexina.',
   'Avoid the combination; if probenecid is essential, consider reducing the cephalexin dose or extending the interval.',
   'Vigiar sinais de toxicidade (neurotoxicidade, diarreia, reações cutâneas) se a associação for usada.',
   'Monitor for signs of toxicity (neurotoxicity, diarrhoea, skin reactions) if the combination is used.',
   'Neurotoxicidade (confusão, mioclonias) ou efeitos adversos aumentados com a associação.',
   'Neurotoxicity (confusion, myoclonus) or increased adverse effects with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefalexina (PREFERRED PHARMACEUTICALS), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=553485f8-890d-4929-a6bb-905221cf411d ; rótulo aprovado Probenecida (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d',
   'DailyMed/FDA (NIH/NLM) — approved Cephalexin label (PREFERRED PHARMACEUTICALS), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=553485f8-890d-4929-a6bb-905221cf411d ; approved Probenecid label (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d', 'published', now()),

  -- Cefazolina × Probenecida (rótulo FDA 7)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefazolina'),
        (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefazolina'),
            (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   'moderate',
   'Cefazolina + probenecida: a probenecida diminui a secreção tubular da cefazolina — associação não recomendada.',
   'Cefazolin + probenecid: probenecid decreases cefazolin tubular secretion — combination not recommended.',
   'O rótulo FDA da cefazolina documenta: "Probenecid may decrease renal tubular secretion of cephalosporins when used concurrently, resulting in increased and more prolonged cephalosporin blood levels. Co-administration of probenecid with Cefazolin is not recommended" (7). O mecanismo é idêntico ao das outras cefalosporinas — bloqueio da secreção tubular renal.',
   'The FDA cefazolin label documents: "Probenecid may decrease renal tubular secretion of cephalosporins when used concurrently, resulting in increased and more prolonged cephalosporin blood levels. Co-administration of probenecid with Cefazolin is not recommended" (7). The mechanism is identical to other cephalosporins — blockade of renal tubular secretion.',
   'Evitar a associação; se a probenecida for essencial, considerar redução da dose da cefazolina.',
   'Avoid the combination; if probenecid is essential, consider reducing the cefazolin dose.',
   'Vigiar sinais de toxicidade se a associação for usada.',
   'Monitor for signs of toxicity if the combination is used.',
   'Efeitos adversos aumentados ou neurotoxicidade com a associação.',
   'Increased adverse effects or neurotoxicity with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefazolina (MEDICAL PURCHASING SOLUTIONS), secção 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=79787707-c84f-f229-e053-2a91aa0a1f16 ; rótulo aprovado Probenecida (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d',
   'DailyMed/FDA (NIH/NLM) — approved Cefazolin label (MEDICAL PURCHASING SOLUTIONS), section 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=79787707-c84f-f229-e053-2a91aa0a1f16 ; approved Probenecid label (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d', 'published', now()),

  -- Cefepima × Gentamicina (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
        (SELECT id FROM public.drugs WHERE slug = 'gentamicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
            (SELECT id FROM public.drugs WHERE slug = 'gentamicina')),
   'moderate',
   'Cefepima + gentamicina: risco aumentado de nefrotoxicidade e ototoxicidade — monitorizar a função renal.',
   'Cefepime + gentamicin: increased risk of nephrotoxicity and ototoxicity — monitor renal function.',
   'O rótulo FDA da cefepima documenta: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). A associação de uma cefalosporina de 4ª geração com um aminoglicosídeo é comum na terapêutica empírica de infeções graves, mas o risco renal e auditivo aditivo exige monitorização, especialmente no idoso e no doente renal.',
   'The FDA cefepime label documents: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). Combining a fourth-generation cephalosporin with an aminoglycoside is common in empirical therapy of severe infections, but the additive renal and auditory risk requires monitoring, especially in the elderly and renally impaired.',
   'Monitorizar a função renal (creatinina, débito urinário) e vigiar ototoxicidade (tinitus, hipoacusia) durante a associação.',
   'Monitor renal function (creatinine, urine output) and watch for ototoxicity (tinnitus, hearing loss) during the combination.',
   'Vigiar níveis séricos do aminoglicosídeo quando aplicável e sintomas vestibulares/auditivos.',
   'Monitor aminoglycoside serum levels when applicable and vestibular/auditory symptoms.',
   'Aumento da creatinina, oligúria, tinitus ou hipoacusia durante a associação.',
   'Rising creatinine, oliguria, tinnitus or hearing loss during the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefepima (WG CRITICAL CARE), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; rótulo aprovado Gentamicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=441b6232-bb60-40ad-85ec-7c41ba43fd5f',
   'DailyMed/FDA (NIH/NLM) — approved Cefepime label (WG CRITICAL CARE), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; approved Gentamicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=441b6232-bb60-40ad-85ec-7c41ba43fd5f', 'published', now()),

  -- Cefepima × Amicacina (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
        (SELECT id FROM public.drugs WHERE slug = 'amicacina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
            (SELECT id FROM public.drugs WHERE slug = 'amicacina')),
   'moderate',
   'Cefepima + amicacina: risco aumentado de nefrotoxicidade e ototoxicidade — monitorizar a função renal.',
   'Cefepime + amikacin: increased risk of nephrotoxicity and ototoxicity — monitor renal function.',
   'O rótulo FDA da cefepima documenta a classe: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). A amicacina, aminoglicosídeo de largo espectro, associa-se à cefepima em regimes empíricos de infeções graves — o risco renal e auditivo é aditivo.',
   'The FDA cefepime label documents the class: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). Amikacin, a broad-spectrum aminoglycoside, is combined with cefepime in empirical regimens for severe infections — the renal and auditory risk is additive.',
   'Monitorizar a função renal e vigiar ototoxicidade durante a associação.',
   'Monitor renal function and watch for ototoxicity during the combination.',
   'Vigiar níveis séricos da amicacina quando aplicável.',
   'Monitor amikacin serum levels when applicable.',
   'Aumento da creatinina, oligúria, tinitus ou hipoacusia durante a associação.',
   'Rising creatinine, oliguria, tinnitus or hearing loss during the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefepima (WG CRITICAL CARE), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; rótulo aprovado Amicacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890',
   'DailyMed/FDA (NIH/NLM) — approved Cefepime label (WG CRITICAL CARE), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; approved Amikacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890', 'published', now()),

  -- Cefepima × Tobramicina (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
        (SELECT id FROM public.drugs WHERE slug = 'tobramicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
            (SELECT id FROM public.drugs WHERE slug = 'tobramicina')),
   'moderate',
   'Cefepima + tobramicina: risco aumentado de nefrotoxicidade e ototoxicidade — monitorizar a função renal.',
   'Cefepime + tobramycin: increased risk of nephrotoxicity and ototoxicity — monitor renal function.',
   'O rótulo FDA da cefepima documenta a classe: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). A tobramicina, usada sobretudo contra Pseudomonas, associa-se à cefepima em infeções graves — risco renal e auditivo aditivo.',
   'The FDA cefepime label documents the class: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). Tobramycin, used mainly against Pseudomonas, is combined with cefepime in severe infections — additive renal and auditory risk.',
   'Monitorizar a função renal e vigiar ototoxicidade durante a associação.',
   'Monitor renal function and watch for ototoxicity during the combination.',
   'Vigiar níveis séricos da tobramicina quando aplicável.',
   'Monitor tobramycin serum levels when applicable.',
   'Aumento da creatinina, oligúria, tinitus ou hipoacusia durante a associação.',
   'Rising creatinine, oliguria, tinnitus or hearing loss during the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefepima (WG CRITICAL CARE), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; rótulo aprovado Tobramicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4751a4f-c9c1-60c5-e053-2995a90aeba9',
   'DailyMed/FDA (NIH/NLM) — approved Cefepime label (WG CRITICAL CARE), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; approved Tobramycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4751a4f-c9c1-60c5-e053-2995a90aeba9', 'published', now()),

  -- Cefepima × Estreptomicina (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
        (SELECT id FROM public.drugs WHERE slug = 'estreptomicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
            (SELECT id FROM public.drugs WHERE slug = 'estreptomicina')),
   'moderate',
   'Cefepima + estreptomicina: risco aumentado de nefrotoxicidade e ototoxicidade — monitorizar a função renal.',
   'Cefepime + streptomycin: increased risk of nephrotoxicity and ototoxicity — monitor renal function.',
   'O rótulo FDA da cefepima documenta a classe: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). A estreptomicina é o aminoglicosídeo clássico — a associação com cefepima (ex.: em endocardite por Streptococcus) tem risco renal e auditivo aditivo.',
   'The FDA cefepime label documents the class: "Aminoglycosides: increased potential of nephrotoxicity and ototoxicity. Monitor renal function" (7.2). Streptomycin is the classic aminoglycoside — combining with cefepime (e.g., in Streptococcus endocarditis) carries additive renal and auditory risk.',
   'Monitorizar a função renal e vigiar ototoxicidade durante a associação.',
   'Monitor renal function and watch for ototoxicity during the combination.',
   'Vigiar níveis séricos da estreptomicina quando aplicável.',
   'Monitor streptomycin serum levels when applicable.',
   'Aumento da creatinina, oligúria, tinitus ou hipoacusia durante a associação.',
   'Rising creatinine, oliguria, tinnitus or hearing loss during the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefepima (WG CRITICAL CARE), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; rótulo aprovado Estreptomicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78982c98-7866-49f1-989f-a289c4242358',
   'DailyMed/FDA (NIH/NLM) — approved Cefepime label (WG CRITICAL CARE), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; approved Streptomycin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78982c98-7866-49f1-989f-a289c4242358', 'published', now()),

  -- Cefepima × Furosemida (rótulo FDA 7.3)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
        (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefepima'),
            (SELECT id FROM public.drugs WHERE slug = 'furosemida')),
   'moderate',
   'Cefepima + furosemida: nefrotoxicidade reportada com diuréticos potentes — monitorizar a função renal.',
   'Cefepime + furosemide: nephrotoxicity reported with potent diuretics — monitor renal function.',
   'O rótulo FDA da cefepima documenta: "Diuretics: nephrotoxicity has been reported following concomitant administration of other cephalosporins with potent diuretics such as furosemide. Monitor renal function" (7.3). O mecanismo é multifatorial (depleção volémica, interferência na autorregulação renal) e relevante sobretudo no doente idoso e no internado.',
   'The FDA cefepime label documents: "Diuretics: nephrotoxicity has been reported following concomitant administration of other cephalosporins with potent diuretics such as furosemide. Monitor renal function" (7.3). The mechanism is multifactorial (volume depletion, interference with renal autoregulation) and relevant mainly in the elderly and inpatients.',
   'Monitorizar a função renal (creatinina, débito urinário) durante a associação, sobretudo no idoso.',
   'Monitor renal function (creatinine, urine output) during the combination, especially in the elderly.',
   'Vigiar eletrólitos e hidratação do doente.',
   'Monitor electrolytes and patient hydration.',
   'Aumento da creatinina ou oligúria em doente a receber cefepima e furosemida.',
   'Rising creatinine or oliguria in a patient receiving cefepime and furosemide.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefepima (WG CRITICAL CARE), secção 7.3: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; rótulo aprovado Furosemida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4',
   'DailyMed/FDA (NIH/NLM) — approved Cefepime label (WG CRITICAL CARE), section 7.3: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5fd857e5-591f-44ca-80cf-fd903660b03c ; approved Furosemide label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5886e233-b2da-4acb-be05-9bf40fb8e7f4', 'published', now()),

  -- Cefotaxima × Probenecida (prontuário 1.1.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefotaxima'),
        (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefotaxima'),
            (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   'moderate',
   'Cefotaxima + probenecida: a probenecida inibe a secreção tubular das cefalosporinas — eleva as concentrações séricas.',
   'Cefotaxime + probenecid: probenecid inhibits cephalosporin tubular secretion — raises serum concentrations.',
   'O Prontuário Terapêutico documenta na introdução das cefalosporinas (1.1.2): "A probenecida inibe competitivamente a secreção tubular da maioria das cefalosporinas causando um aumento significativo das suas concentrações séricas". A cefotaxima é excretada por secreção tubular — a probenecida eleva e prolonga as suas concentrações.',
   'The Prontuário Terapêutico documents in the cephalosporin introduction (1.1.2): "Probenecid competitively inhibits the tubular secretion of most cephalosporins, causing a significant increase in their serum concentrations". Cefotaxime is excreted by tubular secretion — probenecid raises and prolongs its concentrations.',
   'Evitar a associação; se a probenecida for essencial, considerar redução da dose da cefotaxima.',
   'Avoid the combination; if probenecid is essential, consider reducing the cefotaxime dose.',
   'Vigiar sinais de toxicidade se a associação for usada.',
   'Monitor for signs of toxicity if the combination is used.',
   'Efeitos adversos aumentados ou neurotoxicidade com a associação.',
   'Increased adverse effects or neurotoxicity with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Cefalosporinas, 1.1.2 ; rótulo aprovado Probenecida (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Cephalosporins, 1.1.2 ; approved Probenecid label (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d', 'published', now()),

  -- Cefuroxima × Levonorgestrel (rótulo FDA 7.1 — contracetivos orais)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefuroxima'),
        (SELECT id FROM public.drugs WHERE slug = 'levonorgestrel')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefuroxima'),
            (SELECT id FROM public.drugs WHERE slug = 'levonorgestrel')),
   'moderate',
   'Cefuroxima + contracetivos orais: efeitos na flora intestinal podem reduzir a eficácia contracetiva.',
   'Cefuroxime + oral contraceptives: effects on gut flora may reduce contraceptive efficacy.',
   'O rótulo FDA da cefuroxima documenta: "Oral Contraceptives: Effects on gut flora may lower estrogen reabsorption and reduce efficacy of oral contraceptives" (7.1). Os antibióticos de largo espectro podem alterar a flora intestinal e reduzir a reabsorção de estrogénios, comprometendo a fiabilidade contracetiva.',
   'The FDA cefuroxime label documents: "Oral Contraceptives: Effects on gut flora may lower estrogen reabsorption and reduce efficacy of oral contraceptives" (7.1). Broad-spectrum antibiotics may alter gut flora and reduce oestrogen reabsorption, compromising contraceptive reliability.',
   'Advertir as utilizadoras de contracetivos orais para o risco reduzido de eficácia durante e até 7 dias após a antibioterapia; considerar método de barreira adicional.',
   'Advise users of oral contraceptives about the reduced efficacy risk during and up to 7 days after antibiotic therapy; consider an additional barrier method.',
   'Vigiar spotting/hemorragia intermenstrual como sinal de possível perda de eficácia.',
   'Watch for spotting/breakthrough bleeding as a sign of possible loss of efficacy.',
   'Hemorragia intermenstrual ou gravidez não planeada durante antibioterapia com cefuroxima.',
   'Breakthrough bleeding or unplanned pregnancy during cefuroxime antibiotic therapy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima axetil (WOCKHARDT), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=708b7a4d-ba1f-47b5-be4d-a01c2a7017ff ; rótulo aprovado Levonorgestrel: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4',
   'DailyMed/FDA (NIH/NLM) — approved Cefuroxime axetil label (WOCKHARDT), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=708b7a4d-ba1f-47b5-be4d-a01c2a7017ff ; approved Levonorgestrel label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07567b80-d8a1-41c0-95e4-33afa584bbc4', 'published', now()),

  -- Cefuroxima × Antiácidos (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefuroxima'),
        (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefuroxima'),
            (SELECT id FROM public.drugs WHERE slug = 'antiacidos')),
   'moderate',
   'Cefuroxima + antiácidos: os antiácidos reduzem a biodisponibilidade da cefuroxima axetil oral.',
   'Cefuroxime + antacids: antacids reduce the bioavailability of oral cefuroxime axetil.',
   'O rótulo FDA da cefuroxima documenta: "Drugs that reduce gastric acidity may lower the bioavailability of cefuroxime axetil tablets" (7.2). A cefuroxima axetil oral necessita de pH gástrico ácido para a sua absorção; os antiácidos reduzem essa absorção e podem comprometer a eficácia antibiótica.',
   'The FDA cefuroxime label documents: "Drugs that reduce gastric acidity may lower the bioavailability of cefuroxime axetil tablets" (7.2). Oral cefuroxime axetil requires an acidic gastric pH for absorption; antacids reduce that absorption and may compromise antibiotic efficacy.',
   'Separar a toma da cefuroxima oral dos antiácidos por 2-3 horas.',
   'Separate oral cefuroxime from antacids by 2-3 hours.',
   'Avaliar a resposta clínica à antibioterapia durante a associação.',
   'Assess clinical response to antibiotic therapy during the combination.',
   'Falência terapêutica da antibioterapia com toma simultânea de antiácidos.',
   'Therapeutic failure of antibiotic therapy with simultaneous antacid intake.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima axetil (WOCKHARDT), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=708b7a4d-ba1f-47b5-be4d-a01c2a7017ff ; rótulo aprovado Antiácidos: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a13ac81-0c63-48c1-bbb0-f6e67f97b896',
   'DailyMed/FDA (NIH/NLM) — approved Cefuroxime axetil label (WOCKHARDT), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=708b7a4d-ba1f-47b5-be4d-a01c2a7017ff ; approved Antacids label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a13ac81-0c63-48c1-bbb0-f6e67f97b896', 'published', now()),

  -- Cefuroxima × Probenecida (rótulo FDA 7.3)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'cefuroxima'),
        (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'cefuroxima'),
            (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   'moderate',
   'Cefuroxima + probenecida: a probenecida aumenta a exposição sistémica à cefuroxima — associação não recomendada.',
   'Cefuroxime + probenecid: probenecid increases systemic exposure to cefuroxime — combination not recommended.',
   'O rótulo FDA da cefuroxima documenta: "Co-administration with probenecid increases systemic exposure to cefuroxime axetil tablets and is therefore not recommended" (7.3). A probenecida bloqueia a secreção tubular da cefuroxima, elevando as suas concentrações séricas.',
   'The FDA cefuroxime label documents: "Co-administration with probenecid increases systemic exposure to cefuroxime axetil tablets and is therefore not recommended" (7.3). Probenecid blocks cefuroxime tubular secretion, raising its serum concentrations.',
   'Evitar a associação; se a probenecida for essencial, considerar redução da dose da cefuroxima.',
   'Avoid the combination; if probenecid is essential, consider reducing the cefuroxime dose.',
   'Vigiar sinais de toxicidade se a associação for usada.',
   'Monitor for signs of toxicity if the combination is used.',
   'Efeitos adversos aumentados ou neurotoxicidade com a associação.',
   'Increased adverse effects or neurotoxicity with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cefuroxima axetil (WOCKHARDT), secção 7.3: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=708b7a4d-ba1f-47b5-be4d-a01c2a7017ff ; rótulo aprovado Probenecida (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d',
   'DailyMed/FDA (NIH/NLM) — approved Cefuroxime axetil label (WOCKHARDT), section 7.3: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=708b7a4d-ba1f-47b5-be4d-a01c2a7017ff ; approved Probenecid label (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d', 'published', now()),

  -- Etilefrina × Adrenalina (prontuário 3.2.4 — simpaticomimético aditivo)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'etilefrina'),
        (SELECT id FROM public.drugs WHERE slug = 'adrenalina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'etilefrina'),
            (SELECT id FROM public.drugs WHERE slug = 'adrenalina')),
   'moderate',
   'Etilefrina + adrenalina: potenciação do efeito simpaticomimético — risco de arritmias e hipertensão.',
   'Etilefrine + epinephrine: potentiation of sympathomimetic effect — risk of arrhythmias and hypertension.',
   'O Prontuário Terapêutico documenta na monografia da etilefrina (3.2.4): "Pode haver potenciação de efeito se a etilefrina for ministrada simultaneamente com outras substâncias simpaticomiméticas". A adrenalina e a etilefrina são ambas simpaticomiméticas — a associação aditiva aumenta o risco de taquicardia, arritmias e hipertensão.',
   'The Prontuário Terapêutico documents in the etilefrine monograph (3.2.4): "The effect may be potentiated if etilefrine is given simultaneously with other sympathomimetic substances". Epinephrine and etilefrine are both sympathomimetic — the additive combination increases the risk of tachycardia, arrhythmias and hypertension.',
   'Evitar a associação de simpaticomiméticos; se inevitável, monitorizar tensão arterial, frequência cardíaca e ritmo.',
   'Avoid combining sympathomimetics; if unavoidable, monitor blood pressure, heart rate and rhythm.',
   'Vigiar sinais de excesso adrenérgico (palpitações, tremor, dor torácica, arritmias).',
   'Monitor for signs of adrenergic excess (palpitations, tremor, chest pain, arrhythmias).',
   'Taquiarritmia, crise hipertensiva ou dor torácica com a associação.',
   'Tachyarrhythmia, hypertensive crisis or chest pain with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Etilefrina, 3.2.4',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Etilefrine, 3.2.4', 'published', now()),

  -- Etilefrina × Salbutamol (prontuário 3.2.4)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'etilefrina'),
        (SELECT id FROM public.drugs WHERE slug = 'salbutamol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'etilefrina'),
            (SELECT id FROM public.drugs WHERE slug = 'salbutamol')),
   'moderate',
   'Etilefrina + salbutamol: potenciação do efeito simpaticomimético — risco de taquicardia e tremor.',
   'Etilefrine + salbutamol: potentiation of sympathomimetic effect — risk of tachycardia and tremor.',
   'O Prontuário Terapêutico documenta a potenciação entre a etilefrina e outras substâncias simpaticomiméticas (3.2.4). O salbutamol (beta-2 agonista) e a etilefrina têm efeitos simpaticomiméticos aditivos — taquicardia, tremor e possível hipocaliemia.',
   'The Prontuário Terapêutico documents the potentiation between etilefrine and other sympathomimetic substances (3.2.4). Salbutamol (beta-2 agonist) and etilefrine have additive sympathomimetic effects — tachycardia, tremor and possible hypokalaemia.',
   'Monitorizar frequência cardíaca e sintomas adrenérgicos na associação; considerar ajuste de dose.',
   'Monitor heart rate and adrenergic symptoms in the combination; consider dose adjustment.',
   'Vigiar taquicardia, tremor e potássio sérico.',
   'Monitor tachycardia, tremor and serum potassium.',
   'Taquicardia sintomática ou tremor incapacitante com a associação.',
   'Symptomatic tachycardia or disabling tremor with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Etilefrina, 3.2.4',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Etilefrine, 3.2.4', 'published', now()),

  -- Famotidina × Cetoconazol (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
        (SELECT id FROM public.drugs WHERE slug = 'cetoconazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
            (SELECT id FROM public.drugs WHERE slug = 'cetoconazol')),
   'moderate',
   'Famotidina + cetoconazol: a famotidina reduz a absorção do cetoconazol (depende do pH gástrico) — separar as tomas.',
   'Famotidine + ketoconazole: famotidine reduces ketoconazole absorption (gastric pH-dependent) — separate doses.',
   'O rótulo FDA da famotidina documenta: "Drugs Dependent on Gastric pH for Absorption: Systemic exposure of the concomitant drug may be significantly reduced leading to loss of efficacy" (7.1). O cetoconazol requer pH gástrico ácido para absorver — a supressão ácida pela famotidina reduz drasticamente a sua biodisponibilidade.',
   'The FDA famotidine label documents: "Drugs Dependent on Gastric pH for Absorption: Systemic exposure of the concomitant drug may be significantly reduced leading to loss of efficacy" (7.1). Ketoconazole requires an acidic gastric pH for absorption — famotidine-induced acid suppression markedly reduces its bioavailability.',
   'Separar as tomas por pelo menos 2 horas; preferir administrar o cetoconazol com bebida ácida; considerar alternativa antifúngica se houver falência.',
   'Separate doses by at least 2 hours; prefer giving ketoconazole with an acidic drink; consider an alternative antifungal if there is failure.',
   'Avaliar a resposta ao tratamento antifúngico durante a associação.',
   'Assess response to antifungal therapy during the combination.',
   'Falência do tratamento antifúngico com toma simultânea de famotidina.',
   'Failure of antifungal treatment with simultaneous famotidine intake.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Famotidina (TEVA), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; rótulo aprovado Cetoconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd0da52b-fc82-4ec9-854c-0d7c52e926fb',
   'DailyMed/FDA (NIH/NLM) — approved Famotidine label (TEVA), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; approved Ketoconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd0da52b-fc82-4ec9-854c-0d7c52e926fb', 'published', now()),

  -- Famotidina × Itraconazol (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
        (SELECT id FROM public.drugs WHERE slug = 'itraconazol')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
            (SELECT id FROM public.drugs WHERE slug = 'itraconazol')),
   'moderate',
   'Famotidina + itraconazol: a famotidina reduz a absorção do itraconazol (depende do pH gástrico) — separar as tomas.',
   'Famotidine + itraconazole: famotidine reduces itraconazole absorption (gastric pH-dependent) — separate doses.',
   'O rótulo FDA da famotidina documenta a classe: "Drugs Dependent on Gastric pH for Absorption: Systemic exposure of the concomitant drug may be significantly reduced leading to loss of efficacy" (7.1). O itraconazol (cápsulas) requer pH ácido — a supressão ácida pela famotidina reduz a sua absorção.',
   'The FDA famotidine label documents the class: "Drugs Dependent on Gastric pH for Absorption: Systemic exposure of the concomitant drug may be significantly reduced leading to loss of efficacy" (7.1). Itraconazole (capsules) requires an acidic pH — famotidine acid suppression reduces its absorption.',
   'Separar as tomas por pelo menos 2 horas; considerar solução oral de itraconazol (menos dependente do pH) se necessário.',
   'Separate doses by at least 2 hours; consider itraconazole oral solution (less pH-dependent) if needed.',
   'Avaliar a resposta ao tratamento antifúngico durante a associação.',
   'Assess response to antifungal therapy during the combination.',
   'Falência do tratamento antifúngico com toma simultânea de famotidina.',
   'Failure of antifungal treatment with simultaneous famotidine intake.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Famotidina (TEVA), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; rótulo aprovado Itraconazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0',
   'DailyMed/FDA (NIH/NLM) — approved Famotidine label (TEVA), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; approved Itraconazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0', 'published', now()),

  -- Famotidina × Atazanavir (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
        (SELECT id FROM public.drugs WHERE slug = 'atazanavir')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
            (SELECT id FROM public.drugs WHERE slug = 'atazanavir')),
   'moderate',
   'Famotidina + atazanavir: a famotidina reduz a absorção do atazanavir (depende do pH gástrico) — risco de falência virológica.',
   'Famotidine + atazanavir: famotidine reduces atazanavir absorption (gastric pH-dependent) — risk of virological failure.',
   'O rótulo FDA da famotidina documenta a classe dos fármacos dependentes do pH gástrico (7.1). O atazanavir é um inibidor da protease que requer pH ácido para absorver — a supressão ácida pela famotidina reduz significativamente a sua exposição, com risco de falência virológica no VIH.',
   'The FDA famotidine label documents the class of gastric pH-dependent drugs (7.1). Atazanavir is a protease inhibitor that requires an acidic pH for absorption — famotidine acid suppression markedly reduces its exposure, with a risk of virological failure in HIV.',
   'Separar as tomas por pelo menos 10-12 horas quando possível; consultar as recomendações específicas do atazanavir (espaçamento e dose); considerar alternativa.',
   'Separate doses by at least 10-12 hours when possible; consult atazanavir-specific recommendations (spacing and dose); consider an alternative.',
   'Monitorizar a carga viral do VIH durante a associação prolongada.',
   'Monitor HIV viral load during prolonged combination.',
   'Falência virológica ou aumento da carga viral em doente com VIH a tomar famotidina e atazanavir.',
   'Virological failure or rising viral load in an HIV patient taking famotidine and atazanavir.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Famotidina (TEVA), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; rótulo aprovado Atazanavir: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8',
   'DailyMed/FDA (NIH/NLM) — approved Famotidine label (TEVA), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; approved Atazanavir label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8', 'published', now()),

  -- Famotidina × Tizanidina (rótulo FDA 7.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
        (SELECT id FROM public.drugs WHERE slug = 'tizanidina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'famotidina'),
            (SELECT id FROM public.drugs WHERE slug = 'tizanidina')),
   'moderate',
   'Famotidina + tizanidina: a famotidina pode aumentar substancialmente as concentrações de tizanidina (CYP1A2) — evitar, se possível.',
   'Famotidine + tizanidine: famotidine may substantially increase tizanidine concentrations (CYP1A2) — avoid if possible.',
   'O rótulo FDA da famotidina documenta: "Tizanidine (CYP1A2) Substrate: Potential for substantial increases in blood concentrations of tizanidine resulting in hypotension, bradycardia or excessive drowsiness; avoid concomitant use, if possible" (7.2). A famotidina inibe o CYP1A2, reduzindo o metabolismo da tizanidina.',
   'The FDA famotidine label documents: "Tizanidine (CYP1A2) Substrate: Potential for substantial increases in blood concentrations of tizanidine resulting in hypotension, bradycardia or excessive drowsiness; avoid concomitant use, if possible" (7.2). Famotidine inhibits CYP1A2, reducing tizanidine metabolism.',
   'Evitar a associação; se inevitável, reduzir a dose de tizanidina e vigiar hipotensão, bradicardia e sedação.',
   'Avoid the combination; if unavoidable, reduce the tizanidine dose and monitor for hypotension, bradycardia and sedation.',
   'Monitorizar tensão arterial, frequência cardíaca e nível de sedação no início da associação.',
   'Monitor blood pressure, heart rate and level of sedation at the start of the combination.',
   'Hipotensão ortostática, bradicardia ou sedação excessiva com a associação.',
   'Orthostatic hypotension, bradycardia or excessive sedation with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Famotidina (TEVA), secção 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; rótulo aprovado Tizanidina (PREFERRED PHARMACEUTICALS): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8d0b2b22-e1df-4ad5-92e6-f9a369108e4b',
   'DailyMed/FDA (NIH/NLM) — approved Famotidine label (TEVA), section 7.2: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4c6f4f9e-f3f5-4ecf-9f40-887e037e8847 ; approved Tizanidine label (PREFERRED PHARMACEUTICALS): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8d0b2b22-e1df-4ad5-92e6-f9a369108e4b', 'published', now()),

  -- Fenoximetilpenicilina × Probenecida (prontuário 1.1.1.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fenoximetilpenicilina'),
        (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fenoximetilpenicilina'),
            (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   'moderate',
   'Fenoximetilpenicilina + probenecida: a probenecida inibe a secreção tubular das penicilinas — eleva as concentrações séricas.',
   'Phenoxymethylpenicillin + probenecid: probenecid inhibits penicillin tubular secretion — raises serum concentrations.',
   'O Prontuário Terapêutico documenta na monografia da fenoximetilpenicilina (1.1.1.1): "A probenecida inibe competitivamente a secreção tubular das penicilinas causando um aumento significativo das suas concentrações séricas". Historicamente a probenecida era usada como adjuvante para prolongar os níveis das penicilinas — hoje a associação não é recomendada por rotina.',
   'The Prontuário Terapêutico documents in the phenoxymethylpenicillin monograph (1.1.1.1): "Probenecid competitively inhibits the tubular secretion of penicillins, causing a significant increase in their serum concentrations". Historically probenecid was used as an adjuvant to prolong penicillin levels — today the combination is not routinely recommended.',
   'Evitar a associação por rotina; se a probenecida for usada como adjuvante (ex.: indicações específicas), monitorizar toxicidade.',
   'Avoid routine combination; if probenecid is used as an adjuvant (e.g., specific indications), monitor for toxicity.',
   'Vigiar sinais de toxicidade se a associação for usada.',
   'Monitor for signs of toxicity if the combination is used.',
   'Efeitos adversos aumentados com a associação.',
   'Increased adverse effects with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Fenoximetilpenicilina, 1.1.1.1 ; rótulo aprovado Probenecida (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Phenoxymethylpenicillin, 1.1.1.1 ; approved Probenecid label (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d', 'published', now()),

  -- Fondaparinux × Warfarina (rótulo FDA 7)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fondaparinux'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fondaparinux'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'Fondaparinux + warfarina: risco aumentado de hemorragia — monitorizar de perto se a associação for necessária.',
   'Fondaparinux + warfarin: increased bleeding risk — monitor closely if the combination is needed.',
   'O rótulo FDA do fondaparinux documenta: "Agents that may enhance the risk of hemorrhage should be discontinued prior to initiation of therapy with fondaparinux sodium unless these agents are essential. If co-administration is necessary, monitor patients closely for hemorrhage" (7). A warfarina, anticoagulante oral, aumenta o risco hemorrágico aditivo com o fondaparinux.',
   'The FDA fondaparinux label documents: "Agents that may enhance the risk of hemorrhage should be discontinued prior to initiation of therapy with fondaparinux sodium unless these agents are essential. If co-administration is necessary, monitor patients closely for hemorrhage" (7). Warfarin, an oral anticoagulant, adds bleeding risk with fondaparinux.',
   'Suspender os agentes que aumentam o risco hemorrágico antes de iniciar o fondaparinux, salvo se essenciais; se a associação for necessária, monitorizar de perto.',
   'Discontinue agents that increase bleeding risk before starting fondaparinux unless essential; if the combination is necessary, monitor closely.',
   'Monitorizar hemorragias (clínicas e laboratoriais — hemoglobina, plaquetas) e o INR durante a sobreposição.',
   'Monitor for bleeding (clinical and laboratory — haemoglobin, platelets) and INR during overlap.',
   'Hemorragia ativa, queda da hemoglobina ou equimoses espontâneas durante a associação.',
   'Active bleeding, falling haemoglobin or spontaneous bruising during the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fondaparinux (ZYDUS), secção 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2 ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'DailyMed/FDA (NIH/NLM) — approved Fondaparinux label (ZYDUS), section 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2 ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057', 'published', now()),

  -- Fondaparinux × Aspirina (rótulo FDA 7)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fondaparinux'),
        (SELECT id FROM public.drugs WHERE slug = 'aspirina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fondaparinux'),
            (SELECT id FROM public.drugs WHERE slug = 'aspirina')),
   'moderate',
   'Fondaparinux + aspirina: risco aumentado de hemorragia — monitorizar de perto se a associação for necessária.',
   'Fondaparinux + aspirin: increased bleeding risk — monitor closely if the combination is needed.',
   'O rótulo FDA do fondaparinux documenta que os inibidores plaquetários (ácido acetilsalicílico) não afetam a farmacocinética do fondaparinux, mas "Agents that may enhance the risk of hemorrhage should be discontinued prior to initiation of therapy with fondaparinux sodium unless these agents are essential" (7). A aspirina, antiagregante plaquetário, aumenta o risco hemorrágico aditivo.',
   'The FDA fondaparinux label documents that platelet inhibitors (acetylsalicylic acid) do not affect fondaparinux pharmacokinetics, but "Agents that may enhance the risk of hemorrhage should be discontinued prior to initiation of therapy with fondaparinux sodium unless these agents are essential" (7). Aspirin, a platelet inhibitor, adds bleeding risk.',
   'Suspender a aspirina antes de iniciar o fondaparinux, salvo se essencial; se a associação for necessária, monitorizar de perto.',
   'Discontinue aspirin before starting fondaparinux unless essential; if the combination is necessary, monitor closely.',
   'Monitorizar hemorragias (clínicas e laboratoriais) durante a associação.',
   'Monitor for bleeding (clinical and laboratory) during the combination.',
   'Hemorragia ativa ou queda da hemoglobina durante a associação.',
   'Active bleeding or falling haemoglobin during the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fondaparinux (ZYDUS), secção 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2 ; rótulo aprovado Ácido acetilsalicílico: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175',
   'DailyMed/FDA (NIH/NLM) — approved Fondaparinux label (ZYDUS), section 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2 ; approved Acetylsalicylic acid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175', 'published', now()),

  -- Fondaparinux × Diclofenac (rótulo FDA 7 — AINEs)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'fondaparinux'),
        (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'fondaparinux'),
            (SELECT id FROM public.drugs WHERE slug = 'diclofenac')),
   'moderate',
   'Fondaparinux + diclofenac: risco aumentado de hemorragia (AINE) — monitorizar de perto.',
   'Fondaparinux + diclofenac: increased bleeding risk (NSAID) — monitor closely.',
   'O rótulo FDA do fondaparinux documenta que os AINEs (ex.: piroxicam nos estudos) não afetam a farmacocinética do fondaparinux, mas "Agents that may enhance the risk of hemorrhage should be discontinued prior to initiation of therapy with fondaparinux sodium unless these agents are essential" (7). Os AINEs, como o diclofenac, aumentam o risco hemorrágico por inibição plaquetária e irritação gastrointestinal.',
   'The FDA fondaparinux label documents that NSAIDs (e.g., piroxicam in studies) do not affect fondaparinux pharmacokinetics, but "Agents that may enhance the risk of hemorrhage should be discontinued prior to initiation of therapy with fondaparinux sodium unless these agents are essential" (7). NSAIDs such as diclofenac increase bleeding risk through platelet inhibition and gastrointestinal irritation.',
   'Suspender os AINEs antes de iniciar o fondaparinux, salvo se essenciais; se a associação for necessária, monitorizar de perto.',
   'Discontinue NSAIDs before starting fondaparinux unless essential; if the combination is necessary, monitor closely.',
   'Monitorizar hemorragias e sintomas gastrointestinais durante a associação.',
   'Monitor for bleeding and gastrointestinal symptoms during the combination.',
   'Hemorragia ativa, melenas ou dor abdominal com a associação.',
   'Active bleeding, melaena or abdominal pain with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Fondaparinux (ZYDUS), secção 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2 ; rótulo aprovado Diclofenac: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ddd2278b-70be-41ca-8a84-e3fe0f1a1561',
   'DailyMed/FDA (NIH/NLM) — approved Fondaparinux label (ZYDUS), section 7: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2 ; approved Diclofenac label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ddd2278b-70be-41ca-8a84-e3fe0f1a1561', 'published', now()),

  -- Memantina × Dextrometorfano (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
        (SELECT id FROM public.drugs WHERE slug = 'dextrometorfano')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
            (SELECT id FROM public.drugs WHERE slug = 'dextrometorfano')),
   'moderate',
   'Memantina + dextrometorfano: antagonistas NMDA em associação — usar com precaução.',
   'Memantine + dextromethorphan: NMDA antagonists in combination — use with caution.',
   'O rótulo FDA da memantina documenta: "Use with other NMDA antagonists (amantadine, ketamine, and dextromethorphan) has not been systematically evaluated and such use should be approached with caution" (7.1). O dextrometorfano e a memantina são ambos antagonistas NMDA — a associação pode potenciar efeitos adversos do SNC.',
   'The FDA memantine label documents: "Use with other NMDA antagonists (amantadine, ketamine, and dextromethorphan) has not been systematically evaluated and such use should be approached with caution" (7.1). Dextromethorphan and memantine are both NMDA antagonists — the combination may potentiate CNS adverse effects.',
   'Usar com precaução; vigiar sedação, confusão e efeitos no SNC na associação.',
   'Use with caution; monitor sedation, confusion and CNS effects in the combination.',
   'Vigiar alterações do estado mental e sedação.',
   'Monitor mental status changes and sedation.',
   'Sedação excessiva, confusão ou alucinações com a associação.',
   'Excessive sedation, confusion or hallucinations with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Memantina (NAMENDA XR), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=617dcd31-3215-4dd8-9b6e-d888d3bf30f3 ; rótulo aprovado Dextrometorfano: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14',
   'DailyMed/FDA (NIH/NLM) — approved Memantine label (NAMENDA XR), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=617dcd31-3215-4dd8-9b6e-d888d3bf30f3 ; approved Dextromethorphan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d99237c-0b52-0af6-e063-6394a90aba14', 'published', now()),

  -- Memantina × Amantadina (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
        (SELECT id FROM public.drugs WHERE slug = 'amantadina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
            (SELECT id FROM public.drugs WHERE slug = 'amantadina')),
   'moderate',
   'Memantina + amantadina: antagonistas NMDA em associação — usar com precaução.',
   'Memantine + amantadine: NMDA antagonists in combination — use with caution.',
   'O rótulo FDA da memantina documenta: "Use with other NMDA antagonists (amantadine, ketamine, and dextromethorphan) has not been systematically evaluated and such use should be approached with caution" (7.1). A amantadina, usada no Parkinson, partilha o antagonismo NMDA com a memantina — efeitos aditivos possíveis no SNC.',
   'The FDA memantine label documents: "Use with other NMDA antagonists (amantadine, ketamine, and dextromethorphan) has not been systematically evaluated and such use should be approached with caution" (7.1). Amantadine, used in Parkinson disease, shares NMDA antagonism with memantine — possible additive CNS effects.',
   'Usar com precaução; vigiar confusão, alucinações e efeitos no SNC na associação.',
   'Use with caution; monitor confusion, hallucinations and CNS effects in the combination.',
   'Vigiar alterações do estado mental e efeitos extrapiramidais.',
   'Monitor mental status changes and extrapyramidal effects.',
   'Confusão, alucinações ou agravamento dos sintomas parkinsónicos com a associação.',
   'Confusion, hallucinations or worsening of parkinsonian symptoms with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Memantina (NAMENDA XR), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=617dcd31-3215-4dd8-9b6e-d888d3bf30f3 ; rótulo aprovado Amantadina (GOCOVRI): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bee0631-0028-1314-e063-6394a90aaaed',
   'DailyMed/FDA (NIH/NLM) — approved Memantine label (NAMENDA XR), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=617dcd31-3215-4dd8-9b6e-d888d3bf30f3 ; approved Amantadine label (GOCOVRI): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bee0631-0028-1314-e063-6394a90aaaed', 'published', now()),

  -- Memantina × Cetamina (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
        (SELECT id FROM public.drugs WHERE slug = 'cetamina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
            (SELECT id FROM public.drugs WHERE slug = 'cetamina')),
   'moderate',
   'Memantina + cetamina: antagonistas NMDA em associação — usar com precaução (sedação profunda possível).',
   'Memantine + ketamine: NMDA antagonists in combination — use with caution (possible profound sedation).',
   'O rótulo FDA da memantina documenta: "Use with other NMDA antagonists (amantadine, ketamine, and dextromethorphan) has not been systematically evaluated and such use should be approached with caution" (7.1). A cetamina é um antagonista NMDA potente — a associação com memantina pode potenciar efeitos dissociativos e sedativos.',
   'The FDA memantine label documents: "Use with other NMDA antagonists (amantadine, ketamine, and dextromethorphan) has not been systematically evaluated and such use should be approached with caution" (7.1). Ketamine is a potent NMDA antagonist — combining with memantine may potentiate dissociative and sedative effects.',
   'Usar com precaução; vigiar sedação, dissociação e pressão arterial na associação (contexto anestésico).',
   'Use with caution; monitor sedation, dissociation and blood pressure in the combination (anaesthetic setting).',
   'Vigiar nível de consciência e sinais vitais em contexto perioperatório.',
   'Monitor level of consciousness and vital signs in the perioperative setting.',
   'Sedação prolongada, dissociação ou hipertensão com a associação.',
   'Prolonged sedation, dissociation or hypertension with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Memantina (NAMENDA XR), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=617dcd31-3215-4dd8-9b6e-d888d3bf30f3 ; rótulo aprovado Cetamina (KETALAR): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14e8f864-8b8a-4e7e-8439-e510d3107063',
   'DailyMed/FDA (NIH/NLM) — approved Memantine label (NAMENDA XR), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=617dcd31-3215-4dd8-9b6e-d888d3bf30f3 ; approved Ketamine label (KETALAR): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14e8f864-8b8a-4e7e-8439-e510d3107063', 'published', now()),

  -- Memantina × Warfarina (prontuário)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
        (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'memantina'),
            (SELECT id FROM public.drugs WHERE slug = 'warfarina')),
   'moderate',
   'Memantina + warfarina: a memantina pode potenciar o efeito anticoagulante da warfarina — monitorizar o INR.',
   'Memantine + warfarin: memantine may potentiate the anticoagulant effect of warfarin — monitor INR.',
   'O Prontuário Terapêutico documenta na monografia da memantina: "Possibilidade de potenciar o efeito anticoagulante da varfarina". O mecanismo não está totalmente esclarecido — recomenda-se monitorização do INR quando a associação é iniciada ou alterada.',
   'The Prontuário Terapêutico documents in the memantine monograph: "Possibility of potentiating the anticoagulant effect of warfarin". The mechanism is not fully clarified — INR monitoring is recommended when the combination is started or changed.',
   'Monitorizar o INR após iniciar, ajustar ou suspender a memantina em doentes anticoagulados com warfarina.',
   'Monitor INR after starting, adjusting or stopping memantine in patients anticoagulated with warfarin.',
   'Vigiar sinais hemorrágicos (equimoses, gengivorragia, melenas).',
   'Watch for bleeding signs (bruising, gum bleeding, melaena).',
   'INR acima do intervalo-alvo ou hemorragia com a associação.',
   'INR above target range or bleeding with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Memantina ; rótulo aprovado Warfarina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Memantine ; approved Warfarin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=541c9a70-adaf-4ef3-94ba-ad4e70dfa057', 'published', now()),

  -- Montelucaste × Fenobarbital (prontuário 5.1.3.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'montelukast'),
        (SELECT id FROM public.drugs WHERE slug = 'fenobarbital')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'montelukast'),
            (SELECT id FROM public.drugs WHERE slug = 'fenobarbital')),
   'moderate',
   'Montelucaste + fenobarbital: o fenobarbital pode reduzir a eficácia do montelucaste — monitorizar o controlo da asma.',
   'Montelukast + phenobarbital: phenobarbital may reduce montelukast efficacy — monitor asthma control.',
   'O Prontuário Terapêutico documenta as interações do montelucaste com fenobarbital, fenitoína e rifampicina (5.1.3.2). Estes indutores enzimáticos aceleram o metabolismo do montelucaste (CYP3A4/2C9), podendo reduzir as suas concentrações e comprometer o controlo da asma.',
   'The Prontuário Terapêutico documents montelukast interactions with phenobarbital, phenytoin and rifampicin (5.1.3.2). These enzyme inducers accelerate montelukast metabolism (CYP3A4/2C9), potentially reducing its concentrations and compromising asthma control.',
   'Monitorizar o controlo da asma durante a associação; considerar ajuste de dose ou alternativa.',
   'Monitor asthma control during the combination; consider dose adjustment or an alternative.',
   'Avaliar sintomas de asma e função respiratória (PEF) na associação.',
   'Assess asthma symptoms and respiratory function (PEF) in the combination.',
   'Perda de controlo da asma (crise, agravamento dos sintomas) com a associação.',
   'Loss of asthma control (attack, worsening symptoms) with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Montelucaste, 5.1.3.2 ; rótulo aprovado Fenobarbital: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Montelukast, 5.1.3.2 ; approved Phenobarbital label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ef4e97a7-cd18-47a9-a016-2eca5481a87e', 'published', now()),

  -- Montelucaste × Fenitoína (prontuário 5.1.3.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'montelukast'),
        (SELECT id FROM public.drugs WHERE slug = 'fenitoina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'montelukast'),
            (SELECT id FROM public.drugs WHERE slug = 'fenitoina')),
   'moderate',
   'Montelucaste + fenitoína: a fenitoína pode reduzir a eficácia do montelucaste — monitorizar o controlo da asma.',
   'Montelukast + phenytoin: phenytoin may reduce montelukast efficacy — monitor asthma control.',
   'O Prontuário Terapêutico documenta a interação do montelucaste com a fenitoína (5.1.3.2). A fenitoína, indutora do CYP3A4/2C9, acelera o metabolismo do montelucaste e pode reduzir as suas concentrações séricas.',
   'The Prontuário Terapêutico documents the montelukast interaction with phenytoin (5.1.3.2). Phenytoin, a CYP3A4/2C9 inducer, accelerates montelukast metabolism and may reduce its serum concentrations.',
   'Monitorizar o controlo da asma durante a associação.',
   'Monitor asthma control during the combination.',
   'Avaliar sintomas de asma e função respiratória na associação.',
   'Assess asthma symptoms and respiratory function in the combination.',
   'Perda de controlo da asma com a associação.',
   'Loss of asthma control with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Montelucaste, 5.1.3.2 ; rótulo aprovado Fenitoína: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Montelukast, 5.1.3.2 ; approved Phenytoin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7cbd9005-7df2-47ee-adb3-7244c1c69bc3', 'published', now()),

  -- Montelucaste × Rifampicina (prontuário 5.1.3.2)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'montelukast'),
        (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'montelukast'),
            (SELECT id FROM public.drugs WHERE slug = 'rifampicina')),
   'moderate',
   'Montelucaste + rifampicina: a rifampicina pode reduzir a eficácia do montelucaste — monitorizar o controlo da asma.',
   'Montelukast + rifampicin: rifampicin may reduce montelukast efficacy — monitor asthma control.',
   'O Prontuário Terapêutico documenta a interação do montelucaste com a rifampicina (5.1.3.2). A rifampicina, potente indutora do CYP3A4, acelera o metabolismo do montelucaste e pode reduzir significativamente as suas concentrações.',
   'The Prontuário Terapêutico documents the montelukast interaction with rifampicin (5.1.3.2). Rifampicin, a potent CYP3A4 inducer, accelerates montelukast metabolism and may significantly reduce its concentrations.',
   'Monitorizar o controlo da asma durante a associação; considerar ajuste de dose ou alternativa.',
   'Monitor asthma control during the combination; consider dose adjustment or an alternative.',
   'Avaliar sintomas de asma e função respiratória na associação.',
   'Assess asthma symptoms and respiratory function in the combination.',
   'Perda de controlo da asma com a associação.',
   'Loss of asthma control with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Montelucaste, 5.1.3.2 ; rótulo aprovado Rifampicina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Montelukast, 5.1.3.2 ; approved Rifampicin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b389b1a3-672f-47e3-916c-4a9c044b211b', 'published', now()),

  -- Pirazinamida × Isoniazida (prontuário 1.1.12)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'pirazinamida'),
        (SELECT id FROM public.drugs WHERE slug = 'isoniazida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'pirazinamida'),
            (SELECT id FROM public.drugs WHERE slug = 'isoniazida')),
   'moderate',
   'Pirazinamida + isoniazida: risco aumentado de hepatotoxicidade — monitorizar a função hepática.',
   'Pyrazinamide + isoniazid: increased risk of hepatotoxicity — monitor liver function.',
   'O Prontuário Terapêutico documenta na monografia da pirazinamida (1.1.12): "A co-administração de pirazinamida e isoniazida aumenta o risco de desenvolvimento de hepatotoxicidade". Ambos os fármacos do esquema antituberculoso são hepatotóxicos — a associação aditiva exige vigilância hepática.',
   'The Prontuário Terapêutico documents in the pyrazinamide monograph (1.1.12): "Co-administration of pyrazinamide and isoniazid increases the risk of developing hepatotoxicity". Both drugs of the tuberculosis regimen are hepatotoxic — the additive combination requires hepatic surveillance.',
   'Monitorizar a função hepática (transaminases, bilirrubina) e sintomas de hepatite (náuseas, icterícia, fadiga) durante o esquema antituberculoso.',
   'Monitor liver function (transaminases, bilirubin) and hepatitis symptoms (nausea, jaundice, fatigue) during the tuberculosis regimen.',
   'Vigiar transaminases no início e periodicamente; suspender se sinais de lesão hepática.',
   'Monitor transaminases at baseline and periodically; stop if signs of liver injury.',
   'Icterícia, elevação das transaminases ou sintomas de hepatite com a associação.',
   'Jaundice, raised transaminases or hepatitis symptoms with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Pirazinamida, 1.1.12 ; rótulo aprovado Isoniazida: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Pyrazinamide, 1.1.12 ; approved Isoniazid label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=93252cc8-c8d4-401b-bde5-ca8a3b57651e', 'published', now()),

  -- Pirazinamida × Probenecida (prontuário 1.1.12)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'pirazinamida'),
        (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'pirazinamida'),
            (SELECT id FROM public.drugs WHERE slug = 'probenecida')),
   'moderate',
   'Pirazinamida + probenecida: a pirazinamida antagoniza o efeito uricosúrico da probenecida.',
   'Pyrazinamide + probenecid: pyrazinamide antagonises the uricosuric effect of probenecid.',
   'O Prontuário Terapêutico documenta na monografia da pirazinamida (1.1.12): "A pirazinamida antagoniza os efeitos da probenecida e da sulfimpirazona". A pirazinamida reduz a excreção renal de ácido úrico (hiperuricemia), contrariando o efeito uricosúrico da probenecida.',
   'The Prontuário Terapêutico documents in the pyrazinamide monograph (1.1.12): "Pyrazinamide antagonises the effects of probenecid and sulfinpyrazone". Pyrazinamide reduces renal uric acid excretion (hyperuricaemia), counteracting the uricosuric effect of probenecid.',
   'Monitorizar o ácido úrico em doentes em tratamento uricosúrico durante a terapêutica com pirazinamida; considerar ajuste.',
   'Monitor uric acid in patients on uricosuric treatment during pyrazinamide therapy; consider adjustment.',
   'Vigiar sinais de gota (dor articular aguda) em doentes com gota tratada por probenecida.',
   'Watch for gout signs (acute joint pain) in gout patients treated with probenecid.',
   'Crise de gota ou hiperuricemia sintomática com a associação.',
   'Gout flare or symptomatic hyperuricaemia with the combination.',
   'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Pirazinamida, 1.1.12 ; rótulo aprovado Probenecida (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d',
   'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Pyrazinamide, 1.1.12 ; approved Probenecid label (MARLEX): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5d552de5-2d18-4464-bcaf-0311fa3f080d', 'published', now()),

  -- Tafenoquina × Metformina (rótulo FDA 7.1)
  (LEAST((SELECT id FROM public.drugs WHERE slug = 'tafenoquina'),
        (SELECT id FROM public.drugs WHERE slug = 'metformina')),
   GREATEST((SELECT id FROM public.drugs WHERE slug = 'tafenoquina'),
            (SELECT id FROM public.drugs WHERE slug = 'metformina')),
   'moderate',
   'Tafenoquina + metformina: a tafenoquina aumenta a exposição à metformina (substrato OCT2/MATE) — monitorizar toxicidade.',
   'Tafenoquine + metformin: tafenoquine increases metformin exposure (OCT2/MATE substrate) — monitor for toxicity.',
   'O rótulo FDA da tafenoquina documenta: "Avoid co-administration with drugs that are substrates of organic cation transporter-2 (OCT2) or multidrug and toxin extrusion (MATE) transporters (e.g., dofetilide, metformin). If coadministration cannot be avoided, monitor for drug-related toxicities and consider dosage reduction" (7.1). A metformina é substrato OCT2/MATE — a tafenoquina inibe estes transportadores e aumenta os seus níveis.',
   'The FDA tafenoquine label documents: "Avoid co-administration with drugs that are substrates of organic cation transporter-2 (OCT2) or multidrug and toxin extrusion (MATE) transporters (e.g., dofetilide, metformin). If coadministration cannot be avoided, monitor for drug-related toxicities and consider dosage reduction" (7.1). Metformin is an OCT2/MATE substrate — tafenoquine inhibits these transporters and raises its levels.',
   'Evitar a associação sempre que possível; se inevitável, monitorizar sinais de toxicidade da metformina e considerar redução da dose.',
   'Avoid the combination whenever possible; if unavoidable, monitor for metformin toxicity signs and consider dose reduction.',
   'Monitorizar função renal, sintomas gastrointestinais e sinais de acidose láctica (raros) durante a associação.',
   'Monitor renal function, gastrointestinal symptoms and signs of lactic acidosis (rare) during the combination.',
   'Acidose láctica, sintomas gastrointestinais graves ou função renal deteriorada com a associação.',
   'Lactic acidosis, severe gastrointestinal symptoms or worsening renal function with the combination.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tafenoquina (ARAKODA, 60 DEGREES PHARMACEUTICALS), secção 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=299e49d8-470f-4779-a010-4a1ee0e0c6cd ; rótulo aprovado Metformina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341',
   'DailyMed/FDA (NIH/NLM) — approved Tafenoquine label (ARAKODA, 60 DEGREES PHARMACEUTICALS), section 7.1: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=299e49d8-470f-4779-a010-4a1ee0e0c6cd ; approved Metformin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=34496b43-05a2-45fb-a769-52b12e099341', 'published', now())

ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;
