-- =====================================================================
-- 182: Anexos 3 e 4 do Prontuário (Insuficiência Hepática / Insuficiência
--      Renal) como dimensões drug_disease_interactions — aplicação em massa.
-- ---------------------------------------------------------------------
-- Fontes: Prontuário Terapêutico do INFARMED (11.ª ed., 2012):
--   * Anexo 3, "Fármacos e insuficiência hepática" (pág. 593-597)
--   * Anexo 4, "Fármacos e insuficiência renal" (pág. 598-603)
--
-- Abordagem (idêntica às 179/181):
--  * Entradas VALIDADAS visualmente no texto original (os anexos usam
--    2 colunas de texto fluido; entradas ambíguas/falsos positivos
--    foram EXCLUÍDAS — ex.: Estradiol=Etinilestradiol, Morfina=
--    Apomorfina, Omeprazol=Esomeprazol, Tetraciclina=Oxitetraciclina,
--    Paracetamol=Pantoprazol, Hidroxicloroquina=Cloroquina).
--  * INSERT em drug_disease_interactions (novas dimensões), JOIN por
--    slug com a tabela drugs. Idempotente (ON CONFLICT drug_id +
--    condition_slug DO NOTHING).
--  * condition_slug usa o vocabulário existente: insuficiencia_hepatica,
--    insuficiencia_hepatica_grave, insuficiencia_renal,
--    insuficiencia_renal_grave.
-- Aplicar após 173-181. Depende apenas dos fármacos já na BD.
-- =====================================================================

INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
       v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
       v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('diltiazem', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Reduzir a dose na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Reduzir a dose na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Reduzir a dose na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Reduce the dose in hepatic impairment.', 1),
  ('doxazosina', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática.',
   E'Avoid in hepatic impairment.',
   E'Evitar o uso na insuficiência hepática.',
   E'Avoid use in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in hepatic impairment.', 2),
  ('efavirenz', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Redução posológica em função da bilirrubina na insuficiência hepática.',
   E'Dose reduction according to bilirubin in hepatic impairment.',
   E'Reduzir a posologia em função da bilirrubina.',
   E'Reduce the dose according to bilirubin levels.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Redução posológica em função da bilirrubina na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Dose reduction according to bilirubin in hepatic impairment.', 3),
  ('efavirenz', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática grave.',
   E'Avoid in severe hepatic impairment.',
   E'Evitar o uso na insuficiência hepática grave.',
   E'Avoid use in severe hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in severe hepatic impairment.', 4),
  ('epoetina_alfa', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Precaução na insuficiência hepática.',
   E'Caution in hepatic impairment.',
   E'Usar com precaução na insuficiência hepática.',
   E'Use with caution in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Precaução na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Caution in hepatic impairment.', 5),
  ('fenobarbital', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Reduzir a dose na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Reduzir a dose na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Reduzir a dose na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Reduce the dose in hepatic impairment.', 6),
  ('fentanilo', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Redução posológica na insuficiência hepática.',
   E'Dose reduction in hepatic impairment.',
   E'Reduzir a posologia na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Redução posológica na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Dose reduction in hepatic impairment.', 7),
  ('fluconazol', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'contraindication', 'critical',
   E'Evitar; não há informação útil na insuficiência hepática.',
   E'Avoid; no useful information in hepatic impairment.',
   E'Evitar o uso na insuficiência hepática.',
   E'Avoid use in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar; não há informação útil na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid; no useful information in hepatic impairment.', 8),
  ('fluoxetina', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Toxicidade hepática — vigiar a função hepática.',
   E'Hepatic toxicity — monitor liver function.',
   E'Vigiar a função hepática durante o tratamento.',
   E'Monitor liver function during treatment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Toxicidade hepática — vigiar a função hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Hepatic toxicity — monitor liver function.', 9),
  ('glibenclamida', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Reduzir a dose na insuficiência hepática moderada.',
   E'Reduce the dose in moderate hepatic impairment.',
   E'Reduzir a dose na insuficiência hepática moderada.',
   E'Reduce the dose in moderate hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Reduzir a dose na insuficiência hepática moderada.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Reduce the dose in moderate hepatic impairment.', 10),
  ('glibenclamida', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática grave.',
   E'Avoid in severe hepatic impairment.',
   E'Evitar o uso na insuficiência hepática grave.',
   E'Avoid use in severe hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in severe hepatic impairment.', 11),
  ('isotretinoina', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática.',
   E'Avoid in hepatic impairment.',
   E'Evitar o uso na insuficiência hepática.',
   E'Avoid use in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in hepatic impairment.', 12),
  ('itraconazol', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Pode ser necessário reduzir a dose na insuficiência hepática.',
   E'A dose reduction may be necessary in hepatic impairment.',
   E'Ponderar redução da dose e monitorizar.',
   E'Consider dose reduction and monitoring.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Pode ser necessário reduzir a dose na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: A dose reduction may be necessary in hepatic impairment.', 13),
  ('losartano', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Pode ser necessário reduzir a dose na insuficiência hepática.',
   E'A dose reduction may be necessary in hepatic impairment.',
   E'Ponderar redução da dose na insuficiência hepática.',
   E'Consider dose reduction in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Pode ser necessário reduzir a dose na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: A dose reduction may be necessary in hepatic impairment.', 14),
  ('mefloquina', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical',
   E'Evitar o uso para profilaxia na insuficiência hepática grave.',
   E'Avoid use for prophylaxis in severe hepatic impairment.',
   E'Evitar a profilaxia na insuficiência hepática grave.',
   E'Avoid prophylaxis in severe hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar o uso para profilaxia na insuficiência hepática grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid use for prophylaxis in severe hepatic impairment.', 15),
  ('metformina', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'contraindication', 'critical',
   E'Reduzir a posologia; vigilância de transaminases e bilirrubinas; evitar; risco de acidose láctica.',
   E'Reduce the dose; monitor transaminases and bilirubin; avoid; risk of lactic acidosis.',
   E'Evitar na insuficiência hepática pelo risco de acidose láctica; se usado, vigiar transaminases.',
   E'Avoid in hepatic impairment due to the risk of lactic acidosis; if used, monitor transaminases.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Reduzir a posologia; vigilância de transaminases e bilirrubinas; evitar; risco de acidose láctica.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Reduce the dose; monitor transaminases and bilirubin; avoid; risk of lactic acidosis.', 16),
  ('metoclopramida', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Reduzir a posologia na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Reduzir a posologia na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Reduzir a posologia na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Reduce the dose in hepatic impairment.', 17),
  ('metronidazol', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Toxicidade dependente da dose; evitar nas indicações não neoplásicas na insuficiência hepática.',
   E'Dose-dependent toxicity; avoid in non-neoplastic indications in hepatic impairment.',
   E'Reduzir a dose e evitar nas indicações não neoplásicas.',
   E'Reduce the dose and avoid in non-neoplastic indications.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Toxicidade dependente da dose; evitar nas indicações não neoplásicas na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Dose-dependent toxicity; avoid in non-neoplastic indications in hepatic impairment.', 18),
  ('nitrofurantoina', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Há referência a icterícia colestática e a hepatite crónica activa.',
   E'Cholestatic jaundice and active chronic hepatitis have been reported.',
   E'Usar com precaução; vigiar sinais de lesão hepática.',
   E'Use with caution; monitor for signs of liver injury.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Há referência a icterícia colestática e a hepatite crónica activa.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Cholestatic jaundice and active chronic hepatitis have been reported.', 19),
  ('ondansetron', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Não exceder 20 mg/dia na insuficiência hepática.',
   E'Do not exceed 20 mg/day in hepatic impairment.',
   E'Não exceder a dose máxima de 20 mg/dia.',
   E'Do not exceed the maximum dose of 20 mg/day.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Não exceder 20 mg/dia na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Do not exceed 20 mg/day in hepatic impairment.', 20),
  ('pioglitazona', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática grave.',
   E'Avoid in severe hepatic impairment.',
   E'Evitar o uso na insuficiência hepática grave.',
   E'Avoid use in severe hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in severe hepatic impairment.', 21),
  ('propafenona', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Redução posológica na insuficiência hepática.',
   E'Dose reduction in hepatic impairment.',
   E'Reduzir a posologia na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Redução posológica na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Dose reduction in hepatic impairment.', 22),
  ('rivaroxabano', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática.',
   E'Avoid in hepatic impairment.',
   E'Evitar o uso na insuficiência hepática.',
   E'Avoid use in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in hepatic impairment.', 23),
  ('sulfato_magnesio', 'insuficiencia_hepatica_grave', 'Insuficiência hepática grave', 'Severe hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática grave.',
   E'Avoid in severe hepatic impairment.',
   E'Evitar o uso na insuficiência hepática grave.',
   E'Avoid use in severe hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in severe hepatic impairment.', 24),
  ('teofilina', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'precaution', 'moderate',
   E'Redução posológica na insuficiência hepática.',
   E'Dose reduction in hepatic impairment.',
   E'Reduzir a posologia na insuficiência hepática.',
   E'Reduce the dose in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Redução posológica na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Dose reduction in hepatic impairment.', 25),
  ('ticagrelor', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment', 'contraindication', 'critical',
   E'Evitar na insuficiência hepática.',
   E'Avoid in hepatic impairment.',
   E'Evitar o uso na insuficiência hepática.',
   E'Avoid use in hepatic impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 3, Fármacos e insuficiência hepática: Evitar na insuficiência hepática.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 3, Drugs and hepatic impairment: Avoid in hepatic impairment.', 26),
  ('acitretina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'contraindication', 'critical',
   E'Evitar; aumento do risco de toxicidade na insuficiência renal.',
   E'Avoid; increased risk of toxicity in renal impairment.',
   E'Evitar o uso na insuficiência renal.',
   E'Avoid use in renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Evitar; aumento do risco de toxicidade na insuficiência renal.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Avoid; increased risk of toxicity in renal impairment.', 27),
  ('alopurinol', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'100 a 200 mg/dia na IR moderada e 100 mg em dias alternados na IR grave; aumento do risco de toxicidade (erupções cutâneas).',
   E'100 to 200 mg/day in moderate and 100 mg on alternate days in severe renal impairment; increased risk of toxicity (skin rashes).',
   E'Reduzir a dose conforme o grau de insuficiência renal; vigiar erupções cutâneas.',
   E'Reduce the dose according to the degree of renal impairment; watch for skin rashes.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: 100 a 200 mg/dia na IR moderada e 100 mg em dias alternados na IR grave; aumento do risco de toxicidade (erupções cutâneas).', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: 100 to 200 mg/day in moderate and 100 mg on alternate days in severe renal impairment; increased risk of toxicity (skin rashes).', 28),
  ('amoxicilina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose ou prolongar intervalo de administração para 8-12 horas na IR grave; erupções cutâneas mais frequentes.',
   E'Reduce the dose or extend the dosing interval to 8-12 hours in severe renal impairment; skin rashes more frequent.',
   E'Reduzir a dose ou prolongar o intervalo na insuficiência renal grave.',
   E'Reduce the dose or extend the interval in severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose ou prolongar intervalo de administração para 8-12 horas na IR grave; erupções cutâneas mais frequentes.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose or extend the dosing interval to 8-12 hours in severe renal impairment; skin rashes more frequent.', 29),
  ('amoxicilina-clavulanato', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose ou prolongar intervalo de administração para 8-12 horas na IR grave; erupções cutâneas mais frequentes.',
   E'Reduce the dose or extend the dosing interval to 8-12 hours in severe renal impairment; skin rashes more frequent.',
   E'Reduzir a dose ou prolongar o intervalo na insuficiência renal grave.',
   E'Reduce the dose or extend the interval in severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose ou prolongar intervalo de administração para 8-12 horas na IR grave; erupções cutâneas mais frequentes.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose or extend the dosing interval to 8-12 hours in severe renal impairment; skin rashes more frequent.', 30),
  ('ampicilina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose na IR grave; erupções cutâneas mais frequentes.',
   E'Reduce the dose in severe renal impairment; skin rashes more frequent.',
   E'Reduzir a dose na insuficiência renal grave.',
   E'Reduce the dose in severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose na IR grave; erupções cutâneas mais frequentes.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose in severe renal impairment; skin rashes more frequent.', 31),
  ('anastrozol', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'contraindication', 'critical',
   E'Evitar na IR moderada a grave; não há informação.',
   E'Avoid in moderate to severe renal impairment; no information available.',
   E'Evitar o uso na insuficiência renal moderada a grave.',
   E'Avoid use in moderate to severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Evitar na IR moderada a grave; não há informação.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Avoid in moderate to severe renal impairment; no information available.', 32),
  ('azatioprina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose na IR grave.',
   E'Reduce the dose in severe renal impairment.',
   E'Reduzir a dose na insuficiência renal grave.',
   E'Reduce the dose in severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose na IR grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose in severe renal impairment.', 33),
  ('azitromicina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Usar com precaução na IR grave.',
   E'Use with caution in severe renal impairment.',
   E'Usar com precaução na insuficiência renal grave.',
   E'Use with caution in severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Usar com precaução na IR grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Use with caution in severe renal impairment.', 34),
  ('benzilpenicilina-benzatina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Dose máx. na IR grave - 6 g (10 MUI)/dia; risco de neurotoxicidade (doses altas podem induzir convulsões).',
   E'Maximum dose in severe renal impairment - 6 g (10 MU)/day; risk of neurotoxicity (high doses may induce seizures).',
   E'Não exceder 6 g/dia na insuficiência renal grave; vigiar neurotoxicidade.',
   E'Do not exceed 6 g/day in severe renal impairment; monitor for neurotoxicity.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Dose máx. na IR grave - 6 g (10 MUI)/dia; risco de neurotoxicidade (doses altas podem induzir convulsões).', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Maximum dose in severe renal impairment - 6 g (10 MU)/day; risk of neurotoxicity (high doses may induce seizures).', 35),
  ('carbamazepina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Usar com precaução na insuficiência renal.',
   E'Use with caution in renal impairment.',
   E'Usar com precaução na insuficiência renal.',
   E'Use with caution in renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Usar com precaução na insuficiência renal.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Use with caution in renal impairment.', 36),
  ('cefepima', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Prolongar intervalo de administração para 24 a 48 horas na IR moderada a grave.',
   E'Extend the dosing interval to 24-48 hours in moderate to severe renal impairment.',
   E'Prolongar o intervalo de administração na insuficiência renal moderada a grave.',
   E'Extend the dosing interval in moderate to severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Prolongar intervalo de administração para 24 a 48 horas na IR moderada a grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Extend the dosing interval to 24-48 hours in moderate to severe renal impairment.', 37),
  ('cefotaxima', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Dose inicial - 1 g; reduzir dose em 50% ou prolongar intervalo de administração para 8 a 24 horas na IR moderada a grave.',
   E'Initial dose - 1 g; reduce the dose by 50% or extend the dosing interval to 8-24 hours in moderate to severe renal impairment.',
   E'Reduzir a dose ou prolongar o intervalo na insuficiência renal moderada a grave.',
   E'Reduce the dose or extend the interval in moderate to severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Dose inicial - 1 g; reduzir dose em 50% ou prolongar intervalo de administração para 8 a 24 horas na IR moderada a grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Initial dose - 1 g; reduce the dose by 50% or extend the dosing interval to 8-24 hours in moderate to severe renal impairment.', 38),
  ('ceftazidima', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose ou prolongar intervalo de administração (8 a 72 horas) na IR moderada a grave.',
   E'Reduce the dose or extend the dosing interval (8-72 hours) in moderate to severe renal impairment.',
   E'Reduzir a dose ou prolongar o intervalo na insuficiência renal moderada a grave.',
   E'Reduce the dose or extend the interval in moderate to severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose ou prolongar intervalo de administração (8 a 72 horas) na IR moderada a grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose or extend the dosing interval (8-72 hours) in moderate to severe renal impairment.', 39),
  ('ceftriaxona', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose na IR grave; usar com precaução se co-existir IR e IH graves.',
   E'Reduce the dose in severe renal impairment; use with caution if severe renal and hepatic impairment coexist.',
   E'Reduzir a dose na insuficiência renal grave; precaução se co-existir insuficiência hepática.',
   E'Reduce the dose in severe renal impairment; caution if hepatic impairment coexists.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose na IR grave; usar com precaução se co-existir IR e IH graves.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose in severe renal impairment; use with caution if severe renal and hepatic impairment coexist.', 40),
  ('cefuroxima', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose (25 a 50%) e/ou prolongar intervalo de administração na IR moderada a grave.',
   E'Reduce the dose (25-50%) and/or extend the dosing interval in moderate to severe renal impairment.',
   E'Reduzir a dose e/ou prolongar o intervalo na insuficiência renal moderada a grave.',
   E'Reduce the dose and/or extend the interval in moderate to severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose (25 a 50%) e/ou prolongar intervalo de administração na IR moderada a grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose (25-50%) and/or extend the dosing interval in moderate to severe renal impairment.', 41),
  ('cetirizina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose em 50% na IR moderada.',
   E'Reduce the dose by 50% in moderate renal impairment.',
   E'Reduzir a dose em 50% na insuficiência renal moderada.',
   E'Reduce the dose by 50% in moderate renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose em 50% na IR moderada.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose by 50% in moderate renal impairment.', 42),
  ('ciclofosfamida', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose na insuficiência renal.',
   E'Reduce the dose in renal impairment.',
   E'Reduzir a dose na insuficiência renal.',
   E'Reduce the dose in renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose na insuficiência renal.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose in renal impairment.', 43),
  ('cimetidina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'600 a 800 mg/dia na IR ligeira a moderada; 400 mg/dia na IR grave.',
   E'600 to 800 mg/day in mild to moderate; 400 mg/day in severe renal impairment.',
   E'Ajustar a dose conforme o grau de insuficiência renal.',
   E'Adjust the dose according to the degree of renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: 600 a 800 mg/dia na IR ligeira a moderada; 400 mg/dia na IR grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: 600 to 800 mg/day in mild to moderate; 400 mg/day in severe renal impairment.', 44),
  ('ciprofloxacina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose em 25 a 50% na IR moderada a grave. Evitar, se possível; nefro e neurotóxico.',
   E'Reduce the dose by 25-50% in moderate to severe renal impairment. Avoid if possible; nephrotoxic and neurotoxic.',
   E'Reduzir a dose na insuficiência renal moderada a grave; evitar se possível.',
   E'Reduce the dose in moderate to severe renal impairment; avoid if possible.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose em 25 a 50% na IR moderada a grave. Evitar, se possível; nefro e neurotóxico.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose by 25-50% in moderate to severe renal impairment. Avoid if possible; nephrotoxic and neurotoxic.', 45),
  ('claritromicina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose em 25 a 50% na IR moderada a grave.',
   E'Reduce the dose by 25-50% in moderate to severe renal impairment.',
   E'Reduzir a dose na insuficiência renal moderada a grave.',
   E'Reduce the dose in moderate to severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose em 25 a 50% na IR moderada a grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose by 25-50% in moderate to severe renal impairment.', 46),
  ('clopidogrel', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Usar com precaução na insuficiência renal.',
   E'Use with caution in renal impairment.',
   E'Usar com precaução na insuficiência renal.',
   E'Use with caution in renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Usar com precaução na insuficiência renal.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Use with caution in renal impairment.', 47),
  ('cloranfenicol', 'insuficiencia_renal_grave', 'Insuficiência renal grave', 'Severe renal impairment', 'contraindication', 'critical',
   E'Evitar na IR grave; usar apenas se não existirem alternativas (depressão da hematopoiese dose-dependente).',
   E'Avoid in severe renal impairment; use only if no alternatives exist (dose-dependent depression of haematopoiesis).',
   E'Evitar na insuficiência renal grave; se inevitável, monitorizar o hemograma.',
   E'Avoid in severe renal impairment; if unavoidable, monitor blood counts.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Evitar na IR grave; usar apenas se não existirem alternativas (depressão da hematopoiese dose-dependente).', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Avoid in severe renal impairment; use only if no alternatives exist (dose-dependent depression of haematopoiesis).', 48),
  ('cloroquina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Reduzir dose na IR ligeira a moderada, excepto em profilaxia; evitar na IR grave.',
   E'Reduce the dose in mild to moderate renal impairment, except in prophylaxis; avoid in severe renal impairment.',
   E'Reduzir a dose conforme o grau de insuficiência renal; evitar na grave.',
   E'Reduce the dose according to the degree of renal impairment; avoid in severe.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Reduzir dose na IR ligeira a moderada, excepto em profilaxia; evitar na IR grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Reduce the dose in mild to moderate renal impairment, except in prophylaxis; avoid in severe renal impairment.', 49),
  ('clozapina', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Dose inicial - 12,5 mg/dia na IR ligeira e moderada; aumentar gradualmente; evitar na IR grave.',
   E'Initial dose - 12.5 mg/day in mild and moderate renal impairment; increase gradually; avoid in severe renal impairment.',
   E'Iniciar com dose baixa e aumentar gradualmente; evitar na insuficiência renal grave.',
   E'Start with a low dose and increase gradually; avoid in severe renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Dose inicial - 12,5 mg/dia na IR ligeira e moderada; aumentar gradualmente; evitar na IR grave.', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Initial dose - 12.5 mg/day in mild and moderate renal impairment; increase gradually; avoid in severe renal impairment.', 50),
  ('colecalciferol', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'precaution', 'moderate',
   E'Preferir fármacos que não necessitem de hidroxilação renal (calcitriol ou alfacalcidol).',
   E'Prefer drugs that do not require renal hydroxylation (calcitriol or alfacalcidol).',
   E'Preferir calcitriol ou alfacalcidol na insuficiência renal.',
   E'Prefer calcitriol or alfacalcidol in renal impairment.',
   E'Prontuário Terapêutico do INFARMED (11.ª ed., 2012) — Anexo 4, Fármacos e insuficiência renal: Preferir fármacos que não necessitem de hidroxilação renal (calcitriol ou alfacalcidol).', E'Prontuário Terapêutico do INFARMED (11th ed., 2012) — Annex 4, Drugs and renal impairment: Prefer drugs that do not require renal hydroxylation (calcitriol or alfacalcidol).', 51)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
        reason_pt, reason_en, advice_pt, advice_en,
        source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;
