-- =====================================================================
-- 187: Dicionário de alvos moleculares (molecular_targets)
--      CYP450, COX, transportadores (P-gp/BCRP/OATP), MAO e outros
--      alvos clínicos citados nas explicações de interações.
--
-- Motivação: as explicações da BD (Fluxo 4) citam enzimas e proteínas
-- (CYP3A4, CYP2D6, P-gp, COX-1/2, ...) como texto corrido. Esta tabela
-- dá-lhes uma página própria, com "o que é", papel nas interações,
-- substratos/inibidores/indutores e fonte — e será ligada às explicações
-- por deteção automática (regex) nas páginas públicas.
--
-- Schema: espelho de 060 (drug_food_interactions): RLS admin_all +
-- anon_read, soft-delete, status draft/published, trigger
-- update_updated_at_column. Idempotente (IF NOT EXISTS / ON CONFLICT).
--
-- Fontes: DailyMed/FDA (NIH/NLM), EMC-UK (MHRA), Health Canada,
-- PubMed (NIH/NLM) — regra da secção 2 de docs/INTERACOES_FLUXO_PESQUISA.md.
-- =====================================================================

-- ============================================================
-- 1. Tabela
-- ============================================================
CREATE TABLE IF NOT EXISTS public.molecular_targets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  target_type TEXT NOT NULL DEFAULT 'other'
    CHECK (target_type IN ('cyp450', 'cox', 'transporter', 'mao', 'enzyme', 'receptor', 'other')),
  name_pt TEXT NOT NULL,
  name_en TEXT NOT NULL,
  full_name_pt TEXT NOT NULL DEFAULT '',
  full_name_en TEXT NOT NULL DEFAULT '',
  aliases TEXT[] NOT NULL DEFAULT '{}',
  what_is_pt TEXT NOT NULL DEFAULT '',
  what_is_en TEXT NOT NULL DEFAULT '',
  role_pt TEXT NOT NULL DEFAULT '',
  role_en TEXT NOT NULL DEFAULT '',
  substrates_pt TEXT NOT NULL DEFAULT '',
  substrates_en TEXT NOT NULL DEFAULT '',
  inhibitors_pt TEXT NOT NULL DEFAULT '',
  inhibitors_en TEXT NOT NULL DEFAULT '',
  inducers_pt TEXT NOT NULL DEFAULT '',
  inducers_en TEXT NOT NULL DEFAULT '',
  clinical_notes_pt TEXT NOT NULL DEFAULT '',
  clinical_notes_en TEXT NOT NULL DEFAULT '',
  source_pt TEXT NOT NULL DEFAULT '',
  source_en TEXT NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft', 'published')),
  is_archived BOOLEAN NOT NULL DEFAULT false,
  archived_at TIMESTAMPTZ,
  archived_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_molecular_targets_type ON public.molecular_targets (target_type);
CREATE INDEX IF NOT EXISTS idx_molecular_targets_status ON public.molecular_targets (status, is_archived);

-- ============================================================
-- 2. RLS
-- ============================================================
ALTER TABLE public.molecular_targets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_all_molecular_targets" ON public.molecular_targets
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid()));

CREATE POLICY "anon_read_molecular_targets" ON public.molecular_targets
  FOR SELECT TO anon, authenticated
  USING (status = 'published' AND is_archived = false);

-- ============================================================
-- 3. Trigger updated_at
-- ============================================================
CREATE TRIGGER set_molecular_targets_updated_at
  BEFORE UPDATE ON public.molecular_targets
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 4. Seed — 20 alvos (idempotente por slug)
-- ============================================================
INSERT INTO public.molecular_targets
  (slug, target_type, name_pt, name_en, full_name_pt, full_name_en, aliases,
   what_is_pt, what_is_en, role_pt, role_en,
   substrates_pt, substrates_en, inhibitors_pt, inhibitors_en,
   inducers_pt, inducers_en, clinical_notes_pt, clinical_notes_en,
   source_pt, source_en, sort_order, status)
VALUES
  ('cyp3a4', 'cyp450', 'CYP3A4', 'CYP3A4', 'Citocromo P450 3A4', 'Cytochrome P450 3A4',
   ARRAY['CYP3A4', 'CYP3A'],
   E'Enzima do complexo citocromo P450 (família 3, subfamília A) responsável pelo metabolismo de cerca de metade dos fármacos atualmente em uso. Localiza-se sobretudo no fígado e no intestino delgado.',
   E'Enzyme of the cytochrome P450 complex (family 3, subfamily A) responsible for metabolising about half of the drugs currently in use. It is located mainly in the liver and small intestine.',
   E'É o alvo mais frequente nas interações: fármacos que a inibem (ex.: cetoconazol, claritromicina, sumo de toranja) aumentam as concentrações dos substratos; fármacos que a induzem (ex.: rifampicina, carbamazepina, fenitoína) reduzem-nas e podem causar perda de eficácia.',
   E'It is the most frequent target in interactions: drugs that inhibit it (e.g. ketoconazole, clarithromycin, grapefruit juice) raise substrate concentrations; drugs that induce it (e.g. rifampicin, carbamazepine, phenytoin) lower them and may cause loss of efficacy.',
   E'Substratos: simvastatina, atorvastatina, ciclosporina, tacrolimus, sirolimus, claritromicina, eritromicina, midazolam, sildenafil, tadalafil, nifedipino, verapamilo, diltiazem, ivabradina, pimozida.',
   E'Substrates: simvastatin, atorvastatin, ciclosporin, tacrolimus, sirolimus, clarithromycin, erythromycin, midazolam, sildenafil, tadalafil, nifedipine, verapamil, diltiazem, ivabradine, pimozide.',
   E'Inibidores: cetoconazol, itraconazol, fluconazol (fraco), claritromicina, eritromicina, ritonavir, amiodarona, diltiazem, verapamilo, sumo de toranja.',
   E'Inhibitors: ketoconazole, itraconazole, fluconazole (weak), clarithromycin, erythromycin, ritonavir, amiodarone, diltiazem, verapamil, grapefruit juice.',
   E'Indutores: rifampicina, carbamazepina, fenitoína, fenobarbital, erva-de-são-joão (hipericão), dexametasona.',
   E'Inducers: rifampicin, carbamazepine, phenytoin, phenobarbital, St John''s wort (hypericum), dexamethasone.',
   E'Na prática clínica, a inibição é o mecanismo mais relevante: combinações com inibidores fortes exigem redução de dose ou monitorização (ex.: simvastatina + claritromicina, ivabradina + cetoconazol, tacrolimus + diltiazem).',
   E'In clinical practice, inhibition is the most relevant mechanism: combinations with strong inhibitors require dose reduction or monitoring (e.g. simvastatin + clarithromycin, ivabradine + ketoconazole, tacrolimus + diltiazem).',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)',
   E'DailyMed/FDA (NIH/NLM) — approved labels; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)', 1),

  ('cyp2d6', 'cyp450', 'CYP2D6', 'CYP2D6', 'Citocromo P450 2D6', 'Cytochrome P450 2D6',
   ARRAY['CYP2D6'],
   E'Enzima do citocromo P450 que metaboliza cerca de 20-25% dos fármacos, incluindo muitos psicofármacos, opioides e antiarrítmicos. É altamente polimórfica: há metabolizadores lentos, intermédios, extensivos e ultrarrápidos.',
   E'Cytochrome P450 enzyme that metabolises about 20-25% of drugs, including many psychotropics, opioids and antiarrhythmics. It is highly polymorphic: there are poor, intermediate, extensive and ultrarapid metabolisers.',
   E'A inibição do CYP2D6 (ex.: fluoxetina, paroxetina) pode duplicar as concentrações de substratos como a codeína, o tramadol e a metoprolol; nos metabolizadores lentos, pró-fármacos ativados por esta enzima (codeína → morfina) podem ter efeito reduzido.',
   E'CYP2D6 inhibition (e.g. fluoxetine, paroxetine) can double concentrations of substrates such as codeine, tramadol and metoprolol; in poor metabolisers, prodrugs activated by this enzyme (codeine → morphine) may have reduced effect.',
   E'Substratos: codeína, tramadol, hidrocodona, metoprolol, carvedilol, timolol, flecainida, propafenona, haloperidol, risperidona, venlafaxina, fluoxetina, paroxetina.',
   E'Substrates: codeine, tramadol, hydrocodone, metoprolol, carvedilol, timolol, flecainide, propafenone, haloperidol, risperidone, venlafaxine, fluoxetine, paroxetine.',
   E'Inibidores: fluoxetina, paroxetina, bupropiona, quinidina, ritonavir, cinacalcete.',
   E'Inhibitors: fluoxetine, paroxetine, bupropion, quinidine, ritonavir, cinacalcet.',
   E'Indutores: não há indutores clinicamente relevantes; a atividade depende sobretudo da genética (polimorfismo CYP2D6).',
   E'Inducers: there are no clinically relevant inducers; activity depends mainly on genetics (CYP2D6 polymorphism).',
   E'Importante na dor: a codeína e o tramadol dependem do CYP2D6 para produzir o metabolito ativo (morfina / O-desmetiltramadol); em metabolizadores lentos a analgesia falha, em ultrarrápidos há risco de toxicidade opioide.',
   E'Important in pain: codeine and tramadol depend on CYP2D6 to produce the active metabolite (morphine / O-desmethyltramadol); in poor metabolisers analgesia fails, in ultrarapid metabolisers there is a risk of opioid toxicity.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6',
   E'DailyMed/FDA (NIH/NLM) — approved labels (codeine, fluoxetine); PubMed (NIH/NLM) — CYP2D6 pharmacogenetics', 2),

  ('cyp2c9', 'cyp450', 'CYP2C9', 'CYP2C9', 'Citocromo P450 2C9', 'Cytochrome P450 2C9',
   ARRAY['CYP2C9'],
   E'Enzima do citocromo P450 responsável pelo metabolismo dos anticoagulantes cumarínicos (varfarina, acenocumarol), de vários AINEs, da fenitoína e de algumas sulfonilureias.',
   E'Cytochrome P450 enzyme responsible for metabolising coumarin anticoagulants (warfarin, acenocoumarol), several NSAIDs, phenytoin and some sulfonylureas.',
   E'A inibição do CYP2C9 (ex.: fluconazol, amiodarona, metronidazol, cotrimoxazol) é o mecanismo central das interações que aumentam o INR com os cumarínicos; a indução (rifampicina) reduz o efeito anticoagulante.',
   E'CYP2C9 inhibition (e.g. fluconazole, amiodarone, metronidazole, cotrimoxazole) is the central mechanism of interactions that raise INR with coumarins; induction (rifampicin) reduces the anticoagulant effect.',
   E'Substratos: varfarina, acenocumarol, fenitoína, diclofenac, ibuprofeno, celecoxib, glibenclamida, glimepirida, losartano.',
   E'Substrates: warfarin, acenocoumarol, phenytoin, diclofenac, ibuprofen, celecoxib, glibenclamide, glimepiride, losartan.',
   E'Inibidores: fluconazol, voriconazol, metronidazol, amiodarona, cotrimoxazol (sulfametoxazol), cimetidina.',
   E'Inhibitors: fluconazole, voriconazole, metronidazole, amiodarone, cotrimoxazole (sulfamethoxazole), cimetidine.',
   E'Indutores: rifampicina, fenobarbital, carbamazepina, erva-de-são-joão.',
   E'Inducers: rifampicin, phenobarbital, carbamazepine, St John''s wort.',
   E'Essencial na terapêutica anticoagulante: qualquer fármaco que iniba o CYP2C9 pode elevar o INR em dias e exige monitorização apertada e redução de dose preventiva.',
   E'Essential in anticoagulant therapy: any drug that inhibits CYP2C9 can raise the INR within days and requires close monitoring and preventive dose reduction.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (warfarin, fluconazole); EMC-UK (MHRA) — SmPC', 3),

  ('cyp1a2', 'cyp450', 'CYP1A2', 'CYP1A2', 'Citocromo P450 1A2', 'Cytochrome P450 1A2',
   ARRAY['CYP1A2'],
   E'Enzima do citocromo P450 que metaboliza a teofilina, a cafeína, a clozapina e a olanzapina. É induzida pelo tabaco (fumo) e pela carne grelhada, e inibida pela ciprofloxacina e pela fluvoxamina.',
   E'Cytochrome P450 enzyme that metabolises theophylline, caffeine, clozapine and olanzapine. It is induced by tobacco smoke and grilled meat, and inhibited by ciprofloxacin and fluvoxamine.',
   E'A inibição do CYP1A2 (ex.: ciprofloxacina + teofilina) aumenta o risco de toxicidade da teofilina (náuseas, taquicardia, convulsões); os fumadores que deixam de fumar podem acumular substratos metabolizados por esta enzima.',
   E'CYP1A2 inhibition (e.g. ciprofloxacin + theophylline) increases the risk of theophylline toxicity (nausea, tachycardia, seizures); smokers who quit may accumulate substrates metabolised by this enzyme.',
   E'Substratos: teofilina, cafeína, clozapina, olanzapina, duloxetina, tizanidina, melatonina.',
   E'Substrates: theophylline, caffeine, clozapine, olanzapine, duloxetine, tizanidine, melatonin.',
   E'Inibidores: ciprofloxacina, fluvoxamina, cimetidina, contraceptivos orais.',
   E'Inhibitors: ciprofloxacin, fluvoxamine, cimetidine, oral contraceptives.',
   E'Indutores: fumo do tabaco, omeprazol (fraco), rifampicina, brócolos/couves (fracos).',
   E'Inducers: tobacco smoke, omeprazole (weak), rifampicin, broccoli/cabbage (weak).',
   E'Relevante na asma e na psiquiatria: a associação ciprofloxacina + teofilina é uma das interações clássicas de risco convulsivo e exige redução de dose da teofilina.',
   E'Relevant in asthma and psychiatry: ciprofloxacin + theophylline is one of the classic interactions with seizure risk and requires theophylline dose reduction.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (theophylline, ciprofloxacin); EMC-UK (MHRA) — SmPC', 4),

  ('cyp2c19', 'cyp450', 'CYP2C19', 'CYP2C19', 'Citocromo P450 2C19', 'Cytochrome P450 2C19',
   ARRAY['CYP2C19'],
   E'Enzima do citocromo P450 que ativa o clopidogrel (pró-fármaco) e metaboliza os inibidores da bomba de protões (omeprazol, lansoprazol), o diazepam e a sertralina.',
   E'Cytochrome P450 enzyme that activates clopidogrel (prodrug) and metabolises proton pump inhibitors (omeprazole, lansoprazole), diazepam and sertraline.',
   E'A inibição do CYP2C19 (ex.: omeprazol + clopidogrel) reduz a formação do metabolito ativo do clopidogrel e pode diminuir a proteção antiagregante; a indução (rifampicina) acelera o metabolismo dos substratos.',
   E'CYP2C19 inhibition (e.g. omeprazole + clopidogrel) reduces formation of the active clopidogrel metabolite and may decrease antiplatelet protection; induction (rifampicin) accelerates substrate metabolism.',
   E'Substratos: clopidogrel, omeprazol, lansoprazol, pantoprazol, diazepam, sertralina, citalopram, voriconazol.',
   E'Substrates: clopidogrel, omeprazole, lansoprazole, pantoprazole, diazepam, sertraline, citalopram, voriconazole.',
   E'Inibidores: omeprazol, esomeprazol, fluconazol, fluvoxamina, cimetidina.',
   E'Inhibitors: omeprazole, esomeprazole, fluconazole, fluvoxamine, cimetidine.',
   E'Indutores: rifampicina, carbamazepina, fenitoína, erva-de-são-joão.',
   E'Inducers: rifampicin, carbamazepine, phenytoin, St John''s wort.',
   E'Interação clássica: omeprazol (ou esomeprazol) + clopidogrel reduz a eficácia antiagregante; preferir pantoprazol quando um IBP é necessário em doente sob clopidogrel.',
   E'Classic interaction: omeprazole (or esomeprazole) + clopidogrel reduces antiplatelet efficacy; prefer pantoprazole when a PPI is needed in a patient on clopidogrel.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (clopidogrel, omeprazole); EMC-UK (MHRA) — SmPC', 5),

  ('cyp2c8', 'cyp450', 'CYP2C8', 'CYP2C8', 'Citocromo P450 2C8', 'Cytochrome P450 2C8',
   ARRAY['CYP2C8'],
   E'Enzima do citocromo P450 que metaboliza a repaglinida, a pioglitazona, o paclitaxel e a amodiaquina.',
   E'Cytochrome P450 enzyme that metabolises repaglinide, pioglitazone, paclitaxel and amodiaquine.',
   E'A inibição do CYP2C8 (ex.: gemfibrozil + repaglinida) aumenta as concentrações do substrato e o risco de hipoglicemia; a indução reduz o efeito.',
   E'CYP2C8 inhibition (e.g. gemfibrozil + repaglinide) raises substrate concentrations and the risk of hypoglycaemia; induction reduces the effect.',
   E'Substratos: repaglinida, pioglitazona, paclitaxel, amodiaquina, rosiglitazona.',
   E'Substrates: repaglinide, pioglitazone, paclitaxel, amodiaquine, rosiglitazone.',
   E'Inibidores: gemfibrozil, montelucaste, trimetoprim, cetoconazol.',
   E'Inhibitors: gemfibrozil, montelukast, trimethoprim, ketoconazole.',
   E'Indutores: rifampicina, carbamazepina, fenitoína.',
   E'Inducers: rifampicin, carbamazepine, phenytoin.',
   E'A interação gemfibrozil + repaglinida é clinicamente significativa (hipoglicemia grave) e está documentada no rótulo da repaglinida.',
   E'The gemfibrozil + repaglinide interaction is clinically significant (severe hypoglycaemia) and documented in the repaglinide label.',
   E'DailyMed/FDA (NIH/NLM) — rótulo aprovado Repaglinida; EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved Repaglinide label; EMC-UK (MHRA) — SmPC', 6),

  ('cyp2b6', 'cyp450', 'CYP2B6', 'CYP2B6', 'Citocromo P450 2B6', 'Cytochrome P450 2B6',
   ARRAY['CYP2B6'],
   E'Enzima do citocromo P450 que metaboliza o efavirenz, a bupropiona, a metadona e a ciclofosfamida.',
   E'Cytochrome P450 enzyme that metabolises efavirenz, bupropion, methadone and cyclophosphamide.',
   E'A indução do CYP2B6 (ex.: rifampicina, fenobarbital) reduz as concentrações do efavirenz e da bupropiona; a inibição aumenta a exposição.',
   E'CYP2B6 induction (e.g. rifampicin, phenobarbital) lowers efavirenz and bupropion concentrations; inhibition increases exposure.',
   E'Substratos: efavirenz, bupropiona, metadona, ciclofosfamida, sibutramina.',
   E'Substrates: efavirenz, bupropion, methadone, cyclophosphamide, sibutramine.',
   E'Inibidores: clopidogrel, ticlopidina, voriconazol.',
   E'Inhibitors: clopidogrel, ticlopidine, voriconazole.',
   E'Indutores: rifampicina, fenobarbital, carbamazepina, fenitoína.',
   E'Inducers: rifampicin, phenobarbital, carbamazepine, phenytoin.',
   E'Relevante na terapêutica antirretroviral: a rifampicina reduz acentuadamente as concentrações do efavirenz.',
   E'Relevant in antiretroviral therapy: rifampicin markedly lowers efavirenz concentrations.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (efavirenz, bupropion); EMC-UK (MHRA) — SmPC', 7),

  ('cyp2e1', 'cyp450', 'CYP2E1', 'CYP2E1', 'Citocromo P450 2E1', 'Cytochrome P450 2E1',
   ARRAY['CYP2E1'],
   E'Enzima do citocromo P450 que metaboliza o etanol, o paracetamol (originando o metabolito tóxico NAPQI) e a isoniazida. É induzida pelo consumo crónico de álcool.',
   E'Cytochrome P450 enzyme that metabolises ethanol, paracetamol (producing the toxic metabolite NAPQI) and isoniazid. It is induced by chronic alcohol intake.',
   E'O consumo crónico de álcool induz o CYP2E1 e aumenta a formação de NAPQI a partir do paracetamol, elevando o risco de hepatotoxicidade com doses terapêuticas.',
   E'Chronic alcohol intake induces CYP2E1 and increases NAPQI formation from paracetamol, raising the risk of hepatotoxicity at therapeutic doses.',
   E'Substratos: etanol, paracetamol, isoniazida, teofilina (menor via).',
   E'Substrates: ethanol, paracetamol, isoniazid, theophylline (minor pathway).',
   E'Inibidores: dissulfiram, cimetidina, disulfiram.',
   E'Inhibitors: disulfiram, cimetidine.',
   E'Indutores: etanol (crónico), isoniazida, acetona (jejum/diabetes).',
   E'Inducers: ethanol (chronic), isoniazid, acetone (fasting/diabetes).',
   E'Base da precaução "álcool + paracetamol": limitar a dose de paracetamol no doente alcoólico crónico.',
   E'Basis of the "alcohol + paracetamol" precaution: limit paracetamol dose in the chronic alcoholic patient.',
   E'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)',
   E'DailyMed/FDA (NIH/NLM) — approved Paracetamol label; PubMed (NIH/NLM)', 8),

  ('cox1', 'cox', 'COX-1', 'COX-1', 'Ciclo-oxigenase 1', 'Cyclooxygenase 1',
   ARRAY['COX-1', 'COX1', 'PTGS1'],
   E'Enzima constitutiva que produz prostaglandinas com função protetora: mantém a mucosa gástrica, regula a agregação plaquetar (tromboxano A2) e o fluxo renal.',
   E'Constitutive enzyme that produces prostaglandins with protective functions: maintains the gastric mucosa, regulates platelet aggregation (thromboxane A2) and renal flow.',
   E'A inibição da COX-1 pelos AINEs e pela aspirina explica os efeitos gastrolesivos (úlcera, hemorragia) e, na aspirina, o efeito antiagregante plaquetar. É o alvo das interações AINE + anticoagulante/antiagregante.',
   E'COX-1 inhibition by NSAIDs and aspirin explains the gastrotoxic effects (ulcer, bleeding) and, with aspirin, the antiplatelet effect. It is the target of NSAID + anticoagulant/antiplatelet interactions.',
   E'Substratos: ácido araquidónico (origina PGE2, PGI2, tromboxano A2).',
   E'Substrates: arachidonic acid (yields PGE2, PGI2, thromboxane A2).',
   E'Inibidores: aspirina (irreversível, baixas doses), diclofenac, ibuprofeno, naproxeno, cetorolac, indometacina.',
   E'Inhibitors: aspirin (irreversible, low doses), diclofenac, ibuprofen, naproxen, ketorolac, indomethacin.',
   E'Indutores: não aplicável (não há indutores clinicamente relevantes).',
   E'Inducers: not applicable (no clinically relevant inducers).',
   E'A inibição da COX-1 é o mecanismo do risco hemorrágico aditivo quando AINEs/aspirina se associam a anticoagulantes orais ou antiagregantes.',
   E'COX-1 inhibition is the mechanism of additive bleeding risk when NSAIDs/aspirin are combined with oral anticoagulants or antiplatelets.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (aspirina, AINEs); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (aspirin, NSAIDs); EMC-UK (MHRA) — SmPC', 9),

  ('cox2', 'cox', 'COX-2', 'COX-2', 'Ciclo-oxigenase 2', 'Cyclooxygenase 2',
   ARRAY['COX-2', 'COX2', 'PTGS2'],
   E'Enzima induzida pela inflamação que produz prostaglandinas pró-inflamatórias e pró-dolorosas. É o alvo seletivo dos coxibes (celecoxib, etoricoxib).',
   E'Enzyme induced by inflammation that produces pro-inflammatory and pro-nociceptive prostaglandins. It is the selective target of coxibs (celecoxib, etoricoxib).',
   E'Os inibidores seletivos da COX-2 poupam a COX-1 e têm menor risco gastrointestinal, mas mantêm o risco cardiovascular (tromboembólico) e renal; as interações com anticoagulantes continuam a ser relevantes.',
   E'Selective COX-2 inhibitors spare COX-1 and have lower gastrointestinal risk, but retain cardiovascular (thromboembolic) and renal risk; interactions with anticoagulants remain relevant.',
   E'Substratos: ácido araquidónico (origina PGE2, prostaciclina).',
   E'Substrates: arachidonic acid (yields PGE2, prostacyclin).',
   E'Inibidores: celecoxib, etoricoxib, parecoxib; AINEs clássicos em doses anti-inflamatórias também a inibem.',
   E'Inhibitors: celecoxib, etoricoxib, parecoxib; classic NSAIDs at anti-inflammatory doses also inhibit it.',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'O celecoxib é metabolizado pelo CYP2C9 — a associação com fluconazol aumenta a exposição; e mantém risco hemorrágico aditivo com anticoagulantes.',
   E'Celecoxib is metabolised by CYP2C9 — combination with fluconazole increases exposure; it retains additive bleeding risk with anticoagulants.',
   E'DailyMed/FDA (NIH/NLM) — rótulo aprovado Celecoxib; EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved Celecoxib label; EMC-UK (MHRA) — SmPC', 10),

  ('pgp', 'transporter', 'P-gp (glicoproteína-P)', 'P-gp (P-glycoprotein)', 'Glicoproteína-P (MDR1 / ABCB1)', 'P-glycoprotein (MDR1 / ABCB1)',
   ARRAY['P-gp', 'PgP', 'MDR1', 'ABCB1', 'glicoproteina-P'],
   E'Transportador de efluxo da superfamília ABC localizado na membrana intestinal, nos hepatócitos, nos túbulos renais e na barreira hematoencefálica. "Bombeia" fármacos para fora das células, limitando a absorção e a penetração.',
   E'ABC-superfamily efflux transporter located on the intestinal membrane, hepatocytes, renal tubules and the blood-brain barrier. It "pumps" drugs out of cells, limiting absorption and penetration.',
   E'Fármacos que inibem a P-gp (ex.: amiodarona, claritromicina, cetoconazol, verapamilo, diltiazem) aumentam a absorção e as concentrações de substratos como a digoxina, o dabigatrano e o tacrolimus; os indutores reduzem-nas.',
   E'Drugs that inhibit P-gp (e.g. amiodarone, clarithromycin, ketoconazole, verapamil, diltiazem) increase absorption and concentrations of substrates such as digoxin, dabigatran and tacrolimus; inducers lower them.',
   E'Substratos: digoxina, dabigatrano, rivaroxabano (parcial), tacrolimus, sirolimus, ciclosporina, loperamida, fexofenadina, colchicina.',
   E'Substrates: digoxin, dabigatran, rivaroxaban (partial), tacrolimus, sirolimus, ciclosporin, loperamide, fexofenadine, colchicine.',
   E'Inibidores: amiodarona, claritromicina, eritromicina, cetoconazol, itraconazol, verapamilo, diltiazem, ritonavir, ciclosporina, carvedilol.',
   E'Inhibitors: amiodarone, clarithromycin, erythromycin, ketoconazole, itraconazole, verapamil, diltiazem, ritonavir, ciclosporin, carvedilol.',
   E'Indutores: rifampicina, erva-de-são-joão, carbamazepina, fenitoína.',
   E'Inducers: rifampicin, St John''s wort, carbamazepine, phenytoin.',
   E'Interações clássicas: digoxina + claritromicina/amiodarona (toxicidade digitálica), dabigatrano + amiodarona (exposição aumentada), loperamida + inibidores da P-gp (depressão respiratória).',
   E'Classic interactions: digoxin + clarithromycin/amiodarone (digitalis toxicity), dabigatran + amiodarone (increased exposure), loperamide + P-gp inhibitors (respiratory depression).',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (digoxin, dabigatran); EMC-UK (MHRA) — SmPC', 11),

  ('bcrp', 'transporter', 'BCRP', 'BCRP', 'Proteína de resistência ao cancro da mama (ABCG2)', 'Breast cancer resistance protein (ABCG2)',
   ARRAY['BCRP', 'ABCG2'],
   E'Transportador de efluxo (ABCG2) presente no intestino, fígado, rim e placenta, que limita a absorção de vários fármacos e substratos endógenos (ex.: ácido úrico).',
   E'Efflux transporter (ABCG2) present in the gut, liver, kidney and placenta, which limits the absorption of several drugs and endogenous substrates (e.g. uric acid).',
   E'A inibição do BCRP aumenta a exposição a substratos como a rosuvastatina, o metotrexato e a sulfassalazina; a associação com inibidores (ex.: ciclosporina) pode exigir redução de dose.',
   E'BCRP inhibition increases exposure to substrates such as rosuvastatin, methotrexate and sulfasalazine; combination with inhibitors (e.g. ciclosporin) may require dose reduction.',
   E'Substratos: rosuvastatina, atorvastatina (parcial), metotrexato, sulfassalazina, alopurinol (oxipurinol), nitrofurantoína.',
   E'Substrates: rosuvastatin, atorvastatin (partial), methotrexate, sulfasalazine, allopurinol (oxipurinol), nitrofurantoin.',
   E'Inibidores: ciclosporina, eltrombopag, curcumina, sumo de toranja.',
   E'Inhibitors: ciclosporin, eltrombopag, curcumin, grapefruit juice.',
   E'Indutores: rifampicina.',
   E'Inducers: rifampicin.',
   E'A interação rosuvastatina + ciclosporina (aumento de exposição) está documentada no rótulo da rosuvastatina e exige limite de dose.',
   E'The rosuvastatin + ciclosporin interaction (increased exposure) is documented in the rosuvastatin label and requires a dose limit.',
   E'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina; EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved Rosuvastatin label; EMC-UK (MHRA) — SmPC', 12),

  ('oatp1b1', 'transporter', 'OATP1B1', 'OATP1B1', 'Polipéptido transportador de aniões orgânicos 1B1 (SLCO1B1)', 'Organic anion transporting polypeptide 1B1 (SLCO1B1)',
   ARRAY['OATP1B1', 'SLCO1B1', 'OATP-C'],
   E'Transportador hepático de captação (SLCO1B1) que medeia a entrada de fármacos no hepatócito, incluindo a maioria das estatinas (simvastatina, atorvastatina, rosuvastatina, pravastatina).',
   E'Hepatic uptake transporter (SLCO1B1) that mediates drug entry into hepatocytes, including most statins (simvastatin, atorvastatin, rosuvastatin, pravastatin).',
   E'A inibição do OATP1B1 (ex.: ciclosporina, claritromicina) reduz a captação hepática das estatinas e aumenta as concentrações sistémicas, com risco de miopatia e rabdomiólise.',
   E'OATP1B1 inhibition (e.g. ciclosporin, clarithromycin) reduces hepatic uptake of statins and raises systemic concentrations, with risk of myopathy and rhabdomyolysis.',
   E'Substratos: simvastatina, atorvastatina, rosuvastatina, pravastatina, repaglinida, metotrexato, rifampicina.',
   E'Substrates: simvastatin, atorvastatin, rosuvastatin, pravastatin, repaglinide, methotrexate, rifampicin.',
   E'Inibidores: ciclosporina, claritromicina, gemfibrozil, ritonavir, rifampicina (dose única).',
   E'Inhibitors: ciclosporin, clarithromycin, gemfibrozil, ritonavir, rifampicin (single dose).',
   E'Indutores: não aplicável (transporte de captação, não metabolismo).',
   E'Inducers: not applicable (uptake transport, not metabolism).',
   E'O polimorfismo SLCO1B1 e a inibição por ciclosporina/claritromicina explicam o risco de miopatia das estatinas em doentes transplantados.',
   E'The SLCO1B1 polymorphism and inhibition by ciclosporin/clarithromycin explain statin myopathy risk in transplant patients.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)',
   E'DailyMed/FDA (NIH/NLM) — approved labels (simvastatin, rosuvastatin); PubMed (NIH/NLM)', 13),

  ('maoa', 'mao', 'MAO-A', 'MAO-A', 'Monoamina-oxidase A', 'Monoamine oxidase A',
   ARRAY['MAO-A', 'MAOA'],
   E'Enzima mitocondrial que degrada a serotonina, a noradrenalina e a dopamina (e a tiramina alimentar). É inibida seletivamente pela moclobemida.',
   E'Mitochondrial enzyme that degrades serotonin, noradrenaline and dopamine (and dietary tyramine). It is selectively inhibited by moclobemide.',
   E'A inibição da MAO-A aumenta as monoaminas sinápticas; a associação com ISRS, tramadol, petidina ou dextrometorfano pode causar síndrome serotoninérgica, e a ingestão de alimentos ricos em tiramina pode causar crise hipertensiva.',
   E'MAO-A inhibition raises synaptic monoamines; combination with SSRIs, tramadol, pethidine or dextromethorphan can cause serotonin syndrome, and tyramine-rich food can cause a hypertensive crisis.',
   E'Substratos: serotonina, noradrenalina, dopamina, tiramina.',
   E'Substrates: serotonin, noradrenaline, dopamine, tyramine.',
   E'Inibidores: moclobemida (seletivo), fenelzina, tranilcipromina, linezolida (não seletivo).',
   E'Inhibitors: moclobemide (selective), phenelzine, tranylcypromine, linezolid (non-selective).',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'Exigem intervalo de washout (2 semanas) entre inibidores da MAO e ISRS/serotoninérgicos; alimentos ricos em tiramina (queijos curados, cerveja, chouriço) podem causar crise hipertensiva.',
   E'Washout intervals (2 weeks) are required between MAO inhibitors and SSRIs/serotonergics; tyramine-rich foods (aged cheese, beer, cured sausage) can cause a hypertensive crisis.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (IMAO); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (MAOIs); EMC-UK (MHRA) — SmPC', 14),

  ('maob', 'mao', 'MAO-B', 'MAO-B', 'Monoamina-oxidase B', 'Monoamine oxidase B',
   ARRAY['MAO-B', 'MAOB'],
   E'Enzima mitocondrial que degrada preferencialmente a dopamina. É inibida seletivamente pela selegilina e pela rasagilina, usadas na doença de Parkinson.',
   E'Mitochondrial enzyme that preferentially degrades dopamine. It is selectively inhibited by selegiline and rasagiline, used in Parkinson''s disease.',
   E'A inibição seletiva da MAO-B em doses terapêuticas tem menor risco de interação com tiramina, mas a associação com fármacos serotoninérgicos (ISRS, petidina) mantém risco de síndrome serotoninérgica.',
   E'Selective MAO-B inhibition at therapeutic doses has lower tyramine interaction risk, but combination with serotonergic drugs (SSRIs, pethidine) retains serotonin syndrome risk.',
   E'Substratos: dopamina, tiramina (em menor grau que a MAO-A).',
   E'Substrates: dopamine, tyramine (to a lesser extent than MAO-A).',
   E'Inibidores: selegilina, rasagilina.',
   E'Inhibitors: selegiline, rasagiline.',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'Evitar associação de selegilina com petidina (interação potencialmente fatal documentada) e com ISRS.',
   E'Avoid combining selegiline with pethidine (potentially fatal documented interaction) and with SSRIs.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (selegilina); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (selegiline); EMC-UK (MHRA) — SmPC', 15),

  ('vkorc1', 'enzyme', 'VKORC1', 'VKORC1', 'Vitamina K epóxido redutase', 'Vitamin K epoxide reductase',
   ARRAY['VKORC1'],
   E'Enzima que regenera a vitamina K reduzida, necessária à ativação (gama-carboxilação) dos fatores de coagulação II, VII, IX e X e das proteínas C e S. É o alvo terapêutico dos anticoagulantes cumarínicos.',
   E'Enzyme that regenerates reduced vitamin K, required for activation (gamma-carboxylation) of clotting factors II, VII, IX and X and proteins C and S. It is the therapeutic target of coumarin anticoagulants.',
   E'A varfarina e o acenocumarol inibem a VKORC1, reduzindo a síntese de fatores dependentes da vitamina K; a ingestão alimentar de vitamina K antagoniza este efeito e altera o INR.',
   E'Warfarin and acenocoumarol inhibit VKORC1, reducing synthesis of vitamin K-dependent factors; dietary vitamin K intake antagonises this effect and shifts the INR.',
   E'Substratos: vitamina K epóxido (regeneração da vitamina K).',
   E'Substrates: vitamin K epoxide (regeneration of vitamin K).',
   E'Inibidores: varfarina, acenocumarol.',
   E'Inhibitors: warfarin, acenocoumarol.',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'O polimorfismo do VKORC1 explica a sensibilidade individual aos cumarínicos; a ingestão estável de vitamina K é essencial para manter o INR no alvo.',
   E'VKORC1 polymorphism explains individual sensitivity to coumarins; stable vitamin K intake is essential to keep INR in range.',
   E'DailyMed/FDA (NIH/NLM) — rótulo aprovado Varfarina; PubMed (NIH/NLM)',
   E'DailyMed/FDA (NIH/NLM) — approved Warfarin label; PubMed (NIH/NLM)', 16),

  ('g6pd', 'enzyme', 'G6PD', 'G6PD', 'Glucose-6-fosfato desidrogenase', 'Glucose-6-phosphate dehydrogenase',
   ARRAY['G6PD', 'G-6-PD'],
   E'Enzima eritrocitária que protege os glóbulos vermelhos do stress oxidativo (produção de NADPH). A sua deficiência (X-ligada) é a enzimopatia mais comum do mundo, prevalente em África, Mediterrâneo e Ásia.',
   E'Red blood cell enzyme that protects erythrocytes from oxidative stress (NADPH production). Its deficiency (X-linked) is the most common enzymopathy worldwide, prevalent in Africa, the Mediterranean and Asia.',
   E'Fármacos oxidantes podem causar hemólise aguda em doentes com deficiência de G6PD: primaquina, sulfonamidas (cotrimoxazol), nitrofurantoína, dapsona, aspirina em doses altas.',
   E'Oxidant drugs can cause acute haemolysis in G6PD-deficient patients: primaquine, sulfonamides (cotrimoxazole), nitrofurantoin, dapsone, high-dose aspirin.',
   E'Substratos: glucose-6-fosfato (gera NADPH).',
   E'Substrates: glucose-6-phosphate (generates NADPH).',
   E'Inibidores (fármacos hemolíticos): primaquina, tafenoquina, sulfonamidas, nitrofurantoína, dapsona, azul de metileno.',
   E'Inhibitors (haemolytic drugs): primaquine, tafenoquine, sulfonamides, nitrofurantoin, dapsone, methylene blue.',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'Rastreio obrigatório antes de primaquina/tafenoquina (malária vivax) e prudência com sulfonamidas em populações de risco.',
   E'Mandatory screening before primaquine/tafenoquine (vivax malaria) and caution with sulfonamides in at-risk populations.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (primaquina, nitrofurantoína); PubMed (NIH/NLM)',
   E'DailyMed/FDA (NIH/NLM) — approved labels (primaquine, nitrofurantoin); PubMed (NIH/NLM)', 17),

  ('tpmt', 'enzyme', 'TPMT', 'TPMT', 'Tiopurina S-metiltransferase', 'Thiopurine S-methyltransferase',
   ARRAY['TPMT'],
   E'Enzima citosólica que metaboliza as tiopurinas (azatioprina, mercaptopurina, tioguanina). A deficiência de TPMT (polimorfismo) aumenta a exposição aos metabolitos ativos e o risco de mielossupressão.',
   E'Cytosolic enzyme that metabolises thiopurines (azathioprine, mercaptopurine, thioguanine). TPMT deficiency (polymorphism) increases exposure to active metabolites and the risk of myelosuppression.',
   E'Fármacos que inibem a TPMT (ex.: alopurinol) aumentam a toxicidade da azatioprina; a associação alopurinol + azatioprina é a interação clássica e exige redução de dose da azatioprina.',
   E'Drugs that inhibit TPMT (e.g. allopurinol) increase azathioprine toxicity; allopurinol + azathioprine is the classic interaction and requires azathioprine dose reduction.',
   E'Substratos: azatioprina, mercaptopurina, tioguanina.',
   E'Substrates: azathioprine, mercaptopurine, thioguanine.',
   E'Inibidores: alopurinol, febuxostat, mesalazina, sulfassalazina, diuréticos da ansa (doses altas).',
   E'Inhibitors: allopurinol, febuxostat, mesalazine, sulfasalazine, loop diuretics (high doses).',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'A associação alopurinol + azatioprina (ou mercaptopurina) exige redução de dose de 50-75% da tiopurina; considerar doseamento do TPMT antes de iniciar.',
   E'The allopurinol + azathioprine (or mercaptopurine) combination requires a 50-75% thiopurine dose reduction; consider TPMT testing before starting.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (azatioprina, alopurinol); PubMed (NIH/NLM)',
   E'DailyMed/FDA (NIH/NLM) — approved labels (azathioprine, allopurinol); PubMed (NIH/NLM)', 18),

  ('pde5', 'enzyme', 'PDE5', 'PDE5', 'Fosfodiesterase 5', 'Phosphodiesterase 5',
   ARRAY['PDE5'],
   E'Enzima que degrada o GMP cíclico no músculo liso dos corpos cavernosos e nos vasos pulmonares. É o alvo do sildenafil, tadalafil e vardenafil.',
   E'Enzyme that degrades cyclic GMP in corpus cavernosum smooth muscle and pulmonary vessels. It is the target of sildenafil, tadalafil and vardenafil.',
   E'A associação de inibidores da PDE5 com nitratos (nitroglicerina, isossorbida) causa hipotensão grave potencialmente fatal, por potenciação do óxido nítrico; também potenciam a hipotensão com alfabloqueadores e com o riociguat.',
   E'Combining PDE5 inhibitors with nitrates (nitroglycerin, isosorbide) causes severe, potentially fatal hypotension, by potentiating nitric oxide; they also potentiate hypotension with alpha-blockers and riociguat.',
   E'Substratos: GMP cíclico.',
   E'Substrates: cyclic GMP.',
   E'Inibidores: sildenafil, tadalafil, vardenafil.',
   E'Inhibitors: sildenafil, tadalafil, vardenafil.',
   E'Indutores: não aplicável.',
   E'Inducers: not applicable.',
   E'Contraindicação absoluta: inibidores da PDE5 + nitratos (qualquer forma); também evitar com riociguat. O sildenafil e o vardenafil são metabolizados pelo CYP3A4 (interação com cetoconazol, ritonavir, claritromicina).',
   E'Absolute contraindication: PDE5 inhibitors + nitrates (any form); also avoid with riociguat. Sildenafil and vardenafil are metabolised by CYP3A4 (interaction with ketoconazole, ritonavir, clarithromycin).',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (sildenafil, tadalafil); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (sildenafil, tadalafil); EMC-UK (MHRA) — SmPC', 19),

  ('hmgcr', 'enzyme', 'HMG-CoA redutase', 'HMG-CoA reductase', '3-hidroxi-3-metilglutaril-CoA redutase', '3-hydroxy-3-methylglutaryl-CoA reductase',
   ARRAY['HMG-CoA', 'HMGCR'],
   E'Enzima limitante da síntese de colesterol (converte HMG-CoA em mevalonato). É o alvo terapêutico das estatinas.',
   E'Rate-limiting enzyme of cholesterol synthesis (converts HMG-CoA to mevalonate). It is the therapeutic target of statins.',
   E'As estatinas (simvastatina, atorvastatina) são metabolizadas pelo CYP3A4 e transportadas pelo OATP1B1; a inibição por cetoconazol, claritromicina, ciclosporina ou amiodarona aumenta o risco de miopatia e rabdomiólise.',
   E'Statins (simvastatin, atorvastatin) are metabolised by CYP3A4 and transported by OATP1B1; inhibition by ketoconazole, clarithromycin, ciclosporin or amiodarone increases the risk of myopathy and rhabdomyolysis.',
   E'Substratos: HMG-CoA (origina mevalonato e colesterol).',
   E'Substrates: HMG-CoA (yields mevalonate and cholesterol).',
   E'Inibidores (das estatinas via CYP3A4/OATP1B1): claritromicina, cetoconazol, itraconazol, ciclosporina, gemfibrozil, amiodarona, sumo de toranja.',
   E'Inhibitors (of statins via CYP3A4/OATP1B1): clarithromycin, ketoconazole, itraconazole, ciclosporin, gemfibrozil, amiodarone, grapefruit juice.',
   E'Indutores: rifampicina, carbamazepina, fenitoína.',
   E'Inducers: rifampicin, carbamazepine, phenytoin.',
   E'Evitar simvastatina + claritromicina/gemfibrozil/ciclosporina (risco de rabdomiólise); limitar a dose de atorvastatina com claritromicina.',
   E'Avoid simvastatin + clarithromycin/gemfibrozil/ciclosporin (rhabdomyolysis risk); limit atorvastatin dose with clarithromycin.',
   E'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC',
   E'DailyMed/FDA (NIH/NLM) — approved labels (simvastatin, atorvastatin); EMC-UK (MHRA) — SmPC', 20)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- FIM — 20 alvos (8 CYP450, 2 COX, 3 transportadores, 2 MAO, 5 enzimas)
-- Aplicar no Supabase e depois ./revalidar.sh (se o site já o ler).
-- =====================================================================
