-- =====================================================================
-- 189: Seed de drug_target_roles — derivado do parse dos textos de
--      molecular_targets (substrates/inhibitors/inducers) a casar com
--      os nomes reais dos fármacos da BD (name_pt + aliases).
--
-- Gerado por _temp/gen_seed_189.mjs com lib/targets/derive.js
-- (2026-08-18).
-- 133 linhas: 52 substrato,
-- 59 inibidor,
-- 22 indutor.
--
-- Regra das fontes: source_pt de cada linha = fonte do alvo de origem
-- (DailyMed/EMC-UK/Health Canada/PubMed), NÃO é conteúdo inventado.
-- Idempotente (ON CONFLICT DO NOTHING). O admin revê em
-- /admin/alvos/drug-links e remove falsos positivos do parse.
-- =====================================================================

INSERT INTO public.drug_target_roles (drug_id, target_id, role, source_pt, status)
SELECT d.id, t.id, v.role, v.source_pt, 'published'
FROM (VALUES
  ('atorvastatina', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('tacrolimus', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('sirolimus', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('claritromicina', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('eritromicina', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('sildenafil', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('tadalafil', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('verapamilo', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('diltiazem', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('ivabradina', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('pimozida', 'cyp3a4', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('cetoconazol', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('itraconazol', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('fluconazol', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('claritromicina', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('eritromicina', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('ritonavir', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('amiodarona', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('diltiazem', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('verapamilo', 'cyp3a4', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('rifampicina', 'cyp3a4', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('carbamazepina', 'cyp3a4', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('fenobarbital', 'cyp3a4', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('dexametasona', 'cyp3a4', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados; EMC-UK (MHRA) — SmPC; PubMed (NIH/NLM)'),
  ('tramadol', 'cyp2d6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('flecainida', 'cyp2d6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('propafenona', 'cyp2d6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('haloperidol', 'cyp2d6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('fluoxetina', 'cyp2d6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('fluoxetina', 'cyp2d6', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('ritonavir', 'cyp2d6', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (codeína, fluoxetina); PubMed (NIH/NLM) — farmacogenética do CYP2D6'),
  ('acenocumarol', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('diclofenac', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('ibuprofeno', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('celecoxib', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('glibenclamida', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('glimepirida', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('losartano', 'cyp2c9', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('fluconazol', 'cyp2c9', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('voriconazol', 'cyp2c9', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('metronidazol', 'cyp2c9', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('amiodarona', 'cyp2c9', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('cotrimoxazol', 'cyp2c9', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('cimetidina', 'cyp2c9', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'cyp2c9', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('fenobarbital', 'cyp2c9', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('carbamazepina', 'cyp2c9', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (varfarina, fluconazol); EMC-UK (MHRA) — SmPC'),
  ('teofilina', 'cyp1a2', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('clozapina', 'cyp1a2', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('tizanidina', 'cyp1a2', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('ciprofloxacina', 'cyp1a2', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('cimetidina', 'cyp1a2', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('omeprazol', 'cyp1a2', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'cyp1a2', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (teofilina, ciprofloxacina); EMC-UK (MHRA) — SmPC'),
  ('clopidogrel', 'cyp2c19', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('omeprazol', 'cyp2c19', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('sertralina', 'cyp2c19', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('voriconazol', 'cyp2c19', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('omeprazol', 'cyp2c19', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('fluconazol', 'cyp2c19', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('cimetidina', 'cyp2c19', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'cyp2c19', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('carbamazepina', 'cyp2c19', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (clopidogrel, omeprazol); EMC-UK (MHRA) — SmPC'),
  ('pioglitazona', 'cyp2c8', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Repaglinida; EMC-UK (MHRA) — SmPC'),
  ('montelukast', 'cyp2c8', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Repaglinida; EMC-UK (MHRA) — SmPC'),
  ('cetoconazol', 'cyp2c8', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Repaglinida; EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'cyp2c8', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Repaglinida; EMC-UK (MHRA) — SmPC'),
  ('carbamazepina', 'cyp2c8', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Repaglinida; EMC-UK (MHRA) — SmPC'),
  ('efavirenz', 'cyp2b6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('ciclofosfamida', 'cyp2b6', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('clopidogrel', 'cyp2b6', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('voriconazol', 'cyp2b6', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'cyp2b6', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('fenobarbital', 'cyp2b6', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('carbamazepina', 'cyp2b6', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (efavirenz, bupropiona); EMC-UK (MHRA) — SmPC'),
  ('paracetamol', 'cyp2e1', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)'),
  ('isoniazida', 'cyp2e1', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)'),
  ('teofilina', 'cyp2e1', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)'),
  ('dissulfiram', 'cyp2e1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)'),
  ('cimetidina', 'cyp2e1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)'),
  ('isoniazida', 'cyp2e1', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Paracetamol; PubMed (NIH/NLM)'),
  ('aspirina', 'cox1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (aspirina, AINEs); EMC-UK (MHRA) — SmPC'),
  ('diclofenac', 'cox1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (aspirina, AINEs); EMC-UK (MHRA) — SmPC'),
  ('ibuprofeno', 'cox1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (aspirina, AINEs); EMC-UK (MHRA) — SmPC'),
  ('naproxeno', 'cox1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (aspirina, AINEs); EMC-UK (MHRA) — SmPC'),
  ('celecoxib', 'cox2', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Celecoxib; EMC-UK (MHRA) — SmPC'),
  ('digoxina', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('rivaroxabano', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('tacrolimus', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('sirolimus', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('loperamida', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('fexofenadina', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('colchicina', 'pgp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('amiodarona', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('claritromicina', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('eritromicina', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('cetoconazol', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('itraconazol', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('verapamilo', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('diltiazem', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('ritonavir', 'pgp', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'pgp', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('carbamazepina', 'pgp', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (digoxina, dabigatrano); EMC-UK (MHRA) — SmPC'),
  ('atorvastatina', 'bcrp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina; EMC-UK (MHRA) — SmPC'),
  ('metotrexato', 'bcrp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina; EMC-UK (MHRA) — SmPC'),
  ('sulfassalazina', 'bcrp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina; EMC-UK (MHRA) — SmPC'),
  ('alopurinol', 'bcrp', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina; EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'bcrp', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina; EMC-UK (MHRA) — SmPC'),
  ('atorvastatina', 'oatp1b1', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)'),
  ('metotrexato', 'oatp1b1', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)'),
  ('rifampicina', 'oatp1b1', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)'),
  ('claritromicina', 'oatp1b1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)'),
  ('ritonavir', 'oatp1b1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)'),
  ('rifampicina', 'oatp1b1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, rosuvastatina); PubMed (NIH/NLM)'),
  ('linezolida', 'maoa', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (IMAO); EMC-UK (MHRA) — SmPC'),
  ('acenocumarol', 'vkorc1', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulo aprovado Varfarina; PubMed (NIH/NLM)'),
  ('glicose', 'g6pd', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (primaquina, nitrofurantoína); PubMed (NIH/NLM)'),
  ('primaquina', 'g6pd', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (primaquina, nitrofurantoína); PubMed (NIH/NLM)'),
  ('tafenoquina', 'g6pd', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (primaquina, nitrofurantoína); PubMed (NIH/NLM)'),
  ('azatioprina', 'tpmt', 'substrate', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (azatioprina, alopurinol); PubMed (NIH/NLM)'),
  ('alopurinol', 'tpmt', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (azatioprina, alopurinol); PubMed (NIH/NLM)'),
  ('febuxostat', 'tpmt', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (azatioprina, alopurinol); PubMed (NIH/NLM)'),
  ('mesalazina', 'tpmt', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (azatioprina, alopurinol); PubMed (NIH/NLM)'),
  ('sulfassalazina', 'tpmt', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (azatioprina, alopurinol); PubMed (NIH/NLM)'),
  ('sildenafil', 'pde5', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (sildenafil, tadalafil); EMC-UK (MHRA) — SmPC'),
  ('tadalafil', 'pde5', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (sildenafil, tadalafil); EMC-UK (MHRA) — SmPC'),
  ('vardenafil', 'pde5', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (sildenafil, tadalafil); EMC-UK (MHRA) — SmPC'),
  ('claritromicina', 'hmgcr', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC'),
  ('cetoconazol', 'hmgcr', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC'),
  ('itraconazol', 'hmgcr', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC'),
  ('amiodarona', 'hmgcr', 'inhibitor', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC'),
  ('rifampicina', 'hmgcr', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC'),
  ('carbamazepina', 'hmgcr', 'inducer', 'DailyMed/FDA (NIH/NLM) — rótulos aprovados (simvastatina, atorvastatina); EMC-UK (MHRA) — SmPC')
) AS v(drug_slug, target_slug, role, source_pt)
JOIN public.drugs d ON d.slug = v.drug_slug
JOIN public.molecular_targets t ON t.slug = v.target_slug
ON CONFLICT (drug_id, target_id, role) DO NOTHING;
