-- =====================================================================
-- 191 — Expansão: 11 antirretrovirais novos (WHO EML)
--
-- Fármacos: tenofovir, emtricitabina, dolutegravir, lopinavir+ritonavir,
--           darunavir, abacavir, raltegravir, etravirina, rilpivirina,
--           estavudina, didanosina
-- Fontes: rótulos aprovados DailyMed/FDA (NIH/NLM), setIDs validados
--         na API durante sessão de pesquisa (2026-08-18)
-- Padrão: 7.3 (drugs) + 7.6 (profiles + pharmacology)
-- Idempotente: ON CONFLICT DO NOTHING / ON CONFLICT (drug_id) DO NOTHING
-- =====================================================================

-- =====================================================================
-- 1. Fármacos novos em public.drugs
-- =====================================================================
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order)
VALUES
  ('tenofovir', 'Tenofovir', 'Tenofovir', 'Antirretroviral nucleotídeo análogo da transcriptase reversa (NtRTI)', 'Antiretroviral nucleotide analogue reverse transcriptase inhibitor (NtRTI)', ARRAY['Viread', 'TDF', 'tenofovir disoproxil fumarate'], 'published', 120),
  ('emtricitabina', 'Emtricitabina', 'Emtricitabine', 'Antirretroviral nucleosídeo análogo da transcriptase reversa (NRTI)', 'Antiretroviral nucleoside analogue reverse transcriptase inhibitor (NRTI)', ARRAY['Emtriva', 'FTC'], 'published', 121),
  ('dolutegravir', 'Dolutegravir', 'Dolutegravir', 'Antirretroviral inibidor da integrase (INSTI)', 'Antiretroviral integrase strand transfer inhibitor (INSTI)', ARRAY['Tivicay', 'DTG'], 'published', 122),
  ('lopinavir-ritonavir', 'Lopinavir + Ritonavir', 'Lopinavir + Ritonavir', 'Antirretroviral inibidor da protease (IP)', 'Antiretroviral protease inhibitor (PI)', ARRAY['Kaletra', 'LPV/r'], 'published', 123),
  ('darunavir', 'Darunavir', 'Darunavir', 'Antirretroviral inibidor da protease (IP)', 'Antiretroviral protease inhibitor (PI)', ARRAY['Prezista', 'DRV'], 'published', 124),
  ('abacavir', 'Abacavir', 'Abacavir', 'Antirretroviral nucleosídeo análogo da transcriptase reversa (NRTI)', 'Antiretroviral nucleoside analogue reverse transcriptase inhibitor (NRTI)', ARRAY['Ziagen', 'ABC'], 'published', 125),
  ('raltegravir', 'Raltegravir', 'Raltegravir', 'Antirretroviral inibidor da integrase (INSTI)', 'Antiretroviral integrase strand transfer inhibitor (INSTI)', ARRAY['Isentress', 'RAL'], 'published', 126),
  ('etravirina', 'Etravirina', 'Etravirine', 'Antirretroviral inibidor não nucleósido da transcriptase reversa (INNTR)', 'Antiretroviral non-nucleoside reverse transcriptase inhibitor (NNRTI)', ARRAY['Intelence', 'ETV'], 'published', 127),
  ('rilpivirina', 'Rilpivirina', 'Rilpivirine', 'Antirretroviral inibidor não nucleósido da transcriptase reversa (INNTR)', 'Antiretroviral non-nucleoside reverse transcriptase inhibitor (NNRTI)', ARRAY['Edurant', 'RPV'], 'published', 128),
  ('estavudina', 'Estavudina', 'Stavudine', 'Antirretroviral nucleosídeo análogo da transcriptase reversa (NRTI)', 'Antiretroviral nucleoside analogue reverse transcriptase inhibitor (NRTI)', ARRAY['Zerit', 'd4T'], 'published', 129),
  ('didanosina', 'Didanosina', 'Didanosine', 'Antirretroviral nucleosídeo análogo da transcriptase reversa (NRTI)', 'Antiretroviral nucleoside analogue reverse transcriptase inhibitor (NRTI)', ARRAY['Videx', 'ddI'], 'published', 130)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 2. Perfis (drug_profiles)
-- =====================================================================
INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en, indications_pt, indications_en,
   side_effects_pt, side_effects_en, precautions_pt, precautions_en, source_pt, source_en, status)
SELECT d.id, v.overview_public_pt, v.overview_public_en,
  v.indications_pt, v.indications_en,
  v.side_effects_pt, v.side_effects_en,
  v.precautions_pt, v.precautions_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('tenofovir',
   'O tenofovir é um medicamento antirretroviral usado para tratar e prevenir a infecção pelo HIV. Pertence ao grupo dos nucleotídeos análogos da transcriptase reversa (NtRTI) e é frequentemente associado a outros antirretrovirais para compor o tratamento de primeira linha.',
   'Tenofovir is an antiretroviral medication used to treat and prevent HIV infection. It belongs to the nucleotide analogue reverse transcriptase inhibitor (NtRTI) class and is commonly combined with other antiretrovirals for first-line treatment.',
   'Tratamento da infecção pelo HIV-1 em adultos e adolescentes (em combinação com outros antirretrovirais)\nPrevenção da infecção pelo HIV-1 após exposição (profilaxia pós-exposição, PEP)\nTratamento da hepatite B crónica',
   'Treatment of HIV-1 infection in adults and adolescents (in combination with other antiretrovirals)\nPrevention of HIV-1 infection after exposure (post-exposure prophylaxis, PEP)\nTreatment of chronic hepatitis B',
   'Náuseas, vómitos, diarreia\nDor de cabeça\nTonturas\nFadiga\nErupção cutânea\nEfeitos nefrotóxicos (redução da densidade óssea, insuficiência renal em casos raros)',
   'Nausea, vomiting, diarrhoea\nHeadache\nDizziness\nFatigue\nRash\nNephrotoxic effects (decreased bone density, rare renal failure)',
   'Avaliar função renal antes de iniciar e durante o tratamento\nMonitorizar densidade óssea em doentes de risco\nRisco de acidose láctica (raro mas grave)\nNão suspender abruptamente em doentes com hepatite B co-infectados',
   'Assess renal function before initiating and during treatment\nMonitor bone density in at-risk patients\nRisk of lactic acidosis (rare but serious)\nDo not abruptly discontinue in patients co-infected with hepatitis B',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tenofovir (Viread): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418',
   'DailyMed/FDA (NIH/NLM) — approved Tenofovir (Viread) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418'),
  ('emtricitabina',
   'A emtricitabina é um antirretroviral do grupo dos nucleosídeos análogos da transcriptase reversa (NRTI). É utilizada em combinação com outros antirretrovirais para o tratamento do HIV e da hepatite B crónica.',
   'Emtricitabine is an antiretroviral of the nucleoside analogue reverse transcriptase inhibitor (NRTI) class. It is used in combination with other antiretrovirals for the treatment of HIV and chronic hepatitis B.',
   'Tratamento da infecção pelo HIV-1 em adultos, adolescentes e crianças (em combinação)\nTratamento da hepatite B crónica',
   'Treatment of HIV-1 infection in adults, adolescents and children (in combination)\nTreatment of chronic hepatitis B',
   'Cefaleia\nNáuseas, diarreia\nErupção cutânea (hiperpigmentação palmar e plantar)\nElevação das transaminases\nRaramente: acidose láctica, hepatomegalia com esteatose',
   'Headache\nNausea, diarrhoea\nRash (palmar and plantar hyperpigmentation)\nElevated transaminases\nRarely: lactic acidosis, hepatomegaly with steatosis',
   'Avaliar função renal antes de iniciar\nAjuste de dose em insuficiência renal\nRisco de acidose láctica\nNão suspender abruptamente em doentes com hepatite B co-infectados',
   'Assess renal function before initiation\nDose adjustment in renal impairment\nRisk of lactic acidosis\nDo not abruptly discontinue in patients co-infected with hepatitis B',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Emtricitabina (Emtriva): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f',
   'DailyMed/FDA (NIH/NLM) — approved Emtricitabine (Emtriva) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f'),
  ('dolutegravir',
   'O dolutegravir é um inibidor da integrase de nova geração, recomendado pela OMS como terapia de primeira linha para HIV. Tem elevada barreira genética à resistência e boa tolerabilidade.',
   'Dolutegravir is a next-generation integrase strand transfer inhibitor, recommended by WHO as first-line therapy for HIV. It has a high genetic barrier to resistance and good tolerability.',
   'Tratamento da infecção pelo HIV-1 em adultos, adolescentes e crianças (em combinação com outros antirretrovirais)\nProfylaxia pós-exposição (PEP)',
   'Treatment of HIV-1 infection in adults, adolescents and children (in combination with other antiretrovirals)\nPost-exposure prophylaxis (PEP)',
   'Cefaleia\nDiarreia\nNáuseas\nInsónia\nFadiga\nErupção cutânea\nRaramente: reações de hipersensibilidade',
   'Headache\nDiarrhoea\nNausea\nInsomnia\nFatigue\nRash\nRarely: hypersensitivity reactions',
   'Não requer ajuste de dose com insuficiência renal (mas monitorizar)\nEvitar comcarbamazepina, fenitoína, fenobarbital (induzem UGT1A1)\nTolerância alimentar — pode ser tomado com ou sem alimentos',
   'No dose adjustment required with renal impairment (but monitor)\nAvoid with carbamazepine, phenytoin, phenobarbital (induce UGT1A1)\nFood tolerance — can be taken with or without food',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dolutegravir (Tivicay): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921',
   'DailyMed/FDA (NIH/NLM) — approved Dolutegravir (Tivicay) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921'),
  ('lopinavir-ritonavir',
   'O lopinavir associado ao ritonavir é um inibidor da protease potenciado, amplamente utilizado no tratamento do HIV, especialmente em regime de segunda linha. O ritonavir inibe o CYP3A4, elevando os níveis do lopinavir.',
   'Lopinavir boosted with ritonavir is a potentiated protease inhibitor widely used in HIV treatment, especially in second-line regimens. Ritonavir inhibits CYP3A4, increasing lopinavir levels.',
   'Tratamento da infecção pelo HIV-1 em adultos, adolescentes e crianças (em combinação com outros antirretrovirais)',
   'Treatment of HIV-1 infection in adults, adolescents and children (in combination with other antiretrovirals)',
   'Diarreia\nNáuseas, vómitos\nDor abdominal\nCefaleia\nErupção cutânea\nHiperlipidemia (triglicéridos, colesterol)\nHiper glicemia\nPancreatite (rara)',
   'Diarrhoea\nNausea, vomiting\nAbdominal pain\nHeadache\nRash\nHyperlipidaemia (triglycerides, cholesterol)\nHyperglycaemia\nPancreatitis (rare)',
   'Potente inibidor do CYP3A4 — múltiplas interações medicamentosas\nNão usar com fármacos que dependam do CYP3A4 (estatinas, antiarrítmicos, etc.)\nMonitorizar perfil lipídico e glicémico\nRisco de pancreatite com triglicéridos elevados',
   'Potent CYP3A4 inhibitor — numerous drug interactions\nDo not use with CYP3A4-dependent drugs (statins, antiarrhythmics, etc.)\nMonitor lipid profile and glycaemia\nRisk of pancreatitis with elevated triglycerides',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lopinavir + Ritonavir (Kaletra): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3',
   'DailyMed/FDA (NIH/NLM) — approved Lopinavir + Ritonavir (Kaletra) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3'),
  ('darunavir',
   'O darunavir é um inibidor da protease de segunda geração, potenciado pelo ritonavir. Tem activity contra muitas estirpes resistentes a outros inibidores da protease e elevada barreira genética à resistência.',
   'Darunavir is a second-generation protease inhibitor, boosted by ritonavir. It has activity against many strains resistant to other protease inhibitors and a high genetic barrier to resistance.',
   'Tratamento da infecção pelo HIV-1 em adultos e adolescentes (em combinação com ritonavir e outros antirretrovirais)',
   'Treatment of HIV-1 infection in adults and adolescents (in combination with ritonavir and other antiretrovirals)',
   'Diarreia\nNáuseas\nCefaleia\nErupção cutânea\nDor abdominal\nFadiga\nHiperlipidemia',
   'Diarrhoea\nNausea\nHeadache\nRash\nAbdominal pain\nFatigue\nHyperlipidaemia',
   'Potenciado pelo ritonavir — mesmo perfil de interações do IP/r\nMonitorar função hepática\nRisco de erupção cutânea (suspender se grave)\nComprimidos não devem ser mastigados (amargos)',
   'Boosted by ritonavir — same interaction profile as PI/r\nMonitor liver function\nRisk of rash (discontinue if severe)\nTablets should not be chewed (bitter)',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Darunavir (Prezista): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f',
   'DailyMed/FDA (NIH/NLM) — approved Darunavir (Prezista) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f'),
  ('abacavir',
   'O abacavir é um nucleosídeo análogo da transcriptase reversa (NRTI) utilizado no tratamento do HIV. É importante notar o risco de reação de hipersensibilidade, que pode ser fatal se o fármaco não for suspensão imediatamente.',
   'Abacavir is a nucleoside analogue reverse transcriptase inhibitor (NRTI) used in HIV treatment. It is important to note the risk of hypersensitivity reaction, which can be fatal if the drug is not discontinued immediately.',
   'Tratamento da infecção pelo HIV-1 em adultos, adolescentes e crianças (em combinação com outros antirretrovirais)',
   'Treatment of HIV-1 infection in adults, adolescents and children (in combination with other antiretrovirals)',
   'Cefaleia\nNáuseas, vómitos\nDiarreia\nFadiga\nErupção cutânea\nReação de hipersensibilidade (febre, erupção cutânea, sintomas gastrointestinais, sintomas respiratórios)',
   'Headache\nNausea, vomiting\nDiarrhoea\nFatigue\nRash\nHypersensitivity reaction (fever, rash, gastrointestinal symptoms, respiratory symptoms)',
   'TESTE OBRIGATÓRIO HLA-B*5701 antes de iniciar — reduz o risco de reação de hipersensibilidade\nSE SUSPEITA DE HIPERSENSIBILIDADE: suspender IMEDIATAMENTE e NUNCA reintroduzir\nReação de hipersensibilidade pode ser fatal\nRisco de doença cardíaca (estudos epidemiológicos)',
   'MANDATORY HLA-B*5701 TESTING before initiation — reduces risk of hypersensitivity reaction\nIF HYPERSUSPECTED: discontinue IMMEDIATELY and NEVER rechallenge\nHypersensitivity reaction can be fatal\nRisk of cardiac disease (epidemiological studies)',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Abacavir (Ziagen): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1',
   'DailyMed/FDA (NIH/NLM) — approved Abacavir (Ziagen) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1'),
  ('raltegravir',
   'O raltegravir é um inibidor da integrase utilizado no tratamento do HIV. Atua bloqueando a enzima integrase, impedindo a integração do DNA viral no genoma da célula hospedeira.',
   'Raltegravir is an integrase inhibitor used in HIV treatment. It works by blocking the integrase enzyme, preventing integration of viral DNA into the host cell genome.',
   'Tratamento da infecção pelo HIV-1 em adultos, adolescentes e crianças (em combinação com outros antirretrovirais)',
   'Treatment of HIV-1 infection in adults, adolescents and children (in combination with other antiretrovirals)',
   'Cefaleia\nDiarreia\nNáuseas\nErupção cutânea\nInsónia\nFadiga\nDor muscular\nRaramente: elevação de creatinina cinase',
   'Headache\nDiarrhoea\nNausea\nRash\nInsomnia\nFatigue\nMuscle pain\nRarely: elevated creatine kinase',
   'Pode ser administrado com ou sem alimentos\nAjuste de dose em insuficiência renal\nMonitorizar creatinina cinase em doentes com sintomas musculares',
   'Can be administered with or without food\nDose adjustment in renal impairment\nMonitor creatine kinase in patients with muscle symptoms',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Raltegravir (Isentress): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3',
   'DailyMed/FDA (NIH/NLM) — approved Raltegravir (Isentress) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3'),
  ('etravirina',
   'A etravirina é um INNTR de segunda geração com activity contra estirpes do HIV resistentes à nevirapina e ao efavirenz. É utilizada em regimes de segunda linha.',
   'Etravirine is a second-generation NNRTI with activity against HIV strains resistant to nevirapine and efavirenz. It is used in second-line regimens.',
   'Tratamento da infecção pelo HIV-1 em adultos e adolescentes com estirpes resistentes a INNTR (em combinação com outros antirretrovirais)',
   'Treatment of HIV-1 infection in adults and adolescents with NNRTI-resistant strains (in combination with other antirretrovirals)',
   'Erupção cutânea (comum, pode ser grave)\nNáuseas\nDiarreia\nCefaleia\nDor abdominal\nFadiga',
   'Rash (common, can be severe)\nNausea\nDiarrhoea\nHeadache\nAbdominal pain\nFatigue',
   'Administrar após refeições ricas em gordura (aumenta absorção)\nMúltiplas interações — verificar com outros fármacos\nSuspender se erupção cutânea grave',
   'Administer after fatty meals (increases absorption)\nNumerous interactions — check with other drugs\nDiscontinue if severe rash',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etravirina (Intelence): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d',
   'DailyMed/FDA (NIH/NLM) — approved Etravirine (Intelence) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d'),
  ('rilpivirina',
   'A rilpivirina é um INNTR de nova geração com boa tolerabilidade e menor taxa de efeitos neuropsiquiátricos comparativamente ao efavirenz. Requer um carga viral baixa para ser eficaz.',
   'Rilpivirine is a next-generation NNRTI with good tolerability and lower rates of neuropsychiatric effects compared to efavirenz. Requires a low viral load for efficacy.',
   'Tratamento da infecção pelo HIV-1 em adultos e adolescentes com carga viral baixa (<100.000 cópias/mL) e sem mutações de resistência a INNTR (em combinação com outros antirretrovirais)',
   'Treatment of HIV-1 infection in adults and adolescents with low viral load (<100,000 copies/mL) and no NNRTI resistance mutations (in combination with other antirretrovirais)',
   'Cefaleia\nNáuseas\nDiarreia\nErupção cutânea\nInsónia\nDepressão\nRaramente: prolongamento do intervalo QT',
   'Headache\nNausea\nDiarrhoea\nRash\nInsomnia\nDepression\nRarely: QT interval prolongation',
   'Tomar com refeições (aumenta absorção significativamente)\nEvitar inibidores da bomba de protões (reduzem absorção)\nMúltiplas interações — verificar CYP3A4\nRisco de prolongamento do QT',
   'Take with food (significantly increases absorption)\nAvoid proton pump inhibitors (reduce absorption)\nNumerous interactions — check CYP3A4\nRisk of QT prolongation',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rilpivirina (Edurant): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6',
   'DailyMed/FDA (NIH/NLM) — approved Rilpivirine (Edurant) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6'),
  ('estavudina',
   'A stavudina é um NRTI de primeira geração, ainda utilizado em alguns contextos de recursos limitados, embora esteja a ser substituído por fármacos mais modernos devido a efeitos colaterais (toxicidade mitocondrial).',
   'Stavudine is a first-generation NRTI, still used in some resource-limited settings, although it is being replaced by newer drugs due to side effects (mitochondrial toxicity).',
   'Tratamento da infecção pelo HIV-1 em adultos e crianças (em combinação com outros antirretrovirais — regime de segunda/terceira linha)',
   'Treatment of HIV-1 infection in adults and children (in combination with other antiretrovirals — second/third-line regimen)',
   'Neuropatia periférica (comum)\nLipodistrofia (perda de gordura facial, acumulação abdominal)\nNáuseas, vómitos\nCefaleia\nFadiga\nPancreatite (rara)',
   'Peripheral neuropathy (common)\nLipodystrophy (facial fat loss, abdominal accumulation)\nNausea, vomiting\nHeadache\nFatigue\nPancreatitis (rare)',
   'SUBSTITUIR por fármacos mais modernos quando possível\nMonitorizar sintomas de neuropatia periférica\nRisco de pancreatite — suspender se sintomas abdominais graves\nEvitar em doentes com historial de neuropatia',
   'REPLACE with newer drugs when possible\nMonitor for peripheral neuropathy symptoms\nRisk of pancreatitis — discontinue if severe abdominal symptoms\nAvoid in patients with history of neuropathy',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estavudina (Zerit): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434',
   'DailyMed/FDA (NIH/NLM) — approved Stavudine (Zerit) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434'),
  ('didanosina',
   'A didanosina é um NRTI de primeira geração, raramente utilizado atualmente devido a efeitos colaterais significativos (pancreatite, neuropatia, acidose láctica). Foi substituída por fármacos mais modernos e melhor tolerados.',
   'Didanosine is a first-generation NRTI, rarely used currently due to significant side effects (pancreatitis, neuropathy, lactic acidosis). It has been replaced by newer, better-tolerated drugs.',
   'Tratamento da infecção pelo HIV-1 (raramente utilizado — regime de segunda/terceira linha quando outras opções estão esgotadas)',
   'Treatment of HIV-1 infection (rarely used — second/third-line regimen when other options are exhausted)',
   'Náuseas, vómitos, diarreia\nDor abdominal\nPancreatite\nNeuropatia periférica\nRetinopatia\nAcidose láctica\nHiperuricemia',
   'Nausea, vomiting, diarrhoea\nAbdominal pain\nPancreatitis\nPeripheral neuropathy\nRetinopathy\nLactic acidosis\nHyperuricaemia',
   'EFEITOS COLATERAIS GRAVES — substituir por fármacos mais modernos quando possível\nTomar em jejum (1h antes ou 2h após refeições)\nMonitorizar amilase, lipase, ácido úrico\nRisco de pancreatite — suspender imediatamente se dor abdominal',
   'SERIOUS SIDE EFFECTS — replace with newer drugs when possible\nTake on empty stomach (1h before or 2h after meals)\nMonitor amylase, lipase, uric acid\nRisk of pancreatitis — discontinue immediately if abdominal pain',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Didanosina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67',
   'DailyMed/FDA (NIH/NLM) — approved Didanosine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67')
) AS v(slug, overview_public_pt, overview_public_en, indications_pt, indications_en,
      side_effects_pt, side_effects_en, precautions_pt, precautions_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- 3. Farmacologia (drug_pharmacology)
-- =====================================================================
INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en,
   mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en,
   absorption_pt, absorption_en,
   half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id,
  v.pharmacodynamics_pt, v.pharmacodynamics_en,
  v.mechanism_pt, v.mechanism_en,
  v.metabolism_pt, v.metabolism_en,
  v.absorption_pt, v.absorption_en,
  v.half_life_pt, v.half_life_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('tenofovir',
   'O tenofovir é um análogo nucleotídico da adenina que inibe a transcriptase reversa do HIV-1 e do HBV, competindo com o substrato natural (desoxiadenosina trifosfato).',
   'Tenofovir is an adenine nucleotide analogue that inhibits HIV-1 and HBV reverse transcriptase, competing with the natural substrate (deoxyadenosine triphosphate).',
   'Fosforilado intracelularmente ao trifosfato ativo (tenofovir diphosphate), que incorpora-se no DNA viral e provoca terminação da cadeia (ausência do grupo 3-OH). Atua também como inibidor competidor da transcriptase reversa.',
   'Intracellularly phosphorylated to the active diphosphate (tenofovir diphosphate), which incorporates into viral DNA and causes chain termination (absence of the 3-OH group). Also acts as a competitive inhibitor of reverse transcriptase.',
   'Metabolizado minimamente — excretado essencialmente na forma inalterada por via renal (tubular proximal). Não sofre metabolismo hepático significativo. Potencial de interações medicamentosas baixo (não inibe CYP).',
   'Minimally metabolised — excreted essentially unchanged by the renal route (proximal tubular). Does not undergo significant hepatic metabolism. Low drug interaction potential (does not inhibit CYP).',
   'Biodisponibilidade oral: 25% (após administração de tenofovir disoproxil). Alimentos aumentam a absorção (Tmax 0,58-4h). Liga-se às proteínas plasmáticas <1%.',
   'Oral bioavailability: 25% (after tenofovir disoproxil administration). Food increases absorption (Tmax 0.58-4h). Plasma protein binding <1%.',
   '12-17 horas (trifosfato intracelular: >60 horas). Eliminação renal (clcr 51-130 mL/min: 99% excretado na urina).',
   '12-17 hours (intracellular diphosphate: >60 hours). Renal elimination (crcl 51-130 mL/min: 99% excreted in urine).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tenofovir (Viread), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418',
   'DailyMed/FDA (NIH/NLM) — approved Tenofovir (Viread) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418'),
  ('emtricitabina',
   'A emtricitabina é um nucleosídeo análogo da citosina que inibe a transcriptase reversa do HIV-1 e do HBV, atuando como substrato e inibidor da enzima.',
   'Emtricitabine is a cytosine nucleoside analogue that inhibits HIV-1 and HBV reverse transcriptase, acting as both a substrate and inhibitor of the enzyme.',
   'Fosforilado intracelularmente à trifosfato ativo (emtricitabine triphosphate), que se incorpora no DNA viral e provoca terminação da cadeia por ausência do grupo 3-OH. Tem semi-vida intracelular longa, permitindo dose diária.',
   'Intracellularly phosphorylated to the active triphosphate (emtricitabine triphosphate), which incorporates into viral DNA and causes chain termination by absence of the 3-OH group. Has a long intracellular half-life, allowing once-daily dosing.',
   'Metabolizado minimamente — cerca de 86% excretado inalterado na urina e 14% nas fezes. Não sofre metabolismo hepático significativo. Baixo potencial de interações (não inibe CYP).',
   'Minimally metabolised — approximately 86% excreted unchanged in urine and 14% in faeces. Does not undergo significant hepatic metabolism. Low interaction potential (does not inhibit CYP).',
   'Biodisponibilidade oral: 93% (cápsulas) e 75% (solução oral). Alimentos não afetam significativamente a absorção. Tmax: 1-2 horas.',
   'Oral bioavailability: 93% (capsules) and 75% (oral solution). Food does not significantly affect absorption. Tmax: 1-2 hours.',
   '9-14 horas. Eliminação renal: 86% inalterado na urina (clearance renal > clearance glomerular — secreção tubular).',
   '9-14 hours. Renal elimination: 86% unchanged in urine (renal clearance > glomerular clearance — tubular secretion).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Emtricitabina (Emtriva), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f',
   'DailyMed/FDA (NIH/NLM) — approved Emtricitabine (Emtriva) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f'),
  ('dolutegravir',
   'O dolutegravir é um inibidor da integrase que se liga ao sítio ativo da integrase do HIV-1, bloqueando a transferência de filamento de DNA — etapa essencial para a integração do DNA viral no genoma da célula hospedeira.',
   'Dolutegravir is an integrase inhibitor that binds to the active site of HIV-1 integrase, blocking strand transfer — an essential step for integration of viral DNA into the host cell genome.',
   'Metabolizado pelo UGT1A1 (glucuronização) e CYP3A4 (oxidação). Induzido por rifampicina, carbamazepina, fenitoína, fenobarbital (via UGT1A1). Não requer ritonavir como potenciador.',
   'Metabolised by UGT1A1 (glucuronidation) and CYP3A4 (oxidation). Induced by rifampicin, carbamazepine, phenytoin, phenobarbital (via UGT1A1). Does not require ritonavir as a booster.',
   'Absorção oral rápida. Biodisponibilidade: ~63%. Tmax: 2-3 horas. Alimentos não afetam significativamente a absorção. Pode ser administrado com ou sem alimentos.',
   'Rapid oral absorption. Bioavailability: ~63%. Tmax: 2-3 hours. Food does not significantly affect absorption. Can be taken with or without food.',
   '14 horas (33 horas para o metabolito葡萄糖醛酸). Eliminação: 53% fezes, 33% urina (metabolitos). Não requer ajuste de dose na maioria dos casos.',
   '14 hours (33 hours for glucuronide metabolite). Elimination: 53% faeces, 33% urine (metabolites). No dose adjustment required in most cases.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dolutegravir (Tivicay), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921',
   'DailyMed/FDA (NIH/NLM) — approved Dolutegravir (Tivicay) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921'),
  ('lopinavir-ritonavir',
   'O lopinavir é um inibidor da protease que se liga ao sítio ativo da protease do HIV-1, impedindo o processamento das poliproteínas virais (Gag e Gag-Pol). O ritonavir potencia o lopinavir inibindo o CYP3A4.',
   'Lopinavir is a protease inhibitor that binds to the active site of HIV-1 protease, preventing processing of viral polyproteins (Gag and Gag-Pol). Ritonavir boosts lopinavir by inhibiting CYP3A4.',
   'O lopinavir é metabolizado pelo CYP3A4. O ritonavir inibe potente e irreversivelmente o CYP3A4, elevando os níveis plasmáticos do lopinavir em ~100 vezes. A combinação permite dose mais baixa e menor frequência.',
   'Lopinavir is metabolised by CYP3A4. Ritonavir potently and irreversibly inhibits CYP3A4, increasing lopinavir plasma levels by ~100-fold. The combination allows lower dose and less frequent dosing.',
   'Biodisponibilidade oral aumentada pela presença de alimentos (48%). Tmax: 4-6 horas. Liga-se às proteínas plasmáticas 98-99%. Volume de distribuição: 0,17 L/kg.',
   'Oral bioavailability increased by food presence (48%). Tmax: 4-6 hours. Plasma protein binding 98-99%. Volume of distribution: 0.17 L/kg.',
   'Meia-vida: 5-6 horas (com ritonavir). Eliminação: ~80% fezes, ~10% urina (metabolitos). Perfil lipídico deve ser monitorizado.',
   'Half-life: 5-6 hours (with ritonavir). Elimination: ~80% faeces, ~10% urine (metabolites). Lipid profile should be monitored.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lopinavir + Ritonavir (Kaletra), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3',
   'DailyMed/FDA (NIH/NLM) — approved Lopinavir + Ritonavir (Kaletra) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3'),
  ('darunavir',
   'O darunavir é um inibidor da protease que se liga a múltiplos resíduos da protease do HIV-1, mantendo activity contra estirpes resistentes a outros IP. Tem elevada barreira genética à resistência.',
   'Darunavir is a protease inhibitor that binds to multiple residues of HIV-1 protease, maintaining activity against strains resistant to other PIs. It has a high genetic barrier to resistance.',
   'Metabolizado pelo CYP3A4 (principalmente) e CYP2D6. Potenciado pelo ritonavir ou cobicistat (inibidores do CYP3A4). A dose é ajustada consoante o potenciador usado.',
   'Metabolised by CYP3A4 (primarily) and CYP2D6. Boosted by ritonavir or cobicistat (CYP3A4 inhibitors). Dose is adjusted depending on the booster used.',
   'Biodisponibilidade oral: 82% (com ritonavir). Tmax: 2,5-4 horas. Alimentos aumentam ligeiramente a absorção. Liga-se às proteínas plasmáticas 95%.',
   'Oral bioavailability: 82% (with ritonavir). Tmax: 2.5-4 hours. Food slightly increases absorption. Plasma protein binding 95%.',
   'Meia-vida: 15 horas (com ritonavir). Eliminação: ~80% fezes, ~14% urina. Monitorizar perfil lipídico.',
   'Half-life: 15 hours (with ritonavir). Elimination: ~80% faeces, ~14% urine. Monitor lipid profile.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Darunavir (Prezista), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f',
   'DailyMed/FDA (NIH/NLM) — approved Darunavir (Prezista) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f'),
  ('abacavir',
   'O abacavir é um nucleosídeo análogo da guanosina que inibe a transcriptase reversa do HIV-1, após ativação intracelular ao trifosfato ativo.',
   'Abacavir is a guanosine nucleoside analogue that inhibits HIV-1 reverse transcriptase, after intracellular activation to the active triphosphate.',
   'Fosforilado intracelularmente ao trifosfato ativo (carbovir triphosphate), que se incorpora no DNA viral e provoca terminação da cadeia. Não requer fosforilação inicial pelas quinases celulares (diferente de outros NRTI).',
   'Intracellularly phosphorylated to the active triphosphate (carbovir triphosphate), which incorporates into viral DNA and causes chain termination. Does not require initial phosphorylation by cellular kinases (unlike other NRTIs).',
   'Metabolizado pelo álcool desidrogenase e UGT1A1 ao metabolito carboxilato (principal metabolito, 66% na urina). Metabolismo oxidativo pelo CYP3A4 é secundário.',
   'Metabolised by alcohol dehydrogenase and UGT1A1 to the carboxylate metabolite (major metabolite, 66% in urine). Oxidative metabolism by CYP3A4 is secondary.',
   'Biodisponibilidade oral: 83%. Tmax: 1-1,5 horas. Alimentos não afetam significativamente a absorção. Pode ser administrado com ou sem alimentos.',
   'Oral bioavailability: 83%. Tmax: 1-1.5 hours. Food does not significantly affect absorption. Can be taken with or without food.',
   '1,5-2 horas. Eliminação: ~66% urina (metabolitos), ~12% fezes. Não requer ajuste de dose na insuficiência renal leve-moderada.',
   '1.5-2 hours. Elimination: ~66% urine (metabolites), ~12% faeces. No dose adjustment required in mild-moderate renal impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Abacavir (Ziagen), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1',
   'DailyMed/FDA (NIH/NLM) — approved Abacavir (Ziagen) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1'),
  ('raltegravir',
   'O raltegravir é um inibidor da integrase que se liga ao sítio ativo da integrase do HIV-1, bloqueando a transferência de filamento de DNA — impedindo a integração do DNA viral no genoma da célula hospedeira.',
   'Raltegravir is an integrase inhibitor that binds to the active site of HIV-1 integrase, blocking strand transfer — preventing integration of viral DNA into the host cell genome.',
   'Metabolizado principalmente por UGT1A1 (glucuronização). Não é metabolizado pelo CYP3A4. Induzido por rifampicina (via UGT1A1). Elevação da creatinina sérica (inibe a secreção tubular — sem efeito na TFG real).',
   'Metabolised primarily by UGT1A1 (glucuronidation). Not metabolised by CYP3A4. Induced by rifampicin (via UGT1A1). Elevated serum creatinine (inhibits tubular secretion — no effect on actual GFR).',
   'Biodisponibilidade oral: ~60%. Tmax: 1-2 horas (comprimidos 400mg); 2-5 horas (comprimidos 600mg). Alimentos não afetam significativamente a absorção.',
   'Oral bioavailability: ~60%. Tmax: 1-2 hours (400mg tablets); 2-5 hours (600mg tablets). Food does not significantly affect absorption.',
   '9 horas. Eliminação: 51% fezes (metabolitos), 32% urina (metabolitos). Apenas ~2% excretado inalterado.',
   '9 hours. Elimination: 51% faeces (metabolites), 32% urine (metabolites). Only ~2% excreted unchanged.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Raltegravir (Isentress), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3',
   'DailyMed/FDA (NIH/NLM) — approved Raltegravir (Isentress) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3'),
  ('etravirina',
   'A etravirina é um INNTR de segunda geração que se liga a múltiplos sítios da transcriptase reversa do HIV-1, mantendo activity contra estirpes com mutações K103N e Y181C (resistentes à nevirapina e efavirenz).',
   'Etravirine is a second-generation NNRTI that binds to multiple sites of HIV-1 reverse transcriptase, maintaining activity against strains with K103N and Y181C mutations (resistant to nevirapine and efavirenz).',
   'Metabolizado pelo CYP3A4, CYP2C9 e CYP2C19. Induzido por rifampicina, rifabutina, fenitoína, carbamazepina, fenobarbital. Inibido por cimetidina.',
   'Metabolised by CYP3A4, CYP2C9 and CYP2C19. Induced by rifampicin, rifabutin, phenytoin, carbamazepine, phenobarbital. Inhibited by cimetidine.',
   'Biodisponibilidade oral: aumentada significativamente por alimentos ricos em gordura (50% vs jejum). Tmax: 2,5-4 horas. Comprimidos devem ser mastigados ou triturados.',
   'Oral bioavailability: significantly increased by fatty food (50% vs fasting). Tmax: 2.5-4 hours. Tablets should be chewed or crushed.',
   '~41 horas. Eliminação: 92% fezes (metabolitos), 10% urina. Meia-vida longa permite dose duas vezes ao dia.',
   '~41 hours. Elimination: 92% faeces (metabolites), 10% urine. Long half-life allows twice-daily dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etravirina (Intelence), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d',
   'DailyMed/FDA (NIH/NLM) — approved Etravirine (Intelence) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d'),
  ('rilpivirina',
   'A rilpivirina é um INNTR de nova geração que se liga à transcriptase reversa do HIV-1 com alta afinidade, bloqueando a síntese de DNA viral. Tem menor propensão a mutações de resistência comparativamente a NNRTIs de primeira geração.',
   'Rilpivirine is a next-generation NNRTI that binds to HIV-1 reverse transcriptase with high affinity, blocking viral DNA synthesis. Has lower propensity for resistance mutations compared to first-generation NNRTIs.',
   'Metabolizado pelo CYP3A4 (principalmente). Induzido por rifampicina, rifabutina, carbamazepina, fenitoína, fenobarbital. Inibido por inibidores do CYP3A4 (ketoconazol, eritromicina).',
   'Metabolised by CYP3A4 (primarily). Induced by rifampicin, rifabutin, carbamazepine, phenytoin, phenobarbital. Inhibited by CYP3A4 inhibitors (ketoconazole, erythromycin).',
   'Biodisponibilidade oral: significativamente aumentada por alimentos (79% vs jejum). Tmax: 4-5 horas. DEVE ser tomado com uma refeição que contenha gordura.',
   'Oral bioavailability: significantly increased by food (79% vs fasting). Tmax: 4-5 hours. MUST be taken with a meal containing fat.',
   '~50 horas. Eliminação: 85% fezes (metabolitos), <10% urina. Meia-vida longa permite dose diária.',
   '~50 hours. Elimination: 85% faeces (metabolites), <10% urine. Long half-life allows once-daily dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rilpivirina (Edurant), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6',
   'DailyMed/FDA (NIH/NLM) — approved Rilpivirine (Edurant) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6'),
  ('estavudina',
   'A stavudina é um nucleosídeo análogo da timidina que inibe a transcriptase reversa do HIV-1 após fosforilação intracelular ao trifosfato ativo (stavudine triphosphate).',
   'Stavudine is a thymidine nucleoside analogue that inhibits HIV-1 reverse transcriptase after intracellular phosphorylation to the active triphosphate (stavudine triphosphate).',
   'Fosforilado intracelularmente por quinases celulares ao trifosfato ativo, que se incorpora no DNA viral e provoca terminação da cadeia. Metabolizado pelo CYP2C9 e CYP3A4 (metabolismo hepático mínimo).',
   'Intracellularly phosphorylated by cellular kinases to the active triphosphate, which incorporates into viral DNA and causes chain termination. Metabolised by CYP2C9 and CYP3A4 (minimal hepatic metabolism).',
   'Biodisponibilidade oral: >80%. Tmax: 0,5-1,5 horas. Alimentos não afetam significativamente a absorção.',
   'Oral bioavailability: >80%. Tmax: 0.5-1.5 hours. Food does not significantly affect absorption.',
   '0,6-1,6 horas. Eliminação: ~70% urina (metabolitos). Muito curta — requer dose duas vezes ao dia.',
   '0.6-1.6 hours. Elimination: ~70% urine (metabolites). Very short — requires twice-daily dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estavudina (Zerit), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434',
   'DailyMed/FDA (NIH/NLM) — approved Stavudine (Zerit) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434'),
  ('didanosina',
   'A didanosina é um nucleosídeo análogo da adenina que inibe a transcriptase reversa do HIV-1 após fosforilação intracelular ao trifosfato ativo (didanosine triphosphate).',
   'Didanosine is an adenine nucleoside analogue that inhibits HIV-1 reverse transcriptase after intracellular phosphorylation to the active triphosphate (didanosine triphosphate).',
   'Fosforilado intracelularmente ao trifosfato ativo, que se incorpora no DNA viral e provoca terminação da cadeia. Metabolizado pelo CYP3A4 e excretado principalmente por via renal.',
   'Intracellularly phosphorylated to the active triphosphate, which incorporates into viral DNA and causes chain termination. Metabolised by CYP3A4 and primarily eliminated by the renal route.',
   'Biodisponibilidade oral: 20-40% (comprimidos). Alimentos reduzem a absorção significativamente — deve ser administrado em jejum. Cápsulas de liberação retardada: biodisponibilidade ~60%.',
   'Oral bioavailability: 20-40% (tablets). Food significantly reduces absorption — should be administered on an empty stomach. Delayed-release capsules: bioavailability ~60%.',
   '1,5 horas (comprimidos); 6 horas (cápsulas de liberação retardada). Eliminação: ~55% urina (metabolitos). Curta meia-vida — requer dose duas vezes ao dia.',
   '1.5 hours (tablets); 6 hours (delayed-release capsules). Elimination: ~55% urine (metabolites). Short half-life — requires twice-daily dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Didanosina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67',
   'DailyMed/FDA (NIH/NLM) — approved Didanosine label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67')
) AS v(slug,
  pharmacodynamics_pt, pharmacodynamics_en,
  mechanism_pt, mechanism_en,
  metabolism_pt, metabolism_en,
  absorption_pt, absorption_en,
  half_life_pt, half_life_en,
  source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
