-- =====================================================================
-- 193 — Expansão: dimensões (alimento/doença/gravidez) dos 11 ARVs novos
--
-- Fontes: DailyMed/FDA (NIH/NLM) — rótulos aprovados
-- EMC-UK (MHRA) — SmPCs europeias (corroboração)
-- Padrão: 7.6 (JOIN ON d.slug = v.slug)
-- Idempotente: ON CONFLICT DO NOTHING
-- =====================================================================

-- =====================================================================
-- 1. Interações Alimento/Bebida (drug_food_interactions)
-- =====================================================================
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en, severity, mechanism_pt, mechanism_en,
   advice_pt, advice_en, source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en, v.severity,
  v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
  v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('tenofovir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos aumentam ligeiramente a absorção do tenofovir (25% vs jejum), mas o efeito é clinicamente insignificante.',
   'Food slightly increases tenofovir absorption (25% vs fasting), but the effect is clinically insignificant.',
   'Pode ser administrado com ou sem alimentos.',
   'Can be taken with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tenofovir (Viread): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418',
   'DailyMed/FDA (NIH/NLM) — approved Tenofovir (Viread) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418', 1),
  ('emtricitabina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos não afetam significativamente a absorção da emtricitabina.',
   'Food does not significantly affect emtricitabine absorption.',
   'Pode ser administrado com ou sem alimentos.',
   'Can be taken with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Emtricitabina (Emtriva): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f',
   'DailyMed/FDA (NIH/NLM) — approved Emtricitabine (Emtriva) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f', 1),
  ('dolutegravir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos não afetam significativamente a absorção do dolutegravir.',
   'Food does not significantly affect dolutegravir absorption.',
   'Pode ser administrado com ou sem alimentos.',
   'Can be taken with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dolutegravir (Tivicay): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921',
   'DailyMed/FDA (NIH/NLM) — approved Dolutegravir (Tivicay) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921', 1),
  ('rilpivirina', 'alimentos_gordura', 'Alimentos ricos em gordura', 'Fatty foods', 'moderate',
   'A rilpivirina requer alimentos ricos em gordura para absorção adequada. Sem gordura, a biodisponibilidade reduz ~50%.',
   'Rilpivirine requires fatty foods for adequate absorption. Without fat, bioavailability decreases ~50%.',
   'Tomar sempre com uma refeição que contenha gordura (ex.: leite, manteiga, azeite).',
   'Always take with a meal containing fat (e.g. milk, butter, olive oil).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rilpivirina (Edurant): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6',
   'DailyMed/FDA (NIH/NLM) — approved Rilpivirine (Edurant) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6', 1),
  ('etravirina', 'alimentos_gordura', 'Alimentos ricos em gordura', 'Fatty foods', 'moderate',
   'A etravirina tem absorção significativamente aumentada por alimentos ricos em gordura (50% vs jejum).',
   'Etravirine has significantly increased absorption with fatty food (50% vs fasting).',
   'Tomar após refeições ricas em gordura. Os comprimidos devem ser mastigados ou triturados.',
   'Take after fatty meals. Tablets should be chewed or crushed.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etravirina (Intelence): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d',
   'DailyMed/FDA (NIH/NLM) — approved Etravirine (Intelence) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d', 1),
  ('abacavir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos não afetam significativamente a absorção do abacavir.',
   'Food does not significantly affect abacavir absorption.',
   'Pode ser administrado com ou sem alimentos.',
   'Can be taken with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Abacavir (Ziagen): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1',
   'DailyMed/FDA (NIH/NLM) — approved Abacavir (Ziagen) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1', 1),
  ('didanosina', 'alimentos', 'Alimentos', 'Food', 'moderate',
   'Alimentos reduzem significativamente a absorção da didanosina. Deve ser administrado em jejum.',
   'Food significantly reduces didanosine absorption. Should be administered on an empty stomach.',
   'Administrar em jejum: 1h antes ou 2h após refeições.',
   'Administer on empty stomach: 1h before or 2h after meals.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Didanosina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67',
   'DailyMed/FDA (NIH/NLM) — approved Didanosine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67', 1),
  ('estavudina', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos não afetam significativamente a absorção da estavudina.',
   'Food does not significantly affect stavudine absorption.',
   'Pode ser administrado com ou sem alimentos.',
   'Can be taken with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estavudina (Zerit): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434',
   'DailyMed/FDA (NIH/NLM) — approved Stavudine (Zerit) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434', 1),
  ('lopinavir-ritonavir', 'alimentos', 'Alimentos', 'Food', 'moderate',
   'Alimentos aumentam a absorção do lopinavir em 48%. Pode ser administrado com ou sem alimentos, mas a consistência é recomendada.',
   'Food increases lopinavir absorption by 48%. Can be taken with or without food, but consistency is recommended.',
   'Tomar sempre com alimentos ou sempre sem alimentos para manter níveis consistentes.',
   'Always take with food or always without food to maintain consistent levels.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lopinavir + Ritonavir (Kaletra): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3',
   'DailyMed/FDA (NIH/NLM) — approved Lopinavir + Ritonavir (Kaletra) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3', 1),
  ('darunavir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos aumentam ligeiramente a absorção do darunavir. Pode ser administrado com ou sem alimentos.',
   'Food slightly increases darunavir absorption. Can be taken with or without food.',
   'Pode ser administrado com ou sem alimentos. Não mastigar nem triturar os comprimidos.',
   'Can be taken with or without food. Do not chew or crush the tablets.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Darunavir (Prezista): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f',
   'DailyMed/FDA (NIH/NLM) — approved Darunavir (Prezista) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f', 1),
  ('raltegravir', 'alimentos', 'Alimentos', 'Food', 'minor',
   'Alimentos não afetam significativamente a absorção do raltegravir.',
   'Food does not significantly affect raltegravir absorption.',
   'Pode ser administrado com ou sem alimentos.',
   'Can be taken with or without food.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Raltegravir (Isentress): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3',
   'DailyMed/FDA (NIH/NLM) — approved Raltegravir (Isentress) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3', 1)
) AS v(slug, entity_slug, entity_pt, entity_en, severity, mechanism_pt, mechanism_en,
       advice_pt, advice_en, source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- =====================================================================
-- 2. Interações Doença/Condição (drug_disease_interactions)
-- =====================================================================
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en, interaction_type, severity,
   reason_pt, reason_en, advice_pt, advice_en, source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en, v.interaction_type, v.severity,
  v.reason_pt, v.reason_en, v.advice_pt, v.advice_en,
  v.source_pt, v.source_en, v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  ('tenofovir', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment', 'contraindication', 'critical',
   'O tenofovir é nefrotóxico e eliminado por via renal. Insuficiência renal aumenta o risco de toxicidade.',
   'Tenofovir is nephrotoxic and renally eliminated. Renal impairment increases the risk of toxicity.',
   'Avaliar TFG antes de iniciar. Contraindicado se TFG <30 mL/min. Ajustar intervalo de dose conforme TFG.',
   'Assess GFR before initiation. Contraindicated if GFR <30 mL/min. Adjust dosing interval according to GFR.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tenofovir (Viread): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418',
   'DailyMed/FDA (NIH/NLM) — approved Tenofovir (Viread) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418', 1),
  ('tenofovir', 'hepatite_b', 'Hepatite B', 'Hepatitis B', 'precaution', 'moderate',
   'Suspensão abrupta pode causar exacerbação grave da hepatite B. Monitorar carga viral do HBV.',
   'Abrupt discontinuation may cause severe hepatitis B exacerbation. Monitor HBV viral load.',
   'NÃO suspender abruptamente em doentes com hepatite B co-infectados. Considerar terapia anti-HBV concomitante.',
   'DO NOT abruptly discontinue in patients co-infected with hepatitis B. Consider concomitant anti-HBV therapy.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tenofovir (Viread): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418',
   'DailyMed/FDA (NIH/NLM) — approved Tenofovir (Viread) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418', 2),
  ('emtricitabina', 'hepatite_b', 'Hepatite B', 'Hepatitis B', 'precaution', 'moderate',
   'Suspensão abrupta pode causar exacerbação grave da hepatite B. Monitorar carga viral do HBV.',
   'Abrupt discontinuation may cause severe hepatitis B exacerbation. Monitor HBV viral load.',
   'NÃO suspender abruptamente em doentes com hepatite B co-infectados.',
   'DO NOT abruptly discontinue in patients co-infected with hepatitis B.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Emtricitabina (Emtriva): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f',
   'DailyMed/FDA (NIH/NLM) — approved Emtricitabine (Emtriva) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f', 1),
  ('abacavir', 'hipersensibilidade_hla', 'Hipersensibilidade ao abacavir (HLA-B*5701)', 'Abacavir hypersensitivity (HLA-B*5701)', 'contraindication', 'critical',
   'Doentes positivos para HLA-B*5701 têm risco elevado de reação de hipersensibilidade ao abacavir, que pode ser fatal.',
   'HLA-B*5701-positive patients are at high risk of abacavir hypersensitivity reaction, which can be fatal.',
   'TESTE OBRIGATÓRIO HLA-B*5701 antes de iniciar. Se positivo, CONTRAINDICADO. Suspender IMEDIATAMENTE se suspeita de hipersensibilidade.',
   'MANDATORY HLA-B*5701 testing before initiation. If positive, CONTRAINDICATED. Discontinue IMMEDIATELY if hypersensitivity suspected.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Abacavir (Ziagen): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1',
   'DailyMed/FDA (NIH/NLM) — approved Abacavir (Ziagen) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1', 1),
  ('estavudina', 'neuropatia_periferica', 'Neuropatia periférica', 'Peripheral neuropathy', 'precaution', 'moderate',
   'A estavudina causa neuropatia periférica em 15-20% dos doentes. Doentes com neuropatia pré-existente têm risco aumentado.',
   'Stavudine causes peripheral neuropathy in 15-20% of patients. Patients with pre-existing neuropathy are at increased risk.',
   'Evitar em doentes com neuropatia periférica pré-existente. Suspender se surgirem sintomas.',
   'Avoid in patients with pre-existing peripheral neuropathy. Discontinue if symptoms develop.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estavudina (Zerit): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434',
   'DailyMed/FDA (NIH/NLM) — approved Stavudine (Zerit) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434', 1),
  ('didanosina', 'pancreatite', 'Pancreatite', 'Pancreatitis', 'precaution', 'moderate',
   'A didanosina pode causar pancreatite. Doentes com historial de pancreatite têm risco aumentado.',
   'Didanosine can cause pancreatitis. Patients with a history of pancreatitis are at increased risk.',
   'Evitar em doentes com historial de pancreatite. Suspender imediatamente se dor abdominal grave ou elevação de amilase.',
   'Avoid in patients with a history of pancreatitis. Discontinue immediately if severe abdominal pain or amylase elevation.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Didanosina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67',
   'DailyMed/FDA (NIH/NLM) — approved Didanosine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67', 1)
) AS v(slug, condition_slug, condition_pt, condition_en, interaction_type, severity,
       reason_pt, reason_en, advice_pt, advice_en, source_pt, source_en, sort_order)
ON d.slug = v.slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- =====================================================================
-- 3. Gravidez/Lactação (drug_pregnancy_info)
-- =====================================================================
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en,
  v.trimester_pt, v.trimester_en, v.lactation_pt, v.lactation_en,
  v.contraception_pt, v.contraception_en, v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('tenofovir', 'caution',
   'Dados limitados em humanos. Estudos em animais não demonstraram teratogenicidade. A OMS recomenda o uso durante a gravidez quando o benefício justifica o risco.',
   'Limited human data. Animal studies did not demonstrate teratogenicity. WHO recommends use during pregnancy when benefit outweighs risk.',
   'Pode ser usado em todos os trimestres quando indicado para tratamento do HIV. Monitorizar função renal.',
   'Can be used in all trimesters when indicated for HIV treatment. Monitor renal function.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas para evitar transmissão vertical.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers to prevent vertical transmission.',
   'Métodos contraceptivos fiáveis são recomendados durante o tratamento.',
   'Reliable contraceptive methods are recommended during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Tenofovir (Viread): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418',
   'DailyMed/FDA (NIH/NLM) — approved Tenofovir (Viread) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=33fd6418-fbdc-42ca-a50d-ce2a476a5418'),
  ('emtricitabina', 'caution',
   'Dados limitados em humanos. Estudos em animais não demonstraram teratogenicidade. A OMS recomenda o uso durante a gravidez.',
   'Limited human data. Animal studies did not demonstrate teratogenicity. WHO recommends use during pregnancy.',
   'Pode ser usado em todos os trimestres quando indicado.',
   'Can be used in all trimesters when indicated.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Emtricitabina (Emtriva): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f',
   'DailyMed/FDA (NIH/NLM) — approved Emtricitabine (Emtriva) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6599395-3944-44f9-97f2-e0424c6b6a1f'),
  ('dolutegravir', 'caution',
   'A OMS recomenda o dolutegravir como primeira linha em grávidas. Inicialmente havia preocupação com defeitos do tubo neural (2018), mas estudos subsequentes mostraram segurança.',
   'WHO recommends dolutegravir as first-line in pregnant women. Initial concern about neural tube defects (2018), but subsequent studies showed safety.',
   'Recomendado pela OMS como primeira linha em todas as fases da gravidez. A dose pode ser aumentada para 50 mg duas vezes ao dia no 3.º trimestre.',
   'Recommended by WHO as first-line in all stages of pregnancy. Dose may be increased to 50 mg twice daily in the third trimester.',
   'Excretado no leite materno em pequenas quantidades. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk in small amounts. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dolutegravir (Tivicay): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921',
   'DailyMed/FDA (NIH/NLM) — approved Dolutegravir (Tivicay) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=485bc9db-8665-9f5a-e063-6394a90a7921'),
  ('lopinavir-ritonavir', 'caution',
   'Pode ser usado durante a gravidez com precaução. Estudos limitados não demonstraram teratogenicidade significativa.',
   'Can be used during pregnancy with caution. Limited studies did not demonstrate significant teratogenicity.',
   'Pode ser usado em todos os trimestres quando indicado. Monitorizar glicémia e perfil lipídico.',
   'Can be used in all trimesters when indicated. Monitor glycaemia and lipid profile.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lopinavir + Ritonavir (Kaletra): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3',
   'DailyMed/FDA (NIH/NLM) — approved Lopinavir + Ritonavir (Kaletra) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3'),
  ('darunavir', 'caution',
   'Dados limitados em humanos. Estudos em animais não demonstraram teratogenicidade. Pode ser usado quando outras opções estão esgotadas.',
   'Limited human data. Animal studies did not demonstrate teratogenicity. Can be used when other options are exhausted.',
   'Pode ser usado no 2.º e 3.º trimestres com precaução. Dados no 1.º trimestre limitados.',
   'Can be used in the 2nd and 3rd trimesters with caution. 1st trimester data are limited.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Darunavir (Prezista): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f',
   'DailyMed/FDA (NIH/NLM) — approved Darunavir (Prezista) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f'),
  ('abacavir', 'caution',
   'Estudos em animais não demonstraram teratogenicidade. Dados limitados em humanos. Pode ser usado quando indicado.',
   'Animal studies did not demonstrate teratogenicity. Limited human data. Can be used when indicated.',
   'Pode ser usado em todos os trimestres quando indicado.',
   'Can be used in all trimesters when indicated.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Abacavir (Ziagen): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1',
   'DailyMed/FDA (NIH/NLM) — approved Abacavir (Ziagen) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ca73b519-015a-436d-aa3c-af53492825a1'),
  ('raltegravir', 'caution',
   'Estudos em animais não demonstraram teratogenicidade. Dados limitados em humanos. Pode ser usado quando indicado.',
   'Animal studies did not demonstrate teratogenicity. Limited human data. Can be used when indicated.',
   'Pode ser usado em todos os trimestres quando indicado.',
   'Can be used in all trimesters when indicated.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Raltegravir (Isentress): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3',
   'DailyMed/FDA (NIH/NLM) — approved Raltegravir (Isentress) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89a5ec53-d956-4329-8004-0f40f51c88a3'),
  ('etravirina', 'caution',
   'Dados limitados em humanos. Estudos em animais não demonstraram teratogenicidade. Usar com precaução.',
   'Limited human data. Animal studies did not demonstrate teratogenicity. Use with caution.',
   'Pode ser usado no 2.º e 3.º trimestres com precaução. Dados no 1.º trimestre limitados.',
   'Can be used in the 2nd and 3rd trimesters with caution. 1st trimester data are limited.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Etravirina (Intelence): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d',
   'DailyMed/FDA (NIH/NLM) — approved Etravirine (Intelence) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6a9cbc29-9f15-4b24-8d86-206b82887f3d'),
  ('rilpivirina', 'caution',
   'Dados limitados em humanos. Estudos em animais não demonstraram teratogenicidade. Usar com precaução.',
   'Limited human data. Animal studies did not demonstrate teratogenicity. Use with caution.',
   'Pode ser usado no 2.º e 3.º trimestres com precaução.',
   'Can be used in the 2nd and 3rd trimesters with caution.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rilpivirina (Edurant): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6',
   'DailyMed/FDA (NIH/NLM) — approved Rilpivirine (Edurant) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=03880372-2c68-45c6-a53a-f420c49541d6'),
  ('estavudina', 'caution',
   'Estudos em animais não demonstraram teratogenicidade. Dados limitados em humanos. Usar apenas quando outras opções estão esgotadas.',
   'Animal studies did not demonstrate teratogenicity. Limited human data. Use only when other options are exhausted.',
   'Usar apenas no 2.º e 3.º trimestres quando outras opções estão esgotadas.',
   'Use only in the 2nd and 3rd trimesters when other options are exhausted.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Estavudina (Zerit): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434',
   'DailyMed/FDA (NIH/NLM) — approved Stavudine (Zerit) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8bb73c56-74cb-4602-b9a3-57bd1082b434'),
  ('didanosina', 'caution',
   'Estudos em animais demonstraram toxicidade a altas doses. Dados limitados em humanos. Usar apenas quando outras opções estão esgotadas.',
   'Animal studies demonstrated toxicity at high doses. Limited human data. Use only when other options are exhausted.',
   'Evitar no 1.º trimestre. Usar apenas no 2.º e 3.º trimestres quando outras opções estão esgotadas.',
   'Avoid in the 1st trimester. Use only in the 2nd and 3rd trimesters when other options are exhausted.',
   'Excretado no leite materno. Recomenda-se amamentação artificial em doentes HIV-positivas.',
   'Excreted in breast milk. Artificial feeding is recommended for HIV-positive mothers.',
   'Métodos contraceptivos fiáveis são recomendados.',
   'Reliable contraceptive methods are recommended.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Didanosina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67',
   'DailyMed/FDA (NIH/NLM) — approved Didanosine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=829e744d-7bd4-43dc-9b58-ffb016cb8e67')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
