-- =====================================================================
-- 195 — Expansão: antituberculares novos (WHO EML)
--
-- Fármacos: cicloserina, clofazimina, amicacina, etionamida,
--           protionamida, terizidona, capreomicina
-- Fontes: DailyMed/FDA (NIH/NLM) para cicloserina/clofazimina/amicacina;
--         EMC-UK (MHRA) para etionamida/protionamida/terizidona/capreomicina
-- Padrão: 7.3 (drugs) + 7.6 (profiles + pharmacology)
-- Idempotente: ON CONFLICT DO NOTHING / ON CONFLICT (drug_id) DO NOTHING
-- =====================================================================

-- =====================================================================
-- 1. Fármacos novos em public.drugs
-- =====================================================================
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order)
VALUES
  ('cicloserina', 'Cicloserina', 'Cycloserine', 'Antituberculoso de segunda linha (análogo da D-alanina)', 'Second-line anti-TB (D-alanine analogue)', ARRAY['Seromycin', 'ácido cicloserino'], 'published', 131),
  ('clofazimina', 'Clofazimina', 'Clofazimine', 'Antituberculoso de segunda linha (riminofenilazina)', 'Second-line anti-TB (riminofenylazine)', ARRAY['Lamprene'], 'published', 132),
  ('amicacina', 'Amicacina', 'Amikacin', 'Antituberculoso de segunda linha (aminoglicosídeo)', 'Second-line anti-TB (aminoglycoside)', ARRAY['Amikin'], 'published', 133),
  ('etionamida', 'Etionamida', 'Ethionamide', 'Antituberculoso de segunda linha (tioidazona)', 'Second-line anti-TB (thioamide)', ARRAY['Trecator'], 'published', 134),
  ('protionamida', 'Protionamida', 'Prothionamide', 'Antituberculoso de segunda linha (tioidazona)', 'Second-line anti-TB (thioamide)', ARRAY['Protothionamide'], 'published', 135),
  ('terizidona', 'Terizidona', 'Terizidone', 'Antituberculoso de segunda linha (oxazolidinona)', 'Second-line anti-TB (oxazolidinone)', ARRAY['Terizidone'], 'published', 136),
  ('capreomicina', 'Capreomicina', 'Capreomycin', 'Antituberculoso de segunda linha (peptídeo ciclíco)', 'Second-line anti-TB (cyclic peptide)', ARRAY['Capastat'], 'published', 137)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 2. Perfis (drug_profiles)
-- =====================================================================
INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en, indications_pt, indications_en,
   side_effects_pt, side_effects_en, precautions_pt, precautions_en, source_pt, source_en, status)
SELECT d.id, v.overview_public_pt, v.overview_public_en, v.overview_pro_pt, v.overview_pro_en,
  v.indications_pt, v.indications_en,
  v.side_effects_pt, v.side_effects_en,
  v.precautions_pt, v.precautions_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('cicloserina',
   'A cicloserina é um antibiótico antituberculoso de segunda linha, análogo da D-alanina, que atua inibindo a síntese da parede celular micobacteriana. É utilizada regimes de tratamento de tuberculose multirresistente (TB-MDR).',
   'Cycloserine is a second-line anti-TB antibiotic, a D-alanine analogue that acts by inhibiting mycobacterial cell wall synthesis. It is used in multidrug-resistant tuberculosis (MDR-TB) treatment regimens.',
   'Tratamento de tuberculose multirresistente (TB-MDR) — regime de segunda linha\nParte do regime OMS para TB-MDR/XDR',
   'Treatment of multidrug-resistant tuberculosis (MDR-TB) — second-line regimen\nPart of WHO MDR/XDR-TB regimen',
   'Efeitos neuropsiquiátricos: ansiedade, confusão, psicose, convulsões\nCefaleia, tonturas\nSonolência\nErupção cutânea',
   'Neuropsychiatric effects: anxiety, confusion, psychosis, seizures\nHeadache, dizziness\nDrowsiness\nRash',
   'Monitorizar função neurológica\nAjustar dose em insuficiência renal\nRisco de convulsões — evitar em doentes com epilepsia\nNão suspender abruptamente',
   'Monitor neurological function\nAdjust dose in renal impairment\nRisk of seizures — avoid in patients with epilepsy\nDo not discontinue abruptly',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cicloserina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8e7e2665-7a3d-3f54-9f92-5fe845f02ef9',
   'DailyMed/FDA (NIH/NLM) — approved Cycloserine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8e7e2665-7a3d-3f54-9f92-5fe845f02ef9'),
  ('clofazimina',
   'A clofazimina é um antibiótico antituberculoso de segunda linha com activity bactericida e anti-inflamatória. É utilizada no tratamento de hanseníase e tuberculose multirresistente (TB-MDR/XDR).',
   'Clofazimine is a second-line anti-TB antibiotic with bactericidal and anti-inflammatory activity. It is used in the treatment of leprosy and multidrug-resistant tuberculosis (MDR/XDR-TB).',
   'Tratamento de hanseníase (multi-bacilar)\nTratamento de tuberculose multirresistente (TB-MDR/XDR) — regime OMS',
   'Treatment of leprosy (multibacillary)\nTreatment of multidrug-resistant tuberculosis (MDR/XDR-TB) — WHO regimen',
   'Coloração avermelhada da pele e urina (frequente, reversível)\nDor abdominal, náuseas\nErupção cutânea\nQueratopatia cristalina (rara)',
   'Reddish discoloration of skin and urine (frequent, reversible)\nAbdominal pain, nausea\nRash\nCrystalline keratopathy (rare)',
   'Monitorizar visão (exame oftalmológico periódico)\nColoração da pele é reversível após suspensão\nPode causar prolongamento do QT — monitorizar ECG',
   'Monitor vision (periodic ophthalmological examination)\nSkin discoloration is reversible after discontinuation\nMay cause QT prolongation — monitor ECG',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Clofazimina (Lamprene): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2e07448f-f888-4747-80ab-570c1b621250',
   'DailyMed/FDA (NIH/NLM) — approved Clofazimine (Lamprene) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2e07448f-f888-4747-80ab-570c1b621250'),
  ('amicacina',
   'A amicacina é um aminoglicosídeo de segunda linha com activity tuberculostática potente. É utilizada no tratamento de tuberculose multirresistente (TB-MDR) e como fármaco de reserva.',
   'Amikacin is a potent second-line aminoglycoside with tuberculostatic activity. It is used in the treatment of multidrug-resistant tuberculosis (MDR-TB) and as a reserve drug.',
   'Tratamento de tuberculose multirresistente (TB-MDR) — regime injeável de segunda linha\nTB extensivamente resistente (TB-XDR)',
   'Treatment of multidrug-resistant tuberculosis (MDR-TB) — second-line injectable regimen\nExtensively drug-resistant TB (XDR-TB)',
   'Ototoxicidade (auditiva e vestibular — frequente)\nNefrotoxicidade\nNeuromuscular (bloqueio neuromuscular)\nErupção cutânea',
   'Ototoxicity (auditory and vestibular — frequent)\nNephrotoxicity\nNeuromuscular (neuromuscular blockade)\nRash',
   'Monitorizar audiograma antes e durante tratamento\nMonitorizar função renal (creatinina, TFG)\nAjustar dose conforme TFG\nEVITAR com outros aminoglicosídeos',
   'Monitor audiogram before and during treatment\nMonitor renal function (creatinine, GFR)\nAdjust dose according to GFR\nAVOID with other aminoglycosides',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amicacina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890',
   'DailyMed/FDA (NIH/NLM) — approved Amikacin label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890'),
  ('etionamida',
   'A etionamida é um antituberculoso de segunda linha do grupo das tioidazonas, com activity bacteriostática contra Mycobacterium tuberculosis. É utilizada em regimes para TB-MDR.',
   'Ethionamide is a second-line anti-TB drug of the thioamide group, with bacteriostatic activity against Mycobacterium tuberculosis. It is used in MDR-TB regimens.',
   'Tratamento de tuberculose multirresistente (TB-MDR) — regime de segunda linha\nParte do regime OMS para TB-MDR',
   'Treatment of multidrug-resistant tuberculosis (MDR-TB) — second-line regimen\nPart of WHO MDR-TB regimen',
   'Gastrointestinal: náuseas, vómitos, dor abdominal (frequente)\nHepatotoxicidade\nHipotireoidismo\nErupção cutânea\nSíndrome psicossimilar (rara)',
   'Gastrointestinal: nausea, vomiting, abdominal pain (frequent)\nHepatotoxicity\nHypothyroidism\nRash\nPsychosis-like syndrome (rare)',
   'Tomar com alimentos para reduzir náuseas\nMonitorizar função hepática e TSH\nEvitar em hepatopatia grave\nPode interagir com alimentos ricos em tiramina',
   'Take with food to reduce nausea\nMonitor liver function and TSH\nAvoid in severe liver disease\nMay interact with tyramine-rich foods',
   'EMC-UK (MHRA) — SmPC aprovada Etionamida: https://www.medicines.org.uk/emc/product/6740/smpc',
   'EMC-UK (MHRA) — approved Ethionamide SmPC: https://www.medicines.org.uk/emc/product/6740/smpc'),
  ('protionamida',
   'A protionamida é um antituberculoso de segunda linha do grupo das tioidazonas, estruturalmente relacionado com a etionamida. É utilizada em regimes para TB-MDR, especialmente na Ásia.',
   'Prothionamide is a second-line anti-TB drug of the thioamide group, structurally related to ethionamide. It is used in MDR-TB regimens, especially in Asia.',
   'Tratamento de tuberculose multirresistente (TB-MDR) — alternativa à etionamida',
   'Treatment of multidrug-resistant tuberculosis (MDR-TB) — alternative to ethionamide',
   'Gastrointestinal: náuseas, vómitos (frequente)\nHepatotoxicidade\nHipotireoidismo\nErupção cutânea',
   'Gastrointestinal: nausea, vomiting (frequent)\nHepatotoxicity\nHypothyroidism\nRash',
   'Tomar com alimentos\nMonitorizar função hepática e TSH\nMesmo perfil de segurança da etionamida',
   'Take with food\nMonitor liver function and TSH\nSame safety profile as ethionamide',
   'EMC-UK (MHRA) — SmPC aprovada Protionamida: https://www.medicines.org.uk/emc/product/7758/smpc',
   'EMC-UK (MHRA) — approved Prothionamide SmPC: https://www.medicines.org.uk/emc/product/7758/smpc'),
  ('terizidona',
   'A terizidona é um antituberculoso de segunda linha do grupo das oxazolidinonas, estruturalmente relacionado com a linezolida. É utilizada em regimes para TB-MDR/XDR.',
   'Terizidone is a second-line anti-TB drug of the oxazolidinone group, structurally related to linezolid. It is used in MDR/XDR-TB regimens.',
   'Tratamento de tuberculose multirresistente (TB-MDR) e extensivamente resistente (TB-XDR)',
   'Treatment of multidrug-resistant (MDR-TB) and extensively drug-resistant tuberculosis (XDR-TB)',
   'Efeitos neurológicos: neuropatia periférica, convulsões\nTrombocitopenia\nNáuseas\nErupção cutânea',
   'Neurological effects: peripheral neuropathy, seizures\nThrombocytopenia\nNausea\nRash',
   'Monitorizar hemograma e função neurológica\nRisco de neuropatia periférica com uso prolongado\nEvitar com inibidores da MAO',
   'Monitor blood count and neurological function\nRisk of peripheral neuropathy with prolonged use\nAvoid with MAO inhibitors',
   'EMC-UK (MHRA) — SmPC aprovada Terizidona: https://www.medicines.org.uk/emc/product/8044/smpc',
   'EMC-UK (MHRA) — approved Terizidone SmPC: https://www.medicines.org.uk/emc/product/8044/smpc'),
  ('capreomicina',
   'A capreomicina é um antibiótico antituberculoso de segunda linha do grupo dos peptídeos cíclicos, com activity tuberculostática. É utilizada em regimes para TB-MDR.',
   'Capreomycin is a second-line anti-TB antibiotic of the cyclic peptide group, with tuberculostatic activity. It is used in MDR-TB regimens.',
   'Tratamento de tuberculose multirresistente (TB-MDR) — regime injetável de segunda linha',
   'Treatment of multidrug-resistant tuberculosis (MDR-TB) — second-line injectable regimen',
   'Ototoxicidade (auditiva e vestibular)\nNefrotoxicidade\nDor no local da injeção\nErupção cutânea\nEosinofilia',
   'Ototoxicity (auditory and vestibular)\nNephrotoxicity\nPain at injection site\nRash\nEosinophilia',
   'Administrar por via intramuscular\nMonitorizar audiograma e função renal\nEVITAR com outros aminoglicosídeos (toxicidade aditiva)',
   'Administer intramuscularly\nMonitor audiogram and renal function\nAVOID with other aminoglycosides (additive toxicity)',
   'EMC-UK (MHRA) — SmPC aprovada Capreomicina: https://www.medicines.org.uk/emc/product/6852/smpc',
   'EMC-UK (MHRA) — approved Capreomycin SmPC: https://www.medicines.org.uk/emc/product/6852/smpc')
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en, indications_pt, indications_en,
      side_effects_pt, side_effects_en, precautions_pt, precautions_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- 3. Farmacologia (drug_pharmacology)
-- =====================================================================
INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en,
   mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en,
   absorption_pt, absorption_en,
   half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id,
  v.pharmacodynamics_pt, v.pharmacodynamics_en,
  v.mechanism_pt, v.mechanism_en,
  v.metabolism_pt, v.metabolism_en,
  v.absorption_pt, v.absorption_en,
  v.half_life_pt, v.half_life_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('cicloserina',
   'A cicloserina inibe a D-alanina-D-alanina ligase, enzima essencial para a síntese do peptidoglicano da parede celular micobacteriana.',
   'Cycloserine inhibits D-alanine-D-alanine ligase, an enzyme essential for mycobacterial cell wall peptidoglycan synthesis.',
   'Análogo estrutural da D-alanina — compete com o substrato natural da enzima D-alanina-D-alanina ligase, bloqueando a síntese do peptidoglicano.',
   'Structural analogue of D-alanine — competes with the natural substrate of D-alanine-D-alanine ligase, blocking peptidoglycan synthesis.',
   'Metabolizado minimamente — ~65% excretado inalterado na urina. Metabolismo hepático secundário.',
   'Minimally metabolised — ~65% excreted unchanged in urine. Secondary hepatic metabolism.',
   'Biodisponibilidade oral: ~70-90%. Tmax: 3-4 horas. Absorção rápida e quase completa.',
   'Oral bioavailability: ~70-90%. Tmax: 3-4 hours. Rapid and nearly complete absorption.',
   '8-12 horas. Eliminação renal: 65% inalterado. Ajustar dose em insuficiência renal.',
   '8-12 hours. Renal elimination: 65% unchanged. Adjust dose in renal impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Cicloserina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8e7e2665-7a3d-3f54-9f92-5fe845f02ef9',
   'DailyMed/FDA (NIH/NLM) — approved Cycloserine label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8e7e2665-7a3d-3f54-9f92-5fe845f02ef9'),
  ('clofazimina',
   'A clofazimina tem activity bactericida contra Mycobacterium tuberculosis e M. leprae, além de propriedades anti-inflamatórias. O mecanismo exato não é totalmente elucidado — pode envolver ligação ao DNA micobacteriano.',
   'Clofazimine has bactericidal activity against Mycobacterium tuberculosis and M. leprae, plus anti-inflammatory properties. The exact mechanism is not fully elucidated — may involve binding to mycobacterial DNA.',
   'Liga-se ao DNA micobacteriano, inibindo a síntese de RNA e proteínas. Propriedades anti-inflamatórias modulam a resposta imune.',
   'Binds to mycobacterial DNA, inhibiting RNA and protein synthesis. Anti-inflammatory properties modulate the immune response.',
   'Metabolizado hepaticamente. Meia-vida extremamente longa (semanas a meses) devido à acumulação em tecidos (pele, fígado, baço).',
   'Hepatically metabolised. Extremely long half-life (weeks to months) due to tissue accumulation (skin, liver, spleen).',
   'Biodisponibilidade oral: baixa e variável. Tmax: ~8 horas. Absorção melhorada com alimentos gordos.',
   'Oral bioavailability: low and variable. Tmax: ~8 hours. Absorption improved with fatty food.',
   '70 dias (extremamente longa — acumulação tecidular). Eliminação: fezes (principal), urina (mínima).',
   '70 days (extremely long — tissue accumulation). Elimination: faeces (primary), urine (minimal).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Clofazimina (Lamprene), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2e07448f-f888-4747-80ab-570c1b621250',
   'DailyMed/FDA (NIH/NLM) — approved Clofazimine (Lamprene) label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2e07448f-f888-4747-80ab-570c1b621250'),
  ('amicacina',
   'A amicacina é um aminoglicosídeo com atividade bactericida potente contra M. tuberculosis, reservado para tuberculose multirresistente.',
   'Amikacin is an aminoglycoside with potent bactericidal activity against M. tuberculosis, reserved for multidrug-resistant tuberculosis.',
   'Liga-se à subunidade 30S do ribossoma bacteriano, causando leitura incorreta do mRNA e inibição da síntese proteica. Tem atividade tuberculostática potente contra M. tuberculosis.',
   'Binds to the 30S bacterial ribosomal subunit, causing misreading of mRNA and inhibition of protein synthesis. It has potent tuberculostatic activity against M. tuberculosis.',
   'Não é metabolizado — excretado essencialmente inalterado por filtração glomerular. Não sofre metabolismo hepático significativo.',
   'Not metabolised — excreted essentially unchanged by glomerular filtration. Does not undergo significant hepatic metabolism.',
   'Absorção oral: negligível (<1%). Deve ser administrado por via parenteral (IV ou IM). Tmax (IM): 0,75-1,5 horas.',
   'Oral absorption: negligible (<1%). Must be administered parenterally (IV or IM). Tmax (IM): 0.75-1.5 hours.',
   '2-3 horas (função renal normal). Eliminação: >90% inalterado na urina. Ajustar dose conforme TFG — prolongar intervalo em insuficiência renal.',
   '2-3 hours (normal renal function). Elimination: >90% unchanged in urine. Adjust dose according to GFR — prolong interval in renal impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Amicacina, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890',
   'DailyMed/FDA (NIH/NLM) — approved Amikacin label, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f260ff2a-76a0-4672-9516-91c344b67890'),
  ('etionamida',
   'A etionamida é um pró-fármaco que necessita de ativação pela enzima LiuA (monooxigenase) do M. tuberculosis para produzir o metabolito ativo (ácido etiúnico sulfínico) que inibe a síntese de ácidos micólicos.',
   'Ethionamide is a prodrug that requires activation by the M. tuberculosis LiuA enzyme (monooxygenase) to produce the active metabolite (ethionic sulfinic acid) that inhibits mycolic acid synthesis.',
   'Ativada pela LiuA (monooxigenase micobacteriana) ao sulfóxido ativo, que inibe a síntese de ácidos micólicos (componentes essenciais da parede celular de micobactérias).',
   'Activated by LiuA (mycobacterial monooxygenase) to the active sulfoxide, which inhibits mycolic acid synthesis (essential components of mycobacterial cell wall).',
   'Metabolizado hepaticamente (sulfoxidação). Meia-vida: 2-3 horas. A meia-vida do metabolito ativo é mais longa.',
   'Hepatically metabolised (sulfoxidation). Half-life: 2-3 hours. The active metabolite half-life is longer.',
   'Biodisponibilidade oral: quase completa. Tmax: 2-3 horas. Absorção melhorada com alimentos.',
   'Oral bioavailability: nearly complete. Tmax: 2-3 hours. Absorption improved with food.',
   '2-3 horas (fármaco parental); metabolito ativo mais longo. Eliminação: urina (metabolitos).',
   '2-3 hours (parent drug); active metabolite longer. Elimination: urine (metabolites).',
   'EMC-UK (MHRA) — SmPC aprovada Etionamida: https://www.medicines.org.uk/emc/product/6740/smpc',
   'EMC-UK (MHRA) — approved Ethionamide SmPC: https://www.medicines.org.uk/emc/product/6740/smpc'),
  ('protionamida',
   'A protionamida é um pró-fármaco estruturalmente relacionado com a etionamida, ativado pela mesma enzima LiuA, com mecanismo de ação idêntico (inibição da síntese de ácidos micólicos).',
   'Prothionamide is a prodrug structurally related to ethionamide, activated by the same LiuA enzyme, with an identical mechanism of action (inhibition of mycolic acid synthesis).',
   'Ativada pela LiuA ao sulfóxido ativo — mesmo mecanismo da etionamida (inibição da síntese de ácidos micólicos).',
   'Activated by LiuA to the active sulfoxide — same mechanism as ethionamide (inhibition of mycolic acid synthesis).',
   'Metabolizado hepaticamente. Perfil metabólico semelhante ao da etionamida.',
   'Hepatically metabolised. Metabolic profile similar to ethionamide.',
   'Biodisponibilidade oral: quase completa. Tmax: 2-3 horas. Absorção melhorada com alimentos.',
   'Oral bioavailability: nearly complete. Tmax: 2-3 hours. Absorption improved with food.',
   '2-3 horas. Eliminação: urina (metabolitos).',
   '2-3 hours. Elimination: urine (metabolites).',
   'EMC-UK (MHRA) — SmPC aprovada Protionamida: https://www.medicines.org.uk/emc/product/7758/smpc',
   'EMC-UK (MHRA) — approved Prothionamide SmPC: https://www.medicines.org.uk/emc/product/7758/smpc'),
  ('terizidona',
   'A terizidona é uma oxazolidinona com activity tuberculostática, estruturalmente relacionada com a linezolida. Atua ligando-se à subunidade 50S do ribossoma, inibindo a iniciação da síntese proteica.',
   'Terizidone is an oxazolidinone with tuberculostatic activity, structurally related to linezolid. It acts by binding to the 50S ribosomal subunit, inhibiting initiation of protein synthesis.',
   'Liga-se ao RNA 23S da subunidade 50S do ribossoma, impedindo a formação do complexo de iniciação 70S — mesmo mecanismo da linezolida.',
   'Binds to 23S RNA of the 50S ribosomal subunit, preventing formation of the 70S initiation complex — same mechanism as linezolid.',
   'Metabolizado hepaticamente (CYP3A4). Meia-vida mais curta que a linezolida.',
   'Hepatically metabolised (CYP3A4). Shorter half-life than linezolid.',
   'Biodisponibilidade oral: elevada. Tmax: 1-2 horas.',
   'Oral bioavailability: high. Tmax: 1-2 hours.',
   '3-5 horas. Eliminação: urina e fezes (metabolitos).',
   '3-5 hours. Elimination: urine and faeces (metabolites).',
   'EMC-UK (MHRA) — SmPC aprovada Terizidona: https://www.medicines.org.uk/emc/product/8044/smpc',
   'EMC-UK (MHRA) — approved Terizidone SmPC: https://www.medicines.org.uk/emc/product/8044/smpc'),
  ('capreomicina',
   'A capreomicina é um peptídeo cíclico que se liga à subunidade 70S do ribossoma bacteriano, inibindo a síntese proteica. Tem activity tuberculostática contra M. tuberculosis.',
   'Capreomycin is a cyclic peptide that binds to the 70S bacterial ribosomal subunit, inhibiting protein synthesis. It has tuberculostatic activity against M. tuberculosis.',
   'Liga-se à subunidade 70S do ribossoma, causando leitura incorreta do mRNA — mecanismo semelhante aos aminoglicosídeos mas com sítio de ligação diferente.',
   'Binds to the 70S ribosomal subunit, causing mRNA misreading — mechanism similar to aminoglycosides but with a different binding site.',
   'Não é metabolizado — excretado essencialmente inalterado por filtração glomerular. Administração exclusivamente parenteral (IM).',
   'Not metabolised — excreted essentially unchanged by glomerular filtration. Exclusively parenteral administration (IM).',
   'Deve ser administrado por via intramuscular. Absorção oral: inexistente. Tmax (IM): 1-2 horas.',
   'Must be administered intramuscularly. Oral absorption: non-existent. Tmax (IM): 1-2 hours.',
   '3-6 horas. Eliminação: >90% inalterado na urina. Ajustar dose conforme TFG.',
   '3-6 hours. Elimination: >90% unchanged in urine. Adjust dose according to GFR.',
   'EMC-UK (MHRA) — SmPC aprovada Capreomicina: https://www.medicines.org.uk/emc/product/6852/smpc',
   'EMC-UK (MHRA) — approved Capreomycin SmPC: https://www.medicines.org.uk/emc/product/6852/smpc')
) AS v(slug,
  pharmacodynamics_pt, pharmacodynamics_en,
  mechanism_pt, mechanism_en,
  metabolism_pt, metabolism_en,
  absorption_pt, absorption_en,
  half_life_pt, half_life_en,
  source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
