-- =====================================================================
-- 198 — Expansão: 11 cardiovasculares novos (WHO EML)
--
-- Fármacos: lisinopril, losartana, nifedipina, metoprolol,
--           atenolol, propranolol, carvedilol, bisoprolol,
--           rosuvastatina, simvastatina, isossorbida
-- Fontes: rótulos aprovados DailyMed/FDA (NIH/NLM), setIDs validados
--         na websearch (2026-08-19)
-- Padrão: 7.3 (drugs) + 7.6 (profiles + pharmacology)
-- Idempotente: ON CONFLICT DO NOTHING / ON CONFLICT (drug_id) DO NOTHING
-- =====================================================================

-- =====================================================================
-- 1. Fármacos novos em public.drugs
-- =====================================================================
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order)
VALUES
  ('lisinopril', 'Lisinopril', 'Lisinopril', 'Inibidor da enzima conversora da angiotensina (IECA)', 'Angiotensin-converting enzyme inhibitor (ACEI)', ARRAY['Zestril', 'Prinivil'], 'published', 131),
  ('losartana', 'Losartana', 'Losartan', 'Bloqueador do recetor da angiotensina II (BRA)', 'Angiotensin II receptor blocker (ARB)', ARRAY['Cozaar'], 'published', 132),
  ('nifedipina', 'Nifedipina', 'Nifedipine', 'Bloqueador dos canais de cálcio (BCC)', 'Calcium channel blocker (CCB)', ARRAY['Adalat', 'Procardia'], 'published', 133),
  ('metoprolol', 'Metoprolol', 'Metoprolol', 'Betabloqueador seletivo β1', 'Selective beta-1 blocker', ARRAY['Lopressor', 'Toprol-XL'], 'published', 134),
  ('atenolol', 'Atenolol', 'Atenolol', 'Betabloqueador seletivo β1', 'Selective beta-1 blocker', ARRAY['Tenormin'], 'published', 135),
  ('propranolol', 'Propranolol', 'Propranolol', 'Betabloqueador não seletivo (β1+β2)', 'Non-selective beta-blocker (β1+β2)', ARRAY['Inderal'], 'published', 136),
  ('carvedilol', 'Carvedilol', 'Carvedilol', 'Betabloqueador α1+β1+β2', 'Alpha-1/beta blocker', ARRAY['Coreg'], 'published', 137),
  ('bisoprolol', 'Bisoprolol', 'Bisoprolol', 'Betabloqueador seletivo β1', 'Selective beta-1 blocker', ARRAY['Zebeta'], 'published', 138),
  ('rosuvastatina', 'Rosuvastatina', 'Rosuvastatin', 'Inibidor da HMG-CoA redutase (estatina)', 'HMG-CoA reductase inhibitor (statin)', ARRAY['Crestor'], 'published', 139),
  ('simvastatina', 'Simvastatina', 'Simvastatin', 'Inibidor da HMG-CoA redutase (estatina)', 'HMG-CoA reductase inhibitor (statin)', ARRAY['Zocor'], 'published', 140),
  ('isossorbida', 'Isossorbida Dinitrato', 'Isosorbide Dinitrate', 'Nitrato orgânico vasodilatador', 'Organic nitrate vasodilator', ARRAY['Isordil', 'Dilatrate'], 'published', 141)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 2. Perfis (drug_profiles)
-- =====================================================================
INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
   indications_pt, indications_en,
   side_effects_pt, side_effects_en, precautions_pt, precautions_en, source_pt, source_en, status)
SELECT d.id, v.overview_public_pt, v.overview_public_en, v.overview_pro_pt, v.overview_pro_en,
  v.indications_pt, v.indications_en,
  v.side_effects_pt, v.side_effects_en,
  v.precautions_pt, v.precautions_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('lisinopril',
   'O lisinopril é um inibidor da enzima conversora da angiotensina (IECA) amplamente utilizado para tratar a hipertensão e a insuficiência cardíaca. Ao inibir a conversão de angiotensina I em angiotensina II, reduz a resistência vascular periférica e a pressão arterial.',
   'Lisinopril is an ACE inhibitor widely used to treat hypertension and heart failure. By inhibiting the conversion of angiotensin I to angiotensin II, it reduces peripheral vascular resistance and blood pressure.',
   'Hipertensão arterial\nInsuficiência cardíaca\nProteção renal na nefropatia diabética\nPós-enfarte miocárdico',
   'Hypertension\nHeart failure\nRenal protection in diabetic nephropathy\nPost-myocardial infarction',
   'IECA oral de ação prolongada. Inibe a ECA, bloqueando a conversão de angiotensina I em angiotensina II e degradando a bradicinina. Não é pró-fármaco. Excreção 100% renal. Dose habitual: 10-40 mg/dia. Não requer ajuste em disfunção hepática.',
   'Long-acting oral ACE inhibitor. Inhibits ACE, blocking conversion of angiotensin I to angiotensin II and degrading bradykinin. Not a prodrug. 100% renal excretion. Usual dose: 10-40 mg/day. No adjustment needed in hepatic impairment.',
   'Tos seca (comum)\nHipotensão\nHipercalemia\nTonturas\nCefaleia\nDisfunção renal',
   'Dry cough (common)\nHypotension\nHyperkalaemia\nDizziness\nHeadache\nRenal dysfunction',
   'CONTRAINDICADO na gravidez (teratogênico)\nMonitorizar função renal e potássio\nRisco de hipercalemia com poupança de potássio\nEvitar com bloqueadores duplos do RAAS',
   'CONTRAINDICATED in pregnancy (teratogenic)\nMonitor renal function and potassium\nRisk of hyperkalaemia with potassium-sparing agents\nAvoid with dual RAAS blockade',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16'),
  ('losartana',
   'A losartana é um bloqueador do recetor da angiotensina II (BRA) que se liga seletivamente ao recetor AT1, impedindo a vasoconstrição e a secreção de aldosterona. É o primeiro BRA aprovado para uso clínico.',
   'Losartan is an angiotensin II receptor blocker (ARB) that selectively binds to the AT1 receptor, preventing vasoconstriction and aldosterone secretion. It is the first ARB approved for clinical use.',
   'Hipertensão arterial\nNefropatia em diabéticos tipo 2\nInsuficiência cardíaca\nProteção cardiovascular',
   'Hypertension\nNephropathy in type 2 diabetes\nHeart failure\nCardiovascular protection',
   'BRA oral com metabolito ativo E-3174 (10-40x mais potente). Metabolizado por CYP2C9 e CYP3A4. Aproveitamento oral ~33%. Dose habitual: 25-100 mg/dia. Único BRA com atividade uricosúrica.',
   'Oral ARB with active metabolite E-3174 (10-40x more potent). Metabolised by CYP2C9 and CYP3A4. Oral bioavailability ~33%. Usual dose: 25-100 mg/day. Only ARB with uricosuric activity.',
   'Tonturas\nCefaleia\nHipercalemia\nHipotensão\nDiarreia\nRaramente: angioedema',
   'Dizziness\nHeadache\nHyperkalaemia\nHypotension\nDiarrhoea\nRarely: angioedema',
   'CONTRAINDICADO na gravidez (teratogênico)\nMonitorizar função renal e potássio\nAjuste de dose na insuficiência hepática\nRisco de hipotensão na desidratação',
   'CONTRAINDICATED in pregnancy (teratogenic)\nMonitor renal function and potassium\nDose adjustment in hepatic impairment\nRisk of hypotension in dehydration',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Losartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   'DailyMed/FDA (NIH/NLM) — approved Losartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31'),
  ('nifedipina',
   'A nifedipina é um bloqueador dos canais de cálcio diidropiridínico que relaxa o músculo liso vascular, reduzindo a resistência vascular periférica e a pressão arterial.',
   'Nifedipine is a dihydropyridine calcium channel blocker that relaxes vascular smooth muscle, reducing peripheral vascular resistance and blood pressure.',
   'Hipertensão arterial\nAngina de peito (estável e vasoespástica)\nRaynaud\nHipertermia maligna',
   'Hypertension\nAngina pectoris (stable and vasospastic)\nRaynaud\nMalignant hyperthermia',
   'BCC diidropiridínico de curta duração. Bloqueia canais de cálcio tipo L vascular. Metabolismo hepático extenso via CYP3A4. Aproveitamento oral 45-68%. Evitar formulações de curta ação para hipertensão (risco de isquemia).',
   'Short-acting dihydropyridine CCB. Blocks vascular L-type calcium channels. Extensive hepatic metabolism via CYP3A4. Oral bioavailability 45-68%. Avoid short-acting formulations for hypertension (ischaemia risk).',
   'Edema periférico (comum)\nCefaleia\nVasodilatação facial\nTaquicardia reflexa\nTonturas\nConstipação',
   'Peripheral oedema (common)\nHeadache\nFacial flushing\nReflex tachycardia\nDizziness\nConstipation',
   'Evitar em enfarte agudo do miocárdio recente\nCuidado em insuficiência cardíaca\nPode causar taquicardia reflexa\nEvitar com betabloqueadores em doses altas (risco de insuficiência cardíaca)',
   'Avoid in recent acute myocardial infarction\nCaution in heart failure\nMay cause reflex tachycardia\nAvoid with high-dose beta-blockers (risk of heart failure)',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nifedipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15',
   'DailyMed/FDA (NIH/NLM) — approved Nifedipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15'),
  ('metoprolol',
   'O metoprolol é um betabloqueador seletivo β1 que reduz a frequência cardíaca, a contractilidade miocárdica e a pressão arterial. Disponível em formulações de libertação imediata e prolongada.',
   'Metoprolol is a selective beta-1 blocker that reduces heart rate, myocardial contractility, and blood pressure. Available in immediate-release and extended-release formulations.',
   'Hipertensão arterial\nAngina de peito\nInsuficiência cardíaca (formulação prolongada)\nPós-enfarte miocárdico\nArritmias cardíacas\nEnxaqueca profilática',
   'Hypertension\nAngina pectoris\nHeart failure (extended-release)\nPost-myocardial infarction\nCardiac arrhythmias\nMigraine prophylaxis',
   'Betabloqueador seletivo β1. Metabolismo extenso via CYP2D6 (polimorfismo genético). Aproveitamento oral ~50%. Disponível em formulações de libertação imediata e prolongada. Dose habitual: 25-200 mg/dia.',
   'Selective beta-1 blocker. Extensive CYP2D6 metabolism (genetic polymorphism). Oral bioavailability ~50%. Available in immediate-release and extended-release formulations. Usual dose: 50-200 mg/day.',
   'Bradicardia\nFadiga\nTonturas\nDepressão\nInsónia\nMãos e pés frios\nBroncoespasmo (ligeiro)',
   'Bradycardia\nFatigue\nDizziness\nDepression\nInsomnia\nCold extremities\nMild bronchospasm',
   'CONTRAINDICADO em bloqueio AV de 2º e 3º grau\nCuidado em asma/DOPOC\nNão suspender abruptamente (risco de isquemia)\nAjuste de dose em disfunção hepática',
   'CONTRAINDICATED in 2nd and 3rd degree AV block\nCaution in asthma/COPD\nDo not discontinue abruptly (risk of ischaemia)\nDose adjustment in hepatic impairment',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee'),
  ('atenolol',
   'O atenolol é um betabloqueador seletivo β1 de ação prolongada, indicado para hipertensão e angina. Não atravessa significativamente a barreira hematoencefálica, causando menos efeitos neuropsiquiátricos.',
   'Atenolol is a long-acting selective beta-1 blocker indicated for hypertension and angina. Does not significantly cross the blood-brain barrier, causing fewer neuropsychiatric effects.',
   'Hipertensão arterial\nAngina de peito\nArritmias cardíacas\nPós-enfarte miocárdico\nEnxaqueca profilática',
   'Hypertension\nAngina pectoris\nCardiac arrhythmias\nPost-myocardial infarction\nMigraine prophylaxis',
   'Betabloqueador seletivo β1 hidrofílico. Não é metabolizado — excretado inalterado por via renal. Menor penetração no SNC. Aproveitamento oral ~50%. Dose habitual: 25-100 mg/dia. Ajustar em insuficiência renal.',
   'Selective hydrophilic beta-1 blocker. Not metabolised — excreted unchanged renally. Lower CNS penetration. Oral bioavailability ~50%. Usual dose: 25-100 mg/day. Adjust in renal impairment.',
   'Bradycardia\nFadiga\nTonturas\nMãos e pés frios\nDistúrbios gastrointestinais\nBroncoespasmo',
   'Bradycardia\nFatigue\nDizziness\nCold extremities\nGastrointestinal disturbances\nBronchospasm',
   'CONTRAINDICADO em bloqueio AV e em choque cardiogênico\nCuidado em asma/DOPOC\nNão suspender abruptamente\nExcretado por via renal — ajustar em insuficiência renal',
   'CONTRAINDICATED in AV block and cardiogenic shock\nCaution in asthma/COPD\nDo not discontinue abruptly\nRenally excreted — adjust in renal impairment',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atenolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=96dd038f-b363-4e24-9c67-82b7c85c3bc4',
   'DailyMed/FDA (NIH/NLM) — approved Atenolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=96dd038f-b363-4e24-9c67-82b7c85c3bc4'),
  ('propranolol',
   'O propranolol é um betabloqueador não seletivo (β1+β2) indicado para hipertensão, angina, arritmias, tremor essencial, enxaqueca e ansiedade situacional. É lipofílico e atravessa a barreira hematoencefálica.',
   'Propranolol is a non-selective beta-blocker (β1+β2) indicated for hypertension, angina, arrhythmias, essential tremor, migraine, and situational anxiety. It is lipophilic and crosses the blood-brain barrier.',
   'Hipertensão arterial\nAngina de peito\nArritmias cardíacas\nTremor essencial\nEnxaqueca profilática\nAnsiedade situacional\nFeocromocitoma (após alfa-bloqueio)\nHipertireoidismo (sintomático)',
   'Hypertension\nAngina pectoris\nCardiac arrhythmias\nEssential tremor\nMigraine prophylaxis\nSituational anxiety\nPhaeochromocytoma (after alpha-blockade)\nHyperthyroidism (symptomatic)',
   'Betabloqueador não seletivo lipofílico. Metabolismo extenso via CYP2D6/CYP1A2. Aproveitamento oral ~25%. Atividade estabilizadora de membrana. Único betabloqueador indicado para tremor essencial e enxaqueca.',
   'Non-selective lipophilic beta-blocker. Extensive CYP2D6/CYP1A2 metabolism. Oral bioavailability ~25%. Membrane-stabilising activity. Only beta-blocker indicated for essential tremor and migraine.',
   'Bradycardia\nFadiga\nTonturas\nDistúrbios do sono\nMãos e pés frios\nBroncoespasmo\nDepressão',
   'Bradycardia\nFatigue\nDizziness\nSleep disturbances\nCold extremities\nBronchospasm\nDepression',
   'CONTRAINDICADO em asma brônquica e DOPOC grave\nCuidado em diabetes (mascara hipoglicemia)\nNão suspender abruptamente\nLipofílico — mais efeitos neuropsiquiátricos',
   'CONTRAINDICATED in bronchial asthma and severe COPD\nCaution in diabetes (masks hypoglycaemia)\nDo not discontinue abruptly\nLipophilic — more neuropsychiatric effects',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4'),
  ('carvedilol',
   'O carvedilol é um betabloqueador com atividade bloqueadora α1 e β1+β2, indicado para hipertensão e insuficiência cardíaca. A bloqueio α1 confere vasodilatação adicional.',
   'Carvedilol is a beta-blocker with alpha-1 and beta-1+beta-2 blocking activity, indicated for hypertension and heart failure. The alpha-1 blockade provides additional vasodilation.',
   'Insuficiência cardíaca (moderada-severa)\nHipertensão arterial\nPós-enfarte miocárdico com disfunção ventricular esquerda',
   'Heart failure (moderate-severe)\nHypertension\nPost-myocardial infarction with left ventricular dysfunction',
   'Betabloqueador não seletivo com atividade bloqueadora α1. Metabolismo via CYP2D6 e CYP2C9. Aproveitamento oral 25-35%. Deve ser tomado com alimentos. Indicado para IC moderada-severa.',
   'Non-selective beta-blocker with alpha-1 blocking activity. Metabolised by CYP2D6 and CYP2C9. Oral bioavailability 25-35%. Should be taken with food. Indicated for moderate-severe heart failure.',
   'Fadiga\nTonturas\nHipotensão\nBradycardia\nDiarrreia\nEdema periférico\nGainho de peso',
   'Fatigue\nDizziness\nHypotension\nBradycardia\nDiarrhoea\nPeripheral oedema\nWeight gain',
   'CONTRAINDICADO em bloqueio AV e em choque cardiogênico\nCuidado em糖尿病 (mascara hipoglicemia)\nAjustar dose em disfunção hepática\nNão suspender abruptamente',
   'CONTRAINDICATED in AV block and cardiogenic shock\nCaution in diabetes (masks hypoglycaemia)\nAdjust dose in hepatic impairment\nDo not discontinue abruptly',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Carvedilol (Coreg): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07c619c6-4a0c-445e-94fa-664a54f68a39',
   'DailyMed/FDA (NIH/NLM) — approved Carvedilol (Coreg) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07c619c6-4a0c-445e-94fa-664a54f68a39'),
  ('bisoprolol',
   'O bisoprolol é um betabloqueador seletivo β1 de ação prolongada com a maior seletividade β1 entre os betabloqueadores disponíveis. Indicado para hipertensão, angina e insuficiência cardíaca.',
   'Bisoprolol is a long-acting selective beta-1 blocker with the highest beta-1 selectivity among available beta-blockers. Indicated for hypertension, angina, and heart failure.',
   'Hipertensão arterial\nAngina de peito\nInsuficiência cardíaca crónica estável\nPós-enfarte miocárdico',
   'Hypertension\nAngina pectoris\nStable chronic heart failure\nPost-myocardial infarction',
   'Betabloqueador seletivo β1 com maior seletividade (razão β1:β2 = 75:1). Metabolismo 50% hepático / 50% renal. Aproveitamento oral >90%. Dose habitual: 2,5-10 mg/dia. Sem polimorfismo genético significativo.',
   'Selective beta-1 blocker with highest selectivity (beta-1:beta-2 ratio = 75:1). 50% hepatic / 50% renal metabolism. Oral bioavailability >90%. Usual dose: 2.5-10 mg/day. No significant genetic polymorphism.',
   'Bradycardia\nFadiga\nTonturas\nCefaleia\nMãos e pés frios\nDistúrbios gastrointestinais',
   'Bradycardia\nFatigue\nDizziness\nHeadache\nCold extremities\nGastrointestinal disturbances',
   'CONTRAINDICADO em bloqueio AV e em choque cardiogênico\nCuidado em asma/DOPOC\nNão suspender abruptamente\nExcretado por via renal e hepática',
   'CONTRAINDICATED in AV block and cardiogenic shock\nCaution in asthma/COPD\nDo not discontinue abruptly\nRenally and hepatically excreted',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bisoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4f20df45-3f9c-4a91-b394-e93a08111ec3',
   'DailyMed/FDA (NIH/NLM) — approved Bisoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4f20df45-3f9c-4a91-b394-e93a08111ec3'),
  ('rosuvastatina',
   'A rosuvastatina é uma estatina de alta potência que inibe seletivamente a HMG-CoA redutase, reduzindo a síntese hepática de colesterol e elevando os recetores LDL.',
   'Rosuvastatin is a high-intensity statin that selectively inhibits HMG-CoA reductase, reducing hepatic cholesterol synthesis and upregulating LDL receptors.',
   'Hipercolesterolemia primária\nHiperlipidemia mista\nPrevenção cardiovascular primária e secundária\nAterosclerose progressiva',
   'Primary hypercholesterolaemia\nMixed dyslipidaemia\nPrimary and secondary cardiovascular prevention\nProgressive atherosclerosis',
   'Estatina de alta potência. Metabolismo mínimo via CYP2C9 (10%). Não é pró-fármaco. Aproveitamento oral ~20%. Meia-vida ~19h permite dose diária. Menor potencial de interações via CYP comparativamente a simvastatina.',
   'High-intensity statin. Minimal CYP2C9 metabolism (10%). Not a prodrug. Oral bioavailability ~20%. Half-life ~19h allows once-daily dosing. Lower CYP-mediated interaction potential compared to simvastatin.',
   'Cefaleia\nMialgia\nDor abdominal\nNáuseas\nAumento das transaminases\nRaramente: miopatia/rabdomiólise',
   'Headache\nMyalgia\nAbdominal pain\nNausea\nElevated transaminases\nRarely: myopathy/rhabdomyolysis',
   'CONTRAINDICADO na gravidez e aleitamento\nAjustar dose em insuficiência renal\nEvitar com gemfibrozilo (risco de miopatia)\nMonitorizar transaminases e CK',
   'CONTRAINDICATED in pregnancy and breastfeeding\nAdjust dose in renal impairment\nAvoid with gemfibrozil (risk of myopathy)\nMonitor transaminases and CK',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina (Crestor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=325a5d0e-9a72-4015-9fcd-1655fb504cee',
   'DailyMed/FDA (NIH/NLM) — approved Rosuvastatin (Crestor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=325a5d0e-9a72-4015-9fcd-1655fb504cee'),
  ('simvastatina',
   'A simvastatina é uma estatina de potência moderada que inibe a HMG-CoA redutase, reduzindo a síntese hepática de colesterol. É um pró-fármaco que requer ativação hepática.',
   'Simvastatin is a moderate-intensity statin that inhibits HMG-CoA reductase, reducing hepatic cholesterol synthesis. It is a prodrug requiring hepatic activation.',
   'Hipercolesterolemia primária\nHiperlipidemia mista\nPrevenção cardiovascular\nAterosclerose',
   'Primary hypercholesterolaemia\nMixed dyslipidaemia\nCardiovascular prevention\nAtherosclerosis',
   'Estatina de potência moderada. Pró-fármaco que requer hidrólise hepática. Metabolismo via CYP3A4 — MÚLTIPLOS CONTRAINDICAÇÕES com inibidores CYP3A4. Aproveitamento oral ~5%. Dose máxima 40 mg/dia (80 mg suspensa).',
   'Moderate-intensity statin. Prodrug requiring hepatic hydrolysis. CYP3A4 metabolism — MULTIPLE CONTRAINDICATIONS with CYP3A4 inhibitors. Oral bioavailability ~5%. Maximum dose 40 mg/day (80 mg withdrawn).',
   'Cefaleia\nMialgia\nDor abdominal\nNáuseas\nAumento das transaminases\nRaramente: miopatia/rabdomiólise',
   'Headache\nMyalgia\nAbdominal pain\nNausea\nElevated transaminases\nRarely: myopathy/rhabdomyolysis',
   'CONTRAINDICADO na gravidez e aleitamento\nEvitar suco de toranja (aumenta níveis)\nLimite 40 mg/dia (80 mg suspensa)\nMúltiplas interações via CYP3A4',
   'CONTRAINDICATED in pregnancy and breastfeeding\nAvoid grapefruit juice (increases levels)\nLimit 40 mg/day (80 mg withdrawn)\nNumerous CYP3A4-mediated interactions',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9'),
  ('isossorbida',
   'A isossorbida dinitrato é um nitrato orgânico que se converte em óxido nítrico (NO), provocando vasodilatação venosa e arterial, reduzindo a pré e pós-carga cardíaca.',
   'Isosorbide dinitrate is an organic nitrate that is converted to nitric oxide (NO), causing venous and arterial vasodilation, reducing cardiac preload and afterload.',
   'Angina de peito (profilaxia)\nInsuficiência cardíaca aguda e crónica\nHipertensão pulmonar',
   'Angina pectoris (prophylaxis)\nAcute and chronic heart failure\nPulmonary hypertension',
   'Nitrato orgânico de ação curta. Conversão em NO pelo músculo liso vascular. Metabolismo hepático por desidrogenase. Tolerância com uso contínuo — manter intervalo livre de 10-12h. Disponível em formulações oral e sublingual.',
   'Short-acting organic nitrate. Converted to NO by vascular smooth muscle. Hepatic metabolism by dehydrogenase. Tolerance with continuous use — maintain 10-12 hour nitrate-free interval. Available in oral and sublingual formulations.',
   'Cefaleia (comum)\nHipotensão ortostática\nTonturas\nRubor facial\nTaquicardia reflexa\nTolerância (efeito rebote)',
   'Headache (common)\nOrthostatic hypotension\nDizziness\nFacial flushing\nReflex tachycardia\nTolerance (rebound effect)',
   'CONTRAINDICADO com inibidores da PDE5 (sildenafil, tadalafil)\nEfeito rebote com suspensão abrupta\nTolerância com uso contínuo — manter intervalo livre\nHipotensão severa',
   'CONTRAINDICATED with PDE5 inhibitors (sildenafil, tadalafil)\nRebound effect with abrupt discontinuation\nTolerance with continuous use — maintain nitrate-free interval\nSevere hypotension',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541')
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
      indications_pt, indications_en,
      side_effects_pt, side_effects_en, precautions_pt, precautions_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- 3. Farmacologia (drug_pharmacology)
-- =====================================================================
INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en,
   mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en,
   absorption_pt, absorption_en,
   half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id,
  v.pharmacodynamics_pt, v.pharmacodynamics_en,
  v.mechanism_pt, v.mechanism_en,
  v.metabolism_pt, v.metabolism_en,
  v.absorption_pt, v.absorption_en,
  v.half_life_pt, v.half_life_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('lisinopril',
   'Inibe a enzima conversora da angiotensina (ECA), bloqueando a conversão de angiotensina I em angiotensina II e degradando a bradicinina.',
   'Inhibits the angiotensin-converting enzyme (ACE), blocking conversion of angiotensin I to angiotensin II and degrading bradykinin.',
   'Bloqueio da ECA resulta em redução da angiotensina II (vasoconstrição) e acumulação de bradicinina (vasodilatação). Efeito duplo anti-hipertensivo.',
   'ACE blockade results in reduced angiotensin II (vasoconstriction) and bradykinin accumulation (vasodilation). Dual antihypertensive effect.',
   'Não é metabolizado — excretado inalterado por via renal. Não sofre metabolismo hepático significativo. Não é pró-fármaco.',
   'Not metabolised — excreted unchanged by the renal route. Does not undergo significant hepatic metabolism. Not a prodrug.',
   'Biodisponibilidade oral: ~25%. Alimentos não afetam significativamente a absorção. Tmax: 7 horas.',
   'Oral bioavailability: ~25%. Food does not significantly affect absorption. Tmax: 7 hours.',
   '12 horas. Eliminação: 100% renal (inalterado). Ajustar dose em insuficiência renal.',
   '12 hours. Elimination: 100% renal (unchanged). Adjust dose in renal impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16'),
  ('losartana',
   'Bloqueador seletivo do recetor AT1 da angiotensina II, impedindo a vasoconstrição, secreção de aldosterona e remodelação cardíaca.',
   'Selective blocker of the angiotensin II AT1 receptor, preventing vasoconstriction, aldosterone secretion, and cardiac remodelling.',
   'Liga-se ao recetor AT1 da angiotensina II com alta afinidade, bloqueando todos os efeitos fisiológicos da angiotensina II mediados por este recetor.',
   'Binds to the angiotensin II AT1 receptor with high affinity, blocking all physiological effects of angiotensin II mediated by this receptor.',
   'Metabolizado pelo CYP2C9 e CYP3A4 ao metabólito ativo E-3174 (10-40x mais potente). Induzido por rifampicina. Potenciado por cimetidina.',
   'Metabolised by CYP2C9 and CYP3A4 to the active metabolite E-3174 (10-40x more potent). Induced by rifampicin. Boosted by cimetidine.',
   'Biodisponibilidade oral: ~33%. Alimentos não afetam significativamente a absorção. Tmax: 1-2 horas (losartana); 3-4 horas (E-3174).',
   'Oral bioavailability: ~33%. Food does not significantly affect absorption. Tmax: 1-2 hours (losartan); 3-4 hours (E-3174).',
   '2 horas (losartana); 6-9 horas (E-3174). Eliminação: ~35% fezes, ~60% urina (metabolitos).',
   '2 hours (losartan); 6-9 hours (E-3174). Elimination: ~35% faeces, ~60% urine (metabolites).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Losartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   'DailyMed/FDA (NIH/NLM) — approved Losartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31'),
  ('nifedipina',
   'Bloqueador seletivo dos canais de cálcio tipo L diidropiridínico que inibe o influxo transmembranar de cálcio no músculo liso vascular.',
   'Selective dihydropyridine L-type calcium channel blocker that inhibits transmembrane calcium influx into vascular smooth muscle.',
   'Bloqueia os canais de cálcio tipo L no músculo liso vascular, impedindo o influxo de Ca²⁺ e causando relaxamento do músculo liso e vasodilatação.',
   'Blocks L-type calcium channels in vascular smooth muscle, preventing Ca²⁺ influx and causing smooth muscle relaxation and vasodilation.',
   'Metabolizado pelo CYP3A4. Inibido por cetoconazol, eritromicina. Induzido por fenitoína, carbamazepina, rifampicina.',
   'Metabolised by CYP3A4. Inhibited by ketoconazole, erythromycin. Induced by phenytoin, carbamazepine, rifampicin.',
   'Biodisponibilidade oral: 45-68% (cápsulas). Alimentos aumentam a absorção. Tmax: 30-60 minutos (cápsulas).',
   'Oral bioavailability: 45-68% (capsules). Food increases absorption. Tmax: 30-60 minutes (capsules).',
   '2-5 horas. Eliminação: ~80% urina (metabolitos), ~20% fezes. Metabolismo de primeiro passo extenso.',
   '2-5 hours. Elimination: ~80% urine (metabolites), ~20% faeces. Extensive first-pass metabolism.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nifedipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15',
   'DailyMed/FDA (NIH/NLM) — approved Nifedipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15'),
  ('metoprolol',
   'Betabloqueador seletivo β1 que reduz a frequência cardíaca, a contractilidade e a condução AV. Efeito mínimo nos recetores β2 pulmonares.',
   'Selective beta-1 blocker that reduces heart rate, contractility, and AV conduction. Minimal effect on pulmonary beta-2 receptors.',
   'Bloqueia seletivamente os recetores β1 cardíacos, reduzindo a frequência cardíaca, a contractilidade miocárdica e a condução AV. Efeito dependente da dose.',
   'Selectively blocks cardiac beta-1 receptors, reducing heart rate, myocardial contractility, and AV conduction. Dose-dependent effect.',
   'Metabolizado extensivamente pelo CYP2D6. Inibido por fluoxetina, paroxetina, quinidina. Induzido por rifampicina. Polimorfismo genético CYP2D6.',
   'Extensively metabolised by CYP2D6. Inhibited by fluoxetine, paroxetine, quinidine. Induced by rifampicin. CYP2D6 genetic polymorphism.',
   'Biodisponibilidade oral: ~50% (primeiro passo hepático extenso). Alimentos aumentam a absorção. Tmax: 1-2 horas.',
   'Oral bioavailability: ~50% (extensive first-pass hepatic metabolism). Food increases absorption. Tmax: 1-2 hours.',
   '3-7 horas. Eliminação: ~95% urina (metabolitos), <5% inalterado. Ajustar em disfunção hepática.',
   '3-7 hours. Elimination: ~95% urine (metabolites), <5% unchanged. Adjust in hepatic impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee'),
  ('atenolol',
   'Betabloqueador seletivo β1 hidrofílico de ação prolongada. Menor penetração no SNC comparativamente ao metoprolol e propranolol.',
   'Selective hydrophilic beta-1 blocker with prolonged action. Lower CNS penetration compared to metoprolol and propranolol.',
   'Bloqueia seletivamente os recetores β1 cardíacos, reduzindo a frequência cardíaca, a contractilidade e a condução AV. Ação prolongada permite dose diária.',
   'Selectively blocks cardiac beta-1 receptors, reducing heart rate, contractility, and AV conduction. Prolonged action allows once-daily dosing.',
   'Não é metabolizado — excretado inalterado por via renal. Não sofre metabolismo hepático significativo. Baixo potencial de interações via CYP.',
   'Not metabolised — excreted unchanged by the renal route. Does not undergo significant hepatic metabolism. Low CYP-mediated interaction potential.',
   'Biodisponibilidade oral: ~50%. Alimentos reduzem ligeiramente a absorção. Tmax: 2-4 horas.',
   'Oral bioavailability: ~50%. Food slightly reduces absorption. Tmax: 2-4 hours.',
   '6-9 horas. Eliminação: >90% inalterado na urina. Ajustar dose em insuficiência renal (TFG <35 mL/min).',
   '6-9 hours. Elimination: >90% unchanged in urine. Adjust dose in renal impairment (GFR <35 mL/min).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atenolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=96dd038f-b363-4e24-9c67-82b7c85c3bc4',
   'DailyMed/FDA (NIH/NLM) — approved Atenolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=96dd038f-b363-4e24-9c67-82b7c85c3bc4'),
  ('propranolol',
   'Betabloqueador não seletivo (β1+β2) lipofílico que atravessa a barreira hematoencefálica. Atividade estabilizadora de membrana (efeito anestésico local).',
   'Non-selective lipophilic beta-blocker (β1+β2) that crosses the blood-brain barrier. Membrane-stabilising activity (local anaesthetic effect).',
   'Bloqueia não seletivamente os recetores β1 e β2, reduzindo a frequência cardíaca, a contractilidade, a condução AV e causando broncoespasmo (via β2).',
   'Non-selectively blocks beta-1 and beta-2 receptors, reducing heart rate, contractility, AV conduction, and causing bronchospasm (via beta-2).',
   'Metabolizado extensivamente pelo CYP2D6 e CYP1A2. Inibido por fluoxetina, cimetidina. Induzido por rifampicina. Polimorfismo genético.',
   'Extensively metabolised by CYP2D6 and CYP1A2. Inhibited by fluoxetine, cimetidine. Induced by rifampicin. Genetic polymorphism.',
   'Biodisponibilidade oral: ~25% (metabolismo de primeiro passo extenso). Alimentos aumentam a absorção. Tmax: 1-2 horas.',
   'Oral bioavailability: ~25% (extensive first-pass metabolism). Food increases absorption. Tmax: 1-2 hours.',
   '3-6 horas. Eliminação: ~90% urina (metabolitos), <1% inalterado. Ajustar em disfunção hepática.',
   '3-6 hours. Elimination: ~90% urine (metabolites), <1% unchanged. Adjust in hepatic impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4'),
  ('carvedilol',
   'Betabloqueador não seletivo (β1+β2) com atividade bloqueadora α1 adrenérgica. A bloqueio α1 confere vasodilatação e reduz a resistência vascular periférica.',
   'Non-selective beta-blocker (β1+β2) with alpha-1 adrenergic blocking activity. Alpha-1 blockade provides vasodilation and reduces peripheral vascular resistance.',
   'Bloqueia simultaneamente recetores β1, β2 e α1, reduzindo a frequência cardíaca, a contractilidade e a resistência vascular periférica. Efeito anti-hipertensivo triple.',
   'Simultaneously blocks beta-1, beta-2, and alpha-1 receptors, reducing heart rate, contractility, and peripheral vascular resistance. Triple antihypertensive effect.',
   'Metabolizado pelo CYP2D6 e CYP2C9. Inibido por fluoxetina, paroxetina. Polimorfismo CYP2D6 afecta exposição.',
   'Metabolised by CYP2D6 and CYP2C9. Inhibited by fluoxetine, paroxetine. CYP2D6 polymorphism affects exposure.',
   'Biodisponibilidade oral: 25-35%. Alimentos aumentam significativamente a absorção (deve ser tomado com alimentos). Tmax: 1-2 horas.',
   'Oral bioavailability: 25-35%. Food significantly increases absorption (should be taken with food). Tmax: 1-2 hours.',
   '6-10 horas. Eliminação: ~60% fezes, ~16% urina. Metabolismo hepático extenso.',
   '6-10 hours. Elimination: ~60% faeces, ~16% urine. Extensive hepatic metabolism.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Carvedilol (Coreg): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07c619c6-4a0c-445e-94fa-664a54f68a39',
   'DailyMed/FDA (NIH/NLM) — approved Carvedilol (Coreg) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07c619c6-4a0c-445e-94fa-664a54f68a39'),
  ('bisoprolol',
   'Betabloqueador seletivo β1 com a maior seletividade entre os betabloqueadores disponíveis. Ação prolongada permite dose diária.',
   'Selective beta-1 blocker with the highest selectivity among available beta-blockers. Prolonged action allows once-daily dosing.',
   'Bloqueia seletivamente os recetores β1 cardíacos com razão de seletividade β1:β2 de 75:1, reduzindo a frequência cardíaca e a contractilidade.',
   'Selectively blocks cardiac beta-1 receptors with a beta-1:beta-2 selectivity ratio of 75:1, reducing heart rate and contractility.',
   'Metabolizado ~50% hepaticamente (CYP3A4) e ~50% renalmente. Não sofre polimorfismo genético significativo. Interações mínimas via CYP.',
   'Metabolised ~50% hepatically (CYP3A4) and ~50% renally. No significant genetic polymorphism. Minimal CYP-mediated interactions.',
   'Biodisponibilidade oral: >90%. Alimentos não afetam significativamente a absorção. Tmax: 2-4 horas.',
   'Oral bioavailability: >90%. Food does not significantly affect absorption. Tmax: 2-4 hours.',
   '10-12 horas. Eliminação: ~50% urina (metabolitos e inalterado), ~50% fezes. Não requer ajuste na insuficiência hepática.',
   '10-12 hours. Elimination: ~50% urine (metabolites and unchanged), ~50% faeces. No adjustment required in hepatic impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Bisoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4f20df45-3f9c-4a91-b394-e93a08111ec3',
   'DailyMed/FDA (NIH/NLM) — approved Bisoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4f20df45-3f9c-4a91-b394-e93a08111ec3'),
  ('rosuvastatina',
   'Inibidor competitivo e reversível da HMG-CoA redutase, enzima limitante da síntese hepática de colesterol. Estatina de alta potência.',
   'Competitive and reversible inhibitor of HMG-CoA reductase, the rate-limiting enzyme in hepatic cholesterol synthesis. High-intensity statin.',
   'Inibe seletivamente a HMG-CoA redutase, bloqueando a conversão de HMG-CoA a mevalonato, precursor do colesterol. Eleva os recetores LDL hepatários.',
   'Selectively inhibits HMG-CoA reductase, blocking conversion of HMG-CoA to mevalonate, a cholesterol precursor. Upregulates hepatic LDL receptors.',
   'Metabolizado minimamente pelo CYP2C9 (10%). Não é pró-fármaco. Inibido levemente pelo cimetidina. Baixo potencial de interações via CYP.',
   'Minimally metabolised by CYP2C9 (10%). Not a prodrug. Slightly inhibited by cimetidine. Low CYP-mediated interaction potential.',
   'Biodisponibilidade oral: ~20%. Alimentos não afetam significativamente a absorção. Tmax: 3-5 horas.',
   'Oral bioavailability: ~20%. Food does not significantly affect absorption. Tmax: 3-5 hours.',
   '~19 horas. Eliminação: ~90% fezes, ~10% urina. Meia-vida longa permite dose diária.',
   '~19 hours. Elimination: ~90% faeces, ~10% urine. Long half-life allows once-daily dosing.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina (Crestor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=325a5d0e-9a72-4015-9fcd-1655fb504cee',
   'DailyMed/FDA (NIH/NLM) — approved Rosuvastatin (Crestor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=325a5d0e-9a72-4015-9fcd-1655fb504cee'),
  ('simvastatina',
   'Inibidor da HMG-CoA redutase de potência moderada. É um pró-fármaco que requer hidrólise hepática ao metabolito ativo (ácido simvastatínico).',
   'Moderate-intensity HMG-CoA reductase inhibitor. It is a prodrug requiring hepatic hydrolysis to the active metabolite (simvastatin acid).',
   'Pró-fármaco que sofre hidrólise hepática pela esterases ao ácido simvastatínico (metabólito ativo), que inibe a HMG-CoA redutase.',
   'Prodrug that undergoes hepatic hydrolysis by esterases to simvastatin acid (active metabolite), which inhibits HMG-CoA reductase.',
   'Metabolizado pelo CYP3A4. Múltiplas interações: inibidores fortes (cetoconazol, itraconazol, eritromicina, claritromicina) CONTRAINDICADOS. Induzido por rifampicina, fenitoína, carbamazepina.',
   'Metabolised by CYP3A4. Numerous interactions: strong inhibitors (ketoconazole, itraconazole, erythromycin, clarithromycin) CONTRAINDICATED. Induced by rifampicin, phenytoin, carbamazepine.',
   'Biodisponibilidade oral: ~5%. Alimentos aumentam ligeiramente a absorção. Tmax: 1,3-2,4 horas.',
   'Oral bioavailability: ~5%. Food slightly increases absorption. Tmax: 1.3-2.4 hours.',
   '~2 horas (metabólito ativo). Eliminação: ~60% fezes, ~13% urina. Metabolismo de primeiro passo extenso.',
   '~2 hours (active metabolite). Elimination: ~60% faeces, ~13% urine. Extensive first-pass metabolism.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9'),
  ('isossorbida',
   'Nitrato orgânico que se converte em óxido nítrico (NO) no músculo liso vascular, ativando a guamilato ciclase e elevando o GMPc, causando vasodilatação.',
   'Organic nitrate that is converted to nitric oxide (NO) in vascular smooth muscle, activating guanylate cyclase and raising cGMP, causing vasodilation.',
   'É convertido em óxido nítrico (NO) pelo músculo liso vascular. O NO ativa a guamilato ciclase solúvel, elevando o GMPc intracelular e provocando relaxamento do músculo liso.',
   'Is converted to nitric oxide (NO) by vascular smooth muscle. NO activates soluble guanylate cyclase, raising intracellular cGMP and causing smooth muscle relaxation.',
   'Metabolizado hepaticamente (desidrogenase). Tolerância com uso contínuo (depleção de grupamentos sulfidrilo). Não sofre interações via CYP.',
   'Hepatically metabolised (dehydrogenase). Tolerance with continuous use (sulphydryl group depletion). No CYP-mediated interactions.',
   'Biodisponibilidade oral: 25-50% (efeito de primeiro passo extenso). Deve ser administrado em jejum para máxima absorção. Tmax: 15-30 minutos (sublingual).',
   'Oral bioavailability: 25-50% (extensive first-pass effect). Should be administered on an empty stomach for maximum absorption. Tmax: 15-30 minutes (sublingual).',
   '1 hora (oral); minutos (sublingual). Eliminação: urina (metabolitos glucuronidados).',
   '1 hour (oral); minutes (sublingual). Elimination: urine (glucuronide metabolites).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541')
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en,
       mechanism_pt, mechanism_en,
       metabolism_pt, metabolism_en,
       absorption_pt, absorption_en,
       half_life_pt, half_life_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
