-- =====================================================================
-- 199 — Expansão: pares de interação + dimensões cardiovasculares
--
-- Pares críticos/moderados dos 11 fármacos novos com fármacos existentes
-- Dimensões: alimento, doença, gravidez/lactação
-- Fontes: DailyMed, EMC-UK, Prontuário Terapêutico
-- =====================================================================

-- =====================================================================
-- 1. Pares de interação (drug_interactions)
-- =====================================================================
INSERT INTO public.drug_interactions
  (drug_a_id, drug_b_id, severity, summary_pt, summary_en,
   mechanism_pt, mechanism_en, management_pt, management_en,
   monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
   source_pt, source_en, source_url, status)
SELECT a.id, b.id, v.severity, v.summary_pt, v.summary_en,
  v.mechanism_pt, v.mechanism_en, v.management_pt, v.management_en,
  v.monitoring_pt, v.monitoring_en, v.red_flags_pt, v.red_flags_en,
  v.source_pt, v.source_en, v.source_url,
  'published'
FROM (VALUES
  ('espironolactona', 'lisinopril', 'critical',
   'Inibidor ECA + espironolactona: risco grave de hipercalemia.',
   'ACE inhibitor + spironolactone: serious risk of hyperkalaemia.',
   'Ambos reduzem a excreção renal de potássio. A combinação pode causar hipercalemia severa e potencialmente fatal. Monitorizar K+ e função renal rigorosamente.',
   'Both reduce renal potassium excretion. The combination can cause severe and potentially fatal hyperkalaemia. Monitor K+ and renal function closely.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   ''),
  ('furosemida', 'lisinopril', 'moderate',
   'Inibidor ECA + diurético de alça: potencial de hipotensão excessiva.',
   'ACE inhibitor + loop diuretic: potential for excessive hypotension.',
   'A combinação pode causar hipotensão sintomática, especialmente na primeira dose do IECA. Iniciar IECA com dose baixa e ajustar consoante a resposta.',
   'The combination may cause symptomatic hypotension, especially with the first ACE inhibitor dose. Start ACEI at low dose and adjust according to response.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   ''),
  ('hidroclorotiazida', 'lisinopril', 'moderate',
   'Inibidor ECA + tiazídico: potencial de hipotensão excessiva.',
   'ACE inhibitor + thiazide: potential for excessive hypotension.',
   'A combinação pode causar hipotensão sintomática. Iniciar IECA com dose baixa e ajustar consoante a resposta hemodinâmica.',
   'The combination may cause symptomatic hypotension. Start ACEI at low dose and adjust according to hemodynamic response.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   ''),
  ('espironolactona', 'losartana', 'critical',
   'BRA + espironolactona: risco grave de hipercalemia.',
   'ARB + spironolactone: serious risk of hyperkalaemia.',
   'Ambos reduzem a excreção renal de potássio. A combinação pode causar hipercalemia severa. Monitorizar K+ e função renal.',
   'Both reduce renal potassium excretion. The combination can cause severe hyperkalaemia. Monitor K+ and renal function.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Losartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   'DailyMed/FDA (NIH/NLM) — approved Losartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   ''),
  ('ibuprofeno', 'losartana', 'moderate',
   'BRA + AINE: redução do efeito anti-hipertensivo e risco renal.',
   'ARB + NSAID: reduced antihypertensive effect and renal risk.',
   'Os AINE inibem as prostaglandinas renais, reduzindo a eficácia dos BRA e aumentando o risco de disfunção renal e hipercalemia.',
   'NSAIDs inhibit renal prostaglandins, reducing ARB efficacy and increasing the risk of renal dysfunction and hyperkalaemia.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Losartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   'DailyMed/FDA (NIH/NLM) — approved Losartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   ''),
  ('nifedipina', 'sildenafil', 'critical',
   'Bloqueador do cálcio + inibidor da PDE5: risco de hipotensão severa.',
   'Calcium channel blocker + PDE5 inhibitor: risk of severe hypotension.',
   'Ambos causam vasodilatação. A combinação pode causar hipotensão severa e sintomática. Considerar dose reduzida de sildenafil.',
   'Both cause vasodilation. The combination can cause severe symptomatic hypotension. Consider reduced sildenafil dose.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nifedipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15',
   'DailyMed/FDA (NIH/NLM) — approved Nifedipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15',
   ''),
  ('amiodarona', 'metoprolol', 'critical',
   'Betabloqueador + antiarrítmico: risco de bradicardia severa e bloqueio AV.',
   'Beta-blocker + antiarrhythmic: risk of severe bradycardia and AV block.',
   'Ambos reduzem a condução AV e a frequência cardíaca. A combinação pode causar bradicardia severa, bloqueio AV e parada cardíaca.',
   'Both reduce AV conduction and heart rate. The combination can cause severe bradycardia, AV block, and cardiac arrest.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   ''),
  ('verapamilo', 'metoprolol', 'critical',
   'Betabloqueador + bloqueador do cálcio (não diidropiridínico): risco de bloqueio AV e insuficiência cardíaca.',
   'Beta-blocker + non-dihydropyridine CCB: risk of AV block and heart failure.',
   'Ambos reduzem a condução AV e a contractilidade. A combinação pode causar bloqueio AV severo, bradicardia e insuficiência cardíaca.',
   'Both reduce AV conduction and contractility. The combination can cause severe AV block, bradycardia, and heart failure.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   ''),
  ('fluoxetina', 'metoprolol', 'moderate',
   'Betabloqueador + ISRS: inibição do CYP2D6 aumenta níveis de metoprolol.',
   'Beta-blocker + SSRI: CYP2D6 inhibition increases metoprolol levels.',
   'A fluoxetina inibe potente o CYP2D6, aumentando os níveis plasmáticos de metoprolol em 2-5 vezes. Risco de bradicardia e hipotensão.',
   'Fluoxetine potently inhibits CYP2D6, increasing metoprolol plasma levels 2-5 fold. Risk of bradycardia and hypotension.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   ''),
  ('propranolol', 'verapamilo', 'critical',
   'Betabloqueador + bloqueador do cálcio: risco de bloqueio AV severo e parada cardíaca.',
   'Beta-blocker + calcium channel blocker: risk of severe AV block and cardiac arrest.',
   'Ambos deprimem a condução AV e a contractilidade. A combinação pode causar bloqueio AV de alto grau e parada cardíaca.',
   'Both depress AV conduction and contractility. The combination can cause high-grade AV block and cardiac arrest.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   ''),
  ('propranolol', 'cimetidina', 'moderate',
   'Betabloqueador + anti-H2: inibição do metabolismo hepático do propranolol.',
   'Beta-blocker + H2 blocker: inhibition of hepatic metabolism of propranolol.',
   'A cimetidina inibe o CYP, aumentando os níveis plasmáticos de propranolol. Risco de bradicardia e hipotensão excessiva.',
   'Cimetidine inhibits CYP, increasing propranolol plasma levels. Risk of excessive bradycardia and hypotension.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   ''),
  ('simvastatina', 'cetoconazol', 'critical',
   'Estatina + antifúngico azólico: CONTRAINDICADO — níveis de simvastatina aumentados >10x.',
   'Statin + azole antifungal: CONTRAINDICATED — simvastatin levels increased >10-fold.',
   'O cetoconazol inibe potente o CYP3A4, aumentando os níveis de simvastatina mais de 10 vezes. CONTRAINDICADO — risco extremo de rabdomiólise.',
   'Ketoconazole potently inhibits CYP3A4, increasing simvastatin levels more than 10-fold. CONTRAINDICATED — extreme risk of rhabdomyolysis.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   ''),
  ('simvastatina', 'eritromicina', 'critical',
   'Estatina + macrólido: CONTRAINDICADO — níveis de simvastatina aumentados significativamente.',
   'Statin + macrolide: CONTRAINDICATED — simvastatin levels significantly increased.',
   'A eritromicina inibe o CYP3A4, aumentando os níveis de simvastatina e o risco de miopatia e rabdomiólise. CONTRAINDICADO.',
   'Erythromycin inhibits CYP3A4, increasing simvastatin levels and the risk of myopathy and rhabdomyolysis. CONTRAINDICATED.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   ''),
  ('amiodarona', 'simvastatina', 'moderate',
   'Estatina + antiarrítmico: aumento do risco de miopatia.',
   'Statin + antiarrhythmic: increased risk of myopathy.',
   'A amiodarona pode aumentar os níveis de simvastatina. Dose máxima de simvastatina: 20 mg/dia com amiodarona.',
   'Amiodarone may increase simvastatin levels. Maximum simvastatin dose: 20 mg/day with amiodarone.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   ''),
  ('isossorbida', 'sildenafil', 'critical',
   'Nitrato + inibidor da PDE5: CONTRAINDICADO — hipotensão severa potencialmente fatal.',
   'Nitrate + PDE5 inhibitor: CONTRAINDICATED — potentially fatal severe hypotension.',
   'Ambos causam vasodilatação potente. A combinação pode causar hipotensão severa e potencialmente fatal. CONTRAINDICADO — intervalo mínimo de 24h.',
   'Both cause potent vasodilation. The combination can cause severe and potentially fatal hypotension. CONTRAINDICATED — minimum 24-hour interval.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   ''),
  ('tadalafil', 'isossorbida', 'critical',
   'Nitrato + inibidor da PDE5: CONTRAINDICADO — hipotensão severa potencialmente fatal.',
   'Nitrate + PDE5 inhibitor: CONTRAINDICATED — potentially fatal severe hypotension.',
   'Ambos causam vasodilatação potente. A combinação pode causar hipotensão severa e potencialmente fatal. CONTRAINDICADO — intervalo mínimo de 24h.',
   'Both cause potent vasodilation. The combination can cause severe and potentially fatal hypotension. CONTRAINDICATED — minimum 24-hour interval.',
   '', '',
   '', '',
   '', '',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   '')
) AS v(slug_a, slug_b, severity,
      summary_pt, summary_en,
      mechanism_pt, mechanism_en, management_pt, management_en,
      monitoring_pt, monitoring_en, red_flags_pt, red_flags_en,
      source_pt, source_en, source_url)
JOIN public.drugs a ON a.slug = v.slug_a
JOIN public.drugs b ON b.slug = v.slug_b
ON CONFLICT (drug_a_id, drug_b_id) DO NOTHING;

-- =====================================================================
-- 2. Dimensões: Alimento/Bebida (drug_food_interactions)
-- =====================================================================
INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en,
   severity, mechanism_pt, mechanism_en, advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en,
  v.severity, v.mechanism_pt, v.mechanism_en, v.advice_pt, v.advice_en,
  v.source_pt, v.source_en, 1, 'published'
FROM (VALUES
  ('simvastatina', 'sumo_toranja', 'Sumo de toranja', 'Grapefruit juice',
   'moderate', 'Aumenta significativamente os níveis de simvastatina (inibe CYP3A4 intestinal).',
   'Significantly increases simvastatin levels (inhibits intestinal CYP3A4).',
   'Evitar sumo de toranja. Pode substituir por outras estatinas (rosuvastatina, pravastatina).',
   'Avoid grapefruit juice. May substitute with other statins (rosuvastatin, pravastatin).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9'),
  ('nifedipina', 'sumo_toranja', 'Sumo de toranja', 'Grapefruit juice',
   'moderate', 'Aumenta os níveis de nifedipina (inibe CYP3A4 intestinal).',
   'Increases nifedipine levels (inhibits intestinal CYP3A4).',
   'Evitar quantidades excessivas de sumo de toranja.',
   'Avoid excessive amounts of grapefruit juice.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nifedipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15',
   'DailyMed/FDA (NIH/NLM) — approved Nifedipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15'),
  ('isossorbida', 'alcool', 'Bebidas alcoólicas', 'Alcoholic beverages',
   'moderate', 'O álcool potencia o efeito hipotensivo da isossorbida.',
   'Alcohol potentiates the hypotensive effect of isosorbide.',
   'Evitar ou limitar o consumo de álcool durante o tratamento.',
   'Avoid or limit alcohol consumption during treatment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541'),
  ('carvedilol', 'alimentos', 'Alimentos', 'Food',
   'none', 'Os alimentos aumentam significativamente a absorção do carvedilol (deve ser tomado com alimentos).',
   'Food significantly increases carvedilol absorption (should be taken with food).',
   'Tomar sempre com alimentos para garantir absorção consistente.',
   'Always take with food to ensure consistent absorption.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Carvedilol (Coreg): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07c619c6-4a0c-445e-94fa-664a54f68a39',
   'DailyMed/FDA (NIH/NLM) — approved Carvedilol (Coreg) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=07c619c6-4a0c-445e-94fa-664a54f68a39')
) AS v(slug, entity_slug, entity_pt, entity_en,
       severity, mechanism_pt, mechanism_en, advice_pt, advice_en,
       source_pt, source_en)
JOIN public.drugs d ON d.slug = v.slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- =====================================================================
-- 3. Dimensões: Doença/Condição (drug_disease_interactions)
-- =====================================================================
INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en,
   interaction_type, severity, reason_pt, reason_en,
   advice_pt, advice_en,
   source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en,
  v.interaction_type, v.severity, v.reason_pt, v.reason_en,
  v.advice_pt, v.advice_en,
  v.source_pt, v.source_en, 1, 'published'
FROM (VALUES
  ('lisinopril', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment',
   'precaution', 'moderate', 'Pode agravar a insuficiência renal. Reduzir dose ou suspender se creatinina >3x o normal.',
   'May worsen renal impairment. Reduce dose or discontinue if creatinine >3x normal.',
   'Monitorizar TFG e creatinina. Ajustar ou suspender consoante a função renal.',
   'Monitor GFR and creatinine. Adjust or discontinue according to renal function.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16'),
  ('losartana', 'insuficiencia_hepatica', 'Insuficiência hepática', 'Hepatic impairment',
   'precaution', 'moderate', 'Ajuste de dose necessário na insuficiência hepática moderada-severa.',
   'Dose adjustment required in moderate-severe hepatic impairment.',
   'Iniciar com dose reduzida em insuficiência hepática.',
   'Start with reduced dose in hepatic impairment.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Losartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   'DailyMed/FDA (NIH/NLM) — approved Losartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31'),
  ('metoprolol', 'asma_bronquica', 'Asma brônquica', 'Bronchial asthma',
   'precaution', 'moderate', 'Pode causar broncoespasmo em doentes com asma. Preferir betabloqueador cardioseletivo.',
   'May cause bronchospasm in asthmatic patients. Prefer cardioselective beta-blocker.',
   'Evitar em asma grave. Usar dose mínima se necessário.',
   'Avoid in severe asthma. Use minimum dose if necessary.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee'),
  ('propranolol', 'asma_bronquica', 'Asma brônquica', 'Bronchial asthma',
   'contraindication', 'critical', 'CONTRAINDICADO em asma brônquica — bloqueio β2 causa broncoespasmo severo.',
   'CONTRAINDICATED in bronchial asthma — beta-2 blockade causes severe bronchospasm.',
   'CONTRAINDICADO em qualquer forma de asma ou DOPOC grave.',
   'CONTRAINDICATED in any form of asthma or severe COPD.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4'),
  ('propranolol', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus',
   'precaution', 'moderate', 'Mascara os sintomas adrenérgicos da hipoglicemia (taquicardia, tremor).',
   'Masks the adrenergic symptoms of hypoglycaemia (tachycardia, tremor).',
   'Monitorizar glicemia frequentemente. Preferir betabloqueador cardioseletivo.',
   'Monitor blood glucose frequently. Prefer cardioselective beta-blocker.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4'),
  ('isossorbida', 'insuficiencia_cardiaca_grave', 'Insuficiência cardíaca grave', 'Severe heart failure',
   'precaution', 'moderate', 'Pode causar hipotensão severa. Usar com cautela em IC grave.',
   'May cause severe hypotension. Use with caution in severe heart failure.',
   'Iniciar com dose baixa e titrar lentamente.',
   'Start at low dose and titrate slowly.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541')
) AS v(slug, condition_slug, condition_pt, condition_en,
       interaction_type, severity, reason_pt, reason_en,
       advice_pt, advice_en,
       source_pt, source_en)
JOIN public.drugs d ON d.slug = v.slug
ON CONFLICT DO NOTHING;

-- =====================================================================
-- 4. Dimensões: Gravidez/Lactação (drug_pregnancy_info)
-- =====================================================================
INSERT INTO public.drug_pregnancy_info
  (drug_id, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
   lactation_pt, lactation_en, contraception_pt, contraception_en,
   source_pt, source_en, status)
SELECT d.id, v.pregnancy_category, v.risk_pt, v.risk_en, v.trimester_pt, v.trimester_en,
  v.lactation_pt, v.lactation_en, v.contraception_pt, v.contraception_en,
  v.source_pt, v.source_en, 'published'
FROM (VALUES
  ('lisinopril', 'contraindicated',
   'CONTRAINDICADO na gravidez. Efeitos teratogênicos: malformações renais, hipoplasia pulmonar, hipotensão neonatal.',
   'CONTRAINDICATED in pregnancy. Teratogenic effects: renal malformations, pulmonary hypoplasia, neonatal hypotension.',
   'CONTRAINDICADO em todos os trimestres.', 'CONTRAINDICATED in all trimesters.',
   'Desconhecido se excretado no leite. Preferir alternativas.',
   'Unknown if excreted in breast milk. Prefer alternatives.',
   'Suspender antes da conceção. Não usar durante a gravidez e aleitamento.',
   'Discontinue before conception. Do not use during pregnancy or breastfeeding.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Lisinopril: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16',
   'DailyMed/FDA (NIH/NLM) — approved Lisinopril label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e6898cf8-34c8-44d5-8a86-fbe3be847b16'),
  ('losartana', 'contraindicated',
   'CONTRAINDICADO na gravidez. Risco de lesão fetalrenal e neonatal.',
   'CONTRAINDICATED in pregnancy. Risk of fetal/neonatal renal injury.',
   'CONTRAINDICADO em todos os trimestres.', 'CONTRAINDICATED in all trimesters.',
   'Desconhecido se excretado no leite. Preferir alternativas.',
   'Unknown if excreted in breast milk. Prefer alternatives.',
   'Suspender antes da conceção. Não usar durante a gravidez e aleitamento.',
   'Discontinue before conception. Do not use during pregnancy or breastfeeding.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Losartana: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31',
   'DailyMed/FDA (NIH/NLM) — approved Losartan label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1dadbe02-289c-4312-9e65-40f3314dcc31'),
  ('nifedipina', 'caution',
   'Usar apenas se benefício justificar risco. Pode causar hipotensão materna e fetal.',
   'Use only if benefit justifies risk. May cause maternal and fetal hypotension.',
   'Evitar no 1º trimestre se possível.', 'Avoid in 1st trimester if possible.',
   'Excretado no leite em baixas concentrações. Geralmente compatível.',
   'Excreted in breast milk in low concentrations. Generally compatible.',
   'Usar a dose mínima eficaz. Monitorizar pressão arterial materna e fetal.',
   'Use the minimum effective dose. Monitor maternal and fetal blood pressure.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Nifedipina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15',
   'DailyMed/FDA (NIH/NLM) — approved Nifedipine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b8b8cfee-ea71-44c2-81af-675efecfdf15'),
  ('metoprolol', 'caution',
   'Usar apenas se benefício justificar risco. Pode causar bradicardia e hipoglicemia no neonato.',
   'Use only if benefit justifies risk. May cause neonatal bradycardia and hypoglycaemia.',
   'Evitar no 3º trimestre se possível.', 'Avoid in 3rd trimester if possible.',
   'Excretado no leite. Geralmente compatível com amamentação.',
   'Excreted in breast milk. Generally compatible with breastfeeding.',
   'Monitorizar neonato para bradicardia e hipoglicemia no parto.',
   'Monitor neonate for bradycardia and hypoglycaemia at delivery.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Metoprolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee',
   'DailyMed/FDA (NIH/NLM) — approved Metoprolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5466243e-1e3d-175e-e063-6394a90a5dee'),
  ('atenolol', 'caution',
   'Usar apenas se benefício justificar risco. Pode causar bradicardia e hipoglicemia no neonato.',
   'Use only if benefit justifies risk. May cause neonatal bradycardia and hypoglycaemia.',
   'Evitar no 3º trimestre se possível.', 'Avoid in 3rd trimester if possible.',
   'Excretado no leite. Geralmente compatível com amamentação.',
   'Excreted in breast milk. Generally compatible with breastfeeding.',
   'Monitorizar neonato para bradicardia e hipoglicemia no parto.',
   'Monitor neonate for bradycardia and hypoglycaemia at delivery.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Atenolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=96dd038f-b363-4e24-9c67-82b7c85c3bc4',
   'DailyMed/FDA (NIH/NLM) — approved Atenolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=96dd038f-b363-4e24-9c67-82b7c85c3bc4'),
  ('propranolol', 'caution',
   'Usar apenas se benefício justificar risco. Pode causar bradicardia, hipoglicemia e distúrbios respiratórios no neonato.',
   'Use only if benefit justifies risk. May cause neonatal bradycardia, hypoglycaemia, and respiratory distress.',
   'Evitar no 3º trimestre se possível.', 'Avoid in 3rd trimester if possible.',
   'Excretado no leite em baixas concentrações. Geralmente compatível.',
   'Excreted in breast milk in low concentrations. Generally compatible.',
   'Monitorizar neonato para bradicardia, hipoglicemia e distúrbios respiratórios.',
   'Monitor neonate for bradycardia, hypoglycaemia, and respiratory distress.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Propranolol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4',
   'DailyMed/FDA (NIH/NLM) — approved Propranolol label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0d5ac315-df2b-4b3a-bc7e-ad04752865c4'),
  ('rosuvastatina', 'contraindicated',
   'CONTRAINDICADO na gravidez e aleitamento. Risco de malformações fetais.',
   'CONTRAINDICATED in pregnancy and breastfeeding. Risk of fetal malformations.',
   'CONTRAINDICADO em todos os trimestres.', 'CONTRAINDICATED in all trimesters.',
   'Não usar durante o aleitamento.',
   'Do not use during breastfeeding.',
   'Suspender pelo menos 3 meses antes da conceção.',
   'Discontinue at least 3 months before conception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Rosuvastatina (Crestor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=325a5d0e-9a72-4015-9fcd-1655fb504cee',
   'DailyMed/FDA (NIH/NLM) — approved Rosuvastatin (Crestor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=325a5d0e-9a72-4015-9fcd-1655fb504cee'),
  ('simvastatina', 'contraindicated',
   'CONTRAINDICADO na gravidez e aleitamento. Risco de malformações fetais.',
   'CONTRAINDICATED in pregnancy and breastfeeding. Risk of fetal malformations.',
   'CONTRAINDICADO em todos os trimestres.', 'CONTRAINDICATED in all trimesters.',
   'Não usar durante o aleitamento.',
   'Do not use during breastfeeding.',
   'Suspender pelo menos 3 meses antes da conceção.',
   'Discontinue at least 3 months before conception.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Simvastatina (Zocor): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9',
   'DailyMed/FDA (NIH/NLM) — approved Simvastatin (Zocor) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9'),
  ('isossorbida', 'caution',
   'Usar apenas se benefício justificar risco. Pode causar hipotensão materna.',
   'Use only if benefit justifies risk. May cause maternal hypotension.',
   'Usar com cautela em qualquer trimestre.', 'Use with caution in any trimester.',
   'Desconhecido se excretado no leite. Preferir alternativas.',
   'Unknown if excreted in breast milk. Prefer alternatives.',
   'Usar dose mínima eficaz. Monitorizar pressão arterial.',
   'Use minimum effective dose. Monitor blood pressure.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Isossorbida Dinitrato: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541',
   'DailyMed/FDA (NIH/NLM) — approved Isosorbide Dinitrate label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=44ede034-1fa1-4993-9aa5-49e04fada541')
) AS v(slug, pregnancy_category, risk_pt, risk_en, trimester_pt, trimester_en,
       lactation_pt, lactation_en, contraception_pt, contraception_en,
       source_pt, source_en)
JOIN public.drugs d ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
