-- =====================================================================
-- 202 — Expansão: 9 antidiabéticos novos (WHO EML)
--
-- Fármacos: empagliflozina, dapagliflozina, canagliflozina,
--           sitagliptina, saxagliptina, vildagliptina,
--           liraglutida, dulaglutida, acarbose
-- Fontes: rótulos aprovados DailyMed/FDA (NIH/NLM), setIDs validados
--         na websearch (2026-08-19)
-- Padrão: 7.3 (drugs) + 7.6 (profiles + pharmacology)
-- Idempotente: ON CONFLICT DO NOTHING / ON CONFLICT (drug_id) DO NOTHING
-- =====================================================================

-- =====================================================================
-- 1. Fármacos novos em public.drugs
-- =====================================================================
INSERT INTO public.drugs (slug, name_pt, name_en, class_pt, class_en, aliases, status, sort_order)
VALUES
  ('empagliflozina', 'Empagliflozina', 'Empagliflozin', 'Inibidor do cotransportador sódio-glicose 2 (SGLT2)', 'Sodium-glucose cotransporter 2 (SGLT2) inhibitor', ARRAY['Jardiance'], 'published', 142),
  ('dapagliflozina', 'Dapagliflozina', 'Dapagliflozin', 'Inibidor do cotransportador sódio-glicose 2 (SGLT2)', 'Sodium-glucose cotransporter 2 (SGLT2) inhibitor', ARRAY['Farxiga', 'Forxiga'], 'published', 143),
  ('canagliflozina', 'Canagliflozina', 'Canagliflozin', 'Inibidor do cotransportador sódio-glicose 2 (SGLT2)', 'Sodium-glucose cotransporter 2 (SGLT2) inhibitor', ARRAY['Invokana'], 'published', 144),
  ('sitagliptina', 'Sitagliptina', 'Sitagliptin', 'Inibidor da dipeptidil peptidase-4 (DPP-4)', 'Dipeptidyl peptidase-4 (DPP-4) inhibitor', ARRAY['Januvia'], 'published', 145),
  ('saxagliptina', 'Saxagliptina', 'Saxagliptin', 'Inibidor da dipeptidil peptidase-4 (DPP-4)', 'Dipeptidyl peptidase-4 (DPP-4) inhibitor', ARRAY['Onglyza'], 'published', 146),
  ('vildagliptina', 'Vildagliptina', 'Vildagliptin', 'Inibidor da dipeptidil peptidase-4 (DPP-4)', 'Dipeptidyl peptidase-4 (DPP-4) inhibitor', ARRAY['Galvus'], 'published', 147),
  ('liraglutida', 'Liraglutida', 'Liraglutide', 'Agonista do recetor do peptídeo semelhante ao glucagon-1 (GLP-1 RA)', 'Glucagon-like peptide-1 receptor agonist (GLP-1 RA)', ARRAY['Victoza', 'Saxenda'], 'published', 148),
  ('dulaglutida', 'Dulaglutida', 'Dulaglutide', 'Agonista do recetor do peptídeo semelhante ao glucagon-1 (GLP-1 RA)', 'Glucagon-like peptide-1 receptor agonist (GLP-1 RA)', ARRAY['Trulicity'], 'published', 149),
  ('acarbose', 'Acarbose', 'Acarbose', 'Inibidor da alfa-glucosidase', 'Alpha-glucosidase inhibitor', ARRAY['Precose', 'Glucobay'], 'published', 150)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 2. Perfis (drug_profiles) — overview_public + overview_pro
-- =====================================================================
INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
   indications_pt, indications_en,
   side_effects_pt, side_effects_en, precautions_pt, precautions_en,
   source_pt, source_en, status)
SELECT d.id, v.overview_public_pt, v.overview_public_en, v.overview_pro_pt, v.overview_pro_en,
  v.indications_pt, v.indications_en,
  v.side_effects_pt, v.side_effects_en,
  v.precautions_pt, v.precautions_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('empagliflozina',
   'A empagliflozina é um inibidor do SGLT2 que reduz a reabsorção renal de glicose, promovendo glicosúria e reduzindo a glicemia. Tem benefícios cardiovasculares e renais comprovados.',
   'Empagliflozin is an SGLT2 inhibitor that reduces renal glucose reabsorption, promoting glycosuria and lowering blood glucose. Has proven cardiovascular and renal benefits.',
   'Inibidor oral seletivo do SGLT2. Reduz HbA1c 0,5-0,8%. Perda de peso 2-3 kg. Reduz pressão arterial. Benefícios cardiovasculares (reduz mortalidade CV) e renais (retarda progressão da DRC).',
   'Oral selective SGLT2 inhibitor. Reduces HbA1c 0.5-0.8%. Weight loss 2-3 kg. Blood pressure reduction. Cardiovascular benefits (reduces CV mortality) and renal benefits (slows CKD progression).',
   'Diabetes mellitus tipo 2\nInsuficiência cardíaca (reduz hospitalização por IC)\nDoença renal crónica (retarda progressão)',
   'Type 2 diabetes mellitus\nHeart failure (reduces HF hospitalisation)\nChronic kidney disease (slows progression)',
   'Infeções genitais (candidíase)\nCetoacidose diabética (rara)\nHipotensão\nDesequilíbrio eletrolítico\nFratura (aumento ligeiro)',
   'Genital infections (candidiasis)\nDiabetic ketoacidosis (rare)\nHypotension\nElectrolyte imbalance\nFracture (slight increase)',
   'Não usar em DM1\nRisco de cetoacidose — interromper 3 dias antes de cirurgia\nMonitorizar função renal e eletrólitos\nEvitar em TFG <20 mL/min',
   'Do not use in T1DM\nDKA risk — discontinue 3 days before surgery\nMonitor renal function and electrolytes\nAvoid if eGFR <20 mL/min',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Empagliflozina (Jardiance): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8b6261f6-4bdc-462e-8af1-4064664c62f3',
   'DailyMed/FDA (NIH/NLM) — approved Empagliflozin (Jardiance) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8b6261f6-4bdc-462e-8af1-4064664c62f3'),
  ('dapagliflozina',
   'A dapagliflozina é um inibidor do SGLT2 com indicação para diabetes, insuficiência cardíaca e doença renal crónica. Efeito cardiorenal comprovado.',
   'Dapagliflozin is an SGLT2 inhibitor indicated for diabetes, heart failure, and chronic kidney disease. Proven cardiorenal effect.',
   'Inibidor oral seletivo do SGLT2. Reduz HbA1c 0,5-0,8%. Perda de peso 2-3 kg. Reduz pressão arterial. Benefícios CV e renais (estudos DAPA-HF, DAPA-CKD).',
   'Oral selective SGLT2 inhibitor. Reduces HbA1c 0.5-0.8%. Weight loss 2-3 kg. Blood pressure reduction. CV and renal benefits (DAPA-HF, DAPA-CKD trials).',
   'Diabetes mellitus tipo 2\nInsuficiência cardíaca (com ou sem DM2)\nDoença renal crónica (com ou sem DM2)',
   'Type 2 diabetes mellitus\nHeart failure (with or without T2DM)\nChronic kidney disease (with or without T2DM)',
   'Infeções genitais (candidíase)\nCetoacidose diabética (rara)\nHipotensão\nNecrose fascial perineal (Fournier — muito rara)',
   'Genital infections (candidiasis)\nDiabetic ketoacidosis (rare)\nHypotension\nFournier gangrene (very rare)',
   'Não usar em DM1\nRisco de cetoacidose — interromper antes de cirurgia\nMonitorizar função renal\nEvitar em TFG <20 mL/min',
   'Do not use in T1DM\nDKA risk — discontinue before surgery\nMonitor renal function\nAvoid if eGFR <20 mL/min',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dapagliflozina (Farxiga): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=72ad22ae-efe6-4cd6-a302-98aaee423d69',
   'DailyMed/FDA (NIH/NLM) — approved Dapagliflozin (Farxiga) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=72ad22ae-efe6-4cd6-a302-98aaee423d69'),
  ('canagliflozina',
   'A canagliflozina é um inibidor do SGLT2 para DM2. Risco aumentado de amputação e fratura comparativamente a outros SGLT2.',
   'Canagliflozin is an SGLT2 inhibitor for T2DM. Increased risk of amputation and fracture compared to other SGLT2 inhibitors.',
   'Inibidor oral do SGLT2. Reduz HbA1c 0,5-0,8%. Reduz HBA1c e peso. Risco aumentado de amputação e fratura (CANVAS). Usar com cautela.',
   'Oral SGLT2 inhibitor. Reduces HbA1c 0.5-0.8%. Reduces HbA1c and weight. Increased risk of amputation and fracture (CANVAS). Use with caution.',
   'Diabetes mellitus tipo 2',
   'Type 2 diabetes mellitus',
   'Infeções genitais\nCetoacidose diabética\nAmputação (risco aumentado)\nFratura (risco aumentado)\nHipotensão',
   'Genital infections\nDiabetic ketoacidosis\nAmputation (increased risk)\nFracture (increased risk)\nHypotension',
   'Não usar em DM1\nEvitar em doentes com risco de amputação\nMonitorizar pés regularmente\nEvitar em TFG <30 mL/min',
   'Do not use in T1DM\nAvoid in patients at risk of amputation\nMonitor feet regularly\nAvoid if eGFR <30 mL/min',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Canagliflozina (Invokana): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9057d3b-b104-4f09-8a61-c61ef9d4a3f3',
   'DailyMed/FDA (NIH/NLM) — approved Canagliflozin (Invokana) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9057d3b-b104-4f09-8a61-c61ef9d4a3f3'),
  ('sitagliptina',
   'A sitagliptina é um inibidor da DPP-4 que aumenta as incretinas endógenas (GLP-1 e GIP), estimulando a secreção de insulina dependente de glicose.',
   'Sitagliptin is a DPP-4 inhibitor that increases endogenous incretins (GLP-1 and GIP), stimulating glucose-dependent insulin secretion.',
   'Inibidor oral da DPP-4. Reduz HbA1c 0,5-0,7%. Neutro em peso. Baixo risco de hipoglicemia (seleção glicose-dependente). Bem tolerado.',
   'Oral DPP-4 inhibitor. Reduces HbA1c 0.5-0.7%. Weight neutral. Low hypoglycaemia risk (glucose-dependent selectivity). Well tolerated.',
   'Diabetes mellitus tipo 2 (monoterapia ou em combinação)',
   'Type 2 diabetes mellitus (monotherapy or combination)',
   'Cefaleia\nInfeções do tracto respiratório superior\nNasofaringite\nDor de cabeça\nRaramente: pancreatite, artrite reativa',
   'Headache\nUpper respiratory tract infections\nNasopharyngitis\nHeadache\nRarely: pancreatitis, reactive arthritis',
   'Ajustar dose em insuficiência renal (25 mg se TFG <30)\nRisco de pancreatite — suspender se suspeitada\nNão usar em DM1',
   'Adjust dose in renal impairment (25 mg if eGFR <30)\nPancreatitis risk — discontinue if suspected\nDo not use in T1DM',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Sitagliptina (Januvia): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f85a48d0-0407-4c50-b488-8dbb32db7e3d',
   'DailyMed/FDA (NIH/NLM) — approved Sitagliptin (Januvia) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f85a48d0-0407-4c50-b488-8dbb32db7e3d'),
  ('saxagliptina',
   'A saxagliptina é um inibidor da DPP-4 com meia-vida mais curta que a sitagliptina. Possível aumento do risco de insuficiência cardíaca.',
   'Saxagliptin is a DPP-4 inhibitor with shorter half-life than sitagliptin. Possible increased risk of heart failure.',
   'Inibidor oral da DPP-4. Reduz HbA1c 0,5-0,7%. Neutro em peso. Meia-vida 2,5h (mais curta). Risco de IC (estudo SAVOR-TIMI 53).',
   'Oral DPP-4 inhibitor. Reduces HbA1c 0.5-0.7%. Weight neutral. Half-life 2.5h (shorter). HF risk (SAVOR-TIMI 53 trial).',
   'Diabetes mellitus tipo 2',
   'Type 2 diabetes mellitus',
   'Cefaleia\nInfeções do tracto respiratório superior\nPancreatite\nInsuficiência cardíaca (risco aumentado)',
   'Headache\nUpper respiratory tract infections\nPancreatitis\nHeart failure (increased risk)',
   'Ajustar dose em insuficiência renal\nMonitorizar sinais de IC\nNão usar em DM1',
   'Adjust dose in renal impairment\nMonitor for HF signs\nDo not use in T1DM',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Saxagliptina (Onglyza): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c5116390-e0fe-4969-94cb-e9de5165fbab',
   'DailyMed/FDA (NIH/NLM) — approved Saxagliptin (Onglyza) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c5116390-e0fe-4969-94cb-e9de5165fbab'),
  ('vildagliptina',
   'A vildagliptina é um inibidor da DPP-4 administrado duas vezes ao dia. Neutra em peso e com baixo risco de hipoglicemia.',
   'Vildagliptin is a DPP-4 inhibitor administered twice daily. Weight neutral with low hypoglycaemia risk.',
   'Inibidor oral da DPP-4. Reduz HbA1c 0,5-0,7%. Neutro em peso. Dose 50-100 mg/dia (2x/dia). Bem tolerado.',
   'Oral DPP-4 inhibitor. Reduces HbA1c 0.5-0.7%. Weight neutral. Dose 50-100 mg/day (twice daily). Well tolerated.',
   'Diabetes mellitus tipo 2',
   'Type 2 diabetes mellitus',
   'Cefaleia\nNáusea\nTontura\nHipoglicemia (rara, em combinação com sulfoniluréia)',
   'Headache\nNausea\nDizziness\nHypoglycaemia (rare, with sulfonylurea)',
   'Não usar em insuficiência hepática\nAjustar dose em insuficiência renal\nNão usar em DM1',
   'Do not use in hepatic impairment\nAdjust dose in renal impairment\nDo not use in T1DM',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Vildagliptina (Galvus): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd54d30b-9390-4e5a-bf62-fbf18b91e4cd',
   'DailyMed/FDA (NIH/NLM) — approved Vildagliptin (Galvus) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd54d30b-9390-4e5a-bf62-fbf18b91e4cd'),
  ('liraglutida',
   'A liraglutida é um agonista do GLP-1 de ação prolongada (injeção subcutânea diária). Reduz HbA1c, peso e risco cardiovascular.',
   'Liraglutide is a long-acting GLP-1 receptor agonist (once-daily subcutaneous injection). Reduces HbA1c, weight, and cardiovascular risk.',
   'Agonista do GLP-1 injectável. Reduz HbA1c 1,0-1,5%. Perda de peso significativa (5-8%). Benefícios CV (estudo LEADER). Injeção SC diária.',
   'Injectable GLP-1 agonist. Reduces HbA1c 1.0-1.5%. Significant weight loss (5-8%). CV benefits (LEADER trial). Once-daily SC injection.',
   'Diabetes mellitus tipo 2 (monoterapia ou em combinação)\nObesidade (dose 3,0 mg — Saxenda)',
   'Type 2 diabetes mellitus (monotherapy or combination)\nObesity (3.0 mg dose — Saxenda)',
   'Náuseas (comum, transitório)\nVómitos\nDiarreia\nDor abdominal\nPancreatite (rara)\nTumores tiroidianos C (em roedores)',
   'Nausea (common, transient)\nVomiting\nDiarrhoea\nAbdominal pain\nPancreatitis (rare)\nThyroid C-cell tumours (in rodents)',
   'CONTRAINDICADO em Neoplasia Medular da Tiroidide (MEN2)\nRisco de pancreatite\nEvitar em insuficiência renal severa\nAjustar dose em insuficiência hepática',
   'CONTRAINDICATED in Medullary Thyroid Carcinoma (MEN2)\nPancreatitis risk\nAvoid in severe renal impairment\nAdjust dose in hepatic impairment',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Liraglutida (Victoza): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=29f4637b-e204-425b-b89c-3b1a315d6588',
   'DailyMed/FDA (NIH/NLM) — approved Liraglutide (Victoza) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=29f4637b-e204-425b-b89c-3b1a315d6588'),
  ('dulaglutida',
   'A dulaglutida é um agonista do GLP-1 de ação prolongada (injeção subcutânea semanal). Reduz HbA1c, peso e risco cardiovascular.',
   'Dulaglutide is a long-acting GLP-1 receptor agonist (once-weekly subcutaneous injection). Reduces HbA1c, weight, and cardiovascular risk.',
   'Agonista do GLP-1 injectável semanal. Reduz HbA1c 1,0-1,5%. Perda de peso. Benefícios CV (REWIND). Mais prático que liraglutida (1x/semana).',
   'Injectable weekly GLP-1 agonist. Reduces HbA1c 1.0-1.5%. Weight loss. CV benefits (REWIND). More convenient than liraglutide (once/week).',
   'Diabetes mellitus tipo 2',
   'Type 2 diabetes mellitus',
   'Náuseas\nDiarreia\nVómitos\nDor abdominal\nPancreatite (rara)\nReações no local da injeção',
   'Nausea\nDiarrhoea\nVomiting\nAbdominal pain\nPancreatitis (rare)\nInjection site reactions',
   'CONTRAINDICADO em Neoplasia Medular da Tiroidide (MEN2)\nRisco de pancreatite\nAjustar dose em insuficiência renal',
   'CONTRAINDICATED in Medullary Thyroid Carcinoma (MEN2)\nPancreatitis risk\nAdjust dose in renal impairment',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dulaglutida (Trulicity): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=463050bd-2b1c-40f5-b3c3-0a04bb433309',
   'DailyMed/FDA (NIH/NLM) — approved Dulaglutide (Trulicity) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=463050bd-2b1c-40f5-b3c3-0a04bb433309'),
  ('acarbose',
   'A acarbose é um inibidor da alfa-glucosidase que retarda a digestão de hidratos de carbono no intestino delgado, reduzindo os picos pós-prandiais de glicose.',
   'Acarbose is an alpha-glucosidase inhibitor that delays carbohydrate digestion in the small intestine, reducing postprandial glucose spikes.',
   'Inibidor oral da alfa-glucosidase. Reduz HbA1c 0,5-0,8%. Reduz picos pós-prandiais. Efeitos gastrointestinais comuns (gás, flatulência). Tomar com a primeira mordida da refeição.',
   'Oral alpha-glucosidase inhibitor. Reduces HbA1c 0.5-0.8%. Reduces postprandial spikes. Common gastrointestinal effects (gas, flatulence). Take with first bite of meal.',
   'Diabetes mellitus tipo 2 (adjunto à dieta)',
   'Type 2 diabetes mellitus (diet adjunct)',
   'Flatulência\nDor abdominal\nDiarreia\nHiperamilasemia (assintomática)',
   'Flatulence\nAbdominal pain\nDiarrhoea\nHyperamylasaemia (asymptomatic)',
   'Não usar em insuficiência renal ou hepática\nEfeitos GI dose-dependentes\nTomar com a primeira mordida da refeição',
   'Do not use in renal or hepatic impairment\nGI effects dose-dependent\nTake with first bite of meal',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acarbose (Precose): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c85bc02a-bf18-4690-84b8-2c256bce5f9f',
   'DailyMed/FDA (NIH/NLM) — approved Acarbose (Precose) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c85bc02a-bf18-4690-84b8-2c256bce5f9f')
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
      indications_pt, indications_en,
      side_effects_pt, side_effects_en, precautions_pt, precautions_en,
      source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- 3. Farmacologia (drug_pharmacology)
-- =====================================================================
INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en,
   mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en,
   absorption_pt, absorption_en,
   half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id,
  v.pharmacodynamics_pt, v.pharmacodynamics_en,
  v.mechanism_pt, v.mechanism_en,
  v.metabolism_pt, v.metabolism_en,
  v.absorption_pt, v.absorption_en,
  v.half_life_pt, v.half_life_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('empagliflozina',
   'Inibe seletivamente o SGLT2 no túbulo contorcido proximal, bloqueando 80-90% da reabsorção de glicose renal.',
   'Selectively inhibits SGLT2 in the proximal convoluted tubule, blocking 80-90% of renal glucose reabsorption.',
   'Bloqueia o SGLT2, impedindo o transporte de glicose de volta para a circulação. A glicose é excretada na urina (glicosúria ~70 g/dia).',
   'Blocks SGLT2, preventing glucose transport back into circulation. Glucose is excreted in urine (~70 g/day glycosuria).',
   'Metabolizado por UGT1A3, UGT1A8, UGT1A9 ao glucurónido inativo. Não interfere com CYP. Baixo potencial de interações.',
   'Metabolised by UGT1A3, UGT1A8, UGT1A9 to inactive glucuronide. Does not interfere with CYP. Low interaction potential.',
   'Biodisponibilidade oral: 78%. Alimentos não afetam significativamente a absorção. Tmax: 1,5 horas.',
   'Oral bioavailability: 78%. Food does not significantly affect absorption. Tmax: 1.5 hours.',
   '12,4 horas. Eliminação: 54% fezes, 36% urina (metabolitos).',
   '12.4 hours. Elimination: 54% faeces, 36% urine (metabolites).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Empagliflozina (Jardiance): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8b6261f6-4bdc-462e-8af1-4064664c62f3',
   'DailyMed/FDA (NIH/NLM) — approved Empagliflozin (Jardiance) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8b6261f6-4bdc-462e-8af1-4064664c62f3'),
  ('dapagliflozina',
   'Inibe seletivamente o SGLT2, bloqueando a reabsorção renal de glicose e promovendo glicosúria.',
   'Selectively inhibits SGLT2, blocking renal glucose reabsorption and promoting glycosuria.',
   'Bloqueia o SGLT2 no túbulo proximal, impedindo o transporte de glicose. A glicose excretada arrasta sódio e água (diurético osmótico).',
   'Blocks SGLT2 in the proximal tubule, preventing glucose transport. Excreted glucose drags sodium and water (osmotic diuretic).',
   'Metabolizado por UGT1A6, UGT1A9 ao glucurónido inativo (metabolito M2). Metabolito M3 (4-hidroxil) com atividade reduzida. Não interfere com CYP.',
   'Metabolised by UGT1A6, UGT1A9 to inactive glucuronide (M2 metabolite). M3 metabolite (4-hydroxyl) with reduced activity. Does not interfere with CYP.',
   'Biodisponibilidade oral: 78%. Alimentos não afetam a absorção. Tmax: 1-2 horas.',
   'Oral bioavailability: 78%. Food does not affect absorption. Tmax: 1-2 hours.',
   '12,9 horas. Eliminação: ~75% urina (metabolitos), ~20% fezes.',
   '12.9 hours. Elimination: ~75% urine (metabolites), ~20% faeces.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dapagliflozina (Farxiga): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=72ad22ae-efe6-4cd6-a302-98aaee423d69',
   'DailyMed/FDA (NIH/NLM) — approved Dapagliflozin (Farxiga) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=72ad22ae-efe6-4cd6-a302-98aaee423d69'),
  ('canagliflozina',
   'Inibe o SGLT2 (seletivo) e, em menor grau, o SGLT1 (não seletivo), bloqueando a reabsorção renal de glicose.',
   'Inhibits SGLT2 (selective) and, to a lesser extent, SGLT1 (non-selective), blocking renal glucose reabsorption.',
   'Bloqueia o SGLT2 e SGLT1. A inibição do SGLT1 no intestino pode contribuir para efeitos gastrointestinais.',
   'Blocks SGLT2 and SGLT1. SGLT1 inhibition in the intestine may contribute to gastrointestinal effects.',
   'Metabolizado por UGT1A9 e UGT2B4 ao glucurónido. Fraca inibição do UGT1A9. Metabolismo CYP mínimo.',
   'Metabolised by UGT1A9 and UGT2B4 to glucuronide. Weak UGT1A9 inhibition. Minimal CYP metabolism.',
   'Biodisponibilidade oral: ~65%. Alimentos não afetam significativamente a absorção. Tmax: 1-2 horas.',
   'Oral bioavailability: ~65%. Food does not significantly affect absorption. Tmax: 1-2 hours.',
   '10-13 horas. Eliminação: ~60% urina (metabolitos), ~33% fezes.',
   '10-13 hours. Elimination: ~60% urine (metabolites), ~33% faeces.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Canagliflozina (Invokana): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9057d3b-b104-4f09-8a61-c61ef9d4a3f3',
   'DailyMed/FDA (NIH/NLM) — approved Canagliflozin (Invokana) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9057d3b-b104-4f09-8a61-c61ef9d4a3f3'),
  ('sitagliptina',
   'Inibe a DPP-4, aumentando os níveis de GLP-1 e GIP. Estimula a secreção de insulina dependente de glicose e suprime a secreção de glucagon.',
   'Inhibits DPP-4, increasing GLP-1 and GIP levels. Stimulates glucose-dependent insulin secretion and suppresses glucagon secretion.',
   'Bloqueia a DPP-4, impedindo a degradação das incretinas GLP-1 e GIP. Os níveis elevados de incretinas estimulam a secreção de insulina apenas quando a glicemia está elevada.',
   'Blocks DPP-4, preventing degradation of incretins GLP-1 and GIP. Elevated incretin levels stimulate insulin secretion only when glucose is elevated.',
   'Metabolizado minimamente (~16% via CYP3A4 com contribuição do CYP2C8). ~79% excretado inalterado na urina. Baixo potencial de interações.',
   'Minimally metabolised (~16% via CYP3A4 with CYP2C8 contribution). ~79% excreted unchanged in urine. Low interaction potential.',
   'Biodisponibilidade oral: 87%. Alimentos não afetam a absorção. Tmax: 1-4 horas.',
   'Oral bioavailability: 87%. Food does not affect absorption. Tmax: 1-4 hours.',
   '~12,4 horas. Eliminação: ~79% urina (inalterado), ~14% fezes.',
   '~12.4 hours. Elimination: ~79% urine (unchanged), ~14% faeces.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Sitagliptina (Januvia): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f85a48d0-0407-4c50-b488-8dbb32db7e3d',
   'DailyMed/FDA (NIH/NLM) — approved Sitagliptin (Januvia) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f85a48d0-0407-4c50-b488-8dbb32db7e3d'),
  ('saxagliptina',
   'Inibe a DPP-4, aumentando as incretinas. Metabolito ativo (5-hidrox saxagliptina) tem meia-vida mais longa.',
   'Inhibits DPP-4, increasing incretins. Active metabolite (5-hydroxy saxagliptin) has longer half-life.',
   'Bloqueia a DPP-4, aumentando GLP-1 e GIP. O metabolito ativo 5-hidrox.saxagliptina contribui para ~50% da atividade.',
   'Blocks DPP-4, increasing GLP-1 and GIP. Active metabolite 5-hydroxy saxagliptin contributes ~50% of activity.',
   'Metabolizado pelo CYP3A4 (e em menor grau CYP2D6) ao metabolito ativo 5-hidrox.saxagliptina. Inibido por ketoconazol (dose máxima 2,5 mg).',
   'Metabolised by CYP3A4 (and to a lesser extent CYP2D6) to active metabolite 5-hydroxy saxagliptin. Inhibited by ketoconazole (max dose 2.5 mg).',
   'Biodisponibilidade oral: 75%. Alimentos não afetam significativamente a absorção. Tmax: 2 horas.',
   'Oral bioavailability: 75%. Food does not significantly affect absorption. Tmax: 2 hours.',
   '2,5 horas (saxagliptina); 3,1 horas (5-hidrox). Eliminação: ~60% urina, ~28% fezes.',
   '2.5 hours (saxagliptin); 3.1 hours (5-hydroxy). Elimination: ~60% urine, ~28% faeces.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Saxagliptina (Onglyza): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c5116390-e0fe-4969-94cb-e9de5165fbab',
   'DailyMed/FDA (NIH/NLM) — approved Saxagliptin (Onglyza) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c5116390-e0fe-4969-94cb-e9de5165fbab'),
  ('vildagliptina',
   'Inibe a DPP-4, aumentando as incretinas. Atividade reversível (diferente de sitagliptina).',
   'Inhibits DPP-4, increasing incretins. Reversible activity (unlike sitagliptin).',
   'Bloqueia reversivelmente a DPP-4, aumentando GLP-1 e GIP. A ligação reversível permite atividade residual mesmo com níveis baixos do fármaco.',
   'Reversibly blocks DPP-4, increasing GLP-1 and GIP. Reversible binding allows residual activity even at low drug levels.',
   'Metabolizado hidroliticamente pelo peptídeo presente em eritrócitos (metabolito Ba41-795L inativo). Não interfere com CYP.',
   'Hydrolytically metabolised by peptidase in erythrocytes (inactive Ba41-795L metabolite). Does not interfere with CYP.',
   'Biodisponibilidade oral: 85%. Alimentos não afetam significativamente a absorção. Tmax: 1-2 horas.',
   'Oral bioavailability: 85%. Food does not significantly affect absorption. Tmax: 1-2 hours.',
   '~2 horas (vildagliptina); ~3 horas (Ba41-795L). Eliminação: ~70% urina (metabolitos).',
   '~2 hours (vildagliptin); ~3 hours (Ba41-795L). Elimination: ~70% urine (metabolites).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Vildagliptina (Galvus): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd54d30b-9390-4e5a-bf62-fbf18b91e4cd',
   'DailyMed/FDA (NIH/NLM) — approved Vildagliptin (Galvus) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dd54d30b-9390-4e5a-bf62-fbf18b91e4cd'),
  ('liraglutida',
   'Agonista do recetor GLP-1 de ação prolongada. Análogo do GLP-1 com 97% de homologia. Estimula secreção de insulina dependente de glicose.',
   'Long-acting GLP-1 receptor agonist. GLP-1 analogue with 97% homology. Stimulates glucose-dependent insulin secretion.',
   'Liga-se ao recetor GLP-1, estimulando a secreção de insulina dependente de glicose, suprimindo a secreção de glucagon, atrasando o esvaziamento gástrico e promovendo saciedade.',
   'Binds to the GLP-1 receptor, stimulating glucose-dependent insulin secretion, suppressing glucagon secretion, delaying gastric emptying, and promoting satiety.',
   'Metabolizado por protéase e clivagem enzimática em metabolitos aminoácidos e ácido graxo. Não interfere com CYP.',
   'Metabolised by protease and enzymatic cleavage to amino acid and fatty acid metabolites. Does not interfere with CYP.',
   'Biodisponibilidade oral: <1% (deve ser injectado). Absorção SC: ~55%. Tmax: 8-12 horas.',
   'Oral bioavailability: <1% (must be injected). SC absorption: ~55%. Tmax: 8-12 hours.',
   '~13 horas. Eliminação: ~6% urina (inalterado), ~70% fezes (metabolitos).',
   '~13 hours. Elimination: ~6% urine (unchanged), ~70% faeces (metabolites).',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Liraglutida (Victoza): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=29f4637b-e204-425b-b89c-3b1a315d6588',
   'DailyMed/FDA (NIH/NLM) — approved Liraglutide (Victoza) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=29f4637b-e204-425b-b89c-3b1a315d6588'),
  ('dulaglutida',
   'Agonista do recetor GLP-1 de ação muito prolongada (semanal). Molécula quimicamente ligada ao Fc de IgG4.',
   'Very long-acting (weekly) GLP-1 receptor agonist. Molecule chemically linked to IgG4 Fc.',
   'Liga-se ao recetor GLP-1, estimulando a secreção de insulina dependente de glicose e suprimindo a secreção de glucagon. A ligação ao Fc de IgG4 prolonga a meia-vida.',
   'Binds to the GLP-1 receptor, stimulating glucose-dependent insulin secretion and suppressing glucagon secretion. IgG4 Fc binding prolongs half-life.',
   'Metabolizado por protéase em aminoácidos e ácido graxo. Não interfere com CYP.',
   'Metabolised by protease to amino acids and fatty acid. Does not interfere with CYP.',
   'Biodisponibilidade oral: <1% (deve ser injectado). Absorção SC: ~65%. Tmax: 24-72 horas.',
   'Oral bioavailability: <1% (must be injected). SC absorption: ~65%. Tmax: 24-72 hours.',
   '~4-5 dias (permite dose semanal). Eliminação: ~60% urina (metabolitos), ~30% fezes.',
   '~4-5 days (allows weekly dosing). Elimination: ~60% urine (metabolites), ~30% faeces.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Dulaglutida (Trulicity): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=463050bd-2b1c-40f5-b3c3-0a04bb433309',
   'DailyMed/FDA (NIH/NLM) — approved Dulaglutide (Trulicity) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=463050bd-2b1c-40f5-b3c3-0a04bb433309'),
  ('acarbose',
   'Inibe competitivamente a alfa-glucosidase no bordo em escova do intestino delgado, retardando a digestão de hidratos de carbono complexos.',
   'Competitively inhibits alpha-glucosidase at the brush border of the small intestine, delaying digestion of complex carbohydrates.',
   'Liga-se competitivamente à alfa-glucosidase, impedindo a hidrólise de dissacarídeos e oligossacarídeos em monossacarídeos absorvíveis.',
   'Competitively binds to alpha-glucosidase, preventing hydrolysis of disaccharides and oligosaccharides into absorbable monosaccharides.',
   'Metabolizado predominantemente no tracto gastrointestinal (apenas <2% absorvido). Os metabolitos são excretados renalmente.',
   'Metabolised predominantly in the gastrointestinal tract (only <2% absorbed). Metabolites are renally excretados.',
   'Biodisponibilidade oral: <2%. Tmax: ~1 hora (para o fármaco inalterado). Efeito local no intestino.',
   'Oral bioavailability: <2%. Tmax: ~1 hour (for unchanged drug). Local effect in intestine.',
   '~2 horas (para o fármaco inalterado). A eliminação é maioritariamente gastrointestinal.',
   '~2 hours (for unchanged drug). Elimination is predominantly gastrointestinal.',
   'DailyMed/FDA (NIH/NLM) — rótulo aprovado Acarbose (Precose): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c85bc02a-bf18-4690-84b8-2c256bce5f9f',
   'DailyMed/FDA (NIH/NLM) — approved Acarbose (Precose) label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c85bc02a-bf18-4690-84b8-2c256bce5f9f')
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en,
       mechanism_pt, mechanism_en,
       metabolism_pt, metabolism_en,
       absorption_pt, absorption_en,
       half_life_pt, half_life_en,
       source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
