-- =====================================================================
-- 213 — Expansão Antipsicóticos/Antidepressivos: fármacos + perfis + farmacologia
--
-- 15 fármacos novos com UUIDs fixos para ordem canónica previsível
-- Fontes: DailyMed/FDA, EMC-UK, Prontuário Terapêutico
-- =====================================================================

-- =====================================================================
-- 1. Fármacos novos (drugs) — com UUID fixo
-- =====================================================================
INSERT INTO public.drugs
  (id, slug, name_pt, name_en, class_pt, class_en, aliases, status)
VALUES
  ('a0000000-0000-4000-8000-000000000010', 'risperidona', 'Risperidona', 'Risperidone', 'Antipsicótico atípico', 'Atypical antipsychotic', '{"risperidone","risperdal"}', 'published'),
  ('a0000000-0000-4000-8000-000000000011', 'olanzapina', 'Olanzapina', 'Olanzapine', 'Antipsicótico atípico', 'Atypical antipsychotic', '{"olanzapine","zyprexa"}', 'published'),
  ('a0000000-0000-4000-8000-000000000012', 'quetiapina', 'Quetiapina', 'Quetiapine', 'Antipsicótico atípico', 'Atypical antipsychotic', '{"quetiapine","seroquel"}', 'published'),
  ('a0000000-0000-4000-8000-000000000013', 'aripiprazol', 'Aripiprazol', 'Aripiprazole', 'Antipsicótico atípico', 'Atypical antipsychotic', '{"aripiprazole","abilify"}', 'published'),
  ('a0000000-0000-4000-8000-000000000014', 'paroxetina', 'Paroxetina', 'Paroxetine', 'ISRS', 'SSRI', '{"paroxetine","paxil","seroxat"}', 'published'),
  ('a0000000-0000-4000-8000-000000000015', 'citalopram', 'Citalopram', 'Citalopram', 'ISRS', 'SSRI', '{"citalopram","celexa"}', 'published'),
  ('a0000000-0000-4000-8000-000000000016', 'escitalopram', 'Escitalopram', 'Escitalopram', 'ISRS', 'SSRI', '{"escitalopram","lexapro","cipralex"}', 'published'),
  ('a0000000-0000-4000-8000-000000000017', 'amitriptilina', 'Amitriptilina', 'Amitriptyline', 'Antidepressivo tricíclico', 'Tricyclic antidepressant', '{"amitriptyline","laroxyl","tryptizol"}', 'published'),
  ('a0000000-0000-4000-8000-000000000018', 'venlafaxina', 'Venlafaxina', 'Venlafaxine', 'IRSN', 'SNRI', '{"venlafaxine","effexor"}', 'published'),
  ('a0000000-0000-4000-8000-000000000019', 'duloxetina', 'Duloxetina', 'Duloxetine', 'IRSN', 'SNRI', '{"duloxetine","cymbalta"}', 'published'),
  ('a0000000-0000-4000-8000-00000000001a', 'mirtazapina', 'Mirtazapina', 'Mirtazapine', 'NaSSA', 'NaSSA', '{"mirtazapine","remeron"}', 'published'),
  ('a0000000-0000-4000-8000-00000000001b', 'diazepam', 'Diazepam', 'Diazepam', 'Benzodiazepina', 'Benzodiazepine', '{"diazepam","valium"}', 'published'),
  ('a0000000-0000-4000-8000-00000000001c', 'lorazepam', 'Lorazepam', 'Lorazepam', 'Benzodiazepina', 'Benzodiazepine', '{"lorazepam","ativan"}', 'published'),
  ('a0000000-0000-4000-8000-00000000001d', 'clonazepam', 'Clonazepam', 'Clonazepam', 'Benzodiazepina', 'Benzodiazepine', '{"clonazepam","rivotril"}', 'published'),
  ('a0000000-0000-4000-8000-00000000001e', 'zolpidem', 'Zolpidem', 'Zolpidem', 'Hipnótico', 'Hypnotic', '{"zolpidem","stilnox","ambien"}', 'published')
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 2. Perfis (drug_profiles) — 8 colunas + 'published'
-- =====================================================================
INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en,
   overview_pro_pt, overview_pro_en,
   source_pt, source_en, status)
SELECT d.id, v.overview_public_pt, v.overview_public_en,
  v.overview_pro_pt, v.overview_pro_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('risperidona',
   'A risperidona é um medicamento antipsicótico usado para tratar esquizofrenia, perturbações bipolares e irritação associada a autismo.',
   'Risperidone is an antipsychotic medication used to treat schizophrenia, bipolar disorder, and irritability associated with autism.',
   'Antipsicótico atípico com actividade antagonista D2 e 5-HT2A. Meia-vida: 3-6 h (risperidona), 17-24 h (9-hidroxirisperidona). Dose: 1-6 mg/dia.',
   'Atypical antipsychotic with D2 and 5-HT2A antagonist activity. Half-life: 3-6 h (risperidone), 17-24 h (9-hydroxyrisperidone). Dose: 1-6 mg/day.',
   'DailyMed/FDA — rótulo aprovado Risperidona: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58b7504f-c4a3-ef1b-e063-6394a90ac0f3',
   'DailyMed/FDA — approved Risperidone label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58b7504f-c4a3-ef1b-e063-6394a90ac0f3'
  ),
  ('olanzapina',
   'A olanzapina é um antipsicótico atípico usado para esquizofrenia, perturbação bipolar e depressão resistente (em combinação com fluoxetina).',
   'Olanzapine is an atypical antipsychotic used for schizophrenia, bipolar disorder, and treatment-resistant depression (combined with fluoxetine).',
   'Antipsicótico atípico com perfis multi-receptor (D2, 5-HT2A, H1, M1, α1). Meia-vida: 21-54 h. Pode causar ganho de peso e síndrome metabólica.',
   'Atypical antipsychotic with multi-receptor profile (D2, 5-HT2A, H1, M1, α1). Half-life: 21-54 h. May cause weight gain and metabolic syndrome.',
   'DailyMed/FDA — rótulo aprovado Olanzapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=709d79a1-2742-4629-af43-161be166833a',
   'DailyMed/FDA — approved Olanzapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=709d79a1-2742-4629-af43-161be166833a'
  ),
  ('quetiapina',
   'A quetiapina é um antipsicótico atípico usado para esquizofrenia, perturbação bipolar e como adjuncto na depressão maior.',
   'Quetiapine is an atypical antipsychotic used for schizophrenia, bipolar disorder, and as adjunct in major depression.',
   'Antipsicótico atípico com afinidade por D2, 5-HT2A, H1 e α1. Metabolito activo (norquetiapina). Meia-vida: 6-7 h. Dose: 150-800 mg/dia.',
   'Atypical antipsychotic with affinity for D2, 5-HT2A, H1 and α1. Active metabolite (norquetiapine). Half-life: 6-7 h. Dose: 150-800 mg/day.',
   'DailyMed/FDA — rótulo aprovado Quetiapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3112a006-1c61-47f2-84f5-9a7670d09c9b',
   'DailyMed/FDA — approved Quetiapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3112a006-1c61-47f2-84f5-9a7670d09c9b'
  ),
  ('aripiprazol',
   'O aripiprazol é um antipsicótico atípico com actividade parcial de agonismo D2, usado para esquizofrenia, perturbação bipolar e depressão.',
   'Aripiprazole is an atypical antipsychotic with partial D2 agonist activity, used for schizophrenia, bipolar disorder, and depression.',
   'Agonista parcial D2 e 5-HT1A, antagonista 5-HT2A. Perfil único — menor risco de efeitos extrapiramidais e síndrome metabólica. Meia-vida: 75 h.',
   'Partial D2 agonist and 5-HT1A agonist, 5-HT2A antagonist. Unique profile — lower risk of extrapyramidal effects and metabolic syndrome. Half-life: 75 h.',
   'DailyMed/FDA — rótulo aprovado Aripiprazol: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=50214c47-2ea3-b373-e063-6394a90aad23',
   'DailyMed/FDA — approved Aripiprazole label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=50214c47-2ea3-b373-e063-6394a90aad23'
  ),
  ('paroxetina',
   'A paroxetina é um ISRS usado para depressão, perturbação de ansiedade social, TOC e perturbação de pânico.',
   'Paroxetine is an SSRI used for depression, social anxiety disorder, OCD, and panic disorder.',
   'ISRS com maior afinidade por transportador de serotonina. Meia-vida: 21 h. Inibe CYP2D6. Efeito anticolinérjico mais pronunciado que outros ISRS.',
   'SSRI with highest serotonin transporter affinity. Half-life: 21 h. Inhibits CYP2D6. More anticholinergic effect than other SSRIs.',
   'DailyMed/FDA — rótulo aprovado Paroxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7d558598-6905-46da-8f34-668456c68411',
   'DailyMed/FDA — approved Paroxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7d558598-6905-46da-8f34-668456c68411'
  ),
  ('citalopram',
   'O citalopram é um ISRS usado para depressão e perturbações de ansiedade. É o ISRS com menor perfil de interações.',
   'Citalopram is an SSRI used for depression and anxiety disorders. It is the SSRI with the lowest interaction profile.',
   'ISRS selectivo com meia-vida de 35 h. Baixa afinidade por outros transportadores. Dose máxima: 40 mg/dia (20 mg em idosos).',
   'Selective SSRI with half-life of 35 h. Low affinity for other transporters. Maximum dose: 40 mg/day (20 mg in elderly).',
   'DailyMed/FDA — rótulo aprovado Citalopram: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=aa9c1440-354f-43a6-9e70-fd7bafcb03c5',
   'DailyMed/FDA — approved Citalopram label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=aa9c1440-354f-43a6-9e70-fd7bafcb03c5'
  ),
  ('escitalopram',
   'O escitalopram é o ISRS mais selectivo, usado para depressão e perturbação de ansiedade generalizada.',
   'Escitalopram is the most selective SSRI, used for depression and generalised anxiety disorder.',
   'Enantiómetro activo do citalopram. Selectividade superior para o transportador de serotonina. Meia-vida: 27-32 h. Dose: 10-20 mg/dia.',
   'Active enantiomer of citalopram. Superior selectivity for the serotonin transporter. Half-life: 27-32 h. Dose: 10-20 mg/day.',
   'DailyMed/FDA — rótulo aprovado Escitalopram: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2db02476-325f-ee47-a7e5-b5aed56c364c',
   'DailyMed/FDA — approved Escitalopram label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2db02476-325f-ee47-a7e5-b5aed56c364c'
  ),
  ('amitriptilina',
   'A amitriptilina é um antidepressivo tricíclico usado para depressão, dor neuropática, enxaqueca profilática e incontinência urinária.',
   'Amitriptyline is a tricyclic antidepressant used for depression, neuropathic pain, migraine prophylaxis, and urinary incontinence.',
   'TCAC com actividade noradrenérgica e serotoninérgica. Efeito anticolinérjico forte. Meia-vida: 10-50 h. Dose: 25-150 mg/dia.',
   'TCA with noradrenergic and serotonergic activity. Strong anticholinergic effect. Half-life: 10-50 h. Dose: 25-150 mg/day.',
   'DailyMed/FDA — rótulo aprovado Amitriptilina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abf6a3f5-0df9-4b23-995d-63b973ef80c1',
   'DailyMed/FDA — approved Amitriptyline label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abf6a3f5-0df9-4b23-995d-63b973ef80c1'
  ),
  ('venlafaxina',
   'A venlafaxina é um IRSN usado para depressão, perturbação de ansiedade generalizada e dor neuropática.',
   'Venlafaxine is an SNRI used for depression, generalised anxiety disorder, and neuropathic pain.',
   'IRSN que inibe recaptação de serotonina (doses baixas) e noradrenalina (doses altas). Meia-vida: 5-11 h (metabolito activo: 11-13 h).',
   'SNRI that inhibits serotonin (low doses) and noradrenaline (high doses) reuptake. Half-life: 5-11 h (active metabolite: 11-13 h).',
   'DailyMed/FDA — rótulo aprovado Venlafaxina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3e51f786-3691-4ec4-836b-7f2c9a385aa7',
   'DailyMed/FDA — approved Venlafaxine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3e51f786-3691-4ec4-836b-7f2c9a385aa7'
  ),
  ('duloxetina',
   'A duloxetina é um IRSN usado para depressão, perturbação de ansiedade generalizada e dor neuropática diabética.',
   'Duloxetine is an SNRI used for depression, generalised anxiety disorder, and diabetic neuropathic pain.',
   'IRSN com maior afinidade por transportador de serotonina que noradrenalina. Meia-vida: 12 h. Inibe CYP1A2.',
   'SNRI with higher affinity for serotonin transporter than noradrenaline. Half-life: 12 h. Inhibits CYP1A2.',
   'DailyMed/FDA — rótulo aprovado Duloxetina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=461d769c-b787-4bc7-b4a6-7a5f33ae9d45',
   'DailyMed/FDA — approved Duloxetine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=461d769c-b787-4bc7-b4a6-7a5f33ae9d45'
  ),
  ('mirtazapina',
   'A mirtazapina é um NaSSA usado para depressão, especialmente com insónia e perda de apetite.',
   'Mirtazapine is a NaSSA used for depression, especially with insomnia and appetite loss.',
   'Antagonista α2, 5-HT2A, 5-HT2C e H1. Efeito sedativo e apetitivo. Meia-vida: 20-40 h. Dose: 15-45 mg/dia.',
   'α2, 5-HT2A, 5-HT2C and H1 antagonist. Sedative and appetite-stimulating effect. Half-life: 20-40 h. Dose: 15-45 mg/day.',
   'DailyMed/FDA — rótulo aprovado Mirtazapina: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89ae6a33-933f-47aa-a2de-2a71cd3f7d44',
   'DailyMed/FDA — approved Mirtazapine label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=89ae6a33-933f-47aa-a2de-2a71cd3f7d44'
  ),
  ('diazepam',
   'O diazepam é uma benzodiazepina usada para ansiedade, espasmos musculares, convulsões e síndrome de abstinência alcoólica.',
   'Diazepam is a benzodiazepine used for anxiety, muscle spasms, seizures, and alcohol withdrawal syndrome.',
   'Benzodiazepina de meia-vida longa (20-100 h). Agonista GABA-A. Metabolitos activos. Acumulação em idosos.',
   'Long half-life benzodiazepine (20-100 h). GABA-A agonist. Active metabolites. Accumulation in the elderly.',
   'DailyMed/FDA — rótulo aprovado Diazepam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=260e2041-2bb3-482f-850e-b5d47a7bdbe6',
   'DailyMed/FDA — approved Diazepam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=260e2041-2bb3-482f-850e-b5d47a7bdbe6'
  ),
  ('lorazepam',
   'O lorazepam é uma benzodiazepina usada para ansiedade, insónia, crises epilépticas e náuseas/vómitos.',
   'Lorazepam is a benzodiazepine used for anxiety, insomnia, epileptic seizures, and nausea/vomiting.',
   'Benzodiazepina de meia-vida curta (10-20 h). Agonista GABA-A. Sem metabolitos activos. Preferível em insuficiência hepática.',
   'Short half-life benzodiazepine (10-20 h). GABA-A agonist. No active metabolites. Preferred in hepatic impairment.',
   'DailyMed/FDA — rótulo aprovado Lorazepam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6dfbe8be-168c-44e9-acfa-fa838b92d3b7',
   'DailyMed/FDA — approved Lorazepam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6dfbe8be-168c-44e9-acfa-fa838b92d3b7'
  ),
  ('clonazepam',
   'O clonazepam é uma benzodiazepina usada para epilepsia (ausência, mioclónica) e perturbação de pânico.',
   'Clonazepam is a benzodiazepine used for epilepsy (absence, myoclonic) and panic disorder.',
   'Benzodiazepina de meia-vida longa (18-50 h). Agonista GABA-A. Anticonvulsivante de largo espectro.',
   'Long half-life benzodiazepine (18-50 h). GABA-A agonist. Broad-spectrum anticonvulsant.',
   'DailyMed/FDA — rótulo aprovado Clonazepam: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=64bb2cdf-f57d-4a41-a5bf-ee77b6e64d06',
   'DailyMed/FDA — approved Clonazepam label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=64bb2cdf-f57d-4a41-a5bf-ee77b6e64d06'
  ),
  ('zolpidem',
   'O zolpidem é um hipnótico não-benzodiazepínico usado para insónia de curto prazo.',
   'Zolpidem is a non-benzodiazepine hypnotic used for short-term insomnia.',
   'Agonista selectivo do recetor GABA-Aω1. Meia-vida: 2-5 h. Forma de libertação prolongada disponível. Risco de sonambulismo.',
   'Selective GABA-Aω1 receptor agonist. Half-life: 2-5 h. Extended-release formulation available. Risk of sleepwalking.',
   'DailyMed/FDA — rótulo aprovado Zolpidem: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=413b6f65-101e-e2cf-0802-711d080b851b',
   'DailyMed/FDA — approved Zolpidem label: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=413b6f65-101e-e2cf-0802-711d080b851b'
  )
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- 3. Farmacologia (drug_pharmacology) — 13 colunas + 'published'
-- =====================================================================
INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en,
   mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en,
   absorption_pt, absorption_en,
   half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id,
  v.pharmacodynamics_pt, v.pharmacodynamics_en,
  v.mechanism_pt, v.mechanism_en,
  v.metabolismo_pt, v.metabolismo_en,
  v.absorption_pt, v.absorption_en,
  v.half_life_pt, v.half_life_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('risperidona',
   'Antagonista D2 e 5-HT2A. Efeito sobre sintomas positivos e negativos da esquizofrenia.',
   'D2 and 5-HT2A antagonist. Effect on positive and negative symptoms of schizophrenia.',
   'Antagonismo competitivo dos recetores D2 no circuito mesolímbico (efeito antipsicótico) e 5-HT2A no córtex (melhoria dos sintomas negativos).',
   'Competitive antagonism of D2 receptors in the mesolimbic circuit (antipsychotic effect) and 5-HT2A in the cortex (improvement of negative symptoms).',
   'Metabolizado por CYP2D6 a 9-hidroxirisperidona (activo). CYP3A4 contribui secundariamente.',
   'Metabolised by CYP2D6 to 9-hydroxyrisperidone (active). CYP3A4 contributes secondarily.',
   'Absorção oral completa. Biodisponibilidade: 70%. Comida não afecta extensão.',
   'Complete oral absorption. Bioavailability: 70%. Food does not affect extent.',
   '3-6 h (risperidona); 17-24 h (9-hidroxirisperidona).',
   '3-6 h (risperidone); 17-24 h (9-hydroxyrisperidone).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('olanzapina',
   'Antagonista multi-receptor (D2, 5-HT2A, H1, M1, α1). Efeito antipsicótico e sedativo.',
   'Multi-receptor antagonist (D2, 5-HT2A, H1, M1, α1). Antipsychotic and sedative effect.',
   'Antagonismo D2 mesolímbico e cortical. Antagonismo H1 contribui para sedação e ganho de peso. Antagonismo M1 para efeitos anticolinérgicos.',
   'Mesolimbic and cortical D2 antagonism. H1 antagonism contributes to sedation and weight gain. M1 antagonism for anticholinergic effects.',
   'Metabolizado por CYP1A2 (principal) e UGT. Fumadores têm clearance 40% maior.',
   'Metabolised by CYP1A2 (major) and UGT. Smokers have 40% higher clearance.',
   'Absorção oral boa. Biodisponibilidade: 60%. Pico: 5-8 h.',
   'Good oral absorption. Bioavailability: 60%. Peak: 5-8 h.',
   '21-54 h (média: 30 h).',
   '21-54 h (mean: 30 h).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('quetiapina',
   'Antagonista D2, 5-HT2A, H1 e α1. Norquetiapina (metabolito) inibe recaptação de noradrenalina.',
   'D2, 5-HT2A, H1 and α1 antagonist. Norquetiapine (metabolite) inhibits noradrenaline reuptake.',
   'Antagonismo D2 dependente da região cerebral. Alta afinidade H1 (sedação) e α1 (hipotensão ortostática). Norquetiapina contribui para efeito antidepressivo.',
   'Region-dependent D2 antagonism. High H1 affinity (sedation) and α1 (orthostatic hypotension). Norquetiapine contributes to antidepressant effect.',
   'Metabolizado por CYP3A4. Norquetiapina (metabolito activo).',
   'Metabolised by CYP3A4. Norquetiapine (active metabolite).',
   'Absorção oral rápida. Biodisponibilidade: 100%. Comida aumenta absorção.',
   'Rapid oral absorption. Bioavailability: 100%. Food increases absorption.',
   '6-7 h (quetiapina); 12 h (norquetiapina).',
   '6-7 h (quetiapine); 12 h (norquetiapine).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('aripiprazol',
   'Agonista parcial D2 e 5-HT1A, antagonista 5-HT2A. Perfil único — estabilizador dopaminérgico.',
   'Partial D2 agonist and 5-HT1A agonist, 5-HT2A antagonist. Unique profile — dopaminergic stabiliser.',
   'Agonismo parcial D2: em áreas hiperdopaminérgicas (efeito antipsicótico) e hipodopaminérgicas (efeito antidepressivo). Perfil mais benigno que antipsicóticos típicos.',
   'Partial D2 agonism: in hyperdopaminergic areas (antipsychotic effect) and hypodopaminergic areas (antidepressant effect). More benign profile than typical antipsychotics.',
   'Metabolizado por CYP2D6 e CYP3A4. Dehidroaripiprazol (metabolito activo, 30% da actividade).',
   'Metabolised by CYP2D6 and CYP3A4. Dehydroaripiprazole (active metabolite, 30% of activity).',
   'Absorção oral boa. Biodisponibilidade: 87%. Comida não afecta.',
   'Good oral absorption. Bioavailability: 87%. Food does not affect.',
   '75 h (aripiprazol); 94 h (dehidroaripiprazol).',
   '75 h (aripiprazole); 94 h (dehydroaripiprazole).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('paroxetina',
   'ISRS com maior afinidade por SERT. Efeito anticolinérjico mais pronunciado que outros ISRS.',
   'SSRI with highest SERT affinity. More anticholinergic effect than other SSRIs.',
   'Inibição potente da recaptação de serotonina (SERT). Efeito anticolinérjico (boca seca, retenção urinária). Inibe CYP2D6.',
   'Potent serotonin reuptake inhibition (SERT). Anticholinergic effect (dry mouth, urinary retention). Inhibits CYP2D6.',
   'Metabolizado por CYP2D6 (polimórfico). Extensa首過 metabolização.',
   'Metabolised by CYP2D6 (polymorphic). Extensive first-pass metabolism.',
   'Absorção oral. Biodisponibilidade: 50%. Pico: 5-8 h.',
   'Oral absorption. Bioavailability: 50%. Peak: 5-8 h.',
   '21 h.',
   '21 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('citalopram',
   'ISRS mais selectivo. Menor perfil de interações entre ISRS.',
   'Most selective SSRI. Lowest interaction profile among SSRIs.',
   'Inibição selectiva da recaptação de serotonina (SERT). Baixa afinidade por outros transportadores e recetores.',
   'Selective serotonin reuptake inhibition (SERT). Low affinity for other transporters and receptors.',
   'Metabolizado por CYP2C19 e CYP3A4. Menos dependente de CYP2D6 que outros ISRS.',
   'Metabolised by CYP2C19 and CYP3A4. Less CYP2D6 dependent than other SSRIs.',
   'Absorção oral completa. Biodisponibilidade: 80%. Pico: 1-4 h.',
   'Complete oral absorption. Bioavailability: 80%. Peak: 1-4 h.',
   '35 h.',
   '35 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('escitalopram',
   'ISRS mais selectivo (enantiómetro activo do citalopram).',
   'Most selective SSRI (active enantiomer of citalopram).',
   'Inibição extremamente selectiva de SERT. Sem actividade significativa noutros transportadores.',
   'Extremely selective SERT inhibition. No significant activity on other transporters.',
   'Metabolizado por CYP2C19 e CYP3A4. Sem metabolitos activos.',
   'Metabolised by CYP2C19 and CYP3A4. No active metabolites.',
   'Absorção oral completa. Biodisponibilidade: 80%. Pico: 1-4 h.',
   'Complete oral absorption. Bioavailability: 80%. Peak: 1-4 h.',
   '27-32 h.',
   '27-32 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('amitriptilina',
   'TCAC com actividade noradrenérgica e serotoninérgica. Efeito anticolinérjico forte.',
   'TCA with noradrenergic and serotonergic activity. Strong anticholinergic effect.',
   'Inibe recaptação de noradrenalina (NERT) e serotonina (SERT). Efeitos anticolinérgicos (M1), anti-histamínicos (H1) e α1-adrenérgicos.',
   'Inhibits noradrenaline (NERT) and serotonin (SERT) reuptake. Anticholinergic (M1), antihistaminic (H1) and α1-adrenergic effects.',
   'Metabolizado por CYP2D6 e CYP3A4. Nortriptilina (metabolito activo).',
   'Metabolised by CYP2D6 and CYP3A4. Nortriptyline (active metabolite).',
   'Absorção oral. Biodisponibilidade: 30-60%. Pico: 2-8 h.',
   'Oral absorption. Bioavailability: 30-60%. Peak: 2-8 h.',
   '10-50 h (média: 25 h).',
   '10-50 h (mean: 25 h).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('venlafaxina',
   'IRSN: inibe recaptação de serotonina (doses baixas) e noradrenalina (doses altas).',
   'SNRI: inhibits serotonin (low doses) and noradrenaline (high doses) reuptake.',
   'Inibição de SERT (doses ≥75 mg) e NERT (doses ≥150 mg). Sem actividade anticolinérjica, anti-histamínica ou α1.',
   'SERT inhibition (doses ≥75 mg) and NERT inhibition (doses ≥150 mg). No anticholinergic, antihistaminic or α1 activity.',
   'Metabolizado por CYP2D6 a O-desmetilvenlafaxina (activa, metabolito dominante).',
   'Metabolised by CYP2D6 to O-desmethylvenlafaxine (active, dominant metabolite).',
   'Absorção oral completa. Biodisponibilidade: 40-45%.',
   'Complete oral absorption. Bioavailability: 40-45%.',
   '5-11 h (venlafaxina); 11-13 h (O-desmetilvenlafaxina).',
   '5-11 h (venlafaxine); 11-13 h (O-desmethylvenlafaxine).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('duloxetina',
   'IRSN com maior afinidade por SERT que NERT. Efeito em dor neuropática.',
   'SNRI with higher SERT than NERT affinity. Effect in neuropathic pain.',
   'Inibe recaptação de serotonina (SERT) e noradrenalina (NERT). Actividade adicional nos recetores σ1.',
   'Inhibits serotonin (SERT) and noradrenaline (NERT) reuptake. Additional activity at σ1 receptors.',
   'Metabolizado por CYP1A2 (induzido por tabaco) e CYP2D6.',
   'Metabolised by CYP1A2 (induced by smoking) and CYP2D6.',
   'Absorção oral. Biodisponibilidade: 70-80%. Comida retarda absorção.',
   'Oral absorption. Bioavailability: 70-80%. Food delays absorption.',
   '12 h.',
   '12 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('mirtazapina',
   'Antagonista α2, 5-HT2A, 5-HT2C e H1. Efeito sedativo e apetitivo.',
   'α2, 5-HT2A, 5-HT2C and H1 antagonist. Sedative and appetite-stimulating effect.',
   'Antagonismo α2 pré-sináptico → aumento de noradrenalina e serotonina. Antagonismo 5-HT2C → aumento de dopamina e noradrenalina. Antagonismo H1 → sedação.',
   'Presynaptic α2 antagonism → increased noradrenaline and serotonin. 5-HT2C antagonism → increased dopamine and noradrenaline. H1 antagonism → sedation.',
   'Metabolizado por CYP2D6, CYP3A4 e CYP1A2. Sem metabolitos activos significativos.',
   'Metabolised by CYP2D6, CYP3A4 and CYP1A2. No significant active metabolites.',
   'Absorção oral rápida e completa. Biodisponibilidade: 50%.',
   'Rapid and complete oral absorption. Bioavailability: 50%.',
   '20-40 h.',
   '20-40 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('diazepam',
   'Benzodiazepina de meia-vida longa. Agonista GABA-A.',
   'Long half-life benzodiazepine. GABA-A agonist.',
   'Ligação ao sítio benzodiazepínico do recetor GABA-A → potenciação do efeito do GABA → inibição neuronal aumentada.',
   'Binding to the benzodiazepine site of the GABA-A receptor → potentiation of GABA effect → increased neuronal inhibition.',
   'Metabolizado por CYP3A4 e CYP2C19 a desmetildiazepam (activo, meia-vida 100 h), oxazepam e temazepam.',
   'Metabolised by CYP3A4 and CYP2C19 to desmethyldiazepam (active, half-life 100 h), oxazepam and temazepam.',
   'Absorção oral rápida e completa. Biodisponibilidade: 100%.',
   'Rapid and complete oral absorption. Bioavailability: 100%.',
   '20-100 h (com metabolitos activos: até 200 h).',
   '20-100 h (with active metabolites: up to 200 h).',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('lorazepam',
   'Benzodiazepina de meia-vida curta. Agonista GABA-A. Sem metabolitos activos.',
   'Short half-life benzodiazepine. GABA-A agonist. No active metabolites.',
   'Ligação ao sítio benzodiazepínico do recetor GABA-A. Via glucuronidação (UGT2B7) — sem metabolitos activos.',
   'Binding to the benzodiazepine site of the GABA-A receptor. Glucuronidation pathway (UGT2B7) — no active metabolites.',
   'Metabolizado por glucuronidação (UGT2B7). Sem metabolitos activos — preferível em insuficiência hepática.',
   'Metabolised by glucuronidation (UGT2B7). No active metabolites — preferred in hepatic impairment.',
   'Absorção oral completa. Biodisponibilidade: 80-90%.',
   'Complete oral absorption. Bioavailability: 80-90%.',
   '10-20 h.',
   '10-20 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('clonazepam',
   'Benzodiazepina de meia-vida longa. Anticonvulsivante de largo espectro.',
   'Long half-life benzodiazepine. Broad-spectrum anticonvulsant.',
   'Ligação ao sítio benzodiazepínico do GABA-A. Efeito anticonvulsivante mais pronunciado que outras benzodiazepinas.',
   'Binding to the benzodiazepine site of GABA-A. More pronounced anticonvulsant effect than other benzodiazepines.',
   'Metabolizado por CYP3A4. Metabolitos inactivos.',
   'Metabolised by CYP3A4. Inactive metabolites.',
   'Absorção oral completa. Biodisponibilidade: 90-100%.',
   'Complete oral absorption. Bioavailability: 90-100%.',
   '18-50 h.',
   '18-50 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  ),
  ('zolpidem',
   'Agonista selectivo do recetor GABA-Aω1 (hipnótico).',
   'Selective GABA-Aω1 receptor agonist (hypnotic).',
   'Ligação selectiva à subunidade α1 do GABA-A. Sedação sem efeito ansiolítico, anticonvulsivante ou relaxante muscular significativo.',
   'Selective binding to the α1 subunit of GABA-A. Sedation without significant anxiolytic, anticonvulsant or muscle relaxant effect.',
   'Metabolizado por CYP3A4. Metabolitos inactivos.',
   'Metabolised by CYP3A4. Inactive metabolites.',
   'Absorção oral rápida. Biodisponibilidade: 70%. Pico: 0,5-3 h.',
   'Rapid oral absorption. Bioavailability: 70%. Peak: 0.5-3 h.',
   '2-5 h.',
   '2-5 h.',
   'DailyMed/FDA', 'DailyMed/FDA'
  )
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
       metabolismo_pt, metabolismo_en, absorption_pt, absorption_en,
       half_life_pt, half_life_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
