-- =====================================================================
-- 216 — Expansão Antiepilépticos: 9 fármacos novos + perfis + farmacologia
--
-- Fontes: DailyMed/FDA, EMC-UK, Prontuário Terapêutico
-- UUIDs fixos para prever ordem canónica
-- =====================================================================

-- =====================================================================
-- 1. Fármacos (drugs)
-- =====================================================================
INSERT INTO public.drugs
  (id, slug, name_pt, name_en, class_pt, class_en, aliases, status)
VALUES
  ('a0000000-0000-4000-8000-000000000020', 'levetiracetam', 'Levetiracetam', 'Levetiracetam', 'Antiepiléptico', 'Antiepileptic', '{"keppra","briviact"}', 'published'),
  ('a0000000-0000-4000-8000-000000000021', 'gabapentina', 'Gabapentina', 'Gabapentin', 'Antiepiléptico / Analgésico neuropático', 'Antiepileptic / Neuropathic pain', '{"neurontin","gabapentino"}', 'published'),
  ('a0000000-0000-4000-8000-000000000022', 'pregabalina', 'Pregabalina', 'Pregabalin', 'Antiepiléptico / Analgésico neuropático', 'Antiepileptic / Neuropathic pain', '{"lyrica"}', 'published'),
  ('a0000000-0000-4000-8000-000000000023', 'etossuximida', 'Etossuximida', 'Ethosuximide', 'Antiepiléptico (ausências)', 'Antiepileptic (absence seizures)', '{"zarontin"}', 'published'),
  ('a0000000-0000-4000-8000-000000000024', 'topiramato', 'Topiramato', 'Topiramate', 'Antiepiléptico de amplo espectro', 'Broad-spectrum antiepileptic', '{"topamax","topiramat"}', 'published'),
  ('a0000000-0000-4000-8000-000000000025', 'oxcarbazepina', 'Oxcarbazepina', 'Oxcarbazepine', 'Antiepiléptico (derivado carboxamida)', 'Antiepileptic (carboxamide derivative)', '{"trileptal","oxcarbazepino"}', 'published'),
  ('a0000000-0000-4000-8000-000000000026', 'zonisamida', 'Zonisamida', 'Zonisamide', 'Antiepiléptico de amplo espectro', 'Broad-spectrum antiepileptic', '{"zonegran"}', 'published'),
  ('a0000000-0000-4000-8000-000000000027', 'lacosamida', 'Lacosamida', 'Lacosamide', 'Antiepiléptico (enrilosamina)', 'Antiepileptic (enrilosamine)', '{"vimpat"}', 'published'),
  ('a0000000-0000-4000-8000-000000000028', 'primidona', 'Primidona', 'Primidone', 'Antiepiléptico (barbitúrico)', 'Antiepileptic (barbiturate)', '{"mysoline"}', 'published')
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 2. Perfis (drug_profiles) — 8 colunas + 'published'
-- =====================================================================
INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en,
   overview_pro_pt, overview_pro_en,
   source_pt, source_en, status)
SELECT d.id,
  v.overview_public_pt, v.overview_public_en,
  v.overview_pro_pt, v.overview_pro_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('levetiracetam',
   'O levetiracetam é um antiepiléptico usado para tratar epilepsia parcial, generalizada primária e crises mioclónicas. É geralmente bem tolerado e tem poucas interações medicamentosas.',
   'Levetiracetam is an antiepileptic used to treat partial, primary generalised, and myoclonic seizures. It is generally well tolerated with few drug interactions.',
   'Antiepiléptico de 2ª geração. Mecanismo único: liga à proteína SV2A vesicular, modulando a libertação de neurotransmissores. Não é metabolizado por CYP — metabolismo renal mínimo. Meia-vida: 6-8 h. Dose: 500-1500 mg 2x/dia. Efeitos adversos: sonolência, irritabilidade, alterações comportamentais.',
   'Second-generation antiepileptic. Unique mechanism: binds to synaptic vesicular protein SV2A, modulating neurotransmitter release. Not metabolised by CYP — minimal renal metabolism. Half-life: 6-8 h. Dose: 500-1500 mg 2x/day. Adverse effects: somnolence, irritability, behavioural changes.',
   'DailyMed/FDA — Keppra; EMC-UK — Levetiracetam',
   'DailyMed/FDA — Keppra; EMC-UK — Levetiracetam'),
  ('gabapentina',
   'A gabapentina é um antiepiléptico também usado para dor neuropática e pós-herpética. É estruturalmente semelhante ao GABA mas não actua directamente nos recetores GABA.',
   'Gabapentin is an antiepileptic also used for neuropathic and postherpetic pain. It is structurally similar to GABA but does not act directly on GABA receptors.',
   'Antiepiléptico gabapentinoide. Liga à subunidade α2δ dos canais de cálcio voltagem-dependentes, reduzindo a libertação de neurotransmissores excitatórios. Não é metabolizado por CYP. Excreção renal (100%). Meia-vida: 5-7 h. Dose: 300-3600 mg/dia (dividido 3x). Absorção saturável — biodisponibilidade diminui com dose.',
   'Gabapentinoid antiepileptic. Binds to the α2δ subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release. Not metabolised by CYP. Renal excretion (100%). Half-life: 5-7 h. Dose: 300-3600 mg/day (divided 3x). Saturable absorption — bioavailability decreases with dose.',
   'DailyMed/FDA — Neurontin; EMC-UK — Gabapentin',
   'DailyMed/FDA — Neurontin; EMC-UK — Gabapentin'),
  ('pregabalina',
   'A pregabalina é um antiepiléptico e analgésico neuropático. É um gabapentinoide com maior afinidade pela subunidade α2δ que a gabapentina.',
   'Pregabalin is an antiepileptic and neuropathic pain reliever. It is a gabapentinoid with higher affinity for the α2δ subunit than gabapentin.',
   'Gabapentinoide com maior afinidade pela subunidade α2δ dos canais de cálcio. Absorção oral rápida e linear (ao contrário da gabapentina). Meia-vida: 6,3 h. Dose: 75-600 mg/dia (dividido 2-3x). Metabolismo: <2% hepático (CYP3A4 mínimo). Excreção renal (90%). Efeitos adversos: sonolência, tonturas, edema periférico, ganho de peso.',
   'Gabapentinoid with higher affinity for the α2δ subunit of calcium channels. Rapid and oral linear absorption (unlike gabapentin). Half-life: 6.3 h. Dose: 75-600 mg/day (divided 2-3x). Metabolism: <2% hepatic (minimal CYP3A4). Renal excretion (90%). Adverse effects: somnolence, dizziness, peripheral oedema, weight gain.',
   'DailyMed/FDA — Lyrica; EMC-UK — Pregabalin',
   'DailyMed/FDA — Lyrica; EMC-UK — Pregabalin'),
  ('etossuximida',
   'A etossuximida é o fármaco de primeira linha para crises de ausência. É efectiva apenas para este tipo de crise.',
   'Ethosuximide is the first-line drug for absence seizures. It is effective only for this seizure type.',
   'Antiepiléptico de espectro estreito — efectivo apenas para ausências primárias. Mecanismo: inibe correntes de Ca²⁺ tipo T no tálamo. Meia-vida: 40-60 h (crianças: 30 h). Metabolizado por CYP3A4, CYP2E1. Dose: 15-40 mg/kg/dia. Nível terapêutico: 40-100 μg/mL. Efeitos adversos: náusea, dor abdominal, cefaleia, sonolência.',
   'Narrow-spectrum antiepileptic — effective only for primary absences. Mechanism: inhibits T-type Ca²⁺ currents in the thalamus. Half-life: 40-60 h (children: 30 h). Metabolised by CYP3A4, CYP2E1. Dose: 15-40 mg/kg/day. Therapeutic level: 40-100 μg/mL. Adverse effects: nausea, abdominal pain, headache, somnolence.',
   'DailyMed/FDA — Zarontin; EMC-UK — Ethosuximide',
   'DailyMed/FDA — Zarontin; EMC-UK — Ethosuximide'),
  ('topiramato',
   'O topiramato é um antiepiléptico de amplo espectro também usado para enxaqueca profiláctica e perda de peso.',
   'Topiramate is a broad-spectrum antiepileptic also used for migraine prophylaxis and weight loss.',
   'Antiepiléptico de múltiplos mecanismos: bloqueio de canais de Na⁺, potenciação GABA-A, antagonismo do recetor AMPA, inibição da anidrase carbónica. Metabolizado hepaticamente (CYP3A4 parcial) e por glucuronidação (30-50% excretado inalterado renalmente). Meia-vida: 19-25 h. Dose: 25-400 mg/dia. Risco: pedras renais (inibição anidrase carbónica), perda de peso, alteração cognitiva.',
   'Broad-spectrum antiepileptic with multiple mechanisms: Na⁺ channel blockade, GABA-A potentiation, AMPA receptor antagonism, carbonic anhydrase inhibition. Hepatically metabolised (partial CYP3A4) and glucuronidated (30-50% excreted unchanged renally). Half-life: 19-25 h. Dose: 25-400 mg/day. Risk: renal stones (carbonic anhydrase inhibition), weight loss, cognitive impairment.',
   'DailyMed/FDA — Topamax; EMC-UK — Topiramate',
   'DailyMed/FDA — Topamax; EMC-UK — Topiramate'),
  ('oxcarbazepina',
   'A oxcarbazepina é um derivado da carbamazepina com melhor tolerabilidade e menos interações medicamentosas.',
   'Oxcarbazepine is a carbamazepine derivative with better tolerability and fewer drug interactions.',
   'Pro-fármaco — metabolizado a MHD (10-monohidroxiderivado), que é o metabolito activo. Mecanismo: bloqueio de canais de Na⁺ voltagem-dependentes. Induz CYP3A4 e UGT (menos que carbamazepina). Meia-vida do MHD: 9-11 h. Dose: 300-2400 mg/dia. Hiponatremia mais comum que com carbamazepina (2-3%). Vantagem: não produz epóxido activo (menos toxicidade).',
   'Prodrug — metabolised to MHD (10-monohydroxyderivative), the active metabolite. Mechanism: blockade of voltage-gated Na⁺ channels. Induces CYP3A4 and UGT (less than carbamazepine). MHD half-life: 9-11 h. Dose: 300-2400 mg/day. Hyponatraemia more common than with carbamazepine (2-3%). Advantage: does not produce active epoxide (less toxicity).',
   'DailyMed/FDA — Trileptal; EMC-UK — Oxcarbazepine',
   'DailyMed/FDA — Trileptal; EMC-UK — Oxcarbazepine'),
  ('zonisamida',
   'A zonisamida é um antiepiléptico de amplo espectro estruturalmente semelhante às sulfonamidas.',
   'Zonisamide is a broad-spectrum antiepileptic structurally similar to sulphonamides.',
   'Bloqueio de canais de Na⁺ e T-type Ca²⁺. Inibe a anidrase carbónica. Meia-vida: 50-70 h (permite dose 1x/dia). Metabolizado por CYP3A4 e redução não enzimática. Dose: 100-400 mg/dia. Risco: pedras renais, hipertermia em idosos, piora cognitiva. Evitar em磺胺类过敏ia.',
   'Na⁺ and T-type Ca²⁺ channel blockade. Carbonic anhydrase inhibition. Half-life: 50-70 h (allows once-daily dosing). Metabolised by CYP3A4 and non-enzymatic reduction. Dose: 100-400 mg/day. Risk: renal stones, hyperthermia in elderly, cognitive worsening. Avoid in sulphonamide allergy.',
   'DailyMed/FDA — Zonegran; EMC-UK — Zonisamide',
   'DailyMed/FDA — Zonegran; EMC-UK — Zonisamide'),
  ('lacosamida',
   'A lacosamida é um antiepiléptico de nova geração para epilepsia parcial.',
   'Lacosamide is a new-generation antiepileptic for partial epilepsy.',
   'Mecanismo selectivo: potencia a inactivação lenta dos canais de Na⁺ voltagem-dependentes (diferente de fenitoina/carbamazepina que actuam na inactivação rápida). Meia-vida: 13 h. Metabolizado por CYP3A4 e CYP2C19 (mínimo). Dose: 100-400 mg/dia. Biodisponibilidade oral: 100%. Efeitos adversos: náusea, tonturas, cefaleia. Vantagem: poucas interações medicamentosas.',
   'Selective mechanism: potentiates slow inactivation of voltage-gated Na⁺ channels (different from phenytoin/carbamazepine which act on fast inactivation). Half-life: 13 h. Metabolised by CYP3A4 and CYP2C19 (minimal). Dose: 100-400 mg/day. Oral bioavailability: 100%. Adverse effects: nausea, dizziness, headache. Advantage: few drug interactions.',
   'DailyMed/FDA — Vimpat; EMC-UK — Lacosamide',
   'DailyMed/FDA — Vimpat; EMC-UK — Lacosamide'),
  ('primidona',
   'A primidona é um antiepiléptico clássico que é metabolizado a fenobarbital e feniletilmalonamida.',
   'Primidone is a classic antiepileptic metabolised to phenobarbital and phenylethylmalonamide.',
   'Pro-fármaco: metabolizado a fenobarbital (activa, 50-60%) e feniletilmalonamida (activa, 25-30%). Mecanismo: bloqueio de canais Na⁺ e potenciação GABA. Meia-vida: primidona 5-15 h, fenobarbital 80-120 h. Dose: 250-2000 mg/dia. Mesmas interações que fenobarbital. Induz CYP3A4, CYP2C9, CYP2C19, UGT.',
   'Prodrug: metabolised to phenobarbital (active, 50-60%) and phenylethylmalonamide (active, 25-30%). Mechanism: Na⁺ channel blockade and GABA potentiation. Half-life: primidone 5-15 h, phenobarbital 80-120 h. Dose: 250-2000 mg/day. Same interactions as phenobarbital. Induces CYP3A4, CYP2C9, CYP2C19, UGT.',
   'DailyMed/FDA — Mysoline; EMC-UK — Primidone',
   'DailyMed/FDA — Mysoline; EMC-UK — Primidone')
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;

-- =====================================================================
-- 3. Farmacologia (drug_pharmacology) — 13 colunas + 'published'
-- =====================================================================
INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en,
   mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en,
   absorption_pt, absorption_en,
   half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id,
  v.pharmacodynamics_pt, v.pharmacodynamics_en,
  v.mechanism_pt, v.mechanism_en,
  v.metabolism_pt, v.metabolism_en,
  v.absorption_pt, v.absorption_en,
  v.half_life_pt, v.half_life_en,
  v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('levetiracetam',
   'Actividade antiepiléptica via ligação à proteína SV2A vesicular. Efeito sobre a neurotransmissão glutamatérgica e GABAérgica.',
   'Antiepileptic activity via binding to synaptic vesicular protein SV2A. Effect on glutamatergic and GABAergic neurotransmission.',
   'Liga-se selectivamente à SV2A (proteína vesicular sináptica 2A), modulando a libertação de neurotransmissores. Não actua sobre canais iónicos ou recetores convencionais.',
   'Selectively binds to SV2A (synaptic vesicular protein 2A), modulating neurotransmitter release. Does not act on conventional ion channels or receptors.',
   'Não é metabolizado por CYP. Metabolismo hidrolítico renal mínimo (50% inalterado). Metabolitos inactivos.',
   'Not metabolised by CYP. Minimal renal hydrolytic metabolism (50% unchanged). Inactive metabolites.',
   'Absorção oral rápida e completa. Biodisponibilidade: 100%. Comida não afecta absorção. Pico: 1-2 h.',
   'Rapid and complete oral absorption. Bioavailability: 100%. Food does not affect absorption. Peak: 1-2 h.',
   '6-8 h (adultos), 4-6 h (crianças).',
   '6-8 h (adults), 4-6 h (children).',
   'DailyMed/FDA — Keppra; EMC-UK',
   'DailyMed/FDA — Keppra; EMC-UK'),
  ('gabapentina',
   'Actividade antiepiléptica e analgésica neuropática via modulação de canais de cálcio.',
   'Antiepileptic and neuropathic pain activity via calcium channel modulation.',
   'Liga à subunidade α2δ-1 dos canais de cálcio voltagem-dependentes, reduzindo a entrada de Ca²⁺ e a libertação de neurotransmissores excitatórios (glutamato, noradrenalina, substância P).',
   'Binds to the α2δ-1 subunit of voltage-gated calcium channels, reducing Ca²⁺ influx and excitatory neurotransmitter release (glutamate, noradrenaline, substance P).',
   'Não é metabolizado. Excretado 100% inalterado por via renal. Sem interações CYP.',
   'Not metabolised. Excreted 100% unchanged renally. No CYP interactions.',
   'Absorção por transporte saturável. Biodisponibilidade: 60% (300 mg), 35% (1600 mg). Pico: 2-3 h.',
   'Saturable absorption. Bioavailability: 60% (300 mg), 35% (1600 mg). Peak: 2-3 h.',
   '5-7 h (normal), até 13 h em insuficiência renal.',
   '5-7 h (normal), up to 13 h in renal impairment.',
   'DailyMed/FDA — Neurontin; EMC-UK',
   'DailyMed/FDA — Neurontin; EMC-UK'),
  ('pregabalina',
   'Actividade antiepiléptica e analgésica neuropática. Maior afinidade que gabapentina pela subunidade α2δ.',
   'Antiepileptic and neuropathic pain activity. Higher α2δ subunit affinity than gabapentin.',
   'Liga selectivamente à subunidade α2δ dos canais de cálcio voltagem-dependentes. Afinidade 6x superior à gabapentina. Reduz a libertação de neurotransmissores excitatórios no SNC e medula espinhal.',
   'Selectively binds to the α2δ subunit of voltage-gated calcium channels. 6-fold higher affinity than gabapentin. Reduces excitatory neurotransmitter release in the CNS and spinal cord.',
   'Metabolismo mínimo (<2%). Não é substrato nem inibidor significativo de CYP. Excreção renal (90% inalterado).',
   'Minimal metabolism (<2%). Not a substrate or significant inhibitor of CYP. Renal excretion (90% unchanged).',
   'Absorção oral rápida e linear. Biodisponibilidade: >90%. Pico: 1-2 h. Comida não afecta Cmax significativamente.',
   'Rapid and linear oral absorption. Bioavailability: >90%. Peak: 1-2 h. Food does not significantly affect Cmax.',
   '6,3 h.',
   '6.3 h.',
   'DailyMed/FDA — Lyrica; EMC-UK',
   'DailyMed/FDA — Lyrica; EMC-UK'),
  ('etossuximida',
   'Actividade antiepiléptica selectiva para crises de ausência primária. Inibe correntes de Ca²⁺ tipo T no tálamo.',
   'Selective antiepileptic activity for primary absence seizures. Inhibits T-type Ca²⁺ currents in the thalamus.',
   'Bloqueio selectivo das correntes de Ca²⁺ tipo T nos neurónios talâmicos, interrompendo a actividade oscillatória de 3 Hz que sustenta as crises de ausência.',
   'Selective blockade of T-type Ca²⁺ currents in thalamic neurons, interrupting the 3 Hz oscillatory activity that sustains absence seizures.',
   'Metabolizado por CYP3A4 (70%) e CYP2E1. Metabolitos inactivos. Não induz CYP.',
   'Metabolised by CYP3A4 (70%) and CYP2E1. Inactive metabolites. Does not induce CYP.',
   'Absorção oral completa e rápida. Biodisponibilidade: 100%. Pico: 1-4 h. Comida não afecta absorção.',
   'Complete and rapid oral absorption. Bioavailability: 100%. Peak: 1-4 h. Food does not affect absorption.',
   '40-60 h (adultos), 30 h (crianças).',
   '40-60 h (adults), 30 h (children).',
   'DailyMed/FDA — Zarontin; EMC-UK',
   'DailyMed/FDA — Zarontin; EMC-UK'),
  ('topiramato',
   'Actividade antiepiléptica de amplo espectro. Múltiplos mecanismos de acção.',
   'Broad-spectrum antiepileptic activity. Multiple mechanisms of action.',
   'Bloqueio de canais Na⁺ voltagem-dependentes (inactivação), potenciação de correntes mediadas por GABA-A, antagonismo de recetores AMPA/glutamato, inibição da anidrase carbonica (isoenzimas II e IV).',
   'Blockade of voltage-gated Na⁺ channels (inactivation), potentiation of GABA-A-mediated currents, AMPA/glutamate receptor antagonism, carbonic anhydrase inhibition (isoenzymes II and IV).',
   'Metabolizado hepaticamente (CYP3A4 parcial, ~40%). Glucuronidação (~50%). 30-50% excretado inalterado renalmente.',
   'Hepatically metabolised (partial CYP3A4, ~40%). Glucuronidation (~50%). 30-50% excreted unchanged renally.',
   'Absorção oral rápida. Biodisponibilidade: >80%. Pico: 1-4 h. Comida não afecta Cmax mas retarda Tmax.',
   'Rapid oral absorption. Bioavailability: >80%. Peak: 1-4 h. Food does not affect Cmax but delays Tmax.',
   '19-25 h.',
   '19-25 h.',
   'DailyMed/FDA — Topamax; EMC-UK',
   'DailyMed/FDA — Topamax; EMC-UK'),
  ('oxcarbazepina',
   'Actividade antiepiléptica via bloqueio de canais de Na⁺. Pro-fármaco metabolizado a MHD.',
   'Antiepileptic activity via Na⁺ channel blockade. Prodrug metabolised to MHD.',
   'Pro-fármaco: metabolizado a MHD (10-monohidroxiderivado), que bloqueia canais de Na⁺ voltagem-dependentes, estabilizando os canais no estado inactivo. Actua sinergicamente com fenitoína e valproato.',
   'Prodrug: metabolised to MHD (10-monohydroxyderivative), which blocks voltage-gated Na⁺ channels, stabilising channels in the inactive state. Acts synergistically with phenytoin and valproate.',
   'Metabolizado por CYP3A4 a MHD. MHD é glucuronidado (UGT). Induz CYP3A4 e UGT (menos que carbamazepina — não forma epóxido).',
   'Metabolised by CYP3A4 to MHD. MHD is glucuronidated (UGT). Induces CYP3A4 and UGT (less than carbamazepine — does not form epoxide).',
   'Absorção oral rápida e completa. Biodisponibilidade: >95%. MHD pico: 4-6 h.',
   'Rapid and complete oral absorption. Bioavailability: >95%. MHD peak: 4-6 h.',
   'MHD: 9-11 h.',
   'MHD: 9-11 h.',
   'DailyMed/FDA — Trileptal; EMC-UK',
   'DailyMed/FDA — Trileptal; EMC-UK'),
  ('zonisamida',
   'Actividade antiepiléptica de amplo espectro. Bloqueio de Na⁺ e inibição de anidrase carbonica.',
   'Broad-spectrum antiepileptic activity. Na⁺ blockade and carbonic anhydrase inhibition.',
   'Bloqueio de canais Na⁺ voltagem-dependentes e correntes T-type Ca²⁺. Inibe a anidrase carbonica (isoenzimas II e IV), contribuindo para efeitos adversos (pedras renais, acidose metabólica).',
   'Blockade of voltage-gated Na⁺ channels and T-type Ca²⁺ currents. Inhibits carbonic anhydrase (isoenzymes II and IV), contributing to adverse effects (renal stones, metabolic acidosis).',
   'Metabolizado por CYP3A4 (50%) e redução não enzimática (25%). 35% excretado inalterado. Metabolitos inactivos.',
   'Metabolised by CYP3A4 (50%) and non-enzymatic reduction (25%). 35% excreted unchanged. Inactive metabolites.',
   'Absorção oral completa e rápida. Biodisponibilidade: 100%. Pico: 2-6 h. Comida não afecta absorção.',
   'Complete and rapid oral absorption. Bioavailability: 100%. Peak: 2-6 h. Food does not affect absorption.',
   '50-70 h.',
   '50-70 h.',
   'DailyMed/FDA — Zonegran; EMC-UK',
   'DailyMed/FDA — Zonegran; EMC-UK'),
  ('lacosamida',
   'Actividade antiepiléptica selectiva via potenciação da inactivação lenta de canais Na⁺.',
   'Selective antiepileptic activity via potentiation of slow Na⁺ channel inactivation.',
   'Potencia selectivamente a inactivação lenta dos canais Na⁺ voltagem-dependentes (diferente de fenitoina/carbamazepina que potenciam a inactivação rápida). Resultado: menos efeitos colaterais neuropáticos.',
   'Selectively potentiates slow inactivation of voltage-gated Na⁺ channels (different from phenytoin/carbamazepine which potentiate fast inactivation). Result: fewer neuropathic adverse effects.',
   'Metabolizado por CYP3A4 (30%) e CYP2C19 (15%). 50% excretado inalterado renalmente. Inibe fracamente CYP2C19.',
   'Metabolised by CYP3A4 (30%) and CYP2C19 (15%). 50% excreted unchanged renally. Weakly inhibits CYP2C19.',
   'Absorção oral rápida e completa. Biodisponibilidade: 100%. Pico: 1-4 h.',
   'Rapid and complete oral absorption. Bioavailability: 100%. Peak: 1-4 h.',
   '13 h.',
   '13 h.',
   'DailyMed/FDA — Vimpat; EMC-UK',
   'DailyMed/FDA — Vimpat; EMC-UK'),
  ('primidona',
   'Actividade antiepiléptica barbitúrica. Pro-fármaco activo.',
   'Barbiturate antiepileptic activity. Active prodrug.',
   'Metabolizado a fenobarbital (activa, 50-60%) e feniletilmalonamida (activa, 25-30%). Ambos contribuem para o efeito antiepiléptico. Fenobarbital potencia GABA-A. Feniletilmalonamida bloqueia canais Na⁺.',
   'Metabolised to phenobarbital (active, 50-60%) and phenylethylmalonamide (active, 25-30%). Both contribute to antiepileptic effect. Phenobarbital potentiates GABA-A. Phenylethylmalonamide blocks Na⁺ channels.',
   'Metabolizado por CYP3A4, CYP2C9, CYP2C19 e glucuronidação. Induz CYP3A4, CYP2C9, CYP2C19, UGT (mesmo perfil que fenobarbital).',
   'Metabolised by CYP3A4, CYP2C9, CYP2C19 and glucuronidation. Induces CYP3A4, CYP2C9, CYP2C19, UGT (same profile as phenobarbital).',
   'Absorção oral completa. Biodisponibilidade: 100%. Pico: 2-4 h.',
   'Complete oral absorption. Bioavailability: 100%. Peak: 2-4 h.',
   'Primidona: 5-15 h. Fenobarbital (metabolito): 80-120 h.',
   'Primidone: 5-15 h. Phenobarbital (metabolite): 80-120 h.',
   'DailyMed/FDA — Mysoline; EMC-UK',
   'DailyMed/FDA — Mysoline; EMC-UK')
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
       metabolism_pt, metabolism_en, absorption_pt, absorption_en,
       half_life_pt, half_life_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
