-- =====================================================================
-- 258 — Lote 1 LNME (4/4): farmacologia em public.drug_pharmacology
-- ---------------------------------------------------------------------
-- Cinco campos PT/EN por fármaco (farmacodinâmica, mecanismo,
-- metabolismo, absorção, meia-vida), redigidos a partir da secção 12
-- CLINICAL PHARMACOLOGY dos rótulos DailyMed (setIDs validados) e
-- corroborados no Prontuário Terapêutico do INFARMED (11.ª ed., 2012).
-- Padrão 7.6 (JOIN VALUES + ON d.slug = v.slug + ON CONFLICT DO NOTHING).
-- Idempotente. Companheiras: 255 (drugs), 256/257 (perfis).
-- =====================================================================

INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en, absorption_pt, absorption_en,
   half_life_pt, half_life_en, source_pt, source_en, status)
SELECT d.id, v.pharmacodynamics_pt, v.pharmacodynamics_en, v.mechanism_pt, v.mechanism_en,
       v.metabolism_pt, v.metabolism_en, v.absorption_pt, v.absorption_en,
       v.half_life_pt, v.half_life_en, v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('albendazol',
   E'Antihelmíntico de largo espetro com atividade contra nemátodos, cestodos e tremátodos tecidulares; a eficácia depende da exposição sistémica do metabolito ativo (sulfoxido), ao contrário dos outros benzimidazólicos de ação luminal.',
   E'Broad-spectrum anthelmintic active against tissue nematodes, cestodes and trematodes; efficacy depends on systemic exposure to the active metabolite (sulfoxide), unlike other luminal-acting benzimidazoles.',
   E'Liga-se à β-tubulina do parasita e inibe a sua polimerização em microtúbulos, destruindo a microcanalização citoplasmática e bloqueando a captura de glicose — o parasita morre por depleção energética. Inibe também a fumarato redutase mitocondrial helmíntica.',
   E'Binds parasite β-tubulin and inhibits its polymerisation into microtubules, destroying cytoplasmic microtubules and blocking glucose uptake — the parasite dies of energy depletion. Also inhibits helminthic mitochondrial fumarate reductase.',
   E'Hidrólise rápida a sulfoxido por metabolismo de primeira passagem (CYP3A4 e flavinomonooxigenase); o sulfoxido é o metabolito ativo e sofre oxidação a sulfona inativa. O dexametasona/cimetidina aumentam as concentrações de sulfoxido; indutores (carbamazepina, fenitoína) reduzem-nas.',
   E'Rapid hydrolysis to sulfoxide via first-pass metabolism (CYP3A4 and flavin monooxygenase); sulfoxide is the active metabolite and undergoes further oxidation to inactive sulfone. Dexamethasone/cimetidine raise sulfoxide concentrations; inducers (carbamazepine, phenytoin) lower them.',
   E'Baixa por via oral em jejum (< 5%), aumentando 3–5 vezes com refeição gordurosa (o esquema da neurocisticercose recomenda 40 g de gordura na refeição de administração). O sulfoxido atinge pico plasmático em 2–5 h.',
   E'Poorly absorbed orally when fasting (< 5%), increasing 3–5-fold with a fatty meal (the neurocysticercosis regimen recommends 40 g of fat at the dosing meal). Sulfoxide peaks in plasma at 2–5 h.',
   E'Sulfoxido: 8–12 h (prolongado em cisticercose por biliar-recirculação); sulfona: ~10 h.',
   E'Sulfoxide: 8–12 h (prolonged in cysticercosis via enterohepatic recirculation); sulfone: ~10 h.',
   E'DailyMed/FDA — Albendazole Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8de337eb-92e1-15b5-e053-2a95a90ac4f1',
   E'DailyMed/FDA — Albendazole Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8de337eb-92e1-15b5-e053-2a95a90ac4f1'),
  ('mebendazol',
   E'Antihelmíntico luminal de largo espetro contra nemátodos intestinais; absorção sistémica mínima, o que concentra a ação no trato gastrointestinal e dá boa tolerância em programas de desparasitação em massa.',
   E'Broad-spectrum luminal anthelmintic against intestinal nematodes; minimal systemic absorption concentrates its action in the GI tract and gives good tolerance in mass deworming programmes.',
   E'Inibe a polimerização da β-tubulina helmíntica em microtúbulos citoplasmáticos, bloqueando irreversivelmente a captação e utilização de glicose pelo verme; efeito citocida (não apenas paralisante) nas células intestinais do parasita.',
   E'Inhibits helminthic β-tubulin polymerisation into cytoplasmic microtubules, irreversibly blocking worm glucose uptake and utilisation; cytocidal (not merely paralytic) to the parasite''s intestinal cells.',
   E'Metabolizado rapidamente a inativos (cetomebendazol e hidrolisados) por biotransformação intestinal e hepática; < 2% excretado na urina sem alteração. A carbamazepina/fenitoína podem reduzir os níveis plasmáticos; cimetidina eleva-os.',
   E'Rapidly metabolised to inactive products (ketomebendazole and hydrolysed metabolites) by intestinal and hepatic biotransformation; < 2% excreted unchanged in urine. Carbamazepine/phenytoin may lower plasma levels; cimetidine raises them.',
   E'Mínima: 2–10% da dose oral (variação individual ampla), aumentada por refeição gordurosa — irrelevante para nemátodos intestinais, mas exploitable em infestações tecidulares. Pico plasmático 2–4 h.',
   E'Minimal: 2–10% of the oral dose (wide individual variation), increased by fatty meals — irrelevant for intestinal nematodes but exploitable in tissue infestations. Plasma peak 2–4 h.',
   E'2,5–5,5 h (fração absorvida); excreção fecal predomina (fração não absorvida e metabolitos biliares).',
   E'2.5–5.5 h (absorbed fraction); faecal excretion predominates (unabsorbed fraction and biliary metabolites).',
   E'DailyMed/FDA — EMVERM (Mebendazole), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a8c46363-f739-4f6e-bca8-1ce5e8d3f78d',
   E'DailyMed/FDA — EMVERM (Mebendazole), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a8c46363-f739-4f6e-bca8-1ce5e8d3f78d'),
  ('ivermectina',
   E'Antiparasitário sistémico de espectro dirigido a nemátodos (oncocercose, strongiloidíase) e artrópodes (sarna, piolhos); morte dos microfilárias desencadeia reações inflamatórias (Mazzotti) proporcionais à carga parasitária.',
   E'Systemic antiparasitic targeted at nematodes (onchocerciasis, strongyloidiasis) and arthropods (scabies, lice); microfilariae death triggers inflammatory (Mazzotti) reactions proportional to parasite load.',
   E'Liga-se com alta afinidade a canais de cloro gated por glutamato nas células nervosas/musculares de invertebrados, abrindo-os e causando hiperpolarização, paralisia flácida e morte por inanição/fagocitose. Nos mamíferos, os canais homólogos estão confinados ao SNC e a glicoproteína-P exclui o fármaco (barreira hematoencefálica) — base da segurança seletiva.',
   E'Binds with high affinity to glutamate-gated chloride channels in invertebrate nerve/muscle cells, opening them and causing hyperpolarisation, flaccid paralysis and death by starvation/phagocytosis. In mammals the homologous channels are confined to the CNS and P-glycoprotein excludes the drug (blood-brain barrier) — the basis of selective safety.',
   E'Hidroxilação e desmetilação hepáticas (CYP3A4 principal) a metabolitos inativos; substrato de P-gp. Indutores potentes (rifampicina, ivermectina anti-epileptica) reduzem a exposição; inibidores de CYP3A4/P-gp elevam-na.',
   E'Hepatic hydroxylation and demethylation (mainly CYP3A4) to inactive metabolites; P-gp substrate. Potent inducers (rifampicin, antiepileptics) reduce exposure; CYP3A4/P-gp inhibitors raise it.',
   E'Biodisponibilidade oral ~65% (aumenta até 2,5 vezes com refeição); pico 4–5 h; alta lipofilia, volume de distribuição ~3,1 L/kg, concentrado em tecido adiposo e fígado; não atravessa significativamente a BHE.',
   E'Oral bioavailability ~65% (up to 2.5-fold increase with food); peak 4–5 h; high lipophilia, volume of distribution ~3.1 L/kg, concentrated in adipose tissue and liver; does not significantly cross the BBB.',
   E'~18 h (intervalo 12–54 h); excreção fecal predomina (> 90% dos metabolitos), < 1% na urina sem alteração.',
   E'~18 h (range 12–54 h); faecal excretion predominates (> 90% of metabolites), < 1% unchanged in urine.',
   E'DailyMed/FDA — STROMECTOL (Ivermectin), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=681888c9-af79-4b7d-ae80-c3f4f6f1effd',
   E'DailyMed/FDA — STROMECTOL (Ivermectin), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=681888c9-af79-4b7d-ae80-c3f4f6f1effd'),
  ('pirantel',
   E'Antihelmíntico luminal de primeira escolha pediátrica contra nemátodos intestinais (Ascaris, Enterobius, ancilostomas); atua por paralisia espástica do verme no lúmen, expulso por peristaltismo.',
   E'First-line paediatric luminal anthelmintic against intestinal nematodes (Ascaris, Enterobius, hookworms); acts by spastic paralysis of the worm in the lumen, expelled by peristalsis.',
   E'Agonista dos recetores nicotínicos da junção neuromuscular dos nemátodos: despolarização persistente e irreversível do músculo do verme, paralisia espástica e expulsão. Não atua em ovos nem em larvas migrantes tissulares.',
   E'Agonist of nematode neuromuscular nicotinic receptors: persistent and irreversible depolarisation of worm muscle, spastic paralysis and expulsion. Inactive against eggs and tissue-migrating larvae.',
   E'Metabolizado hepaticamente a N-metil-pirantel (metabolito principal, inativo); fração absorvida excretada na urina (7–17% como N-metil). Sem interações CYP relevantes descritas.',
   E'Hepatic metabolism to N-methyl-pyrantel (main inactive metabolite); absorbed fraction excreted in urine (7–17% as N-methyl). No relevant CYP interactions described.',
   E'Baixa por via oral (6–17%); pico plasmático 1–3 h; administração com comida não altera significativamente a eficácia luminal. A pamoato é pouco solúvel, mantendo o fármaco no intestino.',
   E'Poorly absorbed orally (6–17%); plasma peak 1–3 h; administration with food does not significantly change luminal efficacy. The pamoate salt is poorly soluble, keeping the drug in the intestine.',
   E'~1–3 h (fração absorvida, excretada renalmente como N-metil); a fração não absorvida elimina-se nas fezes.',
   E'~1–3 h (absorbed fraction, renally excreted as N-methyl); the unabsorbed fraction is eliminated in faeces.',
   E'DailyMed/FDA — PINWORM MEDICINE (Pyrantel Pamoate), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f23d5092-48ca-46c4-830a-c34d0a3a7f57',
   E'DailyMed/FDA — PINWORM MEDICINE (Pyrantel Pamoate), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f23d5092-48ca-46c4-830a-c34d0a3a7f57'),
  ('oxitocina',
   E'Hormona uterotónica de primeira linha na profilaxia e tratamento da hemorragia pós-parto e na indução do trabalho de parto; perfusão contínua ajustável graças à meia-vida muito curta.',
   E'First-line uterotonic hormone for prevention and treatment of postpartum haemorrhage and labour induction; continuously adjustable infusion thanks to its very short half-life.',
   E'Liga-se aos recetores de oxitocina Gq-coupled do miométrio, ativando fosfolipase C → IP3 → libertação de cálcio do retículo sarcoplasmático e influxo por canais dependentes de voltagem: aumento da contratilidade, da frequência e do tónus uterinos. Sensibilização recetorial progressiva ao longo da gestação (potenciado por estrogénios e prostaglandinas). Em doses farmacológicas altas, ativa recetores V2 renais (efeito antidiurético).',
   E'Binds Gq-coupled oxytocin receptors in the myometrium, activating phospholipase C → IP3 → calcium release from the sarcoplasmic reticulum and voltage-dependent influx: increased uterine contractility, frequency and tone. Progressive receptor sensitisation throughout gestation (potentiated by oestrogens and prostaglandins). At high pharmacological doses, activates renal V2 receptors (antidiuretic effect).',
   E'Degradação por oxitocinase plasmática e hepática (cis-trans-isomerização e desamidação); < 1% excretado na urina sem alteração. Sem metabolismo CYP relevante — interações farmacocinéticas mínimas.',
   E'Degradation by plasma and hepatic oxytocinase (cis-trans isomerisation and deamidation); < 1% excreted unchanged in urine. No relevant CYP metabolism — minimal pharmacokinetic interactions.',
   E'IV: início imediato, ação dose-dependente; IM: início 3–5 min, duração 30–60 min. Biodisponibilidade oral nula (degradação proteolítica); uso exclusivamente parenteral.',
   E'IV: immediate onset, dose-dependent action; IM: onset 3–5 min, duration 30–60 min. Nil oral bioavailability (proteolytic degradation); parenteral use only.',
   E'3–5 min (IV); 20–40 min aparentes por IM pela absorção contínua do depósito.',
   E'3–5 min (IV); apparent 20–40 min by IM due to continuous depot absorption.',
   E'DailyMed/FDA — PITOCIN (Oxytocin), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6e5a66fc-e507-497c-b5ce-44a8c95898ad',
   E'DailyMed/FDA — PITOCIN (Oxytocin), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6e5a66fc-e507-497c-b5ce-44a8c95898ad'),
  ('misoprostol',
   E'Análogo da PGE1 com ação uterotónica e gastroprotetora; a estabilidade à temperatura ambiente e a via vaginal/sublingual fizeram dele o uterotónico de maior alcance em programas de saúde materna onde a cadeia de frio é limitada.',
   E'PGE1 analogue with uterotonic and gastroprotective action; room-temperature stability and the vaginal/sublingual route made it the most far-reaching uterotonic in maternal health programmes where cold chain is limited.',
   E'Liga-se a recetores EP1/EP3 do miométrio: aumento de cálcio intracelular e contração uterina, mais amolecimento e dilatação cervical (remodelagem de colagénio). Na mucosa gástrica, ativa EP3 nas células parietais → reduz secreção de HCl e aumenta muco e fluxo bicarbonatado (efeito citoprotetor).',
   E'Binds myometrial EP1/EP3 receptors: raised intracellular calcium and uterine contraction, plus cervical softening and dilation (collagen remodelling). In gastric mucosa, activates parietal-cell EP3 → reduced HCl secretion and increased mucus and bicarbonate flow (cytoprotective effect).',
   E'Hidrólise rápida de éster (mucosa intestinal, fígado, plasma) a ácido misoprostólico, o único metabolito ativo; não há metabolismo CYP relevante — interações farmacocinéticas mínimas.',
   E'Rapid ester hydrolysis (intestinal mucosa, liver, plasma) to misoprostol acid, the only active metabolite; no relevant CYP metabolism — minimal pharmacokinetic interactions.',
   E'Oral: absorção rápida (pico 12–30 min), biodisponibilidade ~15% do ácido ativo. Vaginal/sublingual: pico mais tardio (60–90 min) mas concentrações máximas 2–3× maiores e prolongadas — base da preferência obstétrica.',
   E'Oral: rapid absorption (peak 12–30 min), ~15% bioavailability of the active acid. Vaginal/sublingual: later peak (60–90 min) but 2–3-fold higher and prolonged maximum concentrations — the basis of obstetric preference.',
   E'Ácido misoprostólico: 20–40 min.',
   E'Misoprostol acid: 20–40 min.',
   E'DailyMed/FDA — CYTOTEC (Misoprostol), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4ab12da7-5731-4e06-bf1c-bc3f2e711f12',
   E'DailyMed/FDA — CYTOTEC (Misoprostol), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4ab12da7-5731-4e06-bf1c-bc3f2e711f12'),
  ('metilergometrina',
   E'Uterotónico ergotado de ação firme e prolongada, usado APÓS o descolamento da placenta; contraindicado antes (risco de retenção placentária e hipertensão grave).',
   E'Firm, long-acting ergot uterotonic used AFTER placental delivery; contraindicated before (risk of retained placenta and severe hypertension).',
   E'Agonista parcial dos recetores alfa-1-adrenérgicos e 5-HT2 do miométrio: aumento do tónus basal (contração tetânica sustentada) e da frequência de contrações; menor atividade vasopressora que os outros alcaloides do ergot, mas retém risco de vasoconstrição coronária/periférica em doses altas ou predispostos.',
   E'Partial agonist at myometrial alpha-1-adrenergic and 5-HT2 receptors: increased basal tone (sustained tetanic contraction) and contraction frequency; less vasopressor activity than other ergot alkaloids but retains coronary/peripheral vasoconstriction risk at high doses or in predisposed patients.',
   E'Hidroxilação hepática extensa (CYP3A4) e conjugação; a fração absorvida sofre primeira passagem significativa (biodisponibilidade oral ~60%). Inibidores de CYP3A4 (macrólidos, azólicos) elevam a exposição — risco de ergotismo.',
   E'Extensive hepatic hydroxylation (CYP3A4) and conjugation; the absorbed fraction undergoes significant first-pass (oral bioavailability ~60%). CYP3A4 inhibitors (macrolides, azoles) raise exposure — ergotism risk.',
   E'Oral: absorção boa (~60–70%), pico 30–60 min, início 5–15 min. IM: pico mais rápido (início 2–5 min). IV (raro, diluído): imediato — risco de hipertensão grave.',
   E'Oral: good absorption (~60–70%), peak 30–60 min, onset 5–15 min. IM: faster peak (onset 2–5 min). IV (rare, diluted): immediate — risk of severe hypertension.',
   E'3,4 h (IV); 8–12 h aparentes por via oral (absorção/prolongação do efeito uterino).',
   E'3.4 h (IV); apparent 8–12 h orally (absorption/prolonged uterine effect).',
   E'DailyMed/FDA — METHERGINE (Methylergonovine), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f04ca06-fe52-46d6-96cd-2e77ef6fa36f',
   E'DailyMed/FDA — METHERGINE (Methylergonovine), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f04ca06-fe52-46d6-96cd-2e77ef6fa36f'),
  ('metildopa',
   E'Anti-hipertensivo central de referência na gravidez, com eficácia comprovada e segurança fetal estabelecida em décadas de uso; menos usado fora da gestação pelos efeitos centrais.',
   E'Reference central antihypertensive in pregnancy, with proven efficacy and established fetal safety over decades of use; less used outside gestation due to central effects.',
   E'Metabolizado no SNC a α-metil-noradrenalina, falsa-transmissor que estimula recetores alfa-2 centrais (tronco): redução do efluxo simpático, da resistência vascular periférica e da frequência cardíaca; fluxo renal e placentário preservados.',
   E'Converted in the CNS to α-methylnoradrenaline, a false transmitter stimulating central (brainstem) alpha-2 receptors: reduced sympathetic outflow, peripheral vascular resistance and heart rate; renal and placental flows preserved.',
   E'Descarboxilação e hidroxilação no SNC (dopa-descarboxilase e dopamina-β-hidroxilase); excreção renal de α-metildopa sem alteração (~40–60%) e conjugados. Diálise remove o fármaco.',
   E'Decarboxylation and hydroxylation in the CNS (dopa decarboxylase and dopamine-β-hydroxylase); renal excretion of unchanged methyldopa (~40–60%) and conjugates. Dialysis removes the drug.',
   E'Absorção oral variável (~25–50%, saturável em doses altas); pico 2–4 h; efeito anti-hipertensivo máximo 6–8 h após dose. Alimentos não alteram significativamente a extensão da absorção.',
   E'Variable oral absorption (~25–50%, saturable at high doses); peak 2–4 h; maximum antihypertensive effect 6–8 h after the dose. Food does not significantly change absorption extent.',
   E'1,5–2 h (plasmática); efeito farmacológico prolongado (24–48 h) pela persistência do falsa-transmissor nos depósitos centrais.',
   E'1.5–2 h (plasma); prolonged pharmacological effect (24–48 h) due to persistence of the false transmitter in central stores.',
   E'DailyMed/FDA — Methyldopa Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9e22e1d8-04ec-4b67-92ea-b09c706f2703',
   E'DailyMed/FDA — Methyldopa Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9e22e1d8-04ec-4b67-92ea-b09c706f2703'),
  ('hidralazina',
   E'Vasodilatador arterial direto para hipertensão refratária (oral, em combinação) e urgência hipertensiva obstétrica (IV); o uso em monoterapia é limitado pela taquicardia reflexa e retenção hidrossalina.',
   E'Direct arterial vasodilator for refractory hypertension (oral, in combination) and obstetric hypertensive emergency (IV); monotherapy is limited by reflex tachycardia and fluid retention.',
   E'Abre canais de K+ e ativa a guanilato ciclase no músculo liso arteriolar (mais do que venular), reduzindo a pós-carga; a queda da pressão desencadeia taquicardia reflexa (barorreflexo), ativação simpática e libertação de renina — daí a combinação com betabloqueador e diurético.',
   E'Opens K+ channels and activates guanylate cyclase in arteriolar (more than venular) smooth muscle, reducing afterload; the pressure drop triggers reflex tachycardia (baroreflex), sympathetic activation and renin release — hence combination with a beta-blocker and diuretic.',
   E'Acetilação hepática (N-acetiltransferase 2 — polimorfismo acetilador rápido/lento) e hidroxilação; acetiladores lentos têm níveis mais altos e mais efeitos adversos (incluindo lupus induzido). Metabolitos excretados na urina.',
   E'Hepatic acetylation (N-acetyltransferase 2 — fast/slow acetylator polymorphism) and hydroxylation; slow acetylators have higher levels and more adverse effects (including drug-induced lupus). Metabolites excreted in urine.',
   E'Absorção oral boa (> 75% para a forma hidralazina) mas biotransformação de primeira passagem substancial (biodisponibilidade sistémica 25–55% em acetiladores lentos); pico 45–90 min. Alimentos aumentam a absorção.',
   E'Good oral absorption (> 75% for hydralazine form) but substantial first-pass metabolism (systemic bioavailability 25–55% in slow acetylators); peak 45–90 min. Food increases absorption.',
   E'3–7 h (plasmática); ação vasodilatadora mais prolongada (ligação ao tecido vascular). Na insuficiência renal, meia-vida pode chegar a 7–16 h.',
   E'3–7 h (plasma); vasodilatory action longer (vascular tissue binding). In renal failure, half-life may reach 7–16 h.',
   E'DailyMed/FDA — Hydralazine Hydrochloride Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=47ad263b-ad3d-4f98-b0aa-d9e82ab6cb67',
   E'DailyMed/FDA — Hydralazine Hydrochloride Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=47ad263b-ad3d-4f98-b0aa-d9e82ab6cb67'),
  ('lidocaina',
   E'Anestésico local amida de referência, com bloqueio nervoso reversível dependente da dose, concentração e tempo de exposição do tecido; adicionada de epinefrina, duração e margem de segurança aumentam.',
   E'Reference amide local anaesthetic, with reversible nerve block dependent on dose, concentration and tissue exposure time; with epinephrine, duration and safety margin increase.',
   E'Bloqueia canais de sódio voltagem-dependentes da membrana neuronal (estado ativado/inativado — uso-dependente): interrompe a propagação do potencial de ação nas fibras nociceptivas antes nas pequenas (mielínicas finas e C) do que nas motoras grossas. A epinefrina vasoconstri o leito local, reduzindo a absorção e o pico plasmático.',
   E'Blocks voltage-gated sodium channels of the neuronal membrane (activated/inactivated state — use-dependent): interrupts action potential propagation in nociceptive fibres earlier in small (thin myelinated and C) than in large motor fibres. Epinephrine vasoconstricts the local bed, reducing absorption and plasma peak.',
   E'Oxidação N-dealquilação (CYP1A2 e CYP3A4) a monoetilglicinaxilidida (MEGX) e glicinaxilidida, excretadas renais; extração hepática alta (clearance dependente de fluxo). Antiarrítmico: eficácia reduzida na insuficiência cardíaca (menor fluxo hepático).',
   E'N-dealkylation oxidation (CYP1A2 and CYP3A4) to monoethylglycinexylidide (MEGX) and glycinexylidide, renally excreted; high hepatic extraction (flow-dependent clearance). As an antiarrhythmic: efficacy reduced in heart failure (lower hepatic flow).',
   E'Infiltração local: absorção proporcional à vascularização do local (intercostal > caudal > epidural > subcutânea); pico 30–45 min. A epinefrina reduz a taxa de absorção em ~1/3. Biodisponibilidade oral irrelevante (primeira passagem total).',
   E'Local infiltration: absorption proportional to site vascularity (intercostal > caudal > epidural > subcutaneous); peak 30–45 min. Epinephrine reduces absorption rate by ~1/3. Oral bioavailability irrelevant (complete first pass).',
   E'1,5–2 h (pós-infusão); na toxicidade sistémica a distribuição rápida é seguida de re-elevação (segunda fase). Neonatos: 3–4 h.',
   E'1.5–2 h (post-infusion); in systemic toxicity rapid distribution is followed by re-elevation (second phase). Neonates: 3–4 h.',
   E'DailyMed/FDA — XYLOCAINE (Lidocaine HCl, Epinephrine), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9e8d0318-b2fe-4084-aedf-de97f61605a8',
   E'DailyMed/FDA — XYLOCAINE (Lidocaine HCl, Epinephrine), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9e8d0318-b2fe-4084-aedf-de97f61605a8'),
  ('midazolam',
   E'Benzodiazepina de ultracurta duração com amnésia anterógrada robusta: padrão em sedação procedural, mas exige monitorização rigorosa pela depressão respiratória dose-dependente.',
   E'Ultra-short-acting benzodiazepine with robust anterograde amnesia: standard in procedural sedation, but requires strict monitoring due to dose-dependent respiratory depression.',
   E'Modulador alostérico positivo do recetor GABA-A: aumenta a frequência de abertura do canal de cloro em resposta ao GABA, hiperpolarizando os neurónios — efeitos ansiolítico, sedativo, hipnótico, miorrelaxante e anticonvulsivo. Antagonizável por flumazenil.',
   E'Positive allosteric modulator of the GABA-A receptor: increases the frequency of chloride channel opening in response to GABA, hyperpolarising neurones — anxiolytic, sedative, hypnotic, myorelaxant and anticonvulsant effects. Reversible by flumazenil.',
   E'Hidroxilação hepática quase total (CYP3A4/3A5) a 1-hidroximidazolam (ativo, ~60–80% da potência do original), glucuronidado e excretado renalmente; nenhum fármaco original recuperado na urina. Inibidores potentes de CYP3A4 (claritromicina, azólicos, diltiazem) multiplicam a exposição.',
   E'Almost complete hepatic hydroxylation (CYP3A4/3A5) to 1-hydroxymidazolam (active, ~60–80% of parent potency), glucuronidated and renally excreted; no unchanged drug recovered in urine. Potent CYP3A4 inhibitors (clarithromycin, azoles, diltiazem) multiply exposure.',
   E'IV: imediata. IM: absorção rápida e completa (> 90%, pico 20–30 min). Oral: rápida, mas primeira passagem de ~40% (biodisponibilidade 30–70%). Intranasal/buccal: boa (pico 10–15 min), útil no estado de mal fora do hospital.',
   E'IV: immediate. IM: rapid complete absorption (> 90%, peak 20–30 min). Oral: rapid, but ~40% first pass (bioavailability 30–70%). Intranasal/buccal: good (peak 10–15 min), useful in out-of-hospital status epilepticus.',
   E'1,5–3,5 h (adultos sadios); prolongada em idosos (3–4 h), obesos, insuficiência hepática e em recém-nascidos (6–12 h).',
   E'1.5–3.5 h (healthy adults); prolonged in the elderly (3–4 h), obese, hepatic impairment and neonates (6–12 h).',
   E'DailyMed/FDA — MIDAZOLAM (Midazolam HCl), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d9305142-417d-4d8c-9a23-f9a1b6771cac',
   E'DailyMed/FDA — MIDAZOLAM (Midazolam HCl), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d9305142-417d-4d8c-9a23-f9a1b6771cac'),
  ('atropina',
   E'Anticolinérgico de referência na bradicardia sintomática e como antídoto colinérgico; efeitos dose-graduados do quadrante antimuscarínico (secreções → frequência cardíaca → TGI → órgão → CNS).',
   E'Reference anticholinergic in symptomatic bradycardia and as cholinergic antidote; dose-graded effects across the antimuscarinic quadrant (secretions → heart rate → GI → organ → CNS).',
   E'Antagonista competitivo dos recetores muscarínicos (M1–M5): bloqueia a ação da acetilcolina pós-ganglionar parassimpática — no coração remove o tónus vagal (taquicardia), nas glândulas reduz secreções, no músculo liso diminui o peristaltismo, na pupila causa midríase/cicloplegia. Atravessa a BHE (efeitos centrais) e a placenta.',
   E'Competitive antagonist at muscarinic receptors (M1–M5): blocks post-ganglionic parasympathetic acetylcholine action — in the heart removes vagal tone (tachycardia), in glands reduces secretions, in smooth muscle decreases motility, in the pupil causes mydriasis/cycloplegia. Crosses the BBB (central effects) and the placenta.',
   E'Hidrólise hepática a tropina e ácido trópico (~50%); o restante excretado renalmente sem alteração. Sem interações CYP clinicamente relevantes — excreção renal dominante.',
   E'Hepatic hydrolysis to tropine and tropic acid (~50%); the rest excreted renally unchanged. No clinically relevant CYP interactions — renal excretion dominant.',
   E'IV: imediata (pico < 2 min). IM: rápida e completa. Oral: absorvida mas a primeira passagem é parcial (biodisponibilidade 10–25%); o efeito oftalmológico (colírio) é local e prolongado.',
   E'IV: immediate (peak < 2 min). IM: rapid and complete. Oral: absorbed but partial first pass (bioavailability 10–25%); ophthalmic effect (eye drops) is local and prolonged.',
   E'2–5 h (plasmática); a midríase e a cicloplegia duram dias (ligação tecidual ocular), a taquicardia 2–3 h por IV.',
   E'2–5 h (plasma); mydriasis and cycloplegia last days (ocular tissue binding), tachycardia 2–3 h after IV.',
   E'DailyMed/FDA — ATROPINE SULFATE Injection, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8663ff94-8bea-4061-9fd5-3ab2e85e862e',
   E'DailyMed/FDA — ATROPINE SULFATE Injection, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8663ff94-8bea-4061-9fd5-3ab2e85e862e'),
  ('clorpromazina',
   E'Antipsicótico típico fenotiazínico de largo perfil receptorial (D2 > alfa-1 ≈ M1 ≈ H1), o que explica eficácia e também o fardo de efeitos adversos; ainda essencial na saúde pública pela robustez e custo.',
   E'Phenothiazine typical antipsychotic with a broad receptor profile (D2 > alpha-1 ≈ M1 ≈ H1), explaining both efficacy and the side-effect burden; still essential in public health for robustness and cost.',
   E'Antagonismo potente de recetores D2 mesolímbicos/mesocorticais (antipsicótico, antiemético no centro do vómito) com antagonismo aditivo: alfa-1 (hipotensão ortostática), M1 (boca seca, midríase, retenção), H1 (sedação) e 5-HT2. Prolonga o QT (bloqueio hERG) e reduz o limiar convulsivo.',
   E'Potent antagonism of mesolimbic/mesocortical D2 receptors (antipsychotic, antiemetic at the vomiting centre) with additive antagonism: alpha-1 (orthostatic hypotension), M1 (dry mouth, mydriasis, retention), H1 (sedation) and 5-HT2. Prolongs QT (hERG blockade) and lowers the seizure threshold.',
   E'Oxidação, N-desmetilação e conjugação hepáticas (CYP2D6 e CYP1A2; polimorfismo altera exposição); > 100 metabolitos descritos, a maioria inativos. Excreção: urina (metabolitos) e bile.',
   E'Hepatic oxidation, N-demethylation and conjugation (CYP2D6 and CYP1A2; polymorphism alters exposure); > 100 metabolites described, mostly inactive. Excretion: urine (metabolites) and bile.',
   E'Absorção oral variável (32–50% por primeira passagem; IM dobra a exposição); pico 2–4 h (oral) / 15–30 min (IM). Alta ligação a proteínas (> 95%) e grandes depósitos tecidulares — efeitos persistem após suspensão.',
   E'Variable oral absorption (32–50% first pass; IM doubles exposure); peak 2–4 h (oral) / 15–30 min (IM). High protein binding (> 95%) and large tissue depots — effects persist after stopping.',
   E'16–30 h (plasmática), prolongada em idosos e hepatopatas; depósitos tecidulares prolongam o efeito (bipolaridade clínica por semanas).',
   E'16–30 h (plasma), prolonged in the elderly and liver disease; tissue depots extend the effect (clinical tail for weeks).',
   E'DailyMed/FDA — Chlorpromazine Hydrochloride Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d43718e5-66d7-44f9-9fc8-80d38d3e41ce',
   E'DailyMed/FDA — Chlorpromazine Hydrochloride Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d43718e5-66d7-44f9-9fc8-80d38d3e41ce'),
  ('prometazina',
   E'Anti-histamínico H1 de 1.ª geração com sedação forte e ação antiemética; o perfil de segurança exige restrições etárias e cuidado com a via injetável.',
   E'First-generation H1 antihistamine with strong sedation and antiemetic action; its safety profile demands age restrictions and care with the injectable route.',
   E'Antagonista H1 competitivo (bloqueia broncoconstricção, prurido e vasodilatação histamínica) com ação aditiva: antagonismo muscarínico (boca seca, midríase), sedação central via H1 cerebral e bloqueio D2 no centro do vómito (antiemético). Prolonga o QT em doses altas.',
   E'Competitive H1 antagonist (blocks histamine bronchoconstriction, pruritus and vasodilation) with additive actions: muscarinic antagonism (dry mouth, mydriasis), central sedation via brain H1 and D2 blockade at the vomiting centre (antiemetic). Prolongs QT at high doses.',
   E'Metabolismo hepático extenso (N-desmetilação, S-oxidação, aromática hidroxilação — CYP2D6 e outros); excreção renal de metabolitos; fração mínima sem alteração. Cirrose e idosos: exposição aumentada.',
   E'Extensive hepatic metabolism (N-demethylation, S-oxidation, aromatic hydroxylation — CYP2D6 and others); renal excretion of metabolites; minimal unchanged fraction. Cirrhosis and the elderly: increased exposure.',
   E'Oral: boa absorção, pico 2–3 h, início 20–30 min. IM: rápida (pico 1–2 h); NUNCA intravenosa direta sem diluição (necrose tecidual, gangrena com extravasamento arterial).',
   E'Oral: good absorption, peak 2–3 h, onset 20–30 min. IM: rapid (peak 1–2 h); NEVER direct undiluted IV (tissue necrosis, gangrene with arterial extravasation).',
   E'10–19 h (adultos); prolongada em recém-nascidos e lactentes — base da contraindicação < 2 anos.',
   E'10–19 h (adults); prolonged in neonates and infants — the basis of the < 2 years contraindication.',
   E'DailyMed/FDA — Promethazine Hydrochloride Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51e3baab-eba7-460c-9de1-bf6cfc378310',
   E'DailyMed/FDA — Promethazine Hydrochloride Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=51e3baab-eba7-460c-9de1-bf6cfc378310'),
  ('hidroxizina',
   E'Anti-histamínico sedativo de primeira geração com uso duplo clínico: antipruriginoso/antialérgico e ansiolítico sem dependência; metabolito ativo parcial (cetirizina) com menos sedação.',
   E'Sedating first-generation antihistamine with dual clinical use: antipruritic/antiallergic and non-dependence-forming anxiolytic; partially active metabolite (cetirizine) with less sedation.',
   E'Antagonista H1 central e periférico (sedação, ansiólise, antiprurido) com antagonismo muscarínico moderado (efeitos anticolinérgicos leves) e alfa-1 (hipotensão discreta). Prolongamento do QT documentado (bloqueio hERG) — dose-dependente e com preocupação regulatória atual (doses curtas de altas doses).',
   E'Central and peripheral H1 antagonist (sedation, anxiolysis, antipruritus) with moderate muscarinic antagonism (mild anticholinergic effects) and alpha-1 (discrete hypotension). Documented QT prolongation (hERG blockade) — dose-dependent and a current regulatory concern (short high-dose courses).',
   E'Metabolismo hepático quase total (CYP2D6 principal e CYP3A4) a cetirizina (metabolito ativo, H1 periférico potente com menos passagem da BHE); excreção renal de cetirizina e metabolitos. Insuficiência renal/hepática: aumentar intervalo.',
   E'Almost complete hepatic metabolism (mainly CYP2D6 and CYP3A4) to cetirizine (active metabolite, potent peripheral H1 with less BBB passage); renal excretion of cetirizine and metabolites. Renal/hepatic impairment: lengthen interval.',
   E'Oral: absorção rápida e boa (> 80%), pico 2 h, início clínico 15–60 min. IM: rápida (pico ~1 h). Comida não altera significativamente a extensão.',
   E'Oral: rapid good absorption (> 80%), peak 2 h, clinical onset 15–60 min. IM: rapid (peak ~1 h). Food does not significantly change extent.',
   E'~20 h (adultos); 7–12 h em crianças (doses mais frequentes por peso). Cetirizina (metabolito): 8–9 h.',
   E'~20 h (adults); 7–12 h in children (more frequent weight-based doses). Cetirizine (metabolite): 8–9 h.',
   E'DailyMed/FDA — Hydroxyzine Hydrochloride Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58d99cf6-2319-410b-b8be-de9c304541b6',
   E'DailyMed/FDA — Hydroxyzine Hydrochloride Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=58d99cf6-2319-410b-b8be-de9c304541b6'),
  ('imipramina',
   E'Antidepressivo tricíclico protótipo: eficaz mas de índice terapêutico estreito e toxicidade cardíaca grave em sobredosagem; uso atual reservado a indicações específicas (enurese, dor neuropática, depressão refratária).',
   E'Prototype tricyclic antidepressant: effective but with a narrow therapeutic index and severe cardiac toxicity in overdose; current use reserved for specific indications (enuresis, neuropathic pain, resistant depression).',
   E'Inibe a recaptação de serotonina e noradrenalina (transportadores SERT/NET), aumentando a neurotransmissão monoaminérgica; os efeitos clínicos antidepressor demoram 2–4 semanas (dessensibilização recetorial). Antagonismo M1, H1, alfa-1 explica boca seca, sedação e hipotensão; bloqueio dos canais de sódio cardíacos (fase 0) explica a cardiotoxicidade da sobredosagem e o prolongamento do QT/QRS.',
   E'Inhibits serotonin and noradrenaline reuptake (SERT/NET transporters), increasing monoaminergic neurotransmission; antidepressant effects take 2–4 weeks (receptor desensitisation). M1, H1, alpha-1 antagonism explains dry mouth, sedation and hypotension; cardiac sodium channel blockade (phase 0) explains overdose cardiotoxicity and QT/QRS prolongation.',
   E'N-desmetilação hepática (CYP2C19, CYP1A2, CYP3A4) a desipramina (metabolito ativo mais noradrenérgico); hidroxilação anelar por CYP2D6 (polimorfismo importante — metabolizadores lentos acumulam). Glucuronidação e excreção renal.',
   E'Hepatic N-demethylation (CYP2C19, CYP1A2, CYP3A4) to desipramine (more noradrenergic active metabolite); ring hydroxylation by CYP2D6 (important polymorphism — slow metabolisers accumulate). Glucuronidation and renal excretion.',
   E'Absorção oral boa (~75–95%), mas primeira passagem significativa (biodisponibilidade 30–75%); pico 1–2 h; alta lipofilia, grande volume de distribuição (10–15 L/kg) e ligação a proteínas ~90%.',
   E'Good oral absorption (~75–95%), but significant first pass (bioavailability 30–75%); peak 1–2 h; high lipophilia, large volume of distribution (10–15 L/kg) and ~90% protein binding.',
   E'6–20 h (imipramina); desipramina 14–25 h — permite dose 1–2×/dia, mas prolonga a recuperação de sobredosagem.',
   E'6–20 h (imipramine); desipramine 14–25 h — allows 1–2×/day dosing, but prolongs overdose recovery.',
   E'DailyMed/FDA — Imipramine Hydrochloride Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=649837df-147f-436c-9553-32ffecf4c6f1',
   E'DailyMed/FDA — Imipramine Hydrochloride Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=649837df-147f-436c-9553-32ffecf4c6f1'),
  ('clotrimazol',
   E'Antifúngico imidazólico tópico com espectro dermatofito+leveduras e absorção sistémica desprezável; base do tratamento tópico das micoses superficiais em todas as faixas etárias.',
   E'Topical imidazole antifungal covering dermatophytes+yeasts with negligible systemic absorption; the backbone of superficial mycosis topical treatment across all ages.',
   E'Inibe a 14-α-desmetilase (CYP51) fúngica, bloqueando a conversão de lanosterol em ergosterol: o défice de ergosterol e o acúmulo de esteróis metilados desorganizam a membrana celular do fungo (fungistático) e, com exposição prolongada, tornam-na permeável (fungicida).',
   E'Inhibits fungal 14-α-demethylase (CYP51), blocking lanosterol-to-ergosterol conversion: ergosterol depletion and accumulation of methylated sterols disorganise the fungal cell membrane (fungistatic) and, with prolonged exposure, make it permeable (fungicidal).',
   E'Absorção sistémica mínima: a fração que atravessa a pele/epitélio vaginal é metabolizada rapidamente no fígado (oxidação e degradação do anel imidazólico) a metabolitos inativos, excretados fecal e urinariamente. Não há interações CYP sistémicas clinicamente relevantes.',
   E'Minimal systemic absorption: the fraction crossing skin/vaginal epithelium is rapidly metabolised in the liver (oxidation and imidazole ring degradation) to inactive metabolites, excreted in faeces and urine. No clinically relevant systemic CYP interactions.',
   E'Cutânea: < 0,5% da dose atravessa a epiderme intacta (mais em pele lesada e oclusão). Vaginal: 3–10% absorvido (pico 8–24 h); concentrações locais elevadas persistem 2–3 dias após cada óvulo.',
   E'Cutaneous: < 0.5% of the dose crosses intact epidermis (more in broken skin and occlusion). Vaginal: 3–10% absorbed (peak 8–24 h); high local concentrations persist 2–3 days after each pessary.',
   E'Não determinável clinicamente (absorção sistémica desprezável); a ação local persiste pela afinidade à queratina.',
   E'Not clinically determinable (negligible systemic absorption); local action persists through keratin affinity.',
   E'DailyMed/FDA — Clotrimazole Cream, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4581d0c9-1f85-42c8-87d7-5f38fbbc923a',
   E'DailyMed/FDA — Clotrimazole Cream, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4581d0c9-1f85-42c8-87d7-5f38fbbc923a'),
  ('miconazol',
   E'Antifúngico imidazólico tópico de amplo uso (cutâneo, vaginal, oral) com fungicidismo direto na membrana fúngica; a exceção sistémica é o gel bucal, com interação real com anticoagulantes cumarínicos.',
   E'Widely used imidazole topical antifungal (cutaneous, vaginal, oral) with direct fungicidal membrane action; the systemic exception is the buccal gel, with a real interaction with coumarin anticoagulants.',
   E'Duas ações membrana: (1) inibição da 14-α-desmetilase (CYP51) → défice de ergosterol; (2) em concentrações tópicas altas, interação direta com fosfolipídios da membrana → perda de integridade e morte celular (fungicida). Também inibe a produção de ácidos proteolíticos do fungo e tem atividade antibacteriana leve contra Gram+.',
   E'Two membrane actions: (1) inhibition of 14-α-demethylase (CYP51) → ergosterol depletion; (2) at high topical concentrations, direct interaction with membrane phospholipids → loss of integrity and cell death (fungicidal). Also inhibits fungal proteolytic acid production and has mild Gram+ antibacterial activity.',
   E'Fração absorvida (significativa apenas no gel oral) metabolizada hepaticamente; inibe CYP2C9 sistemicamente quando absorvido — interação com warfarina/acenocumarol com hemorragias descritas (INR elevado). Excreção renal e biliar de metabolitos.',
   E'The absorbed fraction (significant only for oral gel) is hepatically metabolised; systemically inhibits CYP2C9 when absorbed — interaction with warfarin/acenocoumarol with described bleeding (raised INR). Renal and biliary excretion of metabolites.',
   E'Cutânea: < 1%. Vaginal: ~1–3% (nitrato de miconazol); concentrações locais terapêuticas por > 24 h por aplicação. Gel oral: absorção mucosa parcial — suficiente para interações sistémicas.',
   E'Cutaneous: < 1%. Vaginal: ~1–3% (miconazole nitrate); therapeutic local concentrations for > 24 h per application. Oral gel: partial mucosal absorption — enough for systemic interactions.',
   E'Não determinável clinicamente na via tópica; na via oral (gel), meia-vida de eliminação ~20–25 h (estimada de dados de INR/interação).',
   E'Not clinically determinable by the topical route; by the oral route (gel), elimination half-life ~20–25 h (estimated from INR/interaction data).',
   E'DailyMed/FDA — MICONAZOLE 3 Combination Pack, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=65c99592-7c11-41fc-8296-aad0a8f39926',
   E'DailyMed/FDA — MICONAZOLE 3 Combination Pack, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=65c99592-7c11-41fc-8296-aad0a8f39926'),
  ('terbinafina',
   E'Alilamina fungicida oral/tópica de primeira escolha nas onicomicoses por dermatófitos; o depósito cutâneo/ungueal prolongado permite tratamentos finitos com altas taxas de cura.',
   E'First-choice oral/topical allylamine fungicide for dermatophyte onychomycoses; the prolonged skin/nail depot allows finite treatments with high cure rates.',
   E'Inibição seletiva da esqualeno epoxidase fúngica (não afeta a isoforma humana em doses terapêuticas): acumulação de esqualeno intracelular (tóxico à membrana) e bloqueio da síntese de ergosterol — fungicida para dermatófitos, fungistático para Candida (exceção do espectro).',
   E'Selective inhibition of fungal squalene epoxidase (human isoform unaffected at therapeutic doses): intracellular squalene accumulation (membrane-toxic) and blocked ergosterol synthesis — fungicidal for dermatophytes, fungistatic for Candida (spectrum exception).',
   E'Biotransformação hepática extensa (CYP2C9, CYP1A2, CYP3A4, CYP2C8) a metabolitos inativos, excretados renais (~70%) e fecais; inibição fraca de CYP2D6 (monitorizar desipramina/tolterodina). Inibidores potentes de CYP2C9 (fluconazol) e indutores (rifampicina) alteram a exposição.',
   E'Extensive hepatic biotransformation (CYP2C9, CYP1A2, CYP3A4, CYP2C8) to inactive metabolites, renally (~70%) and faecally excreted; weak CYP2D6 inhibition (monitor desipramine/tolterodine). Potent CYP2C9 inhibitors (fluconazole) and inducers (rifampicin) alter exposure.',
   E'Absorção oral > 70% (aumenta ~20% com refeição); pico 1–2 h; extensa ligação a proteínas e alta lipofilia com difusão pela queratina (ungueal alcança concentrações terapêuticas em semanas e persiste após o fim do tratamento).',
   E'Oral absorption > 70% (increases ~20% with food); peak 1–2 h; extensive protein binding and high lipophilia with keratin diffusion (nail reaches therapeutic concentrations within weeks and persists after stopping).',
   E'~22 h inicial (fase α) mas meia-vida de eliminação terminal de ~200–400 h pela lenta redistribuição do depósito cutâneo/ungueal — não exige ajuste posológico (fim de tratamento por cura clínica, não por nível sérico).',
   E'~22 h initial (α phase) but terminal elimination half-life of ~200–400 h due to slow redistribution from the skin/nail depot — no dose adjustment needed (stop by clinical cure, not serum level).',
   E'DailyMed/FDA — Terbinafine Hydrochloride Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=584d1fae-0120-49a0-e063-6394a90a36fc',
   E'DailyMed/FDA — Terbinafine Hydrochloride Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=584d1fae-0120-49a0-e063-6394a90a36fc'),
  ('griseofulvina',
   E'Antifúngico oral fungistático clássico para dermatofitoses do cabelo e pele em crianças; hoje frequentemente substituído pela terbinafina, mas continua em uso onde o custo e a disponibilidade prevalecem.',
   E'Classic oral fungistatic antifungal for hair and skin dermatophytoses in children; today often replaced by terbinafine, but still in use where cost and availability prevail.',
   E'Liga-se à tubulina do fungo e perturba a função do fuso mitótico (bloqueio da mitose em metafase) — fungistático: exige a incorporação do fármaco na queratina recém-formada para que a infecção «cresça para fora» com a renovação epitelial/ungueal. Efeito inócuo nos mamíferos nas doses terapêuticas.',
   E'Binds fungal tubulin and disrupts mitotic spindle function (metaphase mitosis arrest) — fungistatic: requires drug incorporation into newly formed keratin so the infection grows out with epithelial/nail renewal. Harmless to mammals at therapeutic doses.',
   E'Oxidação aromática (CYP3A4) e desmetilação a 6-desmetilgriseofulvina (ativo parcial), conjugada e excretada na urina. INDUTOR potente de CYP3A4 e CYP2C9: reduz a eficácia de contraceptivos orais e de warfarina (INR desce) — interações clinicamente importantes.',
   E'Aromatic oxidation (CYP3A4) and demethylation to 6-desmethylgriseofulvin (partially active), conjugated and urinary excreted. POTENT inducer of CYP3A4 and CYP2C9: reduces oral contraceptive and warfarin efficacy (INR falls) — clinically important interactions.',
   E'Absorção muito variável e dependente da formulação (ultramicroinizada ≈ 2× a microssolúvel); aumentada dramaticamente por refeição gordurosa (o esquema pediátrico deve incluir leite/gordura); pico 4 h.',
   E'Very variable, formulation-dependent absorption (ultramicrosized ≈ 2× microsized); dramatically increased by a fatty meal (the paediatric regimen should include milk/fat); peak 4 h.',
   E'9–21 h; alta ligação a queratina em formação prolonga a ação no tecido alvo para além dos níveis plasmáticos.',
   E'9–21 h; high binding to forming keratin prolongs target-tissue action beyond plasma levels.',
   E'DailyMed/FDA — Griseofulvin Tablet (ultramicrosize), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f21314eb-3581-4e06-9fe7-8239cc80ba11',
   E'DailyMed/FDA — Griseofulvin Tablet (ultramicrosize), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f21314eb-3581-4e06-9fe7-8239cc80ba11'),
  ('retinol',
   E'Vitamina A essencial à visão, diferenciação epitelial e imunidade; a suplementação infantil periódica é uma das intervenções de saúde pública de maior custo-eficácia em países endémicos de deficiência.',
   E'Vitamin A essential for vision, epithelial differentiation and immunity; periodic child supplementation is one of the most cost-effective public health interventions in deficiency-endemic countries.',
   E'Após redução a retinal e oxidação a ácido retinoico, ativa recetores nucleares RAR/RXR que regulam a transcrição de genes de diferenciação epitelial, imunidade e metabólicos; na retina, o 11-cis-retinal é o cromóforo da rodopsina (visão crepuscular). Função adjuvante na resposta imune humoral e celular (redução da mortalidade por sarampo).',
   E'After reduction to retinal and oxidation to retinoic acid, activates nuclear RAR/RXR receptors regulating transcription of epithelial differentiation, immune and metabolic genes; in the retina, 11-cis-retinal is the rhodopsin chromophore (twilight vision). Adjuvant role in humoral and cellular immune response (reduced measles mortality).',
   E'Hidrólise dos ésteres na mucosa intestinal; oxidação/redução interconvertida entre retinol/retinal; esterificação hepática (palmitato) para armazenamento nas células estreladas; oxidação final a ácidos retinoicos excretados na bile e urina como glucuronídos. Doses altas: saturação da esterificação e toxicidade pelo retinol livre.',
   E'Ester hydrolysis in the intestinal mucosa; interconverting oxidation/reduction between retinol/retinal; hepatic esterification (palmitate) for storage in stellate cells; final oxidation to retinoic acids excreted in bile and urine as glucuronides. High doses: esterification saturation and toxicity from free retinol.',
   E'Requer bile e gordura dietética (transporte em quilomicrons e via linfática); biodisponibilidade do acetato/palmitato ~70–90% com comida; a forma hidrossolúvel (palmitato miscível) para uso parenteral em má absorção grave. Zinco e proteínas são cofatores do transporte (RBP).',
   E'Requires bile and dietary fat (chylomicron transport and lymphatic route); acetate/palmitate bioavailability ~70–90% with food; water-miscible form (miscible palmitate) for parenteral use in severe malabsorption. Zinc and proteins are transport cofactors (RBP).',
   E'Plasmática curta (horas) mas depósito hepático enorme (90% das reservas, equivalentes a meses/anos) — a deficiência clínica só surge quando as reservas hepáticas se esgotam.',
   E'Short plasma half-life (hours) but enormous hepatic depot (90% of reserves, equivalent to months/years) — clinical deficiency only appears when hepatic stores are exhausted.',
   E'DailyMed/FDA — AQUASOL A PARENTERAL (Retinyl Palmitate), secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1abd66eb-6ac8-4a9e-a609-251e46ea1a27',
   E'DailyMed/FDA — AQUASOL A PARENTERAL (Retinyl Palmitate), section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1abd66eb-6ac8-4a9e-a609-251e46ea1a27'),
  ('tiamina',
   E'Cofator vitaminico do metabolismo energético; a carência instala-se em semanas e manifesta-se no sistema nervoso e coração — a reposição precoce é urgente e altamente eficaz.',
   E'Vitamin cofactor of energy metabolism; deficiency installs within weeks and manifests in the nervous system and heart — early replacement is urgent and highly effective.',
   E'Na forma ativa (pirofosfato de tiamina, TPP) é coenzima de três complexos chaves: piruvato desidrogenase (glicólise → acetil-CoA), α-cetoglutarato desidrogenase (ciclo de Krebs) e transcetolase (via das pentoses); a deficiência bloqueia o metabolismo glucídico neuronal, causando lesão simétrica de estruturas periventriculares (Wernicke) e vasodilatação periférica com insuficiência cardíaca de alto débito (beribéri húmido).',
   E'In its active form (thiamine pyrophosphate, TPP) it is coenzyme of three key complexes: pyruvate dehydrogenase (glycolysis → acetyl-CoA), α-ketoglutarate dehydrogenase (Krebs cycle) and transketolase (pentose pathway); deficiency blocks neuronal glucose metabolism, causing symmetric injury of periventricular structures (Wernicke) and peripheral vasodilation with high-output heart failure (wet beriberi).',
   E'Fosforilação tecidular a TPP (tiamina quinase, gasta ATP); desfosforilação plasmática por ectonucleotidases; excreção renal do excesso (metabolitos piruvato e tiamina livre) — sem toxicidade por acúmulo. A furosemida e o álcool aumentam a excreção renal.',
   E'Tissue phosphorylation to TPP (thiamine kinase, ATP-consuming); plasma dephosphorylation by ectonucleotidases; renal excretion of excess (pyruvate metabolites and free thiamine) — no accumulation toxicity. Furosemide and alcohol increase renal excretion.',
   E'Oral: transportadores saturáveis de alta afinidade (THTR1/2) — absorção ~50% em doses fisiológicas mas < 10% em doses altas únicas (dividir a dose); IM/IV: 100% (reservada a urgência). Biotransformação a TPP no fígado.',
   E'Oral: high-affinity saturable transporters (THTR1/2) — ~50% absorption at physiological doses but < 10% at single high doses (split the dose); IM/IV: 100% (reserved for emergency). Hepatic biotransformation to TPP.',
   E'10–20 dias (TPP nos tecidos); plasmática de 1–2 h por IV — a eficácia clínica depende da reposição das reservas enzimáticas, não do nível sérico.',
   E'10–20 days (tissue TPP); plasma 1–2 h after IV — clinical efficacy depends on enzyme store replenishment, not serum level.',
   E'DailyMed/FDA — THIAMINE HYDROCHLORIDE Injection, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06446e9a-0e85-0623-e063-6294a90ac403',
   E'DailyMed/FDA — THIAMINE HYDROCHLORIDE Injection, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=06446e9a-0e85-0623-e063-6294a90ac403'),
  ('dapsona',
   E'Sulfona bacteriostática pedra angular da lepra; a meia-vida longa e o preço baixo permitem regimes MDT simples da OMS. O uso exige triagem de G6PD e vigilância de reações de hipersensibilidade.',
   E'Bacteriostatic sulfone cornerstone of leprosy treatment; the long half-life and low price allow simple WHO MDT regimens. Use requires G6PD screening and hypersensitivity reaction surveillance.',
   E'Análogo estrutural do PABA: inibe competitivamente a dihidropteroato sintase de Mycobacterium leprae e de protozoários (com pirimetamina), bloqueando a síntese de dihidrofolato → dTHF → purinas e timina — efeito bacteriostático dependente da capacidade sintética do microrganismo. Ação antileprótica complementada por inibição da mieloperoxidase neutrofílica (efeito anti-inflamatório na dermite herpetiforme).',
   E'Structural PABA analogue: competitively inhibits Mycobacterium leprae and protozoal (with pyrimethamine) dihydropteroate synthase, blocking dihydrofolate → dTHF → purines and thymine synthesis — bacteriostatic effect dependent on the microorganism''s synthetic capacity. Antileprotic action complemented by neutrophil myeloperoxidase inhibition (anti-inflammatory effect in dermatitis herpetiformis).',
   E'N-acetilação (NAT2 — acetiladores rápidos/lentos, sem relevância clínica de dose) e N-hidroxilação (CYP2C9/3A4) a hidroxilaminas — responsáveis pela metemoglobinemia e hemólise; conjugação glucuronídica e excreção renal de metabolitos. Circulação enterohepática relevante.',
   E'N-acetylation (NAT2 — fast/slow acetylators, no clinical dose relevance) and N-hydroxylation (CYP2C9/3A4) to hydroxylamines — responsible for methaemoglobinaemia and haemolysis; glucuronide conjugation and renal excretion of metabolites. Relevant enterohepatic circulation.',
   E'Absorção oral quase completa (> 90%), pico 2–8 h; distribuição ampla com concentração elevada na pele, músculos, fígado e rins; liga-se parcialmente às proteínas. Alimentos não alteram significativamente a extensão.',
   E'Almost complete oral absorption (> 90%), peak 2–8 h; wide distribution with high concentrations in skin, muscle, liver and kidneys; partial protein binding. Food does not significantly change extent.',
   E'20–30 h — permite dose única diária; a circulação enterohepática e a alta lipofilia prolongam a exposição. Neonatos e insuficiência renal: meia-vida mais longa.',
   E'20–30 h — allows once-daily dosing; enterohepatic circulation and high lipophilia prolong exposure. Neonates and renal impairment: longer half-life.',
   E'DailyMed/FDA — Dapsone Tablet, secção 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=839d7440-ba0e-4c56-b648-d374b155cf03',
   E'DailyMed/FDA — Dapsone Tablet, section 12 Clinical Pharmacology: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=839d7440-ba0e-4c56-b648-d374b155cf03')
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
       metabolism_pt, metabolism_en, absorption_pt, absorption_en,
       half_life_pt, half_life_en, source_pt, source_en)
ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
