-- =====================================================================
-- 263 — Lote 2 LNME (4/6): farmacologia em public.drug_pharmacology
-- ---------------------------------------------------------------------
-- 25 fármacos (Lote 2 completo). Conteúdo autoral PT/EN ancorado nos
-- rótulos DailyMed (setIDs validados) e Prontuário Terapêutico INFARMED.
-- Padrão 7.6: JOIN (VALUES) ON d.slug = v.slug + ON CONFLICT DO NOTHING.
-- Idempotente. Companheiras: 260 (drugs), 261/262 (perfis).
-- =====================================================================

INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en, absorption_pt, absorption_en, half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id, v.pharmacodynamics_pt, v.pharmacodynamics_en, v.mechanism_pt, v.mechanism_en,
       v.metabolism_pt, v.metabolism_en, v.absorption_pt, v.absorption_en,
       v.half_life_pt, v.half_life_en, v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('amoxicilina-acido-clavulanico',
   E'Bactericida por inibição da síntese da parede celular; o clavulanato alarga o espetro aos produtores de beta-lactamase.',
   E'Bactericidal through cell wall synthesis inhibition; clavulanate extends the spectrum to beta-lactamase producers.',
   E'A amoxicilina liga as PBPs (proteínas de ligação à penicilina) e impede a reticulação do peptidoglicano; o clavulanato inibe irreversivelmente as beta-lactamases bacterianas.',
   E'Amoxicillin binds PBPs (penicillin-binding proteins) preventing peptidoglycan cross-linking; clavulanate irreversibly inhibits bacterial beta-lactamases.',
   E'Hidrólise hepática parcial; excreção predominantemente renal (≥ 60% inalterada na urina). Ajustar na insuficiência renal.',
   E'Partial hepatic hydrolysis; predominantly renal excretion (≥ 60% unchanged in urine). Adjust in renal failure.',
   E'Boa absorção oral (75–90%), reduzida por alimento mas sem impacto clínico relevante na dose total.',
   E'Good oral absorption (75–90%), reduced by food but without clinically relevant impact on total dose.',
   E'Amoxicilina ~ 1–1,5 h; clavulanato ~ 1 h (reduzidos na insuficiência renal).',
   E'Amoxicillin ~ 1–1.5 h; clavulanate ~ 1 h (reduced in renal failure).',
   E'DailyMed — Amoxicillin and Clavulanate Potassium Tablet: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1bda03a2-6c7d-4c9e-b98a-e5e01bebb3b1',
   E'DailyMed — Amoxicillin and Clavulanate Potassium Tablet: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1bda03a2-6c7d-4c9e-b98a-e5e01bebb3b1'),

  ('tetracaina',
   E'Bloqueio reversível da condução nervosa sensorial (e motora em doses altas) com início em 1–5 min e duração 30–60 min tópica.',
   E'Reversible blockade of sensory nerve conduction (and motor at high doses) with onset in 1–5 min and 30–60 min topical duration.',
   E'Bloqueia os canais de sódio voltagem-dependentes do axónio, impedindo a despolarização e a propagação do potencial de ação.',
   E'Blocks voltage-gated sodium channels in the axon, preventing depolarisation and action potential propagation.',
   E'Hidrólise por pseudocolinesterase plasmática a PABA e dietilaminoetanol; metabolismo hepático mínimo.',
   E'Hydrolysis by plasma pseudocholinesterase to PABA and diethylaminoethanol; minimal hepatic metabolism.',
   E'Tópica: absorção variável conforme mucosa e vasoconstrição; absorção rápida em mucosa inflamada.',
   E'Topical: variable absorption depending on mucosa and vasoconstriction; rapid absorption on inflamed mucosa.',
   E'~ 6–8 h (éster; limitada pela rápida hidrólise plasmática).',
   E'~ 6–8 h (ester; limited by rapid plasma hydrolysis).',
   E'DailyMed — Tetracaine Hydrochloride Solution: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=01fba5f8-a60a-444c-9abd-299540b8815a',
   E'DailyMed — Tetracaine Hydrochloride Solution: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=01fba5f8-a60a-444c-9abd-299540b8815a'),

  ('bicarbonato-sodio',
   E'Alcalinização do plasma e da urina; correção da acidose metabólica com elevação do pH e do bicarbonato sérico.',
   E'Plasma and urine alkalinisation; correction of metabolic acidosis with raised pH and serum bicarbonate.',
   E'Tampona H+ em CO2 e H2O via anidrase carbónica; o CO2 é eliminado pulmonarmente (ventilação insuficiente → alcalose intracelular paradoxal).',
   E'Buffers H+ into CO2 and H2O via carbonic anhydrase; CO2 is eliminated by the lungs (insufficient ventilation → paradoxical intracellular acidosis).',
   E'Não sofre metabolismo hepático; excretado renalmente como bicarbonato.',
   E'No hepatic metabolism; renally excreted as bicarbonate.',
   E'Oral: absorção intestinal completa; IV: distribuição no volume extracelular.',
   E'Oral: complete intestinal absorption; IV: extracellular volume distribution.',
   E'~ 6–12 h (alcalinização urinária prolongada).',
   E'~ 6–12 h (prolonged urinary alkalinisation).',
   E'DailyMed — Sodium Bicarbonate Tablet (antacid): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=28cdf049-acdb-4098-a5ca-e86257c81954',
   E'DailyMed — Sodium Bicarbonate Tablet (antacid): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=28cdf049-acdb-4098-a5ca-e86257c81954'),

  ('clorexidina',
   E'Antissepsia com efeito residual prolongado (6 h+) na pele; redução logarítmica de flora cutânea residente e transitória.',
   E'Antisepsis with prolonged residual effect (6 h+) on skin; logarithmic reduction of resident and transient skin flora.',
   E'Biguanida catiónica que liga fosfolípidos aniónicos da membrana bacteriana, rompendo-a e extravasando o citoplasma (bactéricida em concentrações altas).',
   E'Cationic biguanide binding anionic phospholipids of the bacterial membrane, disrupting it and leaking cytoplasm (bactericidal at high concentrations).',
   E'Não é metabolizado sistemicamente (uso tópico); absorção sistémica mínima pela pele íntegra.',
   E'Not systemically metabolised (topical use); minimal systemic absorption through intact skin.',
   E'Aplicação tópica: não se aplica (uso externo).',
   E'Topical application: not applicable (external use).',
   E'Não aplicável (uso tópico; persistência local no estrato córneo).',
   E'Not applicable (topical use; local persistence in the stratum corneum).',
   E'DailyMed — Chlorhexidine Gluconate Rinse: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7e3862b9-3786-4cfe-bfad-c992a7038eca',
   E'DailyMed — Chlorhexidine Gluconate Rinse: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7e3862b9-3786-4cfe-bfad-c992a7038eca'),

  ('iodopovidona',
   E'Antissepsia de largo espetro (bactérias, fungos, vírus, esporos) com início em segundos e duração enquanto seco na pele.',
   E'Broad-spectrum antisepsis (bacteria, fungi, viruses, spores) with onset in seconds and duration while dry on skin.',
   E'O iodo livre oxidado nucleoproteínas e enzimas bacterianas (grupos sulfidrilo, hidroxilo e amina), matando microorganismos por desnaturação irreversível.',
   E'Free iodine oxidises bacterial nucleoproteins and enzymes (sulphydryl, hydroxyl and amine groups), killing microorganisms by irreversible denaturation.',
   E'Absorção de iodo pela pele/mucosa lesada; o iodo acumula-se na tiroide (captura ativa) e é excretado na urina.',
   E'Iodine absorption through damaged skin/mucosa; iodine accumulates in the thyroid (active uptake) and is excreted in urine.',
   E'Tópica: absorção sistémica relevante apenas em mucosas extensas, queimaduras ou uso prolongado.',
   E'Topical: relevant systemic absorption only on extensive mucosa, burns or prolonged use.',
   E'~ 2 h (iopovidona cutânea); iodo ~ 6–8 h.',
   E'~ 2 h (cutaneous povidone); iodine ~ 6–8 h.',
   E'DailyMed — Povidone Iodine: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76b15f6a-51d6-45ec-b6cb-8b10a08ed32a',
   E'DailyMed — Povidone Iodine: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76b15f6a-51d6-45ec-b6cb-8b10a08ed32a'),

  ('sulfato-zinco',
   E'Correção da deficiência de zinco; redução da duração da diarreia infantil e melhor cicatrização.',
   E'Correction of zinc deficiency; reduced duration of childhood diarrhoea and better wound healing.',
   E'Cofactor de metaloenzimas (polimerases, superóxido dismutase, carboxipeptidases); modula imunidade inata e adaptação dos enterócitos na diarreia.',
   E'Cofactor of metalloenzymes (polymerases, superoxide dismutase, carboxypeptidases); modulates innate immunity and enterocyte adaptation in diarrhoea.',
   E'Excreção predominantemente fecal (não absorvido + secreção pancreática); parte renal (24 mg/dia).',
   E'Predominantly faecal excretion (unabsorbed + pancreatic secretion); partly renal (24 mg/day).',
   E'Absorção duodenal/jejunal 20–30%; inibida por fitatos, ferro, cálcio e tetraciclinas.',
   E'Duodenal/jejunal absorption 20–30%; inhibited by phytates, iron, calcium and tetracyclines.',
   E'~ 12 h (dependente da concentração plasmática e das reservas).',
   E'~ 12 h (dependent on plasma concentration and stores).',
   E'DailyMed — Zinc Sulfate Injection [Apotex]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9cf2dab-6ec8-e099-464a-af46a3601971',
   E'DailyMed — Zinc Sulfate Injection [Apotex]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9cf2dab-6ec8-e099-464a-af46a3601971'),

  ('acido-ascorbico',
   E'Correção do défice de vitamina C; melhora da absorção de ferro e da cicatrização.',
   E'Correction of vitamin C deficiency; improved iron absorption and wound healing.',
   E'Co-factor de dioxygenases (prolil e lisil hidroxilases do colagénio); redutor de Fe3+ a Fe2+ no duodeno; antioxidante hidrossolúvel (neutraliza radicais livres).',
   E'Cofactor of dioxygenases (collagen prolyl and lysyl hydroxylases); reduces Fe3+ to Fe2+ in the duodenum; water-soluble antioxidant (neutralises free radicals).',
   E'Metabolismo hepático parcial a oxalato (via desidroascórbico); excreção renal dose-dependente (reabsorção saturável).',
   E'Partial hepatic metabolism to oxalate (via dehydroascorbic acid); dose-dependent renal excretion (saturable reabsorption).',
   E'Absorção intestinal ativa (SVCT1) com saturação em doses > 200 mg; biodisponibilidade 70–90%.',
   E'Active intestinal absorption (SVCT1) with saturation at doses > 200 mg; bioavailability 70–90%.',
   E'~ 1,5–2,5 h (mais curto em doses altas por excreção saturada).',
   E'~ 1.5–2.5 h (shorter at high doses from saturated excretion).',
   E'DailyMed — Ascor L 500 (Ascorbic Acid Injection): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2b71bd05-2891-34f2-e054-00144ff8d46c',
   E'DailyMed — Ascor L 500 (Ascorbic Acid Injection): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2b71bd05-2891-34f2-e054-00144ff8d46c'),

  ('acido-folico',
   E'Correção da anemia macrocítica e prevenção de defeitos do tubo neural; redução da homocisteína.',
   E'Correction of macrocytic anaemia and prevention of neural tube defects; homocysteine reduction.',
   E'Reduzido a tetrahidrofolato (THF) e poliglutamado intracelularmente; THF doa unidades de carbono para a síntese de purinas e timidilato (dTMP → ADN).',
   E'Reduced to tetrahydrofolate (THF) and intracellularly polyglutamated; THF donates one-carbon units for purine and thymidylate synthesis (dTMP → DNA).',
   E'Hidrólise hepática a THF; excreção renal (folato livre e metabólitos).',
   E'Hepatic hydrolysis to THF; renal excretion (free folate and metabolites).',
   E'Absorção duodenal por transportador PCFT; biodisponibilidade ~ 85% oral, maior que o folato alimentar.',
   E'Duodenal absorption via PCFT transporter; oral bioavailability ~ 85%, higher than food folate.',
   E'~ 3 h (distribuição em pool de folato); efeito hematológico visível em 5–7 dias.',
   E'~ 3 h (folate pool distribution); haematological effect visible in 5–7 days.',
   E'EMC-UK — Folic Acid Tablets: https://www.medicines.org.uk/emc/product/4095',
   E'EMC-UK — Folic Acid Tablets: https://www.medicines.org.uk/emc/product/4095'),

  ('sulfato-ferroso',
   E'Correção da anemia ferropénica; reticulocitose em 7–10 dias e normalização da hemoglobina em 6–8 semanas.',
   E'Correction of iron-deficiency anaemia; reticulocytosis in 7–10 days and haemoglobin normalisation in 6–8 weeks.',
   E'O Fe2+ entra no enterócito via DMT1, é armazenado como ferritina ou exporta-se via ferroportina (com hepcidina a regular); incorporado na protoporfirina IX para formar heme.',
   E'Fe2+ enters the enterocyte via DMT1, is stored as ferritin or exported via ferroportin (hepcidin-regulated); incorporated into protoporphyrin IX to form heme.',
   E'Não tem metabolismo hepático; o ferro é reciclado por macrofagos e armazenado em ferritina/hemossiderina; perdas apenas por hemorragia e descamação.',
   E'No hepatic metabolism; iron is recycled by macrophages and stored in ferritin/haemosiderin; losses only through bleeding and desquamation.',
   E'Absorção duodenal regulada por hepcidina; 10–15% em estado normal, até 30% na deficiência; vitamina C melhora, fitatos/taninos/antiácidos reduzem.',
   E'Duodenal absorption regulated by hepcidin; 10–15% in normal state, up to 30% in deficiency; vitamin C improves, phytates/tannins/antacids reduce.',
   E'~ 6 h (oral); a utilização medular dura semanas.',
   E'~ 6 h (oral); marrow utilisation takes weeks.',
   E'DailyMed — Ferrous Sulfate 325 mg Tablet: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5599f519-766c-4f34-84cf-d314d0a550aa',
   E'DailyMed — Ferrous Sulfate 325 mg Tablet: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5599f519-766c-4f34-84cf-d314d0a550aa'),

  ('vitamina-d',
   E'Elevação do 25-OH-D sérico; melhora da absorção de cálcio e da mineralização óssea.',
   E'Raised serum 25-OH-D; improved calcium absorption and bone mineralisation.',
   E'Hidroxilação hepática (CYP2R1) a 25-OH-D (forma armazenada) e renal (CYP27B1) a 1,25-(OH)2-D ativo; o calcitriol liga o recetor VDR e regula genes de absorção de cálcio (TRPV6, calbindina).',
   E'Hepatic hydroxylation (CYP2R1) to 25-OH-D (stored form) and renal (CYP27B1) to active 1,25-(OH)2-D; calcitriol binds the VDR receptor and regulates calcium absorption genes (TRPV6, calbindin).',
   E'Hidroxilação hepática e renal sequencial; inativação por CYP24A1 (24-hidroxilase); excreção biliar.',
   E'Sequential hepatic and renal hydroxylation; inactivation by CYP24A1 (24-hydroxylase); biliary excretion.',
   E'Absorção intestinal com bile (lipossolúvel); biodisponibilidade 50–80%, melhor com refeição gordurosa.',
   E'Intestinal absorption with bile (fat-soluble); bioavailability 50–80%, better with a fatty meal.',
   E'Colecalciferol ~ 2–3 semanas (depósito adiposo); calcitriol ~ 4–6 h.',
   E'Cholecalciferol ~ 2–3 weeks (adipose storage); calcitriol ~ 4–6 h.',
   E'DailyMed — Cholecalciferol (ver VANTREX como referência de multivitamínico): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3a1f0405-6983-410d-b625-54517a6a235f',
   E'DailyMed — Cholecalciferol (see VANTREX as a multivitamin reference): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3a1f0405-6983-410d-b625-54517a6a235f'),

  ('calcio',
   E'Correção da hipocalcemia; redução da reabsorção óssea e da PTH em dose suplementar; neutralização do HCl gástrico (antiácido).',
   E'Correction of hypocalcaemia; reduced bone resorption and PTH at supplementary doses; gastric HCl neutralisation (antacid).',
   E'O Ca2+ exerce funções estruturais (hidroxiapatita óssea), de sinalização (contração muscular, exocitose, coagulação via fatores IV) e modulação da excitabilidade neuronal.',
   E'Ca2+ exerts structural (bone hydroxyapatite), signalling (muscle contraction, exocytosis, clotting via factor IV) and neuronal excitability modulation functions.',
   E'Não tem metabolismo; excreção renal (99% reabsorvido), fecal e sudorípara; regulação por PTH e vitamina D.',
   E'No metabolism; renal (99% reabsorbed), faecal and sweat excretion; regulated by PTH and vitamin D.',
   E'Carbonato de cálcio: 25–40% de absorção (melhor com refeição e vitamina D); dissolve-se em meio ácido gástrico (reduzido em IPP).',
   E'Calcium carbonate: 25–40% absorption (better with meal and vitamin D); dissolves in acidic gastric medium (reduced on PPIs).',
   E'~ 3–5 h (oral; dependente da dose e da distribuição óssea).',
   E'~ 3–5 h (oral; dose- and bone distribution-dependent).',
   E'DailyMed — Calcium Carbonate (antacid): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=25db68f7-af79-4a43-ac16-469ff08d64b8',
   E'DailyMed — Calcium Carbonate (antacid): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=25db68f7-af79-4a43-ac16-469ff08d64b8'),

  ('noreisterona',
   E'Contracepção com supressão do pico de LH; transformação secretória do endométrio e espessamento do muco cervical.',
   E'Contraception with LH peak suppression; secretory endometrial transformation and cervical mucus thickening.',
   E'Agonista do recetor de progesterona (com atividade androgénica residual): suprime o pico LH por retroalimentação hipotalâmica, mantém o muco cervical hostil e estabiliza o endométrio.',
   E'Progesterone receptor agonist (with residual androgenic activity): suppresses the LH peak through hypothalamic feedback, maintains hostile cervical mucus and stabilises the endometrium.',
   E'Redução hepática (CYP3A4) a metabólitos inativos; excreção renal e biliar.',
   E'Hepatic reduction (CYP3A4) to inactive metabolites; renal and biliary excretion.',
   E'Boa absorção oral (~ 65%); biodisponibilidade reduzida por indutores enzimáticos.',
   E'Good oral absorption (~ 65%); bioavailability reduced by enzyme inducers.',
   E'~ 8 h (noretisterona acetato).',
   E'~ 8 h (norethisterone acetate).',
   E'DailyMed — Nora-BE (Norethindrone) Tablet [Teva]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=426ac898-7745-4645-bf9b-bae319e260e8',
   E'DailyMed — Nora-BE (Norethindrone) Tablet [Teva]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=426ac898-7745-4645-bf9b-bae319e260e8'),

  ('levonorgestrel-etinilestradiol',
   E'Supressão da ovulação (> 99% de eficácia com toma correta); regularização do ciclo.',
   E'Ovulation suppression (> 99% efficacy with correct dosing); cycle regulation.',
   E'O levonorgestrel liga fortemente o recetor de progesterona; o etinilestradiol liga o recetor estrogénico e mantém o endométrio estável e a retroalimentação FSH/LH suprimida.',
   E'Levonorgestrel binds the progesterone receptor strongly; ethinylestradiol binds the oestrogen receptor and keeps the endometrium stable and FSH/LH feedback suppressed.',
   E'Levonorgestrel: CYP3A4 hepático; etinilestradiol: hidroxilação CYP3A4 e sulfatação; ambos excretados renal e biliarmente.',
   E'Levonorgestrel: hepatic CYP3A4; ethinylestradiol: CYP3A4 hydroxylation and sulphation; both renally and biliary excreted.',
   E'Absorção oral rápida e completa; o etinilestradiol sofre primeira passagem significativa (biodisponibilidade ~ 40%).',
   E'Rapid complete oral absorption; ethinylestradiol undergoes significant first-pass (bioavailability ~ 40%).',
   E'Levonorgestrel ~ 30 h; etinilestradiol ~ 13–27 h.',
   E'Levonorgestrel ~ 30 h; ethinylestradiol ~ 13–27 h.',
   E'DailyMed — Camrese (Levonorgestrel/Ethinyl Estradiol): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e198d28-4986-4b93-833f-17c7ed4ce13e',
   E'DailyMed — Camrese (Levonorgestrel/Ethinyl Estradiol): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0e198d28-4986-4b93-833f-17c7ed4ce13e'),

  ('desmopressina',
   E'Redução da diurese (↑ reabsorção de água); ↑ fator VIII e von Willebrand (2–4×) em 30–90 min.',
   E'Reduced diuresis (↑ water reabsorption); ↑ factor VIII and von Willebrand (2–4×) within 30–90 min.',
   E'Agonista seletivo V2 renal (pouca atividade V1 pressórica): ativa adenilciclase e aquaporina-2 no túbulo coletor; endotélio libera fator de von Willebrand/fator VIII.',
   E'Selective renal V2 agonist (little pressor V1 activity): activates adenyl cyclase and aquaporin-2 in the collecting tubule; endothelium releases von Willebrand factor/factor VIII.',
   E'Degradação por peptidases teciduais (mais lenta que na vasopressina); excreção renal.',
   E'Tissue peptidase degradation (slower than vasopressin); renal excretion.',
   E'Intranasal: 10–20%; oral (sublingual): 0,1%; IV: 100%.',
   E'Intranasal: 10–20%; oral (sublingual): 0.1%; IV: 100%.',
   E'IV: 1,5–3 h; oral: 3–4 h; intranasal: 3–4 h (efeito 8–12 h).',
   E'IV: 1.5–3 h; oral: 3–4 h; intranasal: 3–4 h (effect 8–12 h).',
   E'DailyMed — Desmopressin Acetate: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abe23504-ea98-4ed9-9a9a-6db9eaa35251',
   E'DailyMed — Desmopressin Acetate: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=abe23504-ea98-4ed9-9a9a-6db9eaa35251'),

  ('neostigmina',
   E'Reversão do bloqueio neuromuscular não despolarizante em 10–20 min; ↑ peristalse e tónus vesical.',
   E'Reversal of non-depolarising neuromuscular blockade within 10–20 min; ↑ peristalsis and bladder tone.',
   E'Inibição reversível da acetilcolinesterase: ↑ acetilcolina na fenda sináptica, deslocando competitivamente o bloqueante do recetor nicotínico (ação indireta agonista).',
   E'Reversible acetylcholinesterase inhibition: ↑ acetylcholine in the synaptic cleft, competitively displacing the blocker from the nicotinic receptor (indirect agonist action).',
   E'Hidrólise hepática por esterases; excreção renal predominante (50% inalterada).',
   E'Hepatic esterase hydrolysis; predominant renal excretion (50% unchanged).',
   E'IV: ação imediata; IM: pico em 20–30 min; oral: má absorção (1–2%).',
   E'IV: immediate action; IM: peak in 20–30 min; oral: poor absorption (1–2%).',
   E'~ 1–2 h (IV).',
   E'~ 1–2 h (IV).',
   E'DailyMed — Neostigmine Methylsulfate Injection [Gland Pharma]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4eab6184-1771-4c15-a127-4eb3e47affc2',
   E'DailyMed — Neostigmine Methylsulfate Injection [Gland Pharma]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4eab6184-1771-4c15-a127-4eb3e47affc2'),

  ('vecuronio',
   E'Paralisia muscular flácida completa (intubação em 2–3 min; duração 25–40 min).',
   E'Complete flaccid muscle paralysis (intubation in 2–3 min; duration 25–40 min).',
   E'Antagonista competitivo do recetor nicotínico nicotínico da placa motora; reversível por neostigmine (↑ acetilcolina) ou sugamadex (encapsulação química).',
   E'Competitive antagonist at the motor end-plate nicotinic receptor; reversible by neostigmine (↑ acetylcholine) or sugammadex (chemical encapsulation).',
   E'Desacetilação hepática a 3-hidroxivecurônio (metabolito ativo ~ 50% da potência); excreção biliar e renal.',
   E'Hepatic deacetylation to 3-hydroxyvecuronium (active metabolite ~ 50% potency); biliary and renal excretion.',
   E'IV exclusivo; não aplicável por via oral.',
   E'IV exclusive; not applicable orally.',
   E'~ 60–90 min (prolongado em doença hepática/renal avançada).',
   E'~ 60–90 min (prolonged in advanced liver/kidney disease).',
   E'DailyMed — Vecuronium Bromide Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=582c7f44-b614-18df-e063-6294a90a74b6',
   E'DailyMed — Vecuronium Bromide Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=582c7f44-b614-18df-e063-6294a90a74b6'),

  ('suxametonio',
   E'Fasciculações (10–30 s) seguidas de paralisia flácida (45–60 s após dose; duração 5–10 min).',
   E'Fasciculations (10–30 s) followed by flaccid paralysis (45–60 s after dose; duration 5–10 min).',
   E'Agonista despolarizante do recetor nicotínico: mantém o recetor despolarizado e insensível (fase I); não reversível por neostigmina (que o agravaria).',
   E'Nicotinic receptor depolarising agonist: keeps the receptor depolarised and insensitive (phase I); not reversible by neostigmine (which would worsen it).',
   E'Hidrólise rápida pela butirilcolinesterase plasmática (pseudocolinesterase) a succinilmonocolina e colina; excreção renal.',
   E'Rapid hydrolysis by plasma butyrylcholinesterase (pseudocholinesterase) to succinylmonocholine and choline; renal excretion.',
   E'IV exclusivo; ação em < 1 min após perfusão braquial.',
   E'IV exclusive; action < 1 min after brachial infusion.',
   E'~ 3–6 min (deficiência de pseudocolinesterase: até 4–8 h).',
   E'~ 3–6 min (pseudocholinesterase deficiency: up to 4–8 h).',
   E'DailyMed — Succinylcholine Chloride Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=efe5a242-5ba0-4b14-844c-206a79850d81',
   E'DailyMed — Succinylcholine Chloride Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=efe5a242-5ba0-4b14-844c-206a79850d81'),

  ('bupivacaina',
   E'Bloqueio sensorial (e motor em concentração alta) com início em 5–10 min e duração 3–8 h.',
   E'Sensory (and motor at high concentration) block with onset in 5–10 min and 3–8 h duration.',
   E'Bloqueio do canal de sódio voltagem-dependente (preferência pelo estado inativado); dissociação lenta na diástole cardíaca explica a cardiotoxicidade relativa.',
   E'Voltage-gated sodium channel block (preference for the inactivated state); slow dissociation during cardiac diastole explains relative cardiotoxicity.',
   E'Hidroxilação hepática (CYP3A4) a metabólitos inativos; excreção renal.',
   E'Hepatic hydroxylation (CYP3A4) to inactive metabolites; renal excretion.',
   E'Infiltração local: absorção dependente da vascularização; adrenalina reduz o pico plasmático em 30–50%.',
   E'Local infiltration: absorption dependent on vascularity; adrenaline reduces plasma peak by 30–50%.',
   E'~ 3,5 h (adulto; neonato até 8–12 h).',
   E'~ 3.5 h (adult; neonate up to 8–12 h).',
   E'DailyMed — Bupivacaine Hydrochloride (via rótulo combinado): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76b15f6a-51d6-45ec-b6cb-8b10a08ed32a',
   E'DailyMed — Bupivacaine Hydrochloride (via combined label): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76b15f6a-51d6-45ec-b6cb-8b10a08ed32a'),

  ('propofol',
   E'Sedação/anestesia em ~ 30 s (um braço-giro); despertar 5–15 min após suspensão da perfusão.',
   E'Sedation/anaesthesia in ~ 30 s (one arm-brain time); awakening 5–15 min after stopping infusion.',
   E'Modulador positivo do recetor GABA-A (potencia a corrente de Cl−) e inibidor leve dos canais de sódio; suprime a resposta de stress e a memória.',
   E'GABA-A receptor positive modulator (potentiates Cl− current) and mild sodium channel inhibitor; suppresses stress response and memory.',
   E'Clearance hepático elevado (CYP2B6, CYP2C9, glucuronidação) que excede o fluxo hepático (clearance extra-hepático pulmonar e renal também descrito).',
   E'High hepatic clearance (CYP2B6, CYP2C9, glucuronidation) exceeding hepatic flow (extrahepatic pulmonary and renal clearance also described).',
   E'IV exclusivo; distribuição em 3 compartimentos com depot adiposo (despertar ainda rápido após perfusão curta, mais lento após longa).',
   E'IV exclusive; 3-compartment distribution with adipose depot (awakening still rapid after short infusion, slower after long).',
   E'~ 30–60 min (vida de eliminação terminal ~ 4–24 h; contexto-sensitive half-time variável).',
   E'~ 30–60 min (terminal elimination half-life ~ 4–24 h; variable context-sensitive half-time).',
   E'DailyMed — Propofol Injection, Emulsion: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ec25932-6c21-4cd5-8f60-80761f2e20a6',
   E'DailyMed — Propofol Injection, Emulsion: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ec25932-6c21-4cd5-8f60-80761f2e20a6'),

  ('efedrina',
   E'↑ tensão arterial, ↑ frequência cardíaca, broncodilatação e midríase; início IV em 1–2 min, duração 30–60 min.',
   E'↑ blood pressure, ↑ heart rate, bronchodilation and mydriasis; IV onset in 1–2 min, duration 30–60 min.',
   E'Ação direta α1/β1/β2 e indireta (libera noradrenalina do axónio via mecanismo de troca); taquifilaxia por depleção de noradrenalina.',
   E'Direct α1/β1/β2 action and indirect (noradrenaline release from the axon via exchange mechanism); tachyphylaxis through noradrenaline depletion.',
   E'Parcialmente metabolizada hepaticamente (N-desmetilação); 70–90% excretada inalterada na urina (mais lenta em urina alcalina).',
   E'Partially hepatically metabolised (N-demethylation); 70–90% excreted unchanged in urine (slower in alkaline urine).',
   E'Oral: boa absorção; IV/IM: ação imediata/5–15 min; atravessa a barreira hematoencefálica (efeito CNS).',
   E'Oral: good absorption; IV/IM: immediate/5–15 min action; crosses the blood-brain barrier (CNS effect).',
   E'~ 3–5 h (oral; mais longo com urina alcalina).',
   E'~ 3–5 h (oral; longer with alkaline urine).',
   E'DailyMed — Ephedrine Sulfate Tablet [CVS]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e338deef-efad-1d82-e053-2995a90a1bf9',
   E'DailyMed — Ephedrine Sulfate Tablet [CVS]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e338deef-efad-1d82-e053-2995a90a1bf9'),

  ('flumazenil',
   E'Reversão da sedação e da depressão respiratória por benzodiazepínicos em 1–2 min; efeito dura 45–90 min.',
   E'Reversal of benzodiazepine sedation and respiratory depression in 1–2 min; effect lasts 45–90 min.',
   E'Antagonista competitivo do sítio benzodiazepínico do GABA-A; sem atividade intrínseca significativa (agonista inverso fraco em dose alta).',
   E'Competitive antagonist at the benzodiazepine site of GABA-A; no significant intrinsic activity (weak inverse agonist at high dose).',
   E'Metabolismo hepático extenso (oxidação e glucuronidação) a metabólitos inativos; excreção renal.',
   E'Extensive hepatic metabolism (oxidation and glucuronidation) to inactive metabolites; renal excretion.',
   E'IV: biodisponibilidade 100%; oral: ~ 20% (primeira passagem).',
   E'IV: 100% bioavailability; oral: ~ 20% (first pass).',
   E'~ 45–90 min (vida curta; risco de re-sedação com benzodiazepínicos longos).',
   E'~ 45–90 min (short half-life; re-sedation risk with long benzodiazepines).',
   E'DailyMed — Flumazenil Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=56452ba8-521d-1f84-e063-6294a90af6fc',
   E'DailyMed — Flumazenil Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=56452ba8-521d-1f84-e063-6294a90af6fc'),

  ('clonidina',
   E'Redução da tensão arterial e da frequência cardíaca; sedação e analgesia espinhal.',
   E'Reduced blood pressure and heart rate; sedation and spinal analgesia.',
   E'Agonista alfa-2A central: reduz a descarga simpática do centro vasomotor bulbare; na medula, inibe a liberação de substância P e glutamato (analgesia).',
   E'Central alpha-2A agonist: reduces sympathetic outflow from the bulbar vasomotor centre; in the spinal cord, inhibits substance P and glutamate release (analgesia).',
   E'Hidroxilação hepática (CYP2D6) e conjugação; ~ 65% excretado inalterado na urina.',
   E'Hepatic hydroxylation (CYP2D6) and conjugation; ~ 65% excreted unchanged in urine.',
   E'Oral: ~ 75–95% de biodisponibilidade; parche transdérmico: liberação de 7 dias.',
   E'Oral: ~ 75–95% bioavailability; transdermal patch: 7-day release.',
   E'~ 12–16 h (parche: ~ 20 h).',
   E'~ 12–16 h (patch: ~ 20 h).',
   E'DailyMed — Clonidine Hydrochloride Tablet [Alembic]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d90b2ca4-7753-4012-a1b2-fb92bdf0ebb6',
   E'DailyMed — Clonidine Hydrochloride Tablet [Alembic]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d90b2ca4-7753-4012-a1b2-fb92bdf0ebb6'),

  ('nitroprussiato',
   E'Redução imediata da pré- e pós-carga; início em segundos, duração 1–2 min (titulação contínua).',
   E'Immediate preload and afterload reduction; onset in seconds, 1–2 min duration (continuous titration).',
   E'Doador de NO não enzimático: o NO liberado ativa a guanilato ciclase → ↑ GMP cíclico → relaxamento da musculatura lisa arterial e venosa.',
   E'Non-enzymatic NO donor: released NO activates guanylate cyclase → ↑ cyclic GMP → arterial and venous smooth muscle relaxation.',
   E'Reação com hemoglobina → metemoglobina + cianeto; o cianeto é convertido a tiocianato pela rodanase hepática (com tiosulfato como cofactor); excreção renal do tiocianato.',
   E'Reaction with haemoglobin → methaemoglobin + cyanide; cyanide is converted to thiocyanate by hepatic rhodanese (with thiosulfate cofactor); renal thiocyanate excretion.',
   E'IV exclusivo; ação imediata.',
   E'IV exclusive; immediate action.',
   E'~ 2–4 min (nitroprussiato); tiocianato ~ 3–4 dias (insuficiência renal: acumulação).',
   E'~ 2–4 min (nitroprusside); thiocyanate ~ 3–4 days (renal failure: accumulation).',
   E'DailyMed — Sodium Nitroprusside Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5a599880-c133-44ef-a9f2-bd1b681563be',
   E'DailyMed — Sodium Nitroprusside Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5a599880-c133-44ef-a9f2-bd1b681563be'),

  ('heparina',
   E'Anticoagulação imediata (↑ TTPa dose-dependente); prevenção e tratamento de tromboses arteriais e venosas.',
   E'Immediate anticoagulation (dose-dependent aPTT rise); prevention and treatment of arterial and venous thromboses.',
   E'Ativa a antitrombina III por ligação a sequências pentassacáridas específicas: inibição de trombina (IIa), Xa, IXa, XIa e XIIa; efeito limitado a fibrinas dependentes de trombina.',
   E'Activates antithrombin III by binding specific pentasaccharide sequences: inhibition of thrombin (IIa), Xa, IXa, XIa and XIIa; effect limited to thrombin-dependent fibrins.',
   E'Não tem metabolismo hepático clássico; degradação por desulfatação e despolimerização reticuloendotelial; excreção renal.',
   E'No classic hepatic metabolism; degradation by reticuloendothelial desulphation and depolymerisation; renal excretion.',
   E'IV/SC exclusivo; biodisponibilidade SC dose-dependente (20–60% em dose profilática; > 90% em dose terapêutica).',
   E'IV/SC exclusive; dose-dependent SC bioavailability (20–60% at prophylactic dose; > 90% at therapeutic dose).',
   E'~ 60–90 min IV (dose-dependente; mais longo em dose alta).',
   E'~ 60–90 min IV (dose-dependent; longer at high dose).',
   E'DailyMed — Heparin Sodium Injection [Gland Pharma]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=301b19bc-21c2-4a35-9d29-569b08d855c4',
   E'DailyMed — Heparin Sodium Injection [Gland Pharma]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=301b19bc-21c2-4a35-9d29-569b08d855c4'),

  ('dopamina',
   E'↑ contractilidade e frequência cardíaca (β1) e vasoconstrição periférica (α) dose-dependente.',
   E'↑ contractility and heart rate (β1) and dose-dependent peripheral vasoconstriction (α).',
   E'Agonista direto D1, β1 e α1, e indireto (libera noradrenalina dos terminais); efeito renal vasodilatador em dose baixa via D1.',
   E'Direct D1, β1 and α1 agonist, and indirect (noradrenaline release from terminals); renal vasodilator effect at low dose via D1.',
   E'Metabolização rápida por MAO e COMT (plasma, fígado e rim); vida plasmática < 2 min → perfusão contínua obrigatória.',
   E'Rapid metabolism by MAO and COMT (plasma, liver, kidney); plasma half-life < 2 min → continuous infusion mandatory.',
   E'IV exclusivo; não atravessa significativamente a barreira hematoencefálica.',
   E'IV exclusive; does not significantly cross the blood-brain barrier.',
   E'~ 2 min (IV).',
   E'~ 2 min (IV).',
   E'DailyMed — Dopamine Hydrochloride Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f306ad2-3606-4525-5a8a-ce78f426c1a2',
   E'DailyMed — Dopamine Hydrochloride Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1f306ad2-3606-4525-5a8a-ce78f426c1a2'),

  ('dobutamina',
   E'↑ contractilidade cardíaca com ↑ leve da frequência; redução da resistência vascular sistémica (β2).',
   E'↑ cardiac contractility with mild heart rate rise; reduced systemic vascular resistance (β2).',
   E'Agonista β1 predominante (racémico: (-)-isómero α1-agonista, (+)-isómero β1/β2-agonista) — efeito líquido inotrópico com vasodilatação leve.',
   E'Predominantly β1 agonist (racemic: (-)-isomer α1 agonist, (+)-isomer β1/β2 agonist) — net inotropic effect with mild vasodilation.',
   E'Metabolização por COMT e conjugação hepática; vida plasmática curta → perfusão contínua.',
   E'Metabolised by COMT and hepatic conjugation; short plasma half-life → continuous infusion.',
   E'IV exclusivo; início em 1–2 min; pico em 10 min.',
   E'IV exclusive; onset in 1–2 min; peak at 10 min.',
   E'~ 2 min (IV).',
   E'~ 2 min (IV).',
   E'DailyMed — Dobutamine in Dextrose Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=559367ef-5c20-99ea-e063-6294a90a4ff2',
   E'DailyMed — Dobutamine in Dextrose Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=559367ef-5c20-99ea-e063-6294a90a4ff2'),

  ('noradrenalina',
   E'Vasoconstrição sistémica intensa com inotropismo moderado; ↑ tensão arterial sistólica e diastólica.',
   E'Intense systemic vasoconstriction with moderate inotropy; ↑ systolic and diastolic blood pressure.',
   E'Agonista α1 predominante (vasoconstrição) com β1 moderado (inotropismo) e β2 mínimo (sem broncodilatação).',
   E'Predominant α1 agonist (vasoconstriction) with moderate β1 (inotropy) and minimal β2 (no bronchodilation).',
   E'Metabolização por MAO e COMT (vida < 2 min); excreção renal de metabólitos (VMA, normetanefrina).',
   E'Metabolised by MAO and COMT (half-life < 2 min); renal excretion of metabolites (VMA, normetanephrine).',
   E'IV exclusivo (perfusão contínua); não atravessa significativamente a barreira hematoencefálica.',
   E'IV exclusive (continuous infusion); does not significantly cross the blood-brain barrier.',
   E'~ 2 min (IV).',
   E'~ 2 min (IV).',
   E'DailyMed — Norepinephrine Bitartrate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=109aa5e6-4e42-4131-97b0-f24d3a4cb4e8',
   E'DailyMed — Norepinephrine Bitartrate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=109aa5e6-4e42-4131-97b0-f24d3a4cb4e8'),

  ('aminofilina',
   E'Broncodilatação em 30–60 min IV; ↑ força diafragmática; diurese leve.',
   E'Bronchodilation within 30–60 min IV; ↑ diaphragmatic strength; mild diuresis.',
   E'Inibição não seletiva das fosfodiesterases (↑ AMPc e GMPc → relaxamento da musculatura brônquica); antagonismo do recetor de adenosina (efeito pró-convulsivo e diurético).',
   E'Non-selective phosphodiesterase inhibition (↑ cAMP and cGMP → bronchial smooth muscle relaxation); adenosine receptor antagonism (pro-convulsant and diuretic effect).',
   E'Metabolismo hepático extenso (CYP1A2 → 1-metilxantina, CYP3A4, CYP2E1); ~ 10% excretado inalterado na urina.',
   E'Extensive hepatic metabolism (CYP1A2 → 1-methylxanthine, CYP3A4, CYP2E1); ~ 10% excreted unchanged in urine.',
   E'Oral: boa absorção (~ 90%); IV: biodisponibilidade 100%; forma IV preferida em urgência.',
   E'Oral: good absorption (~ 90%); IV: 100% bioavailability; IV form preferred in emergency.',
   E'~ 6–8 h (adulto não fumador); ~ 4–5 h (fumador); prolongado em neonatos, idosos e insuficiência hepática/cardíaca.',
   E'~ 6–8 h (non-smoking adult); ~ 4–5 h (smoker); prolonged in neonates, elderly and liver/heart failure.',
   E'DailyMed — Aminophylline Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=819207a2-0c37-b275-e053-2a91aa0afb36',
   E'DailyMed — Aminophylline Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=819207a2-0c37-b275-e053-2a91aa0afb36'),

  ('metilprednisolona',
   E'Anti-inflamação potente (5× hidrocortisona); supressão da resposta imune celular e da produção de citocinas.',
   E'Potent anti-inflammatory action (5× hydrocortisone); suppression of cellular immune response and cytokine production.',
   E'Liga o recetor intracelular de glicocorticoides → translocação nuclear → altera transcrição: ↓ IL-1, IL-6, TNF-α, ↑ lipocortina-1 (inibe PLA2 → ↓ prostaglandinas/leucotrienos), ↑ IκB (inibe NF-κB).',
   E'Binds the intracellular glucocorticoid receptor → nuclear translocation → alters transcription: ↓ IL-1, IL-6, TNF-α, ↑ lipocortin-1 (inhibits PLA2 → ↓ prostaglandins/leukotrienes), ↑ IκB (inhibits NF-κB).',
   E'Metabolismo hepático (CYP3A4) a metabólitos inativos; excreção renal; pouca inativação placentária comparado à prednisolona.',
   E'Hepatic metabolism (CYP3A4) to inactive metabolites; renal excretion; little placental inactivation compared with prednisolone.',
   E'Oral: boa absorção (pico 1–2 h); IV (succinato): ação imediata; acetato (Depo-Medrol): depósito intra-articular de 1–3 semanas.',
   E'Oral: good absorption (peak 1–2 h); IV (succinate): immediate action; acetate (Depo-Medrol): intra-articular depot 1–3 weeks.',
   E'~ 2–3 h (plasmática); efeito biológico 12–36 h.',
   E'~ 2–3 h (plasma); biological effect 12–36 h.',
   E'DailyMed — Methylprednisolone (via rótulo combinado Physicians EZ Use M-PRED): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76b15f6a-51d6-45ec-b6cb-8b10a08ed32a',
   E'DailyMed — Methylprednisolone (via combined label Physicians EZ Use M-PRED): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=76b15f6a-51d6-45ec-b6cb-8b10a08ed32a')
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
       metabolism_pt, metabolism_en, absorption_pt, absorption_en, half_life_pt, half_life_en,
       source_pt, source_en)
  ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
