-- =====================================================================
-- 265 — Lote 3 LNME (5/6): perfis em public.drug_profiles
-- ---------------------------------------------------------------------
-- 13 fármacos (Lote 3 completo). Conteúdo autoral PT/EN ancorado nos
-- rótulos DailyMed (setIDs validados) e Prontuário Terapêutico INFARMED.
-- Padrão 7.6: JOIN (VALUES) ON d.slug = v.slug + ON CONFLICT DO NOTHING.
-- Idempotente. Companheiras: 264 (drugs), 266 (farmacologia).
-- =====================================================================

INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
   indications_pt, indications_en, side_effects_pt, side_effects_en,
   precautions_pt, precautions_en, source_pt, source_en, status)
SELECT d.id, v.overview_public_pt, v.overview_public_en, v.overview_pro_pt, v.overview_pro_en,
       v.indications_pt, v.indications_en, v.side_effects_pt, v.side_effects_en,
       v.precautions_pt, v.precautions_en, v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('clomifeno',
   E'Clomifeno é um comprimido que estimula a ovulação em mulheres com dificuldade em engravidar porque não ovulam regularmente (síndrome do ovário poliquístico, ciclos irregulares).',
   E'Clomiphene is a tablet that stimulates ovulation in women struggling to conceive because they do not ovulate regularly (polycystic ovary syndrome, irregular cycles).',
   E'SERM (modulador seletivo do recetor de estrogénio): bloqueia recetores estrogénicos hipotalâmicos, levantando a retroalimentação negativa → ↑ FSH/LH → estímulo folicular e ovulação. Anti-estrogénico periférico pode afinar o endométrio e reduzir o muco cervical em ciclos prolongados.',
   E'SERM (selective oestrogen receptor modulator): blocks hypothalamic oestrogen receptors, lifting negative feedback → ↑ FSH/LH → follicular stimulation and ovulation. Peripheral anti-oestrogenic effect can thin the endometrium and reduce cervical mucus in prolonged cycles.',
   E'• Infertilidade por anovulação (SOP, ciclos irregulares)\\n• Oligomenorreia funcional sem outra causa\\n• Verificação da reserva ovárica em protocolos de indução',
   E'• Infertility from anovulation (PCOS, irregular cycles)\\n• Functional oligomenorrhoea without other cause\\n• Ovarian reserve check in induction protocols',
   E'• Ondas de calor e alteração do humor\\n• Distensão abdominal e dor pélvica\\n• Náuseas e cefaleias\\n• Síndrome de hiperestimulação ovárica (dose alta): dor abdominal intensa, inchaço, ganho de peso rápido\\n• Risco de gravidez múltipla (~ 5–10%, sobretudo gémeos)\\n• Perturbações visuais (manchas, fotofobia) — suspender e avaliar\\n• Procure ajuda imediata se houver dor abdominal intensa, inchaço rápido ou visão alterada.',
   E'• Hot flushes and mood change\\n• Abdominal bloating and pelvic pain\\n• Nausea and headaches\\n• Ovarian hyperstimulation syndrome (high dose): intense abdominal pain, bloating, rapid weight gain\\n• Multiple pregnancy risk (~ 5–10%, mostly twins)\\n• Visual disturbances (spots, photophobia) — stop and assess\\n• Seek immediate help if intense abdominal pain, rapid bloating or visual change occurs.',
   E'• Não usar na gravidez (contraindicado) nem em quistos ováricos não avaliados\\n• Uso limitado a 6 ciclos cumulativos (risco de tumor ovárico discutido)\\n• Monitorização folicular (ecografia) recomendada\\n• Em doença hepática, suspender e investigar antes de continuar',
   E'• Do not use in pregnancy (contraindicated) or unassessed ovarian cysts\\n• Limit to 6 cumulative cycles (ovarian tumour risk discussed)\\n• Follicular monitoring (ultrasound) recommended\\n• In liver disease, stop and investigate before continuing',
   E'Rótulo aprovado DailyMed/FDA — Clomiphene Citrate Tablet [Camber]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54f608de-6f14-4120-819e-aeb9350c3070 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012): clomifeno "não deve usar-se na gravidez"',
   E'DailyMed/FDA approved label — Clomiphene Citrate Tablet [Camber]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54f608de-6f14-4120-819e-aeb9350c3070 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012): clomiphene "must not be used in pregnancy"'),

  ('testosterona',
   E'Testosterona injetável é usado quando o corpo não produz testosterona suficiente: puberdade atrasada em rapazes, hipogonadismo do adulto e em certos tipos de cancro da mama em mulheres (uso especializado).',
   E'Injectable testosterone is used when the body does not produce enough testosterone: delayed puberty in boys, adult hypogonadism and certain types of breast cancer in women (specialised use).',
   E'Éster de testosterona de liberação lenta (cipionato) hidrolisado in vivo à testosterona livre. Liga o recetor androgénico intracelular: promove caracteres sexuais masculinos, anabolismo proteico, retroalimentação hipofisária (↓ LH/FSH → ↓ espermatogénese endógena e ↓ estrogénios por aromatização).',
   E'Slow-release testosterone ester (cipionate) hydrolysed in vivo to free testosterone. Binds the intracellular androgen receptor: promotes male sexual characteristics, protein anabolism, pituitary feedback (↓ LH/FSH → ↓ endogenous spermatogenesis and ↓ oestrogens by aromatisation).',
   E'Hidrólise tissular plasmática e hepática do éster; a testosterona livre é metabolizada hepaticamente (androsterona/etiocholanolona) e excretada na urina; inativação oral extensa (primeira passagem) → formas parenterais.',
   E'Plasma and tissue ester hydrolysis; free testosterone is hepatically metabolised (androsterone/etiocholanolone) and excreted in urine; extensive oral inactivation (first pass) → parenteral forms.',
   E'IM profunda: pico plasmático 1–2 dias, duração 2–4 semanas.',
   E'Deep IM: plasma peak 1–2 days, duration 2–4 weeks.',
   E'• Acne e oleosidade da pele\\n• Retenção de líquidos e edemas\\n• Ginecomastia (aromatização periférica)\\n• Atrofia testicular e infertilidade (supressão do eixo)\\n• Alteração do humor, agressividade, apneia do sono\\n• Policitemia (↑ hematócrito)\\n• Agravamento de hipertrofia prostática benigna\\n• Procure ajuda imediata se houver dor torácica, falta de ar súbita ou sinais de trombose.',
   E'• Acne and oily skin\\n• Fluid retention and oedema\\n• Gynaecomastia (peripheral aromatisation)\\n• Testicular atrophy and infertility (axis suppression)\\n• Mood change, aggression, sleep apnoea\\n• Polycythaemia (↑ haematocrit)\\n• Worsening of benign prostatic hyperplasia\\n• Seek immediate help if chest pain, sudden shortness of breath or thrombosis signs occur.',
   E'• CONTRAINDICADO no cancro da próstata ou mama masculino\\n• Não usar em mulheres grávidas (virilização fetal)\\n• Vigiar hematócrito (> 54%: suspender), PSA e antigénio prostático\\n• Nunca administrar IV; IM profunda na glúteo\\n• Risco de abuso e dependência — prescrição controlada',
   E'• CONTRAINDICATED in prostate or male breast cancer\\n• Do not use in pregnant women (fetal virilisation)\\n• Monitor haematocrit (> 54%: stop), PSA and prostate antigen\\n• Never administer IV; deep IM in the gluteus\\n• Abuse and dependence risk — controlled prescription',
   E'Rótulo aprovado DailyMed/FDA — Testosterone Cypionate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=40a332e3-9c64-4595-91c3-dfef24f3d3bb — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Testosterone Cypionate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=40a332e3-9c64-4595-91c3-dfef24f3d3bb — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('progesterona',
   E'Progesterona é a hormona natural da segunda metade do ciclo menstrual e da gravidez. Usada em cápsulas para apoiar a gravidez em casos de risco, tratar perturbações do ciclo e na terapêutica hormonal da menopausa (com estrogénio).',
   E'Progesterone is the natural hormone of the second half of the menstrual cycle and of pregnancy. Used in capsules to support at-risk pregnancies, treat cycle disorders, and in menopausal hormone therapy (with oestrogen).',
   E'Gestagénio natural micronizado: liga o recetor de progesterona com afinidade idêntica à hormona endógena. Transforma o endométrio proliferativo em secretório, mantém a decidua na gravidez, reduz a contratilidade uterina e na menopausa protege o endométrio do estímulo estrogénico.',
   E'Natural micronised progestogen: binds the progesterone receptor with affinity identical to the endogenous hormone. Transforms proliferative endometrium to secretory, maintains the decidua in pregnancy, reduces uterine contractility and in menopause protects the endometrium from oestrogen stimulation.',
   E'Metabolismo hepático extenso (redução a pregnanolona e metabolitos sulfatados/glucuronidados); excreção renal. O micronizado aumenta a absorção (a forma não micronizada é quase inativa por via oral).',
   E'Extensive hepatic metabolism (reduction to pregnanolone and sulphated/glucuronidated metabolites); renal excretion. Micronisation increases absorption (non-micronised form is almost inactive orally).',
   E'Oral: absorção variável (melhor com alimento gorduroso); vaginal: absorção uterina direta ("efeito de primeira passagem uterino").',
   E'Oral: variable absorption (better with fatty food); vaginal: direct uterine absorption ("uterine first-pass effect").',
   E'~ 5–20 min (vida curta; metabolitos ativos sustentam o efeito).',
   E'~ 5–20 min (short half-life; active metabolites sustain the effect).',
   E'• Sonolência e tonturas (toma nocturna preferida)\\n• Sangramento irregular e mastalgia\\n• Inchaço e alteração do humor\\n• Reações no local (forma vaginal): ardor, corrimento\\n• Risco trombótico menor que o dos progestagénios sintéticos, mas presente\\n• Procure ajuda imediata se houver dor de perna com inchaço, dor torácica súbita ou falta de ar.',
   E'• Drowsiness and dizziness (night dosing preferred)\\n• Irregular bleeding and breast tenderness\\n• Bloating and mood change\\n• Site reactions (vaginal form): burning, discharge\\n• Thrombotic risk lower than synthetic progestogens, but present\\n• Seek immediate help if leg pain with swelling, sudden chest pain or shortness of breath occurs.',
   E'• Contra-indicado em trombose venosa prévia, doença hepática e cancro da mama conhecido\\n• Aviso de condução (sonolência) — tomar ao deitar\\n• Não usar como contracetivo isolado\\n• Em ameaça de aborto, apenas com indicação médica clara (evidência limitada)',
   E'• Contraindicated in previous venous thrombosis, liver disease and known breast cancer\\n• Driving warning (drowsiness) — take at bedtime\\n• Do not use as sole contraceptive\\n• In threatened miscarriage, only with clear medical indication (limited evidence)',
   E'Rótulo aprovado DailyMed/FDA — Progesterone Capsule: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d7619751-47b4-47c9-b716-e2a704b350c8 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Progesterone Capsule: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d7619751-47b4-47c9-b716-e2a704b350c8 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('carbimazol',
   E'Carbimazol é um medicamento que reduz a produção das hormonas da tiroide. É usado no hipertiroidismo (doença de Basedow, bócio tóxico) para controlar os sintomas: tremores, palpitações, emagrecimento e ansiedade.',
   E'Carbimazole is a medicine that reduces thyroid hormone production. It is used in hyperthyroidism (Graves\u2019 disease, toxic goitre) to control symptoms: tremor, palpitations, weight loss and anxiety.',
   E'Profármaco convertido in vivo a metimazol (metabolito ativo): inibe a peroxidase tiroideia, bloqueando a iodinação da tirosina e o acoplamento de T3/T4. Não inativa hormona já sintetizada → início de ação clínico em 2–4 semanas (esgotamento das reservas).',
   E'Prodrug converted in vivo to methimazole (active metabolite): inhibits thyroid peroxidase, blocking tyrosine iodination and T3/T4 coupling. Does not inactivate already-synthesised hormone → clinical onset in 2–4 weeks (store depletion).',
   E'Conversão hepática rápida a metimazol; metabolismo hepático do metimazol; excreção renal.',
   E'Rapid hepatic conversion to methimazole; hepatic metabolism of methimazole; renal excretion.',
   E'Oral: boa absorção; pico plasmático do metimazol em 1–2 h; captura tiroideia ativa.',
   E'Oral: good absorption; methimazole plasma peak in 1–2 h; active thyroid uptake.',
   E'~ 3–6 h (metimazol; permanência intratiroideia mais longa → dose única diária possível).',
   E'~ 3–6 h (methimazole; longer intrathyroid persistence → once-daily dosing possible).',
   E'• Erupção cutânea e prurido (5–10%)\\n• Náuseas, dor articular e alteração do gosto\\n• Agranulocitose (0,3–0,5% — grave): febre, dor de garganta, úlceras orais\\n• Hepatotoxicidade colestática (raro)\\n• Hipotiroidismo por excesso de dose\\n• Procure ajuda imediata se houver febre com dor de garganta ou úlceras na boca (risco de agranulocitose).',
   E'• Skin rash and itching (5–10%)\\n• Nausea, joint pain and taste change\\n• Agranulocytosis (0.3–0.5% — serious): fever, sore throat, oral ulcers\\n• Cholestatic hepatotoxicity (rare)\\n• Hypothyroidism from excess dose\\n• Seek immediate help if fever with sore throat or mouth ulcers occurs (agranulocytosis risk).',
   E'• Vigiar hemograma se febre/dor de garganta (agranulocitose)\\n• Vigiar função tiroideia (TSH, T4 livre) a cada 4–6 semanas no início\\n• Primeiro trimestre de gravidez: preferir propiltiouracilo (carbimazol → embriopatia)\\n• Não usar em hipertiroidismo induzido por amiodarona tipo 2 (preferir corticoide)',
   E'• Monitor blood count if fever/sore throat (agranulocytosis)\\n• Monitor thyroid function (TSH, free T4) every 4–6 weeks initially\\n• First trimester of pregnancy: prefer propylthiouracil (carbimazole → embryopathy)\\n• Do not use in amiodarone-induced hyperthyroidism type 2 (prefer corticosteroid)',
   E'DailyMed — Carbimazole Powder (rótulo veterinário; uso clínico baseado em EMC-UK): https://www.medicines.org.uk/emc/product/8566 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed — Carbimazole Powder (veterinary label; clinical use based on EMC-UK): https://www.medicines.org.uk/emc/product/8566 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('propiltiouracilo',
   E'Propiltiouracilo (PTU) é um antitiroideu usado no hipertiroidismo, sobretudo no primeiro trimestre da gravidez e nas tempestades tiroideias graves, quando o carbimazol não é a escolha preferida.',
   E'Propylthiouracil (PTU) is an antithyroid drug used in hyperthyroidism, especially in the first trimester of pregnancy and in severe thyroid storms, when carbimazole is not the preferred choice.',
   E'Tionamida que inibe a tiroide peroxidase (↓ síntese de T3/T4) e, adicionalmente, a desiodase periférica tipo 1 (↓ conversão T4 → T3) — vantagem na tempestade tiroideia. Ação mais rápida que o carbimazol na redução de T3.',
   E'Thionamide inhibiting thyroid peroxidase (↓ T3/T4 synthesis) and additionally peripheral type-1 deiodinase (↓ T4 → T3 conversion) — advantage in thyroid storm. Faster than carbimazole in reducing T3.',
   E'Metabolismo hepático (glucuronidação); excreção renal; atravessa a placenta e o leite (menos que o metimazol no 1.º trimestre, pela maior ligação proteica).',
   E'Hepatic metabolism (glucuronidation); renal excretion; crosses placenta and milk (less than methimazole in the 1st trimester, due to higher protein binding).',
   E'Oral: absorção rápida; pico em 1–2 h; precisa de doses divididas (vida curta).',
   E'Oral: rapid absorption; peak in 1–2 h; requires divided doses (short half-life).',
   E'~ 1–2 h (exige 2–4 tomas/dia).',
   E'~ 1–2 h (requires 2–4 doses/day).',
   E'• Erupção cutânea e prurido\\n• Dor articular e náuseas\\n• Agranulocitose (0,3–0,5% — grave): febre, dor de garganta\\n• Hepatotoxicidade HEPATOCELULAR grave (mais frequente que com metimazol, especialmente em crianças): falência hepática\\n• Vasculite ANCA-positiva (uso prolongado)\\n• Hipotiroidismo por excesso\\n• Procure ajuda imediata se houver icterícia, urina escura, febre com dor de garganta ou dor abdominal intensa.',
   E'• Skin rash and itching\\n• Joint pain and nausea\\n• Agranulocytosis (0.3–0.5% — serious): fever, sore throat\\n• Serious HEPATOCELLULAR hepatotoxicity (more frequent than with methimazole, especially in children): liver failure\\n• ANCA-positive vasculitis (prolonged use)\\n• Hypothyroidism from excess\\n• Seek immediate help if jaundice, dark urine, fever with sore throat or intense abdominal pain occurs.',
   E'• Vigiar transaminases e bilirrubina no início e se sintomas hepáticos\\n• Vigiar hemograma se febre/dor de garganta\\n• Segundo trimestre de gravidez: reverter para carbimazol (PTU hepatotóxico)\\n• Rápido para tempestade tiroideia (↓ conversão periférica de T3)',
   E'• Monitor transaminases and bilirubin at baseline and if liver symptoms\\n• Monitor blood count if fever/sore throat\\n• Second trimester of pregnancy: switch back to carbimazole (PTU hepatotoxic)\\n• Fast in thyroid storm (↓ peripheral T3 conversion)',
   E'Rótulo aprovado DailyMed/FDA — Propylthiouracil Tablet [Par Health]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0c23a2c-b250-4c0d-9b2a-c1483faa2ca0 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012): "deverá ser o fármaco de escolha" na gravidez (1.º trimestre)',
   E'DailyMed/FDA approved label — Propylthiouracil Tablet [Par Health]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0c23a2c-b250-4c0d-9b2a-c1483faa2ca0 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012): "should be the drug of choice" in pregnancy (1st trimester)'),

  ('piridoxina',
   E'Piridoxina (vitamina B6) é usada para corrigir a falta de B6 (convulsões neonatais resistentes, neuropatias, anemia sideroblástica) e em situações especiais: intoxicação por isoniazida e enjoo na gravidez (com doxilamina).',
   E'Pyridoxine (vitamin B6) is used to correct B6 deficiency (resistant neonatal seizures, neuropathies, sideroblastic anaemia) and in special situations: isoniazid poisoning and pregnancy nausea (with doxylamine).',
   E'Co-factor de mais de 100 enzimas do metabolismo dos aminoácidos, neurotransmissores (GABA, dopamina, serotonina) e heme. A piridoxina é convertida a piridoxal-5-fosfato (PLP), co-enzima da descarboxilação do glutamato a GABA — base do uso na intoxicação por isoniazida (que inibe a piridoxina quinase → ↓ GABA → convulsões).',
   E'Cofactor of over 100 enzymes of amino acid, neurotransmitter (GABA, dopamine, serotonin) and heme metabolism. Pyridoxine is converted to pyridoxal-5-phosphate (PLP), the co-enzyme of glutamate decarboxylation to GABA — basis for use in isoniazid poisoning (which inhibits pyridoxine kinase → ↓ GABA → seizures).',
   E'Fosforilação hepática a PLP; excreção renal de 4-piridóxico (metabolito inativo).',
   E'Hepatic phosphorylation to PLP; renal excretion of 4-pyridoxic acid (inactive metabolite).',
   E'Absorção jejunal ativa e passiva; biodisponibilidade oral alta; dose IV na intoxicação por isoniazida.',
   E'Jejunal active and passive absorption; high oral bioavailability; IV dose in isoniazid poisoning.',
   E'~ 15–20 dias (reserva corporal; PLP mais curto).',
   E'~ 15–20 days (body stores; PLP shorter).',
   E'• Nas doses habituais: bem tolerada\\n• Doses muito altas crónicas (> 500 mg/dia): neuropatia sensorial periférica (adormecimento, ataxia) — geralmente reversível\\n• Sonolência em dose IV alta\\n• Reação alérgica (raro)\\n• Procure ajuda imediata se houver formigueiro persistente ou perda de coordenação durante tratamentos prolongados em dose alta.',
   E'• At usual doses: well tolerated\\n• Chronic very high doses (> 500 mg/day): peripheral sensory neuropathy (tingling, ataxia) — usually reversible\\n• Drowsiness at high IV dose\\n• Allergic reaction (rare)\\n• Seek immediate help if persistent tingling or loss of coordination occurs during prolonged high-dose treatment.',
   E'• Doses ≥ 10 mg/dia podem mascarar défice de B12 (degeneração subaguda combinada)\\n• Interação com levodopa isolada (↓ eficácia — a piridoxina acelera a descarboxilação periférica); sem problema com carbidopa\\n• Reduz os níveis de fenitoína e fenobarbital\\n• Na intoxicação por isoniazida: dose igual à de isoniazida ingerida',
   E'• Doses ≥ 10 mg/day can mask B12 deficiency (combined subacute degeneration)\\n• Interaction with isolated levodopa (↓ efficacy — pyridoxine accelerates peripheral decarboxylation); no problem with carbidopa\\n• Lowers phenytoin and phenobarbital levels\\n• In isoniazid poisoning: dose equal to the ingested isoniazid amount',
   E'DailyMed — Pyridoxine (rótulos combinados VANTREX/LUNATAL; rótulo mono-ingrediente injetável também validado): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3a1f0405-6983-410d-b625-54517a6a235f — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed — Pyridoxine (combined labels VANTREX/LUNATAL; injectable mono-ingredient label also validated): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3a1f0405-6983-410d-b625-54517a6a235f — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('acido-tranexamico',
   E'Ácido tranexâmico é um medicamento que ajuda a estancar hemorragias: menstruações muito abundantes, hemorragias do parto, traumatismos, cirurgias e hemorragias nasais. Não forma coágulos — só evita que os que se formam se desfiram.',
   E'Tranexamic acid is a medicine that helps stop bleeding: very heavy periods, childbirth bleeding, trauma, surgery and nosebleeds. It does not form clots — it only stops the ones that form from breaking down.',
   E'Análogo da lisina: liga-se às lisanos-ligantes do plasminogénio, bloqueando a sua conversão a plasmina e a fibrinólise. Efeito antifibrinolítico seletivo (não promove coagulação generalizada). Reduz a mortalidade por hemorragia em traumatismos se administrado nas primeiras 3 h (estudo CRASH-2).',
   E'Lysine analogue: binds lysine-binding sites of plasminogen, blocking its conversion to plasmin and fibrinolysis. Selective antifibrinolytic effect (does not promote generalised coagulation). Reduces bleeding mortality in trauma if given within the first 3 h (CRASH-2 study).',
   E'Minimamente metabolizado (< 5%); excreção renal predominantemente inalterada (ajustar na insuficiência renal).',
   E'Minimally metabolised (< 5%); predominantly unchanged renal excretion (adjust in renal failure).',
   E'Oral: biodisponibilidade 30–50% (saturável); IV: biodisponibilidade 100%; penetra mal na LCR.',
   E'Oral: bioavailability 30–50% (saturable); IV: 100%; poor CSF penetration.',
   E'~ 2–3 h (IV); efeito clínico mais longo (inibição tecidual).',
   E'~ 2–3 h (IV); longer clinical effect (tissue inhibition).',
   E'• Náuseas, vómitos e diarreia (oral)\\n• Dores musculares e cãibras\\n• Retenção urinária em doses altas (obstrução uretral por coágulo)\\n• Tromboembolismo (raro em risco baixo, mas sério): TVP, embolia pulmonar, AVC\\n• Perturbações visuais de cor (uso prolongado)\\n• Procure ajuda imediata se houver dor de perna com inchaço, dor torácica súbita, falta de ar ou dificuldade em falar.',
   E'• Nausea, vomiting and diarrhoea (oral)\\n• Muscle aches and cramps\\n• Urinary retention at high doses (clot urethral obstruction)\\n• Thromboembolism (rare at low risk, but serious): DVT, pulmonary embolism, stroke\\n• Colour vision disturbances (prolonged use)\\n• Seek immediate help if leg pain with swelling, sudden chest pain, shortness of breath or speech difficulty occurs.',
   E'• CONTRAINDICADO em trombose ativa, história de tromboembolismo e hematuria macroscópica de origem renal (coágulos obstrutivos)\\n• Administrar nas primeiras 3 h no trauma (perde eficácia depois)\\n• Não administrar com concentrados de complexo protrombínico ou fatores ativados sem avaliação\\n• Ajustar dose na insuficiência renal',
   E'• CONTRAINDICATED in active thrombosis, history of thromboembolism and macroscopic renal-source haematuria (obstructive clots)\\n• Give within the first 3 h in trauma (loses efficacy after)\\n• Do not give with prothrombin complex concentrates or activated factors without assessment\\n• Adjust dose in renal failure',
   E'Rótulo aprovado DailyMed/FDA — Tranexamic Acid Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d97790f-048b-494d-aa22-5689643a724b — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012): "fibrinolíticos estão contra-indicados em doentes com hemorragias... défices da coagulação, dissecção aórtica"',
   E'DailyMed/FDA approved label — Tranexamic Acid Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d97790f-048b-494d-aa22-5689643a724b — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('protamina',
   E'Protamina é o antídoto da heparina. Usada no hospital para reverter rapidamente o efeito anticoagulante após cirurgias cardíacas, procedimentos de cateterismo e em hemorragias graves sob heparina.',
   E'Protamine is the antidote to heparin. Used in hospital to rapidly reverse the anticoagulant effect after heart surgeries, catheterisation procedures and in serious bleeding under heparin.',
   E'Polipeptídeo muito básico (rico em arginina) que liga ionicamente a heparina (ácida), formando um complexo estável sem atividade anticoagulante. Neutraliza ~ 100 U de heparina por 1 mg de protamina; efeito em 30–60 s. Reversão parcial das heparinas de baixo peso molecular.',
   E'Very basic polypeptide (arginine-rich) that ionically binds heparin (acidic), forming a stable complex without anticoagulant activity. Neutralises ~ 100 U of heparin per 1 mg protamine; effect in 30–60 s. Partial reversal of low molecular weight heparins.',
   E'Degradado por peptidases; metabolismo não completamente esclarecido; excreção renal de fragmentos.',
   E'Degraded by peptidases; metabolism not fully elucidated; renal excretion of fragments.',
   E'IV exclusivo; ação imediata.',
   E'IV exclusive; immediate action.',
   E'~ 7–9 min (efeito clínico 2 h).',
   E'~ 7–9 min (clinical effect 2 h).',
   E'• Hipotensão e bradicardia (perfusão rápida)\\n• Reações anafiláticas e anafilaxia (especialmente alérgicos ao peixe, diabéticos em insulina NPH ou vasectomizados)\\n• Hipertensão pulmonar e colapso cardiovascular (raro, grave)\\n• Anticoagulação paradoxal por excesso (protamina liga a trombina em dose alta)\\n• Rubor e sensação de calor\\n• Procure ajuda imediata se houver queda súbita da tensão, dificuldade em respirar ou colapso durante a injeção.',
   E'• Hypotension and bradycardia (rapid infusion)\\n• Anaphylactic and anaphylactoid reactions (especially fish-allergic, NPH-insulin diabetics or vasectomised patients)\\n• Pulmonary hypertension and cardiovascular collapse (rare, serious)\\n• Paradoxical anticoagulation from excess (protamine binds thrombin at high dose)\\n• Flushing and heat sensation\\n• Seek immediate help if sudden blood pressure drop, breathing difficulty or collapse occurs during injection.',
   E'• Perfusão LENTA (≤ 5 mg/min) com monitorização hemodinâmica\\n• Dose calculada pelo tempo desde a última heparina e pela TTPa/ACT\\n• Ambiente com suporte de reanimação disponível\\n• Cuidado em alergia ao peixe e exposição prévia à protamina/NPH',
   E'• SLOW infusion (≤ 5 mg/min) with haemodynamic monitoring\\n• Dose calculated by time since last heparin and aPTT/ACT\\n• Setting with resuscitation support available\\n• Caution in fish allergy and previous protamine/NPH exposure',
   E'Rótulo aprovado DailyMed/FDA — Protamine Sulfate Injection [Fresenius Kabi]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c76876da-b9a8-45d0-9278-7df3288d3a06 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Protamine Sulfate Injection [Fresenius Kabi]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c76876da-b9a8-45d0-9278-7df3288d3a06 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('cloreto-potassio',
   E'Cloreto de potássio é um suplemento do mineral potássio, usado para corrigir o potássio baixo (hipopotassémia): fraqueza, cãibras, palpitações e arritmias. Existe em comprimidos, soluções orais e perfusões hospitalares.',
   E'Potassium chloride is a potassium mineral supplement, used to correct low potassium (hypokalaemia): weakness, cramps, palpitations and arrhythmias. It comes in tablets, oral solutions and hospital infusions.',
   E'Eletrólito intracelular predominante (~ 98% do K corporal). Restaura o gradiente de membrana (potencial de repouso), essencial para a excitabilidade neuromuscular, condução cardíaca e contratilidade. A hipopotassémia hiperpolariza a membrana (fraqueza, arritmias); a reposição IV rápida é cardiotoxicamente perigosa (paragem em diástole).',
   E'Predominant intracellular electrolyte (~ 98% of body K). Restores the membrane gradient (resting potential), essential for neuromuscular excitability, cardiac conduction and contractility. Hypokalaemia hyperpolarises the membrane (weakness, arrhythmias); rapid IV replacement is cardiotoxically dangerous (diastolic arrest).',
   E'Não tem metabolismo; regulação renal rigorosa (aldosterona, pH ácido-base); excreção renal e fecal.',
   E'No metabolism; strict renal regulation (aldosterone, acid-base pH); renal and faecal excretion.',
   E'Oral: absorção intestinal passiva (20–40% de biodisponibilidade; melhor em formulações de liberação prolongada); IV: 100%.',
   E'Oral: passive intestinal absorption (20–40% bioavailability; better in prolonged-release formulations); IV: 100%.',
   E'~ 1–1,5 h (oral); distribuição intracelular lenta (equilíbrio em 24–48 h).',
   E'~ 1–1.5 h (oral); slow intracellular distribution (equilibrium in 24–48 h).',
   E'• Irritação gástrica e úlcera (comprimidos; tomar com muita água e com alimento)\\n• Dor no local da perfusão (periférica; concentração alta)\\n• Hiperpotassémia por excesso: formigueiro, fraqueza, paralisia, alterações do ECG (ondas T apicais, alargamento do QRS, paragem)\\n• Dor abdominal (liberação prolongada)\\n• Procure ajuda imediata se houver palpitações, fraqueza intensa ou formigueiro durante a reposição.',
   E'• Gastric irritation and ulcer (tablets; take with plenty of water and with food)\\n• Infusion site pain (peripheral; high concentration)\\n• Hyperkalaemia from excess: tingling, weakness, paralysis, ECG changes (tall T waves, widened QRS, arrest)\\n• Abdominal pain (prolonged release)\\n• Seek immediate help if palpitations, intense weakness or tingling occur during replacement.',
   E'• IV: NUNCA em bolo; concentração ≤ 40 mmol/L (periférica) ou ≤ 20 mmol/h em cuidados intensivos com monitor\\n• Vigiar potássio sérico e ECG em reposição IV\\n• Corrigir magnésio baixo em simultâneo (a hipomagnesémia mantém a hipopotassémia)\\n• Cuidado em insuficiência renal, com IECA/ARA II, espironolactona e AINEs (↑ risco de hiperpotassémia)',
   E'• IV: NEVER as bolus; concentration ≤ 40 mmol/L (peripheral) or ≤ 20 mmol/h in monitored intensive care\\n• Monitor serum potassium and ECG on IV replacement\\n• Correct low magnesium simultaneously (hypomagnesaemia maintains hypokalaemia)\\n• Caution in renal failure, with ACEIs/ARBs, spironolactone and NSAIDs (↑ hyperkalaemia risk)',
   E'Rótulo aprovado DailyMed/FDA — Potassium Chloride Oral Solution: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=483f338e-a164-4c1f-a34e-fef3312cb7ec — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Potassium Chloride Oral Solution: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=483f338e-a164-4c1f-a34e-fef3312cb7ec — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('sulfato-magnesio',
   E'Sulfato de magnésio é usado no hospital para dois fins principais: prevenir convulsões na eclampsia (convulsões da gravidez) e corrigir o magnésio baixo. Também relaxa os brônquios em crises de asma graves e trata arritmias torsades.',
   E'Magnesium sulfate is used in hospital for two main purposes: preventing seizures in eclampsia (pregnancy seizures) and correcting low magnesium. It also relaxes the airways in severe asthma attacks and treats torsades arrhythmias.',
   E'Antagonista fisiológico do cálcio: bloqueia canais de NMDA e canais de Ca2+ voltagem-dependentes → estabilização neuronal (anticonvulsivo), vasodilatação cerebral, broncodilatação e efeito antiarrítmico (torsades). Aumenta a excreção renal de sódio (leve diurese). Níveis ≥ 8–10 mg/dL abolem reflexos patelares; > 12 mg/dL risco de paragem respiratória.',
   E'Physiological calcium antagonist: blocks NMDA channels and voltage-gated Ca2+ channels → neuronal stabilisation (anticonvulsant), cerebral vasodilation, bronchodilation and antiarrhythmic effect (torsades). Increases renal sodium excretion (mild diuresis). Levels ≥ 8–10 mg/dL abolish patellar reflexes; > 12 mg/dL respiratory arrest risk.',
   E'Não tem metabolismo; excreção renal rápida (vida dependente da função renal).',
   E'No metabolism; rapid renal excretion (half-life kidney-function dependent).',
   E'IV/IM: biodisponibilidade 100%/~ 90%; oral: má absorção (efeito osmótico laxante predominante).',
   E'IV/IM: 100%/~ 90% bioavailability; oral: poor absorption (predominant osmotic laxative effect).',
   E'~ 4–6 h (renal normal); prolongado em insuficiência renal.',
   E'~ 4–6 h (normal kidneys); prolonged in renal failure.',
   E'• Rubor, suores e sensação de calor (perfusão)\\n• Náuseas e sede\\n• Hipotensão e fraqueza muscular\\n• Em excesso: reflexos patelares ausentes (sinal de alerta), diplopia, fala arrastada, depressão respiratória, paragem cardíaca\\n• Depressão do recém-nascido (uso prolongado antes do parto)\\n• Procure ajuda imediata se houver dificuldade em respirar, batimentos muito lentos ou falta de reflexos nos joelhos.',
   E'• Flushing, sweating and heat sensation (infusion)\\n• Nausea and thirst\\n• Hypotension and muscle weakness\\n• In excess: absent patellar reflexes (warning sign), double vision, slurred speech, respiratory depression, cardiac arrest\\n• Newborn depression (prolonged use before delivery)\\n• Seek immediate help if breathing difficulty, very slow heartbeat or absent knee reflexes occur.',
   E'• Em eclampsia: dose de ataque 4 g IV + manutenção 1–2 g/h; vigiar reflexos patelares, frequência respiratória (> 12/min) e diurese (> 25 mL/h)\\n• Ter gluconato de cálcio IV disponível como antídoto\\n• Reduzir dose na insuficiência renal\\n• Não usar em hipotensão prévia sem correção de volume',
   E'• In eclampsia: 4 g IV loading dose + 1–2 g/h maintenance; monitor patellar reflexes, respiratory rate (> 12/min) and urine output (> 25 mL/h)\\n• Have IV calcium gluconate available as antidote\\n• Reduce dose in renal failure\\n• Do not use in pre-existing hypotension without volume correction',
   E'DailyMed — Magnesium Sulfate (rótulos IV; usar referência de rótulos hospitalares): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5b4b4805-a8ff-4efe-94bc-411090ab5f9c — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed — Magnesium Sulfate (IV labels; hospital label reference): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5b4b4805-a8ff-4efe-94bc-411090ab5f9c — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('gluconato-calcio',
   E'Gluconato de cálcio é a forma de cálcio dada por injeção no hospital para situações urgentes: potássio muito alto que afeta o coração, cálcio muito baixo com espasmos, transfusões maciças e intoxicação por bloqueadores dos canais de cálcio.',
   E'Calcium gluconate is the form of calcium given by injection in hospital for urgent situations: very high potassium affecting the heart, very low calcium with spasms, massive transfusions and calcium channel blocker poisoning.',
   E'Fornece Ca2+ ionizado imediatamente: estabiliza a membrana miocárdica (hiperpotassémia), restaura o gradiente de excitabilidade (hipocalcémia/tetania), fornece substrato de contratilidade (hipocalcémia pós-transfusão maciça) e compete com o bloqueio dos canais de Ca2+ (verapamil/diltiazem).',
   E'Provides ionised Ca2+ immediately: stabilises the myocardial membrane (hyperkalaemia), restores the excitability gradient (hypocalcaemia/tetany), supplies contractility substrate (post-massive transfusion hypocalcaemia) and competes with calcium channel block (verapamil/diltiazem).',
   E'Não tem metabolismo; distribuição no compartimento extracelular; excreção renal (regulada por PTH e vitamina D).',
   E'No metabolism; extracellular compartment distribution; renal excretion (regulated by PTH and vitamin D).',
   E'IV: biodisponibilidade 100%; oral: 10–30% (mal absorvido, preferir carbonato).',
   E'IV: 100% bioavailability; oral: 10–30% (poorly absorbed, prefer carbonate).',
   E'~ 30–60 min (efeito clínico de estabilização 30–120 min).',
   E'~ 30–60 min (clinical stabilisation effect 30–120 min).',
   E'• Hiperpotassémia paradoxal não previne arritmias se o pH for ácido (corrigir pH primeiro)\\n• Bradicardia e arritmias em perfusão rápida\\n• Extravasamento: necrose cutânea e calcificação (grave)\\n• Hipercalemia por excesso (raro; mais comum em insuficiência renal)\\n• Sabor metálico e rubor (perfusão rápida)\\n• Procure ajuda imediata se houver dor intensa, branqueamento ou inchaço no local da perfusão.',
   E'• Paradoxical hyperkalaemia does not prevent arrhythmias if pH is acid (correct pH first)\\n• Bradycardia and arrhythmias on rapid infusion\\n• Extravasation: skin necrosis and calcification (serious)\\n• Hypercalcaemia from excess (rare; more common in renal failure)\\n• Metallic taste and flushing (rapid infusion)\\n• Seek immediate help if intense pain, whitening or swelling occurs at the infusion site.',
   E'• NUNCA misturar com bicarbonato de sódio na mesma linha (precipitação de carbonato de cálcio)\\n• Perfusão lenta com monitorização cardíaca em hiperpotassémia\\n• Cuidado em doentes sob digitálicos (sinergismo arrítmico)\\n• Preferir via central para soluções concentradas',
   E'• NEVER mix with sodium bicarbonate in the same line (calcium carbonate precipitation)\\n• Slow infusion with cardiac monitoring in hyperkalaemia\\n• Caution in patients on digitalis (arrhythmic synergy)\\n• Prefer central line for concentrated solutions',
   E'Rótulo aprovado DailyMed/FDA — Calcium Gluconate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=16307c00-d0d5-4e05-821f-17b0c1a29fc9 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Calcium Gluconate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=16307c00-d0d5-4e05-821f-17b0c1a29fc9 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('n-acetilcisteina',
   E'N-acetilcisteína (NAC) é o antídoto do paracetamol: salva o fígado quando dada a tempo depois de uma sobredosagem. Também é usada como mucolítico para afrouxar o catarro na bronquite e fibrose quística.',
   E'N-acetylcysteine (NAC) is the antidote to paracetamol: it saves the liver when given in time after an overdose. It is also used as a mucolytic to loosen phlegm in bronchitis and cystic fibrosis.',
   E'Repõe o glutatião hepático (doador de cisteína): o NAPQI (metabolito tóxico do paracetamol) liga-se covalentemente a proteínas hepatocitárias na ausência de glutatião → necrose centrilobular. A NAC precoce (até 8 h idealmente, mas com benefício até 24 h) impede a progressão. Mucolítico: rompe ligações dissulfureto das glicoproteínas do muco.',
   E'Replenishes hepatic glutathione (cysteine donor): NAPQI (toxic paracetamol metabolite) binds covalently to hepatocyte proteins in the absence of glutathione → centrilobular necrosis. Early NAC (ideally up to 8 h, but with benefit up to 24 h) prevents progression. Mucolytic: breaks disulphide bonds of mucus glycoproteins.',
   E'Desacetilação a cisteína (uso hepatoprotetor); oxidação hepática e renal; excreção renal.',
   E'Deacetylation to cysteine (hepatoprotector use); hepatic and renal oxidation; renal excretion.',
   E'Oral: biodisponibilidade 6–10% (primeira passagem extensa); IV: 100% (preferido na sobredosagem).',
   E'Oral: bioavailability 6–10% (extensive first pass); IV: 100% (preferred in overdose).',
   E'~ 2–6 h (IV; dose-dependente).',
   E'~ 2–6 h (IV; dose-dependent).',
   E'• Náuseas, vómitos e urticária (reacção de hipersensibilidade comum, sobretudo na dose de ataque IV)\\n• Rubor facial e sensação de calor\\n• Broncospasmo (asma)\\n• Anafilaxia (raro)\\n• Odor sulfuroso (esperado e inofensivo)\\n• Procure ajuda imediata se houver dificuldade em respirar, inchaço do rosto ou colapso durante a perfusão.',
   E'• Nausea, vomiting and urticaria (common hypersensitivity reaction, especially at IV loading dose)\\n• Facial flushing and heat sensation\\n• Bronchospasm (asthma)\\n• Anaphylaxis (rare)\\n• Sulphurous odour (expected and harmless)\\n• Seek immediate help if breathing difficulty, facial swelling or collapse occurs during infusion.',
   E'• Perfusão inicial mais lenta (60 min em vez de 15) em doentes com risco de reação\\n• Cuidado em asma grave\\n• Não diluir com sucos ácidos (inativação)\\n• Iniciar o mais cedo possível após a sobredosagem — o relógio é o fator mais importante',
   E'• Slower initial infusion (60 min instead of 15) in patients with reaction risk\\n• Caution in severe asthma\\n• Do not dilute with acidic juices (inactivation)\\n• Start as early as possible after overdose — time is the most important factor',
   E'Rótulo aprovado DailyMed/FDA — Acetylcysteine Solution [Hospira]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Acetylcysteine Solution [Hospira]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('deferoxamina',
   E'Deferoxamina é um medicamento que retira o excesso de ferro do corpo. Usado em doentes que recebem muitas transfusões de sangue (talassémia, anemia aplásica) e na urgência de intoxicação aguda por ferro (crianças que ingerem comprimidos de ferro).',
   E'Deferoxamine is a medicine that removes excess iron from the body. Used in patients receiving many blood transfusions (thalassaemia, aplastic anaemia) and in the emergency of acute iron poisoning (children who swallow iron tablets).',
   E'Sideróforo bacteriano (Streptomyces pilosus) modificado: liga Fe3+ com afinidade extremamente alta (log K ~ 31) formando ferrioxamina, excretada renalmente. Não liga Fe2+ da hemoglobina → só retira ferro livre e do ferritina/hemossiderina. A toxicidade ocular e auditiva é dose- e duração-dependente.',
   E'Modified bacterial siderophore (Streptomyces pilosus): binds Fe3+ with extremely high affinity (log K ~ 31) forming ferrioxamine, renally excreted. Does not bind haemoglobin Fe2+ → only removes free iron and ferritin/haemosiderin iron. Ocular and auditory toxicity is dose- and duration-dependent.',
   E'Metabolismo hepático (plasma alamina-oxidasas) a metabólitos inativos; excreção renal (ferrioxamina — urina cor de vinho) e biliar.',
   E'Hepatic metabolism (plasma amine oxidases) to inactive metabolites; renal excretion (ferrioxamine — wine-coloured urine) and biliary.',
   E'Oral: má absorção (< 15%) → uso parenteral; SC/IM/IV; penetra mal no tecido hepático com fibrose avançada.',
   E'Oral: poor absorption (< 15%) → parenteral use; SC/IM/IV; poor penetration of fibrotic liver tissue.',
   E'~ 20–30 min (SC/IM); mais curta IV.',
   E'~ 20–30 min (SC/IM); shorter IV.',
   E'• Dor e induração no local SC\\n• Reações alérgicas e anafilaxia (raro)\\n• Toxicidade ocular: visão turva, catarata, retinopatia (doses altas crónicas)\\n• Toxicidade auditiva: perda de audição de frequências altas\\n• Infecções por Yersinia e mucormicose (o ferro liberado favorece o crescimento)\\n• Rubor, hipotensão e taquicardia (IV rápida)\\n• Urina cor de vinho-rosado (ferrioxamina — esperado na sobrecarga intensa)\\n• Procure ajuda imediata se houver alteração súbita da visão ou da audição durante o tratamento.',
   E'• Pain and induration at SC site\\n• Allergic reactions and anaphylaxis (rare)\\n• Ocular toxicity: blurred vision, cataract, retinopathy (chronic high doses)\\n• Auditory toxicity: high-frequency hearing loss\\n• Yersinia infections and mucormycosis (released iron favours growth)\\n• Flushing, hypotension and tachycardia (rapid IV)\\n• Wine-pink urine (ferrioxamine — expected in intense overload)\\n• Seek immediate help if sudden vision or hearing change occurs during treatment.',
   E'• Vigiar audição (audiometria) e visão (oftalmologia) a cada 3–6 meses em tratamentos crónicos\\n• Não usar em anúria grave sem ajuste\\n• Cuidado com regimes de dose alta contínua (toxicidade ocular/auditiva cumulativa)\\n• Suspender em infeção ativa por Yersinia/Sepsis até controlo',
   E'• Monitor hearing (audiometry) and vision (ophthalmology) every 3–6 months in chronic treatment\\n• Do not use in severe anuria without adjustment\\n• Caution with continuous high-dose regimens (cumulative ocular/auditory toxicity)\\n• Stop in active Yersinia infection/sepsis until controlled',
   E'Rótulo aprovado DailyMed/FDA — Deferoxamine Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d91e16df-8daa-4cd2-86a2-273eaa2446e0 — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'DailyMed/FDA approved label — Deferoxamine Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d91e16df-8daa-4cd2-86a2-273eaa2446e0 — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)')
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
       indications_pt, indications_en, side_effects_pt, side_effects_en,
       precautions_pt, precautions_en, source_pt, source_en)
  ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
