-- =====================================================================
-- 266 — Lote 3 LNME (6/6): farmacologia em public.drug_pharmacology
-- ---------------------------------------------------------------------
-- 13 fármacos (Lote 3 completo). Conteúdo autoral PT/EN ancorado nos
-- rótulos DailyMed (setIDs validados) e Prontuário Terapêutico INFARMED.
-- Padrão 7.6: JOIN (VALUES) ON d.slug = v.slug + ON CONFLICT DO NOTHING.
-- Idempotente. Companheiras: 264 (drugs), 265 (perfis).
-- =====================================================================

INSERT INTO public.drug_pharmacology
  (drug_id, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
   metabolism_pt, metabolism_en, absorption_pt, absorption_en, half_life_pt, half_life_en,
   source_pt, source_en, status)
SELECT d.id, v.pharmacodynamics_pt, v.pharmacodynamics_en, v.mechanism_pt, v.mechanism_en,
       v.metabolism_pt, v.metabolism_en, v.absorption_pt, v.absorption_en,
       v.half_life_pt, v.half_life_en, v.source_pt, v.source_en, 'published'
FROM public.drugs d
JOIN (VALUES
  ('clomifeno',
   E'Indução da ovulação com elevação de FSH/LH; pico de LH ~ 7–12 dias após a última toma de 5 dias.',
   E'Ovulation induction with FSH/LH elevation; LH peak ~ 7–12 days after the last of 5 days of dosing.',
   E'SERM: antagonista estrogénico hipotalâmico (↑ GnRH → FSH/LH) e anti-estrogénico periférico (↓ muco cervical, ↓ espessamento endometrial em ciclos prolongados).',
   E'SERM: hypothalamic oestrogen antagonist (↑ GnRH → FSH/LH) and peripheral anti-oestrogen (↓ cervical mucus, ↓ endometrial thickening in prolonged cycles).',
   E'Metabolismo hepático extenso (N-desmetilação e hidroxilação) a isómeros ativos; excreção biliar/renal.',
   E'Extensive hepatic metabolism (N-demethylation and hydroxylation) to active isomers; biliary/renal excretion.',
   E'Oral: boa absorção; pico em ~ 6 h; acumulação em tecidos (vida longa do metabolito).',
   E'Oral: good absorption; peak in ~ 6 h; tissue accumulation (long metabolite half-life).',
   E'~ 5 dias (trans-citrate); metabolitos até 6 semanas.',
   E'~ 5 days (trans-citrate); metabolites up to 6 weeks.',
   E'DailyMed — Clomiphene Citrate Tablet [Camber]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54f608de-6f14-4120-819e-aeb9350c3070',
   E'DailyMed — Clomiphene Citrate Tablet [Camber]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=54f608de-6f14-4120-819e-aeb9350c3070'),

  ('testosterona',
   E'Manutenção dos caracteres sexuais masculinos, anabolismo proteico e retroalimentação negativa no eixo hipotálamo-hipófise-gónadas.',
   E'Maintenance of male sexual characteristics, protein anabolism and negative feedback on the hypothalamus-pituitary-gonad axis.',
   E'Agonista do recetor androgénico intracelular: translocação nuclear → transcrição de genes androgéno-dependentes (DHT amplifica o sinal em tecidos 5α-redutase-ricos).',
   E'Intracellular androgen receptor agonist: nuclear translocation → transcription of androgen-dependent genes (DHT amplifies the signal in 5α-reductase-rich tissues).',
   E'Hidrólise do éster (cipionato) in vivo; metabolização hepática e periférica (5α-redutase → DHT; aromatase → estradiol); glucuronidação e excreção renal.',
   E'In vivo ester (cipionate) hydrolysis; hepatic and peripheral metabolism (5α-reductase → DHT; aromatase → estradiol); glucuronidation and renal excretion.',
   E'IM profunda: liberação lenta do depósito oleoso; pico 1–2 dias.',
   E'Deep IM: slow release from the oily depot; peak 1–2 days.',
   E'~ 8 dias (cipionato IM); testosterona livre ~ 10–100 min.',
   E'~ 8 days (IM cipionate); free testosterone ~ 10–100 min.',
   E'DailyMed — Testosterone Cypionate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=40a332e3-9c64-4595-91c3-dfef24f3d3bb',
   E'DailyMed — Testosterone Cypionate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=40a332e3-9c64-4595-91c3-dfef24f3d3bb'),

  ('progesterona',
   E'Transformação secretória do endométrio, ↓ contratilidade uterina, proteção endometrial (com estrogénio).',
   E'Secretory endometrial transformation, ↓ uterine contractility, endometrial protection (with oestrogen).',
   E'Agonista do recetor de progesterona (PR-A e PR-B); regulador da transcrição de genes de estabilização endometrial e de manutenção da gravidez.',
   E'Progesterone receptor agonist (PR-A and PR-B); transcription regulator of endometrial stabilisation and pregnancy maintenance genes.',
   E'Redução hepática a pregnanolona (metabolito neuroesteroide sedativo); sulfatação e glucuronidação; excreção renal.',
   E'Hepatic reduction to pregnanolone (sedative neurosteroid metabolite); sulphation and glucuronidation; renal excretion.',
   E'Oral micronizado: absorção variável com alimento; vaginal: absorção uterina direta com mínima exposição sistémica.',
   E'Oral micronised: variable absorption with food; vaginal: direct uterine absorption with minimal systemic exposure.',
   E'~ 5–20 min (muito curto; sustentado por metabolitos).',
   E'~ 5–20 min (very short; sustained by metabolites).',
   E'DailyMed — Progesterone Capsule: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d7619751-47b4-47c9-b716-e2a704b350c8',
   E'DailyMed — Progesterone Capsule: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d7619751-47b4-47c9-b716-e2a704b350c8'),

  ('carbimazol',
   E'Redução progressiva da síntese de T3/T4 (início clínico 2–4 semanas); normalização da função tiroideia em 6–12 semanas.',
   E'Progressive reduction of T3/T4 synthesis (clinical onset 2–4 weeks); normalisation of thyroid function in 6–12 weeks.',
   E'Profármaco a metimazol: inibe a tiroide peroxidase (TPO), bloqueando a iodinação da tiroglobulina e o acoplamento de iodotirosinas (MIT/DIT → T3/T4).',
   E'Prodrug to methimazole: inhibits thyroid peroxidase (TPO), blocking thyroglobulin iodination and iodotyrosine coupling (MIT/DIT → T3/T4).',
   E'Conversão hepática a metimazol; metabolismo subsequente do metimazol; excreção renal.',
   E'Hepatic conversion to methimazole; subsequent methimazole metabolism; renal excretion.',
   E'Oral: absorção rápida e completa; captura tiroideia ativa (acumulação na glândula).',
   E'Oral: rapid complete absorption; active thyroid uptake (glandular accumulation).',
   E'~ 3–6 h (metimazol; permanência intratiroideia mais longa).',
   E'~ 3–6 h (methimazole; longer intrathyroid persistence).',
   E'DailyMed — Carbimazole (rótulo veterinário; EMC-UK para uso clínico): https://www.medicines.org.uk/emc/product/8566',
   E'DailyMed — Carbimazole (veterinary label; EMC-UK for clinical use): https://www.medicines.org.uk/emc/product/8566'),

  ('propiltiouracilo',
   E'Redução rápida de T3 (↓ síntese tiroideia + ↓ conversão periférica T4→T3); útil na tempestade tiroideia.',
   E'Fast T3 reduction (↓ thyroid synthesis + ↓ peripheral T4→T3 conversion); useful in thyroid storm.',
   E'Inibição da tiroide peroxidase (TPO) e da desiodase periférica tipo 1 (bloqueia a conversão T4 → T3).',
   E'Inhibition of thyroid peroxidase (TPO) and of peripheral type-1 deiodinase (blocks T4 → T3 conversion).',
   E'Glucuronidação hepática; excreção renal; menos ligação proteica que o metimazol (mais atravessa a placenta no 2.º–3.º trimestre).',
   E'Hepatic glucuronidation; renal excretion; less protein binding than methimazole (more crosses placenta in 2nd–3rd trimester).',
   E'Oral: absorção rápida; pico 1–2 h; exige doses divididas pela vida curta.',
   E'Oral: rapid absorption; peak 1–2 h; requires divided doses due to short half-life.',
   E'~ 1–2 h.',
   E'~ 1–2 h.',
   E'DailyMed — Propylthiouracil Tablet [Par Health]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0c23a2c-b250-4c0d-9b2a-c1483faa2ca0',
   E'DailyMed — Propylthiouracil Tablet [Par Health]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b0c23a2c-b250-4c0d-9b2a-c1483faa2ca0'),

  ('piridoxina',
   E'Correção do défice de B6; restabelecimento do GABA neuronal na intoxicação por isoniazida.',
   E'Correction of B6 deficiency; restoration of neuronal GABA in isoniazid poisoning.',
   E'Precursor do piridoxal-5-fosfato (PLP), co-enzima da descarboxilase do ácido glutâmico (glutamato → GABA), da transaminase e da sintase do heme.',
   E'Precursor of pyridoxal-5-phosphate (PLP), co-enzyme of glutamic acid decarboxylase (glutamate → GABA), transaminase and heme synthase.',
   E'Fosforilação hepática e tecidual a PLP; oxidação a 4-piridóxico; excreção renal.',
   E'Hepatic and tissue phosphorylation to PLP; oxidation to 4-pyridoxic acid; renal excretion.',
   E'Absorção jejunal ativa (transportadores) e difusão passiva; biodisponibilidade alta; dose IV na urgência.',
   E'Jejunal active (transporter) and passive diffusion absorption; high bioavailability; IV dose in emergency.',
   E'~ 15–20 dias (reserva corporal); PLP ~ 1–3 dias.',
   E'~ 15–20 days (body stores); PLP ~ 1–3 days.',
   E'DailyMed — Pyridoxine (via rótulos VANTREX/LUNATAL e injetável): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3a1f0405-6983-410d-b625-54517a6a235f',
   E'DailyMed — Pyridoxine (via VANTREX/LUNATAL and injectable labels): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3a1f0405-6983-410d-b625-54517a6a235f'),

  ('acido-tranexamico',
   E'Bloqueio da fibrinólise: estancamento da hemorragia sem ativação generalizada da coagulação; ↓ mortalidade no trauma se < 3 h.',
   E'Fibrinolysis blockade: bleeding control without generalised coagulation activation; ↓ trauma mortality if < 3 h.',
   E'Análogo da lisina: liga-se ao domínio kringle-1/4 do plasminogénio, impedindo a sua ligação à fibrina e conversão a plasmina; inibe também a atividade da plasmina já formada.',
   E'Lysine analogue: binds the kringle-1/4 domain of plasminogen, preventing its binding to fibrin and conversion to plasmin; also inhibits already-formed plasmin activity.',
   E'Minimamente metabolizado (< 5%); excreção renal inalterada (ajustar na insuficiência renal).',
   E'Minimally metabolised (< 5%); unchanged renal excretion (adjust in renal failure).',
   E'Oral: 30–50% (saturável em dose alta); IV: 100%; volume de distribuição limitado (~ 9–12 L).',
   E'Oral: 30–50% (saturable at high dose); IV: 100%; limited volume of distribution (~ 9–12 L).',
   E'~ 2–3 h (IV); efeito antifibrinolítico mais longo.',
   E'~ 2–3 h (IV); longer antifibrinolytic effect.',
   E'DailyMed — Tranexamic Acid Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d97790f-048b-494d-aa22-5689643a724b',
   E'DailyMed — Tranexamic Acid Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d97790f-048b-494d-aa22-5689643a724b'),

  ('protamina',
   E'Neutralização da heparina em 30–60 s (1 mg neutraliza ~ 100 U); reversão parcial de HBPM.',
   E'Heparin neutralisation within 30–60 s (1 mg neutralises ~ 100 U); partial LMWH reversal.',
   E'Polipeptídeo catiónico que liga ionicamente o grupo sulfato ácido da heparina, formando complexo estável sem atividade anticoagulante.',
   E'Cationic polypeptide ionically binding the acidic sulphate group of heparin, forming a stable complex without anticoagulant activity.',
   E'Degradação por peptidases; metabolismo não completamente esclarecido; excreção renal.',
   E'Peptidase degradation; metabolism not fully elucidated; renal excretion.',
   E'IV exclusivo; ação imediata.',
   E'IV exclusive; immediate action.',
   E'~ 7–9 min (efeito clínico ~ 2 h).',
   E'~ 7–9 min (clinical effect ~ 2 h).',
   E'DailyMed — Protamine Sulfate Injection [Fresenius Kabi]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c76876da-b9a8-45d0-9278-7df3288d3a06',
   E'DailyMed — Protamine Sulfate Injection [Fresenius Kabi]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c76876da-b9a8-45d0-9278-7df3288d3a06'),

  ('cloreto-potassio',
   E'Restabelecimento do potássio sérico e intracelular; normalização do potencial de membrana neuromuscular e cardíaco.',
   E'Restoration of serum and intracellular potassium; normalisation of neuromuscular and cardiac membrane potential.',
   E'Eletrólito primário intracelular: mantém o gradiente de K+ pela Na/K-ATPase (3 Na+ out / 2 K+ in), estabilizando o potencial de repouso da membrana (~ −90 mV).',
   E'Primary intracellular electrolyte: maintains the K+ gradient via Na/K-ATPase (3 Na+ out / 2 K+ in), stabilising the membrane resting potential (~ −90 mV).',
   E'Não tem metabolismo; regulação renal rigorosa via aldosterona e pH; excreção renal (90%) e fecal.',
   E'No metabolism; strict renal regulation via aldosterone and pH; renal (90%) and faecal excretion.',
   E'Oral: absorção passiva intestinal 20–40%; formulações de liberação prolongada melhoram tolerância; IV: 100%.',
   E'Oral: passive intestinal absorption 20–40%; prolonged-release formulations improve tolerance; IV: 100%.',
   E'~ 1–1,5 h (oral); equilíbrio intracelular em 24–48 h.',
   E'~ 1–1.5 h (oral); intracellular equilibrium in 24–48 h.',
   E'DailyMed — Potassium Chloride Oral Solution: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=483f338e-a164-4c1f-a34e-fef3312cb7ec',
   E'DailyMed — Potassium Chloride Oral Solution: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=483f338e-a164-4c1f-a34e-fef3312cb7ec'),

  ('sulfato-magnesio',
   E'Anticonvulsivo na eclampsia (↓ convulsões em ~ 50% vs. diazepam/fenitoína); broncodilatação em asma grave; antiarrítmico em torsades.',
   E'Anticonvulsant in eclampsia (↓ seizures by ~ 50% vs. diazepam/phenytoin); bronchodilation in severe asthma; antiarrhythmic in torsades.',
   E'Antagonista fisiológico do Ca2+: bloqueia canais NMDA (neuroproteção) e canais de Ca2+ voltagem-dependentes (vasodilatação, broncodilatação); estabiliza o potencial de membrana.',
   E'Physiological Ca2+ antagonist: blocks NMDA channels (neuroprotection) and voltage-gated Ca2+ channels (vasodilation, bronchodilation); stabilises membrane potential.',
   E'Não tem metabolismo; excreção renal rápida (vida dependente da função renal).',
   E'No metabolism; rapid renal excretion (half-life kidney-function dependent).',
   E'IV: 100%; IM: ~ 90%; oral: má absorção (efeito laxante osmótico).',
   E'IV: 100%; IM: ~ 90%; oral: poor absorption (osmotic laxative effect).',
   E'~ 4–6 h (renal normal).',
   E'~ 4–6 h (normal kidneys).',
   E'DailyMed — Magnesium Sulfate (via rótulos hospitalares): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5b4b4805-a8ff-4efe-94bc-411090ab5f9c',
   E'DailyMed — Magnesium Sulfate (via hospital labels): https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5b4b4805-a8ff-4efe-94bc-411090ab5f9c'),

  ('gluconato-calcio',
   E'Estabilização miocárdica imediata (hiperpotassémia), correção da tetania e suporte de contratilidade.',
   E'Immediate myocardial stabilisation (hyperkalaemia), tetany correction and contractility support.',
   E'Fornece Ca2+ ionizado: ↑ gradiente electroquímico transmembranário, estabiliza canais de Na+ (hiperpotassémia), restaura a excitação-contração e inverte o bloqueio dos canais de Ca2+.',
   E'Provides ionised Ca2+: ↑ transmembrane electrochemical gradient, stabilises Na+ channels (hyperkalaemia), restores excitation-contraction and reverses calcium channel block.',
   E'Não tem metabolismo; distribuição extracelular; excreção renal regulada por PTH/vitamina D.',
   E'No metabolism; extracellular distribution; renal excretion regulated by PTH/vitamin D.',
   E'IV: 100%; oral: 10–30% (preferir carbonato para suplementação oral).',
   E'IV: 100%; oral: 10–30% (prefer carbonate for oral supplementation).',
   E'~ 30–60 min (efeito clínico de estabilização 30–120 min).',
   E'~ 30–60 min (clinical stabilisation effect 30–120 min).',
   E'DailyMed — Calcium Gluconate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=16307c00-d0d5-4e05-821f-17b0c1a29fc9',
   E'DailyMed — Calcium Gluconate Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=16307c00-d0d5-4e05-821f-17b0c1a29fc9'),

  ('n-acetilcisteina',
   E'Prevenção da hepatotoxicidade por paracetamol (NAPQI neutralizado); mucólise por quebra de dissulfuretos.',
   E'Prevention of paracetamol hepatotoxicity (NAPQI neutralised); mucolysis by disulphide breaking.',
   E'Doador de cisteína: ↑ glutatião hepático que conjuga o NAPQI (metabolito reativo do paracetamol) a mercapturato inofensivo. Mucolítico: rompe ligações dissulfureto das glicoproteínas do muco, reduzindo a viscosidade.',
   E'Cysteine donor: ↑ hepatic glutathione that conjugates NAPQI (paracetamol reactive metabolite) to harmless mercapturate. Mucolytic: breaks disulphide bonds of mucus glycoproteins, reducing viscosity.',
   E'Desacetilação a cisteína; metabolização por oxidases hepáticas e renais; excreção renal.',
   E'Deacetylation to cysteine; metabolism by hepatic and renal oxidases; renal excretion.',
   E'Oral: 6–10% (primeira passagem extensa — razão da preferência IV na sobredosagem); IV: 100%.',
   E'Oral: 6–10% (extensive first pass — reason for IV preference in overdose); IV: 100%.',
   E'~ 2–6 h (IV; dose-dependente).',
   E'~ 2–6 h (IV; dose-dependent).',
   E'DailyMed — Acetylcysteine Solution [Hospira]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586',
   E'DailyMed — Acetylcysteine Solution [Hospira]: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5558a5f5-e821-473b-7d8a-5d33d09f0586'),

  ('deferoxamina',
   E'Quelato Fe3+ livre e do ferritina/hemossiderina; excreção renal e biliar do ferrioxamina (urina cor de vinho).',
   E'Chelates free Fe3+ and ferritin/haemosiderin iron; renal and biliary excretion of ferrioxamine (wine-coloured urine).',
   E'Sideróforo bacteriano: ligação octaédrica de alta afinidade ao Fe3+ (log K ~ 31), formando ferrioxamina solúvel excretável. Não retira ferro da hemoglobina ou do citocromo.',
   E'Bacterial siderophore: high-affinity octahedral binding to Fe3+ (log K ~ 31), forming soluble excretable ferrioxamine. Does not remove iron from haemoglobin or cytochromes.',
   E'Metabolismo hepático por amina-oxidasas plasmáticas; excreção renal de ferrioxamina e biliar do ferro ligado.',
   E'Hepatic metabolism by plasma amine oxidases; renal excretion of ferrioxamine and biliary of bound iron.',
   E'Oral: < 15% (preferir SC/IM/IV); SC contínua otimiza a quelação do ferro hepático.',
   E'Oral: < 15% (prefer SC/IM/IV); continuous SC optimises hepatic iron chelation.',
   E'~ 20–30 min (SC/IM); ~ 5–10 min (IV).',
   E'~ 20–30 min (SC/IM); ~ 5–10 min (IV).',
   E'DailyMed — Deferoxamine Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d91e16df-8daa-4cd2-86a2-273eaa2446e0',
   E'DailyMed — Deferoxamine Injection: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d91e16df-8daa-4cd2-86a2-273eaa2446e0')
) AS v(slug, pharmacodynamics_pt, pharmacodynamics_en, mechanism_pt, mechanism_en,
       metabolism_pt, metabolism_en, absorption_pt, absorption_en, half_life_pt, half_life_en,
       source_pt, source_en)
  ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
