-- =====================================================================
-- 269 — Lote 4 (2/3): perfis em public.drug_profiles
-- ---------------------------------------------------------------------
-- 6 fármacos do Lote 4 (insulinas + excluídos DailyMed). Conteúdo
-- autoral PT/EN ancorado em EMC-UK (fonte primária deste lote),
-- DailyMed (insulinas: rótulos equivalentes) e Prontuário INFARMED.
-- Padrão 7.6: JOIN (VALUES) ON d.slug = v.slug + ON CONFLICT DO NOTHING.
-- Idempotente. Companheiras: 268 (drugs), 270 (farmacologia).
-- =====================================================================

INSERT INTO public.drug_profiles
  (drug_id, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
   indications_pt, indications_en, side_effects_pt, side_effects_en,
   precautions_pt, precautions_en, source_pt, source_en)
SELECT d.id, v.overview_public_pt, v.overview_public_en, v.overview_pro_pt, v.overview_pro_en,
       v.indications_pt, v.indications_en, v.side_effects_pt, v.side_effects_en,
       v.precautions_pt, v.precautions_en, v.source_pt, v.source_en
FROM public.drugs d
JOIN (VALUES
  ('insulina-regular',
   E'A insulina regular (Actrapid, Humulin R) é a insulina de ação rápida usada no tratamento da diabetes tipo 1 e tipo 2, e em situações agudas como a cetoacidose diabética. Age cerca de 30 minutos depois da injeção.',
   E'Regular insulin (Actrapid, Humulin R) is the fast-acting insulin used to treat type 1 and type 2 diabetes, and in acute situations such as diabetic ketoacidosis. It acts about 30 minutes after the injection.',
   E'Insulina humana solúvel (análoga à endógena): liga o recetor de insulina (tirosina-quinase) → translocação de GLUT4, ↑ captação de glicose no músculo/adiposo, ↑ glicogénese, ↓ gluconeogénese e glicogenólise hepática, ↑ lipogénese. Início 30 min, pico 1,5–3,5 h, duração 7–8 h por via SC.',
   E'Soluble human insulin (identical to endogenous): binds the insulin receptor (tyrosine kinase) → GLUT4 translocation, ↑ glucose uptake in muscle/adipose tissue, ↑ glycogenesis, ↓ hepatic gluconeogenesis and glycogenolysis, ↑ lipogenesis. Onset 30 min, peak 1.5–3.5 h, duration 7–8 h SC.',
   E'• Diabetes mellitus tipo 1 (e tipo 2 com falência de antidiabéticos orais)\n• Cetoacidose diabética (IV, com fluidos e potássio)\n• Controlo glicémico peri-operatório e em cuidados intensivos\n• Hiperglicemia aguda com descompensação',
   E'• Diabetes mellitus type 1 (and type 2 with oral antidiabetic failure)\n• Diabetic ketoacidosis (IV, with fluids and potassium)\n• Peri-operative and intensive care glycaemic control\n• Acute hyperglycaemia with decompensation',
   E'• Hipoglicemia (o efeito adverso mais importante): tremores, suores, confusão, perda de consciência\n• Lipodistrofia no local de injeção (rodizar zonas)\n• Reações alérgicas locais (rubor, inchaço)\n• Edema inicial de insulina\n• Ganho de peso\n• Procure ajuda imediata se houver suores com confusão ou perda de consciência (hipoglicemia grave).',
   E'• Hypoglycaemia (the most important adverse effect): tremor, sweating, confusion, loss of consciousness\n• Lipodystrophy at the injection site (rotate sites)\n• Local allergic reactions (redness, swelling)\n• Initial insulin oedema\n• Weight gain\n• Seek immediate help if sweating with confusion or loss of consciousness occurs (severe hypoglycaemia).',
   E'• Tomar 30 min antes das refeições (nunca depois)\n• Rotizar locais de injeção (absorção variável com lipodistrofia)\n• Os betabloqueantes mascaram sintomas de hipoglicemia (taquicardia) — Prontuário 8.4.1\n• Conservar em frigorífico (2–8 °C); congelada perde eficácia\n• Insulina regular é a única administrável IV (cetoacidose)',
   E'• Take 30 min before meals (never after)\n• Rotate injection sites (variable absorption with lipodystrophy)\n• Beta-blockers mask hypoglycaemia symptoms (tachycardia) — Prontuário 8.4.1\n• Store refrigerated (2–8 °C); frozen insulin loses efficacy\n• Regular insulin is the only one given IV (ketoacidosis)',
   E'EMC-UK — Actrapid 100 IU/ml, Solution for Injection in a vial (Novo Nordisk), SmPC: https://www.medicines.org.uk/emc/product/3849/smpc — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012), 8.4.1 Insulinas',
   E'EMC-UK — Actrapid 100 IU/ml, Solution for Injection in a vial (Novo Nordisk), SmPC: https://www.medicines.org.uk/emc/product/3849/smpc — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012), 8.4.1 Insulins'),

  ('insulina-nph',
   E'A insulina NPH (Insulatard, Humulin I) é a insulina de ação intermédia: começa a agir 1–2 horas depois da injeção e cobre as necessidades de insulina durante grande parte do dia. Usa-se normalmente combinada com insulina regular.',
   E'NPH insulin (Insulatard, Humulin I) is the intermediate-acting insulin: it starts acting 1–2 hours after the injection and covers insulin needs for most of the day. It is usually combined with regular insulin.',
   E'Insulina humana com protamina (isofânica): a ligação iónica à protamina retarda a dissociação e a absorção SC, prolongando o efeito. Início 1–2 h, pico 4–12 h, duração 18–24 h. Efeito adicional protamina-dependente (diabéticos em NPH têm maior risco de reação à protamina — ver perfil da protamina).',
   E'Human insulin with protamine (isophane): ionic binding to protamine delays dissociation and SC absorption, prolonging the effect. Onset 1–2 h, peak 4–12 h, duration 18–24 h. Protamine-related effect (NPH-treated diabetics have higher protamine reaction risk — see protamine profile).',
   E'• Diabetes mellitus tipo 1 e tipo 2 (controlo basal, 1–2×/dia)\n• Combinação com insulina regular (basal-bolus) na diabetes tipo 1\n• Manutenção do controlo glicémico entre refeições e à noite',
   E'• Diabetes mellitus type 1 and 2 (basal control, 1–2×/day)\n• Combination with regular insulin (basal-bolus) in type 1 diabetes\n• Glycaemic control between meals and overnight',
   E'• Hipoglicemia (frequentemente noturna ou antes da próxima refeição pelo pico de 4–12 h)\n• Lipodistrofia no local de injeção\n• Reações alérgicas locais\n• Ganho de peso\n• Edema de insulina\n• Procure ajuda imediata se houver suores noturnos com cefaleia ou confusão (hipoglicemia noturna).',
   E'• Hypoglycaemia (often overnight or before the next meal due to the 4–12 h peak)\n• Lipodystrophy at the injection site\n• Local allergic reactions\n• Weight gain\n• Insulin oedema\n• Seek immediate help if night sweats with headache or confusion occur (nocturnal hypoglycaemia).',
   E'• NUNCA administrar IV (só SC)\n• Suspensão: homogeneizar suavemente antes de carregar (não agitar vigorosamente)\n• Não misturar na mesma seringa com análogos ultra-rápidos (apenas com insulina regular)\n• Rodizar locais; injeção ao deitar cobre a noite\n• Vigiar glicemia noturna pelo risco de hipoglicemia do pico',
   E'• NEVER give IV (SC only)\n• Suspension: gently resuspend before loading (do not shake vigorously)\n• Do not mix in the same syringe with ultra-rapid analogues (only with regular insulin)\n• Rotate sites; bedtime injection covers the night\n• Monitor nocturnal glucose due to peak hypoglycaemia risk',
   E'EMC-UK — Insulatard 100 IU/ml, suspension for injection (Novo Nordisk), SmPC: https://www.medicines.org.uk/emc/product/3848/smpc — com referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012), 8.4.1 Insulinas ("fixação sobre uma proteína, como a protamina")',
   E'EMC-UK — Insulatard 100 IU/ml, suspension for injection (Novo Nordisk), SmPC: https://www.medicines.org.uk/emc/product/3848/smpc — with additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012), 8.4.1 Insulins ("binding to a protein such as protamine")'),

  ('flucloxacilina',
   E'Flucloxacilina é um antibiótico em cápsulas ou injetável usado para infeções por estafilococos dourado resistentes à penicilina: abcessos, furúnculos, celulite, impetigo e infeções de feridas.',
   E'Flucloxacillin is an antibiotic in capsules or injectable form used for infections by penicillin-resistant Staphylococcus aureus: abscesses, boils, cellulitis, impetigo and wound infections.',
   E'Isoxazolilpenicilina resistente às beta-lactamases estafilocócicas: o substituinte isoxazol bloqueia estericamente o sítio ativo da penicilinase, mantendo a atividade contra S. aureus sensível à meticilina. Liga as PBP e inibe a síntese da parede celular bacteriana.',
   E'Isoxazolyl penicillin resistant to staphylococcal beta-lactamases: the isoxazol substituent sterically blocks the penicillinase active site, maintaining activity against meticillin-sensitive S. aureus. Binds PBPs and inhibits bacterial cell wall synthesis.',
   E'• Infeções cutâneas e de tecidos moles por S. aureus (impetigo, celulite, furúnculos)\n• Abcessos e infeções de feridas\n• Osteomielite e artrite séptica estafilocócica (IV prolongado)\n• Endocardite estafilocócica sensível (com gentamicina)\n• Profilaxia peri-operatória em cirurgia ortopédica/cardíaca',
   E'• Skin and soft tissue infections by S. aureus (impetigo, cellulitis, boils)\n• Abscesses and wound infections\n• Staphylococcal osteomyelitis and septic arthritis (prolonged IV)\n• Sensitive staphylococcal endocarditis (with gentamicin)\n• Peri-operative prophylaxis in orthopaedic/cardiac surgery',
   E'• Náuseas, vómitos e diarreia\n• Colestase hepática e icterícia (uso prolongado, especialmente idosos e > 2 semanas)\n• Reações alérgicas (urticária → anafilaxia em alérgicos à penicilina)\n• Colite por Clostridioides difficile (raro)\n• Escurecimento da urina e dor abdominal (sinal de hepatite colestática)\n• Procure ajuda imediata se houver urticária generalizada, dificuldade em respirar, icterícia ou urina escura.',
   E'• Nausea, vomiting and diarrhoea\n• Cholestatic hepatitis and jaundice (prolonged use, especially elderly and > 2 weeks)\n• Allergic reactions (urticaria → anaphylaxis in penicillin-allergic patients)\n• Clostridioides difficile colitis (rare)\n• Dark urine and abdominal pain (cholestatic hepatitis sign)\n• Seek immediate help if widespread urticaria, breathing difficulty, jaundice or dark urine occurs.',
   E'• CONTRAINDICADO em alergia à penicilina\n• Tomar com o estômago vazio (a comida reduz a absorção)\n• Tratamentos > 2 semanas: vigiar função hepática\n• Dose ajustada na insuficiência renal grave\n• Comprimidos efervescentes: atenção ao sódio em hipertensos',
   E'• CONTRAINDICATED in penicillin allergy\n• Take on an empty stomach (food reduces absorption)\n• Treatment > 2 weeks: monitor liver function\n• Dose adjusted in severe renal impairment\n• Effervescent tablets: sodium caution in hypertensive patients',
   E'EMC-UK — Flucloxacillin 500 mg Capsules, hard (Brown & Burk), SmPC: https://www.medicines.org.uk/emc/product/12636/smpc — sem rótulo DailyMed (nunca comercializada nos EUA, regra 13.1); referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'EMC-UK — Flucloxacillin 500 mg Capsules, hard (Brown & Burk), SmPC: https://www.medicines.org.uk/emc/product/12636/smpc — no DailyMed label (never marketed in the USA, rule 13.1); additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)'),

  ('espectinomicina',
   E'Espectinomicina é um antibiótico injetável usado no tratamento da gonorreia, sobretudo quando há alergia às cefalosporinas ou resistência documentada. Aplica-se numa única injeção intramuscular profunda.',
   E'Spectinomycin is an injectable antibiotic used to treat gonorrhoea, especially when there is cephalosporin allergy or documented resistance. It is given as a single deep intramuscular injection.',
   E'Aminociclitol (aminoglicosídeo atípico) produzido por Streptomyces spectabilis: liga a subunidade 30S do ribossoma mas num sítio distante da estreptomicina, inibindo a síntese proteica de forma bactericida. Não liga o DNA ribossomal de forma dependente de força iónica (diferencia-se dos aminoglicosídeos clássicos).',
   E'Aminocyclitol (atypical aminoglycoside) produced by Streptomyces spectabilis: binds the 30S ribosomal subunit at a site distant from streptomycin, inhibiting protein synthesis bactericidally. Does not cause mRNA misreading (unlike classical aminoglycosides).',
   E'• Gonorreia aguda (uretral, cervical, retal) em dose única\n• Gonorreia em grávidas alérgicas às cefalosporinas (OMS)\n• Gonorreia com resistência documentada às cefalosporinas\n• Disseminação gonocócica (com doxiciclina de sequência)',
   E'• Acute gonorrhoea (urethral, cervical, rectal) as a single dose\n• Gonorrhoea in pregnant women allergic to cephalosporins (WHO)\n• Gonorrhoea with documented cephalosporin resistance\n• Disseminated gonococcal infection (with follow-up doxycycline)',
   E'• Dor no local da injeção IM\n• Urticária e febre\n• Tonturas e náuseas\n• Reações alérgicas (raro)\n• Ototoxicidade e nefrotoxicidade (muito raro em dose única)\n• Procure ajuda imediata se houver urticária generalizada ou dificuldade em respirar após a injeção.',
   E'• Pain at the IM injection site\n• Urticaria and fever\n• Dizziness and nausea\n• Allergic reactions (rare)\n• Ototoxicity and nephrotoxicity (very rare as a single dose)\n• Seek immediate help if widespread urticaria or breathing difficulty occurs after the injection.',
   E'• Não eficaz na sífilis ou clamídia — testar/tratar co-infeções\n• IM profunda no glúteo (nunca IV)\n• Dose única reduz adesão como barreira\n• Sem rótulo humano nos EUA/UK — uso segundo protocolos OMS/LNME',
   E'• Not effective against syphilis or chlamydia — test/treat co-infections\n• Deep IM in the gluteus (never IV)\n• Single dose removes adherence as a barrier\n• No human label in the USA/UK — use per WHO/LNME protocols',
   E'Sem rótulo humano DailyMed/EMC (retirada dos mercados americano e britânico) — fonte primária: Prontuário Terapêutico do INFARMED (11.ª ed., 2012) e protocolos OMS de ITS; contexto de classe (aminoglicosídeos): EMC-UK — Gentamicin SmPC: https://www.medicines.org.uk/emc/product/3892/smpc',
   E'No human DailyMed/EMC label (withdrawn from US and UK markets) — primary source: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012) and WHO STI protocols; class context (aminoglycosides): EMC-UK — Gentamicin SmPC: https://www.medicines.org.uk/emc/product/3892/smpc'),

  ('permanganato-potassio',
   E'Permanganato de potássio é um antisséptico em cristais ou comprimidos que se dissolve em água para banhos e compressas em lesões da pele: feridas com cheiro, eczema com exsudação, micoses dos pés e picadas.',
   E'Potassium permanganate is an antiseptic in crystals or tablets dissolved in water for soaks and compresses in skin lesions: smelly wounds, weeping eczema, athlete\u2019s foot and bites.',
   E'Agente oxidante forte: em contacto com a pele oxida proteínas e estruturas bacterianas/fúngicas (ação antisséptica e deodorizante) e precipita proteínas superficiais (efeito astringente que seca a exsudação). Diluído a 1:10.000 (0,01%) — a solução deve ficar rosa-claro; concentrações superiores queimam a pele.',
   E'Strong oxidising agent: on contact with skin it oxidises proteins and bacterial/fungal structures (antiseptic and deodorising action) and precipitates surface proteins (astringent effect that dries exudation). Diluted 1:10,000 (0.01%) — the solution should be pale pink; higher concentrations burn the skin.',
   E'• Eczema com exsudação/bolhas (banhos e compressas)\n• Feridas exsudativas e mal cheirosas\n• Tinea pedis (pé de atleta) intertriginosa\n• Piodermites superficiais (adjuvante de limpeza)\n• Úlceras de perna com exsudação',
   E'• Weeping/blistering eczema (soaks and compresses)\n• Exudative and smelly wounds\n• Intertriginous tinea pedis (athlete\u2019s foot)\n• Superficial pyodermas (cleaning adjuvant)\n• Exudative leg ulcers',
   E'• Queimaduras e irritação se mal diluído (cristais não dissolvidos queimam)\n• Manchas castanhas temporárias na pele e unhas\n• Ressecamento e dermatite de contato (uso prolongado)\n• Toxidade sistémica grave se ingerido (perforação gástrica, metemoglobinemia)\n• Procure ajuda imediata se for ingerido — NUNCA usar por via oral.',
   E'• Burns and irritation if poorly diluted (undissolved crystals burn)\n• Temporary brown staining of skin and nails\n• Drying and contact dermatitis (prolonged use)\n• Serious systemic toxicity if swallowed (gastric perforation, methaemoglobinaemia)\n• Seek immediate help if ingested — NEVER use orally.',
   E'• USO EXTERNO exclusivo; nunca ingerir\n• Diluir até rosa-claro pálido (1:10.000; 0,01%); deixar dissolver completamente antes de imergir\n• Não aplicar em peles secas ou exsudativas sem orientação (ressecamento)\n• Preparação farmacêutica individual dos cristais (diluição errada = queimaduras)',
   E'• EXTERNAL USE only; never ingest\n• Dilute to pale pink (1:10,000; 0.01%); let crystals dissolve completely before immersing\n• Do not apply to dry or non-exudative skin without guidance (drying)\n• Pharmaceutical compounding of crystals (wrong dilution = burns)',
   E'BNF — Potassium permanganate (external use only): https://bnf.nice.org.uk/drugs/potassium-permanganate/ — sem rótulo DailyMed (regra 13.1); referências adicionais: SPS NHS (uso tópico seguro): https://www.sps.nhs.uk/articles/using-potassium-permanganate-for-skin-conditions-or-wound-care/ — Prontuário Terapêutico do INFARMED (11.ª ed., 2012): solução a 1:10.000 em eczema exsudativo',
   E'BNF — Potassium permanganate (external use only): https://bnf.nice.org.uk/drugs/potassium-permanganate/ — no DailyMed label (rule 13.1); additional references: NHS SPS (safe topical use): https://www.sps.nhs.uk/articles/using-potassium-permanganate-for-skin-conditions-or-wound-care/ — Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012): 1:10,000 solution in weeping eczema'),

  ('ciproterona',
   E'Acetato de ciproterona é um medicamento antiandrogénio que reduz o efeito dos hormonas masculinos. Usado em mulheres para acne grave e pêlo excessivo (com etinilestradiol) e em homens para puberdade precoce, parafilia e cancro da próstata.',
   E'Cyproterone acetate is an antiandrogen medicine that reduces the effect of male hormones. Used in women for severe acne and excess hair (with ethinylestradiol) and in men for precocious puberty, paraphilia and prostate cancer.',
   E'Antiandrogénio esteróide: bloqueia o recetor de androgénios nos tecidos-alvo (pele, próstata) e suprime a libertação de LH/FSH (efeito progestagénio central) → ↓ testosterona e ↓ produção de sebo. A combinação com etinilestradiol (co-cyprindiol) regulariza o ciclo e protege o endométrio.',
   E'Steroidal antiandrogen: blocks the androgen receptor in target tissues (skin, prostate) and suppresses LH/FSH release (central progestogenic effect) → ↓ testosterone and ↓ sebum production. The combination with ethinylestradiol (co-cyprindiol) regularises the cycle and protects the endometrium.',
   E'• Acne moderado/grave e hirsutismo em mulheres (co-cyprindiol, 2ª linha)\n• Puberdade precoce periférica em raparigas\n• Parafilia e desvio de impulsos sexuais em homens (alta dose)\n• Cancro da próstata avançado (alta dose, com GnRH)',
   E'• Moderate/severe acne and hirsutism in women (co-cyprindiol, 2nd line)\n• Peripheral precocious puberty in girls\n• Paraphilia and sexual impulse disorders in men (high dose)\n• Advanced prostate cancer (high dose, with GnRH)',
   E'• Trombose venosa (co-cyprindiol: risco comparável ao contraceptivo estroprogestativo)\n• Ganho de peso e mastalgia (mulheres)\n• Diminuição da libido e infertilidade reversível (homens)\n• Ginecomastia\n• Hepatotoxicidade (uso prolongado em alta dose): icterícia, tumores hepáticos benignos (raro)\n• Hiperglicemia\n• Procure ajuda imediata se houver dor de perna com inchaço, dor torácica súbita ou icterícia.',
   E'• Venous thrombosis (co-cyprindiol: risk comparable to oestrogen-progestogen contraceptives)\n• Weight gain and breast tenderness (women)\n• Decreased libido and reversible infertility (men)\n• Gynaecomastia\n• Hepatotoxicity (prolonged high-dose use): jaundice, benign liver tumours (rare)\n• Hyperglycaemia\n• Seek immediate help if leg pain with swelling, sudden chest pain or jaundice occurs.',
   E'• CONTRAINDICADO em trombose prévia, doença hepática e gravidez\n• Co-cyprindiol: 2ª linha para acne (após tópicos e antibióticos) — MHRA/EMC\n• Suspender 4 semanas antes de cirurgias com risco trombótico\n• Vigiar função hepática em alta dose prolongada\n• Em homens: informar sobre reversibilidade da infertilidade e possível esterilidade temporária',
   E'• CONTRAINDICATED in previous thrombosis, liver disease and pregnancy\n• Co-cyprindiol: 2nd line for acne (after topicals and antibiotics) — MHRA/EMC\n• Stop 4 weeks before thrombotic-risk surgery\n• Monitor liver function in prolonged high-dose use\n• In men: counsel on reversible infertility and possible temporary sterility',
   E'EMC-UK — Co-cyprindiol 2000/35 microgram Film-coated Tablets (Morningside Healthcare), SmPC: https://www.medicines.org.uk/emc/product/9760/smpc — sem rótulo DailyMed (regra 13.1); referência adicional: Prontuário Terapêutico do INFARMED (11.ª ed., 2012)',
   E'EMC-UK — Co-cyprindiol 2000/35 microgram Film-coated Tablets (Morningside Healthcare), SmPC: https://www.medicines.org.uk/emc/product/9760/smpc — no DailyMed label (rule 13.1); additional reference: Prontuário Terapêutico do INFARMED, INFARMED (11th ed., 2012)')
) AS v(slug, overview_public_pt, overview_public_en, overview_pro_pt, overview_pro_en,
       indications_pt, indications_en, side_effects_pt, side_effects_en,
       precautions_pt, precautions_en, source_pt, source_en)
  ON d.slug = v.slug
ON CONFLICT (drug_id) DO NOTHING;
