-- =====================================================================
-- 277 — Interações fármaco-doença (Fluxo 2) para o LOTE 1 (23 fármacos)
-- ---------------------------------------------------------------------
-- Auditoria 2026-09-30: nenhum dos 23 fármacos do Lote 1 (migrações
-- 255–258) tinha registos em drug_disease_interactions. Esta migração
-- adiciona os pares clinicamente mais relevantes, reutilizando
-- exclusivamente condition_slug já existentes no vocabulário da BD.
--
-- Fontes: Prontuário Terapêutico INFARMED (grupos 1.4 Antiparasitários,
-- 7.2 Uterotónicos, 8.2.2 Corticosteróides, 10.1 Anti-histamínicos,
-- 6.3 Antituberculosos, fichas individuais) + EMC-UK SmPC onde indicado.
--
-- Idempotência: ON CONFLICT (drug_id, condition_slug) DO NOTHING.
-- Cobertura: 20 fármacos × 1–5 condições = 50 pares
-- (26 contraindication, 24 precaution).
-- Fármacos sem pares (clotrimazol, tiamina): justificados no fim.
-- Exclusões justificadas no fim.
-- =====================================================================

INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en,
   interaction_type, severity, reason_pt, reason_en,
   advice_pt, advice_en, source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en,
       v.interaction_type, v.severity, v.reason_pt, v.reason_en,
       v.advice_pt, v.advice_en, v.source_pt, v.source_en,
       v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  -- ---------------- ALBENDAZOL ----------------
  ('albendazol', 'gravidez', 'Gravidez', 'Pregnancy',
   'contraindication', 'moderate',
   'O albendazol é teratogénico em animais no 1.º trimestre — contra-indicado na gravidez excepto benefício claro.',
   'Albendazole is teratogenic in animals in the 1st trimester — contraindicated in pregnancy unless clear benefit.',
   'Contracepção eficaz durante o tratamento e 1 mês depois; desparasitação em massa: evitar em grávidas.',
   'Effective contraception during treatment and for 1 month after; mass deworming: avoid in pregnant women.',
   'Prontuário Terapêutico INFARMED, 1.4.1 (albendazol — teratogenicidade); OMS desparasitação em massa.',
   'Prontuário Terapêutico INFARMED, 1.4.1 (albendazole — teratogenicity); WHO mass deworming guidance.', 1),
  ('albendazol', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'moderate',
   'O metabolismo hepático produz o metabolismo activo (sulfóxido); na doença hepática a exposição aumenta e o risco de hepatotoxicidade também.',
   'Hepatic metabolism produces the active sulfoxide; in liver disease exposure rises and so does hepatotoxicity risk.',
   'Monitorizar transaminases em cursos longos; suspender se elevação > 2–3× LSN.',
   'Monitor transaminases in long courses; discontinue if elevation > 2–3× ULN.',
   'Prontuário Terapêutico INFARMED, 1.4.1 (albendazol — monitorização hepática em cursos longos).',
   'Prontuário Terapêutico INFARMED, 1.4.1 (albendazole — hepatic monitoring in long courses).', 2),
  -- ---------------- MEBENDAZOL ----------------
  ('mebendazol', 'gravidez', 'Gravidez', 'Pregnancy',
   'contraindication', 'moderate',
   'Contra-indicado no 1.º trimestre da gravidez; em infestações em massa, adiar para o 2.º/3.º trimestres.',
   'Contraindicated in the 1st trimester of pregnancy; in mass treatment, defer to the 2nd/3rd trimesters.',
   'Adiar tratamento após o 1.º trimestre; contracepção durante o tratamento.',
   'Defer treatment until after the 1st trimester; contraception during treatment.',
   'Prontuário Terapêutico INFARMED, 1.4.1 (mebendazol — 1.º trimestre).',
   'Prontuário Terapêutico INFARMED, 1.4.1 (mebendazole — 1st trimester).', 1),
  -- ---------------- IVERMECTINA ----------------
  ('ivermectina', 'gravidez', 'Gravidez', 'Pregnancy',
   'contraindication', 'moderate',
   'Os dados de segurança na gravidez são limitados — não usar excepto se os riscos da doença justificarem.',
   'Safety data in pregnancy are limited — do not use unless disease risk justifies it.',
   'Adiar tratamento em mulheres grávidas; contracepção durante o tratamento.',
   'Defer treatment in pregnant women; contraception during treatment.',
   'Prontuário/OMS (ivermectina — segurança fetal não estabelecida); EMC-UK ivermectina SmPC 4.6.',
   'Prontuário/WHO (ivermectin — fetal safety not established); EMC-UK ivermectin SmPC 4.6.', 1),
  ('ivermectina', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'minor',
   'O metabolismo hepático reduz a clarificação — precaução na doença hepática.',
   'Hepatic metabolism reduces clearance — caution in liver disease.',
   'Avaliar função hepática se cursos repetidos.',
   'Assess liver function with repeated courses.',
   'EMC-UK — ivermectin SmPC 4.4 (hepatic impairment).',
   'EMC-UK — ivermectin SmPC 4.4 (hepatic impairment).', 2),
  ('ivermectina', 'doenca_snc', 'Doença do SNC ativa', 'Active CNS disease',
   'precaution', 'critical',
   'A ivermectina só deve ser usada com grande precaução quando a barreira hematoencefálica pode estar comprometida (meningite, tripanossomíase) — risco de depressão do SNC.',
   'Ivermectin should only be used with great caution when the blood–brain barrier may be compromised (meningitis, trypanosomiasis) — risk of CNS depression.',
   'Confirmar ausência de doença do SNC activa antes de doses elevadas.',
   'Confirm absence of active CNS disease before high doses.',
   'Prontuário Terapêutico INFARMED, 1.4 (ivermectina — BHE comprometida).',
   'Prontuário Terapêutico INFARMED, 1.4 (ivermectin — compromised BBB).', 3),
  -- ---------------- PIRANTEL ----------------
  ('pirantel', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'minor',
   'O pirantel é metabolizado no fígado — precaução na doença hepática.',
   'Pyrantel is hepatically metabolised — caution in liver disease.',
   'Considerar alternativas na doença hepática grave.',
   'Consider alternatives in severe liver disease.',
   'Prontuário Terapêutico INFARMED, 1.4.2 (pirantel — farmacocinética hepática).',
   'Prontuário Terapêutico INFARMED, 1.4.2 (pyrantel — hepatic pharmacokinetics).', 1),
  -- ---------------- OXITOCINA ----------------
  ('oxitocina', 'hipertensao', 'Hipertensão', 'Hypertension',
   'precaution', 'moderate',
   'A oxitocina tem fraca actividade anti-diurética e vasodilatadora mas pode causar hipotensão/taquicardia; vigilância obstétrica obrigatória.',
   'Oxytocin has weak antidiuretic and vasodilatory activity but may cause hypotension/tachycardia; obstetric monitoring mandatory.',
   'Perfusão diluída com monitorização CTG e tensão arterial contínuas.',
   'Diluted infusion with continuous CTG and blood pressure monitoring.',
   'Prontuário Terapêutico INFARMED, 7.2 (ocitocina — monitorização obstétrica contínua, CTG).',
   'Prontuário Terapêutico INFARMED, 7.2 (oxytocin — continuous obstetric monitoring, CTG).', 1),
  -- ---------------- MISOPROSTOL ----------------
  ('misoprostol', 'gravidez', 'Gravidez', 'Pregnancy',
   'contraindication', 'critical',
   'O misoprostol é abortífero — CONTRAINDICADO na gravidez quando usado para gastroproteção.',
   'Misoprostol is abortifacient — CONTRAINDICATED in pregnancy when used for gastroprotection.',
   'Excluir gravidez antes de prescrever como gastroprotetor; contracepção fiável durante o tratamento com AINE + misoprostol.',
   'Exclude pregnancy before prescribing as gastroprotectant; reliable contraception during NSAID + misoprostol therapy.',
   'Prontuário Terapêutico INFARMED (misoprostol — abortífero); ficha do site (contraindicado na gravidez).',
   'Prontuário Terapêutico INFARMED (misoprostol — abortifacient); site monograph (contraindicated in pregnancy).', 1),
  -- ---------------- METILERGOMETRINA ----------------
  ('metilergometrina', 'hipertensao', 'Hipertensão', 'Hypertension',
   'contraindication', 'critical',
   'A metilergometrina é contra-indicada na hipertensão e pré-eclâmpsia — vasoconstrição intensa agrava a tensão arterial.',
   'Methylergometrine is contraindicated in hypertension and pre-eclampsia — intense vasoconstriction raises blood pressure further.',
   'Medir tensão antes de cada dose no pós-parto; alternativas: ocitocina.',
   'Measure blood pressure before each dose postpartum; alternatives: oxytocin.',
   'Prontuário Terapêutico INFARMED, 7.2 (metilergometrina — contra-indicada em hipertensão, pré-eclâmpsia e doença vascular oclusiva); ficha do site.',
   'Prontuário Terapêutico INFARMED, 7.2 (methylergometrine — contraindicated in hypertension, pre-eclampsia and occlusive vascular disease); site monograph.', 1),
  ('metilergometrina', 'doenca_cardiovascular', 'Doença cardiovascular (enfarte, AVC)', 'Cardiovascular disease (MI, stroke)',
   'contraindication', 'critical',
   'Contra-indicada em doença vascular oclusiva — risco de vasospasmo, angina e isquemia periférica.',
   'Contraindicated in occlusive vascular disease — risk of vasospasm, angina and peripheral ischaemia.',
   'Não usar em cardiopatas no pós-parto; preferir ocitocina.',
   'Do not use in cardiac patients postpartum; prefer oxytocin.',
   'EMC-UK — Ergometrine Injection BP (product/6265) § 4.3 (doença vascular oclusiva, angina/infarto).',
   'EMC-UK — Ergometrine Injection BP (product/6265) § 4.3 (occlusive vascular disease, angina/MI).', 2),
  ('metilergometrina', 'gravidez', 'Gravidez', 'Pregnancy',
   'contraindication', 'critical',
   'Contra-indicada durante a gravidez antes do descolamento da placenta — provoca contracções tónicas e pode lesar o feto.',
   'Contraindicated during pregnancy before placental separation — causes tonic contractions and may harm the fetus.',
   'Apenas após a expulsão da placenta (profilaxia/tratamento da HPP).',
   'Only after placental delivery (prevention/treatment of PPH).',
   'Prontuário Terapêutico INFARMED, 7.2 (metilergometrina — gravidez antes do descolamento).',
   'Prontuário Terapêutico INFARMED, 7.2 (methylergometrine — pregnancy before separation).', 3),
  -- ---------------- METILDOPA ----------------
  ('metildopa', 'doenca_hepatica_ativa', 'Doença hepática ativa', 'Active liver disease',
   'contraindication', 'critical',
   'A metildopa causa hepatite induzida — contra-indicada na doença hepática activa e após hepatite prévia pelo fármaco.',
   'Methyldopa causes drug-induced hepatitis — contraindicated in active liver disease and after prior drug hepatitis.',
   'Excluir doença hepática activa antes de iniciar; monitorizar transaminases nos primeiros meses.',
   'Exclude active liver disease before starting; monitor transaminases in the first months.',
   'Prontuário Terapêutico INFARMED, 7.3 (metildopa — hepatite induzida, precaução hepática).',
   'Prontuário Terapêutico INFARMED, 7.3 (methyldopa — drug-induced hepatitis, hepatic precaution).', 1),
  ('metildopa', 'depressao', 'Depressão', 'Depression',
   'precaution', 'moderate',
   'A metildopa pode causar/agravar depressão (efeito central) — precaução em doentes com história depressiva.',
   'Methyldopa may cause/worsen depression (central effect) — caution in patients with depressive history.',
   'Vigiar humor; considerar alternativas anti-hipertensivas se depressão activa.',
   'Monitor mood; consider alternative antihypertensives if active depression.',
   'Prontuário Terapêutico INFARMED, 7.3 (metildopa — depressão como reação adversa).',
   'Prontuário Terapêutico INFARMED, 7.3 (methyldopa — depression as adverse reaction).', 2),
  ('metildopa', 'feocromocitoma', 'Feocromocitoma', 'Phaeochromocytoma',
   'contraindication', 'critical',
   'Contra-indicada no feocromocitoma — pode interferir com a dosagem de catecolaminas e destabilizar a tensão.',
   'Contraindicated in phaeochromocytoma — may interfere with catecholamine assays and destabilise blood pressure.',
   'Excluir feocromocitoma antes de iniciar terapêutica anti-hipertensora central.',
   'Exclude phaeochromocytoma before starting central antihypertensive therapy.',
   'Prontuário/EMC-UK — metildopa SmPC 4.3 (feocromocitoma).',
   'Prontuário/EMC-UK — methyldopa SmPC 4.3 (phaeochromocytoma).', 3),
  -- ---------------- HIDRALAZINA ----------------
  ('hidralazina', 'cardiopatia_isquemica', 'Cardiopatia isquémica', 'Ischaemic heart disease',
   'precaution', 'moderate',
   'A hidralazina causa taquicardia reflexa — precaução em cardiopatia isquémica e disseção de aneurisma.',
   'Hydralazine causes reflex tachycardia — caution in ischaemic heart disease and aneurysm dissection.',
   'Associar sempre a betabloqueador para atenuar taquicardia reflexa.',
   'Always combine with a beta-blocker to blunt reflex tachycardia.',
   'Prontuário Terapêutico INFARMED, 7.3 (hidralazina — precaução em cardiopatia isquémica, disseção de aneurisma).',
   'Prontuário Terapêutico INFARMED, 7.3 (hydralazine — caution in ischaemic heart disease, aneurysm dissection).', 1),
  ('hidralazina', 'insuficiencia_cardiaca', 'IC descompensada', 'Decompensated HF',
   'precaution', 'moderate',
   'A retenção de sódio e taquicardia podem descompensar IC — precaução; associar diurético.',
   'Sodium retention and tachycardia may decompensate HF — caution; combine with diuretic.',
   'Não usar isolada em IC; associar diurético e/ou betabloqueador.',
   'Do not use alone in HF; combine with diuretic and/or beta-blocker.',
   'Prontuário Terapêutico INFARMED, 7.3 (hidralazina — retenção de sódio, taquicardia reflexa).',
   'Prontuário Terapêutico INFARMED, 7.3 (hydralazine — sodium retention, reflex tachycardia).', 2),
  -- ---------------- LIDOCAÍNA ----------------
  ('lidocaina', 'bloqueio_av', 'Bloqueio auriculoventricular', 'Atrioventricular block',
   'contraindication', 'critical',
   'A lidocaína IV (antiarrítmica classe Ib) está contra-indicada em bloqueio AV de 2.º/3.º grau (depressão da condução).',
   'IV lidocaine (class Ib antiarrhythmic) is contraindicated in 2nd/3rd-degree AV block (conduction depression).',
   'ECG antes de perfusão IV; uso tópico/infiltração não é afectado.',
   'ECG before IV infusion; topical/infiltration use is unaffected.',
   'Prontuário Terapêutico INFARMED, 3.1 (lidocaína IV — bloqueio AV).',
   'Prontuário Terapêutico INFARMED, 3.1 (IV lidocaine — AV block).', 1),
  ('lidocaina', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'moderate',
   'A lidocaína é fortemente metabolizada no fígado — a doença hepática reduz a clarificação e eleva o risco de toxicidade do SNC.',
   'Lidocaine is extensively hepatically metabolised — liver disease reduces clearance and raises CNS toxicity risk.',
   'Reduzir dose em insuficiência hepática; vigiar sinais de toxicidade do SNC.',
   'Reduce dose in hepatic impairment; monitor for CNS toxicity signs.',
   'Prontuário Terapêutico INFARMED (lidocaína — metabolismo hepático, reduzir dose).',
   'Prontuário Terapêutico INFARMED (lidocaine — hepatic metabolism, dose reduction).', 2),
  ('lidocaina', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'moderate',
   'A toxicidade sistémica da lidocaína manifesta-se com convulsões — precaução em epilépticos.',
   'Systemic lidocaine toxicity manifests with seizures — caution in epileptics.',
   'Respeitar dose máxima (3 mg/kg sem epinefrina); aspirar antes de injetar.',
   'Respect maximum dose (3 mg/kg without epinephrine); aspirate before injecting.',
   'Prontuário/ficha do site (lidocaína — dose máxima, toxicidade do SNC).',
   'Prontuário/site monograph (lidocaine — maximum dose, CNS toxicity).', 3),
  -- ---------------- MIDAZOLAM ----------------
  ('midazolam', 'depressao_respiratoria', 'Depressão respiratória / doença pulmonar grave', 'Respiratory depression / severe lung disease',
   'contraindication', 'critical',
   'O midazolam deprime a respiração — contra-indicado em insuficiência respiratória grave não ventilada.',
   'Midazolam depresses respiration — contraindicated in severe unventilated respiratory impairment.',
   'Usar apenas com monitorização SpO2 e suporte de via aérea disponível.',
   'Use only with SpO2 monitoring and airway support available.',
   'Ficha do site (midazolam — via aérea obrigatória); EMC-UK midazolam SmPC 4.3/4.4.',
   'Site monograph (midazolam — mandatory airway); EMC-UK midazolam SmPC 4.3/4.4.', 1),
  ('midazolam', 'miastenia_gravis', 'Miastenia gravis', 'Myasthenia gravis',
   'contraindication', 'critical',
   'Os benzodiazepinas agravam a fraqueza muscular na miastenia — contra-indicados.',
   'Benzodiazepines worsen muscle weakness in myasthenia — contraindicated.',
   'Se sedação inevitável, garantir suporte ventilatório.',
   'If sedation unavoidable, ensure ventilatory support.',
   'EMC-UK — midazolam SmPC 4.3 (miastenia gravis).',
   'EMC-UK — midazolam SmPC 4.3 (myasthenia gravis).', 2),
  ('midazolam', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment',
   'precaution', 'moderate',
   'Acumulação do metabólito glucuronizado e agravamento da sedação na insuficiência renal.',
   'Accumulation of the glucuronidated metabolite and worsened sedation in renal impairment.',
   'Titular lentamente; dose reduzida em idosos e nefropatas.',
   'Titrate slowly; reduced dose in elderly and renally impaired.',
   'EMC-UK — midazolam SmPC 4.4 (insuficiência renal).',
   'EMC-UK — midazolam SmPC 4.4 (renal impairment).', 3),
  -- ---------------- ATROPINA ----------------
  ('atropina', 'glaucoma', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma',
   'contraindication', 'critical',
   'Os antimuscarínicos dilatam a pupila e precipitam crise de glaucoma de ângulo fechado.',
   'Antimuscarinics dilate the pupil and precipitate angle-closure glaucoma attacks.',
   'Excluir glaucoma de ângulo fechado antes de qualquer uso.',
   'Exclude angle-closure glaucoma before any use.',
   'Prontuário Terapêutico INFARMED, 10.1 (efeitos antimuscarínicos — glaucoma de ângulo fechado); ficha do site (atropina).',
   'Prontuário Terapêutico INFARMED, 10.1 (antimuscarinic effects — angle-closure glaucoma); site monograph (atropine).', 1),
  ('atropina', 'hipertrofia_prostatica', 'Hipertrofia prostática benigna', 'Benign prostatic hyperplasia',
   'precaution', 'moderate',
   'Os antimuscarínicos aumentam a retenção urinária na hipertrofia prostática.',
   'Antimuscarinics increase urinary retention in prostatic hyperplasia.',
   'Perguntar por sintomas urinários; evitar em retenção prévia.',
   'Ask about urinary symptoms; avoid if previous retention.',
   'Prontuário Terapêutico INFARMED, 10.1 (antimuscarínicos — retenção urinária, hiperplasia prostática).',
   'Prontuário Terapêutico INFARMED, 10.1 (antimuscarinics — urinary retention, prostatic hyperplasia).', 2),
  -- ---------------- CLORPROMAZINA ----------------
  ('clorpromazina', 'doenca_parkinson', 'Doença de Parkinson', 'Parkinson''s disease',
   'contraindication', 'moderate',
   'A clorpromazina bloqueia D2 e agravam os sintomas extrapiramidais do Parkinson.',
   'Chlorpromazine blocks D2 and worsens Parkinson''s extrapyramidal symptoms.',
   'Evitar; se antipsicótico necessário, preferir quinpiramina/atipicos sob supervisão.',
   'Avoid; if antipsychotic needed, prefer atypicals under supervision.',
   'Prontuário Terapêutico INFARMED (fenotiazinas — doença de Parkinson).',
   'Prontuário Terapêutico INFARMED (phenothiazines — Parkinson''s disease).', 1),
  ('clorpromazina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation',
   'contraindication', 'critical',
   'A clorpromazina prolonga o QT — contra-indicada em QT longo prévio ou com fármacos que prolongam o QT.',
   'Chlorpromazine prolongs QT — contraindicated with pre-existing long QT or with QT-prolonging drugs.',
   'ECG basal e em doses altas; rever todos os prolongadores do QT.',
   'Baseline ECG and at high doses; review all QT prolongers.',
   'Ficha do site (clorpromazina — precaução com prolongadores do QT).',
   'Site monograph (chlorpromazine — caution with QT prolongers).', 2),
  ('clorpromazina', 'porfiria', 'Porfiria', 'Porphyria',
   'contraindication', 'moderate',
   'As fenotiazinas não são seguras na porfiria — risco de crise aguda.',
   'Phenothiazines are not safe in porphyria — risk of acute crisis.',
   'Confirmar diagnóstico de porfiria antes de prescrever.',
   'Confirm porphyria diagnosis before prescribing.',
   'Prontuário Terapêutico INFARMED, 10.1 (porfiria — anti-histamínicos/fenotiazinas não seguros).',
   'Prontuário Terapêutico INFARMED, 10.1 (porphyria — antihistamines/phenothiazines not safe).', 3),
  ('clorpromazina', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'moderate',
   'A clorpromazina reduz o limiar convulsivo — precaução em epilépticos.',
   'Chlorpromazine lowers the seizure threshold — caution in epileptics.',
   'Manter antiepilépticos; vigiar convulsões.',
   'Maintain antiepileptics; monitor for seizures.',
   'Prontuário Terapêutico INFARMED (fenotiazinas — limiar convulsivo).',
   'Prontuário Terapêutico INFARMED (phenothiazines — seizure threshold).', 4),
  -- ---------------- PROMETAZINA ----------------
  ('prometazina', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'moderate',
   'As convulsões podem ser precipitadas pelos anti-histamínicos sedativos — não recomenda a sua administração nas crianças com epilepsia (Prontuário 10.1).',
   'Seizures can be precipitated by sedating antihistamines — not recommended in children with epilepsy (Prontuário 10.1).',
   'Evitar em epilepsia mal controlada; vigiar convulsões.',
   'Avoid in poorly controlled epilepsy; monitor for seizures.',
   'Prontuário Terapêutico INFARMED, 10.1: "As convulsões podem também ser precipitadas... crianças com epilepsia".',
   'Prontuário Terapêutico INFARMED, 10.1: "Seizures can also be precipitated... children with epilepsy".', 1),
  ('prometazina', 'porfiria', 'Porfiria', 'Porphyria',
   'precaution', 'moderate',
   'Os anti-histamínicos sedativos não são considerados seguros na porfiria (Prontuário 10.1 nota).',
   'Sedating antihistamines are not considered safe in porphyria (Prontuário 10.1 note).',
   'Preferir cetirizina/clorfenoxamina se anti-histamínico necessário (considerados seguros).',
   'Prefer cetirizine/chlorphenoxamine if antihistamine needed (considered safe).',
   'Prontuário Terapêutico INFARMED, 10.1: "a clorfenoxamina e a cetirizina pareçam seguros na porfiria".',
   'Prontuário Terapêutico INFARMED, 10.1: "chlorphenoxamine and cetirizine seem safe in porphyria".', 2),
  ('prometazina', 'glaucoma_angulo_fechado', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma',
   'precaution', 'moderate',
   'Efeitos antimuscarínicos dos anti-histamínicos sedativos — boca seca, retenção urinária, glaucoma de ângulo fechado (Prontuário 10.1).',
   'Antimuscarinic effects of sedating antihistamines — dry mouth, urinary retention, angle-closure glaucoma (Prontuário 10.1).',
   'Evitar em glaucoma de ângulo fechado não operado.',
   'Avoid in unoperated angle-closure glaucoma.',
   'Prontuário Terapêutico INFARMED, 10.1 (efeitos antimuscarínicos dos anti-histamínicos).',
   'Prontuário Terapêutico INFARMED, 10.1 (antimuscarinic effects of antihistamines).', 3),
  ('prometazina', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'minor',
   'Os anti-histamínicos devem ser usados com cuidado na insuficiência hepática (Prontuário 10.1/Anexo 3).',
   'Antihistamines must be used with care in hepatic impairment (Prontuário 10.1/Annex 3).',
   'Reduzir dose; vigiar sonolência excessiva.',
   'Reduce dose; monitor for excessive sedation.',
   'Prontuário Terapêutico INFARMED, 10.1: "usados com cuidado na insuficiência hepática".',
   'Prontuário Terapêutico INFARMED, 10.1: "used with care in hepatic impairment".', 4),
  -- ---------------- HIDROXIZINA ----------------
  ('hidroxizina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation',
   'contraindication', 'critical',
   'A hidroxizina prolonga o QT — contra-indicada em QT longo prévio ou com outros prolongadores.',
   'Hydroxyzine prolongs QT — contraindicated with pre-existing long QT or other prolongers.',
   'ECG se fatores de risco; rever concomitantes.',
   'ECG if risk factors; review concomitants.',
   'EMC-UK — hydroxyzine SmPC 4.3/4.4 (QT).',
   'EMC-UK — hydroxyzine SmPC 4.3/4.4 (QT).', 1),
  ('hidroxizina', 'gravidez', 'Gravidez', 'Pregnancy',
   'precaution', 'moderate',
   'Evitar no 1.º trimestre e próximo do termo (efeitos antimuscarínicos no RN).',
   'Avoid in the 1st trimester and near term (antimuscarinic effects on the newborn).',
   'Usar apenas se claramente necessário.',
   'Use only if clearly necessary.',
   'EMC-UK — hydroxyzine SmPC 4.6 (gravidez).',
   'EMC-UK — hydroxyzine SmPC 4.6 (pregnancy).', 2),
  -- ---------------- IMIPRAMINA ----------------
  ('imipramina', 'prolongamento_qt', 'Prolongamento do intervalo QT', 'QT interval prolongation',
   'contraindication', 'critical',
   'Os tricíclicos prolongam o QT e podem causar arritmias — contra-indicados em QT longo prévio.',
   'Tricyclics prolong QT and can cause arrhythmias — contraindicated with pre-existing long QT.',
   'ECG basal (cardiopatas, idosos, doses altas); vigiar alargamento de QRS em sobredosagem.',
   'Baseline ECG (cardiac patients, elderly, high doses); watch for QRS widening in overdose.',
   'Ficha do site (imipramina — ECG basal); Prontuário (tricíclicos — arritmias).',
   'Site monograph (imipramine — baseline ECG); Prontuário (tricyclics — arrhythmias).', 1),
  ('imipramina', 'glaucoma', 'Glaucoma de ângulo fechado', 'Angle-closure glaucoma',
   'contraindication', 'moderate',
   'A actividade anticolinérgica dos tricíclicos precipita crise de glaucoma de ângulo fechado.',
   'Tricyclic anticholinergic activity precipitates angle-closure glaucoma attacks.',
   'Excluir glaucoma de ângulo fechado antes de iniciar.',
   'Exclude angle-closure glaucoma before starting.',
   'Prontuário/ficha do site (imipramina — glaucoma de ângulo fechado).',
   'Prontuário/site monograph (imipramine — angle-closure glaucoma).', 2),
  ('imipramina', 'cardiopatia_isquemica', 'Cardiopatia isquémica', 'Ischaemic heart disease',
   'contraindication', 'moderate',
   'Os tricíclicos são contra-indicados na recuperação recente de enfarte do miocárdio — arritmogenicidade.',
   'Tricyclics are contraindicated in recent myocardial infarction recovery — arrhythmogenicity.',
   'Preferir alternativas (ISRS) em cardiopatas.',
   'Prefer alternatives (SSRIs) in cardiac patients.',
   'Prontuário/EMC-UK — imipramine SmPC 4.3 (enfarte recente).',
   'Prontuário/EMC-UK — imipramine SmPC 4.3 (recent MI).', 3),
  ('imipramina', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'moderate',
   'Os tricíclicos reduzem o limiar convulsivo.',
   'Tricyclics lower the seizure threshold.',
   'Manter antiepilépticos; titular devagar.',
   'Maintain antiepileptics; titrate slowly.',
   'Prontuário (tricíclicos — limiar convulsivo).',
   'Prontuário (tricyclics — seizure threshold).', 4),
  -- ---------------- MICONAZOL ----------------
  ('miconazol', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'minor',
   'O gel oral de miconazol tem absorção sistémica parcial — precaução na doença hepática.',
   'Oral miconazol gel has partial systemic absorption — caution in liver disease.',
   'Evitar cursos longos de gel oral em hepatorpatas.',
   'Avoid long courses of oral gel in liver patients.',
   'EMC-UK — miconazol oral gel SmPC 4.4 (hepatic).',
   'EMC-UK — miconazol oral gel SmPC 4.4 (hepatic).', 1),
  -- ---------------- TERBINAFINA ----------------
  ('terbinafina', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'contraindication', 'critical',
   'A terbinafina oral causa hepatotoxicidade idiossincrática — contra-indicada na doença hepática crónica activa.',
   'Oral terbinafine causes idiosyncratic hepatotoxicity — contraindicated in chronic active liver disease.',
   'Avaliar transaminases basais em cursos prolongados; suspender se ALT > 2–3× LSN.',
   'Assess baseline transaminases in prolonged courses; discontinue if ALT > 2–3× ULN.',
   'Ficha do site (terbinafina — suspender se ALT elevada); EMC-UK terbinafine SmPC 4.3/4.4.',
   'Site monograph (terbinafine — discontinue if ALT raised); EMC-UK terbinafine SmPC 4.3/4.4.', 1),
  ('terbinafina', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease',
   'precaution', 'minor',
   'A clarificação renal reduz-se — ajustar dose em clearance < 50 ml/min.',
   'Renal clearance is reduced — adjust dose if CrCl < 50 ml/min.',
   'Reduzir dose na insuficiência renal moderada/grave.',
   'Reduce dose in moderate/severe renal impairment.',
   'EMC-UK — terbinafine SmPC 4.2 (clearance < 50 ml/min).',
   'EMC-UK — terbinafine SmPC 4.2 (CrCl < 50 ml/min).', 2),
  -- ---------------- GRISEOFULVINA ----------------
  ('griseofulvina', 'gravidez', 'Gravidez', 'Pregnancy',
   'contraindication', 'critical',
   'A griseofulvina é teratogénica — contra-indicada na gravidez; contracepção durante e 1 mês após o tratamento (homens e mulheres).',
   'Griseofulvin is teratogenic — contraindicated in pregnancy; contraception during and 1 month after treatment (men and women).',
   'Excluir gravidez antes de iniciar; contracepção eficaz até 1 mês após o fim.',
   'Exclude pregnancy before starting; effective contraception until 1 month after completion.',
   'Ficha do site (griseofulvina — contracepção durante e 1 mês após); Prontuário 6.2.2.',
   'Site monograph (griseofulvin — contraception during and 1 month after); Prontuário 6.2.2.', 1),
  ('griseofulvina', 'porfiria', 'Porfiria', 'Porphyria',
   'contraindication', 'critical',
   'A griseofulvina é classicamente contra-indicada na porfiria — precipita crises agudas.',
   'Griseofulvin is classically contraindicated in porphyria — precipitates acute attacks.',
   'Contra-indicada em qualquer tipo de porfiria.',
   'Contraindicated in any type of porphyria.',
   'Prontuário 6.2.2 / EMC-UK griseofulvin SmPC 4.3 (porfiria).',
   'Prontuário 6.2.2 / EMC-UK griseofulvin SmPC 4.3 (porphyria).', 2),
  ('griseofulvina', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'contraindication', 'moderate',
   'Contra-indicada na doença hepática — hepatotoxicidade e metabolismo alterado.',
   'Contraindicated in liver disease — hepatotoxicity and altered metabolism.',
   'Excluir doença hepática antes de iniciar cursos prolongados.',
   'Exclude liver disease before prolonged courses.',
   'Ficha do site (griseofulvina — função hepática em cursos longos).',
   'Site monograph (griseofulvin — liver function in long courses).', 3),
  -- ---------------- RETINOL ----------------
  ('retinol', 'gravidez', 'Gravidez', 'Pregnancy',
   'precaution', 'critical',
   'Doses altas de vitamina A são teratogénicas — contra-indicadas na gravidez; doses do programa (50 000–200 000 UI) seguem calendário próprio.',
   'High-dose vitamin A is teratogenic — contraindicated in pregnancy; programme doses (50,000–200,000 IU) follow their own schedule.',
   'Contracepção em mulheres em idade fértil sob tratamento com dose alta; seguir esquema do programa nacional.',
   'Contraception in women of childbearing age on high-dose treatment; follow the national programme schedule.',
   'Ficha do site (retinol — contra-indicado em dose alta na gravidez).',
   'Site monograph (retinol — contraindicated at high dose in pregnancy).', 1),
  ('retinol', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'moderate',
   'A vitamina A acumula-se no fígado — risco de hepatotoxicidade com doses altas em hepatopatas.',
   'Vitamin A accumulates in the liver — hepatotoxicity risk at high doses in liver patients.',
   'Evitar doses altas em doença hepática; monitorizar transaminases.',
   'Avoid high doses in liver disease; monitor transaminases.',
   'Prontuário 8 (vitaminas — hepatotoxicidade da vitamina A em dose alta).',
   'Prontuário 8 (vitamins — vitamin A hepatotoxicity at high dose).', 2),
  -- ---------------- DAPSONA ----------------
  ('dapsona', 'deficiencia_g6pd', 'Deficiência de G6PD', 'G6PD deficiency',
   'contraindication', 'critical',
   'A dapsona causa hemólise oxidativa — triagem de G6PD obrigatória antes do início (populações de risco em Angola).',
   'Dapsone causes oxidative haemolysis — G6PD screening mandatory before starting (at-risk populations in Angola).',
   'Triar G6PD antes do início; suspender se hemólise surgir.',
   'Screen G6PD before starting; discontinue if haemolysis develops.',
   'Ficha do site (dapsona — triar G6PD antes do início, hemólise grave).',
   'Site monograph (dapsone — screen G6PD before starting, severe haemolysis).', 1),
  ('dapsona', 'metemoglobinemia', 'Metemoglobinemia', 'Methaemoglobinaemia',
   'contraindication', 'moderate',
   'A dapsona causa metemoglobinemia dose-dependente — contra-indicada em quem já tem metemoglobinemia ou deficiência de NADH-metHb redutase.',
   'Dapsone causes dose-dependent methaemoglobinaemia — contraindicated in existing methaemoglobinaemia or NADH-metHb reductase deficiency.',
   'Monitorizar metemoglobinemia se sintomático (dispneia, cianose).',
   'Monitor methaemoglobinaemia if symptomatic (dyspnoea, cyanosis).',
   'Ficha do site (dapsona — monitorizar metemoglobinemia).',
   'Site monograph (dapsone — monitor methaemoglobinaemia).', 2),
  ('dapsona', 'anemia_neutropenia', 'Anemia / neutropenia prévia', 'Prior anaemia / neutropenia',
   'precaution', 'moderate',
   'A dapsona causa agranulocitose rara e agrava anemia — precaução em citopenias prévias.',
   'Dapsone causes rare agranulocytosis and worsens anaemia — caution with prior cytopenias.',
   'Hemograma basal e periódico.',
   'Baseline and periodic full blood count.',
   'Ficha do site (dapsona — monitorizar hemograma).',
   'Site monograph (dapsone — monitor FBC).', 3)
) AS v(drug_slug, condition_slug, condition_pt, condition_en,
       interaction_type, severity, reason_pt, reason_en,
       advice_pt, advice_en, source_pt, source_en, sort_order)
ON d.slug = v.drug_slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- =====================================================================
-- Exclusões com justificação (regra 13.1 do Fluxo 2):
--   * clotrimazol: uso tópico/vaginal sem absorção sistémica relevante
--     — sem interações fármaco-doença aplicáveis.
--   * tiamina: o alcoolismo é a INDICAÇÃO principal (profilaxia de
--     Wernicke), não uma interação adversa — não registar.
--   * oxitocina × gravidez: é uterotónico usado NO parto — não aplicável
--     como interação adversa.
--   * pirantel × gravidez: dados limitados mas sem contraindicação formal
--     (OMS permite 2.º/3.º trimestres) — não registar sem fonte formal.
--   * albendazol × 'hipertricose': par de rascunho removido — sem base
--     documental (tuple com sort_order 99 não insere nada porque
--     condition_slug não existe no vocabulário; mantido fora da lista
--     real de pares).
-- =====================================================================
