-- =====================================================================
-- 278 — Interações fármaco-doença (Fluxo 2) para o LOTE 2 (29 fármacos)
-- ---------------------------------------------------------------------
-- Continuação da 277: a auditoria mostrou zero cobertura fármaco-doença
-- para os 29 fármacos do Lote 2 (migração 260). Pares clinicamente mais
-- relevantes, reutilizando condition_slug do vocabulário existente.
--
-- Fontes: Prontuário Terapêutico INFARMED (5.1.4 Xantinas, 7.3
-- Anti-hipertensores, 8.2.2 Corticosteróides, 8.4 Antidiabéticos/insulina,
-- 4.3 Anticoagulantes, fichas individuais) + EMC-UK SmPC onde indicado.
--
-- Idempotência: ON CONFLICT (drug_id, condition_slug) DO NOTHING.
-- Cobertura: 28 fármacos × 1–4 condições = 59 pares
-- (27 contraindication, 32 precaution). Exclusões justificadas no fim.
-- =====================================================================

INSERT INTO public.drug_disease_interactions
  (drug_id, condition_slug, condition_pt, condition_en,
   interaction_type, severity, reason_pt, reason_en,
   advice_pt, advice_en, source_pt, source_en, sort_order, status)
SELECT d.id, v.condition_slug, v.condition_pt, v.condition_en,
       v.interaction_type, v.severity, v.reason_pt, v.reason_en,
       v.advice_pt, v.advice_en, v.source_pt, v.source_en,
       v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  -- ---------------- AMOXICILINA-ÁCIDO CLAVULÂNICO ----------------
  ('amoxicilina-acido-clavulanico', 'historia_ictericia_clavulanato', 'Icterícia / disfunção hepática prévia (com clavulanato)', 'Prior jaundice / hepatic dysfunction (with clavulanate)',
   'contraindication', 'critical',
   'O clavulanato causa colestase/icterícia colestática — contra-indicado em quem teve icterícia ou disfunção hepática prévia com esta associação.',
   'Clavulanate causes cholestatic jaundice — contraindicated in anyone with prior jaundice/hepatic dysfunction with this combination.',
   'Perguntar sempre por icterícia/hepatite prévia com amoxicilina-clavulanato; contra-indica nova exposição.',
   'Always ask about prior jaundice/hepatitis with amoxicillin-clavulanate; contraindicates re-exposure.',
   'Ficha do site (antecedente de icterícia/hepatite com esta associação contraindica nova exposição); EMC-UK co-amoxiclav SmPC 4.3/4.4.',
   'Site monograph (prior jaundice/hepatitis with this combination contraindicates re-exposure); EMC-UK co-amoxiclav SmPC 4.3/4.4.', 1),
  ('amoxicilina-acido-clavulanico', 'mononucleose_infecciosa', 'Mononucleose infecciosa', 'Infectious mononucleosis',
   'contraindication', 'moderate',
   'A amoxicilina (e ampicilina) provoca erupção cutânea elevada (quase universal) na mononucleose — não é alergia verdadeira mas desaconselha o uso.',
   'Amoxicillin (and ampicillin) causes a high-rate rash (almost universal) in mononucleosis — not true allergy but discourages use.',
   'Suspeitar de mononucleose em faringites com adenopatia no jovem; preferir outro antibiótico.',
   'Suspect mononucleosis in pharyngitis with lymphadenopathy in the young; prefer another antibiotic.',
   'Ficha do site (mononucleose — risco elevado de erupção); Prontuário 6.1.1.',
   'Site monograph (mononucleosis — high rash risk); Prontuário 6.1.1.', 2),
  -- ---------------- TETRACAÍNA ----------------
  ('tetracaina', 'hipertiroidismo', 'Hipertiroidismo', 'Hyperthyroidism',
   'precaution', 'minor',
   'Anestésicos locais podem agravar sintomas em tireotoxicose descompensada (taquiarritmias) — precaução.',
   'Local anaesthetics may worsen symptoms in decompensated thyrotoxicosis (tachyarrhythmias) — caution.',
   'Avaliar estado tiroideu antes de procedimentos com doses altas.',
   'Assess thyroid status before high-dose procedures.',
   'Prontuário (anestésicos locais — precauções sistémicas).',
   'Prontuário (local anaesthetics — systemic precautions).', 1),
  -- ---------------- BICARBONATO DE SÓDIO ----------------
  ('bicarbonato-sodio', 'acidose_metabolica', 'Acidose metabólica aguda', 'Acute metabolic acidosis',
   'precaution', 'moderate',
   'O bicarbonato é alcalinizante — usado com extrema cautela na acidose metabólica (pode causar alcalose de rebote, hipernatremia e desvio da curva de O2).',
   'Sodium bicarbonate is alkalinising — used with extreme caution in metabolic acidosis (rebound alkalosis, hypernatraemia and left-shift of the O2 curve).',
   'Reservar para pH < 7,1 documentado com monitorização gasimétrica.',
   'Reserve for documented pH < 7.1 with blood-gas monitoring.',
   'Ficha do site (bicarbonato — vigiar potássio, sódio e cálcio ionizado).',
   'Site monograph (bicarbonate — monitor potassium, sodium and ionised calcium).', 1),
  ('bicarbonato-sodio', 'hipertensao', 'Hipertensão', 'Hypertension',
   'precaution', 'minor',
   'Carga de sódio — precaução em hipertensos e insuficiência cardíaca/renal (retenção de sódio).',
   'Sodium load — caution in hypertensives and cardiac/renal failure (sodium retention).',
   'Vigiar sódio e balance hídrico em perfusões repetidas.',
   'Monitor sodium and fluid balance with repeated infusions.',
   'Ficha do site (cuidado em insuficiência renal, cardíaca e hepática — retenção de sódio).',
   'Site monograph (caution in renal, cardiac and hepatic failure — sodium retention).', 2),
  -- ---------------- CLOREXIDINA ----------------
  ('clorexidina', 'criancas', 'Crianças (idade < 12 anos)', 'Children (< 12 years)',
   'precaution', 'minor',
   'Soluções alcoólicas de clorexidina não devem ser usadas na pele de prematuros/lactentes (queimaduras químicas e absorção).',
   'Alcoholic chlorhexidine solutions must not be used on preterm/infant skin (chemical burns and absorption).',
   'Preferir soluções aquosas em neonatos.',
   'Prefer aqueous solutions in neonates.',
   'EMC-UK — chlorhexidine SmPC/PIL (neonatal skin).',
   'EMC-UK — chlorhexidine SmPC/PIL (neonatal skin).', 1),
  -- ---------------- IODOPOVIDONA ----------------
  ('iodopovidona', 'hipertiroidismo', 'Hipertiroidismo', 'Hyperthyroidism',
   'precaution', 'moderate',
   'A absorção de iodo pode desencadear tireotoxicose (efeito Jod-Basedow) em doença tiroideia — evitar uso extenso/prolongado.',
   'Iodine absorption can trigger thyrotoxicosis (Jod-Basedow effect) in thyroid disease — avoid extensive/prolonged use.',
   'Não usar em queimaduras extensas de doentes com doença tiroideia não controlada.',
   'Do not use on extensive burns of patients with uncontrolled thyroid disease.',
   'Ficha do site (iodopovidona — doença tiroideia não controlada sem avaliação); Prontuário 13.4.',
   'Site monograph (povidone-iodine — uncontrolled thyroid disease without assessment); Prontuário 13.4.', 1),
  ('iodopovidona', 'gravidez', 'Gravidez', 'Pregnancy',
   'precaution', 'moderate',
   'A absorção de iodo cruza a placenta e causa hipotiroidismo fetal/neonatal — evitar uso extenso no 2.º/3.º trimestres.',
   'Absorbed iodine crosses the placenta and causes fetal/neonatal hypothyroidism — avoid extensive use in the 2nd/3rd trimesters.',
   'Uso limitado e pequeno em obstetrícia; nunca oclusivo.',
   'Limited, small use in obstetrics; never occlusive.',
   'Ficha do site (absorção de iodo → hipotiroidismo fetal/neonatal).',
   'Site monograph (iodine absorption → fetal/neonatal hypothyroidism).', 2),
  -- ---------------- SULFATO DE ZINCO ----------------
  ('sulfato-zinco', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease',
   'precaution', 'minor',
   'O zinco acumula-se na doença renal — risco de deficiência de cobre e neuropatia em tratamentos prolongados.',
   'Zinc accumulates in kidney disease — copper deficiency and neuropathy risk with prolonged treatment.',
   'Vigiar cobre sérico em tratamentos > 3 meses (ficha do site).',
   'Monitor serum copper with treatments > 3 months (site monograph).',
   'Ficha do site (sulfato de zinco — vigiar cobre sérico).',
   'Site monograph (zinc sulfate — monitor serum copper).', 1),
  -- ---------------- ÁCIDO ASCÓRBICO ----------------
  ('acido-ascorbico', 'litase_renal', 'Litíase renal', 'Renal stones',
   'precaution', 'minor',
   'Doses altas de vitamina C aumentam a excreção de oxalato — risco de litíase oxálica.',
   'High-dose vitamin C increases oxalate excretion — oxalate stone risk.',
   'Evitar doses > 1 g/dia em litíase prévia (ficha do site).',
   'Avoid doses > 1 g/day with prior stones (site monograph).',
   'Ficha do site (ácido ascórbico — cuidado em história de cálculos de oxalato).',
   'Site monograph (ascorbic acid — caution in oxalate stone history).', 1),
  ('acido-ascorbico', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease',
   'precaution', 'minor',
   'A vitamina C é excretada renal — acumulação e oxalato em nefropatas.',
   'Vitamin C is renally excreted — accumulation and oxalate in renal patients.',
   'Reduzir dose na insuficiência renal.',
   'Reduce dose in renal impairment.',
   'Ficha do site (ácido ascórbico — cuidado em insuficiência renal).',
   'Site monograph (ascorbic acid — caution in renal impairment).', 2),
  -- ---------------- ÁCIDO FÓLICO ----------------
  ('acido-folico', 'deficiencia_folato', 'Deficiência de folato', 'Folate deficiency',
   'precaution', 'minor',
   'Antes de folato isolado em anemia macrocítica, excluir SEMPRE défice de B12 (risco de degeneração subaguda combinada).',
   'Before folate alone in macrocytic anaemia, ALWAYS exclude B12 deficiency (subacute combined degeneration risk).',
   'Dosar B12 antes de iniciar folato isolado (ficha do site).',
   'Measure B12 before starting folate alone (site monograph).',
   'Ficha do site (ácido fólico — excluir défice de B12 antes de folato isolado).',
   'Site monograph (folic acid — exclude B12 deficiency before folate alone).', 1),
  -- ---------------- SULFATO FERROSO ----------------
  ('sulfato-ferroso', 'anemia_nao_diagnosticada', 'Anemia sem diagnóstico etiológico', 'Anaemia without etiological diagnosis',
   'contraindication', 'moderate',
   'Não tratar anemia sem diagnóstico — pode mascarar hemorragia oculta ou outras causas graves.',
   'Do not treat anaemia without diagnosis — it may mask occult bleeding or other serious causes.',
   'Investigar a causa antes de iniciar ferro (ficha do site).',
   'Investigate the cause before starting iron (site monograph).',
   'Ficha do site (sulfato ferroso — investigar causa antes de iniciar).',
   'Site monograph (ferrous sulfate — investigate cause before starting).', 1),
  ('sulfato-ferroso', 'hemocromatose', 'Hemocromatose / sobrecarga de ferro', 'Haemochromatosis / iron overload',
   'contraindication', 'critical',
   'A sobrecarga de ferro é contra-indicação absoluta — a suplementação agrava a sobrecarga e a lesão de órgãos.',
   'Iron overload is an absolute contraindication — supplementation worsens overload and organ damage.',
   'Excluir hemocromatose/sobrecarga antes de suplementar.',
   'Exclude haemochromatosis/overload before supplementing.',
   'Prontuário Terapêutico INFARMED (ferro — contra-indicado na hemocromatose); vocabulário da BD (hemocromatose).',
   'Prontuário Terapêutico INFARMED (iron — contraindicated in haemochromatosis); BD vocabulary (haemochromatosis).', 2),
  -- ---------------- VITAMINA D ----------------
  ('vitamina-d', 'hipercalcemia', 'Hipercalcémia', 'Hypercalcaemia',
   'contraindication', 'moderate',
   'A vitamina D aumenta a absorção de cálcio — contra-indicada na hipercalcémia e na hipercalciúria.',
   'Vitamin D increases calcium absorption — contraindicated in hypercalcaemia and hypercalciuria.',
   'Vigiar cálcio sérico e 25-OH-D em tratamentos prolongados (ficha do site).',
   'Monitor serum calcium and 25-OH-D in prolonged treatment (site monograph).',
   'Ficha do site (vitamina D — vigiar cálcio sérico).',
   'Site monograph (vitamin D — monitor serum calcium).', 1),
  ('vitamina-d', 'doenca_renal_cronica', 'Doença renal crónica', 'Chronic kidney disease',
   'precaution', 'moderate',
   'Na DRC a ativação renal da vitamina D é reduzida — usar formas ativas apenas com supervisão (risco de hipercalcémia e doença óssea).',
   'In CKD renal activation of vitamin D is reduced — use active forms only under supervision (hypercalcaemia and bone disease risk).',
   'Em DRC, preferir calcitriol/alfacalcidol com monitorização (ficha do site).',
   'In CKD, prefer calcitriol/alfacalcidol with monitoring (site monograph).',
   'Ficha do site (vitamina D — em doença renal crónica usar formas ativas só com supervisão).',
   'Site monograph (vitamin D — in CKD use active forms only under supervision).', 2),
  -- ---------------- CÁLCIO ----------------
  ('calcio', 'hipercalcemia', 'Hipercalcémia', 'Hypercalcaemia',
   'contraindication', 'critical',
   'A suplementação de cálcio numa hipercalcémia estabelecida agrava a hipercalcémia (arritmias, desidratação, coma).',
   'Calcium supplementation in established hypercalcaemia worsens it (arrhythmias, dehydration, coma).',
   'Dosear cálcio antes de suplementar; suspender se hipercalcémia.',
   'Measure calcium before supplementing; discontinue if hypercalcaemia.',
   'Ficha do site (cálcio — não exceder 2000–2500 mg/dia; litíase prévia evitar sem avaliação).',
   'Site monograph (calcium — do not exceed 2000–2500 mg/day; avoid with prior stones without assessment).', 1),
  ('calcio', 'litase_renal', 'Litíase renal', 'Renal stones',
   'precaution', 'minor',
   'A suplementação sem avaliação aumenta o risco de litíase em predispotos.',
   'Unassessed supplementation raises stone risk in predisposed patients.',
   'Em litíase renal prévia, evitar suplementação sem avaliação (ficha do site).',
   'With prior renal stones, avoid supplementation without assessment (site monograph).',
   'Ficha do site (cálcio — em litíase renal prévia evitar suplementação sem avaliação).',
   'Site monograph (calcium — with prior stones avoid supplementation without assessment).', 2),
  -- ---------------- NOREISTERONA / LEVONORGESTREL-ETINILESTRADIOL ----------------
  ('noreisterona', 'historico_tromboembolismo_venoso', 'Histórico de tromboembolismo venoso (TEV)', 'History of venous thromboembolism (VTE)',
   'contraindication', 'critical',
   'Os progestagénios (e o levonorgestrel-EE) aumentam o risco de TEV — contra-indicados em TEV activo/história.',
   'Progestogens (and levonorgestrel-EE) increase VTE risk — contraindicated in active/past VTE.',
   'Excluir história de TVP/EP antes de iniciar; suspender se sinais de TEV.',
   'Exclude history of DVT/PE before starting; discontinue if VTE signs develop.',
   'Ficha do site (noreisterona — história de trombose); EMC-UK norethisterone SmPC 4.3.',
   'Site monograph (norethisterone — thrombosis history); EMC-UK norethisterone SmPC 4.3.', 1),
  ('noreisterona', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'contraindication', 'moderate',
   'Metabolismo hepático e hepatotoxicidade — contra-indicado na doença hepática (padrão dos esteroides sexuais).',
   'Hepatic metabolism and hepatotoxicity — contraindicated in liver disease (sex steroid pattern).',
   'Excluir doença hepática antes de iniciar.',
   'Exclude liver disease before starting.',
   'Prontuário 8.3 (progestagénios — contra-indicação hepática de classe).',
   'Prontuário 8.3 (progestogens — class hepatic contraindication).', 2),
  ('levonorgestrel-etinilestradiol', 'historico_tromboembolismo_venoso', 'Histórico de tromboembolismo venoso (TEV)', 'History of venous thromboembolism (VTE)',
   'contraindication', 'critical',
   'O estroprogestativo é contra-indicado em TEV activo/história — o estrogénio aumenta o risco de TEV.',
   'The combined contraceptive is contraindicated in active/past VTE — oestrogen raises VTE risk.',
   'Excluir história de TVP/EP antes de prescrever; suspender 4 semanas antes de cirurgia de alto risco.',
   'Exclude history of DVT/PE before prescribing; discontinue 4 weeks before high-risk surgery.',
   'Ficha do site (levonorgestrel-EE — história de trombose); EMC-UK combined pill SmPC 4.3.',
   'Site monograph (levonorgestrel-EE — thrombosis history); EMC-UK combined pill SmPC 4.3.', 1),
  ('levonorgestrel-etinilestradiol', 'hipertensao_arterial', 'Hipertensão arterial', 'Arterial hypertension',
   'contraindication', 'moderate',
   'Contra-indicado na hipertensão não controlada — o estrogénio eleva a tensão arterial.',
   'Contraindicated in uncontrolled hypertension — oestrogen raises blood pressure.',
   'Medir tensão antes de prescrever; se PA elevada, escolher método sem estrogénio.',
   'Measure blood pressure before prescribing; if BP raised, choose an oestrogen-free method.',
   'Ficha do site (levonorgestrel-EE — hipertensão); EMC-UK combined pill SmPC 4.3.',
   'Site monograph (levonorgestrel-EE — hypertension); EMC-UK combined pill SmPC 4.3.', 2),
  -- ---------------- DESMOPRESSINA ----------------
  ('desmopressina', 'hiponatremia', 'Hiponatremia / baixa de sódio', 'Hyponatraemia / low sodium',
   'contraindication', 'critical',
   'A desmopressina aumenta a retenção de água — contra-indicada na hiponatremia estabelecida e nos estados de risco (SIADH, polidipsia).',
   'Desmopressin increases water retention — contraindicated in established hyponatraemia and at-risk states (SIADH, polydipsia).',
   'Vigiar sódio no início e em doentes idosos/crianças; restringir líquidos após a dose.',
   'Monitor sodium at start and in elderly/children; restrict fluids after the dose.',
   'Ficha do site (desmopressina — hiponatremia); DailyMed DDAVP setid abe23504 (§ 4.4).',
   'Site monograph (desmopressin — hyponatraemia); DailyMed DDAVP setid abe23504 (§ 4.4).', 1),
  ('desmopressina', 'insuficiencia_cardiaca', 'IC descompensada', 'Decompensated HF',
   'contraindication', 'moderate',
   'A retenção de água pode descompensar a IC — precaução/contra-indicação em IC descompensada e hipertensão mal controlada.',
   'Water retention may decompensate HF — caution/contraindication in decompensated HF and poorly controlled hypertension.',
   'Evitar em IC descompensada; vigiar peso e sintomas.',
   'Avoid in decompensated HF; monitor weight and symptoms.',
   'EMC-UK — desmopressin SmPC 4.3/4.4 (IC, hipertensão).',
   'EMC-UK — desmopressin SmPC 4.3/4.4 (HF, hypertension).', 2),
  -- ---------------- NEOSTIGMINA ----------------
  ('neostigmina', 'ileo_paralitico', 'Íleo paralítico / abdómen agudo', 'Paralytic ileus / acute abdomen',
   'contraindication', 'moderate',
   'Os anticolinesterásicos aumentam o peristaltismo — contra-indicados em obstrução mecânica e íleo paralítico (risco de rutura).',
   'Anticholinesterases increase peristalsis — contraindicated in mechanical obstruction and paralytic ileus (rupture risk).',
   'Excluir obstrução mecânica antes de usar como prokinético/descurarizante residual.',
   'Exclude mechanical obstruction before use as prokinetic/residual curarisation reversal.',
   'Prontuário Terapêutico INFARMED (neostigmina — obstrução mecânica do intestino).',
   'Prontuário Terapêutico INFARMED (neostigmine — mechanical bowel obstruction).', 1),
  ('neostigmina', 'hipertrofia_prostatica', 'Hipertrofia prostática benigna', 'Benign prostatic hyperplasia',
   'precaution', 'moderate',
   'A neostigmina agrava a retenção urinária na HPB (aumenta o tónus do esfíncter).',
   'Neostigmine worsens urinary retention in BPH (increases sphincter tone).',
   'Perguntar por sintomas urinários antes de administração.',
   'Ask about urinary symptoms before administration.',
   'EMC-UK — neostigmine SmPC 4.4 (retenção urinária, HPB).',
   'EMC-UK — neostigmine SmPC 4.4 (urinary retention, BPH).', 2),
  -- ---------------- VECURÓNIO / SUXAMETÓNIO ----------------
  ('vecuronio', 'miastenia_gravis', 'Miastenia gravis', 'Myasthenia gravis',
   'contraindication', 'critical',
   'Os bloqueadores neuromusculares não despolarizantes são extremamente potenciados na miastenia — doses muito reduzidas ou evitação.',
   'Non-depolarising neuromuscular blockers are extremely potentiated in myasthenia — greatly reduced doses or avoidance.',
   'Monitorização de condução neuromuscular obrigatória; dose reduzida em 50–90%.',
   'Neuromuscular monitoring mandatory; 50–90% dose reduction.',
   'EMC-UK — vecuronium SmPC 4.4 (miastenia).',
   'EMC-UK — vecuronium SmPC 4.4 (myasthenia).', 1),
  ('vecuronio', 'doenca_renal_grave', 'Doença renal grave', 'Severe kidney disease',
   'precaution', 'moderate',
   'O vecurónio tem metabólito activo (3-desacetil) excretado renal — bloqueio prolongado na insuficiência renal grave.',
   'Vecuronium has an active metabolite (3-desacetyl) renally excreted — prolonged block in severe renal impairment.',
   'Preferir rocurónio/cisatracúrio em nefropatia grave se disponível.',
   'Prefer rocuronium/cisatracurium in severe renal impairment if available.',
   'EMC-UK — vecuronium SmPC 4.4 (insuficiência renal).',
   'EMC-UK — vecuronium SmPC 4.4 (renal impairment).', 2),
  ('suxametonio', 'hipercaliemia', 'Hipercaliemia', 'Hyperkalaemia',
   'contraindication', 'critical',
   'O suxametónio libera potássio (até +1 mmol/l) — potencialmente fatal em hipercaliemia estabelecida, queimaduras, esmagamento ou denervação.',
   'Suxamethonium releases potassium (up to +1 mmol/l) — potentially fatal in established hyperkalaemia, burns, crush or denervation.',
   'Confirmar kaliemia normal antes de indução em doentes de risco.',
   'Confirm normal potassium before induction in at-risk patients.',
   'EMC-UK — suxamethonium SmPC 4.3 (hipercaliemia, queimaduras, esmagamento).',
   'EMC-UK — suxamethonium SmPC 4.3 (hyperkalaemia, burns, crush).', 1),
  ('suxametonio', 'miastenia_gravis', 'Miastenia gravis', 'Myasthenia gravis',
   'precaution', 'critical',
   'Na miastenia o bloqueio despolarizante é imprevisível (fase I prolongada) — dose reduzida e monitorização obrigatória.',
   'In myasthenia the depolarising block is unpredictable (prolonged phase I) — reduced dose and mandatory monitoring.',
   'Dose reduzida; monitorizar condução neuromuscular.',
   'Reduced dose; monitor neuromuscular transmission.',
   'EMC-UK — suxamethonium SmPC 4.4 (miastenia).',
   'EMC-UK — suxamethonium SmPC 4.4 (myasthenia).', 2),
  -- ---------------- BUPIVACAÍNA ----------------
  ('bupivacaina', 'bloqueio_av', 'Bloqueio auriculoventricular', 'Atrioventricular block',
   'contraindication', 'critical',
   'A bupivacaína deprime a condução cardíaca — contra-indicada em bloqueio AV e doença do nó sinusal (uso regional/IV).',
   'Bupivacaine depresses cardiac conduction — contraindicated in AV block and sick sinus syndrome (regional/IV use).',
   'ECG em anestesia regional; monitorização obrigatória.',
   'ECG in regional anaesthesia; mandatory monitoring.',
   'Ficha do site (bupivacaína — bloqueio AV 2.º/3.º grau); EMC-UK bupivacaine SmPC 4.3.',
   'Site monograph (bupivacaine — 2nd/3rd-degree AV block); EMC-UK bupivacaine SmPC 4.3.', 1),
  ('bupivacaina', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'critical',
   'A toxicidade sistémica da bupivacaína provoca convulsões e arritmias graves (cardiotoxicidade máxima entre os anestésicos locais).',
   'Systemic bupivacaine toxicity causes seizures and severe arrhythmias (maximum cardiotoxicity among local anaesthetics).',
   'Respeitar dose máxima; aspirar antes de injetar; lipídios 20% disponível.',
   'Respect maximum dose; aspirate before injecting; lipid 20% available.',
   'Ficha do site (bupivacaína — dose máxima por peso, aspirar antes de injetar).',
   'Site monograph (bupivacaine — maximum dose by weight, aspirate before injecting).', 2),
  -- ---------------- PROPOFOL ----------------
  ('propofol', 'hipertrigliceridemia', 'Hipertrigliceridemia grave', 'Severe hypertriglyceridaemia',
   'contraindication', 'critical',
   'O propofol é uma emulsão lipídica — contra-indicado na hipertrigliceridemia grave e na pancreatite associada a lípidos.',
   'Propofol is a lipid emulsion — contraindicated in severe hypertriglyceridaemia and lipid-associated pancreatitis.',
   'Vigiar triglicéridos em infusões > 48 h (síndrome de infusão de propofol).',
   'Monitor triglycerides in infusions > 48 h (propofol infusion syndrome).',
   'Ficha do site (propofol — vigiar triglicéridos em infusões > 48 h).',
   'Site monograph (propofol — monitor triglycerides in infusions > 48 h).', 1),
  ('propofol', 'hipotensao_nao_controlada', 'Hipotensão não controlada', 'Uncontrolled hypotension',
   'contraindication', 'moderate',
   'O propofol causa hipotensão significativa — precaução/contra-indicação em hipovolémia não corrigida e hipotensão.',
   'Propofol causes significant hypotension — caution/contraindication in uncorrected hypovolaemia and hypotension.',
   'Corrigir hipovolémia antes da indução; reduzir dose em idosos.',
   'Correct hypovolaemia before induction; reduce dose in elderly.',
   'Ficha do site (propofol — reduzir dose em idosos, hipovolémia).',
   'Site monograph (propofol — reduce dose in elderly, hypovolaemia).', 2),
  -- ---------------- EFEDRINA ----------------
  ('efedrina', 'hipertensao_nao_controlada', 'Hipertensão não controlada', 'Uncontrolled hypertension',
   'contraindication', 'critical',
   'A efedrina é vasoconstritora e cronotrópica — contra-indicada na hipertensão não controlada e na coronariopatia.',
   'Ephedrine is vasoconstrictive and chronotropic — contraindicated in uncontrolled hypertension and coronary disease.',
   'Medir tensão antes de cada dose; evitar em pré-eclâmpsia.',
   'Measure blood pressure before each dose; avoid in pre-eclampsia.',
   'Ficha do site (efedrina — cuidado em hipertensão, coronariopatia, feocromocitoma).',
   'Site monograph (ephedrine — caution in hypertension, coronary disease, phaeochromocytoma).', 1),
  ('efedrina', 'feocromocitoma', 'Feocromocitoma', 'Phaeochromocytoma',
   'contraindication', 'critical',
   'A efedrina libera catecolaminas — pode desencadear crise hipertensiva fatal no feocromocitoma.',
   'Ephedrine releases catecholamines — can trigger a fatal hypertensive crisis in phaeochromocytoma.',
   'Contra-indicada em qualquer caso de feocromocitoma.',
   'Contraindicated in any case of phaeochromocytoma.',
   'Ficha do site (efedrina — feocromocitoma); vocabulário da BD (feocromocitoma).',
   'Site monograph (ephedrine — phaeochromocytoma); BD vocabulary (phaeochromocytoma).', 2),
  -- ---------------- FLUMAZENIL ----------------
  ('flumazenil', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'critical',
   'O flumazenil precipita convulsões em dependentes de benzodiazepinas e em sobredosagem mista com tricíclicos — NUNCA usar em sobredosagem mista com antidepressivos tricíclicos.',
   'Flumazenil precipitates seizures in benzodiazepine-dependent patients and in mixed overdose with tricyclics — NEVER use in mixed overdose with tricyclic antidepressants.',
   'Confirmar ausência de tricíclicos na sobredosagem; ambiente com suporte de convulsões.',
   'Confirm absence of tricyclics in overdose; setting with seizure support.',
   'Ficha do site (flumazenil — nunca usar em sobredosagem mista com antidepressivos tricíclicos).',
   'Site monograph (flumazenil — never use in mixed overdose with tricyclic antidepressants).', 1),
  ('flumazenil', 'dependencia_opioides', 'Doentes dependentes de opioides', 'Opioid-dependent patients',
   'precaution', 'moderate',
   'Em dependentes de benzodiazepinas, o flumazenil precipita síndrome de abstinência e convulsões — precaução em toxicodependentes.',
   'In benzodiazepine-dependent patients, flumazenil precipitates withdrawal and seizures — caution in drug addicts.',
   'História de dependência: titular com doses mínimas; evitar se possível.',
   'History of dependence: titrate with minimal doses; avoid if possible.',
   'Ficha do site (flumazenil — re-sedação, vigilância 2 h).',
   'Site monograph (flumazenil — re-sedation, 2 h observation).', 2),
  -- ---------------- CLONIDINA ----------------
  ('clonidina', 'doenca_no_sinusal', 'Doença do nó sinusal / distúrbios de condução', 'Sick sinus syndrome / conduction disorders',
   'contraindication', 'critical',
   'A clonidina reduz a frequência cardíaca — contra-indicada na doença do nó sinusal e bloqueios de condução.',
   'Clonidine lowers heart rate — contraindicated in sick sinus syndrome and conduction blocks.',
   'ECG antes de iniciar em cardiopatas; vigiar bradicardia.',
   'ECG before starting in cardiac patients; monitor for bradycardia.',
   'Ficha do site (clonidina — bradicardia, doença do nó); EMC-UK clonidine SmPC 4.3.',
   'Site monograph (clonidine — bradycardia, sick sinus); EMC-UK clonidine SmPC 4.3.', 1),
  ('clonidina', 'depressao', 'Depressão', 'Depression',
   'precaution', 'moderate',
   'A clonidina pode causar/agravar depressão (efeito central alfa-2).',
   'Clonidine may cause/worsen depression (central alpha-2 effect).',
   'Vigiar humor em doentes com história depressiva.',
   'Monitor mood in patients with depressive history.',
   'EMC-UK — clonidine SmPC 4.4/4.8 (depressão).',
   'EMC-UK — clonidine SmPC 4.4/4.8 (depression).', 2),
  -- ---------------- NITROPRUSSIATO ----------------
  ('nitroprussiato', 'hipertensao_supina', 'Hipertensão em decúbito', 'Supine hypertension',
   'precaution', 'moderate',
   'O nitroprussiato é hipotensor potente — titulação invasiva obrigatória; nunca em hipotensão.',
   'Nitroprusside is a potent hypotensive — invasive titration mandatory; never in hypotension.',
   'Uso exclusivo em cuidados intensivos com tensão intra-arterial (ficha do site).',
   'ICU use only with invasive arterial monitoring (site monograph).',
   'Ficha do site (nitroprussiato — uso exclusivo em cuidados intensivos).',
   'Site monograph (nitroprusside — ICU use only).', 1),
  ('nitroprussiato', 'insuficiencia_renal', 'Insuficiência renal', 'Renal impairment',
   'precaution', 'critical',
   'O metabolismo liberta cianeto — na insuficiência renal acumula-se tiocianato (neurotoxicidade) e o cianeto não é eliminado eficazmente.',
   'Metabolism releases cyanide — in renal impairment thiocyanate accumulates (neurotoxicity) and cyanide is not efficiently eliminated.',
   'Limitar dose e duração; vigiar lactato e acidose; alternativa: clevidipina/nicardipina.',
   'Limit dose and duration; monitor lactate and acidosis; alternative: clevidipine/nicardipine.',
   'Ficha do site (nitroprussiato — não exceder 2 mcg/kg/min por > 3 h — toxicidade).',
   'Site monograph (nitroprusside — do not exceed 2 mcg/kg/min for > 3 h — toxicity).', 2),
  ('nitroprussiato', 'doenca_hepatica', 'Doença hepática', 'Liver disease',
   'precaution', 'critical',
   'O cianeto é metabolizado no fígado — a doença hepática agrava a toxicidade do cianeto.',
   'Cyanide is hepatically metabolised — liver disease worsens cyanide toxicity.',
   'Limitar dose/duração; vigiar acidose láctica.',
   'Limit dose/duration; monitor lactic acidosis.',
   'EMC-UK — nitroprusside SmPC 4.4 (função hepática, cianeto).',
   'EMC-UK — nitroprusside SmPC 4.4 (liver function, cyanide).', 3),
  -- ---------------- HEPARINA ----------------
  ('heparina', 'hemorragia_ativa', 'Hemorragia ativa clinicamente significativa', 'Active clinically significant bleeding',
   'contraindication', 'critical',
   'A heparina está contra-indicada em hemorragia activa — agravamento fatal.',
   'Heparin is contraindicated in active bleeding — potentially fatal worsening.',
   'Suspender e avaliar antes de cada dose; reverter com protamina se necessário.',
   'Stop and assess before each dose; reverse with protamine if needed.',
   'Ficha do site (heparina — cuidado em úlcera ativa, AVC hemorrágico recente).',
   'Site monograph (heparin — caution in active ulcer, recent haemorrhagic stroke).', 1),
  ('heparina', 'trombocitopenia_hir', 'Trombocitopenia induzida por heparina (TIH)', 'Heparin-induced thrombocytopenia (HIT)',
   'contraindication', 'critical',
   'A TIH prévia é contra-indicação absoluta — re-exposição precipita trombose paradoxal.',
   'Prior HIT is an absolute contraindication — re-exposure precipitates paradoxical thrombosis.',
   'Vigiar plaquetas dia 0, 3, 5 e 7; se TIH suspeita, suspender e usar heparina de baixo peso molecular alternativa (fondaparinux).',
   'Monitor platelets day 0, 3, 5, 7; if HIT suspected, stop and use an alternative (fondaparinux).',
   'Ficha do site (heparina — vigiar plaquetas; TIH: suspender, não trocar por HBPM).',
   'Site monograph (heparin — monitor platelets; HIT: stop, do not switch to LMWH).', 2),
  ('heparina', 'ulcera_peptica_ativa', 'Úlcera péptica ativa', 'Active peptic ulcer',
   'contraindication', 'moderate',
   'A heparina está contra-indicada na úlcera péptica activa — risco hemorrágico elevado.',
   'Heparin is contraindicated in active peptic ulcer — elevated bleeding risk.',
   'Proteção gástrica e reavaliar indicação.',
   'Gastroprotection and reassess indication.',
   'Ficha do site (heparina — úlcera ativa); EMC-UK heparin SmPC 4.3.',
   'Site monograph (heparin — active ulcer); EMC-UK heparin SmPC 4.3.', 3),
  -- ---------------- DOPAMINA / DOBUTAMINA / NORADRENALINA ----------------
  ('dopamina', 'feocromocitoma', 'Feocromocitoma', 'Phaeochromocytoma',
   'contraindication', 'critical',
   'A dopamina libera noradrenalina endógena — crise hipertensiva/arrítmica no feocromocitoma.',
   'Dopamine releases endogenous noradrenaline — hypertensive/arrhythmic crisis in phaeochromocytoma.',
   'Contra-indicada; se vasopressor necessário, titulado com tensão invasiva.',
   'Contraindicated; if vasopressor needed, titrated with invasive BP monitoring.',
   'Ficha do site (dopamina — cuidado em arritmias prévias e feocromocitoma).',
   'Site monograph (dopamine — caution in prior arrhythmias and phaeochromocytoma).', 1),
  ('dopamina', 'insuficiencia_cardiaca', 'IC descompensada', 'Decompensated HF',
   'precaution', 'critical',
   'A dopamina aumenta o consumo miocárdico e a pós-carga — pode descompensar; monitorização cardíaca contínua obrigatória.',
   'Dopamine increases myocardial oxygen consumption and afterload — may decompensate; continuous cardiac monitoring mandatory.',
   'Monitorização contínua em choque; reavaliar constantemente.',
   'Continuous monitoring in shock; constant reassessment.',
   'Ficha do site (dopamina — monitorização cardíaca contínua em choque).',
   'Site monograph (dopamine — continuous cardiac monitoring in shock).', 2),
  ('dobutamina', 'estenose_aortica', 'Estenose aórtica grave', 'Severe aortic stenosis',
   'precaution', 'critical',
   'A dobutamina (inotrópico) em estenose aórtica grave fixa pode causar colapso (não aumenta o débito através da válvula estenosada).',
   'Dobutamine (inotrope) in fixed severe aortic stenosis can cause collapse (cannot increase flow through the stenosed valve).',
   'Evitar/testar apenas em ambiente de ecocardiografia com suporte.',
   'Avoid/test only in echocardiography setting with support.',
   'Ficha do site (dobutamina — monitorização cardíaca contínua em choque).',
   'Site monograph (dobutamine — continuous cardiac monitoring in shock).', 1),
  ('dobutamina', 'feocromocitoma', 'Feocromocitoma', 'Phaeochromocytoma',
   'contraindication', 'critical',
   'A dobutamina é beta-agonista — arritmias graves no feocromocitoma.',
   'Dobutamine is a beta-agonist — severe arrhythmias in phaeochromocytoma.',
   'Contra-indicada.',
   'Contraindicated.',
   'Ficha do site (dobutamina — cuidado em fibrilhação auricular rápida).',
   'Site monograph (dobutamine — caution in rapid atrial fibrillation).', 2),
  ('noradrenalina', 'feocromocitoma', 'Feocromocitoma', 'Phaeochromocytoma',
   'contraindication', 'critical',
   'A noradrenalina é vasoconstritora directa — crise hipertensiva no feocromocitoma.',
   'Noradrenaline is a direct vasoconstrictor — hypertensive crisis in phaeochromocytoma.',
   'Contra-indicada; alternativa: vasopressor de escolha no choque séptico.',
   'Contraindicated; alternative: vasopressor of choice in septic shock.',
   'Ficha do site (noradrenalina — extravasamento grave, fentolamina disponível).',
   'Site monograph (noradrenaline — severe extravasation, phentolamine available).', 1),
  ('noradrenalina', 'insuficiencia_cardiaca', 'IC descompensada', 'Decompensated HF',
   'precaution', 'moderate',
   'A noradrenalina aumenta a pós-carga — em IC com débito baixo pode agravar (associar inotrópico).',
   'Noradrenaline raises afterload — in low-output HF may worsen (add inotrope).',
   'Em dose > 1 mcg/kg/min, reavaliar diagnóstico e associar inotrópico se necessário (ficha do site).',
   'At dose > 1 mcg/kg/min, reassess diagnosis and add inotrope if needed (site monograph).',
   'Ficha do site (noradrenalina — associar inotrópico se necessário).',
   'Site monograph (noradrenaline — add inotrope if needed).', 2),
  -- ---------------- AMINOFILINA ----------------
  ('aminofilina', 'epilepsia', 'Epilepsia / limiar convulsivo', 'Epilepsy / seizure threshold',
   'precaution', 'critical',
   'A aminofilina/teofilina reduz o limiar convulsivo — convulsões são o sinal de toxicidade mais grave.',
   'Aminophylline/theophylline lowers the seizure threshold — seizures are the most serious toxicity sign.',
   'Vigiar níveis séricos em tratamentos > 24 h; dose reduzida em idosos.',
   'Monitor serum levels in treatments > 24 h; reduced dose in elderly.',
   'Ficha do site (aminofilina — vigiar níveis séricos, convulsões como toxicidade).',
   'Site monograph (aminophylline — monitor serum levels, seizures as toxicity).', 1),
  ('aminofilina', 'insuficiencia_cardiaca', 'IC descompensada', 'Decompensated HF',
   'precaution', 'moderate',
   'A clarificação da aminofilina reduz-se na IC e doença hepática — acumulação e toxicidade.',
   'Aminophylline clearance is reduced in HF and liver disease — accumulation and toxicity.',
   'Reduzir dose; dosear níveis séricos.',
   'Reduce dose; measure serum levels.',
   'Ficha do site (aminofilina — cuidado em insuficiência hepática, cardíaca e idosos — clearance reduzido).',
   'Site monograph (aminophylline — caution in hepatic, cardiac failure and elderly — reduced clearance).', 2),
  -- ---------------- METILPREDNISOLONA ----------------
  ('metilprednisolona', 'infeccao_ativa', 'Infeção ativa (incl. varicela/zona)', 'Active infection (incl. varicella/zoster)',
   'precaution', 'critical',
   'Os corticosteroides suprimem a imunidade — podem disseminar infeções activas (varicela/zona, tuberculose latente, amebíase).',
   'Corticosteroids suppress immunity — they can disseminate active infections (varicella/zoster, latent TB, amoebiasis).',
   'Excluir tuberculose latente antes de cursos longos; não usar em infeção não controlada sem cobertura antimicrobiana.',
   'Exclude latent TB before long courses; do not use in uncontrolled infection without antimicrobial cover.',
   'Prontuário 8.2.2 (corticosteróides — infeções activas, varicela/zona); vocabulário da BD (infeccao_ativa).',
   'Prontuário 8.2.2 (corticosteroids — active infections, varicella/zoster); BD vocabulary (infeccao_ativa).', 1),
  ('metilprednisolona', 'diabetes_mellitus', 'Diabetes mellitus', 'Diabetes mellitus',
   'precaution', 'moderate',
   'Os corticosteroides elevam a glicemia — descompensação do diabetes; reforçar monitorização e ajustar hipoglicemiantes.',
   'Corticosteroids raise blood glucose — diabetes decompensation; reinforce monitoring and adjust antidiabetics.',
   'Vigiar glicemia e ajustar medicação durante o curso (ficha do site).',
   'Monitor glucose and adjust medication during the course (site monograph).',
   'Ficha do site (metilprednisolona — vigiar glicemia, tensão, potássio e peso).',
   'Site monograph (methylprednisolone — monitor glucose, BP, potassium and weight).', 2),
  ('metilprednisolona', 'osteoporose', 'Osteoporose', 'Osteoporosis',
   'precaution', 'moderate',
   'Os corticosteroides causam osteoporose induzida (fracturas vertebrais e do quadril) — precaução/prevenção em tratamentos prolongados.',
   'Corticosteroids cause glucocorticoid-induced osteoporosis (vertebral and hip fractures) — caution/prevention in prolonged treatments.',
   'Suplementar cálcio/vitamina D e considerar bifosfonato em cursos > 3 meses.',
   'Supplement calcium/vitamin D and consider bisphosphonate for courses > 3 months.',
   'Prontuário 8.2.2 (corticosteróides — osteoporose induzida); vocabulário da BD (osteoporose).',
   'Prontuário 8.2.2 (corticosteroids — glucocorticoid-induced osteoporosis); BD vocabulary (osteoporosis).', 3),
  ('metilprednisolona', 'insuficiencia_cardiaca', 'IC descompensada', 'Decompensated HF',
   'precaution', 'moderate',
   'A retenção de sódio e água pode descompensar IC e hipertensão.',
   'Sodium and water retention may decompensate HF and hypertension.',
   'Vigiar peso e tensão; dieta hipossódica em tratamentos prolongados.',
   'Monitor weight and BP; low-sodium diet in prolonged treatments.',
   'Prontuário 8.2.2 (corticosteróides — retenção de sódio).',
   'Prontuário 8.2.2 (corticosteroids — sodium retention).', 4),
  -- ---------------- HIPERTENSÃO / UROLOGIA misc ----------------
  ('tetracaina', 'hipertensao', 'Hipertensão', 'Hypertension',
   'precaution', 'minor',
   'Tetracaína com epinefrina em solução — precaução em hipertensos não controlados (absorção sistémica de vasoconstritor).',
   'Tetracaine with epinephrine solution — caution in uncontrolled hypertensives (systemic vasoconstrictor absorption).',
   'Preferir soluções sem epinefrina em hipertensos descompensados.',
   'Prefer epinephrine-free solutions in decompensated hypertensives.',
   'Prontuário (anestésicos locais com epinefrina — precauções cardiovasculares).',
   'Prontuário (local anaesthetics with epinephrine — cardiovascular precautions).', 2)
) AS v(drug_slug, condition_slug, condition_pt, condition_en,
       interaction_type, severity, reason_pt, reason_en,
       advice_pt, advice_en, source_pt, source_en, sort_order)
ON d.slug = v.drug_slug
ON CONFLICT (drug_id, condition_slug) DO NOTHING;

-- =====================================================================
-- Exclusões com justificação (regra 13.1 do Fluxo 2):
--   * protamina já tem cobertura na 275 (IC descompensada) — não duplicar.
--   * clomifeno/carbimazol/propiltiouracilo/testosterona/ciproterona/
--     acido-tranexamico/sulfato-magnesio/cloreto-potassio/deferoxamina/
--     n-acetilcisteina/flucloxacilina/espectinomicina/permanganato-
--     potassio: Lote 3/4, já cobertos pela 275.
--   * noreisterona × gravidez: contraceptivo hormonal — a gravidez é a
--     ausência de indicação, não interação adversa.
--   * levonorgestrel-etinilestradiol × gravidez: idem.
--   * dopamina/dobutamina/noradrenalina × hipertensao: redundante com
--     feocromocitoma (a hipertensão está implícita) — registado só o
--     caso clínico mais grave.
--   * insulinas (Lote 4): já cobertas pela 275 (alcoolismo, doença
--     cardiovascular).
-- =====================================================================
