-- =====================================================================
-- 281 — Interações fármaco-alimento (Fluxo 2) para fármacos antigos
--       sem cobertura (complemento da secção 18.6)
-- ---------------------------------------------------------------------
-- A cobertura 226/226 da 18.6 foi verificada por fármaco; a auditoria
-- pós-LNME (secção 19) revelou 46 fármacos antigos pré-LNME que ficaram
-- de fora. Os exemplos solicitados (lítio × cafeína, levodopa ×
-- proteínas, sinvastatina × toranja) JÁ EXISTEM na BD — verificados
-- antes de escrever. Esta migração cobre os 46 restantes:
--   * 26 pares clínicos documentados (antidepressivos/ansiolíticos/
--     antipsicóticos/antiepilépticos × álcool, IECA/ARA × potássio
--     alimentar, acarbose × primeira mordida, cefpodoxima × comida,
--     rosuvastatina × álcool);
--   * 19 entradas sem_interacao_alimentar ('none') — betabloqueadores,
--     SGLT2i, gliptinas, GLP-1 SC, inalados, roflumilast, telitromicina;
--   * naloxona excluída por via (IM/IN/IV).
--
-- Idempotência: ON CONFLICT (drug_id, entity_slug) DO NOTHING.
-- =====================================================================

INSERT INTO public.drug_food_interactions
  (drug_id, entity_slug, entity_pt, entity_en,
   severity, mechanism_pt, mechanism_en,
   advice_pt, advice_en, source_pt, source_en, sort_order, status)
SELECT d.id, v.entity_slug, v.entity_pt, v.entity_en,
       v.severity, v.mechanism_pt, v.mechanism_en,
       v.advice_pt, v.advice_en, v.source_pt, v.source_en,
       v.sort_order, 'published'
FROM public.drugs d
JOIN (VALUES
  -- ---------- BENZODIAPINAS / HIPNÓTICOS × ÁLCOOL ----------
  ('lorazepam', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma depressão do SNC à lorazepam — sedação excessiva, depressão respiratória e prejuízo motor; Prontuário 10.1 (l. 30138): os hipnóticos e ansiolíticos potencial os efeitos sedativos.',
   'Alcohol adds CNS depression to lorazepam — excessive sedation, respiratory depression and motor impairment; Prontuário 10.1 (l. 30138): hypnotics and anxiolytics potentiate sedative effects.',
   'Evite completamente o álcool durante o tratamento.',
   'Avoid alcohol completely during treatment.',
   'Prontuário Terapêutico INFARMED, 10.1 (l. 30138); EMC-UK lorazepam SmPC 4.5.',
   'Prontuário Terapêutico INFARMED, 10.1 (l. 30138); EMC-UK lorazepam SmPC 4.5.', 1),
  ('clonazepam', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma depressão do SNC e pode reduzir o controlo das crises; a associação é desaconselhada.',
   'Alcohol adds CNS depression and may impair seizure control; the combination is discouraged.',
   'Evite o álcool durante o tratamento.',
   'Avoid alcohol during treatment.',
   'EMC-UK — Clonazepam SmPC 4.5 (alcohol); Prontuário 10.1 (l. 30138).',
   'EMC-UK — Clonazepam SmPC 4.5 (alcohol); Prontuário 10.1 (l. 30138).', 1),
  ('diazepam', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma depressão do SNC e depressão respiratória ao diazepam — combinação clássica de risco.',
   'Alcohol adds CNS and respiratory depression to diazepam — a classic risk combination.',
   'Evite completamente o álcool; nunca associe em idosos.',
   'Avoid alcohol completely; never combine in the elderly.',
   'EMC-UK — Diazepam SmPC 4.5 (alcohol, contraindicated in some labels); Prontuário 10.1.',
   'EMC-UK — Diazepam SmPC 4.5 (alcohol); Prontuário 10.1.', 1),
  ('zolpidem', 'alcool', 'Álcool', 'Alcohol', 'critical',
   'O álcool com zolpidem reduz drasticamente o limiar de despertar — comportamentos complexos durante o sono (conduzir, comer sem memória) e depressão respiratória; os rótulos proíbem a combinação.',
   'Alcohol with zolpidem drastically lowers arousal threshold — complex sleep behaviours (sleep-driving, eating without memory) and respiratory depression; labels prohibit the combination.',
   'NUNCA tome zolpidem com álcool; se bebeu, não tome a dose dessa noite.',
   'NEVER take zolpidem with alcohol; if you drank, skip that night''s dose.',
   'DailyMed — Ambien (zolpidem) § 2/4/5 (complex sleep behaviours, alcohol contraindicated); EMC-UK zolpidem SmPC 4.4.',
   'DailyMed — Ambien (zolpidem) § 2/4/5 (complex sleep behaviours, alcohol contraindicated); EMC-UK zolpidem SmPC 4.4.', 1),
  -- ---------- ANTIDEPRESSIVOS × ÁLCOOL ----------
  ('paroxetina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool potencial a sedação e pode agravar os efeitos cognitivos; a paroxetina (ISRS) soma depressão do SNC.',
   'Alcohol potentiates sedation and may worsen cognitive effects; paroxetine (SSRI) adds CNS depression.',
   'Evite ou modere fortemente o álcool, sobretudo no início do tratamento.',
   'Avoid or strongly moderate alcohol, especially at treatment start.',
   'EMC-UK — Paroxetine SmPC 4.5/4.7 (alcohol); ficha do site.',
   'EMC-UK — Paroxetine SmPC 4.5/4.7 (alcohol); site monograph.', 1),
  ('escitalopram', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool pode potencial os efeitos psicomotores e cognitivos do escitalopram.',
   'Alcohol may potentiate escitalopram psychomotor and cognitive effects.',
   'Modere o álcool; avalie a resposta individual nos primeiros dias.',
   'Moderate alcohol; assess individual response in the first days.',
   'EMC-UK — Escitalopram SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Escitalopram SmPC 4.5/4.7 (alcohol).', 1),
  ('citalopram', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool potencial a sedação; com QT prolongado, o consumo pesado soma risco cardíaco.',
   'Alcohol potentiates sedation; with QT prolongation, heavy drinking adds cardiac risk.',
   'Modere o álcool; atenção extra se tiver fatores de risco de QT.',
   'Moderate alcohol; extra caution with QT risk factors.',
   'EMC-UK — Citalopram SmPC 4.5/4.7 (alcohol, QT).',
   'EMC-UK — Citalopram SmPC 4.5/4.7 (alcohol, QT).', 1),
  ('amitriptilina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação e depressão respiratória aos tricíclicos e pode agravar arritmias; Prontuário 10.1 (l. 30138) inclui os analgésicos e narcóticos entre os potencializadores.',
   'Alcohol adds sedation and respiratory depression to tricyclics and may worsen arrhythmias; Prontuário 10.1 (l. 30138) lists analgesics and narcotics among potentiators.',
   'Evite o álcool; o efeito soma-se à sedação diurna da amitriptilina.',
   'Avoid alcohol; it adds to amitriptyline''s daytime sedation.',
   'Prontuário Terapêutico INFARMED, 10.1 (l. 30138); ficha do site (proteção solar, evitar álcool).',
   'Prontuário Terapêutico INFARMED, 10.1 (l. 30138); site monograph.', 1),
  ('venlafaxina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool potencial a sedação e a hipotensão; em consumo pesado soma risco hepático e de TA elevada.',
   'Alcohol potentiates sedation and hypotension; heavy use adds hepatic and blood-pressure risk.',
   'Modere fortemente o álcool durante o tratamento.',
   'Strongly moderate alcohol during treatment.',
   'EMC-UK — Venlafaxine SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Venlafaxine SmPC 4.5/4.7 (alcohol).', 1),
  ('duloxetina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma hepatotoxicidade à duloxetina (transaminases elevadas descritas) e potencial a sedação; consumo pesado é desaconselhado no rótulo.',
   'Alcohol adds hepatotoxicity to duloxetine (raised transaminases reported) and potentiates sedation; heavy use is discouraged in the label.',
   'Evite o álcool, sobretudo se tiver doença hepática ou consumir regularmente.',
   'Avoid alcohol, especially with liver disease or regular use.',
   'EMC-UK — Duloxetine SmPC 4.4 (hepatic injury, alcohol); DailyMed Cymbalta.',
   'EMC-UK — Duloxetine SmPC 4.4 (hepatic injury, alcohol); DailyMed Cymbalta.', 1),
  ('mirtazapina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma fortemente a sedação da mirtazapina — risco de sonolência excessiva e quedas, sobretudo em idosos.',
   'Alcohol strongly adds to mirtazapine sedation — excessive drowsiness and falls risk, especially in the elderly.',
   'Evite o álcool ao deitar e nas primeiras semanas.',
   'Avoid alcohol at bedtime and in the first weeks.',
   'EMC-UK — Mirtazapine SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Mirtazapine SmPC 4.5/4.7 (alcohol).', 1),
  -- ---------- ANTIPSICÓTICOS × ÁLCOOL ----------
  ('risperidona', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação, hipotensão ortostática e prejuízo cognitivo à risperidona.',
   'Alcohol adds sedation, orthostatic hypotension and cognitive impairment to risperidone.',
   'Evite o álcool, sobretudo ao iniciar ou aumentar dose.',
   'Avoid alcohol, especially when starting or increasing dose.',
   'EMC-UK — Risperidone SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Risperidone SmPC 4.5/4.7 (alcohol).', 1),
  ('olanzapina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação e hipotensão ortostática; soma ainda risco metabólico (ganho ponderal, glicemia).',
   'Alcohol adds sedation and orthostatic hypotension; it also adds metabolic risk (weight gain, glucose).',
   'Evite o álcool; vigilância de peso e glicemia.',
   'Avoid alcohol; monitor weight and glucose.',
   'EMC-UK — Olanzapine SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Olanzapine SmPC 4.5/4.7 (alcohol).', 1),
  ('quetiapina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação intensa e hipotensão ortostática da quetiapina — risco de quedas e acidentes.',
   'Alcohol adds intense sedation and orthostatic hypotension of quetiapine — falls and accidents risk.',
   'Evite o álcool, sobretudo nas subidas de dose.',
   'Avoid alcohol, especially during dose titration.',
   'EMC-UK — Quetiapine SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Quetiapine SmPC 4.5/4.7 (alcohol).', 1),
  ('aripiprazol', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação e prejuízo do juízo à aripiprazol.',
   'Alcohol adds sedation and impaired judgement to aripiprazole.',
   'Modere ou evite o álcool.',
   'Moderate or avoid alcohol.',
   'EMC-UK — Aripiprazole SmPC 4.5/4.7 (alcohol).',
   'EMC-UK — Aripiprazole SmPC 4.5/4.7 (alcohol).', 1),
  -- ---------- ANTIEPILÉPTICOS × ÁLCOOL ----------
  ('levetiracetam', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação e pode baixar o limiar convulsivo na retirada — risco de crises em epilépticos que bebam.',
   'Alcohol adds sedation and may lower the seizure threshold on withdrawal — seizure risk in drinking epileptics.',
   'Evite o álcool; o consumo pontual deve ser discutido com o neurologista.',
   'Avoid alcohol; occasional use should be discussed with the neurologist.',
   'EMC-UK — Levetiracetam SmPC 4.7 (alcohol).',
   'EMC-UK — Levetiracetam SmPC 4.7 (alcohol).', 1),
  ('lacosamida', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma tonturas, ataxia e pode prolongar o PR — a associação potencial os efeitos no SNC e na condução cardíaca.',
   'Alcohol adds dizziness and ataxia and may prolong PR — the combination potentiates CNS and cardiac conduction effects.',
   'Evite o álcool, sobretudo na titulação.',
   'Avoid alcohol, especially during titration.',
   'EMC-UK — Lacosamide SmPC 4.4/4.5 (PR interval, alcohol).',
   'EMC-UK — Lacosamide SmPC 4.4/4.5 (PR interval, alcohol).', 1),
  ('zonisamida', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O álcool soma sedação e o risco de acidose/desidratação (zonisamida é inibidora da anidrase carbónica) — risco de litíase com desidratação.',
   'Alcohol adds sedation and acidosis/dehydration risk (zonisamide inhibits carbonic anhydrase) — stone risk with dehydration.',
   'Modere o álcool; hidrate bem.',
   'Moderate alcohol; hydrate well.',
   'EMC-UK — Zonisamide SmPC 4.4/4.5 (CNS, dehydration).',
   'EMC-UK — Zonisamide SmPC 4.4/4.5 (CNS, dehydration).', 1),
  ('etossuximida', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação/GI e pode desestabilizar o controlo das ausências.',
   'Alcohol adds sedation/GI effects and may destabilise absence seizure control.',
   'Evite o álcool em idades escolares/adolescência.',
   'Avoid alcohol in school-age/adolescence.',
   'EMC-UK — Ethosuximide SmPC/PIL 4.5/4.7 (alcohol).',
   'EMC-UK — Ethosuximide SmPC/PIL 4.5/4.7 (alcohol).', 1),
  ('primidona', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma sedação intensa (a primidona é barbiturato-like) e potencial a depressão do SNC.',
   'Alcohol adds intense sedation (primidone is barbiturate-like) and potentiates CNS depression.',
   'Evite completamente o álcool.',
   'Avoid alcohol completely.',
   'EMC-UK — Primidone SmPC 4.5 (alcohol); Prontuário 10.1 (l. 30138 — barbitúricos).',
   'EMC-UK — Primidone SmPC 4.5 (alcohol); Prontuário 10.1 (l. 30138 — barbiturates).', 1),
  ('pregabalina', 'alcool', 'Álcool', 'Alcohol', 'moderate',
   'O álcool soma depressão do SNC e depressão respiratória à pregabalina — sonolência, tonturas e risco de quedas/blackouts.',
   'Alcohol adds CNS and respiratory depression to pregabalin — drowsiness, dizziness and falls/blackouts risk.',
   'Evite o álcool, sobretudo na titulação e em idosos.',
   'Avoid alcohol, especially during titration and in the elderly.',
   'EMC-UK — Pregabalin SmPC 4.4/4.7 (alcohol — CNS depression).',
   'EMC-UK — Pregabalin SmPC 4.4/4.7 (alcohol — CNS depression).', 1),
  -- ---------- CARDIOVASCULARES ----------
  ('losartana', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate',
   'A losartana (ARA II) reduz a excreção de potássio — a soma com alimentos muito ricos em potássio (substitutos de sal, bananas, sumos) eleva o risco de hipercaliemia.',
   'Losartan (ARB) reduces potassium excretion — adding potassium-rich foods (salt substitutes, bananas, juices) raises hyperkalaemia risk.',
   'Não use substitutos de sal; modere frutos/sumos ricos em potássio; mantenha as análises em dia.',
   'Do not use salt substitutes; moderate potassium-rich fruits/juices; keep blood tests up to date.',
   'Ficha do site (losartana — risco de hipercalemia com poupança de potássio); EMC-UK losartan SmPC 4.4.',
   'Site monograph (losartan — hyperkalaemia risk with potassium sparing); EMC-UK losartan SmPC 4.4.', 1),
  ('lisinopril', 'potassio_alimentar', 'Potássio alimentar elevado', 'High dietary potassium', 'moderate',
   'O lisinopril (IECA) reduz a excreção de potássio — a soma com alimentos muito ricos em potássio eleva o risco de hipercaliemia (arritmias).',
   'Lisinopril (ACEi) reduces potassium excretion — adding potassium-rich foods raises hyperkalaemia risk (arrhythmias).',
   'Não use substitutos de sal; modere potássio alimentar; análises de potássio e creatinina regulares.',
   'Do not use salt substitutes; moderate dietary potassium; regular potassium and creatinine tests.',
   'Ficha do site (enalapril/IECA — vigiar potássio); EMC-UK lisinopril SmPC 4.4.',
   'Site monograph (enalapril/ACEi — monitor potassium); EMC-UK lisinopril SmPC 4.4.', 1),
  ('rosuvastatina', 'alcool', 'Álcool', 'Alcohol', 'minor',
   'O consumo pesado de álcool soma hepatotoxicidade à rosuvastatina (transaminases) — o rótulo desaconselha consumo excessivo em doentes sob estatina.',
   'Heavy alcohol use adds hepatotoxicity to rosuvastatin (transaminases) — labels discourage excessive intake in statin patients.',
   'Modere o álcool; transaminases conforme orientação.',
   'Moderate alcohol; transaminases as advised.',
   'EMC-UK — Rosuvastatin (Crestor) SmPC 4.4 (hepatic, alcohol).',
   'EMC-UK — Rosuvastatin (Crestor) SmPC 4.4 (hepatic, alcohol).', 1),
  -- ---------- TOLERÂNCIA/ABSORÇÃO ----------
  ('acarbose', 'toma_com_alimentos', 'Tomar com alimentos', 'Take with food', 'moderate',
   'A acarbose deve ser mastigada com a PRIMEIRA MORDIDA da refeição — actua inibindo as alfa-glucosidases intestinais sobre o alimento ingerido; fora do timing perde eficácia e soma flatulência.',
   'Acarbose must be chewed with the FIRST BITE of the meal — it inhibits intestinal alpha-glucosidases on the ingested food; outside this timing it loses efficacy and adds flatulence.',
   'Mastigue com a primeira mordida de cada refeição principal (ficha do site).',
   'Chew with the first bite of each main meal (site monograph).',
   'Ficha do site (acarbose — tomar com a primeira mordida da refeição); EMC-UK acarbose SmPC 4.2.',
   'Site monograph (acarbose — take with first bite of meal); EMC-UK acarbose SmPC 4.2.', 1),
  ('cefpodoxima', 'toma_com_alimentos', 'Tomar com alimentos', 'Take with food', 'minor',
   'A absorção do cefpodoxima proxetil melhora com alimentos — tomar durante as refeições aumenta a biodisponibilidade.',
   'Cefpodoxime proxetil absorption improves with food — taking it during meals increases bioavailability.',
   'Tome durante as refeições.',
   'Take during meals.',
   'EMC-UK — Cefpodoxime SmPC 4.2/4.5 (absorption enhanced by food).',
   'EMC-UK — Cefpodoxime SmPC 4.2/4.5 (absorption enhanced by food).', 1),
  -- ---------- SEM INTERAÇÃO ALIMENTAR RELEVANTE ----------
  ('metoprolol', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'Os alimentos reduzem ligeiramente a biodisponibilidade do metoprolol sem consequência clínica relevante nos esquemas habituais.',
   'Food slightly reduces metoprolol bioavailability without clinically relevant consequence on usual schedules.',
   'Pode tomar com ou sem alimentos, à mesma hora.',
   'Take with or without food, at the same time.',
   'EMC-UK — Metoprolol SmPC 4.2 (with or without food).',
   'EMC-UK — Metoprolol SmPC 4.2 (with or without food).', 1),
  ('atenolol', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A alimentação não interfere clinicamente com o atenolol (biodisponibilidade ~50% independente).',
   'Food does not clinically interfere with atenolol (~50% bioavailability, food-independent).',
   'Pode tomar com ou sem alimentos.',
   'Take with or without food.',
   'EMC-UK — Atenolol SmPC 4.2.',
   'EMC-UK — Atenolol SmPC 4.2.', 1),
  ('bisoprolol', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A alimentação não interfere clinicamente com o bisoprolol.',
   'Food does not clinically interfere with bisoprolol.',
   'Pode tomar com ou sem alimentos, de manhã.',
   'Take with or without food, in the morning.',
   'EMC-UK — Bisoprolol SmPC 4.2 (with or without food).',
   'EMC-UK — Bisoprolol SmPC 4.2 (with or without food).', 1),
  ('propranolol', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'Os alimentos aumentam a biodisponibilidade do propranolol (~70%), mas sem exigir ajuste se a toma for consistente — o que importa é a rotina.',
   'Food increases propranolol bioavailability (~70%), but no adjustment is needed if intake is consistent — routine is what matters.',
   'Tome sempre da mesma forma (com ou sem alimentos) para manter o efeito estável.',
   'Always take it the same way (with or without food) to keep the effect stable.',
   'Prontuário 7.3 (propranolol — biodisponibilidade ↑ com alimentos); DailyMed Inderal.',
   'Prontuário 7.3 (propranolol — bioavailability ↑ with food); DailyMed Inderal.', 1),
  ('empagliflozina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A empagliflozina pode ser tomada com ou sem alimentos.',
   'Empagliflozin can be taken with or without food.',
   'Pode tomar com ou sem alimentos, de manhã.',
   'Take with or without food, in the morning.',
   'EMC-UK — Jardiance (empagliflozin) SmPC 4.2.',
   'EMC-UK — Jardiance (empagliflozin) SmPC 4.2.', 1),
  ('dapagliflozina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A dapagliflozina pode ser tomada com ou sem alimentos.',
   'Dapagliflozin can be taken with or without food.',
   'Pode tomar com ou sem alimentos, de manhã.',
   'Take with or without food, in the morning.',
   'EMC-UK — Forxiga (dapagliflozin) SmPC 4.2.',
   'EMC-UK — Forxiga (dapagliflozin) SmPC 4.2.', 1),
  ('canagliflozina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A canagliflozina pode ser tomada com ou sem alimentos.',
   'Canagliflozin can be taken with or without food.',
   'Pode tomar com ou sem alimentos, antes da primeira refeição.',
   'Take with or without food, before the first meal.',
   'EMC-UK — Invokana (canagliflozin) SmPC 4.2.',
   'EMC-UK — Invokana (canagliflozin) SmPC 4.2.', 1),
  ('sitagliptina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A sitagliptina pode ser tomada com ou sem alimentos.',
   'Sitagliptin can be taken with or without food.',
   'Pode tomar com ou sem alimentos, à mesma hora.',
   'Take with or without food, at the same time.',
   'EMC-UK — Januvia (sitagliptin) SmPC 4.2.',
   'EMC-UK — Januvia (sitagliptin) SmPC 4.2.', 1),
  ('saxagliptina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A saxagliptina pode ser tomada com ou sem alimentos.',
   'Saxagliptin can be taken with or without food.',
   'Pode tomar com ou sem alimentos.',
   'Take with or without food.',
   'EMC-UK — Onglyza (saxagliptin) SmPC 4.2.',
   'EMC-UK — Onglyza (saxagliptin) SmPC 4.2.', 1),
  ('vildagliptina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A vildagliptina pode ser tomada com ou sem alimentos.',
   'Vildagliptin can be taken with or without food.',
   'Pode tomar com ou sem alimentos.',
   'Take with or without food.',
   'EMC-UK — Galvus (vildagliptin) SmPC 4.2.',
   'EMC-UK — Galvus (vildagliptin) SmPC 4.2.', 1),
  ('liraglutida', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A liraglutida é injetável SC uma vez/dia, independentemente das refeições; pode causar náuseas transitórias que não dependem de alimento.',
   'Liraglutide is a once-daily SC injection, independent of meals; transient nausea does not depend on food.',
   'Injete à mesma hora, com ou sem refeição.',
   'Inject at the same time, with or without a meal.',
   'EMC-UK — Victoza (liraglutide) SmPC 4.2.',
   'EMC-UK — Victoza (liraglutide) SmPC 4.2.', 1),
  ('dulaglutida', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'A dulaglutida é injetável SC semanal, independente das refeições.',
   'Dulaglutide is a weekly SC injection, independent of meals.',
   'Injete no mesmo dia da semana, com ou sem refeição.',
   'Inject on the same weekday, with or without a meal.',
   'EMC-UK — Trulicity (dulaglutide) SmPC 4.2.',
   'EMC-UK — Trulicity (dulaglutide) SmPC 4.2.', 1),
  ('beclometasona', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'Uso inalado — sem interação alimentar aplicável; enxaguar a boca após a toma para prevenir candidíase.',
   'Inhaled use — no food interaction applicable; rinse the mouth after dosing to prevent candidiasis.',
   'Enxague a boca após cada inalação.',
   'Rinse your mouth after each inhalation.',
   'EMC-UK — Beclometasone inhaler PIL (mouth rinsing).',
   'EMC-UK — Beclometasone inhaler PIL (mouth rinsing).', 1),
  ('fluticasona', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'Uso inalado — sem interação alimentar aplicável; enxaguar a boca após a toma.',
   'Inhaled use — no food interaction applicable; rinse the mouth after dosing.',
   'Enxague a boca após cada inalação.',
   'Rinse your mouth after each inhalation.',
   'EMC-UK — Fluticasone inhaler PIL (mouth rinsing).',
   'EMC-UK — Fluticasone inhaler PIL (mouth rinsing).', 1),
  ('roflumilast', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'Pode ser tomado com ou sem alimentos; a toma com refeição reduz náuseas.',
   'Can be taken with or without food; taking with a meal reduces nausea.',
   'Tome com alimentos se sentir náuseas.',
   'Take with food if you feel nauseous.',
   'EMC-UK — Daxas (roflumilast) SmPC 4.2/PIL.',
   'EMC-UK — Daxas (roflumilast) SmPC 4.2/PIL.', 1),
  ('telitromicina', 'sem_interacao_alimentar', 'Sem interação alimentar relevante', 'No clinically relevant food interaction', 'none',
   'Pode ser tomada com ou sem alimentos; refeições gordurosas aumentam ligeiramente a absorção sem exigir ajuste.',
   'Can be taken with or without food; fatty meals slightly increase absorption without dose adjustment.',
   'Pode tomar com ou sem alimentos.',
   'Take with or without food.',
   'EMC-UK — Telithromycin (Ketek) SmPC 4.2.',
   'EMC-UK — Telithromycin (Ketek) SmPC 4.2.', 1)
) AS v(drug_slug, entity_slug, entity_pt, entity_en,
       severity, mechanism_pt, mechanism_en,
       advice_pt, advice_en, source_pt, source_en, sort_order)
ON d.slug = v.drug_slug
ON CONFLICT (drug_id, entity_slug) DO NOTHING;

-- =====================================================================
-- Exclusões:
--   * naloxona: via IM/IN/IV em emergência — sem interação alimentar
--     aplicável.
--   * lítio × cafeína, levodopa × proteínas, sinvastatina × toranja:
--     já existem na BD (verificado antes de escrever — secção 18.6).
--   * metoprolol/atenolol/bisoprolol/propranolol, SGLT2i, gliptinas,
--     GLP-1 SC, inalados, roflumilast, telitromicina: registados como
--     sem_interacao_alimentar ('none') em vez de excluídos, para fechar
--     a cobertura fármaco a fármaco.
-- =====================================================================
